### ISSUE TITLE
Please upload crates to crates.io

### ISSUE THREAD

**Issue by joshtriplett** [Azure/iotedge#1]
Please consider uploading all the crates here to Rust's crates.io repository, so that people can easily pull in these crates as dependencies.

Thanks for releasing these!

**Comment by myagley** [comment]
Hi Josh,

Thanks for the suggestion. We will certainly consider uploading the useful crates to crates.io. Many of the crates are pretty application specific, but we do have a few that could be generally useful for the community.

Thanks,
Mike

**Comment by lt72** [comment]
Thank you for your input we recorded your suggestion and will take it in consideration in our planning. Closing this issue for now, as ask is tracked elsewhere.
