### ISSUE TITLE
[Feature request] Provide ways to monitor messages between modules 

### ISSUE THREAD

**Issue by formulahendry** [Azure/iotedge#1004]
One customer asks whether there is a easier way to monitor messages between modules as well as from the edge device to the cloud.

**Comment by 4nandP** [comment]
The workaround we used was just routing the messages to the cloud as well for monitoring and then using the [tooling](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-edge) to see device to cloud messages. Works out fine for development debugging, but will chew through your message quota so not for production.

**Comment by veyalla** [comment]
Supporting [IoT Hub Distributed Tracing](https://azure.microsoft.com/en-us/blog/preview-distributed-tracing-support-for-iot-hub/) is on our roadmap which should help with this.

**Comment by veyalla** [comment]
Please file or vote for additional feature enhancements at https://feedback.azure.com/forums/907045-azure-iot-edge
