### ISSUE TITLE
Does Windows Host Windows Container support DPS TMP based authentication

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#1013]
Does Windows Host Windows Container support DPS TMP based authentication??
Our Requirement is as given below
1. Provision Device with DPS
2. Use TPM base authentication from Edge Module 
3. Use Windows host with windows container.

So please let me know does it support or not.. If yes then send me the reference link please

**Comment by veyalla** [comment]
Please see: 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-simulated-device-windows

**Comment by myagley** [comment]
Version `1.0.7.1` supports physical TPMs by default now. Please feel free to reopen if you are still facing issues.
