### ISSUE TITLE
iotedge missing functionality that iotedgectl (v1) had

### ISSUE THREAD

**Issue by treedust** [Azure/iotedge#102]
iotedge would appear to be lacking documentation and/or functionality that iotedgectl (iotedge v1) had. 

I have noticed that iotedge does not have a way to give container registry credentials nor does Azure IoT Edge documentation explains how to provide iotedge such credentials.

**Comment by veyalla** [comment]
@kgremban Do we have documentation around container registry credentials?

**Comment by treedust** [comment]
@veyalla Yes there use to be docs when it was iotedgectl 

https://pypi.org/project/azure-iot-edge-runtime-ctl/ -> https://github.com/Azure/iot-edge-v1 


> login: This command accepts a registry server, username and credentials as input and configures the IoT Edge with this data. Running login will update the IoT Edge configuration file with the registry information. This is useful for users who host their module images on private registries. Note: in the event the Edge runtime is active and running, the Edge Agent will be stopped and the existing instance will be removed and restarted with the new credentials.

**Comment by treedust** [comment]
Yes that works well. Does that mean iotedgectl functionality will no longer be the same as iotedge?

**Comment by veyalla** [comment]
Yes, iotedgectl was for preview bits and is deprecated. 

With GA, you should use iotedge tool.

**Comment by kgremban** [comment]
@treedust @veyalla The registry credentials are now stored in the deployment manifest, not manually entered into the device. You can see an example of the format at: https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#deployment-manifest-example 

Additionally, if you're using the VS Code solution templates, they auto-generate a .env file that is git ignored, where you can enter your registry credentials and they'll be referenced from the deployment manifest template.

**Comment by treedust** [comment]
> Yes, iotedgectl was for preview bits and is deprecated.
> With GA, you should use iotedge tool.

Okay than you. The docs are still a bit off from using the Azure Portal to using DPS on a pi set up for v2. 

@veyalla @kgremban

**Comment by treedust** [comment]
> Yes, iotedgectl was for preview bits and is deprecated.
> With GA, you should use iotedge tool.

Okay thank you

@veyalla @kgremban
