### ISSUE TITLE
How mapping usb port on host  to container ?

### ISSUE THREAD

**Issue by v-jiq** [Azure/iotedge#1025]
I want to  mapping usb port on host to container.  if directly runs container not by  iotedge , I can do that by using this option "--device=/dev/ttyUSB0" .  if runs container by iotedge , I don't know what I should fill to the createoption  of container. 

I'm not going to be able to complete the mapping if  I try filled that  like below picture:
![1553761168(1)](https://user-images.githubusercontent.com/39880470/55141418-5d4f1c80-5175-11e9-881f-ccc961f3193c.png)

I want to consult what I should fill to containers option to complete mapping。

**Comment by veyalla** [comment]
[Here](https://www.hackster.io/waltercoan/azure-iot-edge-reading-data-from-plc-industrial-iot-ef8214#toc-steps-to-build-1) is an example:

```
{
 "HostConfig": {
   "User": "root",
   "Privileged": true,
   "Devices": [
     {
       "PathOnHost": "/dev/ttyACM0",
       "PathInContainer": "/dev/ttyACM0",
       "CgroupPermissions": "mrw"
     }
   ]
 }
}
```
