### ISSUE TITLE
HSM API returned an invalid null response  when setup edge runtime using TPM and also having edge runtime version 1.0.6.1 an dwindow version 1809

### ISSUE THREAD

**Issue by piyushsharma2512** [Azure/iotedge#1034]
HSM API returned an invalid null response  when setup edge runtime using TPM and also having edge runtime version 1.0.6.1 an dwindow version 1809. Any one having Idea to update. 

PS C:\Users\matlab> Stop-Service iotedge -NoWait
>> $Env:IOTEDGE_RUN_AS_CONSOLE = "ON"
>> $Env:IOTEDGE_USE_TPM_DEVICE = "ON"
>> $Env:IOTEDGE_LOG = "debug"
>>
>> C:\ProgramData\iotedge\iotedged.exe -c C:\ProgramData\iotedge\config.yaml
<6>2019-04-02T11:34:32Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2019-04-02T11:34:32Z [INFO] - Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor::background] starting background reactor
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor::background] starting background reactor
<6>2019-04-02T11:34:32Z [INFO] - Using runtime network id nat
<6>2019-04-02T11:34:32Z [INFO] - Initializing the module runtime...
<6>2019-04-02T11:34:32Z [INFO] - Initializing module runtime...
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 1 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 1 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [hyper::proto::h1::io] flushed 167 bytes
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 0 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 1 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 1 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [hyper::proto::h1::io] read 759 bytes
<7>2019-04-02T11:34:32Z [DBUG] - [hyper::proto::h1::io] parsed 7 headers
<7>2019-04-02T11:34:32Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (554 bytes)
<7>2019-04-02T11:34:32Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
<7>2019-04-02T11:34:32Z [DBUG] - [hyper::client::pool] pooling idle connection for "npipe://5c5c2e5c706970655c696f74656467655f6d6f62795f656e67696e65"
<6>2019-04-02T11:34:32Z [INFO] - Successfully initialized module runtime
<6>2019-04-02T11:34:32Z [INFO] - Finished initializing the module runtime.
<6>2019-04-02T11:34:32Z [INFO] - Configuring C:\ProgramData\iotedge as the home directory.
<6>2019-04-02T11:34:32Z [INFO] - Configuring certificates...
<6>2019-04-02T11:34:32Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2019-04-02T11:34:32Z [INFO] - Finished configuring certificates.
<6>2019-04-02T11:34:32Z [INFO] - Initializing hsm...
<6>2019-04-02T11:34:32Z [INFO] - Finished initializing hsm.
<6>2019-04-02T11:34:32Z [INFO] - Detecting if configuration file has changed...
<7>2019-04-02T11:34:32Z [DBUG] - [iotedged::settings] Config state matches supplied config.
<6>2019-04-02T11:34:32Z [INFO] - No change to configuration file detected.
<6>2019-04-02T11:34:32Z [INFO] - Obtaining workload CA succeeded.
<6>2019-04-02T11:34:32Z [INFO] - Provisioning edge device...
Error: Time:Tue Apr  2 11:34:32 2019 File:D:\a\1\s\edgelet\hsm-sys\azure-iot-hsm-c\deps\utpm\src\tpm_comm_win32.c Func:tpm_comm_create Line:99 Failure: Tbsi_Context_Create A compatible Trusted Platform Module (TPM) Security Device cannot be found on this computer..
Error: Time:Tue Apr  2 11:34:32 2019 File:D:\a\1\s\edgelet\hsm-sys\azure-iot-hsm-c\deps\utpm\src\tpm_codec.c Func:Initialize_TPM_Codec Line:258 creating tpm_comm object
<3>2019-04-02T11:34:32Z [ERR!] (D:\a\1\s\edgelet\hsm-sys\azure-iot-hsm-c\src\hsm_client_tpm_device.c:initialize_tpm_device:272) Failure initializeing TPM Codec
<3>2019-04-02T11:34:32Z [ERR!] (D:\a\1\s\edgelet\hsm-sys\azure-iot-hsm-c\src\hsm_client_tpm_device.c:hsm_client_tpm_create:305) Failure initializing tpm device.
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 0 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 0 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] dropping I/O source: 0
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor] loop process - 1 events, 0.000s
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor::background] shutting background reactor down NOW
<7>2019-04-02T11:34:32Z [DBUG] - [tokio_reactor::background] background reactor has shutdown
<3>2019-04-02T11:34:32Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
<3>2019-04-02T11:34:32Z [ERR!] -        caused by: HSM API returned an invalid null response

**Comment by myagley** [comment]
This should be fixed in version `1.0.7.1`.
