### ISSUE TITLE
Created IoT Edge for arm64 - NVIDIA Tegra Jetson TX2 - package

### ISSUE THREAD

**Issue by krunallokhande** [Azure/iotedge#104]
I build an image for IoT Edge ARM64 architecture. Attached screenshot for the same.
DEVICE: Nvidia Tegra Jetson TX2
ARCHITECTURE: ARM64
OS: UBUNTU 16.04 - 64 bit

I need to make a package or installable to install this. It's running when executed but I am not able to install iot-edge on my Jetson device. Need help to install this as service, so I can check IoT EdgeAgent and EdgeHub if they can support arm64 architecture.

![iotedgearm64](https://user-images.githubusercontent.com/24507437/43504409-f6cbbc58-9580-11e8-96a1-7e6929307fb4.png)

## Steps to Reproduce

1. Install iot edge on arm64 architecture. 
2.
3.
4.

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
ARM64

### Container Operating System
Linux containers

**Comment by krunallokhande** [comment]
Hi,

Please find below screenshots for logs building IoT Edge for aarch64 or ARM64 architecture.
We used the make file to install the iot edge on Nvidia Tegra Jetson TX2. It executed successfully but the iotedge service is still not installed or configured properly. 

We checked the binaries which does support aarch64 architecture but libiothsm.so library is not found for the same. We are not sure if this is blocking the service or service needs to be installed separately. 

Also, guide us on installing the iot edge service as its saying

```
● iotedge.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)
```

Kindly help us identify if we are missing something on configuration or building process.

**1.  Config YAML - Connection String :** 
![config yaml-part1](https://user-images.githubusercontent.com/24507437/43521987-7f2fc718-95b5-11e8-8413-41ee0159cd43.png)


**2. Config YAML - Folder/Path:** 
![config yaml-part2](https://user-images.githubusercontent.com/24507437/43521991-840b8100-95b5-11e8-93b4-4d1772761e71.png)

**3. Journal Logs:** 
![journal logs](https://user-images.githubusercontent.com/24507437/43521996-879775b8-95b5-11e8-9839-edcf3aee344a.png)


**4. Library Dependency - libiothsm.so: We searched but no aarch64 support available.** 
![library deps](https://user-images.githubusercontent.com/24507437/43522003-8c6a72b6-95b5-11e8-9024-c53f83ddbeb7.png)


**5. Other Libs:** 
![libs-in-fs](https://user-images.githubusercontent.com/24507437/43522017-92574938-95b5-11e8-9eb3-594e5e5998f6.png)


**6. Service Logs:** 
![service log](https://user-images.githubusercontent.com/24507437/43522026-9b11d156-95b5-11e8-8833-68ecf9923eb9.png)

**Comment by myagley** [comment]
Hi Krunal, we don't currently support arm64 devices. Here is the list of the supported platforms: https://docs.microsoft.com/en-us/azure/iot-edge/support

It may be possible to get this working, but you will need to build both the `iotedged` and `libiothsm` for arm64. You will need to get the arm64 toolchain for Rust (iotedged) and build the `libiothsm` separately. The source for `libiothsm` is here: https://github.com/Azure/iotedge/tree/master/edgelet/hsm-sys/azure-iot-hsm-c

To build packages, you can try `make deb` in the `edgelet` directory and `make package` for the `libiothsm`.

**Comment by krunallokhande** [comment]
Thanks @myagley .
 I will build both iotedged and libiothsm.so for arm64 and confirm if those are working.

**Comment by vjrantal** [comment]
FWIW, I was able to build on Jetson TX2 (aarch64) and able to test that a sample module worked on that platform. More details from https://github.com/vjrantal/iot-edge-darknet-module/issues/10.

**Comment by FluxReality** [comment]
[This](https://catalog.azureiotsolutions.com/details?title=Cloudian-AI-Box&source=all-devices-page) device is listed on this Microsoft affiliated site as "**Azure Certified for IoT device**", and contains an **ARM Cortex-A57@2 GHz + NVIDIA Denver2@2 GHz** CPU and GPU.

How can this be?

**Comment by myagley** [comment]
Hello. "Azure Certified for IoT device" means that the device is certified for Azure IoT in general. Practically speaking, this means it was certified for use with IoT Hub.

There is a separate certification process for IoT Edge. As of right now, IoT Edge does not officially support arm64 devices. However, it has been made to work. There are scripts that were recently checked in that will help build here: https://github.com/Azure/iotedge/tree/master/edgelet/build/linux/ubuntu16.04/aarch64

**Comment by LazarusX** [comment]
Did a quick examination, it look like the scripts rely on a private Docker image which requires credentials to access:

https://github.com/Azure/iotedge/blob/445c2ec2cfb2d851cb5f79f22352e23f0456daf5/edgelet/build/linux/ubuntu16.04/aarch64/package-iotedged.sh#L15

**Comment by myagley** [comment]
Hmm ok. We can get that pushed to a public registry. In the meantime, you should be able to build this image with the scripts and info here: https://github.com/Azure/iotedge/tree/master/edgelet/build/linux/docker/cross-compile

**Comment by oak-tree** [comment]
@myagley 
Hey, I followed the instruction at [https://blogs.msdn.microsoft.com/iotdev/2018/11/05/a-workaround-to-run-azure-iot-edge-on-arm64-devices/](https://blogs.msdn.microsoft.com/iotdev/2018/11/05/a-workaround-to-run-azure-iot-edge-on-arm64-devices/) in order to build the `cross-compile` on `jetson tx2` which runs on `arm64`. I succeed to built it but. When running 


>/azure/iotedge/edgelet/build/linux/ubuntu16.04/aarch64$ ./package-libiothsm.sh

I get the following error:

> CMake Error at /usr/local/share/cmake-3.11/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/toolchain/bin/aarch64-linux-gnu-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /target/hsm/build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_913bc/fast"
    /usr/bin/make -f CMakeFiles/cmTC_913bc.dir/build.make CMakeFiles/cmTC_913bc.dir/build
    make[1]: Entering directory '/target/hsm/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_913bc.dir/testCCompiler.c.o
    /toolchain/bin/aarch64-linux-gnu-gcc    -o CMakeFiles/cmTC_913bc.dir/testCCompiler.c.o   -c /target/hsm/build/CMakeFiles/CMakeTmp/testCCompiler.c
    /toolchain/bin/aarch64-linux-gnu-gcc: 1: /toolchain/bin/aarch64-linux-gnu-gcc: cannot open @@: No such file
    /toolchain/bin/aarch64-linux-gnu-gcc: 1: /toolchain/bin/aarch64-linux-gnu-gcc: ELF: not found
    /toolchain/bin/aarch64-linux-gnu-gcc: 3: /toolchain/bin/aarch64-linux-gnu-gcc: Syntax error: "(" unexpected
    CMakeFiles/cmTC_913bc.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_913bc.dir/testCCompiler.c.o' failed
    make[1]: *** [CMakeFiles/cmTC_913bc.dir/testCCompiler.c.o] Error 2
    make[1]: Leaving directory '/target/hsm/build/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_913bc/fast' failed
    make: *** [cmTC_913bc/fast] Error 2

>  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)

> -- Configuring incomplete, errors occurred!
See also "/target/hsm/build/CMakeFiles/CMakeOutput.log".
See also "/target/hsm/build/CMakeFiles/CMakeError.log".

**Comment by idavis** [comment]
@oak-tree You need to run the build from an amd64 machine. It will compile the arm64 binaries for you without needing to run on device.

Note: I had to run ./package-iotedged.sh and then ./package-libiotsm.sh  as litiotsm wouldn't compile first with the error:

```
CMake Error at tests/CMakeLists.txt:5 (usePermissiveRulesForSamplesAndTests):
  Unknown CMake command "usePermissiveRulesForSamplesAndTests".
```
Once I built iotedged then libiotsm compiled without issue.
