### ISSUE TITLE
Blob Storage on IoT Edge Device with windows VM and Linux Container

### ISSUE THREAD

**Issue by VikasJaiswal** [Azure/iotedge#1045]
Hi,
Will it work if I use Blob Storage on IoT Edge Device with below configuration:
Host VM: Windows 10
Docker Container: Linux

If yes, please provide the configuration for deployment.Json and the connection string which would be used to retrieve and store the data on Blob Container. I had tried but it doesn't work.

I want to use full feature like Auto-expiration and Auto-tiering, so I am using Linux containers as it is mentioned in the document that these features are not available for windows containers for now.

**Comment by myagley** [comment]
Thanks for the issue report. Unfortunately using Linux containers on a Windows host is not a supported scenario. It's possible that we could get this to work but we don't plan on supporting this configuration long term.

**Comment by VikasJaiswal** [comment]
Thanks for the response. Is there any plan to release windows supported version of the "Azure Blob Storage on IoT Edge" image with full functionalities i.e.  Auto-expiration and Auto-tiering.
