### ISSUE TITLE
Securely store registry credential

### ISSUE THREAD

**Issue by shizn** [Azure/iotedge#1055]
## Expected Behavior

Use service principal or token-based auth for ACR. Or put the credentials in KeyVault-like services.

## Current Behavior

Admin credential is plaintext and stored in deployment.json.

**Comment by myagley** [comment]
We do already support service principal based auth for ACR. This still requires the service principal auth in the deployment, but it is possible. This is discussed in this doc article: https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist#manage-access-to-your-container-registry

Is there something more that we should be considering?

**Comment by shizn** [comment]
Thanks. We probably need to put a link to service principal auth in the VS/VS Code development tutorial, my assumption is that people just don't know about the service principal support. Let me first update the tutorial, and then get back to customer and see if this can meet their requirements.

**Comment by StefanSchoof** [comment]
For me as user a solution, where the iothub creates an manged service identity and uses this identity to create some kind of short living sas token to pull from the container registry would be great. This would make this passwordless and simpler to setup. AFAIK there is currently nothing like sas for the acr, so this not something can done quickly.

**Comment by Vossekop** [comment]
I've also read the documentation regarding these credentials. I would normally think that each device would get it's own credentials (so we have the ability to lock out compromised/misbehaving devices). But that means creating potentially thousands of service principals. Which is a bit of a management nightmare in ACR as far as I can tell. I am not saying I would have a specific solution in mind for the problem, but I feel this is a scenario that should be improved.

Also, I might not have looked closely enough, but how is the configuration file containing the credentials protected on the device?

**Comment by veyalla** [comment]
Docs don’t call this out, as far as I know. But the deployment that is pulled down over TLS is encrypted at rest by the edge agent.
