### ISSUE TITLE
How to set Environment Variables while deploying ML Module

### ISSUE THREAD

**Issue by ilyas-it83** [Azure/iotedge#106]
Trying to fetch data from tempsensor-->filtermodule-->mlmodule and finally do Upstream.

## Expected Behavior
When creating MLModule as per the article and deploying as a custom module instead of ML module doesnt set Environment variables in the MLModule, however filtermodule has got all the necessary env variables  related to IotEdge and Hub

## Current Behavior
filtermodule has all the necessary IoTHub related environment variables but not ML Module

## Steps to Reproduce
Setup tempSensor, filtermodule, ML module as per the docs, modify the iot_score.py to fetch data from the filtermodule by following the instructions given in the filtermodule sample code and run.

You will see the MLModule doesnt contain IotHub related Env variables.

### Device (Host) Operating System
Distributor ID: Ubuntu
Release: 17.10
Codename: artful

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.0 (52ef77d)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
Client:
Version: 18.06.0-dev
API version: 1.37
Go version: go1.10.2
Git commit: daf021fe
Built: Mon Jun 25 21:07:53 2018
OS/Arch: linux/amd64
Experimental: false
Orchestrator: swarm

Server:
Engine:
Version: dev
API version: 1.37 (minimum version 1.12)
Go version: go1.10.2
Git commit: 9aac187
Built: Mon Jun 25 20:43:05 2018
OS/Arch: linux/amd64
Experimental: false

## Logs - Env Variables found in  filtermodule
HOSTNAME=e8b83c8848f2
TERM=xterm
IOTEDGE_GATEWAYHOSTNAME=xxxvm
IOTEDGE_IOTHUBHOSTNAME=xxxxxx.azure-devices.net
IOTEDGE_WORKLOADURI=http://172.17.0.1:15581/
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
IOTEDGE_AUTHSCHEME=sasToken
IOTEDGE_MODULEGENERATIONID=636686535936416809
RuntimeLogLevel=Information
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/app
IOTEDGE_MODULEID=filtermodulepy
IOTEDGE_DEVICEID=myEdgeDevice3
IOTEDGE_APIVERSION=2018-06-28
SHLVL=1
HOME=/home/docker
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/printenv

## Logs - Env Variables found in  MLModule
mlmodule -env var
-----------------

SPARK_HOME=/home/mmlspark/lib/spark
HOSTNAME=d559f81c590a
TERM=xterm
CONDA_VERSION=4.2.12
WORKER_TIMEOUT=300
AML_MODEL_DC_STORAGE_ENABLED=false
USER=mmlspark
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LD_LIBRARY_PATH=/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:
AML_APP_INSIGHTS_KEY=0d02c49f-1852-4918-833e-9b68a48c9453
PATH=/home/mmlspark/lib/conda/bin:/home/mmlspark/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SPARK_VERSION=2.1.1
AML_MODEL_DC_EVENT_HUB_ENABLED=false
PWD=/home/mmlspark
JAVA_HOME=/home/mmlspark/lib/jdk
MML_PACKAGE=com.microsoft.ml.spark:mmlspark_2.11:0.7.91
AML_BATCH_ENTRYPOINT=/var/azureml-app/main.sh
JAVA_VERSION=1.8.0
MML_BUILD_INFO=0.7.91: Azure/mmlspark/master@48d65f9e; MMLSpark#240865
SHLVL=1
HOME=/home/mmlspark
CONDA_HOME=/home/mmlspark/lib/conda
PYTHONPATH=:/home/mmlspark/lib/spark/python/lib/*.zip
MMLSPARK_PROFILE=yes
MMLSPARK_JUPYTER_PORT=8888
MML_VERSION=0.7.91
AML_APP_INSIGHTS_ENABLED=false
MML_M2REPOS=file:/home/mmlspark/mml-m2,https://mmlspark.azureedge.net/maven
_=/usr/bin/printenv

**Comment by varunpuranik** [comment]
Hi @ilyas-it83, Just to make sure, was the ML module deployed as part of the deployment, and started by the Edge runtime? 
If so, it should have the environment variables. The Edge runtime doesn't treat any module differently than the other modules, and as such the Edge specific environment variables (IOTEDGE_*) should get injected to all modules that are started by Edge runtime. 
So the only way the ML module won't have those variables is if it was started out of band. 
If it was indeed part of the deployment, can you try removing the ml module container ($>sudo docker rm -f mlmodule). Then the edge runtime will re-create the module and you should see the environment variables. 
If it still doesn't work, then can you please send us the EdgeAgent logs? That might tell us more.

**Comment by ilyas-it83** [comment]
@varunpuranik, This issue happend only once, but later when i did the re-deployment, the module received all the Edge specific environment variables (IOTEDGE_*). I could not re-produce the same issue again to help you with the logs. So please close the issue for now.
