### ISSUE TITLE
IoT edge device in transparent gateway mode with downstream device : which features are not enabled ?

### ISSUE THREAD

**Issue by ewertons** [Azure/iotedge#1075]
This issue was filed on behalf of @krokoko, porting issue https://github.com/Azure/azure-iot-sdk-c/issues/938 to the correct repo:

"Hello guys,
I was wondering if you have a clear list / roadmap for the features which are available/not available from a downstream device connected to an iot edge device in transparent gateway mode, something like this : https://github.com/Azure/azure-iot-sdk-c#key-features-and-roadmap . I would like to use the file upload to blob storage and automatic provisioning, which are not available yet. Also I would like to add a firmware update, is a supported scenario ?
Thank you for the good job ! :)"

## Steps to Reproduce

1.
2.
3.
4.

**Comment by krokoko** [comment]
Any update ?

**Comment by krokoko** [comment]
ping

**Comment by lt72** [comment]
@krokoko unfortunately we will not be able to publish a roadmap at this time. Blob storage is not supported.
