### ISSUE TITLE
Build of IoT Edge Solution failing on Mac OS X with VS Code

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1077]
Hi,

I have created sample IoT Edge solution using C# module and able to build solution if select amd64 for linux or arm32v7.

This complete setup is on Mac OS X- 10.14.3

Below is the log for successful build-

```
docker build  --rm -f "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule/Dockerfile.amd64" -t localhost:5000/samplemodule:0.0.1-amd64 "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule"
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v8.1.3 --silent` to unset it.
AMAC02T82A5G8WL:samplesolution singh.prateek$ docker build  --rm -f "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule/Dockerfile.amd64" -t localhost:5000/samplemodule:0.0.1-amd64 "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule"
Sending build context to Docker daemon  499.2kB
Step 1/12 : FROM microsoft/dotnet:2.1-sdk AS build-env
 ---> d14ca4022ef8
Step 2/12 : WORKDIR /app
 ---> Using cache
 ---> eb579a436ee1
Step 3/12 : COPY *.csproj ./
 ---> Using cache
 ---> 6545fdce6700
Step 4/12 : RUN dotnet restore
 ---> Using cache
 ---> 4c9957eecd3f
Step 5/12 : COPY . ./
 ---> Using cache
 ---> a6a8fe4644df
Step 6/12 : RUN dotnet publish -c Release -o out
 ---> Using cache
 ---> 1e6cc7003801
Step 7/12 : FROM microsoft/dotnet:2.1-runtime-stretch-slim
 ---> e1979bed16c6
Step 8/12 : WORKDIR /app
 ---> Using cache
 ---> 8b1e6764a5cc
Step 9/12 : COPY --from=build-env /app/out ./
 ---> Using cache
 ---> f0d0e8fdbccc
Step 10/12 : RUN useradd -ms /bin/bash moduleuser
 ---> Using cache
 ---> 81b8f8005ba8
Step 11/12 : USER moduleuser
 ---> Using cache
 ---> 1436a3d62862
Step 12/12 : ENTRYPOINT ["dotnet", "SampleModule.dll"]
 ---> Using cache
 ---> 76b283d4b4f3
Successfully built 76b283d4b4f3
Successfully tagged localhost:5000/samplemodule:0.0.1-amd64

```

Selected amd64 in status bar in bottom. Below is the screenshot-

<img width="1431" alt="Screenshot 2019-04-12 at 00 22 42" src="https://user-images.githubusercontent.com/7486266/55984763-cf6a4a00-5cbb-11e9-808b-a51a689ba987.png">

I need to build a solution on Windows IoT Core but facing issue while building the code.
 If i select to build the solution for windows.amd64. It get failed and build doesn't get completed.  
Facing the same issue on Windows 10 Enterprise with VS Code.
Below is the log for the same-

> docker run -d -p 5000:5000 --restart always --name registry registry:2
> docker build  --rm -f "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule/Dockerfile.windows-amd64" -t localhost:5000/samplemodule:0.0.1-windows-amd64 "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule"
> nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
> Run `npm config delete prefix` or `nvm use --delete-prefix v8.1.3 --silent` to unset it.
> AMAC02T82A5G8WL:samplesolution singh.prateek$ docker run -d -p 5000:5000 --restart always --name registry registry:2
> Unable to find image 'registry:2' locally
> 2: Pulling from library/registry
> c87736221ed0: Pull complete 
> 1cc8e0bb44df: Pull complete 
> 54d33bcb37f5: Pull complete 
> e8afc091c171: Pull complete 
> b4541f6d3db6: Pull complete 
> Digest: sha256:3b00e5438ebd8835bcfa7bf5246445a6b57b9a50473e89c02ecc8e575be3ebb5
> Status: Downloaded newer image for registry:2
> 5f1cbd7626cd41e7323b9fc863a373eff286b1a2202454c5aaa9f24b752fe302
> AMAC02T82A5G8WL:samplesolution singh.prateek$ docker build  --rm -f "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule/Dockerfile.windows-amd64" -t localhost:5000/samplemodule:0.0.1-windows-amd64 "/Users/singh.prateek/Documents/usb_edge_module/samplesolution/modules/SampleModule"
> Sending build context to Docker daemon  499.2kB
> Step 1/10 : FROM microsoft/dotnet:2.1-sdk AS build-env
>  ---> d14ca4022ef8
> Step 2/10 : WORKDIR /app
>  ---> Using cache
>  ---> eb579a436ee1
> Step 3/10 : COPY *.csproj ./
>  ---> Using cache
>  ---> 6545fdce6700
> Step 4/10 : RUN dotnet restore
>  ---> Using cache
>  ---> 4c9957eecd3f
> Step 5/10 : COPY . ./
>  ---> a6a8fe4644df
> Step 6/10 : RUN dotnet publish -c Release -o out
>  ---> Running in ac36c998ccba
> Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Restoring packages for /app/SampleModule.csproj...
>   Installing WindowsAzure.Storage 9.3.2.
>   Installing Microsoft.Azure.Amqp 2.4.1.
>   Installing Microsoft.Azure.Devices.Shared 1.16.0.
>   Installing Microsoft.Azure.Devices.Client 1.20.0.
>   Generating MSBuild file /app/obj/SampleModule.csproj.nuget.g.props.
>   Generating MSBuild file /app/obj/SampleModule.csproj.nuget.g.targets.
>   Restore completed in 4.28 sec for /app/SampleModule.csproj.
>   SampleModule -> /app/bin/Release/netcoreapp2.1/SampleModule.dll
>   SampleModule -> /app/out/
> Removing intermediate container ac36c998ccba
>  ---> 1e6cc7003801
> Step 7/10 : FROM microsoft/dotnet:2.1-runtime-nanoserver-1809
> 2.1-runtime-nanoserver-1809: Pulling from microsoft/dotnet
> 9319e23c8670: Pulling fs layer 
> 06115200a5ea: Pulling fs layer 
> bfe004a217a3: Downloading [==============================>                    ]     501B/832B
> 62910792b602: Waiting 
> 3438d488c839: Waiting 
> a6068294d62b: Waiting 
> **image operating system "windows" cannot be used on this platform**

Below is the screenshot for windows.amd64 selection in status bar-

<img width="1437" alt="Screenshot 2019-04-12 at 00 21 49" src="https://user-images.githubusercontent.com/7486266/55984772-d7c28500-5cbb-11e9-916f-e56733c5da14.png">

Can you please let me know the root cause for this. I tried the same

**Comment by shizn** [comment]
Hey @pratson20. Is your IoT Core device an arm32 or amd64 device? There are several things.
1. There is no support for windows-arm at this moment in VS Code.
2. If you want to build Windows container running on Windows devices, you have to build everything on Windows, and make sure you are in Windows container mode.

**Comment by pratson20** [comment]
Hi @shizn,

I have to build solution for IoT Core(amd64). I have working solution for linux amd64 and building this solution on Mac OS X and deploying on Edge GW running Linux. But, i have to migrate everything on IoT Core(amd64) GW device. 

It is not possible to build solution on Mac OS X for IoT Core(amd64)?

If not then i need to use Windows Machine to build the solution.

Thanks

**Comment by shizn** [comment]
@veyalla could you help share IoT Core (amd64) support timeline?

**Comment by shizn** [comment]
@praston20 If you want to work on MacOS and build Windows containers, there are two options.
1. Use VS Code on MacOS, then configure the Docker Host and point to your IoT Core device. Please see here - https://devblogs.microsoft.com/iotdev/easily-build-and-debug-iot-edge-modules-on-your-remote-device-with-azure-iot-edge-for-vs-code-1-9-0/
2. Switch to Windows dev machine.

**Comment by pratson20** [comment]
Hi @shizn,

I have created Windows VM on Mac OS X with build 1809(17763.348). Done all the setup which is required to build the code  and created sample template to build solution for windows.amd64 but seeing below  issue-

I have enabled Container and Hyper-V in Windows VM.

```
PS C:\Users\User\Documents\Visual Studio 2017\edge\EdgeSolution> docker build  --rm -f "c:\Users\User\Documents\Visual Studio 2017\edge\EdgeSolution\modules\SampleModule\Dockerfile.windows-amd64" -t <container-registry>.azurecr.io/samplemodule:0.0.1-windows-amd64 "c:\Users\User\Documents\Visual Studio 2017\edge\EdgeSolution\modules\SampleModule"
Sending build context to Docker daemon  537.6kB
Step 1/10 : FROM microsoft/dotnet:2.1-sdk AS build-env
 ---> 61c98560a623
Step 2/10 : WORKDIR /app
 ---> Using cache
 ---> 61dfbf486a43
Step 3/10 : COPY *.csproj ./
 ---> Using cache
 ---> e77382e34834
Step 4/10 : RUN dotnet restore
 ---> Running in b00d90c5817e
CreateComputeSystem b00d90c5817e0dc933ee5b95a4ef289b946e9f41eec3998af7403da3964b53aa: 
The virtual machine could not be started because a required feature is not installed.
(extra info: {"SystemType":"Container","Name":"b00d90c5817e0dc933ee5b95a4ef289b946e9f41eec3998af7403da3964b53aa","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\b00d90c5817e0dc933ee5b95a4ef289b946e9f41eec3998af7403da3964b53aa","Layers":[{"ID":"a43dcec4-ef3d-5df0-8860-ce296969d216","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f2e40ead4b9cb1c37cbf08f997ed694087601e163dad0bc40529f856a82b555a"},{"ID":"0730e4ea-31c5-55e9-ac3d-fd993da1626c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1eec0416d7588e1c87203e5734387262f19bcb820d0e90accf1f1063693198fb"},{"ID":"09baf5a9-ade3-54d9-8383-f9cbd9087fd3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2698e79d95efd5572fda9986eb91eeee9c29682afab554689f2cb10faf3e4aeb"},{"ID":"012ba831-6d9f-5e3e-b685-5e4b6e46aca5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0fdb7e51020a4ae9d7c29f3127eb310c92aaf7faeec802af5088bd2906686de3"},{"ID":"3cca5da0-ae86-520f-b264-a772cdd315f5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cb14614c498e7c14374fb3fd882f1f66eea3b697fd4d8ae7f81c5e4346bc52aa"},{"ID":"fbda6b7d-e44f-5d1d-a72b-027a9fc44f8a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\09a36886ff5189da973bda996fa5fa53d35cdf2d67d58ba2b0f94e86ea8d2d57"},{"ID":"3324e73a-7eeb-5bca-94be-04b467863213","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7763a6c302ab1081d57e755f410cf29a0ed117e8a91d6ad2012fb45ec783a75f"},{"ID":"d92ace19-040c-599e-88fe-5a7771c2b9b7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7417825eaaad120f150439e2ac072c1bdf4315b0f17f420e6453e68fc9c76772"},{"ID":"8ddd550c-ab16-5a80-89f0-7a2b6c433040","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c2b31e8ada3949ba1d1aafb924cea5e4926574b5bd880b41f44a7c9d06b4d2fa"}],"HostName":"b00d90c5817e","HvPartition":true,"EndpointList":["CFB14390-AB07-4847-9978-AEC740D3C761"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\c2b31e8ada3949ba1d1aafb924cea5e4926574b5bd880b41f44a7c9d06b4d2fa\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})
```


Can you please let me know the root cause for the same.

Thanks

**Comment by veyalla** [comment]
I don't think the Windows VM in Mac OS can support Hyper-V as this is a nested virtualization configuration.

You can try using the `--isolation=process` switch ([link](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/faq#can-i-run-windows-containers-in-process-isolated-mode-on-windows-10-enterprise-or-professional))
