### ISSUE TITLE
Own Module does not restart

### ISSUE THREAD

**Issue by LukasKarel** [Azure/iotedge#1104]
## Expected Behavior
Module should restart and be in running state.

## Current Behavior
Module does restart but stays in stopped state.

## Steps to Reproduce

1.Restart iotedge
2.Wait until module does restarting some times
3.Wait until module stays in mode stopped

### Device (Host) Operating System
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs

### Architecture
armv7l

### Container Operating System
Linux Container

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 17:16:17 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       8ecd530
  Built:            Mon Feb 11 20:31:38 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.2
  GitCommit:        9754871865f7fe2f4e74d43e2fc7ccd237edcbce
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        96ec2177ae841256168fcf76954f7177af9446eb
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Logs
**journalctl iotedge**:
Apr 18 02:05:14 raspberrypi iotedged[3294]: 2019-04-18T01:05:14Z [INFO] - Stopping module custom_module...
Apr 18 02:05:14 raspberrypi iotedged[3294]: 2019-04-18T01:05:14Z [WARN] - Could not stop module custom_module
Apr 18 02:05:14 raspberrypi iotedged[3294]: 2019-04-18T01:05:14Z [WARN] -         caused by: Target of operation already in this state
Apr 18 02:05:14 raspberrypi iotedged[3294]: 2019-04-18T01:05:14Z [INFO] - [mgmt] - - - [2019-04-18 01:05:14.949052901 UTC] "POST /modules/custom_module/stop?api-version=2018-06-28 HTTP/1.1" 304 Not Modified 0 "-" "-" pid(3630)
Apr 18 02:05:14 raspberrypi iotedged[3294]: 2019-04-18T01:05:14Z [INFO] - Starting module custom_module...
Apr 18 02:05:15 raspberrypi iotedged[3294]: 2019-04-18T01:05:15Z [INFO] - Successfully started module custom_module
Apr 18 02:05:15 raspberrypi iotedged[3294]: 2019-04-18T01:05:15Z [INFO] - [mgmt] - - - [2019-04-18 01:05:15.578459892 UTC] "POST /modules/custom_module/start?api-version=2018-06-28 HTTP/1.1" 204 No Content - "-" "-" pid(3630)
Apr 18 02:05:15 raspberrypi iotedged[3294]: 2019-04-18T01:05:15Z [INFO] - [work] - - - [2019-04-18 01:05:15.609375719 UTC] "POST /modules/%24edgeAgent/genid/636772544784120304/encrypt?api-version=2018-06-28 HTTP/1.1" 200 OK 57

**iotedge logs edgeAgent**:
2019-04-18 01:00:17.246 +00:00 [INF] - Module 'custom_module' scheduled to restart after 05m:00s (04m:56s left).
2019-04-18 01:00:17.640 +00:00 [INF] - Updated reported properties
2019-04-18 01:00:22.759 +00:00 [INF] - Module 'custom_module' scheduled to restart after 05m:00s (04m:51s left).
2019-04-18 01:00:27.896 +00:00 [INF] - Module 'custom_module' scheduled to restart after 05m:00s (04m:46s left).
2019-04-18 01:00:33.031 +00:00 [INF] - Module 'custom_module' scheduled to restart after 05m:00s (04m:41s left).
...
2019-04-18 01:05:09.813 +00:00 [INF] - Module 'custom_module' scheduled to restart after 05m:00s (04s left).
2019-04-18 01:05:14.942 +00:00 [INF] - Plan execution started for deployment 88
2019-04-18 01:05:14.943 +00:00 [INF] - Executing command: "Command Group: (
  [Stop module custom_module]
  [Start module custom_module]
  [Saving custom_module to store]
)"
2019-04-18 01:05:14.943 +00:00 [INF] - Executing command: "Stop module custom_module"
2019-04-18 01:05:14.958 +00:00 [INF] - Executing command: "Start module custom_module"
2019-04-18 01:05:15.579 +00:00 [INF] - Executing command: "Saving custom_module to store"
2019-04-18 01:05:15.580 +00:00 [INF] - Plan execution ended for deployment 88
2019-04-18 01:05:21.013 +00:00 [INF] - Updated reported properties
2019-04-18 01:09:33.129 +00:00 [INF] - Updated reported properties

**iotedge list:**
costum_module                  stopped          Stopped 7 hours ago  registry/custom_module:0.0.7-arm32v7

## Additional Information

The logs says module has restarted sucessfully but iotedge list shows status stopped.
According to IoT Hub the Runtime status of this module is failed. Module has crashed 20 times. Is there a maximum of allowed crashes?

**Comment by darobs** [comment]
Hello @LukasKarel,

By default the edgeAgent has a restart planner that will back off starting modules, and will eventually stop attempting to restart the module after failing to restart it 5 times at max backoff.  At this point, the edge runtime will need manual intervention. 

One intervention is removing the module (`docker rm -f custom_module`). This will reset the backoff process. If you can't affect the device directly, removing it from the deployment and adding it back will also have the same effect.


The number of time it retires is affected by the "MaxRestartCount" setting, which may be set as an environment variable passed into the edgeAgent container.

**Comment by LukasKarel** [comment]
Hello @darobs 

Thank you for your fast reply.

Is it possible to set MaxRestartCount to infinite?

**Comment by darobs** [comment]
It looks like (as of this moment) it is expected to be positive integer value.  You can set it really high, but not infinite.

**Comment by myagley** [comment]
I'm going to close this issue as it looks like a suitable config was provided.
