### ISSUE TITLE
There should be a way to have a running sequence of modules in the deployments

### ISSUE THREAD

**Issue by gauravagarwal28** [Azure/iotedge#1105]
![image](https://user-images.githubusercontent.com/41729265/56351723-6454d200-61eb-11e9-9be5-67a2442b6b61.png)

The modules in my images are failing because the edgeHub module has not yet started and thus the IoT Clients are not getting initialized.

No module should be started until the edgeHub starts.
Also, I have a server module that is dependent on a postgres module.

I keep retrying the connection in my server module until the postgres module starts.
It would be much better if we could have a provision to specify the dependency of a module on another module.

**Comment by myagley** [comment]
Thanks for the issue. I understand the issues that you are facing.

However, IoT Edge doesn't support starting modules in a particular order to encourage building resiliency into your module. This was a deliberate choice.

From the perspective of a module, there is no difference in a module starting before a dependency and that dependency crashing. Start up order may help in the first instance, but won't help if the Edge Hub (or any other module your module depends on) crashes or is updated. You need to build in this resiliency. The IoT Hub SDK will retry operations for you, and you should be able to adjust it's timeouts.

Kelsey Hightower (of Kubernetes fame) does a good job of capturing this philosophy in one of his posts: https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c. The bit about start up order comes near the end.

**Comment by damonbarry** [comment]
Question answered, and no further activity. Closing...

**Comment by luiscantero** [comment]
See [StartupOrder](https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#module-configuration-and-management).
