### ISSUE TITLE
Edge device to device communication within Network

### ISSUE THREAD

**Issue by githubmobiliya** [Azure/iotedge#1115]
Hi Team,

I want to know if there is any support or plan to enable edge device ti device communication with a network without internet. We want to deploy multiple edge devices in single site. This edge devices can host different modules doing analytics, Device integration and others and want to share data to other edge devices. 

Is there any support with iot edge to enable this communication options or anything planned to support in future. Also, any suggestions for custom modules like Pub/Sub, MQTT etc for module level communication. Edge devices may sync data to cloud or not.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mrohera** [comment]
In its current form, the Edge device is expected to connect to IoT Hub at least once to be provisioned and setup with all modules. After this, the Edge can operate offline for extended periods of time.

To understand your question further, did you mean you want to manually setup all Edge devices in an offline fashion?

More about Edge and offline behavior can be read here: https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities

**Comment by mrohera** [comment]
@veyalla
