### ISSUE TITLE
How to access sensor connecting to Raspberry Pi in C# custom module 

### ISSUE THREAD

**Issue by shizn** [Azure/iotedge#1120]
## Current Behavior

Customer is trying to using .Net Core to access GPIO in C# custom module. There is no clue how to do it after searching on Google. So he switched to Python because these are some adafruit libraries and samples showing exactly he wanted.

### Device (Host) Operating System

Raspbian

### Architecture

arm32

### Container Operating System

Linux containers

**Comment by mrohera** [comment]
Hi shizn,
Thank you for your question. Perhaps this is a question you can ask the .NET core team here: https://github.com/dotnet/core

A quick search revealed that there are new APIs in 3.0.0 to support your scenario.

**Comment by bmanners** [comment]
I (the customer) can add Some additional info.

I am trying to access the GPIO pins on a Raspberry Pi via an SPI interface. I *think* the GPIO pins might be exposed via the /dev/ file system folder in Raspian.

I don't really expect libraries or detailed documentation from MS on how to do this but it was the more difficult part of my project. Also i think the whole point of the Iot Hub /Edge is to gather data and bring it back to the cloud. Most of the time that data will be accesses via some hardware interface (GPIO pins, RS232, RS485, I2C, SPI, etc). It might help the Iot Edge ecosystem, by reducing the barrier to entry, if there was some documentation on how to access real data sources. Obviously there are many different hardware platforms and interfaces that IOT Edge can run on so maybe documentation for the most popular hardware / interface combination could be considered.?

Brett

**Comment by bmanners** [comment]
After seeing some info from Build i looked further and was very happy to see what is happening in .Net Core 3. You HAVE made all the libraries i didn't expect!!  WOW, i mean WOW!...that is awesome. There is even a C# driver for the ADC chip i am using! There goes my spare time for a while :-)

Here is the docs on how to access analogue input on a Pi in C# if anyone else needs it.
https://github.com/dotnet/iot/tree/master/src/devices/Mcp3008/samples


Brett

**Comment by shizn** [comment]
Yep. There are the .Net Core 3.0 libraries we are referring to. I'm going to close this issue. Let me know if you have further questions.
