### ISSUE TITLE
Issue with starting docker daemon on Ubuntu 16.04.

### ISSUE THREAD

**Issue by victorwangwinmate** [Azure/iotedge#1123]
So I've gotten all the way to the point where I need to verify successful installation of IoT Edge daemon, and it's failing with the following output:

> ubuntu@arm:/etc/iotedge$` sudo systemctl status iotedge
â— iotedge.service - Azure IoT Edge daemon
Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
Active: inactive (dead) (Result: exit-code) since Thu 2019-04-18 02:45:25 UTC; 2s ago
Docs: man:iotedged(8)
Process: 19457 ExecStart=/usr/bin/iotedged -c /etc/iotedge/config.yaml (code=exited, status=127)
Main PID: 19457 (code=exited, status=127)
Apr 18 02:45:25 arm systemd[1]: iotedge.service: Main process exited, code=exited, status=127/n/a
Apr 18 02:45:25 arm systemd[1]: iotedge.service: Unit entered failed state.
Apr 18 02:45:25 arm systemd[1]: iotedge.service: Failed with result 'exit-code'.
Apr 18 02:45:25 arm systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Apr 18 02:45:25 arm systemd[1]: Stopped Azure IoT Edge daemon.
Apr 18 02:45:25 arm systemd[1]: Dependency failed for Azure IoT Edge daemon.
Apr 18 02:45:25 arm systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.

I tried to check the docker daemon by this command `sudo docker ps -a`, and I would get below output:
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I realize that docker did not start successfully.
consequently, I tried to debug docker by `sudo dockerd` and get below output:

> user@arm:~$ sudo dockerd
INFO[2019-04-23T03:09:40.709312620Z] libcontainerd: started new containerd process  pid=14688
INFO[2019-04-23T03:09:40.711328285Z] parsed scheme: "unix"                         module=grpc
INFO[2019-04-23T03:09:40.712192952Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-04-23T03:09:40.713605951Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-23T03:09:40.714691617Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-23T03:09:40.715992950Z] pickfirstBalancer: HandleSubConnStateChange: 0x4632370, CONNECTING  module=grpc
INFO[2019-04-23T03:09:40.836035559Z] starting containerd                           revision=9754871865f7fe2f4e74d43e2fc7ccd237edcbce version=v1.2.2
INFO[2019-04-23T03:09:40.839784891Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2019-04-23T03:09:40.841148890Z] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
WARN[2019-04-23T03:09:40.843297556Z] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
INFO[2019-04-23T03:09:40.844118889Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
WARN[2019-04-23T03:09:40.856540216Z] failed to load plugin io.containerd.snapshotter.v1.aufs  error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.1.15-1.2.0+gd2fb5c8\n": exit status 1"
INFO[2019-04-23T03:09:40.856883216Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2019-04-23T03:09:40.857312216Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2019-04-23T03:09:40.858622882Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
WARN[2019-04-23T03:09:40.860068548Z] failed to load plugin io.containerd.snapshotter.v1.zfs  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[2019-04-23T03:09:40.860453881Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2019-04-23T03:09:40.860732547Z] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
WARN[2019-04-23T03:09:40.860922547Z] could not use snapshotter aufs in metadata plugin  error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.1.15-1.2.0+gd2fb5c8\n": exit status 1"
WARN[2019-04-23T03:09:40.861170214Z] could not use snapshotter zfs in metadata plugin  error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter"
INFO[2019-04-23T03:09:40.862395213Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2019-04-23T03:09:40.862971546Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2019-04-23T03:09:40.864310879Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.864691879Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.864988212Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.865262212Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.865532545Z] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.865869212Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.866132212Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.866391878Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2019-04-23T03:09:40.867566877Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2019-04-23T03:09:40.868279877Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2019-04-23T03:09:40.872846542Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2019-04-23T03:09:40.873326208Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2019-04-23T03:09:40.873875541Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.874203874Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.874491208Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.874757541Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.875009207Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.875268874Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.875528874Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.875786874Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.876037540Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2019-04-23T03:09:40.877097540Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.877524206Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.877985539Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.878317872Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2019-04-23T03:09:40.879969872Z] serving...                                    address="/var/run/docker/containerd/containerd-debug.sock"
INFO[2019-04-23T03:09:40.880563205Z] serving...                                    address="/var/run/docker/containerd/containerd.sock"
INFO[2019-04-23T03:09:40.880811205Z] containerd successfully booted in 0.047864s
INFO[2019-04-23T03:09:40.890721533Z] pickfirstBalancer: HandleSubConnStateChange: 0x4632370, READY  module=grpc
INFO[2019-04-23T03:09:40.958246834Z] parsed scheme: "unix"                         module=grpc
INFO[2019-04-23T03:09:40.958535167Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-04-23T03:09:40.959026834Z] parsed scheme: "unix"                         module=grpc
INFO[2019-04-23T03:09:40.959174167Z] scheme "unix" not registered, fallback to default scheme  module=grpc
INFO[2019-04-23T03:09:40.966077831Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-23T03:09:40.968045830Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-23T03:09:40.970409495Z] pickfirstBalancer: HandleSubConnStateChange: 0x46920b0, CONNECTING  module=grpc
INFO[2019-04-23T03:09:40.974631160Z] [graphdriver] using prior storage driver: overlay2
INFO[2019-04-23T03:09:40.974754160Z] pickfirstBalancer: HandleSubConnStateChange: 0x46920b0, READY  module=grpc
INFO[2019-04-23T03:09:40.975393826Z] ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]  module=grpc
INFO[2019-04-23T03:09:40.975587159Z] ClientConn switching balancer to "pick_first"  module=grpc
INFO[2019-04-23T03:09:40.987082154Z] pickfirstBalancer: HandleSubConnStateChange: 0x46325e0, CONNECTING  module=grpc
WARN[2019-04-23T03:09:40.990830485Z] Your kernel does not support cgroup blkio weight
WARN[2019-04-23T03:09:40.991620485Z] Your kernel does not support cgroup blkio weight_device
WARN[2019-04-23T03:09:40.992803818Z] Your kernel does not support cgroup blkio throttle.read_bps_device
WARN[2019-04-23T03:09:40.993490817Z] Your kernel does not support cgroup blkio throttle.write_bps_device
WARN[2019-04-23T03:09:40.994062151Z] Your kernel does not support cgroup blkio throttle.read_iops_device
WARN[2019-04-23T03:09:40.994718150Z] Your kernel does not support cgroup blkio throttle.write_iops_device
WARN[2019-04-23T03:09:40.996438149Z] mountpoint for pids not found
INFO[2019-04-23T03:09:40.999801814Z] Loading containers: start.
INFO[2019-04-23T03:09:40.991269152Z] pickfirstBalancer: HandleSubConnStateChange: 0x46325e0, READY  module=grpc
INFO[2019-04-23T03:09:41.518851253Z] Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address
INFO[2019-04-23T03:09:41.651845194Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=moby
INFO[2019-04-23T03:09:41.652629194Z] stopping healthcheck following graceful shutdown  module=libcontainerd
INFO[2019-04-23T03:09:41.653150527Z] stopping event stream following graceful shutdown  error="context canceled" module=libcontainerd namespace=plugins.moby
INFO[2019-04-23T03:09:41.655372860Z] pickfirstBalancer: HandleSubConnStateChange: 0x46325e0, TRANSIENT_FAILURE  module=grpc
INFO[2019-04-23T03:09:41.655906193Z] pickfirstBalancer: HandleSubConnStateChange: 0x46325e0, CONNECTING  module=grpc
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to program NAT chain: Failed to inject DOCKER in PREROUTING chain: iptables failed: iptables --wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER: iptables: No chain/target/match by that name.
 (exit status 1)

At the bottom of the log, I found that it will fail to execute command `iptables --wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER`.
Also, there are warnings in the log.

Can anyone help with this issue?

**Comment by myagley** [comment]
Can you run `journalctl -u docker` to get the logs from the docker engine when it is starting up by the system?

What packages are you using to install Docker?

**Comment by victorwangwinmate** [comment]
@myagley Thanks for your reply.
**Can you run journalctl -u docker to get the logs from the docker engine when it is starting up by the system?**
Below file link is the log of `journalctl -u docker`.
[log.txt](https://github.com/Azure/iotedge/files/3110437/log.txt)

**What packages are you using to install Docker?**
I refer to this Chinese page link as below.
[link](https://docs.microsoft.com/zh-tw/azure/iot-edge/how-to-install-iot-edge-linux-arm#install-the-container-runtime)

Thanks for your help.

**Comment by lt72** [comment]
Closing issue as stale. We apologize for the late answer. Please re=open as needed.
