### ISSUE TITLE
How to send large Json packet to multiple downstream(child) devices from azure edge custom modules

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1124]
Hi,

I have few requirement for my client, can you please suggest how can we implement that?

1. Can we  send large json packet (let say 100kb)  from cloud to edge hub custom module? How can we implement that on edge custom module?

2. Multiple child devices are connected with azure edge hub. How can i send the packet to all downstream(child) devices which is connected with edge hub.

3. Can we do using transparent gateway?

Thanks,
Prateek

**Comment by myagley** [comment]
The maximum payload size for a direct method is 128kb, so you may be able to use it to transfer, if the payload is always guaranteed to be lower than this limit. Cloud to device messages are limited to 64kb, and twin is limited to 8kb: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits

The other option is to use direct methods or twin as a "shoulder tap". You could store the data in a blob store or other storage system and send the device a pointer to this data using a direct method, cloud to device messages, or twin update.

**Comment by pratson20** [comment]
Thanks @myagley
