### ISSUE TITLE
Communication between device twin of edge and child device

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1147]
Hi,

Can we update device twin of downstream devices(child device) from devices twin of edge device(parent device).

We are using transparent gateway solution. Idea is to update desired property of IoT device(downstream device) from device twin of edge device on gateway configured with IoT Edge.

Could we do that?

Regards,
Prateek

**Comment by myagley** [comment]
You aren't able to update the desired properties in a twin on the edge device. All desired property updates need to occur through the cloud. The current design of twin assumes that the desired properties are owned by the cloud.

**Comment by pratson20** [comment]
Thanks @myagley
