### ISSUE TITLE
The operation could not be started because a required feature is not installed

### ISSUE THREAD

**Issue by firstcrazydeveloper** [Azure/iotedge#1171]
I installed  Windows 10 Version 1809( OS build 17763.437).  As mentioned steps, I didn't install Docker. I followed all the given steps from here: https://docs.microsoft.com/en-us/azure/iot-edge/quickstart

But Could not start module edgeAgent and get the following error:
caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be  started because a required feature is not installed

## Expected Behavior

After following all require action Edge Runtime should be installed properly.
## Current Behavior
But When trying to install runtime get the following error:
5/4/2019 4:51:40 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 4:51:40 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging -- A module runtime error occurred.
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging --    caused by: Could not start module edgeAgent                     
5/4/2019 5:01:42 PM  warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging -- Could not start module edgeAgent
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
## Steps to Reproduce

1. Update Window with Version 1809( OS build 17763.437)
2. Enable Container windows feature
3. Install IoTEdge Runtime
4. Check logs

## Context (Environment)
Microsoft Windows 10 version 1809( OS build 17763.437)
Standalone Workstation
### Device (Host) Operating System

Microsoft Windows 10
### Architecture
amd64, Intel Core
### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Docker
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

## Logs
5/4/2019 3:48:44 PM  info: edgelet_docker::runtime -- Successfully got logs for module edgeAgent
5/4/2019 3:48:44 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 3:48:44 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 3:50:55 PM  info: edgelet_core::watchdog -- Stopping edge runtime module edgeAgent
5/4/2019 3:50:55 PM  info: edgelet_docker::runtime -- Stopping module edgeAgent...
5/4/2019 3:50:55 PM  info: iotedged::windows -- iotedged service is shutting down
5/4/2019 3:50:55 PM  info: iotedged::windows -- Stopping iotedged service.
5/4/2019 4:11:20 PM  info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/4/2019 4:11:20 PM  info: iotedged::app -- Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
5/4/2019 4:11:20 PM  info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/4/2019 4:11:20 PM  info: iotedged -- Initializing the module runtime...
5/4/2019 4:11:20 PM  info: edgelet_docker::runtime -- Initializing module runtime...
5/4/2019 4:11:20 PM  info: iotedged::windows -- Starting iotedged service.
5/4/2019 4:11:20 PM  info: iotedged -- Using runtime network id nat
5/4/2019 4:13:43 PM  info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/4/2019 4:13:43 PM  info: iotedged::app -- Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
5/4/2019 4:13:43 PM  info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/4/2019 4:13:43 PM  info: iotedged::windows -- Starting iotedged service.
5/4/2019 4:13:43 PM  info: edgelet_docker::runtime -- Initializing module runtime...
5/4/2019 4:13:43 PM  info: iotedged -- Initializing the module runtime...
5/4/2019 4:13:43 PM  info: iotedged -- Using runtime network id nat
5/4/2019 4:16:07 PM  info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/4/2019 4:16:07 PM  info: iotedged::app -- Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
5/4/2019 4:16:07 PM  info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/4/2019 4:16:07 PM  info: iotedged -- Initializing the module runtime...
5/4/2019 4:16:07 PM  info: edgelet_docker::runtime -- Initializing module runtime...
5/4/2019 4:16:07 PM  info: iotedged::windows -- Starting iotedged service.
5/4/2019 4:16:07 PM  info: iotedged -- Using runtime network id nat
5/4/2019 4:18:30 PM  info: iotedged::app -- Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
5/4/2019 4:18:30 PM  info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/4/2019 4:18:30 PM  info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/4/2019 4:18:30 PM  info: iotedged::windows -- Starting iotedged service.
5/4/2019 4:18:30 PM  info: edgelet_docker::runtime -- Initializing module runtime...
5/4/2019 4:18:30 PM  info: iotedged -- Initializing the module runtime...
5/4/2019 4:18:30 PM  info: iotedged -- Using runtime network id nat
5/4/2019 4:20:57 PM  info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/4/2019 4:20:57 PM  info: iotedged::app -- Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
5/4/2019 4:20:57 PM  info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/4/2019 4:20:57 PM  info: iotedged -- Initializing the module runtime...
5/4/2019 4:20:57 PM  info: edgelet_docker::runtime -- Initializing module runtime...
5/4/2019 4:20:57 PM  info: iotedged::windows -- Starting iotedged service.
5/4/2019 4:20:57 PM  info: iotedged -- Using runtime network id nat
5/4/2019 4:21:29 PM  info: edgelet_docker::runtime -- Successfully initialized module runtime
5/4/2019 4:21:29 PM  info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/4/2019 4:21:29 PM  info: iotedged -- Finished configuring certificates.
5/4/2019 4:21:29 PM  info: iotedged -- Initializing hsm...
5/4/2019 4:21:29 PM  info: iotedged -- Finished initializing the module runtime.
5/4/2019 4:21:29 PM  info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/4/2019 4:21:29 PM  info: iotedged -- Configuring certificates...
5/4/2019 4:21:29 PM  info: iotedged -- Detecting if configuration file has changed...
5/4/2019 4:21:29 PM  info: iotedged -- Finished initializing hsm.
5/4/2019 4:21:29 PM  info: iotedged -- No change to configuration file detected.
5/4/2019 4:21:29 PM  info: iotedged -- Starting workload API...
5/4/2019 4:21:29 PM  info: iotedged -- Starting management API...
5/4/2019 4:21:29 PM  info: iotedged -- Listening on unix:///C:/ProgramData/iotedge/mgmt/sock with 1 thread for
                     management API.
5/4/2019 4:21:29 PM  info: edgelet_core::watchdog -- Starting watchdog with 60 second frequency...
5/4/2019 4:21:29 PM  info: iotedged -- Provisioning edge device...
5/4/2019 4:21:29 PM  info: iotedged -- Obtaining workload CA succeeded.
5/4/2019 4:21:29 PM  info: iotedged -- Finished provisioning edge device.
5/4/2019 4:21:29 PM  info: provisioning::provisioning -- Manually provisioning device
                     "7d529016-3953-4fb9-8d49-3df197862e01" in hub "Buhler-IoT-Development.azure-devices.net"
5/4/2019 4:21:29 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 4:21:29 PM  info: iotedged -- Listening on unix:///C:/ProgramData/iotedge/workload/sock with 1 thread for
                     workload API.
5/4/2019 4:21:29 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 4:21:29 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 4:31:36 PM  warn: edgelet_utils::logging --    caused by: Could not start module edgeAgent                     
5/4/2019 4:31:36 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 4:31:36 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 4:31:36 PM  warn: edgelet_utils::logging -- A module runtime error occurred.
5/4/2019 4:31:36 PM  warn: edgelet_utils::logging -- Could not start module edgeAgent
5/4/2019 4:31:36 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 4:31:36 PM  warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
5/4/2019 4:31:36 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 4:31:36 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 4:41:38 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 4:41:38 PM  warn: edgelet_utils::logging --    caused by: Could not start module edgeAgent                     
5/4/2019 4:41:38 PM  info: edgelet_http::logging -- [mgmt] - - - [2019-05-04 11:11:38.194172 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 399 "-" "iotedge/0.1.0" pid(18736)
5/4/2019 4:41:38 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 4:41:38 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 4:41:38 PM  warn: edgelet_utils::logging -- Could not start module edgeAgent
5/4/2019 4:41:38 PM  warn: edgelet_utils::logging -- A module runtime error occurred.
5/4/2019 4:41:38 PM  warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
5/4/2019 4:41:38 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 4:41:38 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 4:47:04 PM  info: edgelet_core::watchdog -- Stopping edge runtime module edgeAgent
5/4/2019 4:47:04 PM  info: edgelet_docker::runtime -- Stopping module edgeAgent...
5/4/2019 4:47:04 PM  info: iotedged::windows -- iotedged service is shutting down
5/4/2019 4:47:04 PM  info: iotedged::windows -- Stopping iotedged service.
5/4/2019 4:51:39 PM  warn: edgelet_utils::logging --    caused by: Target of operation already in this state            
5/4/2019 4:51:39 PM  warn: edgelet_utils::logging -- Could not stop module edgeAgent
5/4/2019 4:51:39 PM  error: iotedged::windows -- Error while running service. Quitting.
5/4/2019 4:51:39 PM  error: edgelet_utils::logging --   caused by: Could not stop module edgeAgent
5/4/2019 4:51:39 PM  error: edgelet_utils::logging --   caused by: Target of operation already in this state
5/4/2019 4:51:39 PM  error: edgelet_utils::logging -- The watchdog encountered an error
5/4/2019 4:51:39 PM  error: edgelet_utils::logging --   caused by: A module runtime error occurred.
5/4/2019 4:51:40 PM  info: iotedged::app -- Starting Azure IoT Edge Security Daemon
5/4/2019 4:51:40 PM  info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
5/4/2019 4:51:40 PM  info: iotedged::app -- Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
5/4/2019 4:51:40 PM  info: iotedged::windows -- Starting iotedged service.
5/4/2019 4:51:40 PM  info: edgelet_docker::runtime -- Initializing module runtime...
5/4/2019 4:51:40 PM  info: iotedged -- Initializing the module runtime...
5/4/2019 4:51:40 PM  info: iotedged -- Using runtime network id nat
5/4/2019 4:51:40 PM  info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
5/4/2019 4:51:40 PM  info: iotedged -- Finished configuring certificates.
5/4/2019 4:51:40 PM  info: iotedged -- Initializing hsm...
5/4/2019 4:51:40 PM  info: iotedged -- Configuring certificates...
5/4/2019 4:51:40 PM  info: edgelet_docker::runtime -- Successfully initialized module runtime
5/4/2019 4:51:40 PM  info: iotedged -- Finished initializing the module runtime.
5/4/2019 4:51:40 PM  info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
5/4/2019 4:51:40 PM  info: iotedged -- Detecting if configuration file has changed...
5/4/2019 4:51:40 PM  info: iotedged -- Finished initializing hsm.
5/4/2019 4:51:40 PM  info: iotedged -- No change to configuration file detected.
5/4/2019 4:51:40 PM  info: iotedged -- Obtaining workload CA succeeded.
5/4/2019 4:51:40 PM  info: iotedged -- Provisioning edge device...
5/4/2019 4:51:40 PM  info: iotedged -- Starting management API...
5/4/2019 4:51:40 PM  info: iotedged -- Finished provisioning edge device.
5/4/2019 4:51:40 PM  info: provisioning::provisioning -- Manually provisioning device
                     "7d529016-3953-4fb9-8d49-3df197862e01" in hub "Buhler-IoT-Development.azure-devices.net"
5/4/2019 4:51:40 PM  info: iotedged -- Starting workload API...
5/4/2019 4:51:40 PM  info: iotedged -- Listening on unix:///C:/ProgramData/iotedge/mgmt/sock with 1 thread for
                     management API.
5/4/2019 4:51:40 PM  info: edgelet_core::watchdog -- Starting watchdog with 60 second frequency...
5/4/2019 4:51:40 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 4:51:40 PM  info: iotedged -- Listening on unix:///C:/ProgramData/iotedge/workload/sock with 1 thread for
                     workload API.
5/4/2019 4:51:40 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 4:51:40 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging -- A module runtime error occurred.
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging --    caused by: Could not start module edgeAgent                     
5/4/2019 5:01:42 PM  warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging -- Could not start module edgeAgent
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:01:42 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 5:01:42 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:01:42 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 5:01:42 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 5:11:43 PM  warn: edgelet_utils::logging -- Could not start module edgeAgent
5/4/2019 5:11:43 PM  warn: edgelet_utils::logging --    caused by: Could not start module edgeAgent                     
5/4/2019 5:11:43 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:11:43 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 5:11:43 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:11:43 PM  warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
5/4/2019 5:11:43 PM  warn: edgelet_utils::logging -- A module runtime error occurred.
5/4/2019 5:11:43 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 5:11:43 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 5:21:45 PM  warn: edgelet_utils::logging -- A module runtime error occurred.
5/4/2019 5:21:45 PM  warn: edgelet_utils::logging --    caused by: Could not start module edgeAgent                     
5/4/2019 5:21:45 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:21:45 PM  warn: edgelet_utils::logging -- Could not start module edgeAgent
5/4/2019 5:21:45 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:21:45 PM  warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
5/4/2019 5:21:45 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 5:21:45 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 5:21:45 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
5/4/2019 5:31:47 PM  warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
5/4/2019 5:31:47 PM  warn: edgelet_utils::logging -- A module runtime error occurred.
5/4/2019 5:31:47 PM  warn: edgelet_utils::logging -- Could not start module edgeAgent
5/4/2019 5:31:47 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:31:47 PM  info: edgelet_core::watchdog -- Checking edge runtime status
5/4/2019 5:31:47 PM  warn: edgelet_utils::logging --    caused by: hcsshim::OpenComputeSystem                           
                     77b8740d35cd76ee94398b83eb91fab9e19a6d9f5314ad2bba500023e103272d: The operation could not be
                     started because a required feature is not installed.
5/4/2019 5:31:47 PM  warn: edgelet_utils::logging --    caused by: Could not start module edgeAgent                     
5/4/2019 5:31:47 PM  info: edgelet_docker::runtime -- Starting module edgeAgent...
5/4/2019 5:31:47 PM  info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...

## Additional Information
I am also getting the error in Docker:
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by StefanSchoof** [comment]
Have you installed the hyperv feature? The installer does not check this until 1.0.7, see #1068

**Comment by firstcrazydeveloper** [comment]
Yes, Hyper-V feature is already installed.

**Comment by veyalla** [comment]
What you actually need is the "Containers" feature. The installer script in release 1.0.7, as mentioned, will check for this and it will be released very soon!

**Comment by ancaantochi** [comment]
Hi @firstcrazydeveloper ,

1.0.7 was released, please use this version and let us know if you still have this issue.

**Comment by firstcrazydeveloper** [comment]
Sure, I will update and let you know

**Comment by myagley** [comment]
I am going to close this issue as it should be resolved with the 1.0.7 release.
