### ISSUE TITLE
Connecting to multiple docker networks

### ISSUE THREAD

**Issue by mma-mm** [Azure/iotedge#1174]
Hi,

I'd like to connect an edge module to multiple networks. Is there a way to achieve this with iotedge? Easiest for me would be a configuration, that adds the additional network(s) to the container after creation, but before start. 

## Expected Behavior
I can add multiple networks in container configuration or somewhere else at deployment

## Current Behavior
I can only add a single network.

### Device (Host) Operating System
Linux Operating System

### Architecture
amd64 and arm32v7

### Container Operating System
Linux containers

**Comment by myagley** [comment]
Thank you for the issue report. We understand the scenario and think it is a good enhancement.

However, multiple networks isn't currently supported. We have an idea on how to add it but this work will need to be prioritized against other feature requests. I don't have a specific date when this can be expected.

**Comment by veyalla** [comment]
Please file or vote for feature enhancements at https://feedback.azure.com/forums/907045-azure-iot-edge

**Comment by skyrimax** [comment]
Hi, I have run into a situation where I need this feature as well. Has it been implemented? If not, does anyone have the URL to the suggestion so I can upvote it?
