### ISSUE TITLE
High number of "Successful twin reads from devices"

### ISSUE THREAD

**Issue by Peter-B-** [Azure/iotedge#1176]
## Summary

I see a large number of "Successful twin reads from devices" since May, 2nd. Do you have any idea how to find the source of the issue?

## Scenario

I have an IoT Hub S1 with 2 hub units. I have 3 IoT Edge devices deployed on Windows 10 running simulations.  

Starting on May, 2nd midnight UTC, I see a high number of "Successful twin reads from devices" (up to 300k per hour), that have not been there the days before.

You can see the Metric in the chart below:

![successfu twin reads from device](https://user-images.githubusercontent.com/6525889/57226821-255ab500-7010-11e9-8378-f8150894eb58.png)

It seems that each of the 3 IoT Edge devices is requesting the twin information, since stopping one reduces the load, but does not remove it.

I am quite sure that our user code does not cause this issue and since May, 1st was a public holiday here, I am certain that we did not deploy any new software at this time.

Is there a way to find which module is causing the issue?

### Device (Host) Operating System
Win 10, 1809

### Architecture
X64

### Container Operating System
Windows containers

#### iotedged
1.0.6.1

#### Edge Agent
1.0.6

#### Edge Hub
1.0.6

#### Docker
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false

## Logs
I could not find anything interesting in the logs. Please let me know what logs can be helpful to understand the problem.

**Comment by ancaantochi** [comment]
Hi @Peter-B,

It looks like you are hitting a known issue that was fixed in 1.0.7 in edgeHub and edgeAgent. Please update both images.

For edgeHub after you set the image to 1.0.7 you have to turn on using version 2 for TwinManager, that means you have to add an environment variable to the deployment with 
name:  `TwinManagerVersion` 
value  `v2`

**Comment by Peter-B-** [comment]
Hi @ancaantochi,

Thanks for your prompt reply. We managed to update two of our devices to 1.0.7. The issue is resolved.

I will try to update my third device. 

Greetings 
Peter
