### ISSUE TITLE
Azure IoT hub blocked for two days, will not let me change to a paid tier

### ISSUE THREAD

**Issue by vbadri** [Azure/iotedge#118]
I have a free tier subscription to Azure IoT hub with only two edge devices connected to it, one of them mostly off.  On Aug 1, it looks like my hub recorded a slew of messages--within 45 minutes (5 to 5:45 pm PST), 25K messages were recorded by the hub. A few related issues.

1. I'm not sure what these messages were. I'll add message storage for the future, but wondering if there's a way to debug this. I certainly didnt' have anything in the code that would generate messages at that rate, but I did have an error in the config yaml file, and that may have caused spurious messages. 

2. Ever since then, I haven't been able to use the IoT hub. I get a "message count exceeded" error. That made sense till around 5 pm PST on Aug 2 (same day UTC), but not sure why it is still blockign me after that.

3. I tried to change my F1 to a basic tier to basic, but that wasn't allowed because I am apparently "not allowed to downgrade"

Any help with any of these?

I guess the question that relates to the github code is #1.

**Comment by MPapst** [comment]
According to the Documentation it is not possible to change from the free tier to a paid tier. 
I also tried that some months ago and needed to delete and recreate the hub.

**Comment by mrohera** [comment]
For your first problem, there are no messages generated by the Edge Hub, it just does not happen. Everything is initiated by the clients that dispatch messages to the Edge Hub.

- One easy check is that your default route is to set every message to go up to the cloud. This you should be able to see in the routes section of the portal or in the Edge Hub logs. Navigate to your Edge device in the portal --> Click "Set Modules" --> Hit 'Next'. These should show you the configured routes. Anything sent to "INTO $upstream" will hit the cloud. Perhaps this is why your messages went up to the cloud. You can read more about routes here: [https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#declare-routes](https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#declare-routes)

- What was the error in the config.yaml?

**Comment by mrohera** [comment]
Regarding the items 2 and 3

Here is the gist of why you see this problem.
The free tier has a daily limit of 8000 messages/day with a message size limit of 0.5KB. A user cannot upgrade from Free tier to other paid tiers. The daily cycle starts at midnight and your quota of 8K messages replenishes daily. You can also view the number of messages in the Overview tab in the Azure Portal.

More about pricing can be see here: [https://azure.microsoft.com/en-us/pricing/details/iot-hub/](https://azure.microsoft.com/en-us/pricing/details/iot-hub/). The FAQ sections answers the rest of your questions.

**Comment by vbadri** [comment]
@mrohera, On your comment regarding IoT hub not generating messages by itself, I get that. I just wasn't sure what in the edge device was generating those messages since there was no programmed message upload. I do have upstream messages piped to the cloud, but no actual devices were connected to the gateway so there shouldn't have been anything. Anyway, will keep digging.

**Comment by myagley** [comment]
Is there any up date here?

**Comment by vbadri** [comment]
@myagley, MSFT support did confirm hub subscriptions can NOT be chanaged from free to paid. So I just ended up creatign another hub.  Sicne that was the intent of this issue, I'm closing it with thanks to MSFT support.

**Comment by jtmoderate876** [comment]
It is unfortunate that I can't just upgrade my free tier to a paid tier.
Why not?

**Comment by ash2017** [comment]
IoT Hub does not allow one to upgrade from Free tier to Basic or Standard Tier per design and they have different message size limits. To compare IoT Hub tiers, please see [this doc](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-scaling)

**Comment by jason-e-gross** [comment]
@mrohera 
That's not true.    The edge agent and hub agent will transmit self-health/status messages that you have no control over, and are absolutely not part of your code -- and it still WILL count against your message count.

I created an IOT Edge device just today, that doesn't do any communication (just writes hello world to the console), and removed $upstream reference and the temp simulator - and within an hour of it running, there's 17 messages on my count list.

All the edge agent/hub module messaging for keeping tabs on the health of the docker images/containers, etc - you definitely "pay" for.

**Comment by mrohera** [comment]
@veyalla adding you to address @jason-e-gross 's comment. is there some guidance that can be given to customers for what to expect about status and health messages.

**Comment by veyalla** [comment]
@ebertrams and @varunpuranik have been looking into this.
