### ISSUE TITLE
Update on Windows to 1.0.7 fails with "IoT Edge is installed in an invalid location"

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/iotedge#1185]
## Expected Behavior
Update an iotedge 1.0.6 install to 1.0.7 works with the command form the documentation: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#update-an-existing-installation

## Current Behavior
```powershell
PS > . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Update-IoTEdge

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Initialize-IoTEdge, Insta...

IoT Edge is installed in an invalid location. To reinstall, first remove the existing installation using "Uninstall-IoTEdge".
```

## Steps to Reproduce

1. Install iotedge 1.0.6 (do not know how this can done now after 1.0.7 is installed)
2. Run `. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Update-IoTEdge`

### Device (Host) Operating System
Windows Server 2019 1809

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
```
docker -H npipe:////./pipe/iotedge_moby_engine version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        142dfcedca
 Built:             02/28/2019 06:33:17
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.11.4
  Git commit:       5ec3138
  Built:            Thu Jan 24 17:16:18 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Logs

N/A

## Additional Information

N/A

**Comment by myagley** [comment]
Does running `Uninstall-IoTEdge` and then reinstalling solve the issue? Note that the installation mechanism was changed between 1.0.6 and 1.0.7 to use a cab file. There may be a one time uninstall/reinstall required for this transition. This will not be required going forward.

**Comment by StefanSchoof** [comment]
Because I have not seen any note in the documentation and/or the azure blog, that a update to 1.0.7 needs are reinstall, I had not try to uninstall. Now I did an Uninstall and Deploy/Initialize and the agent is running.

I think you should add remark to https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#update-an-existing-installation, that an update to 1.0.7 needs an Uninstall/reinstall.

**Comment by lt72** [comment]
Thank you for your feedback, closing the issue as it is resolved.
