### ISSUE TITLE
Recommended Integration Testing Strategy?

### ISSUE THREAD

**Issue by jackt-moran** [Azure/iotedge#1189]
Hi,
Is there a recommended way to perform integration tests on IoT Edge deployments? I know I could use docker-compose or similar tools to do this, but I was hoping to get as close to staging/production environments as possible. 

As a part of this question, I am also wondering if there is any way to guarantee module initialization order with the deployment templates? For my use case, guaranteeing module initialization order would be useful for both integration testing and live environments. I haven't found any ways to guarantee order directly through the Docker Engine API (I would've expected this to have been asked already so maybe I'm missing something).

**Comment by nmiodice** [comment]
@varunpuranik  We have written some testing code that will block on IoT deployments to be verified active and running prior to invoking tests

https://github.com/microsoft/detoxed-py

**Comment by lt72** [comment]
Issue seems resolved, closing now. Please re-open as needed.
