### ISSUE TITLE
HTTP Post to IoT Edge Device (Gateway)

### ISSUE THREAD

**Issue by the-nate-is-late** [Azure/iotedge#1202]
## Expected Behavior

Querying endpoint on deployed module does returns the same results as querying a local module.

## Current Behavior

I use ```curl --header "Content-Type: application/json" --request POST --data '{"inputName": "input1","data":"hello world"}' http://localhost:53000/api/v1/messages``` to submit and remotely trigger data in a module.

I tried to use ```curl --header "Content-Type: application/json" --request POST --data '{"inputName": "input1","data":"hello world"}' http://deployedgatewaymodule/api/v1/messages```, but get rejected with a 401.

## Steps to Reproduce

1. Create module locally.
2. Use ```curl --header "Content-Type: application/json" --request POST --data '{"inputName": "input1","data":"hello world"}' http://localhost:53000/api/v1/messages``` to push data to module.
3. Push module to remote device.
4. Use ```curl --header "Content-Type: application/json" --request POST --data '{"inputName": "input1","data":"hello world"}' http://{device_name}/api/v1/messages```
5. Get rejected with a 401.

## Context (Environment)
Using a Raspberry Pi on the end device. Can see the messages getting rejected by edgeHub.

### Device (Host) Operating System

Rasbian-stretch

### Architecture

arm32

### Container Operating System

```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

#### iotedged

1.0.6.1

#### Edge Agent

1.0

#### Edge Hub

1.0

#### Docker

```
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 17:16:17 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       8ecd530
  Built:            Mon Feb 11 20:31:38 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.2
  GitCommit:        9754871865f7fe2f4e74d43e2fc7ccd237edcbce
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        96ec2177ae841256168fcf76954f7177af9446eb
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Logs

```
iotedge logs edgeHub
2019-05-10 20:03:24.042 +00:00 [INF] - Request starting HTTP/1.1 POST https://{device_name}/api/v1/messages/ application/json; charset=utf-8 50
2019-05-10 20:03:24.045 +00:00 [INF] - Request finished in 2.8272ms 401 text/html
2019-05-10 20:03:24.046 +00:00 [INF] - Connection id ""0HLMLG1DLFBS8"", Request id ""0HLMLG1DLFBS8:00000001"": the application completed without reading the entire request body.

```

## Additional Information

This may be by design but, if so, I'm still left wondering if there's a way to push data to a gateway using HTTP protocols without using the full SDK. I have gone through https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway and am able to submit requests using DeviceClient, but would like to use HttpClient (or similar) to send the requests instead.

**Comment by myagley** [comment]
The Edge Hub does not support sending messages over HTTP. It only supports AMQP and MQTT for devices/module messages.
