### ISSUE TITLE
Add C2D message Support for IoTEdge Modules

### ISSUE THREAD

**Issue by martinrbowman** [Azure/iotedge#1205]
I have a need to use C2D messages with IoTEdge Modules on a project migrating from Iotdevice to Iotedge

Request this be added to a future release, for users migrating from iotdevice to iotedge.

**Comment by myagley** [comment]
This is something that we are looking at but I don't have a definite timeline at this moment.

**Comment by murali513** [comment]
@martinrbowman or @yophilav  C2D message support feature added or not?

**Comment by veyalla** [comment]
Not yet supported.

Please file or vote for feature enhancements at https://feedback.azure.com/forums/907045-azure-iot-edge
