### ISSUE TITLE
Direct DEVICE methods disappear after a while

### ISSUE THREAD

**Issue by njbuch** [Azure/iotedge#1206]
Having implemented simple direct methods has been working for months, slight unstably with 1.0.6, but no improvements into 1.0.7.21905529.

When trying to active the method, the response is simply (VSCode) "[DirectMethod] Failed to invoke Direct Method: Not found" most of the times. Sometimes it heals itself by some minutes, and retrying might work.

## Expected Behavior

The direct methods should always return meaningfully when the device is online.

## Current Behavior

The method is not found.

## Steps to Reproduce

1. Deploy a direct method in a module written in C#
2. Hack around, wait and try.
3.
4.

### Device (Host) Operating System

Raspberry Pi 3+ Raspbian GNU/Linux 9.9 (stretch) Release:  9.9

### Architecture

arm32

### Container Operating System

Linux docker

### Runtime Versions
Not sure

#### iotedged

1.0.7.21905529

#### Edge Agent

Same

#### Edge Hub

Same

#### Docker

3.0.2
## Additional Information

It seems that in the period where the direct methods cannot be found, there is some logs stating some time-out challenges:
```
2019-05-12 17:52:24.319 +00:00 [INF] - Starting compaction of store deploymentConfig
2019-05-12 18:04:47.928 +00:00 [INF] - Starting periodic operation refresh twin config...
2019-05-12 18:13:47.264 +00:00 [WRN] - Updating reported properties failed with error The operation has timed out. type Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
2019-05-12 18:18:52.737 +00:00 [WRN] - Updating reported properties failed with error The operation has timed out. type Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
2019-05-12 18:23:57.867 +00:00 [WRN] - Updating reported properties failed with error The operation has timed out. type Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException
2019-05-12 18:24:03.129 +00:00 [INF] - Updated reported properties
2019-05-12 18:25:36.905 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 29 and reported properties version 76.
2019-05-12 18:25:36.909 +00:00 [INF] - Successfully completed periodic operation refresh twin config
```

**Comment by myagley** [comment]
Can you run `iotedge check` and post the results? This will give some indication of the connectivity status.

**Comment by njbuch** [comment]
```
pi@raspberrypi:~sudo iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
√ config.yaml has correct URIs for daemon mgmt endpoint
√ latest security daemon
√ host time is close to real time
√ container time is close to host time
√ DNS server
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry
√ production readiness: container engine
‼ production readiness: logs policy
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
√ host can connect to and perform TLS handshake with IoT Hub MQTT port
√ container on the default network can connect to IoT Hub AMQP port
√ container on the default network can connect to IoT Hub HTTPS port
√ container on the default network can connect to IoT Hub MQTT port
√ container on the IoT Edge module network can connect to IoT Hub AMQP port
√ container on the IoT Edge module network can connect to IoT Hub HTTPS port
√ container on the IoT Edge module network can connect to IoT Hub MQTT port
√ Edge Hub can bind to ports on host

One or more checks raised warnings.
pi@raspberrypi:~ $ timedatectl
      Local time: man 2019-05-13 18:51:33 CEST
  Universal time: man 2019-05-13 16:51:33 UTC
        RTC time: n/a
       Time zone: Europe/Copenhagen (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

```

**Comment by njbuch** [comment]
Restarting the module with the code of the direct method on the device, makes the method callable again.

**Comment by njbuch** [comment]
> Restarting the module with the code of the direct method on the device, makes the method callable again.

Just to clarify: This comment is not considered a solution. Since oiringally posting, I have had several device under test, and this problem seems to re-appear every once in a while, and it cribbles the setup.

**Comment by myagley** [comment]
What SDK are you using? C#, C, etc.

If C#, what version?

**Comment by njbuch** [comment]
I am using 1.0.7 and have not upgraded the device since that release. But I see that you have been busy, would you recommend upgrading to solve this challenge?

**Comment by myagley** [comment]
The root cause of the connectivity issues are in the C# SDK (which the IoT Edge runtime uses internally). If your module is using the C# SDK, it will also need to be updated to make the end to end flow more stable. The latest C# SDK is version `1.20.1`. It is recommended to upgrade to this version.

**Comment by njbuch** [comment]
I did a dotnet restore in the module folder, rebuilt and pushed the images to the device, and also followed  [this](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge) to update the device. 

It seems that the C# SDK is the version you mention, but it seems from the edgeAgent/edgeHub logs that the version 1.0.7.21905529 stays - despite removing images and stuff.. is the 1.0.7.1 update important?

Continuing the test...

**Comment by arsing** [comment]
Please reopen if the issue is not resolved.

**Comment by njbuch** [comment]
This issue is still a (now huge) problem. Now with Version - 1.0.8.23694809 of EdgeAgent and Microsoft.Azure.Devices.Client --version 1.21.0.

**Comment by njbuch** [comment]
> The root cause of the connectivity issues are in the C# SDK (which the IoT Edge runtime uses internally).

Is there a way to debug connectivity issues, and assist the module in recovering?

**Comment by njbuch** [comment]
Just to provide possibly important info:
```
CMD> dotnet list package
Project 'DeviceCore' has the following package references
   [netcoreapp2.1]: 
   Top-level Package                                                 Requested   Resolved
   > Microsoft.Azure.Devices.Client                                  1.21.0      1.21.0
   > Microsoft.Extensions.Configuration                              2.1.1       2.1.1
   > Microsoft.Extensions.Configuration.Abstractions                 2.1.1       2.1.1
   > Microsoft.Extensions.Configuration.Binder                       2.1.1       2.1.1
   > Microsoft.Extensions.Configuration.EnvironmentVariables         2.1.1       2.1.1
   > Microsoft.Extensions.Configuration.FileExtensions               2.1.1       2.1.1
   > Microsoft.Extensions.Configuration.Json                         2.0.0       2.0.0
   > Microsoft.NETCore.App                                     (A)   [2.1.0, )   2.1.0
   > System.Runtime.Loader                                           4.3.0       4.3.0

(A) : Auto-referenced package.
```

**Comment by veyalla** [comment]
Hi @njbuch - please use the issue template (presented when creating an issue) for logs and information we'll need to help debug this.

**Comment by njbuch** [comment]
> Hi @njbuch - please use the issue template (presented when creating an issue) for logs and information we'll need to help debug this.

Created new issue here: [link](https://github.com/Azure/iotedge/issues/1550)
