### ISSUE TITLE
Upload multiple large videos to Azure storage using edge module parallelly

### ISSUE THREAD

**Issue by sarweshs** [Azure/iotedge#1215]
Hi, @arduppal , @mbialecka, and @sudhirap

Hi,Can anyone tell me If the auto-tiering is multithreaded or single threaded?
We are getting multiple files from multiple robots in the common Edge Gateway Local Blob Storage. I see there is an option for setting the upload type as LIFO or FIFO, does this mean Its single threaded/Sequential?
If yes then the common gateway will be a single point of blockage as It would be receiving the files at a faster rate.
If we use a new container in blob for each upload, Will that trigger auto-tiering for each container? (Kind of multithreading?)
Let me know If the question is not clear.

## Expected Behavior
When multiple robots/devices send files to the local BLOB storage in the edge gateway, the files should be uploaded parallelly and not one by one. 
As per the documentation, We see a setting as LIFO/FIFO which makes me feel is its single threaded.

## Current Behavior
We are seeing some kind of time difference when multiple files were uploaded in local blob of edge gateway. So It looks like its single threaded.

**I could not find any document as well whether Its multi threaded or single threaded. This is something which should be available in document. If its available in any online document, would be great If you can mention the link in the response.**

**Comment by mbialecka** [comment]
Tiering is multithreaded, with current preview version using up to 4 threads (the actual number of threads used is managed by .NET). In the next release this number will be configurable and the default value is not decided yet. The upload type aka backlog policy main purpose is disconnected scenario or more generally a scenario where network bandwidth that doesn't allow for tiering in at least the same pace as writing blobs in the module.

Multi-threaded tiering works across all containers so increasing number of containers doesn't increase number of worker threads.

We will update our docs to include threading information with the next release or sooner. Thanks for the feedback!

**Comment by sarweshs** [comment]
Hi @arduppal ,@mbialecka, and @sudhirap,
How can we know whether the file was fully uploaded on cloud. The scenario is something like this

-  We are uploading a file (Approx 500MB) We are utilizing the new Blob Storage on IoT Edge feature.  The problem we’re trying to solve is auto-pruning of the files from the gateway **after they’ve been uploaded to the cloud**.  The auto-expiring  feature seems to only be time-based, so when the TTL has expired the file is deleted, even if the file has not uploaded  to the cloud. 

-  We’re looking for a way to ensure that files are only deleted from the gateway AFTER they’ve been successfully uploaded to the cloud. So kind of a solution that the TTL should be triggered when the file is fully uploaded to cloud.

- If this is not possible, Is there anyway to know (May be by event or something) that the file which was sent to blob storage on edge gateway is fully uploaded to Cloud?

**Comment by lt72** [comment]
@sarweshs sorry for the delayed answer. Do you still need help?
