### ISSUE TITLE
Get runtime status through java service sdk

### ISSUE THREAD

**Issue by monilsarkar** [Azure/iotedge#1227]
Hi,

I was trying to get the runtime status of an iot edge device through reading module twins using java service sdk.

Does the java service sdk support api's to get the module twin of an iot edge device.
I looked into module twins, but was not able to fins the relevant api to get the module twin for a device through the java sdk.

Is there any other way to determine the run time status of an iot edge device other than through the module twins.

Regards
Monil

**Comment by varunpuranik** [comment]
@monilsarkar - This seems like a question for the Java SDK. Can you please refile the question in the Java SDK repo - https://github.com/Azure/azure-iot-sdk-java
@prmathur-microsoft
