### ISSUE TITLE
Iot Edge runtime not installing on Windows 10 enterprise 

### ISSUE THREAD

**Issue by saikovvuri** [Azure/iotedge#1228]
Attempting to install iot edge runtiome on Windows 64 following documentation from 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows ,
## Expected Behavior

Iot Edge Runtime should be successfully installed
## Current Behavior

giving a compatibility issue with container host

PS C:\WINDOWS\system32> . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
>> Deploy-IotEdge

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Initialize-IoTEdge, Insta...
The container host is on unsupported build version 18362.
Please use a container host running one of the following build versions for running Windows containers:
17763

The prerequisites for installation of the IoT Edge Security daemon are not met. Please fix all known issues before rerunning this script.

## Steps to Reproduce

1. 
2.
3.
4.

### Device (Host) Operating System

Version	10.0.18362 Build 18362

### Architecture

X64
### Container Operating System

Windows Containers
#### iotedged

1.0.7
#### Docker

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

## Additional Information

I have ensure from windows features that both Hyper-V and containers support is enabled

**Comment by myagley** [comment]
Hi Sai,

IoT Edge is only supported on Windows 10 RS5 (build 17763). It looks like your system is running Windows 10 1903, which isn't supported. Here is the list of supported platforms for reference: https://docs.microsoft.com/en-us/azure/iot-edge/support#tier-1

**Comment by saikovvuri** [comment]
thanks Mike,  I overlooked the fact that my system got updated to Windows 10, version 1903  yesterday. 

Closing the issue now

**Comment by veyalla** [comment]
Do you have feedback on the message that was output that would have made it clearer? 

More and more folks are going to run into this as 1903 is widely rolled out.

**Comment by saikovvuri** [comment]
Hello Venkat, I would say the message is crisp enough.  Since it was working a few days back with 1.0.6 on my computer, i assumed something was wrong with 1.0.7 bits completely overlooking the fact that just last evening windows updated to version 1903. 

Hope this helps

**Comment by pkoronawa** [comment]
But where can we download the old 17763 version?

**Comment by davidzwa** [comment]
Interested in any update. It's weird that something like this is limited by a newer version of Windows, when the whole idea behind containerization is that it is not.

Please provide us with insight

**Comment by pkoronawa** [comment]
Windows Server 2019 from the [Evaluation Center](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019?filetype=ISO) is still on the supported 17763 build and that is what I have been using. See related issue #1897

**Comment by davidzwa** [comment]
Went for a Raspberry Pi and for an Azure VM. Still, the solution to assume an image running docker containers is quite suboptimal.

**Comment by davidzwa** [comment]
@saikovvuri I have found it to work on build 18363 albeit with a different approach, which was in a closed issue:
https://github.com/Azure/iotedge/issues/144

**Comment by ede0m** [comment]
When does IoTEdge plan to support running windows containers on the newer, stable windows host builds (v1903, 1909)?

**Comment by davidzwa** [comment]
+1 on the roadmap

**Comment by rajashekar2012** [comment]
Is IoT edge supported in newer build versions of windows 10 (v1903, 1909) now ?

**Comment by joostruis** [comment]
> Is IoT edge supported in newer build versions of windows 10 (v1903, 1909) now ?
No. Sadly not.
Situation would be that you have to ask customers to "downgrade" their machines to be able to deploy your products. Ridiculous. Yet we still have no idea when this is going to be supported...

**Comment by veyalla** [comment]
There are no plans to support any other Windows versions. The future direction of Windows support is shared here: https://aka.ms/winiot-low
