### ISSUE TITLE
IoT Edge Expected Behavior when DPS enrollment is disabled

### ISSUE THREAD

**Issue by saikovvuri** [Azure/iotedge#1235]
Reaching out to check what is the expected behavior of iotedge when the DPS enrollment is disabled (temporarily)
## Current Behavior

IoTEdge uses DPS with TPM attestation.  While iotedge is running, if DPS enrollment is disabled from the portal, as expected iotedge will run interuppted with no issues. 

However if the iotedge is restarted,  the observed behavior is iotedge will start the DPS registration but the operation wont succeed so it will restore the credentials from the backup. and continue.

the questions is whether this is as per design or should the iotedge should exit with provisioning error since DPS device enrollment has been disabled, may be the Ops team has concluded that this edge device has been compromised and does not want the edge device to re-provision

## Steps to Reproduce

1.
2.
3.
4.

### Device (Host) Operating System

Windows 10 Enterprise
### Architecture

x64
### Container Operating System

Windows Containers
#### iotedged

1.0.6
#### Edge Agent

1.0.6
#### Edge Hub

1.0.6
## Logs

5/20/2019 10:06:16 PM info: dps::registration -- Starting DPS registration with scope_id "0ne0005B494", registration_id
                      "edgehub12189"
5/20/2019 10:06:19 PM warn: edgelet_utils::logging --   caused by: Could not get operation status
5/20/2019 10:06:19 PM warn: edgelet_utils::logging -- Could not provision device
5/20/2019 10:06:19 PM info: provisioning::provisioning -- Restoring device credentials from backup
5/20/2019 10:06:19 PM warn: edgelet_utils::logging --   caused by: HTTP request failed: [404 Not Found]
5/20/2019 10:06:19 PM info: iotedged -- Finished provisioning edge device.

**Comment by saikovvuri** [comment]
Please mark this as a "Question"

**Comment by myagley** [comment]
I think this is the correct behavior, although you could make the argument that it shouldn't fall back to the cached provisioning result. In any case, if you want to disable a rogue device, you will need to do this in the IoT Hub, not DPS. I don't think DPS will currently remove a disabled device from the IoT Hub it was provisioned to.

**Comment by saikovvuri** [comment]
@myagley thanks for the response.  Yes currently DPS only sends a provisioning request to IoT hub during device registration and does not communicate the opposite to IoT hub, when the registration is removed in DPS.
So what should be the alternative to "shouldn't fall back to the cached provisioning result" when DPS does not return a valid response

**Comment by lt72** [comment]
Hi @saikovvuri, sorry for the late answer and thank you for your patience. I assume you do not need assistance any longer. Please re-open this issue if that is not the case and we will answer promptly.
