### ISSUE TITLE
DPS using in-built TPM on Aaeon Gw running Win IoT Core device

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1237]
Hi,

I am following below link to do DPS using in-built TPM key on Aaeon GW.
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows

I am able to retrieve Registration Id and Endorsement key using Windows Device Portal.
Following below steps-

Get Device Identity Information
In this part, we harvest the information that identifies the device to the Azure device provisioning service.

Get Limpet.exe (see the Installing Pre-built Binaries page).

Connect to the device and run the following commands:

 cd c:\windows\system32
 limpet.exe -azuredps -enrollmentinfo
 
The output should look like-

 Provisioning information

     Registration Id:
     <registration_id>

     Endorsement Key:
     <endoresement_key> 

I have installed Windows RS5 image and version is 10.0.17763.107.
I am able to do DPS on same gateway using Ubuntu.

There is no update is happening Windows IoT Core config.yaml file.

Can you please let me know the steps on Windows IoT Core DPS using TPM.

**Comment by veyalla** [comment]
@jcoliz Could someone from your team help with this?

**Comment by jcoliz** [comment]
That's my pal @gmileka !

**Comment by gmileka** [comment]
Hi pratson20,

After you got the registration id and the endorsement key,
1. Did you create an individual enrollment in DPS?
2. Did you store the scope id in the config.yaml file?
3. How did you determine that it did not work?

thanks,
george

**Comment by pratson20** [comment]
Hi @gmileka,

Thanks for your reply.
There is no issue happening if doing DPS for Ubuntu OS. I have passed scope id and registration id manually and it worked.

But issue is happening in IoT Core if connecting to IoT Core GW remotely-

1. Created individual enrolment in DPS.
2. To Store scope id in config.yaml file- Followed below steps but results are not as expected-
and followed below URL to proceed with DPS on IoT Core-
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#option-2-install-and-automatically-provision


Running this command-

[192.168.1.106]: PS C:\Data\Users\administrator\Documents> **. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
>> Initialize-IoTEdge -Dps**

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Initialize-IoTEdge, Insta...

```
cmdlet Initialize-IoTEdge at command pipeline position 1
Supply values for the following parameters:
```
ScopeId: XXXXXXXXXXXXXXXX
RegistrationId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
The container host is on supported build version 17763.
Generating config.yaml...
Configured device for DPS provisioning.
Configured device with hostname 'minwinpc'.
Configured ProgramData directory.
Configured device with Moby Engine URL 'npipe://./pipe/iotedge_moby_engine' and network 'nat'.
Updated system PATH.
Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start service iotedge
on computer '.'.
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

[192.168.1.106]: PS C:\Data\Users\administrator\Documents> Get-Service iotedge

Status   Name               DisplayName
------   ----               -----------
Stopped  iotedge            Azure IoT Edge Daemon


But, i have observed using this way values are not getting save in config.yaml.
As per my understanding, need to pass the value through power shell terminal if connecting device remotely in PROD.


Regards,
Prateek

**Comment by veyalla** [comment]
This is a regression bug. We'll have a fix out in 1.0.7.1 release planned for this week.

**Comment by pratson20** [comment]
Thanks @veyalla for update

**Comment by veyalla** [comment]
https://github.com/Azure/azure-iotedge/releases/tag/1.0.7.1 is out which should fix this issue. 

Please [update the daemon](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge#windows-devices)  and the runtime containers. Let us know if this fixes the issue.

**Comment by pratson20** [comment]
Thanks @veyalla. Issue is fixed with latest iotedge version.
