### ISSUE TITLE
How can i deploy Squid Http Proxy server on IoT egde gateway?

### ISSUE THREAD

**Issue by AmitBarthwal** [Azure/iotedge#1244]
## Expected Behavior

Need to implement Squid proxy http server on IoT edge gateway.
Do we have any docker image, so that i can deploy as a module.
### Device (Host) Operating System

Ubuntu 18.04
### Architecture

amd64
### Container Operating System

Linux containers
#### iotedged

iotedge 1.0.6.1 

#### Docker

Docker version 3.0.3

**Comment by myagley** [comment]
Hello. We don't provide an out of the box squid container image, but it looks databog has one on Docker Hub: https://hub.docker.com/r/datadog/squid

You may want to check this out.

**Comment by AmitBarthwal** [comment]
Hi myagley,
Thanks for response.
About datadog/squid, I didn't find any info, how we can make this to sit on the edge runtime environment with other modules, and leverage the properties to set for proxy the requests.
Do you have any idea on that?

**Comment by myagley** [comment]
This image should work with Linux containers. What is the issue that you are seeing?

This image can be deployed to IoT Edge but you will need to do the work to get the proxy configured. This section talks about how to configure: https://hub.docker.com/r/datadog/squid#configuration

You basically have three options to get this configured:
1. If your configuration is static, you can use this image as a base layer and add your config in a layer
2. You can use a custom [entrypoint](https://docs.docker.com/engine/reference/builder/#entrypoint) to dynamically generate the config when the container is started
3. Configure the proxy on the host and mount the config file into the container. This is what the configuration section for this image on Docker Hub mentions.

**Comment by AmitBarthwal** [comment]
Thanks Myagley..
I have deployed the squid server module on IoT edge, seems good to go to next step.
I was looking to configure Squid proxy server, as you suggested (https://hub.docker.com/r/datadog/squid#configuration), but seems very less information to work around.

On your first point, if configuration is static...Could you please share any sample settings ?
Second point, do i need to create a script for dynamically generating config file and mounting the config file into the container.

As i didn't find any good documents for complete configuration of the squid proxy server, if you can provide some, it will be helpful..

**Comment by myagley** [comment]
I've never used squid personally so I don't think I can provide any detailed help on configuring it. Perhaps the examples section of the squid documentation would be a good place to start: https://wiki.squid-cache.org/ConfigExamples

**Comment by AmitBarthwal** [comment]
Thanks Myagley..

I have configured the Squid server and mount the config file with a little work around.
I have added the squid server in the iot-edge by pulling the docker image and pushing to gateway using deployment manifest.
Squid location below..
https://hub.docker.com/r/datadog/squid#configuration

I have used squid.conf file which i mounted, placed on host location, to this /etc/squid/squid.conf.
Here is my deployment manifest squid create option snap below and checked its working fine

 "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "3128/tcp": [
                      {
                        "HostPort": "3128"
                      }
                    ]
                  },
                  "Binds": [
                    "/path/to/host/location/squid.conf:/etc/squid/squid.conf"
                  ]
                },
                "Mounts": [
                  {
                    "Name": "configurationMount",
                    "Source": "/path/to/host/location/squid.conf",
                    "Destination": "/etc/squid/squid.conf",
                    "Type": "bind",
                    "Mode": "",
                    "RW": true,
                    "Propagation": "rprivate"
                  }
                ]
              }

I just wanted to know, how can i forward the request coming from the user to the squid proxy server to the azure cloud. 
Any leads will be helpful.

[squid.txt](https://github.com/Azure/iotedge/files/3240207/squid.txt)

**Comment by AmitBarthwal** [comment]
Thanks..Deployed the squid server
