### ISSUE TITLE
Module twin $metadata $lastUpdated property is updated for every desired property

### ISSUE THREAD

**Issue by AMCN41R** [Azure/iotedge#1246]
## Expected Behavior
The module twin provides metadata for desired properties including a `$lastUpdated` property which should be updated when the corresponding desired property is updated.

## Current Behavior
Updating any property results in the `$lastUpdated` property being updated for EVERY existing desired property, not just the one that was actually updated.

## Steps to Reproduce
1. Create 2 desired properties on a module in the Azure portal and click save.
2. Update the first property to a new value and click save
3. Observe the desired property metadata

Expected:
`$lastUpdated` for the first property should be updated with a new timestamp, while the second property metadata does not change.

Actual:
Both values are updated to the same timestamp.

## Additional Information
This also happens from the C# SDK `RegistryManager` from `Microsoft.Azure.Devices` (v1.17.3)

Example:
```csharp
var registryClient = RegistryManager.CreateFromConnectionString("connection-string");
var twin = await registryClient.GetTwinAsync(deviceId, moduleId);
twin.Properties.Desired[key] = value;
await registryClient.UpdateTwinAsync(deviceId, moduleId, twin, twin.ETag);
```

**Comment by varunpuranik** [comment]
This seems like an IoTHub issue. @simonporter - can you please comment on this?

**Comment by isyama** [comment]
When you update desired properties (or tags), please call UpdateTwin by passing properties that you want to update only; otherwise, we will update all properties passed in the call. For example,

var registryClient = RegistryManager.CreateFromConnectionString("connection-string");
var twin = await registryClient.GetTwinAsync(deviceId, moduleId);

var twinToUpdate = new Twin();
twinToUpdate.DeviceId = twin.DeviceId;
twinToUpdate.ModuleId = twin.ModuleId;
twinToUpdate.Properties.Desired[key] = value;
await registryClient.UpdateTwinAsync(deviceId, moduleId, twinToUpdate, twin.ETag);

**Comment by AMCN41R** [comment]
Ok, thanks. I've tested this and works as expected.

To get the same result in the portal, I have to delete all desired properties expected the ones I want to update, then click save.

Are either of these processes documented anywhere?

**Comment by isyama** [comment]
Please see "Partially update device twin." of the link below.

https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#back-end-operations

**Comment by AMCN41R** [comment]
Thanks @isyama. I'd seen those, and just wondered if there were any specific implementation examples (C# for instance). If not, it would be great to see those, but I'm happy to close the ticket.

**Comment by isyama** [comment]
Thanks for the feedback, @AMCN41R. I couldn't find the language specific doc you are looking for. @rezasherafat, please point Alex to such a doc if you have one. Thanks again.
