### ISSUE TITLE
The container host is on unsupported build version 18362.

### ISSUE THREAD

**Issue by lanatmwan** [Azure/iotedge#1248]
Using the command from the docs (which erroneously includes an unneeded backtick) results in an error when attempting to install on the latest slow ring Windows Insider build. This prevents testing on v.next builds of Windows. https://docs.microsoft.com/en-us/azure/iot-edge/quickstart

**Comment by veyalla** [comment]
This is as-designed behavior, IoT Edge only supports RS5-based builds (17763). It won't work and hence can't be installed on other Windows versions. See: https://aka.ms/iotedge-platsup#tier-1

If you find an issue with docs on build 17763, please file feedback under the article.

If you are using the Windows host for development and testing (not production, so no support) of Linux based containers, see this how-to: https://docs.microsoft.com/azure/iot-edge/how-to-install-iot-edge-windows-with-linux

.

**Comment by pkoronawa** [comment]
The link now takes you to a download of a newer unsupported version of Windows 10 Enterprise
