### ISSUE TITLE
Logging for Edge Modules

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#1262]
Hi Team,
    We want to log all exceptions and information into Files on container space. So could you suggest the best library for File base logging in Edge Module

**Comment by myagley** [comment]
IoT Edge collects all log lines written to stdout/stderr. This is the preferred method for log collection on IoT Edge, as we will build out features around this mechanism.

If you'd like to bypass IoT Edge's log collection and write directly to a file, that is also possible. What language are you using?

**Comment by sachidanand** [comment]
We are using C#.. So could you send me the link of C# Extension for logging into file from Edge Module

**Comment by myagley** [comment]
We use the ASP.NET Core logging extension in the runtime itself: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1

**Comment by ancaantochi** [comment]
Closing issue and it looks the question was answered.
