### ISSUE TITLE
Download files from blob storage

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1263]
Hi,

How can we download file from blob storage in custom edge module. I have requirement to send image url from Cloud using Module twin to trigger edge module to start downloading the file from blob storage.

I have seen there is edge module support for uploading file but that is available in marketplace.
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob

Regards,
Prateek

**Comment by pratson20** [comment]
Hi,

I am able to download the file blob storage sdk in azure edge custom module  using [Blob Storage SDK](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet?tabs=linux) . But it is difficult to find downloaded file location. I have to transfer this file to other machine to display on screen. In my case it is similar to below screenshot-

![image](https://user-images.githubusercontent.com/7486266/58472600-3d7fa900-8164-11e9-9cd1-5202fb060656.png)

Is it safe to send blob storage connection string through module twin?
I am updating desired properties(blob storage connection string and file name). 

If this is not valid then Can you please let me know the right design to implement this kind of solution.

Thanks,

**Comment by avranju** [comment]
There are 2 questions here it looks like:

1. How do we store the downloaded file in a location that's easily accessible from the host?
2. Is sending a storage connection string via the module twin an acceptable way of transmitting secrets to modules?

For 1, I think mounting a host folder path into the container at a specific location and then downloading the file into that path is probably the way to go (see the value for the `createOptions` attribute in the [Edge Hub docs](https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities#additional-offline-storage) for an example showcasing how to mount host paths into a module).
 
For 2, as of right now, yes, sending secrets via module twins is the right approach.

**Comment by pratson20** [comment]
Thanks @avranju . Closing this issue
