### ISSUE TITLE
Version number 1.0.7.1 reported as 1.0.7 with iotedge version and sudo iotedge check commands

### ISSUE THREAD

**Issue by JeeWeetje** [Azure/iotedge#1264]
If you install the latest Azure IoT Edge runtime (version 1.0.7.1) the commands `iotedge version` and `sudo iotedge check` report version number 1.0.7 which causes confusion and wrong results in the checkpoints.

## Expected Behavior
Command `iotedge version` should return `1.0.7.1 (checksum)` 
Command `sudo iotedge check` should return `√ latest security daemon` 

## Current Behavior
Command `iotedge version` returns `iotedge 1.0.7 (f455ae2cd66db716c4bd8e7aaa7984ce092481c0)` 
Command `sudo iotedge check` returns `‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7 but version 1.0.7.1 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.` 

## Steps to Reproduce
1. `sudo apt install libiothsm-std iotedge`
2. `iotedge version`
3. `sudo iotedge check`

## Context (Environment)
Industrial PC from Advantech (UNO-2372G) used from Research & Development 

### Device (Host) Operating System
`Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic`

### Architecture
amd64

### Container Operating System
Linux containers, Windows containers

#### iotedged
1.0.7.1 (according apt, 1.0.7 according to iotedge version)
#### Edge Agent
1.0 tag

#### Edge Hub
1.0 tag

#### Docker
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 22:01:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Logs
![Untitled](https://user-images.githubusercontent.com/693760/58465851-ced92600-8138-11e9-8b93-ca22cbee4e73.png)

## Additional Information
Registered as new device (via DPS) without a deployed workload, that is why the edgeHub is missing for the connectivity checks and DPS registration is causing the failed correct connection string check.

**Comment by sandervandevelde** [comment]
Same behavior here:

![image](https://user-images.githubusercontent.com/694737/58466763-a2bea480-813a-11e9-9ebc-ffbbcc8818b6.png)

**Comment by arsing** [comment]
`1.0.7-1` is v1.0.7, not v1.0.7.1. The `-1` is an RPM package naming convention to mean first release of this version.

**Comment by myagley** [comment]
We were not able to push the packages into the package repository until this morning. They have been pushed and verified. You will need to update your local cache before upgrading:

```
sudo apt-get update
sudo apt install libiothsm-std iotedge
```

Thank you for your patience.

**Comment by JeeWeetje** [comment]
Before the `sudo apt install` I did the `sudo apt update` this morning.

Did as suggested:
`sudo apt-get update
sudo apt install libiothsm-std iotedge`

Installed a version 1.0.7.1-1, so even never than the 1.0.7.1 before. See attached logs
[iotedge-1.0.7.1-1-logs.txt](https://github.com/Azure/iotedge/files/3229907/iotedge-1.0.7.1-1-logs.txt)
