### ISSUE TITLE
Can IoT edge device connect to Sql server using windows authentication

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#1267]
Hi,
I have got a requirement that IoT edge device sitting in corporate network and want to sql server using windows authentication.

Is it possible or not, if possible can I have some link or guide documents?

Thanks,
Muhammad Masood

**Comment by veyalla** [comment]
Checkout [Group managed service accounts for Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts) docs which has an example for [SQL Server connection strings](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts#sql-connection-strings).

**Comment by m4masood** [comment]
Thanks @veyalla I have got linux container.

**Comment by veyalla** [comment]
I don't think this is possible with Linux containers, but I am not the expert here so I suggest you do your own research.

**Comment by m4masood** [comment]
I found one post at https://www.codeproject.com/Articles/1272546/Authenticate-NET-Core-Client-of-SQL-Server-with-In I will try and update it here.

**Comment by m4masood** [comment]
Hi,
The module can connect to TLS enabled sql server. Here is the link https://github.com/dotnet/SqlClient/issues/147

Thanks,
Muhammad Masood
