### ISSUE TITLE
Why Rocks DB logging of edgeHub is written filesystem?

### ISSUE THREAD

**Issue by sahya** [Azure/iotedge#1274]
## Expected Behavior

it is question.
I am beginner so I may wrong this question.

I want to use tempfs /tmp/edgeHub because Rocks DB of edgeHub is very hard written at NAND disk (flash storage). So the disk lifespan was very short. (I know how to configuration of using tempfs at iothub.)

I think docker containers logging of defacto standard architecture is stdout.
Why Rocks DB don't use stdout & tempfs instead of rootfs? The product don't wanted to inform log information to end user?

## Current Behavior

I hope The edgeHub of Rocks DB logging to tempfs or stdout.

## Steps to Reproduce

1. Send to edgeHub about many msg/sec,

## Context (Environment)
Raspi 2
microsd TLC 16GB

### Architecture

arm32

### Container Operating System

Raspi 

#### iotedged

iotedge 1.0.7

#### Edge Agent

EdgeAgent1.0.7

#### Edge Hub

iEdgeHub 1.0.7

#### Docker

moby-engine_3.0.5_armhf

**Comment by myagley** [comment]
RocksDB is an embedded database that is used to persist messages to disk for store and forward in the case of going offline. It isn't directly related to logging.

Are you seeing additional logs being written somewhere for rocksdb? Did your flash drive actually wear out? Is there some form of wear leveling enabled on the device?

If you don't need persistence of messages, there are some settings that can be used to turn off RocksDB. This may be an option for you.

**Comment by sahya** [comment]
Thank you for telling me.

>Are you seeing additional logs being written somewhere for rocksdb? 

Sorry, I might have misunderstanding. I was realize "/tmp/edgeHub/00245.log" is edge module logging. 
And "/tmp/edgeHub/LOG" is RocksDB logging.
The log is almost the same as # 1181.
Sorry, I cant publish infomation for you because it is confidencial.

> Did your flash drive actually wear out?

yes. It is a little different from this log problem, but the writing of flash drive written about 1MB/sec on /tmp/edgeHub when taking measurement by iostat.

> Is there some form of wear leveling enabled on the device?

It is probably No. 
We have not made any special intentional measures against the consumption of the disk life of the device.

**Comment by sahya** [comment]
> If you don't need persistence of messages, there are some settings that can be used to turn off RocksDB. This may be an option for you.
Would you please tell me option paramater that persistence of messages turn off?

**Comment by myagley** [comment]
The logs in the `/tmp/edgeHub` directory are not application logs. These files contain the data for the RocksDB embedded database. This database uses a data structure called a Log Structured Merge true (LSM tree). This is where the `log` in the filenames comes from.

The Edge Hub logs its application logs to stdout and these are collected by the Docker daemon.

You can disable persistence by setting the following environment variable in the Edge Hub's section of the deployment:
`usePersistentStorage`=`false`

**Comment by sahya** [comment]
Thank you for your explanation.

> This database uses a data structure called a Log Structured Merge true (LSM tree). This is where the log in the filenames comes from.

I see.
So doesn't the LSM tree `log`  need stdout, isn't it correct?
Sorry, I want to know a little more. would you please give me a little more time.
Is it correct because it is for the architecture that it is not something to show to the users of iotedge?

Thank you for teach me "disable persistence parameter".
If you continue to use the architecture (Rocksdb), 
I think it is useful to describe the `usePersistentStorage`  in the azure docs as a parameter for future users to use flash storage.

**Comment by myagley** [comment]
No, the LSM tree persists directly to the filesystem. It doesn't directly use stdout. The use of RocksDB is an internal implementation detail. It is not a public interface and isn't expected to be interacted with directly by a user. The user interacts with it via the various Edge Hub APIs over mqtt/ampq/http etc.

**Comment by sahya** [comment]
thanks myagley! OK, I understand.

**Comment by sahya** [comment]
I will make the best use of your comment from now on. because I just now developing to use developing by iotedge.

**Comment by sahya** [comment]
@myagley could you consider about documentation?

about following it
*If you continue to use the architecture (Rocksdb),
I think it is useful to describe the usePersistentStorage in the azure docs as a parameter for future users to use flash storage. (note: In the document that you have to be careful when setting up Flash Storage such as SSD and SD card)*

**Comment by richterr** [comment]
> No, the LSM tree persists directly to the filesystem. It doesn't directly use stdout. The use of RocksDB is an internal implementation detail. It is not a public interface and isn't expected to be interacted with directly by a user. The user interacts with it via the various Edge Hub APIs over mqtt/ampq/http etc.

Can you share information how the DB behaves in case of a hardware failure, please? For example if the device is offline and the configured TTL of the edgeHub is not yet reached but disk is already full?
Thanks in advance.

**Comment by myagley** [comment]
The write to the database will fail and an error will be returned to the client. 

We are adding the ability to bound the message log by size (in addition to the time based limits that we have today). What would you expect for that behavior if the limit is reached? Should the log drop messages add the head of the queue to make room or prevent more items from being pushed onto the end of the queue?

**Comment by richterr** [comment]
Thanks for the quick response @myagley. Just needed to know what behavior to expect since we have to answer to our customers.
I think a ring buffer makes more sense. It makes sure that aggregations someone might do in the cloud resume delivering data sooner.

**Comment by lt72** [comment]
Closing this issue as it seems stale, please feel free to re-open if you need to.

**Comment by fabriziogueli** [comment]
Hello, 
Any news on the offline feature that @myagley was talking about? 
(Bound the message on RocksDB by size in addition to the time based limits that we have today)

When the limit is reached it would be useful to have a behavior similar to a circular buffer.

Has this functionality already been implemented?

Thanks for your support
