### ISSUE TITLE
Please document how binding a container to the host network works on both Linux and Windows

### ISSUE THREAD

**Issue by barnstee** [Azure/iotedge#1275]
On Linux, this is done through the 'host' network binding that is already set up when Docker is installed.
On Windows, you first need to setup an external  Hyper-V switch called "host" and bind it to a network adapter on the gateway using PowerShell:
PS>get-netadapter
From the list returned, pick a network adapter name connecting to the network you want to bind your IoT Edge module.
PS>new-vmswitch -name host -NetAdapterName <network adapter name> -AllowManagementOS $true

Also, the following deployment manifest changes are required per module:

```
"createOptions": {
    "NetworkingConfig": {
        "EndpointsConfig": {
             "host": {}
        }
    },
    "HostConfig": {
        "NetworkMode": "host"
    }
}
```

**Comment by Protoinfy** [comment]
Followed  @barnstee hints but still I still can't access to host network ip addresses on Windows ( host was bound to Wi-Fi network).  Tried the following:
`PS>new-vmswitch -name host -NetAdapterName Wi-Fi -AllowManagementOS $true`
Same deployment template, but for a Linux amd64 target was successful.
Please could you please document how to correctly bind networks on Windows?
Thanks

**Comment by veyalla** [comment]
@dineshgovindasamy could you please provide some guidance here?

**Comment by myagley** [comment]
Can you discuss your scenario a little more?

Running on the host network isn't a common scenario and should be done as a last resort. It removes network isolation and is not desirable. I know of only two reason why using the `host` network is required:
1. Binding a bluetooth socket. Due to a kernel bug in Linux, binding a bluetooth socket (`AF_BLUETOOTH`) is only possible in the default network namespace. This is being fixed and will no longer be an issue shortly.
2. Receiving multicast UDP traffic. The Moby iptables rules do not forward multicast UDP traffic to a container on a user-defined bridge network. On Linux this requires running on the `host` network, and on Windows requires running on the `transparent` network.

We should be able to get your scenario to work with a proper set of port bindings or routes on the host.

**Comment by barnstee** [comment]
3. IP scanning the local network (OPC Twin requirement).

Cheers,

             Erich

**Comment by Protoinfy** [comment]
Thanks for your quick replies.
Maybe my scenario is not right or advisable... furthermore I started learning iotedge from not so long, so I suspect I'm doing mistakes.

I have a windows service able to read values from a PLC(siemens s7)  on a LAN PC. This service could also run in the same host of the iotedge. My idea was to ask values from this service and send them to the iot hub using an edge module. So i'm just trying to tcp connect to the service. Despite the probably wrong scenario, there are ways to achieve this without using the host network?

By now, I'm studying the connected factory solution accelerator for a more structured solution for industrial iot, but i don't have the full picture from the PLC/automation point of view, I need more info from my colleagues...

**Comment by barnstee** [comment]
Your scenario is correct. In fact, we (the Azure Industrial IoT team) are using the same one. We normalize the data at the edge using OPC UA, so our module flow is:
S7 PLC->Adapter->OPC Twin/Publisher->Edge Hub->The cloud
The Adapter comes from a 3rd party and also runs on Edge. However, it is not officially released yet. Ping me offline if you need more info.

**Comment by nouira** [comment]
When I add theh networking config to a module
`              "createOptions": {
                "NetworkingConfig": {
                  "EndpointsConfig": {
                    "host": {}
                  }
                },
                "HostConfig": {
                  "NetworkMode": "host"
                }
              }`
I get this error
`ERROR: 'network_mode' and 'networks' cannot be combined
ERROR: Error while executing command: docker-compose -f C:\ProgramData\iotedgehubdev\data\data\docker-compose.yml down. Command '['docker-compose', '-f', 'C:\\ProgramData\\iotedgehubdev\\data\\data\\docker-compose.yml', 'down']' returned non-zero exit status 1.`

Do I need to add another settings else where ?
I'm running on Windows 10 with iotedgehubdev

**Comment by fgheysels** [comment]
I wonder if there's any news on this :)

**Comment by davidzwa** [comment]
1 - @myagley I have the same interest, both iotedgeHubDev and a normal Windows (with Linux Container) setup dont seem to work with bind to host. On my raspberry-pi-3 and Azure VM (18.04) it works fine.

2 - I also can't resolve the desired properties (TwinCollection) using the ModuleClient (I get transient error after a while).
`Hub communication error: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.`

I haven't changed my hub and agent networkMode, but only the module which uses multicast UDP (Net-MDNS library).

Any tip?

**Comment by veyalla** [comment]
This is documented here for now: https://github.com/Azure/Industrial-IoT/blob/master/docs/deploy/howto-install-iot-edge.md#special-cases-for-windows-networking-configuration
