### ISSUE TITLE
edgeAgent creates a `vethXXXXXXXX`-interface, killing internet connection

### ISSUE THREAD

**Issue by thomafred** [Azure/iotedge#1282]
## Expected Behavior

When booting device, or restarting iotedge-processes, internet connectivity should remain stable system wide.

Furthermore, the iotedge-processes should select the default network interface.

## Current Behavior

When restarting iotedge edgeAgent, a new network interface is created `vethXXXXXXXX`, which is made a default interface, killing the system-wide internet connections which has not been assigned to a specific interface.

## Steps to Reproduce

1. Boot device, wait for edgehub and edgeagent to start.
2. ping some server: `ping 8.8.8.8`, observe pings returning
3. Restart iotagent: `iotedge restart iotAgent`, wait for agent to restart
4. ping the server again: `ping 8.8.8.8`, observe pings failing.

### Device (Host) Operating System
Debian GNU/Linux 9 (stretch)

### Architecture
arm32

### Container Operating System
Linux Containers

#### iotedged
iotedge 1.0.7 (f455ae2cd66db716c4bd8e7aaa7984ce092481c0)

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker

```sh
Client:                                                                                                                                                                                     
 Version:           3.0.5                                                                                                                                                                   
 API version:       1.40                                                                                                                                                                    
 Go version:        go1.12.1                                                                                                                                                                
 Git commit:        ba9934d4                                                                                                                                                                
 Built:             Thu Apr 18 23:28:44 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Fri Apr 19 07:14:38 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Logs

Network routes before restarting edgeAgent:

```sh
$ route
default         XXX.XXX.XXX.XXX 0.0.0.0         UG    0      0        0 ppp0
{...}
XXX.XXX.XXX.XXX 0.0.0.0         255.255.255.255 UH    0      0        0 ppp0
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vethd17a09b
link-local      0.0.0.0         255.255.0.0     U     0      0        0 veth3656fff
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vethb616bcf
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vethe873b68
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vethf5615f9
link-local      0.0.0.0         255.255.0.0     U     0      0        0 veth2af995b
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.19.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-5f7c6dccffca
192.168.6.0     0.0.0.0         255.255.255.252 U     0      0        0 usb1
192.168.7.0     0.0.0.0         255.255.255.252 U     0      0        0 usb0
```

Network routes after restarting edgeAgent:

```sh
default         0.0.0.0         0.0.0.0         U     0      0        0 vethfdae5bf
default         XXX.XXX.XXX.XXX 0.0.0.0         UG    0      0        0 ppp0
{...}
XXX.XXX.XXX.XXX 0.0.0.0         255.255.255.255 UH    0      0        0 ppp0
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vethfdae5bf
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.19.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-5f7c6dccffca
192.168.6.0     0.0.0.0         255.255.255.252 U     0      0        0 usb1
192.168.7.0     0.0.0.0         255.255.255.252 U     0      0        0 usb0
```

## Additional Information

When booting the device, I noticed that the edgeAgent starts before the edgeHub, and that the `vethXXXXXXX`-interfaces is created after the edgeHub starts. When restarting the edgeAgent, all `vethXXXXXXXX`-interfaces appear to be deleted, and replaced by a single interface which is made default by the network manager.

**Comment by arsing** [comment]
The interfaces are created by docker when it starts containers, and I can see some comments from 2014 on [Docker's issue tracker](https://github.com/moby/moby/issues/4453#issuecomment-63743740) about this interaction with NM.

Can you check if you see this with any docker containers, not necessarily edge-agent and edge-hub?

The difference between edge-agent and edge-hub is that the former starts on the default network ("bridge") and the latter on the container runtime network (named "azure-iot-edge" by default). So something like `docker run -it --rm --name edgeAgent alpine:latest` and `docker run -it --rm --network azure-iot-edge --name edgeHub alpine:latest` should be sufficient to simulate it.

**Comment by thomafred** [comment]
Hi @arsing,

Following your recommendation, I attempted to simulate the docker networks. However this did not create any vethXX-interfaces as expected, and internet connection remained active.

**Comment by thomafred** [comment]
Can someone let me know whether or not this is resolvable?

**Comment by arsing** [comment]
Just to be sure, when you wrote:

>3. Restart iotagent: `iotedge restart iotAgent`, wait for agent to restart

... you meant `systemctl restart iotedge`, right?

---

I set up a Debian 9 VM with network-manager (`1.6.2-3+deb9u2`), iotedge (`1.0.7.1`) and moby-engine (`3.0.5`), and could not repro. It is not *identical* to your scenario though, since it's an amd64 VM, not arm32.

After restarting `iotedge`:

```
$ nmcli device status

DEVICE           TYPE      STATE      CONNECTION         
br-4f38843cca20  bridge    connected  br-4f38843cca20    
docker0          bridge    connected  docker0            
eth0             ethernet  connected  Wired connection 1 
vetha28cd16      ethernet  unmanaged  --                 
vethb1bb41d      ethernet  unmanaged  --                 
vethe5afc18      ethernet  unmanaged  --                 
lo               loopback  unmanaged  -
```

The three `veth*` correspond to the three modules I have (Edge Agent, Edge Hub, Temp Sensor`) but you can see they defaulted to being unmanaged.

```
$ sudo route

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         172.16.52.1     0.0.0.0         UG    100    0        0 eth0
168.63.129.16   172.16.52.1     255.255.255.255 UGH   100    0        0 eth0
169.254.169.254 172.16.52.1     255.255.255.255 UGH   100    0        0 eth0
172.16.52.0     0.0.0.0         255.255.255.0   U     100    0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-4f38843cca20
```

`ping` continued to be able to work.

**Comment by arsing** [comment]
> Just to be sure, when you wrote:
> 
> > 1. Restart iotagent: `iotedge restart iotAgent`, wait for agent to restart
> 
> ... you meant `systemctl restart iotedge`, right?

Actually, I guess you meant `iotedge restart edgeAgent`. Even with that, I do not see the behavior you mentioned.

>When restarting the edgeAgent, all vethXXXXXXXX-interfaces appear to be deleted, and replaced by a single interface which is made default by the network manager.

I only see one of the `veth*` interfaces go away (the one corresponding to Edge Agent's container). When it comes back the interface gets recreated, and still is unmanaged by NM. So it does not show up in `route` and `ping` continues to work.

**Comment by thomafred** [comment]
I suspect that 32-bit vs 64-bit architectures might be a culprit here. iotedge is currently running on a BeagleBone Black, although it previously was running on a Raspberry Pi 3 for prototyping purposes. On this platform, which is arm64, we did not experience this problem at all.

Retrying the steps using `systemctl restart iotedge` instead of `iotedge restart iotAgent` did yield any different result.

Like you point out, the `vethXXXXXXXX`-interfaces are unmanaged here as well, but yet they still do show up in the `route`-table.

```sh
$ nmcli device status
DEVICE           TYPE      STATE        CONNECTION      
br-5f7c6dccffca  bridge    connected    br-5f7c6dccffca 
docker0          bridge    connected    docker0         
ttyACM0          gsm       connected    test            
eth0             ethernet  unavailable  --                           
usb0             ethernet  unmanaged    --              
usb1             ethernet  unmanaged    --              
veth5cef87a      ethernet  unmanaged    --              
veth8b5fed6      ethernet  unmanaged    --              
vethb82a2a9      ethernet  unmanaged    --              
vethf3e4164      ethernet  unmanaged    --              
lo               loopback  unmanaged    --  

$ sudo route
default         0.0.0.0         0.0.0.0         U     0      0        0 vethb82a2a9
default         XXX.XXX.XXX.XXX 0.0.0.0         UG    0      0        0 ppp0
XXX.XXX.XXX.XXX 0.0.0.0         255.255.255.255 UH    0      0        0 ppp0
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vethb82a2a9
link-local      0.0.0.0         255.255.0.0     U     0      0        0 veth5cef87a
link-local      0.0.0.0         255.255.0.0     U     0      0        0 veth8b5fed6
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vethf3e4164
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.19.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-5f7c6dccffca
192.168.6.0     0.0.0.0         255.255.255.252 U     0      0        0 usb1
192.168.7.0     0.0.0.0         255.255.255.252 U     0      0        0 usb0

$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From YYY.YYY.YYY.YYY icmp_seq=1 Destination Host Unreachable
```

**Comment by arsing** [comment]
>I suspect that 32-bit vs 64-bit architectures might be a culprit here. iotedge is currently running on a BeagleBone Black, although it previously was running on a Raspberry Pi 3 for prototyping purposes. On this platform, which is arm64, we did not experience this problem at all.

The rpi3 is also an arm64 device. I assume you mean you had a 32-bit OS on it.

I would assume the bitness of the OS is not the difference, but rather likely the versions / configuration of NM and Docker.


>Retrying the steps using `systemctl restart iotedge` instead of `iotedge restart iotAgent` did yield any different result.

Again, there is no module called `iotAgent`. I assume you mean `iotedge restart edgeAgent`.


>Like you point out, the `vethXXXXXXXX`-interfaces are unmanaged here as well, but yet they still do show up in the `route`-table.

Surprising. You don't have two different network managers simultaneously, do you?

If not, you should follow up with https://github.com/moby/moby and NetworkManager

**Comment by thomafred** [comment]
Hi @arsing 

My apologies for imprecise in copy/pasting. I of course mean `iotedge restart edgeAgent`.

To clarify the course of events: We first had an RPi3 (arm64) with 64-bit Debian installed. We later moved the BeagleBone Black platform (arm32) which is running 32-bit Debian. This is when we first noticed the problems of the `vethXXXXXXXX`-interfaces like described above.

**Comment by arsing** [comment]
Ah, okay. So the BeagleBone Black is the one with the problem, not the rpi3. Got it.

I'd still assume the difference is in configuration or package versions rather than CPU / OS bitness. You can try removing NM (at least temporarily) to confirm whether it is involved with the problem or not. If removing NM does fix it, and if there are no configuration / package version differences between the working rpi3 and the non-working Beaglebone Black, then as I said you should follow up with Moby / NetworkManager. If you open an issue there, please link it here so we can follow it.

Also, if removing NM fixes the problem, but you need NM because of needing to connect to networks dynamically, you could also try replacing it with wickedd, etc.

(We currently don't support Debian, which is to say that we don't have it in our test infra. The arm32 tests are on Raspbian and don't have NM. I'll keep NM in mind when we add Debian to our test infra.)

**Comment by lt72** [comment]
Closing, as it seems resolved. Please re-open as needed.

**Comment by FinitelyFailed** [comment]
We have a very similar issue. When we have IoT Edge running there are virtual routes added to the routing table. Which seems to be in conflict with other routes and in turn effectly blocks external access.
We run on a RaspberryPi CM4 and RaspberryPi 3b. Tested on both 32- and 64-bit. The OS is built with Yocto and based on kirkstone, we have tried an image based on dunfell as well.

We tested on iotedge 1.4.3 and 1.4.16 with the same result.

IoT Edge Runtime:
iotedge 1.4.3
iotedge 1.4.16

EdgeAgent:
1.4.3
1.4.16
EdgeHub:
1.4.3
1.4.16

Docker:
Docker version 20.10.25, build 911449ca24
Dockerd:
Docker version 20.10.25, build 791d8ab87747169b4cbfcdf2fd57c81952bae6d5


When the system is not running:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    0      0        0 eth0
default         _gateway        0.0.0.0         UG    10     0        0 eth0
10.0.0.4        _gateway        255.255.255.255 UGH   0      0        0 eth0
10.0.0.4        _gateway        255.255.255.255 UGH   10     0        0 eth0
10.100.0.0      *               255.255.254.0   U     10     0        0 eth0
10.100.0.1      *               255.255.255.255 UH    0      0        0 eth0
10.100.0.1      *               255.255.255.255 UH    10     0        0 eth0
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
172.18.0.0      *               255.255.0.0     U     0      0        0 br-76722341f6b8
```


After 'iotedge system restart':

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         *               255.255.255.255 UH    0      0        0 veth0c4be3d
default         *               0.0.0.0         U     0      0        0 veth0c4be3d
default         _gateway        0.0.0.0         UG    0      0        0 eth0
default         _gateway        0.0.0.0         UG    10     0        0 eth0
10.0.0.4        _gateway        255.255.255.255 UGH   0      0        0 eth0
10.0.0.4        _gateway        255.255.255.255 UGH   10     0        0 eth0
10.100.0.0      *               255.255.254.0   U     10     0        0 eth0
10.100.0.1      *               255.255.255.255 UH    0      0        0 eth0
10.100.0.1      *               255.255.255.255 UH    10     0        0 eth0
169.254.0.0     *               255.255.0.0     U     0      0        0 veth0c4be3d
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
172.18.0.0      *               255.255.0.0     U     0      0        0 br-76722341f6b8

```

As you can see there are a number of vertial routes added to the routing table.

We found a similar issue and tried this answer: https://stackoverflow.com/a/65806913/2546371, as we have the connman network manager on our os. When we add 'veth*' to connmans blacklist and restarted connman all 'veth*' routes are removed and external communication starts to work (pinging google.se etc.). But iotedge can't connect to our Azure IoT hub, which isn't supprising as we meddled with stuff after IoT Edge tried to setup network in docker etc. After a reboot the state of the system as is was before with a lot of virtual routes and broken external communication.
