### ISSUE TITLE
Install fails in Debian Stretch (iotedge_1.0.0-1_amd64.deb)

### ISSUE THREAD

**Issue by Jan-Olof** [Azure/iotedge#130]
## Expected Behavior
The "sudo apt-get install iotedge" command should install IoT Edge

## Current Behavior
```
sudo apt-get install iotedge

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 iotedge : Depends: libssl1.0.0 (>= 1.0.2~beta3) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
If we try to install libssl1.0.0 this fails too:
```
sudo apt-get install libssl1.0.0

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libssl1.0.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.0' has no installation candidate
```
## Steps to Reproduce
1. Follow the install instructions here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux.
2. When installing repository configuration, use this link: https://packages.microsoft.com/config/debian/9/prod.list

### Device (Host) Operating System
Debian Stretch

### Architecture
 amd64

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.0

#### Edge Agent
1.0.0

#### Edge Hub
1.0.0

#### Docker
18.06.0-dev

## Additional Information
I am aware that Debian is currently not supported and that there is a suggestion about this here: https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/34685371-can-not-install-iotedge-1-0-0-1-amd64-deb-package.

However we would really like to test IoT Edge on Debian, as this is very important for us. Does anyone have any suggestions for workarounds so that we can install for testing? 

Also, any information on when a version of IoT Edge that can be installed on Debian is available is really appreciated.

**Comment by Jan-Olof** [comment]
I seem to have found a workaround that enables IoT Edge to be installed on Debian 9. I was able to install the package "libssl1.0.0 (1.0.2l-1~bpo8+1)" using these commands:

```
wget "http://ftp.se.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb"
sudo dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb
```

Let's see if everything works as it should.

**Comment by myagley** [comment]
Yes, we are working on fully enabling Debian Stretch support in this current sprint. As you point out, there is an issue with how the libssl library is named vs. Ubuntu.

Your workaround show work, but let me know if you run into any issues. Thanks!

**Comment by Jan-Olof** [comment]
Thanks for your answer. Yes, with the workaround everything seem to be OK.

**Comment by myagley** [comment]
Debian packages are now supported through the build scripts located here: https://github.com/Azure/iotedge/tree/master/edgelet/contrib

I'm going to close this issue now, as we should be able to produce correct packages for Debian using these scripts now. Please feel free to reopen. Thanks!

**Comment by chriswue** [comment]
@myagley  Hm, I've run into the same issue when trying to build a container based on the debian-stretch-slim base image. The work-around helps. This is how I'm setting it up:

    FROM microsoft/dotnet:2.2-runtime-stretch-slim
    ARG DEBIAN_FRONTEND=noninteractive

    RUN apt-get update && \
        apt-get install -y --no-install-recommends apt-transport-https gnupg2 && \
        curl "http://ftp.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb" -O && \
        dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb && \
        rm libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb && \
        curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
        curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/microsoft-prod.list && \
        apt-get update && \
        apt-get install -y --no-install-recommends moby-engine && \
        apt-get install -y --no-install-recommends iotedge

If I don't install the libssl package manually I get the same error as Jan-Olof.

Building an image based on the stock debian stretch slim image also result in the same problem so looks like a packaging issue to me.

    FROM amd64/debian:stretch-slim
    ARG DEBIAN_FRONTEND=noninteractive

    RUN apt-get update && \
        apt-get install -y --no-install-recommends ca-certificates curl apt-transport-https gnupg2 && \
        curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
        curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/microsoft-prod.list && \
        apt-get update && \
        apt-get install -y --no-install-recommends moby-engine && \
        apt-get install -y --no-install-recommends iotedge

In both cases the result is

    The following packages have unmet dependencies:
     iotedge : Depends: libssl1.0.0 (>= 1.0.2~beta3) but it is not installable
    E: Unable to correct problems, you have held broken packages.

**Comment by chriswue** [comment]
On that note - I just found the iotedge stretch package is outdated - it's still 1.0.0 while the ubuntu one is 1.0.4. With ubuntu the issue doesn't exist and the 18.04 docker image is only like 10MB larger than stretch so I'll go with that instead.

**Comment by Mo-GH** [comment]
the work around not work for me and the link is not anymore valid : 
http://ftp.se.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_amd64.deb"

thanks

**Comment by chriswue** [comment]
@Mo-GH It doesn't look like Debian9 images are built regularly. https://packages.microsoft.com/debian/9/prod/pool/main/i/iotedge/ contains only 1.0.7.1 My advise would be to got with Ubuntu instead. If there are issues on Debian (such as packaging or dependency issues) then you're likely on your own.
