### ISSUE TITLE
Can we send Telemetry messages from a custom IoT edge module to IoT Hub without any leaf device

### ISSUE THREAD

**Issue by AmitBarthwal** [Azure/iotedge#1301]
I need to get some values about the OS of the gateway using a custom module and push the values as a telemetry messages. Will it be a correct way to push some telemetry data to IoT hub without any leaf device.

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64
### Container Operating System
Linux containers
#### Edge Agent
iotedge 1.0.6.1

#### Docker
Docker version 3.0.3

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```

**Comment by myagley** [comment]
That should work as expected using the default route in the Edge Hub. By default, the Edge Hub sends all telemetry from devices and modules to IoT Hub. You can look at the simulated temperature sensor for an example of a module sending telemetry: https://github.com/Azure/iotedge/blob/master/edge-modules/SimulatedTemperatureSensor/src/Program.cs#L166
