### ISSUE TITLE
Desired properties are not updating when deploying from Azure portal

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#1335]
Hi,

I have got a module that reads some configuration from desired properties. When I deploy from Azure portal, it does not reflects in the module. Looks like edge device is caching the desired properties.

I am supplying below properties:
{
    "properties.desired":{
        "TemperatureThreshold":25
    }
}

but it is receiving other than above like shown in below image:
![module screenshot](https://user-images.githubusercontent.com/7548298/59498185-3e406b00-8ed8-11e9-9e80-4659ebcbeaeb.png)
 
Can you please assist on this? How can I force device to load the latest properties?

Thanks,
Muhammad Masood

**Comment by m4masood** [comment]
Any updates?

**Comment by m4masood** [comment]
Hi,
I am having issue with desired properties in one of my IoT Edge server sitting behind the proxy. Other servers are fine.

Can you please assist on how can I flush or make sure IoT Edge module gets updated desired properties?

Thanks,
Muhammad Masood

**Comment by ancaantochi** [comment]
@m4masood ,

Just to make sure I understand the issue, from the filterModule logs it looks like it received desired property change and it failed in the callback? It's not necessary to use web sockets for the module when you connect to edgeHub, only the upstream protocol has to be over websockets.

Please provide edgeHub logs during the twin update, if possible with debug level turn on: [https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#view-the-messages-going-through-the-iot-edge-hub](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#view-the-messages-going-through-the-iot-edge-hub)

**Comment by m4masood** [comment]
Hi @ancaantochi ,
I am supplying a json to device properties in Azure portal but the module received different (older version of the properties) so to me it is picking from cached version.
I will see if I can get the logs.
Thanks,
Muhammad Masood

**Comment by m4masood** [comment]
Hi,
I deleted edgeAgent and edgeHub container and restarted the iotedge and it fixed and getting latest desired properties.
I will post here if there is any issue.

Thanks,
Muhammad Masood
