### ISSUE TITLE
'journalctl -u iotedge' will i get the logs in the file? 

### ISSUE THREAD

**Issue by AmitBarthwal** [Azure/iotedge#1349]
I need to get the system logs of iotedge and push them to the IoT hub.
'journalctl -u iotedge' logs i need on the file that i can mount to the docker container file system, and leverage that log file.
## Expected Behavior
Need to create a module that will read the "journalctl -u iotedge" logs and send to the iot hub.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
// Paste here
```
</details>

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
 Linux container

#### iotedged
iotedge 1.0.6.1

#### Docker
Docker version 3.0.3

**Comment by darobs** [comment]
Mike marked this as a potential enhancement, but until that happens, you can get access to the host journal data.  If you have a container with systemd utilities install and you mount the journald log directory (usually /var/log/journal) to it:

For example, on Ubuntu, using an Ubuntu container:
```sh
docker run --rm -v /var/log/journal:/var/log/journal:ro darobs/run_forever:amd64-0.1 journalctl --directory /var/log/journal/ -u iotedge -n 4
```
Produced this:
-- Logs begin at Mon 2018-10-08 17:42:27 UTC, end at Wed 2019-06-19 17:05:02 UTC. --
Jun 07 17:57:39 \<mysystem\> systemd[1]: Stopped Azure IoT Edge daemon.
Jun 07 17:57:39 \<mysystem\> systemd[1]: iotedge.service: Start request repeated too quickly.
Jun 07 17:57:39 \<mysystem\> systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jun 07 17:57:39 \<mysystem\> systemd[1]: Failed to start Azure IoT Edge daemon.

As a convenience, if you mount the machine-id and hostname, you don't need the `--directory` option.
```sh
docker run --rm -v /var/log/journal:/var/log/journal:ro darobs/run_forever:amd64-0.1 -v /etc/machine-id:/etc/machine-id:ro -v /etc/hostname:/etc/hostname:ro journalctl -u iotedge -n 4
```

**Comment by AmitBarthwal** [comment]
Thanks darobs for reply.

I have tried to mount the directories and hostname.
I am using node.js with below code to get the response

var execSync = require('child_process').execSync;
var cmd_debuglog = "journalctl -u iotedge -n 4";
var debug_response = execSync(cmd_debuglog, options);
console.log("debug log file is generated " + debug_response);


I got an error below:-

/bin/sh: journalctl: not found
child_process.js:650
    throw err;
    ^

Error: Command failed: journalctl -u iotedge -n 4
/bin/sh: journalctl: not found

    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at /app/app.js:265:27
    at Mqtt.<anonymous> (/app/node_modules/azure-iot-device/lib/internal_client.js:338:13)
    at emitOne (events.js:116:13)
    at Mqtt.emit (events.js:211:7)
    at Mqtt._onDeviceMethod (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:831:18)
    at Mqtt._dispatchMqttMessage (/app/node_modules/azure-iot-device-mqtt/lib/mqtt.js:741:25)
    at emitTwo (events.js:131:20)
    at MqttBase.emit (events.js:214:7)

I think this error i am getting because systemd utilites not installed in container.
Could please share me how can i install systemd utilites in docker image?
Or you think this error is due to something else.

**Comment by AmitBarthwal** [comment]
Hi,

I have tried with the given docker image but 'journalctl' command was not working.

docker run --rm -v /var/log/journal:/var/log/journal:ro darobs/run_forever:amd64-0.1 journalctl --directory /var/log/journal/ -u iotedge -n 4


Can anyone please share how to proceed on the above?

**Comment by darobs** [comment]
Oh, my apologies, I modified the "darobs/run_forever:amd64-0.1" image underneath you and removed the systemd installation in that image's Dockerfile.   I assumed you'd use your own Docker image - that one is just ubuntu18.04 with a program that just pauses until a signal is sent.

```sh
docker run -it -v /var/log/journal:/var/log/journal:ro ubuntu:18.04 bash
```
Once you get a prompt, you can do this:
```sh
ap-get update
apt-get install systemd
journalctl --directory /var/log/journal/ -u iotedge -n 4
```

**Comment by AmitBarthwal** [comment]
Thanks darobs..
i have taken the ubuntu:18.04 as my base image and install systemd utility in the image.
Journalctl is working now with my custom code.

Thanks for the solution..
