### ISSUE TITLE
Problem with built of modules using windows docker for windows device in vs code

### ISSUE THREAD

**Issue by arnabhetc** [Azure/iotedge#1350]
Hi,
        First of all, I would like to mention that, I am using my organization Laptop,  that has a lot of self-security checks and security agent installed, 
       
                    

- I building a module for windows AMD-64, I have switched the container to windows container from Linux.

- The built for the Linux is happening successfully,  but when I am doing the built for the windows device the following I am facing 
               
         1. The built is stopping  and the system is crashing 
         2. Even the built is starting its getting ended at step 4/10 
            "Logon failure: the user has not been granted the requested logon type for this computer."
                 
I have tried upgrading the policies according to one Microsoft answer but my organization is not supporting that 
link - https://answers.microsoft.com/en-us/windows/forum/windows_7-networking/logon-failure-the-user-has-not-been-granted-the/9cafeb92-ce7c-48d1-a286-f1202a5c8afb 

 
any possible solutions for this?

**Comment by darobs** [comment]
Hello @arnabhetc,

Is this the docker build that's failing?

There might be more suggestions, but I found [this issue](https://github.com/docker/for-win/issues/2105), which may have some helpful pointers.

**Comment by ancaantochi** [comment]
Closing this issue because no reply for more than 10 days. Please reopen if you still have this issue.
