### ISSUE TITLE
Deploy-IoTEdge : how-to force or confirm confirmation message?

### ISSUE THREAD

**Issue by conekeo** [Azure/iotedge#1365]
Hi,

I want to automate the task of deploying IOT Edge via Powershell.

After running this:
```. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Deploy-IoTEdge```

I always has this confirmation message: 
```
> Confirm
> Do you want to continue with installation?
> [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
```

How can I force or confirm automatically the confirmation message?

## Expected Behavior
Don't ask for a confirmation message. Use default.

## Current Behavior
Ask for a confirmation message

### Device (Host) Operating System
Windows 10 Enterprise 1809

### Architecture
x64

### Container Operating System
Windows containers 

#### Docker
Docker version 18.09.2, build 6247962

**Comment by darobs** [comment]
That could be a useful feature.  In the meantime, that looks you may be able to avoid that prompt by using the "-SkipBatteryCheck" switch.

```powershell
 {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Deploy-IoTEdge -SkipBatteryCheck
```

I can't guarantee nothing else will raise a prompt.

**Comment by arsing** [comment]
@conekeo Just to be clear, you do see the warning about `One or more batteries were detected on this device.` before the confirmation prompt, yes?

If you're willing to take the risk as that warning states, then as @darobs said you can bypass the confirmation prompt with `-SkipBatteryCheck`

**Comment by conekeo** [comment]
@darobs Thanks!
@arsing Yes, I saw the warning.
