### ISSUE TITLE
No persistent connection between iothub and iotedge runtime

### ISSUE THREAD

**Issue by payalgaikwad42** [Azure/iotedge#1367]
Hi @Alberto-Vega-MSFT, 
I have iotedge runtime 1.0.7.1 installed on my 4 systems and each system have 9 iotedge modules deployed on it including edgeHub and edgeAgent. 
Scenario:
We have iotedge devices acting as a gateway. 
By invoking the direct method on one of the module (SocketClient) we are controlling smart iot devices e.g light switch from mobile app. 
we are managing the state of deployed iotedge modules(connected or disconnected) by generating events for each module on iothub. 
so if anyone of the module is in disconnected state then we are displaying the message as "Gateway disconnected" on mobile app. 
What we do is restart the iotedge again and control the device. 

Issue:
We are getting gateway disconnected messge more frequently. after an hour on average.
we have to restart the gateway after every 1 or 2 hrs.  
when I see  "IoT Edge hub connections" on portal one or more modules are in disconnected state. 
This is not feasible as we are doing development for client application. 
Also when checked from VS code I see edgeHub and edgeAgent into disconnected state hence messaging through edgehub gets interrupted as well.   
 
Can anyone help by looking into this issue ?
As why the iotedge module are unable to hold continuous connected with iothub?
Is this the issue with new release of iotedge as we are facing this issue after updating the version of iotedge to 1.0.7.1 ?

**Comment by darobs** [comment]
Hello @payalgaikwad42,

Thank you for reporting this.

May I get the platform architecture/OS, which protocol you're using, and which SDK versions you are using for your modules and devices?

Thanks in advance,

**Comment by veyalla** [comment]
Which language are your modules written in? If they are C#, what version of the Device client SDK are they using?

**Comment by payalgaikwad42** [comment]
@veyalla @darobs 
OS - Linux (ubuntu 16.04)
SDK version of device client - 1.7.0 for nodejs , 1.17.0 for java, 1.20.2 for C#
I observed this variation in sdk version today only. Should all of them have same version ?
Protocol used - mqtt
I have modules return in C#, nodejs and java.

**Comment by payalgaikwad42** [comment]
I have checked the state of iotedge modules on terminal and vs code both gives different output as given below: 


![vsode](https://user-images.githubusercontent.com/42204123/59915083-67617e00-9439-11e9-9970-c815b37aa23d.png)
![listdevice](https://user-images.githubusercontent.com/42204123/59915090-6b8d9b80-9439-11e9-9d0f-3b7022e9e81b.png)


And i am guessing because of this I am unable to use offline capability of iotedge in my application. 
because I am testing offline capability and observing that no messages are getting sent to iothub when iotedge is in offline mode and again connected to internet.

**Comment by payalgaikwad42** [comment]
@veyalla 
i noticed one more problem regarding disconnected state of the iotedge modules- 
offline state modules are not getting saved in edgeHub in order to send them to iothub when iotedge device goes online. 
I was able to find these logs of edgeHub but couldn't figure them out. 
[edgehublogs.txt](https://github.com/Azure/iotedge/files/3314009/edgehublogs.txt)

**Comment by varunpuranik** [comment]
Hi @payalgaikwad42 , a few questions - 

- Can you please elaborate how you check if the module has connectivity? Does the module send messages, or do you invoke a method from the cloud, or is it something else?
- What do you mean by this - "offline state modules are not getting saved in edgeHub". Can you also describe how you concluded that? From the logs, it seems like EdgeHub lost connectivity, and it was not restored till it was restarted.
- You mentioned installing Edge runtime version 1.0.7.1. But from the screenshot, looks like you are deploying EdgeHub and EdgeAgent versions 1.0. Can you please check the actual version running on the device? It should be at the beginning of the logs for both modules. Else you can just specifically deploy the 1.0.7.1 version of both modules. 
- And lastly, can you please run iotedge check and paste the output here? https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#run-the-iotedge-check-command

**Comment by payalgaikwad42** [comment]
- We get event at IoTHub whenever any of the module gets disconnected or connected and then wwe store this state into database. Usong event feature on IoTHub. 

![deviceevent](https://user-images.githubusercontent.com/42204123/60070502-92e3b180-9734-11e9-900a-640bee7b89d3.png)



- By this "offline state modules are not getting saved in edgeHub" I meant to say, I am assuming that when edgeHub looses its connectivity it is not able to save the messages it receives from other modules in order to send them to IoTHub. 

- The Version i am using for both edgeHub and edgeAgent is correct 1.0.7.1
![image](https://user-images.githubusercontent.com/42204123/60070089-0a184600-9733-11e9-8c18-a6889313a4b2.png)
![image](https://user-images.githubusercontent.com/42204123/60070108-169c9e80-9733-11e9-9118-4cb34c8fee9e.png)



- This is the output of sudo  iotedge check : 

![image](https://user-images.githubusercontent.com/42204123/60069765-c07b2b80-9731-11e9-97db-bae464badb42.png)

- This is the output of sudo iotedge check --verbose
![image](https://user-images.githubusercontent.com/42204123/60070199-6a0eec80-9733-11e9-809d-cba0fd3bff0b.png)

- In the check it is saying "caused by: Could not open container engine config file /etc/docker/daemon.json" what does that means?

**Comment by payalgaikwad42** [comment]
@varunpuranik Hi, 
When I disconnect my iotedge gateway to test offline capability there are few things i am observing:
1. My module nodepipe sends the message to iothub even when the iotedge is in disconnected state
these are the message sent via nodepipe to iothub (through edgehub) when iotedge device was disconnected from internet. 
![image](https://user-images.githubusercontent.com/42204123/60151725-79f20380-97fb-11e9-8459-2196689d42c9.png)
2. After i connect edge device to internet i am able to see devices are in running and connected state from portal and from teminal but that state is not getting reflected in vs code. I am guessing because of that i am not able to use monitor the build in endpoints feature of vs code. 

![image](https://user-images.githubusercontent.com/42204123/60151868-fedd1d00-97fb-11e9-9b9f-fea6dd6234da.png)
![image](https://user-images.githubusercontent.com/42204123/60151888-13211a00-97fc-11e9-8a1a-2b62b75ece76.png)
![image](https://user-images.githubusercontent.com/42204123/60151890-174d3780-97fc-11e9-85a0-20aa062a47cc.png)


All these screenshots are of the same time.

**Comment by payalgaikwad42** [comment]
@veyalla  @varunpuranik @darobs 
Any updates on this?

**Comment by veyalla** [comment]
I am having trouble understanding what the problem actually is? Messages not being delivered or VS Code not showing up as connected?

Note, after coming back online, it can take 10-15min before connectivity to edge modules is re-established and messages are forwarded.

**Comment by payalgaikwad42** [comment]
> Note, after coming back online, it can take 10-15min before connectivity to edge modules is re-established and messages are forwarded.

@veyalla Thanks for this information. 
I was concern about why iotedge does not connect to iothub immediately after coming back online. 

> I am having trouble understanding what the problem actually is? Messages not being delivered or VS Code not showing up as connected?

My concern is now, 
When iotedge is online iotedge list commands shows all the modules in running state but when checked from VS code some modules shows disconnected state.
My question is, even when the device is online why modules looses connection (average time after every 2 hrs)with the iothub? 
Why edgeHub and edgeAgent are unable to maintain persistent connection with iothub?

And it takes more than 10 to 15 mins to regain the connectivity on its own. 
I am seeing this issue with new version of iotedge (1.0.7.1)
previously i have used iotedge and it used to run straight for more than 12hr without loosing connection.

**Comment by BewaControl-ReneDivossen** [comment]
@veyalla: Do you consider 10-15 min for reconnecting as satisfactory and leave it at that or are you working on speeding this up in the upcoming release?
As far as I remember, reconnecting was way faster with 1.0.6 (but unfortunately very unreliable).

**Comment by veyalla** [comment]
We are looking into it, but do not consider it a blocker. 

From your scenario point-of-view, is the current behavior acceptable?

**Comment by veyalla** [comment]
@payalgaikwad42 We cannot repro the edge modules not being able to maintain a persistent cloud connection. Is it possible that your network is going down sporadically?

Currently, the recommended way to monitor connection to your device is via IoT Hub/Event Grid DeviceDisconnected notifications. See: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-event-grid#event-types

I recommend using this instead of VS code based manual monitoring.

**Comment by BewaControl-ReneDivossen** [comment]
@veyalla: For us reliability is the top priority.  Offline times must not cause loss of messages and the edge device (including all modules) must reconnect without human interaction.   If this is only possible with the given 10-15 min reconnection time we'll have to live with it for now.  

One problem we see is unstable internet connections with frequent outages. If for example there is a short outage every 10 minutes the edge device might never reconnect.

**Comment by Maher4Ever** [comment]
@veyalla Can you imagine how frustrating it is for users when they need to wait for 15 minutes to be able to turn on/off their lights after a disconnection? How infuriating/scary it is for a parent to have to wait for 15 minutes before being able to check up on your infant child just because the camera feed is offline?

The ramifications of this issue are huge and discourage the use of the IoT Edge platform for any serious product. The fact that this issue still happens months after it's been reported is really mind-boggling.

You point to a URL that describes how to monitor the connection. That's *not* the issue! The issue is that IoT Edge modules take 15 minutes to reconnect.
