### ISSUE TITLE
Powershell: The running command stopped because the preference variable "ErrorActionPreference" ...

### ISSUE THREAD

**Issue by conekeo** [Azure/iotedge#1373]
Hi there! 

I try to automatize the installation IoT Edge using C# + powershell. I created a console app for testing purpose.

c# console app code:
```
   static void Main(string[] args)
        {
            string deviceConnectionString = "HostName=xxxx;DeviceId=xxxx;SharedAccessKey=xxxxxx";

            Console.WriteLine("Start Installation - IoTEdge!");

            PowerShell ps = PowerShell.Create();

            ps.AddScript(@". {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; Deploy-IoTEdge -SkipBatteryCheck:$true");
            ps.AddScript(@". {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; Initialize-IoTEdge -DeviceConnectionString "+ deviceConnectionString);

            ps.Invoke();

            Console.WriteLine("Completed!");
            Console.ReadKey();
        }
```

## Current Behavior
I got this error:

`The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\Program Files (x86)\iotedge\config.yaml' because it does not exist.`

any idea?

### Device (Host) Operating System
Windows 10 Enterprise

**Comment by arsing** [comment]
>`Cannot find path 'C:\Program Files (x86)\iotedge\config.yaml`

You're using 32-bit PS, presumably because your C# application is targeting 32-bit.

It's fixed by 76eacaf988e7d421b4e45c70a45d8160f1feaaa1. Meanwhile, you can work around it by compiling your C# application for 64-bit.

**Comment by arsing** [comment]
(Apart from that, you don't need to run `Deploy-` and `Initialize-` separately, since `Install-` does that for you anyway.)

**Comment by darobs** [comment]
Hello @conekeo,

These two commands work if you execute them consecutively?

You may want to double check Powershell is running as x64: See [here](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#install-and-configure-the-iot-edge-service).

(Get-Process -Id $PID).StartInfo.EnvironmentVariables["PROCESSOR_ARCHITECTURE"]

**Comment by conekeo** [comment]
Thanks @arsing @darobs . It's working. I was able to run my console app in x64 and use  Install- instead
` ps.AddScript(@". {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; Install-IoTEdge  -SkipBatteryCheck:$true -Manual -DeviceConnectionString '" + deviceConnectionString + "'");
`
