### ISSUE TITLE
How can i proceed with Unit testing in IoT edge Modules?

### ISSUE THREAD

**Issue by AmitBarthwal** [Azure/iotedge#1380]
I am looking for Writing my Unit test cases for the IoT edge module in Node.js.
Do anyone have some sample Unit test for ioT edge module with module method call test , module twin test..

### Device (Host) Operating System
 Ubuntu 18.04

### Architecture
 amd64
### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.6.1

#### Docker
Docker version 3.0.3

**Comment by darobs** [comment]
In general, our containerized modules have unit tests which we run as part of the checkin pipeline, plus a few integration tests, and then we do end-to-end tests on a nightly basis, but none of our project's production code is Node.js.

May I suggest the Azure IoT SDK for node project for ideas? For example, [end-to-end tests](https://github.com/Azure/azure-iot-sdk-node/tree/master/e2etests/test).

**Comment by AmitBarthwal** [comment]
Thanks darobs for your inputs..

The link you have provided for unit test in node.js, i tried the same but i need to understand where these unit test code importing the actual code for unit testing.

As i can see for module-method.js unit test, it is creating the module and then testing the methods.
Could you please share me your inputs on the same.

**Comment by ancaantochi** [comment]
Each project has unit tests, for example edge hub: [https://github.com/Azure/iotedge/tree/master/edge-hub/test](https://github.com/Azure/iotedge/tree/master/edge-hub/test)

If you have questions about nodejs unit tests, please open an issue on the github that David sent, they know the details about that.

**Comment by ancaantochi** [comment]
Closing this issue because no comments for a while, please reopen if you have other questions
