### ISSUE TITLE
Need info on AmqpWs and MqttWs on Port 443

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1385]
Hi,

I am trying to configure edge gateway to use Mqtt over web-socket which use 443 port. But still i can see it is not working with below configuration.

Done following configuration-

- deployment.template.json-

>         "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": {}
            },
            "env": {
              "UpstreamProtocol": {
                "value": "MqttWs"
              }
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            },
            "env": {
              "UpstreamProtocol": {
                "value": "MqttWs"
              }
            }
          }
        },

- Configuration in config.yaml -

> agent:
  name: "edgeAgent"
  type: "docker"
  env:
    UpstreamProtocol: "MqttWs"
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}

- Configuration in custom module in code-

>             MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Mqtt_WebSocket_Only);
            ITransportSettings[] settings = { mqttSetting };

After all these configuration, still i can't see modules are running. Only module is running that is edgeAgent.

Can you please let me know the root cause for the same.

Thanks

**Comment by arsing** [comment]
Please edit your issue to use the issue template.

**Comment by ancaantochi** [comment]
Closing this issue because of no reply for more than 10 day. Please reopen if you still have this issue.
