### ISSUE TITLE
Question - Is it possible to control the process or access some files in Host OS from C# IoT Edge Module.

### ISSUE THREAD

**Issue by vjrag** [Azure/iotedge#1389]
Is it possible to control the process running in Host OS (for eg. start or stop c# console application) and access / change files in host machine folders for eg (txt file available in /home/user/folder1) from C# IoT Edge Module ?

**Comment by mrohera** [comment]
To access host files from your container or vice versa you can explore volume mounts. Here is some documentation about that: https://docs.docker.com/storage/volumes/

Also here is an example of volume mounts configured and used for the IoT Edge: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-store-data-sql-server#add-a-sql-server-container

As far as a host process communicating with your application running in a container, you could use domain sockets for example to achieve this. You would have to mount this socket into your application's container and use that to transport your inter application messages.

**Comment by ancaantochi** [comment]
Closing this issue because it didn't have any comments for than 10 days. Please reopen if the commment didn't answer your questions.
