### ISSUE TITLE
Powershell IoT Edge Installation commands in run via UWP app?

### ISSUE THREAD

**Issue by conekeo** [Azure/iotedge#1401]
Hi,
I'm trying to to modify the IoT Core Default App (UWP)  to start the Iot Edge installation commands via Powershell.
https://github.com/Microsoft/Windows-iotcore-samples/tree/master/Samples/IoTCoreDefaultApp

I encountered some problem because the library that run Powershell  System.Management.Automation is not supported.
```
Error	NU1202	Package System.Management.Automation 6.2.1 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-arm-aot. Package System.Management.Automation 6.2.1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)	
```

It there a way to run Powershell IoT Edge Installation commands in UWP app?
Any others possibles solutions?

```
string deviceConnectionString = "HostName=xxx.azure-devices.net;DeviceId=xxxTestEdge;SharedAccessKey=xxxxx";

            Console.WriteLine("Start Deploy - IoTEdge!");

            InitialSessionState iss = InitialSessionState.CreateDefault();
            Runspace rs = RunspaceFactory.CreateRunspace(iss);
            rs.Open();
            PowerShell ps = PowerShell.Create();
            ps.Runspace = rs;

            ps.AddScript(@". {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; Install-IoTEdge -Manual -SkipBatteryCheck:$true -DeviceConnectionString '" + deviceConnectionString + "' -RestartIfNeeded");


            ps.Invoke();
```

## Steps to Reproduce
Create a blank UWP project.

## Expected Behavior
Be able to run IoT Edge installation commands via an UWP app/a modified  IoT Core Default App on Windows IoT Core.

### Device (Host) Operating System
Windows 10 Enterprise
Visual Studio 2017
Target and Min: Windows 10, version 1809 (build 17763)

**Comment by kgremban** [comment]
@TerryWarwick Please take a look. Thanks!

**Comment by TerryWarwick** [comment]
On the surface it looks to me like the app you are modifying is using the 15063 app contract.  Try updating the app contract to 17763 and see if it makes any difference.

**Comment by conekeo** [comment]
@TerryWarwick To be sure, I tried with a blank UWP with Target and Min: Windows 10, version 1809 (build 17763) and still got the error that the Package System.Management.Automation is not compatible.

**Comment by jiria** [comment]
System.Management.Automation is not support for UWP profile. Can you instead start PowerShell process and have it run the script from the UWP?

**Comment by conekeo** [comment]
@jiria  Nothing happen when running Powershell process in UWP app, but the same code it work when running via a console app.

script.ps1:

```
. {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; Install-IoTEdge -Manual -SkipBatteryCheck:$true -DeviceConnectionString 'HostName=xxxx.azure-devices.net;DeviceId=xxxTestEdge;SharedAccessKey=xxxx='
```
source code:

```

async void OnInstallIoTEdgeButton_Clicked(object sender, RoutedEventArgs e)
        {
           var ps1File = @"C:\runpowershellscript\script.ps1";

           //* Create Process
            Process process = new Process();
            process.StartInfo.FileName = "powershell.exe";
            process.StartInfo.Arguments = $"-NoProfile -ExecutionPolicy unrestricted \"{ps1File}\"";
            process.StartInfo.UseShellExecute = false;
            process.StartInfo.RedirectStandardOutput = true;
            process.StartInfo.RedirectStandardError = true;
            //* Set your output and error (asynchronous) handlers
            process.OutputDataReceived += new DataReceivedEventHandler(OutputHandler);
            process.ErrorDataReceived += new DataReceivedEventHandler(OutputHandler);
            //* Start process and handlers
            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();
            process.WaitForExit();

}

static void OutputHandler(object sendingProcess, DataReceivedEventArgs outLine)
{
            Debug.WriteLine(outLine.Data);
}


```

any idea?

**Comment by jiria** [comment]
Just guessing, did you add the Centennial declaration into your app manifest?

**Comment by conekeo** [comment]
@jiria  No Centennial declaration in my app manifest. I just created a blank UWP app with a button for testing purpose right now.

app manifest:
```
<Capabilities>
    <Capability Name="internetClient" />
    <iot:Capability Name="systemManagement" />
  </Capabilities>
```

**Comment by conekeo** [comment]
I found this ProcessLauncherSample (UWP app) example from  https://github.com/microsoft/Windows-iotcore-samples/tree/develop/Samples/ExternalProcessLauncher/CS

I deployed the ProcessLauncherSample  app to WIndows IoT Core for testing.


I add powershell.exe to the allow list of the device:
```
reg.exe ADD "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\EmbeddedMode\ProcessLauncher" /v AllowedExecutableFilesList /t REG_MULTI_SZ /d "c:\windows\system32\cmd.exe\0c:\windows\system32\ipconfig.exe\0c:\windows\system32\tlist.exe\0c:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe\0"
```

Running ommand `c:\windows\system32\ipconfig.exe` without argument is working.
But I got and access denied error when trying to run this command: `c:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`

arguments:
`get-date`

access denied error:
```
Make sure you're allowed to run the specified exe; either
1) Add the exe to the AppX package, or\n
2) Add the absolute path of the exe to the allow list:                                        HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\EmbeddedMode\\ProcessLauncherAllowedExecutableFilesList.
Also, make sure the <iot:Capability Name=\"systemManagement\" /> has been added to the AppX manifest capabilities.
```

my app manifest contains `<iot:Capability Name=\"systemManagement\" /> `

any idea why I'm not able to run powershell? Without this command I cannot run IoT Edge installation command via an UWP app.

**Comment by conekeo** [comment]
I found a solution!  You can test this by using the console module installed in Windows IoT Core.
The console use `c:\windows\system32\cmd.exe`.

I created a Powershel script with IoT Edge command (c:\test\test.ps1) in the device:

```
. {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression;Install-IoTEdge -Manual -SkipBatteryCheck:$true -DeviceConnectionString 'HostName=xxxx.azure-devices.net;DeviceId=xxxTestEdge;SharedAccessKey=xxx' -RestartIfNeeded
```
I called in the console command prompt:
```
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& 'c:\test\test.ps1'"
```
