### ISSUE TITLE
PATH is not updated on IoTCore before second reboot for additional sessions

### ISSUE THREAD

**Issue by jiria** [Azure/iotedge#1404]
## Expected Behavior
After running Deploy-IoTEdge and Initialize-IoTEdge on IoTCore, I should be able to run iotedge list from any new remote PS session.

## Current Behavior
After running Deploy-IoTEdge and Initialize-IoTEdge on IoTCore, I can run iotedge list only from the first session, but not from additional sessions. This is because Set-SystemPath requires reboot on IoTCore to apply the change machine wide. 

Perhaps the Set-SystemPath can be moved into Deploy-IoTEdge, which needs to reboot on IoTCore anyway and as such, would initialize the path right away. A concern could be to make sure to delete the addition in case Deploy-IoTEdge fails.

**Comment by arsing** [comment]
>Perhaps the Set-SystemPath can be moved into Deploy-IoTEdge, which needs to reboot on IoTCore anyway and as such, would initialize the path right away.

Yeah, that makes sense.

>A concern could be to make sure to delete the addition in case Deploy-IoTEdge fails.

It can be done at the end of `Deploy-` so that rollback is not a problem.

---

Would you like to send a PR?

**Comment by jiria** [comment]
I will probably not get to this any time soon :(
