### ISSUE TITLE
Docker.service fails when deploying to Raspberry Pi B2

### ISSUE THREAD

**Issue by njbuch** [Azure/iotedge#1405]
## Expected Behavior

The docker.service is expected to start, enabling iotedge to run.

## Current Behavior

The docker.service installed with the iotedge install instructions does not work on this model of Raspberry.

## Steps to Reproduce

1. Install Stretch on the Raspberry 
2. Install newest updates and reboot
3. Install iotedge according to official install instructions and reboot
4. Wait for it... it never starts

## Context (Environment)
Raspberry Pi Model B Rev 2

### Output of `iotedge check`
Cannot run.

<details>
<summary>Click here</summary>

```
// Paste here
```
</details>

### Device (Host) Operating System

Raspian Stretch with newest updates.

### Architecture

armv61

#### Docker

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by arsing** [comment]
Neither Moby nor IoT Edge support arm32v6 devices, only arm32v7.
