### ISSUE TITLE
IoT Edge Runtime (Agent, Hub) env options

### ISSUE THREAD

**Issue by JihongL** [Azure/iotedge#1407]
I wonder what options are available for edgeAgent and edgeHub.
I found some options like `https_proxy`, `UpstreamProtocol`, `RuntimeLogLevel` in docs.
These are only options for edgeAgent?
If another available options for edgeAgent or Hub, Please let me know.

**Comment by arsing** [comment]
As far as documented, and thus supported, options go, you have https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support + https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist + https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot . Together they account for these Edge Agent env vars:

- `RuntimeLogLevel`
- `UpstreamProtocol`
- `https_proxy`

and these Edge Hub env vars:

- `OptimizeForPerformance`
- `RuntimeLogLevel`
- `UpstreamProtocol`
- `amqpSettings__enabled`
- `httpSettings__enabled`
- `https_proxy`
- `mqttSettings__enabled`

---

You can of course read the code to discover other settings, but it may be unsupported to set them.
