### ISSUE TITLE
IoT Edge install fails on Raspian Buster - error while loading shared libraries: libssl.so.1.0.2

### ISSUE THREAD

**Issue by nanowireUK** [Azure/iotedge#1408]
## Expected Behavior
Used the guide at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm to install moby and iotedge on a fresh install of Raspbian Buster.

Install should run through and I should be left with a working iotedge installation.

Confirmed it is working on Raspbian Stretch.

## Current Behavior
Install runs through as expected but any iotedge commands result in the error:
`iotedge: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory`

## Steps to Reproduce
1. Set up an SD Card with Raspbian Buster
2. Follow the guide https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm to install Moby and iotedge
3. Optional reboot - makes no difference
4. Run `sudo iotedge list`

### Output of `iotedge check`

`iotedge: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory`

### Device (Host) Operating System
Raspberry Pi 3 Model B Rev 1.2
Linux raspberrypi 4.19.50-v7+ armv7l
Version:June 2019
Release date:2019-06-20
Kernel version:4.19

### Architecture
arm32

### Container Operating System
Linux

#### iotedged
1.0.7.1

#### Edge Agent
N/A - doesn't get this far

#### Edge Hub
N/A - doesn't get this far

#### Docker
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 23:28:44 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Fri Apr 19 07:14:38 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Logs
```
Jul 03 14:21:56 raspberrypi iotedged[793]: /usr/bin/iotedged: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=127/n/a
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Service RestartSec=100ms expired, scheduling restart.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 1.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.socket: Succeeded.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.mgmt.socket: Succeeded.
Jul 03 14:21:56 raspberrypi iotedged[798]: /usr/bin/iotedged: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=127/n/a
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Service RestartSec=100ms expired, scheduling restart.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 2.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.mgmt.socket: Succeeded.
Jul 03 14:21:56 raspberrypi systemd[1]: iotedge.socket: Succeeded.
Jul 03 14:21:57 raspberrypi iotedged[802]: /usr/bin/iotedged: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=127/n/a
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Service RestartSec=100ms expired, scheduling restart.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 3.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.mgmt.socket: Succeeded.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.socket: Succeeded.
Jul 03 14:21:57 raspberrypi iotedged[809]: /usr/bin/iotedged: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=127/n/a
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Service RestartSec=100ms expired, scheduling restart.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 4.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.mgmt.socket: Succeeded.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.socket: Succeeded.
Jul 03 14:21:57 raspberrypi iotedged[823]: /usr/bin/iotedged: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=127/n/a
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Service RestartSec=100ms expired, scheduling restart.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 5.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.socket: Succeeded.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.mgmt.socket: Succeeded.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Start request repeated too quickly.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.mgmt.socket: Failed with result 'service-start-limit-hit'.
Jul 03 14:21:57 raspberrypi systemd[1]: iotedge.socket: Failed with result 'service-start-limit-hit'.
```

**Comment by darobs** [comment]
Hello @nanowireUK 

Thank you for bringing this to our attention.

It looks like Raspbian Buster has updated the version of OpenSSL to 1.1 and has dropped 1.0 libraries entirely - and that means it looks like we need to build new packages to support it. I'll add this task to our backlog.

As a temporary workaround, you can install the 1.0.2 packages from here:
https://packages.debian.org/stretch/libssl1.0.2
or the Raspbian stretch repo.

**Comment by renshan2** [comment]
I have the exactly same issue. Can you let me know when the new package becomes available?

Thank you!

**Comment by arsing** [comment]
(Marking as enhancement because Debian 10 + derivatives are not [supported](https://docs.microsoft.com/en-us/azure/iot-edge/support#tier-1) at the moment.)

**Comment by kpm-at-hfi** [comment]
Following... new package would be great, thanks!

**Comment by OrangeGeek** [comment]
Following as well...

**Comment by darobs** [comment]
It looks like libssl1.0.2 is present in the release version of Buster.  I was able to do 
```sh
sudo apt-get install libssl1.0.2
```
successfully.  I was able to install iotedge after that.

**Comment by arsing** [comment]
#1473 modifies our packaging code in a way that makes it easier to add new distros and arches that have functioning cross compilers in their repos. This includes Debian 10, so that PR adds Debian 10 as well.

If anyone wants to test it out, take that PR and run `VERSION=1.0.9 PACKAGE_OS=debian10 PACKAGE_ARCH=aarch64 ./edgelet/build/linux/package.sh` from the repo root. You should get `./edgelet/target/hsm/libiothsm-std_1.0.9-1_armhf.deb` and `./edgelet/target/aarch64-unknown-linux-gnu/release/iotedge_1.0.9-1_armhf.deb` that have been compiled on Debian 10 and link to `libssl1.1`

**Comment by mjrousos** [comment]
I ran into this as well, but found that `sudo apt-get install libssl1.0.2` works around it.

**Comment by arsing** [comment]
#1473 is now merged, so as mentioned in https://github.com/Azure/iotedge/issues/1408#issuecomment-514924228 you can now build Debian 10 packages for `iotedge` and `libiothsm-std` with:

- `PACKAGE_OS=debian10 PACKAGE_ARCH=arm32v7 ./edgelet/build/linux/package.sh`, or
- `PACKAGE_OS=debian10 PACKAGE_ARCH=aarch64 ./edgelet/build/linux/package.sh`

depending on what distro you're running on your Pi.

The generated binaries will link to openssl 1.1, and more importantly the packages will have a dependency on the `libssl1.1` package. So `apt` will install it automatically if you didn't already have it.

Note that regardless of that script making it easy to build the packages, as of now we haven't decided to officially support Debian 10 / Raspbian Buster as [a tier 1 platform.](https://aka.ms/iotedge-platsup#tier-1)

**Comment by asishsinha** [comment]
> It looks like libssl1.0.2 is present in the release version of Buster.  I was able to do
> sudo apt-get install libssl1.0.2
> successfully.  I was able to install iotedge after that.

Stumbled on the same problem and the above workaround worked.

$ sudo dpkg -i libiothsm-std_1.0.8-2_armhf.deb
$ sudo apt-get install libssl1.0.2
$ sudo dpkg -i iotedge_1.0.8-2_armhf.deb

**Comment by arsing** [comment]
1.0.9-rc1 has been released.
