### ISSUE TITLE
How do i send messages to IoTHub via user-defined partition using IoTHub REST API

### ISSUE THREAD

**Issue by keshav1git** [Azure/iotedge#1414]
I'm able to send messages to IoTHub but messages by default  goes to partition "2" , how do make messages to go to partition "0". 

## Expected Behavior
should be able to send messages to IoTHub with `partition configuration` provided by user in REST Api

## Current Behavior
I'm sending messages to IoTHub **ONLY** to partition "2"  using REST API 

## Steps to Reproduce
used reference from [link](https://docs.microsoft.com/en-us/rest/api/iothub/device/senddeviceevent)

## Context (Environment)
I'm able to send messages to IoTHub but messages by default  goes to partition "2" , how do make messages to go to partition "0". 

#### iotedged
IoT-edge version 1.0.7.1

#### Edge Agent
Edge Agent version 1.0.7.1

#### Edge Hub
Edge Hub version 1.0.7.1

#### Docker
docker version -18.09.06

**Comment by myagley** [comment]
IoT Hub hashes the device id to determine what partition to write the message to. There is no current way to change this behavior or to specify a different partitioning scheme. The reason this is the case is to preserve message ordering per device.

Can you discuss your scenario a little more? What would you like to achieve by specifying the partition?

**Comment by keshav1git** [comment]
I figured out that there were two ways i can send messages to IoTHub:
1) using azure IoTHubClient (azure-iothub-device-client)
2) IoTHub REST api

scenario 1 :

when i use IoTHubClient  from xyz_device to send  telemetry messages, it were being received by IoTHUB at partition "0".

scenario 2 :
when i use  IoTHub REST api mechanism from same xyz_device to send  messages to IoTHUb it were being received by IoTHUB at partition "2".

so i wanted to know whether i can configure partition in iothub rest point 
something like  :
```
 api = "https://<IOTHUB_NAME>.azure-devices.net/devices/xyz_device/messages/events?api-version=<IOTHUB_API_VER>?SEND_TO_PARTITION="0/2"
```

**Comment by lt72** [comment]
@darobs can you please answer question above and close issue?

**Comment by darobs** [comment]
Hello @keshav1git,

@myagley is correct, there is no current way to change this behavior or to specify a different partitioning scheme.  

If you think that assigning a partition is a useful or needed feature, you can [provide this as feedback to the IoT Hub User Voice](https://feedback.azure.com/forums/321918-azure-iot).

To alleviate the concern in your scenario, the hash to the the partition is set in the service and it is a function of the deviceid and the partition count. The partition will only change for a given device if the number of partitions has changed. It should **not** changed based on how the API is called.  If you have seen this, please report back to us or raise a issue through Azure Support.
