### ISSUE TITLE
Sending messages between two IoT Edge devices run on different machines

### ISSUE THREAD

**Issue by yuceturkomer** [Azure/iotedge#1415]
Hi there!

Is it possible to communicate between two different IoT Edge Devices(on different boards) that are on same local network, using similiar structure used for communication of two modules by editing route configurations? I want two IoT Edge devices to communicate safe locally, without going to the cloud side.

 Something like:
```
...
"routes": {
    "DevAtoDevB": "FROM <Device A Outputs> INTO <Device B Inputs>"
},
...
```

Kind Regards

**Comment by arsing** [comment]
Not using Edge Hub. It would require chaining Edge Hub to Edge Hub which is not something we support. You would have to use a custom mechanism to have the modules talk to each other.

**Comment by yuceturkomer** [comment]
Okay, thanks for the response. I'm closing the issue.
