### ISSUE TITLE
RuntimeError: No access to /dev/mem. Try running as root!

### ISSUE THREAD

**Issue by solankigithub** [Azure/iotedge#142]
I have created my own blink.py program to blink an LED.
Now i would like to deploy this program from Azure IOT Edge (Azure portal)
All the steps are captured in the below link:
https://stackoverflow.com/questions/51769717/not-able-to-deploy-python-program-from-azure-iot-edge-to-rasberry-pi/51782444#51782444

**Comment by myagley** [comment]
Hello. To get this working, you will need to add the device (`/dev/mem`) to the container. You can do this by adding it to the `createOptions` field in the portal as part of the deployment. Something like this should work:

```json
{
    "HostConfig": {
        "Devices": [
            {
                "PathOnHost": "/dev/mem",
                "PathInContainer": "/dev/mem",
                "CgroupPermissions": "rwm"
            }
        ]
    }
}
```

The full list of available options are here: https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate

![image](https://user-images.githubusercontent.com/833747/43966014-9c242726-9c75-11e8-924a-98cdf577e2b0.png)

**Comment by solankigithub** [comment]
Thanks Mike,
It worked after giving the 
```
{
    "HostConfig": {
        "Devices": [
            {
                "PathOnHost": "/dev/gpiomem",
                "PathInContainer": "/dev/gpiomem",
                "CgroupPermissions": "rwm"
            }
        ]
    }
}

```
I had to change /dev/mem to /dev/gpiomem

Thanks for sharing the docker create link, but i would like to know more about how can i map these create options in "createOptions"

-Sandy

**Comment by solankigithub** [comment]
Issue resolved, thanks !
