### ISSUE TITLE
iotedged does not run because of missing /tmp/iotedge on default ubuntu installation

### ISSUE THREAD

**Issue by fmms** [Azure/iotedge#145]
## Expected Behavior
When following https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux I get a system where iotedged can be executed as soon as I have configured my connection string.

## Current Behavior
The deamon does not start succesfully
```
root@felix-Virtual-Machine:/home/felix# iotedged 
<6>2018-08-11T22:23:41Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2018-08-11T22:23:41Z [INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
<6>2018-08-11T22:23:41Z [INFO] - Using default configuration
<6>2018-08-11T22:23:41Z [INFO] - Using runtime network id azure-iot-edge
<6>2018-08-11T22:23:41Z [INFO] - Initializing the module runtime...
<6>2018-08-11T22:23:41Z [INFO] - Finished initializing the module runtime.
<6>2018-08-11T22:23:41Z [INFO] - Configuring /tmp/iotedge as the home directory.
<6>2018-08-11T22:23:41Z [INFO] - Configuring certificates...
<6>2018-08-11T22:23:41Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2018-08-11T22:23:41Z [INFO] - Finished configuring certificates.
<6>2018-08-11T22:23:41Z [INFO] - Initializing hsm...
<3>2018-08-11T22:23:41Z [ERR!] (/opt/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:get_base_dir:473) Directory path in env variable IOTEDGE_HOMEDIR is invalid. Found /tmp/iotedge
<3>2018-08-11T22:23:41Z [ERR!] (/opt/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision:1906) HSM base directory does not exist. Set environment variable IOTEDGE_HOMEDIR to a valid path.
<3>2018-08-11T22:23:41Z [ERR!] (/opt/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:hsm_client_crypto_init:43) Could not create store. Error code 1949
<3>2018-08-11T22:23:41Z [ERR!] - An hsm error occurred.
<3>2018-08-11T22:23:41Z [ERR!] - 	caused by: HSM failure
<3>2018-08-11T22:23:41Z [ERR!] - 	caused by: HSM Init failure: 44
```

## Steps to Reproduce
1. Install Ubuntu 18.04 in Hyper V
2. Follow https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux  
3. restart, just to be sure all environment variables are set as expected by the packages
4.  run iotedged the above error message will be displayed.

### Device (Host) Operating System
Ubuntu 18.04,

### Architecture
amd64

### Container Operating System
Linux Containers

#### iotedged
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Docker
```
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Mon Jun 25 20:43:05 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

## Additional Information

happy to provide more information. Btw. this seems similar to an issue at https://github.com/Azure/iot-edge-v1/issues/642 but that guy was not using Ubuntu.

**Comment by myagley** [comment]
Hello. Thanks for the issue report. This looks like a configuration issue. Can you please post your `config.yaml`? You can find this on the device as `/etc/iotedge/config.yaml`. Please be sure to redact your connection string before posting.

Typically, the daemon is started via `systemd`, using `systemctl`. (`systemctl restart iotedge`). You can see this in [Verify successful installation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux#verify-successful-installation). If you'd like to start the daemon in the foreground, you must pass a config file `iotedged -c config.yaml`. The recommended method is to use `systemd`/`systemctl`.

**Comment by fmms** [comment]
Ok, this was a user error. The variable is configured via homedir in config.yaml.
