### ISSUE TITLE
runtime.settings.loggingOptions format example? 

### ISSUE THREAD

**Issue by hubert-associates** [Azure/iotedge#1456]
I've found the descriptions, 

https://docs.microsoft.com/en-us/azure/iot-edge/module-edgeagent-edgehub#edgeagent-desired-properties
https://github.com/Azure/iotedge/blob/master/e2e_deployment_files/long_haul_deployment.template.json

but no success and no examples of the required syntax in  the $edgeAgent and $edgeHub 
properties.desired.runtime.settings.loggingOptions section.

would it be possible to put this in your long haul deployment template example, or just here?

Thanks

**Comment by avranju** [comment]
This is stringified JSON representation of Docker logging options. Its format is documented in the [Docker API reference](https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate) and should look like this:
```json
{
  "Type": "<type>",
  "Config": {
    "key1": "val1",
    "key2": "val2"
  }
}
```
As of Docker API version 1.30, the `Type` needs to be one of `json-file`, `syslog`, `journald`, `gelf`, `fluentd`, `awslogs`, `splunk`, `etwlogs` or `none`. The values inside `Config` depends on the log driver chosen in `Type`. You can find some general information on configuring logging drivers [here](https://docs.docker.com/config/containers/logging/configure/).

Here's an example using [`journald`](https://docs.docker.com/config/containers/logging/journald/):
```json
{
  "Type": "journald",
  "Config": {
    "labels": "location",
    "env": "TEST1, TEST2"
  }
}
```
When setting this in the Edge deployment you'd need to stringify the JSON, so it'd look like this:
```
"{\"Type\":\"journald\",\"Config\":{\"labels\":\"location\",\"env\":\"TEST1, TEST2\"}}"
```

**Comment by hubert-associates** [comment]
Big help. Many thanks.
