### ISSUE TITLE
Cannot update ConfigRefreshFrequencySecs for edgeAgent

### ISSUE THREAD

**Issue by gretasasso** [Azure/iotedge#1462]
Hi everyone, 
I have seen on iot hub's metric some strange values..  I have actually one edge ( raspberry) power on with only two modules running, edgeAgent and edgeHub. Other modules are currently stopped.
- Max Successful twin reads from devices --> one per hour
- Avg Response size of twin reads from devices  --> about 9.3 KB  one time each hour
- Total number of messages used --> it increased by about 30 messages every hour, probably because one twin read it will be count with block's size of 512 bytes

I want to reduce this messages.. 

I have already asked into  msdn's forum and tried to edit edgeAgent's env variable with :

`
"systemModules": {
          "edgeAgent": {
            "type": "docker",
            "env": {
              "ConfigRefreshFrequencySecs": {
                "value": 1800
              }
            },
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": "{}"
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "env": {
              "ConfigRefreshFrequencySecs": {
                "value": 800
              },
              "RuntimeLogLevel": {
                "value": "debug"
              }
            },
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": "{}"
            }
          }
        }
`

I also have tried to trigger  a redeployment of the edgeAgent editing the image value ( azureiotedge-agent:1.0.7 ) without any results.

**Comment by veyalla** [comment]
@varunpuranik can help.

**Comment by sergaz-msft** [comment]
Adding MSDN Thread where issue started being troubleshooted: https://social.msdn.microsoft.com/Forums/en-US/b764e691-4733-4caa-bf37-439471c02adc/number-of-messages-used-from-iot-edge?forum=azureiothub

**Comment by lt72** [comment]
@varunpuranik can you please make a recommendation, on MSDN issue as well?

**Comment by lt72** [comment]
Closing as stale. Latest work on metrics is available in 1.0.9 rc4
