### ISSUE TITLE
Azure IoT Edge Daemon (iotedge) Not working in windows

### ISSUE THREAD

**Issue by Ramji1411** [Azure/iotedge#1468]
I have been trying to get IOTEdge working on my Windows PC in a docker desktop. I am getting the following error and unable to solve yet even after referring to multiple solution options.

## Expected Behavior

After the container is deployed and the following command is executed, the IOTEDGE is expected to start working
{Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
>> Initialize-IoTEdge -ContainerOs Linux

## Current Behavior

I get the following error and the initialize command doesnt get completed

Start-Service : Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start service iotedge on computer '.'.
At line:1328 char:9
+         Start-Service $EdgeServiceName
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

## Steps to Reproduce

1. Followed the procedures explained in the below link
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-linux

## Context (Environment)
Windows 10 running Docker Desktop

### Output of `iotedge check`
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
× config.yaml has correct URIs for daemon mgmt endpoint
    Error: could not execute list-modules request: an error occurred trying to connect: Operation timed out (os error 110)
√ latest security daemon
√ host time is close to real time
√ container time is close to host time
‼ DNS server
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
× production readiness: certificates expiry
    Could not enumerate files under C:\ProgramData\iotedge\hsm\certs
‼ production readiness: container engine
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port
    Could not connect to EDAPTest.azure-devices.net:5671
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
× host can connect to and perform TLS handshake with IoT Hub MQTT port
    Could not connect to EDAPTest.azure-devices.net:8883
× container on the IoT Edge module network can connect to IoT Hub AMQP port
    Container on the azure-iot-edge network could not connect to EDAPTest.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS port
    Container on the azure-iot-edge network could not connect to EDAPTest.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port
    Container on the azure-iot-edge network could not connect to EDAPTest.azure-devices.net:8883
× Edge Hub can bind to ports on host
    Could not check current state of Edge Hub container

One or more checks raised errors. Re-run with --verbose for more details.
<details>
<summary>Click here</summary>

```
// Paste here
```
</details>

### Device (Host) Operating System
Windows 10

### Architecture

AMD 64
#### iotedged

iotedge 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
#### Docker

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fiotedge_moby_engine/v1.39/version: open //./pipe/iotedge_moby_engine: The system cannot find the file specified.
## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by varunpuranik** [comment]
@Ramji1411 ,
Can you please get the iotedge daemon logs by running the following command, and paste them here? That might tell us what is going on.
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Get-IoTEdgeLog

Also, from the iotedge check output, it looks like the Amqp and Mqtt ports are blocked on your device. This will prevent the IoT Edge runtime to not work properly, even if it is able to start up. Can you please unblock those ports and run iotedge check again?

**Comment by Ramji1411** [comment]
Hi Varun,
Thanks. I think it was a security related issue. I created a new Azure VM
with Windows 10 Pro Latest build and it worked fine.

Thanks
Ramji
