### ISSUE TITLE
Question: Can we read reported properties from device through module twin?

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1474]
Hi,

I am reporting some device information through module twin when module get started. This activity happening just once.

Is there any way to read last reported properties from device when module get restarted  all the time.

Thanks,
Prateek

**Comment by varunpuranik** [comment]
Hi @pratson20 ,
Yes, if you do a GetTwin operation from the module, you get the desired and reported properties in the module's twin. You can use that to check what reported properties were set by the module the last time. 
Hope that helps!

**Comment by pratson20** [comment]
hi @varunpuranik . Thank you for information.

I have one more question-
Running two modules- custom_module1 and custom_module2. Can we restart custom_module1 from custom_module2 ? If yes, then can you please share some reference.


Thanks

**Comment by varunpuranik** [comment]
Hi @pratson20 ,

No, one module cannot restart another module. That is by design - it is a security feature to prevent one module from interfering with operation of another module. 

Thanks.

**Comment by pratson20** [comment]
Thanks @varunpuranik 

Thanks for info. Closing this thread.
