### ISSUE TITLE
IoT Edge module receive messages over https from leaf devices

### ISSUE THREAD

**Issue by amogh79** [Azure/iotedge#1480]
## Expected Behavior

I want an IoT edge module which can receive messages over https from leaf devices. Once the messages are received on IoT edge the messages will be sent upstream to IoT Hub. 
Please help me with how this can be achieved.
I am potentially thinking of developing an web api as iot edge module not sure if that is possible.
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
C# and .Net core for development
IoT Edge on Ubuntu 18.04
### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
// Paste here
```
</details>

### Device (Host) Operating System

Ubuntu 18.04
### Architecture

amd64
### Container Operating System

Linux containers
#### Docker

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by veyalla** [comment]
Yes, that is possible. 

Check out the protocol translation pattern from our gateway docs:
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-as-gateway#patterns

**Comment by amogh79** [comment]
Thanks for your response.
I already checked that and saw that there is an example only for transparent gateway. I am more of looking into building an opaque gateway with the identity of IoT edge device on IoT hub. I want to create IoT edge modules which will support each of the following scenarios:

1. Leaf devices should be able to post messages to the edge module - Push via HTTP
2. IoT Edge module should be able to call a webhook on the leaf device - Pull via HTTP
3. Leaf devices should be able to post messages to the edge module - Push via MQTT 
4. Leaf devices should be able to post messages to the edge module - Push via KAFKA
5. IoT Edge module should be able to call a webhook on the leaf device - Pull via Modbus
6. IoT Edge module should be able to call a webhook on the leaf device - Pull via Bacnet

**Comment by veyalla** [comment]
The core logic of the module will be specific to its protocol and would be similar to any containerized application. The only additional piece is integration of Azure IoT SDK to use Azure IoT's identity and data plane features via the edgeHub module.

You can the modbus module as a reference:  https://github.com/Azure/iot-edge-modbus

**Comment by amogh79** [comment]
Thanks for the response.
How do I create module which can accept Http post requests? 
Do I need to create a web api hosted in core and forward the incoming post request to the iot edge module or the iot edge module itself can listen on https 443 and accept the incoming post request?
And if either or both of the above is possible what is the best way to do and how do I start with that? Please point me to examples or code samples for this.

**Comment by veyalla** [comment]
An edge module is just a docker container under the covers. Developing web applications using docker containers is not really in scope of this project. 

If you are using .NET, see https://dotnet.microsoft.com/learn/web/aspnet-microservice-tutorial/intro for guidance.

**Comment by ttll13** [comment]
Closing as it seems resolved.
