### ISSUE TITLE
Facing Problem while installing IoT edge for windows IoT core with TPM key

### ISSUE THREAD

**Issue by arnabhetc** [Azure/iotedge#1486]
Hi, I am trying to install azure IoT edge on aeon GW, running Windows IoT core 

I am using this link - https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows

there are two commands 

- one for the installation of IoT edge 

- the second one is for the DPS, with keys, 

generally while performing the second step, it asks for scope id and registration id and then built config.yaml file, 

what is happening?
It's not asking for the registration, it only asks for the scope id and then starts building the config.yaml file and gives the error that registration id is not there, but it never asked for it so, a

once the config.yaml is built with this half information, then there is no way to change it for IoT core I need to reinstall the IoT core image, I have tried twice showing the same thing 

I am attaching the logs for the details

[192.168.1.106]: PS C:\Data\Users\administrator\Documents> . {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; `
>> Initialize-IoTEdge -Dps

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Initialize-IoTEdge, Insta...

cmdlet Initialize-IoTEdge at command pipeline position 1
Supply values for the following parameters:
**ScopeId: 0ne*******F**
**The container host is on supported build version 17763.
Generating config.yaml..**.
**Initialize-IoTEdge : Exception calling "Invoke" with "1" argument(s): "RegistrationId is required for this DPS**
provisioning mode."
At line:2 char:1
+ Initialize-IoTEdge -Dps
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Initialize-IoTEdge], MethodInvocationException
    + FullyQualifiedErrorId : RuntimeException,Initialize-IoTEdge 

**I have already done this multiple times, never faced this issue, It was working with edge version- 1.0.7.1 and we are running gateway with the edge ,  but this week after the release of 1.0.8 facing this issue
**

@iotedge-ci @azure-keyvault  
<img width="960" alt="install issue" src="https://user-images.githubusercontent.com/47913360/62137780-28f69300-b304-11e9-8747-b68eb0deaf26.PNG">

**Comment by arsing** [comment]
>generally while performing the second step, it asks for scope id and registration id and then built config.yaml file,
>
>what is happening?

There are more ways to use DPS that just scope ID, so the parameter is optional.

> It's not asking for the registration, it only asks for the scope id and then starts building the config.yaml file and gives the error that registration id is not there, but it never asked for it so, a

If you invoke the commandlet without all required parameters it will interactively ask you for the parameters. `-ScopeId` is not a required parameter, so it will not ask you for it.

We need to fix the docs you linked to. But anyway the answer is quite simply to use the `-RegistrationId` parameter of the script if you want to set a registration ID.

**Comment by arsing** [comment]
Filed https://github.com/MicrosoftDocs/azure-docs/issues/36148
