### ISSUE TITLE
Module twin desired property version is not re-setting to 1 after remove and push the same module

### ISSUE THREAD

**Issue by manupradeep2000** [Azure/iotedge#1493]
Module twin desired property $version is not re-setting to 1 even after remove and push the same module in device. The $version of module twin is starting from 1 at azure portal if I remove and push the module. I am removing and pushing the module to device programmatically using the azure api 
"https://IOT-Kochi3.azure-devices.net/twins/{deviceid}/modules/{moduleid}?api-version=2018-06-30"
The desired properties are not updating to device till the $version of module twin property is equal in device and cloud.

## Steps to Reproduce

1. Created a module which use desired property "HBF".
2. Deployed the module to device with desired property "HBF":10.
3. Device is reading the desired property and can see the $version in device log is 1.
4. Update the desired property "HBF" in cloud 10 times and this will reach to device 10 times.
5. Remove the module from device and push the same module once again to device.
6. Can the see the $version of module twin as 11, where the $version of module twin in Azure portal would be 1.
7. If we are doing any update in the module twin property "HBF", it will not reach to device until the $version of module twin of Azure portal reach 11.

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
Latest available 

#### Docker

**Comment by myagley** [comment]
What version of the Edge Hub are you using? This should have been fixed in 1.0.8.

**Comment by manupradeep2000** [comment]
Thanks. I have updated the version to 1.0.8 and now it is working as expected.

**Comment by myagley** [comment]
I'm glad you got it working. I'm going to close this issue, but please feel free to reopen if you have more questions.
