### ISSUE TITLE
Does IoT Edge module can access data from Sql server using TLS?

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#1510]
Hi,

I have got couple of IoT Edge modules (running in linux container) and writing data to Sql database using TLS 1.2.

The Sql server is configured for TLS 1.2.

Is it supported from IoT Edge module or not. If supported what do I need to do at IoT Edge module site?

Thanks,
Muhammad Masood

**Comment by arsing** [comment]
There is no restriction to what software you run inside your IoT Edge module. It's just a regular container.

**Comment by m4masood** [comment]
Hi,
I know it is a regular container. The question here is what do I need for my module to connect to TLS enabled Sql server?

Currently the module is accessing Sql server using System.Data.SqlClient (4.4.3) for .net core.

I am getting below error:
Error: The connection is broken and recovery is not possible.  The client driver attempted to recover the connection one or more times and all attempts failed.  Increase the value of ConnectRetryCount to increase the number of recovery attempts.
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---

Can you please assist on this?

Thanks,
Muhammad Masood

**Comment by arsing** [comment]
My point is that the connectivity problem is not specific to IoT Edge. Verify it in a container that you start manually with `docker run`. If that doesn't work either, then follow up with SQL Server.
