### ISSUE TITLE
DPS with X.509 for Edge device?

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1515]
Hi,

I can see X.509 certificate option is enable for edge device in DPS service. Do we have group enrolment support available for Edge ver 1.0.8. If yes, can you please share any reference document to try that on Edge device.

![image](https://user-images.githubusercontent.com/7486266/62486328-9874f280-b7dc-11e9-8b46-bb7fb735818a.png)

Thanks,
Prateek

**Comment by veyalla** [comment]
This functionality will be available in next release (1.0.9). A RC for this will be available next week.
