### ISSUE TITLE
Device to cloud connectionString

### ISSUE THREAD

**Issue by cconnert** [Azure/iotedge#1522]
Hi,

We would like to roll out the following setup on our IoT device:

- DPS with TPM or X509 (currently we use shared keys, as X509 is not released yet and we did not receive any TPM prototypes yet)
- After provisioning we assign labels based on the enrollment group to manage our deployments for different customers
- We would like to use IoT device configuration to manage device-specific configurations

Our issue now is, that with regards to #205 and #719 we cannot write a self-contained module which automatically connects to the IoT Hub and syncs our configuration, as we cannot get a connection string. On the other hand the IoT device configuration does not allow us to provide module configurations. Any hints how to approach this situation? 

The workaround, as described int #205, but personally I do not like relying on external configuration files and thus would like to have a different approach. Will we get a IoT module configuration in the portal at some point? Or can you provide a similar mechanism to the ModuleClient in the DeviceClient for managed devices?

**Comment by cconnert** [comment]
Or maybe we can register device callbacks within the ModuleClient?

**Comment by veyalla** [comment]
> We would like to use IoT device configuration to manage device-specific configurations
Do you intend to specify these device-specific configuration manually per device in the device twin?

**Comment by cconnert** [comment]
Exactly we would like to use the device twin to sync and manage the configurations

**Comment by veyalla** [comment]
Couldn't you use a module twin for this?

**Comment by cconnert** [comment]
Well we could, but then we lose the ability to manage the configuration from the Azure-Portal. As far as I am aware the managed configuration apply only to device-twins

**Comment by veyalla** [comment]
You can view/change module twin desired properties per device from the portal. 

I am not sure what “managed configuration” means. Can you elaborate, please?

**Comment by cconnert** [comment]
I mean the following feature: https://www.youtube.com/watch?v=OKM1E9dBJHY

**Comment by veyalla** [comment]
IoT Edge uses only modules identities for workloads. One way to make your scenario work is:

- Assign a module that will receive host specific data.
- Create an at-scale deployment for common portions of the solution while making sure you are not setting the desired properties for the module in the previous step in the deployment.
- Set the desired properties section of the twin for module in step 1 separately with device specific unique settings. You can do this from the portal, CLI, VS Code or programmatically. 
<img width="1184" alt="PNG image" src="https://user-images.githubusercontent.com/22105760/62814194-2a724900-bac4-11e9-8ab9-cd52c1a61e7d.png">

- Now even if you change the deployment at device level the module’s unique settings which is not touched by the deployment will be retained.
- You can now use the module identity normally to read the unique setting on device and perform host specific setup.

**Comment by lt72** [comment]
@cconnert Closing issues as it seems to be resolved positively. Please feel free to re-open the issue if you still need help.
