### ISSUE TITLE
Location of Log file of Azure IoT edge Modules in Windows IoT Core. 

### ISSUE THREAD

**Issue by arnabhetc** [Azure/iotedge#1527]
Hi all,
              I am using Azure IoT edge services in a gateway with windows IoT core, for each module, some log is generated, when we run the command

          iotedge loogs <modulename> -f 

We are using the following settings for the log file 

    "createOptions": {
    "HostConfig": {
        "LogConfig": {
            "Type": "json-file",
            "Config": {
                "max-size": "10m",
                "max-file": "3"
            }
        }
    } }

 

1. We can see the logs, SO I wanted to know where these logs get stored in which location of the storage?

2. Is this the correct method of Of controlling the LOG file that is created by the IoT edge Modules? 

@azure-keyvault @azure-iot  @iotedge-ci @azure-sdk

**Comment by veyalla** [comment]
I am presuming the got the createOptions to use from https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist#place-limits-on-log-size?

So yes, this is one of the recommended ways to control logs on the edge device. 

For IoT Core the log files will mostly likely be at: 
%PROGRAMDATA%\iotedge-moby\containers\[module_ID]\
