### ISSUE TITLE
How-to add SSL certificate in IoT Edge Module?

### ISSUE THREAD

**Issue by conekeo** [Azure/iotedge#1530]
Hi,

How do I add SSL certificate in a IoT Edge module?
I try to build a  IoT module Windows container image with SSL certicate.

In Visual Studio, I put a certificate in <module project>/cert/xxxx.root.ca.cert.pem

dockerfile:

```
RUN mkdir C:\cert

ADD cert/ /cert/
RUN powershell -NoProfile -Command \
    certutil -addstore "Root" "C:/cert/xxxx.root.ca.cert.pem"

```

Error:
```
Step 10/13 : RUN mkdir C:\cert
 ---> Using cache
 ---> e569d9634d74
Step 11/13 : ADD cert/ /cert/
ADD failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder156275182\cert: The system cannot find the file specified.
```

any idea how to do it?

### Device (Host) Operating System
Windows Pro 10

### Architecture
windows x64

### Container Operating System
Windows containers 

#### iotedge
IoT Edge v.1.0.8

#### Docker
Docker version 19.03.1, build 74b1e89

**Comment by arsing** [comment]
Files referenced in an `ADD` statement need to be relative to build context. See any Dockerfile reference for details.
