### ISSUE TITLE
How to get the host IP in a module?

### ISSUE THREAD

**Issue by LiangJy123** [Azure/iotedge#1543]
Hi ,
    I have a question about how to get the host IP .

**OS : Win 10**

See the architecture picture:
![image](https://user-images.githubusercontent.com/13048899/62765981-ed0dbb80-bac3-11e9-97f4-43badd11f632.png)
I want to build a connection (the red line),but the client is in a module which means it need an IP.

With docker for Windows , I can use the host name **host.docker.internal**  to achieve my work.
Because when I install docker for Windows, it will modify my **hosts** file .

![image](https://user-images.githubusercontent.com/13048899/62767056-69a19980-bac6-11e9-9e0e-44344e9d4a23.png)

If I only use Moby downloaded by using "Deploy-IoTEdge" script , How can I get the host IP?

Give some suggestions, please ~

**Comment by sw6y15** [comment]
@v-jiq

**Comment by veyalla** [comment]
The edgeAgent will inject an environment variable called `IOTEDGE_GATEWAYHOSTNAME` which you can use from within the module.

**Comment by LiangJy123** [comment]
Hi @veyalla 

I have tried this way ,but it didn't work for me.

Because , the **IOTEDGE_GATEWAYHOSTNAME**  finally converts to the edgeHub IP.



```C#
            string HostName = Environment.GetEnvironmentVariable("IOTEDGE_GATEWAYHOSTNAME");
            ws = new WebSocket($"ws://{HostName}:19870/Laputa");
```

Try the way again and get the same log:
![image](https://user-images.githubusercontent.com/13048899/62842342-13aa3d00-bce4-11e9-9577-77c743d26d2a.png)

**Comment by veyalla** [comment]
Hmm, if I use the command:
```
 docker.exe -H npipe:////./pipe/iotedge_moby_engine exec -it tempSensor cmd
```
...to login in to the module and do:

```
ping %IOTEDGE_GATEWAYHOSTNAME%
```
...it resolves to the ip address of the host.

**Comment by LiangJy123** [comment]
It also gets the edgeHub IP.

![image](https://user-images.githubusercontent.com/13048899/62848828-c04de400-bd0f-11e9-98ae-03c11ef2e382.png)


Is it possible that my device is in domain management which caused this problem?

**Comment by veyalla** [comment]
@dineshgovindasamy - do you know why there would be a difference in behavior?

**Comment by arsing** [comment]
As a workaround, the FQDN of the host might resolve correctly. Try that.

It that does work, then the value of the env var is the same as what you set for `hostname` in `config.yaml`. So set the FQDN there and your module should also get it.

**Comment by LiangJy123** [comment]
Hi @arsing , 

I check that the **hostname** in **config.yaml** , the host computer name ,and  the environment variable of the **IOTEDGE_GATEWAYHOSTNAME**  are  same. 


When I ping my host computer name in _host computer_ , I can get my IP in the LAN.


When I ping my host computer name in the _module_ , I will get edgeHub IP.

Please let me know if I understand wrong what your means.

**Comment by arsing** [comment]
I'm not asking you to confirm that they're the same; I already told you they would be the same. I'm saying that you should check if resolving the FQDN from within the container gives the correct IP instead of Edge Hub's IP. If the FQDN gives the correct IP, I'm telling you to set the `hostname` in `config.yaml` to the FQDN.

**Comment by arsing** [comment]
For example, if your domain is `example.com`, then your host's FQDN would be `desktop-f7t3en2.example.com`. So if you now do `docker.exe -H npipe:////./pipe/iotedge_moby_engine exec -it SendDataModule ping desktop-f7t3en2.example.com` does that give you the host IP? If yes, then edit the `config.yaml` to have `hostname: 'desktop-f7t3en2.example.com'` instead of `hostname: 'desktop-f7t3en2'`

**Comment by LiangJy123** [comment]
Hi @arsing 
Thank you for your patience.
Following your steps, I got a strange result:
 - The host computer Info:
![test4](https://user-images.githubusercontent.com/13048899/63077770-fe474400-bf6b-11e9-8513-2d0f1c4984c3.png)

- Ping in host computer:
![image](https://user-images.githubusercontent.com/13048899/63077913-701f8d80-bf6c-11e9-90a1-784b03dca400.png)

- Ping in edge module:
![image](https://user-images.githubusercontent.com/13048899/63077986-a78e3a00-bf6c-11e9-8d6f-951b0d76f2e1.png)

The  **desktop-f7t3en2.workgroup.com** gets  an  IP ,but it is not myhost computer's.

**Comment by arsing** [comment]
Your domain is not `workgroup.com`. You originally said your host is domain-joined, but your screenshot shows it's in a workgroup, not a domain.

**Comment by LiangJy123** [comment]
Hi  @arsing ,
Sorry for my misunderstanding about domain management .

**Comment by LiangJy123** [comment]
It seems to be not active, so I just close this question.
I will try other ways to solve the problem.
Thank you.

**Comment by keshava-hm** [comment]
what's the solution for this?

Is there a way to get host IP from iot edge module?

**Comment by LiangJy123** [comment]
I believe the right approach is to take the host's name from the environment variable.
Then convert the host name to IP.

 It's just that I can't do it in my network environment. 

So I found two ways to get around it.
1.  Just like @arsing  saying , use FQDN.
To find your device's FQDN, use the command "NSLOOKUP + your device computer name".
Then you can get computer name alias.
But it's not working  all the time . It depends your network enviroment.
2.  Change module network mode from bridge to transpant mode ( Windows platform).
But this I closed the firewall before pinging through my host computer.

**Comment by keshava-hm** [comment]
Thanks, @LiangJy123 for response.

When I convert the host name to IP, I get a different IP than the host IP.

> 2. Change module network mode from bridge to transpant mode ( Windows platform).
>    But this I closed the firewall before pinging through my host computer.

You mean , "NetworkMode": "host", ?

**Comment by keshava-hm** [comment]
> 1. Just like @arsing  saying , use FQDN.
>    To find your device's FQDN, use the command "NSLOOKUP + your device computer name".
>    Then you can get computer name alias.
>    But it's not working  all the time . It depends your network enviroment.

This does work when I hard code the FQDN name. But is there a way to get this from edge module?

Thanks a lot.

**Comment by LiangJy123** [comment]
I also hard code it. (Laughing and crying)
I tried  to get this from edge module but didn't find the way, for example, specifying a DNS resolution server.


---------------------------------------------------分割线---------------------------------------
I can't implement host mode in Windows system, maybe Moby is like docker.
![image](https://user-images.githubusercontent.com/13048899/69122628-4d0bf900-0ada-11ea-842b-b318184d29a9.png)


Create a transparent mode  driver :
1. use "netadapter" command , find a physical net adapter name.
![image](https://user-images.githubusercontent.com/13048899/69126350-f9ea7400-0ae2-11ea-9bbd-1c33efc6d59b.png)


2. Create a transparent mode  driver ,  named "host"(so you can use same config like host mode):
```
docker network create -d transparent -o com.docker.network.windowsshim.interface="Ethernet" host
```
The variable of "com.docker.network.windowsshim.interface" is a  physical net adapter name.

3. Bind it 
```
   "createOptions": {
                "NetworkingConfig": {
                    "EndpointsConfig": {
                         "host": {}
                    }
                },
                "HostConfig": {
                    "NetworkMode": "host"
                }
            }
```

If your app in module can't connect your host computer ,maybe you need close your firewall or other firewall setting

**Comment by keshava-hm** [comment]
My aim is to communicate over TCP to an app on host which is listening on a port.
I was using a workaround to write the host IP from app to a text file and access this file by mounting the directory in docker to get the host IP on my module... Do you think there's a better way to do this?

**Comment by keshava-hm** [comment]
> You can try this command:
> 
> ```
>  docker.exe -H npipe:////./pipe/iotedge_moby_engine exec network create -d transparent -o com.docker.network.windowsshim.interface="Ethernet" host
> ```
> 
> I have no problem with your method.
> The method of getting around is never better than the direct method.
> Or Microsoft's friends will bring a better and more direct approach.

Thanks a lot for the response. I think you mean by
```
docker.exe -H npipe:////./pipe/iotedge_moby_engine network create -d transparent -o com.docker.network.windowsshim.interface="Ethernet" host
```

I'll try this.

**Comment by keshava-hm** [comment]
Thanks for the help, @LiangJy123 , but when I try this, I get following error:
_Transient network error occurred, please retry._
Do you have any idea on this?
Thanks.
--Keshava

**Comment by LiangJy123** [comment]
Hi @keshava-hm , Where did you get the exception?

**Comment by keshava-hm** [comment]
> Hi @keshava-hm , Where did you get the exception?

I think I get exception when I try to communicate to edge hub. Do we need to set the above options to edge hub as well?

With this network settings, can we communicate to the other modules using MQTT?

One more thing, can we use "vEthernet (nat)" network interface to communicate between host pc and edge module?
Because, if we can, then we can get and use the default gateway IP from docker container. Is there any issues in doing so?

Thanks a lot.
Regards,
Keshava

**Comment by LiangJy123** [comment]
> I think I get exception when I try to communicate to edge hub. Do we need to set the above options to edge hub as well?

Oh! I can't help you with this exception. 
I can't install iotedge because my computer version is not 17763.

I read the c-sharp-sdk source code  about the module communication.
It may use the  value of **IOTEDGE_GATEWAYHOSTNAME** 
![image](https://user-images.githubusercontent.com/13048899/69690393-9970bd80-1106-11ea-9ad9-0e58e4899908.png)

![image](https://user-images.githubusercontent.com/13048899/69690906-35e78f80-1108-11ea-947a-b60de34bb319.png)
The mapping port: 
```
    "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": {"PortBindings": {
                "5671/tcp": [
                  {
                    "HostPort": "5671"
                  }
                ],
                "8883/tcp": [
                  {
                    "HostPort": "8883"
                  }
                ],
                "443/tcp": [
                  {
                    "HostPort": "443"
                  }
                ]
              }
            }
          }
        }
```

So the data route is:
![image](https://user-images.githubusercontent.com/13048899/69691660-adb6b980-110a-11ea-995a-bdbe00b770bd.png)

Hope this helps you.


-----------------------------------------------------------------------------------------------------------

> One more thing, can we use "vEthernet (nat)" network interface to communicate between host pc and edge module?
> Because, if we can, then we can get and use the default gateway IP from docker container. Is there any issues in doing so?

I tried it six months ago and it didn't work. 
Probably disabled for security reasons.

**Comment by keshava-hm** [comment]
Thanks @LiangJy123 , thanks a lot for the help! :)
