### ISSUE TITLE
Leaf Device using x509 fails when using AMQP

### ISSUE THREAD

**Issue by ksaye** [Azure/iotedge#1547]
Leaf device fails to authenticate to IoT Edge when using x509 Self signed and AMQP but works with MQTT.  Error message: "TLS authentication error." innerException "The remote certificate is invalid according to the validation procedure".

Edge OS: Windows IoT 10 LTSC 2019 10.0.17763.107
IoT Edge Version:  1.0.8.23694809

Client OS: Windows 10 Enterprise 10.0.18362.10012
Client SDK: .Net 1.21.0

Steps to reproduce:
1. Install Windows 10 LTSC
2. Install IoT Edge
3. Using OpenSSL, follow https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway#generate-certificates-with-windows to generate the the certs and install on Gateway
4. Deploy EdgeHub
5. Follow https://docs.microsoft.com/en-us/azure/iot-edge/how-to-authenticate-downstream-device#x509-authentication to generate the Client Cert, get the thumbprint, create leaf device and assign it as a child to the Edge, copy the needed certs to the Client OS.
6. Run the sample code below, changing hostname, iothubname, certpath and device name, too see the failure:

`

            try
                {
                var cert = new X509Certificate2(@"C:\Users\KevinSaye\Desktop\transparent\certs\certs\iot-device-leaf1-primary.cert.pfx");
                var auth = new DeviceAuthenticationWithX509Certificate("leaf1", cert);
                var protocol = TransportType.Amqp;

                var deviceClient = DeviceClient.Create("Pavan.azure-devices.net", "computestick", auth, protocol);

                Console.WriteLine("Sending using " + protocol.ToString());

                if (deviceClient == null)
                {
                    Console.WriteLine("Failed to create DeviceClient!");
                }
                else
                {
                    Console.WriteLine("Successfully created DeviceClient!");
                    deviceClient.SendEventAsync(new Message(Encoding.UTF8.GetBytes("Hello"))).Wait();
                }

                Console.WriteLine("Exiting. ....\n");
                Console.ReadKey();
            }
            catch (Exception ex)
            {

                Console.WriteLine("Error in sample: {0} and {1}", ex.Message, ex.InnerException.InnerException);
                Console.ReadKey();
            }

`

7. Change the protocol to TransportType.Mqtt and the sample works.  You also get the error 'Request header does not contain ModuleId' if you use the protocol TransportType.Http1.

**Comment by lt72** [comment]
@philipktlin can you please take a look at this one?

**Comment by philipktlin** [comment]
I believe this is related to Certificate Invocation List; you need to set revocation mode to No Check.

Try to follow section "Method 4: Turning off Check for Server Certificate Revocation" in this link, https://appuals.com/fix-revocation-information-security-certificate-site-not-available/.  To disable certificate revocation, see if it works.

**Comment by philipktlin** [comment]
Close it for now; and feel free to re-open if revocation mode doesn't work.
