### ISSUE TITLE
Downstream device not connecting to Edge Gateway

### ISSUE THREAD

**Issue by gearsmotion789** [Azure/iotedge#1549]
I've tried running the .NET example on my downstream device, following the instructions @ https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device#use-certificates-with-azure-iot-sdks. However, when I run, it attempts to send 1 message, but then stops. It never finishes sending all 10 messages.

Note: my downstream device uses symmetric key authentication

I've tried doing everything from the beginning (reset up the resource, edge gateway, etc.) multiple times, but I always have this problem. I recently found that maybe I might need to add my `azure-iot-test-only.root.ca.cert.pem` in my iot hub's certificates. I then attempted to verify the certificate with `./certGen.sh create_verification_certificate "E2507074A5FCF6B4E5C5761C48EE14088FC1B576 854C4A06"`. I then uploaded my verified cert from `<WRKDIR>\private\iot-device-verification-code.key.pem`. However, it gave me an error as shown here:

`Internal Error. If you contact a support representative please include this correlation identifier: 0e65a824-721a-4775-8776-9420b2578b34, timestamp: 2019-08-10 09:53:09Z, errorcode: IH500019.`

**How can I get my certificate verified so that my downstream device can connect to my edge gateway?**

**Comment by ancaantochi** [comment]
Hi @gearsmotion789,

I am sorry for the late reply, we must have missed your question.

You don't have to add azure-iot-test-only.root.ca.cert.pem to IotHub certificates, but you have to install it on the downstream device:

[https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device#install-certificates-in-the-os](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device#install-certificates-in-the-os)

You can check that the certificate validation passes using openssl s_client:
`openssl s-client -connect <gateway_hostname>:8883`   

Does the downstream device throw any exception?

**Comment by lt72** [comment]
Closing as stale.
