### ISSUE TITLE
Send big size message payload from One Module to Another Module

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#1554]
Hi Team,
    We have requirement to send message payload of 1mb from one module to another module. But as of now we are getting the below error so could you please let me know how to achieve this. 

Can we set Environment variable for this limit so that we can communicate to modules with big size payload locally. When we will send to upstream then we can split the payload and then send less than 256kb to upstream. 

The error what we are getting is 
Exception: System.AggregateException: One or more errors occurred. (Message size (1130947 bytes) is too big to process. Maximum allowed payload size is 262143) ---> System.InvalidOperationException: Message size (1130947 bytes) is too big to process. Maximum allowed payload size is 262143

**Comment by sachidanand** [comment]
HI Team can you update me on this on Priority .....

**Comment by veyalla** [comment]
Hi @sachidanand - I checked internally. This value is not configurable.

**Comment by sachidanand** [comment]
Can you please let me know how we can achieve it.. Actually the requirement is that we need to send more than 256 kb payload within modules locally and at the time of upstream we will split them .. So could you please let me know the solution for this...

**Comment by veyalla** [comment]
You could use the blob store module to store the payloads centrally on the edge device and pass local payload references/URI between modules instead of embedding the payload in the message.
