### ISSUE TITLE
Modules stop communicating after edgeHub errors

### ISSUE THREAD

**Issue by yalaas** [Azure/iotedge#156]
## Expected Behavior

edgeHub and module SDK should keep modules connected and should handle errors and recover from them 

## Current Behavior

We had multiple instances of modules stop communicating. EdgeHub log indicated errors in all these instances. We have identified two root cases so far:
1. Module sending reported properties with more than 512 byes JSON value for a key.  
2. Module sending large amount of data using IoTHubModuleClient_LL_SendEventToOutputAsync() while the receiving module is still booting up. In this case messages seem to be queued up and delivered all at once when the receiving module connects which causes the receiving module gets disconnected for ever.

## Steps to Reproduce

Scenario 1
Send a reported property with more than 512 bytes JSON value

Scenario 2 
Send 256K size messages from module A using C SDK  IoTHubModuleClient_LL_SendEventToOutputAsync() and route it to module B

### Device (Host) Operating System

Debian 8 

### Architecture

arm32

### Container Operating System

Linux containers

### Runtime Versions
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:26:47 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

#### iotedged

iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
#### Edge Agent

1.0
#### Edge Hub

1.0
#### Docker

 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:26:47 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

**Comment by avranju** [comment]
Issue 1 (i.e. 512 bytes limit for JSON value) is by design and is in place because that's the limit that Azure IoT Hub supports.

For issue 2, what SDK is module B using? Also, what protocol? If MQTT, what QoS level was used?

**Comment by yalaas** [comment]
@avranju C SDK is being used, protocol is  MQTT. I am not setting the QoS explicitly but the behavior and the logs indicate QoS1. Do you know if there is an option or an API to change the QoS in the C SDK?

**Comment by myagley** [comment]
Is this still an issue with the latest version of IoT Edge (1.0.6)?

**Comment by myagley** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen.
