### ISSUE TITLE
Error updating reported properties in IoT Hub: Service rejected the message with status: 403

### ISSUE THREAD

**Issue by arabold** [Azure/iotedge#1560]
I'm deploying my modules manually to my local edge server. Everything works perfectly fine, I can update modules, everything seems to run properly, IoT messages are being sent, routed and process, etc. However, the device twin functionality doesn't seem to work as expected. It seems that the Edge Server is unable to report it's current status to the cloud Azure IoT Hub.

In the logs of `edgeAgent` I'm seeing the following error message:
```
Error updating reported properties in IoT Hub
System.InvalidOperationException: Service rejected the message with status: 403
```

## Expected Behavior
I would expect that the Azure Portal shows the modules as being properly reported by the Edge Server. However, only `$edgeAgent` seems to work:

![image](https://user-images.githubusercontent.com/1548229/62915868-e47ae680-bd4a-11e9-8394-6797feccdbda.png)

Please note that on this Edge Server all modules are working properly. They are deployed and communicate with each other as expected. 

## Current Behavior
Here's the log in more detail, with my specific configuration removed:
```
<7> 2019-08-13 04:32:50.231 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Starting reconcile operation
<7> 2019-08-13 04:32:50.232 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient] - Making a Http call to unix:///var/run/iotedge/mgmt.sock to List modules
<7> 2019-08-13 04:32:50.232 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket /var/run/iotedge/mgmt.sock
<7> 2019-08-13 04:32:50.232 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket /var/run/iotedge/mgmt.sock
<7> 2019-08-13 04:32:50.232 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://mgmt.sock/modules?api-version=2019-01-30
<7> 2019-08-13 04:32:50.232 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
<7> 2019-08-13 04:32:50.232 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Obtained edge agent config
<7> 2019-08-13 04:32:50.239 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Response received OK
<7> 2019-08-13 04:32:50.240 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient] - Received a valid Http response from unix:///var/run/iotedge/mgmt.sock for List modules
<7> 2019-08-13 04:32:50.244 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - List of desired modules is - { ... }
[Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - List of current modules is - { ... }
<7> 2019-08-13 04:32:50.247 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Planners.HealthRestartPlanner] - HealthRestartPlanner created Plan, with 0 command(s).
<7> 2019-08-13 04:32:50.249 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Updating reported properties in IoT Hub
<7> 2019-08-13 04:32:50.539 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Error updating reported properties in IoT Hub
System.InvalidOperationException: Service rejected the message with status: 403
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass25_0.<<SendTwinPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinPatchAsync(TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties)
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 100
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.UpdateReportedPropertiesAsync(TwinCollection reportedProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 105
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateReportedPropertiesAsync(TwinCollection patch) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 107
<4> 2019-08-13 04:32:50.540 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.Reporters.IoTHubReporter] - Updating reported properties failed with error Service rejected the message with status: 403 type System.InvalidOperationException
<7> 2019-08-13 04:32:50.540 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Finished reconcile operation
```

I have enabled `debug` logs in `/etc/iotedge/config.yml` but that's all I get. `403` would typically indicate that I use wrong credentials somewhere, but as stated before: everything else seems to work fine.

*Note*: The "List of desired modules" and "List of current modules" log entries seem to be truncated in my logs. Only about half of the JSON is printed. Not sure if this is a limitation of the logger or a bug?

## Steps to Reproduce
n/a - A simple local setup works as expected. It seems to relate to my more complex settings. I have not been able to figure out what exactly causes this yet.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname edgehub.local.example.com but device reports hostname dev-sandbox.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

21 check(s) succeeded.
1 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
```
</details>

### Device (Host) Operating System
Ubuntu 18.04 Server

### Architecture
amd64

### Container Operating System
moby

#### iotedged
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

#### Edge Agent
1.0.8

#### Edge Hub
1.0.8

#### Docker
Docker version 3.0.6, build a63faebc

## Additional Information

I have two possible causes I could think of, without having been able to confirm any of them yet:
1) The `iotedge check` shows a mismatch between the server's hostname and the respective `config.yaml` value. This is intentional as all our edge servers use the same FQDN but run in distinct and separated networks. But why would that matter for the reporting of device and module properties? I have a device connection string - that should be sufficient, shouldn't it?
2) Our `deployment.template.json` is actually quite big and I had to remove a couple of settings already as otherwise it wouldn't deploy. Maybe we're hitting some sort of size limitation when the Edge Server tries to report properties back to the Azure IoT Hub?

**Comment by arabold** [comment]
**Update**: The "List of desired modules" and "List of current modules" log entries above seem to be truncated in my logs. Only about half of the JSON is printed. Not sure if this is a limitation of the logger or an actual bug?

**Comment by veyalla** [comment]
Hi @arabold - I think it might be a size limitation as you guessed given the large number of modules deployed.

 @varunpuranik or @philipktlin can help confirm.

**Comment by arabold** [comment]
This is still an issue for us. The IoT Edge device supports up to 20 modules (including the IoT Agent the the IoT Hub). Each module allows their own twin settings. But doing so seems to easily exceed whatever limit applies because the whole deployment configuration itself is actually nothing else than a device twin setting for the Agent. Or am I misunderstanding something here?

**Comment by lt72** [comment]
@arsing can you please take a look at this one?

**Comment by arsing** [comment]
@arabold

It's true that having 20 modules will push the Edge Agent's reported properties just past the 8KiB limit for module twins. Eg with 20 copies of SimulatedTempSensor the twin comes out to just over 12 KiB.

It's possible that exceeding this limit manifests as a 403.

However we're already in the process of updating the limits on module twin sizes. Can you check if you still have the issue?

**Comment by arsing** [comment]
The increased limits are now generally available.
