### ISSUE TITLE
IoT Edge does not support DeviceRequests new Moby API to support Nvidia GPUs

### ISSUE THREAD

**Issue by ebertrams** [Azure/iotedge#1580]
## Expected Behavior
Support Nvidia GPU via IoT Edge deployment

## Current Behavior
Nvidia GPU is no longer supported as Moby now natively supports Nvidia GPU as opposed to using nvidia-docker third party tool before.

## Steps to reproduce
Ubuntu 18.08 on amd64 pc with Nvidia GPU 
Install Moby via the Linux Tutorial: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux

Nvidia-docker used to work with IoT Edge by specifying HostConfig > Runtime = "nvidia"

This is no longer the case with  Nvidia GPUs now being natively supported by Moby. See https://github.com/NVIDIA/nvidia-docker

With the latest Moby Version (API version 1.40), one can now add GPUs to its container by using the command:
docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
which maps to the following parameters using Docker Engine API:
"createOptions": {
                  "HostConfig": {
                  "DeviceRequests": [{"Capabilities":  ["gpu"], "Count": -1}]
                }

Issue is that the new DeviceRequests node is ignored by IoT Edge and thus result in a container being created with DeviceRequests=null, which breaks the GPU support.

**Comment by arsing** [comment]
As I said in the email thread, it needs to be supported by [`Docker.DotNet`](https://github.com/microsoft/Docker.DotNet/blob/master/src/Docker.DotNet/Models/HostConfig.Generated.cs) . Once it does that, and we update Edge Agent's nuget dependency to reference the new package, it'll start working automatically. Until then there isn't really anything for us to do.

**Comment by arsing** [comment]
I talked with @varunpuranik and there are two other options for the general problem:

1. We can parse the `createOptions` from the deployment loosely. Instead of mapping it to `Docker.DotNet` types we can leave it as a JSON blob, and just do the minimal amount of modifications we need (add mount for workload socket, add env vars, set network, etc). This is future-proof, and also avoids the other kind of problems we've had like #1130 and #1517 where the type is generated incorrectly.

1. We can generate our own types for `createOptions` instead of using `Docker.DotNet`.

**Comment by josiahlaivins** [comment]
What are the create options supposed to look like? I am attempting  --gpus all also, but still cannot access nvidia-smi on the device. I am able to run my module locally, but not over iot edge.

**Comment by arsing** [comment]
If you've got it working with `docker run`, then you can dump its create options with `docker inspect`

Based on the internal bug report I'd got, it was what's mocked in https://github.com/Azure/iotedge/commit/5a6d5067c832ad85b39cc15d323442a973b3d3f7#diff-f934dbd6b3bc59bc9fb35e9e1a0e6b91R213 , but you should verify with Docker docs / nvidia docs / your live container to be sure.

**Comment by johansked** [comment]
Is this feature released yet?

I am able to get the gpu passthrough to work with docker run --gpus all. When I copy the createOptions to my deployment config it still gets ignored when creating the container via IoT Edge.

In the deployment.template.json I set the DeviceRequest (copied from docker inpect) in the HostConfig (for the module):

```
"imageclassifiermodelservice": {
  "version": "1.0",
  "type": "docker",
  "status": "running",
  "restartPolicy": "always",
  "settings": {
    "image": "${MODULES.imageclassifiermodelservice}",
    "createOptions": {
      "ExposedPorts": {
        "80/tcp": {}
      },
      "HostConfig": {
        "PortBindings": {
          "80/tcp": [
            {
              "HostPort": "80"
            }
          ]
        },
        "DeviceRequests": [
          {
            "Driver": "",
            "Count": -1,
            "DeviceIDs": null,
            "Capabilities": [["gpu"]],
            "Options": {}
          }
        ]
      }
    }
  }
}
```

Which translates to the following deployment (for that module):
```
"imageclassifiermodelservice": {
  "version": "1.0",
  "type": "docker",
  "status": "running",
  "restartPolicy": "always",
  "settings": {
    "image": "xxx/image-classifier-model-service:0.0.9-amd64",
    "createOptions": "{\"ExposedPorts\":{\"80/tcp\":{}},\"HostConfig\":{\"PortBindings\":{\"80/tcp\":[{\"HostPort\":\"80\"}]},\"DeviceRequests\":[{\"Driver\":\"\",\"Count\":-1,\"DeviceIDs\":null,\"Capabilities\":[[\"gpu\"]],\"Options\":{}}]}}"
  }
}
```

When I create a new deployment for the GPU device it does not respect the DeviceRequest properties when creating the container:
![image](https://user-images.githubusercontent.com/6658933/73262434-6ca45980-41ce-11ea-83ef-d2acb4799df6.png)

And the device does not report it back to the IoT Hub
![image](https://user-images.githubusercontent.com/6658933/73262504-965d8080-41ce-11ea-832b-77fd8bafc3ff.png)

I have tried running different version of IoTEdge and the edgeAgent container
- IoT Edge v1.0.8
- IoT Edge v1.0.9-rc4
- edgeAgent 1.0.8
- edgeAgent 1.0.8.4
- edgeAgent 1.0.9-rc4

With no success.

Looking at the moby-config the DeviceRequests should be ok.
https://github.com/moby/moby/blob/master/api/types/container/host_config.go
https://github.com/moby/moby/blob/master/api/swagger.yaml

The environment I am currently running is an Azure Standard NC6 VM with Ubuntu 18.04. Moby version is:
![image](https://user-images.githubusercontent.com/6658933/73262916-a590fe00-41cf-11ea-99ec-e94459f8a1e7.png)

**Comment by ebertrams** [comment]
@johansked it is not released yet. Is is planned to be release with IoT Edge version 1.0.10. In the meantime, you can use nvidia-docker. Thanks!

**Comment by johansked** [comment]
@ebertrams that works for now, thank you!

For anyone else seeing this. I did the following:

- Installed docker instead of moby
- Followed instructions for installing nvidia-docker2 (https://github.com/NVIDIA/nvidia-docker/tree/v2.1.0)
- Installed iotedge
- Updated my deployment-template with 

```
"imageclassifiermodelservice": {
  "version": "1.0",
  "type": "docker",
  "status": "running",
  "restartPolicy": "always",
  "settings": {
    "image": "${MODULES.imageclassifiermodelservice}",
    "createOptions": {
      "ExposedPorts": {
        "80/tcp": {}
      },
      "HostConfig": {
        "PortBindings": {
          "80/tcp": [
            {
              "HostPort": "80"
            }
          ]
        },
        "Runtime": "nvidia"
      }
    }
  }
}
```

**Comment by josiahlaivins** [comment]
I would like to re-open this. nvidia-docker2 is deprecated and does not support the runtime=nvidia fix anymore. Using deviceRequests is required. Any updates?

**Comment by ebertrams** [comment]
@josiahlaivins , support for DeviceRequests is still planned to be released with IoT edge version 1.0.10, e.g. the next release.  Until then, the only workaround is to use the deprecated nvidia-docker2 per above comments.

**Comment by josiahlaivins** [comment]
@ebertrams  Ok, thanks for the update. If you dont't might a second question where do we go to see the most recent versions of edgeHub and edgeAgent? Would have expected a docker registry link.

Regardless, thanks for the quick reply!

**Comment by ebertrams** [comment]
Here you go:
- edgeAgent: https://hub.docker.com/_/microsoft-azureiotedge-agent
- edgeHub: https://hub.docker.com/_/microsoft-azureiotedge-hub

Release notes: https://github.com/Azure/azure-iotedge/releases
