### ISSUE TITLE
Use DPS service for Edge Authentication with x.509 Certificate

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#1587]
Hi Team,
     Can I use DPS Service with X.509 certificate based authentication with Edge Modules. Please provide me some details or sample code if you have around it.

**Comment by veyalla** [comment]
Hi @sachidanand - this is not supported. 

With 1.0.9 release expected in the next few weeks, you'll be able to do DPS provisioning with X.509, but modules will still use SAS keys derived from the certificate.

**Comment by sachidanand** [comment]
will you provide documents around it that how to implement it ?? also SAS key means do we need to store symmetric key in the Module ??

**Comment by lt72** [comment]
@kkdawkins can you please provide clarifications about the implementation and point customers to the working version in 1.0.9 RC?

**Comment by veyalla** [comment]
Here are the instructions for testing this with [1.0.9-rc2](https://github.com/Azure/azure-iotedge/releases/tag/1.0.9-rc2):
https://github.com/Azure/iotedge/blob/master/doc/rc/how-to-auto-provision-x509-certificates.md

**Comment by lt72** [comment]
Closing as resolved, please re-open as needed.

**Comment by Anil-Poolayulla-Chelottillam** [comment]
Now after using 1.0.9-rc2, DPS  is working with X509(connecting with DPS, module download is successful). 

But downloaded edge module fails to send telemetry to cloud. 

Can anybody point out the changes for edge module to work with X509 certificate?
