### ISSUE TITLE
Edge logging module support on windows IoT Core

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1590]
Hi,

What is the best way to use logging for Windows based containers on IoT Core. I have got this post for logging on Linux platform-
https://github.com/veyalla/logspout-loganalytics

Is there any support available for Windows IoT Core?

Planning to enable below services-
https://azure.microsoft.com/en-us/pricing/details/monitor/

Thanks,
Prateek

**Comment by veyalla** [comment]
@pratson20 This is on our longer term roadmap.

With 1.0.8 release, you can try our experimental feature for pulling logs from an edge device which works on all platforms: https://github.com/Azure/iotedge/blob/master/doc/built-in-logs-pull.md

**Comment by pratson20** [comment]
@veyalla  I have tried experimental feature for pulling log-

I am on edge runtime - 1.0.9-RC1

edgeAgent "image": "mcr.microsoft.com/azureiotedge-agent:1.0.8",

Done changes in edgeAgent-

`              "ExperimentalFeatures__Enabled": {
                "value": "true"
              },
              "ExperimentalFeatures__EnableUploadLogs": {
                "value": "true"
              }`


Triggering below packet  from edgeAgent direct method for azure portal-

![image](https://user-images.githubusercontent.com/7486266/64024078-3dbe8480-cb57-11e9-9457-51f63de393ce.png)


Response-

![image](https://user-images.githubusercontent.com/7486266/64024094-48791980-cb57-11e9-97cb-828ac2812f1c.png)

Can you please help me on this.

Thanks,
Prateek

**Comment by veyalla** [comment]
@pratson20 Please take of this comment in the docs:

_Due to certain design limitations, settings for the Edge Agent do not take affect unless its image is also changed (as of 1.0.8 release). If you are using the default Edge Agent settings, change the image to use a specific tag along with the environment variables above, e.g. mcr.microsoft.com/azureiotedge-agent:1.0.8._

When you add the env vars for agent, also change the tag for edgeAgent. If you already changed the tag doing `docker rm -f edgeAgent` might help (the edge daemon will detect the agent is gone and bring it back up).

**Comment by pratson20** [comment]
Thank you @veyalla 

Above configuration worked for me.
