### ISSUE TITLE
Can't pull the images down with the slow connection (spotty cellular service)

### ISSUE THREAD

**Issue by imZack** [Azure/iotedge#1593]
If you are using cellular as the primary connection and the signal/speed isn't good enough. IoT Edge won't be able to finish the deployment plan due to the docker images never pull down successfully.

## Expected Behavior
Resume the download progress from where it stopped.

## Current Behavior
After disconnect/timeout, the download progress will start over.

## Steps to Reproduce
1.
2.
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
// Paste here
```
</details>

### Device (Host) Operating System
Debian 9

### Architecture
armv7

### Container Operating System
Linux container

#### iotedged
1.0.8

#### Edge Agent
1.0.8

#### Edge Hub
1.0.8

#### Docker

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by arsing** [comment]
`iotedged` does the API equivalent of `docker pull`, so the resume behavior has to come from Moby's side. https://github.com/moby/moby/issues/26146 appears to be the relevant issue.

**Comment by ancaantochi** [comment]
@imZack,
Is the image pull failing when downloading edgeAgent, edgeHub or other custom image? Can you please include iotedged logs?

As a workaround, can the images be pulled on the device before the deployment when the device is on a faster connection? For example pre-download edgeAgent and edgeHub 1.0.8 and when there is an update to these images (to version 1.0.9) only updated layers will be pulled.

I will follow up with moby team regarding the issue #26146, it looks like they are working on fixing it.

**Comment by veyalla** [comment]
Another thing to try is to set `--max-concurrent-downloads` to `1` in the [Docker daemon options](https://docs.docker.com/engine/reference/commandline/dockerd/)

**Comment by imZack** [comment]
@ancaantochi I'll try to capture the logs next time. However, in my case, it includes edgeAgent/edgeHub and a custom image. Basically, if your internet isn't stable/fast enough, the device will be hard to finish the provisioning process.

@veyalla Thanks for pointing that out. That should slightly help if the downloading process won't get interrupted which is not easy sometimes when you need to deploy devices in the field.

**Comment by KevinKao809** [comment]
@ancaantochi We do plan to pre-download edgeAgent, edgeHub and our custom module at local repo at next product release. However, this will not solve when customer download their own custom module on demand.
