### ISSUE TITLE
HTTP communication between Edge modules (instead of Routes)

### ISSUE THREAD

**Issue by iAmoric** [Azure/iotedge#1597]
Hi,

I know the communication between IoT Edge modules is done through [Routes](https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#declare-routes), but is there a way to use a classic HTTP communication ? 

Thanks

**Comment by myagley** [comment]
Yes, that should "just work". You will need to setup an HTTP server in one module and an HTTP client in another one. The IP address of the server can be resolved via DNS by the client by using the server module's name.

This is how the SQL Server example works: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-store-data-sql-server It allows clients to use the native SQL network protocol directly and uses the module name for DNS resolution.

**Comment by iAmoric** [comment]
Ok great, thanks for the example.
And for an external client to connect to a http server running on the edge, i guess i have to expose/bind ports on host ?

**Comment by arsing** [comment]
Yes.
