### ISSUE TITLE
Prebuilt Simulated Temperature Sensor on ARM-powered edge device

### ISSUE THREAD

**Issue by dave-am** [Azure/iotedge#1603]
I successfully deployed the prebuilt [_Simulated Temperature Sensor_](https://azuremarketplace.microsoft.com/en/marketplace/apps/microsoft.edge-simulated-temperature-sensor-ga?tab=Overview) module on a custom ARM-based Linux edge device by following [this tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-modules-vscode).

I noticed that the process running inside the container associated with the module is:

`/usr/bin/dotnet SimulatedTemperatureSensor.dll`

`/usr/bin/dotnet` is a ARM ELF executable, while `SimulatedTemperatureSensor.dll` is a PE file including x86 code (at the end of the message I copied a snippet of its contents extracted with objdump).
Does this mean that the container includes an x86 emulator too and that the simulated sensor code (written in C#) is run on top of this emulator?

```
Sections:
Idx Name Size VMA LMA File off Algn
0 .text 0000436c 00402000 00402000 00000200 2**2
CONTENTS, ALLOC, LOAD, READONLY, CODE
1 .rsrc 00000604 00408000 00408000 00004600 2**2
CONTENTS, ALLOC, LOAD, READONLY, DATA
2 .reloc 0000000c 0040a000 0040a000 00004e00 2**2
CONTENTS, ALLOC, LOAD, READONLY, DATA
SYMBOL TABLE:
no symbols



Disassembly of section .text:

00402000 <.text>:
402000: 48 dec %eax
402001: 63 00 arpl %ax,(%eax)
402003: 00 00 add %al,(%eax)
402005: 00 00 add %al,(%eax)
402007: 00 48 00 add %cl,0x0(%eax)
40200a: 00 00 add %al,(%eax)
40200c: 02 00 add (%eax),%al
40200e: 05 00 5c 30 00 add $0x305c00,%eax
402013: 00 b0 31 00 00 01 add %dh,0x1000031(%eax)
402019: 00 00 add %al,(%eax)
40201b: 00 12 add %dl,(%edx)
40201d: 00 00 add %al,(%eax)
40201f: 06 push %es
```

**Comment by arsing** [comment]
>Does this mean that the container includes an x86 emulator too and that the simulated sensor code (written in C#) is run on top of this emulator?

No it does not.

**Comment by dave-am** [comment]
So how can the ARM processor execute the x86 code?
