### ISSUE TITLE
Cannot Send or receive messages after deploying IoT Edge 

### ISSUE THREAD

**Issue by samisarfraz** [Azure/iotedge#161]
I have couple of questions:

1.	I have successfully configured IoT Edge on raspberry Pi 3; Linux os and able to connect leaf device with IoT edge (I can see my device connected on Azure IoT Portal but I cannot receive or send command using direct method from device explorer (IoT Hub).

If I take out IoT edge then I can receive message and send commands using device explorer (IoT hub).

2.	I would like to know that if I create an android app to control & monitor my devices (send command using direct method and receive messages from devices). Communication flow will be android app ---> IoT Hub ---> IoT Edge ---> Leaf Device (bi-directional communication) and if internet link is down but android user, IoT edge and Leaf Devices are all connected to same AP (network) then I will be able to send commands and receive message from device? Communication flow will be android app ---> IoT Edge ---> Leaf Device (bi-directional communication). MQTT

**Comment by varunpuranik** [comment]
@samisarfraz -
Re #1 - Are you able to send telemetry from your leaf device? Can you share the EdgeHub logs for your scenario?

Re #2 - How does the android app communicate with IoTHub? Through the service interface, I believe?  (using the service connect credentials?). In that case IoT Edge does not have a service API. So you cannot use your android app to directly communicate with IoT Edge, even if they are on the same network.

**Comment by samisarfraz** [comment]
@varunpuranik Thanks for the reply.
As for Issue 1 leaf device is connected to the IoT edge and sending messages we can see it from device monitor but we are not able to see messages on EdgeHub

And for issue 2 how can we make it work. what will be the way around so we can use android application or web based application to communicate with iot edge and leave devices in case when internet link is down. 

as you said how will the app communicate with iot hub. Can't we use APIs which device explorer is using to connect with IoT hub. (for now we are using Device explorer for sending/receiving  commands in the place of an app (android/IOS). Can you brief us on this issue so that it'll be easy for us when we start working on app side.

Thanks
Sami Sarfraz

**Comment by varunpuranik** [comment]
Re #1 - I am not sure what you mean by this "but we are not able to see messages on EdgeHub"? Where do you expect to see the messages? 

Re #2 - Right now there is no way to achieve this. We are working on improving the IoT Edge offline story (including offline configuration), at which point you should be able to achieve something similar to what you are trying to do. That should be available in the coming months, but we don't have an ETA at the moment.

**Comment by samisarfraz** [comment]
okay i think i got your question wrong. can you please tell me how can i see the log of my leaf devices in the edgehub?. This is the tutorial i read https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux and for logs there is a command to show all logs of a module but idk how to see the log of a leaf device.
Thanks.

**Comment by varunpuranik** [comment]
You cannot really filter out a module logs to see only the logs for a leaf device - you can only see the entire log of a module (like edgeHub). But if you have enabled debug logs for the edgeHub, you should be able to search for the logs related to your leaf device in the edgeHub logs quite easily (using standard text search).
To enable debug logs on the edgeHub, set the environment variable RuntimeLogLevel to debug.

**Comment by myagley** [comment]
I am going to close this issue out due to inactivity. Please feel free to reopen. Thanks!
