### ISSUE TITLE
Clarification Security Manager Credential Lifecycle

### ISSUE THREAD

**Issue by myfacilitygithub** [Azure/iotedge#1636]
Hi, so far I have been installing Edge without HSM and without provisioning any X.509 certificate. So how does the security daemon can authenticate modules through Workload API as described at https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-security-manager#the-iot-edge-security-daemon in a default configuration? Are certificates generates automatically under the hood? Where are module and device credential stored? How does Security Daemon keep module credential in sync with IoT Hub? What if a module communicates (through Edge) to another third-party service that is NOT IoT Hub?

**Comment by myfacilitygithub** [comment]
@darobs many thanks for the answer.
Bear with me pls, assuming I have a module that communicates with third-party services only never touching Edge! Hence has no Azure SDK in it. But it still has an identity in IoT Hub because is running as Edge module. Am I correct that in this case the module_Id (and module_key?) are cached in the Edge runtime only? And what use can Edge make of such keys (since it cannot interact with module)?

thanks

**Comment by darobs** [comment]
If you have a module that does not use the security daemon, and does not communicate to IoT Hub through edgeHub, and then the only information stored for a module would be the module name and its generation ID when edgeAgent creates the module.  There is an identity that's managed by the security daemon, but there will be no credentials generated for the module until a [sign operation is requested.](https://github.com/Azure/iotedge/blob/master/edgelet/api/workloadVersion_2019_01_30.yaml#L34) Even then the credentials generated will be a SAS token with an expiration (normally 2 hours).  The credentials are derived and signed from the device credentials given to the Security Daemon.

If the module never communicates to the edgeHub, the edgeHub won't cache any identity or credentials for the module.

The Edge runtime as it is doesn't do anything with these module credentials.

**Comment by myfacilitygithub** [comment]
ok thanks. The SAS token is the one a module use for communication with IoT Hub?

**Comment by darobs** [comment]
Correct.

**Comment by myfacilitygithub** [comment]
thanks

**Comment by lt72** [comment]
Closing this issue as it seems resolved, please feel free to re-open as needed.
