### ISSUE TITLE
Module not using Edge clarification

### ISSUE THREAD

**Issue by myfacilitygithub** [Azure/iotedge#1637]
Am I correct that a module requires keys to authenticate to Edge runtime? However if a module does not need to communicate with Edge neither with IoT Hub, it will not include Azure SDK. In this situation how security in manged (e.g. to receive module upgrades)?
thanks

**Comment by myfacilitygithub** [comment]
Ok so the Agent manages the Module container identified by its module_id, right?

**Comment by lt72** [comment]
Correct.
Closing as stale, please re-open as needed.
