### ISSUE TITLE
Issue installing IoTEdge on RPI4  (Errors were encountered while processing:  aufs-dkms)

### ISSUE THREAD

**Issue by mortslhawmit** [Azure/iotedge#1642]
## Expected Behavior
Following the guide at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm to install moby and iotedge on an Rpi4 
(it seems like the guide only include stretch right now so im not sure if IoTEdge is supported on the Rpi4 yet?)

Installation should go well and iotedge should start working.

## Current Behavior
Cannot get past "install moby-cli" 

## Steps to Reproduce
1. Setup a fresh rpi4 with buster
2. Follow the steps in the guide
3. When running step to install moby-cli error occures

### Device (Host) Operating System
Raspberry Pi 4 Model B
Raspbian GNU/Linux 10 (buster)
Linux raspberrypi 4.19.46-v7l+ #866 SMP Fri Jun 7 18:00:39 BST 2019 armv7l GNU/Linux

### Architecture
arm32

### Container Operating System
Linux

## Logs

<summary>Logs from going through the steps of the guide (following raspbian stretch)</summary>

```
pi@raspberrypi:~ $ curl https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list > ./microsoft-prod.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   104  100   104    0     0    249      0 --:--:-- --:--:-- --:--:--   250
pi@raspberrypi:~ $ sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
pi@raspberrypi:~ $ curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0   2996      0 --:--:-- --:--:-- --:--:--  3006
pi@raspberrypi:~ $ sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:3 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch InRelease [23.0 kB]
Get:4 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main all Packages [546 B]
Get:5 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main amd64 Packages [1,230 B]
Get:6 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main armhf Packages [2,863 B]
Get:7 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main arm64 Packages [1,236 B]
Reading package lists... Done
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'testing' to 'stable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
pi@raspberrypi:~ $ sudo apt-get install moby-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  aufs-dkms aufs-tools cgroupfs-mount dkms raspberrypi-kernel-headers
Suggested packages:
  aufs-dev python3-apport menu
The following NEW packages will be installed:
  aufs-dkms aufs-tools cgroupfs-mount dkms moby-engine raspberrypi-kernel-headers
0 upgraded, 6 newly installed, 0 to remove and 93 not upgraded.
Need to get 52.3 MB of archives.
After this operation, 281 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1.20190819-1 [24.9 MB]
Get:2 http://raspbian.playstar.se/raspbian buster/main armhf dkms all 2.6.1-4 [74.4 kB]
Get:3 http://raspbian.playstar.se/raspbian buster/main armhf aufs-dkms all 4.19+20190211-1 [183 kB]
Get:4 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main armhf moby-engine armhf 3.0.6 [27.0 MB]
Get:5 http://raspbian.playstar.se/raspbian buster/main armhf aufs-tools armhf 1:4.14+20190211-1 [103 kB]
Get:6 http://raspbian.playstar.se/raspbian buster/main armhf cgroupfs-mount all 1.4 [6,276 B]
Fetched 52.3 MB in 7s (7,298 kB/s)
Selecting previously unselected package dkms.
(Reading database ... 132894 files and directories currently installed.)
Preparing to unpack .../0-dkms_2.6.1-4_all.deb ...
Unpacking dkms (2.6.1-4) ...
Selecting previously unselected package aufs-dkms.
Preparing to unpack .../1-aufs-dkms_4.19+20190211-1_all.deb ...
Unpacking aufs-dkms (4.19+20190211-1) ...
Selecting previously unselected package aufs-tools.
Preparing to unpack .../2-aufs-tools_1%3a4.14+20190211-1_armhf.deb ...
Unpacking aufs-tools (1:4.14+20190211-1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../3-cgroupfs-mount_1.4_all.deb ...
Unpacking cgroupfs-mount (1.4) ...
Selecting previously unselected package moby-engine.
Preparing to unpack .../4-moby-engine_3.0.6_armhf.deb ...
Unpacking moby-engine (3.0.6) ...
Selecting previously unselected package raspberrypi-kernel-headers.
Preparing to unpack .../5-raspberrypi-kernel-headers_1.20190819-1_armhf.deb ...
Unpacking raspberrypi-kernel-headers (1.20190819-1) ...
Setting up aufs-tools (1:4.14+20190211-1) ...
Setting up dkms (2.6.1-4) ...
Setting up raspberrypi-kernel-headers (1.20190819-1) ...
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.66+
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.66-v7+
run-parts: executing /etc/kernel/header_postinst.d/dkms 4.19.66-v7l+
Setting up moby-engine (3.0.6) ...
Adding group `docker' (GID 115) ...
Done.
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
Setting up aufs-dkms (4.19+20190211-1) ...
Loading new aufs-4.19+20190211 DKMS files...
It is likely that 4.19.46-v7l+ belongs to a chroot's host
Building for 4.19.46+, 4.19.46-v7+, 4.19.46-v7l+, 4.19.66+, 4.19.66-v7+ and 4.19.66-v7l+
Module build for kernel 4.19.46+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.46-v7+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Module build for kernel 4.19.46-v7l+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 4.19.66+
Error! Bad return status for module build on kernel: 4.19.66+ (armv7l)
Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.
dpkg: error processing package aufs-dkms (--configure):
 installed aufs-dkms package post-installation script subprocess returned error exit status 10
Setting up cgroupfs-mount (1.4) ...
Processing triggers for systemd (241-5+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Errors were encountered while processing:
 aufs-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by mortslhawmit** [comment]
Found that [1642](https://github.com/Azure/iotedge/issues/1408) had a very simmilar issue, it seems like the workaround by running "sudo apt-get install libssl1.0.2" made it so that iotedge now starts, i still got the "aufs-dkms" error but everything seems to work fine anyway.

**Comment by mortslhawmit** [comment]
Hi @darobs thanks this fixed the  "buster InRelease'.." issue but I still get the following error when running 

> sudo apt-get install moby-engine

```Loading new aufs-4.19+20190211 DKMS files...
It is likely that 4.19.46-v7l+ belongs to a chroot's host
Building for 4.19.66+, 4.19.66-v7+ and 4.19.66-v7l+
Building initial module for 4.19.66+
Error! Bad return status for module build on kernel: 4.19.66+ (armv7l)
Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.
dpkg: error processing package aufs-dkms (--configure):
 installed aufs-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 aufs-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
But IoTEdge works fine.

**Comment by darobs** [comment]
I'm assuming the moby runtime is working fine because it chose to use the overlay2 filesystem instead of aufs.  (https://docs.docker.com/storage/storagedriver/aufs-driver/)  

You can find out which storage driver it's using by finding the "Storage Driver" section in the `docker info` command.

It also looks like there's a issue on the moby project related to this: https://github.com/moby/moby/issues/39542

**Comment by braianuc** [comment]
> Hi @darobs thanks this fixed the "buster InRelease'.." issue but I still get the following error when running
> 
> > sudo apt-get install moby-engine
> 
> ```
> It is likely that 4.19.46-v7l+ belongs to a chroot's host
> Building for 4.19.66+, 4.19.66-v7+ and 4.19.66-v7l+
> Building initial module for 4.19.66+
> Error! Bad return status for module build on kernel: 4.19.66+ (armv7l)
> Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.
> dpkg: error processing package aufs-dkms (--configure):
>  installed aufs-dkms package post-installation script subprocess returned error exit status 10
> Errors were encountered while processing:
>  aufs-dkms
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```
> 
> But IoTEdge works fine.

This happened to me after accidentally installing Moby with an existing Docker installation.
The Moby installation failed at that time but I ignored it since I thought it wouldn't actually damage the entire configuration. But right after that I could not run apt-get anymore without getting that error no matter what I was installing / removing / etc.

So after a lot of trial and error, here's a workaround that did the job for me. 

I ran:
`sudo apt-get autoremove`

This removed aufs-dkms for me which caused the problem. I got a kernel update prompt which I confirmed without changing anything and then rebooted the machine (`sudo reboot`) and ran:

`sudo apt-get upgrade`

Hope it helps someone.

**Comment by rameshgg** [comment]
Looks like this issue is coming not only with mobi-engine. i tried installing azure-cli (az) , i am also facing the same issue. Hence i have followed the above suggestions, but still i am getting the issue.


**t is likely that 4.19.66-v7+ belongs to a chroot's host
Building for 4.19.66+, 4.19.66-v7+ and 4.19.66-v7l+
Building initial module for 4.19.66+
Error! Bad return status for module build on kernel: 4.19.66+ (armv7l)
Consult /v

"Processing triggers for libc-bin (2.28-10+rpi1) ...
Errors were encountered while processing:
 aufs-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)"**

Can any one help me further ?

**Comment by rameshgg** [comment]
for anything related azure packages , i am getting this error....
pi@raspberrypi:~/DevWork_Azure_IoT $ sudo apt-get install moby-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
moby-engine is already the newest version (3.0.7).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up aufs-dkms (4.19+20190211-1) ...
Removing old aufs-4.19+20190211 DKMS files...

------------------------------
Deleting module version: 4.19+20190211
completely from the DKMS tree.
------------------------------
Done.
Loading new aufs-4.19+20190211 DKMS files...
It is likely that 4.19.66-v7+ belongs to a chroot's host
Building for 4.19.66+, 4.19.66-v7+ and 4.19.66-v7l+
Building initial module for 4.19.66+
Error! Bad return status for module build on kernel: 4.19.66+ (armv7l)
Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.
dpkg: error processing package aufs-dkms (--configure):
 installed aufs-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 aufs-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

Please can anyone help me out , what could be the reason ? i have fallowed all the above steps... but still stuck with this package... " AUFS-DKM" ...

**Comment by junsaw** [comment]
Does anyone have any update or work around on this ?

**Comment by veyalla** [comment]
@cpuguy83 Any guidance you can provide here?

**Comment by cpuguy83** [comment]
Probably we should drop aufs from the recommended packages since it's deprecated.
This would have the side-effect that if someone wants aufs they'll need to pull it in manually.

---

I am curious why it's failing to build, though.

> Consult /var/lib/dkms/aufs/4.19+20190211/build/make.log for more information.

What is in this log file?

**Comment by junsaw** [comment]
Please see log file details below:

DKMS make.log for aufs-4.19+20190211 for kernel 4.19.75+ (armv7l)
Wed 23 Oct 2019 06:31:13 AM EDT
make: Entering directory '/var/lib/dkms/aufs/4.19+20190211/build'
-I/var/lib/dkms/aufs/4.19+20190211/build/include -DCONFIG_AUFS_FS_MODULE -UCONFIG_AUFS -DCONFIG_AUFS_BRANCH_MAX_127 -DCONFIG_AUFS_SBILIST
make -C /lib/modules/4.19.75+/build M=/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs EXTRA_CFLAGS="-I/var/lib/dkms/aufs/4.19+20190211/build/include -DCONFIG_AUFS_FS_MODULE -UCONFIG_AUFS -DCONFIG_AUFS_BRANCH_MAX_127 -DCONFIG_AUFS_SBILIST" modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.75+'
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.o
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.o
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.o
  CC [M]  /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.o
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:33,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:134:2: error: unknown type name ‘vfs_readf_t’
  vfs_readf_t  si_xread;
  ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.h:135:2: error: unknown type name ‘vfs_writef_t’
  vfs_writef_t  si_xwrite;
  ^~~~~~~~~~~~
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
                    key_ref_t
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘pte_write’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     pte_write
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
                    key_ref_t
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     key_ref_t
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:38,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:243:20: error: unknown type name ‘vfs_readf_t’
 ssize_t xino_fread(vfs_readf_t func, struct file *file, void *buf, size_t size,
                    ^~~~~~~~~~~
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘key_ref_t’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     key_ref_t
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.h:245:21: error: unknown type name ‘vfs_writef_t’; did you mean ‘pte_write’?
 ssize_t xino_fwrite(vfs_writef_t func, struct file *file, void *buf,
                     ^~~~~~~~~~~~
                     pte_write
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:46,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h: In function ‘au_vm_prfile_set’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/file.h:334:7: error: ‘struct vm_area_struct’ has no member named ‘vm_prfile’; did you mean ‘vm_file’?
  vma->vm_prfile = file;
       ^~~~~~~~~
       vm_file
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘pte_same’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         pte_same
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.c:23:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘file_update_time’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         file_update_time
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.c:27:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘file_update_time’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         file_update_time
In file included from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/aufs.h:57,
                 from /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.c:25:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h: In function ‘vfsub_update_time’:
/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/vfsub.h:233:9: error: implicit declaration of function ‘update_time’; did you mean ‘pte_same’? [-Werror=implicit-function-declaration]
  return update_time(h_inode, ts, flags);
         ^~~~~~~~~~~
         pte_same
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/sbinfo.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/module.o] Error 1
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/super.o] Error 1
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/aufs/4.19+20190211/build/fs/aufs/branch.o] Error 1
make[1]: *** [Makefile:1519: _module_/var/lib/dkms/aufs/4.19+20190211/build/fs/aufs] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.75+'
make: *** [Makefile:47: fs/aufs/aufs.ko] Error 2
make: Leaving directory '/var/lib/dkms/aufs/4.19+20190211/build'

**Comment by junsaw** [comment]
@cpuguy83 any recommendations here ?

**Comment by cpuguy83** [comment]
This looks relevant: https://github.com/raspberrypi/linux/issues/3021

I think I will propose we remove aufs from the list of recommended packages.
For users who are already using aufs they'll already have the package so upgrades shouldn't be a problem.

For now you an install with `--no-install-reccomends`, note that this may prevent some other desirable packages from being installed.

**Comment by junsaw** [comment]
Thanks I attempted to do that using the IoT Edge installation documentation and injecting the **--no-install-reccomends** and it fails.  The question is, is there anything on the roadmap to support Raspberry Pi 4,

**Comment by cpuguy83** [comment]
What fails?

If you use `--no-install-recommends` then the aufs modules will not be installed.

**Comment by cpuguy83** [comment]
Isn't rpi4 arm64 not armhf?

**Comment by junsaw** [comment]
Any suggestions ???  I guess what I am getting at is, is there anything in the pipeline to support Raspberry Pi 4 / Buster ?

**Comment by veyalla** [comment]
Supporting Buster as [Tier 1](https://docs.microsoft.com/en-us/azure/iot-edge/support#tier-1) is on our roadmap but not imminent.

**Comment by DmitryN270713** [comment]
Installing docker-ce does not exactly solves the issue, but container can be run at least. The issue that will be faced is:

× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.8' locally
    1.0.8: Pulling from azureiotedge-diagnostics
    6e39823df636: Pulling fs layer
    a7e88e83dd1d: Pulling fs layer
    a7e88e83dd1d: Verifying Checksum
    a7e88e83dd1d: Download complete
    6e39823df636: Verifying Checksum
    6e39823df636: Download complete
    6e39823df636: Pull complete
    a7e88e83dd1d: Pull complete
    Digest: sha256:4c850ef2bdf5092617d515e9e46e3382c01d44120399a86cb5eec57cd9383275
    Status: Downloaded newer image for mcr.microsoft.com/azureiotedge-diagnostics:1.0.8
    Error: could not execute list-modules request: an error occurred trying to connect: Connection refused (os error 111)

**Comment by DmitryN270713** [comment]
After configuring IoTEdge properly (docker-ce used instead of moby-engine by Microsoft) it seems like this temporary solution should help people with Buster.
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

19 check(s) succeeded.
4 check(s) raised warnings.

**Comment by V4A001** [comment]
Same isue here. Trying to run this example: https://devblogs.microsoft.com/iotdev/debug-iot-edge-c-or-csharp-linux-module-container-with-visual-studio-azure-iot-edge-tools/ on a Raspberry pi 2 or 3.

**Comment by cpuguy83** [comment]
segfault happens on buster (from a high level) due to static linking.
Unfortunately I haven't gotten much farther than that since delve (the golang debugger) does not currently support arm.

Tested with a dynamically linked binary and there's no segfault. So looking into this further.

**Comment by MrFr1tz** [comment]
Any news regarding this issue?

**Comment by cpuguy83** [comment]
I'll post when I have an update.
I'm still looking into integrating a fix into our build pipeline.

**Comment by MaxThom** [comment]
Here is how I installed iotedge on rpi4 with Raspbian Buster (must be a clean image without  ANY installation attempt) :

curl -sL get.docker.com | sed 's/9)/10)/' | sh
sudo usermod pi -aG docker
sudo reboot

sudo apt-get install libssl1.0.2

curl https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list > ./microsoft-prod.list
sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
sudo apt-get update
sudo apt-get -y install iotedge

sudo nano /etc/iotedge/config.yaml
ADD THE DEVICE TO THE IOTHUB AND SET PRIMARY CONNECTION STRING IN CONFIG.YAML

sudo systemctl restart iotedge

DO A DEFAULT DEPLOYMENT FROM THE IOTHUB DEVICE PAGE WITH Set Modules
You should see edgeAgent and edgeHub running with sudo iotedge list after a few minutes.

Hope it helps !!

**Comment by cpuguy83** [comment]
## This is intended for testing purposes only

I have uploaded some new packages to our testing repos which will hopefully resolve this issue.
Please give it a try if you can.
Note the packages are equivalent of docker engine's 19.03.6-rc2.

Assuming you already have the MS keys loaded (b/c you installed the old moby-engine package): 
```
$ sudo echo 'deb [arch=amd64] https://packages.microsoft.com/debian/10/prod testing main' > /etc/apt/sources.list.d/ms-testing.list
$ sudo apt-get update && sudo apt-get install -y moby-engine moby-cli
```

These new packages are no longer statically compiled.
Packages should install version  3.0.11~rc.0+azure-0, along with runc and containerd.

I do not currently have a timeframe for pushing these to the main repo.

**Comment by cpuguy83** [comment]
Azure moby packages should now run correctly on Raspbian. We don't have a Raspbian specific repo, but the Debian equivalent should work now.

**Comment by cpuguy83** [comment]
This would be starting with package versions 19.03.11 and up (note, we changed our versioning scheme to match the upstream moby versions now that moby has version tags).
