### ISSUE TITLE
Module desired property updates not delivered after module restarts 

### ISSUE THREAD

**Issue by yalaas** [Azure/iotedge#165]
## Expected Behavior

Module desired properties should be delivered to the module when they are updated in the cloud

## Current Behavior

If the module restarts, desired properties updates don't get delivered to the module 

## Steps to Reproduce

1. Remove the module e.g. docker rm -f {module name} 
2. Wait for edgeAgent to create and start the module 
3. Send a desired property update from Module Identity Twin in Azure Portal
4. Observe whether the update made it to the module

### Device (Host) Operating System

Debian 8

### Architecture

arm32

### Container Operating System

Linux containers
#### iotedged

iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent

1.0

#### Edge Hub

1.0

#### Docker

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:26:47 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:12 2018
  OS/Arch:      linux/arm
  Experimental: false

**Comment by varunpuranik** [comment]
Just to make sure I understand your problem correctly - 
- Your module on startup sets the DesiredPropertyUpdateCallback. 
- When you restart the module, this call completes successfully. 
- After this completes, you set the desired properties on that module twin in the portal
- The module never sees this.
Is that right? If so, can you send the EdgeHub logs during this period (after you kill the module, to when it doesn't get the desired properties though you expect it to).

Note that if the desired properties were set _while the module was restarting_, then the callback is not expected to fire. The module is expected to go an explicit GetTwin on startup.

**Comment by myagley** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen with the requested information. Thanks.
