### ISSUE TITLE
iotedge logs include --timestamp option

### ISSUE THREAD

**Issue by saoc90** [Azure/iotedge#1663]
## Expected Behavior
The iotedge logs command should support the --timestamp / -t command. This is useful when a modules gets restarted and it has set to a low debug level where it only shows error messages or for diagnostics reasons when I want to know when a error happened. [Docker](https://docs.docker.com/engine/reference/commandline/logs/) supports that argument.

## Current Behavior
```
PS C:\windows\system32> iotedge logs edgehub --tail 10 --timestamp
error: Found argument '--timestamp' which wasn't expected, or isn't valid in this context

USAGE:
    iotedge.exe logs <MODULE> --tail <NUM>

For more information try --help
```
This command is currently not supported according to the code:
[Code](https://github.com/Azure/iotedge/blob/master/edgelet/iotedge/src/main.rs)

### Device (Host) Operating System
Windwos IoT Professional 1809 LTSC

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

#### Docker
```
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 22:01:41 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by darobs** [comment]
Hell @saoc90,

This looks like a good idea for an enhancement, thank you.

**Comment by veyalla** [comment]
Please file or vote for existing feature request at https://feedback.azure.com/forums/907045-azure-iot-edge
