### ISSUE TITLE
Preserving desired properties when updating module

### ISSUE THREAD

**Issue by svejstrup** [Azure/iotedge#1670]
I'm developing a system using Iot Edge and would like to automate the deployment of new versions of a module. 

I have set up a CI/CD pipeline using the built-in steps in Azure Devops and configured it to deploy to multiple devices based on device tags. 

Each module is configured with device specific properties such as a location ID, update frequency and credentials for a local server it needs to contact.  Now the problem is that the generated deployment manifest contains module desired properties that will overwrite any properties already on the device, making me unable to deploy to multiple devices using the same deployment.

## Expected Behavior

Desired properties should not be updated if they are not specified in deployment manifest.

According to the [documentation](https://docs.microsoft.com/bs-latn-ba/azure/iot-edge/module-composition#define-or-update-desired-properties):
> If you do not specify a module twin's desired properties in the deployment manifest, IoT Hub won't modify the module twin in any way. Instead, you can set the desired properties programmatically.

## Current Behavior

If no desired properties (or only a subset) are specified in the deployment manifest, then all missing properties are set to null and removed from the device twin.

## Steps to Reproduce

1. Create module and set a desired property
2. Create deployment for device without specifying any desired properties in deployment manifest
3. Updated desired properties are sent to the module with value of each property set to null and twin is updated to have no desired properties

## Remarks
I'm not entirely sure if the current behavior is indeed intended and desired properties are just meant be more general so they can be updated for groups of devices at once.

**Comment by ancaantochi** [comment]
@svejstrup,

When there is no desired properties in the deployment do you set like below?
```
"myModule": {
  "properties.desired": {}
}
```
This will remove the existing desired properties.

If you don't want to modify the module twin you should remove the section all together. If you remove it from the deployment.template.json in the pipeline it should generate a deployment without the myModule desired properties.

**Comment by svejstrup** [comment]
yes you are absolutely right! I did what you said and also tried 
``` 
"myModule": {
}
```

which just resulted in an error, but i never tried removing the section all together. I seems to work as expected now, thank you very much! :)
