### ISSUE TITLE
iotedge release tar files missing c-shared and utpm folder contents

### ISSUE THREAD

**Issue by mohandatla** [Azure/iotedge#1685]
## Expected Behavior

Following folders with the content are expected to present so that build does not need to do git submodule recurse.
iotedge/edgelet/hsm-sys/azure-iot-hsm-c/deps/c-shared
iotedge/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm

## Current Behavior

Download the source tar file from release location and build RPM package
It is not building due to the following folders are missing in tar
iotedge/edgelet/hsm-sys/azure-iot-hsm-c/deps/c-shared
iotedge/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm
## Steps to Reproduce

1. Download the release tar file on Linux system. 
2. Extract the tar file.
3. On bash command prompt go to extracted folder location, for example iotedge.
cd iotedge/edgelet
make release 
It will through git submodule update error since this is not a typical git environment.

## Context (Environment)
Linux, arm64
### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
// Paste here
```
</details>

#### Docker

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by myagley** [comment]
Where are you downloading the release from? https://github.com/Azure/iotedge/releases?

I don't think this is expected to work. These tarballs are generated automatically by GitHub when we tag a release and I don't think GitHub supports submodules when they do this.

We do generate complete tarballs on the release repo at https://github.com/Azure/azure-iotedge. For example the `1.0.8` dist tarball is here: https://github.com/Azure/azure-iotedge/releases/download/1.0.8/iotedge-1.0.8.tar.gz

**Comment by myagley** [comment]
Yes, the `make release` target uses git to generate the tarball to produce the RPMs. You will need to have the repo cloned via git to make RPMs.

This works for us currently, but if you have a better way to make this work we'd be happy to take a pull request.

**Comment by mohandatla** [comment]
Thanks for checking on it. I do not aware of any better ways, i went ahead with git clone --recursive
