### ISSUE TITLE
IoT Edge start fail with DPS-TPM

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#1687]
Azure IoT Edge version: 1.0.7.1
OS: Ubuntu 18.04 (X64)
TPM: TPM simulator (https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm1332.tar.gz)
I can retrieve TPM EK by 'tpm_device_provision' (attached image)
![EK](https://user-images.githubusercontent.com/3096796/59670177-0d20ad00-91ee-11e9-9043-6536c8d82815.jpg)
But, fail on restart Azure IoT Edge by DPS-TPM.

Error Log:
-- Logs begin at Tue 2019-06-18 13:11:28 CST. --
Jun 18 17:23:56 tpm iotedged[2494]: Error: Time:Tue Jun 18 17:23:56 2019 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Line:258 creating tpm_comm object
Jun 18 17:23:56 tpm iotedged[2494]: 2019-06-18T09:23:56Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:initialize_tpm_device:272) Failure initializeing TPM Codec
Jun 18 17:23:56 tpm iotedged[2494]: 2019-06-18T09:23:56Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:hsm_client_tpm_create:305) Failure initializing tpm device.
Jun 18 17:23:56 tpm systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 17:23:56 tpm systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jun 18 17:23:56 tpm systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Jun 18 17:23:56 tpm systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 10.
Jun 18 17:23:56 tpm systemd[1]: Stopped Azure IoT Edge daemon.
Jun 18 17:23:56 tpm systemd[1]: Dependency failed for Azure IoT Edge daemon.
Jun 18 17:23:56 tpm systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.

Azure IoT Edge config.yaml:
# DPS TPM provisioning configuration
provisioning:
  source: "dps"
  global_endpoint: "https://global.azure-devices-provisioning.net"
  scope_id: "0ne0005784B"
  attestation:
    method: "tpm"
    registration_id: "lhvgfqxfmgapeaavnvdiz6bcd6nvfjjtwzcrsdl53ll47edmr54q"

**Comment by lt72** [comment]
@kkdawkins @arsing can you please take a look at this one and see if there is anything we can do?

**Comment by arsing** [comment]
Based on the log in the OP:

>>Jun 18 17:23:56 tpm iotedged[2494]: Error: Time:Tue Jun 18 17:23:56 2019 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Line:258 creating tpm_comm object

... I suspect that neither the `/dev/tpm0` device nor the `/dev/tpmrm0` device nor the `tpm2-abrmd` service were available at the time `iotedged` started. Though I expected to see a "Failure: connecting to the TPM device" log before that one in those cases.

Ref:

- https://github.com/Azure/azure-utpm-c/blob/036c2403cc0524ad6e4463a5887b74d388cc8a68/src/tpm_codec.c#L256-L258
- https://github.com/Azure/azure-utpm-c/blob/036c2403cc0524ad6e4463a5887b74d388cc8a68/src/tpm_comm_linux.c#L216-L218

>But, fail on restart Azure IoT Edge by DPS-TPM.

Does this mean that it worked once with the iotedge service, but then failed when you restarted the iotedge service? Or does it mean that it worked once with the iotedge service, but then failed when you restarted the device? Or does it mean that it never worked with the iotedge service?

I assume the TPM simulator creates either `/dev/tpm0` or `/dev/tpmrm0` ? If so, check that it creates them with permissions such that the iotedge service's user can read them.

**Comment by KevinKao809** [comment]
Hello,
Now, we used physical TPM device, so, this issue is not bother me any more.

**Comment by emilm** [comment]
> Based on the log in the OP:
> 
> > > Jun 18 17:23:56 tpm iotedged[2494]: Error: Time:Tue Jun 18 17:23:56 2019 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Line:258 creating tpm_comm object
> 
> ... I suspect that neither the `/dev/tpm0` device nor the `/dev/tpmrm0` device nor the `tpm2-abrmd` service were available at the time `iotedged` started. Though I expected to see a "Failure: connecting to the TPM device" log before that one in those cases.
> 
> Ref:
> 
> * https://github.com/Azure/azure-utpm-c/blob/036c2403cc0524ad6e4463a5887b74d388cc8a68/src/tpm_codec.c#L256-L258
> * https://github.com/Azure/azure-utpm-c/blob/036c2403cc0524ad6e4463a5887b74d388cc8a68/src/tpm_comm_linux.c#L216-L218
> 
> > But, fail on restart Azure IoT Edge by DPS-TPM.
> 
> Does this mean that it worked once with the iotedge service, but then failed when you restarted the iotedge service? Or does it mean that it worked once with the iotedge service, but then failed when you restarted the device? Or does it mean that it never worked with the iotedge service?
> 
> I assume the TPM simulator creates either `/dev/tpm0` or `/dev/tpmrm0` ? If so, check that it creates them with permissions such that the iotedge service's user can read them.

Correct! I tried to run tpm_server together with "tpm2-abrmd --tcti="mssim:host=localhost,port=2321" --allow-root"

I can successfully create EK with tpm2_getpubek -H 0x81010000 -g 0x01 -f ek.pub, convert that to base64 and use it in DPS. But I get the error:

```
<3>2019-12-05T16:28:21Z [ERR!] (/usr/src/debug/libiothsm-std/1.0.7-r0/iotedge-1.0.7/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_in_mem.c:ek_srk_unsupported:215) API unsupported
<3>2019-12-05T16:28:21Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
<3>2019-12-05T16:28:21Z [ERR!] -        caused by: HSM API failure occurred: 216
```

I use ibmswtpm2 v1332.

**Comment by arsing** [comment]
@emilm Your case is not the same as this issue. You're using libiothsm in in-memory TPM mode instead of TPM device mode, and the in-memory TPM mode does not implement EK functionality.

Release packages do not contain the in-memory TPM mode, so I assume you built `iotedge` locally. In that case, make sure you don't set `USE_TEST_TPM_INTERFACE_IN_MEM` to `ON` in the cmake command for libiothsm.

**Comment by emilm** [comment]
Thank you. I found out before you answered and corrected my post. Sorry.

I try to use yocto and meta-iotedge. https://github.com/Azure/meta-iotedge
It seems largely unmaintained right now and maybe it's causing problems. I am using _warrior_.

What I have noticed, is that from poking in that referred source code, it tries to connect to the old (and deprecated?) resourcemgr. The new resource manager for TPM seems to be tpm2-abrmd.

tpm2-abrmd does not have a socket interface on port 2123, thus iotedge will fail and fall back to /dev/tpm0 which I don't have, since I am running the IBM TPM2 sim.

My suggestion is to implement communication directly with tpm2-abrmd as well.
https://github.com/Azure/azure-utpm-c/blob/master/src/tpm_comm_linux.c#L39 - /usr/lib/arm-linux-gnueabihf/libtcti-socket.so.0 is not present in tpm2-tss 2.x. Only in 1.X: https://github.com/tpm2-software/tpm2-tss/blob/1.x/tcti/tcti_socket.cpp

**Comment by arsing** [comment]
If you see lines 32 and 33 of that file, you can see constants for tpm2-abrmd. Specifically, inside `tpm_usermode_resmgr_connect`, you can see it tries tpm2-abrmd before it tries the tcti-socket-based resource manager.

So if the tpm2-abrmd detection is also not working for you, you should probably open an issue against azure-utpm-c.

**Comment by emilm** [comment]
Thanks. Sorry for my ignorance.

I have no /dev/tpmrm0, so I have to investigate why it's not created. I had no idea that was the entry point to the management interface. Thanks!

**Comment by RandyWang131** [comment]
> > Based on the log in the OP:
> > > > Jun 18 17:23:56 tpm iotedged[2494]: Error: Time:Tue Jun 18 17:23:56 2019 File:/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Line:258 creating tpm_comm object
> > 
> > 
> > ... I suspect that neither the `/dev/tpm0` device nor the `/dev/tpmrm0` device nor the `tpm2-abrmd` service were available at the time `iotedged` started. Though I expected to see a "Failure: connecting to the TPM device" log before that one in those cases.
> > Ref:
> > 
> > * https://github.com/Azure/azure-utpm-c/blob/036c2403cc0524ad6e4463a5887b74d388cc8a68/src/tpm_codec.c#L256-L258
> > * https://github.com/Azure/azure-utpm-c/blob/036c2403cc0524ad6e4463a5887b74d388cc8a68/src/tpm_comm_linux.c#L216-L218
> > 
> > > But, fail on restart Azure IoT Edge by DPS-TPM.
> > 
> > 
> > Does this mean that it worked once with the iotedge service, but then failed when you restarted the iotedge service? Or does it mean that it worked once with the iotedge service, but then failed when you restarted the device? Or does it mean that it never worked with the iotedge service?
> > I assume the TPM simulator creates either `/dev/tpm0` or `/dev/tpmrm0` ? If so, check that it creates them with permissions such that the iotedge service's user can read them.
> 
> Correct! I tried to run tpm_server together with "tpm2-abrmd --tcti="mssim:host=localhost,port=2321" --allow-root"
> 
> I can successfully create EK with tpm2_getpubek -H 0x81010000 -g 0x01 -f ek.pub, convert that to base64 and use it in DPS. But I get the error:
> 
> ```
> Error: Time:Thu Dec  5 19:52:19 2019 File:/usr/src/debug/libiothsm-std/1.0.7-r0/iotedge-1.0.7/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_usermode_resmgr_connect Line:150 Failure: No user mode TRM found.
> Error: Time:Thu Dec  5 19:52:19 2019 File:/usr/src/debug/libiothsm-std/1.0.7-r0/iotedge-1.0.7/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_comm_create Line:216 Failure: connecting to the TPM device
> Error: Time:Thu Dec  5 19:52:19 2019 File:/usr/src/debug/libiothsm-std/1.0.7-r0/iotedge-1.0.7/edgelet/hsm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Line:258 creating tpm_comm object
> <3>2019-12-05T19:52:19Z [ERR!] (/usr/src/debug/libiothsm-std/1.0.7-r0/iotedge-1.0.7/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:initialize_tpm_device:272) Failure initializeing TPM Codec
> <3>2019-12-05T19:52:19Z [ERR!] (/usr/src/debug/libiothsm-std/1.0.7-r0/iotedge-1.0.7/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:hsm_client_tpm_create:305) Failure initializing tpm device.
> <3>2019-12-05T19:52:19Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
> <3>2019-12-05T19:52:19Z [ERR!] -        caused by: HSM API returned an invalid null response
> ```
> 
> I use ibmswtpm2 v1332.
> I run everything as root, including _IOTEDGE_USE_TPM_DEVICE=ON /usr/bin/iotedged -c /etc/iotedge/config.yaml_

Hi emilm,
May I ask how do you convert ek.pub to base64?
I used command #base64 ek.pub then copy the output to enrollment Azure IoT.
but it show the endorsement key is invalid.
Thanks.
