### ISSUE TITLE
EdgeAgent max properties exceeded

### ISSUE THREAD

**Issue by YohskDista** [Azure/iotedge#1694]
Hi everyone,

I recently found a problem with the creation of new modules in an IoT Edge device. We want to deploy between 15 and 20 modules in a device (I know that the limit for each device is 20) and we reach the limits of the module creations when we add the first 12 modules (with 11 modules it can deploy).

## Expected Behavior
I want to be able to deploy 20 modules as described in the Microsoft documentation [here](https://docs.microsoft.com/en-us/azure/iot-edge/module-composition)

## Current Behavior
I receive the follow message when I try to submit the modules deployment :

```
Failed To Set Modules
Forbidden:{
  "Message": "ErrorCode:DeviceModelMaxPropertiesExceeded;'Properties.Desired' size should be less than 8192 bytes.",
  "ExceptionMessage": "Tracking ID:c8d39c42e86f45c5b2eba92ad38ef4ba-G:14-TimeStamp:09/10/2019 13:48:12"
}
```

Each of my modules have 12 environment variables and we have ~800 characters for all environment variables in a module. I set the JSON below in the `Container Create Options` of the module creation :

```
{
    "env": [
        "VARIABLE_1=ValueForVariable1",
        "VARIABLE_2=ValueForVariable2",
        "VARIABLE_3=ValueForVariable3",
        "VARIABLE_4=ValueForVariable4",
        "VARIABLE_5=ValueForVariable5",        
        "VARIABLE_6=ValueForVariable6",
        "VARIABLE_7=ValueForVariable7",
        "VARIABLE_8=ValueForVariable8",
        "VARIABLE_9=ValueForVariable9",
        "VARIABLE_10=ValueForVariable10",
        "VARIABLE_11=ValueForVariable11",
        "VARIABLE_12=ValueForVariable12"
    ]
}
```

### Device (Host) Operating System
Windows 10 Professional

#### iotedged
1.0.6.1

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

**Comment by damonbarry** [comment]
What you're describing sounds about right. 800 chars-worth of environment variable data per module, for 12 modules; that's 9600 bytes. The environment variables for _all_ modules go into the desired properties section of `$edgeAgent`, so you're exceeding the 8K limit for the Edge Agent module.

That's a service-side limit (which I believe was increased from 4K not long ago). Given the current constraints, you'll need to find other ways to get that information to your modules.

**Comment by YohskDista** [comment]
I am just asking myself if it is the right place where to put the module deployment values. I think that some IoT devices will need to have more settings than usual and the limit of 8KB will not be enough for them.

I can understand that a limit must be set but if we think that each module can contain 8KB for desired properties, so the IoT Edge should have a more expanded memory size for this properties. We can have 20 modules in one IoT Edge, perhaps the limit could be 8KB per deployed modules (160KB) ? Or just use a different functionality for the module deployement instead of the desired properties.

**Comment by damonbarry** [comment]
Twin size and architecture are service-side concepts, so not really something we can address by changing the code in this repo.

You can use the Azure Feedback website to make requests for the service. I found a similar feedback item [here](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/33583492-iot-hub-device-and-module-twins-limit) that you can vote on.

There's also a sample [here](https://azure.microsoft.com/en-us/resources/samples/azure-iot-hub-large-twin-example/) that demonstrates how to use blob storage to extend your twin, but I haven't tried it myself.

**Comment by YohskDista** [comment]
Sorry for the late response. Thank you for your help, I will investigate how to do this with the blob storage.

Thank you for your time.
Best regards.
