### ISSUE TITLE
Set env variable RuntimeLogLevel to debug, no additional logging

### ISSUE THREAD

**Issue by chriswaters78** [Azure/iotedge#17]
Hi, I am trying to turn on debug level logging for the GA release. The instructions in the troubleshooting guide don't seem to make any difference to the logs produced. This is deployed to windows using linux containers.

I have set this env variable:

```
echo %RuntimeLogLevel%
debug
```

And restarted the modules / service / rebooted my machine. I still just get [INF] level logging for the edgeHub and edgeAgent modules:

```
[2018-07-11 14:56:28 : Starting Edge Agent
[07/11/2018 02:56:28.375 PM] Edge Agent Main()
2018-07-11 14:56:28.533 +00:00 [INF] - Starting module management agent.
2018-07-11 14:56:28.640 +00:00 [INF] - Version - 1.0.0.14487025 (52ef77db24126bf473265fc09c53d35290a2dd6b)
2018-07-11 14:56:28.641 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

2018-07-11 14:56:28.736 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via AMQP...
2018-07-11 14:56:29.152 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2018-07-11 14:56:32.998 +00:00 [INF] - Edge agent connected to IoT Hub via AMQP.
2018-07-11 14:56:33.384 +00:00 [INF] - Module 'edgeHub' scheduled to restart after 20s (13s left).
```

**Comment by damonbarry** [comment]
I assume you were looking [here](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#view-the-messages-going-through-the-edge-hub)?

Yeah, this looks like a doc bug. This environment variable must be set **in the Edge Hub and/or Agent containers** to see more logging output. You can do that by putting it in a special place in the config.yaml, or for Edge Hub only you can probably specify it in the deployment. But I'll need to gather the details.

I'll post the correct steps here, and also make a PR to the docs repo.

**Comment by damonbarry** [comment]
To see debug logs in Edge Agent and Edge Hub, update config.yaml (Linux: `/etc/iotedge/config.yaml`, Windows: `C:\ProgramData\iotedge\config.yaml`) by inserting the key-value pair `RuntimeLogLevel: debug` into element `agent.env`. E.g.:

```yaml
...

agent:
  name: edgeAgent
  type: docker
  env:
    RuntimeLogLevel: debug
  config:
    image: mcr.microsoft.com/azureiotedge-agent:1.0
    auth: {}

...
```

@chriswaters78 let me know if this works for you.

**Comment by chriswaters78** [comment]
@damonbarry Yes I am getting DBG level logging for both edgeAgent and edgeHub after making that change to my config.yaml file. Thanks.

**Comment by damonbarry** [comment]
Great! Closing...
