### ISSUE TITLE
Change IP address result in reported properties of module out of function for 5 mins

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#1705]
When change IP address on Edge device, the edgeHub can't send out reported properties of module to Azure IoT Hub until it got time out exception. This take 5 mins long.
## Expected Behavior

We would like to specify time out parameter. 
## Current Behavior

No way to specify time out configuration
## Steps to Reproduce

1. 
2. 
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
√ config.yaml has correct URIs for daemon mgmt endpoint
‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7.1 but version 1.0.8 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
‼ host time is close to real time
    Time on the device is out of sync with the NTP server. This may cause problems connecting to IoT Hub.
    Please ensure time on device is accurate, for example by installing an NTP daemon.
× container time is close to host time
    Detected time drift between host and container
√ DNS server
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry
√ production readiness: container engine
√ production readiness: logs policy

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
√ host can connect to and perform TLS handshake with IoT Hub MQTT port
√ container on the default network can connect to IoT Hub AMQP port
√ container on the default network can connect to IoT Hub HTTPS port
√ container on the default network can connect to IoT Hub MQTT port
√ container on the IoT Edge module network can connect to IoT Hub AMQP port
√ container on the IoT Edge module network can connect to IoT Hub HTTPS port
√ container on the IoT Edge module network can connect to IoT Hub MQTT port
√ Edge Hub can bind to ports on host

One or more checks raised errors. Re-run with --verbose for more details.

```
</details>

### Device (Host) Operating System

Debian
### Architecture

ARM32
### Container Operating System

Linux
#### iotedged

1.0.7.1
#### Edge Agent

1.0.8.1
#### Edge Hub

1.0.8.1
#### Docker

```
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 23:28:44 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Fri Apr 19 07:14:38 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
attached
[reported-timeout-5.log](https://github.com/Azure/iotedge/files/3603332/reported-timeout-5.log)

```
</details>

**Comment by myagley** [comment]
I'm trying to understand the scenario. The gateway's IP address is changed and the Edge Hub won't send reported property updates until the operation times out?

Does the reported property eventually get sent?

**Comment by KevinKao809** [comment]
Yes. The reported property be sent to Azure IoT Hub after timeout.

**Comment by lt72** [comment]
@ancaantochi can you please take a look when you have a chance?

**Comment by ancaantochi** [comment]
@KevinKao809, I will try to reproduce the issue and update here. The connection failure is expected, but I think what you would like is to be able to configure the timeout to a shorter period, it that right?

**Comment by KevinKao809** [comment]
@ancaantochi , right. we would like to define timeout by ourselves.

**Comment by ancaantochi** [comment]
@KevinKao809, 
we plan to have a shorter timeout of 1 minute in the next release (1.0.9), does it work for your case?

**Comment by KevinKao809** [comment]
It is better than current 5 min. It will be great, if the value can be defined by environment variable.

Kevin

取得 Android 版 Outlook<https://aka.ms/ghei36>

________________________________

**Comment by ancaantochi** [comment]
@KevinKao809, We release 1.0.9 version which should improve the reconnect time. At the moment it is not configurable, please let me know if it fixes the issue.

**Comment by KevinKao809** [comment]
Yes. I confirmed 1.0.9 fixed below issues:
- edgeHub able back to normal in seconds when change IP address.
- Telemetry no longer lost when change IP address.
- Telemetry send ordering is correct when change IP address.
