### ISSUE TITLE
Change IP address result in D2C message lost between custom module and edgeHub

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#1706]
When change IP address on Edge device, custom module can't send message to edgeHub for 2 mins, and some of message eventually lost when custom module got time out exception. 
## Expected Behavior

The custom module and edgeHub running as container app, and connect by internal private IP (I think so), change WAN IP address shall not impact their connectivity.
## Current Behavior

Custom module can't send out message to edgeHub for 2 mins, and finally result in some message lost.
## Steps to Reproduce

1.
2.
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
√ config.yaml has correct URIs for daemon mgmt endpoint
‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7.1 but version 1.0.8 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
‼ host time is close to real time
    Time on the device is out of sync with the NTP server. This may cause problems connecting to IoT Hub.
    Please ensure time on device is accurate, for example by installing an NTP daemon.
× container time is close to host time
    Detected time drift between host and container
√ DNS server
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry
√ production readiness: container engine
√ production readiness: logs policy

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
√ host can connect to and perform TLS handshake with IoT Hub MQTT port
√ container on the default network can connect to IoT Hub AMQP port
√ container on the default network can connect to IoT Hub HTTPS port
√ container on the default network can connect to IoT Hub MQTT port
√ container on the IoT Edge module network can connect to IoT Hub AMQP port
√ container on the IoT Edge module network can connect to IoT Hub HTTPS port
√ container on the IoT Edge module network can connect to IoT Hub MQTT port
√ Edge Hub can bind to ports on host

One or more checks raised errors. Re-run with --verbose for more details.
```
</details>

### Device (Host) Operating System

Debian
### Architecture

ARM32
### Container Operating System

Linux
#### iotedged

1.0.7.1
#### Edge Agent

1.0.8.1
#### Edge Hub

1.0.8.1
#### Docker

```
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 23:28:44 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Fri Apr 19 07:14:38 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.5
  GitCommit:        bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        2b18fe1d885ee5083ef9f0838fee39b62d653e30
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683


```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
attached: [d2c-2min.log](https://github.com/Azure/iotedge/files/3604219/d2c-2min.log)
```
</details>

## Additional Information

attached: IoTHub Monitor Log
[IoTHubMonitor.log](https://github.com/Azure/iotedge/files/3604223/IoTHubMonitor.log)

**Comment by lt72** [comment]
@KevinKao809 do you know why the IP address changes on Edge? Is that intentional, or part of your testing, etc...?

**Comment by lt72** [comment]
@varunpuranik any chance you can take a look at this one?

**Comment by KevinKao809** [comment]
Hi, About the IP change, this is common case when our IIoT Gateway connect with 3G/LTE cellular. It could happen many times especially when network is unstable.

**Comment by philipktlin** [comment]
Please provide all logs from edgeAgent, edgeHub and custom module; iotedge daemon log and iotedge check result for investigation.

**Comment by ancaantochi** [comment]
@KevinKao809, Is the custom module running on the host network or on azure-iot-edge docker network? By default it runs on azure-iot-edge if you didn't specify another network in the deployement

**Comment by KevinKao809** [comment]
Both，it was happen on both network mode.

取得 Android 版 Outlook<https://aka.ms/ghei36>

________________________________

**Comment by ancaantochi** [comment]
On host network it is expected the connection would fail when the IP was changed. By message loss do you mean that the module was not able to send it to edge hub or does the message send completes successfully but edge hub losses it? The custom module has to handle exceptions and it should retry to send the message.

Can you please attach logs that were requested by  when the custom module is in azure-iot-edge network?

**Comment by chipalost** [comment]
@KevinKao809 , are you still seeing this issue? If so, please provide additional logs so that we can do further investigation.

**Comment by veyalla** [comment]
Closing, please re-open if you are still running into this and please provide logs.
