### ISSUE TITLE
EdgeHub throwing HSM failure issue

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#1719]
Hi,

I have got an IoT Edge server (linux and behind proxy) started giving HSM failure issue. I have restarted the iotedge and it fixed that issue.

Last time I had TLS auth issue which was caused by expired certificate. Can be see at https://github.com/Azure/iotedge/issues/1331 I believe this is not the same issue.

I want to know the root cause of this issue. Will it pop again etc?

Please find the edgeHub logs.
[edgeHub-logs.txt](https://github.com/Azure/iotedge/files/3618761/edgeHub-logs.txt)

Thanks,
Muhammad Masood

**Comment by kkdawkins** [comment]
If you don't configure your own certificates, iotedge will generate default certificates for quick startup.  The self-generated certs are short-lived and meant for dev use. This could explain why the device began failing with a TLS auth issue, and why a reboot solved the problem (the cert would be recreated).
