### ISSUE TITLE
Is there any way to find memory metrics on Windows IoT Core for running modules

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1725]
Hi Team,
i need to find gateway memory metrics for running edge containers on Win IoT Core. I can see there are few commands are available to find-->  **docker stat**

Is there anyway to find memory metrics(CPU utilisation, free and used memory) on IoT Core gateway.

## Steps to Reproduce

1.
2.
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
// Paste here
```
</details>

### Device (Host) Operating System
Windows IoT Core

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged
`iotedge version- 1.0.8`

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0.8

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0.8

#### Docker

```
<Run `docker version` (`docker -H npipe:////./pipe/iotedge_moby_engine version` for Moby on Windows) and paste here>
```

## Logs

<details>
<summary>iotedged logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-agent logs</summary>

```
<Paste here>
```
</details>

<details>
<summary>edge-hub logs</summary>

```
<Paste here>
```
</details>

**Comment by veyalla** [comment]
There is no first-class support in IoT Edge for this today. It is on the roadmap but work hasn't been scheduled yet. For now, you'll have to write a custom module that provides this info.

**Comment by pratson20** [comment]
Hi @veyalla I am able to retrieve Disk storage, CPU utilisation, RAM memory in Windows 10 OS platform, but in Wind IoT Core same solution is working for disk space but not working for CPU utilisation and RAM memory, showing below error-

**Unhandled Exception: System.AggregateException: One or more errors occurred. (Access to the registry key 'Global' is denied.) ---> System.UnauthorizedAccessException: Access to the registry key 'Global' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalGetValueCore(String name, Object defaultValue, Boolean doNotExpand)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)**




Code Snippet to Data Storage- Working on IoT Core


            DriveInfo[] allDrives = DriveInfo.GetDrives();

                foreach (DriveInfo d in allDrives)
                {
                    Console.WriteLine("Drive {0}", d.Name);
                    Console.WriteLine("  Drive type: {0}", d.DriveType);
                    if (d.IsReady == true)
                    {
                        Console.WriteLine("  Volume label: {0}", d.VolumeLabel);
                        Console.WriteLine("  File system: {0}", d.DriveFormat);
                        Console.WriteLine(
                            "  Available space to current user:{0, 15} bytes", 
                            d.AvailableFreeSpace);

                        Console.WriteLine(
                            "  Total available space:          {0, 15} bytes",
                            d.TotalFreeSpace);

                        Console.WriteLine(
                            "  Total size of drive:            {0, 15} bytes ",
                            d.TotalSize);
                    }
                }


Code Snippet to CPU utilisation/RAM memory usage- Not working

        private static void InitialiseCPUCounter()
        {
            cpuCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total", true);
        }

        private static void InitializeRAMCounter()
        {
            ramCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total");
        }


Can you please help on this if any registry need to bee added for IoT Core to fix CPU utilisation/ RAM memory.


Thanks,
Prateek

**Comment by lt72** [comment]
@philipktlin can you point @veyalla to some IoT Core team member that could explain the different in behavior?

**Comment by philipktlin** [comment]
@pratson20 please help to provide what exact version and build number of both Windows 10 and Windows IoT Core you used.

**Comment by philipktlin** [comment]
Also @pratson20 did you check docker stats? and "/containers/(id)/stats" docker API endpoint?

**Comment by pratson20** [comment]
Hi @philipktlin , I am using Windows IoT Core version -10.0.17763.737

Not tried docker stats. Can you please send some reference to use Docker API endpoint

**Comment by veyalla** [comment]
Please file or vote for existing feature request at https://feedback.azure.com/forums/907045-azure-iot-edge
