### ISSUE TITLE
Store Private key for X.509 based DPS securely

### ISSUE THREAD

**Issue by mma-mm** [Azure/iotedge#1728]
Hello,

i'd like to use the X.509-based enrollment in DPS. How can I use the Provisioning in IoTEdge without storing the private key on file system? I'd like to store the Private Key in a HSM and let it never leave. 

How do i need to edit the config.yaml to make it use a hsm? And what API do i need to implement for the HSM access?

Best regards

**Comment by myagley** [comment]
Unfortunately, this scenario is not enabled yet, but is actively being worked on. At this moment, the x.509 provisioning mode only supports a private key on the file system.

**Comment by mma-mm** [comment]
Are there any news on this issue?

**Comment by lt72** [comment]
@mma-mm we are actively working on enabling this feature, but I cannot offer an ETA at this time.

**Comment by asergaz** [comment]
@lt72 should we create [a Feedback](https://feedback.azure.com/forums/907045-azure-iot-edge) entry for this requesT? 

@skyizthelimit requesting the same feature.

Thanks!

**Comment by asergaz** [comment]
I have created a Feedback Request, please vote: https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/39457678-store-private-key-for-x-509-based-dps-securely-on
