### ISSUE TITLE
How to investigate "Could not create module" errors?

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#1745]
## Expected Behavior
Module starts. If module does not start because of an error should be shown, which indicates what has really caused the module to fail. The only error I see is:

> Container runtime error (See below pasted log)

This is not helpful. Unfortunately, because the module does not start, it is also not possible to see any log information.

QUESTION: What is the best practice to investigate such kind of issue?

## Current Behavior
Module cannot be loaded, because of an error. It is probably some error in module itself or some configuration error.
This is exactly the issue, because it is not know what kind of error it is.

## Steps to Reproduce
Deploy module

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
‼ config.yaml has correct hostname - Warning
    config.yaml has hostname Abcde-SR1 which does not comply with RFC 1035.

    - Hostname must be between 1 and 255 octets inclusive.
    - Each label in the hostname (component separated by ".") must be between 1 and 63 octets inclusive.
    - Each label must start with an ASCII alphabet character (a-z), end with an ASCII alphanumeric character (a-z, 0-9), and must contain only ASCII alphanumeric characters or hyphens (a-z, 0-9, "-").

    Not complying with RFC 1035 may cause errors during the TLS handshake with modules and downstream devices.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

15 check(s) succeeded.
```
</details>

### Device (Host) Operating System
Windows 10 

### Architecture
amd64,

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.8

#### Edge Agent
1.0.8

#### Edge Hub
1.0.8

#### Docker

```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Logs

<details>
<summary>edge-agent logs</summary>

```
2019-09-24 07:45:18.506 +00:00 [WRN] - Reconcile failed because of the an exception
System.AggregateException: One or more errors occurred. (Error calling Create module publisher: Could not create module publisher
        caused by: Could not create module publisher
        caused by: Container runtime error
        caused by: expected value at line 1 column 1) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling Create module publisher: Could not create module publisher
        caused by: Could not create module publisher
        caused by: Container runtime error
        caused by: expected value at line 1 column 1
```
</details>

**Comment by arsing** [comment]
For Windows, you look in Event Viewer / use `Get-EventLog` for the logs of the `iotedge` service.

**Comment by ddobric** [comment]
Hi arsing,

thanks for your feedback. Unfortunately, EventLog contains same error. :(
I din't want to spam this issue with that information:

`. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Get-IoTEdgeLog`

Damir

**Comment by arsing** [comment]
Yes, so the Docker HTTP API returned invalid JSON to iotedged. Specifically since the error is at line 1 column 1, that means the response body did not start with the `{` that we expect for the start of a JSON object. Every create-container API response from Docker should be either a success with a JSON body or an error with a JSON body.

We don't know whether it was a success status code with a body that wasn't [a valid `InlineResponse201` JSON object,](https://github.com/Azure/iotedge/blob/0017968b93adb651dec90039fc794b4de5f71789/edgelet/docker-rs/src/apis/container_api.rs#L534-L536) or an error status code with a body that wasn't [a valid JSON value,](https://github.com/Azure/iotedge/blob/0017968b93adb651dec90039fc794b4de5f71789/edgelet/docker-rs/src/apis/mod.rs#L29-L35) because we throw away the status code in the latter case that would've helped to differentiate between the two situations. We should log that. Also, we should also try log the original unparsed body in case that has a clue.

It would be useful to know what version of Docker you're using. (You've not run `docker version` correctly in the issue template - you've run it against Moby even though you're using Docker, since you said you're using Linux containers.)

In the short term you can try:

- Check event log for Docker service's logs.

- Create the container manually with the same create options and see if that works.

- Snoop the TCP traffic between iotedged.exe and dockerd.exe to capture the actual create-container request and response.

**Comment by ddobric** [comment]
Hi @arsing,

docker version is :
`Docker version 19.03.2, build 6a30dfc. `

Regarding incorrect JSON. Yes, I agree. Error looks like parsing issue. The problem for us is that we do not really deal with JSON. Th eonly JSON I have used is this one, which is copied from [opcpublisher [documentation.](https://github.com/Azure/Industrial-IoT/blob/master/docs/modules/publisher.md)

```
{
        "Hostname": "publisher",
        "Cmd": [
            "--pf=/appdata/pn.json",
            "--aa"
        ],
        "HostConfig": {
            "Binds": [
                "d:/iiotedge:/appdata"
            ]
        }
    }
```

This JSON seems to be somehow, somewhere concatenated with JSON used by docker. I even do not know where this JSON is deployed by iotedge?

I tried _docker inspect_, but didn't find anything related.

Also looked in C:\ProgramData\iotedge\config.yaml



Regarding Docker EventLog, there is no any warning/error in there.

**Comment by arsing** [comment]
>The only JSON I have used is this one

Any JSON you use is irrelevant. The three options I gave you have nothing to do with that. Regardless of whatever you do, Docker is supposed to return JSON from the create-containers API.

**Comment by ddobric** [comment]
Hi @arsing ,

here are comments on 3 proposed options:

-  Check event log for Docker service's logs.
_There is no log, because container was never started._

-  Create the container manually with the same create options and see if that works.
 _I do not know how container should be started the same way as withing iotedge. I have an idea about it, but not quite sure. I guess, I will have to provide some environment variables with connection string, etc. Is that somewhere documented?_

-  Snoop the TCP traffic between iotedged.exe and dockerd.exe to capture the actual create-container request and response.
_Communication is established between components. Following trace indicates that request was successfully received by iotedged service. Unfortunately service fails with 500_ 

>      caused by: expected value at line 1 column 1, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs:line 194

Damir

**Comment by veyalla** [comment]
The JSON CreateOptions might have been for Linux containers on Windows. This configuration is not supported in [production](https://docs.microsoft.com/en-us/azure/iot-edge/support#operating-systems).

If you are using Windows containers, give this a try:
```
{
        "Hostname": "publisher",
        "Cmd": [
            "--pf=/appdata/pn.json",
            "--aa"
        ],
        "HostConfig": {
            "Binds": [
                "d:/iiotedge:c:/appdata"
            ]
        }
    }
```

**Comment by CindyXing** [comment]
Besides letting customers to look at logs at edge, I think we should upstream any error/failure to the cloud. Potentially the telemetry channel can be used.

**Comment by ddobric** [comment]
This is solved. Please take a look [here](https://github.com/Azure/Industrial-IoT/issues/116).
