### ISSUE TITLE
How to view deployment status in iot edge device?

### ISSUE THREAD

**Issue by Anil-Poolayulla-Chelottillam** [Azure/iotedge#1747]
**Is there any way to see the deployment progress from iot edge device?** 

My use case :
 > EDGE Device will initiate provisioning.
 > The DPS will start deployment.
 > EDGE Device should display 'deployment complete' message once all modules specified in manifest downloaded. 

I know that deployment status can be seen on cloud. but here I need to know it from device.

**Comment by arsing** [comment]
`docker images` (or the `curl` equivalent against the dockerd unix socket) will tell you when the images you care about have been downloaded. `docker ps` or `iotedge list` will tell you when the containers you care about have started running.
