### ISSUE TITLE
Unable to Built and Push IoT edge solution with azure Devops 

### ISSUE THREAD

**Issue by arnabhetc** [Azure/iotedge#1755]
Hi, 
I am trying to built and push azure edge solution using  Azure DevOps

- My code will be build for Running in Windows container ( Windows-amd64)
- My code is in azure repository 

As my code is in azure Pipeline , so while Building I have selected the Azure Pipelines in the agent pool 

- Like bellow --> 

<img width="1160" alt="Screenshot 2019-09-26 at 1 39 47 PM" src="https://user-images.githubusercontent.com/47913360/65670717-863c6580-e063-11e9-8b34-834379b93dd7.png">

Now for agent i Have Used  "win1803" in the first and build the solution , now for release

I have created a tasks -->

<img width="1181" alt="Screenshot 2019-09-26 at 1 00 00 PM" src="https://user-images.githubusercontent.com/47913360/65670455-02827900-e063-11e9-99b2-bc98355baedc.png">

This is the settings for the " IoT Edge Build"  -->

<img width="600" alt="Screenshot 2019-09-26 at 1 08 23 PM" src="https://user-images.githubusercontent.com/47913360/65670848-c4d22000-e063-11e9-9f74-2464b4b1be37.png">

Now getting error while i release the solution and in that in the " Build module images"  i got the bellow error -->

-  when i used " Windows 1803"  Microsoft hosted agent  while building -->

<img width="1152" alt="Screenshot 2019-09-26 at 12 28 05 PM" src="https://user-images.githubusercontent.com/47913360/65668370-38256300-e05f-11e9-9a28-027487d5865f.png">

- when i used " vs2017-win2016 " i got the bellow error -->

 https://textuploader.com/108xh

This are the [list](https://docs.microsoft.com/en-gb/azure/devops/pipelines/agents/hosted?view=azure-devops)  of the hosted agent provided by Microsoft, which one should we use if not then what else we have to do ?

@azure-sdk  @iotedge-ci

**Comment by arsing** [comment]
Please stop @-spamming groups in every issue you own.
