### ISSUE TITLE
Unable to build &  push IoT Edge solution using Azure Devops

### ISSUE THREAD

**Issue by arnabhetc** [Azure/iotedge#1757]
Hi,
I am trying to built and push azure edge solution using Azure DevOps

My code will be build for Running in Windows container ( Windows-amd64)
My code is in azure repository
As my code is in azure Pipeline , so while Building I have selected the Azure Pipelines in the agent pool

Like bellow -->

![image](https://user-images.githubusercontent.com/47913360/65701998-e4873980-e09f-11e9-9acf-18322419c95e.png)

Now for agent i Have Used "win1803" in the first and build the solution , now for release

I have created a tasks -->

![image](https://user-images.githubusercontent.com/47913360/65702120-16989b80-e0a0-11e9-9c25-001101dbdf61.png)

This is the settings for the " IoT Edge Build" -->

Screenshot 2019-09-26 at 1 08 23 PM

Now getting error while i release the solution and in that in the " Build module images" i got the bellow error -->

when i used " Windows 1803" Microsoft hosted agent while building -->

![image](https://user-images.githubusercontent.com/47913360/65702206-40ea5900-e0a0-11e9-80ea-6022014fda96.png)

when i used " vs2017-win2016 " i got the bellow error -->
https://textuploader.com/108xh

This are the [list](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops) of the hosted agent provided by Microsoft, which one should we use if not then what else we have to do ?

**Comment by veyalla** [comment]
@shizn can you PTAL

**Comment by shizn** [comment]
Thanks for looping me in. This is a known issue, we are investigating this at this moment.

**Comment by pratson20** [comment]
Hi @shizn  , Do you have any timeline for this or any alternate fix for short-term. We have build pipeline for Ubuntu 16.0.4 and its working but have to migrate to Windows IoT Core .

Thanks

**Comment by shizn** [comment]
@pratson20  after double checked your screenshot, I noticed you are using windows 1803 as the build agent, which is not supported by IoT Edge. Our document suggest user create self hosted win1809 build agent to build windows-amd64 images. You can also use vs2019-winserver2019 agent pool, which currently uses win1809.

**Comment by veyalla** [comment]
@pratson20 could you please email me at veyalla@microsoft.com. I’d love to learn a bit more about your scenario.

**Comment by arnabhetc** [comment]
@shizn  we tried with the option " Windows-2019" , but got the same error !  We tried with the "vs2017-win2016 " also but  here got [this](https://textuploader.com/108xh) error

**Comment by blackchoey** [comment]
@arnabhetc Can you share me the Azure Pipelines log when building IoT Edge module on windows-2019 agent?

**Comment by pratson20** [comment]
Hi @blackchoey , @shizn I am able to fix the issue after upgrading the nuget package from 4.3.0 to 5.3.0 with windows-2019 agent.


![image](https://user-images.githubusercontent.com/7486266/65858869-a0888300-e384-11e9-9640-e6a09a3b7db1.png)



I am not sure how it is dependent on nuget pacakge for windows-amd64 build, same build pipeline is working for amd64 for Ubuntu 16.0.4


Hi @veyalla  I have some additional design and implementation challenges that information will send to you over an email.



Thanks,
Prateek

**Comment by lt72** [comment]
Closing this issue as it seems resolved, please feel free to re-open as needed.
