### ISSUE TITLE
This device has an empty configuration for the edge agent - error when deploying using Azure DevOps

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#1769]
Hi,

I have got two devices (running in Linux server behind proxy). I am using Azure DevOps to push some configurations to IoT Edge mdoules using Desired Properties through Azure DevOps IoT Edge deployment.

When I deploy modules using Azure Portal it works fine. But as soon as I deploy modules using Azure DevOps I got below error (edgeAegnt logs):
<6> 2019-09-30 10:17:47.105 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2019-09-30 10:17:47.105 +00:00 [ERR] - Edge agent failed to process desired properties update patch
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 245
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.ApplyPatchAsync(TwinCollection desiredProperties, TwinCollection patch) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 225

When I restart "edgeAgent" module, it fixes the issue and passes the updated configurations to IoT Edge modules.

I really need to fix it as in Production we won't be restarting edgeAgent after each configurations refresh.

Can you please assist on this?

Thanks,
Muhammad Masood

**Comment by damonbarry** [comment]
The `ConfigEmptyException` in the edge agent logs is normal; it just means there's no deployment.

So the question becomes: why isn't the agent receiving the deployment? @shizn Can you help?

**Comment by lt72** [comment]
Closing as stale, please re-open as needed.
