### ISSUE TITLE
Collection of logs generated by apps running in modules

### ISSUE THREAD

**Issue by harika-thallam** [Azure/iotedge#1787]
Hi team,
I am looking for a solution to send the application logs generated on iot edge devices to an azure log analytics workspace.

I have tried using the Microsoft Monitoring agent using which I was able to send logs generated by running docker containers. However, on an edge device, we are using the moby engine instead of the docker daemon because of which monitoring agent is not collecting the log records(followed this set up to run with docker - https://docs.microsoft.com/en-us/azure/azure-monitor/insights/containers#install-and-configure-windows-container-hosts). Moreover, since I am running my edge environment on windows, I didn't find any container image of monitoring agent targeted for windows.(present for Linux https://hub.docker.com/r/microsoft/oms/)
## Expected Behavior
Able to stream application logs to log analytics workspace possibly using the Microsoft Monitoring agent 

## Current Behavior
Tell us what happens instead of the expected behavior

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS : Windows IoT Core
* Architecture : amd64
* Container OS:  Windows containers

### Runtime Versions
* iotedged : 1.0.8
* Edge Agent : mcr.microsoft.com/azureiotedge-agent:1.0
* Edge Hub : mcr.microsoft.com/azureiotedge-hub:1.0
* Docker/Moby : 
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 22:01:41 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          windows/amd64
  Experimental:     false
Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
I looking for a completely automated way of streaming application logs to azure log analytics workspace.

**Comment by veyalla** [comment]
This is not yet supported in a first-class manner but something we'd like to enable in a future release. 

As of now, [experimental log pull feature](https://github.com/Azure/iotedge/blob/master/doc/built-in-logs-pull.md) is closest feature we have for Windows around this scenario.

**Comment by harika-thallam** [comment]
Thanks for the reply veyalla, 
May I know if this something that is actively worked upon and available for next release or is it way down in your roadmap ?

**Comment by harika-thallam** [comment]
![image](https://user-images.githubusercontent.com/53911193/66470300-f062fa80-eaa6-11e9-9a3c-d893d500c736.png)
 I am trying to test the upload logs method from azure cloud cli and I get the error as in image .
Are there any specific things i am missing out ?

**Comment by veyalla** [comment]
@harika-thallam automatic log push is on the longer term roadmap.

For the issue with the experimental log pull, please look at the guidance in https://github.com/Azure/iotedge/issues/1590#issuecomment-527545210

**Comment by harika-thallam** [comment]
Thank you @veyalla.

**Comment by harika-thallam** [comment]
I understand that the features you have directed me to are in the experimental stage. Is there any recommended/preview feature that may be more production fit?

**Comment by veyalla** [comment]
Not currently, but the log pull mechanism in going to be GA in the next release.
