### ISSUE TITLE
Version in reported properties not getting updated for Get Module Twin service

### ISSUE THREAD

**Issue by lijithomas88** [Azure/iotedge#1800]
## Expected Behavior

version in reported properties also should get updated once the module update happens on  iotedgedevice. 

## Current Behavior
Tell us what happens instead of the expected behavior
sample response

```json
{
    "deviceId": "myEdgeDevice",
    "moduleId": "samplemodule",
    "etag": "AAAAAAAAAAI=",
    "deviceEtag": "OTk2NDM3MzUz",
    "status": "enabled",
    "statusUpdateTime": "0001-01-01T00:00:00",
    "connectionState": "Disconnected",
    "lastActivityTime": "2019-10-03T10:47:20.7116741",
    "cloudToDeviceMessageCount": 0,
    "authenticationType": "sas",
    "x509Thumbprint": {
        "primaryThumbprint": null,
        "secondaryThumbprint": null
    },
    "version": 3,
    "properties": {
        "desired": {
            "settings": {
                "image": "test.azurecr.io/samplemodule:0.0.1-arm32v7",
                "createOptions": ""
            },
            "$metadata": {
                "$lastUpdated": "2019-10-03T10:47:19.5741198Z",
                "$lastUpdatedVersion": 2,
                "settings": {
                    "$lastUpdated": "2019-10-03T10:47:19.5741198Z",
                    "$lastUpdatedVersion": 2,
                    "image": {
                        "$lastUpdated": "2019-10-03T10:47:19.5741198Z",
                        "$lastUpdatedVersion": 2
                    },
                    "createOptions": {
                        "$lastUpdated": "2019-10-03T10:47:19.5741198Z",
                        "$lastUpdatedVersion": 2
                    }
                }
            },
            **"$version": 2**
        },
        "reported": {
            "$metadata": {
                "$lastUpdated": "2019-10-03T10:44:30.0767468Z",
                **"$lastUpdatedVersion": 1**
            },
            **"$version": 1**
        }
    }
}
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.  Invoke api 
https://fully-qualified-iothubname.azure-devices.net/devices/{deviceId}/applyConfigurationContent?api-version=2018-06-30
by providing a deployment json with a image in Azure container regsitry. 
sample request
```json
{
    "modulesContent": {
        "$edgeAgent": {
            "properties.desired": {
                "modules": {
                    "samplemodule": {
                        "settings": {
                            "image": "test.azurecr.io/childmodule1:0.0.1-amd64",
                            "createOptions": ""
                        },
                        "type": "docker",
                        "version": "3.0",
                        "status": "running",
                        "restartPolicy": "always"
                    }
                },
                "runtime": {
                    "settings": {
                        "minDockerVersion": "v1.25",
                        "registryCredentials": {
                            "test": {
                                "address": "test.azurecr.io",
                                "password": "",
                                "username": ""
                            }
                        }
                    },
                    "type": "docker"
                },
                "schemaVersion": "1.0",
                "systemModules": {
                    "edgeAgent": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
                            "createOptions": ""
                        },
                        "type": "docker"
                    },
                    "edgeHub": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
                            "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}]}}}"
                        },
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always"
                    }
                }
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "routes": {
                    "route": "FROM /messages/* INTO $upstream",
		    "route1": "FROM /messages/modules/* INTO $upstream"		
                },
                "schemaVersion": "1.0",
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        },
        "samplemodule": {
            "properties.desired": {
            	"settings": {
            	    "image": "test.azurecr.io/childmodule1:0.0.1-amd64",
                    "createOptions": ""
                }
            }
        }
    }
}
```

2. Again invoke the above api by pointing to another image for the same module. 
3.  On invoking Get Module Twin api,
https://fully-qualified-iothubname.azure-devices.net/twins/{id}/modules/{mid}?api-version=2019-07-01-preview
desired properties version changes to 2.
reported properties version remains as 1 even after the module is updated in iotedgdedevice.
Latest image uri is also not showing for reported properties. 
Above version update is happening in Azure portal under Iot Edge Module Details section for IotHub for desired and reported properties. 

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by damonbarry** [comment]
The desired and reported properties in the twin implement an eventual consistency model: the cloud tells the device what it desires, and the module reports back what was actually achieved. The module does not _have_ to echo the desired properties to the reported properties, and replication of desired to reported does not happen automatically. Is your sample module doing anything to update the reported properties?

Side note: In your deployment, you're specifying the sample image twice: once in the edge agent's desired properties, and once in the desired properties of the same module itself. Nothing prevents you from doing that, but your sample module shouldn't need to know its own docker image, so adding it there is probably unnecessary. The edge agent is the module that needs to know the image URIs of all edge modules.

**Comment by lijithomas88** [comment]
On invoking module twin api for $edgeAgent, able to see all information regarding reported properties. 
https://pepsico-iot-platform-deployment-test.azure-devices.net/twins/myEdgeDevice/modules/$edgeAgent?api-version=2019-07-01-preview

Before I was invoking this api with my custom module instead of edgeAgent. 
Thanks for providing the information.
