### ISSUE TITLE
Tests failed with message "The configuration file 'context.json' was not found and is not optional"

### ISSUE THREAD

**Issue by SychevIgor** [Azure/iotedge#1809]
While researched sources codes faced with an error in tests:

OneTimeSetUp: System.IO.FileNotFoundException : The configuration file 'context.json' was not found and is not optional. The physical path is 'C:\src\iotedge\test\Microsoft.Azure.Devices.Edge.Test\bin\Debug\netcoreapp2.1\context.json'.
As a result - multiple tests failed. I didn't not find file like "context.json" in the entire repository and didn't not find a guide - how to create it. 
Please, provide a guide for contributors how to setup this project properly to be sure that test environment works.

## Expected Behavior
Green tests

## Current Behavior
Red tests. Tests failing 

## Steps to Reproduce
Run tests any of the following test from VS2019 test explorer 
![image](https://user-images.githubusercontent.com/578954/66252911-8f1aee80-e769-11e9-9a8c-790b4199e812.png)

**Comment by SychevIgor** [comment]
Could you add a link on this readme to https://github.com/Azure/iotedge/blob/master/doc/devguide.md ? Because link from root readme referencing only devguide and I didn't find link to https://github.com/Azure/iotedge/blob/master/test/README.md

**Comment by damonbarry** [comment]
Sure. Or feel free to submit a PR... 😃

**Comment by lt72** [comment]
@vipeller: can we take care of this?

**Comment by joeyadamhenry** [comment]
I'm not sure what to do

**Comment by SychevIgor** [comment]
ping

**Comment by damonbarry** [comment]
#2740 covers this I think.
