### ISSUE TITLE
Reported properties are not sent using the device SDK

### ISSUE THREAD

**Issue by IvanBoychevMarinov** [Azure/iotedge#1820]
## Expected Behavior
Have the device reported properties visible in the cloud after executing the sendReportedProperties method,

## Current Behavior
The method passes without any exception but the reported properties are not available in the cloud.

## Steps to Reproduce
Unfortunately I just got it, after a week without using the edge 
1. Leave the edge run for long time
2. Run your application and send some reported properteis
3. The reported properties are not visible in the hub
4. Restart iotedge
5. Send some device reported properties
6. The reported properties are now visible in the hub.
## Context (Environment)
Raspbian stretch on Raspberry PI 3
### Output of `iotedge check`
Unfortunatelly this command is not available on razspberry

### Device Information
* Raspbian stretch
* Architecture arm32 
* Container OS Linux containers 

### Runtime Versions
* iotedged iotedge 1.0.6.1
* Edge Agent 1.0.8.1.24554792 (8a9cfedfc6c7455c080dcee6ee21978069024d2f)
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby 3.0.2

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```
```
</details>
# Additional Information
Sorry, Nothing more to say. I just saw the reported properties are missing. I verified my code behaves as expected, then restarted the iotedge and then the reported properties were available.
I will try to upload the whole log from the edge hub, but it is huge.
[hubLogs.txt](https://github.com/Azure/iotedge/files/3702382/hubLogs.txt)

**Comment by kkdawkins** [comment]
Thanks for the report! That's a really old version of iotedge - Does this behavior happen on our current release 1.0.8.2?

**Comment by IvanBoychevMarinov** [comment]
I'm about to upgrade it now and see if this happens. Unfortunately as I said, I'm not even sure how this happened, so I would not be able to confirm if this happens, or not. I will try to reproduce it, but as I said, all I did was just not touch it for about a week.

**Comment by kkdawkins** [comment]
Gotcha - Well let me know if you see the issue again, and I will be happy to help investigate more.

**Comment by IvanBoychevMarinov** [comment]
Thanks! The runtime is already updated and now we have to wait :smile:  I will try to provide some feedback the next couple of weeks. In the meanwhile, I think we can close this, and reopen if still reproducible with the latest version. What do you think?

**Comment by kkdawkins** [comment]
Sounds great @IvanBoychevMarinov ! I will go ahead and close this issue but please do re-open if you can repro with our updated runtime. :) Thanks for reporting.
