### ISSUE TITLE
Add Azure Stream Analytics Iot Edge Module in a Solution using Visual Studio Code

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#1827]
Hi,
I'm trying to add an Azure Stream Analytics job in my Iot Edge Solution, using Visual Studio Code, but I keep receiving this error: **"Parse Stream Analytics jobs info failed: The maximum retry count has been exceeded with empty response from the Stream Analytics."**
![image](https://user-images.githubusercontent.com/8053606/66498381-da106b00-eab5-11e9-898b-bbf4a001fb9e.png)

**Comment by shizn** [comment]
@adashen could you help take care of this issue?

**Comment by adashen** [comment]
There is another similar issue tracked by @SLdragon. Will update this when there is any finding.

**Comment by SLdragon** [comment]
We would tracing this issue here: https://github.com/microsoft/vscode-azure-iot-edge/issues/504

**Comment by SLdragon** [comment]
Thanks for all your feedback, and we have already fixed this issue in 1.18.0, you can download the latest extension here: https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-edge
