### ISSUE TITLE
what will be the edge and docker file configuration for iotcore Container OS instead of nanoserver for edge module on IoT Core

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#1831]
Hi Team,

I would like to use iotcore Container OS instead of nanoserver for edge modules on IoT Core gateway. What will be the configuration for iotcore Container OS. I would like to enable PowerShell, WMI, and the Windows servicing stack that is not available on nanoserver. Here is the reference-
[https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images#windows-server-core-vs-nanoserver](url)

Currently using below docker configuration for nanoserver-

```
FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "samplemodule.dll"]
```

Can you please let me know how can i enable iotcore Container OS. what all the changes need to be done?

### Device Information
* Host OS: Windows IoT Core 
* Architecture : amd64 
* Container OS : Windows containers, nanoserver-1809, iotcore:1809

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.8
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.8
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.8
* Docker/Moby [run `docker version`]:  3.0.5

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

Thanks,
Prateek

**Comment by veyalla** [comment]
@seanmcd-msft - can you advice here?

**Comment by darobs** [comment]
ping @seanmcd-msft

**Comment by lt72** [comment]
Closing as it seems there is an external path to resolution. Please re-open if necessary.

**Comment by seanmcd-msft** [comment]
sorry, for some odd reason I didn't see the notifications for this thread until the close showed up.  The immediate answer to the question is to pull mcr.microsoft.com/windows/iotcore:1809 .  however, that said I don't know that this will solve the problem it sounds like you're really trying to solve.  IoT Core has a much larger API surface then nanoserver, but, it's still a OneCore based edition and has similar WMI and Powershell capabilities.  Also you should be aware that none of the windows docker images support the normal windows servicing stack. The docker servicing model is to rebuild the container off a newer image when one gets published.
