### ISSUE TITLE
Created a route in IotHub for DeviceTwinChangeEvents. Telemetry messages are also reaching this endpoint.

### ISSUE THREAD

**Issue by lijithomas88** [Azure/iotedge#1838]
## Expected Behavior
Created a route in iotHub for routing DeviceTwinChangeEvents to builtinEndPoint /events.  Telemetry messages should not reach this endpoint. Only twin changeevents should reach this endpoint.

## Current Behavior
 Telemetry messages are also reaching  this endpoint. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. In Iothub, select Message Routing option. 
2. Add a route for Device Twin Change events. 
3. Select endpoint as Built In endpoint - events. 
4. Using node program as in below documentation to read messages from this endpoint.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin
https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-node
5. Run node ReadDeviceToCloudMessages.js command to read devicetwinchanges.

Telemetry messages are also reaching this endpoint? Is this expected behaviour? How can I get devicetwin or moduletwinchangeEvents alone in this endpoint?

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by myagley** [comment]
You most likely have the "fallback route" turned on. This is on by default and will route all telemetry messages that don't match a route to the default `/events` endpoint. You can disable this by clicking the "Disable fallback route" button on the "Message routing" blade in the Azure portal.

**Comment by lt72** [comment]
@lijithomas88 Hello, did you have a chance to try out @myagley suggestion?

**Comment by lijithomas88** [comment]
Yes. I checked by disabling fallback route.  Thanks for the resolution.  Closing the issue now
