### ISSUE TITLE
Way to start/stop iot edge module with an Azure Function

### ISSUE THREAD

**Issue by futurexpe** [Azure/iotedge#1843]
## Expected Behavior
We have a scenario where we have multiple modules running on the IoT Edge devices, one of those modules needs to be started/stopped on a schedule.

I was looking for a way to write an Azure function that would trigger the start stop of this module, given that it will have connection string to the module.

I looked at the module client methods but does not seem like there is a way to programatically set the "Desired State" property from there.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient?view=azure-dotnet

Please Suggest if there is an existing way to do this, or if there is a better way to run modules on a schedule.

**Comment by MPapst** [comment]
I am pretty sure that the desired state can only be changed through a deployment.
Why not having a module twin property that tells the module not to do anything?

**Comment by darobs** [comment]
@MPapst is correct, the desired state is set through the edge deployment.  This can be set programmatically, through the Service API `AddConfigurationAsync` or `ApplyConfigurationContentOnDeviceAsync`.  but a direct method or twin property may give you better control.

If you think more integral support for scheduled module might be useful, please make the suggestion in [UserVoice](https://feedback.azure.com/forums/907045-azure-iot-edge).

**Comment by futurexpe** [comment]
thanks @darobs Can you provide me an example on how to modify the configuration state of a Module from started to stopped with the ApplyConfigurationContentOnDeviceAsync

**Comment by MPapst** [comment]
@futurexpe, the  ```ApplyConfigurationContentOnDeviceAsync``` methods expects a deviceId and the configuration json as string. You can copy the configuration from the Azure Portal when applying a manual deployment directly on the device and just change the desired state of your module.

This is a bit overkill, as you always need the complete current deployment and send it through the API to your device.

**Comment by futurexpe** [comment]
@mpapas thanks for the pointer. But I would like to avoid that because then the deployment manifest will get out of sync relatively quickly. Ideally I want to get the latest manifest, update it and re-upload it. I was getting the modules from the edgeAgent twin but mapping it to Configuration Content is turning out to be tricky.

**Comment by futurexpe** [comment]
I was planning this:
1) Get twin from edgeAgent
2) Edit the twin to start the module
3) Parse the twin to the ConfigurationContent
4) Set it using ApplyConfigContentOnDeviceAsync

**Comment by futurexpe** [comment]
This issue is resolved, but would still be a nice to have a direct api to do this in the future.

**Comment by lt72** [comment]
@futurexpe thank you for your request we will definitely include that in our planning and prioritize  accordingly. Closing the issue for now, please feel free to re-open if you have any further question.

**Comment by keshava-hm** [comment]
Is there a way to stop and start an iot edge module from powershell?

Thanks
