### ISSUE TITLE
In Visual studio 2017,Unable to build IoT edge module when i referencing .net core based class library in iotedge project.

### ISSUE THREAD

**Issue by iotrock** [Azure/iotedge#1846]
## Expected Behavior
Should be able to build iotedge module when referencing class library project, in visual studio 2017

## Current Behavior
In Visual studio 2017,Unable to build IoT edge module when i referencing .net core based class library in iotedge project, got error message which is given below
 Skipping project "/IotEdgeClassLibrary/IotEdgeClassLibrary.csproj" because it was not found.
 Skipping project "/IotEdgeClassLibrary/IotEdgeClassLibrary.csproj" because it was not found.
Restore completed in 859.82 ms for /app/IotEdgeModule.csproj.
/usr/share/dotnet/sdk/2.1.802/Microsoft.Common.CurrentVersion.targets(1875,5): warning : The referenced project '../IotEdgeClassLibrary/IotEdgeClassLibrary.csproj' does not exist. [/app/IotEdgeModule.csproj]
Program.cs(13,11): error CS0246: The type or namespace name 'IotEdgeClassLibrary' could not be found (are you missing a using directive or an assembly reference?) [/app/IotEdgeModule.csproj]
The command '/bin/sh -c dotnet publish -c Debug -o out' returned a non-zero code: 1
[ERROR]: Build docker image failed:The command '/bin/sh -c dotnet publish -c Debug -o out' returned a non-zero code: 1

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Created iotedge project in visual studio 2017 using .net core 2.1.
2. Created class library in same solution using .net core 2.1
3. Added reference of class library in iotedge project.
4. Right clicked on the iotedge project, selected the option Build Iotedge Modules. and got error message on output window of visual studio 2017.

## Context (Environment)
IDE : Visual studio 2017
OS : Azure virtual machine(Windwos 10 version 1809)
Docker/Moby [run `docker version`]: 2.1.0.3
###  `Snapshot of project structure, error message, dockerfile`
![Dockerfile](https://user-images.githubusercontent.com/49762230/66706864-2f6aa780-ed56-11e9-93d6-dd0fc2446c04.PNG)
![Error1](https://user-images.githubusercontent.com/49762230/66706865-30033e00-ed56-11e9-80f1-59ea3360278f.PNG)
![Error1Ex](https://user-images.githubusercontent.com/49762230/66706866-30033e00-ed56-11e9-8a7b-aa3cfc01224c.PNG)
![Solution](https://user-images.githubusercontent.com/49762230/66706867-30033e00-ed56-11e9-9971-dedb342b0d56.PNG)

<details>
<summary>Error message</summary>

```

DOCKER_HOST: 
DOCKER_TLS_VERIFY: 
DOCKER_CERT_PATH: 
Additional Env Variables: 
------ Build IoT Edge Modules started: Platform: Linux Amd64, Configuration: Debug ------
The deployment manifest is generated at C:\Project\AzureIotEdge\AzureIotEdgeApp\config\deployment.amd64.debug.json
docker build --rm -f "C:\Project\AzureIotEdge\IotEdgeModule\Dockerfile.amd64.debug" -t previewacr.azurecr.io/iotedgemodule:0.0.1-amd64.debug  "C:\Project\AzureIotEdge\IotEdgeModule"
Sending build context to Docker daemon  668.2kB
Step 1/15 : FROM microsoft/dotnet:2.1-runtime-stretch-slim AS base
 ---> 43005d15cfda
Step 2/15 : RUN apt-get update &&     apt-get install -y --no-install-recommends unzip procps &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> aee8bbf234b6
Step 3/15 : RUN useradd -ms /bin/bash moduleuser
 ---> Using cache
 ---> 5ee8caa96715
Step 4/15 : USER moduleuser
 ---> Using cache
 ---> 3062483c6592
Step 5/15 : RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg
 ---> Using cache
 ---> a1e434090582
Step 6/15 : FROM microsoft/dotnet:2.1-sdk AS build-env
 ---> bf77a711b92c
Step 7/15 : WORKDIR /app
 ---> Using cache
 ---> c70a58309537
Step 8/15 : COPY *.csproj ./
 ---> Using cache
 ---> dcf50d920034
Step 9/15 : RUN dotnet restore
 ---> Using cache
 ---> 4117095b00bd
Step 10/15 : COPY . ./
 ---> Using cache
 ---> 392a1fe535f6
Step 11/15 : RUN dotnet publish -c Debug -o out
 ---> Running in d3384e97e8df
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Skipping project "/IotEdgeClassLibrary/IotEdgeClassLibrary.csproj" because it was not found.
  Skipping project "/IotEdgeClassLibrary/IotEdgeClassLibrary.csproj" because it was not found.
  Restore completed in 859.82 ms for /app/IotEdgeModule.csproj.
/usr/share/dotnet/sdk/2.1.802/Microsoft.Common.CurrentVersion.targets(1875,5): warning : The referenced project '../IotEdgeClassLibrary/IotEdgeClassLibrary.csproj' does not exist. [/app/IotEdgeModule.csproj]
Program.cs(13,11): error CS0246: The type or namespace name 'IotEdgeClassLibrary' could not be found (are you missing a using directive or an assembly reference?) [/app/IotEdgeModule.csproj]
The command '/bin/sh -c dotnet publish -c Debug -o out' returned a non-zero code: 1
[ERROR]: Build docker image failed:The command '/bin/sh -c dotnet publish -c Debug -o out' returned a non-zero code: 1
```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by darobs** [comment]
@shizn @adashen Have you seen somethign like this before?

**Comment by SLdragon** [comment]
Hi, @iotrock , if you reference a library project in the solution folder, you should change the build context path in module.json file to make sure docker can copy and find the libary.

For example, you can change the context path to "../" which reference the solution folder:

![image](https://user-images.githubusercontent.com/5545529/66786380-b2d0f800-ef12-11e9-8049-e9f81735a37d.png)

And then change the Dockerfile to copy the library to the container.

Here is a related issue which discussed this which you can refer: https://github.com/microsoft/vs-azure-iot-edge-docs/issues/10

**Comment by iotrock** [comment]
Hi, @SLdragon,@shizn,@adashen
Changed contextPath in module.json of the project, here is snapshot for reference
![error](https://user-images.githubusercontent.com/49762230/67148655-752bf080-f2bf-11e9-8924-7f46734dd39f.JPG)
After that build the module using Build IoTEdge module, again got error message
**[ERROR]: Build docker image failed:COPY failed: no source files were specified**
and screenshot of error is given below
![error1](https://user-images.githubusercontent.com/49762230/67148699-fedbbe00-f2bf-11e9-862f-dfeffbc35339.JPG)
Dockerfile screenshot is given below for your reference,
![error2](https://user-images.githubusercontent.com/49762230/67148747-8aede580-f2c0-11e9-87e7-7474d3d95b79.JPG)
**As per my project structure, Please let me know that where and what change should i do in dockerfile to build my iotedge module?**

**Comment by iotrock** [comment]
Hi @darobs,@SLdragon,@shizn,@adashen Any update on this issue ???

**Comment by SLdragon** [comment]
Hi, @iotrock, you should also change your Dockerfile. 
When you changed your contextPath to "../", then the docker build context folder is the solution root folder, so you should also change the path reference in your Dockerfile

For example, you need to change COPY command as below:

```
"COPY *.csproj ./" 
 
```
to
```
"COPY IoTEdgeModule/*.csproj ./"
```

You can also check other parts and change the path accordingly.

**Comment by iotrock** [comment]
Hi @SLdragon, Updated "COPY "IoTEdgeModule/*.csproj ./" in Dockerfile, attached snapshot for reference purpose
![Error](https://user-images.githubusercontent.com/49762230/67260525-690b8300-f4b9-11e9-8076-88a58dba03e5.JPG)

**After updating dockerfile, I have built the iotedge module using build IoT edge module and  got error message which is given below**
![error1](https://user-images.githubusercontent.com/49762230/67260643-06ff4d80-f4ba-11e9-94a5-369b454dbf8b.JPG)

**According to my project structure, Please let me know that what all changes should i do in dockerfile to build iotedge module**

**Comment by SLdragon** [comment]
This error is because your dotnet publish command cannot find the project file in the root folder. To help you better understanding how to change the Dockfile, here is a sample docker file you can refer:

```
FROM microsoft/dotnet:2.1-runtime-stretch-slim AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip procps && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash moduleuser
USER moduleuser
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l ~/vsdbg

FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY ./IotEdgeModule1/*.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish "IotEdgeModule1/IotEdgeModule1.csproj" -c Debug -o out 

FROM base
WORKDIR /app
COPY --from=build-env /app/IotEdgeModule1/out ./

ENTRYPOINT ["dotnet", "IotEdgeModule1.dll"]

```

I aslo created a sample project, you can find it here:
[SampleEdgeProjectWithCSharpLibary.zip](https://github.com/Azure/iotedge/files/3759820/SampleEdgeProjectWithCSharpLibary.zip)

**Comment by damonbarry** [comment]
It looks like a solution has been provided and there's been no further activity...closing.

**Comment by SLdragon** [comment]
You can also refer troubleshoot page:

https://github.com/Microsoft/vs-azure-iot-edge-docs/wiki/Troubleshoot#4-docker-build-fails---when-reference-libraryshared-code-in-projectsolution
