### ISSUE TITLE
iotedged failed to start: HSM API failure occurred: 216

### ISSUE THREAD

**Issue by NonStatic2014** [Azure/iotedge#185]
## Expected Behavior

iotedged starts automatically after boot the Raspberry Pi

## Current Behavior

Could not have iotedged start on my Raspberry Pi

## Steps to Reproduce

1. Install environment according to https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm
2. Reboot Raspberry Pi

### Device (Host) Operating System

Raspberry Pi 3, Raspbian Stretch

### Architecture

ARM32

### Container Operating System

Raspbian Stretch

#### iotedged

iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent

N/A

#### Edge Hub

N/A

#### Docker

```bash
pi@raspberrypi:~ $ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:19:46 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:15:34 2018
  OS/Arch:          linux/arm
  Experimental:     false
```

## Logs

```bash
pi@raspberrypi:~ $ sudo /usr/bin/iotedged -c /etc/iotedge/config.yaml
<6>2018-08-20T20:46:00Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2018-08-20T20:46:00Z [INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
<6>2018-08-20T20:46:00Z [INFO] - Using config file: /etc/iotedge/config.yaml
<6>2018-08-20T20:46:00Z [INFO] - Using runtime network id azure-iot-edge
<6>2018-08-20T20:46:00Z [INFO] - Initializing the module runtime...
<6>2018-08-20T20:46:00Z [INFO] - Finished initializing the module runtime.
<6>2018-08-20T20:46:00Z [INFO] - Configuring /var/lib/iotedge as the home directory.
<6>2018-08-20T20:46:00Z [INFO] - Configuring certificates...
<6>2018-08-20T20:46:00Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2018-08-20T20:46:00Z [INFO] - Finished configuring certificates.
<6>2018-08-20T20:46:00Z [INFO] - Initializing hsm...
<6>2018-08-20T20:46:00Z [INFO] - Finished initializing hsm.
<6>2018-08-20T20:46:00Z [INFO] - Detecting if configuration file has changed...
<6>2018-08-20T20:46:00Z [INFO] - No change to configuration file detected.
<6>2018-08-20T20:46:00Z [INFO] - Provisioning edge device...
<3>2018-08-20T20:46:00Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/hsm_client_tpm_in_mem.c:ek_srk_unsupported:215) API unsupported
<3>2018-08-20T20:46:00Z [ERR!] - A hardware hsm error occurred.
<3>2018-08-20T20:46:00Z [ERR!] - 	caused by: HSM API failure occurred: 216
```

**Comment by mrohera** [comment]
It appears that you were trying to provision your Pi using DPS. If you need to use DPS, you are required to have a TPM on your device. Did you intend to use DPS or did you want to manually configure the Edge?

Specifically take a look at your config.yaml under section "Provisioning mode and settings". More about this is listed here: [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm#configure-the-azure-iot-edge-security-daemon](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm#configure-the-azure-iot-edge-security-daemon)

**Comment by NonStatic2014** [comment]
I see. I misunderstand the "auto" provision. After I comment out the auto provisioning setting, it works now. Thank you mrohera!
