### ISSUE TITLE
Clarification on using the log-pull feature for collecting modules logs from edge device.

### ISSUE THREAD

**Issue by harika-thallam** [Azure/iotedge#1852]
Hi team ,

I am following the documentation (https://github.com/Azure/iotedge/blob/master/doc/built-in-logs-pull.md) for configuring module log collection. When I try to do call the UploadLogs method as a direct method though I get a success response of 200 when I use the correlation id to call GetTaskStatus I get the following exception :
{"status":500,"payload":{"message":"Self referencing loop detected for property 'Exception' with type 'Microsoft.WindowsAzure.Storage.StorageException'. Path 'Exception.RequestInformation'."}}

It seems to be an error with sasURI provided in JSON payload for blob storage access (I noticed this from container monitor graphs as the request breakdown as the number of authorization and authentication errors have increased)

I have followed this documentation (https://blogs.msdn.microsoft.com/jpsanders/2017/10/12/easily-create-a-sas-to-download-a-file-from-azure-storage-using-azure-storage-explorer/) for obtaining sasURI and have updated the permissions to provide read,write and all other permissions out there.

I am currently stuck and any help would be appreciated.

I have checked the edgeagent image version and environment variables set and it is in accordance with the things specified on documentation.

**Comment by darobs** [comment]
Hello @harika-thallam, 

I will set this up to try it out, but can you get the edgeAgent logs and see if there is a log that corresponds to this event? 

Thanks,

**Comment by harika-thallam** [comment]
@darobs , after I changed the sasURL for the container , this issue is not occurring. I wasn't aware of this detail as it was not mentioned in documentation either.
Thanks

**Comment by darobs** [comment]
@veyalla Is there a clarification we can make to the document linked above?
