### ISSUE TITLE
Way to Bind IoT Edge Traffic to Specific Network Interface

### ISSUE THREAD

**Issue by AzTrainIoT** [Azure/iotedge#1856]
Is there any configuration setting to bind all IoT Edge traffic (daemon and docker) to a specific network interface when running on a linux based device with multiple network interfaces installed?

**Comment by darobs** [comment]
Hello @AzTrainIoT, 

The IoT Edge Security daemon (iotedged) and dockerd by default uses a Unix Domain Socket, are you referring to the ports exposed from EdgeHub and potentially other modules?

You can bind the exposed ports to a specific IP on the host, this is assignable in the [CreateOptions](https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate) HostConfig.PortBindings.  However, this requires knowing what the IP address is for the Edge device when creating the edge deployment, and probably wouldn't work for an at-scale deployment.

You may be able to manage this from the container runtime on the device.  You can set the default IP to bind on by the `ip` argument in docker settings.  You may also want to look at [Docker's Macvlan](https://docs.docker.com/v17.09/engine/userguide/networking/get-started-macvlan/).

**Comment by AzTrainIoT** [comment]
Hi darobs,

I need to direct all network traffic from the IoT edge solution including the module containers and IoT edge daemon to a specific network interface on the device that has public internet access. 

I know I can  configure the module containers through docker settings but I am unclear on how/if I can configure the daemon, according to the network diagram on the following URL it looks like it performs network communication outside the docker environment?

https://github.com/Azure/iotedge/blob/master/doc/networking.md

Would it be a better practice to configure a local proxy server for this scenario?

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support


Thanks for the quick reply!

**Comment by darobs** [comment]
HI @AzTrainIoT, thank you for your patience.  I have only found the ability to bind to specific IPs in Docker settings.

The IP binding in the `/etc/docker/daemon.json` would look like this:
```json
{
  "ip" : "<ip address>" 
}
```

I think a proxy may be a good alternate way to direct traffic.

**Comment by lt72** [comment]
@AzTrainIoT: closing issue for now, please feel free to re-open as you need to.
