### ISSUE TITLE
HostConfig Mounts: Settings not Updating

### ISSUE THREAD

**Issue by josiahlaivins** [Azure/iotedge#1872]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3731a8-f0df-f1a1-d1a1-e89a769a0908
* Version Independent ID: 50a5190e-eafa-7dde-c18f-be9505b00a0a
* Content: [Declare modules and routes with deployment manifests - Azure IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/module-composition)
* Content Source: [articles/iot-edge/module-composition.md](https://github.com/Microsoft/azure-docs/blob/master/articles/iot-edge/module-composition.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**
## Expected Behavior
In the deployment template, lets say I specify a remote mount to a volume in HostConfig. The volume / mount is successful. I should expect:
- The files to be populated in that container and immediately available for use.
- If I change the remote settings in the deployment manefest and deploy, that volume should update

## Current Behavior
**Issue One**
When setting a remote volume, the files in the container are not immediately accessible. I have to _manually_ force a restart for the files to be accessible by the container. This is going to be crazy to do on 100+ devices...

**Issue Two**
As pointed out in https://stackoverflow.com/a/56414070/4577212, if a volume is host mounted (HostConfig) and associated with a container, the settings become set / unchanging.

After deploying with new settings, the current solution to this is to delete the container, delete the volume, then allow for everything to rebuild. **Does IoT edge do anything to streamline this?**

If I deploy the example below to the device, nothing will happen. I will see the updated deployment manifest in the Azure Portal as reported by the device, but those actual volume settings are not changed. This is going to be a major problem if we have 100 devices and need to manually do this. How does IoT edge handle this?

**TL:DR On initial volume mount, shouldn't have to restart the container manually for the volume to populate in the contianer. If the remote settings change (user / password / ip) changes, the volume should update with those changes on new deployment.**

## Steps to Reproduce
For example:
```json
"createOptions": {
 "HostConfig": {
   "Mounts": [
     {
       "Target": "/alt_data",
       "Source": "samba-data-connection",
       "Type": "volume",
       "ReadOnly": false,
       "VolumeOptions": {
             "DriverConfig": {
             "Name": "local",
             "Options": {
               "type": "cifs",
               "device": "device connection info",
               "o": "usernames and passwords"
           }
         }
       }
     }
   ]
 }
}
```
I might want to change the volume username, password, and ip address to:
```json
  "Options": {
     "type": "cifs",
     "device": "NEW device connection info",
     "o": "NEW usernames and passwords"
 }
```

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
After redeploying the template, these settings will not show on volume inspect, but will be reflected / reported by the device. Deleting the volume manually will cause the new settings to be used.

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

```
</details>

### Device Information
* Host OS [Ubuntu 16.04]: 
* Architecture [amd64]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [iotedge 1.0.8]: 
* Edge Agent [image tag (1.0.0)]: 
* Edge Hub [image tag (1.0.0)]: 
* Docker/Moby [ Version: 3.0.6 API version: 1.40]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

**Comment by darobs** [comment]
Hello @josiahlaivins 

Thanks for reporting this.  

Is this a problem for Windows with Windows containers? Linux containers on Windows is[ not recommended for production](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-linux).

**Comment by josiahlaivins** [comment]
Thanks for the response @darobs 

From all that I have seen, the only away around this is manually executing docker commands to do the reset. _**This will be a massive problem soon once we have a large number of devices.**_ 

Perhaps having root script execution on Module deployment could fix this / provide more flexibility. I do not think docker-compose has anything quite like this, so if IoTEdge provides a solution this is an opportunity to improve passed what is available via compose.

**Comment by philipktlin** [comment]
Thanks to share your scenario with us.

Issue1: this is moby's behavior.  It is better to find support from Moby repo.
Issue2: since docker volume will not be removed even container is removed.  Even IoT Edge detects changes in deployment and try to re-create the container with the new parameters; existing volume doesn't take the new parameter.

To resolve these issues with workaround, I would suggest you to create a custom module to manage the docker volume.

**Comment by philipktlin** [comment]
Close this as this is existing Moby behavior.  noted this scenario, will think about it in the future.
