### ISSUE TITLE
Persistent per device parameters

### ISSUE THREAD

**Issue by abouroubi** [Azure/iotedge#1885]
## Expected Behavior
I want to have per device parameters that don't get overriden when I deploy a new version of my modules.

## Current Behavior
I'm using Environnement vars to configure my module, each device have different configuration, I'm also using IoT device configuration for common parameters like Module version to use, but even if I don't have Env vars, when I deploy a new version, my per device env vars get removed.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Set Env vars in a module deployement for a particular device
2. Create an IoT device configuration that targets the device
3. Apply the configuration
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]:  Raspbian Stretch
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.8
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.0
* Docker/Moby [run `docker version`]: 
Client:
 Version:           3.0.6
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        a63faebc
 Built:             Wed Jun 19 23:09:02 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       b07f53d
  Built:            Thu Jun 20 03:28:26 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by veyalla** [comment]
Would it work if device specific variations are expressed as module desired properties instead of environment variables?

**Comment by abouroubi** [comment]
Haven't tried, this module is a migration from an app that was run on host os and used environment vars, we just containerized it and wanted to use it as is.

**Comment by veyalla** [comment]
@abouroubi - Got it. This is currently not possible. We're introducing deployment improvements in the future which will provide a way to accomplish this.

To understand your scenario at bit more - across how many devices are you looking to do this? Will each device need specialized environment variables on top of a base deployment?

**Comment by abouroubi** [comment]
@veyalla, for now il using it on hundred devices, but the goal is to deploy thousands of them. 
Yes each device will have specialized parameters (like name, position,...) and common parameters (module version, refresh rate,...)

**Comment by dmolokanov** [comment]
I'm closing this issue for now. Stay tuned for the upcoming realeases. Thanks for reaching us!

**Comment by infused-kim** [comment]
This issue was created in 2019 and it was indicated that future deployment improvement would solve this problem. 

Has this been released yet? I haven’t been able to find a good solution so far. 

Layered deployments could perhaps be used to overwrite module environment variables, but you can only have 100 deployments per hub.
