### ISSUE TITLE
Download site for Windows 10 17763

### ISSUE THREAD

**Issue by pkoronawa** [Azure/iotedge#1897]
I get the following error installing IoT Edge runtime on a HyperV VM

The container host is on unsupported build version 18362.
Please use a container host running one of the following build versions for running Windows containers:
17763

Where can I download this specific version of windows?

**Comment by dmolokanov** [comment]
Hello @pkoronawa,
Please find a list of supported host systems on docs website https://docs.microsoft.com/en-us/azure/iot-edge/support

**Comment by pkoronawa** [comment]
Thanks dmolokanov, I've gone to that site and tried building images from there. I've found that the images are newer than what is supported by IoT Edge (18362)

**Comment by veyalla** [comment]
@pkoronawa There are couple of options:

- Use an Azure VM, per the `az vm create...` command in the [Windows quickstart](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#prerequisites)
- For a local VM, you can use Windows Server 2019 image from the [eval center](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019?filetype=ISO)

**Comment by lt72** [comment]
@pkoronawa closing this issue as it seems positively resolved. Please feel to re-open if you need to.
