### ISSUE TITLE
Module to Module Throttle

### ISSUE THREAD

**Issue by josiahlaivins** [Azure/iotedge#1901]
Does the MQTT message size and speed throttling effect module communication if they are on the same device? Is there a way to speed up **module to module same device messaging** via increasing the local message size?

Because we are trying to have 2 modules send each other data (Images / meta data) via messages and a round trip excluding processing is around 15-20ms per image on the same device. We would like to get round trip down to 1ms.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
After redeploying the template, these settings will not show on volume inspect, but will be reflected / reported by the device. Deleting the volume manually will cause the new settings to be used.

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

```
</details>

### Device Information
* Host OS [Ubuntu 16.04]: 
* Architecture [amd64]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [iotedge 1.0.8]: 
* Edge Agent [image tag (1.0.0)]: 
* Edge Hub [image tag (1.0.0)]: 
* Docker/Moby [ Version: 3.0.6 API version: 1.40]:

**Comment by dmolokanov** [comment]
Hello @josiahlaivins,
Could you please provide more information about the environment you are testing on? Versions of iotedged, edgeagent and edgehub and module sdk? What kind of device? x86 or arm?

In the latest release `1.0.8.3` we did some work to improve communication performance and reliability. You can try to test with this version.

**Comment by josiahlaivins** [comment]
Thanks for the response, I added my system information.

**Comment by dmolokanov** [comment]
I believe we don't make any specific actions to throttle messages in EdgeHub. If 15-20 ms is to slow for your case you could probably make some kind of batching on your module level. By batching I mean combine several messages as a one bigger message and then send this one message to other module. I hope it will help.

**Comment by dmolokanov** [comment]
Another thing worth trying to disable persistent storage for EdgeHub. 
Normally, EdgeHub puts a message in a local database that backed with the filesystem. Messages persist there until they sent to the IoT Hub. This is how EdgeHub prevents data loss.
If you put the environment variable for EdgeHub `UsePersistentStorage=false` it will use an in-memory store that should work faster but will lose messages when it crashes.

**Comment by josiahlaivins** [comment]
Thanks for the information. We compared round trip timing between 2 configurations:

Configuration below does round trip 20ms per item consitently. 
```json
"settings": {
"image": "mcr.microsoft.com/azureiotedge-hub:1.0.8.3",
"createOptions": ""
},
"env": {
"OptimizeForPerformance": {"value": "true"},
"UsePersistentStorage": {"value":  "false"}
}
```
Configuration below does round trip 22 - 35 ms per item and gets worse over time it seems. It does seem that using the newer version of iotedge hub and options makes a difference. 
```json
"settings": {
"image": "mcr.microsoft.com/azureiotedge-hub:1.0",
"createOptions": ""
},
"env": {
"OptimizeForPerformance": {"value": "false"},
"UsePersistentStorage": {"value":  "true"}
}
```
It seems that sending messages takes on average 17-20ms regardless of message size between 2 modules:
```python
start = time.time()
await device_client.send_message_to_output(message, 'output2')  # 17-20ms
logger.debug('Module1 -> Module2 time delta: %s ms', s_to_ms(time.time() - start))
```
Interestingly, receiving a message is far faster (~0.001 ms). Do you think this could be a routing issue?

**Comment by dmolokanov** [comment]
@ancaantochi Do you have any additional thoughts on this?

**Comment by vipeller** [comment]
@josiahlaivins I am not quite sure that you measure the right thing or perhaps I don't understand you goal. 

My understanding is that your time concerns includes the following steps:
- Module A sends out a message
- Edge routes it to Module B
- Module B receives the message

You would like to measure from the time Module A sends a message till the point Module B receives the message

Your code snippet only measures the following:
- Module A sends out a message
- EdgeHub receives a message and confirms it back to Module A (but hasn't routed/forwarded it to Module B yet)

Although I don't see the code you used to measure receive time, I assume that it is fast because it just returns back an already processed and enqueued message, basically grabs a reference from a queue and returns it.

I would suggest to check the performance to send through the system time with the message and check on the other side.

Achieving 1ms from sending a message from a module to receiving it at another module, doesn't seem feasible to me with the current implementation, considering all the steps involved in message processing.

**Comment by josiahlaivins** [comment]
@vipeller Thanks for the info. We have tested full round trip, timing, and example of sending a message above. It seems that 1ms might not be possible with high volume single messages. 

We will be looking into way to batch our data. One drawback is that MQTT has a small message size. We will experiment with AMQP (seems to allow larger message sizes (?) ). Our main concern is that it does not seem to be as well supported as MQTT from what we have found in the python sdks.

**Comment by josiahlaivins** [comment]
Asking detailed query [here](https://github.com/Azure/azure-iot-sdk-python/issues/375#issue-514010191). Will be looking at local blob storage or zeromq to send messages larger than 256mb. I think the solution is sending larger batch messages to get the timing down to 1ms.

Thanks for you'alls help though, we have a better idea on how to solve this issue / direction.

**Comment by lt72** [comment]
Closing issue, please re-open if needed.
