### ISSUE TITLE
More messages reported by IoT Hub than I am sending

### ISSUE THREAD

**Issue by pkoronawa** [Azure/iotedge#1908]
I've written a module running in the Simulator that sends messages up to the IoT hub. As seen in the screen shot, I've sent several hundred messages but less than a thousand. Yet my message limit of 8000 has been exceeded.

I've built the Quickstart read-d2c-messages app, and it shows only the messages I know I'm sending. How can I find the other messages that the hub is recording?
![Capture](https://user-images.githubusercontent.com/47200230/67530268-6c4a6e80-f673-11e9-97fd-31a05c8f5528.PNG)

**Comment by veyalla** [comment]
what is the message size? IoT Hub meters messages at 0.5k for Free tier.

 _The message size used to calculate the daily quota is 0.5 KB for a free tier hub and 4KB for all other tiers. For more information, see [Azure IoT Hub Pricing](https://azure.microsoft.com/pricing/details/iot-hub/)._

**Comment by pkoronawa** [comment]
Message size is about 12K so that would explain it. Thanks
