### ISSUE TITLE
Security Daemon looses device configuration

### ISSUE THREAD

**Issue by richterr** [Azure/iotedge#1913]
## Expected Behavior
A device that is offline most of the time gets online for a short time and gets the message there are some changes in the device twin properties. The security daemon tries to re-provisions the device via TPM with the DPS and the connection is lost again. Expectation would be to return to the last working configuration while offline.

Going online again resolves the issue.

## Current Behavior
It shows an error and is not able to re-provision. Logs with debug level say something is wrong with the token (unfortunately these logs can't be provided anymore).

### Device Information
* Host OS 
Ubuntu 18.04
* Architecture
amd64
* Container OS:
Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 
1.0.8
* Edge Agent [image tag (e.g. 1.0.0)]:
1.0.8
* Edge Hub [image tag (e.g. 1.0.0)]:
1.0.8

## Logs

![errorlog_iotedge_security_daemon](https://user-images.githubusercontent.com/42353719/67587134-7f347000-f753-11e9-8a8e-297ce9a5e1aa.jpg)

**Comment by kkdawkins** [comment]
Hello! 

First, a couple of notes on what is happening: 

- A twin update does not trigger a reprovision, only a restart will trigger a reprovision. When a reprovision does happen, the security daemon will fall back to a backup file if the provisioning fails. The fact that the error says that the backup could not be found implies they never had a successful DPS provisioning before, or that something deleted the backup file. 

Suggestions: 

- Can you validate the existence of this file: `/var/lib/iotedge/cache/provisioning_backup.json` Also please ensure that the security daemon's users can read this file. 

- Give us more logs that include the initial run + provision + backup file creation. Please send us text logs, not an image :)

**Comment by kkdawkins** [comment]
Closing for lack of activitiy, feel free to reopen if you want us to puruse this further. Thanks!
