### ISSUE TITLE
EdgeHub functions binding does not preserve system level Message properties

### ISSUE THREAD

**Issue by hazelnutmonkey** [Azure/iotedge#1923]
When using Azure functions with IoT Edge, I am unable to persist system level properties on the Message when sending to IoT Hub, specifically ContentEncoding and ContentType. IoT Hub message routing via message body properties is predicated on having ContentType set to "application/json" and ContentEncoding set to "UTF-8".

## Expected Behavior
Message should contain system properties when it reaches IoT Hub (specifically ContentEncoding and ContentType)

## Current Behavior
There are no ContentEncoding or ContentType properties set.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Use EdgeHub binding in an Azure function:
public static async Task FilterMessageAndSendMessage(
                    [TimerTrigger("0 */5 * * * *", UseMonitor = false)]TimerInfo myTimer, //every 5 minutes
                    **[EdgeHub(OutputName = "output1")] IAsyncCollector<Message> output,**
                    ILogger logger)

2. Create a Message:
var pipeMessage = new Microsoft.Azure.Devices.Client.Message(heartbeatMessageBytes);
3. Set message body type and content encoding 
pipeMessage.ContentEncoding = "UTF-8";
pipeMessage.ContentType = "application/json";
4. Send Message:
await output.AddAsync(pipeMessage);

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Windows 10
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Windows containers

### Runtime Versions
* iotedged [run `iotedge version`]: iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)
* Edge Agent [image tag (e.g. 1.0.0)]:  mcr.microsoft.com/azureiotedge-agent:1.0
* Edge Hub [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-hub:1.0
* Docker/Moby [run `docker version`]: 
Client:
 Version:           3.0.5
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        ba9934d4
 Built:             Thu Apr 18 22:01:41 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          windows/amd64
  Experimental:     false

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Additional Information
I believe this issue has to do with how the message is copied in the Utils.GetMessageCopy function (https://github.com/Azure/iotedge/blob/master/edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Utils.cs).

In that function, only user properties are persisted, but other properties are not copied over to the new object.

**Comment by vipeller** [comment]
@hazelnutmonkey thank you for figuring this out and reporting. It will be fixed as a bug.

**Comment by lt72** [comment]
@vipeller has this been fixed already?

**Comment by vipeller** [comment]
@lt72 There is a pending pull request in the C# SDK (which is needed for a decent fix) and a temporary fix which I haven't written tests for - pulled away for other issues. So the answer is no, but it is on it's way.

**Comment by lt72** [comment]
This should now be fixed. Please re-open as necessary.
