### ISSUE TITLE
IOT Edge device reporting 406 status

### ISSUE THREAD

**Issue by LTTSAvertle** [Azure/iotedge#1927]
I am using Azure IOT Edge devices to send data to cloud. I configured 8 devices in same network and was able to receive data from all 8 devices for few days but now 5 devices reporting status as "406 -- The device is offline or not sending status reports". FYI, I am using MQTT protocol to send the telemetry data. Why the status changed and communication stopped suddenly?

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
