### ISSUE TITLE
Clarification Edge offline

### ISSUE THREAD

**Issue by smoms** [Azure/iotedge#1928]
Hi,
assuming I have use case where I can ignore leaf devices because I use Edge to run SW modules only. What happen to module to module communication through Edge Hub when Edge is offline? Are modules still be able to communicate between each other (credentials are cached)? And for how long? Am I correct that in such context I can ignore the patterns of "Edge as Gateway"?

thanks

**Comment by vipeller** [comment]
@smoms that is not a problem that EdgeHub is offline in your scenario. EdgeHub knows how to authenticate modules (it synchs the information with iot hub when it is online and caches it). Once edge hub was able to connect at least once to iot hub, then it should work for "forever". When edge hub is online, it periodically synchs this information with IoT Hub. 

Also, module to module communication works when edge hub is offline (that was one of the design goals).

I am not quite sure what you mean to ignore Edge as Gateway patterns? 

Let me know if you have further questions, I am happy to answer them.

**Comment by smoms** [comment]
@vipeller many thanks.
To my last question: when Edge is used as Gateway I understood that for the Identity Translation pattern the credential are cached for 2h only. Can you confirm please?

**Comment by vipeller** [comment]
@smoms in case of identity translation, the base problem is that devices don't understand the protocols Iot Hub (IoT Edge) provides. In this case the solution is that the customer writes a module that can talk to these devices. Then this module uses a separate identity for each individual device connecting to Edge. This is a difference to protocol translation pattern, where edge uses the same identity for all devices.

In both cases (protocol/identity translation) the customer writes these modules and it is up to them how to handle the credentials (e.g store it in an encrypted file, or they just hard code it in the code)

When a device connects, the customer module picks the appropriate identity/credentials according to its internal implementation/logic. Then it authenticates itself to Edge Hub. Edge hub might have these credentials cached to support offline scenarios. This cache is refreshed periodically while the device is online, but if the device is offline, then the items in the cache doesn't expiry. This means that using the identity translation pattern, the offline scenario works for more than 2 hours (given that the edge device connected at least once, and had a chance to download all necessary information for all devices to be connected)

Is there 2 hours somewhere in the documentation?

**Comment by smoms** [comment]
@vipeller many thanks for the clear explanation. There is no 2 hours in the doc. But it is mentioned that there is a SAS Token cached at the Edge (I will find the reference here) to authenticate to IoT Hub and such token can expire. But ok, this is only requested if a module/device needs to connect to IoT Hub, right?

**Comment by vipeller** [comment]
@smoms in transparent gateway scenario (when the device would be able to connect directly to IoT Hub, but for some reason an intermediate Edge device is used), the device can authenticate itself to Edge using sas tokens. These tokens expire (the token itself specifies its expiry time). If you use the client SDK, it takes care of generating these tokens, which tokens work for one hour. Before that hour passes, the device needs to be re-authenticated.
Edge is able to pull the data from Iot Hub to authenticate the device (e.g to check that the token is valid) . This data is cached and never expire (but get refreshed when online).
In an offline scenario, when the device works more than an hour, what happens is that at first connection, the client device creates a token, if it uses the client SDK, this token will for an hour. Edge checks that the token is correct (it has the necessary information cached to do the check, so no connection to IoT Hub is needed). Then it stores the token and assigns it to the device, so yes, edge caches the tokens.
Then edge periodically checks its cache that the tokens are still valid (haven't expired). If so, it disconnects the device. To avoid that, the device needs to reauthenticate itself with a new token. As I wrote earlier, the SDK takes care of this, so this all is invisible for the programmer.

**Comment by smoms** [comment]
@vipeller thanks. So assuming 1. Edge is offline AND 2. An hour is passed then the device gets disconnected. Right?

**Comment by vipeller** [comment]
@smoms sorry, then I was not clear. It doesn't matter that edge is online or offline. It is able to authenticate devices offline and should behave the same way regardless if it is offline or online (the only difference is that when it is not able to authenticate a device using its cached data, then it reaches out to Iot Hub, if it is online)

So the device gets disconnected regardless if edge is online or offline, when the device doesn't present a new token, and the old one expires.

if you use the client SDK, it would never happen, as the SDK takes care of that.

without a valid token, edge will not accept messages from the device.

**Comment by smoms** [comment]
@vipeller clear. My point above was a scenario when Edge is offline and device has: 1. valid token or 2. invalid token. In case 1. Edge is buffering messaging, in case 2. it is not. Right?

**Comment by vipeller** [comment]
@smoms that is correct.

**Comment by smoms** [comment]
@vipeller thanks lot.

**Comment by lt72** [comment]
Closing this issue as it seems resolved. Please re-open as needed.
