### ISSUE TITLE
Cannot connect to iothub through 4G/LTE network when the ethernet port connected in local network.

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/iotedge#1945]
Hi,

I think it might be an OS related problem (Windows10). 
But I couldn't find other ways to solve it.

## Expected Behavior
We have some 4G/LTE IoTEdge based gateways 
(iotedge modbus module with Windows10 Ent2019 LTSC).
The gateways should get data from modbus tcp in local nerwork and send data through
4G/LTE network to Iothub in Azure.

## Current Behavior
When the ethernet port connected in local network, the OS keeps trying send all data by the ethernet instead of 4G/LTE.

All applications in the system cannot connect to the Internet through 4G/LTE when the ethernet port connected in local network.

I think there might be some configurations I should modify to solve this. But I couldn't find a way to do it.
Please help me if anyone knows what should I do.

**Comment by myagley** [comment]
What does the output of `iotedge check` show?

Do things work when the ethernet port is not connected to the local network?

**Comment by Dolphinsimon** [comment]
> What does the output of `iotedge check` show?
> 
> Do things work when the ethernet port is not connected to the local network?

Everything works fine when the port is not connected.
I haven't check the iotedge check output. I will try this later.

**Comment by myagley** [comment]
I'm not directly familiar with your device setup, but I would start by looking at the device's network routes to see if there is a route from the container's subnet to the 4G/LTE network interface.

To determine the container's subnet, you can run the following command and look under `IPAM.Config` for the subnet.

`docker -H npipe:////./pipe/iotedge_moby_engine version network inspect nat`

**Comment by Dolphinsimon** [comment]
> I'm not directly familiar with your device setup, but I would start by looking at the device's network routes to see if there is a route from the container's subnet to the 4G/LTE network interface.
> 
> To determine the container's subnet, you can run the following command and look under `IPAM.Config` for the subnet.
> 
> `docker -H npipe:////./pipe/iotedge_moby_engine version network inspect nat`

Thanks for your advice.
I might have found a solution here:https://docs.microsoft.com/en-us/windows-hardware/drivers/mobilebroadband/understanding-and-configuring-windows-connection-manager#windows-10-version-1809-build-17763404-and-later
I've set the policy to 0. The gateways works as expected: Collectiong data from local network and sending them to cloud through LTE network.
I will keep testing this solution for some time to make sure all things working properly.

**Comment by Dolphinsimon** [comment]
Update: We have tested the  Windows Group Policy options above. When the option set to 0,  ethernet adapters and LTE  adapters works together.  For the passed few days, our  gateways have kept a stable state collectiong and sending data.
Thanks for everyone.
