### ISSUE TITLE
EdgeHub offline message logs are not being cleaned up 

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#1948]
Hi Team
    We are facing the below issue...
Steps 
1. Gateway is offline and not connected to Internet
2. EdgeHub stored messages on local as we have set max TTL
3. EdgeHub creates offline message log file on the local container image 
4. Once gateway is online then EdgeHub is sending messages to IoT Hub but the local message log file is remained on local
5. Because of this issue we are facing Hard disk space challenge 

So please suggest the best way for this ....

**Comment by myagley** [comment]
Can you please add the version number for the Edge Hub and runtime, as well as any appropriate Edge Hub logs that exhibit the issue? Thanks!

**Comment by myagley** [comment]
There is an issue with versions `1.0.8.0` to `1.0.8.2` regarding growth of the on disk storage. This was fixed in `1.0.8.3`. If you are not on `1.0.8.3`, I would upgrade and retest.

**Comment by sachidanand** [comment]
Hi We are using this version as of now iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0) 
So do we need to upgrade to 1.0.8.3 version now on production ??? 
Also is this latest version in the preview or it has been released as for general use

**Comment by myagley** [comment]
`1.0.8.3` is generally available and is _not_ a preview release. It's recommended to upgrade to it, if you can, because it has some important stability improvements.

You can read the changelog here: https://github.com/Azure/iotedge/blob/release/1.0.8/CHANGELOG.md

**Comment by sachidanand** [comment]
When we will be getting iotedge 1.0.9 as GA ??

**Comment by myagley** [comment]
We don't have a firm date for 1.0.9. We are anticipating another release candidate before it goes GA. which means it will not GA any earlier than the beginning of January.
