### ISSUE TITLE
Unable to configure Partition ID for azure IoTHub

### ISSUE THREAD

**Issue by keshav1git** [Azure/iotedge#1985]
## Expected Behavior
should be able to send messages to IoTHub with user defined partitionID(0/1/2/3)

i.e., I'm able to send messages to IoTHub but messages by default it goes to partition "2" , how do make messages to go to partition "0" or "1" etc.

## Current Behavior
I'm sending messages to IoTHub **ONLY** to partition "2"  using REST API  [link](https://docs.microsoft.com/en-us/rest/api/iothub/device/senddeviceevent)

## Steps to Reproduce
used reference from [link](https://docs.microsoft.com/en-us/rest/api/iothub/device/senddeviceevent)

## Context (Environment)
I'm able to send messages to IoTHub but messages by default  goes to partition "2" , how do make messages to go to partition "0". 

#### iotedged
IoT-edge version 1.0.7.1

#### Edge Agent
Edge Agent version 1.0.7.1

#### Edge Hub
Edge Hub version 1.0.7.1

#### Docker
docker version -18.09.06

**Comment by myagley** [comment]
There is no way to send a message to a user defined partition on IoT Hub. The partition is selected based on the device id to ensure that all messages from the same id end up in the same partition. This is done by hashing the device id and then mapping a segment of the digests into each partition. This gives a pseudo even distribution of messages across all partitions, assuming each device sends approximately the same number of messages.

There is no way to change this partition logic.

**Comment by keshav1git** [comment]
okay thanks @myagley

**Comment by myagley** [comment]
I am going to close this issue as there are no plans in IoT Hub to allow the partition to be specified.
