### ISSUE TITLE
Provide more specific runtime error if iotedge service is stopped ('Hyper error' )

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#199]
Getting confusing error when executing
` iotedge  list`

```
An error in the management http client occurred.
        caused by: Hyper error
        caused by: No connection could be made because the target machine actively refused it. (os error 10061)
```

OS: Windows 10, x64

Error should rather indicate that the *iotedge* service is stopped.

I know it is not a big deal, but when investigating many other errors in modules, such errors are very confusing.

**Comment by myagley** [comment]
Hi @ddobric. We appreciate the feedback and will look at improving our error messages.

In this case, I'm not sure we can tell the difference between a stopped `iotedged` and a mis-configured `iotedge`. Both of these will appear as a connection refused.
