### ISSUE TITLE
User Voice seems to be dead/unmoderated

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#2005]
As an interested user I followed you suggestion and placed a feature request on User Voice.

> * Have a feature request? Please post it on [User Voice](https://feedback.azure.com/forums/907045-azure-iot-edge) to help us prioritize.

And I did this more than a month ago - https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/38782231-support-hierarchical-module-input-structure - but the issue still waits for an acknowledgement to be published.

So please make sure that the issues awaiting moderation on User Voice get processed; or otherwise remove the project form User Voice and provide other ways to collect feature requests (e.g. as github issues). Don't get me wrong; I'm much satisfied that I'm able to contribute ideas to the project - but at least there should be a response. Thanks in advance for your support!

**Comment by chipalost** [comment]
Thank you for posting feature requests on UserVoice! You're correct that we didn't respond as fast as we should have. I've updated the request on UserVoice and will close this GitHub issue.
