### ISSUE TITLE
restart of edgeHub failed

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#202]
IotEdge module has failed for some reason. I tried to restart it:

`restart edgeHub`

getting following error:

```
An error in the management http client occurred.
        caused by: Hyper error
        caused by: message is incomplete
```

OS: Win10 x64, Linux containers

iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

Docker version 18.06.0-ce, build 0ffa825

**Comment by ddobric** [comment]
**iotedged** service was running at the moment of invoking of restart. But it seems that restart operation caused the service to crash. In any case, it would be helpful to change error message.
Both "Hyper error" and "message is incomplete" do not provide any meaningful information.

For example: "IotEdge service is not running".

**Comment by myagley** [comment]
Understood on improving the error messages. Is it possible to see the logs for `iotedged` from this time period? We are not going to be able to debug this without logs.

The `iotedged` should not crash so it is important to determine if that is what actually happened.

**Comment by ddobric** [comment]
There is nothing in log related to this. This is exactly my issue.
But when it happens again, I will provide some log-data if there is any.

**Comment by ddobric** [comment]
I figured out that this happen if the *config.yaml* is not correctly formatted.
In my case, it contained two tabs in front of connection string. 
I replaced tabs with two spaces. 

It would be great to have an error message, which indicates, that configuration file has some issues.
