### ISSUE TITLE
Can't configure logfile limit

### ISSUE THREAD

**Issue by pkoronawa** [Azure/iotedge#2030]
I have set logging configuration on the edge device as documented, but don't see any change in the log behavior. The same configuration in **\ProgramData\Docker\config** seems to have the desired effect, as indicated by **docker inspect**. However, the docker daemon is not running on the edge device so I can't get the same information.

From the logs
~~~
<6> 2019-11-08 12:04:27.270 -08:00 [INF] - Initializing Edge Agent.
<6> 2019-11-08 12:04:27.443 -08:00 [INF] - Version - 1.0.8.3.25941095 (4776f578628040014b59d261199d9e8ccdc6b00a)
<6> 2019-11-21 11:57:08.421 -08:00 [INF] - Initializing Edge Hub
<6> 2019-11-21 11:57:08.422 -08:00 [INF] - Version - 1.0.8.3.25941095 (4776f578628040014b59d261199d9e8ccdc6b00a)
~~~

~~~
 Directory of C:\ProgramData\iotedge-moby\config

11/05/2019  12:33 PM    <DIR>          .
11/05/2019  12:33 PM    <DIR>          ..
11/09/2019  03:14 PM               117 daemon.json
               1 File(s)            117 bytes
               2 Dir(s)  108,804,091,904 bytes free

C:\ProgramData>type iotedge-moby\config\daemon.json
{
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "500k",
        "max-file": "10"
    }
}
~~~

**Comment by ancaantochi** [comment]
Did you restart Moby Engine service after you made the configuration change?

**Comment by arsing** [comment]
>However, the docker daemon is not running on the edge device so I can't get the same information.
>
>From the logs

If the Docker daemon wasn't running, you wouldn't have had any running modules to get logs from. Why do you think the Docker daemon wasn't running?

**Comment by pkoronawa** [comment]
@ancaantochi i I had not restarted the service explicitly, but I had rebooted the machine. Does that not have the same effect? It does seem that after restarting the service the log file size is honored. However, only a single log file is preserved, despite setting "max-file": "10"

@arsing Because I tried **docker inspect** and received **error during connect:...This error may also indicate that the docker daemon is not running.**

**Comment by arsing** [comment]
>Because I tried **docker inspect** and received **error during connect:...This error may also indicate that the docker daemon is not running.**

I assume you did not set [the `-H` parameter](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#manage-module-containers) or did not run it as Administrator.

**Comment by pkoronawa** [comment]
@arsing Thanks. I missed that parameter in the docs. So the settings are showing up in **inspect**, but I would assume up to 10 logs would be present. I never see more than one in **iotedge-moby\containers\\***

~~~
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "10",
                    "max-size": "500k"
                }
            },
~~~

**Comment by varunpuranik** [comment]
@pkoronawa - in the config, you have set the max-file to 10. So that is the maximum number of files you will have. A new file will be created only if the first file of 500k is full. So you will get 10 files only if you have 9 full files on disk.

**Comment by chipalost** [comment]
Closing this issue as it looks like it has been addressed. Please reactivate if you need more guidance.

**Comment by pkoronawa** [comment]
@varunpuranik The log file has filled and recreated many times, but the previous versions are always deleted. There has never been more than one file at any given time.
