### ISSUE TITLE
Module version of Hub Device Streams?

### ISSUE THREAD

**Issue by radoye** [Azure/iotedge#2034]
What is the recommended way to leverage [IoT Hub Device Streams](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-streams-overview) from a module?

  * Module SDK has "create from environment", handling connection string distribution and enabling us to deploy a feature to all edge devices;
  * Device SDK does not seem to have that, and requires us to handle connection string distribution which is clunky. 

We are trying to create a module that would allow interactive work with an edge device during bring-up and debugging phase. However, we want to remove such a feature once the device is fully operational. 

Hub Device Streams almost seem like they could work. However, they require working with the Device SDK, which we cannot do. Is there a reasonable alternative? Thanks!

**Comment by chipalost** [comment]
This is a known feature request that we're tracking and a couple of work items that need to be completed before this scenario is delivered end to end. First we need a GA version of a module SDK which supports device streams. After that, we need to update Edge Hub to support this feature.

**Comment by emilm** [comment]
Hello! What is the estimate for delivering this functionality to IoT edge? I have the same issue. How would I work around it, is it even possible? Where would I get the connection info from?

**Comment by veyalla** [comment]
This is not yet possible. Please file or vote for existing feature request at https://feedback.azure.com/forums/907045-azure-iot-edge
