### ISSUE TITLE
Is there Edge Runtime APIs so that we can get the Edge module status on the Gateway when Gateway is offline 

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#2048]
Hi Team,
    We want to develop an Utility like as Watch Dog which will monitor Edge Runtime, Edge Modules on Gateway Locally. Specially when the Gateway is offline and we want to perform some steps locally. 
So could you tell me so the best approach for this.. Also could you provide me the Edge Runtime APIs so that we can call them to get the status of the Edge Modules. and Edge Runtime.. Or is there any other way to get these status ??

**Comment by sachidanand** [comment]
Can you please revert on this

**Comment by sachidanand** [comment]
Could you revert on this

**Comment by veyalla** [comment]
The new metrics from the IoT Edge runtime should help with this: https://aka.ms/iotedgemetrics. This will GA in 1.0.10 release
