### ISSUE TITLE
edge_hsm_client_crypto.c:hsm_client_crypto_init:47) Could not create store. Error code 2025

### ISSUE THREAD

**Issue by DK2019-w** [Azure/iotedge#2049]
## Expected Behavior
Create new dev certificates because the old ones were expired and changed the path in the /etc/iotedge/config.yaml path to the new directorey where the newly generated certificates were stored. Started the iotedge runtime again with sudo systemctl start iotedge and normally the edge runtime should be running and the edgeAgent, etc. should be started.

## Current Behavior
The edge runtime is not running according to sudo systemctl status iotedge. And if I use sudo journalctl -u iotedge -f to get more detailed information of the error I got the following error log:
2019-11-27T09:24:57Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:hsm_client_crypto_init:47) Could not create store. Error code 2025

## Steps to Reproduce
Edge runtime installed on RHEL 8.0:
1. Stopped the edge runtime using sudo sytemctl stop iotedge
2. Generate the certificates using the certGen.sh from https://github.com/Azure/azure-iot-sdk-c/tree/master/tools/CACertificates
3. Change the /etc/iotedge/config.yaml to have the path to the certificates generated in 2
4. Started the edge runtime again with sudo systemctl start iotedge
5. Edge runtime doesn't start and has the error: 2019-11-27T09:24:57Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:hsm_client_crypto_init:47) Could not create store. Error code 2025

We already did it the same on Ubuntu Desktop and Server a couple of times and there no problems occurred. Might this an issue with using RHEL or is it an issue with the HSM.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged 1.0.8

**Comment by varunpuranik** [comment]
Can you please provide the iotedged logs for your scenario? That might tell us why IoT Edge runtime is failing to start for you. 
https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#standard-diagnostic-steps

**Comment by DK2019-w** [comment]
-- Logs begin at Die 2019-11-26 07:27:11 CET. --
Dez 04 09:03:34 localhost.localdomain iotedged[7947]: 2019-12-04T08:03:34Z [INFO] - Finished configuring certificates.
Dez 04 09:03:34 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 04 09:03:34 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 04 09:03:34 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 04 09:03:34 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 04 09:03:34 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 04 09:03:34 localhost.localdomain systemd[1]: start request repeated too quickly for iotedge.service
Dez 04 09:03:34 localhost.localdomain systemd[1]: Failed to start Azure IoT Edge daemon.
Dez 04 09:03:34 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 04 09:03:34 localhost.localdomain systemd[1]: iotedge.service failed.
Are this logs sufficient?

**Comment by varunpuranik** [comment]
That actually does not have the information I am looking for. Can you please run the following command and provide us the output - 
$>journalctl -u iotedge

**Comment by DK2019-w** [comment]
X11 forwarding request failed on channel 0
Last login: Wed Dec  4 09:29:35 2019 from 192.168.5.60
[root@localhost ~]# sudo journalctl -u iotedge
-- Logs begin at Mit 2019-12-04 11:12:31 CET, end at Mit 2019-12-11 09:48:14 CET. --
Dez 04 11:12:52 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Version - 1.0.8
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Using runtime network id azure-iot-edge
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Initializing the module runtime...
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Initializing module runtime...
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Successfully initialized module runtime
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Finished initializing the module runtime.
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Configuring certificates...
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Configuring the Device CA certificate using "/home/gw/Documents/CACertificates/certs/new-edge-device-full-chain.cert.pem".
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Configuring the Device private key using "/home/gw/Documents/CACertificates/private/new-edge-device.key.pem".
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Configuring the trusted CA certificates using "/home/gw/Documents/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem".
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Finished configuring certificates.
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [INFO] - Initializing hsm...
Dez 04 11:12:52 localhost.localdomain iotedged[1755]: 2019-12-04T10:12:52Z [ERR!] - The daemon could not start up successfully: Could not initialize HSM
Dez 04 11:12:52 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 04 11:12:52 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 04 11:12:52 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 04 11:12:52 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 04 11:12:52 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 04 11:12:52 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Version - 1.0.8
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Using runtime network id azure-iot-edge
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Initializing the module runtime...
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Initializing module runtime...
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Successfully initialized module runtime
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Finished initializing the module runtime.
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Configuring certificates...
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Configuring the Device CA certificate using "/home/gw/Documents/CACertificates/certs/new-edge-device-full-chain.cert.pem".
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Configuring the Device private key using "/home/gw/Documents/CACertificates/private/new-edge-device.key.pem".
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Configuring the trusted CA certificates using "/home/gw/Documents/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem".
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Finished configuring certificates.
Dez 04 11:12:52 localhost.localdomain iotedged[1837]: 2019-12-04T10:12:52Z [INFO] - Initializing hsm...
Dez 04 11:12:52 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 04 11:12:52 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 04 11:12:52 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 04 11:12:52 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 04 11:12:52 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 04 11:12:52 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 04 11:12:52 localhost.localdomain iotedged[1848]: 2019-12-04T10:12:52Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 04 11:12:52 localhost.localdomain iotedged[1848]: 2019-12-04T10:12:52Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 04 11:12:52 localhost.localdomain iotedged[1848]: 2019-12-04T10:12:52Z [INFO] - Version - 1.0.8
Dez 04 11:12:52 localhost.localdomain iotedged[1848]: 2019-12-04T10:12:52Z [INFO] - Using runtime network id azure-iot-edge
Dez 04 11:12:52 localhost.localdomain iotedged[1848]: 2019-12-04T10:12:52Z [INFO] - Initializing the module runtime...
Dez 04 11:12:52 localhost.localdomain iotedged[1848]: 2019-12-04T10:12:52Z [INFO] - Initializing module runtime...
Dez 04 11:12:52 localhost.localdomain iotedged[1848]: 2019-12-04T10:12:52Z [INFO] - Successfully initialized module runtime

**Comment by kkdawkins** [comment]
@DK2019-w  Are you sure that iotedge has permissions on the new directory?

**Comment by DK2019-w** [comment]
Currently, it has read permissions at the new directory. Are read permissions sufficient?

**Comment by kkdawkins** [comment]
It needs read/write

**Comment by kkdawkins** [comment]
@DK2019-w  - Did this solve your issue?

**Comment by DK2019-w** [comment]
Not really, we changed the permissions to read/write but still the same error occurs.
Current logs:

-- Logs begin at Mit 2019-12-18 04:07:26 CET, end at Mit 2019-12-18 06:16:07 CET. --
Dez 18 04:07:46 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Version - 1.0.8
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Using runtime network id azure-iot-edge
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Initializing the module runtime...
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Initializing module runtime...
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Successfully initialized module runtime
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Finished initializing the module runtime.
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Configuring certificates...
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Configuring the Device CA certificate using "/\"CACertificates/certs/new-edge-device-full-chain.cert.pem\"".
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Configuring the Device private key using "/CACertificates/private/new-edge-device.key.pem".
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Configuring the trusted CA certificates using "/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem".
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Finished configuring certificates.
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [INFO] - Initializing hsm...
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [ERR!] - The daemon could not start up successfully: Could not initialize HSM
Dez 18 04:07:46 localhost.localdomain iotedged[1823]: 2019-12-18T03:07:46Z [ERR!] -         caused by: HSM failure
Dez 18 04:07:46 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 18 04:07:47 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Version - 1.0.8
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Using runtime network id azure-iot-edge
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Initializing the module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Initializing module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Successfully initialized module runtime
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Finished initializing the module runtime.
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Configuring certificates...
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device CA certificate using "/\"CACertificates/certs/new-edge-device-full-chain.cert.pem\"".
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device private key using "/CACertificates/private/new-edge-device.key.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Configuring the trusted CA certificates using "/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Finished configuring certificates.
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [INFO] - Initializing hsm...
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [ERR!] - The daemon could not start up successfully: Could not initialize HSM
Dez 18 04:07:47 localhost.localdomain iotedged[1836]: 2019-12-18T03:07:47Z [ERR!] -         caused by: HSM failure
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 18 04:07:47 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Version - 1.0.8
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Using runtime network id azure-iot-edge
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Initializing the module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Initializing module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Successfully initialized module runtime
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Finished initializing the module runtime.
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Configuring certificates...
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device CA certificate using "/\"CACertificates/certs/new-edge-device-full-chain.cert.pem\"".
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device private key using "/CACertificates/private/new-edge-device.key.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Configuring the trusted CA certificates using "/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1848]: 2019-12-18T03:07:47Z [INFO] - Finished configuring certificates.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 18 04:07:47 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Version - 1.0.8
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Using runtime network id azure-iot-edge
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Initializing the module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Initializing module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Successfully initialized module runtime
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Finished initializing the module runtime.
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Configuring certificates...
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device CA certificate using "/\"CACertificates/certs/new-edge-device-full-chain.cert.pem\"".
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device private key using "/CACertificates/private/new-edge-device.key.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Configuring the trusted CA certificates using "/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Finished configuring certificates.
Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Initializing hsm...
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 18 04:07:47 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain systemd[1]: Started Azure IoT Edge daemon.
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Starting Azure IoT Edge Security Daemon
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Version - 1.0.8
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Using runtime network id azure-iot-edge
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Initializing the module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Initializing module runtime...
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Successfully initialized module runtime
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Finished initializing the module runtime.
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Configuring certificates...
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device CA certificate using "/\"CACertificates/certs/new-edge-device-full-chain.cert.pem\"".
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device private key using "/CACertificates/private/new-edge-device.key.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Configuring the trusted CA certificates using "/CACertificates/certs/azure-iot-test-only.root.ca.cert.pem".
Dez 18 04:07:47 localhost.localdomain iotedged[1870]: 2019-12-18T03:07:47Z [INFO] - Finished configuring certificates.
Dez 18 04:07:47 localhost.localdomain systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dez 18 04:07:48 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 18 04:07:48 localhost.localdomain systemd[1]: iotedge.service failed.
Dez 18 04:07:48 localhost.localdomain systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dez 18 04:07:48 localhost.localdomain systemd[1]: Stopped Azure IoT Edge daemon.
Dez 18 04:07:48 localhost.localdomain systemd[1]: start request repeated too quickly for iotedge.service
Dez 18 04:07:48 localhost.localdomain systemd[1]: Failed to start Azure IoT Edge daemon.
Dez 18 04:07:48 localhost.localdomain systemd[1]: Unit iotedge.service entered failed state.
Dez 18 04:07:48 localhost.localdomain systemd[1]: iotedge.service failed.

**Comment by dmolokanov** [comment]
I noticed something weird in logs you provided:

Dez 18 04:07:47 localhost.localdomain iotedged[1859]: 2019-12-18T03:07:47Z [INFO] - Configuring the Device CA certificate using **"/"CACertificates/certs/new-edge-device-full-chain.cert.pem""**.

Seems like there are additional quotes around the cert chain file path. I don't see it for a key. Could you please verify this part of your config file?

**Comment by DK2019-w** [comment]
Yes, there were some wrong quotes too, so the changing of the permissions to read/write worked and solved the issue.
Thank you, and I will close this ticket.
