### ISSUE TITLE
Use custom connector with IoT Edge Runtime

### ISSUE THREAD

**Issue by ewertons** [Azure/iotedge#2050]
Ported on behalf of @DmitryN270713 from https://github.com/Azure/azure-iot-sdk-c/issues/1337
Apologies for not filling the template, please follow up with customer for more details.

---

Hi guys,
Today I have a bit tricky question. Imagine a situation when someone has written a custom connector to the network (let's say there are a lot of security features hidden and so on). Now imagine that each application can connect to the network (even IoT Edge Runtime) only through this custom connector (let's say, this connector has implementation of both https and plain MQTT protocols).
Now the issue! According to the documentation here https://github.com/Azure/iotedge/blob/master/doc/networking.md the IoT Edge Runtime connects to the network through moby-engine modified by Microsoft. According to the Microsoft, we cannot get this moby-engine. Moreover, if we use original moby project the support from the Microsoft will be caught off, which is a bad thing. So, we cannot modify moby-engine and make it use this custom connector.
Now the question!
Is it possible (may be I missed something in documentation. Not the first time tbh) to use custom connector with IoT Edge Runtime (no proxy, we need plain MQTT protocol)? If yes, can you explain in details how? If no, what posible features inside Iot Edge Runtime/moby engine can help to use custom connector?
Thank you in advance!

**Comment by asergaz** [comment]
Here's the question with a possible solution in StackOverflow: https://stackoverflow.com/questions/58970711/is-it-possible-to-use-custom-connector-with-iot-edge-runtime

@DmitryN270713 please let us know if your issue can now be closed.

**Comment by DmitryN270713** [comment]
Hi @asergaz,

Yes, I know about this. The guy with strange nickname "user...." is me =)

**Comment by chipalost** [comment]
Thanks for asking this question on StackOverflow. That's exactly where we'd like to address issues like this. I'm going to close this issue since it is tracked there. It also looks like you got an answer on StackOverflow. Please let us know if you need more guidance.

**Comment by chipalost** [comment]
Actually closing this issue per the comment above.
