### ISSUE TITLE
Error creating client identity - when bridging mosquitto to edgeHub as module

### ISSUE THREAD

**Issue by vasdee** [Azure/iotedge#2060]
Hi, 

I am trying to build out an transparent gateway using iotedge. Due to some specific use cases with our design, it requires putting a pure MQTT broker (mosquitto in this case) as the primary connection for devices to communicate with and then bridge that with edgeHub before sending the data to unto iothub.

I have managed to install mosquitto directly on the iotedge host (hostname is iothub-test on a RHEL VM in Azure) and can send messages from another VM using mosquitto_pub (or script) using mosquitto as the entry point on 8883 and can successfully bridge that connection to the edgeHub module by rebinding the edgeHub port to 8884. This is all setup via x509 authentication which was mostly derived from the info here [http://busbyland.com/mosquitto-mqtt-broker-to-iot-hub-iot-edge/](http://busbyland.com/mosquitto-mqtt-broker-to-iot-hub-iot-edge/). As a side I was able to configure mosquitto to use the same Edge Device CA certificates as the edge gateway so that from a leaf device perspective, it should be the same experience as connecting to edgeHub directly.

The problem I have is I want to be able to manage mosquitto as an iotedge module, rather than being deployed on the host. Building the mosquitto module and getting it to work as a broker the same way as it was when installed directly on the edge host was easy enough, however the bridge connection errors out with a "Error creating client identity - username is null or whitespace"

I have been following this guide for configuring the connection string [https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly-as-a-module](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly-as-a-module) and based on some other information, I have been attempting to bridge the connection using a separate 'device certificate' as I am under the impression that bridging the connection with the same certs as iotedge could cause problems with circular certificate references. Ideally it would be great to be able to use one set of certs for iotedge, bridge and broker but i'm not sure this is possible.

I think I'm close to getting this working successfully, it might even be that i've been battling too long with this to be able to see it clearly anymore. I'm hoping someone can shed some information on this.

<summary>edge-hub logs</summary>

> 2019-12-03 00:06:38.349 +00:00 [ERR] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceIdentityProvider] - Error creating client identity
> System.ArgumentException: username is null or whitespace.
>    at Microsoft.Azure.Devices.Edge.Util.Preconditions.CheckNonWhiteSpace(String value, String paramName) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Preconditions.cs:line 191
>    at Microsoft.Azure.Devices.Edge.Hub.Mqtt.DeviceIdentityProvider.GetAsync(String clientId, String username, String password, EndPoint clientAddress

<summary>iotedge config</summary>
_omitted most of this as it is mostly vanilla and works correctly with iothub_

> hostname: "iothub-test"
> certificates:
>    device_ca_cert: "/opt/iotedge/credentials/ca/iot-edge-device-ca-EdgeGateway-full-chain.cert.pem"
>    device_ca_pk: "/opt/iotedge/credentials/private/iot-edge-device-ca-EdgeGateway.key.pem"
>    trusted_ca_certs: "/opt/iotedge/credentials/ca/ca-bundle.crt"

<summary>mosquitto broker config</summary>

> \# Broker config 
> listener 8883
> log_type all
> allow_anonymous false
> require_certificate true
> tls_version tlsv1.2
> \# When TLS is enabled, uses the CN name as the identity
> \# this option then uses that identity for the username, which removes the 'allow_anonymous true' requirement
> use_identity_as_username true
> 
> cafile /etc/mosquitto/ca_certificates/ca-bundle.crt
> certfile /etc/mosquitto/certs/iot-edge-device-ca-EdgeGateway-full-chain.cert.pem
> keyfile /etc/mosquitto/private/iot-edge-device-ca-EdgeGateway.key.pem
> 

<summary>mosquitto bridge config</summary>

> \# Bridge configuration
> connection azureiot-bridge
> log_type all
> address iothub-test:8884?GatewayHostName=iothub-test
> remote_username [iothub short name].azure-devices.net/BridgeAdapter/MQTTBroker/?api-version=2019-01-30
> remote_clientid BridgeAdapter/MQTTBroker
> bridge_insecure true
> bridge_cafile /etc/mosquitto/ca_certificates/ca-bundle.crt
> bridge_certfile /etc/mosquitto/certs/iot-device-BridgeAdapter-full-chain.cert.pem
> bridge_keyfile /etc/mosquitto/private/iot-device-BridgeAdapter.key.pem
> start_type automatic
> try_private false
> cleansession true
> start_type automatic
> bridge_protocol_version mqttv311
> bridge_tls_version tlsv1.2
> notifications false
> notification_topic events/
> bridge_attempt_unsubscribe false
> topic # out 1
> topic # in 1

<summary> mosquitto logs </summary>

> 1575332832: Bridge local.BridgeAdapter/MQTTBroker doing local SUBSCRIBE on topic #
> 1575332832: Connecting bridge (step 1) azureiot-bridge (iothub-test:8884)
> 1575332832: Connecting bridge (step 2) azureiot-bridge (iothub-test:8884)
> 1575332832: Bridge BridgeAdapter/MQTTBroker sending CONNECT
> 1575332832: Error creating bridge: Protocol error.

**Comment by varunpuranik** [comment]
Hi @vasdee - 
From the error in EdgeHub, it looks like the bridge is not setting the username in the connect packet it is using to connect to EdgeHub. 
The EdgeHub MQTT Protocol head expects certain properties to be set in the connect packets. 
Look at the C# SDK implementation of this for reference - https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Transport/Mqtt/MqttIotHubAdapter.cs#L293

I assume the bridge you are using is a pure MQTT Bridge (and not using one of the IoT Hub SDKs)? 
Also adding @stevebus who might have some experience getting this scenario to work.

**Comment by stevebus** [comment]
Hey @vasdee .   Glad you found my blog post useful to get started. 🙂  Unfortunately I haven’t tried it (yet) with Mosquitto in an Edge module..

 A few questions/comments:

What is the device id you created in IoTHub to represent your Mosquitto broker?  You have a slash in it (in your remote client ID field), so I assume you created a device ID and manually created a module I’d under it?  I haven’t tried that.

What is iothub-test (in your address)..  what does that resolve to?  (I.e. is that the machine name of your Edge box?  the ‘hostname’ in config.yaml?

What version of edgeHub are you running (top of the edgeHub logs)?

I may have more questions at some point...  but we can start with those..

Also, what container image are you using for mosquito?  Thinking about trying it myself and don’t want to start from scratch if I didn’t have to

**Comment by vasdee** [comment]
@varunpuranik thanks for the reply. Yes it is a pure MQTT Bridge using Mosquitto's built in feature
@stevebus thanks for the writing the article, it had some good pointers in there for getting started on this. 

1) The device id for mosquitto is BridgeAdapter, it was created as a child device under the EdgeGateway device. I'm not sure if this is a required or necessary approach but I did it so I could essential manage the certificates.

2) Correct, iothub-test is a RHEL vm in azure. It is the Edge Gateway box and it is the hostname in config.yaml.

3)  Version - 1.0.8.4.26769994

4) Container image was custom, easy enough though (see below)

A bit of an update on my end, i changed the approach slightly for the bridge configuration. Instead of trying to resolve the edgeHub address via the host's hostname (iothub-test) or localhost. I opened up the port edgeHub port and route the address via the FQDN. This actually works! I can then call mosquitto_pub from my local machine and the message is bridged to edgeHub and routed to Azure IotHhub correctly.

This is not something I'd want to do in production as it would mean exposing the edgeHub port as well as the mosquitto/mqtt module. However, it does make me think that the issue might be solvable by adding the vm hostname into /etc/hosts as an alias to localhost.... I think I've seen other issues raised here where that was a solution...

## mosquitto bridge.conf excerpt

> connection azureiot-bridge
> log_type all
> address [edge-host vm name].australiaeast.cloudapp.azure.com:8884?GatewayHostName=iothub-test
> remote_username [iot hub short name].azure-devices.net/BridgeAdapter/?api-version=2019-01-30
> remote_clientid BridgeAdapter
> bridge_cafile /etc/mosquitto/ca_certificates/ca-bundle.crt
> bridge_certfile /etc/mosquitto/certs/iot-device-BridgeAdapter-full-chain.cert.pem
> bridge_keyfile /etc/mosquitto/private/iot-device-BridgeAdapter.key.pem


## mosquitto dockerfile

mount in the configuration for certs and config under /etc/mosquitto/

```
FROM debian:bullseye-slim

RUN apt-get update
RUN apt-get install mosquitto -y

# Need to expose 
# broker certfile and key
# Bridge certfile and key
VOLUME ["/etc/mosquitto/"]

EXPOSE 1883
EXPOSE 8883

ENTRYPOINT ["/usr/sbin/mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]
```

**Comment by stevebus** [comment]
thanks for the details @vasdee .   Glad you at least got a working solution, but I understand (and agree) that you don't want to have to expose edgeHub externally and use FQDN..   I think adding the vm hostname into /etc/hosts might be a workaround...

Generally, when we communication from module-to-module inside of IoT Edge, you can just use the module name and we will automatically resolve it.  However,  this is a special case in that you are a) using edgeHub as the target module and b) we need the TLS encryption, which adds the complication of the TLS-server-side cert.   So, I would be willing to bet you could use 'edgeHub' as the target address and it would work.  The only complication is which 'hostname' mosquitto will use to validate the TLS cert returned by edgeHub.

So, for example, if you had

address edgeHub:8884?GatewayHostName=iothub-test

would it try to validate the TLS cert that edgeHub returns against the CN/subjectname of 'edgeHub', or of 'iothub-test'...   the TLS cert that edgeHub returns will have a CN/subject name of whatever your 'hostname' parameter in config.yaml is (which I assume is 'iothub-test').

I'm going to try this myself, but it would be interesting to see if it worked for you if you could test it faster.

Also, as an aside, I've worked with other customers with the MQTT broker -> edgeHub scenario as well.  Typically, they do that for one (or both) of two reasons:

1) the 'client' devices can't do TLS and they need the Mosquitto bridge to do the non-TLS->TLS briding, or
2) they need to send MQTT data on arbitrary topics.  (besides the one 'device/[device id]/messages/events one that edgeHub listens on)

since you have mosquitto listening on 8883, I assume it's not #1 above.  I'm curious on why you need mosquitto..  is it #2 above?  or some other reason?

(this helps us think about/inform future product direction)

**Comment by vasdee** [comment]
Using `edgeHub:8884` with or without the `GatewayHostName=iothub-test` unfortunately didn't work.   I don't even see a connection attempt being logged in the edgeHub logs...

The /etc/hosts alias to localhost seems to work too, so I have an ok solution to build on for now.  I'm going to have to read up more about docker networking and name resolution, I get the feeling that the answer might be there somewhere.

To answer your side questions, it is for both reasons. This example has been focused on getting TLS working to prove that the solution 'can work', but in reality I believe we will end up having multiple listeners configured within mosquitto to expose 1883 using some other authentication (or none at all or some extreme cases.) As part of the requirements for this project, we are also prescribing a specific payload and topic structure for new greenfields development. This will allow us to have some kind of governance over the data going upstream.

If you are taking suggestions for the product team, to address point 2, it would be a nice feature if iotedge was able to route arbitrary topic names and only drop them once they are reach the $upstream route. In my solution, mosquitto uses the nifty module feature to host a service, but if I want anything to be able to subscribe to a non-standard topic, i have to host another module and connect directly to mosquitto itself. Having the routing here would potentially remove that and simplify the solution somewhat, but not a deal breaker for sure.

**Comment by veyalla** [comment]
Thanks for the feedback! Please file or vote for existing feature request at https://feedback.azure.com/forums/907045-azure-iot-edge
