### ISSUE TITLE
windows install script vcruntime check needs to be wow64 aware for enterprise

### ISSUE THREAD

**Issue by seanmcd-msft** [Azure/iotedge#2078]
As mentioned in https://github.com/Azure/iotedge/pull/1871#discussion_r354624952 , the Windows installer script looks at `C:\Windows\System32\vcruntime140.dll` to decide whether the MSVCRT is already installed or not. This will probably get redirected to `C:\Windows\SysWoW64` when running 32-bit PS on 64-bit Windows. If so, it should be fixed to be PS-bitness-independent, just like https://github.com/Azure/iotedge/commit/76eacaf988e7d421b4e45c70a45d8160f1feaaa1 did for Program Files.

(Assigning to Sean per email conversation.)

**Comment by veyalla** [comment]
@seanmcd-msft is there an update here?

**Comment by seanmcd-msft** [comment]
no. this is lower priority then other stuff i'm doing and i haven't gotten to it yet.  It is a bug.  but, it's very unlikely to be an issue in practice since most people won't run the installer from 32 bit PS.
