### ISSUE TITLE
Transacted consumers with C SDK possible? Re-open #900?

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#2089]
Is this (#900) limitation still in place (with e.g. 0.2.0.0-16bionic)? Is it possible to write C/C++ consumers that support transactions between the IoT edge and other systems? If not, what are the options to establish a reliable communication? Since I'm using other C libraries using another SDK that supports AMQP on the edge seems not to be a (good) option.

**Comment by varunpuranik** [comment]
@alaendle - It seems like you want to achieve at-least-one semantics with an app using the C SDK talking to EdgeHub. In that case, the recommended pattern is - 
- Add a callback for receiving messages, and send a Completed response when you receive the message, which is used as an ACK. 
- If you need to delay processing a message in your app for some reason, store it locally, and process it when the app wants to (instead of returning an Abandoned or Rejected response).
This should allow you to achieve what you need over MQTT. Does that solve your scenario? Or do you have some other requirements that are not fulfilled by this?

**Comment by alaendle** [comment]
@varunpuranik - Please excuse that I was unclear or at least vague in my description of the problem. But you filled the missing points with valid assumptions - thanks for that 👍 ! Indeed I want to process messages with at-least-once quality - and use the C sdk to talk to the local EdgeHub of an Azure IoT Edge.

To be honest I'm not satisfied with both of the recommended patterns. The second couldn't guarantee at-least-once in a strict sense (since it could not recover from a crash while persisting an incoming message); and the first idea just moves the problem from transport to application level - and this highly conflicts with the goal of composability (and for me this is one of the key features of the Microsoft Edge solution that stands out).

I grasp your edge solution as some kind of tool that also enable ETL processes through the edgeHub routing in a very composable way. So we may have some kind of input- and output-adapters - and maybe in-between some transformation steps. For that kind of reason I've implemented e.g. a bridge between two different message broker products and edgeHub.

To be more concrete - we have a design like the following:

**`PLC (programmable logic controller) -> Local Message Broker -> Edge Module acting as a gateway -> EdgeHub -> Edge Module acting as a gateway -> Enterprise Message Broker`**

With this picture in mind I guess you agree that the ACK surrogate message is a messy workaround; it would potentially work if we put this logic in both edge modules, but it would couple both modules so tight and would also make it very difficult to attach intermediary transformation steps (by just changing the edgeHub routes) that it is not worth to use edgeHub for communication at all. Leading to a design like:

**`PLC (programmable logic controller) -> Local Message Broker -> Edge Module acting as a gateway -> Enterprise Message Broker`**

While the above design satisfies the at-least-once semantic I'm not pleased with its extensibility and modularity (why are input and output destinations coupled; how to add transformation steps; etc.).

So I hope I could clarify our thoughts and requirements - please don't hesitate to ask for further clarifications or additional information if needed. And I also hope that it's now clear why we would favor at-least-once support on edgeHub communication 😉

**Comment by varunpuranik** [comment]
@alaendle - Sorry I am a bit confused. 
My understanding of the original ask was to have a module connect to EdgeHub and receive messages with at-least-once semantics (so that if the module fails to ack a message for some reason, the message will be sent again to the module). I explained the pattern to achieve this with one module in my previous answer.
What you describe is complex app deployment with multiple brokers. It is not clear to me what your scenario is, and what actual issue you are running into. And how that is related to having the ability to Abandon messages a module receives (https://github.com/Azure/iotedge/issues/900)
Can you please clarify?

**Comment by alaendle** [comment]
@varunpuranik - Thanks and sorry, it wasn't my intention to cause additional confusion.

Basically I want what you've stated - **receive messages from EdgeHub with at-least-once semantics**.

I just thought it would be wise to add some context to be able to share my concerns with your initial answer. But if this adds confusion, here is just my requirement without additional info.

I want...
1. Receive a message from EdgeHub
2. Process it
3. Acknowledge it OR reject it for redelivery DEPENDENT on the process result

And point (3) is where I see the relationship to #900.

Hope this helps; but please don't hesitate to contact me again if I was still unclear. Thanks for your support.

**Comment by varunpuranik** [comment]
@alaendle - thanks, that makes sense. And I appreciate the context as well.
The flow you ask works with AMQP, but not with MQTT. That is a C# SDK limitation and not a limitation with EdgeHub as such. Can you use AMQP as the protocol to talk to EdgeHub. 
Please note that currently there is a perf issue with receiving messages over AMQP. So if perf is a concern for you, please test if it meets your requirements.

**Comment by alaendle** [comment]
@varunpuranik For sure I could consider AMQP; but before I try that, are you sure that the C SDK (not the C# SDK) has support for it?

I just ask because https://github.com/Azure/iotedge/issues/900#issuecomment-475084546 suggests otherwise - but maybe this is wrong has changed in the meanwhile.

> 
> 
> With MQTT message disposition isn't supported at all. This feature is supported only on AMQP and AMQP support is not available in the C SDK [...]

**Comment by varunpuranik** [comment]
@alaendle - ah, yes. The C SDK does not support AMQP yet. 
So unfortunately at this point, your only option is to accept the message (send Completed response), and handle the additional logic in your module code. 

@jebrando @jspaith as fyi

**Comment by alaendle** [comment]
With other words, it is not possible to write a C module that processes messages at-least-once; so messages could get lost during the process. Since the complete Azure IoT Edge platform is build around the concept of exchanging messages between devices, modules and the cloud I didn't believe this state could last forever. Or is the C SDK not really supported and just a crutch for people that couldn't use C#? I really think the C SDK  needs to catch up to the C# SDK; e.g. not only the C SDK should respect the [IOTHUBMESSAGE_DISPOSITION_RESULT](https://docs.microsoft.com/de-de/azure/iot-hub/iot-c-sdk-ref/iothub-client-core-common-h#iothubmessage_disposition_result) it also should allow asynchronous responses (like it's [.NET counterpart](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.messagehandler?view=azure-dotnet#return-value))

**Comment by veyalla** [comment]
Assigning to @jebrando, please let us know if you'd like us to move to the c repo.

**Comment by anhashia** [comment]
HI @alaendle 

For MQTT,  delivery once is set at  **QOS: DELIVER_AT_LEAST_ONCE** at MQTT protocol level, It is set in MQTT PUBLISH packet..
	
This is the **default** IoT C SDK uses (**QoS=1**) for send event.  So when IoT Hub or IoT Edge module receives the message, the MQTT broker running on them has to respond with confirmation message (PUBACK). 

It is tied to send call

> IoTHubDeviceClient_LL_SendEventAsync(device_ll_handle, message_handle, send_confirm_callback, NULL);'' 

`static void send_confirm_callback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)`

Check for **IOTHUB_CLIENT_CONFIRMATION_RESULT** result.

If client (device) is not able to process PUBACK message sent by MQTT broker for some reason, it will remain in queue in IoT C SDK and will be **retried** as per set retry policy.  This will happen all under the hood and will  all be **transparent** to the user.  

For example, if client lost network connection right at the time, it has to process PUBACK, the message will be marked for **re-delivery** by IoT C SDK. In this case MQTT broker (IoT Hub or IoT Edge module)  may get same message twice but at different en-queued time. Messages are differentiated using **message id** which has to be unique set by the user. So user will have ability to detect duplicates.
 
There is also a message timeout which can be set for the message. If message cannot be sent, it will timeout as per user setting.

C# SDK should also behave similarly as this at MQTT protocol level.

**Comment by anhashia** [comment]
Hi @alaendle 

For receive, path would be similar. For **QoS=1** which is default in IoT C SDK. SDK under the hood will manage it. If MQTT broker (IoT Hub or IoT edge) doesn't get PUBACK, it will retry to send the packet.  There should  really be *no* action in the user application (module) . This will all happen at MQTT protocol level

**IoT C SDK constructs**
#define IOTHUBMESSAGE_DISPOSITION_RESULT_VALUES \
    IOTHUBMESSAGE_ACCEPTED, \
    IOTHUBMESSAGE_REJECTED, \
    IOTHUBMESSAGE_ABANDONED

IOTHUBMESSAGE_REJECTED and IOTHUBMESSAGE_ABANDONED is **not** relevant for MQTT. It is only relevant for AMQP, where user can explicitly decide how to dispose the incoming message as per their application logic. For example., application may decide to reject the message or it may decide to abandon the message. In the case of abandon the IoT Hub will retry to send the message till delivery count is exceeded. 

If your requirements is that you want to make sure that message is delivered once then QoS=1 at MQTT protocol should take care of it.

If your specific  requirement is to have application level user/business logic rejection then AMQP would be way to go. But as has been mentioned in the thread above, AMQP for edge modules in IoT C SDK  is not currently supported.

**Comment by alaendle** [comment]
Hello @anhashia, 

thanks for your reply, want I didn't fully understand for now is the statement that the C SDK under the hood manages the transaction (sends the corresponding PUBACK) - without 
relying on the IOTHUBMESSAGE_DISPOSITION_RESULT_VALUES. Basically I wonder how this is done? 

My assumption was that also for MQTT a return value of IOTHUBMESSAGE_ACCEPTED acknowledges a message, while IOTHUBMESSAGE_ABANDONED triggers a redelivery (skips the corresponding PUBACK). 

Since this assumption seems to be wrong, how is the behaviour currently defined? Is a PUBACK send directly after the processing of the callback - without evaluation of the IOTHUBMESSAGE_DISPOSITION_RESULT? What happens if an exception occurs inside the callback - or even the module crashes inside the callback?

However, I have to do more testing of the actual behaviour - likely happens next week; for sure I will follow up this issue...

Thanks again for your support.

**Comment by anhashia** [comment]
Hi @alaendle 

Disposition call is stubbed out C SDK for **MQTT** protocol
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/src/iothubtransport_mqtt_common.c#L3517

- It will have **no** effect even if your send IOTHUBMESSAGE_ABANDONED for MQTT

It is controlled at MQTT level under the hood as part of MQTT operation call back handle by **umqtt** library 
https://github.com/Azure/azure-umqtt-c/blob/master/src/mqtt_client.c#L636 which IoT C SDK uses.

For QoS=1, the client (receiver) code will need send PUBACK.
If there is issue here and it is not sent for any reason for QoS=1, then MQTT broker will have to retry.

**Comment by alaendle** [comment]
@anhashia  Thanks for the detailed explanation - I really hope I'm not overusing your patience. 

To be honest I didn't fully understand how the two places you pointed in the sources are related; but I think the main point was to proof the the IOTHUBMESSAGE_DISPOSITION_RESULT is discarded, right?

> For QoS=1, the client (receiver) code will need send PUBACK.
If there is issue here and it is not sent for any reason for QoS=1, then MQTT broker will have to retry.

Is this the way the edge hub is working? 

I tried to verify that in a simple setting...

I have a source module sending 100 messages, and a corresponding sink module receiving the messages - both a just newly created C Modules in VSCode with latest templates and SDK's with slightest modifications to create a showcase for this issue.

There is only one route just connecting the two modules

https://github.com/alaendle/showcase-edge-transaction/blob/c082f9939ef4cdb831fc42474690f470e88847d1/deployment.template.json#L92

Unfortunately the event sink crashes on telegram "50" (since I've learned that the return value isn't used from the InputMessageCallback I kill the complete process)

https://github.com/alaendle/showcase-edge-transaction/blob/c082f9939ef4cdb831fc42474690f470e88847d1/modules/Sink/main.c#L54-L57

For sure the module recovers and receives the other telegrams - but I never see telegram "50" again - so it seems to got lost during the crash.

I wonder how this could be the case if QoS=1 is the default and if I got the code you've pointed right, the PUBACK should not have been send, before the module crashed.

My expectation would be that telegram "50" gets redelivered - at least after some time; since it should never have been acknowledged.

Or in other words; I still wonder if it is possible to write a C module that receives data from the edge with AT-LEAST-ONCE semantic.

**Comment by anhashia** [comment]
@alaendle 
For MQTT protocol, disposition code is stubbed out. So you cannot control the rejection via API call as you are doing in your code.

Even if you send IOTHUBMESSAGE_REJECTED with MQTT , it will have no effect as message will already be processed. 

MQTT (QoS=1) is controlled at MQTT level in **umqtt** library . By the time you get callback in application MQTT PUBACK will already be published by umqtt library.

**Comment by alaendle** [comment]
O.k., so to summarize you simple make out that **umqtt** auto commits each incoming message and so the iot C edge module has absolutely no control over it.

However the C# SDK behaves differently - even if MQTT is used - so if an exception or crash happens during the callback the message gets redelivered.

https://github.com/alaendle/showcase-edge-transaction/blob/428c8c8b352a9e95525ac4d52762df0eeb43b51b/modules/SharpSink/Program.cs#L76-L78

In my view, it is essential to be able to work in a transaction-safe manner for any serious application. I wonder why this is not recognized as a bug, or at least a legitimate feature request for the C SDK.

**Comment by anhashia** [comment]
Hi @alaendle 

C# IoT SDK has API at application level

``
await _deviceClient.CompleteAsync(receivedMessage).ConfigureAwait(false);
``

If this is **not** called by application then message won't be marked for delivery. So retry would happen on reconnect from MQTT broker side on **not** using clean session. This is per MQTT spec and is similar to C SDK. Only difference being that in IoT C SDK, the API is not directly available and happens under the hood by **umqtt**

If you are seeing some difference in behavior when used in context of **modules**, then that needs investigation. For example, if iotedge module (MQTT broker in your case) doesn't get an PUBACK , then it should retry on reconnect as per MQTT on clean session=0.  It shouldn't matter whether module is on C# SDK or C SDK as this controlled by MQTT spec for QoS=1.

I don't know if you simulation is exactly mimicking this behavior (not sending PUBACK) for module written C SDK.

**Comment by alaendle** [comment]
Hi @anhashia 

I think we are getting close to a common point of view. The different behaviour between the C and the C# sample seems to be caused by the send or missed PUBACK message. However, and that is my main complaint, with the C SDK the module has no chance to control the PUBACK. As far as I could understand the code the following happens.

1. UMQTT receives a PUBLISH and raises it message received handler
2. The handler inside the C SDK just registers the received message for further processes (queues the module callback for async execution)
3. From UMQTT perspective the handler was executed (without any problem (exception, etc.)) and therefore acknowledges the message to the edge
4. The handler of the module is called (while the queued callbacks are processed)

However, if you assume a crash between step 3 and 4 it might happen that - from the perspective of a client of the C sdk - a message never reaches a software module. So it seems that at least with the current implementation it's not possible to have AT-LEAST-ONCE semantic with the C sdk.

**Comment by anhashia** [comment]
Hi @alaendle 
Application level control using IoT C SDK is currently only with **AMQP** protocol. But right now it doesn't look like AMQP support is there for writing custom edge modules using IoT C SDK.

**Comment by alaendle** [comment]
Hi @anhashia,
maybe this sums it up...
> If you are seeing some difference in behavior when used in context of **modules**, then that needs investigation.

And that is exactly the case - the C module behavior differs from the C# module in the case that module crashes before/during the module message handler. Note that both implementations use MQTT fror transport.

```cpp
static IOTHUBMESSAGE_DISPOSITION_RESULT InputQueue1Callback(IOTHUB_MESSAGE_HANDLE message, void* userContextCallback)
{
    unsigned const char* messageBody;
    size_t contentSize;

    if (IoTHubMessage_GetByteArray(message, &messageBody, &contentSize) == IOTHUB_MESSAGE_OK)
    {
        messageBody = bytearray_to_str(messageBody, contentSize);
    } else
    {
        messageBody = "<null>";
    }

    // simulate crashes - never accept message "50"
    if(strcmp("50", messageBody) == 0) {
        exit(99);
    }

    printf("Received Data: [%s]\r\n", messageBody);


    messagesReceivedByInput1Queue++;
    return IOTHUBMESSAGE_ACCEPTED;
}
```

```csharp
        static async Task<MessageResponse> PipeMessage(Message message, object userContext)
        {
            int counterValue = Interlocked.Increment(ref counter);

            var moduleClient = userContext as ModuleClient;
            if (moduleClient == null)
            {
                throw new InvalidOperationException("UserContext doesn't contain " + "expected values");
            }

            byte[] messageBytes = message.GetBytes();
            string messageString = Encoding.UTF8.GetString(messageBytes);
            Console.WriteLine($"Received message: {counterValue}, Body: [{messageString}]");

            if ("50".Equals(messageString))
            {
                Environment.Exit(99);
            }
            return MessageResponse.Completed;
        }
```
The C# module receives message "50" after it restarts; while the C module never sees message "50" again.

And this because the C# SDK acknowledges the message after the module callback, while - as already explained in https://github.com/Azure/iotedge/issues/2089#issuecomment-580770221 the C SDK does that in advance.

Don't get me wrong I'm not expecting some kind of NACK for MQTT; but as written before I think that a module could expect to see a message (read: module handler is raised under ALL circumstances) send with QoS=1 at-least-once. So I still consider the missing guarantee to be a bug in the C SDK.

Please note that the complete code to reproduce the different hehavior can be found at https://github.com/alaendle/showcase-edge-transaction.

**Comment by anhashia** [comment]
+ @jspaith

**Comment by jspaith** [comment]
@anhashia & @alaendle - thanks A TON for your detailed analysis here.  You are correct, the C SDK does indeed send the PUBACK *before* it invokes the callback.  I actually think though there's a change your app can make  @alaendle to get what you want.  Lots of details...

In mqtt_client.c in [umqtt](https://github.com/Azure/azure-umqtt-c/), the relevant bit of `ProcessPublishMessage` which processes the C2D request.

```c
    mqtt_client->fnMessageRecv(msgHandle, mqtt_client->ctx); // This is where callback is invoked, and not return code isn't checked
	...
    else if (qosValue == DELIVER_AT_LEAST_ONCE)
    {
        pubRel = mqtt_codec_publishAck(packetId);
```

Since you're quite curious, way more details...  The next bit gets into the fact that the C SDK has two different threading models.
*  If you're using IoT C SDK's with \_LL\_ prefix is for lower layer.  This means that your app owns locking and only runs on one thread.  That `fnMessageRecv` call above is going to shoot directly to your callback.
*  If you're not using IoT C SDK's with \_LL\_ prefix is for convenience layer.  This means we'll help you out with threading more and in particular your callback will be invoked on a thread that the SDK spins up for you.  (In particular you'll be called on `dispatch_user_callbacks` from inside SDK.)

Interestingly  @alaendle, I think that if you were using the \_LL\_ API set then you'd actually get what you want.  If your app crashes in `fnMessageRecv` (which works its way up to the `InputQueue1Callback`, e.g.) then the SDK won't get a chance to call its puback.

On the convenience layer though it's different.  The dispatcher thread runs async, and the pubAck in `ProcessPublishMessage` *will* get called before you get a chance to run (there's locks enforcing this).

The behavior of C# SDK probably is desirable for C, too.  You can open an issue on this @alaendle at https://github.com/Azure/azure-iot-sdk-c.  (Even though this isn't the umqtt repo, the IOT-C-SDK repo would have to change to enable this, too.)  I'll just be honest though and say it's almost certain we'll never fix this.  So you can link back to this issue but I wouldn't spend too much time on bug report.

Fixing this would require:
* Us to plumb up from umqtt the DoPuback() to the IoT SDK itself and IoT SDK to call it
* Understand locking implications of this from convenience layer, where we guarantee thread safety.
* Doing this on existing function would break back-compat with existing apps that are returning `IOTHUBMESSAGE_REJECTED` or `IOTHUBMESSAGE_ABANDONED` but still getting PUBACK.  So now we're off into Ex() functions to enable this.

As I said though, I'm almost positive (short of stepping through code) for your crash scenario if you move the the lower-layer then you'd get what you want.   Code crashing=>no PUBACK.  If you do this , do NOT just blindly add IoTHub_Foo to IoTHub_LL_Foo.  I recently wrote a [doc](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/threading_notes.md) explaining more fundamental issues between these.

**Comment by alaendle** [comment]
@jspaith Thanks for your detailed and constructive feedback. However my example (https://github.com/alaendle/showcase-edge-transaction/blob/master/modules/Sink/main.c) already uses the lower layer - and the behaviour is that the message is lost. My interpretation is that even more for a single threaded app the fact is true that the module callback isn't raised directly; that's what [ll_dowork](https://docs.microsoft.com/en-us/azure/iot-hub/iot-c-sdk-ref/iothub-client-ll-h/iothubclient-ll-dowork) is for? At least this is my assumption, I haven't read the code.

I also understand the fixing this problem might be a breaking change you like to avoid. But I think at least theoretically there is a chance that the acknowledgement just happens as a continuation of the callback - and this could be handled entirely by the edge SDK (for sure umqtt has to provide the possibility); so from client perspective there shouldn't be any change in the API nor in the behaviour (o.k. the only change is that if the module crashes in its callback the continuation would never run and therefore the message would not be acknowledged - but that's the goal).

**Comment by varunpuranik** [comment]
This issue is related to the C SDK, and not to IoT Edge as such. So I will close this issue. As @jspaith suggested, please open an issue on the C SDK repo for further discussions on this.

**Comment by jspaith** [comment]
@alaendle - this is interesting then.  The DoWork() basically acts as the message pump for the system.  So if you do an IoTHub_LL_SendEvent() or whatever it is, we don't send the data right away.  Instead its queued up.  The LL_DoWork() causes the message to be processed.  LL_Dowork also causes network recv() to be called, any book-keeping if needed like MQTT PING, etc.

In your case is that if your app crashes during the callback in LL, the PUBACK from the device should not be sent.  (Note that you do NOT need to call LL_Dowork() for the PUBACK to be sent, you're already in a dowork call in `ProcessPublishMessage` so it just immediately sends.  See call stack below.)

Now clearly there's no way for your app to say "please don't PUBACK" this, but for crashing case and message being lost would be interesting to have a log to see if PUBACK being sent or if something else is up?

Call stack below to show that the send happens after callback, which it does.

```c
00 WS2_32!send
01 iothub_convenience_sample!socketio_send
02 iothub_convenience_sample!xio_send
03 iothub_convenience_sample!send_chunk
04 iothub_convenience_sample!internal_send
05 iothub_convenience_sample!tlsio_schannel_send
06 iothub_convenience_sample!xio_send
07 iothub_convenience_sample!sendPacketItem
08 iothub_convenience_sample!ProcessPublishMessage
09 iothub_convenience_sample!recvCompleteCallback
0a iothub_convenience_sample!completePacketData
0b iothub_convenience_sample!mqtt_codec_bytesReceived
0c iothub_convenience_sample!onBytesReceived
0d iothub_convenience_sample!on_underlying_io_bytes_received
0e iothub_convenience_sample!socketio_dowork
0f iothub_convenience_sample!xio_dowork
10 iothub_convenience_sample!tlsio_schannel_dowork
11 iothub_convenience_sample!xio_dowork
12 iothub_convenience_sample!mqtt_client_dowork
13 iothub_convenience_sample!IoTHubTransport_MQTT_Common_DoWork
14 iothub_convenience_sample!IoTHubTransportMqtt_DoWork
15 iothub_convenience_sample!IoTHubClientCore_LL_DoWork
16 iothub_convenience_sample!ScheduleWork_Thread
```

**Comment by alaendle** [comment]
Thank you for the support and commitment. Since this issue is already way too long, I will follow the suggestion and create a new issue for the C SDK. Maybe this is also a chance to focus on the actual problem again.
