### ISSUE TITLE
Iot Edge Hub Error - Transparent Gateway - Unable to connect iot device

### ISSUE THREAD

**Issue by waltmatthews** [Azure/iotedge#209]
I have had a transparent gateway running on Windows and Linux fine until sometime after last Friday.  
This week, I started having issues with a transparent gateway. I've rebuilt the Windows 10 PC from scratch and followed the below instructions.    This issue is happening on both Windows and Linux gateways which were working just fine before.  

Instructions I followed for the rebuilt Windows PC:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-windows

The IoT Edge Agent and Hub appear to be running fine in the Docker container.  I'm running the containers in Linux mode; however, I've also had the issue using Windows.  I've self-signed test certificates following the instructions and have the root-ca cert installed on the IoT Device PC.  The IoT Device PC connects just fine when going direct to the IoT Hub.   When I include the gateway, it fails with the message:  "Exception: The remote certificate is invalid according to the validation procedure."

In the IoT edgeHub logs, I'm seeing the below error.   Please provide any guidance as to what this would be caused by.   Thanks.

2018-08-24 19:25:21.359 +00:00 [INF] - Connection id ""0HLG9UTAIRIMF"" request processing ended abnormally.
System.IO.IOException: The decryption operation failed, see inner exception. ---> Interop+OpenSsl+SslException: Decrypt failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.Decrypt(SafeSslHandle context, Byte[] outBuffer, Int32 offset, Int32 count, SslErrorCode& errorCode)
   at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.AdaptedPipeline.ReadInputAsync(Stream stream)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

**Comment by varunpuranik** [comment]
Hi @waltmatthews, what is happening in your scenario is that the CA certificate from which the Edge device certificate was created, has not been correctly installed on the leaf device machine. So the leaf device is not able to validate the certificate that the server (EdgeHub) is presenting. 
It works when you connect to IoTHub, because IoTHub has a well-known CA cert, so the leaf device is able to validate it.
So I would look at installing the CA cert on the leaf device as described here - https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-windows#installation-on-the-downstream-device

Also, the EdgeHub error seems to be coming from the Http stack, which is currently only used for method invocations. Are you invoking methods from your leaf device?

**Comment by waltmatthews** [comment]
One other note, when I test using the statement:  openssl s_client -connect [my gateway]:8883 -CAfile [my root ca with path] -showcerts works correctly (responds with OK message).

**Comment by waltmatthews** [comment]
Closing .  Issue was connection string [my gateway] was using IP, not host name.

**Comment by Mdukes00** [comment]
when i change my host name to the dns name i get this error

PS C:\Users\azureuser\Desktop\cert> iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname mytestvmwind.westeurope.cloudapp.azure.com but device reports hostname EdgeWindowsVM.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has
 the device hostname as the first component.
