### ISSUE TITLE
Module status is N/A on Azure IoT Hub Portal

### ISSUE THREAD

**Issue by blackchoey** [Azure/iotedge#2146]
Open this issue on behalf of @smoms. Here's the words from smoms:
> in the Azure IoT Hub Portal i can see the 2 modules tempSensor and filtermodule but all column status are N/A. And in fact if i click "Set Module" the page is empty. Why is that? thanks

@smos, please help provide more details here if you still have this issue. Thanks.

**Comment by dmolokanov** [comment]
Hi @blackchoey! Thanks for opening the issue. It is really hard to reason about this behavior without information about edge runtime and logs.

@smos Could you please add this information to the issue. We have a template for it. Feel free to create a new issue if required.

**Comment by smoms** [comment]
sorry this issue was ages ago. I do not remember anymore. pls be more reactive if you want community to help.

**Comment by dmolokanov** [comment]
Closing this issue as no immediate action required. Feel free to open an issue if you will have an update or any other issues in the future with iotedge in the future. Thanks!
