### ISSUE TITLE
Invoking DM on Leaf Device from module fails with System.Net.Http.CurlException:

### ISSUE THREAD

**Issue by stevebus** [Azure/iotedge#218]
with IoT Edge set as a transparent gateway, invoking a Direct Method on the leaf device from a module fails with the exception shown in the logs

## Expected Behavior
Expect Direct Method to be successfully invoked on the leaf device

## Current Behavior

When the Direct Method is involved on the leaf device from the module, it throws the below exception which are captured in it's logs..   no seemingly related errors are captured in the edgeHub logs in the same timeframe

Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<ExecuteAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.<PostAsync>d__17`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Client.ModuleClient.<InvokeMethodAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at alertmodule.Program.<PipeMessage>d__4.MoveNext() in /app/Program.cs:line 101
R

## Steps to Reproduce

1. setup IoT Edge as a transparent gateway per the documentation
2.  connect an IoT leaf device - in my case, I'm using [this](https://github.com/AzureIoTGBB/azure-iot-edge-hol-linux/tree/master/module2/dotnet/readserial_nodevice) C# / AMQP client as a leaf device (after changing the device client version to 1.18.0 in csproj, changing protocol to AMQP, and updating the connstr
3.  create a module that invokes a DM on the leaf client..  I'm using this code:
      var result = await moduleClient.InvokeMethodAsync("iotTestDev01", new MethodRequest(command));

(where command is a string containing the value "ON", which is the name of my DM, and iotTestDev01 is the name of my leaf device)

## Context (Environment)

Same environment as issue [203](https://github.com/Azure/iotedge/issues/203)

(angelod) Copying environment: 
Ubuntu 18.04 VM in Azure
i've tried my "leaf" device as both a python script and a dotnet core app, same results
python device was created today with a fresh manual build of the python sdk
C# leaf device was created today with 1.18.0 version of the device client.

Device (Host) Operating System
Ubuntu 18.04

Architecture
amd64

Container Operating System
Linux

Runtime Versions
latest (installed today)

iotedged
iotedge 1.0.1 (6e5e86d)

Edge Agent
1.0

Edge Hub
1.0

Docker
(installed yesterday from the MS provided moby install)

Client:
Version: 18.06.0-dev
API version: 1.37
Go version: go1.10.2
Git commit: daf021fe
Built: Mon Jun 25 21:07:53 2018
OS/Arch: linux/amd64
Experimental: false
Orchestrator: swarm

Server:
Engine:
Version: dev
API version: 1.37 (minimum version 1.12)
Go version: go1.10.2
Git commit: 9aac187
Built: Mon Jun 25 20:43:05 2018
OS/Arch: linux/amd64
Experimental: false

**Comment by andrepodnozov** [comment]
I'm also seeing this on a Windows Edge host (Docker configured for Linux containers).

**Comment by Mangu** [comment]
A customer of mines is also seeing this issue. Worked fine last week.

**Comment by aribeironovaes** [comment]
Hi @stevebus , @Mangu , @andrepodnozov , 

Sorry for the delay! It took some time to investigate, but we found the issue and a workaround. 

This is probably happening if you created your module using our VSTS Template. 
The base image of that template has some problems to validate the certificate on InvokeMethod. 
While we will follow up with the .NET Team, can you please change your Docker File to be based on otnet:2.1.2-runtime-alpine3.7? 

Here is how your new docker file (Dockerfile.amd64 on your module folder): 

FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
COPY nuget.config ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1.2-runtime-alpine3.7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN adduser -Ds /bin/sh moduleuser 
USER moduleuser

ENTRYPOINT ["dotnet", "DMSampleModule.dll"] <== Your module name here. 

Redeploy your module (Make sure you bump version or delete old container). 

Let me know if you have any problems. 

Thanks for waiting! 

Angelo Ribeiro.

**Comment by shizn** [comment]
We will update the default project template. https://github.com/Microsoft/vscode-azure-iot-edge/issues/240

**Comment by stevebus** [comment]
to circle back..   tested with @aribeironovaes Dockerfile above.   After removing the line "COPY nuget.config ./", which for debugging pointed nuget to myget (don't need this for production), the image built fine and my DM call from my module to my leaf devices works fine!

**Comment by aribeironovaes** [comment]
Another update, After some tests, I realize that we don't need to switch to alpine (Just do it if you want). You can just change the .net images (both SDK and runtime) to 2.1. 

HOpe this helps! Let me know if I can close this issue. 

Thanks, 

Angelo Ribeiro.

**Comment by andrepodnozov** [comment]
I confirm that after changing "dotnet:2.0" to "dotnet:2.1" for both sdk and runtime I can now invoke  DirectMethods.

**Comment by aribeironovaes** [comment]
Thanks a lot for confirming Andre. Closing this issue here.
