### ISSUE TITLE
IoT Edge device configuration proxy do not work

### ISSUE THREAD

**Issue by Nick287** [Azure/iotedge#2181]
HI, 
Here's my question about proxy. I have setup a windows server as an edge host device (Host OS Windows server 2019 - 1809), but the device is in on-premises environment and this device can access the public network ONLY through the Proxy.
firewall blocks most ports (etc. 8883 5671 blocked but 443 available) so i just follow this guide setup iotedge proxy [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support]()

The configuration script like this (proxy server no need username and password)：
- . {Invoke-WebRequest -proxy http://137.55.147.123:10123 -useb aka.ms/iotedge-win} | Invoke-Expression; Deploy-IoTEdge -proxy http://137.55.147.123:10123

- . {Invoke-WebRequest -proxy http://137.55.147.123:10123 -useb aka.ms/iotedge-win} | Invoke-Expression; Initialize-IoTEdge

- [Environment]::SetEnvironmentVariable("HTTP_PROXY", "http://137.55.147.123:10123", [EnvironmentVariableTarget]::Machine)

- reg add HKLM\SYSTEM\CurrentControlSet\Services\iotedge /v Environment /t REG_MULTI_SZ /d https_proxy=http://137.55.147.123:10123

- C:\ProgramData\iotedge\config.yaml
agent:
  name: "edgeAgent"
  type: "docker"
  evn:
    https_proxy: "http://137.55.147.123:10123"
    UpstreamProtocol: "AmqpWs"
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0.8"
    auth: {}

but seems this proxy configuration doesn't work at all... and powershell command "Invoke-WebRequest -proxy http://137.55.147.123:10123" perfect functioning.

I get "iot edge check" log list here:
--------------------

PS C:\Windows\system32> iotedge check
Configuration checks

√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
‼ config.yaml has correct hostname - Warning
    config.yaml has hostname WIN-9U7UH7898HI which does not comply with RFC 1035.

    - Hostname must be between 1 and 255 octets inclusive.
    - Each label in the hostname (component separated by ".") must be between 1 and 63 octets inclusive.
    - Each label must start with an ASCII alphabet character (a-z), end with an ASCII alphanumeric character (a-z, 0-9), and must contain only ASCII alphanumeric characters or hyphens (a-z, 0-9, "-").

    Not complying with RFC 1035 may cause errors during the TLS handshake with modules and downstream devices.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect to bdbiothub.azure-devices.cn:5671
× host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - Error
    Could not connect to bdbiothub.azure-devices.cn:443
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect to bdbiothub.azure-devices.cn:8883
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the nat network could not connect to bdbiothub.azure-devices.cn:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the nat network could not connect to bdbiothub.azure-devices.cn:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the nat network could not connect to bdbiothub.azure-devices.cn:8883
× Edge Hub can bind to ports on host - Error
    Could not check current state of Edge Hub container

8 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
7 check(s) raised errors. Re-run with --verbose for more details.

**Comment by Nick287** [comment]
My configuration problem...

**Comment by omarine** [comment]
Hello,

i am having the same issue,what configuration problem you had ?

**Comment by anilchoudhury** [comment]
I think the problem may be with DNS.
Check the content of '/etc/docker/daemon.json' file as this defines the DNS servers.

To get the DNS server for your device, run the following command:
```
~ $ nslookup -type=any google.com
Server: 192.168.7.1
Address: 192.168.7.1:53
Non-authoritative answer:
Name: google.com
Address: 142.250.191.206
google.com nameserver = ns1.google.com
google.com nameserver = ns4.google.com
google.com nameserver = ns2.google.com
google.com nameserver = ns3.google.com
```

DNS Server: 192.168.7.1
Update the file with DNS settings. 

Also ensure that you have set proxy settings for docker and iotedge in following paths:
```
~ $ cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTPS_PROXY=<proxy address:port>
Environment="HTTP_PROXY=<proxy address:port>
Environment="NO_PROXY=localhost,127.0.0.1"

~ $ cat /etc/systemd/system/iotedge.service.d/http-proxy.conf
[Service]
Environment="HTTPS_PROXY=http://proxy.etn.com:8080"
Environment="HTTP_PROXY=http://proxy.etn.com:8080"
Environment="NO_PROXY=localhost,127.0.0.1"
```

In 'Edge Agent module spec' section of '/etc/iotedge/config.yaml' file:
```
agent:
  name: "edgeAgent"
  type: "docker"
  env:
    https_proxy: "http://proxy.corp.com:8080"
    http_proxy: "http://proxy.corp.com:8080"
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.1"
    auth: {}
```

Later restart all services:
~$ sudo systemctl daemon-reload
~$ sudo systemctl restart docker

check docker running status:
~ $ sudo journalctl -u docker | tail

~$ sudo systemctl restart iotedge

Check iotedge running status:
~ $ sudo journalctl -u iotedge | tail

You can also check iotedge status but its less importance as I am getting 12 errors, still i am able to access IotEdge and able to deploy containers from cloud:
~ $ sudo iotedge check 2>&1 | tee /tmp/iotedge-check.log
