### ISSUE TITLE
Verify messages sent from Edge to Cloud

### ISSUE THREAD

**Issue by PWSys** [Azure/iotedge#2216]
Regarding communication between IoTEdge and IoTHub, is it possible to programmatically verify messages are successfully received by IoT Hub?   Maybe an edge function can cache the messages locally until it is verified.  I understand that in the event of lost connectivity IoTEdge will cache messages, but it would be nice to know at the Edge if messages are not making their way to the cloud.

The use case is that embedded systems cache data until they receive a verification that the information has been consumed.  This is important for event-based data.

**Comment by philipktlin** [comment]
To verify event messages successfully received in IoT Hub, you can pull event messages from IoT Hub's built-in event hub endpoints.  Please read https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin.

Recently we started to implement a test named connectivity test; which is used to test IoT Edge features working under different conditions, e.g. online and offline.  You can take a look at it from https://github.com/Azure/iotedge/tree/master/test/connectivity.

**Comment by PWSys** [comment]
Thanks for the info.  It does not look like there is a way to query for a specific message.  If I am understanding this correctly, an Edge Function would have to stream all messages from the IoTHub looking for the specific item.  This seems expensive.  I guess alternatively this could be done on the Cloud with a C2D message.  It would be nice even if the EdgeHub could provide verification a message was written.

The tests look great!  It would be great to alert modules at the edge if the EdgeHub lost connectivity.
