### ISSUE TITLE
Leaf device failed with  mqtt_client timed out waiting for CONNACK

### ISSUE THREAD

**Issue by arnabhetc** [Azure/iotedge#2244]
## Expected Behavior
Using leafDevice with X509 downstream device authentication [ [python SDK](https://github.com/Azure/azure-iot-sdk-python/tree/v1-deprecated) ], so the expected scenario is 
receiving data to Edge modules.

# Current Behavior
Due to some unknown scenario, the  leaf device is failing with below error 
`Error: Time:Mon Jan  6 12:16:36 2020 File:/home/user/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2230 mqtt_client timed out waiting for CONNACK
Error: Time:Mon Jan  6 12:16:36 2020 File:/home/user/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2230 mqtt_client timed out waiting for CONNACK
Error: Time:Mon Jan  6 12:16:36 2020 File:/home/user/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2230 mqtt_client timed out waiting for CONNACK
Error: Time:Mon Jan  6 12:16:36 2020 File:/home/user/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2230 mqtt_client timed out waiting for CONNACK
Error: Time:Mon Jan  6 12:16:36 2020 File:/home/user/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2230 mqtt_client timed out waiting for CONNACK`

At the same time, the custom module where we are receiving this data is having this error 

`Unhandled Exception: System.TimeoutException: The operation timed out. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   at parsermodule.Program.PublishMessage(Object userContext, Object dataPayload, String packetType) in /app/Program.cs:line 1011
   at parsermodule.Program.HeartbeatTask(Object userContext, Object userContext1) in /app/Program.cs:line 1041
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
`

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Running the Leaf device python code 
2.  After running sometimes the error can be noticed in lead device logs 

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname edgegateway.local but device reports hostname user-desktop.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

20 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS :  Ubuntu 16.04
* Architecture : amd64 
* Container OS : Linux containers 

### Runtime Versions
* iotedged :  iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)
* Edge Agent : mcr.microsoft.com/azureiotedge-agent:1.0.8.4
* Edge Hub : mcr.microsoft.com/azureiotedge-hub:1.0.8.4
* Docker/Moby : 3.0.8

## Logs

EdgeAgent logs --> 

[edgeAgentlogs.txt](https://github.com/Azure/iotedge/files/4025109/edgeAgentlogs.txt)

EdgeHub Logs --> 

[edgeHublogs.txt](https://github.com/Azure/iotedge/files/4025114/edgeHublogs.txt)

Custom module -->
[parsermodulefull.txt](https://github.com/Azure/iotedge/files/4025127/parsermodulefull.txt)

iotedge logs  --> 
[journalctl.txt](https://github.com/Azure/iotedge/files/4025130/journalctl.txt)

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by philipktlin** [comment]
1. Would you please provide details what are you doing? sending messages from cloud to leaf device and to "parsemodule" module?
2. The log date range of edgeAgent and edgeHub is more than 1 month and it doesn't turn on for debug level.  Please set runtime log level to debug (https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot) and restart iotedge; run your scenario again and capture the log.

**Comment by arnabhetc** [comment]
So from the leaf device, I am sending data to parsermodule and in parser module that data is being processed and sent to IoTHub, I am using X509 certificate-based authentication for the downstream device. This gateways are running in production so its not possible to trun on the debug currently.

**Comment by veyalla** [comment]
Hi @arnabhetc, the V1 Python SDK is deprecated and we can no longer get support that SDK. Is it possible to be migrate to the V2 SDK which is not GA?

**Comment by philipktlin** [comment]
Closed since it is marked as stale.
