### ISSUE TITLE
Leaf device behind transparent Iot Edge gateway sends twin-change-notifications as telemetry, resulting in increased unexpected message volume

### ISSUE THREAD

**Issue by wickste** [Azure/iotedge#2251]
## Expected Behavior
Leaf device behind IoT Edge gateway should behave exactly the same way as a device connected to IoTHub directly.

## Current Behavior
Comparing the same device with and without IoT Edge gateway I see an increased message volume in IoTHub. Specifically, for every call to UpdateReportedProperties, I get an extra, unexpected telemetry event. This does not happen when the same device is connected to IoTHub directly.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Follow official instructions to set up transparent gateway: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway
2. Follow official instructions to connect a downstream device: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device
3. Use the below code in your device implementation
4. Use "az iot hub monitor-events -n <iothubname> --properties all" to monitor events

## Device Client Code
```
while (true)
{
    // report properties
    reportedProperties = new TwinCollection();
    reportedProperties["Summary"] = summary;
    reportedProperties["Details"] = details;
    await deviceClient.UpdateReportedPropertiesAsync(reportedProperties);

    // report  telemetry
    var telemetryDataPoint = new
    {
        Temperature = temperature,
        Humidity = humidity,
        Pressure = pressure,
    };


    var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
    var message = new Message(Encoding.UTF8.GetBytes(messageString));
    message.ContentEncoding = "utf-8";
    message.ContentType = "application/json";

    await deviceClient.SendEventAsync(message);
    await Task.Delay(telemetryInterval);
}
```

### Output of `az iot hub monitor-events`
The above code will result in two telemetry events for each iteration of the while (the first of the two is unexpected). This is twice the amount of messages compared to the same device connected to IoTHub directly. Here is the output showing the extra telemetry message:

````
{
    "event": {
        "origin": "MyLeafDevice",
        "payload": "{\"Summary\":\"Rain\",\"Details\":\"light rain\",
        "annotations": {
            "iothub-connection-device-id": "MyLeafDevice",
            "iothub-connection-auth-method": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
            "iothub-connection-auth-generation-id": "637138886134044133",
            "iothub-enqueuedtime": 1578334839823,
            "iothub-message-source": "Telemetry",
            "x-opt-sequence-number": 21156,
            "x-opt-offset": "13315904",
            "x-opt-enqueued-time": 1578334839811
        },
        "properties": {
            "system": {},
            "application": {
                "iothub-message-schema": "twinChangeNotification"
            }
        }
    }
}
{
    "event": {
        "origin": "MyLeafDevice",
        "payload": {
            "Temperature": 8.681319,
            "Humidity": 56,
            "Pressure": 1023.3226
            }
        },
        "annotations": {
            "iothub-connection-device-id": "MyLeafDevice",
            "iothub-connection-auth-method": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
            "iothub-connection-auth-generation-id": "637138886134044133",
            "iothub-enqueuedtime": 1578334839855,
            "iothub-message-source": "Telemetry",
            "x-opt-sequence-number": 21157,
            "x-opt-offset": "13316448",
            "x-opt-enqueued-time": 1578334839858
        },
        "properties": {
            "system": {
                "content_encoding": "utf-8",
                "content_type": "application/json"
            }
        }
    }
}
````

### Device Information
* Ubuntu 18.04
* amd64
* Linux containers

### Runtime Versions
* iotedged: iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0) 
* Edge Agent: mcr.microsoft.com/azureiotedge-agent:1.0 
* Edge Hub: mcr.microsoft.com/azureiotedge-hub:1.0 
* Docker/Moby: 3.0.8

**Comment by ancaantochi** [comment]
Hi @wickste,
- Does the reported get updated or it is just sent as telemetry instead?
- What protocol are you using and which sdk version?

Can you please provide edgeHub debug logs? Here are the details about how to turn on debug logs: 
https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#check-container-logs-for-issues

**Comment by wickste** [comment]
Hi @ancaantochi ,
- the reported property does get updated
- I tried MQTT and AMQP, it repos with both
- I am using C# SDK v1.21.3

Nothing suspicious in the edgeHub logs, just info messages like this:
<6> 2020-01-07 06:14:24.656 +00:00 [INF] - Updated reported properties for MyDevice_dotnet_1.21.3.0_MQTT
<6> 2020-01-07 06:14:24.798 +00:00 [INF] - Updated reported properties for MyDevice_dotnet_1.21.3.0_AMQP
<

**Comment by ancaantochi** [comment]
@wickste, 
Can you please check the routes, do you have any route that contains: FROM /twinChangeNotifications?

**Comment by wickste** [comment]
@ancaantochi No, my only route is this. I was following the tutorial to the letter:

````
FROM /* INTO $upstream
````

**Comment by ancaantochi** [comment]
This route includes reported properties update to be send as telemetry to upstream.
Please update the routes to: FROM /messages/* INTO $upstream and let me know if that works.

Here is routes documentation: https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#declare-routes

**Comment by ancaantochi** [comment]
Documentation was updated so the default route sample is /messages/* instead of /*
By design, if the route is set with /* it sends a telemetry messages for each desired property update.
