### ISSUE TITLE
Enable Azure IoT Edge Failed on Raspberry pi 2  of ubuntu mate 16.04/18.04

### ISSUE THREAD

**Issue by onlinepy** [Azure/iotedge#2257]
I followed the tutorial steps to install it: https://docs.microsoft.com/en-us/Azure/iot-edge/how-to-install-iot-edge-linux,  
i configuration the file : sudo nano /etc/iotedge/config.yaml  and restart the daemon: sudo systemctl restart iotedge 
and then check the status of the IoT Edge Daemon:  systemctl status iotedge
logs : 
Process: 27382 ExecStart= /usr/bin/iotedged  -c /etc/iotedge/config.yaml (code=exited, status=127)
Main PID: 27382 (code= exited, status= 127)
systemd[1]: iotedge.service:  Unit entered failed state.
systemd[1]: iotedge.service:  Failed with result 'exit-code'.
systemd[1]: iotedge.service:  iotedge.service: Sercice hold-off time over, scheduling restart.
systemd[1]: Stopped Azure IoT Edge daemon.
systemd[1]: Dependency failed for Azure IoT Edge daemon.
systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.

**Comment by ancaantochi** [comment]
Can you please check if there are more details in the edge daemon logs:

`sudo journalctl -u iotedge --no-pager --no-full`

**Comment by arsing** [comment]
If you still have the problem, please open a new issue, and make sure to fill out the issue template instead of deleting it.
