### ISSUE TITLE
(1.0.9 rc3) mgmt/sock and workload/sock not created

### ISSUE THREAD

**Issue by AaronEdelman** [Azure/iotedge#2278]
## Expected Behavior
iotedge list & iotedge check return results

Would expect 
listen:
  management_uri: 'unix:///C:/Data/ProgramData/iotedge/mgmt/sock'
  workload_uri: 'unix:///C:/Data/ProgramData/iotedge/workload/sock'

files to exist

## Current Behavior
PS C:\Data\Users\Administrator\Documents> iotedge list
The term 'iotedge' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a.....

PS C:\Data\ProgramData\iotedge\mgmt> cd sock
cd : Cannot find path 'sock' because it does not exist.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Run Deploy-IotEdge
. {Invoke-WebRequest -useb https://raw.githubusercontent.com/Azure/iotedge/1.0.9-rc3/scripts/windows/setup/IotEdgeSecurityDaemon.ps1} | Invoke-Expression; Deploy-IoTEdge -ContainerOs Windows -OfflineInstallationPath C:/Data/Users/DefaultAccount/Documents
2. Run Initialize-IotEdge
. {Invoke-WebRequest -useb https://raw.githubusercontent.com/Azure/iotedge/1.0.9-rc3/scripts/windows/setup/IotEdgeSecurityDaemon.ps1} | Invoke-Expression; ` Initialize-IoTEdge -Dps -ScopeId xxxxxxxx -X509IdentityCertificate C:/Data/Users/DefaultAccount/Documents/cert.pem  -X509IdentityPrivateKey C:/Data/Users/DefaultAccount/Documents/key.pem"

Module comes in as expected.

### Output of `. {Invoke-WebRequest -useb https://raw.githubusercontent.com/Azure/iotedge/1.0.9-rc3/scripts/windows/setup/IotEdgeSecurityDaemon.ps1} | Invoke-Expression; Get-IoTEdgeLog`

TimeCreated         Message
-----------         -------
1/9/2020 7:13:49 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:13:49.777400600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:13:54 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:13:54.827070900 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:13:59 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:13:59.881546500 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:04 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:04.927840300 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:08 AM info: edgelet_core::watchdog -- Checking edge runtime status
1/9/2020 7:14:08 AM info: edgelet_core::watchdog -- Edge runtime is running.
1/9/2020 7:14:09 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:09.976466100 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:15 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:15.045427 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200
                    OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:20 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:20.089163500 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:25 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:25.139810700 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:30 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:30.181308 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200
                    OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:35 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:35.233844600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:40 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:40.293265200 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:45 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:45.338979900 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:50 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:50.409526200 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:14:55 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:14:55.469538300 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:00 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:00.522723700 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:05 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:05.571044200 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:08 AM info: edgelet_core::watchdog -- Checking edge runtime status
1/9/2020 7:15:08 AM info: edgelet_core::watchdog -- Edge runtime is running.
1/9/2020 7:15:10 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:10.606650700 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:15 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:15.657061700 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:20 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:20.714959100 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:25 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:25.762774300 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:30 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:30.821722600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:35 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:35.872391700 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:40 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:40.921352500 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:45 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:45.970639500 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:51 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:51.015289600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:15:56 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:15:56.058058 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200
                    OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:01 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:01.117698 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200
                    OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:06 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:06.158083800 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:08 AM info: edgelet_core::watchdog -- Checking edge runtime status
1/9/2020 7:16:08 AM info: edgelet_core::watchdog -- Edge runtime is running.
1/9/2020 7:16:11 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:11.195920600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:16 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:16.241373100 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:21 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:21.280045600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:26 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:26.323819600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:31 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:31.370416300 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:16:31 AM info: edgelet_http::logging -- [work] - - - [2020-01-09 15:16:31.385407200 UTC] "POST
                    /modules/%24edgeAgent/genid/637141786160727264/encrypt?api-version=2019-01-30 HTTP/1.1" 200 OK 1553 "-" "-" auth_id(-)
1/9/2020 7:16:31 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:31.710334 UTC] "GET /identities/?api-version=2019-01-30 HTTP/1.1"
                    200 OK 319 "-" "-" auth_id(-)
1/9/2020 7:16:31 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:16:31.746649400 UTC] "PUT
                    /identities/xxxxxxxxxxxxmodule?api-version=2019-01-30 HTTP/1.1" 200 OK 109 "-" "-" auth_id(-)
1/9/2020 7:16:31 AM info: edgelet_docker::runtime -- Pulling image xxxxxxxxxxxxxx.azurecr.io/xxxxxxxxxxxxxxxmodule:0.0.23-windows-amd64...
1/9/2020 7:17:08 AM info: edgelet_core::watchdog -- Checking edge runtime status
1/9/2020 7:17:08 AM info: edgelet_core::watchdog -- Edge runtime is running.
1/9/2020 7:17:55 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:17:55.768919500 UTC] "POST
                    /modules/xxxxxxxxxxxxxx/prepareupdate?api-version=2019-01-30 HTTP/1.1" 204 No Content - "-" "-" auth_id(-)
1/9/2020 7:17:55 AM info: edgelet_docker::runtime -- Stopping module xxxxxxxxxxxxmodule...
1/9/2020 7:17:57 AM info: edgelet_docker::runtime -- Successfully stopped module xxxxxxxxxxxmodule
1/9/2020 7:17:57 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:17:57.286823500 UTC] "POST
                    /modulesxxxxxxxxxxxxxxmodule/stop?api-version=2019-01-30 HTTP/1.1" 204 No Content - "-" "-" auth_id(-)
1/9/2020 7:17:57 AM info: edgelet_http_mgmt::server::module::update -- Updating module systemmanagermodule
1/9/2020 7:17:57 AM info: edgelet_docker::runtime -- Removing module xxxxxxxxxxxxxxxmodule...
1/9/2020 7:17:57 AM info: edgelet_docker::runtime -- Successfully removed module xxxxxxxxxxxxmodule
1/9/2020 7:17:57 AM info: edgelet_docker::runtime -- Pulling image xxxxxxxxxxxx.azurecr.io/xxxxxxxxxxxmodule:0.0.23-windows-amd64...
1/9/2020 7:17:57 AM info: edgelet_docker::runtime -- Successfully pulled image xxxxxxxxxxx.azurecr.io/xxxxxxxxxxxmodule:0.0.23-windows-amd64
1/9/2020 7:17:57 AM info: edgelet_docker::runtime -- Creating module xxxxxxxxxxxmodule...
                    /modules/xxxxxxxxxxxxmodule?api-version=2019-01-30 HTTP/1.1" 200 OK 1122 "-" "-" auth_id(-)
1/9/2020 7:17:57 AM info: edgelet_docker::runtime -- Starting module xxxxxxxxxxxxmodule...
1/9/2020 7:18:00 AM info: edgelet_docker::runtime -- Successfully started module xxxxxxxxxxxxmodule
1/9/2020 7:18:00 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:00.220374800 UTC] "POST
1/9/2020 7:18:05 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:05.444579400 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:08 AM info: edgelet_core::watchdog -- Checking edge runtime status
1/9/2020 7:18:08 AM info: edgelet_core::watchdog -- Edge runtime is running.
1/9/2020 7:18:10 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:10.620662900 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:15 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:15.676774200 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:20 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:20.719677600 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:25 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:25.768561100 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:30 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:30.810944900 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:35 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:35.868480400 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:40 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:40.911301400 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1"
                    200 OK 1353 "-" "-" auth_id(-)
1/9/2020 7:18:45 AM info: edgelet_http::logging -- [mgmt] - - - [2020-01-09 15:18:45.951648 UTC] "GET /modules?api-version=2019-01-30 HTTP/1.1" 200
                    OK 1353 "-" "-" auth_id(-)
<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by AaronEdelman** [comment]
It actually looks as though the socks do exist. So I'm no clear on why the iotedge commands wouldn't work.

Mode                LastWriteTime         Length Name
     ----                -------------         ------          ----
-a----         1/9/2020  10:50 AM              0 sock

**Comment by veyalla** [comment]
You might need to disconnect and reconnect (or logout and login) for the environment variables to update.

**Comment by AaronEdelman** [comment]
@veyalla thanks for he response. I'm not sure what disconnect/reconnect means in this regard. Turning the device on/off and stopping/starting iotedge through powershell do not fix the issue.

**Comment by arsing** [comment]
>### Device Information
>
>    * Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]:
>
>    * Architecture [e.g. amd64, arm32, arm64]:
>
>    * Container OS [e.g. Linux containers, Windows containers]:

You need to fill out the information we ask you in the issue template. It's there in the template for a reason.

>So I'm no clear on why the iotedge commands wouldn't work.

Define "wouldn't work". If you mean the same "not recognized as the name of a cmdlet, function, script file, or operable program" error as you have in the OP, then that has nothing to do with the `sock` directory existing. It's because `C:\Program Files\iotedge` is not in your shell's `PATH`.

The installer adds it there automatically, but the code is different depending on what kind of Windows it is, which is again why we ask you to fill out the issue template.

**Comment by TerryWarwick** [comment]
It is pretty clear that this is on an IOT Core device by the **C:\Data\Program Data** path originally referenced.  Please try the following commands and report your findings

- Run **iotedge list** from the **c:\program files\iotedge** folder. 
- Inspect your path variable to ensure that iotedge and iotedge-moby are in the path.
   **env$:path -split ";"**   

If **C:\Program Files\iotedge** and **C:\Program Files\iotedge-moby** are not in the path, please add them and try again from a directory other than C:\Program Files\iotedge.

**Comment by seanmcd-msft** [comment]
This should be fixed. but, the fixes weren't cherry-picked from master when rc3 got tagged.  Please retry with rc4 or newer.

thanks

**Comment by AaronEdelman** [comment]
@TerryWarwick Thanks for the instructions. 
- Running iotedge list from C:\Data\ProgramData\iotedge returns "The term 'iotedge' is not recognized..."
- Adding iotedge and iotedge-moby to the path returns the same result

@seanmcd-msft Thank-you I will try that.

**Comment by AaronEdelman** [comment]
Updated to 1.0.9-rc4.

I also noticed that my deployment specified "image": "mcr.microsoft.com/azureiotedge-agent:1.0", not "image": "mcr.microsoft.com/azureiotedge-agent:1.0.9-rc4" - which is what I think was causing the issue with iotedge list not working.

This can be closed.
