### ISSUE TITLE
[v2] http proxy support for iotedged

### ISSUE THREAD

**Issue by aribeironovaes** [Azure/iotedge#230]
Details Here: https://github.com/Azure/iot-edge-v1/issues/465

Original issue opened on v1 github, moved here. Original was about iotedgectl.

**Comment by aribeironovaes** [comment]
Work in Progress.

**Comment by myagley** [comment]
Proxy support was added in version 1.0.2 of the runtime. More information is here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support
