### ISSUE TITLE
iotedge daemon compile fail with aarch64-linux-android

### ISSUE THREAD

**Issue by pclesr** [Azure/iotedge#2311]
When compiling the daemon using the android toolchain, it fails in num_cpus v1.8.0

edgelet/build/linux/cross.sh --toolchain aarch64-linux-android --release true
    Updating crates.io index
  Downloaded libc v0.2.66
  Downloaded 1 crate (457.8 KB) in 0.80s
Unable to find image 'rustembedded/cross:aarch64-linux-android-0.1.16' locally
aarch64-linux-android-0.1.16: Pulling from rustembedded/cross
f7277927d38a: Pull complete
8d3eac894db4: Pull complete
edf72af6d627: Pull complete
3e4f86211d23: Pull complete
121a19e8f1af: Pull complete
57a71eb34794: Pull complete
4a910c5450fa: Pull complete
f32509d65cf5: Pull complete
81dedf77871d: Pull complete
2a7dc3d2751d: Pull complete
bc2071a8880a: Pull complete
4e16b5051e62: Pull complete
5a7876927582: Pull complete
da6cd7735dbf: Pull complete
c7b63d6e8c1f: Pull complete
a39956aa286b: Pull complete
Digest: sha256:fa8083730c15ccf1485a9c9998d47f5911bce3c07fec78d673f7909cb10e98bd
Status: Downloaded newer image for rustembedded/cross:aarch64-linux-android-0.1.16
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.66
   Compiling proc-macro2 v0.4.19
   Compiling spin v0.5.2
   Compiling byteorder v1.3.1
   Compiling unicode-xid v0.1.0
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.9
   Compiling either v1.5.3
   Compiling scopeguard v1.0.0
   Compiling cc v1.0.37
   Compiling lazycell v0.6.0
   Compiling version_check v0.1.3
   Compiling futures v0.1.29
   Compiling typenum v1.10.0
   Compiling autocfg v0.1.6
   Compiling slab v0.4.1
   Compiling pkg-config v0.3.11
   Compiling serde v1.0.92
   Compiling ryu v0.2.7
   Compiling matches v0.1.6
   Compiling failure_derive v0.1.2
   Compiling fnv v1.0.6
   Compiling syn v0.15.36
   Compiling linked-hash-map v0.5.1
   Compiling rustc-demangle v0.1.7
   Compiling openssl v0.10.12
   Compiling foreign-types-shared v0.1.1
   Compiling itoa v0.4.1
   Compiling void v1.0.2
   Compiling unicode-normalization v0.1.5
   Compiling byte-tools v0.2.0
   Compiling constant_time_eq v0.1.3
   Compiling percent-encoding v1.0.1
   Compiling ucd-util v0.1.1
   Compiling regex v0.2.11
   Compiling indexmap v1.0.1
   Compiling native-tls v0.2.1
   Compiling bitflags v1.0.3
   Compiling try-lock v0.2.2
   Compiling arrayref v0.3.4
   Compiling openssl-probe v0.1.2
   Compiling fake-simd v0.1.2
   Compiling utf8-ranges v1.0.0
   Compiling nix v0.14.1
   Compiling httparse v1.2.4
   Compiling safemem v0.2.0
   Compiling consistenttime v0.2.0
   Compiling dtoa v0.4.2
   Compiling hex v0.3.2
   Compiling rayon-core v1.6.0
   Compiling doc-comment v0.3.1
   Compiling scopeguard v0.3.3
   Compiling sysinfo v0.9.6
   Compiling crc32fast v1.2.0
   Compiling regex v1.0.2
   Compiling adler32 v1.0.4
   Compiling quick-error v1.2.1
   Compiling k8s-openapi v0.5.1
   Compiling regex-syntax v0.6.12
   Compiling unicode-width v0.1.4
   Compiling vec_map v0.8.0
   Compiling winapi v0.3.5
   Compiling ansi_term v0.11.0
   Compiling termcolor v0.3.6
   Compiling strsim v0.7.0
   Compiling podio v0.1.6
   Compiling byte-unit v3.0.3
   Compiling iotedged-eventlog-messages v0.1.0 (/project/iotedged-eventlog-messages)
   Compiling objekt v0.1.2
   Compiling tokio-named-pipe v0.1.0 (/project/tokio-named-pipe)
   Compiling hyper-named-pipe v0.1.0 (/project/hyper-named-pipe)
   Compiling lazy_static v1.3.0
   Compiling arrayvec v0.4.7
   Compiling log v0.4.5
   Compiling semver v0.9.0
   Compiling nom v4.2.3
   Compiling unicase v2.1.0
   Compiling num-traits v0.2.8
   Compiling num-integer v0.1.41
   Compiling num-bigint v0.2.3
   Compiling num-rational v0.2.2
   Compiling num-iter v0.1.39
   Compiling num-complex v0.2.3
   Compiling signal-future v0.1.0 (/project/signal-future)
   Compiling unicode-bidi v0.3.4
   Compiling tokio-sync v0.1.7
   Compiling yaml-rust v0.4.0
   Compiling foreign-types v0.3.2
   Compiling unreachable v1.0.0
   Compiling regex-syntax v0.5.6
   Compiling backtrace-sys v0.1.31
   Compiling openssl-sys v0.9.36
   Compiling cmake v0.1.40
   Compiling bzip2-sys v0.1.7
   Compiling block-buffer v0.3.3
   Compiling humantime v1.1.1
   Compiling miniz_oxide v0.3.2
   Compiling textwrap v0.9.0
   Compiling tabwriter v1.0.4
   Compiling crossbeam-utils v0.6.6
   Compiling want v0.2.0
   Compiling rustc_version v0.2.3
   Compiling thread_local v0.3.5
   Compiling idna v0.1.4
   Compiling hsm-sys v0.1.0 (/project/hsm-sys)
   Compiling iovec v0.1.2
   Compiling net2 v0.2.32
   Compiling num_cpus v1.8.0
error[E0308]: mismatched types
  --> /cargo/registry/src/github.com-1ecc6299db9ec823/net2-0.2.32/src/socket.rs:40:51
   |
40 |             ::cvt(c::bind(self.inner.raw(), addr, len as len_t)).map(|_| ())
   |                                                   ^^^^^^^^^^^^ expected u32, found i32
help: you can convert an `i32` to `u32` and panic if the converted value wouldn't fit
   |
40 |             ::cvt(c::bind(self.inner.raw(), addr, (len as len_t).try_into().unwrap())).map(|_| ())
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling memchr v2.0.1
error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `net2`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by arsing** [comment]
>it fails in num_cpus v1.8.0

No, your error shows it fails to compile `net2`

[This](https://github.com/rust-lang-nursery/net2-rs/commit/d958a03dea71f3b2315adc0167bda6aa63c081c9) probably fixed the issue, so see if `cargo update -p net2 --precise 0.2.33` helps.

**Comment by veyalla** [comment]
We don't support IoT Edge on Android, yet. 

@pclesr Can you share the scenario for attempting this?

**Comment by pclesr** [comment]
This is part of the Microsoft/Audi partnership, with the requirement that iot run on a cortex A53 with Android.

**Comment by arsing** [comment]
@pclesr Did you try the command I suggested?

**Comment by veyalla** [comment]
Please add this functionality as a new suggestion (or upvote an existing one) at https://aka.ms/iotedge-suggestion
