### ISSUE TITLE
iotedge check incorrectly shows an error when using DPS

### ISSUE THREAD

**Issue by jlorich** [Azure/iotedge#2313]
Running `iotedge check` when configured with symmetric key DPS displays the following problem:

```
× config.yaml has well-formed connection string - Error
    Device is not using manual provisioning, so Azure IoT Hub hostname needs to be specified with --iothub-hostname
```

This occurs even though Edge is running perfectly fine against DPS. An IoT Hub hostname should explicitly _not_ be specified with DPS.  I believe this to be an error with the `iotedge check` command.

**Comment by veyalla** [comment]
There currently isn't a way for the tool to discovery which hub the device is assigned to when using DPS. There are scenarios where customers know which hub their device will be assigned to so they can specify the address using `--iothub-name` to verify connectivity to it.

Does making this a warning instead of an error help?

**Comment by arsing** [comment]
>An IoT Hub hostname should explicitly *not* be specified with DPS.

That reasoning applies to the actual provisioning done by `iotedged`, not to `iotedge check`. `iotedge check` does not do provisioning itself, so it has no way to know what the IoT Hub hostname is for the "Can the device connect to the IoT Hub?" tests.

>Does making this a warning instead of an error help?

Not unless we want to also disable the connectivity tests.

**Comment by JeeWeetje** [comment]
@veyalla I think a warning is a better option. But with the explanation you give about - - iothub-name option and url to dps provioning iot edge docs (as - - verbose output or just normal output? ).

**Comment by arsing** [comment]
>>Does making this a warning instead of an error help?
>
>Not unless we want to also disable the connectivity tests.

@veyalla and I discussed offline and he asked for the connectivity tests to also downgrade to warnings if `--iothub-hostname` is not specified..

Note that this means we'll not run some tests just because the user ran the tool incorrectly. It also means users whose devices genuinely can't connect to IoT Hub for whatever reason (aggressive firewall rules, etc - the kind of things the connectivity tests are intended to catch in the first place) will see no errors from `iotedge check`.

**Comment by JeeWeetje** [comment]
Would it be an option to show that if the user does not provide the ```--iothub-name``` parameter when testing a DPS registered edge:

### normal warning
```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
!!! config.yaml has well-formed connection string - Warning
    Device is not using manual provisioning, so Azure IoT Hub hostname needs to be specified with --iothub-hostname. The connectivity tests can not be run without the --iothub-name parameter.
...
Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
!! Connectivity - Warning
     tests with the iothub skipped due to missing --iothub-name parameter
```

### verbose warning
```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
!! config.yaml has well-formed connection string - Warning
    Device is not using manual provisioning, so Azure IoT Hub hostname needs to be specified with --iothub-hostname. The connectivity tests can not be run without the --iothub-name parameter.

<add verbose  explanation here>
...
Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
!! Connectivity - Warning
     Connection tests with the iothub skipped due to missing --iothub-name parameter
     <add verbose information here>
```
This way you provide information why ```sudo iotedge check``` for DPS registered edges will not include all tests if the ```--iothub-name``` parameter is not provided

Although it provided better information, I think the real enhancement of ```sudo iotedge check``` for DPS registered edge devices would be checking the normal routes the run time and modules take with DPS registered edge devices. Correct me if wrong, but the check runs within the same security context?

**Comment by JeeWeetje** [comment]
Issue #1232 is related, and had the same questions. Now I know why the discussion looked familiar. ;-)

**Comment by arsing** [comment]
Implemented in https://github.com/Azure/iotedge/pull/2504
