### ISSUE TITLE
CONNECT failed: RefusedNotAuthorized

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#232]
Trying to use *edgeHub* as transparent gateway by using following code:

```csharp
            string hubName = "MYHUB.azure-devices.net";
            string deviceName = "DEVICEID";
            // Copied from iotedgedevice blade in azure portal => obfuscated.
            string sasKey = "AAAAABBBBBBBBBBBBBBBBBBBBBBBBBBAAAAA=";

            // MACHINENAME is the name of docker host and name of X509 certificate.
            var iotEdgeConnStr = $"HostName={hubName};DeviceId={deviceName};SharedAccessKey=
            {sasKey};GatewayHostName=MACHINENAME";

            var deviceClient = DeviceClient.CreateFromConnectionString(iotEdgeConnStr, TransportType.Mqtt);

            deviceClient.SendEventAsync(new Message(new byte[] {0x01, 0x02, 0x03 })).Wait();
```
Connection String as provided in documentation:
~~~
HostName=yourHub.azure-devices.net;DeviceId=yourDevice;SharedAccessKey=XXXYYYZZZ=;GatewayHostName=mygateway.contoso.com
~~~

## Expected Behavior
Events are successfully sent to *edgeHub*.

## Current Behavior

SendEventAsync method fails with: 
> UnauthorizedException: CONNECT failed: RefusedNotAuthorized

The code above is definitely able to establish the connection to edgHub. See logs below. Certificate chain trust is configures correctly. For example, if I change MACHINENAME in conneciton string to localhost, I get certificate trust error, because certificate is issued for MACHINE.

How to provide correct connection string to connect ot edgeHub?

### Device (Host) Operating System
Windows10

### Architecture
x64

### Container Operating System
Linux containers (amd64)

#### iotedged
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Docker
Docker version 18.06.0-ce, build 0ffa825

## edgeHub Logs
Unable to generate identity for 
clientId DEVICEID and username MACHINENAME/DEVICEID/?api-version=2018-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.17.0%20%28.NET%20Core%204.6.26628.05%3B%20Microsoft%20Windows%2010.0.17134%3B%20X64%29

**Comment by ddobric** [comment]
Not sure if I understand, what you mean with MACHINENAME.

I use in connection string machine name like HOSTXY. This is exactly the name of certificate. If I change this, then certificate validation will fail. It means, the name of host should be correct?

What exactly in this connection string should be changed? Where can we find some example?

~~~
var iotEdgeConnStr = $"HostName={hubName};DeviceId={deviceName};SharedAccessKey=
            {sasKey};GatewayHostName=MACHINENAME";
~~~

**Comment by ddobric** [comment]
DeviceSDK was 1.17.
IotEdge runtime 1.0.0
Still does not work.

What is recommended way to upgrade runtime?

Usually, I would expect following:

`iotedge update`

**Comment by lt72** [comment]
Closing issue as it seems stale, please re-open if necessary.
