### ISSUE TITLE
IoTEdge works but iotedge check throws container-engine-uri error

### ISSUE THREAD

**Issue by MateRadz** [Azure/iotedge#2321]
Hi,

As in the subject I have my IOTEdge set up on Windows Server. In portal device runtime configuration I have "mcr.microsoft.com/azureiotedge-hub:1.0.7.1".
I am using edge as transparent gateway. Messages from downstream devices are going through but when I launch "iotedge check" in Powershell I get the following error:

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
× container engine is installed and functional - Error
    Could not communicate with container engine at npipe://./pipe/iotedge_moby_engine.
    Please check your moby-engine installation and ensure the service is running.
    You might need to run this command as Administrator.

2 check(s) succeeded.
1 check(s) raised errors. Re-run with --verbose for more details.

Should I be worried? What may be the cause of this issue?

**Comment by varunpuranik** [comment]
@MateRadz - did you try to run the iotedge check command as Administrator?

**Comment by MateRadz** [comment]
Ok I will provide more details. Answering your last question  yes it happens regardless if it runs as administrator or normally.

**Comment by MateRadz** [comment]
Windows Version	10.0.17763 Build 17763
on VMWare Virtual Platform
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0). However  in portal device runtime configuration I have "mcr.microsoft.com/azureiotedge-hub:1.0.7.1" as instructed by Steve Busby in this post's comments (This is actually me asking Steve).
http://busbyland.com/connect-node-red-to-azure-iot-edge/

**Comment by veyalla** [comment]
@MateRadz How did you install IoT Edge on this system? Are you running Linux containers on Windows using Docker Desktop?

**Comment by MateRadz** [comment]
I run simply . {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; `
Deploy-IoTEdge
in Powershell on Windows.
I only know there is moby behind the scenes but I was not playing directly with docker.moby.

**Comment by veyalla** [comment]
@MateRadz I cannot repro this. Is it possible to try our [Windows Quickstart](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart), which deploys a VM and see if you run into the same issue.

**Comment by varunpuranik** [comment]
@MateRadz - we are not able to repro this issue, and don't have enough information to investigate it further. I am closing the issue. If you are able to repro it and have more information to help us investigate, please feel free to reopen.
