### ISSUE TITLE
c# Direct call to IoT Edge module gives "Unauthorized"

### ISSUE THREAD

**Issue by slavkab** [Azure/iotedge#2322]
Works in portal but fails in console app.

```C#
        static void Main(string[] args)
        {
            ModuleClient modClient = ModuleClient.CreateFromConnectionString(_moduleConnStr, TransportType.Mqtt);

            Task.Run(async () => await InvokeMethod(modClient));

            Console.ReadKey();
        }

        static async Task<MethodResponse> InvokeMethod(ModuleClient moduleClient)
        {
            try
            {
                await moduleClient.OpenAsync();


                // Create the request
                MethodRequest request = new MethodRequest(_method, Encoding.UTF8.GetBytes("{ \"Message\": \"Test\" }"));

                // Execute request
                var resp = await moduleClient.InvokeMethodAsync(_deviceId, _moduleId, request);

                // Write response to log for debugging
                Console.WriteLine($"Got result {resp.ResultAsJson} with status code {resp.Status}");

                return resp;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
                return await Task.FromResult(new MethodResponse(500));
            }
        }
```

**Comment by varunpuranik** [comment]
@slavkab - 
A module can invoke a direct method on another module or device only when it is connected to EdgeHub, and the device/module it is calling the direct method on is also connected to the same EdgeHub. 
In your example, are you connecting to the EdgeHub or IoTHub?
When you invoke the direct method from the portal, you are using Service permissions (implicitly) and the call gets routed via the IoTHub. So it works. 

Also note that unlike IoTHub, the EdgeHub does not have a certificate that is signed by a well-known certificate. So to be able to make the call, you will have to install the EdgeHub certificate (or the CA certificate up the chain) as a "trusted" certificate on your box. 
When you run the module and EdgeHub on the edge device in the context of the IoT Edge runtime (by doing a deployment), then all this is correctly set up for you automatically. But in that case you need to use the ModuleClient.CreateFromEnvironment overload to create the module client.

**Comment by slavkab** [comment]
Thank you Varun for prompt  response.

In my example I am connecting to IoT Hub Edge device module (Cloud to
device), using module connection string. I thought if I use SAS key (in
connection string) the call to module should be authorized.
As I understand, module connection string authorizes calls from module to
module only. It's not intuitive :).

**Comment by slavkab** [comment]
I was trying to simulate Cloud to Device(Module) call, and used wrong class, should use ServiceClient, like this:
```
                var servClient = ServiceClient.CreateFromConnectionString(_hubConnStr);

                var methodInvokation = new CloudToDeviceMethod(_method);
                methodInvokation.SetPayloadJson("{ \"Message\": \"Test\" }");
                CloudToDeviceMethodResult resp = await servClient.InvokeDeviceMethodAsync(_deviceId, _moduleId,methodInvokation);

                Console.WriteLine($"Got result {resp.GetPayloadAsJson()} with status code {resp.Status}");

```
