### ISSUE TITLE
IoT Hub Edge Module Falsely Reports Container Create Option Init

### ISSUE THREAD

**Issue by dapisani** [Azure/iotedge#2328]
## Expected Behavior
With container create option,
"HostConfig": {
…
"Init": true
…
}

Should create container with option "--init=true" which "Run an init inside the container that forwards signals and reaps processes"

## Current Behavior
IoT Hub will report back container create option,
"HostConfig": {
…
"Init": true
…
}
but container will not be created with that parameter.  This is reflected by no "tini" process in the container. And, docker inspect not showing "Init": true.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create Iot Hub Edge Module
2. Set desired container create options to 
"HostConfig": {
…
"Init": true
…
}
3. Wait until it reports back
"HostConfig": {
…
"Init": true
…
}
4. Run docker inspect on the container.  Notice it does not have "Init": true.

### Device Information
* Host OS [Ubuntu 18.04]: 
* Architecture [amd64]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)]: 
* Edge Agent [1.0]: 
* Edge Hub [1.0]: 
* Docker/Moby [19.03.5]:

**Comment by varunpuranik** [comment]
Looks like "Init":true is an undocumented feature in the Docker API that somehow works. Which probably explains why it doesn't get parsed and handled correctly.
What modules did you want to run this on? Can you work around this by adding tini to your module image?

**Comment by dapisani** [comment]
I am trying to run this on a module which needs to have a basic init system like tini.  I have already added tini to my image and made it an entrypoint. 

I first tried the "Init": true path and ran into this issue. It makes sense if you guys don't support it, but at least it shouldn't come back as reported.

**Comment by veyalla** [comment]
@varunpuranik do we consider this a bug? any plans to address it?

**Comment by varunpuranik** [comment]
Yes, we should add it to our backlog.
