### ISSUE TITLE
Configuration file permissions required on module start 

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#233]
Trying to migrate existing module from preview IotEdge runtime to the last one. The module loads trained ML trained model. This was working on preview runtime.
What is proposed way to deal with such kind of extra permissions, which have to be set in post-build process?

## Current Behavior
With new runtime version module fails with following error:
Model file is copied during build process to the output folder of application. However, when container runs, it fails with following exception, when it tries to lad the file:

> System.IO.IOException: Permission denied

Application is implemented in C#/.NET Core.

After starting container with bash, I can see following permissions on the file:

> 8 -rwxr-xr-x 1 root root 4530

I also tried to set permissions inside of *dockerfile* in build process of image with 

`RUN chmod 777 app/filename`

Build process outputs following error in this case:

> chmod: changing permissions of '/app/model.json': Operation not permitted

### Device (Host) Operating System
Windows10

### Architecture
x64

### Container Operating System
Linux containers (amd64)

### Runtime Versions
iotedged
iotedge 1.0.0 (52ef77d)

### Docker
Docker version 18.06.0-ce, build 0ffa825

## Failed module Log

```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/app/model.json' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at LearningFoundation.PersistenceProviders.JsonPersistenceProvider.Load(String name)
   at LearningFoundation.LearningApi.Load(String modelName, IModelPersistenceProvider persistenceProvider)
  ...
```

**Comment by aribeironovaes** [comment]
Hi @ddobric , 

Not sure which file is this. Is it part of the Microsoft Machine Learning Module? 

If it is, they will be the best to address your issue: https://github.com/Azure/ai-toolkit-iot-edge

Can you open a git hub issue there? 

Let me know, 

Angelo Ribeiro

**Comment by jason-e-gross** [comment]
The user moduleuser bit is so that your module is not running as root in the container.   If you commented out that line entirely, your dockerfile would work.  In reality, though, you should give moduleuser as much or as little as it needs to do whatever job it's doing in the Linux container.

I would gently beg to differ, that as module developers, we need to have an intimate knowledge of what the dockerfile is doing, and modify it as necessary to fit our module task.  Mount a volume, open ports, etc.

________________________________

**Comment by ddobric** [comment]
Hi @jason-e-gross,

Thanks for feedback. I totally agree that devs should know what they do and how all works under the hub. To achieve that, we need first to approve documentation.

Also, there is a huge difference between knowing how to do something and be enforced to do something. Microsoft stands for developer productivity for good reason which should also be achieved and improved with this stack.

If I do manually building and creating of csproj + docker file, then I probably doing something highly customised. This is fine. But building hello-world should not require developers to dig in several building process  artefacts.

**Comment by ddobric** [comment]
Hi @aribeironovaes 

thanks for feedback. The issue is confidentially related to some machine learning  framework.
The issue here is to find a better way to work with configuration and related files, which result from build process in output folder.
For example, some configuration files should be rather set for read permission. I guess asp.net core folks solved that issue in their build process.

**Comment by myagley** [comment]
Hi @ddobric. I'd like to get your issue routed to the right team. Where are the Dockerfiles that you posted above from? This will help us get your feedback incorporated into the product. Thanks.
