### ISSUE TITLE
Increasing auto_generated_ca_lifetime_days  dosn't work in release 1.0.9RC4

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#2340]
Hi Team,
     I am using the default certificate generated by the Edge runtime. And I want to increase the expiry date for that certificate as it is default 90 days only. So I have read in the release that you have given feature their to add the days in the expiry and I did the same but it doesn't work. 

So could you tell me how to use in the config.yml file. I have used it like given below and when I see the logs then it is still showing 90 days expiry in the edgeHub logs. 

certificates:
#   device_ca_cert: "<ADD URI TO DEVICE CA CERTIFICATE HERE>"
#   device_ca_pk: "<ADD URI TO DEVICE CA PRIVATE KEY HERE>"
#   trusted_ca_certs: "<ADD URI TO TRUSTED CA CERTIFICATES HERE>"
     auto_generated_ca_lifetime_days: 1000

**Comment by kkdawkins** [comment]
Could you send us your config.yaml? I just tried a quick repro here and it worked fine. Also, please send some logs so that I can see what you're looking at. 

Tip: Please use back-ticks (`) to drop code (like the config.yaml). It's hard to see your sample above.

**Comment by sachidanand** [comment]
Please find the config.yml below 

`###############################################################################
#                      IoT Edge Daemon configuration
###############################################################################
#
# This file configures the IoT Edge daemon. The daemon must be restarted to
# pick up any configuration changes.
#
# Note - this file is yaml. Learn more here: http://yaml.org/refcard.html
#
###############################################################################

###############################################################################
# Provisioning mode and settings
###############################################################################
#
# Configures the identity provisioning mode of the daemon.
#
# Supported modes:
#     manual - using an iothub connection string
#     dps    - using dps for provisioning
#
# DPS Settings
#     scope_id - Required. Value of a specific DPS instance's ID scope
#     registration_id - Required. Registration ID of a specific device in DPS
#     symmetric_key - Optional. This entry should only be specified when
#                     provisioning devices configured for symmetric key
#                     attestation
###############################################################################

# Manual provisioning configuration
provisioning:
  source: 'manual'
  device_connection_string: 'XXXXXX'

# DPS TPM provisioning configuration
# provisioning:
#   source: "dps"
#   global_endpoint: "https://global.azure-devices-provisioning.net"
#   scope_id: "{scope_id}"
#   attestation:
#     method: "tpm"
#     registration_id: "{registration_id}"

# DPS symmetric key provisioning configuration
# provisioning:
#   source: "dps"
#   global_endpoint: "https://global.azure-devices-provisioning.net"
#   scope_id: "{scope_id}"
#   attestation:
#     method: "symmetric_key"
#     registration_id: "{registration_id}"
#     symmetric_key: "{symmetric_key}"

###############################################################################
# Certificate settings
###############################################################################
#
# Configures the certificates required to operate the IoT Edge
# runtime as a gateway which enables external leaf devices to securely
# communicate with the Edge Hub. If not specified, the required certificates
# are auto generated for quick start scenarios which are not intended for
# production environments.
#
# Settings:
#     device_ca_cert   - path to the device ca certificate and its chain
#     device_ca_pk     - path to the device ca private key file
#     trusted_ca_certs - path to a file containing all the trusted CA
#                        certificates required for Edge module communication
#
###############################################################################l


certificates:
  #device_ca_cert: ''
  #device_ca_pk: ''
  #trusted_ca_certs: ''
  auto_generated_ca_lifetime_days: 1000

###############################################################################
# Edge Agent module spec
###############################################################################
#
# Configures the initial Edge Agent module.
#
# The daemon uses this definition to bootstrap the system. The Edge Agent can
# then update itself based on the Edge Agent module definition present in the
# deployment in IoT Hub.
#
# Settings:
#     name     - name of the edge agent module. Expected to be "edgeAgent".
#     type     - type of module. Always "docker".
#     env      - Any environment variable that needs to be set for edge agent module.
#     config   - type specific configuration for edge agent module.
#       image  - (docker) Modules require a docker image tag.
#       auth   - (docker) Modules may need authoriation to connect to container registry.
#
# Adding environment variables:
# replace "env: {}" with
#  env:
#    key: "value"
#
# Adding container registry authorization:
# replace "auth: {}" with
#    auth:
#      username: "username"
#      password: "password"
#      serveraddress: "serveraddress"
#
###############################################################################

agent:
  name: "edgeAgent"
  type: "docker"
  env:
    https_proxy: "xxxxxxxx"
    UpstreamProtocol: "AmqpWs"
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0.9-rc4"
    auth: {}

###############################################################################
# Edge device hostname
###############################################################################
#
# Configures the environment variable 'IOTEDGE_GATEWAYHOSTNAME' injected into
# modules. Regardless of case the hostname is specified below, a lower case
# value is used to configure the Edge Hub server hostname as well as the
# environment variable specified above.
#
# It is important to note that when connecting downstream devices to the
# Edge Hub that the lower case value of this hostname be used in the
# 'GatewayHostName' field of the device's connection string URI.
###############################################################################

hostname: 's3w7j'

###############################################################################
# Watchdog settings
###############################################################################
#
# The IoT edge daemon has a watchdog that periodically checks the health of the
# Edge Agent module and restarts it if it's down.
#
# max_retries - Configures the number of retry attempts that the IoT edge daemon
#               should make for failed operations before failing with a fatal error.
#
#               If this configuration is not specified, the daemon keeps retrying
#               on errors and doesn't fail fatally.
#
#               On a fatal failure, the daemon returns an exit code which
#               signifies the kind of error encountered. Currently, the following
#               error codes are returned by the daemon -
#
#               150 - Invalid Device ID specified.
#               151 - Invalid IoT hub configuration.
#               152 - Invalid SAS token used to call IoT hub.
#                     This could signal an invalid SAS key.
#               1 - All other errors.
###############################################################################

#watchdog:
#  max_retries: 2

###############################################################################
# Connect settings
###############################################################################
#
#
# Configures URIs used by clients of the management and workload APIs
#     management_uri - used by the Edge Agent and 'iotedge' CLI to start,
#                      stop, and manage modules
#     workload_uri   - used by modules to retrieve tokens and certificates
#
# The following uri schemes are supported:
#     http - connect over TCP
#     unix - connect over Unix domain socket
#
# If the 'unix' scheme is selected, the daemon expects that the parent
# directory of the specified socket file already exists, and that the Windows
# group 'NT AUTHORITY\Authenticated Users' has been given 'Modify' rights on
# the directory. For example, if the URI "unix:///C:/path/to/sock.file" is
# specified, then the directory "C:\path\to" must exist with the correct
# permissions.
#
###############################################################################

connect:
  management_uri: 'unix:///C:/ProgramData/iotedge/mgmt/sock'
  workload_uri: 'unix:///C:/ProgramData/iotedge/workload/sock'

###############################################################################
# Listen settings
###############################################################################
#
# Configures the listen addresses for the daemon.
#     management_uri - used by the Edge Agent and 'iotedge' CLI to start,
#                      stop, and manage modules
#     workload_uri   - used by modules to retrieve tokens and certificates
#
# The following uri schemes are supported:
#     http - listen over TCP
#     unix - listen over Unix domain socket
#
# If the 'unix' scheme is selected, the daemon expects that the parent
# directory of the specified socket file already exists, and that the Windows
# group 'NT AUTHORITY\Authenticated Users' has been given 'Modify' rights on
# the directory. For example, if the URI "unix:///C:/path/to/sock.file" is
# specified, then the directory "C:\path\to" must exist with the correct
# permissions.
#
###############################################################################

listen:
  management_uri: 'unix:///C:/ProgramData/iotedge/mgmt/sock'
  workload_uri: 'unix:///C:/ProgramData/iotedge/workload/sock'

###############################################################################
# Home Directory
###############################################################################
#
# This configures the home directory for the daemon.
#
###############################################################################

homedir: "C:\\ProgramData\\iotedge"

###############################################################################
# Moby Container Runtime settings
###############################################################################
#
# uri - configures the uri for the container runtime.
# network - configures the network on which the containers will be created.
#
###############################################################################

moby_runtime:
  uri: 'npipe://./pipe/iotedge_moby_engine'
  network: 'nat'
`

**Comment by sachidanand** [comment]
[config.txt](https://github.com/Azure/iotedge/files/4102421/config.txt)

**Comment by sachidanand** [comment]
2020-01-23 10:07:12.533 +00:00 Edge Hub Main()
<6> 2020-01-23 11:07:16.744 +01:00 [INF] - Installing certificates [CN=iotedged workload ca:4/20/2020 12:30:51 PM],[CN=Test Edge Device CA:4/20/2020 12:30:51 PM],[CN=Test Edge Owner CA:4/20/2020 12:30:51 PM] to CertificateAuthority
<6> 2020-01-23 11:07:16.827 +01:00 [INF] - Installing certificates [CN=Test Edge Owner CA:4/20/2020 12:30:51 PM] to CertificateAuthority
<6> 2020-01-23 11:07:18.930 +01:00 [INF] - Detected proxy http://194.9.121.79:3128/
<6> 2020-01-23 11:07:20.818 +01:00 [INF] - Created persistent store at C:\Windows\TEMP\edgeHub
<6> 2020-01-23 11:07:20.918 +01:00 [INF] - Initializing Edge Hub
<6> 2020-01-23 11:07:20.919 +01:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-01-23 11:07:20.923 +01:00 [INF] - Version - 1.0.9-rc4.27891379 (b0c0c72f2fe948e1175894db3c405d808e5e310e)
<6> 2020-01-23 11:07:20.923 +01:00 [INF] - OptimizeForPerformance=True
<6> 2020-01-23 11:07:20.932 +01:00 [INF] - Loaded server certificate with expiration date of "2020-04-20T12:30:51.0000000+02:00"
<6> 2020-01-23 11:07:21.060 +01:00 [INF] - Created new message store
<6> 2020-01-23 11:07:21.060 +01:00 [INF] - Started task to cleanup processed and stale messages
<6> 2020-01-23 11:07:21.407 +01:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2020-01-23 11:07:21.447 +01:00 [INF] - Created device scope identities cache
<6> 2020-01-23 11:07:21.468 +01:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-01-23 11:07:21.515 +01:00 [INF] - Initialized storing twin manager
<6> 2020-01-23 11:07:21.579 +01:00 [INF] - Initializing configuration
<6> 2020-01-23 11:07:21.653 +01:00 [INF] - New device connection for device 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:21.716 +01:00 [INF] - Processing pending subscriptions for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:21.976 +01:00 [INF] - Attempting to connect to IoT Hub for client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub via AMQP over WebSockets...
<6> 2020-01-23 11:07:24.328 +01:00 [INF] - Exiting disconnected state
<6> 2020-01-23 11:07:24.338 +01:00 [INF] - Received device connected callback
<6> 2020-01-23 11:07:24.383 +01:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2020-01-23 11:07:24.385 +01:00 [INF] - Processing subscriptions for client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub.
<6> 2020-01-23 11:07:24.427 +01:00 [INF] - Entering connected state
<6> 2020-01-23 11:07:24.437 +01:00 [INF] - Cloud connection for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub is True
<6> 2020-01-23 11:07:24.456 +01:00 [INF] - Connection status for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub changed to ConnectionEstablished
<6> 2020-01-23 11:07:24.465 +01:00 [INF] - Client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2020-01-23 11:07:24.482 +01:00 [INF] - Created cloud proxy for client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub via AMQP over WebSockets, with client operation timeout 20 seconds.
<6> 2020-01-23 11:07:24.495 +01:00 [INF] - Initialized cloud proxy 742d2e0e-7760-4810-a266-548d6409bc8c for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:24.499 +01:00 [INF] - Created cloud connection for client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:25.249 +01:00 [INF] - Processing pending subscriptions for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:25.365 +01:00 [INF] - Updated reported properties for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:25.879 +01:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2020-01-23 11:07:25.912 +01:00 [INF] - Obtained edge hub config from module twin
<6> 2020-01-23 11:07:26.346 +01:00 [INF] - Set the following 1 route(s) in edge hub
<6> 2020-01-23 11:07:26.346 +01:00 [INF] - upstream: FROM /messages/* INTO $upstream
<6> 2020-01-23 11:07:26.354 +01:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-01-23 11:07:26.357 +01:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-01-23 11:07:26.386 +01:00 [INF] - Started operation Get EdgeHub config
<6> 2020-01-23 11:07:26.387 +01:00 [INF] - Initialized edge hub configuration
<6> 2020-01-23 11:07:26.432 +01:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2020-01-23 11:07:26.656 +01:00 [INF] - Updated reported properties for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:26.678 +01:00 [INF] - Scheduling server certificate renewal for "2020-04-20T12:28:21.0003793Z".
<6> 2020-01-23 11:07:26.682 +01:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2020-01-23 11:07:26.695 +01:00 [INF] - Starting MQTT head
<6> 2020-01-23 11:07:26.795 +01:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2020-01-23 11:07:27.023 +01:00 [INF] - Starting AMQP head
<6> 2020-01-23 11:07:27.060 +01:00 [INF] - Started MQTT head
<6> 2020-01-23 11:07:27.297 +01:00 [INF] - Started AMQP head
<6> 2020-01-23 11:07:27.304 +01:00 [INF] - Starting HTTP head
<6> 2020-01-23 11:07:27.714 +01:00 [INF] - User profile is available. Using '"C:\\Users\\ContainerUser\\AppData\\Local\\ASP.NET\\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
<4> 2020-01-23 11:07:28.979 +01:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2020-01-23 11:07:29.049 +01:00 [INF] - Started HTTP head
<6> 2020-01-23 11:07:33.876 +01:00 [INF] - New token received on the Cbs link
<6> 2020-01-23 11:07:34.595 +01:00 [INF] - Client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC in device scope authenticated locally.
<6> 2020-01-23 11:07:34.669 +01:00 [INF] - New device connection for device 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:34.721 +01:00 [INF] - Bind device proxy for device 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:34.726 +01:00 [INF] - Initialized device listener in the AMQP protocol head for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:34.777 +01:00 [INF] - Opened link Events for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:34.874 +01:00 [INF] - Updated reported properties for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/$edgeHub
<6> 2020-01-23 11:07:35.110 +01:00 [INF] - Opened link TwinReceiving for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:35.125 +01:00 [INF] - Processing pending subscriptions for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:35.126 +01:00 [INF] - Attempting to connect to IoT Hub for client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC via AMQP over WebSockets...
<6> 2020-01-23 11:07:35.129 +01:00 [INF] - Opened link TwinSending for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:35.264 +01:00 [INF] - Cloud connection for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC is True
<6> 2020-01-23 11:07:35.264 +01:00 [INF] - Connection status for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC changed to ConnectionEstablished
<6> 2020-01-23 11:07:35.265 +01:00 [INF] - Client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC connected to cloud, processing existing subscriptions.
<6> 2020-01-23 11:07:35.266 +01:00 [INF] - Created cloud proxy for client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC via AMQP over WebSockets, with client operation timeout 20 seconds.
<6> 2020-01-23 11:07:35.267 +01:00 [INF] - Initialized cloud proxy defbb270-c90d-439c-8a22-6d57bdd6eb19 for 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC
<6> 2020-01-23 11:07:35.267 +01:00 [INF] - Created cloud connection for client 89b9a454-5a62-4899-8f77-f9f7e8a671fd/DC

**Comment by sachidanand** [comment]
Please update me on this

**Comment by veyalla** [comment]
Hi @sachidanand - thanks for your patience. We're still stabilizing this capability, it doesn't seem to be working as intended. Will keep you posted.

**Comment by sachidanand** [comment]
By when we will be getting the stable version of it ???

**Comment by veyalla** [comment]
It has some rough edges that we'll fix 1.0.10 but we confirmed this works with 1.0.9-rc4 using the following steps:
* Install IoT Edge (use `offlineinstallationpath`  to try RC)
* Update `config.yaml` with the desired expiry time (in days)
* Manually delete the contents of `%programdata%\iotedge\hsm` folder
* Restart iotedge `Restart-Service iotedge`
* Run `iotedge check --verbose` to confirm certificate lifetime in the `production readiness: certificates` check.

Note: The edgeHub will still request a 90 day server cert in this scenario but on certificate expiry, it will crash, get restarted and request a new cert with a fresh 90 day lifetime. This should happen without user intervention. 

Please try these steps and lets us know if this is working for you.

**Comment by kkdawkins** [comment]
I'll go ahead and close this - feel free to reopen if you need more help. Thanks!
