### ISSUE TITLE
Question - edgeAgent properties for Connectivity Status & Module Update Progress

### ISSUE THREAD

**Issue by vjrag** [Azure/iotedge#2341]
**edgeAgent properties for Connectivity Status** 

How frequently edgeAgent reports the below properties as part of twin reported property.

- lastDesiredStatus.code
- lastDesiredStatus.description

Can these parameters be used to determine if the Azure IoT Edge Runtime is communicating with IoT Hub ? What if the device goes offline, will the status change back from 200 after sometime at IoT hub side ?

**edgeAgent properties for Module Update Progress**
If we are pushing some module updates via edgeAgent Desired properties, Is there any feedback mechanism to check the module update progress at IoT hub side

Is it a right way to compare edgeAgent Desired Properties with reported properties to derive the status of upgrade ?

**Comment by varunpuranik** [comment]
@vjrag - 
Re: EdgeAgent properties for Connectivity Status
EdgeAgent will update its reported properties, only when there are any changes to the status (not periodically). So, it is not a good indicator if the device is online or offline. Unfortunately, there is no reliable way to check connectivity status of a device from IoTHub. 
Re: Status of upgrade 
Yes, EdgeAgent will report the current status of its deployment in the reported properties. So the way is to compare the Desired and Reported properties for EdgeAgent.

**Comment by vjrag** [comment]
Thanks @varunpuranik for the details. 
Is there any other parameters edgeAgent or edgeHub reports at certain interval which we can use for deriving lastcommunicationtime Or should we need to have a heartbeat module which we can use for reporting the last communication time at some defined interval (may be via module twin) ?

**Comment by varunpuranik** [comment]
Unfortunately there is no property that is updated periodically by the EdgeHub or EdgeAgent.
