### ISSUE TITLE
Azure IoT Edge Module Connection State = Disabled

### ISSUE THREAD

**Issue by FrankPfattheicher** [Azure/iotedge#237]
Sometimes i get a ConnectionStateChanged event saying

status: Disabled 
reason: Client_Close

Still everything is working !?

There is no further state change...

Do i have some "keep alive" ?

Why it is not automatically reconnecting?

**Comment by damonbarry** [comment]
Can I get a little more info? It sounds like you're describing the connection state handler logic in the IoT SDK for C#...is that right? Are you using the SDK within a custom IoT Edge module?

**Comment by FrankPfattheicher** [comment]
I started with a very basic module using C#, SDK, VS-Code IoT Edge Solution template
All works like expected.
To learn more i registered for the ConnectionStatusChanges event

> ioTHubModuleClient.SetConnectionStatusChangesHandler(ConnectionStatusChanged);

> public static async void ConnectionStatusChanged(ConnectionStatus status, ConnectionStatusChangeReason reason)
>        {
>            Console.WriteLine($"ConnectionStatusChanged: {status}, reason={reason}");
>        }

I get a Connected event as expected.
After a while the unexpected Disabled / Client_Close event !??

Nevertheless still everthing is working...

**Comment by damonbarry** [comment]
@varunpuranik?

**Comment by varunpuranik** [comment]
@FrankPfattheicher - what transport are you using? MQTT? If so, then EdgeHub will drop the downstream connection when the token expires, but the SDK has the logic to recover the connection automatically for you. The callback should just be used in case you want to do something interesting when that happens.

**Comment by FrankPfattheicher** [comment]
IoT-Edge is always using AMQP...

Varun Puranik <notifications@github.com> schrieb am Mo., 10. Sep. 2018,
19:35:

**Comment by ddimitrov90** [comment]
we are using amqp and recently (may be with the latest updates) started receiving this (1-2-3 minutes after start of module) ConnectionStatusChanged event with the same result:
Disabled with reason Client_Close.

Is this a problem? Is this affecting the sending of messages upstream or between modules?

**Comment by lt72** [comment]
@ddimitrov90 Hello, sorry for the late answer. Do you still need help with this?

**Comment by FrankPfattheicher** [comment]
Didn't try this for a year 🙈

Best Regards / Mit Grüßen aus Baden

Frank Pfattheicher

---------------------------------------------------------------------

ICT BADEN GmbH, D-76227 Karlsruhe, Seboldstraße 9

fon: 0172-7207196, e-mail: fpf@ict-baden.de

Geschäftsführer: Frank Pfattheicher

Amtsgericht Mannheim: HRB 706949

USt-IdNr: DE 265276745


Am Mi., 30. Okt. 2019 um 19:17 Uhr schrieb Lorenzo Tessiore <
notifications@github.com>:

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
