### ISSUE TITLE
Question: How to assign static ip address for an IoTEdge module

### ISSUE THREAD

**Issue by dockslim** [Azure/iotedge#2378]
We want to run a server inside an IoT Edge module, and run clients in other modules. When we start the server module, we need to assign a static ip address from the azure IoT edge subnet to it, so that clients in other module can connect to the server module with the static ip. We are unable to figure out how to do that yet. Anyone can help?

**Comment by veyalla** [comment]
@dockslim Private docker networks like the one IoT Edge creates get service discovery thru built-in DNS. So if your server module was called "server1" and listening on port 5000. Other IoT Edge modules can access it at "http://server1:5000" (assuming http endpoint).

**Comment by dockslim** [comment]
It works! Thank you!

**Comment by simonachmueller** [comment]
Hi, I have a case where a module does not support dns resolution, I need to use IP address to point on another deployed module. Is there any way to assign a static IP address to the module?
