### ISSUE TITLE
 Warning: Reconcile failed because of the an exception

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#239]
Running IotEdge on PI with few modules. For a while all works fine, but *edgAgent* log contains repeating warning message:

> [WRN] - Reconcile failed because of the an exception

After some time edgeHub and all modules enter failed state. *edgeAgent* continues running.
In that case *edgeHub* contains following last log message before termination:

> terminate called after throwing an instance of 'std::bad_alloc'

All modules in that case writes following exception before termination:

> Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
>    at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
>    at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
> --- End of stack trace from previous location where exception was thrown ---
>    at sinusgen.Program.Init() in /app/Program.cs:line 69
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at sinusgen.Program.Main(String[] args)

*edgeAgent* is in this case only running module:

See log excerpt of edgeAgent below. EdgeAgent log excerpt:
> 
>         █████╗ ███████╗██╗   ██╗██████╗ ███████╗
>        ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
>        ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
>        ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
>        ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
>        ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
> 
>  ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
>  ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
>  ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
>  ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
>  ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
>  ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝
> 
> 2018-09-03 08:10:28.528 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
> 2018-09-03 08:10:31.995 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
> 2018-09-03 08:10:34.116 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
> 2018-09-03 08:10:35.769 +00:00 [WRN] - Reconcile failed because of the an exception
> System.ArgumentNullException: Value cannot be null.
> Parameter name: createOptions
>    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 159
> 2018-09-03 08:10:36.538 +00:00 [INF] - Updated reported properties
> 2018-09-03 08:10:41.612 +00:00 [WRN] - Reconcile failed because of the an exception
> System.ArgumentNullException: Value cannot be null.
> . . .
> 59
> 2018-09-03 07:36:54.168 +00:00 [WRN] - Reconcile failed because of the an exception
> System.ArgumentNullException: Value cannot be null.
> Parameter name: createOptions
>    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 159
> 2018-09-03 07:36:59.246 +00:00 [WRN] - Reconcile failed because of the an exception
> System.ArgumentNullException: Value cannot be null.
> Parameter name: createOptions
>    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 159
> 2018-09-03 07:37:04.317 +00:00 [WRN] - Reconcile failed because of the an exception
> System.ArgumentNullException: Value cannot be null.
> Parameter name: createOptions
>    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 159

Note: *OptimizeForPerformance* is set on false.
Please also note, that hard reset of this PI-device fails. 
![image](https://user-images.githubusercontent.com/1756871/44975642-3922b880-af63-11e8-975b-a760964a52f4.png)
To run device, I have to restart modules. 
![image](https://user-images.githubusercontent.com/1756871/44975709-6ec7a180-af63-11e8-9841-7f93158ed67d.png)
After that all modules running well for some time. However *edgeAgent* log contains warnings described above and it does not accept module updates.

### Device (Host) Operating System
Raspbian GNU/Linux 9 (stretch)

### Architecture
ARM

### Runtime Versions
iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)

### Docker
18.06.0-dev, build daf021fe

## Logs
Following log entries are repeating.

Sep 03 09:52:05 raspberrypi iotedged[412]: 2018-09-03T07:52:05Z [INFO] - Checking edge runtime status
Sep 03 09:52:05 raspberrypi iotedged[412]: 2018-09-03T07:52:05Z [INFO] - Edge runtime is running.
Sep 03 09:52:05 raspberrypi iotedged[412]: 2018-09-03T07:52:05Z [INFO] - [mgmt] - - - [2018-09-03 07:52:05.548880438 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:05 raspberrypi iotedged[412]: 2018-09-03T07:52:05Z [INFO] - [work] - - - [2018-09-03 07:52:05.556769128 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:10 raspberrypi iotedged[412]: 2018-09-03T07:52:10Z [INFO] - [mgmt] - - - [2018-09-03 07:52:10.622738296 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:10 raspberrypi iotedged[412]: 2018-09-03T07:52:10Z [INFO] - [work] - - - [2018-09-03 07:52:10.637029688 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:15 raspberrypi iotedged[412]: 2018-09-03T07:52:15Z [INFO] - [mgmt] - - - [2018-09-03 07:52:15.737886313 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:15 raspberrypi iotedged[412]: 2018-09-03T07:52:15Z [INFO] - [work] - - - [2018-09-03 07:52:15.746730575 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:20 raspberrypi iotedged[412]: 2018-09-03T07:52:20Z [INFO] - [mgmt] - - - [2018-09-03 07:52:20.817041754 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:20 raspberrypi iotedged[412]: 2018-09-03T07:52:20Z [INFO] - [work] - - - [2018-09-03 07:52:20.826536901 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:25 raspberrypi iotedged[412]: 2018-09-03T07:52:25Z [INFO] - [work] - - - [2018-09-03 07:52:25.892559796 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:25 raspberrypi iotedged[412]: 2018-09-03T07:52:25Z [INFO] - [mgmt] - - - [2018-09-03 07:52:25.905026554 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:30 raspberrypi iotedged[412]: 2018-09-03T07:52:30Z [INFO] - [mgmt] - - - [2018-09-03 07:52:30.978646517 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:30 raspberrypi iotedged[412]: 2018-09-03T07:52:30Z [INFO] - [work] - - - [2018-09-03 07:52:30.988172445 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:36 raspberrypi iotedged[412]: 2018-09-03T07:52:36Z [INFO] - [mgmt] - - - [2018-09-03 07:52:36.058280425 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:36 raspberrypi iotedged[412]: 2018-09-03T07:52:36Z [INFO] - [work] - - - [2018-09-03 07:52:36.068165467 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:41 raspberrypi iotedged[412]: 2018-09-03T07:52:41Z [INFO] - [work] - - - [2018-09-03 07:52:41.132533862 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:41 raspberrypi iotedged[412]: 2018-09-03T07:52:41Z [INFO] - [mgmt] - - - [2018-09-03 07:52:41.146151922 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:46 raspberrypi iotedged[412]: 2018-09-03T07:52:46Z [INFO] - [mgmt] - - - [2018-09-03 07:52:46.216624001 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:46 raspberrypi iotedged[412]: 2018-09-03T07:52:46Z [INFO] - [work] - - - [2018-09-03 07:52:46.218838478 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:51 raspberrypi iotedged[412]: 2018-09-03T07:52:51Z [INFO] - [work] - - - [2018-09-03 07:52:51.301934861 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:51 raspberrypi iotedged[412]: 2018-09-03T07:52:51Z [INFO] - [mgmt] - - - [2018-09-03 07:52:51.303700536 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:56 raspberrypi iotedged[412]: 2018-09-03T07:52:56Z [INFO] - [mgmt] - - - [2018-09-03 07:52:56.378806607 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:52:56 raspberrypi iotedged[412]: 2018-09-03T07:52:56Z [INFO] - [work] - - - [2018-09-03 07:52:56.387376390 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:52:59 raspberrypi iotedged[412]: 2018-09-03T07:52:59Z [INFO] - [mgmt] - - - [2018-09-03 07:52:59.858285693 UTC] "GET /modules/fncrecognizer/logs?api-version=201….0" pid(11751)
Sep 03 09:53:01 raspberrypi iotedged[412]: 2018-09-03T07:53:01Z [INFO] - [mgmt] - - - [2018-09-03 07:53:01.443417109 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:01 raspberrypi iotedged[412]: 2018-09-03T07:53:01Z [INFO] - [work] - - - [2018-09-03 07:53:01.445998565 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:05 raspberrypi iotedged[412]: 2018-09-03T07:53:05Z [INFO] - Checking edge runtime status
Sep 03 09:53:05 raspberrypi iotedged[412]: 2018-09-03T07:53:05Z [INFO] - Edge runtime is running.
Sep 03 09:53:06 raspberrypi iotedged[412]: 2018-09-03T07:53:06Z [INFO] - [mgmt] - - - [2018-09-03 07:53:06.523832171 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:06 raspberrypi iotedged[412]: 2018-09-03T07:53:06Z [INFO] - [work] - - - [2018-09-03 07:53:06.532758985 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:11 raspberrypi iotedged[412]: 2018-09-03T07:53:11Z [INFO] - [mgmt] - - - [2018-09-03 07:53:11.607806859 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:11 raspberrypi iotedged[412]: 2018-09-03T07:53:11Z [INFO] - [work] - - - [2018-09-03 07:53:11.618938149 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:16 raspberrypi iotedged[412]: 2018-09-03T07:53:16Z [INFO] - [mgmt] - - - [2018-09-03 07:53:16.685871024 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:16 raspberrypi iotedged[412]: 2018-09-03T07:53:16Z [INFO] - [work] - - - [2018-09-03 07:53:16.690688623 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:21 raspberrypi iotedged[412]: 2018-09-03T07:53:21Z [INFO] - [mgmt] - - - [2018-09-03 07:53:21.767113513 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:21 raspberrypi iotedged[412]: 2018-09-03T07:53:21Z [INFO] - [work] - - - [2018-09-03 07:53:21.776596524 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:24 raspberrypi iotedged[412]: 2018-09-03T07:53:24Z [INFO] - [mgmt] - - - [2018-09-03 07:53:24.442009800 UTC] "GET /modules/sinusgen/logs?api-version=2018-06-….0" pid(11759)
Sep 03 09:53:26 raspberrypi iotedged[412]: 2018-09-03T07:53:26Z [INFO] - [mgmt] - - - [2018-09-03 07:53:26.848625318 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:26 raspberrypi iotedged[412]: 2018-09-03T07:53:26Z [INFO] - [work] - - - [2018-09-03 07:53:26.857815673 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:31 raspberrypi iotedged[412]: 2018-09-03T07:53:31Z [INFO] - [mgmt] - - - [2018-09-03 07:53:31.920058428 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:31 raspberrypi iotedged[412]: 2018-09-03T07:53:31Z [INFO] - [work] - - - [2018-09-03 07:53:31.927836024 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:36 raspberrypi iotedged[412]: 2018-09-03T07:53:36Z [INFO] - [mgmt] - - - [2018-09-03 07:53:36.995382361 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:36 raspberrypi iotedged[412]: 2018-09-03T07:53:36Z [INFO] - [work] - - - [2018-09-03 07:53:36.997326526 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:42 raspberrypi iotedged[412]: 2018-09-03T07:53:42Z [INFO] - [mgmt] - - - [2018-09-03 07:53:42.080515809 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:42 raspberrypi iotedged[412]: 2018-09-03T07:53:42Z [INFO] - [work] - - - [2018-09-03 07:53:42.086275335 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)
Sep 03 09:53:47 raspberrypi iotedged[412]: 2018-09-03T07:53:47Z [INFO] - [mgmt] - - - [2018-09-03 07:53:47.154132856 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 2… "-" pid(1413)
Sep 03 09:53:47 raspberrypi iotedged[412]: 2018-09-03T07:53:47Z [INFO] - [work] - - - [2018-09-03 07:53:47.163889774 UTC] "POST /modules/%24edgeAgent/genid/63671427888394… "-" pid(1413)

**Comment by veyalla** [comment]
@ddobric Do you have the optimizeforperformance env var set to false? If not, could you please try that? Instructions [here](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#stability-issues-on-resource-constrained-devices).

**Comment by ddobric** [comment]
Yes. This was first I have checked.

**Comment by dsajanice** [comment]
I have a couple questions: 1) How did you create the deployment for this Edge device? 2) Did you specify some create options for the edgeAgent container? If yes, what did you specify?

**Comment by ddobric** [comment]
I use deployment template file

```json
"systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": ""
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}], \"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
            }
          }
        },
```

**Comment by dsajanice** [comment]
It looks like the edgeAgent createOptions should be "{}". I see that the default deployment template in VS Code has "". I am looking in to why this is the case. Could you please try again with it set to "{}".

**Comment by ddobric** [comment]
This could be the issue. Btw. there is also an issue in portal related to options:
![image](https://user-images.githubusercontent.com/1756871/45058030-b3545980-b097-11e8-996b-528116e5e3d4.png)

It is empty by default.

**Comment by dsajanice** [comment]
If the deployment was incorrectly set via VS Code with "", then the 'Set Modules' workflow in the portal will display the red warning sign that you pasted above. Did you do the first deployment of the device via the portal and a subsequent one via VS Code?

**Comment by dsajanice** [comment]
If your system is still in the state where edgeAgent is failing, could you please turn debug logging on. One way to do this is to add the RuntimeLogLevel variable to the agent section in the config.yaml file on the device as follows:
....
agent:
  name: "edgeAgent"
  type: "docker"
  env:
    RuntimeLogLevel: "debug"
.... 

Please restart iotedged (sudo systemctl restart iotedge) and paste the logs here from edgeAgent (docker logs edgeAgent).

**Comment by ddobric** [comment]
unfortunately I have uninstall it few hours ago.
I tried loglevel debug. After that I was not able to stop service. It was hanging, so I uninstalled everything. But it will happen again.

**Comment by ddobric** [comment]
After adding debug to config and restart of service, the only running module is edgeAgent. 
All other images (hub + 2xmodules) are still on the box, but not started. 

#### edgeAgent

```
2018-09-05 07:02:47.670 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Waiting on shutdown handler to trigger
2018-09-05 07:02:48.003 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2018-09-05 07:02:49.153 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Initialize twin refresh with interval '01:00:00'
2018-09-05 07:02:49.287 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ConfigSources.TwinConfigSource] - TwinConfigSource Created
2018-09-05 07:02:49.295 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.FileBackupConfigSource] - Edge agent config backup created here - backup.json
2018-09-05 07:02:51.017 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Modules.AgentModule] - Created persistent store at /tmp/edgeAgent
2018-09-05 07:02:51.116 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient] - Making a Http call to unix:///var/run/iotedge/mgmt.sock to Getting System Info
2018-09-05 07:02:51.252 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket /var/run/iotedge/mgmt.sock
2018-09-05 07:02:51.272 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket /var/run/iotedge/mgmt.sock
2018-09-05 07:02:51.310 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://mgmt.sock/systeminfo?api-version=2018-06-28
2018-09-05 07:02:57.837 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Connection status changed to Connected with reason Connection_Ok
2018-09-05 07:02:57.920 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
2018-09-05 07:02:57.947 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient] - Device client for edge agent created.
2018-09-05 07:02:58.620 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Begin refreshing twin from upstream...
2018-09-05 07:02:59.683 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent updated deployment config from desired properties.
2018-09-05 07:02:59.685 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Updated edge agent configuration from upstream twin.
2018-09-05 07:03:28.717 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent desired properties updated callback invoked.
2018-09-05 07:03:28.833 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent updated deployment config from desired properties.
2018-09-05 07:03:28.836 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent desired properties patch applied successfully.
2018-09-05 07:04:48.522 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent desired properties updated callback invoked.
2018-09-05 07:04:48.547 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent updated deployment config from desired properties.
2018-09-05 07:04:48.547 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection] - Edge agent desired properties patch applied successfully.

```
#### iotserviced

```
Sep 05 08:57:39 raspberrypi iotedged[6701]: 2018-09-05T06:57:39Z [INFO] - Checking edge runtime status
Sep 05 08:57:39 raspberrypi iotedged[6701]: 2018-09-05T06:57:39Z [INFO] - Edge runtime is running.
Sep 05 08:58:39 raspberrypi iotedged[6701]: 2018-09-05T06:58:39Z [INFO] - Checking edge runtime status
Sep 05 08:58:39 raspberrypi iotedged[6701]: 2018-09-05T06:58:39Z [INFO] - Edge runtime is running.
Sep 05 08:59:39 raspberrypi iotedged[6701]: 2018-09-05T06:59:39Z [INFO] - Checking edge runtime status
Sep 05 08:59:39 raspberrypi iotedged[6701]: 2018-09-05T06:59:39Z [INFO] - Edge runtime is running.
Sep 05 09:00:39 raspberrypi iotedged[6701]: 2018-09-05T07:00:39Z [INFO] - Checking edge runtime status
Sep 05 09:00:39 raspberrypi iotedged[6701]: 2018-09-05T07:00:39Z [INFO] - Edge runtime is running.
Sep 05 09:01:32 raspberrypi iotedged[6701]: 2018-09-05T07:01:32Z [WARN] - Container not found
Sep 05 09:01:32 raspberrypi iotedged[6701]: 2018-09-05T07:01:32Z [INFO] - [mgmt] - - - [2018-09-05 07:01:32.910651162 UTC] "GET /modules/edgeHub/logs?api-version=2018-06-28&follow=true&tail=…0.1.0" pid(6945)
Sep 05 09:01:39 raspberrypi iotedged[6701]: 2018-09-05T07:01:39Z [INFO] - [mgmt] - - - [2018-09-05 07:01:39.021930225 UTC] "GET /modules/edgeAgent/logs?api-version=2018-06-28&follow=true&tai…0.1.0" pid(6947)
Sep 05 09:01:39 raspberrypi iotedged[6701]: 2018-09-05T07:01:39Z [INFO] - Checking edge runtime status
Sep 05 09:01:39 raspberrypi iotedged[6701]: 2018-09-05T07:01:39Z [INFO] - Edge runtime is running.
Sep 05 09:01:50 raspberrypi iotedged[6701]: 2018-09-05T07:01:50Z [ERR!] - server connection error: (unknown) Broken pipe (os error 32)
Sep 05 09:01:50 raspberrypi iotedged[6701]: 2018-09-05T07:01:50Z [INFO] - [mgmt] - - - [2018-09-05 07:01:50.555257145 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 200 OK 103 "-" "-" pid(6750)
Sep 05 09:02:06 raspberrypi iotedged[6701]: 2018-09-05T07:02:06Z [INFO] - [mgmt] - - - [2018-09-05 07:02:06.960870554 UTC] "GET /modules/edgeAgent/logs?api-version=2018-06-28&follow=true&tai…0.1.0" pid(7062)
Sep 05 09:02:11 raspberrypi iotedged[6701]: 2018-09-05T07:02:11Z [INFO] - [mgmt] - - - [2018-09-05 07:02:11.855119716 UTC] "GET /modules/edgeAgent/logs?api-version=2018-06-28&follow=true&tai…0.1.0" pid(7064)
Sep 05 09:02:18 raspberrypi iotedged[6701]: 2018-09-05T07:02:18Z [INFO] - [mgmt] - - - [2018-09-05 07:02:18.886020558 UTC] "GET /modules/edgeAgent/logs?api-version=2018-06-28&follow=true&tai…0.1.0" pid(7066)
Sep 05 09:02:20 raspberrypi iotedged[6701]: 2018-09-05T07:02:20Z [INFO] - [mgmt] - - - [2018-09-05 07:02:20.007966129 UTC] "GET /modules/edgeAgent/logs?api-version=2018-06-28&follow=true&tai…0.1.0" pid(7068)
Sep 05 09:02:25 raspberrypi iotedged[6701]: 2018-09-05T07:02:25Z [INFO] - [mgmt] - - - [2018-09-05 07:02:25.592656740 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 529 "-" "iote…0.1.0" pid(7070)
Sep 05 09:02:34 raspberrypi iotedged[6701]: 2018-09-05T07:02:34Z [INFO] - [mgmt] - - - [2018-09-05 07:02:34.829408440 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 529 "-" "iote…0.1.0" pid(7072)
Sep 05 09:02:39 raspberrypi iotedged[6701]: 2018-09-05T07:02:39Z [INFO] - Checking edge runtime status
Sep 05 09:02:39 raspberrypi iotedged[6701]: 2018-09-05T07:02:39Z [INFO] - Edge runtime status is stopped, starting module now...
Sep 05 09:02:44 raspberrypi iotedged[6701]: 2018-09-05T07:02:44Z [INFO] - [mgmt] - - - [2018-09-05 07:02:44.311721326 UTC] "POST /modules/edgeAgent/restart?api-version=2018-06-28 HTTP/1.1" 2…0.1.0" pid(7195)
Sep 05 09:02:46 raspberrypi iotedged[6701]: 2018-09-05T07:02:46Z [INFO] - [mgmt] - - - [2018-09-05 07:02:46.496326500 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 530 "-" "iote…0.1.0" pid(7410)
Sep 05 09:02:49 raspberrypi iotedged[6701]: 2018-09-05T07:02:49Z [INFO] - [mgmt] - - - [2018-09-05 07:02:49.807338895 UTC] "GET /modules/edgeAgent/logs?api-version=2018-06-28&follow=true&tai…0.1.0" pid(7425)
Sep 05 09:02:56 raspberrypi iotedged[6701]: 2018-09-05T07:02:56Z [INFO] - [work] - - - [2018-09-05 07:02:56.427033428 UTC] "POST /modules/%24edgeAgent/genid/636714278883940668/sign?api-versi…-" "-" pid(7318)
Sep 05 09:03:14 raspberrypi iotedged[6701]: 2018-09-05T07:03:14Z [INFO] - [mgmt] - - - [2018-09-05 07:03:14.250894278 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 530 "-" "iote…0.1.0" pid(7490)
Sep 05 09:03:39 raspberrypi iotedged[6701]: 2018-09-05T07:03:39Z [INFO] - Checking edge runtime status
Sep 05 09:03:39 raspberrypi iotedged[6701]: 2018-09-05T07:03:39Z [INFO] - Edge runtime is running.
Sep 05 09:03:51 raspberrypi iotedged[6701]: 2018-09-05T07:03:51Z [INFO] - [mgmt] - - - [2018-09-05 07:03:51.795246242 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 530 "-" "iote…0.1.0" pid(7496)
```

**Comment by dsajanice** [comment]
Could you please check the tail of edgeHub logs (docker tail --100 edgeHub) for errors. Were the modules running before restart?

**Comment by ddobric** [comment]
I have changed manually in system modules startOptions from "" to {}.
After that

**Comment by dsajanice** [comment]
@ddobric I tried various ways to reproduce the reconcile issue but was unable to. Given the information I got from your logs, it seems like the "{}" was the issue. I have filed a bug with our VS Code team and they will be fixing it soon. If you hit this issue again, lets go over your workflow again.
