### ISSUE TITLE
IOT-Edge Hub back-off state

### ISSUE THREAD

**Issue by BilalAkmal47** [Azure/iotedge#240]
i am trying to deploy a module into iot-edge device, for that i am following these [Official Documentation](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart). 
- Have an IoTHub subscription
- Created Edge Device in it
- Installed IoTEdge Runtime on my local machine (to act it like as a simulated device)
- Docker for windows is installed, up and running
(Everything works well till here, as i checked the status of `Get-Service iotedge` command)
- Set up the Device module and used this `mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0` as an image

after setting up the module on Microsoft Azure portal, edgeHub Module goes into back-off state. i have seen this issue [IOT-Edge Hub back-off state](https://github.com/Azure/iot-edge-v1/issues/531) and tried to restart docker as some of the comments suggested, but all in vain. 
i have also run the `docker logs edgeAgent` command to show you some logs, which are attached with this post.
[logs.txt](https://github.com/Azure/iot-edge-v1/files/2339847/logs.txt)

Azure portal Status  
![2](https://user-images.githubusercontent.com/6631670/44910133-7d337480-ad3b-11e8-89b0-de072483f387.png)

![1](https://user-images.githubusercontent.com/6631670/44910142-8ae8fa00-ad3b-11e8-85b2-6f1882bbc1ed.PNG)

iotedgeruntime status

![3](https://user-images.githubusercontent.com/6631670/44910147-93d9cb80-ad3b-11e8-896e-3af926b69599.PNG)

**Comment by damonbarry** [comment]
When you followed the steps in the linked document, did you set up IoT Edge to use Linux containers, or Windows?

The exceptions in the log do seem to point to a Docker for Windows error. You tried to restart Docker and it didn't work...can you also try to do a factory reset of Docker? Open the Docker Settings windows, click the Reset tab, and click "Reset to factory defaults...". Note this will delete all **containers and images** on your machine.

**Comment by BilalAkmal47** [comment]
First of all thanks for your reply.

i have installed the iotedgeruntime with windows containers. as i am using Windows 10. following is the command that i have used. 

`. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; 
Install-SecurityDaemon -Manual -ContainerOs Windows`

PS: i have also restart the docker and even reset it to factory default. but nothing helped :(

**Comment by damonbarry** [comment]
Ok. Are you getting the _same_ error (same callstack) _every_ time you try this scenario?

There is a Docker for Windows issue (https://github.com/docker/for-win/issues/1745) that sounds similar to yours...do you perhaps have another server on your Windows 10 box that is listening on port 443? You can find out by opening an administrator command prompt and issuing the following command:

```
netstat -a -p TCP -n | find "LISTENING"
```

**Comment by veyalla** [comment]
Hi @BilalAkmal47 - By default, the edge hub tries to bind to ports 443, 8883 and 5671 to accept connections from downstream devices. As port 443 is already in use, it fails and seems like Windows containers throws a generic error.

If you don't intend to use the edge device as a gateway, you can prevent edge hub from trying to bind to 443 by following instructions at https://github.com/MicrosoftDocs/azure-docs/issues/13531#issuecomment-414032497

Please try that and let us know if it helped.

**Comment by BilalAkmal47** [comment]
Hi, Thanks for your response @veyalla. i have changed the setmodule configurations and removed port binding on 443.
after this my iotedge runtime stop responding and service failed to start. i coudlnt figured it out, that why this happened. i uninstalled the runtime and installed it again. now the error has changed. see the logs.

[logs.txt](https://github.com/Azure/iotedge/files/2365494/logs.txt)

**Comment by myagley** [comment]
Does this still reproduce?

**Comment by myagley** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen.
