### ISSUE TITLE
Support for new Windows 10 versions

### ISSUE THREAD

**Issue by grahamehorner** [Azure/iotedge#2400]
Please can you advise on when/if Azure IoT Edge will support newer versions on the Windows 10 operating system; we have a number of projects that require us to use Windows 10 1903 build 18362.418 however this prevents use from using Azure IoT Edge for other projects
```
The container host is on unsupported build version 18362.
Please use a container host running one of the following build versions for running Windows containers:
17763

The prerequisites for installation of the IoT Edge Security daemon are not met. Please fix all known issues before rerunning this script.
```

**Comment by veyalla** [comment]
@grahamehorner At this time there are no plans to support non LTSC Windows versions, unfortunately.
