### ISSUE TITLE
Edge Agent crashes on boot - BadImageFormatException

### ISSUE THREAD

**Issue by xtellurian** [Azure/iotedge#241]
## Expected Behavior
Edge Agent container should start normally.

## Current Behavior
Edge Agent crashes on boot, even after container is deleted.

## Steps to Reproduce

1. Run $ sudo docker run -it  mcr.microsoft.com/azureiotedge-agent:1.0 

### Device (Host) Operating System
Raspian Lite, Raspberry Pi 3

### Architecture
arm32v7

### Container Operating System
Linux Containers

#### iotedged
iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)

#### Edge Agent
1.0

#### Edge Hub
N/A

#### Docker
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Wed Jun 27 00:53:52 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Tue Jun 26 23:27:27 2018
  OS/Arch:      linux/arm
  Experimental: false

## Logs
 $ iotedge logs edgeAgent
[2018-09-04 04:46:02 +00:00]: Starting Edge Agent
[09/04/2018 04:46:03.386 AM] Edge Agent Main()
System.BadImageFormatException: Could not load file or assembly 'System.ObjectModel, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.ObjectModel, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.Main() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 31

## Additional Information
Worked on initial install. Did a reboot, (with sudo shutdown -r ) and now the edge agent container doesn't start.

**Comment by dsajanice** [comment]
Could you please provide more details on your workflow? How did you start EdgeAgent the first time? Did you delete EdgeAgent? What did you do before the reboot? Thanks.

**Comment by xtellurian** [comment]
The first time, I simply followed the instructions [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm) - the scripts I have collated into a gist [here](https://gist.github.com/xtellurian/a26ea81dcfd46bb7ea056f984b8aba0d)

Edge agent was started by the Linux service the first time. I used `docker run...` to see if I could reproduce.

I did delete the EdgeAgent using `docker rm ....`

Sorry I haven't been able to reproduce this issue because I'm plagued with _other_ issues. If it helps, I'm trying to run another module with the following container-create options

```
{\"NetworkingConfig\":{\"EndpointsConfig\": {\"host\": {}}},\"HostConfig\": {\"NetworkMode\": \"host\"}}
```

**Comment by xtellurian** [comment]
@dsajanice how is it possible that the container doesn't start? It doesn't seem like edgeAgent has any volumes mounted into the container?

**Comment by dsajanice** [comment]
"Edge agent was started by the Linux service the first time. I used docker run... to see if I could reproduce.

I did delete the EdgeAgent using docker rm ...."

What was the relative order of these operations?

**Comment by xtellurian** [comment]
My suspicion is the root cause is the underlying filesystem was corrupted.
