### ISSUE TITLE
Rocks DB is creating huge log files in the device disk storage. These log files are going to exhaust the device's disk space.

### ISSUE THREAD

**Issue by JesvinJoseph** [Azure/iotedge#2431]
## Expected Behavior
There should be a way to limit the Rocks DB log file size from the cloud

## Current Behavior
There are multiple log files inside the edgeHub folder even with 64 MB. This is going to exhaust my disk storage. I didn't see any option to limit the log file size. In the options file, the property is set like "max_log_file_size=0" AND "keep_log_file_num=1000". My time to live is just 30 minutes.

## Steps to Reproduce
1. Just mount a folder to edgeHub to "[Give modules access to a device's local storage](https://docs.microsoft.com/bs-cyrl-ba/azure/iot-edge/how-to-access-host-storage-from-module)"
2. Make the IoT edge offline to persist the data locally.
3. We can see huge log files are getting created inside the edgeHub folder in the device's local storage.

### Output of `iotedge check`

The iot edge is working in offline mode
<details>
<summary>Click here</summary>

```

√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
× container engine is installed and functional - Error
    Could not communicate with container engine at unix:///var/run/docker.sock.
    Please check your moby-engine installation and ensure the service is running.
    You might need to run this command as root.

2 check(s) succeeded.
1 check(s) raised errors. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS [ Ubuntu 16.04]: 
* Architecture [amd64]: 
* Container OS [ Linux containers]: 

### Runtime Versions
* iotedged [iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)]: 
* Edge Agent [image tag 1.0]: 
* Edge Hub [image tag 1.0]: 
* Docker/Moby [`
Client:
 Version:           3.0.9+azure
 API version:       1.40
 Go version:        go1.12.14
 Git commit:        99c5edceb48d64c1aa5d09b8c9c499d431d98bb9
 Built:             Tue Nov  5 00:55:15 2019
 OS/Arch:           linux/amd64
 Experimental:      false
`]: 

## Additional Information
I have atached an image of the log files created inside the edgeHub folder. Please have a look at the files and its size. the .log files have 64 MB size. looks like this is going to exhaust the disk space. I have striked out the user and group of the file. The folder contains 352MB data. amoung them 301MB is by log files.
![edgeHub](https://user-images.githubusercontent.com/42056590/73452537-5fbc6d00-436a-11ea-918a-433ea1d5bab9.png)

**Comment by varunpuranik** [comment]
@JesvinJoseph - 
RocksDB is used by multiple modules deployed on IoT Edge. Which module are you seeing this issue in? The referenced issue https://github.com/MicrosoftDocs/azure-docs/issues/47054 is related to the Blob store module. Can you please confirm that, that is the module where you are seeing this?

**Comment by JesvinJoseph** [comment]
I have seen the issue in both blob storage and edgeHub. This issue is for the edgeHub module while it persists the messages in local storage during the offline mode. When we mount local storage to the edgeHub module, it will create a folder named **edgeHub** in the local disk storage where it keeps all the logs and data. I have attached a screenshot of the files inside that folder. I can see more than 93% of the volume is consumed by the logs. I will give you one more example. The total size of edgeHub folder is 471MB
![edgeHub](https://user-images.githubusercontent.com/42056590/73653281-1f6e2f00-4689-11ea-8add-c8993f638c42.png)
If you check the files which consume this much of size, they are the logs files. Here you can see there are 6 log files which have size more than 70MB
![edgeHub1](https://user-images.githubusercontent.com/42056590/73653516-99061d00-4689-11ea-9922-060d8dc6180f.png)

**Comment by ancaantochi** [comment]
By default edgeHub and edgeAgent sets the total log files size to **512MB**. 
If you want to set to a lower value you can set an Enviroment variable to the edgeHub module and edgeAgent modules ` RocksDB_MaxTotalWalSize` and set a value in bytes (the default is set to 512 * 1024 * 1024). 

These are the logs that RocksDB creates, when it reaches the max value it will force flushing from logs files to the sst files.

For blob storage module I see that they responded they will fix in the next release.

**Comment by JesvinJoseph** [comment]
@ancaantochi Thank you very much for your help. I will try this option. But I didn't see this in any document. Can you share the link?. If it is not, it will be very helpful if somebody can add this.

**Comment by ancaantochi** [comment]
RocksDB_MaxTotalWalSize env variable is not documented, we are working on documenting multiple setting which are no documented at the moment.
Does the number of sst files drops when the device is back online and it can send messages? Also I assume the total size of the files should be less than what the logs were. You don't need to configure anything for flushing the log files to sst, it is how RocksDb works internally, here is some documentation: 

[https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log](https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log)
[https://github.com/facebook/rocksdb/blob/5.10.fb/include/rocksdb/options.h#L404](https://github.com/facebook/rocksdb/blob/5.10.fb/include/rocksdb/options.h#L404)

Please let me know if you need more details.

**Comment by JesvinJoseph** [comment]
@ancaantochi Thank you for the help. 👍

**Comment by JesvinJoseph** [comment]
@ancaantochi But when I checked the edgeHub folder, there is another file with name **LOG** which is having 3,6 GB size. The device is online and continuously sending data for last 3 days.

**Comment by ancaantochi** [comment]
That file it is a actual debug logs for rocksdb and we left the default settings which means that the file could grow very large. EdgeHub doesn't have a way to set that logs file size (exposed by rocksdb here: [https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L595](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L595)). We will work on having these options exposed to env variables.

**Comment by imZack** [comment]
@ancaantochi Is there a way to disable the "debug log"? Since it doesn't have a max size limit from your comment. What would be the best way to work around this?

**Comment by ancaantochi** [comment]
We don't have a workaround at the moment, but we will add it in 1.0.9 release. By default the log level will be set to None and configurable with an env variable.

**Comment by imZack** [comment]
Looking forward to having 1.0.9, thanks for the update.

**Comment by akiliu00512** [comment]
is it able to turn off rocks db debug log on version 1.0.8.*? we are not able to upgrade the version. Or is it safe to delete these debug log by writing a periodic job?

**Comment by and-rewsmith** [comment]
It is ok to have a task to remove the LOG files, but it is important to know that Rocks DB creates 2 types of log files:
- the write ahead logs which contain the actual data (files like 000420.log) which should not be removed because it could cause data loss
- Rocks db internal logs (files like LOG or LOG.old.<number>) which are ok to be deleted.

**Comment by ancaantochi** [comment]
closing issue, please reopen if you have related questions
