### ISSUE TITLE
CloudProxy timeout operation

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#246]
## Expected Behavior

After cable is plugged or network interface is brought up C2DMessagesLoop should be aware of this event and data routed to $upstream should be pushed to cloud.

## Current Behavior

Once cable is plugged or network interface is brough up C2DMessagesLoop throws timeout exception.
We suspect that this is blocking edge for sending data that queued up once connection was down (If C2D communication is disabled and we run same test after 2 hours data are pushed to cloud).
If iotedge service is restarted it starts pushing data to iothub again.

## Steps to Reproduce

1. Create windows 10 VM machine that is going to be used as a leaf node. It should be in same network as edge VM ( set static IP 10.0.0.2/24). Also deploy to this machine simple app that is using **.net framework 4.6.2** and Microsoft.Azure.Device.Client 1.18
You can use this app 
[C2DApp.zip](https://github.com/Azure/iotedge/files/2352202/C2DApp.zip)
or this code
```
while (!this.cts.IsCancellationRequested)
                {
                    try
                    {
                        message = await deviceClient.ReceiveAsync(TimeSpan.FromSeconds(30));

                        if (message == null)
                        {
                            continue;
                        }

                        await CompleteMessage(deviceClient, message);
                    }
                    catch (TimeoutException tex)
                    {
                        this.logger.ExceptionLog.LogException("Timeout during client.ReceiveAsync", tex);
                        await Task.Delay(TimeSpan.FromSeconds(60));
                    }
                    catch (Exception ex)
                    {
                        try
                        {
                            await deviceClient.RejectAsync(message);
                        }
                        catch (Exception ex2)
                        {
                            this.logger.ExceptionLog.LogException($"Unable to reject message: {message?.MessageId ?? "No MessageId"}", ex2);
                        }
                    }
                }
```

2, Create linux VM (ubuntu 18.04) that is going to have two network interfaces eth0 -> can connect to internet (on my local machine this interface is configured to get ip from dhcp) and eth1 is set to static IP (e.g. 10.0.0.100/24) that allows machine from step one to connect over iotedge proxy to internet.
3. Create module using below code 
[AmqpTemp.zip](https://github.com/Azure/iotedge/files/2350193/AmqpTemp.zip)
and configure routing to send data from this module to go to $upstream
4. Deploy module to iot edge machine
5. Start edge and verify that data are being sent to cloud
6. Start on Windows VM from step 2 - C2DApp .net framework application that is connecting to azure using e.g. connection string
HostName=someiothub.azure-devices.net;DeviceId=somedevice;SharedAccessKey=someaccess;GatewayHostName=**10.0.0.100**
7. login to linux VM and execute docker logs edgeHub --tail 100 -f 
to confirm that request for getting C2D messages are served over proxy

2018-09-04 19:11:01.148 +00:00 [INF] - Start listening for C2D messages for device somedeviceid
2018-09-04 19:11:01.149 +00:00 [INF] - Opened link C2D for somedeviceid

8. Being still on linux VM execute
ifconfig eth0 down
and wait for 2hours
9. Execute ifconfig eth0 up
10. check docker logs edgeHub --tail 100

You should see that the C2DMessagesLoop is still throwing exceptions:
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloudReceiver.C2DMessagesLoop(IClient deviceClient) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 240

### Device (Host) Operating System

Ubuntu 18.04
### Architecture

amd64

### Container Operating System

linux
#### Edge Agent

1.0.1
#### Edge Hub

1.0.1
#### Docker

Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Mon Jun 25 20:43:05 2018
  OS/Arch:      linux/amd64
  Experimental: false

## Logs

When the connection is down CloudProxy is throwing this exception

2018-09-04 20:58:09.662 +00:00 [ERR] - Error receiving message for device adamusoworkp in cloud proxy 19bad27b-fa28-4ac0-963d-7dac6201772b
System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutMessage>b__63_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.CloudProxy.CloudReceiver.C2DMessagesLoop(IClient deviceClient) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs:line 240

Once it is up even for 15 minutes still same exceptions are raised.

[c2dtesting.txt](https://github.com/Azure/iotedge/files/2350329/c2dtesting.txt)

**Comment by AdamMachera** [comment]
#139

**Comment by varunpuranik** [comment]
@AdamMachera - since this is related to C2D messages, it might be a bug in EdgeHub. I am looking into it right now. I will update the thread when I have something.

**Comment by myagley** [comment]
Is this related to #422?

**Comment by AdamMachera** [comment]
Yes, I think it might be connected.
Once fix is applied I would have to test it.

Regards,
Adam

śr., 17 paź 2018 o 21:15 Mike Yagley <notifications@github.com> napisał(a):

**Comment by AdamMachera** [comment]
It seems that version 1.0.4 solves this issue.
