### ISSUE TITLE
Azure Iot Edge self signed certificates

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#2460]
I'm using an Azure Iot Edge as a transparent gateway, and I would like to connect my downstream devices... How can I do it? I used to have the same certificates in both Edge and downstream devices, but with self-signed ones I have no idea how to do it...

**Comment by kkdawkins** [comment]
Hello! 

We have some pretty comprehensive documentation around this exact scenario! Please give this a read and let us know if you have any issues.

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway 

Thanks,
Kevin

**Comment by Ilheu** [comment]
Hi @kkdawkins, I wish you had read my problem more carefully ... 
I was using Iot Edge as a transparent gateway, and suddenly the downstream devices stopped communicating, because there was an update and now I can only get the edge to connect without the certificates , it is generating its own certificates. I asked how can my downstream devices send data to iotedge if they don't have the same certificates, and that is not explained in your documentation. 
With this, my clients are not receiving the data they should.
My downstream devices have the following code: https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/edge_downstream_device.js

**Comment by kkdawkins** [comment]
Provided docs - feel free to reopen if you get stuck/have an issue. Thanks!

**Comment by Ilheu** [comment]
@kkdawkins, the docs that you provided me, have no information about what I asked, I am already using Azure Iot Edge as a transparent device with dev certificates. 
**There is no information how can my downstream devices communicate with iotedge using self-signed certificates.**

**Comment by veyalla** [comment]
See: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-authenticate-downstream-device#register-device-x509-ca-signed

Is this what you're looking for?

**Comment by kkdawkins** [comment]
I apologize, @Ilheu - I misunderstood.
