### ISSUE TITLE
IoTEdge does not start edgeAgent when installed behind proxy

### ISSUE THREAD

**Issue by hartmutbehrens** [Azure/iotedge#247]
The edgeAgent fails to start up after installing the IoT Edge runtime on a server behind a proxy  (https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux) 

## Expected Behavior
The edgeAgent should start up and communicate with the IoT hub

## Current Behavior
edgeAgent fails to start up

## Steps to Reproduce

1. Follow steps in https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux on a computer behind a proxy

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
x86_64

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)

#### Edge Agent
N/A - does not download, but /etc/iotedge/config.yaml is configured to ask for 1.0

#### Edge Hub
N/A - does not download because edgeAgent does not download

#### Docker
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Mon Jun 25 20:43:05 2018
  OS/Arch:      linux/amd64
  Experimental: false

## Logs
iotedge.service - Azure IoT Edge daemon
     Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-09-05 08:48:33 SAST; 22min ago
     Docs: man:iotedged(8)
 Main PID: 15243 (iotedged)
    Tasks: 6
   Memory: 3.3M
      CPU: 46ms
   CGroup: /system.slice/iotedge.service
           ââ15243 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Sep 05 09:09:34 anglowps iotedged[15243]: 2018-09-05T07:09:34Z [WARN] -         caused by: Connection refused (os error 111)
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [INFO] - Checking edge runtime status
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [INFO] - Creating and starting edge runtime module edgeAgent
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [ERR!] - Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [WARN] - Error in watchdog when checking for edge runtime status:
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [WARN] - Identity error
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [WARN] -         caused by: IoT Hub service error
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [WARN] -         caused by: Core error
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [WARN] -         caused by: Hyper error
Sep 05 09:10:33 anglowps iotedged[15243]: 2018-09-05T07:10:33Z [WARN] -         caused by: Connection refused (os error 111)

## Additional Information
1. Configure docker proxy settings using this: https://docs.docker.com/config/daemon/systemd/
2. Confirmed that `docker pull mcr.microsoft.com/azureiotedge-agent:1.0` is working

**Comment by damonbarry** [comment]
iotedged isn't proxy-aware yet. We're working on it, and hope to make it available soon. The proxy issue is being tracked by #230, so I'll close this one.
