### ISSUE TITLE
EdgeHub sends the online messages only after sending all the locally persisted messages. How can we specify the order(FIFO or LIFO) of the message?

### ISSUE THREAD

**Issue by JesvinJoseph** [Azure/iotedge#2486]
## Expected Behavior
Example Situation:
We have a data acquisition module that sends data in every second to the edgeHub. Device lost the connectivity for 12 days and we have 1 million messages locally persisted by the edgeHub. When the device gets the connectivity back on the 13th day, we need to send the live messages at that moment ASAP to the cloud and the edgeHub should send these 1 million messages in between these online messages. 

Brief:- The offline messages should not affect the online message flow to the cloud.

## Current Behavior
Now the edgeHub will send all these 1 million messages first, after that, it will start sending the live messages.

### Device Information
* Host OS [Ubuntu 16.04]: 
* Architecture [amd64]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [`iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)`]: 
* Edge Agent [image tag 1.0]: 
* Edge Hub [image tag 1.0]: 
* Docker/Moby [`
Client:
 Version:           3.0.9+azure
 API version:       1.40
 Go version:        go1.12.14
 Git commit:        99c5edceb48d64c1aa5d09b8c9c499d431d98bb9
 Built:             Tue Nov  5 00:55:15 2019
 OS/Arch:           linux/amd64
 Experimental:      false`]:

**Comment by varunpuranik** [comment]
@JesvinJoseph -
I would like to understand your scenario a bit more. Specifically, do you want the older messages also to eventually make it to the cloud, or do you only care about the "live" messages? 
Changing order of messages to lifo has other implications such as old messages getting starved, and if and when they get processed will depend on the incoming rate. 
One way to only get newer messages is to adjust the TTL setting that the EdgeHub exposes, so that older messages get deleted, and only the newer ones are processed.

**Comment by JesvinJoseph** [comment]
@varunpuranik Thanks for the reply.
We want the older messages also to eventually make it to the cloud.
We need all the messages. So we can't delete them. So for the older messages, FIFO is also fine. But we have higher priority for the live messages than older messages.

**Comment by varunpuranik** [comment]
@JesvinJoseph - thanks for the details. 
One clarification - how do you distinguish the newer messages from the older ones? Do you have a timestamp field in the message, set by the device? 
Also, how do you define "live" messages?

**Comment by JesvinJoseph** [comment]
@varunpuranik , Yes we have a timestamp in the message header set by the device. We have an IoT hub triggered azure function which compared the current UTC with the timestamp in the message header. If the difference is less than 1 minute, its a live message and otherwise it is an offline message.

The messages that are generated by the data acquisition module when there is an active internet connection is considered to be "Live" message. If there are no offline messages, the live messages will reach the IoT Hub immediately. 

We have a live dashboard that shows real-time values. Rest all data are sent to different pass components for analytics and batch processing.

**Comment by varunpuranik** [comment]
@JesvinJoseph - thanks for the details about your scenario. We will have to look at how to support this in IoT Edge. I will keep you posted when we have an update. 
Thanks!

**Comment by veyalla** [comment]
Please file or vote for existing feature request at https://feedback.azure.com/forums/907045-azure-iot-edge
