### ISSUE TITLE
IoT Edge on Win10 stable connectivity to IoT Central

### ISSUE THREAD

**Issue by mitkox** [Azure/iotedge#2488]
## Expected Behavior
FANUC connector as downstream device of IoT Edge on Win10 to send data to IoT Central 

## Current Behavior
The IoT Edge is stopping sending data 20mins after start 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install IoT Edge on Win10 
2. Connect it to IoT Central 
3. Install the Temp Simulation Module
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Windows 10 
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.8.5
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.8.5
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.8.5
* Docker/Moby [run `docker version`]: 19.3.5

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

PS C:\Users\sulzerpoc> iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
× config.yaml has well-formed connection string - Error
    Device is not using manual provisioning, so Azure IoT Hub hostname needs to be specified with --iothub-hostname
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file C:\ProgramData\iotedge-moby\config\daemon.json
        caused by: The system cannot find the path specified. (os error 3)
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file C:\ProgramData\iotedge-moby\config\daemon.json
        caused by: The system cannot find the path specified. (os error 3)

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
‼ host can connect to and perform TLS handshake with IoT Hub AMQP port - Warning
    skipping because of previous failures
‼ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - Warning
    skipping because of previous failures
‼ host can connect to and perform TLS handshake with IoT Hub MQTT port - Warning
    skipping because of previous failures
‼ container on the IoT Edge module network can connect to IoT Hub AMQP port - Warning
    skipping because of previous failures
‼ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Warning
    skipping because of previous failures
‼ container on the IoT Edge module network can connect to IoT Hub MQTT port - Warning
    skipping because of previous failures
√ Edge Hub can bind to ports on host - OK

12 check(s) succeeded.
3 check(s) raised warnings.
1 check(s) raised errors.
6 check(s) were skipped due to errors from other checks.

</details>

<details>
<summary>edge-agent logs</summary>

PS C:\Users\sulzerpoc> iotedge logs edgeAgent
2020-02-06 18:16:41.388 +00:00 Edge Agent Main()
<6> 2020-02-06 18:16:41.689 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-02-06 18:16:41.914 +00:00 [INF] - Version - 1.0.8.5.28262167 (b5de730c6020b852f9636b7117138de6c6fced36)
<6> 2020-02-06 18:16:41.914 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-02-06 18:16:41.995 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false}
<6> 2020-02-06 18:16:42.590 +00:00 [INF] - Started operation refresh twin config
<6> 2020-02-06 18:16:42.629 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2020-02-06 18:16:43.420 +00:00 [INF] - Created persistent store at C:\Windows\TEMP\edgeAgent
<6> 2020-02-06 18:16:43.952 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2020-02-06 18:16:44.077 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2020-02-06 18:16:44.169 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 168.
<6> 2020-02-06 18:16:44.578 +00:00 [INF] - Plan execution started for deployment 2
<6> 2020-02-06 18:16:44.627 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module edgeHub]\n  [Start module edgeHub]\n)"
<6> 2020-02-06 18:16:44.635 +00:00 [INF] - Executing command: "Create module edgeHub"
<6> 2020-02-06 18:16:44.834 +00:00 [INF] - Executing command: "Start module edgeHub"
<6> 2020-02-06 18:16:46.114 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module CyberTech]\n  [Start module CyberTech]\n)"
<6> 2020-02-06 18:16:46.114 +00:00 [INF] - Executing command: "Create module CyberTech"
<6> 2020-02-06 18:16:46.745 +00:00 [INF] - Executing command: "Start module CyberTech"
<6> 2020-02-06 18:16:49.559 +00:00 [INF] - Plan execution ended for deployment 2
<6> 2020-02-06 18:16:49.997 +00:00 [INF] - Updated reported properties
<6> 2020-02-06 18:16:55.190 +00:00 [INF] - Updated reported properties
<4> 2020-02-06 18:34:17.473 +00:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in C:\agent\_work\7\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 117
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\7\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\versioning\ModuleManagementHttpClientVersioned.cs:line 124
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.GetModules[T](CancellationToken cancellationToken) in C:\agent\_work\7\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\version_2019_01_30\ModuleManagementHttpClient.cs:line 137
   at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironment.GetModulesAsync(CancellationToken token) in C:\agent\_work\7\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Docker\DockerEnvironment.cs:line 50
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.GetCurrentModuleSetAsync(CancellationToken token) in C:\agent\_work\7\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 227
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in C:\agent\_work\7\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 117
<6> 2020-02-06 18:34:17.663 +00:00 [INF] - Updated reported properties
<6> 2020-02-06 18:34:22.823 +00:00 [INF] - Updated reported properties
<6> 2020-02-06 19:16:42.590 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-02-06 19:16:42.615 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 172.
<6> 2020-02-06 19:16:42.616 +00:00 [INF] - Successfully completed periodic operation refresh twin config
</details>

<details>
<summary>edge-hub logs</summary>

PS C:\Users\sulzerpoc> iotedge logs edgeHub
2020-02-06 18:16:46.489 +00:00 Edge Hub Main()
[02/06/2020 06:16:48.428 PM] Found intermediate certificates: [CN=iotedged workload ca:5/4/2020 10:44:28 AM],[CN=Test Edge Device CA:5/4/2020 10:44:28 AM],[CN=Test Edge Owner CA:5/4/2020 10:44:28 AM]
<6> 2020-02-06 18:16:50.541 +00:00 [INF] - Created persistent store at C:\Windows\TEMP\edgeHub
<6> 2020-02-06 18:16:50.617 +00:00 [INF] - Initializing Edge Hub
<6> 2020-02-06 18:16:50.618 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-02-06 18:16:50.620 +00:00 [INF] - Version - 1.0.8.5.28262167 (b5de730c6020b852f9636b7117138de6c6fced36)
<6> 2020-02-06 18:16:50.620 +00:00 [INF] - OptimizeForPerformance=True
<6> 2020-02-06 18:16:50.625 +00:00 [INF] - Loaded server certificate with expiration date of "2020-05-04T10:44:28.0000000+00:00"
<6> 2020-02-06 18:16:50.727 +00:00 [INF] - Created new message store
<6> 2020-02-06 18:16:50.863 +00:00 [INF] - Created device scope identities cache
<6> 2020-02-06 18:16:50.869 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2020-02-06 18:16:50.896 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-02-06 18:16:50.996 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2020-02-06 18:16:51.299 +00:00 [INF] - Initialized storing twin manager
<6> 2020-02-06 18:16:51.333 +00:00 [INF] - Initializing configuration
<6> 2020-02-06 18:16:51.360 +00:00 [INF] - New device connection for device IoTEdge/$edgeHub
<6> 2020-02-06 18:16:51.640 +00:00 [INF] - Attempting to connect to IoT Hub for client IoTEdge/$edgeHub via AMQP...
<6> 2020-02-06 18:16:51.797 +00:00 [INF] - Starting periodic operation Get EdgeHub config...
<6> 2020-02-06 18:16:51.849 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2020-02-06 18:16:51.850 +00:00 [INF] - Initialized edge hub configuration
<6> 2020-02-06 18:16:51.874 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2020-02-06 18:16:52.113 +00:00 [INF] - Scheduling server certificate renewal for "2020-05-04T10:41:58.0000737Z".
<6> 2020-02-06 18:16:52.115 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2020-02-06 18:16:52.121 +00:00 [INF] - Starting MQTT head
<6> 2020-02-06 18:16:52.370 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2020-02-06 18:16:52.587 +00:00 [INF] - Starting AMQP head
<6> 2020-02-06 18:16:52.614 +00:00 [INF] - Started MQTT head
<6> 2020-02-06 18:16:52.772 +00:00 [INF] - Started AMQP head
<6> 2020-02-06 18:16:52.775 +00:00 [INF] - Starting HTTP head
<6> 2020-02-06 18:16:52.971 +00:00 [INF] - User profile is available. Using '"C:\\Users\\ContainerUser\\AppData\\Local\\ASP.NET\\DataProtection-Keys"' as key repository and Windows DPAPI to encrypt keys at rest.
<6> 2020-02-06 18:16:53.012 +00:00 [INF] - Creating key {cbb8b77e-a1d5-46f6-8217-3fa5eebfa874} with creation date 2020-02-06 18:16:53Z, activation date 2020-02-06 18:16:52Z, and expiration date 2020-05-06 18:16:52Z.
<6> 2020-02-06 18:16:53.079 +00:00 [INF] - Writing data to file '"C:\\Users\\ContainerUser\\AppData\\Local\\ASP.NET\\DataProtection-Keys\\key-cbb8b77e-a1d5-46f6-8217-3fa5eebfa874.xml"'.
<6> 2020-02-06 18:16:53.141 +00:00 [INF] - Exiting disconnected state
<6> 2020-02-06 18:16:53.146 +00:00 [INF] - Received device connected callback
<6> 2020-02-06 18:16:53.161 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2020-02-06 18:16:53.161 +00:00 [INF] - Processing subscriptions for client IoTEdge/$edgeHub.
<6> 2020-02-06 18:16:53.178 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-02-06 18:16:53.189 +00:00 [INF] - Entering connected state
<6> 2020-02-06 18:16:53.193 +00:00 [INF] - Cloud connection for IoTEdge/$edgeHub is True
<6> 2020-02-06 18:16:53.207 +00:00 [INF] - Connection status for IoTEdge/$edgeHub changed to ConnectionEstablished
<6> 2020-02-06 18:16:53.210 +00:00 [INF] - Client IoTEdge/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2020-02-06 18:16:53.217 +00:00 [INF] - Created cloud proxy for client IoTEdge/$edgeHub via AMQP, with client operation timeout 20 seconds.
<6> 2020-02-06 18:16:53.230 +00:00 [INF] - Initialized cloud proxy 4137f25c-19ec-41e4-8a5b-c8ea3dc78937 for IoTEdge/$edgeHub
<6> 2020-02-06 18:16:53.236 +00:00 [INF] - Created cloud connection for client IoTEdge/$edgeHub
<4> 2020-02-06 18:16:53.619 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2020-02-06 18:16:53.662 +00:00 [INF] - Started HTTP head
<6> 2020-02-06 18:16:53.724 +00:00 [INF] - Updated reported properties for IoTEdge/$edgeHub
<6> 2020-02-06 18:16:53.885 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2020-02-06 18:16:53.918 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2020-02-06 18:16:54.105 +00:00 [INF] - Set the following 1 route(s) in edge hub
<6> 2020-02-06 18:16:54.105 +00:00 [INF] - route: FROM /* INTO $upstream
<6> 2020-02-06 18:16:54.107 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2020-02-06 18:16:54.107 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2020-02-06 18:16:54.108 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2020-02-06 18:16:55.776 +00:00 [INF] - New token received on the Cbs link
<6> 2020-02-06 18:16:55.945 +00:00 [INF] - Client IoTEdge/CyberTech in device scope authenticated locally.
<6> 2020-02-06 18:16:55.961 +00:00 [INF] - New device connection for device IoTEdge/CyberTech
<6> 2020-02-06 18:16:55.971 +00:00 [INF] - Bind device proxy for device IoTEdge/CyberTech
<6> 2020-02-06 18:16:55.972 +00:00 [INF] - Initialized device listener in the AMQP protocol head for IoTEdge/CyberTech
<6> 2020-02-06 18:16:55.980 +00:00 [INF] - Opened link Events for IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.064 +00:00 [INF] - Opened link MethodReceiving for IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.069 +00:00 [INF] - Opened link MethodSending for IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.078 +00:00 [INF] - Attempting to connect to IoT Hub for client IoTEdge/CyberTech via AMQP...
<6> 2020-02-06 18:16:56.128 +00:00 [INF] - Opened link TwinReceiving for IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.129 +00:00 [INF] - Opened link TwinSending for IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.155 +00:00 [INF] - Cloud connection for IoTEdge/CyberTech is True
<6> 2020-02-06 18:16:56.155 +00:00 [INF] - Connection status for IoTEdge/CyberTech changed to ConnectionEstablished
<6> 2020-02-06 18:16:56.155 +00:00 [INF] - Client IoTEdge/CyberTech connected to cloud, processing existing subscriptions.
<6> 2020-02-06 18:16:56.155 +00:00 [INF] - Created cloud proxy for client IoTEdge/CyberTech via AMQP, with client operation timeout 20 seconds.
<6> 2020-02-06 18:16:56.155 +00:00 [INF] - Initialized cloud proxy 03dc13c0-8821-44d8-a2da-02698d0de80b for IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.155 +00:00 [INF] - Created cloud connection for client IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.279 +00:00 [INF] - Opened link ModuleMessages for IoTEdge/CyberTech
<6> 2020-02-06 18:16:56.430 +00:00 [INF] - Updated reported properties for IoTEdge/$edgeHub
<6> 2020-02-06 18:21:51.878 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 18:26:51.868 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 18:31:51.865 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 18:36:51.876 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 18:41:51.877 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 18:46:51.127 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-02-06 18:46:51.248 +00:00 [INF] - Cleaned up 357 messages from queue for endpoint iothub and 357 messages from message store.
<6> 2020-02-06 18:46:51.876 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 18:51:51.886 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 18:56:51.882 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:01:51.875 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:06:51.873 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:07:56.024 +00:00 [INF] - New token received on the Cbs link
<6> 2020-02-06 19:07:56.025 +00:00 [INF] - Token updated for IoTEdge/CyberTech
<6> 2020-02-06 19:11:51.880 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:16:51.883 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:16:53.727 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2020-02-06 19:16:54.114 +00:00 [INF] - Starting periodic operation Get EdgeHub config...
<6> 2020-02-06 19:16:54.143 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2020-02-06 19:16:54.147 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config
<6> 2020-02-06 19:16:54.280 +00:00 [INF] - Updated reported properties for IoTEdge/$edgeHub
<6> 2020-02-06 19:17:21.270 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-02-06 19:17:21.310 +00:00 [INF] - Cleaned up 143 messages from queue for endpoint iothub and 143 messages from message store.
<6> 2020-02-06 19:21:51.883 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:26:51.876 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:31:51.877 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:36:51.886 +00:00 [INF] - Reauthenticating connected clients
<6> 2020-02-06 19:41:51.879 +00:00 [INF] - Reauthenticating connected clients

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by kkdawkins** [comment]
Can we get iotedged logs?

**Comment by philipktlin** [comment]
Please provide tempSensor module log as well.  By default, tempSensor will send only 500 messages.  If you want to send unlimited messages, you need to update "MessageCount" environment variable to -1.

**Comment by mitkox** [comment]
3rd party module software issue. The IoT Edge on Win was working ok.
