### ISSUE TITLE
Could not get an active Iot Hub connection for device machine-edge/AmqpTemp

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#250]
## Expected Behavior

Once module is no longer used because new deployment occur system should stream data for other modules that are pushing data to $upstream

## Current Behavior

Data from other modules are not passed to $upstream due to "Could not get an active Iot Hub connection for device machine-edge/AmqpTemp"

## Steps to Reproduce

1. Deploy to edge custom module
[AmqpTemp.zip](https://github.com/Azure/iotedge/files/2356662/AmqpTemp.zip)
2. Stop network interface on edge so some of the messages queue up
3. Deploy to edge new deployment.json that removes custom module from step 1
4. Start network interface and see that module from step 1 is no longer present
5. In docker logs edgeHub I'm seeing 
Could not get an active Iot Hub connection for device machine-edge/AmqpTemp
and data from other modules cannot be pushed

### Device (Host) Operating System

Ubuntu18.04
### Architecture

amd64
### Container Operating System

Linux
#### Edge Agent

1.0.1
#### Edge Hub

1.0.1
## Logs

2018-09-06 10:47:58.030 +00:00 [WRN] - Could not get an active Iot Hub connection for device machine-edge/AmqpTemp
2018-09-06 10:47:58.030 +00:00 [WRN] - Could not get an active Iot Hub connection for device machine-edge/AmqpTemp

**Comment by varunpuranik** [comment]
@AdamMachera - this is currently a known issue/limitation of the Edge runtime. We are working on a fix for this right now, and should be available in one of our upcoming releases (the fix has been merged with master). I will update this thread when we publish the images.

**Comment by myagley** [comment]
This should be fixed with 1.0.2 of the Edge Hub. Is it possible to verify? Thanks.

**Comment by myagley** [comment]
This issue should be addressed by the 1.0.2 release. I'm going to close it due to inactivity but please feel free to reopen.
