### ISSUE TITLE
Issue using module buildOptions

### ISSUE THREAD

**Issue by Walobyte** [Azure/iotedge#2537]
While attempting to recreate what was deemed 'Closed' here: https://github.com/Microsoft/vscode-azure-iot-edge/issues/95

My goal is to have an azure yaml pipeline pass an (argument) access token into my docker file so that it can complete a dotnet restore with the provided arguments (essentially to authenticate to a private nuget feed). 

(for testing purposes, I have this working with a system access token hard coded as an ARG value in the docker file.)

With standalone docker, this should be faily simply, just define the docker command

`
 docker build --build-arg some_variable_name=a_value
`

From module.json buildOptions:

`"buildOptions":[
     "--build-args some_variable_name=${a_value_placeholder}"
]`

${a_value_placeholder} is described in my .env file which would be populated in my yaml pipeline.

When iotedge calls docker build, no arguments are supplied.

`
docker build --rm  "C\...\dockerfile" -t localhost:5000/module:0.0.1
`

Any insights?

**Comment by varunpuranik** [comment]
@Walobyte - are you running into this issue while building your module in VSCode? If so, can you log an issue on the IoT Edge VSCode repo? https://github.com/microsoft/vscode-azure-iot-edge

**Comment by Walobyte** [comment]
Sure. Thanks
