### ISSUE TITLE
MetricsCollector module should react to device twin changes

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#2551]
## Expected Behavior
If the device twin is changed, means the scraped prometheus endpoints chance, e.g. because a new module is added, the MetricsCollector module should recognize that.

## Current Behavior
At the moment the MetricsCollector just evaluates it's device twin on start-up. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Deploy MetricsCollector module
2. Add another edge module exposing a prometheus endpoint
3. Add the prometheus endpoint to the endpoints-list of the MetricsCollector device twin
4. Note that the new endpoint is not scraped

## Additional Information
Please note that the current behaviour basically mean you have to stop/start the MetricsCollector every time the list of prometheus endpoints changes. This is very inconvenient if you have no direct access to the edge and are forced to do two deployments via the Azure portal just to stop and start the MetricsCollector module in order to refresh the prometheus endpoint list.

**Comment by veyalla** [comment]
@alaendle - this is module is not officially supported. It is part of the community sample, please open an issue at the sample's repo. Thanks!

**Comment by alaendle** [comment]
Well - the code at least was copied/transferred to this repository, so my guess was that this repository also took over responsibility (who guarantees that changes in the upstream repo also got included here? My assumption is that if the issue gets fixed upstream, I'm asked to open an issue here to apply the fix 😄 ).

https://github.com/Azure/iotedge/blob/bb4984e6b2cd643fb0e5652797067f61d21459c0/edge-modules/MetricsCollector/Program.cs#L71-L75

@veyalla However, I will create the issue in your repo...
