### ISSUE TITLE
Is there a plan to expand the supported windows 10 versions to install IoT Edge Runtime?

### ISSUE THREAD

**Issue by LucasPortoUFCG** [Azure/iotedge#2566]
"For development and test scenarios, Azure IoT Edge with Windows containers can be installed on any version of Windows 10 or Windows Server 2019 (build 17763) that supports the containers feature".

The build 17763 reffers to windows 10 version 1809.

I would like to know if there is a way to install IoT Edge runtime on windows 10 version 1909.

**Comment by veyalla** [comment]
Thanks for the question, at this time only 1809 LTSC Windows version (17763) is planned to be supported.

**Comment by rgamage** [comment]
Sure would be nice if the docs mentioned this odd limitation on the supported version of windows 10. See this issue here: https://github.com/MicrosoftDocs/azure-docs/issues/34581
