### ISSUE TITLE
IoT Edge Install fails because it can't get the IP Address of the host

### ISSUE THREAD

**Issue by ckcampbell248** [Azure/iotedge#2587]
#Expected Behavior
Initialize-IoTEdge step should have completed and started the edgeAgent container. 

## Current Behavior
Initialize-IoTEdge failed with "Initialize-IoTEdge : The property 'IPAddress' cannot be found on this object. Verify that the property exists."

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Ensure you are running the latest version of Docker Desktop (I'm on 2.2.0.3 (42716))
2. Follow the steps at: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-linux. 
3. Initialize-IoTEdge will fail

## Context (Environment)
Windows 10 build 19041 / Docker Desktop 2.2.0.3 (42716)

### Output of `iotedge check`
Would not run because install didn't complete

### Please provide any additional information that may be helpful in understanding the issue.

After the failure, I looked into the IotEdgeSecurityDaemon.ps1 script located at aka.ms/iotedge-win. To assign the IP address, it is referencing a network connection on the local machine called "vEthernet (DockerNAT)". This does not exist on my machine. Instead I have "vEthernet (Default Switch)". I downloaded the script to my local machine and modified it to look for "vEthernet (Default Switch)". After doing this, running Initialize-IotEdge pointing at the local version of the script worked and IoT Edge is now running on my machine. 

Per this issue: https://github.com/docker/for-win/issues/5538, Docker has removed the DockerNAT connection. 

After the script change and completion of Initialize-IotEdge, the edgeAgent is running and I can now run iotedge check. I have deployed a module and things seem to be working so it appears that the removal of DockerNAT is the issue.

**Comment by lfitchett** [comment]
Thank you for your report. Feel free to open a pull request to fix the issue! If you don't want to do so, let me know and I'll file it as a bug in our backlog. 

Note that since this is a dev only scenario (no production impact) it will be lower priority.

**Comment by sandervandevelde** [comment]
I and several others encountered the same issue today also during a workshop. Is this filed as a bug already?

Although this is a dev only scenario, this is the only scenario for new IoT Edge developers to setup a proper dev environment (on Windows). So it's 'blocking' for the future generation of IoT Edgers :-)   

![image](https://user-images.githubusercontent.com/694737/76266901-46f87e80-6269-11ea-8e35-06a50c8fd156.png)

**Comment by hvp004** [comment]
Why is this close? Is there a solution to this?

**Comment by veyalla** [comment]
This is fixed in the [1.0.9 release](https://techcommunity.microsoft.com/t5/internet-of-things/iot-edge-1-0-9/ba-p/1237100). Closing..
