### ISSUE TITLE
moby_runtime is not applying config from /etc/iotedge/config.yaml

### ISSUE THREAD

**Issue by manueljesusrd** [Azure/iotedge#2591]
Moby is applying a configuration for its virtual interface that is conflicting with out client's local private networking. In order to solve it, I've changed docker's bridge config in its daemon.json file and the changes are working without a problem. Nevertheless, I noticed that we're still getting a "br-" interface with the network configured as 172.17.X.X. It seems to be the one that moby_runtime creates related to the azure iot edge:
![image](https://user-images.githubusercontent.com/49117973/75339135-353dd100-5890-11ea-8813-0e2575642b50.png)

I've followed the instructions contained in the doc (https://github.com/Azure/iotedge/blob/master/doc/networking.md , which by the way is still wrong and it was solved by this post -> https://github.com/Azure/iotedge/issues/2183#issuecomment-569155844) in order to change that virtual interface, but I'm getting no results: 
![image](https://user-images.githubusercontent.com/49117973/75339215-661e0600-5890-11ea-8aab-72696f1d197e.png)

I'm using this config in config.yaml:
![image](https://user-images.githubusercontent.com/49117973/75339426-cad96080-5890-11ea-850a-aae3fa0bfda4.png)

And this config for docker:
![image](https://user-images.githubusercontent.com/49117973/75339793-784c7400-5891-11ea-8e41-24ab2fb1fa55.png)

After the changes I've:
- Stopped iotedge service
- Remove network azure-iot-edge from docker networks
- Restarted both docker and iotedge daemon services

After all these tests I'm getting docker0 correctly but still getting the virtual interface "br-" with the wrong routes.

**Comment by lfitchett** [comment]
1. Are you using version 109-rc1 or higher? This feature was only added in 109. 
1. Have you ran docker network prune or docker system prune -a while iotedge was stopped?

If you still have issues, please show the output of the daemon's logs (journalctl -u iotedge -e)

**Comment by manueljesusrd** [comment]
Hi @lfitchett 
We were using version 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0). This version is installed by default when using **sudo apt-get install iotedge**, so I guessed it was OK. I updated to 1.0.9-rc5 and now it's working!
Thank you for your help!
