### ISSUE TITLE
Question: Edge Module Logs Remote Access?

### ISSUE THREAD

**Issue by thnk2wn** [Azure/iotedge#2596]
From what I can tell, I'm assuming there's no way to access Edge module logs remotely from the IoT hub / Azure cloud side without ssh access to the device (usually no-go outside of dev)?

Best I can tell the logs need to be sent, either using a container engine log nozzle of sorts like  https://github.com/veyalla/logspout-loganalytics or have each module send message to a logging module which then sends upstream to the hub.

Presumably the logspout approach would be better as it could support both Edge runtime system modules and custom ones in theory.

If not already there, it might be nice though if the Edge runtime exposed direct method calls or other mechanisms to remotely query these logs without having to develop custom code to send that data which may or may not be accessed.

**Comment by veyalla** [comment]
[Built-in log pull](https://github.com/Azure/iotedge/blob/master/doc/built-in-logs-pull.md) functionality via edgeAgent direct methods is available as an experimental feature. We intend to make it generally available soon.

Is this what you're looking for?

**Comment by thnk2wn** [comment]
Thanks @veyalla. That looks like it might be helpful, although not quite what I'm looking for. That seems more like pushing logs than pulling them even though initiated from outside the device. Also we're not really looking to upload to blob storage but return a subset of logs directly from the device container logs back as the direct method call response. Or to have that data flow as telemetry events to the hub (tagged a certain way) so that we can use hub message routing to send where we'd like.

Today in our non-edge IoT setup we have a custom Serilog sink that sends logs from our apps via hub telemetry events that get routed to service bus queues, picked up from there by cloud apps that then posted to Seq. But we also have a custom Agent process that polls docker logs via docker .net given a since timestamp more as a near real time fallback.

We also send log events in Serilog compact json format for the additional log enrichment so I'm not sure how well it'd work with the format indicated in that markdown.

I was just curious if the Edge agent provided some kind of on-demand log pull (not upload) or generic transmission to the hub where it could be read without requiring a specific form of persistence. We can work around either way, just might be able to maintain less custom code.

Some questions about this feature:
- Would this work for edge system modules as well?
- Any idea of pricing impacts for this?
- Is the implementation effectively like hub file uploads supported today?
- Would such uploaded logs ever be available in the Azure portal?
  - For example, we had a problem with container registry mismatch to a deployment template and container registry credential issues. Both of these caused edge runtime not to be able to install modules but from the Azure portal side, we were blind to the issues and generally can't ssh into devices

**Comment by veyalla** [comment]
Re: your questions:
* Yes 
* For the uploaded data is not counted as telemetry so it is cost of direct method + network egress + storage in blobstore
* Yes, except IoT Hub doesn't support file upload natively for module identities. When it does, we'll support uploading to the associated storage account
* Not yet, we're looking into it though.

The logs returned in the direct method response is actually added in 1.0.9 (GetLogs) and we'll update the md files with it soon. 

If you want to try it out GetLogs take a look at [this](https://labs.iotedge.dev/codelabs/deploy-iotedge-vm/index.html?index=..%2F..index#0) lab and [this](https://labs.iotedge.dev/codelabs/iotedge-remote-diagnostics/index.html?index=..%2F..index#4) one.

**Comment by thnk2wn** [comment]
Great, thanks!
