### ISSUE TITLE
Question: Converting a non-edge Device to Edge?

### ISSUE THREAD

**Issue by thnk2wn** [Azure/iotedge#2601]
Today we have many devices which are non-edge devices. Is there any support to convert these devices to Edge devices? In other words change an existing IoT device and update it such that capability switches to iotedge enabled without re-registering it as a new device id?

Obviously we'd have to install the edge runtime on these devices but just curious if it was possible to transition the IoT registration over? Best I can tell we'll have to re-provision these existing devices as new devices with ids

**Comment by lfitchett** [comment]
You can change the capability of the device using the c# service client.

![image](https://user-images.githubusercontent.com/13950901/75471083-8f00d280-5946-11ea-86da-101d42149203.png)

You can get the connection string here: 
![image](https://user-images.githubusercontent.com/13950901/75471161-ab047400-5946-11ea-8914-871135b07cde.png)

**Comment by thnk2wn** [comment]
Great, thanks!
