### ISSUE TITLE
Mounting modules logs to filesystem to persist log if docker rebooted or restarted.

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#2622]
## Expected Behavior
I would like to mount all docker logs to file system. In case docker get deleted, restarted or device get rebooted. So through logs, want to debug if any issue. Does it cause any issue like- system storage full as we have limited storage and some space constraints.

## Current Behavior
I have set the log policy and each docker modules can store upto 100 mb(5 log files- 20mb each).
Trying to mount containers log to OS filesystem but can't see logs in that location. Tried to mount edgeAgent logs to filesystem and here is the configuration for same-

```
       "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0.8.4",
              "createOptions": {
                "HostConfig": {
                  "Binds": ["/etc/iotedge/storage/:/var/lib/docker/containers/"],
                  "Dns": ["1.1.1.1"],
                  "LogConfig": {
                    "Type": "json-file",
                    "Config": {
                      "max-size": "10m",
                      "max-file": "3"
                    }
                  }
                },
                "Mounts": [
                  {
                    "Name": "DockerLog",
                    "Source": "/var/lib/docker/containers/",
                    "Destination": "/etc/iotedge/storage/",
                    "Type": "bind",
                    "Mode": "",
                    "RW": true,
                    "Propagation": "rprivate"
                  }]
              }
            },
            "env": {
              "OptimizeForPerformance": {
                "value": "false"
              },
              "UpstreamProtocol": {
                "value": "Mqtt"
              },
              "storageFolder": {
                "value": "/var/lib/docker/containers/"
              }
            }
          }
}
```
and executed following command as well-
**sudo chown 1000 /etc/iotedge/storage/
sudo chmod 700 /etc/iotedge/storage/**

After doing this configuration, i can't see any docker logs at host storage path. Can you please point where exactly, i have made mistake or any additional changes is required.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname edgegateway.local but device reports hostname ubuntu.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: certificates - OK
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

22 check(s) succeeded.
1 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [Ubuntu 16.04]: 
* Architecture [amd64]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [run `iotedge version`- 1.0.8]: 
* Edge Agent [image tag (e.g. 1.0.8.4)]: 
* Edge Hub [image tag (e.g. 1.0.8.4)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by lfitchett** [comment]
Hi

IoT Edge uses docker to store and retrieve its logs. You can use the normal docker configuration to modify this: https://docs.docker.com/config/containers/logging/configure/

**Comment by pratson20** [comment]
Hi @lfitchett,
Thanks for the reply.

I am using below configuration in Deployment file-
                  "LogConfig": {
                    "Type": "json-file",
                    "Config": {
                      "max-size": "10m",
                      "max-file": "3"
                    }
                  }

I can see the logs getting stored at location- /var/lib/docker/containers/. Facing one challenge if gateway get rebooted or iotedge get restarted, All modules logs get deleted and logs too. To avoid this issue how can i see that log in local file system if modules get deleted or iotedge get restarted.


Thanks,
Prateek

**Comment by lfitchett** [comment]
This is a docker logging issue. If you point the logger to syslog or journald it should persist, but it is standard docker behavior to delete logs of removed containers. If you are just restarting the modules the logs will persist, but if you remove the container or upgrade it it will clear logs. Try using a different driver than the default like hourneld: https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers.
