### ISSUE TITLE
edgeHub : HSM failure

### ISSUE THREAD

**Issue by Wuxbear** [Azure/iotedge#267]
## Expected Behavior
edgeHub status should be running

## Current Behavior
root@linaro-alip:~# iotedge list 
NAME             STATUS           DESCRIPTION                 CONFIG
**edgeHub          failed           Failed (132) 2 minutes ago  mcr.microsoft.com/azureiotedge-hub:1.0**
tempSensor       running          Up 15 minutes               mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent        running          Up 15 minutes               mcr.microsoft.com/azureiotedge-agent:1.0

## Steps to Reproduce

1. refer the page https://docs.microsoft.com/zh-tw/azure/iot-edge/how-to-install-iot-edge-linux-arm
2. setup the IoT hub and tempSensor module
3. execute command "iotedge list"

### Device (Host) Operating System
Linaro 9.4

### Architecture
armhf

### Container Operating System
Linux

#### iotedged
root@linaro-alip:~# iotedge version 
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent                          1.0                 da31c1e0df4b        3 weeks ago         231MB

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub                            1.0                 5439a2248b5d        3 weeks ago         247MB

#### Docker
root@linaro-alip:~# docker version 
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Wed Jun 27 00:53:52 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Tue Jun 26 23:27:27 2018
  OS/Arch:      linux/arm
  Experimental: false
root@linaro-alip:~# 

## Logs

```
root@linaro-alip:~# iotedge logs edgeHub
[2018-09-11 02:24:14 +00:00]: Starting Edge Hub
[09/11/2018 02:24:15.042 AM] Edge Hub Main()

Unhandled Exception: System.AggregateException: One or more errors occurred. (Error calling CreateServerCertificateAsync: Sign failed
        caused by: A error occurred retrieving a key from the key store.
        caused by: HSM failure
        caused by: HSM API returned an invalid null response) ---> Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadCommunicationException: Erd
        caused by: A error occurred retrieving a key from the key store.
        caused by: HSM failure
        caused by: HSM API returned an invalid null response
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-util/src/M1
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient.CreateServerCertificateAsync(String hostname, DateTime expiration) in /home/vsts2
   at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetServerCertificatesFromEdgelet(Uri workloadUri, String workloadApiVersion, String7
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.MainAsync(IConfigurationRoot configuration) in /home/vsts/work/1/s/edge-hub/src/Micros1
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Azure.Devices.Edge.Hub.Service.Program.Main() in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Pr1
[2018-09-11 02:24:47 +00:00]: Starting Edge Hub
[09/11/2018 02:24:48.206 AM] Edge Hub Main()
```

**Comment by darobs** [comment]
Thank you for reporting this problem. 

The error the edgeHub is seeing is the iotedge daemon getting a null response from the HSM library.  We can probably narrow down the error by looking at the logs on iotedge:

```
sudo journalctl -u iotedge 
```

and looking for the HSM API failures.

(We may have to turn on more detailed logging on the iotedge daemon to find the exact message, See the [troubleshooting guide](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot) for how to turn on debug logging.)

**Comment by Wuxbear** [comment]
After check the debug log, it's the system setup error.
The iotedge is working now, thank for your help.
