### ISSUE TITLE
edgeAgent and edgeHub module could not be found

### ISSUE THREAD

**Issue by PNWang** [Azure/iotedge#268]
## Expected Behavior
After iotedge installation, there should be edgeAgent and edgeHub as default module.

## Current Behavior
No any module inside.

## Steps to Reproduce

1. Following the https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-windows
2. Install and manually provision
3. After iotedge installation, no any default module inside (check by "iotedge list" command).

### Device (Host) Operating System
Windows 10 Enterprise build 17134 release 1804

### Architecture
x64

### Container Operating System
Windows container

#### iotedged
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

#### Edge Agent
Cannot get edgeAgent module.

#### Edge Hub
Cannot get edgeHub module.

#### Docker
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:36:40 2018
  OS/Arch:          windows/amd64
  Experimental:     false

## Logs
9/11/2018 1:50:54 AM info: iotedged::windows -- Starting iotedged service.
9/11/2018 1:50:54 AM info: iotedged -- Using runtime network id nat
9/11/2018 1:50:54 AM info: iotedged -- Initializing the module runtime...
9/11/2018 1:50:54 AM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
9/11/2018 1:50:54 AM info: iotedged::app -- Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
9/11/2018 1:50:54 AM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
9/11/2018 1:50:54 AM info: iotedged -- Finished initializing the module runtime.
9/11/2018 1:50:54 AM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
9/11/2018 1:50:54 AM info: iotedged -- Finished configuring certificates.
9/11/2018 1:50:54 AM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
9/11/2018 1:50:54 AM info: iotedged -- Configuring certificates...
9/11/2018 1:50:54 AM info: iotedged -- Initializing hsm...
9/11/2018 1:50:54 AM info: iotedged -- Finished initializing hsm.
9/11/2018 1:50:54 AM info: iotedged -- Detecting if configuration file has changed...
9/11/2018 1:50:54 AM info: iotedged -- Provisioning edge device...
9/11/2018 1:50:54 AM info: iotedged -- No change to configuration file detected.
9/11/2018 1:50:54 AM info: provisioning::provisioning -- Manually provisioning device "edge_device" in hub
                     "itri-utdc.azure-devices.net"
9/11/2018 1:50:54 AM info: iotedged -- Finished provisioning edge device.
9/11/2018 1:50:54 AM info: iotedged -- Listening on http://xxx.xxx.xxx.xxx:xxxxx/ with 1 thread for workload API.
9/11/2018 1:50:54 AM info: edgelet_core::watchdog -- Starting watchdog with 60 second frequency...
9/11/2018 1:50:54 AM info: iotedged -- Starting workload API...
9/11/2018 1:50:54 AM info: iotedged -- Starting management API...
9/11/2018 1:50:54 AM info: iotedged -- Listening on http://xxx.xxx.xxx.xxx:xxxxx/ with 1 thread for management API.
9/11/2018 1:50:54 AM info: edgelet_core::watchdog -- Checking edge runtime status
9/11/2018 1:50:54 AM info: edgelet_core::watchdog -- Creating and starting edge runtime module edgeAgent
9/11/2018 1:50:54 AM info: edgelet_core::watchdog -- Updating identity for module $edgeAgent
9/11/2018 1:51:43 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 08:51:43.550046100 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)
9/11/2018 1:52:23 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 08:52:23.632731500 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)
9/11/2018 1:52:29 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 08:52:29.954962200 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)
9/11/2018 1:52:40 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 08:52:40.130114500 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)
9/11/2018 1:52:52 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 08:52:52.940729800 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)
9/11/2018 2:01:32 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 09:01:32.789839800 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)
9/11/2018 2:03:22 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 09:03:22.788096700 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)
9/11/2018 2:10:23 AM info: edgelet_http::logging -- [mgmt] - - - [2018-09-11 09:10:23.470042 UTC] "GET
                     /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 14 "-" "iotedge/0.1.0" pid(any)

**Comment by darobs** [comment]
Those management requests happening implies that edgeAgent is running.  If you run `docker ps -a` on the system, you will probably see edgeAgent running.

I suspect this is a bug in `iotedge` that should have been addressed in version 1.0.1. I need to figure out how to get 1.0.1 in Windows and I'll add those instruction here.

**Comment by myagley** [comment]
@darobs the management requests look like they are coming from `iotedge list` (based on the user agent).

Is it possible to see the Edge Agent logs? It's possible the Edge Agent is exiting.

**Comment by darobs** [comment]
Hello @PNWang, that message, which could use to be better, I think, is just indicating that no deployment was set for the device.

Have you configured any modules on the device?

**Comment by PNWang** [comment]
Hello @darobs, this issue (edgeAgent could not be found) has occurred again before but been solved by creating another new iot hub.
Now I have delivered some modules inside and everything works well.

Thank you for help.

**Comment by myagley** [comment]
I'm going to close this issue for now. Please feel free to reopen. Thanks!
