### ISSUE TITLE
restaring iotedge runtime remotely

### ISSUE THREAD

**Issue by AE-AEssam** [Azure/iotedge#2690]
I have the scenario with an iot edge device on linux machine, and its auto provisined with DPS. In case that we want to change the configuration of this device through DPS, then we would need to restart the iot edge run time on the device so that it will re-provision to get the new configuration. 

- My question is what is best way to restart iotedge runtime on the device in  a remote way. I tried to search but I found out  that it is not supported to do by invoked methods. Then what could be other option ? 
- Is it possible to create a module to reboot the device and invoke it by a method ? if so then how could the module communicate with the device directly to reboot it.

**Comment by richma-ms** [comment]
Thanks for reaching out.

Unfortunately there's no built-in way to trigger re-provisioning today.  Given that, you're on the right path in thinking about a custom module to receive a C2D notification, and then do something on the device.  But I can't think of anything off the top of my head regarding how code inside a docker container can directly access system resources on the host.  Maybe there's some Linux magic that can make it happen, but seems to me it'd break the whole containerized workload model.

If you're willing to go one step further though, an idea to try is to implement both a customer module, and a service that runs natively on the host machine.  When the module receives a direct method from the cloud, it connects to the service via loopback and forwards the notification.  From there, the service just needs to fire "service iotedge restart".
