### ISSUE TITLE
DirectMethod call from ModuleClient returns: Device not registered

### ISSUE THREAD

**Issue by njbuch** [Azure/iotedge#2697]
## Expected Behavior
Calling a direct method in a module on a device from another module on another device should work.

## Current Behavior
I get the error:

  at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.ModuleClient.InvokeMethodAsync(Uri uri, MethodRequest methodRequest, CancellationToken cancellationToken)
   at MotionDetection.Program.SendAsync(ModuleClient client, BlockingCollection`1 queue, CancellationToken cancellationToken) in /app/Program.cs:line 391
Device {"message":"Client device1/module1 not found","exceptionMessage":"","status":0,"payload":null} not registered

## Steps to Reproduce
1. First try calling your directmethod from visual studio code and returns a nice 200.
2. Try this way to call that above direct method on another device in another module:
```
try
                    {
                        var payloadData = new
                        {
                            name = "michael"
                        };

                        if (ioTHubModuleClient != null)
                        {
                            MethodRequest request = new MethodRequest("MyMethod", UTF8Encoding.Default.GetBytes(JsonConvert.SerializeObject(payloadData)));
                            var resp = await ioTHubModuleClient.InvokeMethodAsync("device1", "module1", request);
                        }
                        else
                        {
                            Console.WriteLine("the user context is null");
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.StackTrace);
                        Console.WriteLine(ex.Message);
                    }

```

## Context (Environment)
The module calling the method, and the module exposing the method are running on Raspberry Pi4 with workarounds to use Raspian Stretch.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: certificates expiry - Warning
    Device CA certificate in /var/lib/iotedge/hsm/certs/device_ca_aliasazxVrrdEVxd7kvKvne1pOEyuSHF8EXSowNDhMzl30jI_.cert.pem will expire soon (2020-03-16 16:54:24 UTC)
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
√ production readiness: logs policy - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

20 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS [Raspian Stretch]: 
* Architecture [arm32]: 
* Container OS [Linux containers]: 

### Runtime Versions
* iotedged [iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)]: 
* Edge Agent  [1.0.8.5.28262167 (b5de730c6020b852f9636b7117138de6c6fced36)]: 
* Edge Hub [ 1.0.8.5.28262167 (b5de730c6020b852f9636b7117138de6c6fced36)]: 
* Docker/Moby [19.03.1]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by ggjjj** [comment]
Hi @njbuch,

Today we support Invoking Direct Method in 2 ways: 
1. From one module to another module of the **same device** 
2. From Cloud to Module of a device from the Azure portal

Can you describe the scenario of why you would need to use direct method on a different device?

Closest to what you want to do can be done as described below:
Lets say there are two devices - device1 and device2 that are connected to the same IoT hub.  If you want to trigger direct method from device1 to device2, then create a service client [not module client as you tried] in a module in device1 which makes IoT hub server to trigger a direct method to a module in device2. This is similar to the method 2 as described above.

**Comment by njbuch** [comment]
Thanks a lot clarifying the problem. Two questions then:
1: Any plans to support that in the future?
2: Can you point to docs/tech choices on the cloud trigger work-around?

**Comment by ggjjj** [comment]
Can you describe your scenario and use case so that we can understand the need to support it. 

For the documents - try the service client sample from [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/service/ServiceClientSample)

and invoke the method **InvokeDeviceMethodAsync** from the service client object and specify the device ID and method name.

**Comment by njbuch** [comment]
Hi again, I have sites with RPis with cameras, running some AI. The cameras are submitting telemetry for detections and images, but when something specific is detected, they need to activate a specific RPi that activates some physical stimuli. I wanted to avoid cloud code in the concept, to reduce complexity. I looked at the gateway-device concept which was too complex for the prototype.

As I understand you hints about service-client, I need to have code running on a server somewhere else, to support the logic of transferring calls to the right device - which is very clumsy. I am considering a direct socket connection between the devices instead.

**Comment by ggjjj** [comment]
Currently we don't have any way to avoid cloud code for your request. Marked as a feature request! Thanks for trying it out.

**Comment by veyalla** [comment]
Please file or vote for feature requests at: https://feedback.azure.com/forums/907045-azure-iot-edge
