### ISSUE TITLE
edgeHub container fails to start, probably due to user permissions (listen on port 443 with unprivileged user)

### ISSUE THREAD

**Issue by roicostas** [Azure/iotedge#27]
I am trying to setup GA on redhat 7. One of the errors I have found is that the edgeHub Docker container is unable to start. After some troubleshooting and after checking that the iotedged daemon was reachable through http I created a custom Docker image with user "root" and it worked so I suspect it is due to the edgeHub is unable to listen in that port and it fails. This is the error I am getting: 

[2018-07-17 07:23:34 : Starting Edge Hub
[07/17/2018 07:23:34.254 AM] Edge Hub Main()
FailFast:
Exception thrown from SocketAsyncEngine event loop: System.TypeInitializationException: The type initializer for 'OperationQueue`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading.ThreadPool, Version=4.1.1.0, Culture=neutral, PublicKeyToken=*********'. Access is denied.
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.HandleEvent(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__24_0(System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
Exception details:
System.TypeInitializationException: The type initializer for 'OperationQueue`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading.ThreadPool, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Access is denied.
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.HandleEvent(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()

**Comment by darobs** [comment]
Hello @roicostas 

Thank you for reporting this issue.  We currently run the edgeHub as a non-privileged user, and use `setcap` to give the application access to `CAP_NET_BIND_SERVICE`.  That should be sufficient for edgeHub to access sockets.
 
The inner exception is: "Could not load file or assembly 'System.Threading.ThreadPool'" - are you building the edgeHub container?  If so, this might mean an assembly is missing or file access is restricted.

**Comment by roicostas** [comment]
No, that error shows on the official image. I have built my own from the official release just to run the image as root and workaround this problem. 

Some capabilities are not supported by all filesystems, may that be it? I am using the overlay2 filesystem in rhel 7.5.

**Comment by darobs** [comment]
Got it - wanted to make sure I understood the problem.

The overlay2 FS should be fine (at least, it is on my ubuntu and other Debian based systems).  

We are working on support for Red Hat right now, so we will be working on a fix for this.

**Comment by myagley** [comment]
We've finally got some RPM packages produced and I've verified on a Centos 7.5 device. I do not see the permissions issue.

What version of RHEL are you using?

**Comment by myagley** [comment]
Just a note, .NET Core 2.1.0 has an issue running with SELinux. We are updating our images to .NET Core 2.1.2 to mitigate.

**Comment by aribeironovaes** [comment]
Closing since we have updated to 2.1.2. If you believe this issue was not fixed, please reopen.

**Comment by pbiswas-kol** [comment]
I am getting same issue. edge running on RHEL 7.4

**Comment by pbiswas-kol** [comment]
I am getting below error after install 1.0.1

FailFast:
Exception thrown from SocketAsyncEngine event loop: System.TypeInitializationException: The type initializer for 'OperationQueue`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading.ThreadPool, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Access is denied.

   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.HandleEvent(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()

   at System.Environment.FailFast(System.String, System.Exception)
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__24_0(System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)

Exception details:
System.TypeInitializationException: The type initializer for 'OperationQueue`1' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Threading.ThreadPool, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Access is denied.

   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.HandleEvent(SocketAsyncContext context)
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
[2018-09-06 00:26:18 : Starting Edge Hub
[09/06/2018 12:26:18.563 AM] Edge Hub Main()

Please help to resolve this edgeHub error.

**Comment by pbiswas-kol** [comment]
Yes I have installed iotedge daemon, moby-engine from  https://github.com/Azure/azure-iotedge/releases/tag/1.0.1. How do I know which version of edgeHub is running ?

**Comment by roicostas** [comment]
With the new daemon you should also update edgeHub and edgeAgent images. They can be configured in the iotedge deployment. They should be mcr.microsoft.com/azureiotedge-hub:1.0.1 and mcr.microsoft.com/azureiotedge-agent:1.0.1. When creating the new deployment after selecting your desired modules and configuration you can also edit iotedge modules configuration. You just need to change that setting.

In order to workaround edgeHub permissions I also have created my own edgeHub image which just sets the user as root.

**Comment by pbiswas-kol** [comment]
After change edgeAgent and edgeHub version (1.0.1), I am getting same permission error in edgeHub

edgeHub          failed           Failed (139) a minute ago  mcr.microsoft.com/azureiotedge-hub:1.0.1

edgeAgent        running          Up 4 minutes               mcr.microsoft.com/azureiotedge-agent:1.0.1

Could you please share your docker file for your custom build edgeHub that set user to root ?

**Comment by roicostas** [comment]
Setting User as root in the deployment does not work so you need a new image. It does not make sense for me being able to change a subset not documented of Docker options and not others. This is my workaround:

- Dockerfile
```
FROM mcr.microsoft.com/azureiotedge-hub:1.0.1
User root
```

- Build
```
docker build -t <my_registry/user in dockerhub>/azureiotedge-hub:1.0.1-as_root .
```

- Use this image in your deployment

**Comment by pbiswas-kol** [comment]
Thanks @roicostas 
Our RHEL was 7.4 after update the RHEL to 7.5 its working without root user access.

Thank you again.

**Comment by Jan-Olof** [comment]
It seems like we have the same issue as @roicostas 

We also use RHEL 7.5 and it works after a fresh install and then it fails after reboot.

**Comment by pbiswas-kol** [comment]
I have not rebooted my server after RHEL 7.5. But when it was RHEL 7.4 I found that workload.sock 
 and mgmt.sock are  missing after reboot and  I installed edge runetime again.

@roicostas so any workarround for this reboot issue.

**Comment by ArsalanSaleemGhuman** [comment]
> Setting User as root in the deployment does not work so you need a new image. It does not make sense for me being able to change a subset not documented of Docker options and not others. This is my workaround:
> 
>     * Dockerfile
> 
> 
> ```
> FROM mcr.microsoft.com/azureiotedge-hub:1.0.1
> User root
> ```
> 
>     * Build
> 
> 
> ```
> docker build -t <my_registry/user in dockerhub>/azureiotedge-hub:1.0.1-as_root .
> ```
> 
>     * Use this image in your deployment

This resolved the error I was getting which is  error reported here https://github.com/Azure/iotedge/issues/671
