### ISSUE TITLE
X509 connect from leaf node to edge

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#270]
Unable to connect from leaf node to iotedge using certificates generated from standalone CA.
IotHub in cloud was configured to allow leaf node connections using X509 Authentication.
When connecting directly to cloud messages were flowing.
So I wanted to configure leaf nodes to communicate over TLS with edge.

I was following this documentation:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-linux
but I think it is only related to self signed certificates.

## Expected Behavior

Leaf node should be able to connect to iotedge when using certificates provided by standalone CA (for edge device X509 certificate was generated and signed by rootCA with key usage Client and Server Authentication), when root CA is imported into Trusted Root Authorities store of the leaf node.

## Current Behavior

Unable to communicate from leaf to edge. Leaf is unable to validate public key that is presented by edge device.

When using this code:

`var cert = new X509Certificate2(@"c:\temp\generated\deviceovercert.pfx", "somepassword");
                var auth = new DeviceAuthenticationWithX509Certificate(deviceId, cert);
                var deviceClient = DeviceClient.Create("adamiotwithca.azure-devices.net", "adamedge.iothubtesting.com", auth, TransportType.Amqp_Tcp_Only);
deviceClient.SendEventAsync(eventMessage).SendEventAsync(eventMsg).Wait()`

I'm getting this exception:
_System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>_

When using this code:

` var cert = new X509Certificate2(@"c:\temp\generated\deviceovercert.pfx", "somepassword");
                var auth = new DeviceAuthenticationWithX509Certificate(deviceId, cert);
                AmqpTransportSettings settings = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
                settings.RemoteCertificateValidationCallback += (sender, certificate, chain, errors) =>
                {
                    return true;
                };
                var deviceClient = DeviceClient.Create("adamiotwithca.azure-devices.net", "adamedge.iothubtesting.com", auth, new [] { settings});`

In the RemoteCertificateValidationCallback I see that edge device presents to leaf node default certificate:
_[Subject]
  CN=edgemodules
[Issuer]
  CN=iotedged workload ca
[Serial Number]
  79EA0DFB
[Not Before]
  11.09.2018 11:57:50
[Not After]
  10.12.2018 10:57:30
[Thumbprint]
  23DACC5922969F8F3926AE7C7AFE5DEFA3748716_

## Steps to Reproduce

1. Create Win2012 standalone CA
2. Export root CA
3. Add root CA and validate that you own this certificate following this procedure:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started
4. On windows machine add to c:\Windows\System32\drivers\etc\hosts ip of iotedge machine e.g.
192.0.2.5 adamedge.iothubtesting.com
where 192.0.2.5 is my virtual machine hosting iotedge
5. Import root CA certificate from step 2 into windows 10 trusted root authorities store
6. Create CSR for leaf node (windows 10 machine) that asks for (Client authentication): 
[deviceovercert.zip](https://github.com/Azure/iotedge/files/2370587/deviceovercert.zip)
Once CSR is completed this you will have certificate with private key
7. Create CSR for edge device (enhanced key usage:
Client Authentication (1.3.6.1.5.5.7.3.2)
Server Authentication (1.3.6.1.5.5.7.3.1)
key usage:
Digital Signature, Non-Repudiation, Key Encipherment, Data Encipherment (f0),
Subject CN = adamedge
Subject Alternate Names:
DNS Name=adamedge
DNS Name=adamedge.iothubtesting.com)
e.g.
[adamedge.zip](https://github.com/Azure/iotedge/files/2370598/adamedge.zip)
but for the edge device we are using certificate in same pem format:
[adamedge.cert.pem.zip](https://github.com/Azure/iotedge/files/2370603/adamedge.cert.pem.zip)
8. Using winscp copy 
rootCA.pem to /var/lib/iotedge/hsm/certs/
adamedge.cert.pem to /var/lib/iotedge/hsm/certs/
adamedge.privkey.pem to /var/lib/iotedge/hsm/cert_keys
9. update /etc/iotedge/config.yaml to use certificates

certificates:
  device_ca_cert: "/var/lib/iotedge/hsm/certs/adamedge.cert.pem"
  device_ca_pk: "/var/lib/iotedge/hsm/cert_keys/adamedge.privkey.pem"
  trusted_ca_certs: "/var/lib/iotedge/hsm/certs/rootCA.pem"
10. Restart iotedge
11. Go to /var/lib/iotedge/hsm/certs
I see that two certs were generated:
iotedged-workload-caGrw6jn-HzmxG8plggnAjPDuGJr0qGW94X1KnqPwU9ng_.cert.pem
edgeHub6367225208709886773vX5-JR0CU_RuAa_m6AmdChrrYXv-dUAtqplgAbZeuE_.cert.pem
[edgeCerts.zip](https://github.com/Azure/iotedge/files/2370717/edgeCerts.zip)
and at the bottom they contain certificate:
adamedge.cert.pem

Remarks:
Nothing changes if I:
cat adamedge.cert.pem rootCA.pem > adamedge.cert.fullchain.pem
and change configuration:
certificates:
  device_ca_cert: "/var/lib/iotedge/hsm/certs/adamedge.cert.fullchain.pem"
  device_ca_pk: "/var/lib/iotedge/hsm/cert_keys/adamedge.privkey.pem"
  trusted_ca_certs: "/var/lib/iotedge/hsm/certs/rootCA.pem"

Still edge presents itself with the self generated certificate and I'm getting exception:
_System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>_

## Context (Environment)
Windows 10 - leaf node and Linux ubuntu hosting iotedge
### Device (Host) Operating System

Ubuntu 18.04
### Architecture

amd64
### Container Operating System

Linux containers
#### iotedged

iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)

#### Edge Agent

1.0.1

#### Edge Hub

1.0.1

**Comment by myagley** [comment]
Hi Adam. Unfortunately X509 certificate authentication for leaf devices is not supported in the Edge Hub. This is something we are actively working on and we are targeting its completion before the end of the calendar year.

**Comment by myagley** [comment]
This now supported as of version 1.0.6. The downstream device will need to be in the edge device's scope and the public portion of the CA certificate will need to be configured in the `config.yaml` of the daemon in `certificates.trusted_ca_certs`.

You can learn more about configuring this here: 
https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-as-gateway

**Comment by amit12cool** [comment]
I have registered by edge device through DPS which uses sha256 primary and secondary thumbprint. Now when i try to register my leaf device through edge device it seems its using the sh1 thumbprint as a result i see a thumbprint mismatch error in edgeHub module. Below is the error:-

```
<4> 2020-09-22 09:04:02.425 +00:00 [WRN] - Error authenticating certificate for amidha-leaf-ca because the certificate thumbprint did not match the primary or the secondary thumbprints.
<6> 2020-09-22 09:04:02.425 +00:00 [INF] - Unable to authenticate client amidha-leaf-ca with cached service identity amidha-leaf-ca. Resyncing service identity...
```
