### ISSUE TITLE
Test certificate not being created properly as the Individual enrollment with X509 certificate causing issue

### ISSUE THREAD

**Issue by vermaaditya** [Azure/iotedge#2738]
Hi, 

Based on the URL https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs
I am trying to create an Individual enrollment with the help of Test certificates. 
For creating test certificates as suggested I am using the link - https://docs.microsoft.com/bs-latn-ba/azure/iot-edge/how-to-create-test-certificates. 

But when I upload the full chain cert I am getting the error - "The certificate is not a valid base64 string value.". To resolve this I am using workaround mentioned in - https://github.com/MicrosoftDocs/azure-docs/issues/6886. 

After this i start getting the error - CN (common name) in primary certificate is invalid. Please upload another certificate. where in the CN in the certificate is - testadityaedge001. 

Kindly help in resolving the issue. Either the documentation needs to be corrected, or the Powershell script to create the full chain device identity certificate needs to be corrected.

Awaiting the resolve. 

Steps to Reproduce
Described above

Environment - Powershell to generate the script in Admin mode
Edge - to upload the cer in portal.azure.com

**Comment by ancaantochi** [comment]
Hi @vermaaditya, 

I tried the steps and I was able to reproduce both issues when I uploaded the full chain: "The certificate is not a valid base64 string value." and then "CN (common name) in primary certificate is invalid". 

It worked when I uploaded just the identity cert (iot-edge-device-identity-testadityaedge001.cert.pem). I think DPS should work with the full chain as the documentation specifies, but for individual enrolment just the identity cert upload should be ok. I raised the issue with DPS team. In the meantime please upload just the cert and let me know if that works.

**Comment by vermaaditya** [comment]
Appreciate your prompt response.

Yes, it works with the device identity cert (iot-edge-device-identity-testadityaedge001.cert.pem). 
But can you kindly help why the full chain cert isnt working. 
If I am not using the full chain cert, what all places will be impacted?

**Comment by ancaantochi** [comment]
I think it is an issue with DPS validation that the full chain is not accepted, I raised the issue with them.
For individul enrolment you don't need the full chain. It will get the documentation updated because it is not very clear.
