### ISSUE TITLE
DPS group enrollment does not work - neither rootCA nor intermediate

### ISSUE THREAD

**Issue by haverboecker** [Azure/iotedge#2739]
Hello!

I just tried to use the recently release iot edge to provision a test device using x509 certificates. Previously, I could provision a normal device that way, but the iot egde runtime can only do it quite recently.

## Expected Behavior
I would expect to see the device beeing provisioned.

## Current Behavior
The device is not provisioned and the edge deamon stops.

## Steps to Reproduce
1. I provide and verify a CA
2. I set up an enrollment group with a RootCA as a certificate
3. I set up the config.yaml so it points to the certs and provides the desired information as in here https://github.com/Azure/iotedge/blob/master/doc/rc/how-to-auto-provision-x509-certificates.md
4. I restart the deamon, it stops after a short while.

As for point no 1, I created the certificates by mayself, not using the openssh-certs, that come with some tutorials. But as I could provision devices before with such certificates with the help of the JavaProvisioningSample, I believe the certificates or their chain seems to be OK.

As for Point no 2, I also tried to set up an intermediate form the rootCA that I set up in step 1. The error is a bit different, but in both cases, the deamon tries 4 times or so and then stops.

### Output of `iotedge check`

> Configuration checks
> --------------------
> √ config.yaml is well-formed - OK
> √ config.yaml has well-formed connection string - OK
> √ container engine is installed and functional - OK
> √ config.yaml has correct hostname - OK
> × config.yaml has correct URIs for daemon mgmt endpoint - Error
>     Error: could not execute list-modules request: an error occurred trying to connect: Connection refused (os error 111)
> √ latest security daemon - OK
> √ host time is close to real time - OK
> √ container time is close to host time - OK
> √ DNS server - OK
> √ production readiness: identity certificates expiry - OK
> ‼ production readiness: certificates - Warning
>     The Edge device is using self-signed automatically-generated development certificates.
>     They will expire in 69 days (at 2020-06-03 10:49:21 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
>     After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
>     Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
> √ production readiness: container engine - OK
> √ production readiness: logs policy - OK
> ‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
>     The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
>     Data might be lost if the module is deleted or updated.
>     Please see https://aka.ms/iotedge-storage-host for best practices.
> ‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
>     The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
>     Data might be lost if the module is deleted or updated.
>     Please see https://aka.ms/iotedge-storage-host for best practices.
> 
> Connectivity checks
> -------------------
> √ host can connect to and perform TLS handshake with DPS endpoint - OK
> √ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
> √ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
> √ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
> √ container on the default network can connect to IoT Hub AMQP port - OK
> √ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
> √ container on the default network can connect to IoT Hub MQTT port - OK
> √ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
> √ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
> √ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
> 
> 21 check(s) succeeded.
> 3 check(s) raised warnings. Re-run with --verbose for more details.
> 1 check(s) raised errors. Re-run with --verbose for more details.

Please note, the daemon is not running at the time of the command above.

### Device Information
* Ubuntu 18.04
* amd64
* Linux containers

### Runtime Versions
* iotedged iotedge 1.0.9
* Edge Agent Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
* Edge Hub Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44) 
* Docker/Moby Version: 3.0.11+azure

## Logs
This is happening when directly using a rootCA:

> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [INFO] - Starting provisioning edge device via X509 provisioning...
> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [INFO] - Starting DPS registration with scope_id "XXX", registration_id "DpsEdgeTestDeviceCA"
> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [WARN] - Could not provision device
> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [WARN] -         caused by: X509 certificate based registration failed
> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [WARN] -         caused by: HTTP request failed: [401 Unauthorized] {"errorCode":401002,"trackingId":"64c577d5-1b81-4196-b265-806d53718b96","message":"Signing certificate info did not match chain elements.","timestampUtc":"2020-03-25T19:05:29.6654798Z"}
> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [ERR!] -         caused by: Could not restore previous provisioning result
> Mar 25 19:05:29 DpsEdgeTestDeviceCA iotedged[23450]: 2020-03-25T19:05:29Z [ERR!] -         caused by: No such file or directory (os error 2)
> Mar 25 19:05:29 DpsEdgeTestDeviceCA systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
> Mar 25 19:05:29 DpsEdgeTestDeviceCA systemd[1]: iotedge.service: Failed with result 'exit-code'.
> Mar 25 19:05:30 DpsEdgeTestDeviceCA systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
> Mar 25 19:05:30 DpsEdgeTestDeviceCA systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 63.
> Mar 25 19:05:30 DpsEdgeTestDeviceCA systemd[1]: Stopped Azure IoT Edge daemon.
> Mar 25 19:05:30 DpsEdgeTestDeviceCA systemd[1]: Dependency failed for Azure IoT Edge daemon.
> Mar 25 19:05:30 DpsEdgeTestDeviceCA systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.
> 

This is happening when I use an intermediate from the rootCA:

> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [INFO] - Starting provisioning edge device via X509 provisioning...
> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [INFO] - Starting DPS registration with scope_id "XXX", registration_id "DpsEdgeTestDevice"
> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [WARN] - Could not provision device
> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [WARN] -         caused by: X509 certificate based registration failed
> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [WARN] -         caused by: HTTP request failed: [401 Unauthorized] {"errorCode":401002,"trackingId":"2ac04e1d-0bcc-4e97-968c-684b4cbe42f2","message":"CA certificate not found.","timestampUtc":"2020-03-25T18:57:47.0959217Z"}
> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [ERR!] -         caused by: Could not restore previous provisioning result
> Mar 25 18:57:47 DpsEdgeTestDevice iotedged[21909]: 2020-03-25T18:57:47Z [ERR!] -         caused by: No such file or directory (os error 2)
> Mar 25 18:57:47 DpsEdgeTestDevice systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
> Mar 25 18:57:47 DpsEdgeTestDevice systemd[1]: iotedge.service: Failed with result 'exit-code'.
> Mar 25 18:57:47 DpsEdgeTestDevice systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
> Mar 25 18:57:47 DpsEdgeTestDevice systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 54.
> Mar 25 18:57:47 DpsEdgeTestDevice systemd[1]: Stopped Azure IoT Edge daemon.
> Mar 25 18:57:47 DpsEdgeTestDevice systemd[1]: Dependency failed for Azure IoT Edge daemon.
> Mar 25 18:57:47 DpsEdgeTestDevice systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.
> 

## Additional Information
Do you have any idea what I could be doing wrong? To me the logs seem to indicate that the data in the config.yaml is interpreted correctly, but somehow the provisioning in the cloud does not accept the certs. Which is strange, as I have used similar ones in the past for the JavaProvisioningSample.

Or is there some easy tutorial I can use for this case to iteratively get close to the cause of the problem?

Thanks for any help!

Peer

**Comment by ancaantochi** [comment]
Hi @haverboecker,

From the logs it looks like DPS fails the authentication because it can't build the full chain from device identity cert to the root certificate. When you setup the cert in config.yaml doesn't it only contain the identity cert or the chain? Can you please setup with the full chain and let me know if that works.

You mentioned that these certificates worked before, was it with 1.0.9 release or only with JavaProvisioningSample?

Thanks,
Anca

**Comment by haverboecker** [comment]
Hello!

Thanks for the reply!

You were right, I only had the device cert itself provided. I need to put the device cert and intermediate cert into the same file, then it works.

It worked before, but only with the provisioning sample. IIRC in the sample I also had to provide another cert, not sure anymore if intermediate or root. But probably thats why it worked there.

If I still run into problems later on, I will get back to you again.

Thanks again!

Best regards,

Peer
