### ISSUE TITLE
transparent gateway Edge Hub AuthenticationMode issue

### ISSUE THREAD

**Issue by Nick287** [Azure/iotedge#2744]
IoT Edge transparent gateway Edge Hub AuthenticationMode Issue
Create IoT Edge transparent gateway on Linux Ubuntu
Keep the authentication mode of the gateway device as default (local)
Create a new iot device form iothub and then use symmetric key authentication connect to iothub  like this ( HostName=myiothub.azure-devices.net;DeviceId=myDownstreamDevice;SharedAccessKey=xxxyyyzzz;GatewayHostName=myGatewayDevice )
Close the simulator device and wait for the device to go offline (I usually wait about 40 minutes)
Use symmetrically key authentication connect to the Edge hub again that will be fail. And cannot connect to hub ever again.

We found a way for work around this issue that is we need set the the environment variable "AuthenticationMode" to "value" like this

"env": {
"AuthenticationMode": {
"value": "Cloud"
}

The gateway device can access iothub for authentication every time without any problems, but at the same time it can cause another issue which is that the gateway is disabled offline capabilities.

BTW, If you established a parent/child relationship for this downstream device, then this problem does not exist.

Problem Statement: Unable to connect to Edge Hub using symmetrical key authentication.

Ubuntu 18.04.1 LTS
Edge Hub 1.0.8

**Comment by ancaantochi** [comment]
Hi @Nick287,

It's not clear what you mean by:

> Close the simulator device and wait for the device to go offline

It is requiered to set a parent-child relationship for authentication to work while offline. 

Can you please provide edgeHub logs?

**Comment by veyalla** [comment]
Closing stale issue, please re-open if still an issue.
