### ISSUE TITLE
Iotedge runtime not working when it's installed side by side with an antivirus

### ISSUE THREAD

**Issue by omarine** [Azure/iotedge#2748]
## Expected Behavior
IotEdge commands should execute normally 

## Current Behavior
All iotedge commands seem to hang indefinitely

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.activate antivirus
2.Istall IotEdge Runtime
3.execute iotedge commands IotEdge check or any other iotedge commands(iotedge list)

### Output of `iotedge check`

<details>
<summary>n/a</summary>

```

<n/a>

```
</details>

### Device Information
* Host OS [Microsoft Windows Server Version 1809]: 
* Architecture [arm64]: 
* Container OS [Windows containers]: 

### Runtime Versions
* iotedged [iotedge 1.0.9]: 
* Edge Agent [1.0]: 
* Edge Hub [1.0]: 
* Docker/Moby [3.0.5]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<n/a>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<n/a>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<n/a>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by veyalla** [comment]
There are known issues with compatibility of OS container technology with some antivirus products. This is outside the control of the IoT Edge application runtime. Please contact your antivirus vendor the possible workarounds like [this one for Symantec](https://knowledge.broadcom.com/external/article?legacyId=TECH246815)...

Closing, as there is nothing actionable from our side to alleviate this...
