### ISSUE TITLE
Azure IoT Edge module crashing with Temporary failure in name resolution

### ISSUE THREAD

**Issue by mronnlun** [Azure/iotedge#2764]
## Expected Behavior
The module should open a connection to IoT Hub and start sending data

## Current Behavior
The edge module crashes with the error 

> ConnectionFailedError(None) caused by gaierror(-3, 'Temporary failure in name resolution')\n"]

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a folder
2. Add this file https://github.com/Azure/azure-iot-sdk-python-preview/blob/master/azure-iot-device/samples/advanced-edge-scenarios/send_message.py
3. Add a docker file with these contents
```
FROM arm32v7/python:3

RUN pip install azure-iot-device
ADD testscript.py /

CMD [ "python", "./testscript.py" ]
```
4. Build container on Raspberry with Raspbian-strech

## Context (Environment)
The container is built using Docker tasks in a pipeline in Azure DevOps and I'm using a Raspberry with Raspbian Stretch as build server.

I have installed Azure IoT Edge Runtime on another Raspberry where the module is deployed.

### Output of `iotedge check`
I don't currently have ssh access to the device (it's at my colleagues home due to social distancing)

### Device Information
* Raspberry Pi 3
* Raspbian Stretch https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/
* Architecture arm
* Linux containers

### Runtime Versions
* iotedged - installed in december 2019 
* Edge Agent 1.0.9
* Edge Hub 1.0.9
* Docker

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
<details>
<summary>edge-agent logs</summary>

```

transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 366, in connect
    rc = self._mqtt_client.connect(
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 117, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/usr/local/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 387, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by gaierror(-3, 'Temporary failure in name resolution')
ConnectOperation: completing with error ConnectionFailedError(None) caused by gaierror(-3, 'Temporary failure in name resolution')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionFailedError(None) caused by gaierror(-3, 'Temporary failure in name resolution')
ConnectOperation: completing with error ConnectionFailedError(None) caused by gaierror(-3, 'Temporary failure in name resolution')
Callback completed with error ConnectionFailedError(None) caused by gaierror(-3, 'Temporary failure in name resolution')
["azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by gaierror(-3, 'Temporary failure in name resolution')\n"]

```
</details>

## Additional Information
This is also reported here https://stackoverflow.com/questions/60938238/azure-iot-edge-module-crashing-with-temporary-failure-in-name-resolution

**Comment by BertKleewein** [comment]
@mronnlun - does this happen every time you try to connect or is this problem intermittent?

**Comment by mronnlun** [comment]
It happened all the time but I refactored the code for other purposes and after that this stopped happening. So this can be closed.

**Comment by dylanbronson** [comment]
Feel free to reopen if you run into this issue again!
