### ISSUE TITLE
Module identity missing when starting up containers

### ISSUE THREAD

**Issue by vpangaldus** [Azure/iotedge#2765]
We have this following scenario for our project.

Story:
* edge device is succesfully provisioned and connected to IoT Hub 
* edge device used in offline scenario, where all custom modules are running
* edge device need to be updated for whatever urgent reason (in offline environment)
* all modules including edgeHub and edgeAgent are deleted. We configured the storageFolder for both edgeHub and edgeAgent, and expected that any required information to run modules would be stored there.

Expected behavior:
* after firmware update (in offline environment) the edge device must still work, where all modules which are deployed previously must continue their operations.

Is there a mechanism from IoTEdge to support the above story? As we understand that one of the thing that need to be taken care is the module identity. Is there a way to store the module identity and recover it after all modules were deleted including their images? If not, is there a plan to support this scenario soon?

Thank you.

**Comment by micahl** [comment]
Thank you for sharing your scenario, @vpangaldus.  The module identities are cached internally, but not preserved across updates.  If the device is offline you'd need to bring it back online to sync with Hub and get the module identities again.  This is something we'll need to investigate.

**Comment by veyalla** [comment]
Note, if your firmware update process does not delete existing containers they should continue to work when offline after the update.

**Comment by corollaries** [comment]
@micahl Can you give any estimate on when this is going to be investigated? At the moment this is a breaking issue for us with regards to offline scenarios.

@veyalla We use a dual partition firmware update meaning that any container won't be there after the update. Though perhaps we could look into somehow copying/moving the containers to the new partition. I'll investigate if that's possible.

**Comment by micahl** [comment]
@corollaries, there is some very early investigation in areas related to identity and offline that's already happening.  Just to set expectations, however, we haven't locked in work to address this.  We do want to ensure we understand your scenario.  Is it exactly the same as the one given in the issue description?  Also, have you considered creating a third partition for data that would persist between firmware updates and have the containers live there?

**Comment by corollaries** [comment]
@micahl, thanks a lot for the update!

It is exactly the same indeed. We have some partitions for persistent data. On a firmware update the data is copied to the other partition. The docker containers are stored on the partition, but when copied we encountered all sorts of problems mainly with docker not being able to startup anymore. (Not entirely sure if it's due to permissions or symlinks not existing anymore)
However, given the circumstances this is something we can further investigate on our end on how to mitigate that issue. 

Nonetheless, being able to store module identities on the filesystem to ensure persistency would still be a great feature to have for IoT Edge!

**Comment by veyalla** [comment]
Please file or vote for existing feature request at https://feedback.azure.com/forums/907045-azure-iot-edge

**Comment by dominikdalek** [comment]
Which of the existing features would that be, @veyalla ?

**Comment by corollaries** [comment]
None of the existing features covered this as far as I could see. I filed a new one:
https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/40748083-support-storing-the-module-identities-within-edgea
