### ISSUE TITLE
Edge stops routing messages after exactly 20 messages (TP gateway, MQTT client)

### ISSUE THREAD

**Issue by stevebus** [Azure/iotedge#277]
I have an MQTT client using the paho.mqtt library in python.  It connects to IoTHub and then sends messages every 5 seconds forever.  The messages are routed to a module (for logging/debugging) and also routed to IoT Hub.

## Expected Behavior
IoT Edge routes the incoming messages forever

## Current Behavior
The MQTT client app connects and sends messages.  The first 20 messages are successfully routed to both the logging module and IoT Hub.  After 20 messages, the MQTT client continues to send messages (no errors in either the client or edgeHub), but no further routing of messages occur.  Restarting the client causes messages to again start routing, but they stop after 20.

## Steps to Reproduce

1. set up edge as a transparent gateway per the docs
2. create a paho.mqtt client that connects and then sends messages in an endless loop (example code below the "context" section with PII removed)
3.  create a module to log the messages sent to it (you can borrow mine if you need to - URI below)
4.  set up a route to send leaf device messages to both the logger module and IoT Hub (see below)

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64  (virtual machine)

### Container Operating System
Linux

#### iotedged
1.0.1
#### Edge Agent
1.0.1
#### Edge Hub
1.0.1
#### Docker
stevebus@ubuntu2:~$ docker version
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Mon Jun 25 20:43:05 2018
  OS/Arch:      linux/amd64
  Experimental: false

## Logs
nothing of interest in the logs.  you see the client connect in edgeHub (snippet below).  After that, nothing is logged (except the first 20 messages getting logged in the logger module's logs)

## Additional Information
Code...

here is my MQTT client code with the PII removed
```python
from paho.mqtt import client as mqtt
import ssl
import time
import random

path_to_root_cert = '<$CERTDIR>/certs/azure-iot-test-only.root.ca.cert.pem' # e.g. './azure-iot-test-only.root.ca.cert.pem'

device_id = "<device id>" # e.g. "myIoTDevice"

sas_token = "<sas token>"

iot_hub_name = "<iot hub name>" #e.g. exampleIoTHub

#EDGE - the FQDN of the device.. for example: myedgedevice.local

edge_device_name = "<edge device name>"

def on_connect(client, userdata, flags, rc):
    print ("Device connected with result code: " + str(rc))
def on_disconnect(client, userdata, rc):
    print ("Device disconnected with result code: " + str(rc))
def on_publish(client, userdata, mid):
    print ("Device sent message")

client = mqtt.Client(client_id=device_id, protocol=mqtt.MQTTv311)

client.on_connect = on_connect

client.on_disconnect = on_disconnect

client.on_publish = on_publish

#EDGE - we need to add the + "/api-version=2016-11-14" (api version) to the end of the username. Technically, you can do this if you are talking directly to IoTHub as well, but it's optional. Edge seems to require it.

client.username_pw_set(username=iot_hub_name+".azure-devices.net/" + device_id + "/api-version=2016-11-14", password=sas_token)

client.tls_set(ca_certs=path_to_root_cert, certfile=None, keyfile=None, cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLSv1, ciphers=None)

client.tls_insecure_set(False)

client.connect(edge_device_name, port=8883)
i = 1
m = 1
while i < 10:
  cdxMessage = """
  {"header":{"version":1},"data":{"patientSessionId":"9999999","filterIntervalSecs":0,"token":0,"ClinicId":"1276","mrn":"5000077333","treatmentId":"25457343","machineNumber":"","DialyzerType":"","AccessType":"","machineData":[{"recordId$
 """ 
  client.publish("devices/" + device_id + "/messages/events/", cdxMessage, qos=1)
  #i += 1
  time.sleep(5)
  print ("Device sent message " + str(m))
  m += 1
```

for logging, I'm using this module ->   stevebuscr.azurecr.io/logmodule:0.0.1-amd64   (nothing of PII importance there)

for routing, I'm using this route...

```json
{
  "routes": {
    "leaftologger": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId)  INTO BrokeredEndpoint(\"/modules/logmodule/inputs/input1\")",
    "leaftoiothub": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId)  INTO $upstream"
  }
}
```

**Comment by stevebus** [comment]
FYI - after some troubleshooting, this same script fails against IoT Hub itself, so this is not an IoT Edge problem specifically.  Will close the issue and re-open elsewhere after some more troubleshooting.

**Comment by Gowresh-MARC** [comment]
Was this issue solved? I am having the same issue. I am sending data every second and after 19 messages, the logging in Device Explorer Twin stops but my python script gives no error.

**Comment by stevebus** [comment]
Hey @Gowresh-MARC  -  I'm going from a 3 year old memory :-), but I believe my code above was not calling the "network loop" functions as described here -> https://pypi.org/project/paho-mqtt/#network-loop

I think by not servicing the incoming networking loop, the client wasn't getting the "ACKs" back from the messages it sent, so it stopped.  That's my theory at least...

So you need to add a call to 

client.loop_start() 

before the call to client.connect() above.  See if that helps.

--Steve

**Comment by Gowresh-MARC** [comment]
> Hey @Gowresh-MARC - I'm going from a 3 year old memory :-), but I believe my code above was not calling the "network loop" functions as described here -> https://pypi.org/project/paho-mqtt/#network-loop
> 
> I think by not servicing the incoming networking loop, the client wasn't getting the "ACKs" back from the messages it sent, so it stopped. That's my theory at least...
> 
> So you need to add a call to
> 
> client.loop_start()
> 
> before the call to client.connect() above. See if that helps.
> 
> --Steve

Hi @stevebus - adding `client.loop_start()` solved the issue. Thank you very much.
