### ISSUE TITLE
Issue with user permissions to manipulate binded directory

### ISSUE THREAD

**Issue by koncewiczbartosz** [Azure/iotedge#2782]
Hi team,

I am working on a app which is detecting files in directory which is bound on host and sends the files to blobs on Azure.

The issue I experience is that the app cannot delete files in that directory, because:

> The process cannot access the file 'C:\app\data\upload\file.xml' because it is being used by another process.

I am using FileSystemWatcher, but I don't think it is the issue, because this happens **only on Windows containers on Windows** (with moby engine) - other scenarios such as

- Linux on Linux (moby)
- Windows on Windows (Docker Desktop) 
- Linux on Windows (Docker Desktop) 

do work.

I bind folders likewise:

```
"createOptions": {
    "HostConfig": {
        "Binds": ["$HOST_DIRECTORY:$CONTAINER_DIRECTORY"]
    }
}
```

I do not know if this is related, but based on this [link](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module) I have changed ownership of binded folder to user with ID 1000 and it fixed the issue on Linux, so maybe is there similar solution on Windows?

Some additional information:

```
C:\Windows\system32>docker -H npipe:////./pipe/iotedge_moby_engine system info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 55
 Server Version: 3.0.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)
 OSType: windows
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.999GiB
 Name: KRKRNDIOT3
 ID: 10224a23-170c-43e3-9cbe-5e012ec55453
 Docker Root Dir: C:\ProgramData\iotedge-moby
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Dockerfile is pretty standard:

```
FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out
FROM microsoft/dotnet:2.2-runtime-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "project.dll"]
```

If there would some additional information needed I am more than happy to provide :)

**Comment by dylanbronson** [comment]
Hi, thanks for all the info!

I recommend double checking your app code to make sure that you are properly closing the file whenever you are done using it. This error will occur when you haven't closed it from somewhere else in your app. 

The reason you don't see it happening on any of the other scenarios is because Docker Desktop uses a Linux VM as the host of the containers. With Moby, the host is Windows. Linux allows the deletion of files while they're still open, but Windows does not by default.
