### ISSUE TITLE
Telemetry messages not appearing in DeviceExplorer

### ISSUE THREAD

**Issue by vermaaditya** [Azure/iotedge#2794]
Hi, 

We are trying to integrate the Kepware to IoT hub via IoT Edge. 

The connectivity is setup based on the inputs that are provided in the reported issue - https://github.com/Azure/iotedge/issues/2732.

We are also able to see the spike in the IoT hub overview on the Portal (attaching the image below) - 
![image](https://user-images.githubusercontent.com/20763984/78343115-fc43fb00-75b7-11ea-8669-952f59787836.png)

When we configure the message routing to Blob storage, we are able to see the telemetry messages in the specified container.

But when we try to read the data connecting a **device explorer**, or the **stream analytics** or using Azure IoT C# samples from https://github.com/Azure-Samples/azure-iot-samples-csharp/archive/master.zip, no message/events or error appears up.

Also, in the overview, we dont see any usage at the IoT hub - 
![image](https://user-images.githubusercontent.com/20763984/78343536-96a43e80-75b8-11ea-8655-e0e170c07290.png)

## Expected Behavior
The messages/ events should start propogating via DeviceExplorer/ Stream Analytics/ Azure IoT C# sample code.

## Current Behavior
The messages are only visible if the message routing is enabled in the blob storage.

## Steps to Reproduce
1. - We have followed the steps provided in the previous github issue that was reported - https://github.com/Azure/iotedge/issues/2732 to send messages to IoT hub
2. - Via Device explorer - Use the connection string from the IoT hub (iothubowner),
3. Go to the data tab and select the IoT edge device. The events are not appearing up
4. But a normal IoT device(not edge device) provisioned is working properly in all the 4 channels

Kindly provide inputs. 

Thanks,

**Comment by dylanbronson** [comment]
Hello @vermaaditya, thank you for all the info. I would like to confirm:

You have the message routing set up, and you are seeing your messages arrive to IoTHub? You said "The messages are only visible if the message routing is enabled in the blob storage." Do you mean the messages are visible in device explorer? Or elsewhere?

Message routing must be set up for the messages to flow to IoTHub. If your message routing is set up correctly, and you can see the messages arriving in IoTHub from your module through Edge, then I am not sure why you cannot see the messages in DeviceExplorer.

**Comment by vermaaditya** [comment]
The expected behavior is that the messages should be visible in DeviceExplorer/ Stream Analytics/ Azure IoT C# sample code. This is not happening. 
Messages are not visible in device explorer / Stream Analytics/ Azure IoT C# sample code.
They should appear in all the places.

**Comment by dylanbronson** [comment]
@vermaaditya Just to clarify, the messages are not visible, even though you have message routing set up, correct?

In the previous GH issue, it was mentioned that end-to-end data transmission was occurring successfully. How did you verify that previously? And is that still the case?

**Comment by dylanbronson** [comment]
"...with no message routing in scope"

This is likely your issue. You need to set an upstream route so that the messages can flow to IoTHub. Otherwise Edge will not know where to send the message.

You can see the below doc for more information:
https://docs.microsoft.com/en-us/azure/iot-edge/module-composition#declare-routes

Let me know if this helps and if I understood you correctly.

**Comment by vermaaditya** [comment]
@dylanbronson - that was a minor miss from my end. Based on the link - https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-d2c#built-in-endpoint, if a custom endpoint is created the in built endpoint are not functional. Thanks anyways..
