### ISSUE TITLE
Running edgeAgent container as non root

### ISSUE THREAD

**Issue by clustor** [Azure/iotedge#2795]
We have a requirement to run all containers as non-root from a security perspective. edgeHub is running already as "edgehubuser" but edgeAgent is running as a root. Reading through the code it looks like this might be needed to communicate with moby-runtime using  "unix:///var/run/docker.sock". Are there any recommendations on how to make this container to run as non-root user?

## Expected Behavior
edgeAgent should be running as non-root user

## Current Behavior
edgeAgent is currently running as root user inside the container

## Steps to Reproduce
1. Create an IoT edge device
2. Install IoT edge run time 
3. Start the iotedge run time on device

## Context (Environment)
Ubuntu 18.04 LTS

### Output of `iotedge check`

```

√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 72 days (at 2020-06-14 18:46:57 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.

```

### Device Information
* Host OS : Ubuntu 18.04
* Architecture : amd64 
* Container OS : Linux containers

### Runtime Versions
* iotedged :  1.0.9
* Edge Agent : 1.0 
* Edge Hub : 1.0 
* Docker/Moby : 19.03.6 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

**Comment by dylanbronson** [comment]
Hi @clustor, thanks for your question.

While we don't support running edgeAgent as non-root out of the box, it should be possible.

One way to do this would be to create a new image for edgeAgent, which uses edgeAgent as a base and add lines to the Dockerfile like this: 

# Add an unprivileged user account for running Edge Agent    
ARG EDGEAGENTUSER_ID=1000   
RUN adduser -Ds /bin/sh -u ${EDGEAGENTUSER_ID} edgeagentuser
USER edgeagentuser 

Then you would also need to modify the management socket, at "edgelet/contrib/systemd/debian/iotedge.mgmt.socket." You need to match user/group id in the agent image to the persmissions in this file. Or you can modify that file directly.

(thanks to @darobs for the recommendation on how to achieve this)

**Comment by arsing** [comment]
>Reading through the code it looks like this might be needed to communicate with moby-runtime using "unix:///var/run/docker.sock".

FYI, Edge Agent does not need to talk to Docker. There is code in Edge Agent to talk to Docker directly ("docker mode") but that is not used. The default mode of operation is for it to talk to `iotedged` over the management endpoint ("edgelet mode").
