### ISSUE TITLE
CLI command for doing blocking synchronous update for use with testing

### ISSUE THREAD

**Issue by admayber** [Azure/iotedge#2834]
It would be extremely useful for testing purposes to have a cli command available that would force a sync with the IoT Hub, block until any changes to the deployment are complete (image pull, container restart, etc.), and issue a nonzero exit code in case of a failure.

The use case for this is that we run regular end-to-end tests of our edge deployment by spinning up VMs with IoT Edge and running our deployment on them. However, in order to properly determine when to start the test hooks, and to guard against errors in the deployment process, requires constant asynchronous monitoring of the iot edge logs and list of active modules. 

It would streamline our tests considerably and reduce spurious errors if there was a command we could run that would force an update and block until it was finished, or else give an error code. Ideally we could run this command and on completion either engage our test hooks in case of success or raise an error with the command output for diagnostic purposes. The closest analogue would be something like the "docker pull" command in that it also monitors an async process, blocks to completion, and reports a status code on failure.

**Comment by veyalla** [comment]
Thanks for the feedback. Can you elaborate on what “block” means? In this mode, what shouldn’t it do that it is currently doing ?

**Comment by admayber** [comment]
Ah sure, thanks for responding. I just meant blocking in the sense of asynchronous calls being blocking or non-blocking. The method we currently use to set up the deployment is run the set-modules cli command and then monitor the runtime until things are up. In this case I would consider set-modules a non-blocking async setup command, since it release control before the task is complete. 

To bring up the example again, a blocking setup command would function more like docker pull, which holds control until the task has either succeeded or failed. A major advantage of this from our perspective is that we can get a status code and error messages all in one place. With the set-modules command we have to continuously check the "iotedge list" output and use a timeout in case there is some kind of error, since we don't want to get into the business of building a parser for the iotedge service logs.

A small mockup of what I'm thinking for clarity:

command: az iot edge set-local-modules <device and deployment parameters>

output: # effectively just the docker service logs, maybe more detailed output
Pulling image <xyz>.... Successfully pulled
Starting module <xyz>.... Module started
Pulling image <abcd>.... Error: Could not pull... <detailed output>
# could either stop here or continue trying to pull other modules and issue an overall failure report at the end

**Comment by veyalla** [comment]
Thanks for clarifying.

The challenge with this is “set-modules” is essentially a wrapper over setting the edge agent’s twin with the desired state, and twin operations are inherently asynchronous.

A better approach to monitoring the output of ‘iotedge list’ would be leverage the reported properties of the edgeAgent. This can be monitored cloud side to ensure the desired changes have been applied before triggering your tests. 

Further, you can implement a bespoke readiness mechanism in your custom modules using its own reported properties. You can monitor these reported properties in the cloud to ensure the component is in the right state before starting your tests.
