### ISSUE TITLE
Not All Create Options in the Azure Portal are being copied to the EdgeAgent deployment

### ISSUE THREAD

**Issue by m-monson** [Azure/iotedge#2844]
## Expected Behavior
I was expecting to see the EdgeAgent > Create Options I set in the Azure Portal show up in the actual deployment.  

NOTE: Everything works as expected when I use exactly the same Create Options on Edge Hub. It is **Only** Edge Device that has the problem.  Note that I did not set them at the same time (only the hub or the agent not both)

## Current Behavior
When inspecting the edge agent settings with "sudo docker inspect" I only see the environment variables I added not the port binding or port expose. 

## Steps to Reproduce
1. Enter the following in the Edge Agent Create Options tab in the portal  located at:
Home > Mt-IoT-Hub | IoT Edge > myEdgeDevice > Set modules on device: myEdgeDevice
```
{
  "HostConfig": {
    "PortBindings": {
      "9600/tcp": [
        {
          "HostPort": "9600"
        }
      ]
    }
  },
  "ExposedPorts": {
    "9600/tcp": {}
  }
}
```
2.  Enter the following environment variables in the same tab
experimentalfeatures__enabled true
experimentalfeatures__enableMetrics true 

## Context (Environment)
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

### Output of `iotedge check`
azureuser@diagnosticVm:~$ sudo iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
‼ config.yaml has correct hostname - Warning
    config.yaml has hostname diagnosticVm which does not comply with RFC 1035.

    - Hostname must be between 1 and 255 octets inclusive.
    - Each label in the hostname (component separated by ".") must be between 1 and 63 octets inclusive.
    - Each label must start with an ASCII alphabet character (a-z), end with an ASCII alphanumeric character (a-z, 0-9), and must contain only ASCII alphanumeric characters or hyphens (a-z, 0-9, "-").

    Not complying with RFC 1035 may cause errors during the TLS handshake with modules and downstream devices.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.8 but 1.0.9 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

18 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.details>
<summary>Click here</summary>

 I am trying to scrape the EdgeAgent metrics as specified in your doc/BuiltInMetrics.md document. 
I am using a module operating in host mode so I need to bind and expose port 9600.  I entered the following configuration into the Create Options section of the Edge Agent Configuration in the Azure Portal.  This is the path to the settings:
Home > Diagnostic-IoT-Hub | IoT Edge > myEdgeDevice > Set modules on device: myEdgeDevice
EdgeAgent 
     Create Options
```
{
  "HostConfig": {
    "PortBindings": {
      "9600/tcp": [
        {
          "HostPort": "9600"
        }
      ]
    }
  },
  "ExposedPorts": {
    "9600/tcp": {}
  }
}
experimentalfeatures__enabled true
experimentalfeatures__enableMetrics true 
```
</details>
### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.9)]: 
* Edge Hub [image tag (e.g. 1.0.9)]: 
* Docker/Moby [run `docker version`]: 
azureuser@diagnosticVm:~$ sudo docker version
Client:
 Version:           3.0.11+azure
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        eb310fca49568dccd87c6136f774ef6fff2a1b51
 Built:             Tue Mar  3 21:59:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.11+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       aa6a9891b0
  Built:            Tue Mar 10 18:53:36 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Logs

<details>
<summary>edge-agent configuration</summary>

```
"HostConfig": {
  ...
		"PortBindings": null,
  ...```
</details>

<details>
<summary>edge-hub configuration</summary>

```
"HostConfig": {
  ...
		"PortBindings": null,
  ...```
</details>

<details>
<summary>edge-hub configuration </summary>
```
"HostConfig": {
  ...
      "PortBindings": {
          "9600/tcp": [
              {
                  "HostIp": "",
                  "HostPort": "9600"
              }
          ]
      },
  ...
"Config": { 
	...
      "ExposedPorts": {
            "443/tcp": {},
            "5671/tcp": {},
            "8883/tcp": {},
            "9600/tcp": {}
        },
  ...
```
</details>
[bug_report.json.txt](https://github.com/Azure/iotedge/files/4477944/bug_report.json.txt)

## Additional Information
Like I mentioned everything works as expected for edgeHub, but for edgeAgent only the environment variables are getting included in the config. 

Just to be sure it wasn't an issue with my config I followed the steps at: https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux. to create the VM and the edge device.  I see the same issue whether I have any additional modules loaded or just the hub and agent.

The attached file 4477944/bug_report.json.txt has the docker inspect output for both the EdgeHub (which works) and EdgeAgent (which has the issue)

**Comment by and-rewsmith** [comment]
Hi @m-monson and thanks for the bug report!

There is currently a bug where edge agent will fail to update its environment variables or CreateOptions unless the image changes. A PR to fix this is open here:
https://github.com/Azure/iotedge/pull/2828

This sounds like it may be causing your issue, although I would have expected the environment variable update to also not have worked. Is it possible that the image tag changed when you made the update to the environment variables?

If so, then we are already working on a fix.

**Comment by and-rewsmith** [comment]
@m-monson Any update?
