### ISSUE TITLE
IotEdge windows device modules not sending data to IoT hub

### ISSUE THREAD

**Issue by sharadrumane** [Azure/iotedge#2847]
i have successfully deployed my modules on iotedge windows device. i am able to check the logs of all the deployed modules. but my modules are not sending data to IoT Hub. i tried doing basic troubleshooting  but didn't get any result. is there any specific setting that i need to do? beacuse my linux device modules are sending data to IoT Hub, only i am facing issue with my windows device

**Comment by RotateAt60MPH** [comment]
I've found that if you follow the support template for new issues, the technical folks are much more likely to be able to help.  As you posted, there's not a lot of info to go on.  Hope this helps.

**Comment by and-rewsmith** [comment]
+1 for the support template. Are you familiar with the [this resource](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot)? It contains a lot of helpful troubleshooting steps.

**Comment by and-rewsmith** [comment]
@sharadrumane Any updates?
