### ISSUE TITLE
Can't report Json array by using Module twin (properties.reported)? 

### ISSUE THREAD

**Issue by LiangJy123** [Azure/iotedge#2882]
Hi,
I just wanted to make sure if module twin can report Json array or not.
The scenario is listing all usb device plugged in edge device and upload  the device list to the cloud by using module twin ( properties.reported ) .
My test array is :
```
{"test":[{"k":"1"},{"k":"2"}]}
``` 
and I get the error log at edgeHub:
![image](https://user-images.githubusercontent.com/13048899/80280284-b3eea780-8735-11ea-9c03-18ebf5081e67.png)

Environment:
Linux 
Pi 3 
iotedge 1.0.9
EdgeHub - Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
EdgeAgent - Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)

Thanks.

**Comment by arsing** [comment]
Correct, arrays are not supported. This is a limitation of IoT Hub as documented [here.](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format)

You may want to do what we do for createOptions in Edge Agent's twin, which is to take an arbitrary JSON value (which may include arrays, may have more nesting that IoT Hub allows, etc) and stringify it. Then from IoT Hub's point-of-view it just appears as a string and is allowed. Of course then whatever client accesses the reported property also needs to manually deserialize the string.
