### ISSUE TITLE
IoT Edge deployment is repeatedly attempting to take place in a loop

### ISSUE THREAD

**Issue by nabeelmsft** [Azure/iotedge#2908]
Hi Team,

Customer has reported that they are constantly receiving the following loT Edge log entries:

2020-04-24 16:17:30.953 +00:00 [INF] - Plan execution started for deployment 93
2020-04-24 16:17:30.953 +00:00 [INF] - Plan execution ended for deployment 93
2020-04-24 16:17:36.492 +00:00 [INF] - Plan execution started for deployment 93
2020-04-24 16:17:36.492 +00:00 [INF] - Plan execution ended for deployment 93

It looks like the deployment is repeatedly attempting to take place and the above mentioned log is being generated. This loop is causing a huge consumption of data. The expectation for the deployment is to kick off once a day but it looks like there is an infinite loop where the execution of deployment is being kicked off in quick succession.  

Is this issue with Edge Platform or docker or something in the code. 

Additional information
To give more context, the customer has established the imagePullpolicy of "on-create" as mentioned here: https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-runtime#iot-edge-agent

This issue was surfaced when customer was reviewing the following warning:
Apr 16 22:27:02 cs-v04-000-0937 iotedged[3574]: 2020-04-17T03:27:02Z [WARN] - Could not pull image csicontainers.azurecr.io/oos-detection-app:0.0.22-amd64
Apr 16 22:27:02 cs-v04-000-0937 iotedged[3574]: 2020-04-17T03:27:02Z [WARN] -        caused by: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/e227e1214b9d14e744b7982c68df79b34e14ba9b3145e84f24815c495fe08926/merged: too many levels of symbolic links
Looks like it is indicating that the IoT Edge daemon is trying to pull new containers, but failing. 

 

Thank you!

**Comment by philipktlin** [comment]
This should be docker related issue.  Please try to pull the image manually using docker image pull command, and I expected the same error will show up.

**Comment by ebertrams** [comment]
@nabeelmsft has this issue been solved? If not please add some more details. We will close the bug otherwise.

**Comment by nabeelmsft** [comment]
Hello @ebertrams, I have provided the information to customer regarding that this issue seems to be a docker related issue. The customer mentioned they are have told their Dev team about this being a docker issue and the dev. is looking into that. In the meantime, the customer has asked us if there are any suggestions of how to minimize/prevent that bug from happening that we can share.

**Comment by philipktlin** [comment]
Same problem is reported here, https://github.com/docker/for-win/issues/5763.  And check this out, https://serverfault.com/questions/640895/why-do-some-host-volumes-in-docker-containers-give-the-error-too-many-levels-of, it may help.

**Comment by nabeelmsft** [comment]
Thanks @philipktlin for providing more information. I have forwarded the information to the customer. Since this appears to be docker related issue, I am going to close the bug. Thanks for all the help!

**Comment by gridpatrik** [comment]
We're seeing this issue from time to time and now it has occurred on a device shipped across the globe.
