### ISSUE TITLE
Status of Edge Runtime is not updating on Azure Portal Under IoT Hub Edge Device

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#2931]
Hi Team,
   We are facing one issue currently in production environment. Details are below..

1. We have edge runtime 1.0.8 on production gateway
2. Edge runtime is runing fine on the gateway and all the modules also running fine. 
3. But the status on IoT Hub edge Device it is showing 500 "An error occured in the ioT Edge Runtime" 
4. So could you please let me know the reason for this as it is depicting wrong status. 

Screenshot is 
![image](https://user-images.githubusercontent.com/4133423/81315558-bd0f3b00-908a-11ea-9acc-b83c1648cc92.png)

**Comment by damonbarry** [comment]
@sachidanand If you look at $edgeAgent's twin in the portal, you should find

```json
"lastDesiredStatus": {
  "code": 500,
  "description": "..."
}
```

That's where this value is coming from. Edge Agent reports code=500 if there was some problem reconciling an incoming deployment config with the current state of the device, or if it encountered a problem while generating the outbound reported properties in response to the inbound desired properties. Especially in the latter case (reconcile succeeded but reporting failed), it makes sense that your edge device would continue to operate normally even though there was a reporting error.

If this is what you're seeing, then we'd need to examine the logs at the point where the reporting failure occurred to figure out what happened.

**Comment by damonbarry** [comment]
@sachidanand Also note that a change went into 1.0.8.3 (PR #1795) that fixes a problem customers were reporting related to runtime status. I'm not sure which patch of 1.0.8 you're running, but if it's 1.0.8.1 or 1.0.8.2, then you should see different behavior after you upgrade.

**Comment by sachidanand** [comment]
We are using runtime 1.0.8 on production right now ...... So if we will migrate to runtime version 1.0.9 then it should be fixed right ???

**Comment by sachidanand** [comment]
> @sachidanand If you look at $edgeAgent's twin in the portal, you should find
> 
> ```json
> "lastDesiredStatus": {
>   "code": 500,
>   "description": "..."
> }
> ```
> 
> That's where this value is coming from. Edge Agent reports code=500 if there was some problem reconciling an incoming deployment config with the current state of the device, or if it encountered a problem while generating the outbound reported properties in response to the inbound desired properties. Especially in the latter case (reconcile succeeded but reporting failed), it makes sense that your edge device would continue to operate normally even though there was a reporting error.
> 
> If this is what you're seeing, then we'd need to examine the logs at the point where the reporting failure occurred to figure out what happened.

We are getting the below details in EdgeAgent reported property
 "lastDesiredStatus": {
        "code": 500,
        "description": "Operation timed out"
      },
  },
      "runtime": {
        "platform": {
          "os": "windows",
          "architecture": "x86_64",
          "version": "1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)"
        },

**Comment by damonbarry** [comment]
> We are using runtime 1.0.8 on production right now ...... So if we will migrate to runtime version 1.0.9 then it should be fixed right ???

Not sure what you mean by "fixed", but the change that went into 1.0.8.3+ won't prevent 500 status from showing up in the portal However it will prevent that status from hanging around indefinitely after the problem has been corrected. For example, if a transient network issue caused the reported properties update to time out, then you'd see 500 status in the portal. But later, when reported properties are updated, the status should return to 200 "success".

**Comment by sachidanand** [comment]
So is it issue right now with 1.0.8 that it is not updating 200 once it turns to 500 error???

**Comment by damonbarry** [comment]
@sachidanand I think that's true at least in some cases, not all. And It was fixed in 1.0.8.3 so the latest 1.0.8 does not have this problem.

**Comment by sachidanand** [comment]
So in this case it is just issue that it is not updating status to IoT Hub in reported property. And because of this we should not loss any data right because other modules are working fine in this device ...

**Comment by damonbarry** [comment]
Yes, that's correct.

**Comment by ebertrams** [comment]
@sachidanand Can you try with the latest version of IoT Edge to confirm that we can close this issue? Thanks!

**Comment by sachidanand** [comment]
Hi Team,
    I can't go with latest version on production right now as we need to test it first with our all the custom modules and then only we can update it in fleet. 
I have collected some logs from production gateway so could you check them once and let me know the issue ...


`Edge Agent`:
<6> 2020-05-18 06:25:22.537 +02:00 [INF] - Successfully completed periodic operation refresh twin config
<4> 2020-05-18 07:11:11.470 +02:00 [WRN] - Reconcile failed because of the an exception
System.TimeoutException: Operation timed out
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in C:\agent\_work\4\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 117
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation)
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\versioning\ModuleManagementHttpClientVersioned.cs:line 124
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_01_30.ModuleManagementHttpClient.GetModules[T](CancellationToken cancellationToken) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\version_2019_01_30\ModuleManagementHttpClient.cs:line 137
   at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironment.GetModulesAsync(CancellationToken token) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Docker\DockerEnvironment.cs:line 50
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.GetCurrentModuleSetAsync(CancellationToken token) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 223
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 117
<6> 2020-05-18 07:11:11.758 +02:00 [INF] - Updated reported properties
<6> 2020-05-18 07:11:17.131 +02:00 [INF] - Updated reported properties
<6> 2020-05-18 07:25:22.542 +02:00 [INF] - Starting periodic operation refresh twin config...


`Edge Runtime`:
8.05.2020 14:01:28 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:01:28.798305 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:01:33 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:01:33.895718 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:01:38 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:01:38.970783300 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:01:44 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:01:44.043967800 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:01:47 error: edgelet_http -- server connection error: (unknown)
18.05.2020 14:01:47 error: edgelet_utils::logging -- error writing a body to connection: An existing connection was forcibly closed by the
                    remote host. (os error 10054)
18.05.2020 14:01:49 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:01:49.119459200 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:01:54 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:01:54.229169 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:01:56 info: edgelet_core::watchdog -- Checking edge runtime status
18.05.2020 14:01:56 info: edgelet_core::watchdog -- Edge runtime is running.
18.05.2020 14:01:59 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:01:59.330638600 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:02:04 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:02:04.608777700 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:02:09 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:02:09.720402800 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
18.05.2020 14:02:14 info: edgelet_http::logging -- [mgmt] - - - [2020-05-18 12:02:14.790283800 UTC] "GET /modules?api-version=2019-01-30
                    HTTP/1.1" 200 OK 48309 "-" "-" auth_id(-)
