### ISSUE TITLE
[Question] Observe connectionstate of Leaf-Devices

### ISSUE THREAD

**Issue by burgerTo** [Azure/iotedge#2935]
Hi, 
I'm looking for a way to observe the connection state of leaf-Devices, which are connected to the edge-hub. 
The secenario is: We have a edge-module, which needs to know the connection state of every leaf-device. Also if the edge is not connected to the iot-hub. 

On the iot-hub, I have the possibiliy to register to "connection events" through the "Diagnostic settings"->eventGrid. 

Is there a similar way on the edge-hub? Maybe some "edge-hub-events" which reports connection events? 

Thanks. 
Best regards
Toni

**Comment by varunpuranik** [comment]
@burgerTo - EdgeHub currently does not expose such events to clients on the device. It will, however report the clients that connect/disconnect in its reported properties. So you can monitor the EdgeHub reported properties in the cloud and find out which client has connected/disconnected.

**Comment by ebertrams** [comment]
Hi @burgerTo, Did @varunpuranik  answer your question? Could we mark it as closed? Thanks!

**Comment by burgerTo** [comment]
Hi, 
thanks for the answer and sorry for the late response. 
I will try it out. 
If i got it right, I can only monitor the edgeHub reported properties when there is a existing cloud connection? (Like it is needed for all other twin-operations) 
In my use-case, i need to monitor the connection state of the leaf devices, when there is no active connection from edge to the iot-hub.

**Comment by ebertrams** [comment]
@burgerTo your understanding is correct. To monitor leaf device states you do need a cloud access today to look at edgeHub's reported properties. There is no workaround to do that today without cloud connectivity. I'll add a feature request in our backlog. Thanks.

**Comment by varunpuranik** [comment]
Closing the issue, as per @ebertrams comment.
