### ISSUE TITLE
Problem with New IoT edge release - EdgeHub : 417 -- The device's deployment configuration is not set

### ISSUE THREAD

**Issue by nitinkhandelwal26** [Azure/iotedge#2941]
Dear IoT Edge Team,

There is problem with the new IoT edge release. $edgehub module is not getting configured. I have run all the given command but it's not working and showing status: 417 -- The device's deployment configuration is not set
I also deployed Azure Marketplace offering for Azure IoT Edge on Ubuntu, still the same issue. 417 -- The device's deployment configuration is not set.

I executed > iotedge check --verbose
× Edge Hub can bind to ports on host - Error
Could not check current state of Edge Hub container
caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub

And when I check status on edge VM its only showing agent status there is no edge hub.

Way to reproduce the Bug:
Can you please check by deploying Marketplace offering for Azure IoT Edge on ubuntu or running commands given in 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux
, you will find the problem.

Please help me with priority.

root@iotedge:/home/iotadm# iotedge restart edgeAgent && iotedge restart edgeHub
edgeAgent
A module runtime error occurred
caused by: Could not restart module edgeHub
caused by: Client error

Regards,
Nitin

**Comment by dylanbronson** [comment]
Hello, just to make sure - have you created a deployment? In order for edgeHub to be deployed, it needs its deployment manifest to be set. 
To do so, you can go through your portal and set the deployment manifest from your IoTHub. 

More info here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-modules-portal
Make sure to remember to provision your device either a) manually or b) with DPS. Instructions for both options can be found here: 

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux#option-1-manual-provisioning

If you have checked this with no success, let us know please.

**Comment by nitinkhandelwal26** [comment]
@dylanbronson It worked after deployment of simulated Temperature sensor module, 

Also, after doing iotedge check --verbose on my edge VM,
I got a few warnings in which one was

bangbang  latest security daemon - Warning
Installed IoT Edge daemon has version 1.0.8 but 1.0.9 is the latest stable version available.
Please see https://aka.ms/iotedge-update-runtime for update instructions.

when I upgrade my edge with the article given above, it's still showing the same warning,

It means IoT edge is still running on 1.0.8 :

root@iotedge:/home/iotadm# iotedge version
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

There is no way to upgrade it to latest version 1.0.9,
Can you please check the version of your IoT edge and open the relevant bug if your version is also 1.0.8.

**Comment by darobs** [comment]
Hell0 @nitinkhandelwal26 ,

It looks like your initial problem has been fixed.

I just ran into the same problem with the iotedge version, and it may be a problem with the Microsoft product list used by apt-get. 
Please follow the instructions to [install the Microsoft software repository feed](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux#register-microsoft-key-and-software-repository-feed), or you can also get the binaries from [our release Github project](https://github.com/Azure/azure-iotedge/releases).

Updating the repository feed worked for me.

Closing this issue, but you are welcome to reopen it or create another issue if this has not been resolved.
