### ISSUE TITLE
Keep direct method name and playload in browser after sending

### ISSUE THREAD

**Issue by peirens-bart** [Azure/iotedge#2943]
## Expected Behavior
When a user is filling in a "method Name" and "Payload" the info is preserved after "Invoke Method" is clicked.

## Current Behavior
"method Name" and "Payload" is empty after "Invoke Method" is clicked.

## Steps to Reproduce

1. Go to the "Direct Method" tab of a module in the Azure portal
2. Fill in "Method Name" and "Payload"
3. Click on "Invoke Method"
4. Fill in the info again when a new invoke is needed

## Context (Environment)

Azure portal

## Additional Information
It would be handy if the info is preserved because we use this feature for starting an RFID reader in test fase. in prodcution the start command is invoked from a GPIO input module.
now we need to create the start json payload every time.

Ideal a user has a direct command history list where he can select a line in that list for sending the same command again. or even play the whole history again.

**Comment by darobs** [comment]
Hello @peirens-bart 

This is a great suggestion.  The best place for features and usability suggestions would be [IoT User Voice](https://feedback.azure.com/forums/321918-azure-iot), but I will also point our team members responsible for the portal UX to this issue.

**Comment by peirens-bart** [comment]
@darobs Thanks, do I add this request in IoT user voice?

**Comment by darobs** [comment]
Yes. I contacted the portal UX team and they added this to the backlog.  Adding the request in User Voice helps the team set priorities for enhancements like this.  Thank you for your contribution!

**Comment by darobs** [comment]
After contacting the Portal UX team, they have added this to their feature backlog. I'm not privy to their schedule, so I don't have an ETA.

Closing this issue as there is no work to be done in this repository.  Thank you!
