### ISSUE TITLE
IoT Edge Device primary thumbprint

### ISSUE THREAD

**Issue by amogh79** [Azure/iotedge#2951]
Hi,

I followed the steps here https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs and was successfully able to auto provision a IoT Edge device onto the IoT hub. 

I can see the IoT Edge Device in the linked IoT  Hub, I am unable to understand though as which certificate's thumbprint is in the primary and secondary thumbprint.

Can you please clarify on this?

Thanks
Amogh

**Comment by darobs** [comment]
These should correspond to the "Primary Certificate" and "Secondary Certificate" when you establish your enrollment in DPS. When I tried this with only a primary certificate, the primary thumbprint is duplicated into the secondary.

You can see the thumbprints of the primary and secondary certificate you uploaded if you go to the "Manage Enrollments" section  on the DPS portal page.

**Comment by amogh79** [comment]
Thanks for your response.
I checked per comments but surprisingly the thumbprint of the certificates in the DPS and that of the device provisioned in IoT hub via same enrollment group on DPS do not match. Any thoughts on which certificate's thumb print is shown against the device in IoT Hub?

**Comment by darobs** [comment]
The difference between the thumbprint on the Hub and the thumbprint in DPS is the digest used.  DPS is showing SHA1 and the hub is showing SHA256.
I confirmed this by 
```
openssl x509 -noout -fingerprint -sha256 -in <my-cert>
```
and compared it to the thumbprint for the device in the portal. They matched.

This command:
```
 openssl x509 -noout -fingerprint -in <my-cert>
```
matched the thumbprint in DPS.

**Comment by ebertrams** [comment]
@amogh79  does darobs's reply answer your question? Could we close this issue? Thanks!

**Comment by ebertrams** [comment]
@amogh79 any updates on this item? Can we close it? Thanks!

**Comment by amogh79** [comment]
Sorry for the delays please close this I was able to use the command

**Comment by damonbarry** [comment]
Thanks!
