### ISSUE TITLE
Module to Module communication - delayed message acknowledgment 

### ISSUE THREAD

**Issue by bamajeed** [Azure/iotedge#2955]
Question about Module to Module communication: Module A sends a message to Module B. Module B occasionally takes a long time to process the message so EdgeHub resends the message to Module B triggering a duplicate processing of the message. How can we avoid such scenarion?

**Comment by darobs** [comment]
Thank you @bamajeed, 

Please look at https://github.com/Azure/iotedge/issues/832 for some suggestions on how to handle this.

**Comment by ebertrams** [comment]
@bamajeed Does darobs's reply answer your question? Can we close this ticket? Thanks!
