### ISSUE TITLE
Direct Method Scheduled Job Always Times Out for IOT Edge Device Modules

### ISSUE THREAD

**Issue by vvaibhav-msft** [Azure/iotedge#2958]
## Expected Behavior
On Scheduling Device Method to call Direct Method on Device Modules in IOT Edge should succeed

## Current Behavior
The Scheduled Job always fails with Code "Device Not Online" and Description "Timed out waiting for device to connect"

## Steps to Reproduce
**1.** From Postman send the following request to schedule Direct Method call on IOT Edge Device Modules
PUT /jobs/v2/jobaj?api-version=2018-06-30 HTTP/1.1
Host: aware-edge-vvaibhav-iothub.azure-devices.net
Authorization: SharedAccessSignature sr=aware-edge-vvaibhav-iothub.azure-devices.net&sig=Vbbv7e6wZ1DX1xm94J%2BjXX5OG68FUshN8blea3f%2B9RM%3D&skn=iothubowner&se=1586886786
Content-Type: application/json; charset=utf-8
Content-Type: text/plain
 
{
    "jobId": "jobaj",
    "type": "scheduleDeviceMethod",
    "cloudToDeviceMethod": {
        "methodName": "refreshEdgeMonitoringRulesv",
        "payload": null,
        "responseTimeoutInSeconds": 30
    },
    "queryCondition": "FROM devices.modules WHERE ModuleId = 'AwareMonitoring'",
    "startTime": "2020-04-14T07:58:00.000Z",
    "maxExecutionTimeInSeconds": 30
}

**2.** In Azure Portal when I navigate to 
IOT Hub "aware-edge-vvaibhav-iothub" -> Query Explorer -> Jobs ->
and execute the query "SELECT * FROM c"

I see the job status as failed with error "DeviceNotOnline-Timed out waiting for device to connect".
**3.** I am following the documentation and guidance mentioned in the following links
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-jobs?view=azps-1.1.0
https://github.com/Azure/iotedge/issues/719

## Context (Environment)
Subscription ID: cbadc96b-2923-4459-bb2d-b237af7f84d6
Resource Group: aware-edge-vvaibhav
IOT HUB: aware-edge-vvaibhav-iothub

### Output of `iotedge check`
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 46 days (at 2020-06-30 07:38:05 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

18 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS- Linux container: 

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: Client:
 Version:           3.0.10+azure
 API version:       1.40
 Go version:        go1.12.14
 Git commit:        99c5edceb48d64c1aa5d09b8c9c499d431d98bb9
 Built:             Tue Nov  5 00:55:15 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<6> 2020-05-13 14:38:39.008 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 14:38:39.016 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 14:38:39.018 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 15:38:21.850 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-13 15:38:21.851 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-13 15:38:21.851 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-13 15:38:21.851 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-13 15:38:39.021 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 15:38:39.029 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 15:38:39.030 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 16:38:39.033 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 16:38:39.040 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 16:38:39.041 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 17:38:21.851 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-13 17:38:21.851 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-13 17:38:21.851 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-13 17:38:21.851 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-13 17:38:39.042 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 17:38:39.051 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 17:38:39.052 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 18:38:39.052 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 18:38:39.060 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 18:38:39.061 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 19:38:21.852 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-13 19:38:21.852 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-13 19:38:21.852 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-13 19:38:21.852 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-13 19:38:39.063 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 19:38:39.070 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 19:38:39.071 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 20:38:39.072 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 20:38:39.113 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 20:38:39.114 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 21:38:21.853 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-13 21:38:21.853 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-13 21:38:21.853 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-13 21:38:21.853 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-13 21:38:39.114 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 21:38:39.122 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 21:38:39.123 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 22:38:39.123 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 22:38:39.130 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 22:38:39.131 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-13 23:38:21.850 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-13 23:38:21.850 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-13 23:38:21.850 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-13 23:38:21.851 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-13 23:38:39.130 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-13 23:38:39.138 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-13 23:38:39.139 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 00:38:39.137 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 00:38:39.145 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 00:38:39.146 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 01:38:21.854 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-14 01:38:21.854 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-14 01:38:21.854 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-14 01:38:21.854 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-14 01:38:39.149 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 01:38:39.157 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 01:38:39.158 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 02:38:39.157 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 02:38:39.221 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 02:38:39.222 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 03:38:21.849 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-14 03:38:21.849 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-14 03:38:21.849 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-14 03:38:21.849 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-14 03:38:39.223 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 03:38:39.230 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 03:38:39.231 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 04:38:39.228 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 04:38:39.236 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 04:38:39.237 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 05:38:21.850 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-14 05:38:21.850 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-14 05:38:21.850 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-14 05:38:21.850 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-14 05:38:39.241 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 05:38:39.249 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 05:38:39.250 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 06:38:39.249 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 06:38:39.259 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 06:38:39.259 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 07:38:21.849 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-14 07:38:21.849 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-14 07:38:21.850 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-14 07:38:21.850 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-14 07:38:39.260 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 07:38:39.269 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 07:38:39.270 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 08:38:39.271 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 08:38:39.280 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 08:38:39.281 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 09:38:21.850 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-14 09:38:21.850 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-14 09:38:21.851 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-14 09:38:21.851 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-14 09:38:39.282 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 09:38:39.303 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 09:38:39.304 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 10:38:39.307 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 10:38:39.316 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 10:38:39.316 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 11:38:21.849 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-14 11:38:21.849 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-14 11:38:21.849 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-14 11:38:21.849 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-14 11:38:39.318 +00:00 [INF] - Starting periodic operation refresh twin config...
6> 2020-05-14 11:38:39.326 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 11:38:39.327 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 12:38:39.327 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 12:38:39.337 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 12:38:39.338 +00:00 [INF] - Successfully completed periodic operation refresh twin config
<6> 2020-05-14 13:38:21.852 +00:00 [INF] - Starting compaction of stores
<6> 2020-05-14 13:38:21.852 +00:00 [INF] - Starting compaction of store default
<6> 2020-05-14 13:38:21.852 +00:00 [INF] - Starting compaction of store deploymentConfig
<6> 2020-05-14 13:38:21.852 +00:00 [INF] - Starting compaction of store moduleState
<6> 2020-05-14 13:38:39.337 +00:00 [INF] - Starting periodic operation refresh twin config...
<6> 2020-05-14 13:38:39.347 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 54 and reported properties version 128.
<6> 2020-05-14 13:38:39.348 +00:00 [INF] - Successfully completed periodic operation refresh twin config
[IOTEdgeCheckAndConfigYaml.docx](https://github.com/Azure/iotedge/files/4628931/IOTEdgeCheckAndConfigYaml.docx)

```
</details>

<details>
<summary>edge-hub logs</summary>

```

azureuser@vm-er2w2zzm3ud2m:~$ iotedge logs --tail 25 edgeHub
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, Cancella
tionToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
<4> 2020-05-14 14:10:08.391 +00:00 [WRN] - Unable to send message to aware-edge-vvaibhav-vm1/AwareMonitoring because ModuleMessages link was not found.
<4> 2020-05-14 14:10:38.394 +00:00 [WRN] - Did not receive ack for message 7a1ee00b-79c1-4ed9-801b-56f628f6470c from device/module aware-edge-vvaibhav-vm1/Awar
eMonitoring
<4> 2020-05-14 14:10:38.394 +00:00 [WRN] - Error sending messages to module aware-edge-vvaibhav-vm1/AwareMonitoring
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Mi
crosoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 427
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, Cancella
tionToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
<4> 2020-05-14 14:11:38.390 +00:00 [WRN] - Unable to send message to aware-edge-vvaibhav-vm1/AwareMonitoring because ModuleMessages link was not found.
<6> 2020-05-14 14:12:06.823 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2020-05-14 14:12:06.824 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.
<4> 2020-05-14 14:12:08.390 +00:00 [WRN] - Did not receive ack for message 3972a874-9e7d-4b80-a392-6fd1cb45b6de from device/module aware-edge-vvaibhav-vm1/Awar
eMonitoring
<4> 2020-05-14 14:12:08.390 +00:00 [WRN] - Error sending messages to module aware-edge-vvaibhav-vm1/AwareMonitoring
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Mi
crosoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 427
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, Cancella
tionToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
<6> 2020-05-14 14:12:36.823 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint aware-edge-vvaibhav-vm1/AwareMonitoring/events
<6> 2020-05-14 14:12:36.901 +00:00 [INF] - Cleaned up 370 messages from queue for endpoint aware-edge-vvaibhav-vm1/AwareMonitoring/events and 370 messages from
 message store.
<4> 2020-05-14 14:13:08.395 +00:00 [WRN] - Unable to send message to aware-edge-vvaibhav-vm1/AwareMonitoring because ModuleMessages link was not found.
<4> 2020-05-14 14:13:38.395 +00:00 [WRN] - Did not receive ack for message aed3d2ce-c911-410e-a1d1-bdb1c98d664e from device/module aware-edge-vvaibhav-vm1/Awar
eMonitoring
<4> 2020-05-14 14:13:38.395 +00:00 [WRN] - Error sending messages to module aware-edge-vvaibhav-vm1/AwareMonitoring
System.TimeoutException: Message completion response not received
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.SendMessageAsync(IMessage message, String input) in /home/vsts/work/1/s/edge-hub/src/Mi
crosoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 427
   at Microsoft.Azure.Devices.Edge.Hub.Core.Routing.ModuleEndpoint.ModuleMessageProcessor.ProcessAsync(ICollection`1 routingMessages, IDeviceProxy dp, Cancella
tionToken token) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/ModuleEndpoint.cs:line 167
<6> 2020-05-14 14:14:07.417 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2020-05-14 14:14:38.395 +00:00 [WRN] - Unable to send message to aware-edge-vvaibhav-vm1/AwareMonitoring because ModuleMessages link was not found.
```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vvaibhav-msft** [comment]
Attaching iotedge check logs and config.yaml file details
[IOTEdgeCheckAndConfigYaml.docx](https://github.com/Azure/iotedge/files/4628992/IOTEdgeCheckAndConfigYaml.docx)

**Comment by darobs** [comment]
Hello @vvaibhav-msft.

Thank you for reporting this. There's some investigation I'm doing to follow up on this.

**Comment by vvaibhav-msft** [comment]
Hi @darobs 
Is there any update on the findings here?

**Comment by yophilav** [comment]
Hello @vvaibhav-msft , 
From Azure portal, can you successfully ping the direct method to the module?

**Comment by vvaibhav-msft** [comment]
Hi,
Thank you very much for looking into this issue. I am able to ping the direct method from the azure portal.
However I always receive {"status":500,"payload":null} response.

There is another development as well. I see that direct method calls which I was attempting to make using Postman(complete request body shared in steps to reproduce above) and which were failing with "DeviceNotOnline-Timed out waiting for device to connect" error, are now succeeding as well.

However I have hit another snag now. I am always seeing response as
"deviceMethodResponse": {
        "status": 500,
        "payload": null
      }
whether I call the direct method from azure portal or schedule it using postman.

My postman request body looks like below
{
    "jobId": "jobvvaibhav32112",
    "type": "scheduleDeviceMethod",
    "cloudToDeviceMethod": {
        "methodName": "refreshEdgeMonitoringRules",
        "payload": "Test12",
        "responseTimeoutInSeconds": 30
    },
    "queryCondition": "FROM devices.modules WHERE ModuleId = 'AwareMonitoring'",
    "startTime": "2020-07-24T15:14:00.000Z",
    "maxExecutionTimeInSeconds": 30
}

and my direct method handler in code is also set to always return 200 status as below.

return new MethodResponse(Encoding.UTF8.GetBytes("{\"Test\":\"Value\"}"), StatusCodes.Status200OK);

Could you please advise why my payload is not making it to Direct Method and why I am always seeing status 500.

**Comment by yophilav** [comment]
**Could you please advise why my payload is not making it to Direct Method and why I am always seeing status 500.**
Hmmm... It seems like the edgeHub may have trouble connecting the IoTHub (unclear). I'll need to look at more logs to really see what's going on.

Could you please do the following: 
1. Run `iotedge support-bundle` and rename the output *.zip to something (so it wont' be overwrote by step3)
2. set `RuntimeLogLevel=debug` on edgeAgent (which should automatically set RuntimeLogLevel=debug on edgeHub as well)
3. Restart both edgeAgent and edgeHub using `docker restart edgeAgent edgeHub`
4. try the post man again
5. Run `iotedge support-bundle` one more time. And send me both support bundle. I'm not sure if the restarting the modules will fix the issue or not (it may?) but either way I'll have a detail logs on what's going on to investigate

Thank you!

**Comment by vvaibhav-msft** [comment]
I have shared the support_bundle in a separate email. When i did the step 4 after restarting the edgeAgent and edgeHub, this time the direct method call executed with 200 response status. Also my request payload value also showed correctly in the direct method.

**Comment by yophilav** [comment]
@vvaibhav-msft 
Thank you for the logs! They are very helpful.
From the logs, it looks like the `jobs` are being forwarded as a _message_ not as a _direct method_ as we presumed.
Could you please try subscribing to a message handle instead of a direct method handle in your client module please?
e.g. uses SetInputMessageHandlerAsync() instead of SetMethodHandlerAsync()

For `SetInputMessageHandlerAsync()` reference: 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient.setinputmessagehandlerasync?view=azure-dotnet
Note the parameter `inputName` for you is going to be the `refreshEdgeMonitoringRules`

**Comment by vvaibhav-msft** [comment]
When I use SetInputMessageHandlerAsync, the direct method is not triggered.
When i go back to using SetMethodHandlerAsync, it gets triggered.

**Comment by yophilav** [comment]
I'm closing this issue in favor of direct communication and using internal Work Item to track this issue .
