### ISSUE TITLE
Edge Runtime 1.0.9 is not working with Proxy And SSL Interception 

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#2973]
Hi Team,
    We have proxy based environment for edge gateway and we are trying to connect edge runtime 1.0.9 version over proxy. Now we are getting below error so could you help us to configure it.. 

Our Proxy has SSL interception which is certificate based so where should we upload this certificate so that edge runtime can read it as it is throwing exception of trusted certificate.. 

.05.2020 16:27:04 info: edgelet_docker::runtime -- Successfully initialized module runtime
18.05.2020 16:27:04 info: iotedged -- Removing all modules...
18.05.2020 16:27:04 info: iotedged -- Change to configuration file detected.
18.05.2020 16:27:04 info: iotedged -- Finished removing modules.
18.05.2020 16:27:04 info: iotedged -- Edge issuer CA expiration date: 2034-10-26T11:52:34Z
18.05.2020 16:27:08 info: iotedged -- Starting workload API...
18.05.2020 16:27:08 info: iotedged -- Starting management API...
18.05.2020 16:27:08 info: iotedged -- Listening on unix:///C:/ProgramData/iotedge/workload/sock with 1 thread for workload API.
18.05.2020 16:27:08 info: edgelet_core::watchdog -- Checking edge runtime status
18.05.2020 16:27:08 info: edgelet_core::watchdog -- Starting watchdog with 60 second frequency...
18.05.2020 16:27:08 info: iotedged -- Listening on unix:///C:/ProgramData/iotedge/mgmt/sock with 1 thread for management API.
18.05.2020 16:27:08 info: edgelet_core::watchdog -- Creating and starting edge runtime module edgeAgent
18.05.2020 16:27:08 warn: edgelet_utils::logging --     caused by: Could not get module $edgeAgent                                                                                  
18.05.2020 16:27:08 warn: edgelet_utils::logging --     caused by: Could not perform HTTP request                                                                                   
18.05.2020 16:27:08 warn: edgelet_utils::logging --     caused by: an error occurred trying to connect: A certificate chain processed, but terminated in a root certificate which is
                    not trusted by the trust provider. (os error -2146762487)
18.05.2020 16:27:08 warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
18.05.2020 16:27:08 warn: edgelet_utils::logging -- A module runtime error occurred.
18.05.2020 16:27:08 warn: edgelet_utils::logging --     caused by: Could not get identity $edgeAgent

**Comment by dmolokanov** [comment]
Hello @sachidanand. Could you please attach logs for iotedged, EdgeAgent, EdgeHub their version, OS version and `iotedge check` command output? It'll help to understand the environment you are trying edge on.

**Comment by sachidanand** [comment]
Hi Team,
    edgeAgent and edgeHub module are not there as Edge runtime is not able to call the HTTP request and because of that edgeAgent module is not downloaded here.. 

1. We are using windows 10 on Gateway 
2. Edge runtime version is 1.0.9 
3. Internet connection is via Proxy and our proxy is using SSL interception 
4. Output of iotedge check command 


PS C:\Users\Administrator> iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
PS C:\Users\Administrator> iotedge check
Configuration checks
--------------------
v config.yaml is well-formed - OK
v config.yaml has well-formed connection string - OK
v container engine is installed and functional - OK
v Windows host version is supported - OK
v config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.9' locally
    1.0.9: Pulling from azureiotedge-diagnostics
    docker: error pulling image configuration: Get https://mcrweu0.cdn.mscr.io/42012bb2682a4d76ba7fa17a9d9a9162-qb2vm9uiex//docker/registry/v2/blobs/sha256/b0/b0435914ddba2d8fa9e0e07c6e39cfadd2e910220ebd118c7a528a34d348fb8b/data?P1=1589880327&P2=1&P3=1&P4=teTiZ7A8rflCPhJL9Y2OfKctwULrJ1MPNF4zKxNFbhM%3D&se=2020-05-19T09%3A25%3A27Z&sig=pFQasHgsrhL9WI3%2Bg3IQoCGb3al7Y2kD31jGvwPomsI%3D&sp=r&sr=b&sv=2016-05-31&regid=42012bb2682a4d76ba7fa17a9d9a9162: x509: certificate signed by unknown authority.
    See 'docker run --help'.
? latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9 but 1.0.9.1 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
× host time is close to real time - Error
    Could not query NTP server
× container time is close to host time - Error
    Could not query local time inside container
v DNS server - OK
v production readiness: certificates - OK
v production readiness: container engine - OK
v production readiness: logs policy - OK
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect to buhler-dev-telemetry.azure-devices.net:5671
× host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - Error
    Could not connect to buhler-dev-telemetry.azure-devices.net:443
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect to buhler-dev-telemetry.azure-devices.net:8883
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the nat network could not connect to buhler-dev-telemetry.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the nat network could not connect to buhler-dev-telemetry.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the nat network could not connect to buhler-dev-telemetry.azure-devices.net:8883

9 check(s) succeeded.
1 check(s) raised warnings. Re-run with --verbose for more details.
11 check(s) raised errors. Re-run with --verbose for more details.

**Comment by dmolokanov** [comment]
Let me clarify your architecture. You have a proxy between Cloud and IoT Edge device, correct? This proxy terminates all TLS traffic between Cloud and Edge device. What kind of certificates do you use in your setup: a self-signed certificate or production certificate? What is authentication schema you have for your Edge device (it can be configured in the portal)?

**Comment by sachidanand** [comment]
We are having below details 
1. Architecture is Edge Gateway connects to Cloud via proxy 
2. On Proxy Server we have SSL Interception which does the interception on each request. 
3. This Interception use the production certificate and then only it pass the request to cloud .

Answers of queries:
1. We are using production certificate
2. We are using Device Connection string for authentication .. This connection string is set in the config.yml file 
3. I am not sure about the proxy software because our customer uses different softwares so can't list it here ..

**Comment by dmolokanov** [comment]
There are some unknowns in your case, but what you can try and it may work. 
1. make sure your edge device configured to authenticate using SAS tokens (it will not work with certificate-based auth). Usually, it means that there is a connection string is specified in the `config.yaml` file.
2. verify edge device can connection **without** Proxy.
3. install your root CA you use in the Proxy as a trusted certificate on the host machine you run Edge runtime.

Hopefully, the Edge platform will trust this root CA and will be able to work in the `Proxy <--> Edge` chain.

Some useful information about configuring Edge as a transparent gateway can be found here https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway

**Comment by sachidanand** [comment]
Hi @dmolokanov ,
     1. We are using connection string based authentication and not using certificate
2. Edge device is able to connect without proxy network but this network is not recommended as it is open network so we need to go via proxy network only. 
3. I have install root CA in trusted certificate but Edge runtime is not able to pick it from there and that is the error which i have sent initially .. 

So now could you check these scenario and then let me know if there are any specific location is for certificate installation.. So that Edge Runtime can pick it

**Comment by sachidanand** [comment]
Hi Team,
   Is there any update on this ..   Could you tell me whether Edge Runtime supports Proxy with SSL Interception certificate based or not ??

**Comment by damonbarry** [comment]
@sachidanand We don't test this particular proxy scenario, and we don't have built-in support for it. One of the main reasons we don't support it is that docker doesn't support it.

That said, you should be able to make it work via some sort of adapter. For example, it should be possible to install an intermediate proxy that can present the cert to the SSL intercept proxy. Then configure docker, iotedged, and any modules that need to reach the internet (e.g., Edge Agent and Edge Hub) to use the intermediate proxy.

**Comment by ebertrams** [comment]
@sachidanand Did you get a chance to try out damonbarry s suggestion? Can we close this ticket? Thanks!

**Comment by sachidanand** [comment]
The solution doesn't seem to work for us as we can not deploy one additional proxy in between just for cert verification ..  
Doesn't IoT Edge Runtime support these certificates when it connects to Internet via proxy ???

**Comment by damonbarry** [comment]
IoT Edge does not officially support this scenario (meaning we don't test it in-house, and we haven't tried it).

I spent time today trying to set up this scenario, but I couldn't quite make it work. I configured a squid proxy server for SSL intercept (using [this blog article](https://scubarda.com/2020/03/23/configure-squid-proxy-for-ssl-tls-inspection-https-interception/)).

It was easy to get `dockerd` and `iotedged` to use this proxy; I installed the certificate system-wide and they just _worked_.

I was also able to get a .NET Core app to make HTTP requests through the proxy. It worked on the host, and it worked in a container if I passed the `https_proxy` env var and volume-mounted `/etc/ssl/certs/` from the host (this was on Ubuntu).

But I couldn't get Edge Agent to use the proxy. I passed it the `https_proxy` env var, set `UpstreamProtocol` to `AmqpWs`, and mounted `/etc/ssl/certs/`, but it wouldn't connect. The squid logs showed this:

```
2020-06-05 23:57:54 109 172.17.0.1 NONE/200 0 CONNECT {my-hub}.azure-devices.net:443 - HIER_DIRECT/104.40.49.44 - "-" "SQUID-CS" 91 -
2020-06-05 23:57:54  34 172.17.0.1 TCP_MISS/400 285 GET https://{my-hub}.azure-devices.net/$iothub/websocket - HIER_DIRECT/104.40.49.44 - "-" "SQUID-CS" 218 -
```

I don't know if there's a problem in the SDK, or if I'm overlooking some dumb mistake. Since I made it work for a simple .NET app in a container I don't see why it won't work for Edge Agent, but I haven't been able to get it working so far. Note also that getting the certificate into the Edge Agent container _on Windows_ might be an additional challenge; you probably can't just map in some cert files like you can in Linux.

**Comment by sachidanand** [comment]
So what would be the next steps?? Could you check it with Windows once and then let me know if you find some option to make it work on Windows.. Because we are using windows image only in our all prodcution gateways. 
As of now we are stuck with it and not moving ahead so do let me know if you find something around it ..

**Comment by damonbarry** [comment]
Seems to be an issue with the C# SDK; see my comments in the referenced issue for more details.

Again, this is not a supported scenario, but hopefully an SDK fix in the future will unblock you. In the meantime, as suggested earlier, you could deploy an intermediate proxy as an edge module, and instruct agent and hub to communicate with IoT Hub through the intermediate.

**Comment by damonbarry** [comment]
BTW, you can upvote the feature suggestion for cert-based proxy auth [here](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/36740230-certificate-based-proxy-authentication).
