### ISSUE TITLE
Device Twin payload - two different json formats

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/iotedge#2974]
## Expected Behavior
Why are the device twin formats different between a PARTIAL and COMPLETE update?

## Current Behavior
There are two formats of the device twin payload.  On initial module provisioning (COMPLETE), the payload looks like this (for a sample project):

{ "desired":{ "TemperatureThreshold":25,

But, when you update the Digital Twin (either in the portal, or in VS Code), and a digital twin callback in the edge is executed (PARTIAL), the payload format looks like this:

 {"TemperatureThreshold":25,

This is what the digital twin look like:

```
    "properties": {
        "desired": {
            "TemperatureThreshold": 25,
            "$metadata": {
                "$lastUpdated": "2020-05-18T20:15:37.1460236Z",
                "$lastUpdatedVersion": 21,
                "TemperatureThreshold": {
                    "$lastUpdated": "2020-05-18T20:15:37.1460236Z",
                    "$lastUpdatedVersion": 21
                },
            },
            "$version": 21
        },
        "reported": {
            "$metadata": {
                "$lastUpdated": "2020-05-13T16:06:56.396155Z",
                "$lastUpdatedVersion": 1
            },
            "$version": 1
        }
    },
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a sample Edge Module and provision it to an Edge Device
2. In VSCode, right click the Edge Module on the Edge Device, then 'Edit Digital Twin'
3. Edit some part of the digital twin, and then 'update'.
4. Watch digital twin payload gets sent to the module.

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Raspian
* Architecture [e.g. amd64, arm32, arm64]: arm32v7
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0
* Docker/Moby [run `docker version`]: 3.0.00+azure

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by dmolokanov** [comment]
Hello @RotateAt60MPH. There are several operations can be done on the device twin: retrieve twin, partial update, observe desired properties.
Please refer documentation via https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-operations

**Comment by dmolokanov** [comment]
Do you have any additional questions on the subject?

**Comment by RotateAt60MPH** [comment]
Well, that helps.  Does mean more complex logic in the module to handle 2 variations of the same twin information, though.  I'll take this as 'works as designed'.
