### ISSUE TITLE
Development certificate expiry - bug or question

### ISSUE THREAD

**Issue by pietersap** [Azure/iotedge#2979]
## Expected Behavior

We are running iot edge "live" in a test environment using the self-signed developer certificates that the runtime provides us. The [documentation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates) states that these certificates expire in 90 days and they can be reset by restarting the device.

Expected behaviour: if the device is restarted, the developer certificates are reset. As a result, a device that is not up for at least 90 days can never have expired certificates.

## Current Behavior

![image](https://user-images.githubusercontent.com/32063689/82426099-b4a20180-9a87-11ea-9f06-b3f4d03ce11b.png)

When running iotedge check today on one of our devices, we received an error that the certificates were expired. In total, the device has definitely been running for more than 90 days. However, the device had been restarted (for a reason unknown to us, perhaps someone in the test location pulled the plug or whatever) one day ago (reflected in the ```uptime``` command, also in the screenshot). 

Afterwards, the runtime was restarted by us (not the device itself) with ```systemctl restart iotedge```. This solved the expiry of the certificates.

Of course we will not use the developer certificates when proceeding to a production environment. But having an exact understanding of how these things work might help us a lot while troubleshooting and will give us more control of the situation. 

Looking for answers to following questions:
- how is it possible that the certificates where expired, even though the device uptime is only one day?
- according to the documentation, a "restart" should reset the certificates. In the expected behaviour, is it sufficient to restart the runtime with ```systemctl restart iotedge```, or does it have to be a real reboot of the whole device?

Thanks

### Device Information
* Host OS: Raspbian Stretch
* Architecture: arm32
* Container OS: Linux containers

### Runtime Versions
**iotedge version**
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

**runtime module versions**
edgeAgent and edgeHub: 1.0.9

**docker version**
Client:
 Version:           3.0.7
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        578ab52e
 Built:             Wed Oct  2 21:39:40 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       ed20165
  Built:            Wed Oct  2 23:22:11 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by dmolokanov** [comment]
Hello @pietersap! I tried to reproduce the behavior you described and confirmed that `iotedged` regenerates certificates during the startup process when it detects existing certificate expiry. With my short-lived certificate, it was regenerated via both `systemctl restart iotedge` and system reboot.

The most logical explanation I can come up with is that certificate expired **after**  was rebooted.
Uptime is `1 day 4:37` and the current time is `2020-05-20 07:38:18`. So reboot happened approximately at `2020-05-19 03:01:18`
The certificate expired at `2020-05-19 15:22:44` which is **after** `2020-05-19 03:01:18`

**Comment by dmolokanov** [comment]
I'm closing this issue for now. But feel free to reopen this issue if you have any additional questions or concerns.

**Comment by pietersap** [comment]
@dmolokanov thank you for the clarification. What caused the confusion is that we believed the certificates where *always* regenerated at any restart, not only if the current ones are expired. As a result we thought it impossible to have an expired certificate on a device that had restarted just a day ago.
