### ISSUE TITLE
Debian stretch iotedge package is not in repos

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#2983]
## Expected Behavior
`sudo apt install iotedge` should install the DEB package for Debian Stretch

## Current Behavior
When running `sudo apt install iotedge` an error is returned: Package 'iotedge' has no installation candidate

## Steps to Reproduce
When running Debian stretch, I should be able to install `iotedge` package from Microsoft repos. Following instructions from [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux), 
```bash
sudo apt update
sudo apt install gpg apt-transport-https
curl https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list > ./microsoft-prod.list
sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
sudo apt update
sudo apt install iotedge
```

### Output of `iotedge check`
Can't get there far because `iotedge` is not installable

### Device Information
* Host OS - Debian Stretch 
* Architecture - amd64 

## Additional Information
As a reference, I checked Ubuntu 18.04 Microsoft repo to see that https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/dists/bionic/main/binary-amd64/Packages lists `iotedge` as a package. The comparable Debian Stretch repo https://packages.microsoft.com/debian/stretch/multiarch/prod/dists/stretch/main/binary-amd64/Packages does not list `iotedge` as a package.

**Comment by gri6507** [comment]
Perhaps related to this problem is that fact that https://packages.microsoft.com/debian/stretch/multiarch/prod/pool/main/i/iotedge/ only shows ARM packages, but not AMD64

**Comment by dmolokanov** [comment]
Hello @gri6507! Thanks for the question. 
As a matter of fact, we don't ship amd64 packages for Debian stretch only for arm32. By the link, you can find OS we support and what Tier 1 means for us. https://docs.microsoft.com/en-us/azure/iot-edge/support#operating-systems

I'm closing the issue now, but you are more than welcome to re-open if you have any additional questions.
