### ISSUE TITLE
[edgeHub] Support for incoming cloud to module messages in edgeHub

### ISSUE THREAD

**Issue by emilm** [Azure/iotedge#2984]
Ref issue https://github.com/Azure/azure-iot-sdk-csharp/issues/1370
@timtay-microsoft responded that edgeHub does not support this.

My usecase is that someone interacts with my device / module, and it needs to request the server to respond to the query from the user interacting with the device. The ideal thing would be a Direct Method to cloud from device/module, but that's not there. So in order to respond, the server has to 
a) respond with C2D (cloud to _module_ really) so my edge module can act accordingly
b) respond with Direct Method to module (not optimal, but works)
c) remove GATEWAY_HOSTNAME or something to bypass edgeHub and connect directly (what's the right way to do this?)

I think this important that you have a coherent solution for 2 way messaging, so you don't have to respond with a Direct Method to the Module which will create an unnecessary response. A request-response with DM would be device -> cloud - request->response->"request" 

Thanks! :)

**Comment by dmolokanov** [comment]
@veyalla Could you comment on this, please?

**Comment by veyalla** [comment]
@emilm are you asking for [this](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/34271500-c2d-messaging) feature?

**Comment by emilm** [comment]
> @emilm are you asking for [this](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/34271500-c2d-messaging) feature?

Correct! Most of it seems to be in place. The only missing piece seems to be edgeHub. It already works for Direct Methods to a module.

I see that the FR has been there since 2018 and I assumed it was dead. :)

**Comment by veyalla** [comment]
An update was provided in Nov 2019 (see the comments). Still the same status, unfortunately. It is not in our near-term roadmap.

Let's continue to use the feedback site to track.

**Comment by emilm** [comment]
OK. What do you recommend me to do in this case?

a) Use direct methods as a response mechanism (works today)
b) set up the module to connect directly to IoT hub and not via edgeHub (how is this done?)
c) ???

Thanks.

**Comment by veyalla** [comment]
a) is the recommended pattern with IoT Edge today.
