### ISSUE TITLE
IoT Edge Deployments - not working with boolean Target Condition

### ISSUE THREAD

**Issue by sergaz-msft** [Azure/iotedge#299]
## Expected Behavior

IoT Edge Deployments should be applied to all devices matching Target Conditions with boolean tags. According to [this](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#tags-and-properties-format): "All values in JSON objects can be of the following JSON types: boolean, number, string, object."

## Current Behavior

Example:
If my edge device twin has the following json tags:

```json
...
"tags": {
    "inPortugal": true
  }
...
```

Even though the Portal tells me that the Target Condition will be applied to my device
![image](https://user-images.githubusercontent.com/22173500/45637916-8e061900-baa3-11e8-9aa0-ed0f4f81052a.png)

In the end the Deployment is never applied to the edge device. It works well if I use string:

```json
...
"tags": {
    "inPortugal": "yesitis"
  }
...
```
![image](https://user-images.githubusercontent.com/22173500/45638037-dde4e000-baa3-11e8-874b-a46dfca3ec84.png)

Related issue: https://github.com/MicrosoftDocs/azure-docs/issues/14815

**Comment by myagley** [comment]
Thanks for the issue report! I followed up with the IoT Hub service team to help investigate this. I'll post again here when I know more.

**Comment by dsajanice** [comment]
The IoT Hub service team has confirmed its a bug.

**Comment by myagley** [comment]
This has been fixed in the IoT Hub service. It is scheduled to be deployed at the beginning of October.

**Comment by myagley** [comment]
This fix has been deployed to IoT Hub. Closing this issue.
