### ISSUE TITLE
IoT Device configuration won't update Azure system modules

### ISSUE THREAD

**Issue by nishad1092** [Azure/iotedge#2994]
Hi there, 

I would like to update my edgeAgent and edgeHub with new update image and create option settings, so that when the device comes online it gets automatically assigned to a layered deployment,
Im using the Add Module config\add device config under IoT Device config to do it but it isnt updating and gives "417 -- The device's deployment configuration is not set"

Im providing, all property seperated:

 "properties.desired.systemModules.edgeAgent.settings.image": "mcr.microsoft.com/azureiotedge-agent:1.0.8-rc1",

    "properties.desired.systemModules.edgeHub.settings.image": "mcr.microsoft.com/azureiotedge-hub:1.0.8-rc1",

    "properties.desired.systemModules.edgeHub.settings.createOptions": "{\"HostConfig\":{\"Binds\":[\"/home/xxx/:/home/\"],\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}",

    "properties.desired.systemModules.edgeAgent.settings.createOptions": "{\"HostConfig\":{\"Binds\":[\"/home/xxx/:/home/\"]}}"
}

Please let me know how to update systemModules, then only layered deployment gets working.

**Comment by vipeller** [comment]
Hi @nishad1092,

could you attach the logs from edgeAgent after you tried to update the deployment?
also can you try to restart the iot edge runtime by

sudo systemctl restart iotedge

to see what happens?

**Comment by vipeller** [comment]
Hi @nishad1092,

any update on this? If you attach the logs, that may reveal something about what goes wrong

**Comment by nishad1092** [comment]
Hi @vipeller , Sorry for the delayed reponse, This is  what My module configuration looks like:
{
    "properties.desired.systemModules.edgeAgent.settings": {
        "image": "mcr.microsoft.com/azureiotedge-agent:1.0.8-rc1"
    },
    "properties.desired.systemModules.edgeHub.settings": {
        "image": "mcr.microsoft.com/azureiotedge-hub:1.0.8-rc1"
    }
}

![image](https://user-images.githubusercontent.com/26060457/83051018-068bee00-a06b-11ea-8463-4e8c3db5b729.png)


And, the edgeAgent logs:
```
:~$ sudo iotedge logs -f edgeAgent
2020-05-27 17:04:22 +00:00 Starting Edge Agent
2020-05-27 17:04:22.862 +00:00 Edge Agent Main()
<6> 2020-05-27 17:04:23.991 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-05-27 17:04:24.841 +00:00 [INF] - Version - 1.0.8-rc1.22563438 (95c6254573c85635f3cf42fb90fa6ef7a92bb7da)
<6> 2020-05-27 17:04:24.843 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-05-27 17:04:26.788 +00:00 [INF] - Started operation refresh twin config
<6> 2020-05-27 17:04:26.933 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2020-05-27 17:04:28.947 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2020-05-27 17:04:33.507 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2020-05-27 17:04:34.327 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2020-05-27 17:04:34.858 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 1 and reported proper                                   ties version 1.
<6> 2020-05-27 17:04:34.869 +00:00 [INF] - Deployment config in edge agent's desired properties is empty.
<3> 2020-05-27 17:04:34.883 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent                                   . Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in /home                                   /vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 225
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.RefreshTwinAsync() in /home/vsts/work/1/s/edge-agent/src/Microsof                                   t.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 184
<6> 2020-05-27 17:04:35.950 +00:00 [INF] - Updated reported properties


```

**Comment by nishad1092** [comment]
As u can see @vipeller  there is no change in the edgeAgent status, It doesn't load the cnfiguration

**Comment by vipeller** [comment]
@nishad1092 : there was any base deployment before you applied the layered update? According to the error message, the agent twin is empty. Can you check the current twin of edgeAgen on azure portal?

![image](https://user-images.githubusercontent.com/51135538/83068974-03b6dc00-a01e-11ea-9a51-78dfbc345200.png)

in my case the edge device was 'maki', select the edge device, then $edgeAgent module, then 'module identity twin'

What I'd like to know if there is a correct twin there (and then if there is, we need to figure out why the agent gets an empty twin when it requests it)

**Comment by nishad1092** [comment]
@vipeller  

Its a new device, and there isnt any deployment done before. The idea is, I need all new devices to have 1.0.8-rc1 version of edgeAgent and EdgeBase (because Now its 1.0 by default) and it needs to happen during the creation of device,

this is the module twin of edgeagent

![image](https://user-images.githubusercontent.com/26060457/83113841-cddd2a80-a0e5-11ea-9a34-04ab8ee986e9.png)

**Comment by vipeller** [comment]
@nishad1092 sorry, but I need you to push the "Module Identity Twin" button (where the red arrow points), and then it will bring up a json text which is the twin. I'd like to see that because the error message from your log says that the twin is empty, and I need to know if that really is.

**Comment by nishad1092** [comment]
Hi @vipeller , this is inside module twin:
![image](https://user-images.githubusercontent.com/26060457/83171606-fe4bb580-a133-11ea-9c15-446ffefe8537.png)

**Comment by vipeller** [comment]
@nishad1092 thank you, now we can see that the agent twin is empty (the properties/desired part doesn't give any description for edge agent about what to deploy).

If I understand, you want layered deployment. Even for layered deployment it needs a base-line, so then the changes get applied to the base-line:

https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring#layered-deployment

**Comment by nishad1092** [comment]
hi @vipeller , Yes I want layered deployment, So there is no way to get a default version of system modules before the base deployment?

**Comment by nishad1092** [comment]
hi @vipeller , I did a base deployment with edgeAgent versiion 1.0.8-rc1, and then I created a device configuration with 1.0.9 but It isnt reflecting. 

{
    "properties.desired.systemModules.edgeAgent.settings": {
        "image": "mcr.microsoft.com/azureiotedge-agent:1.0.9"
    },
    "properties.desired.systemModules.edgeHub.settings": {
        "image": "mcr.microsoft.com/azureiotedge-hub:1.0.9"
    }
}.

What is the issue here?

**Comment by nishad1092** [comment]
hi @vipeller , I have an update, so after creating the update, it is reflecting in the 'Device twin', ie in the IoT edge device main page (edge device --> Device twin) but it isnt getting reflected anywhere else(most it has to be reflected  inside $edgeAgent --> Image URI) so this isn't giving me any change in the device also.

**Comment by vipeller** [comment]
@nishad1092 Let me repeat to be sure that I understand:
- you created a base deployment, so as a result edgeAgent twin contained 1.0.8-rc1 modules to deploy, also the device had those images
- added the layers to update to 1.0.9. As a result, a new JSON segments showed up in the device twin (I assume it got a { systemModules { edgeAgent { settings { image: xxx }}} section)

and the question is that why it went to the device twin when it was supposed to go $edgeAgent twin? Could you confirm that this is the case?

**Comment by nishad1092** [comment]
@vipeller Yes, It went to the device twin as a new JSON segment, but not in the $edgeAgent. I guess because of this, it isn't reflecting anywhere in the desired or reported properties.

**Comment by veyalla** [comment]
Closed due to inactivity. Please let us know if you still need help with this.
