### ISSUE TITLE
Module Method Callback response memory - who frees it?

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/iotedge#2995]
## Expected Behavior
Question: memory allocated in a module method callback to hold response JSON is free'd by iotedge?

## Current Behavior
unknown

## Steps to Reproduce
Provide a detailed set of steps to reproduce the question.
1. Create a module method callback function:
```
int _moduleMethodCallback(const char *method_name,
                                         const unsigned char *payload,
                                         size_t size,
                                         unsigned char **response,
                                         size_t *response_size,
                                         void *userContextCallback)
{
    LOG_DEBUG << "Module method callback called ( method='"
              << method_name << "' ):";

    char * pchPayload = ( char * )calloc( sizeof(char), size + 1 );
    memcpy( pchPayload, payload, size );
    std::string strPayload = pchPayload;
    free(pchPayload);

    LOG_DEBUG << "Payload: " << strPayload;

    std::string test = "{ \"status\": 0 }";    
    *response = ( unsigned char * )calloc( sizeof(char), test.length() + 1 );  // leak??
    memcpy( *response, test.c_str(), test.length() );

    *response_size = test.length();

    return 200;  // ??
}
```
2. Register the callback:
```
if (IoTHubModuleClient_LL_SetModuleMethodCallback(
                 _hIoTHubModuleClient,
                 _moduleMethodCallback,
                 (void *)this) != IOTHUB_CLIENT_OK)
    {
        printf("IoTHubModuleClient_LL_SetModuleMethodCallback().FAILED!\r\n");
        ret = MU_FAILURE;
    }
```
3. Invoke the direct method in the portal:
Method Name: test
Payload:  {"hello":"Again"}
4. See the module method callback execute (via module log messages)
5. Examine response: it's
{"status":200,"payload":{ "status": 0 } }

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Raspian
* Architecture [e.g. amd64, arm32, arm64]: armv7l
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0
* Docker/Moby [run `docker version`]: 19.03.8

## Additional Information
There does not appear to be any documentation on how the method callback should be structured (at least for C/C++).  Some suggestions/advice would be appreciated.

**Comment by vipeller** [comment]
@cartertinney could you take a look

**Comment by ewertons** [comment]
Hi @RotateAt60MPH ,
thanks for bringing this up. An issue has been filed against the Azure IoT C SDK repo for improving documentation.

To you specific question, the SDKs are screened for memory leaks and whatever memory is passed to it on callbacks should be freed by the SDK, unless specified. But indeed, there is a lack of documentation on that. The response is freed by the SDK here: 
https://github.com/Azure/azure-iot-sdk-c/blob/2020-01-22/iothub_client/src/iothub_client_core_ll.c#L749

**Comment by RotateAt60MPH** [comment]
Perfect.  Thanks for the info!  So, to summarize: the memory allocated in the module method callback to hold the json response will be freed by the SDK.
