### ISSUE TITLE
edgeAgent and edgeHub containers segfault with SeLinux

### ISSUE THREAD

**Issue by roicostas** [Azure/iotedge#30]
This is known issue with dotnet 2.1.0, see https://github.com/dotnet/dotnet-docker/issues/496.

Just updating to dotnet 2.1.1 works. I have tried this and it seems to work.

**Comment by darobs** [comment]
Thank you, @roicostas, I will put this on our backlog.

**Comment by myagley** [comment]
This should be resolved with #89 which will make it into the next release.
