### ISSUE TITLE
Update meta-iotedge sumo to 1.0.9

### ISSUE THREAD

**Issue by corollaries** [Azure/iotedge#3036]
Hi!

We're using a custom Yocto (sumo) image for running the IoT Edge platform. The latest version that's published on `meta-iotedge` is `1.0.8`. However, we're very eager to use `1.0.9`. Is there any timeframe (or plan even) to update the `meta-iotedge` branches to include `1.0.9`? It's been several weeks since `1.0.9` was released but we haven't seen any update to the Yocto branch. 

Currently the `edgeAgent` and `edgeHub` modules with version `1.0.9` are being deployed to our devices. These modules are thus newer than the `iotedge-daemon`. Is this version 'mismatch' something that could cause problems down the line for us? 

We prefer to use the latest versions of the modules because of some bugfixes. It'd be great if we could update `iotedge-daemon` to the same versions as well.

**Comment by philipktlin** [comment]
We are definitely going to support iotedge 1.0.9 on Yocto. Will come back to you soon for the schedule.

**Comment by veyalla** [comment]
Please add this functionality as a new suggestion (or upvote an existing one) at https://aka.ms/iotedge-suggestion
