### ISSUE TITLE
manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.9.2 not found

### ISSUE THREAD

**Issue by oliverchristen** [Azure/iotedge#3037]
## Expected Behavior
After iotedge runtime update to 1.0.9.2 on a Ubuntu 18.04 box the command `sudo iotedge check` should not display any errors.

## Current Behavior
`sudo iotedge check` displays the following error:
`	× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.9.2' locally
    docker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.9.2 not found: manifest unknown: manifest tagged by "1.0.9.2" is not found.
    See 'docker run --help'.
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.0.9.2' locally
                   docker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.0.9.2 not found: manifest unknown: manifest tagged by "1.0.9.2" is not found.
                   See 'docker run --help'.`

## Steps to Reproduce
1. sudo apt-get update
2. sudo apt-get install libiothsm iotedge
3. iotedge --version => 1.9.0.2
4. sudo iotedge check

### Output of `iotedge check`
See above

### Device Information
* Host OS: Ubuntu 18.04 
* Architecture: amd64
* Container OS: Linux containers 

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9.2
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.9.1.31031043
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.9.1.31031043
* Docker/Moby [run `docker version`]: 1.0.9.2

## Additional Information
The edge device works as expected but the error is displayed anyway. I do not understand why the runtime wants to install a container named `azureiotedge-diagnostics:1.0.9.2`

**Comment by jsucco-growlink** [comment]
Having the same problem on Raspbian Stretch for same iotedge version.

**Comment by damonbarry** [comment]
@oliverchristen @jsucco-growlink I found a glitch in our release process that prevented the manifest images from being published yesterday. I just corrected and re-ran the release job. The images are there now; can you try again?

**Comment by oliverchristen** [comment]
@damonbarry Thank you very much for your immediate response. `sudo iotedge check` now doesn't complain about the `azureiotedge-diagnostics` container manifest any more. You can close the issue from my side. But I don't understand what exactly the check does. Why does it use that container image? It's not configured anywhere, is it?

**Comment by damonbarry** [comment]
@oliverchristen It launches that container to simulate the networking conditions of an IoT Edge module running as a Docker container, and to check things like:
- Can a module reach `iotedged`'s management endpoint? (Edge Agent needs to be able to do this)
- Can a module reach IoT Hub in the cloud? (Edge Agent and Edge Hub both need to be able to do this)
- What's the local time in the container? (We need to make sure time inside the container hasn't drifted too far from the host)

Closing this issue. Thanks!

**Comment by noquarter12** [comment]
Hello I am seeing this issue on IoT Edge Runtime 1.1.6. Exact same problem as described except it is looking for:

```
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.1.6' locally
    docker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.1.6 not found: manifest unknown: manifest tagged by "1.1.6" is not found.
    See 'docker run --help'.
```

**Comment by damonbarry** [comment]
Yes, we're aware of this. (See #5473). We're working on publishing `mcr.microsoft.com/azureiotedge-diagnostics:1.1.6`. In the meantime, you can use the `--diagnostics-image-name mcr.microsoft.com/azureiotedge-diagnostics:1.1.5` option when you call `iotedge check`.

**Comment by noquarter12** [comment]
@damonbarry Thank you! As an aside do you guys have a chat room, discord channel or any other means to discuss this project outside of GitHub? I am very interested in it. 

Thank you.

**Comment by damonbarry** [comment]
@noquarter12 We published `mcr.microsoft.com/azureiotedge-diagnostics:1.1.6` this morning, so the problem should be resolved.

> do you guys have a chat room, discord channel or any other means to discuss this project outside of GitHub?

No, sorry.  :(
