### ISSUE TITLE
[Question] How to get host and docker level metrics

### ISSUE THREAD

**Issue by xiaoyang-connyun** [Azure/iotedge#3045]
In the release log of the version 1.0.9, I see two promising features:
* add prometheus metrics to Agent (1268500)
* add host and docker level metrics (d5531d4).

This is the feature I am waiting for a while, and I would like to start to investigate into how to use these features. Unfortunately, maybe I missed that, but I do not find documentations regarding this topic. So, if there is something, could you please provide me the reference? If the documentation is not ready, could you please provide me some hints how I can make use of these features?

**Comment by philipktlin** [comment]
You can find IoT Edge built-in metrics from https://github.com/Azure/iotedge/blob/master/doc/BuiltInMetrics.md.  Thanks for waiting for this feature.
