### ISSUE TITLE
Best approach to sync edge modules and edge runtime logs to Cloud 

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#3060]
Hi Team,
    Could you suggest best way to sync to the system edge modules, custom edge modules and edge runtime logs from gateway to cloud. We need to for further investigation in future. Currently these logs are on gateway and there are chances to loss these logs on gateway because of storage capacity or restarting of the edgeruntime. 
1. If you can suggest best approach to sync these logs.
2. If you have similar implementation already then please share.

**Comment by veyalla** [comment]
For on-demand pull of logs, you can use the built-in log pull: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-edgeagent-direct-method#experimental-methods

If you want to enable continuous logging, some customers have had success with enabling container monitoring solution on the host: https://github.com/danielscholl/iac-winedge-quickstart#enable-container-solution-monitoring-optional

**Comment by sachidanand** [comment]
We want to sync logs either with log analytic or app insight .. so is there the option to achieve this...

**Comment by veyalla** [comment]
The container monitoring solution I previously mentioned will sync container logs to Log Analytics.

**Comment by sachidanand** [comment]
Is there any approach to use Application Insight on Edge Gateway and then sync it on timer basis to Cloud ??
