### ISSUE TITLE
Module can not connect to edgeHub via MQTT using X.509 certificate

### ISSUE THREAD

**Issue by marcschroeder** [Azure/iotedge#3062]
## Expected Behavior
A module should connect to the edgeHub using MQTT using X.509 certificates.

## Current Behavior
The edgeHub received the connection but throws the following error:

Error authenticating MODULE_NAME using X.509 certificates since this is identity type is unsupported.

## Context (Environment)
Our module uses mosquitto to connect to the edgeHub using a client certificate.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
√ production readiness: identity certificates expiry - OK
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

21 check(s) succeeded.
4 check(s) raised warnings.


```
</details>

### Device Information
* Host OS: Ubuntu 16.04
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* iotedged: 1.0.9.2
* Edge Agent: 1.0
* Edge Hub: 1.0
* Docker/Moby: 3.0.12+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

<details>
<summary>edge-hub logs</summary>

```

<4> 2020-06-09 13:26:06.288 +00:00 [WRN] - Error authenticating DEVICE_ID/MODULE_NAME using X.509 certificates since this is identity type is unsupported.
<6> 2020-06-09 13:26:06.289 +00:00 [INF] - Client DEVICE_ID/MODULE_NAME in device scope not authenticated locally.
<3> 2020-06-09 13:26:06.289 +00:00 [ERR] - Unable to generate identity for clientId DEVICE_ID/MODULE_NAME and username IOT_HUB.azure-devices.net/DEVICE_ID/MODULE_NAME/?api-version=2019-11-05
<6> 2020-06-09 13:26:06.289 +00:00 [INF] - ClientNotAuthenticated, Client ID: DEVICE_ID/MODULE_NAME; Username: IOT_HUB.azure-devices.net/DEVICE_ID/MODULE_NAME/?api-version=2019-11-05, 2a05c71c


```
</details>

**Comment by varunpuranik** [comment]
@marcschroeder - Thanks for the issue. 
IoT Edge doesn't support module identities with X.509 cert auth yet. So EdgeHub does not support modules to connect with X.509 certs. 

Can you please describe your scenario a bit?
How are you deploying and starting the module? Are you doing it manually?

**Comment by marcschroeder** [comment]
Thanks for the clarification.

In our scenario we want to connect an existing component that can publish information on an MQTT broker to the edgeHub to push those information to the IoT Hub.

What would you suggest to use to connect a module via MQTT to the edgeHub? Should we use a SAS-Token for authentication? If so: How would we conveniently receive it?

**Comment by varunpuranik** [comment]
Yes, if your module is deployed to an IoT Edge device via a deployment, then the module identity will be created with a SAS key authentication in IoTHub. 

If your code is using an IoTHub SDK, then you can use the ModuleClient.CreateFromEnvironment() method to create a client using SAS token. 
Here is an example of how our sample module does it - 
https://github.com/Azure/iotedge/blob/master/edge-modules/SimulatedTemperatureSensor/src/Program.cs#L293

**Comment by marcschroeder** [comment]
Is there a good way around the SDK? I could of course just build a small python wrapper but it would be more stable to just run the component itself.

**Comment by lfitchett** [comment]
I would recommend using the sdk if possible, but If you need to generate the key yourself the sdk is open source and you can take the relevant bits. Of interest are probably

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-hub/azure/iot/hub/sastoken.py
https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/azure/iot/device/iothub/edge_hsm.py#L84

**Comment by marcschroeder** [comment]
Thanks for your help. I have created a small wrapper that allows me to listen for output from our component and send them via the Python API to the IoT Edge Hub. This should be fine for now.
