### ISSUE TITLE
Direct method call of an Iot Edge module : device not online or time out when trying to call the device

### ISSUE THREAD

**Issue by mjeannin2** [Azure/iotedge#3064]
Hello team,

We encounter e problem during direct method calls : 

Context : 
Call of direct method on iotEdge

Observed behavior : 
The call to our direct method failed (device not online or time out when trying to call the device) but ,the Edge is still functional and data retrievable. However, its "connectionState" is set to "Disconnected" in its Device Twin, although its modules have their "connectionState" set to "Connected".

Expected behavior 
The call worked without any problem on others devices (the ones where a "connectionState" to "Connected").

The same edge image is use on all our devices

Can the problem can be related to the protocol use by the module to connect to the edgeHub ? (azure-iot-device-amqp vs azure-iot-device-mqtt ?)

Sample responses : 
{"errorCode":404103,"trackingId":"90c7e35c66784298a6d7f80c1825c152-G:22-TimeStamp:06/09/2020 10:21:58-G:0-TimeStamp:06/09/2020 10:21:58","message":"Device not online.","info":{},"timestampUtc":"2020-06-09T10:21:58.4328362Z"}
·         {"Message":"{\"errorCode\":504101,\"trackingId\":\"ddcc3054fb234b55a15a3bdbd4250713-G:10-TimeStamp:06/09/2020 10:38:03-G:41-TimeStamp:06/09/2020 10:38:03\",\"message\":\"Timed out waiting for the response from device.\",\"info\":{},\"timestampUtc\":\"2020-06-09T10:38:03.476295Z\"}","ExceptionMessage":""}

**Comment by lfitchett** [comment]
Which version of IoT Edge are you using. We improved our connection stability greatly in 1.0.9. If you are using an older version, please try upgrading to 1.0.9.2 and let me know if the problem persists.

**Comment by lfitchett** [comment]
Please re-open this issue if upgrading does not fix your issue. Thanks
