### ISSUE TITLE
Updated deployment changes are not applied on edge Gateway

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#3068]
Hi Team,
    When we are updating modules on Edge Gateway then the new change in the modules or modules desired property is not being applied immediately on the gateway. After deployment we have to either restart the edgeAgent or edge runtime and then only new changes are being applied on the gateway. So could you please let me know the reason for this..   

We are using 
1. Windows OS 10 
2. Docker image is windows 
3. Edge Runtime 1.0.8 
4. edgeAgent and edgeHub 1.0.8

**Comment by varunpuranik** [comment]
@sachidanand -
Looks like EdgeAgent module is not receiving the deployment via its Desired properties. Can you provide us the EdgeAgent logs, so that we can confirm?

We made a number of connectivity related fixes to resolve issues like these in the 1.0.9 release. Can you try to upgrade the Edge runtime and EdgeAgent/EdgeHub modules to the version 1.0.9.2, and see if it resolves your issue?

**Comment by sachidanand** [comment]
Actually, I have seen the logs at that time on edgeAgent and edgeAgent didn't receive new deployment manifest and hence it didn't write any thing in the logs ... 

I will check it with iotedge runtime 1.0.9 and then will let you know if the same issue is there or not.. 

Currently we are setting desired property also in the deployment manifest only. We are not sending desired property separately ...  If we need to update the desired property then we are also sending complete deployment manifest..

**Comment by lfitchett** [comment]
Hi, are you still seeing the issue in 1.0.9.2?

**Comment by sachidanand** [comment]
It is working on 1.0.9.2 But the issue is with 1.0.8 and in our all the production gateway we have 1.0.8

**Comment by lfitchett** [comment]
I would strongly recommend upgrading to 1.0.9 if that fixes your issue. Since we don't currently have an LTS, we don't support older versions. 

Closing for now since upgrading fixes the problem, feel free to re-open this or a new issue if you have further questions.
