### ISSUE TITLE
IoT Edge dashboard long live deployment error message

### ISSUE THREAD

**Issue by navadiatarun** [Azure/iotedge#3082]
## Expected Behavior
The limit in the number of long live deployment is azure iot edge dashboard is 100.
When the number crosses 100, a relevant error message is not displayed.

## Current Behavior
The error message is not relevant now. The debugger says Bad request 400.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create 100 long live deployments via IoT Hub node.
2. Submit a new deployment.
3. The error message is not relevant.

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.
![InkedLLIoT100_LI](https://user-images.githubusercontent.com/66818899/84475054-863fcc80-aca9-11ea-94ba-7928fda08781.jpg)

**Comment by lfitchett** [comment]
Hi, this looks like a portal issue unrelated to the edge runtime. Please open a [Portal Issue](https://portal.azure.com/#create/Microsoft.Support).
