### ISSUE TITLE
Running containers outside of edge run time control

### ISSUE THREAD

**Issue by clustor** [Azure/iotedge#3083]
We are integrating Azure IoT on our edge platform and we have couple of questions.

1. Does Edge runtime expect all the containers to be managed by iotedged? We have a need to run our own containers for platform networking and security unrelated to Azure IoT. 
2. Does iotedged monitor/control only the containers started through IoT hub? 
3. Are there any scenarios where iotedged might need to know own all the containers down the line even if it is not needed now?

**Comment by lfitchett** [comment]
> 1. Does Edge runtime expect all the containers to be managed by iotedged? We have a need to run our own containers for platform networking and security unrelated to Azure IoT.

No. Any containers created and started using the command line or some other tool will be ignored by the Edge Daemon.

> 2. Does iotedged monitor/control only the containers started through IoT hub?

Yes. All other containers are ignored.

> 3. Are there any scenarios where iotedged might need to know own all the containers down the line even if it is not needed now?

No. This behavior is not planned to change.

Are you planning on using the same container engine for both? (recommended, its easier than trying to have 2 engines)

**Comment by clustor** [comment]
Thanks for the prompt response.
