### ISSUE TITLE
Start-Service : Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start service iotedge on computer '.'.

### ISSUE THREAD

**Issue by 76ltts** [Azure/iotedge#3091]
## Expected Behavior
should initialize IoT Edge Device on my system

## Current Behavior
 . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
>> Initialize-IoTEdge -ContainerOs Linux                                                                                
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Import-IntermediateCertCh...

cmdlet Initialize-IoTEdge at command pipeline position 1
Supply values for the following parameters:
DeviceConnectionString: HostName=IgnitionIoTHub.azure-devices.net;DeviceId=ignitionDevice;SharedAccessKey=PD1#####****4************UhQUfQgXeTxB9HikUOU=
Docker is running.
WARNING: Linux containers on Windows can be used for development and testing, but are not supported in production IoT
Edge deployments. See https://aka.ms/iotedge-platsup for more details.
The container host is on supported build version 18362.
System PATH does not require an update.
Generating config.yaml...
Configured device for manual provisioning.
Configured device with hostname 'BLTSP00250'.
Configured device with Moby Engine URL 'npipe://./pipe/docker_engine' and network 'azure-iot-edge'.
Start-Service : Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start
service iotedge on computer '.'.
At line:1464 char:9
+         Start-Service $EdgeServiceName
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

## Steps to Reproduce
[https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-linux](url)

### Enviornment
Context (Environment)
Windows 10 with Linux containers (Docker)

Device (Host) Operating System
Windows 10 Enterprise Version 1903 OS Build 18362.30

Container Operating System
Linux containers on Windows

### Output of `iotedge check`
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Error: could not execute list-modules request: an error occurred trying to connect: Connection refused (os error 111)
√ latest security daemon - OK
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
× production readiness: certificates - Error
    Could not enumerate files under C:\ProgramData\iotedge\hsm\certs
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect to IgnitionIoTHub.azure-devices.net:5671
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect to IgnitionIoTHub.azure-devices.net:8883
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the azure-iot-edge network could not connect to IgnitionIoTHub.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to IgnitionIoTHub.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the azure-iot-edge network could not connect to IgnitionIoTHub.azure-devices.net:8883

7 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
9 check(s) raised errors. Re-run with --verbose for more details.

## Additional Information
 . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
>> Initialize-IoTEdge -ContainerOs Linux                                                                                
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Import-IntermediateCertCh...

cmdlet Initialize-IoTEdge at command pipeline position 1
Supply values for the following parameters:
DeviceConnectionString: HostName=IgnitionIoTHub.azure-devices.net;DeviceId=ignitionDevice;SharedAccessKey=PD1#####****4************UhQUfQgXeTxB9HikUOU=
Docker is running.
WARNING: Linux containers on Windows can be used for development and testing, but are not supported in production IoT
Edge deployments. See https://aka.ms/iotedge-platsup for more details.
The container host is on supported build version 18362.
System PATH does not require an update.
Generating config.yaml...
Configured device for manual provisioning.
Configured device with hostname 'BLTSP00250'.
Configured device with Moby Engine URL 'npipe://./pipe/docker_engine' and network 'azure-iot-edge'.
Start-Service : Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start
service iotedge on computer '.'.
At line:1464 char:9
+         Start-Service $EdgeServiceName
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

**Comment by richma-ms** [comment]
Using Linux containers on 18362 is not supported, the latest Windows build that can be used this way is 17763.

https://docs.microsoft.com/en-us/azure/iot-edge/support
