### ISSUE TITLE
Module with integrated Webserver does not start when device is rebooted without internet connection

### ISSUE THREAD

**Issue by karakal** [Azure/iotedge#3096]
## Expected Behavior
We have a working deployment with several custom modules. One of them is a webapp. Everything is working fine when the device is connected to the internet. When I cut the internet connection and reboot the device all the modules should start.

## Current Behavior
When I cut the internet connection and reboot the device all custom modules are starting up correctly except the webapp.

The only message regarding this in the log is:
`Unable to process module webapp add or update as the module identity could not be obtained
`
Another thing is, that the edgeAgent appends the name of another module to the module webapp when restarted offline:
`Executing command: "Stop module opcclient/webapp"
Executing command: "Remove module opcclient/webapp"
Executing command: "Saving opcclient/webapp to store"
`

When I connect the internet connection again, everything is fine within seconds, the edgeAgent also uses the correct name of the module:

`- Executing command: "Command Group: (\n  [Create module webapp]\n  [Start module webapp]\n)"
- Executing command: "Create module webapp"
- Executing command: "Start module webapp"
`

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. create a deployment with a module with a webapplication server in it
2. verify the deployment
3. cut the internet connection
4. reboot the device

## Context (Environment)
iot-edge on Ubuntu 18.0.4 LTS

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.8 but 1.0.9.2 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

21 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS: Ubuntu 18.04
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.9
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.9.2
* Docker/Moby [run `docker version`]: 3.0.13+azure

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by richma-ms** [comment]
Please provide full logs from `iotedge support-bundle`

The startup logic does a module name lookup to get the module identity, and throws that error if the name can't be found.  If it's looking up a bogus module name, it'd make sense why you're seeing the error.

**Comment by karakal** [comment]
This is the support bundle after an offline restart, when my module webapp is failing....
[support_bundle.zip](https://github.com/Azure/iotedge/files/4817501/support_bundle.zip)

**Comment by karakal** [comment]
This ist the support bundle just after plugging the network cable in.....
[support_bundle.zip](https://github.com/Azure/iotedge/files/4817599/support_bundle.zip)

**Comment by karakal** [comment]
Just for clarification:
When started offline, my module appears as:

`opcclient/webapp  stopped          Stopped a minute ago       ****/webapp:1475`

Just after plugging the network cable in, it appears as:

`webapp            running          Up a minute      ****/webapp:1475`

There is another module named opcclient, but this is another module alltogether...

The deployment used here is without storage folders configured, but also the storage folders didn't change anything for the offline capabilites....

**Comment by richma-ms** [comment]
Thanks for providing the logs.  As far as I can tell, the agent state store somehow got bad data in it.  As you pointed out, there's no such module as "opcclient/webapp", this is confirmed by the edgeHub logs, which only shows the two separate "opcclient" and "webapp" module identities.

But in edgeAgent, this bad state is messing up the in-memory mapping of module name -> module identity.  When the look up fails, the agent will try to connect to IoT Hub to create the presumably missing module identity.  This behavior is actually present in both offline/online logs, except of course in the offline case we hit a connectivity failure.

Could you please grab the database from the EdgeAgent container and upload it so we can investigate?  With just logs, we can't tell exactly what data is causing this behavior.  But hopefully with a copy of the DB we'll be able to repro on our end and track down the cause.  Hopefully we'll be able to at least harden the parsing logic again similar failures in the future, as bad entries should not result in bogus modules.

As for your existing issue, you should be able to work around it by clearing out the persisted state of the EdgeAgent.  Since you said that this deployment doesn't have storage configured, manually removing the EdgeAgent container should be enough (it'll get automatically restarted by Edge Daemon afterwards).

**Comment by karakal** [comment]
Sorry, if this is a stupid question: Where is the edgeAgent Database? It's not in /iotedge/storage as I presumed.

Also I tried the following:

- stopping iotedge
- stopping and removing the edgeAgent container
- removing the edgeAgent image
- restarting iotedge

the problem was still existing afterwards...

I then detected something strange in the log of the edgeAgent. The opcclient hat a Links-definition set in the create Options of the module. Another module, that also accesses the webapp over REST didn't have the link set.
So I removed the Links definition from the create Options and now everything is working fine.

I don't understand it really...

If you need any other information please just tell me...

**Comment by richma-ms** [comment]
Can you please provide the deployment manifest for the two modules in question? It'd be useful for us to investigate what's really going on, maybe Docker is behaving in a way unexpected by EdgeAgent when there are links present.

**Comment by karakal** [comment]
Here is the deployment file in question with the error with the erronous offline capabilities:
(I have removed all environment parameters for our own modules and also the tags and the private registry infos and changed all the ports)

`{
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "modules": {
          "tcpserver": {
            "settings": {
              "image": "***/tcpserver:***",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"12348/tcp\":[{\"HostPort\":\"12348\"}]},\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-size\":\"50m\",\"max-file\":\"2\"}}}}"
            },
            "type": "docker",
            "version": "1.0",
            "env": {
              *** environment parameters ***
            },
            "status": "running",
            "restartPolicy": "always"
          },
          "influxdb": {
            "settings": {
              "image": "influxdb:1.8.0-alpine",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"12347/tcp\":[{\"HostPort\":\"12347\"}]},\"Binds\":[\"/opt/influxdb:/var/lib/influxdb\"],\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-size\":\"500m\",\"max-file\":\"2\"}}}}"
            },
            "type": "docker",
            "version": "1.0",
            "env": {
              *** environment parameters ***
            },
            "status": "running",
            "restartPolicy": "always"
          },
          "webapp": {
            "settings": {
              "image": "***/webapp:***",
              "createOptions": "{\"HostConfig\":{\"Links\":[\"mongodb:mongodb\",\"influxdb:influxdb\"],\"PortBindings\":{\"123/tcp\":[{\"HostPort\":\"123\"}],\"12346/tcp\":[{\"HostPort\":\"12346\"}]},\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-size\":\"500m\",\"max-file\":\"2\"}}}}"
            },
            "type": "docker",
            "version": "1.0",
            "env": {
              *** environment parameters ***
            },
            "status": "running",
            "restartPolicy": "always"
          },
          "mongodb": {
            "settings": {
              "image": "mongo:4.2.3-bionic",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"12345/tcp\":[{\"HostPort\":\"12345\"}]},\"Mounts\":[{\"Target\":\"/data/db\",\"Source\":\"mongodb-data\",\"Type\":\"volume\"}],\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-size\":\"500m\",\"max-file\":\"2\"}}}}"
            },
            "type": "docker",
            "version": "1.0",
            "env": {
              *** environment parameters ***
            },
            "status": "running",
            "restartPolicy": "always"
          },
          "opcclient": {
            "settings": {
              "image": "***/opcclient:***",
              "createOptions": "{\"HostConfig\":{\"Links\":[\"webapp:webapp\"],\"PortBindings\":{\"1234/tcp\":[{\"HostPort\":\"1234\"}]},\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-size\":\"50m\",\"max-file\":\"2\"}}}}"
            },
            "env": {
              *** environment parameters ***
            },
            "type": "docker",
            "version": "1.0",
            "status": "running",
            "restartPolicy": "always"
          },
          "MongoDbConnector": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "***/mongodbconnector:***",
              "createOptions": "{\"HostConfig:\":{\"Links\":[\"mongodb:mongodb\"]}}"
            },
            "env": {
              *** environment parameters ***
            }
          }
        },
        "runtime": {
          "settings": {
            "minDockerVersion": "v1.25",
            "registryCredentials": {
              *** credentials ***
            }
          },
          "type": "docker"
        },
        "schemaVersion": "1.0",
        "systemModules": {
          "edgeAgent": {
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0.9.3",
              "createOptions": "{\"HostConfig\":{\"Binds\":[\"/etc/iotedge/storage/:/iotedge/storage/\"],\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-size\":\"500m\",\"max-file\":\"2\"}}}}"
            },
            "type": "docker",
            "env": {
              "UpstreamProtocol": {
                "value": "AMQPWS"
              },
              "storageFolder": {
                "value": "/iotedge/storage"
              }
            }
          },
          "edgeHub": {
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0.9.2",
              "createOptions": "{\"HostConfig\":{\"Binds\":[\"/etc/iotedge/storage/:/iotedge/storage/\"],\"PortBindings\":{\"443/tcp\":[{\"HostPort\":\"443\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}]},\"LogConfig\":{\"Type\":\"json-file\",\"Config\":{\"max-size\":\"500m\",\"max-file\":\"2\"}}}}"
            },
            "type": "docker",
            "env": {
              "UpstreamProtocol": {
                "value": "AMQPWS"
              },
              "amqpSettings__enabled": {
                "value": "true"
              },
              "mqttSettings__enabled": {
                "value": "true"
              },
              "httpSettings__enabled": {
                "value": "false"
              },
              "storageFolder": {
                "value": "/iotedge/storage"
              }
            },
            "status": "running",
            "restartPolicy": "always"
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "routes": {
          *** routes ***
        },
        "schemaVersion": "1.0",
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    },
    "tcpserver": {
      "properties.desired": {
        *** desired properties ***
      }
    }
  }
}
`

The only thing we changed is the createOptions for the opcclient-module where we removed the Links.

**Comment by richma-ms** [comment]
We're tracking this ticket internally for investigation and fix.  Thanks for helping identify this problem.
