### ISSUE TITLE
A module Identity does not exist for this module

### ISSUE THREAD

**Issue by carloshm** [Azure/iotedge#310]
A working module deployed and configured gets removed its identity as a separate module. This affects the behavior of the solution as it expects data in the twin to properly work. Modules are named as NamedModule (Uppercase first letter) and after the unexpected change, a new namedModule module identity is created. A workaround to recover the module is to create a new identity module manually with NamedModule name, although twin properties are removed and it impacts any dependant state.
This workaround is not acceptable in a production environment.

![imagen](https://user-images.githubusercontent.com/2389573/45696993-08e33880-bb65-11e8-99f6-75d351d5893f.png)

![imagen](https://user-images.githubusercontent.com/2389573/45697014-11d40a00-bb65-11e8-972a-5d768ab4517b.png)

## Expected Behavior

a functional module should not be changed, and module identity should remain as initially created.

## Current Behavior

A module lost while connected to IoTHub its identity and it is created as a separate module

## Steps to Reproduce

No specific steps defined this state. A working module moves into this behavior after some time. It may happen when new modules are deployed. We have experienced this behavior many times, before and after GA.

### Device (Host) Operating System

Raspberry Pi Stretch

### Architecture

arm32

### Container Operating System

Linux 

#### iotedged

iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0 

#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker

Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Wed Jun 27 00:53:52 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Tue Jun 26 23:27:27 2018
  OS/Arch:      linux/arm
  Experimental: false

## Additional Information

SDK 1.18 https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/2018-8-17

**Comment by myagley** [comment]
Thanks for the issue report!

@varunpuranik do you think this is related to https://github.com/Azure/iotedge/pull/306?

**Comment by varunpuranik** [comment]
Yes, I do believe that https://github.com/Azure/iotedge/pull/306 is the underlying issue here. It also causes EdgeAgent to not identify the 2 modules as the same, and it recreates the modules.

**Comment by varunpuranik** [comment]
Yes, this should go away after the next release.

**Comment by myagley** [comment]
We are expecting a new release in the next few days.

**Comment by carloshm** [comment]
Which is the best process to be notified for updates?

**Comment by myagley** [comment]
We are working on improving the all up update notification story for IoT Edge. In the meantime, releases are cataloged at the https://github.com/Azure/azure-iotedge/releases repository. The best short term solution may be to add notifications to this repository.

**Comment by myagley** [comment]
Version 1.0.2 of the runtime was just released. This release includes a fix for this issue. I'm going to close this issue for now, but please feel free to reopen. Thanks.

**Comment by carloshm** [comment]
> 
> 
> Version 1.0.2 of the runtime was just released. This release includes a fix for this issue. I'm going to close this issue for now, but please feel free to reopen. Thanks.

Which is the recommended way to update an existing gateway?
