### ISSUE TITLE
Direct Method Invocation with handler returning a string response (as byte []) along with status 200 results in Status 500, payload null on the portal

### ISSUE THREAD

**Issue by alkreddy** [Azure/iotedge#3104]
## Expected Behavior
When **Direct Methods** on IoT Edge Modules are invoked from portal or otherwise, the **response message** (if any) from the method **should be available** in the portal.

## Current Behavior
When the Invoked Direct Method has a response to send back to the caller, the response ends up as **`{"status":500,"payload":null}`**

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create an IoTEdge Module that handles direct method invocation through moduleClient's **`SetMethodHandlerAsync(...)`** method
2. Let the handler return a method response of the form 
**`return new MethodResponse(Encoding.UTF8.GetBytes("Some Response Message"), 200);`**
3. Build and Deploy the module to a Container Registry
4. Add a IoT Edge Device in Azure Portal, set the module we just built
5. Connect a Physical device with the IoT Edge Device and wait for the modules to start up
6. From the Azure Portal, open the module on the device we just created and use the Direct Method option to Invoke a Method supported by the module.
7. Notice that the response is always of the form **`{"payload":null,"status":500}`** . The **Ok** response code with a string response converted to byte array is somewhere in the response processing results in **500 error response**
8. Now, modify the module code so that the **MethodHandler** returns a response of the form
**`return new MethodResponse(200) \\No response message; just code`**
9. repeat deploy and test steps
10. Notice that the response from Direct Method Invocation is now of the form **`{"status":200,"payload":null}`**

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
-------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.8 but 1.0.9.2 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

19 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS : Ubuntu 18.04 
* Architecture : x86_64
* Container OS : Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.8
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.9
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.9
* Docker/Moby [run `docker version`]: 3.0.11+azure

_Note: Same observation with Agent/Hub version 1.0.8_

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by richma-ms** [comment]
Hi, please provide edgeHub logs of this issue for investigation.

**Comment by richma-ms** [comment]
Ah I think I see your problem, the string payload that you pass back in MethodResponse needs to be JSON format.

Try something like:
`return new MethodResponse(Encoding.UTF8.GetBytes({\"result\":\"Some Response Message\"}), 200);`

**Comment by alkreddy** [comment]
Thanks @richma-ms . That sounds like the resolution. Will try it on Monday and let you know.

**Comment by richma-ms** [comment]
Closing this for now, if you're still running into a problem after changing the payload format, please open a new issue.
