### ISSUE TITLE
Not able to deploy more than 20 modules on single Edge Device of IoT Hub

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#3105]
Hi Team,
    Currently we are not able to deploy more than 20 modules on single Edge Device on IoT Hub. So could you tell me how we can achieve it?? 
The requirement is that we need to deploy multiple modules and the count is increasing more than 20 so please let me know the option for this..

**Comment by richma-ms** [comment]
You can have up to 50 modules per Edge device.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits

If you're specified more than 20, but it's not deploying, please double check to make sure that the deployment manifest hasn't exceeded the max size on the edgeAgent twin.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-twin-size

**Comment by sandervandevelde** [comment]
I just checked, it's still 20 at this moment (22 if you include edgehub and edge agent):

![image](https://user-images.githubusercontent.com/694737/84883693-1eb2c400-b091-11ea-87fb-4bdf0ec1d36e.png)

(West Europe IoT Hub, S1)

This seems to be a soft limit. How can it be raised?

**Comment by richma-ms** [comment]
This seems like a bug with the portal UX, I just tried it with az CLI and was able to bypass the 20 modules limit.

I'll file an issue with the portal team internally for them to fix this, in the mean time, please use the CLI to workaround the bug until they push out a fix.

![image](https://user-images.githubusercontent.com/54086435/84962999-02c51780-b0bd-11ea-8876-856e7f816282.png)

**Comment by sandervandevelde** [comment]
This is great news. Thanks for the confirmation.

**Comment by cenkersoy** [comment]
This page mentions "30 modules" : https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-at-scale
