### ISSUE TITLE
Moby Docker is keep increasing the size of disk space.. Specially the folder `windowsfilter` is being creasing disk size

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#3106]
HI Team,
    Moby Docker is keep increasing the size of disk space.. Specially the folder `windowsfilter` is being creasing disk size. So could you tell me the way to clean it up as we are facing issue on the Gateway because of this.. 
We are using Windows 10 and docker image is also windows. IoT Edge Runtime 1.0.8

**Comment by richma-ms** [comment]
This seems to be internally managed by Moby, but there are existing discussions about how to delete it to start over:
https://github.com/moby/moby/issues/26873
