### ISSUE TITLE
Get "None of the intermediate CAs were found in the list of allowed CAs"

### ISSUE THREAD

**Issue by raphaelzulliger** [Azure/iotedge#3128]
I'm basically running into the same issue as reported (and solved) here https://github.com/Azure/azure-iot-sdk-c/issues/580

I solved the issue for myself by switching to the C SDK's `certGen.sh` instead of this iotedge's one located at https://github.com/Azure/iotedge/tree/master/tools/CACertificates

I report this issue because it costed me quite some time to figure it out. Thus it may safe others' time by solving it.

To repeat the essence of the linked C SDK issue: Certificates generated by `certGen.sh create_device_certificate` don't work for IoT devices setup to use "X.509 CA Signed". IoT Hub's log mention the following error:

```
ResultType: 401002
ResultDescription: None of the intermediate CAs were found in the list of allowed CAs: IntermediateCAs=xxxxx; AllowedCAs=xxxxxx
```

**Comment by arsing** [comment]
I'm not sure the fix that the C SDK did is the best approach. They fixed it by having the device ID cert be signed directly by the root CA instead of the intermediate CA. Of course that solves the problem, but then what was the point of creating the intermediate CA?

The proper fix would be to concat the intermediate CA to the device ID cert's PEM so that the client, ie `iotedged` sends the full chain to IoT Hub / DPS as part of TLS client auth. I'm not too familiar with the script so I don't know if the other functions in the script already do that or not, but in general anything that uses CA foo to sign cert bar should create a PEM with at least bar and foo in it.

**Comment by arsing** [comment]
@raphaelzulliger It seems to me our version of the script already does what I said it should do: https://github.com/Azure/iotedge/blob/master/tools/CACertificates/certGen.sh#L251-L258

Did you use the `iot-device-*-full-chain.cert.pem` file or the `iot-device-*.cert.pem` file in your `config.yaml` ?

**Comment by raphaelzulliger** [comment]
> The proper fix would be to concat the intermediate CA to the device ID cert's PEM so that the client, ie `iotedged` sends the full chain to IoT Hub / DPS as part of TLS client auth. I'm not too familiar with the script so I don't know if the other functions in the script already do that or not, but in general anything that uses CA foo to sign cert bar should create a PEM with at least bar and foo in it.

I can't judge this statement, but it sounds good to me and a solution like this was also proposed somewhere on the web. I just didn't feel like adjusting the script accordingly due to lack of knowledge

**Comment by arsing** [comment]
I'm saying you don't need to adjust the script, because it already does that.

**Comment by raphaelzulliger** [comment]
> Did you use the `iot-device-*-full-chain.cert.pem` file or the `iot-device-*.cert.pem` file in your `config.yaml` ?

I was not specific enough: I actually properly setup/configured/run IoT Edge. My problem was that I was not able to bring up the IoT leaf devices using "X.509 CA Signed" method with the `certGen.sh` provided by this project ("X.509 Self-Signed" and "Symmetric Key" worked).

For "CA Signed" I need to provide a `.pfx` file as I'm using code like this (and I think I *need* to have code like this, but let me know if I'm doing something wrong here):

```csharp
var cert = new X509Certificate2(@"new-device.cert.pfx", "1234");
var auth = new DeviceAuthenticationWithX509Certificate(deviceId, cert);
var deviceClient = DeviceClient.Create("xxxxx.azure-devices.net", auth, TransportType.Amqp_Tcp_Only);
```

With a `.pfx`, it seems I have not much options: there is only one generated by `certGen.sh`.

Maybe `certGen.sh` properly includes the intermediate certificate for the "edge" certificates but does not so for the "device" certificates?

**Comment by arsing** [comment]
>Maybe `certGen.sh` properly includes the intermediate certificate for the "edge" certificates but does not so for the "device" certificates?

It does so for all of them. The section of the script I linked to is a common function used for both edge device certs and leaf device certs.


>For "CA Signed" I need to provide a .pfx file

https://github.com/Azure/iotedge/blob/master/tools/CACertificates/certGen.sh#L266 is the part that creates the `.pfx` file. It passes in `issuer_chain` as the `-certfile` parameter, so the `.pfx` should contain the full chain also.


>`var cert = new X509Certificate2(@"new-device.cert.pfx", "1234");`

I don't know if this is correct. AFAIK `X509Certificate2` represents a single cert, so it's likely parsing the .pfx successfully but only picking the first cert (the device cert) and ignoring the rest of the chain. You likely need an `X509Certificate2Collection`, though how you get that from a .pfx and how you get `DeviceClient` to use it, I don't know.

**Comment by raphaelzulliger** [comment]
> It does so for all of them. The section of the script I linked to is a common function used for both edge device certs and leaf device certs.
> 
> > For "CA Signed" I need to provide a .pfx file
> 
> https://github.com/Azure/iotedge/blob/master/tools/CACertificates/certGen.sh#L266 is the part that creates the `.pfx` file. It passes in `issuer_chain` as the `-certfile` parameter, so the `.pfx` should contain the full chain also.
> 
> > `var cert = new X509Certificate2(@"new-device.cert.pfx", "1234");`
> 
> I don't know if this is correct. AFAIK `X509Certificate2` represents a single cert, so it's likely parsing the .pfx successfully but only picking the first cert (the device cert) and ignoring the rest of the chain. You likely need an `X509Certificate2Collection`, though how you get that from a .pfx and how you get `DeviceClient` to use it, I don't know.

Regarding the `X509Certificate2`: This code works when using a certificate created by C SDK's `certGen.sh`.

Maybe I did something wrong but I really tried hard to get it working and tried dozens of things... and switching to C SDK immediately brought success.

Maybe you could try to bring up a leaf device with this version of the `certGen.sh`. I'd would be surprised if you could (and would feel sorry for stealing your time).

**Comment by arsing** [comment]
It'll work for the C SDK's script even if `X509Certificate2` truncates the chain, because as I said the PR you linked made it so that the device ID cert is signed directly by the root CA that you uploaded to Azure.

**Comment by raphaelzulliger** [comment]
> It'll work for the C SDK's script even if `X509Certificate2` truncates the chain, because as I said the PR you linked made it so that the device ID cert is signed directly by the root CA that you uploaded to Azure.

Ah right, sorry for that!

Then, `X509Certificate2Collection` may be the solution. Not sure whether I can try it in the coming days.

Then, I failed to come up with this myself even though I went forth and back in the documentation. My current code is based on the documentation [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-security-x509-get-started#authenticate-your-x509-device-with-the-x509-certificates) which uses `X509Certificate2` and doesn't mention `X509Certificate2Collection` at all.

Either way: Thanks for looking into this! I think we can close this issue. *Maybe* we should create one for "improving" documentation or even file a bug at C SDK to point to the weakness of there approach.

**Comment by arsing** [comment]
I've asked other people in the team who are more familiar with .Net and the SDK to respond.

You should probably ask at https://github.com/Azure/azure-iot-sdk-csharp/issues . Based on https://github.com/Azure/azure-iot-sdk-csharp/issues/330 there is already a way to use a `Collection` with the DPS client (see the usage of `SecurityProviderX509Certificate` in the code sample). So there may be a way to use it with the IoT Hub client too, or it may just be something they need to implement.

**Comment by ancaantochi** [comment]
Confirming comments above, X509Certificate2 is a single certificate so it won't load the full chain. From the DeviceClient code it looks like the only way is to provide a single certificate, so in order to work with CA, the chain would need to be installed on the device. You can install the chain on the device by using this example code: https://github.com/Azure/iotedge/blob/master/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs#L211 

I will follow up with the SDK team to update the documentation.

**Comment by raphaelzulliger** [comment]
Thanks for the great support!

I feel sorry not to have had the time to test this right away and give feedback.
