### ISSUE TITLE
How to allow two edge Modules running in same Edge Device to send their data to different IoT Hubs

### ISSUE THREAD

**Issue by emulic** [Azure/iotedge#3130]
How to properly design a solution where we need to combine 2 IoT Edge modules from two different manufacturers in the same IoT Edge device? Every module should send it's telemtry data to a manufacturer specific IoT Hub. I know, we could simply implement a custom module and use device client to talk to different IoT  Hubs. But there would be some disadvantages by this solution. I.e. you can't profit from edgeHub agent built-in features like offline mode and retry. Handling for Sas Token for second IoT Hub must be managed somehow.  And the manufacturer of the custom module must use IoT hub of other manufacturer to manage his own module (updates etc.).
Are you maybe planning this as a feature in some future version of IotEdge?

**Comment by ggjjj** [comment]
hi @emulic  We don't support this feature as of today. we will add this a feature request to our list. Thanks.

**Comment by veyalla** [comment]
Please file or vote for existing feature request at https://feedback.azure.com/forums/907045-azure-iot-edge
