### ISSUE TITLE
Error : Deployment information could not be retrieved.

### ISSUE THREAD

**Issue by KosukeTsumura** [Azure/iotedge#3171]
I'm not sure that here is appropriate place to report following bugs.

I fould that #417 and it seems that I'm facing same issue when I click 'IoT Edge' from azure portal like followings,
<img width="1440" alt="Screen Shot 2020-07-01 at 22 32 30" src="https://user-images.githubusercontent.com/19725264/86301506-07530980-bc41-11ea-909a-b567dc4c9911.png">

Is it possible to reopen this issue again?

```
There was an error querying devices: Unauthorized:{
  "Message": "{\"errorCode\":401002,\"trackingId\":\"c39a7ac476274d2b89061c842cbee363-G:6-TimeStamp:07/01/2020 23:38:37\",\"message\":\"Unauthorized\",\"timestampUtc\":\"2020-07-01T23:38:37.6260454Z\"}",
  "ExceptionMessage": ""
}.
```

Cheers,

**Comment by ancaantochi** [comment]
@KosukeTsumura 

This looks like an issue with the service or the portal, not an edge issue. I am trying to contact those teams and get a response from them and will update the issue here.

**Comment by varunpuranik** [comment]
@KosukeTsumura - since this is a service/portal issue and unrelated to Edge, can you please open a [Portal Issue](https://portal.azure.com/#create/Microsoft.Support) instead?
