### ISSUE TITLE
Docker is not running in Ubuntu 18.04 + armhf

### ISSUE THREAD

**Issue by V-Guru** [Azure/iotedge#3182]
### Hi Team,
IOT edge runtime is not runnig in Ubuntu 18.04 + armhf environment. I have attached all logs related to docker.
Can you help with below queries.
1. Is there any thing missing in system configuration? See below check-config command
2. What is the issue to run docker?

### Device Information
![image](https://user-images.githubusercontent.com/23724110/86795855-9de15980-c08b-11ea-9264-583f8a590bfa.png)

## Iot Edge and docker versions

![image](https://user-images.githubusercontent.com/23724110/86793353-ffec8f80-c088-11ea-80ab-d29f76f9d932.png)

## Docker error ($dockerd  $systemctl status docker.service $docker info)
![image](https://user-images.githubusercontent.com/23724110/86794062-b0f32a00-c089-11ea-91ba-262a4f407c5e.png)

## ./check-config.sh command result
![image](https://user-images.githubusercontent.com/23724110/86795058-ce74c380-c08a-11ea-8ba2-59216308ba81.png)
![image](https://user-images.githubusercontent.com/23724110/86795144-e5b3b100-c08a-11ea-9dc1-ef74ac255758.png)
![image](https://user-images.githubusercontent.com/23724110/86795207-f7955400-c08a-11ea-9578-ebbef149d648.png)

Thanks,
Suresh

**Comment by dylanbronson** [comment]
Hello,

I haven't dug into the root of the issue yet, but we don't support ARM32 for Ubuntu 18.04, so we have no testing for it. 

We only support ARM32 on Raspbian.
We do support 18.04 on ARM64 in preview.
Here's the full list:
https://docs.microsoft.com/en-us/azure/iot-edge/support
Can you use one of the supported combinations?

**Comment by V-Guru** [comment]
Hi Dylan,

Thanks for the confirmation. We will look into supported combinations.
