### ISSUE TITLE
Unable to install or upgrade moby-engine on Raspbian

### ISSUE THREAD

**Issue by nellesor** [Azure/iotedge#3184]
pi@raspberrypi:~ $ sudo apt-get upgrade moby-engine

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  coinor-libipopt1v5 containerd.io libiothsm-std libmumps-seq-4.10.0 libraw15 netsurf-common realpath vlc-plugin-notify vlc-plugin-samba
  vlc-plugin-video-splitter vlc-plugin-visualization
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  moby-engine
The following packages have been kept back:
  ffmpeg libavdevice57 libavfilter6 libavformat57 libvlc-bin libvlc5 omxplayer python-gpiozero python3-gpiozero python3-thonny vlc vlc-bin vlc-data
  vlc-l10n vlc-plugin-base vlc-plugin-qt vlc-plugin-skins2 vlc-plugin-video-output
0 upgraded, 1 newly installed, 0 to remove and 18 not upgraded.
Need to get 0 B/33.0 MB of archives.
After this operation, 141 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 144004 files and directories currently installed.)
Preparing to unpack .../moby-engine_3.0.13+azure-0_armhf.deb ...
Unpacking moby-engine (3.0.13+azure-0) ...
dpkg: error processing archive /var/cache/apt/archives/moby-engine_3.0.13+azure-0_armhf.deb (--unpack):
 trying to overwrite '/usr/bin/containerd', which is also in package containerd.io 1.2.13-2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/moby-engine_3.0.13+azure-0_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

following this https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux for referance

**Comment by veyalla** [comment]
@cpuguy83 - any ideas?

**Comment by cpuguy83** [comment]
You have the `containerd.io` package installed, which conflicts with moby-engine, which provides it's own version of containerd.

Also note `apt-get upgrade` upgrades all packages on the system (regardless of argument).
To upgrade a specific package, you need to use `apt-get install`.

**Comment by nellesor** [comment]
I had run apt-get install just prior and got a similar error.. I was able to remove the container.io package by running

sudo apt remove containerd.io

and then run through the rest of the tutorial and get my iotedge device running.. thanks so much!

**Comment by veyalla** [comment]
Thanks for the help @cpuguy83
