### ISSUE TITLE
Mount folder on host from module (createoptions)

### ISSUE THREAD

**Issue by mortslhawmit** [Azure/iotedge#319]
Hello! 
I'm struggling to get my binding to work from createoptions, my createoption looks like this

> {
      "Mounts": [ {
      "Type": "bind",
      "Source": "/home/pi/folderwhereikeepmythings",
      "Destination": "/app",
      "Mode": "",
      "RW": true,
      "Propagation": "rprivate"
    }
  ],
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  },
  "HostConfig": {
    "Privileged": true,
    "NetworkMode": "host",
    "Binds": [
      "/home/pi/folderwhereikeepmythings:/app"]
  }
}

I tried to follow the tips from [here](https://github.com/MicrosoftDocs/azure-docs/issues/5417) and i've also tried to figure it out with help from [here](https://docs.docker.com/engine/api/v1.32/#operation/ContainerList) but to no success. 

The module updates the reported createoption with the "Binds" part but not the "Mounts" part, and I'm not sure what I am doing wrong. And when it has updated the Binds part the module wont start anymore so Im guessing that I've done that incorrect aswell.

## Expected Behavior
Module should be granted access to the files located on the host, if createoptions is done correctly?

## Current Behavior
Module wont start with the current createoptions

### Device (Host) Operating System
RPI 3 Raspbian

### Architecture
Arm32

### Container Operating System
Linux containers

#### iotedged
1.0.0

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
18.02.0-ce, build fc4de44

**Comment by mortslhawmit** [comment]
It works better if im not trying to use the /app folder! My bad..

{
"Mounts": [ {
"Type": "bind",
"Source": "/home/pi/folderwhereikeepmythings",
"Destination": "/test",
"Mode": "",
"RW": true,
"Propagation": "rprivate"
}
],
"NetworkingConfig": {
"EndpointsConfig": {
"host": {}
}
},
"HostConfig": {
"Privileged": true,
"NetworkMode": "host",
"Binds": [
"/home/pi/folderwhereikeepmythings:/test"]
}
}

**Comment by nkolchakov** [comment]
I tried different [approach](https://stackoverflow.com/questions/52572289/mount-path-to-azure-iot-edge-module?rq=1) with volume type and I had the same Issue where I can't use '/app' can someone explain why it doesnt work with `/app` folder ?

**Comment by darobs** [comment]
Hi @nkolchakov, it depends on the module. In all of the team's modules (edgeHub, edgeAgent, samples), we put the module binaries in the /app folder ([example](https://github.com/Azure/iotedge/blob/master/edge-modules/SimulatedTemperatureSensor/docker/linux/amd64/Dockerfile)), and I think that's a pretty common pattern. So, if the container is expecting to run a binary in the /app folder, and it's not there because you mounted over it, the container will fail.
