### ISSUE TITLE
iotedge 'check' command produces certificate warnings for devices provisioned with DPS

### ISSUE THREAD

**Issue by iitsDelbruegger** [Azure/iotedge#3196]
We followed the instructions given [here](https://docs.microsoft.com/de-de/azure/iot-edge/how-to-auto-provision-simulated-device-linux) and setup a new IoT Edge device with a Device Provisioning Service and a TPM module in HyperV.

We did not specify any certificates in the config.yaml (see below, this part is commented out) because we expected that the DPS takes care of these details.

As a side note, the instructions could be improved by clarifying how to start a "Simulator.exe" in linux ;) However, the instructions to use a virtual TPM from a real device via Hyper-V (without simulator) worked for us.

## Expected Behavior
We expected the Device Provisioning Service to handle the provisioning of our IoT Edge devices, including secure certificates to communicate with IoT Hub.

## Current Behavior
The iotedge 'check' command produces certificate warnings for devices provisioned with DPS. We get the warning:
`production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2020-10-06 14:06:21 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead.`

## Steps to Reproduce
See  [here](https://docs.microsoft.com/de-de/azure/iot-edge/how-to-auto-provision-simulated-device-linux)

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
sudo iotedge check --iothub-hostname xyz123.azure-devices.net
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2020-10-06 14:06:21 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

18 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Xubuntu 18.04 in Hyper-V on a Windows 10 laptop (Dell XPS 15)

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9.3
* Edge Agent [image tag (e.g. 1.0.0)]: azureiotedge-agent:1.0
* Edge Hub [image tag (e.g. 1.0.0)]: none
* Docker/Moby [run `docker version`]: 19.03.12+azure

## config.yaml

<details>
<summary>excerpt from iotedge config.yaml</summary>

```
provisioning:
  source: "dps"
  global_endpoint: "https://global.azure-devices-provisioning.net"
  scope_id: "abc123"
  attestation:
    method: "tpm"
    registration_id: "abc123"

...

# certificates:
#   device_ca_cert: "<ADD URI TO DEVICE CA CERTIFICATE HERE>"
#   device_ca_pk: "<ADD URI TO DEVICE CA PRIVATE KEY HERE>"
#   trusted_ca_certs: "<ADD URI TO TRUSTED CA CERTIFICATES HERE>"

```
</details>

**Comment by dylanbronson** [comment]
Hello,
This check is for the device CA cert, which is unrelated to the DPS-TPM provisioning method. You can read up on the Device CA cert here: https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs
You can use the test certs for development, but it is recommended to use production ready certs in production

**Comment by iitsDelbruegger** [comment]
Hi @dylanbronson,
this is not the way we understood DPS from the introduction [here](https://docs.microsoft.com/de-de/azure/iot-dps/about-iot-dps):

> When to use Device Provisioning Service
> -  **Zero-touch provisioning to a single IoT solution without hardcoding IoT Hub connection information** at the factory (initial setup)
> -  Load-balancing devices across multiple hubs
> -  Connecting devices to their owner's IoT solution based on sales transaction data (multitenancy)
> -  Connecting devices to a particular IoT solution depending on use-case (solution isolation)
> -  Connecting a device to the IoT hub with the lowest latency (geo-sharding)
> -  Reprovisioning based on a change in the device
> -  **Rolling the keys used by the device to connect to IoT Hub** (when not using X.509 certificates to connect)


How are we supposed to get a zero-touch provisioning if we still have to generate and copy certificates to the device on our own? How is the DPS "rolling the keys" if the device CA certs are unrelated?

**Comment by veyalla** [comment]
@iitsDelbruegger Hope this answers your query. If you'd like to see a product improvement around this please create or up vote a feedback item at: https://feedback.azure.com/forums/907045-azure-iot-edge
