### ISSUE TITLE
Edge Hub not running and connection issue.

### ISSUE THREAD

**Issue by poorvi298** [Azure/iotedge#3208]
I am trying to install IoT Edge runtime on my Ubuntu VM. It installed correctly but no agent was running. I started the edgeAgent by pulling the image using docker. Edge Hub container does not seem to download nor startup. It looks like the Edge Agent is not even communicating with the Azure IoT service but there are no meaningful messages other than receiving an empty edge agent config. I am in a corporate network but have configured proxy .

**Expected Behaviour**
Expected to see both the modules running.

**Current Behaviour**
$ sudo iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeAgent        running          Up 3 days        mcr.microsoft.com/azureiotedge-agent:1.0

$ sudo iotedge check

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 73 days (at 2020-09-24 04:35:44 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect to csi-dev-us-ea-iothub.azure-devices.net:5671 : could not resolve hostname
× host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - Error
    Could not connect to csi-dev-us-ea-iothub.azure-devices.net:443 : could not resolve hostname
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect to csi-dev-us-ea-iothub.azure-devices.net:8883 : could not resolve hostname
× container on the default network can connect to IoT Hub AMQP port - Error
    Container on the default network could not connect to csi-dev-us-ea-iothub.azure-devices.net:5671
× container on the default network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the default network could not connect to csi-dev-us-ea-iothub.azure-devices.net:443
× container on the default network can connect to IoT Hub MQTT port - Error
    Container on the default network could not connect to csi-dev-us-ea-iothub.azure-devices.net:8883
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the azure-iot-edge network could not connect to csi-dev-us-ea-iothub.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to csi-dev-us-ea-iothub.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the azure-iot-edge network could not connect to csi-dev-us-ea-iothub.azure-devices.net:8883

8 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
10 check(s) raised errors. Re-run with --verbose for more details.

**Steps to reproduce**
1. Follow procedures on https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support
2. After deployment and installation on computer, run "sudo iotedge list"
3. See no module running. Wait several minutes or hours. Nothing different. 
4. Run "docker pull  mcr.microsoft.com/azureiotedge-agent:1.0" and after this restarted the iot edge.
5. Only edgeAgent running.
6. View logs and see message "Empty edge agent config was received." and also "Error creating a device-to-cloud connection"

**Context(Environment)**
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Container Operating System**

Linux containers

**Runtime Versions**

iotedged
iotedge 1.0.9.3

Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

Edge Hub
none

**Logs**

iotedge logs edgeAgent

2020-07-01 16:13:07  Starting Edge Agent
2020-07-01 16:13:07.320 +00:00 Edge Agent Main()
<6> 2020-07-01 16:13:07.572 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-07-01 16:13:07.778 +00:00 [INF] - Version - 1.0.9.3.32101608 (ad04e23b1865211913282b918263700deafdccfa)
<6> 2020-07-01 16:13:07.778 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-07-01 16:13:07.806 +00:00 [INF] - Detected proxy https://pitc-zscaler-aspac-bangalore3pr.proxy.corporate.ge.com:80/
<6> 2020-07-01 16:13:07.862 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false,"EnableGetLogs":false,"EnableMetrics":false}
<6> 2020-07-01 16:13:08.042 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:09/24/2020 04:35:44] to Root
<6> 2020-07-01 16:13:08.617 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2020-07-01 16:13:08.704 +00:00 [INF] - Started operation refresh twin config
<6> 2020-07-01 16:13:08.724 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<6> 2020-07-01 16:13:08.812 +00:00 [INF] - Registering request handler RestartModule
<4> 2020-07-01 16:13:13.971 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-01 16:13:13.978 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-01 16:13:23.995 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-01 16:13:23.995 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-01 16:13:33.995 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-01 16:13:33.995 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-01 16:13:43.996 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-01 16:13:43.997 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<6> 2020-07-01 16:13:44.500 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2020-07-01 16:13:53.998 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead

**Comment by dylanbronson** [comment]
Hi, it is definitely wrong that you see no modules running after a few minutes after installing and deploying. This probably means something is going wrong with the Edge daemon pulling the edgeAgent image. You shouldn't have to pull the image yourself. 
(I assume you went through the "configure the daemons" steps)

Seeing the Edge daemon logs would be quite helpful. 
This page will show you how to do that. You can also just run the support-bundle command (also in the link), which will gather a folder of logs. If you post them here, please make sure to redact any personal information that you don't want to be public.

https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot

**Comment by poorvi298** [comment]
Hi, I am posting the logs of docker and Edge daemon.

[docker.txt](https://github.com/Azure/iotedge/files/4922852/docker.txt)
[iotedged.txt](https://github.com/Azure/iotedge/files/4922853/iotedged.txt)

**Comment by dylanbronson** [comment]
Hi, Apologies for the delay.

It looks like your proxy is unable to connect to IoT Hub.

The edgeAgent logs reflect that no deployment has occurred. This is probably because it can't connect to IoT Hub. But iotedged should be able to pull edgeAgent automatically if it could connect to IoT Hub. So those both seem to be the same root issue.

Do you have a firewall that is blocking your proxy from contacting IoT Hub? You can check this by trying to resolve your IoT Hub with a ping from command line - make sure you are going through the proxy.

**Comment by poorvi298** [comment]
Hi,
I have a firewall but I don't think that should block my proxy because i tried few java sdks and they are working fine. I have set the same proxy in both the places.

I tried the ping <iothubname>.azure-devices.net command, and it is showing unknown host.
Is the command correct and if yes, what can I do next?
And I don't know whether it is going through proxy or not.

**Comment by dylanbronson** [comment]
Hi, Can you try pinging hub like this:
```
openssl s_client -connect {your hub name}.azure-devices.net:8883 -proxy {yourproxy:port}
```
You need openssl s_client 1.1 to use the -proxy option

Also, can you make sure you followed these steps correctly: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#moby-daemon - specifically the configuration of the docker daemon steps (https://docs.docker.com/config/daemon/systemd/#httphttps-proxy).

If the docker daemon proxy configuration is not set up correctly, then that would also explain this behavior

**Comment by ebertrams** [comment]
@poorvi298 , any updates on this issue? Did dyanbronson recommendation solved your issue? Thanks

**Comment by ebertrams** [comment]
@poorvi298 , Any updates on this issue? Can we close this item? Thanks

**Comment by varunpuranik** [comment]
@poorvi298 - I will close this issue, since we did not hear back from you. Please feel free to open a new issue if you run into any more problems.
