### ISSUE TITLE
Sending cloud to device messages to a module

### ISSUE THREAD

**Issue by amogh79** [Azure/iotedge#3230]
## Expected Behavior
This is not a bug but rather a question

## Current Behavior
I want to send cloud 2 device message from an Azure Function to a edge module.

## Steps to Reproduce
N/A

## Context (Environment)
Windows and .Net Core with windows container edge modules on windows VMs

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Windows
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Windows

### Runtime Versions
* iotedged [run `iotedge version`]: Latest
* Edge Agent [image tag (e.g. 1.0.0)]: Latest
* Edge Hub [image tag (e.g. 1.0.0)]: Latest
* Docker/Moby [run `docker version`]: Latest

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
We are building edge modules which need some information flowing from cloud to the edge modules on occurrence of some events. I have successfully sent cloud to device messages to IoT devices but never to and IoT Edge module. I read some old posts where it is explained that Edge Modules don't support cloud to device messaging with ModuleClient but can be implemented using Device client. Please help me understand if today's edge module version allows sending cloud to device messages. If not what is the alternative for it.

**Comment by yophilav** [comment]
Good evening @amogh79! 
Thank you for your question.  Could you alias me to the document please? 
Currently you can implement a Clout-to-Device message (C2D) using [DeviceClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.deviceclient?view=azure-dotnet) class, but not [ModuleClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient?view=azure-dotnet) class. 

I think this instruction should be a good place to start. 😃
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d

After you have implemented the code using the DeviceClient, you can then build the code into a container image and deploy it as an edge module.

**Comment by amogh79** [comment]
@yophilav thanks for your response. Following text talks about Cloud to Device message in the link, "When using an opaque gateway (protocol translation) pattern, all devices connecting through that gateway share the same cloud-to-device queue, which can contain at most 50 messages. It follows that the opaque gateway pattern should be used only when few devices are connecting through each field gateway, and their cloud-to-device traffic is low."

https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-as-gateway

Not sure what it means and is not giving a clear idea if cloud to device messaging is supported by edge modules or not.

Please let me know your thoughts.

**Comment by yophilav** [comment]
I have confirm with my colleague that the C2D can be done behind a gateway with the limitation of 50 messages per device. 
The limitation was inherited from IoTHub specification (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-c2d)

In our group we have a test module that receives a C2D message behinds a transparent gateway (namely edgeHub). 
The C2D receiver module code can be found here:
https://github.com/Azure/iotedge/blob/master/test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageReceiver.cs#L69
