### ISSUE TITLE
device provisioning services with rasberrypi3

### ISSUE THREAD

**Issue by avinashKS99** [Azure/iotedge#3233]
Hi 
i am trying to provision the raspberry with x509 certificate when i am provisioning  first time the status of DPS shown as assigned.once device bottling up the state change to fail and remains in failed only after restating runtime in device. i am sharing the status of DPS.
Registration Status
Status: failed
Error code: 400207
Error message: Custom allocation failed with status code: 400
Assigned hub: -
Device ID: -
Last assigned: Thu Jul 16 2020 12:32:17 GMT+0530 (India Standard Time)

**Comment by yophilav** [comment]
Hello @avinashKS99 ,
Thank you for contacting us! 
Have you tried to follow the steps in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs to deploy & setup X509 provisioning?

**Comment by yophilav** [comment]
@avinashKS99 
Any updates on this issue?

**Comment by varunpuranik** [comment]
Closing this issue. 
@avinashKS99 - please feel free to re-open this issue or open a new one if you are still having any problems. Also please provide detailed logs as described here - https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#check-the-status-of-the-iot-edge-security-manager-and-its-logs
