### ISSUE TITLE
edgeHub is failting to authenticate modules on production after some time

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#3234]
Hi Team,
  We are facing issue on production gateway. After some days we have seen that edgeHub failed to authenticate modules suddenly and then we are loosing data because of this issue. Could you please let us know the reason for this and fix for this. 
This edge gateway was running since long time and then suddenly we have seen that it stops sending data. When we have gone through the logs then we have seen the below error and exactly after this error we are not getting data.
When we restart the gateway then we are able to receive data again ... So could you please let us know the reason and solution for this.. 

### Environment
OS: Windows
IoT Edge Runtime Version: 1.0.8
edgeAgent:1.0.8
edgeHub:1.0.8 
Certificate: We are using production ready certificate which expire date is next 10 years 

### Logs of edgeHub:
{"log":"\u003c6\u003e 2020-07-15 06:36:36.944 +02:00 [INF] - Reauthenticating connected clients\r\n","stream":"stdout","time":"2020-07-15T04:36:36.9453385Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:36.974 +02:00 [INF] - Error authenticating token for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream because the token is expired or could not be parsed\r\n","stream":"stdout","time":"2020-07-15T04:36:36.9763303Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:36.980 +02:00 [INF] - Credentials for client 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream are not valid.\r\n","stream":"stdout","time":"2020-07-15T04:36:36.9813273Z"}
{"log":"\u003c4\u003e 2020-07-15 06:36:36.981 +02:00 [WRN] - Reauthenticating client 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream failed, removing client connection\r\n","stream":"stdout","time":"2020-07-15T04:36:36.9813273Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:36.985 +02:00 [INF] - Unable to re-authenticate 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream, dropping client connection.\r\n","stream":"stdout","time":"2020-07-15T04:36:36.9853229Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:36.986 +02:00 [INF] - Closing AMQP device proxy for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream because no handler was registered.\r\n","stream":"stdout","time":"2020-07-15T04:36:36.9863228Z"}
{"log":"Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream.\r\n","stream":"stdout","time":"2020-07-15T04:36:36.9863228Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:37.117 +02:00 [INF] - Closing link Events for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream\r\n","stream":"stdout","time":"2020-07-15T04:36:37.1172768Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:37.117 +02:00 [INF] - Closing link Events for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream\r\n","stream":"stdout","time":"2020-07-15T04:36:37.1182732Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:37.400 +02:00 [INF] - Closing link TwinSending for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream\r\n","stream":"stdout","time":"2020-07-15T04:36:37.3998735Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:37.400 +02:00 [INF] - Closing link TwinReceiving for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream\r\n","stream":"stdout","time":"2020-07-15T04:36:37.3998735Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:37.401 +02:00 [INF] - Closing link MethodSending for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4018758Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:37.401 +02:00 [INF] - Closing link MethodReceiving for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4018758Z"}
{"log":"\u003c6\u003e 2020-07-15 06:36:37.402 +02:00 [INF] - Closing link ModuleMessages for 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4018758Z"}
{"log":"\u003c4\u003e 2020-07-15 06:36:37.404 +02:00 [WRN] - Error re-authenticating client 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream, closing the connection.\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"System.OperationCanceledException: The AMQP object sender30 is aborted.\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"   at Microsoft.Azure.Amqp.AmqpObject.EndClose(IAsyncResult result)\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"--- End of stack trace from previous location where exception was thrown ---\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.LinkHandler.CloseAsync(TimeSpan timeout) in C:\\agent\\_work\\4\\s\\edge-hub\\src\\Microsoft.Azure.Devices.Edge.Hub.Amqp\\linkhandlers\\LinkHandler.cs:line 81\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"   at Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionManager.RemoveDeviceConnection(ConnectedDevice device, Boolean removeCloudConnection) in C:\\agent\\_work\\4\\s\\edge-hub\\src\\Microsoft.Azure.Devices.Edge.Hub.Core\\ConnectionManager.cs:line 178\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"   at Microsoft.Azure.Devices.Edge.Hub.Core.ConnectionReauthenticator.ReauthenticateConnections(Object sender, ElapsedEventArgs elapsedEventArgs) in C:\\agent\\_work\\4\\s\\edge-hub\\src\\Microsoft.Azure.Devices.Edge.Hub.Core\\ConnectionReauthenticator.cs:line 93\r\n","stream":"stdout","time":"2020-07-15T04:36:37.4088712Z"}
{"log":"\u003c4\u003e 2020-07-15 06:36:41.805 +02:00 [WRN] - Module 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream is not connected\r\n","stream":"stdout","time":"2020-07-15T04:36:41.8059553Z"}
{"log":"\u003c4\u003e 2020-07-15 06:36:42.824 +02:00 [WRN] - Module 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream is not connected\r\n","stream":"stdout","time":"2020-07-15T04:36:42.8244101Z"}
{"log":"\u003c4\u003e 2020-07-15 06:36:44.941 +02:00 [WRN] - Module 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream is not connected\r\n","stream":"stdout","time":"2020-07-15T04:36:44.9412929Z"}
{"log":"\u003c4\u003e 2020-07-15 06:36:49.198 +02:00 [WRN] - Module 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream is not connected\r\n","stream":"stdout","time":"2020-07-15T04:36:49.1988481Z"}
{"log":"\u003c4\u003e 2020-07-15 06:36:57.817 +02:00 [WRN] - Module 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream is not connected\r\n","stream":"stdout","time":"2020-07-15T04:36:57.8176687Z"}
{"log":"\u003c4\u003e 2020-07-15 06:37:12.593 +02:00 [WRN] - Module 44c7b04c-d589-4618-aabc-c0cb78311615/iot-edge-module-upstream is not connected\r\n","stream":"stdout","time":"2020-07-15T04:37:12.5933466Z"}

**Comment by sachidanand** [comment]
iotedge check 
![image](https://user-images.githubusercontent.com/4133423/87670059-62bbe600-c76f-11ea-947e-006f074bf8d1.png)

**Comment by sachidanand** [comment]
Hi Team is there any update on this ....

**Comment by veyalla** [comment]
@sachidanand Apologies, but we don't have a long-term support release and only issue bug fixes in the latest release (1.0.9). Is it possible for you to update to the latest 1.0.9 version of iotedged, edge agent and edge hub, and attempt a repro?

**Comment by sachidanand** [comment]
> @sachidanand Apologies, but we don't have a long-term support release and only issue bug fixes in the latest release (1.0.9). Is it possible for you to update to the latest 1.0.9 version of iotedged, edge agent and edge hub, and attempt a repro?

@veyalla , It is not possible right now to upgrade with 1.0.9 as we have lots of gateways already in the plant and it is not easy process to upgrade them ..  Could you provide some workaround as of now for this issue ??

**Comment by veyalla** [comment]
This *might* be a cert expiry issue, but we don't have the ability in 1.0.8 to confirm via 'iotedge check'.

In case it is a cert issue, restarting iotedged will renew the quickstart certs if they are in use. If it doesn't help, I suggest opening a support ticket from Azure Portal as it will need more involved debug. 

**However, if any bug fixes are required they will be provided only for the latest release (1.0.9 as of now) they wont be ported for older releases**
