### ISSUE TITLE
Custom Python Module Not Reported by the Edge Device

### ISSUE THREAD

**Issue by ClarenceCHL** [Azure/iotedge#3257]
## Expected Behavior
I am trying to develop a real-time monitoring system based on IoT Edge. In other words, I am trying to deploy my static camera algorithm to the IoT Edge device such that I can read my camera data from the edge device.

## Current Behavior
when I try to deploy my custom module to my edge device, the portal shows me '406 -- The device is offline or not sending status reports' message. I tried to search the #406 error message online and none of the answers solved my issue.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a Linux Virtual Machine in Azure and use it as our edge device.
2. Using VS Code on Mac OS to develop python module.
3. Push and Build the custom python module and deploy it on our edge device (Linux Virtual Machine).
4. Right-click the edge device and select "Monitor the build-in endpoints" or view the logs on the virtual machine.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9.3 but 1.0.9.4 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 85 days (at 2020-10-15 03:16:51 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 18.04.4
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]:  Windows containers (Docker)

### Runtime Versions
* iotedged [run `iotedge version`]: iotedge 1.0.9.3
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: Client:
 Version:           19.03.12+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        0ed913b885c8919944a2e4c8d0b80a318a8dd48b
 Built:             Wed Jun 17 17:27:03 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by and-rewsmith** [comment]
Hi @ClarenceCH! Thanks for reporting this issue. I have followed your repro steps above and can see this issue in the portal. I would like to ask a few questions:
- Why do you mention monitoring the build in endpoint? This didn't seem to have any effect on the runtime response from the edge device, so I think I might be missing something.
- Other than not being able to see the correct runtime status of your edge device, does this have any other negative effects on your workflow? For me, VSCode accurately reports the edge device's runtime status even when the portal does not. I can also interact with the device successfully through the VSCode interfaces.
- Do you have any idea where the issue first occurs in your repro steps above. I will test again to try to narrow down where this happens, but just want to make sure we are on the same page

**Comment by darobs** [comment]
PR #3244 is fixing the `406` message masking the real status.

**Comment by ClarenceCHL** [comment]
> Hi @ClarenceCh! Thanks for reporting this issue. I have followed your repro steps above and can see this issue in the portal. I would like to ask a few questions:
> 
> * Why do you mention monitoring the build-in endpoint? This didn't seem to have any effect on the runtime response from the edge device, so I think I might be missing something.
> * Other than not being able to see the correct runtime status of your edge device, does this have any other negative effects on your workflow? For me, VSCode accurately reports the edge device's runtime status even when the portal does not. I can also interact with the device successfully through the VSCode interfaces.
> * Do you have any idea where the issue first occurs in your repro steps above. I will test again to try to narrow down where this happens, but just want to make sure we are on the same page

Hi Andrew. Thank you for your kind reply:)
1. It is true that the build-in endpoint does not have any effect on the runtime response. However, the build-in endpoint can monitor the real-time data send back from the deployed module device. I am using the built-in endpoint just to check if the connection is successful. Sadly, it only shows me 'Created partition receiver [0] for consumerGroup [$Default]' and 'Created partition receiver [1] for consumerGroup [$Default]' and nothing else.
2. For me, VS Code shows me that $edgehub and $edgeagent are connected and running. The custom module that I deployed, however, is showing the status of not connected. That is why I run the monitoring built-in endpoint to see if the device is sending data. I tried multiple times, but the result remained the same:(
3. I think step 3 is more likely the step that causing the issue since step 3 is the only step that is making the connection.

**Comment by and-rewsmith** [comment]
So in my reproduction of the problem I followed the steps above and could see the module connected via the VSCode interface. The reason I was getting 406 is because there was _another_ module in my deployment that was failing. 

In your scenario I think your python module has a deployment failure (thus does not show as connected via VSCode) and this results in 406.
