### ISSUE TITLE
IoT Edge 1.0.9.4 not available through apt-get

### ISSUE THREAD

**Issue by ThomasPe** [Azure/iotedge#3284]
## Expected Behavior
I got a notice from `iotedge check` that I'm not using the latest version which is 1.0.9.4. I updated the repository [as described here](https://docs.microsoft.com/de-de/azure/iot-edge/how-to-update-iot-edge), but I'm only seeing packages up til 1.0.9.3.
## Current Behavior
Tell us what happens instead of the expected behavior
Be able to update the runtime to 1.0.9.3 through apt-get
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. https://docs.microsoft.com/de-de/azure/iot-edge/how-to-update-iot-edge

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9.3 but 1.0.9.4 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.

```
</details>

### Device Information
* Host OS: [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9.3
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0
* Docker/Moby [run `docker version`]: 19.03.12+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by yophilav** [comment]
Hi @ThomasPe 

Thank you the issue. It looks like our current repo is not updated with the new fresh iotedged 1.0.9.4 artifacts. I'm working on it right now and I'll keep you update here once it's done. In the meantime, you could do a direct download and install the iotedged from our 1.0.9.4 release repo here: https://github.com/Azure/azure-iotedge/releases/tag/1.0.9.4
Sorry for the inconvenient.

**Comment by yophilav** [comment]
Alright, I the repo should be up-to-date for Linux AMD64. 
Thank you for your patience!

**Comment by ThomasPe** [comment]
looks good, thanks!
