### ISSUE TITLE
Sending Messages from Leaf or Downstream device not being handled by IoT Edge running at Transparent Gateway

### ISSUE THREAD

**Issue by chrislangston** [Azure/iotedge#331]
My Downstream Leaf device is using the NodeJS SDK to send Messages.  I'm unable to get the messages to flow through the IoT Edge Transparent Gateway.  If I Remove GatewayHostName from the connection string, the messages show up directly in IoT Hub.

## Expected Behavior
IoT Edge should receive message from downstream devices and route to IoT Hub and to other Modules running in IoT Edge that have properly routing rules configured.

I expect my Function Module to be triggered along with a generic/debugging route that sends all messages directly to IoT Hub to be invoked.

## Current Behavior
The IoT Edge is not receiving and/or processing messages from the Downstream Device.

## Steps to Reproduce
I have followed all the instruction for setting up a "Downstream Device" to send messages through IoT Edge running in Transparent Gateway.  

These are the instruction I've followed:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-linux

1.  IoT Edge Transparent Gateway VM is configured with all the certs properly setup, configured and verified.  I've been able to using the openssl tool as follows: 

openssl s_client -connect {my-gateway-machine-name-dns-name}.centralus.cloudapp.azure.com:8883 -CAfile /certs/certs/azure-iot-test-only.root.ca.cert.pem -showcerts

2.  Downstream device running on Linux VM with Certs installed and verified.  My connection string is as follows:

HostName={IoTHubName}.azure-devices.net;DeviceId=TC51_EdgeDownStreamDevice01;SharedAccessKey={My-Shared-Access-Key};GatewayHostName={my-gateway-machine-name-dns-name}.centralus.cloudapp.azure.com

a. I have verified I get a successful verification of the SSL cert using the openssl tool.
b. I'm using the the following in my downstream device for my connection using the NodeJS SDK

var client = DeviceClient.fromConnectionString(connectionString, Mqtt);

These are the routing rules:

"$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "sensorToBatteryDataFunctionModule": "FROM /messages/modules/tempSensor/outputs/temperatureOutput INTO BrokeredEndpoint(\"/modules/BatteryDataFunctionModule/inputs/input1\")",
          "debuggingRoute": "FROM /* WHERE NOT IS_DEFINED($connectionModuleId) INTO $upstream",
          "downstreamBatterySensorToBatteryDataFunctionInput1": "FROM /* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint(\"/modules/BatteryDataFunctionModule/inputs/input1\")",
          "BatteryDataFunctionModuleToIoTHub": "FROM /messages/modules/BatteryDataFunctionModule/outputs/* INTO $upstream",
          "MicrogatewayModuleToIoTHub": "FROM /messages/modules/MicrogatewayModule/outputs/* INTO $upstream"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    },

3.  In IoT Hub I have the "TC51_EdgeDownStreamDevice01" Downstream Device registered.
4.  In IoT Hub I have an IoTEdge Device configured.

### Device (Host) Operating System
(Ubuntu 16.04.5) for both VMs hosted in Azure.

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.1 (6e5e86dcf0c9a3732fc72a64d9ec9b0fcb2d6fad)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
Docker version 18.06.0-dev, build daf021fe

## Logs
edgeHub logs:  https://gist.github.com/chrislangston/49536ce00b734435d526f4ce140112fe

## Additional Information
If I use the sample out-of-the-box tempSensor Module running in IoT Edge, my "BatteryDataFunctionModule" is triggered.  However, my use case it to have 100's of Downstream devices sending their data through the IoT Edge device.

**Comment by dsajanice** [comment]
Could you please confirm that the device is able to send messages upstream via EdgeHub with a simple route "FROM /* INTO $upstream". Lets check that first.

**Comment by chrislangston** [comment]
@dsajanice  I built the most basic of .dotnet Core app following the Sample code referencing using "Application level" CA and everything works correctly.  My messages route through all the rules that I have specified in my edgeHub route rules.

Below is what I followed using the .NET app.
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-linux#application-level 

For the NodeJS app I was following the instructions for the "OS level" information.   When using the NodeJS SDK, do I need to do something similar to load the "azure-iot-test-only.root.ca.cert.pem" into some type of CA Trust store?

I will add the other Route rule you specified to see if that makes any difference for the NodeJS app.

**Comment by myagley** [comment]
Hi Chris. We have an example of a downstream device written in node.js here: https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/edge_downstream_device.js

The short answer is that the `azure-iot-test-only.root.ca.cert.pem` needs to be set as part of the client options. @mrohera is there anything else that needs to be done?

**Comment by chrislangston** [comment]
Thanks @myagley for that example.  Maybe that's what is why the messages are not going through. Let me add in those options and verify my results.  I'll make a suggestion to the documentation authors to make that a point for other apps besides just the .net core.

**Comment by veyalla** [comment]
I have been able to get a similar scenario to work by setting this environment variable: ` export NODE_EXTRA_CA_CERTS='replace-with-full-path-to-azure-iot-test-only.root.ca.cert.pem'`

**Comment by mrohera** [comment]
@myagley you are correct the azure-iot-test-only.root.ca.cert.pem would need to be set as part of the client issue.

In the sample, this file is passed in via this variable
// Path to the Edge "owner" root CA certificate
var edge_ca_cert_path = '[Path to Edge CA certificate]';

Another item needed is the the connection string:
//  "HostName=<iothub_host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>;GatewayHostName=<edge device hostname>"
var connectionString = '[Downstream device IoT Edge connection string]';

If these are set correctly, this works. 

The only thing to watch out for is the system time on the downstream device and the Edge device as well. This is critical to note and can fail quite subtly. Certificates have a validity period. One would want to ensure that when a device connects to the Edge the certificates are valid.

**Comment by chrislangston** [comment]
Thanks all for jumping in and responding to this issue, especially @myagley @mrohera and @veyalla .  

I'll make a recommendation to the doc team for the How-to articles to include NodeJS samples (or atleast a link to the sample listed in this thread) for connecting through an application.

I made the false assumption (bad idea on my part) based on the docs that I didn't have to be done at the 'Application level' if one followed the instructions mentioned as the 'OS level'
