### ISSUE TITLE
The daemon could not start up successfully: Could not initialize HSM

### ISSUE THREAD

**Issue by jaypaddy** [Azure/iotedge#3336]
I'm trying to put together DPS Group Enrollment. Following the docs [How to auto provision x509 certs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs) using the [demo certs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates).

I was once able to get the Edge to load the certs however it failed with 401002 status. So just to reconfirm i followed the steps right, i went ahead and re did the steps and have done twice now... I keep getting the following errors:
```
Aug 01 00:00:44 mythicalnuc systemd[1]: Stopped Azure IoT Edge daemon.
Aug 01 00:00:44 mythicalnuc systemd[1]: Started Azure IoT Edge daemon.
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Starting Azure IoT Edge Security Daemon
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Version - 1.0.9.3
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Using config file: /etc/iotedge/config.yaml
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Configuring certificates...
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Finished configuring provisioning environment variables and certificates.
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [INFO] - Initializing hsm...
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] - The daemon could not start up successfully: Could not initialize HSM
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] -         caused by: HSM failure
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] -         caused by: HSM Init failure: 48
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision_edge_…ain.cert.pem'
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision_edge_…home.key.pem'
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision_edge_…valid values:
Aug 01 00:00:44 mythicalnuc iotedged[11359]:   IOTEDGE_DEVICE_IDENTITY_CERT
Aug 01 00:00:44 mythicalnuc iotedged[11359]:   IOTEDGE_DEVICE_IDENTITY_PK
Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:hsm_client_crypto_…ror code 2025
Aug 01 00:00:44 mythicalnuc systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Aug 01 00:00:44 mythicalnuc systemd[1]: iotedge.service: Failed with result 'exit-code'.
Aug 01 00:00:44 mythicalnuc systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Aug 01 00:00:44 mythicalnuc systemd[1]: iotedge.service: Scheduled restart job, restart counter is at 10.
Aug 01 00:00:44 mythicalnuc systemd[1]: Stopped Azure IoT Edge daemon.
Aug 01 00:00:44 mythicalnuc systemd[1]: Dependency failed for Azure IoT Edge daemon.
Aug 01 00:00:44 mythicalnuc systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.

```
Config.yaml
```
# DPS X.509 provisioning configuration
provisioning:
  source: "dps"
  global_endpoint: "https://global.azure-devices-provisioning.net"
  scope_id: "XXXXXXXXX"
  attestation:
    method: "x509"
#    registration_id: "<OPTIONAL REGISTRATION ID. LEAVE COMMENTED OUT TO REGISTER WITH CN OF identity_cert>"
    identity_cert: "file:///iot-edge-device-identity-home-full-chain.cert.pem"
    identity_pk: "file:///iot-edge-device-identity-home.key.pem"

```
Certificates
a. Root CA Cert for DPS
b. Edge Identity Certificate and Key for IotEdge in the same directo as config.yaml
What am i missing?

**Comment by arsing** [comment]
>```
>Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision_edge_…ain.cert.pem'
>Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision_edge_…home.key.pem'
>Aug 01 00:00:44 mythicalnuc iotedged[11359]: 2020-08-01T00:00:44Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision_edge_…valid values:
>Aug 01 00:00:44 mythicalnuc iotedged[11359]:   IOTEDGE_DEVICE_IDENTITY_CERT
>Aug 01 00:00:44 mythicalnuc iotedged[11359]:   IOTEDGE_DEVICE_IDENTITY_PK
>```

Your logs are truncated (notice the `…`) which has obscured the useful parts of the errors. Run `journalctl -a` instead.

Based on what little they do show, it's likely to be from: https://github.com/Azure/iotedge/blob/4b17e98a6317185fee39c3edc78c23e8c0c64ddf/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c#L1769-L1770 and: https://github.com/Azure/iotedge/blob/4b17e98a6317185fee39c3edc78c23e8c0c64ddf/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c#L1789-L1790 So check that your cert PEM and/or private key PEM are actually at that path (directly under `/` as your URIs indicate), and that they're readable by the `iotedge` user that `iotedged` runs as.

**Comment by jaypaddy** [comment]
@arsing - Thank you. You showed me the path. I had a typo in my certificate name. Thank you for the help. Next time i will check for typos before i post.... Also scan through the part of the code that is throwing error, tot learn the code as well. 
The DPS enrollment worked out and my device enrolled. successfully.

Thank you @arsing

**Comment by jaypaddy** [comment]
Thank you to @arsing for helping me look closely. It was typo in the certificate name that resolved the issue.
