### ISSUE TITLE
Windows HSM library release is using emulator by default. (Should use real TPMs).

### ISSUE THREAD

**Issue by darobs** [Azure/iotedge#335]
Windows libiothsm.dll was being built with the default TPM setting "use_emulator" as ON. This was not the intent.  Debug versions of the library should be built with the emulator ON, and release version with this OFF. 

If your Windows system has a real TPM device which you would like to use, the current release will not work correctly - you'll see errors like this:
```
9/20/2018 1:10:13 PM info: iotedged -- Obtaining workload CA succeeded.
9/20/2018 1:10:14 PM error: edgelet_utils::logging -- A hardware hsm error occurred.
9/20/2018 1:10:14 PM error: edgelet_utils::logging --   caused by: HSM API returned an invalid null response
9/20/2018 1:10:14 PM info: iotedged::windows -- Stopped iotedged service.
```

This is set at build-time, so we have fixed the build, and the libiothsm.dll package will be set to use real TPMs in the next release.

## Steps to Reproduce

1.
2.
3.
4.

### Device (Host) Operating System

Windows
### Architecture

amd64
### Container Operating System

any
#### iotedged

1.0.1
#### Edge Agent

n/a
#### Edge Hub

n/a
## Additional Information

Note that if you build the edgelet project in Rust, the HSM library will be built to use the emulator when building debug, and use a TPM device in release mode, but this can be overridden by the "USE_EMULATOR" environment variable.  See edgelet/hsm-sys/build.rs in this repo for details.

**Comment by myagley** [comment]
This has been fixed in the 1.0.2 release.
