### ISSUE TITLE
edgeHub Module breaking connection Module to Module Communication

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#3352]
Hi Team,
   We have tested edge runtime 1.0.9.3 and we are facing one issue into it. edgeHub Module is breaking connection during module to module communication and then all the custom modules are stuck and failing. When we are restarting edgeHub then only it start communicating again.. 
We are using Windows container 
Edge Runtime 1.0.9.3 
edgeHub 1.0.9.3 
edgeAgent 1.0.9.3 

Regards
Sachidanand Sharma

**Comment by massand** [comment]
Please fill the issue template provided when you hit the New Issue button. Also, it would be worth [turning up the edgeHub logs](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#view-the-messages-going-through-the-iot-edge-hub) to view the communication between custom modules and the edgeHub module.

**Comment by rajatkumarsarma** [comment]
edgeHub logs in attached file:

[edgeHubDebugLog.txt](https://github.com/Azure/iotedge/files/5027272/edgeHubDebugLog.txt)

**Comment by sachidanand** [comment]
Hi Team,
   We have updated all the logs here .. So could you check it now ...

**Comment by massand** [comment]
I am looking at the logs, although I don't see any message transmissions I expect to see `[DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from `events. Could you gather the [support-bundle ](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#gather-debug-information-with-support-bundle-command)and provide that in an Azure support issue please? This seems specific to your environment and I would have to see a smaller repro to consider this a reproducible product issue.

**Comment by massand** [comment]
I have confirmed with the team that these logs are not displaying any message flows or error messages. Since you are on 1.0.9.3, I suggest using the support-bundle feature to capture the logs before EdgeHub is restarted and after all module-to-module communication has started failing. Also, we will be able to provide better assistance if the issue template is followed while filing issues. Thanks.
