### ISSUE TITLE
Default Container engine warning

### ISSUE THREAD

**Issue by mgardi85** [Azure/iotedge#3373]
Hi 
I am just starting on iotEdge so pardon if this is a very dumb question.

I have followed the  article listed at https://docs.microsoft.com/en-in/azure/iot-edge/quickstart-linux
to create my first hands-on attempt. The scenario went fine as what is documented.

However if I run the command `sudo iotedge check` , i see a warning that Container engine is not production supported.(Other warning made sense as i had not configured those). I have not installed anything apart from steps listed on the article so if moby engine is not configured then what is installed and what is configured. I tried to look at config.yaml at `/etc/iotedge/` , but that also did not offer any clue.

**Comment by veyalla** [comment]
Hi @mgardi85, thanks for trying IoT Edge and opening an issue!

The check result is a false positive (negative?) due to a recent change in versioning scheme used by Azure Moby. It is fixed in https://github.com/Azure/iotedge/pull/3342 which will available in the next release (1.0.10)

**Comment by massand** [comment]
Closing this issue since PR fix is in.
