### ISSUE TITLE
Transparent gateway does not relay the telemetry from the downstream device

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/iotedge#3380]
I have an IoT Edge configured as a Transparent Gateway, `DeviceID = iotedge-001`
and I have a downstream device connected using connection string and the modified hostname, `DeviceID = downstream-001`

The downstream device connects to the gateway and has no problem sending telemetry, but the telemetry is not visible in **IoT Explorer**.
Yet, I am able to send commands or change properties and these get propagated to the downstream device.

I added a module and created a route to catch the telemetry from `downstream-001` and send it to the `$upstream` and now I see the data in the **IoT Explorer** but under the `iotedge-001` device.

Is the expected behavior of transparent gateway to relay the telemetry? if that is the case it doesn't work in my current deployment. But maybe I did something wrong.

**Comment by uriel-kluk** [comment]
I added the following route and now the telemetry flows, my only suggestion is to add the route to the documentation:
`FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO $upstream`

**Comment by damonbarry** [comment]
> Is the expected behavior of transparent gateway to relay the telemetry?

Yes, that's the expected behavior, if you have a route set up to do it. The simplest route sends everything upstream, and is documented in our how-to guide for transparent gateway, [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway#deploy-edgehub-to-the-gateway).

**Comment by uriel-kluk** [comment]
Thanks for the response.

I read the guide one more time and nothing says that transparent gateway is
mutual exclusiva from messages to modules.

It doesn't explain either that you have to define the direct route into
upstream or data won't flow.

In my opinion, adding the temperature sample just confuses the illustration.

I get it that adding documentation requires a process but it helps improve
the content.

**Comment by damonbarry** [comment]
> I get it that adding documentation requires a process but it helps improve the content.

@uriel-kluk I agree, but this repo is for the source code. Which doc were you looking at?

**Comment by uriel-kluk** [comment]
I referred to the guide you highlighted in the email.
Thanks

**Comment by damonbarry** [comment]
Excellent. I opened MicrosoftDocs/azure-docs#60649.
