### ISSUE TITLE
Feature request: Downstream device in opaque gateways

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/iotedge#3383]
Extract message from the downstream device, transform it and send it to IoT Hub, but still retain the device source.

Example: A downstream device connects to the Gateway, Filter the message using a Stream Analytic Job, and then sends the message to the cloud.

As implemented today, if a message gets extracted by a module and then forwarded upstream, the system properties are attributed to the Edge device.

**Comment by damonbarry** [comment]
If a module A receives a message from a downstream device D and sends the message upstream, the upstream receiver will see that A sent the message. There's no way for A to send the message as D without D's credentials. Module a could choose to mark the message as having originated from D, but that would be up to the module. We don't impose a schema on the message properties.

@uriel-kluk Why do you want this behavior? There might be another way to get this information, depending on the scenario. For example, if you just need it for debugging or monitoring, [metrics](https://github.com/Azure/iotedge/blob/5971e5ed61f5c0320dfc9f9aa878831d3bc2570c/doc/BuiltInMetrics.md) might help.

**Comment by damonbarry** [comment]
Closing this issue. For feature requests, please visit https://aka.ms/iotedge-suggestion and upvote the feature if it already exists, or create a new one.
