### ISSUE TITLE
Manifest - never expire AzureAD unable to pull - unauthorized: authentication required

### ISSUE THREAD

**Issue by mathiash98** [Azure/iotedge#3388]
## Expected Behavior
Deployment Manifest should be able to use a never expire Azure AD password to login to Azure CR docker repository.

## Current Behavior
We made a new Azure AD user with never expire password and used this in our deployment manifest. This led to error messages:
```
Pulling image repository.azurecr.io/img:3322...
Could not pull image repository.azurecr.io/img:3322
caused by: Get https://repository.azurecr.io/v2/img/manifests/3322: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

We were able to login using `sudo docker login -u username repository.azurecr.io` with our password. And we were successfully able to pull our desired docker-image.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a Azure AD application with pull only rights to Azure Container Registry
2. Create a secret with never expire
3. Add clientId and secret to deplyment manifest
4. Deploy manifest and observe error when pulling images from registry

## Context (Environment)
Our system had been running for a year until our previous password expired on multiple ubuntu machines. Then we made a never expire password and observed this issue.

## Our solution:
Use a password which expires after 2 years.

We don't see any reason to why the pull only password need to expire? Expiration leads to a system that is doomed to fail at some point...

**Comment by damonbarry** [comment]
I just tried this scenario on Ubuntu, and it worked as expected. Here's what I did; maybe if there's a difference between our steps we can figure it out:

- Created a service principal following [these instructions](https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist#manage-access-to-your-container-registry):
```bash
# creates a password that expires in 1 year
az ad sp create-for-rbac --name 'http://{my service principal name}' --scopes '{resource id of my acr}' --role acrpull
```
- Using "Set Modules" in the portal, created a deployment that pulls images from my ACR. Added the acr info, including the application ID (username) and app password
- Started iotedged on my edge device, and confirmed that it successfully pulled and started the images (edgeAgent, edgeHub, tempSensor)
- Stopped iotedged
- Ran `docker system prune --all --volumes` on my edge device to make sure there are no cached images
- Ran `rm ~/.docker/config.json` to remove any cached docker credentials (just in case...I don't think iotedged uses this anyway)
- Went to my service principal in the portal, and added a new secret that never expires
- Deleted the old secret from my service principal
- Using "Set Modules" in the portal, I changed my ACR password to the never-expires secret value
- Started iotedged on my edge device, and confirmed that it successfully pulled and started the images (edgeAgent, edgeHub, tempSensor)

**Comment by damonbarry** [comment]
@mathiash98 What version of iotedged are you using?

Someone on the team just pointed me to #3206, which fixes a problem with passwords that contain `?` or `~`. This fix went into 1.0.9.4, but if you're using an earlier version you may have run into this.

**Comment by mathiash98** [comment]
Hmm, strange. we are using 1.0.9.2

Our current 2 year password includes "~" 

We first suspected special characters to be the reason, but we got to generate a password without special characters except "-", but this led to the same "authentication required" when having never expire password. When we added an invalid password with special characters we saw "wrong clientId and secret".

Then we did the same test with 1 year, 2 year and never expire.
Only never expire produces the "authentication required".

I can try this again with version 1.0.9.4

**Comment by ebertrams** [comment]
@mathiash98 , did using 1.0.9.4 solved the issue? Thanks

**Comment by ebertrams** [comment]
@mathiash98, did using 1.0.9.4 solved the issue? Can we close this issue? Thanks

**Comment by varunpuranik** [comment]
@mathiash98 - I will go ahead and close this issue. If you are still running into any problems with 1.0.9.4, please feel free to open a new issue, and provide us with all the relevant details and logs.
