### ISSUE TITLE
[Feature Request] Configure time when cleanup thread starts

### ISSUE THREAD

**Issue by koepalex** [Azure/iotedge#3394]
**Component:** edgeHub module

**Background:** The edgeHub stores by default IoT Hub messages in rocksdb which couldn't be sended. After 30min a clean up threads starts which is dropping messages from rocksdb where the TTL of messages is exceeded. The TTL of edgeHub can be controlled e.g. by IoT Hub -> Edge Devices -> Set Modules -> Environment Settings and has default of 2 hours. In our scenario based on high load, we need to reduce the TTL to e.g. 1 minute and have to wait 30mins (`20-30GB data in rocksdb`) until the clean up thread is starting. 

**Feature Request:** Start the clean up thread which is removing messages with exceeded TTL directly on start up or make the time to start the cleaning configurable.

**Comment by damonbarry** [comment]
@koepalex I'd recommend upvoting this feature request at https://aka.ms/iotedge-suggestion, and adding it if it doesn't already exist.

@varunpuranik Any workarounds or other information suggestions regarding this scenario?

**Comment by koepalex** [comment]
@damonbarry thank I've created the [feature-request](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/41136994-start-the-clean-up-thread-for-messages-that-exceed), if anyone else like to have this feature please upvote 👍

**Comment by varunpuranik** [comment]
Thanks @koepalex 
No, unfortunately there is no workaround for now.

**Comment by veyalla** [comment]
Thanks for filing the feature request!
