### ISSUE TITLE
edgeHub start up failed due to setcap not take effect in Container

### ISSUE THREAD

**Issue by allenzt** [Azure/iotedge#3401]
## Current Behavior and Tries
edgeHub start up failed due to the following log:
```
<4> 2020-08-13 06:48:19.215 +00:00 [WRN] - No XML encryptor configured. Key {8e90ad48-ac59-4a2d-a051-539e6fc2d5ca} may be persisted to storage in unencrypted form.
<6> 2020-08-13 06:48:19.280 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-8e90ad48-ac59-4a2d-a051-539e6fc2d5ca.xml"'.
<4> 2020-08-13 06:48:24.925 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<0> 2020-08-13 06:48:25.329 +00:00 [FTL] - Unable to start Kestrel.
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
<6> 2020-08-13 06:48:26.129 +00:00 [INF] - Stopping
<6> 2020-08-13 06:48:33.661 +00:00 [INF] - New token received on the Cbs link
```
- I do some attemps as the similar issue #671, #27 and #9 suggests. but no help.
- I run `docker  exec -it 53f6ddce6abd getcap /usr/share/dotnet/dotnet` but get nothing.I checked Dockerfile of edgeHub, it should run `setcap 'cap_net_bind_service=+ep' /usr/share/dotnet/dotnet`, but it seems does not take effect when I start container.
- when I run edgeHub with root user, setcap and getcap works well.
- I change `ASPNETCORE_URLS` to `http://+:8080` get the same failed log with above.
- I checked Dockerfile of edge

So, anyone can give me some advice or workaround? thanks in advance!

## Steps to Reproduce
1. run `./iotedged -c config.yaml`
2. wait edgeHub container to run

### 1. docker info
```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.1
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.14.77
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 482.5MiB
Name: VG710
ID: T5WJ:CDAH:VQB4:NDOT:JC4E:BKZH:ESCD:WPJ5:TW6V:TUPJ:GYQN:ZI5Z
Docker Root Dir: /tmp/app/docker/docker_root
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
### 2. kernel 3.14 config with `cat .config | grep -E "EXT4|SECURITY|ATTR"` 
```
"EXT4|SECURITY|ATTR"                                                                               
CONFIG_HAVE_DMA_ATTRS=y
CONFIG_OF_FLATTREE=y
CONFIG_OF_EARLY_FLATTREE=y
# CONFIG_RAID_ATTRS is not set
# CONFIG_SCSI_SPI_ATTRS is not set
# CONFIG_SCSI_FC_ATTRS is not set
# CONFIG_SCSI_ISCSI_ATTRS is not set
# CONFIG_SCSI_SAS_ATTRS is not set
# CONFIG_SCSI_SRP_ATTRS is not set
CONFIG_EXT4_FS=y
CONFIG_EXT4_USE_FOR_EXT23=y
CONFIG_EXT4_FS_POSIX_ACL=y
CONFIG_EXT4_FS_SECURITY=y
# CONFIG_EXT4_DEBUG is not set
CONFIG_TMPFS_XATTR=y
CONFIG_JFFS2_FS_XATTR=y
# CONFIG_JFFS2_FS_SECURITY is not set
# CONFIG_SQUASHFS_XATTR is not set
# CONFIG_SECURITY_DMESG_RESTRICT is not set
# CONFIG_SECURITY is not set
# CONFIG_SECURITYFS is not set
CONFIG_DEFAULT_SECURITY_DAC=y
CONFIG_DEFAULT_SECURITY=""
CONFIG_NLATTR=y

```

### Device Information
* Host OS : OpenWrt CC
* Architecture: arm32 
* Container OS: Linux containers 

### Runtime Versions
* iotedged :  1.0.9.3
* Edge Agent : 1.0.9.3-linux-arm32v7
* Edge Hub: 1.0.9.3-linux-arm32v7
* Docker/Moby : 18.09.1

**Comment by damonbarry** [comment]
@myagley @arsing Any ideas? This looks very much like #671 and #9, but you've already pointed that out. Are you able to demonstrate, independently of IoT Edge, that your kernel has the right features enabled to support `CAP_NET_BIND_SERVICE`? For example, can you run a simple apache server as a nonprivileged user (something like [this](https://cwiki.apache.org/confluence/display/HTTPD/NonRootPortBinding))?

**Comment by arsing** [comment]
Yes, I would assume your kernel either doesn't support that cap, or at least doesn't support it in containers. Try running any binary that binds to tcp/<low number port>, as damonbarry suggested. Something minimal like:

```sh
$ cp "$(which nc)" ./my-nc

$ sudo setcap 'cap_net_bind_service=+ep' "$PWD/my-nc"

$ ./my-nc -l -p 80   # Blocks instead of immediately failing
```

would be sufficient to demonstrate your kernel supports it.

If that works, try doing the same thing within a docker container of any OS.

**Comment by allenzt** [comment]
Thanks a lot! @arsing @damonbarry 

- I run edgeHub with root and nc works well.
![Selection_244](https://user-images.githubusercontent.com/36235312/90210376-613e1600-de20-11ea-8a9f-acfb94a01a5c.png)

- I run edgeHub with edgehubuser, but I can not install netcat. anything else can help to verify ?
![Selection_245](https://user-images.githubusercontent.com/36235312/90210513-b843eb00-de20-11ea-9f2f-f81e78477767.png)

**Comment by arsing** [comment]
>I run edgeHub with edgehubuser, but I can not install netcat. anything else can help to verify ?

You can exec into any container as root regardless of what its default user is, like `docker exec -it --user 0 edgeHub`

**Comment by arsing** [comment]
>I run edgeHub with root and nc works well.

The point of that exercise was to run `my-nc` without root, and to run it on the host, not in the container.

**Comment by allenzt** [comment]
@arsing Thanks for your excellent support! As you said, I test it on my host with non-root user, found setcap failed, do you have any idea about kernel config or filesystem?
- Following is my kernel config
[config.gz](https://github.com/Azure/iotedge/files/5073548/config.gz)
- Following is test log and output of mount.
```
/tmp/app $ setcap 'cap_net_bind_service=+ep' my-nc 
unable to set CAP_SETFCAP effective capability: Operation not permitted
/tmp/app $ mount
rootfs on / type rootfs (rw)
/dev/root on /oldroot type squashfs (ro,relatime)
tmpfs on /oldroot/rootmnt type tmpfs (rw,noatime)
overlayfs on / type overlayfs (rw,noatime,lowerdir=/,upperdir=/rootmnt/.upper)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
tmpfs on /vola type tmpfs (rw,nosuid,nodev,noatime)
cgroup on /sys/fs/cgroup type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,cpu,cpuacct,memory,devices,freezer,net_cls,blkio,perf_event,net_prio)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)
tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600,ptmxmode=000)
debugfs on /sys/kernel/debug type debugfs (rw,noatime)
/dev/mmcblk0p17 on /tmp/backups type ext4 (rw,relatime,data=ordered)
/dev/mmcblk0p21 on /tmp/app type ext4 (rw,relatime,data=ordered)
/dev/mmcblk0p18 on /tmp/pysdk1 type ext4 (rw,relatime,data=ordered)
/dev/mmcblk0p19 on /tmp/pysdk2 type ext4 (rw,relatime,data=ordered)
```

**Comment by arsing** [comment]
Again, please read https://github.com/Azure/iotedge/issues/3401#issuecomment-673720782 carefully. Notice how it tells you to use `sudo` to run `setcap`, but not `my-nc`. In other words, the point is to run `setcap` as root but `my-nc` as a regular user.

**Comment by allenzt** [comment]
Sorry for my negligence, I'm on weekend and will give you feedback ASAP with `sudo setcap 'cap_net_bind_service=+ep' "$PWD/my-nc"`. Thanks for your support!

**Comment by allenzt** [comment]
@arsing as you suggest, setcap command works well. anything else idea?
![image](https://user-images.githubusercontent.com/36235312/90365033-c8b1cb00-e097-11ea-8a1e-65a41936c105.png)

**Comment by arsing** [comment]
In https://github.com/Azure/iotedge/issues/3401#issuecomment-673720782 I asked you to run that test on the host and then in a container. Your image implies you ran it on the host. What about in a container?

**Comment by allenzt** [comment]
@arsing run commands in ubuntu:16.04 container, it shows as below:
![image](https://user-images.githubusercontent.com/36235312/90385375-a169f680-e0b5-11ea-9186-15029d87a85a.png)

**Comment by arsing** [comment]
Yes, so for whatever reason your setup does not allow caps to be set in containers, and presumably binaries with capabilities already set like our Edge Hub have their caps ignored.

One thing I noticed is that kernel 3.14 LTS stopped being supported by the kernel developers in 2016, so presumably your kernel is either out of support or OpenWRT is maintaining it for you. Regardless, maybe this kernel is old enough to support caps in userns; I don't know when the feature was committed and what kernel lines it was backported to. You'll probably want to get help for your distro specifically regarding that. (Note that OpenWRT is not in any of our tiers of supported distros.)

For resolving the Edge Hub issue specifically, you could either run it as root (which is of course undesirable in the general case), or to change its code to bind to different ports instead of 80 / 443.
