### ISSUE TITLE
Python / CV module on IoT Edge

### ISSUE THREAD

**Issue by vermaaditya** [Azure/iotedge#3403]
Hi Team, 

We are facing challenges as a part of the development process for deploying Computer Vision models in the form of Python custom modules on Azure IoT Edge. We are using Azure VM with Windows 10 Pro OS which supports IoT Edge runtime. 
As a part of the process we have initialized IoT edge and deployed SimulatedSensor module from market place. 

As the CV Models are developed in python, and we understand that Python modules are not supported on Windows Machine. We would like to know how can we achieve the deployment of custom CV modules in a Windows 10 OS. 
![image](https://user-images.githubusercontent.com/20763984/90167009-ba725f00-ddb8-11ea-90ec-9dee7dfe953b.png)

After this we are trying to switch the container OS to Linux. We are getting the following error, kindly help us in resolving this issue as Linux Containers on Windows is supported - 
![image](https://user-images.githubusercontent.com/20763984/90167609-83e91400-ddb9-11ea-8b68-992ef1efcd32.png)

Kindly let me know if that will function as per our requirement ? Though for dev and testing purpose. 
![image](https://user-images.githubusercontent.com/20763984/90167425-45535980-ddb9-11ea-9dbb-3f86507967ef.png)

Further to that, we are also trying to resolving the above scenario using WSL mentioned in the link - https://techcommunity.microsoft.com/t5/internet-of-things/linux-modules-with-azure-iot-edge-on-windows-10-iot-enterprise/ba-p/1407066. 

To enable WSL there is a required for Windows 10 Version to be on build # 19041, and for Azure IoT Edge it is - build 17763. Also confirm if we update the Windows 10 version to support WSL how the Azure IoT Edge will function? 

There are a lot of questions, will appreciate response on all of them.

**Comment by vermaaditya** [comment]
@ramkandimalla94 - FYI

**Comment by veyalla** [comment]
Hi @vermaaditya, are you following these steps: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-linux#prepare-the-container-engine?

Which version of Docker Desktop is installed?

**Comment by ramkandimalla94** [comment]
HI @veyalla me and @vermaaditya are from same team. 

I am using 2.1.0.5(40693) version

**Comment by damonbarry** [comment]
@vermaaditya @ramkandimalla94 
Regarding the 1st issue (error while running the install script): You report that you've installed docker, but the install script apparently can't find it. What is the output of the following PowerShell command?
```
Get-Command docker
```

Regarding the 2nd issue (WSL supported version), IoT Edge requires Windows build 17763 (LTS) for _Windows containers on Windows_. If you're doing Linux containers, you can use a newer Windows version.

**Comment by ramkandimalla94** [comment]
@damonbarry 
this is the output of Get-Command docker

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     docker.exe                                         19.3.12.0  C:\Program Files\Docker\Docker\resourc...

**Comment by veyalla** [comment]
Could you also share the output of `docker context ls`?

**Comment by ramkandimalla94** [comment]
output of docker context ls
![image](https://user-images.githubusercontent.com/37137053/90192446-9e82b380-dde0-11ea-8a46-8a3a27bdc4fe.png)

**Comment by damonbarry** [comment]
As shown, the install script failed while trying to execute the command `docker version --format "{{.Server.Os}}"`. Are you able to run this command directly from the command line, and does it return `linux`?

**Comment by ramkandimalla94** [comment]
![image](https://user-images.githubusercontent.com/37137053/90216133-60ef4c00-de1b-11ea-8278-94e83ea8f02a.png)

**Comment by vermaaditya** [comment]
@damonbarry @veyalla - if possible can we have a troubleshooting call over Teams?

**Comment by veyalla** [comment]
https://github.com/Azure/iotedge/issues/3403#issuecomment-673888714 indicates docker is not working correctly on the host. I suggest updating Docker Desktop or setting it up on a new VM (Windows version does not matter) and confirming basic 'docker run' functionality is working before installing IoT Edge.

**Comment by vermaaditya** [comment]
@veyalla - please confirm on the below 2 questions - 

- Is this the only way to Run Python Modules on Windows Devices?
- Is it recommended to deploy Linux Containers on Windows machine in Production environment? I see as per the documentation its not suggested and is crossed as well with the notes but would appreciate if you can reconfirm. 

This will help us in defining the strategy. Please suggest.

**Comment by ebertrams** [comment]
@veyalla , any updates on the above 2 questions? Thanks!

**Comment by veyalla** [comment]
This was communicated offline, including response here for closure.

>Is this the only way to Run Python Modules on Windows Devices?

Yes.

>Is it recommended to deploy Linux Containers on Windows machine in Production environment? I see as per the documentation its not suggested and is crossed as well with the notes but would appreciate if you can reconfirm.

Not currently. The guidance going forward is to leverage the first-party solution we're working towards which will preview later this year. [More details](https://channel9.msdn.com/Shows/Internet-of-Things-Show/Linux-modules-on-Windows-10-IoT-Enterprise)
