### ISSUE TITLE
Establishment of parent/child relationship between edge and leaf devices

### ISSUE THREAD

**Issue by sanjeev-magoo** [Azure/iotedge#3419]
@Question
Refer https://github.com/Azure/azure-iot-sdk-c/issues/1592 issue. 

Considering if child/leaf device has connectivity (one time connectivity for registration only) and is getting registered using DPS to IoTHub, also edge device is registered to same IoTHub. what is the MS recommendation on -

Establishment of parent/child relation between edge and leaf device (looking for non-manual solution). if we use "GatewayHostName" in IoTHub connection string from child/leaf device to connect to IoTHub, will it automatically establish the parent/child relation between edge and leaf device?

**Comment by veyalla** [comment]
>will it automatically establish the parent/child relation between edge and leaf device?

Unfortunately it will not, it needs to be explicitly established using the service SDK. 

Note, if the edge device has connectivity to IoT Hub **and** the downstream device is using a SAS token to authenticate, the edge hub can authenticate the leaf device even if it not designated as a child. But this doesn't work if the edge device is offline or certs are used for leaf device auth.

**Comment by sanjeev-magoo** [comment]
Thanks @veyalla. Actually we are trying to implement a transparent gateway use case using Azure IoT Edge. Our Edge device and leaf devices have their identity in the form of x509 certificates.
Leaf device will not have internet connectivity and it can reach to internet via edge device only. 

We are working on following approach-

1. First IoT edge device will get register to IoTHub using x509 certificate as its identity using DPS service. Once edge device get registered, it will have its IoTHub details.
2. Expose a REST interface for leaf devices (accessible in same network only) from edge module to get the IoTHub detail where leaf device should be registered as child of edge device.
3. Leaf device will fetch IoTHub details via interface defined in step #2.
4. Leaf device will initialize the HSM module (custom HSM module) to read the certificates and provide the device id/certificate to SDK.
5. Leaf device will use IoTHub connection (with x509 option) with GatewayHostName to register itself to IoTHub via edge gateway, provided gateway is in Online mode.
6. Once leaf device has been registered to IoTHub, leaf device can work even if edge device is offline.

any suggestion/feedback on above approach will be highly appreciated.

You mentioned- 
> But this doesn't work if the edge device is offline or certs are used for leaf device auth.

In our case, Edge device can be offline but should be able to authenticate the leaf devices using x509 certificate as identity if the leaf device is already registered to IoTHub. I understand registration of device is not possible if edge device is offline however if device is already registered, it can connect to edge IoTHub and can work in offline mode.
can you please validate above understanding.

**Comment by sanjeev-magoo** [comment]
We are able to connect leaf device to cloud IoTHub via edge IoTHub, where leaf device is using x509 certificate for authentication to edge IoTHub.

Leaf device is able to work in both online (edge is connected to cloud) and offline mode (i.e. when edge device is not connected to cloud IoTHub). In offline mode, Leaf device is able to send D2C messages that gets queued at edge device and when edge device gets connected to cloud IoTHub, these messages are sent/sync with cloud IoThub.
till now, this all is a working fine. 

The only issue where I am currently struggling is about leaf device registration. In the above mentioned case, we have registered leaf device using DPS service. i.e. leaf device need to have internet connectivity atleast during registration process.

Also confirmed at https://github.com/Azure/azure-iot-sdk-c/issues/1592, DPS service doesn't work via IoTEdge and device need to have direct connectivity to DPS.

If leaf device never has direct internet connectivity but can connect to internet via edge device only (edge device has internet connectivity), how do I register the leaf device using x509 certificate to IoTHub directly (without using DPS) using device SDK (not using service SDK)? Assuming device has its identity in the form of x509 certificate and has IoTHub details where it needs to be registered. is this possible with current device C SDK?

**Comment by sanjeev-magoo** [comment]
One of the solution is mentioned at https://github.com/Azure/iotedge/issues/3470.

**Comment by veyalla** [comment]
We are working a first-class solution for this but is not available yet. 

I recommend you add a new suggestion or upvote an existing one in the [feedback](https://feedback.azure.com/forums/907045-azure-iot-edge) portal.

**Comment by rajaggrawal** [comment]
@veyalla 

we are trying to connect leaf device with IoT-Edge using X.509 authentication.

our setup is as follows
Leaf-Device ---> IoTEdge As transparent GW ------> IoTHub

we are executing following steps.

1. edge device is provisioned(IoTEdge/agent/edgehub is up and running) 
2. Provisioned(Register) leaf Device to IoTHub though DPS service with X509 Certs.
3.  trying Connecting leaf device to IoTHub through iotedge.

**step 3 is failing with following error.**

IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED : IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED : IOTHUB_CLIENT_CONNECTION_NO_NETWORK.

**if i create device manually then everything works fine.**

could you please help me what could be issue when i connect a leaf device which is provisioned through DPS.
