### ISSUE TITLE
Create deployment within VSTS

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#345]
Hi there,

I'm trying to use: `az iot edge deployment create` and I'm getting an error to use 'az login' using a contributor service principal which has contributor permissions (with VSTS).

What is the best way to create a deployment using VSTS Azure Powershell?

**Comment by mrohera** [comment]
Hi @nhuurnink ,
I am not sure if you have had a chance to look at [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-ci-cd](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-ci-cd). This describes how one can setup their CI/CD pipeline and step 10 shows how to setup a deployment. Please take a look at that and let us know if this resolves your issue or feel free to come back with more questions.

Thanks.

FYI @shizn

**Comment by Noppey** [comment]
Hi,

I've read that indeed, but I can't use this since I'm using a custom way to build my docker images, as the standard way doesn't allow me to reference other projects.

Therefore I use azure cli, I got it working using an owner service principal with all permissions possible, but I would like to just use my default subscription service connection, but that doesn't seem to work.

**Comment by mrohera** [comment]
@iluican any pointers here perhaps?

**Comment by nhuurnink** [comment]
Hi, thanks!

Where can I track the progress of the support of contextPath in VSTS plugin?

**Comment by shizn** [comment]
Hi @nhuurnink. Since the source code of the VSTS plugin is not open-sourced (we are working on this) For now the only way to track is to watch the tutorial update -  https://docs.microsoft.com/en-us/azure/iot-edge/how-to-ci-cd. A rough ETA for the contextPath support is in 3 weeks.

**Comment by mrohera** [comment]
@nhuurnink if you think your questions have been answered by the referenced issue https://github.com/Azure/iotedge/issues/321, can we close this specific issue?

**Comment by Noppey** [comment]
Yes

Op wo 26 sep. 2018 20:13 schreef mrohera <notifications@github.com>:

**Comment by mrohera** [comment]
Thanks for your response.
