### ISSUE TITLE
Is it possible to register leaf device through iot edge device?

### ISSUE THREAD

**Issue by amit12cool** [Azure/iotedge#3470]
I have implemented Azure IoT edge transparent gateway use case and was able to register/provision my leaf device through DPS(x509).

But I want to register my leaf device on IoT Hub through IoT edge as my leaf devices doesn't have any Internet connection thus they can't access IoT Hub interface.

Or I'm open for other solutions too for my use case.

**Comment by dmolokanov** [comment]
Hi @amit12cool! I believe we don't support this scenario right now. We may have something in the future though.

For now, I can recommend you deploy an Edge module with any HTTP proxy(eg. HAProxy) on the Edge device. Then configure all DPS call going through the proxy.

**Comment by amit12cool** [comment]
Thanks @dmolokanov.Could you please guide me to any links to this implementation?

**Comment by dmolokanov** [comment]
I don't think we have something available. @veyalla, @ebertrams Do we have something publically available?

**Comment by amit12cool** [comment]
@dmolokanov can this be done? I have an express server running in edge module exposed through docker createOptions port mapping and it's accessed by leaf device through http call. So now dps call from leaf device goes through the express server.

**Comment by dmolokanov** [comment]
What do you refer to as an "express server"? I'm not very familiar with it. 
Yes, you are right you need a forward proxy on edge device to proxy calls to DPS. The exact implementation of the proxy server doesn't make any difference. The rest communication goes via edgehub.

**Comment by amit12cool** [comment]
Ok.Thanks.Im able to figure out the implementation now.
Express server is nodejs server listening for http calls on a port.

**Comment by dmolokanov** [comment]
We have a plan to make it easier to configure. Unfortunately, I don't know when it is going to happen. Stay tuned!
