### ISSUE TITLE
Feature Request: `createOptions` as a JSON object

### ISSUE THREAD

**Issue by gimmi** [Azure/iotedge#3498]
The `deployment.json` is a plain JSON file but the field `createOptions` into this file is instead a string containing JSON encoded object. This make `createOptions` field awkward to read and edit.

Please allow `createOptions` to be an object, so it will be possible to write this:

```json
"edgeHub": {
    "settings": {
        "createOptions": "{\"HostConfig\": {\"ExtraHosts\": [\"<parent_hostname>:<parent_IP_address>\"],\"PortBindings\": {\"5671\/tcp\": [{\"HostPort\": \"5671\"}],\"8883\/tcp\": [{\"HostPort\": \"8883\"}],\"443\/tcp\": [{\"HostPort\": \"443\"}]}}}"
    }
}
```

in this format:

```json
"edgeHub": {
    "settings": {
        "createOptions": {
            "HostConfig": {
                "ExtraHosts": ["<parent_hostname>:<parent_IP_address>"],
                "PortBindings": {
                    "5671/tcp": [{"HostPort": "5671"}],
                    "8883/tcp": [{"HostPort": "8883"}],
                    "443/tcp": [{"HostPort": "443"}]
                }
            }
        }
    }
}
```

**Comment by vipeller** [comment]
@gimmi We understand the problem and see how it is inconvenient. Currently the easiest way to define the settings in the format you proposed is through azure portal:

![image](https://user-images.githubusercontent.com/51135538/92266908-d5eef800-ee94-11ea-8993-950a908ade1c.png)

**Comment by gimmi** [comment]
Yes that UI is useful sometime to do some check, but my current workflow is basically storing the `deployment.json` in a version control and provision it via `az cli` so the portal is not where editing is normally taking place.

**Comment by micahl** [comment]
@gimmi would you open a feature request for this at [https://aka.ms/iotedge-suggestion](https://aka.ms/iotedge-suggestion)?

**Comment by gimmi** [comment]
For the past 3 days, unable to login:

![image](https://user-images.githubusercontent.com/6589/93663818-b77b2600-fa6a-11ea-9206-f79ecaa83690.png)

**Comment by danwickstrom** [comment]
If you are using visual studio code, you can edit the createOptions in the deployment template using json format and then right-click on it to generate the deployment manifest.

**Comment by micahl** [comment]
Thanks for calling that out, @danwickstrom.  @gimmi, I'm closing this github item, but if you'd still like this feature request to be considered in the future then to open an item on the feedback site try logging in with your Azure account.
