### ISSUE TITLE
Is there a way to fetch deviceScope of IoT edge device in module?

### ISSUE THREAD

**Issue by amit12cool** [Azure/iotedge#3539]
I have a custom module set up in which I need to get the deviceScope of the edgeDevice. I see IOTEDGE_MODULEGENERATIONID in edgeAgent and edgeHub env variables which is same as the values in deviceScope of IoT edge device twin. Is there a way I can get this IOTEDGE_MODULEGENERATIONID of edgeAgent or edgeHub in my custom module code? Or any other way you can suggest to get the deviceScope?

**Comment by varunpuranik** [comment]
Hi @amit12cool - Currently it is not possible to get the deviceScope of the IoT Edge device in the module. The IoT Edge runtime creates the modules on the device, and sets environment variables in each module that contains information about *that* module, such as the generation ID. Also, the deviceScope of the Edge device should be considered an opaque string, and not derived from the generation ID as such. 
Can you please describe your scenario that requires you to know the deviceScope of the IoT Edge device in a module?

**Comment by amit12cool** [comment]
Thanks @varunpuranik for your response.
My requirement is to set parent device relationship between edge device and leaf device.Seems like that is not possible on device sdk side so I decided to pass on the device scope to azure function which adds the device scope in initial twin used by DPS custom allocation during leaf device registration.
Now when the device created event for leaf device is received by my backend service I will use the device scope in message body to be passed in azure service ask registry update function.

Does that sound feasable? Or you have any other solution for my requirement.

**Comment by varunpuranik** [comment]
Yes, setting the deviceScope needs to be done using Service credentials. So your solution to use the backend (via the Azure function) to do that seems like the right approach to me.

**Comment by amit12cool** [comment]
@varunpuranik On device created event received on service side I do not get the deviceScope field in the event Data of edge device. Is this something by design or a issue?

**Comment by richma-ms** [comment]
@amit12cool please open a customer support ticket for EventHub vs EventGrid, they should be able to route you to the right folks with the answers.

In regards to what you're trying to do though, I know that the using the RegistryManager in C# SDK to get a Device will correctly populate both the `deviceScope` and `capabilities` fields.  So one thing you can potentially do is use the SDK to get the Device again when you receive the creation event on your backend.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager.getdeviceasync?view=azure-dotnet#Microsoft_Azure_Devices_RegistryManager_GetDeviceAsync_System_String_

**Comment by amit12cool** [comment]
@richma-ms Thanks for your reply. It is certainly an option that I'm already using as secondary solution. Since, making a call to registry will incur cost, I was of the opinion to get all the twin details in device created event. On the other side, by any chance could you let me know reason for not getting whole twin in created event be it C# or NodeJS.

For discrepancy in EventHub and EventGrid, I can raise a ticket.

**Comment by richma-ms** [comment]
Unfortunately I don't know offhand why the SDK implementations don't provide all the properties on the created event.  You can create new issues to ask the question over in the corresponding repo, and the SDK devs should be able to answer.
https://github.com/Azure/azure-iot-sdk-csharp/issues
https://github.com/Azure/azure-iot-sdk-node/issues

**Comment by jinyanghuang** [comment]
Hi I am using Java. I retrieve the deviceTwin like
```
SqlQuery sqlQuery = SqlQuery.createSqlQuery("*",SqlQuery.FromType.DEVICES,"capabilities.iotEdge=false",null);
Query twinQuery = twinClient.queryTwin(sqlQuery.getQuery());
DeviceTwinDevice d = twinClient.getNextDeviceTwin(twinQuery);
```
However, I did not see the deviceScope property

`https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.service.devicetwin.devicetwindevice?view=azure-java-stable`

> @amit12cool please open a customer support ticket for EventHub vs EventGrid, they should be able to route you to the right folks with the answers.
> 
> In regards to what you're trying to do though, I know that the using the RegistryManager in C# SDK to get a Device will correctly populate both the `deviceScope` and `capabilities` fields. So one thing you can potentially do is use the SDK to get the Device again when you receive the creation event on your backend.
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.registrymanager.getdeviceasync?view=azure-dotnet#Microsoft_Azure_Devices_RegistryManager_GetDeviceAsync_System_String_
