### ISSUE TITLE
Integrate ping direct method with e.g. AZ Portal "IoT Edge Runtime Response"

### ISSUE THREAD

**Issue by robinovi** [Azure/iotedge#3545]
Guessing this is the wrong place to ask this, but would then want guidance for where to receive an answer on this matter.

As of now there is not a reliable way to know when the device is offline by the following causes:

- Unexpected loss of internet connection
- Power outage

From v1.0.9 there was the introduction of the ping direct method ([source](https://sandervandevelde.wordpress.com/2020/03/24/towards-zero-touch-iot-edge-with-edgeagent-direct-methods/)).

Will this be incorporated in e.g. the Azure portal in some manner to cover these cases, instead of relying on the "IoT Edge Runtime Response" which implies "Last known status reported by this device’s IoT Edge runtime. ...".

I have FYI also added this as a [suggestion](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/41259016-remotely-detect-if-devices-iot-edge-software-are-o).

**Comment by ggjjj** [comment]
@veyalla Can you share any insights on this?

**Comment by veyalla** [comment]
There are no immediate plans that I am aware of, but we will certainly consider if your suggestion gets upvoted by the community. Thanks for filing it!
