### ISSUE TITLE
Windows 10 IoT Core Retail build fails during 'Initialize-IotEdge' with "VC Runtime must be installed before IoT Edge can be initialized."

### ISSUE THREAD

**Issue by robinmholt** [Azure/iotedge#3553]
If I switch my Windows 10 IoT Core FFU generation from a 'Testing' build to a 'Retail' build, I get the following error when I attempt to do the 'Initialize-IoTEdge ...' command:

"VC Runtime must be installed before IoT Edge can be initialized."

Any help on what I should include into the FFU image would be greatly appreciated.

**Comment by ggjjj** [comment]
Did you try installing VC Runtime? https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows#offline-or-specific-version-installation

**Comment by robinmholt** [comment]
Yes, but maybe I had the vc_redist.x64.exe in the wrong location.  I have the .ps1 and .cab file in c:\IoTEdge-Runtime\.  I have the vc_redist.x64.exe in that same directory.  Is that the correct location?  I am sourcing the .ps1 file with my current directory being different.  Should I have the vc_redist.x64.exe in that directory instead?

**Comment by robinmholt** [comment]
OK.  I finally looked a bit close at the log

```
Starting up at 09/15/2020 12:56:12

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, G...
Starting deploy-iotedge after waiting for boot to finish.
The container host is on supported build version 17763.
Skipping VC Runtime installation on IoT Core.
Using IoT Edge from C:\IoTEdge-Runtime\microsoft-azure-iotedge.cab
Committing changes, this will cause a reboot on success. If this is the first
time installation, run "Initialize-IoTEdge" after the reboot completes.
Starting up at 09/15/2020 12:58:41

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, G...
VC Runtime must be installed before IoT Edge can be initialized.
```

Please note the 'Skipping VC Runtime installation on IoT Core' message.  I assume that means it will not even attempt to install anything.

**Comment by ggjjj** [comment]
Looks like the script is not finding vc_redist.x64.exe and hence skipping the installation.  vc_redist.x64.exe can be in C:\IoTEdge-Runtime. Trying moving it where you are sourcing the script.

**Comment by robinmholt** [comment]
I don't think it has anything to do with where the file is located.  I have the file in `c:\IoTEdge-Runtime\vc_redist.x64.exe`.  The powershell function [Get-VcRuntime](https://github.com/Azure/iotedge/blob/a832716f1e23586914b4ddaf5907e9abf86b4004/scripts/windows/setup/IotEdgeSecurityDaemon.ps1#L1595) first checks if we are on Windows 10 IoT Core and prints that 'Skipping' message and then returns.

I also checked and $OfflineInstallationPath is used to locate the file and that is being specified at the Deploy-... stage as c:\IoTEdge-Runtime\.

**Comment by robinmholt** [comment]
OK.  I think I am onto something.  My Retail.xml FFU configuration file includes the IOT_CRT140 feature, but it does not seem to be getting included in the FFU generation.  I just copied the line over directly from the Testing to the Retail .xml file and this time the FFU generation did pick up the IOTUAP_CRT140 package.  Once the image is done building, I will try installing it and see if things progress further.

**Comment by robinmholt** [comment]
The solution was to properly configure the `IOT_CRT140` app feature.  Sorry for the noise.

**Comment by ggjjj** [comment]
Thanks for sharing the solution. Glad it worked out!
