### ISSUE TITLE
edgeAgent stuck in restart loop

### ISSUE THREAD

**Issue by rjoshi** [Azure/iotedge#3560]
`sudo systemctl status iotedge`

> sudo: unable to resolve host Husk-IOT-B00075
> ● iotedge.service - Azure IoT Edge daemon
>    Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
>    Active: active (running) since Tue 2020-09-15 07:03:05 BST; 1 day 23h ago
>      Docs: man:iotedged(8)
>  Main PID: 805 (iotedged)
>       CPU: 21.964s
>    CGroup: /system.slice/iotedge.service
>            └─805 /usr/bin/iotedged -c /etc/iotedge/config.yaml
> 
> Sep 17 06:05:30 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:05:30Z [INFO] - Starting module edgeAgent...
> Sep 17 06:05:32 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:05:32Z [INFO] - Successfully started module edgeAgent
> Sep 17 06:06:30 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:06:30Z [INFO] - Checking edge runtime status
> Sep 17 06:06:30 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:06:30Z [INFO] - Edge runtime status is failed, starting mod
> Sep 17 06:06:30 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:06:30Z [INFO] - Starting module edgeAgent...
> Sep 17 06:06:32 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:06:32Z [INFO] - Successfully started module edgeAgent
> Sep 17 06:07:30 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:07:30Z [INFO] - Checking edge runtime status
> Sep 17 06:07:30 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:07:30Z [INFO] - Edge runtime status is failed, starting mod
> Sep 17 06:07:30 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:07:30Z [INFO] - Starting module edgeAgent...
> Sep 17 06:07:32 Husk-IOT-B00075 iotedged[805]: 2020-09-17T05:07:32Z [INFO] - Successfully started module edgeAgent

`iotedge list`

> NAME             STATUS           DESCRIPTION               CONFIG
> edgeAgent        failed           Failed (1) 0 seconds ago  mcr.microsoft.com/azureiotedge-agent:1.0.9

`docker ps -a`

> CONTAINER ID        IMAGE                                        COMMAND                   CREATED             STATUS                          PORTS               NAMES
> 317599a9b963        mcr.microsoft.com/azureiotedge-agent:1.0.9   "/bin/sh -c 'echo \"$…"   9 days ago          Exited (1) 12 seconds ago                           edgeAgent

`iotedge logs edgeAgent`

> 2020-09-17 05:18:32 +00:00 Starting Edge Agent
> 2020-09-17 05:18:33.142 +00:00 Edge Agent Main()
> <6> 2020-09-17 05:18:34.377 +00:00 [INF] - Initializing Edge Agent.
> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 63
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.Main() in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 39
> ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 63<---
>

**Comment by ggjjj** [comment]
Can you post the exact version of edge Agent. It should be in the logs of edgeAgent

**Comment by rjoshi** [comment]
We have log rotation configured and have this in this error state to help us isolate the root cause. So the version string from logs has been rotated. Pasting the output of iotedge check instead 


Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9.2 but 1.0.9.5 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to Husk-Plant-Hub-S1.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the azure-iot-edge network could not connect to Husk-Plant-Hub-S1.azure-devices.net:8883

17 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
3 check(s) raised errors. Re-run with --verbose for more details.

**Comment by ggjjj** [comment]
Edge Agent is looking for versionInfo.json file and its missing so is the null exception. Could you check this when exec into the edgeAgent container and use the command `cat versionInfo.json` or list the files to check `versionInfo.json` exists or not.

**Comment by rjoshi** [comment]
How can I do that?

**Comment by ggjjj** [comment]
I noticed that you have set host mapping for edgeAgent. 
1. Can you check the permissions for the storage folder as mentioned here https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module#link-module-storage-to-device-storage 
2. Are you setting the `storageFolder` environment variable for edgeAgent?
3. Can you check if the error occurs even after reomoving the host binding and storageFolder?

**Comment by rjoshi** [comment]
Removed host mapping still no impact 

$ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                   CREATED             STATUS                    PORTS               NAMES
b94851b601d7        mcr.microsoft.com/azureiotedge-agent:1.0   "/bin/sh -c 'echo \"$…"   3 seconds ago       Up Less than a second                         edgeAgent

$ docker inspect -f '{{ .Mounts }}' b94851b601d7
[{bind  /var/run/iotedge/mgmt.sock /var/run/iotedge/mgmt.sock   true rprivate} {bind  /var/run/iotedge/workload.sock /var/run/iotedge/workload.sock   true rprivate}]

**Comment by rjoshi** [comment]
Update to 1.0.9.5 the problem is resolved with that. but not sure what went wrong last time.
