### ISSUE TITLE
EdgeHub limits on reported property update

### ISSUE THREAD

**Issue by davidguidali** [Azure/iotedge#3562]
I got the issue that if my module updates its reported properties frequently, those updates are not taken in account by the IoT hub. Since I got a S1 IoT Hub subscription i expect at least up to 10 updates / second to be possible. However, after some try-outs it seems that the limit is at around 1 update each 5 seconds.

I tried the following:

1. Created a test module
2. Connected to iotedgehubdev for debugging / testing
3. Created a device in IoT hub
4. Routed the twin update events to service bus
5. Subscribed to service bus
6. Send twin updates (reported property updates) to IoT hub and compared to messages received from the service bus

Result: With a delay of 5 seconds between the messages, 100 messages of 100 arrive at the service bus.
With a delay of 4 seconds, about 80 messages of 100 arrive at the service bus.
With the delay of 1 second, only 20 messages of 100 arrive at the service bus.

Is there a limit of twin updates on the edge hub? Or does it do kind of discarding messages from a certain period and only send the latest one to IoT hub?

Edit: I have done some tests now where I send twin updates directly to the IoT hub via device sdk. This works fine, I am able to send 50 messages / second. So the issue must be within the edge hub.

Edit #2: I have had a look into the code of the edge hub, it seems that there is a sync to cloud happening every 5 seconds. This is in line with my findings. So it seems only possible to update reported properties every 5 seconds. Is there a way to send reported property updates more often, other than sending it directly to iot hub?

**Comment by ggjjj** [comment]
Edge hub syncs the every 5 seconds and sends the data. It batches the twin updates and sends on every 5 second interval. It is per design and it is not meant to send the data every time when it a new one is available. Do you want to send reported properties whenever it is available and not restricted by the syncing of edge hub?

**Comment by davidguidali** [comment]
Hi @ggjjj 
Thank you very much for your answer. Yes, I want to send reported properties to the iot hub whenever they are available and not be restricted by the edge hub sync. 
I have implemented a custom state reporting of my modules, meaning each module sends states like "processing", "deconnecting", "connecting", "timout" etc. to the iot hub. These describe the state of the connection from the module to the data source (e.g. a OPCUA-server or MQTT-Broker), not to the iot hub. Now there may be some flickering scenarios where e.g. a module disconnects and re-connects to the data source in a short period of time. 
With the current implementation fo edge hub, those states are not reflected properly in my backend and make troubleshooting for me very difficult.

**Comment by ggjjj** [comment]
@davidguidali Apologize for the delay. 
From my understanding, the intention of using `twin` properties to know the state of the modules is not the right approach. Twin is not meant for that. If you want to make sure the states are properly reflected, then we suggest sending telemetry data from the module to IoT hub.

**Comment by davidguidali** [comment]
@ggjjj Thanks for your answer. Good to know that, maybe you should update your documentation because i couldn't find this behavior anywhere documented on the official docs.

**Comment by veyalla** [comment]
Thanks for the feedback. FYI @kgremban
