### ISSUE TITLE
Throttling IoT Edge Upload Speeds?

### ISSUE THREAD

**Issue by ejectbutton** [Azure/iotedge#3564]
Scenario: The Edge device has been unplugged from the internet for some time, and the queue for messages going upstream is quite full. We then decide to plug their device in to the internet to send information to the cloud. We also have a very poor internet connection. 

Here, my use case doesn't want my entire bandwidth to be taken by the edge device just by plugging it in. Is there any way to configure an upload speed for the device?

There's a similar concern with blob file uploads using the Edge Blob Module as described here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob

If we have the same scenario, and there are many files built up, I don't want the entire bandwidth to be taken by uploading theoretically dozens of files. Is there a way to limit this upload speed?

**Comment by ggjjj** [comment]
Currently there is no built in feature for this in IoT edge but we are working on a solution that leverages Linux Traffic control subsystem that will become public in couple of weeks.

**Comment by ggjjj** [comment]
Watch out for the blog in IoT techcommunity Blog https://techcommunity.microsoft.com/t5/internet-of-things/bg-p/IoTBlog and also checkout https://tldp.org/HOWTO/Traffic-Control-HOWTO/intro.html

**Comment by ebertrams** [comment]
@ejectbutton let us know if you d like to have an early access to the technical content that we will publish soon on how to use the LInux Traffic Control subsystem in the meantime. Tagging @arlotito as well. Thanks.

**Comment by ejectbutton** [comment]
@ebertrams That would be great! Thank you both for the update.
