### ISSUE TITLE
Downstream device registered to IoTHub through DPS does not connect to iotedge.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/iotedge#3578]
We are trying to connect leaf device with IoT-Edge using X.509 authentication.

Our setup is as follows

**Leaf-Device ---> IoTEdge As transparent GW ------> IoTHub**

We are executing following steps.

1. Edge device is provisioned(IoTEdge/agent/edgehub are up and running)
2. Provisioned(Register) leaf Device to IoTHub though DPS service with X509 Certs.
3. Trying Connecting leaf device to IoTHub through IoTEdge.

**Step 3 is failing with following error.**

IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED : IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL
IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED : IOTHUB_CLIENT_CONNECTION_NO_NETWORK.

**If i create device manually on IoTHub, then everything works fine.**

Could you please help me what could be issue when i connect a leaf device which is provisioned through DPS.

**Comment by amit12cool** [comment]
I'm also facing the same issue with NodeJs sdk. 

I have registered the edge device with DPS. It was registered successfully and edgeAgent and edgeHub modules ran correctly.

Now, when I registered my downstream device through DPS , the registration was successful using single enrollment group in DPS. 

Till now all good. Now,, When I connect my downstream device through edge gateway connection string ```HostName=amitedge;DeviceId=amidha-leaf-ca;x509=true``` I see error in edgeHub logs like below:-

```
<4> 2020-09-22 11:19:08.080 +00:00 [WRN] - Error authenticating certificate for amidha-leaf-ca because the certificate thumbprint did not match the primary or the secondary thumbprints.
<6> 2020-09-22 11:19:08.080 +00:00 [INF] - Unable to authenticate client amidha-leaf-ca with cached service identity amidha-leaf-ca. Resyncing service identity...
<4> 2020-09-22 11:19:08.990 +00:00 [WRN] - Error authenticating certificate for amidha-leaf-ca because the certificate thumbprint did not match the primary or the secondary thumbprints.
<6> 2020-09-22 11:19:08.990 +00:00 [INF] - Client amidha-leaf-ca in device scope not authenticated locally.
<3> 2020-09-22 11:19:08.990 +00:00 [ERR] - Unable to generate identity for clientId amidha-leaf-ca and username amitedge/amidha-leaf-ca/?api-version=2019-03-30&DeviceClientType=azure-iot-device%2F1.12.2%20(node%20v12.18.0%3B%20Ubuntu%2018.04%3B%20x64)
<6> 2020-09-22 11:19:08.990 +00:00 [INF] - ClientNotAuthenticated, Client ID: amidha-leaf-ca; Username: amitedge/amidha-leaf-ca/?api-version=2019-03-30&DeviceClientType=azure-iot-device%2F1.12.2%20(node%20v12.18.0%3B%20Ubuntu%2018.04%3B%20x64), 6a9c918a
```

My initial RCA is that DPS uses SHA256 thumbprint to register the device while the downstream device making the connection through the edge device is using sha1 thumbprint.

**Comment by richma-ms** [comment]
@amit12cool / @rajaggrawal what happens if you guys try to connect the provisioned leaf device to iothub directly?  Do you still get the same authentication error?

**Comment by amit12cool** [comment]
@richma-ms it works for me.

**Comment by richma-ms** [comment]
@amit12cool thanks, so somehow it's specific to the Edge gateway.  Can you turn on debug logging, collect a support bundle, and open a customer support ticket with it?  It'll get routed to the dev team for further investigation.

https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot

**Comment by veyalla** [comment]
When using DPS, are the leaf devices being set as children of the edge device?

**Comment by amit12cool** [comment]
Yes,I have set it manually from portal.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by rajaggrawal** [comment]
let me share analysis as well.

**Working scenario**
1. Create device manually on IoTHub using sha1 fingerprint
 2.Leaf-device connect with edge 
3. Leaf-device connects with iothub in non-edge use-case.

**non working scenario**
Tried creating a device using sha256 fingerprint as DPS also create device using SHA256 fingerprint. 

1. Create leaf-device manually on IoTHub using sha256 fingerprint
2. Leaf-device does not connect to iot-edge.
3. Leaf-device connect to iothub with  **non-edge use-case**.

**Comment by richma-ms** [comment]
@rajaggrawal, please open a ticket with your debug logs as well.  This way both Edge and DPS teams will get visibility into the issue and can help investigate.
