### ISSUE TITLE
Serialized object often stored as set of chinese characters

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#358]
Hi there,

I'm trying to send an object to my IoT hub. I use a custom endpoint in my IoT Hub to store the message in blob storage. Every message is persisted in my storage (every 2 minutes), and some messages are showing as avro format, but around 70% of my messages have content like:
扏Ūᐄ癡潲挮摯捥済汵ᙬ癡潲献档浥큡笄琢灹≥∺敲潣摲Ⱒ渢浡≥∺敍獳条≥∬慮敭灳捡≥∺楍牣獯景⹴穁牵⹥敄楶散≳∬楦汥獤㨢筛渢浡≥∺湅畱略摥楔敭瑕≣∬祴数㨢猢牴湩≧ⱽ≻慮敭㨢倢潲数瑲敩≳∬祴数㨢≻祴数㨢洢灡Ⱒ瘢污敵≳∺瑳楲杮索ⱽ≻慮敭㨢匢獹整偭潲数瑲敩≳∬祴数㨢≻祴数㨢洢灡Ⱒ瘢污敵≳∺瑳楲杮索ⱽ≻慮敭㨢䈢摯≹∬祴数㨢≛畮汬Ⱒ戢瑹獥崢嵽}⺜뤦䨲ざꮤ겟⋐䎖踂㠙〲㠱〭ⴹ㘲ご㨳㘵㈺⸶㌲〰〰娰฀挤湯敮瑣潩䑮癥捩䥥䑤䥍䐭瑡䍡汯敬瑣牯〭㈰唭牴捥瑨䔭睲湩挤湯敮瑣潩䵮摯汵䥥ᑤ獄牭敒摡牥挨湯敮瑣潩䅮瑵䵨瑥潨鱤笁猢潣数㨢洢摯汵≥∬祴数㨢猢獡Ⱒ椢獳敵≲∺潩桴扵Ⱒ愢捣灥楴杮灉楆瑬牥畒敬㨢畮汬㡽潣湮捥楴湯敄楶散敇敮慲楴湯摉㘤㘳㌷㘴〰ㄹㄹ㐸㤴ᘰ潣瑮湥呴灹⁥灁汰捩瑡潩⽮獪湯挞湯整瑮湅潣楤杮甊晴㠭攘煮敵敵呤浩㡥〲㠱〭ⴹ㘲ご㨳㘵㈺⸶㌲〰〰娰ȀᎼ≻獄牭敖獲潩呮灹≥㔺ⰰ吢浩獥慴灭㨢㈢㄰ⴸ㤰㈭吶㔰㔺㨶㌲Ⱒ䔢敬瑣楲楣祴敄楬敶敲䱤睯慔楲晦湉睋≨㈺㤱〮㈴∬汅捥牴捩瑩剹瑥牵敮䱤睯慔楲晦湉睋≨〺〮∬汅捥牴捩瑩䑹汥癩牥摥潎浲污慔楲晦湉睋≨㈺〸ㄮ∬汅捥牴捩瑩剹瑥牵敮乤牯慭呬牡晩䥦䭮桷㨢⸰ⰰ䔢敬瑣楲楣祴畃牲湥汴䑹汥癩牥摥湉睋㨢⸰㘱ⰱ䔢敬瑣楲楣祴畃牲湥汴剹瑥牵敮䥤䭮≷〺〮∬汅捥牴捩瑩啹敳䉤偹慨敳ㅌ湉睋㨢⸰㔱ⰸ䔢敬瑣楲楣祴獕摥祂桐獡䱥䤲䭮≷渺汵ⱬ䔢敬瑣楲楣祴獕摥祂桐獡䱥䤳䭮≷渺汵ⱬ䔢敬瑣楲楣祴敒畴湲摥祂桐獡䱥䤱䭮≷〺〮∬汅捥牴捩瑩剹瑥牵敮䉤偹慨敳㉌湉睋㨢畮汬∬汅捥牴捩瑩剹瑥牵敮䉤偹慨敳㍌湉睋㨢畮汬∬慔楲晦湉楤慣潴≲ㄺ∬潐敷䙲楡畬敲≳ㄺⰰ䰢湯偧睯牥慆汩牵獥㨢ⰵ倢睯牥慆汩牵䕥敶瑮≳嬺≻楔敭瑳浡≰∺〲㠱〭ⴱ㈲㉔㨱ㄵ㐺∵∬畄慲楴湯湉敓潣摮≳㐺㜱嵽∬畎扭牥晏潖瑬条卥条䥳偮慨敳ㅌ㨢ⰶ丢浵敢佲噦汯慴敧慓獧湉桐獡䱥∲〺∬畎扭牥晏潖瑬条卥条䥳偮慨敳㍌㨢ⰰ丢浵敢佲噦汯慴敧睓汥獬湉桐獡䱥∱ㄺ∬畎扭牥晏潖瑬条卥敷汬䥳偮慨敳㉌㨢ⰰ丢浵敢佲噦汯慴敧睓汥獬湉桐獡䱥∳〺∬湉瑳湡慴敮畯噳汯慴敧桐獡䱥∱㈺㤳㘮∬湉瑳湡慴敮畯噳汯慴敧桐獡䱥∲〺〮∬湉瑳湡慴敮畯噳汯慴敧桐獡䱥∳〺〮∬湉瑳湡慴敮畯䅳灭牥健慨敳ㅌ㨢ⰱ䤢獮慴瑮湡潥獵流数敲桐獡䱥∲〺∬湉瑳湡慴敮畯䅳灭牥健慨敳㍌㨢ⰰ䔢瑸慲敄楶散祔数㨢ⰳ䔢瑸慲敄楶散摉㨢㐢㌷㌰㌰㌳㌹㌰㌰㌱㌸㌰㌷㌱㌱㌱㌲㌱∸∬硅牴䑡癥捩呥浩獥慴灭㨢㈢㄰ⴸ㤰㈭吶㔰㔺㨵㔰Ⱒ䔢瑸慲敄楶散慖畬≥㌺⸰㈰ⰲ倢潲散獳摥㨢慦獬絥⺜뤦䨲ざꮤ겟⋐䎖

It feels that this is happening kind of in batches (like 4 times Chinese, 2 times avro, 6 times Chinese, 4 times Avro, etc...), but I have no clue where this is coming from.

I use these initialization settings:

```
public async Task Initialize()
        {
            var setting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            ITransportSettings[] settings = { setting };

            // Open a connection to the Edge runtime
            ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await ioTHubModuleClient.OpenAsync();
        }
```

where ioTHubModuleClient is an instance variable of my ObjectToHubSender class. The Send method in this same class is:

```
public async Task Send(object input)
        {
            await semaphoreSlim.WaitAsync(); // async locking mechanism
            try
            {
                if (counter % 120 == 0) // send every 2 minutes
                {
                    var bytes = ToJsonByteArray(input);

                    using (var message = new Message(bytes)
                    {
                        ContentEncoding = "utf-8",
                        ContentType = "Application/json"
                    }) {
                        await ioTHubModuleClient.SendEventAsync("output1", message);
                    }
                    
                    Console.WriteLine($"Message {(counter / 120) + 1} sent to hub");
                }

                counter++;
            }
            finally
            {
                semaphoreSlim.Release();
            }
        }
```

```
 private static byte[] ToJsonByteArray(object obj)
        {
            var json = JsonConvert.SerializeObject(obj);
            byte[] messageBytes = Encoding.UTF8.GetBytes(json);

            return messageBytes;
        }
```

The Send method is called by an event handler which is an async void method.

**Comment by mrohera** [comment]
@ash2017 can you look into this or tag someone who could assist with this IoT Hub query?

**Comment by mrohera** [comment]
@markrad can you please help respond or tag someone who could assist with this IoT Hub query?

**Comment by mrohera** [comment]
@nhuurnink to better assist you with your issue, I would suggest you file a ticket for the IoT Hub service. This github repo is specifically for the IoT Edge and what you are reporting is an IoT Hub related issue.

To file a ticket, open up the portal and navigate to your IoT Hub --> Click Help (its the '?' icon on the right) --> click Help + Support button --> New support request.

I will close this issue for now but feel free to come back with any questions.

**Comment by nhuurnink** [comment]
As manishgargiot was looking into this: Did you find anything? If your investigation is over and with no results, I'm fine to close this issue.

**Comment by itsmaryann** [comment]
I also have the same issue. Some files get stored with Chinese characters and some are okay with English strings.

**Comment by ash2017** [comment]
Thank you for sharing this issue. We are investigating.
