### ISSUE TITLE
edgeAgent cannot send changes in RunTime Settings to module

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/iotedge#3581]
## Expected Behavior
Should be able to suppress the iotedge check warning: 
```
â¼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
```
## Current Behavior
Warning always appears, even if attempts to reconfigure the Runtime Settings of edgeAdmin is done.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. In the Azure portal Runtime Settings screen, set the edgeAgent 'storageFolder' env variable to /tmp (as a test).  
2. In the Azure portal Runtime Settings screen, set the edgeAgent Create Options:
```
                "HostConfig": {
                    "Binds":["/etc/iotedge/storage/:/iotedge/storage/"]
                }

```
Save in portal.
3. `docker rm -f edgeAgent`
4. `docker inspect edgeAgent`
There is no 'storageFolder' settings in the container configuration.  And no directory bindings, so the iotedge check warning still appears and still references /tmp/edgeAgent.

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: PI4 Raspian Buster
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9.4
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.0
* Docker/Moby [run `docker version`]: 3.0.13+azure

**Comment by richma-ms** [comment]
@RotateAt60MPH I was able to repro the same behavior that you saw with 1.0.9.4, but it seems to be fixed with the 1.0.10-rc1 build.  Can you try the newer build and see if it's still a problem?

**Comment by RotateAt60MPH** [comment]
@richma-ms What's the best way to me to get 1.0.10-rc1?  Is it available in an 'apt' package?  It's a PI4 so it's really problematic to download and build from source.

**Comment by veyalla** [comment]
@RotateAt60MPH Yes, this is a known issue in edgeAgent versions prior to 1.0.10. Due to design limitations, settings for the Edge Agent do not take affect unless its image is also changed. If you are using the default Edge Agent settings, change the image to use a specific tag along with the environment variables above, e.g. `mcr.microsoft.com/azureiotedge-agent:1.0.9.5`.

RC install instructions:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge#update-to-a-release-candidate-version

**Comment by richma-ms** [comment]
@RotateAt60MPH correction to what I said earlier, RC1 does not have the fix either, but RC2 does.

mcr.microsoft.com/azureiotedge-agent:1.0.10-rc2
