### ISSUE TITLE
SecurityOpt length limitation

### ISSUE THREAD

**Issue by danwickstrom** [Azure/iotedge#3601]
## Expected Behavior
Tell us what should happen
I have a module for which I need to define a Seccomp security profile, but there seems to be a string length limitation on the string passed to the createOptions - limit is 4K.  From docker command line, it would be done as follows:

$ docker run --rm \
             -it \
             --security-opt seccomp=/path/to/seccomp/profile.json \
             hello-world

## Current Behavior
Tell us what happens instead of the expected behavior

For IoT Edge, I don't have access to the docker command line and I can't pass the options as a file, so instead I took the contents of the json structure in the profile.json file and passed it as a string in the deployment manifest createOptions SecurityOpt setting.

"HostConfig": {
                  "SecurityOpt": ["seccomp={
    \"defaultAction\": \"SCMP_ACT_ERRNO\",
    \"syscalls\": [
        {
            \"name\": \"accept\",
            \"action\": "SCMP_ACT_ALLOW",
            \"args\": null
        },
        {
            \"name\": \"accept4\",
            \"action\": "SCMP_ACT_ALLOW",
            \"args\": null
        }, ... 

rest elided 

],

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Configure deployment template HostConfig.SecurityOpt as a string to whitelist allowed syscalls
2. In visual studio code right-click on deployment template and select option to generate deployment manifest
3. Error message is returned indicating that createOptions length is limited to 4K

### Device Information
* Host OS: Ubuntu 20.04: 
* Architecture: amd64
* Container OS: Linux containers: debian:buster-slim

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9.4
* Edge Agent [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-agent:1.0
* Edge Hub [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-hub:1.0
* Docker/Moby [run `docker version`]: 3.0.13+azure

**Comment by richma-ms** [comment]
The deployment manifest is sent to the Edge device via the EdgeAgent's module twin, and there's a size-limit on the twin document itself.  I'll look into whether the 4K strlen limit is intentional, but in the mean time, is it viable for you to put the JSON file on the device?  From there dockerd should be able to read it when deploying the module container.

**Comment by danwickstrom** [comment]
I already tried doing that, but the logs for edgeAgent complained about parsing the pathname for the file.  It didn't seem to like the  '/''s in the pathname for the file.

**Comment by richma-ms** [comment]
Can you provide a snippet from edgeAgent logs where it complains about parsing the pathname?

**Comment by danwickstrom** [comment]
Here's a log snipped from edgeAgent:

	caused by: Could not start module HMI
	caused by: Decoding seccomp profile failed: invalid character '/' looking for beginning of value, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 210
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 127
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2019_11_05.ModuleManagementHttpClient.StartModuleAsync(String name) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs:line 165
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 60
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 87<---

And the inspect command for SecurityOpt:

$ docker inspect -f '{{ .HostConfig.SecurityOpt }}' HMI
[seccomp=/home/username/seccomp-profile.json]

**Comment by richma-ms** [comment]
That error comes from docker daemon.  I did a little digging, and it seems that Docker API to create containers doesn't allow the caller to just specify an absolute path for the seccomp.  To have this working, EdgeAgent would need to read the file from disk and inline the payload when calling into Docker.  So for now just putting the file path is not an option unfortunately.

As for the max size error you're hitting, I looked through the code and it seems that the runtime enforces the max size to be 512 * 100 bytes.  So I suspect that the 4K limit you're seeing is coming from the VS code extension as opposed to Edge.  When you tried to inline the JSON payload, could you tell whether the manifest was actually sent to the Edge device (or was it stopped short by VS code)?  If you have RuntimeLogLevel=debug, EdgeAgent should log out the `createOptions` section whenever a new manifest is applied.  If the limitation is indeed coming from VS code, you may be able to work around it by using the CLI to push the deployment instead.

Another potential workaround is to breakup your JSON payload into different `createOptions` sections.  When EdgeAgent deserializes the deployment manifest, `createOptions` can be read from multiple ordered chunks.  So you have the first portion in `createOptions`, the second in `createOptions01`, then `createOptions02`, etc

**Comment by danwickstrom** [comment]
It seems like the limitation might be in VS code.  With a shorter profile using multiple createOptions0x, the deployment works from VS code.  When the createOptions total size (even with multiple createOptions0x) is larger than 4k, the deployment fails.  However, doing a manual deployment from the command line does seem to work - container starts and createOptions on target using docker inspect seem to show the correct seccomp settings.  Note, I had to manually generate the deployment manifest, since vs code wouldn't do it.

**Comment by danwickstrom** [comment]
I've written a script to insert the seccomp profile into the deployment manifest, and I've tested it using cli to deploy, so as workaround it's ok.  It would be nice to have an update to vs code to fix this.

**Comment by richma-ms** [comment]
Thanks for the update, I'll internally pass the issue along to the tooling team.

**Comment by micahl** [comment]
@danwickstrom thanks for reporting this.  Will you open an issue for the limitation you hit with the VS Code IoT Edge extension on its repo?  [vscode-azure-iot-edge](https://github.com/microsoft/vscode-azure-iot-edge/issues)

@marianan as fyi
