### ISSUE TITLE
edgeAgent GetModuleLogs direct method error using 'since' filter

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/iotedge#3602]
## Expected Behavior
Successfully get module logs

## Current Behavior
Error message:
`{"status":500,"payload":{"message":"Stream finished but there was a truncated final frame in the buffer"}}`

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create an Edge Device to an IoT Hub.
2. Add the SimulatedTemperatureSensor module
3. In the portal, invoke the edgeAgent 'GetModuleLogs' direct method with the following payload:
```
{    
    "schemaVersion": "1.0",
    "items": [
        {
            "id": "edgeAgent", 
            "filter": {
                "tail": "10"
            }
        }
    ],
    "contentType": "text"
}
```
The call is successful.  I see current log messages (within last few minutes).
4. In the portal, invoke the same edgeAgent 'GetModuleLogs' direct method with the following payload:
```
{    
    "schemaVersion": "1.0",
    "items": [
        {
            "id": "edgeAgent", 
            "filter": {
                "since": "15m"
            }
        }
    ],
    "contentType": "text"
}
```
The call fails with the error above.

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: RPI4 Raspian Buster
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9.4
* Edge Agent [image tag (e.g. 1.0.0)]: azureiotedge-agent:1.0.10-rc2
* Edge Hub [image tag (e.g. 1.0.0)]: azureiotedge-hub:1.0

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

**Comment by lfitchett** [comment]
Thank you for reporting. I will investigate.

**Comment by lfitchett** [comment]
I have tried this on a rpi4 and was unable to replicate. Do you see this error consistently or is it periodic?

**Comment by veyalla** [comment]
did you use `1.0.9.4` iotedged as OP has?

**Comment by RotateAt60MPH** [comment]
@veyalla The problem is not sporatic.  Happens every time.

Here's my versions again.

```
NAME                        STATUS           DESCRIPTION      CONFIG
SimulatedTemperatureSensor  running          Up 5 days        mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent                   running          Up 5 days        mcr.microsoft.com/azureiotedge-agent:1.0.10-rc2
edgeHub                     running          Up 5 days        mcr.microsoft.com/azureiotedge-hub:1.0
pi@rpi4edgedev:~ $ iotedge version
iotedge 1.0.9.4
pi@rpi4edgedev:~ $

```
Just re-verified: the results were consistent with the OP.

**Comment by veyalla** [comment]
Sorry, that question was meant for Lee.

Can you try with 1.0.10-rc2 version of iotedged?

**Comment by RotateAt60MPH** [comment]
@veyalla  Something I forgot to mention, which may be relevant: the Edge Agent is configured save it's log to the host (in this case, a RPI4).  Here is the runtime settings I am using for the Edge Agent:

```
{
  "HostConfig": {
    "Binds": [
      "/etc/iotedge/storage/:/iotedge/storage/"
    ]
  }
}
```

I have verified that the host directory is 'active' with log files being created and appended to normally.

**Comment by veyalla** [comment]
@RotateAt60MPH Can you try with 1.0.10-rc2 version of iotedged?

**Comment by RotateAt60MPH** [comment]
@veyalla is it in a apt-get package at this point?  Possible to I get the rc2 without rebuilding from scratch?

**Comment by lfitchett** [comment]
You can download the packages here: https://github.com/Azure/azure-iotedge/releases

**Comment by veyalla** [comment]
...and here are the instructions: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux#install-runtime-using-release-assets

**Comment by RotateAt60MPH** [comment]
@lfitchett Downloaded **iotedge_1.0.10.rc2-1_ubuntu16.04_armhf.deb** and **libiothsm-std_1.0.10.rc2-1_ubuntu16.04_armhf.deb**.  Problem with dependancies:

iotedge install attempt:

```
pi@rpi4edgedev:~ $ sudo dpkg -i iotedge_1.0.10.rc2-1_ubuntu16.04_armhf.deb
(Reading database ... 182523 files and directories currently installed.)
Preparing to unpack iotedge_1.0.10.rc2-1_ubuntu16.04_armhf.deb ...
The user `iotedge' is already a member of `docker'.
Unpacking iotedge (1.0.10~rc2-1) over (1.0.10~rc2-1) ...
dpkg: dependency problems prevent configuration of iotedge:
 iotedge depends on libssl1.0.0 (>= 1.0.2~beta3); however:
  Package libssl1.0.0 is not installed.
 iotedge depends on libiothsm-std (= 1.0.10~rc2-1); however:
  Package libiothsm-std is not configured yet.

dpkg: error processing package iotedge (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (241-7~deb10u4+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 iotedge
```

libiohsm install attempt:

```
pi@rpi4edgedev:~ $ sudo dpkg -i libiothsm-std_1.0.10.rc2-1_ubuntu16.04_armhf.deb
(Reading database ... 182523 files and directories currently installed.)
Preparing to unpack libiothsm-std_1.0.10.rc2-1_ubuntu16.04_armhf.deb ...
Unpacking libiothsm-std (1.0.10~rc2-1) over (1.0.10~rc2-1) ...
dpkg: dependency problems prevent configuration of libiothsm-std:
 libiothsm-std depends on libssl1.0.0; however:
  Package libssl1.0.0 is not installed.

dpkg: error processing package libiothsm-std (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 libiothsm-std

```

SSL installs:

```
pi@rpi4edgedev:~ $ apt list --installed | grep ssl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libssl-dev/testing,now 1.1.1d-0+deb10u3+rpt1 armhf [installed,automatic]
libssl1.0.2/stable,now 1.0.2q-2 armhf [installed,automatic]
libssl1.1/testing,now 1.1.1d-0+deb10u3+rpt1 armhf [installed]

```

The current level(s) of libssl is from a previous out-of-the-box install of iotedge.  Do not think it is possible to install an older version of libssl....?

**Comment by RotateAt60MPH** [comment]
I just noticed in my previous post - I downloaded the Ubuntu arm version, which I don't think is compatible with Raspian Buster, so I'm not able to test rc2.

**Comment by veyalla** [comment]
Please try the Debian 9 version: https://github.com/Azure/azure-iotedge/releases/download/1.0.10-rc2/iotedge_1.0.10.rc2-1_debian9_armhf.deb (and the corresponding hsmlib).

**Comment by RotateAt60MPH** [comment]
@veyalla  I will be testing this this week.

**Comment by veyalla** [comment]
Any update here? 1.0.10 is now released.

**Comment by veyalla** [comment]
Please re-open if still an issue with 1.0.10

**Comment by rtheil** [comment]
Just a note here. This is happening on 1.1.15. I changed the since/until values to unix timestamps and it works fine. Does not work with rfc3339 dates
