### ISSUE TITLE
Missing packages on https://packages.microsoft.com/

### ISSUE THREAD

**Issue by boppbo** [Azure/iotedge#3619]
## Expected Behavior
Expect to be able to install and update iotedge by package manager

## Current Behavior
I have to download and install deb manually

## Context (Environment)
According to https://docs.microsoft.com/en-us/azure/iot-edge/support I should be able to use Debian 9 packages for Ubuntu 2004. But the multiarch package source doesn't contain arm64 packages.
https://packages.microsoft.com/debian/9/multiarch/
https://packages.microsoft.com/debian/9/multiarch/prod/pool/main/i/iotedge/

I know Ubuntu 20.04 isn't tier-1 but I would appreciate if you could copy the packages in its corresponding source, too. 
https://packages.microsoft.com/ubuntu/20.04/

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 20.04
* Architecture [e.g. amd64, arm32, arm64]: arm64

**Comment by veyalla** [comment]
Please add this request as a new suggestion (or upvote an existing one) at https://aka.ms/iotedge-suggestion

**Comment by boppbo** [comment]
@veyalla Maybe I would if I could:

Request Id: 25019714-e60c-4722-b39a-e8b4b0311800
Correlation Id: fe320cb9-2876-4785-b4d3-e1097a53067a
Timestamp: 2020-09-29T14:48:33Z
Message: AADSTS50020: User account '<removed>' from identity provider 'live.com' does not exist in tenant 'UserVoice, Inc.' and cannot access the application '91a42e81-999b-4cf1-aa36-bb33f25ff53b'(windowsazure.uservoice.com) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by veyalla** [comment]
Please try using your Azure account
