### ISSUE TITLE
yocto sumo builds now fail for release 1.0.6

### ISSUE THREAD

**Issue by dvescovi1** [Azure/iotedge#3638]
## Expected Behavior
NXP yocto recipes for sumo release use to work. 
yocto bitbake builds use to work fine but now fail with fetch url error from this repo

## Current Behavior
git fetch now fail for release 1.0.6 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.follow build instructions at [readme](https://source.codeaurora.org/external/imx/meta-imx-iotedge/tree/README.md?h=sumo)
2.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: NXP 1MX8m
* Architecture [e.g. amd64, arm32, arm64]: ARM64
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.6??
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
here is output from bitbake build:
WARNING: libiothsm-std-1.0.6.1-r0 do_fetch: Failed to fetch URL gitsm://github.com/azure/iotedge.git;protocol=https;branch=release/1.0.6, attempting MIRRORS if available
ERROR: libiothsm-std-1.0.6.1-r0 do_fetch: Fetcher failure: Unable to find revision 3fa6cbef8b7fc3c55a49a622735eb1021b8a5963 in branch release/1.0.6 even from upstream
ERROR: libiothsm-std-1.0.6.1-r0 do_fetch: Fetcher failure for URL: 'gitsm://github.com/azure/iotedge.git;protocol=https;branch=release/1.0.6'. Unable to fetch URL from any source.
ERROR: libiothsm-std-1.0.6.1-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/david/agent/_work/idpi_sumo/edge-imx/buildevkedge/tmp/work/aarch64-poky-linux/libiothsm-std/1.0.6.1-r0/temp/log.do_fetch.22265
ERROR: Task (/home/david/agent/_work/idpi_sumo/edge-imx/sources/meta-iotedge/recipes-core/libiothsm-std/libiothsm-std_1.0.6.1.bb:do_fetch) failed with exit code '1'
WARNING: iotedge-daemon-1.0.6.1-r0 do_fetch: Failed to fetch URL gitsm://github.com/azure/iotedge.git;protocol=https;branch=release/1.0.6, attempting MIRRORS if available
ERROR: iotedge-daemon-1.0.6.1-r0 do_fetch: Fetcher failure: Unable to find revision 3fa6cbef8b7fc3c55a49a622735eb1021b8a5963 in branch release/1.0.6 even from upstream
ERROR: iotedge-daemon-1.0.6.1-r0 do_fetch: Fetcher failure for URL: 'gitsm://github.com/azure/iotedge.git;protocol=https;branch=release/1.0.6'. Unable to fetch URL from any source.
ERROR: iotedge-daemon-1.0.6.1-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/david/agent/_work/idpi_sumo/edge-imx/buildevkedge/tmp/work/aarch64-poky-linux/iotedge-daemon/1.0.6.1-r0/temp/log.do_fetch.25849
ERROR: Task (/home/david/agent/_work/idpi_sumo/edge-imx/sources/meta-iotedge/recipes-core/iotedge-daemon/iotedge-daemon_1.0.6.1.bb:do_fetch) failed with exit code '1'
WARNING: iotedge-cli-1.0.6.1-r0 do_fetch: Failed to fetch URL gitsm://github.com/azure/iotedge.git;protocol=https;branch=release/1.0.6, attempting MIRRORS if available
ERROR: iotedge-cli-1.0.6.1-r0 do_fetch: Fetcher failure: Unable to find revision 3fa6cbef8b7fc3c55a49a622735eb1021b8a5963 in branch release/1.0.6 even from upstream
ERROR: iotedge-cli-1.0.6.1-r0 do_fetch: Fetcher failure for URL: 'gitsm://github.com/azure/iotedge.git;protocol=https;branch=release/1.0.6'. Unable to fetch URL from any source.
ERROR: iotedge-cli-1.0.6.1-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/david/agent/_work/idpi_sumo/edge-imx/buildevkedge/tmp/work/aarch64-poky-linux/iotedge-cli/1.0.6.1-r0/temp/log.do_fetch.25867
ERROR: Task (/home/david/agent/_work/idpi_sumo/edge-imx/sources/meta-iotedge/recipes-core/iotedge-cli/iotedge-cli_1.0.6.1.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3661 tasks of which 3423 didn't need to be rerun and 3 failed.

Summary: 3 tasks failed:
 

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by micahl** [comment]
@dvescovi1 1.0.6 is almost 2 years old at this point and not recommended.  You should be using a more recent version of IoT Edge (e.g. 1.0.9.4).
