### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ssojha** [Azure/iotedge#3642]
ConnectOperation: completing with error None caused by [Errno -2] Name or service not known
RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [Errno -2] Name or service not known.  Setting timer.
transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 340, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [Errno -2] Name or service not known

**Comment by lfitchett** [comment]
Can you please add some context around your issue. What scenario are you running, what are your versions of edgeAgent, edgeHub and iotedge? Please run iotedge check and include the output. 

The new bug template has a good layout for all of this information: https://github.com/Azure/iotedge/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by ssojha** [comment]
iotedge version : 1.0.9.4

Hi,

thanks for quick turn around .
i have a ubuntu18 machine, i have installed few iotedge modules following below link . one of my module trying to connect 8883 and always giving me above error.
https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite/blob/master/docs/stepbystep.md

**Comment by ssojha** [comment]
> iotedge version : 1.0.9.4
> 
> Hi,
> 
> thanks for quick turn around .
> i have a ubuntu18 machine, i have installed few iotedge modules following below link . one of my module trying to connect 8883 and always giving me above error.
> https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite/blob/master/docs/stepbystep.md

note: 8883 ports are opened.

**Comment by lfitchett** [comment]
Trying to connect to port 8883 of edgeHub? If so, what address are you using? Is your python code running in a docker container (module) or on the host alongside the edge deployment? If the latter, you'll need to bind edgeHub's port to a specific local ip and connect using that, if the former, you should be able to connect to http://edgehub:8883.

Also is iotedge even running? Can you run `sudo iotedge check` and share the results

**Comment by ssojha** [comment]
yes trying to connect to 8883 of edgeHub. yes the pythone code is running inside the conatiner.
can you please let me know how to bind edgeHub's port to a specific local ip and connect using that ?

yes iotedge is running ..
thanks in advance

**Comment by lfitchett** [comment]
Please just run `sudo iotedge check`. 

In addition, if you are comfortable sharing logs on the public github, you can run `iotedge support-bundle`

**Comment by ssojha** [comment]
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 68 days (at 2020-12-09 15:58:58 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

19 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
[support_bundle.zip](https://github.com/Azure/iotedge/files/5317611/support_bundle.zip)

**Comment by ssojha** [comment]
please help and let me know if anymore info is needed.

**Comment by veyalla** [comment]
I don't see any errors from the IoT Edge runtime side. 

Please open an issue on https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite and follow up there.
