### ISSUE TITLE
Edge Module Instantiation Error with Azure Container Registry

### ISSUE THREAD

**Issue by clustor** [Azure/iotedge#3645]
I am not sure if this is edgeAgent issue but there is something odd going on. 

If I use the username and password generated from "Access Keys" with Admin User enabled in Azure CR while setting up a module, everything works (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account). But if I use the username and password for a service principal (https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal), I get unauthorized error. 

## Expected Behavior
I expect edgeAgent to connect to the Azure Container registry either with Admin user or service principal user.

## Current Behavior
Oct 02 00:20:02 XXXXX daemon:info docker:edgeAgent/bc97f1f93f98[4503]: 	caused by: Get "https://xxxxx.azurecr.io/v2/alpine-xxx/manifests/latest": unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.. Will retry in 02m:53s

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a service principal using instructions provided at https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal
2. Build a sample module and push to the container registry 
3. Maker sure docker login to the container registry works with service principal and able to pull the module
4. Configure Container Registry credentials with service principal username and password in "Set Modules"
5. Notice errors reported by edge run time. 

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10~dev
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0
* Docker/Moby [run `docker version`]: 18.09.1-ce

**Comment by lfitchett** [comment]
So to confirm the scenario: 
* Generated username/password for service principal authenticates when manually running `docker login` **and is able to pull your module using `docker pull`**.
* When the same username/password is used by the edge device, the authentication error happens. 

If this is the case, I would ask you to verify the correct username and password is in the $edgeagent module twin:
![image](https://user-images.githubusercontent.com/13950901/94974302-f70e2d00-04c2-11eb-9d42-f68ce8cdf760.png)

**Comment by clustor** [comment]
Yes. I was able to "docker pull" and I double checked the deployment manifest has the correct username & password. Is there any way to enable logs to see what's going on edgeAgent when it's trying to pull the manifest?

**Comment by lfitchett** [comment]
You can set the RuntimeLogLevel environment variable to "debug": https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#view-the-messages-going-through-the-iot-edge-hub

**Comment by veyalla** [comment]
@clustor which version of iotedged version are you using and from where did you get it? This sound like this issue, fixed in 1.0.9.4 release:

https://github.com/Azure/iotedge/commit/698bec5b83d536e48d6b923eeeb2a518557973dd

**Comment by CindyXing** [comment]
@clustor can you please confirm if the password contains '?' or '~'; and what iotedged version you are using? Thanks.

**Comment by clustor** [comment]
@veyalla I am using 1.0.10~dev
@CindyXing  Yes. It does have '~'.  I created service principal using the script provided here https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal.

**Comment by veyalla** [comment]
1.0.10 GA was released last week , please try on this and re-open if still an issue.
