### ISSUE TITLE
Connecting to a container in different network

### ISSUE THREAD

**Issue by clustor** [Azure/iotedge#3646]
azure-iot-edge (172.18.0.0/16) network is setup by edge run time and we also have system containers that need to run on default bridge (172.17.0.0/16). We have a need to connect to a REST service of a container running on the default bridge from modules installed through Azure IoT Edge on the same node.

Do you know if this is feasible? I thought I will check with this community first before reaching out to Docker CE forums. 

Thanks.

**Comment by lfitchett** [comment]
I believe you can connect a container to 2 networks at once. Is it feasible to add the system containers to the iotedge network? If not, you can configure the edge modules to also connect to the default network. The createOptions in the deployment accept the same json as the docker api: https://docs.docker.com/engine/api/v1.40/#operation/ContainerCreate

**Comment by veyalla** [comment]
@clustor do you need any further help here?
