### ISSUE TITLE
Upgrading from 1.0.8 to 1.0.10-rc2 needs storage cache to be deleted

### ISSUE THREAD

**Issue by davidguidali** [Azure/iotedge#3647]
In my company we want to upgrade the edge runtime on our IPCs from 1.0.8 to 1.0.10.x as soon as its released. 
I did some testing with upgrading to 1.0.10-rc2 and while the upgrade itlself worked, I noticed a timeout in the edgeHub:

![image](https://user-images.githubusercontent.com/61904428/94900639-9caaa780-0495-11eb-88bb-620a619852d5.png)

The edgeHub failed to read the cache and therefore timouted and re-started continuously. After I deleted the storage folder, the edgeHub started to work again but of course I lost all my cached telemetry data.

Will there be a way to upgrade to 1.0.10.x without loosing the cached data?

**Comment by veyalla** [comment]
Thanks for reporting, we're taking a look.

**Comment by veyalla** [comment]
We can't seem to be able to repro this. 

If you can readily repro on your end, can you please open an Azure Support request attaching the [support-bundle](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#gather-debug-information-with-support-bundle-command) of the failure? You can reference this issue in the support request.

**Comment by davidguidali** [comment]
Its difficult to reproduce since I don't know what data were stored originally in the cache. However, If I'm gonna see this error again I'll do the steps you recommended. Thanks!

**Comment by veyalla** [comment]
Thank you!
