### ISSUE TITLE
Latest Iot Edge automatic deployment is triggered once again when we delete an old unused deployment

### ISSUE THREAD

**Issue by JesvinJoseph** [Azure/iotedge#3649]
## Expected Behavior
When we delete an unused deployment from iothub, It should not trigger or change anything to the device

## Current Behavior
When we delete an old unused iot edge deployment from iothub, the latest deployment is triggered once again. Especialy the twin change as part of the deployment.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a automatic deployment with a module (that can receive module twin changes) and the desired property is set along with the deployment
2. Once the deployment is created, module willl start running on the device and we can see the twin property received on the module from its logs.
3. Clone the deployment and change the twin properties of the same module and save it.
4. One the cloned deployment id created, new twin properies are received on the module. We can see that from the module logs.
5. After 5 mins, delete the old deployment.
6. Now on the module logs, we can see a twin change trigger.

**Comment by veyalla** [comment]
Do you see the same behavior if the cloned deployment is assigned a higher priority in step 3?

**Comment by JesvinJoseph** [comment]
> 
> 
> Do you see the same behavior if the cloned deployment is assigned a higher priority in step 3?

Yes, @veyalla. Even if the priority is high, the same behavior.

**Comment by veyalla** [comment]
@yophilav can you please try to repro?

**Comment by yophilav** [comment]
I couldn't reproduce the symptoms given the repro steps. 
I did the following: 
1. Create `deployment1` from azure portal with just  default runtime modules (edgeAgent1.0 & edgeHub:1.0 ; priority = 10)
2. Wait for the modules to be deployed on the target device
3. Clone `deployment1` and named it `deployment2` and update the image tags of runtime modules from `1.0` to be `1.0.10-rc2` ; priority = 20
4. Wait for the system modules to be deployed
5. Remove `deployment1` 
6. Wait 5 minutes to see if there is a redeployment of a module.

@JesvinJoseph 
Could you provide the version of the edgeAgent & edgeHub please? 
What exact operation/variable are you applying to the module on the ReproStep(3)?

**Comment by JesvinJoseph** [comment]
@yophilav I have mentioned the case of a twin change trigger. Please add a custom module that can receive its module twin change and do the steps once again. If that is difficult, deploy a stream analytics edge module. clone the deployment, delete and add the stream analytics module once again.   So that its module twin will get change in the cloned deployment. Then if you delete the old deployment, you can see that the stream analytics module has received a new trigger to restart the engine.

**Comment by JesvinJoseph** [comment]
@veyalla @yophilav Are you able to reproduce the issue? Do you need any additional information?

**Comment by veyalla** [comment]
This is the response we got from the IoT Hub team: 

*Yes that is expected. Any deployment crud will rerun the ADM engine in the backend which might evaluate that the device/module needs to be updated with cumulative payload of all the applicable deployments based on device/module state and deployment priority and create/update/delete event.*

If you have further questions, I suggest you open a support ticket via the Azure Portal for IoT Hub service.
