### ISSUE TITLE
Question: Best way to download files to IoT Edge module?

### ISSUE THREAD

**Issue by Jan-Olof** [Azure/iotedge#365]
Hi,

We would like to download files from Azure to IoT Edge. These files would then be placed on the host system and we would manipulate them there, preferably from a module. (Basically these files contain upgrades to other software on the host.)

Does anyone have any ideas about the best way to do this?

**Comment by mrohera** [comment]
If you mount a volume into your container using the module's create options. that pretty much all you need. Using this, your host on which the Edge is running on and your module can exchange files at will.

Link detailing docker mounts: [https://docs.docker.com/storage/volumes/](https://docs.docker.com/storage/volumes/)

**Comment by Jan-Olof** [comment]
Thanks a lot for the answer about the file sharing between edge module and host.

About the first part of my question, I still wonder about the best way to download (transfer) files from Azure to an IoT Edge module. (For example, from a storage blob.) 

I have found this communication guide: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-c2d-guidance and also tutorials like this: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-c2d

So, is "Direct methods" the best way to do this or would you recommend something else?

**Comment by myagley** [comment]
At this point, IoT Hub doesn't have any APIs that support general file downloads. Both C2D messages and methods have payload size restrictions and were never intended for file download.

Is it possible to go to storage blobs directly from your module?

**Comment by Jan-Olof** [comment]
Thanks for clearing that up. Saves a lot of time.

I will try to use storage blobs directly. Is there anything special to consider when using a IoT Edge module or is it just like in the usual examples? E.g. https://github.com/Azure-Samples/storage-blobs-dotnet-quickstart

**Comment by myagley** [comment]
It should just be like the examples. The default network configuration should allow you to get out to the internet from the container, so you should be able to use the storage blobs SDK directly.

**Comment by Jan-Olof** [comment]
Thanks a lot for answering my questions!
