### ISSUE TITLE
How to use workloadClient using azure-iot-c-sdk

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/iotedge#3671]
we are using azure-iot-c-sdk for iotedge module development.

we are trying to implement following **azure-iot-edge-identity-translation-lite** module in C programming with help of azure-iot-c-sdk.
**https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite**.

**steps are as follow**s

1. send registration message to hub , and our azure function register the device to iothub.
2. Azure function call the direct method to module once it create the device
3. device module call sign method of worload-api to generate symmetric key

**steps 1,2,3 are working but signKey generated at device-module is not same as registered device, due to that i am not able to connect device.**

we are using same azure function which is part of azure-iot-edge-identity-translation-lite.
below is the azure function.
https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite/blob/master/src/cloud/functions/LeafDeviceCloudProcess.cs

I did not find a way to generate key using azure-iot-c-sdk . 
so i used libcurl to invoke workload api.
**Could you please check and let me know what is the issue here?**

Following C code trying to implement **SignAsync** method implemented with C#(azure-iot-edge-identity-translation-lite)
**https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite/blob/master/src/edge/modules/IdentityTranslationLite/Program.cs#L93**
`
Json::Value sendPostRequest(const std::string &url, const std::string &body)
{
    std::cout<<"initiating post request";
Json::Value deviceData;

    MemoryStruct chunk;
    chunk.memory = static_cast<char *>(malloc(1)); 
    chunk.memory[0] = 0;
    chunk.size = 0;

    CURL *curl;
    CURLcode response;
    long http_code;
    std::string postUrl = url;
    curl = curl_easy_init();
    curl_global_init(CURL_GLOBAL_ALL);
    if (curl) {
        struct curl_slist *headers = NULL;
        headers = curl_slist_append(headers, "cache-control: no-cache");
        headers = curl_slist_append(headers, "content-type: application/json");
        curl_easy_setopt(curl, CURLOPT_URL, postUrl.c_str());

    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, curlWriteCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, static_cast<void *>(&chunk));
    
        curl_easy_setopt(curl, CURLOPT_UNIX_SOCKET_PATH, "/var/run/iotedge/workload.sock");
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
        curl_easy_setopt(curl, CURLOPT_HTTPAUTH, (long)CURLAUTH_BASIC);
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "POST");
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, body.c_str());

        response = curl_easy_perform(curl);
        if (response != CURLE_OK) {

            std::cout<<"request is failed\n";
            curl_easy_cleanup(curl);
            curl_global_cleanup();
            return false;
        }
        curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
    }
    curl_easy_cleanup(curl);
    curl_global_cleanup();

    writeJson(chunk.memory, deviceData);
    free(chunk.memory);
    chunk.memory = NULL;
    chunk.size = 0;

    return deviceData;

}
int main()

{
   char url[1024];
    sprintf(url,"http://localhost/modules/%s/genid/%s/sign?api-version=2019-11-05",getenv("IOTEDGE_MODULEID"),getenv("IOTEDGE_MODULEGENERATIONID"));
	std::string payload =R"({ "keyId": "primary",  "algo": "HMACSHA256",  "data": "LeafDeviceId"})";

    Json::Value signKey = sendPostRequest(urlString,payload);
    key = signKey["digest"].asString();
}
`
**sendPostRequest method return success(200) and i am getting following response
"digest\" : \"BZkbu0bpX7BBo06uacWrOvQEIFW0V3rFjRyrmd/+S6c=**

**Comment by yophilav** [comment]
Hello rajaggrawal,

Thank you the question! Given the nature of the question, I believe you would get a more accurate answer by posting the question directly to Azure IoT C SDK git repo  [https://github.com/Azure/azure-iot-sdk-c](https://github.com/Azure/azure-iot-sdk-c)

**Comment by rajaggrawal** [comment]
Hi @yophilav 

this is not entirely related with c-sdk.

its about sign method of workload.

i am following C# signKey implementaion from azure-iot-edge-identity-translation module.
### https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite/blob/master/src/edge/modules/IdentityTranslationLite/Program.cs#L93

I am trying to do same with curl command
**Is the following does the same which is done in signKey method in above link ?**

curl -POST --unix-socket /var/run/iotedge/workload.sock "http://localhost/modules/workloadapiSymmKey/genid/637368715028830651/sign?api-version=2019-11-05" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"keyId\": \"device_key\",  \"algo\": \"HMACSHA256\",  \"data\": \"LeafDeviceId\"}"

**Comment by yophilav** [comment]
Could you please elaborate on what exactly are you trying to sign/auth here?

**Comment by rajaggrawal** [comment]
Hi @yophilav ,

Purpose is to connect a leaf device to IoTHub which does not have identity,  to implement this we are referring **azure-iot-edge-identity-translation module**.

please check this registration flow.

### https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite/blob/master/docs/media/registrationflow.png

Steps 1 to 6 :  Are fine for us.
Step 7 : Azure function has generated Symmetric key and created device on IoTHub  ---> OK
Step 8 : Direct method is received to module  ---> OK
Step 9 : Device module is generating symmetric key using sign method of workload-api and connect device. ---->OK

**But symmetric key generated at step 7 does not match with symmetric key generated at step 9 and connection to gets fail.**

I am sending this payload in sign method of workload-api.
{ "keyId": "primary",  "algo": "HMACSHA256",  "data": "<MyLeafDevice>"}

{
"edgeDeviceId":"<MyEdgeDevice>",
"edgeModuleId":"<MyModuleID">,
"hubHostname":"<MyIotHub>",
"leafDeviceId":"<MyLeafDevice>",
"operation":"create"
}

**Comment by veyalla** [comment]
I suggest you open an issue on the https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite repo as you are following guidance from there.
