### ISSUE TITLE
problem to find package while installing iotedge on ubuntu 16.04 for arm32

### ISSUE THREAD

**Issue by vinils** [Azure/iotedge#3693]
**Device**
Raspberry PI 4 with Ubuntu 16.04

**Repro steps** (link ref [how-to-install-iot-edge-linux](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux) )
curl https://packages.microsoft.com/config/ubuntu/16.04/multiarch/prod.list > ./microsoft-prod.list
sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
even after to install
sudo apt-get update
sudo apt-get install moby-engine
sudo apt-get install moby-cli
sudo apt-get update
sudo apt-get install iotedge

**Actual result**
No package found

**Expected result**
iotedge installed

Ubuntu 16 is a [Tier 2](https://docs.microsoft.com/en-us/azure/iot-edge/support#tier-2) and there is debs on [github releases](https://github.com/Azure/azure-iotedge/releases) which works fine but Im not being able to find them on the repository feed ( https://packages.microsoft.com/config/ubuntu/16.04/multiarch/prod.list)

**Comment by veyalla** [comment]
This is by design. Currently only Tier 1 OS packages are available from the MS Linux repos. Raspbian is the only arm32 OS in Tier 1.
