### ISSUE TITLE
Not able to see logs from module.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/iotedge#3710]
I am running C module and which is started successfully.
i am not able to see any logs from module.

**sudo iotedge logs myModule -f**

there is no single log which is visible.

if i restart iotedge then i can see few logs from module

**sudo /etc/init.d/iotedge restart**

After restart myModule started before edgeHub and i can see few logs.
**But once edgehub started, no single logs appear** .

If i freshly deploy module from cloud then no logs appear.

**Comment by massand** [comment]
@rajaggrawal - Could you provide the support-bundle from your installation by running the [`iotedge support-bundle` command if you are running the latest 1.0.9+ build](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#gather-debug-information-with-support-bundle-command)? If `iotedge support-bundle` isn't available, please gather the iotedged logs by following instructions [here](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#check-the-status-of-the-iot-edge-security-manager-and-its-logs) and [here](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#check-container-logs-for-issues). 

Also, please provide the following details about your environment - 

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

**Comment by massand** [comment]
@rajaggrawal - the entire support-bundle might not be needed here. Please provide the logs required by the new issue template (in addition to the custom module logs):


## Logs


<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

**Comment by veyalla** [comment]
@rajaggrawal any update?

**Comment by rajaggrawal** [comment]
Apologize to respond late.

This issue may not be related with iotedge as i am not able to see logs while running docker logs command.
**docker logs containerID** 

i am not able to collect logs. needs to make setup freshly.

**Comment by varunpuranik** [comment]
Thanks for the update @rajaggrawal. As it does not appear to be an IoT Edge related issue, I will close this issue. If you run into any IoT Edge related issues, feel free to open a new one.
