### ISSUE TITLE
IoT Edge Deployment is targetting a device, but the deployment is not applied

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#3723]
Hi,

This is my current situation:

- I have IoT Edge installed on a VM; 
- IoT Edge is configured to be provisioned via DSP (TPM enrollment)
- I have an IoT Edge deployment defined in my IoT Hub
- The IoT Edge VM is enrolled in DPS and shows up as IoT Edge device in IoT Hub
- In IoT Hub, I can see that my deployment is targetting the IoT Edge device, but the deployment is not applied
- The IoT Edge device reports `417 -- The device's deployment configuration is not set`

Why is the deployment not being applied ?  Since the deployment is not applied, IoT Edge is offcourse not able to download the modules that are defined in the deployment.

When I look at the edgeAgent logs, this is being reported:

```
2020-10-15 08:05:49.195 +00:00 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.UpdateDeploymentConfig(TwinCollection desiredProperties) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\EdgeAgentConnection.cs:line 245
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>b__29_0(Twin twin) in C:\agent\_work\4\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\EdgeAgentConnection.cs:line 176
```

The ModuleTwin of the edgeAgent is indeed empty:
```
{
  "deviceId": "9336983-esap",
  "moduleId": "$edgeAgent",
  "etag": "AAAAAAAAAAE=",
  "deviceEtag": "NDc0NzYyMzAz",
  "status": "enabled",
  "statusUpdateTime": "0001-01-01T00:00:00Z",
  "connectionState": "Disconnected",
  "lastActivityTime": "0001-01-01T00:00:00Z",
  "cloudToDeviceMessageCount": 0,
  "authenticationType": "sas",
  "x509Thumbprint": {
    "primaryThumbprint": null,
    "secondaryThumbprint": null
  },
  "version": 11,
  "properties": {
    "desired": {
      "$metadata": {
        "$lastUpdated": "0001-01-01T00:00:00Z"
      },
      "$version": 1
    },
    "reported": {
      "schemaVersion": "1.0",
      "version": {
        "version": "1.0.9.2",
        "build": "31573326",
        "commit": "784c766b4050ebd30731a837c254e5dfe7b10fad"
      },
      "lastDesiredStatus": {
        "code": 417,
        "description": "This device has an empty configuration for the edge agent. Please set a deployment manifest."
      },
      "runtime": {
        "platform": {
          "os": "windows",
          "architecture": "x86_64",
          "version": "1.0.10 (c6350db898b2bd7abe1d50a340a1b1a91e72127d)"
        },
        "Type": "Unknown"
      },
```

Note:  I had IoT Edge already installed on this VM and everything was working before.  I've uninstalled IoT Edge and reinstalled it , and now I'm faced with this issue.

**Comment by fgheysels** [comment]
I've removed the IoT Hub, redeployed the IoT Hub, deployed the same IoT Edge deployment to that IoT hub and everything is working again ....

**Comment by massand** [comment]
Based on your twin document, it sounds like the service hadn't applied the deployment on the IoT Hub side and Edge Agent rightfully threw an exception at this state. Also, since your issue is fixed with an IoT Hub redeployment, it could have been a service blip in your specific region. Which region was this and did you have any Layered deployments applied on the IoT Hub for IoT Edge devices when this occurred? Thanks for reporting this.

**Comment by fgheysels** [comment]
This was in the North Europe region, on a F1 IoT Hub.

I had performed multiple kinds of deployments that day:
- I've uninstalled iotedge on an existing VM , and re-installed IoT Edge and reprovisioned the VM to DPS (I did this multiple times to test our registration/onboarding procedure)
- I've deployed custom modules and routes multiple times on that day to that VM

**Comment by veyalla** [comment]
Free hubs frequently run into quota issues. That might a reason as well. Closing as the issue seems to be fixed now.
