### ISSUE TITLE
IoT Edge containers on Windows host OS

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#3733]
In the documentation, it is stated [here](https://docs.microsoft.com/en-us/azure/iot-edge/support#operating-systems) that only Windows containers are supported in Azure IoT Edge when the host OS is Windows.
However, it seems that the edgeAgent and edgeHub system modules are only available as Linux containers, wo when running IoT Edge on Windows, those 2 system modules are in fact linux containers ?

Then I wonder why Linux containers for custom modules are not supported in IoT Edge on Windows.

**Comment by massand** [comment]
edgeAgent and edgeHub modules run as Windows containers when Windows containers are enabled natively on the system. If Linux containers are enabled on docker, docker will pull the Linux container version. 

Here is the full list of tags on Docker Hub - https://mcr.microsoft.com/v2/azureiotedge-agent/tags/list

**Comment by krottiers** [comment]
@massand Could you point us to the dockerfile of the windows version then? In the docker folder of the edge agent and hub I can only see a linux folder: [https://github.com/Azure/iotedge/tree/master/edge-agent/docker](https://github.com/Azure/iotedge/tree/master/edge-agent/docker )

**Comment by massand** [comment]
https://github.com/Azure/iotedge/tree/release/1.0.10/edge-agent/docker/windows
