### ISSUE TITLE
DNS resolution doesn't work in IoT Edge Windows containers

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#3734]
I have a set of custom containers (Windows) running in Azure IoT Edge on a Windows host OS.   In one of those containers, I need to call a http endpoint for which I have the hostname.   However, when performing that HTTP request using the hostname, I get the following exception back:

```
An exception occured while writing to InfluxDb:
System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

When I change the code so that the IP address is used to do the request instead of the hostname, everything works fine.

- I have specified DNS servers in the `daemon.json` file and restarted the Moby engine (iotedge-moby) as explained here, but this doesn't solve the issue.
- As an alternative, I have specified the DNS servers that must be used in the `createOptions` of both my custom container and the edgeHub and edgeAgent modules, but this also doesn't solve the issue.

How can this issue be fixed ?

When looking on the Internet, it seems that multiple people are having issues with performing DNS lookups from within Windows containers.

As I can read [here](https://social.msdn.microsoft.com/Forums/azure/en-US/af21fb5c-e4d1-4913-959a-5c10b295b639/unable-to-do-dns-lookup-from-a-windows-container-in-azure-container-instance?forum=AzureContainerServices), it seems to be an issue in the `nanoserver 1809` package ?   
I'm using `mcr.microsoft.com/dotnet/core/runtime:3.1-nanoserver-1809`, which is the standard runtime base image that is being used when creating a new IoT Edge module.   If the issue regarding DNS resolution in Windows containers is indeed an issue in the `nanoserver 1809` base image, I wonder there is no new image availabe where this issue is resolved ? Can we use the `nanoserver 1903` image (that is mentioned in the article that I have linked) in an IoT Edge solution on Windows ?
Moreover, as mentionned [here](https://hub.docker.com/_/microsoft-windows-nanoserver/), the `nanoserver 1809` image (which is thus used by default when creating a new IoT Edge module) will be EOL on November 10th, that's less then one month away.   So in that case, what container image should be use for Windows containers in IoT Edge ?

**Comment by veyalla** [comment]
After DNS is set in daemon.json the container instances need to be deleted before the new DNS takes effect. Please run the following commands in an elevated PowerShell environment after DNS is set:

```
docker context create iotedge --docker "host=npipe:////./pipe/iotedge_moby_engine"
docker context use iotedge
docker rm -f $(docker ps -aq)
```
This operation will delete all the saved and running containers, but new instances should be created in about a minute with DNS configured in daemon.json if iotedged is running.

I am not aware of connectivity issues with 3.1 based images, that might be specific to ACI...

**Comment by fgheysels** [comment]
Thanks, I'll try to do that and post any updates on that.

Some extra information:  we have defined an 'onboarding' process for our edge devices where we install the IoT Edge and directly after that we set the DNS in daemon.json.   So actually, the DNS information is available before any modules (except for the edgeAgent) are available.

**Comment by veyalla** [comment]
Any updates here?

**Comment by fgheysels** [comment]
I've verified if daemon.json contains the correct DNS IP's
I've executed the commands you listed here, the containers were removed and new instances were created
The issue however, remains.

I'm pretty sure that the issue originates from the nanoserver-1809 image, which we also need to use since IoT Edge for Windows requires this base image (which is actually EOL next month).

**Comment by veyalla** [comment]
We cannot repro this issue with nanoserver-1809 image. Since we'll need more details from device, can you please go ahead and open a support ticket from the Azure Portal? You can reference this github issue in the support ticket. 

Re: Nanoserver 1809 EOL, we have some good news. It has been extended -
![image](https://user-images.githubusercontent.com/22105760/97230055-84793000-1796-11eb-95b5-f0de1c84bdb7.png)
 https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/base-image-lifecycle
