### ISSUE TITLE
When iotedge  is installed on aks,i couldn't find find links to  device ca certificates

### ISSUE THREAD

**Issue by omarine** [Azure/iotedge#3759]
Describe the bug
certificates settings missing in config.yaml when iotedge runtime deployed on aks

To Reproduce

Install iotedge runtime on aks cluster(Linux)
Connect to your pod/container (iotedged)
Navigate to /etc/iotedged and display content of the confi.yaml
Expected behavior
certificates settings missing

Screenshots

when iotedge runtime is installed on windows vm

the certificates settings section looks :

![image](https://user-images.githubusercontent.com/13197345/96600650-71c3ae80-12f1-11eb-8d62-d62096cd75af.png)

On Aks

![image](https://user-images.githubusercontent.com/13197345/96600695-7ee09d80-12f1-11eb-9fa5-243630d625f9.png)

I hear iotedge on aks is still in preview and opcpublisher is not supported on aks ! but the new opcpublisher is a part of the iotindustrial which is deployable  on aks?

Thanks in avdance for your answer.

**Comment by veyalla** [comment]
What was the helm command used to install IoT Edge on K8s? Also, what is the relation between opcpublisher and device ca certs in iotedged?

**Comment by omarine** [comment]
Sorry a mistake, i meant iotedge runtime.so do you have an explanation on how to use device ca in aks ?
 here is the helm command : 
helm install --repo https://edgek8s.blob.core.windows.net/staging {name of release} edge-kubernetes \
  --namespace {namespace name} \
  --set "iotedged.data.persistentVolumeClaim.name={name of the pvc}" \
  --set "provisioning.deviceConnectionString=$connStr" \
  --set "edgeAgent.env.persistentVolumeClaimDefaultSizeInMb=5000" \
  --set "edgeAgent.env.storageClassName={storage class name}"

**Comment by veyalla** [comment]
This is not listed in the examples, but [values.yaml](https://github.com/Azure/iotedge/blob/a9ff7e70677bb2765e1cd2ef467bd49021d9aa4a/kubernetes/charts/edge-kubernetes/values.yaml#L108-L125) has information in it to set it up.

**Comment by omarine** [comment]
Hello,

it's on the iotedge-k8s-doc 

https://microsoft.github.io/iotedge-k8s-doc/examples/pervol_translation.html


helm install --repo https://edgek8s.blob.core.windows.net/staging pv-example1 edge-kubernetes \
  --namespace pv1 \
  --set "provisioning.deviceConnectionString=$connStr" \
  --set "edgeAgent.env.persistentVolumeClaimDefaultSizeInMb=5000" \
  --set "edgeAgent.env.storageClassName=azurefile"

Maybe then there might be some command in helm install to provision and x509 certificate instead of connectionString

same when installin iotedge runtime since the version of 1.0.10 it is now possible to specify 

. {Invoke-WebRequest -useb https://aka.ms/iotedge-win} | Invoke-Expression; `
Initialize-IoTEdge -ManualX509

what would be the equivalent in aks ?

Thanks in advance

**Comment by darobs** [comment]
Hi @omarine,

Right now, Edge on K8s has feature parity with 1.0.9, which **doesn't have manual x.509 provisioning**, just X.509 through DPS. 

Feature parity for 1.0.10 is planned for Edge on K8s - coming soon now that 1.0.10 is released.  This is how it will work:

You will have to create a secret to install the certificates into the pods then reference the secret in the Helm chart.
 ```sh
kubectl create secret generic -n device-namespace edge-authentication --from-file=certs/identity_certificate.pem --from-file=private/identity_key.pem

helm install --repo https://edgek8s.blob.core.windows.net/staging pv-example1 edge-kubernetes \
  --namespace pv1 \
  --set "provisioning.authentication.identitySecret=edge-authentication"
  --set "provisioning.authentication.identityCert=identity_certificate.pem"
  --set "provisioning.authentication.identityPk=identity_key.pem"
  --set "provisioning.authentication.iothubHostname=<your iothub hostname>"
```

I extracted this example from [here](https://raw.githubusercontent.com/Azure/iotedge/edge-on-k8s-public-preview/kubernetes/charts/edge-kubernetes/values.yaml).

```yaml
###############################################################################
# Provisioning mode and settings
###############################################################################
#
# Configures the identity provisioning mode of the daemon.
#
# Supported modes:
#     manual   - using an iothub connection string or an X.509 identity certificate
#     dps      - using dps for provisioning
#     external - the device has been provisioned externally.
#                Uses an external provisioning endpoint to get device specific information.
#
# Manual settings when using IoT Hub connection string
#     deviceConnectionString - Required. The Edge device connection string
#                                when using SharedAccessKey authentication mode.
#                                Ex. "HostName=<hub-name>.azure-devices.net;DeviceId=<device-id>;SharedAccessKey=<key>
#
# Manual authentication settings when using an X.509 identity certificate
#   Please create a secret containing 2 items, the Edge device identity X.509 certificate, and the 
#   Edge device identity private key. Then give the chart the secret name and the item names. 
#   For example, if a secret is created like this:
#   `kubectl create secret generic -n device-namespace edge-authentication --from-file=certs/identity_certificate.pem --from-file=private/identity_key.pem
#   The YAML would look like:
#     identitySecret: "edge-authentication"
#     identityCert: "identity_certificate.pem"
#     identityPk: "identity_key.pem"
#
#     iothubHostname - Required. The Azure Iot Hub hostname.
#                       Ex. <hub-name>.azure-devices.net
#     deviceId       - Required. The Edge device id.
#     identitySecret - Required. The secret name.
#     identityCert   - Required. The secret item name for Edge device identity X.509 certificate.
#     identityPk     - Required. The secret item name forEdge device identity private key.
#
# DPS Settings
#   If configuring for configured for X.509 authentication, please create a secret containing 2 
#   items, the Edge device identity X.509 certificate, and the Edge device identity private key. 
#   Then give the chart the secret name and the item names. For example, if a secret is created like 
#   this:
#   `kubectl create secret generic -n device-namespace edge-authentication --from-file=certs/identity_certificate.pem --from-file=private/identity_key.pem
#   The YAML would look like:
#     identitySecret: "edge-authentication"
#     identityCert: "identity_certificate.pem"
#     identityPk: "identity_key.pem"
#
#     scopeId        - Required. Value of a specific DPS instance's ID scope
#     registrationId - Required for TPM and symmetric key provisioning flows.
#                       Optional for X.509 provisioning. Registration ID of a
#                       specific device in DPS.
#                       For more information regarding DPS registration ids
#                       please see https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device#registration-id
#     symmetricKey   - Optional. This entry should only be specified when
#                       provisioning devices configured for symmetric key
#                       attestation. Device specific symmetric key.
#     identitySecret - Optional. The secret name.
#     identityCert   - Optional. The secret item name for Edge device identity X.509 certificate.
#     identityPk     - Optional. The secret item name forEdge device identity private key.
#
# External Settings
#     endpoint - Required. Value of the endpoint used to retrieve device specific
#                information such as its IoT hub connection information.
#
# Dynamic Re-provisioning Settings
#     dynamicReprovisioning - Optional. A flag to opt-in to the dynamic re-provisioning 
#                              feature. If enabled, IoT Edge on detecting a possible 
#                              device re-provisioning event will shut down the daemon.
#                              This is so that on the next daemon startup, the device is 
#                              set up with the new provisioning information of the device in 
#                              in IoT Hub.
#                              For the external provisioning mode specifically, the daemon 
#                              will notify the external provisioning endpoint about the
#                              re-provisioning event before shutting down.
###############################################################################
```
