### ISSUE TITLE
IoT edge security daemon (V1.0.7.1) is not compatible with edgeAgent (1.0.10)

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#3774]
## Expected Behavior
edgeAgent and edgeHub shall start and connect to Azure IoT Hub as normal.

## Current Behavior
edgeAgent can't communicate with security daemon

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Every things are fine until reboot gateway device.
2. 
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
√ container engine is installed and functional
√ config.yaml has correct hostname
√ config.yaml has correct URIs for daemon mgmt endpoint
‼ latest security daemon
    Installed IoT Edge daemon has version 1.0.7.1 but version 1.0.10 is available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time
√ container time is close to host time
√ DNS server
√ production readiness: certificates
√ production readiness: certificates expiry
√ production readiness: container engine
‼ production readiness: logs policy
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
× host can connect to and perform TLS handshake with IoT Hub MQTT port
    Could not connect to iothub-ul4ry.azure-devices.net:8883
√ container on the default network can connect to IoT Hub AMQP port
√ container on the default network can connect to IoT Hub HTTPS port
√ container on the default network can connect to IoT Hub MQTT port
√ container on the IoT Edge module network can connect to IoT Hub AMQP port
√ container on the IoT Edge module network can connect to IoT Hub HTTPS port
√ container on the IoT Edge module network can connect to IoT Hub MQTT port
× Edge Hub can bind to ports on host
    Could not check current state of Edge Hub container

One or more checks raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Debian
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: edgeAgent & edgeHub

### Runtime Versions
* iotedged [run `iotedge version`]: iotedge 1.0.7.1 (f7c51d92be8336bc6be042e1f1f2505ba01679f3)
* Edge Agent [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-agent   1.0.8.3
* Edge Hub [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-hub     1.0.8.3
* Docker/Moby [run `docker version`]: 3.0.5

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

[iotedge.log](https://github.com/Azure/iotedge/files/5420321/iotedge.log)


```
</details>

<details>
<summary>edge-agent logs</summary>

```

[edgeAgent.log](https://github.com/Azure/iotedge/files/5420318/edgeAgent.log)


```
</details>

<details>
<summary>edge-hub logs</summary>

```

No.

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

Although we locks edgeAgent & edgeHub version (1.0.8.3) on Azure IoT Hub, it looks like when device reboot, iotedge still pull back up to date edgeAgent from mcr.microsoft.com, which now is 1.0.10. The problem should be iotedge security daemon 1.0.7.1 doesn't compatible with edgeAgent 1.0.10.

docker images:
REPOSITORY                             TAG                               IMAGE ID            CREATED             SIZE
mcr.microsoft.com/azureiotedge-agent   1.0                               99fab0535ed5        9 days ago          246MB
mcr.microsoft.com/azureiotedge-hub     1.0                               311ab10444ef        11 months ago       219MB
mcr.microsoft.com/azureiotedge-hub     1.0.8.3                           58aba0b3a73d        12 months ago       252MB
mcr.microsoft.com/azureiotedge-agent   1.0.8.3                           5a73e4cee07a        12 months ago       238MB

iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeAgent        running          Up 3 minutes     mcr.microsoft.com/azureiotedge-agent:1.0

**Comment by veyalla** [comment]
@KevinKao809 The config.yaml defines the "bootstrap" edge agent, please ensure that is pinned to a specific version as well and referencing the rolling tag "1.0"

**Comment by KevinKao809** [comment]
Hi Venkat,
Where I can get flow diagram about Azure IoT Edge starting process?

**Comment by veyalla** [comment]
@kgremban is the startup flow documented in our docs?

@KevinKao809 - Quick summary, when iotedged starts up (and there is no re-provisioning required), it looks for existing container named edgeAgent. If found it starts it up, otherwise it creates a container named edgeAgent from the image specified in its config.yaml (a.k.a the bootstrap agent). That agent updates itself to version specified in the deployment if different from the version in config.yaml. In production, it is not recommended to use rolling tags like "1.0", use specific versions like 1.0.9.5, 1.0.10 etc everywhere including the config.yaml.
