### ISSUE TITLE
Clarification regarding number of dropped messages by edgeHub.

### ISSUE THREAD

**Issue by karok2m** [Azure/iotedge#3793]
Hello IoT Edge team. I have a few question regarding cleanup of messages by `edgeHub`. I see that `edgeHub` performs a periodic cleanup of messages, I do have `timeToLiveSec` set to `7200`. And I want to understand if those messages should be considered as dropped or not. So, are the messages reported as cleaned up the ones which were in the send queue but were dropped because of the ttl ? Are those numbers also reported as metrics ?

I also see that there are two numbers being reported, number of cleaned up messages from **queue** and from **message store**. Though, they seem to have the same value for me. When calculating number of dropped messages, should I sum those two numbers for each cleanup period or use only one of the values ?

I am also curious about how do those numbers correlate to `edgehub_messages_sent_total` and `edgehub_messages_received_total` values reported in metrics. Should the difference between those two and `edgehub_queue_length` be equal to total number of dropped messages because of cleanup ?

Sample log of `edgeHub`:

```
<6> 2020-10-22 23:28:12.764 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
...
<6> 2020-10-22 23:36:25.752 +00:00 [INF] - Cleaned up 34221 messages from queue for endpoint iothub and 34221 messages from message store.
```

**Comment by dylanbronson** [comment]
Firstly, in release 1.0.10, we fixed a metric called "edgehub_messages_dropped_total" - this metric should get you what you're looking for. 

For more info on your other questions:
Messages that are cleaned up in those logs have either expired or already been sent. so you cannot use just that log for dropped messages.
edgehub_messages_sent_total is a total number of message an endpoint is sending.
edgehub_messages_received_total  is total number of messages received coming from an endpoint 
edgehub_queue_length is the number of total messages in the queue. However, at the moment, it is only an estimate during offline periods.
You are probably right that sent_total - received_total - queue_length would get you a good estimate of messages dropped, but using the above mentioned metric should work more cleanly.

Queue removal vs message store removal: A message can be removed from a queue but still be in the message store if another queue refers to the same message (e.g. if you have an endpoint sending the same message to multiple endpoints)

I hope this answered all your questions!

https://github.com/Azure/iotedge/blob/master/doc/BuiltInMetrics.md for reference

**Comment by karok2m** [comment]
Thanks @dylanbronson, I will use `edgehub_messages_dropped_total`  with `1.0.10` version of `edgeHub` then.
