### ISSUE TITLE
Proxy set up causing error - agent not starting

### ISSUE THREAD

**Issue by richardleeaus** [Azure/iotedge#382]
Hello,

I've been trying to set up the proxy in our corporate environment, unfortunately when i edit the config.yaml with the proxy settings (which are confirmed to work elsewhere), the security daemon doesn't start the edge agent.

I've set the proxy for the security daemon in registry and everythings seems ok?

This is for running linux containers on windows 10.

Below is the output from the logs - the only way to fix this issue is to uninstall everything and reinstall - any ideas?

2/10/2018 1:25:00 PM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
2/10/2018 1:25:00 PM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
2/10/2018 1:25:00 PM info: iotedged::app -- Version - 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)
2/10/2018 1:25:00 PM info: iotedged -- Detected HTTPS proxy server http://xxxxxxxxxxxx:8080/
2/10/2018 1:25:00 PM info: iotedged::windows -- Starting iotedged service.
2/10/2018 1:25:00 PM info: iotedged -- Initializing the module runtime...
2/10/2018 1:25:00 PM info: iotedged -- Using runtime network id azure-iot-edge
2/10/2018 1:25:00 PM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
2/10/2018 1:25:00 PM info: iotedged -- Finished configuring certificates.
2/10/2018 1:25:00 PM info: iotedged -- Initializing hsm...
2/10/2018 1:25:00 PM info: iotedged -- Finished initializing the module runtime.
2/10/2018 1:25:00 PM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
2/10/2018 1:25:00 PM info: iotedged -- Configuring certificates...
2/10/2018 1:25:00 PM info: iotedged -- Change to configuration file detected.
2/10/2018 1:25:00 PM info: iotedged -- Detecting if configuration file has changed...
2/10/2018 1:25:00 PM info: iotedged -- Finished initializing hsm.
2/10/2018 1:25:00 PM info: iotedged -- Removing all modules...
2/10/2018 1:25:00 PM info: iotedged -- Finished removing modules.
2/10/2018 1:25:01 PM info: iotedged -- Provisioning edge device...
2/10/2018 1:25:01 PM info: provisioning::provisioning -- Manually provisioning device "xxxxxx" in hub "Edge-Prod-AUE-IH.azure-devices.net"
2/10/2018 1:25:01 PM info: iotedged -- Starting management API...
2/10/2018 1:25:01 PM info: iotedged -- Finished provisioning edge device.
2/10/2018 1:25:01 PM info: iotedged -- Starting workload API...
2/10/2018 1:25:01 PM info: iotedged -- Listening on http://10.0.75.1:15580/ with 1 thread for management API.
2/10/2018 1:25:01 PM info: edgelet_core::watchdog -- Starting watchdog with 60 second frequency...
2/10/2018 1:25:01 PM info: iotedged -- Listening on http://10.0.75.1:15581/ with 1 thread for workload API.
2/10/2018 1:25:01 PM info: edgelet_core::watchdog -- Checking edge runtime status
2/10/2018 1:25:01 PM info: edgelet_core::watchdog -- Creating and starting edge runtime module edgeAgent
2/10/2018 1:25:01 PM error: edgelet_http::client -- Io(Custom { kind: Other, error: StringError("unsuccessful tunnel") })
2/10/2018 1:25:01 PM warn: edgelet_utils::logging --    caused by: Core error

2/10/2018 1:25:01 PM warn: edgelet_utils::logging --    caused by: Hyper error

2/10/2018 1:25:01 PM warn: edgelet_utils::logging --    caused by: unsuccessful tunnel

2/10/2018 1:25:01 PM warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
2/10/2018 1:25:01 PM warn: edgelet_utils::logging -- Identity error
2/10/2018 1:25:01 PM warn: edgelet_utils::logging --    caused by: IoT Hub service error

**Comment by richardleeaus** [comment]
Also - just to add to this - we store the username and password in the full proxy string. This works with other services where we have needed to use a proxy.

**Comment by myagley** [comment]
Thanks for the issue report. Is it possible to post a redacted value for the `HTTP_PROXY` env value so that we understand the format of the string and try to get a repro? Thanks!

**Comment by richardleeaus** [comment]
Hi,
Just tried this again with a fresh install - same issue unfortunately.
Redacted value below:

http://domain%5Cloginusername:password@proxy.domain.com.au:8080

**Comment by sebader** [comment]
This was fixed in this PR https://github.com/Azure/iotedge/pull/498
Should appear in the next release.

**Comment by richardleeaus** [comment]
Great, thank you!

**Comment by richardleeaus** [comment]
Usually for the username part, we have to prefix it with the domain (e.g. company name. microsoft/username). From my awareness this unfortunately means we have the encode the forward slash.

**Comment by ondrejspilka** [comment]
Hello, what is the status? With version 1.0.4. IoT edge fails when backslash or %5C is used in HTTPS proxy string.

**Comment by myagley** [comment]
This was fixed in #619 and will be in the next release.

**Comment by myagley** [comment]
This has been fixed in the 1.0.5 release. More information on upgrading is here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge
