### ISSUE TITLE
new version of iot edge - can't update module

### ISSUE THREAD

**Issue by richardleeaus** [Azure/iotedge#384]
Hi

With the new IoT Edge (1.0.2) i am able to initially set up the IoT Edge application through the security deamon (no proxy settings), and all containers successfully pull down and run. It seems like the security daemon does this at start up (guess)?

However, after the initial pull down and start, if i try to change any environment variable of containers, or update a image to a new container, i get the following error.

Does this make sense?

2018-10-02 06:15:06.648 +00:00 [INF] - Plan execution started for deployment 35
2018-10-02 06:15:06.648 +00:00 [INF] - Executing command: "Stop module modulename"
2018-10-02 06:15:07.457 +00:00 [INF] - Executing command: "Saving modulename to store"
2018-10-02 06:15:07.458 +00:00 [INF] - Plan execution ended for deployment 35
2018-10-02 06:15:07.612 +00:00 [INF] - Updated reported properties
2018-10-02 06:15:28.009 +00:00 [INF] - Unable to process module modulename add or update as the module identity could not be obtained

Also the below i think is the output from the security deamon

2/10/2018 4:21:05 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:05.326018600 UTC] "POST /modules/sql_datascience/stop?api-version=2018-06-28 HTTP/1.1" 304 Not Modified -
                     "-" "-" pid(any)
2/10/2018 4:21:05 PM warn: edgelet_utils::logging -- Container already in this state
2/10/2018 4:21:05 PM info: edgelet_http::logging -- [work] - - - [2018-10-02 06:21:05.337015500 UTC] "POST /modules/%24edgeAgent/genid/636675627034742788/encrypt?api-version=2018-06-28
                     HTTP/1.1" 200 OK 5269 "-" "-" pid(any)
2/10/2018 4:21:10 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:10.363399600 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 2431 "-" "-" pid(any)
2/10/2018 4:21:10 PM info: edgelet_http::logging -- [work] - - - [2018-10-02 06:21:10.364396900 UTC] "POST /modules/%24edgeAgent/genid/636675627034742788/encrypt?api-version=2018-06-28
                     HTTP/1.1" 200 OK 5269 "-" "-" pid(any)
2/10/2018 4:21:10 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:10.424397300 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 157 "-" "-"
                     pid(any)
2/10/2018 4:21:10 PM error: edgelet_http_mgmt::error -- Internal server error: Identity manager error
                        caused by: IoT Hub service error

                        caused by: Core error

                        caused by: Hyper error

                        caused by: unsuccessful tunnel

2/10/2018 4:21:28 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:28.774410800 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 171 "-" "-"
                     pid(any)
2/10/2018 4:21:28 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:28.779406900 UTC] "POST /modules/sql_datascience/stop?api-version=2018-06-28 HTTP/1.1" 304 Not Modified -
                     "-" "-" pid(any)
2/10/2018 4:21:28 PM warn: edgelet_utils::logging -- Container already in this state
2/10/2018 4:21:28 PM info: edgelet_http::logging -- [work] - - - [2018-10-02 06:21:28.808421300 UTC] "POST /modules/%24edgeAgent/genid/636675627034742788/encrypt?api-version=2018-06-28
                     HTTP/1.1" 200 OK 5269 "-" "-" pid(any)
2/10/2018 4:21:33 PM info: edgelet_http::logging -- [work] - - - [2018-10-02 06:21:33.851466 UTC] "POST /modules/%24edgeAgent/genid/636675627034742788/encrypt?api-version=2018-06-28
                     HTTP/1.1" 200 OK 5269 "-" "-" pid(any)
2/10/2018 4:21:33 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:33.852478900 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 2431 "-" "-" pid(any)
2/10/2018 4:21:33 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:33.947782100 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 171 "-" "-"
                     pid(any)
2/10/2018 4:21:33 PM error: edgelet_http_mgmt::error -- Internal server error: Identity manager error
                        caused by: IoT Hub service error

                        caused by: Core error

                        caused by: Serde error

                        caused by: expected value at line 1 column 1

2/10/2018 4:21:34 PM info: edgelet_http::logging -- [mgmt] - - - [2018-10-02 06:21:34.035492300 UTC] "GET /identities/?api-version=2018-06-28 HTTP/1.1" 500 Internal Server Error 171 "-" "-"
                     pid(any)
2/10/2018 4:21:34 PM error: edgelet_http_mgmt::error -- Internal server error: Identity manager error
                        caused by: IoT Hub service error

                        caused by: Core error

                        caused by: Serde error

                        caused by: expected value at line 1 column 1

Cheers
Richard

**Comment by myagley** [comment]
What does your network configuration look like? Are you running IoT Edge behind a proxy or firewall?

It's possible that the IoT Hub was returning errors from this period (as evidenced by the last few logs). What is your iot hub name?

**Comment by richardleeaus** [comment]
Thanks for getting back to me.

Correct, we are behind a proxy but we opened up the HTTPS to pass through from the edge machine. This set up had been working for previous versions of IoT Edge. I opened up firewall ports on the machine it self for testing. Again this was working previously?

I am happy to email our IoT Hub name to your email/private? (It's set up for a client of ours - we are a MS partner)

Cheers
Richard

**Comment by richardleeaus** [comment]
Hi

I think i got this working - will monitor over the next day.

I removed the https_proxy and http_proxy environment variables from the Windows 10 host. This had been there for a while prior to this version but after removing it this time round, things seems to be OK.

The client had opened up all HTTPS traffic to bypass the proxy to get this to work, but i'll be testing the new proxy settings over the coming days in the hope that will work.
