### ISSUE TITLE
Issue when uninstalling 1.0 and installing 1.02

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#386]
Trying to install new version of IotEdge. Unfortunately, it fails with not very plausible result.

![image](https://user-images.githubusercontent.com/1756871/46362831-a49a9b80-c671-11e8-9c06-4db23ac201ef.png)

**Comment by veyalla** [comment]
Here at the details on how to upgrade:
https://azure.microsoft.com/en-us/updates/iot-edge1-0-2/

**Comment by myagley** [comment]
@veyalla we could add a `Update-SecurityDaemon` scriplet that calls `Uninstall-SecurityDaemon` and then installs?

**Comment by veyalla** [comment]
Yup, we can queue that up for GA on Windows enhancements.

**Comment by ddobric** [comment]
Thanks, it works with provided instructions.

Independent on this, I would recommend to improve a bit user experience. First, executing script is broken over multiple lines. Second, error "Unable to connect to remote service" is not an error (at least in my specific case) and it sounds very scary. Make warning or Information instead of error.

![image](https://user-images.githubusercontent.com/1756871/46420243-e0943600-c72f-11e8-947c-2dd0f5beee8a.png)

**Comment by myagley** [comment]
The Windows install script was updated to fix these error messages when uninstalling with the 1.0.4 release.
