### ISSUE TITLE
Production Certificates

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#3864]
Hello, I want to use production certificates instead of dev or test ones. I can't find information about how to get a production root CA and two x.509 certificates for each device I create. I've read all documentation and information inside documents provided by azure.

Does anyone has documentation or any tutorial to add a production certificate? What should I do after picking a certificate authority? I don't have any experience in certificates workflow, just in theory...

**Comment by and-rewsmith** [comment]
Here is the documentation I am familiar with about production certs:
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs#root-ca-certificate

I'm not aware of a tutorial which we endorse. I would recommend reaching out to Baltimore, Verisign, or DigiCert to discuss how to obtain these.

**Comment by arsing** [comment]
@eustacea Do you have any links?

**Comment by eustacea** [comment]
Here is documentation on installing the certificates:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates

Global Sign is one recommendation for commercial PKI service provider and already understands IoT Edge certificates needs including DeviceCA which appears to be what you need.
https://www.globalsign.com/en/iot-edge-enroll

Hope this helps.
