### ISSUE TITLE
 Environment IOTEDGE_AUTHSCHEME not set on Ubuntu

### ISSUE THREAD

**Issue by archanabwk** [Azure/iotedge#3867]
**IoTEdge version:** 1.0.10
**OS:** Ubuntu 18.04
I am facing IOTEDGE_AUTHSCHEME related issue on my Ubuntu system. I have added the proper device connection string in /etc/iotegde/config.yaml file. I reinstalled IoTEdge last week, so looks like it has upgraded to 1.0.10. This error was not there with earlier version. 

```
Error: Time:Mon Nov  2 13:56:12 2020 File:/home/arg/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:retrieve_edge_environment_variabes Line:177 Environment IOTEDGE_AUTHSCHEME not set
Error: Time:Mon Nov  2 13:56:12 2020 File:/home/arg/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromEnvironment Line:1186 retrieve_edge_environment_variabes failed
Error: Time:Mon Nov  2 13:56:12 2020 File:/home/arg/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:create_iothub_instance Line:924 Failure creating iothub handle
ERROR: iotHubModuleClientHandle is NULL! connect failed
```
Please help.

**Comment by archanabwk** [comment]
Any reply to this issue?

**Comment by arsing** [comment]
You need to fill in the issue template. That's why we have one.

**Comment by ebertrams** [comment]
Hi @archanabwk , we cannot repro. Can you please provide detailed repro steps and full logs for us to investigate? Thanks

**Comment by varunpuranik** [comment]
@archanabwk - I will close this issue since we have not heard back from you. If you are still running into any problems, please feel free to open a new issue and provide all details requested in the issue template and provide logs for the IoT Edge components.
