### ISSUE TITLE
[ProtocolGateway] - TLS handshake failed., System.IO.IOException: Channel is closed when trying to connect to transparent gateway

### ISSUE THREAD

**Issue by krokoko** [Azure/iotedge#387]
Hello,

While following the tutorial here : https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-linux , i am facing an issue when I try to connect my leaf device to the transparent gateway.

I am able to verify my certificates with openssl command (Verify return code: 0 (ok)) both locally on the gateway and from the downstream device.

When I run an example (iothub_ll_telemetry_sample), the message is not send with the following message :
`Error: Time:Thu Sep 13 13:36:35 2018 File:/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:665 SSL handshake failed: 5`

I activated the debug logs on the gateway, which prints me the same message :
`2018-09-13 18:38:13.086 +00:00 [WRN] [ProtocolGateway] - TLS handshake failed., System.IO.IOException: Channel is closed, 1f917e58
`
My edge device is running with the environment variable OptimizeForPerformance set to false. The hostname is correctly set in my device connection string. It seems to really be a certificate issue.
Also i tested using the SET_OPTION_TRUSTED_CERTS but the same issue is coming.

I tested with MQTT (errors above) and HTTP (Failure in HTTP communication: server reply code is 401. Info: HTTP Response:Request header does not contain ModuleId).

The issue is reproducible with 2 VM machines (Ubuntu 16.04). You have to launch the telemetry_example with sudo to make it work, but it's not a satisfying solution.

Thank you !

## Expected Behavior
The downstream device is able to connect and send message to the transparent gateway

## Current Behavior
The downstream device is not able to connect to the gateway.

## Steps to Reproduce
1. Setup 2 VM under Ubuntu 16.04 : 1 will act as a transparent gateway, the other one as the downstream device
2. Put in place the transparent gateway pattern following the official tutorial : [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway-linux)
2. On the downstream device, install the azure iot c sdk and the root certificate
3. Update the connection string in the iothub_ll_telemetry example 

### Device (Host) Operating System
 Ubuntu 16.04

### Architecture
x86_64

#### iotedged
iotedge 1.0.1

#### Edge Agent
1.0.1

#### Edge Hub
1.0.1

#### Docker
Docker version 18.06.1-ce, build e68fc7a

## Logs
Here are the logs on the downstream device when launching the iothub_ll_telemetry_example
```
./iothub_ll_telemetry_sample
Full connection string : HostName=XXX;DeviceId=XXX;SharedAccessKey=XXX;GatewayHostName=mygateway
Creating IoTHub Device handle
Sending message 1 to IoTHub
SendEventAsync succeed
Called destroy on message!
*   Trying XXX.XXX.112.25...
* TCP_NODELAY set
* Connected to mygateway (XXX.XXX.112.25) port 443 (#0)
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: mygateway (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=mygateway
*        start date: Tue, 18 Sep 2018 21:07:29 GMT
*        expire date: Tue, 16 Oct 2018 08:38:05 GMT
*        issuer: CN=iotedged workload ca
*        compression: NULL
* ALPN, server accepted to use http/1.1
> POST /devices/LCDAQ/messages/events?api-version=2016-11-14 HTTP/1.1
Host: mygateway
iothub-to: /devices/LCDAQ/messages/events
Authorization: SharedAccessSignature sr=XXX
Accept: application/json
Connection: Keep-Alive
User-Agent: iothubclient/1.2.8 (native; Linux; x86_64)
Content-Type: application/octet-stream
iothub-app-property_key: property_value
Content-Length: 12

* upload completely sent off: 12 out of 12 bytes
< HTTP/1.1 401 Unauthorized
< Date: Thu, 20 Sep 2018 18:01:32 GMT
< Content-Type: text/html
< Server: Kestrel
< Transfer-Encoding: chunked
<
* Connection #0 to host mygateway left intact
Error: Time:Thu Sep 20 19:03:49 2018 File:/home/admin/azure-iot-sdk-c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:624 Failure in HTTP communication: server reply code is 401
Info: HTTP Response:Request header does not contain ModuleId
Error: Time:Thu Sep 20 19:03:49 2018 File:/home/admin/azure-iot-sdk-c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1700 unexpected HTTP status code (401)
Called do work!
IoTHubClient_LL_GetSendStatus() returns 0
client status 1
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
```

I replaced all the sensitive informations with XX values.

## Additional Information
The above logs appears when using HTTPS. Running with MQTT doesn't print any error log, but the message is not sent ( `Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY` ) , and still the TLS handshake issue on edge device side.

**Comment by myagley** [comment]
Thanks for the issue report.

@mrohera do these errors look familiar?

**Comment by mrohera** [comment]
Hi krokoko, thanks for reporting this problem. 
Here is something you can try: If you have not installed the root CA certificate on your Ubuntu host, then you would have to add this line to your client code:

```
IoTHubDeviceClient_SetOption(device_handle, OPTION_TRUSTED_CERT, cert_string);
```
Specifically you can see this in [line 251](https://github.com/Azure/azure-iot-sdk-c/blob/5ff1bcf8e8fa2a54528e8071c3458cb70441330b/iothub_client/samples/iotedge_downstream_device_sample/iotedge_downstream_device_sample.c#L251)

Here is a link to a complete sample geared towards connecting a downstream device to the Edge.

- *Note:* Currently it is in PR but it will make its way to the master branch.
https://github.com/Azure/azure-iot-sdk-c/pull/644

**Comment by krokoko** [comment]
Hello @myagley , @mrohera ,

  Thank you for the quick follow up. I tested previously both solutions (install the root certificate on host to test that the edge device is correctly setup, and also the OPTION_TRUSTED_CERT) without success. 

I will try the code in the PR submit by Steve and let you know. Thanks !

**Comment by krokoko** [comment]
Sorry i was busy these last days, i'll test it today and let you know, thanks !

**Comment by krokoko** [comment]
Hello @myagley , @mrohera ,

   I just tested the code in the PR with 2 Ubuntu 16.04 VM (same configuration as the one i describe at the beginning of the ticket) and it's working fine ! Thank you ! :) I will test it with physical devices this week probably and let you know. 

The issue was coming from the `IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_TRUSTED_CERT, cert_string);` in **the iothub_ll_telemetry_sample** where the provided certificate was wrong (weird as i was copy/pasting the content of the certificate in a char * buffer and providing it). By getting the certificate content with the new `obtain_edge_ca_certificate();` method it's working fine.

I guess you can close the issue now... Thanks again for you help ! :)

**Comment by myagley** [comment]
Thanks for getting back. I will close the issue for now, but please feel free to reopen it if you have any more questions. Thanks!

**Comment by mleister97** [comment]
Hey @krokoko

It seems like I am facing the same issue. Did you find an solution without calling the method `obtain_edge_ca_certificate();` as I don't want to attach a storage module to my ESP?
