### ISSUE TITLE
Error: DistributionNotFound: No distributions at all found for azure-iothub-device-client

### ISSUE THREAD

**Issue by ksaye** [Azure/iotedge#390]
When trying to build an IoT Edge module for ARM32 (to run on a RPi 3), I get the error:

**'DistributionNotFound: No distributions at all found for azure-iothub-device-client'**

when the 'pip install azure-iothub-device-client' command is run.

Looking at /root/.pip/pip.log, I do not see a '/azure_iothub_device_client-1.4.3-py3-none-linux_armv6l.whl'

when you run 'docker run -it resin/rpi-raspbian:stretch bash' on window it uses a different processor type.  the output of 'uname -m' is armv61

when you run 'docker run -it resin/rpi-raspbian:stretch bash' on raspbian it uses a different processor type.  the output of 'uname -m' is armv71

How am I, using Visual Studio Code, to 'build' an image on windows, targeting ARM32?

note this error happens on image resin/raspberrypi3-python:2.7 also, which is in the default Dockerfile.arm32v7

Steps to repo the issue:

on Windows
1. run docker run -it resin/rpi-raspbian:stretch bash
2. then run apt update && apt install python-pip
3. then run pip install azure-iothub-device-client

rerun the command on Raspbian, after installing moby from: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm#install-the-container-runtime

**Comment by myagley** [comment]
Hi Kevin,

We appreciate the issue report. Is it possible to move it over to the python SDK repo here: https://github.com/Azure/azure-iot-sdk-python/issues? They will be able to help. Thanks!

**Comment by myagley** [comment]
This issue should be filed against the python sdk repo noted above. I'm going to close this for now.
