### ISSUE TITLE
If EdgeHub is restarted when offline, it fails to deliver stored messages when connectivity is re-established

### ISSUE THREAD

**Issue by veyalla** [Azure/iotedge#392]
## Expected Behavior
After IoT Hub connectivity is re-established, Edge Hub should be able to deliver messages queued while offline even when if it restarts when offline. 

## Current Behavior
Expected behavior doesn't happen. Messages are not delivered upstream.

## Steps to Reproduce

1. Repro only on RPi with Raspbian
2. Configure local module or downstream device to send messages to IoT Hub via Edge 
3. Take Edge device offline
4. Stop/kill edge Hub
5. Edge hub will restart and clients messages will be accepted again
6. Go online
7. Edge hub is not able to deliver any messages to IoT Hub

## Context (Environment)
Raspberry Pi 3; Edge Hub upstream protocol set to MQTT;

### Device (Host) Operating System

Raspbian Stretch

### Architecture

arm32

### Container Operating System

Linux

#### iotedged

iotedge 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)

#### Edge Agent

1.0.2

#### Edge Hub

1.0.2

#### Docker

Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Wed Jun 27 00:53:52 2018
 OS/Arch:      linux/arm
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.2
  Git commit:   9aac187
  Built:        Tue Jun 26 23:27:27 2018
  OS/Arch:      linux/arm
  Experimental: false

**Comment by myagley** [comment]
Thanks Venkat. We can repro and are actively investigating.

**Comment by myagley** [comment]
This may be resolved by #422

**Comment by myagley** [comment]
This fix has been released in 1.0.4
