### ISSUE TITLE
Error code 401002 Unauthorized iot edge

### ISSUE THREAD

**Issue by sutthisart** [Azure/iotedge#3932]
Excuse ,me. Do you have solutions for this error code?
I don't know what should I do.

Win10
https://imgur.com/a/4eBUXmn.jpg

Ubuntu18.04
https://imgur.com/a/oTgEOhS.jpg

Thank you for advance

**Comment by ancaantochi** [comment]
Hi @sutthisart, 

Can you please follow the github issue template to provide more information and also paste the logs from iotedged?

How are the devices provisioned? Is it with manual provisioning and you set up the connection string of the device in the config.yaml?

Thanks!

**Comment by sutthisart** [comment]
Sorry, Dev.
I forgot to text to you.
I've solved this issue.
I deleted issue iothub  then I re-created new iothub and followed this repo.
Thank you so much.

ในวันที่ อ. 10 พ.ย. 2020 เวลา 03:04 Anca Antochi <notifications@github.com>
เขียนว่า:
