### ISSUE TITLE
Azure IoT Edge Module Identity Translation for Downstream Devices in IoT Central and IoT Hub

### ISSUE THREAD

**Issue by Hariharnath-Paduchuru** [Azure/iotedge#3933]
**Problem Statement :** 
Need to provision Leaf devices via Azure Edge Runtime on IoT central and IoT hub
We are trying to implement the Identity translation pattern as mentioned in below link.
https://docs.microsoft.com/en-us/azure/iot-central/core/concepts-architecture#iot-edge-gateway-device-connected-to-downstream-devices-with-identity-provided-by-the-iot-edge-gateway
But found that "Runtime support of gateway providing identity to downstream devices and provisioning of downstream devices isn't currently supported". It mentioned we need to implement our own Identity translation 

**Approach:**
We have an Ubuntu Machine which is acting as an IoT edge device. Here we are getting multiple types of data from different sensor devices like Bluetooth(Philips Bulb) and zigbee(Smartthings multi sensor) sensors. 

Now we want a module to do Identity translation which should be responsible for registering and provisioning the sensor devices on IoT Central and IoT hub as individual devices.

We have gone through the following links for Identity Translation

- https://medium.com/medialesson/azure-iot-edge-identity-translation-getting-started-621b55a237cf

Using the above link, we have made created Device CA certificates to make IoT Edge device to act as a Gateway
We have deployed 2 simulated temperature sensor modules and one node.js Identity translation module.
We were able to get the data from the simulated sensor modules, but we were not able to Identify individual devices from the messages we are getting and it doesn't solve our problem statement of provisioning the simulated temp sensors as leaf devices

- https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite

1. From this sample code, we understood that this works for IoT hub, **we are not sure how this sample needs to be modified to make it work for IoT central.**
2. Can we achieve the same behaviour of Identity translation without using eventgrid and function app, so that everything is included in the single identity translation module.

3. As mentioned in the below code, it uses IoThub connection string, but this won't be available for IoT Central. Please guide us how to use this Identity translation for IoT central
https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite/blob/master/src/cloud/functions/LeafDeviceCloudProcess.cs

Any help on how we can implement Identity translation with azure edge runtime for IoT central and IoT hub specifically would be appreciated.

**Comment by ebertrams** [comment]
As you found out @Hariharnath-Paduchuru, it is not officially supported today.

However we will be releasing a new MQTT broker with a new authorization model this week in public preview that will significantly simplify how to send/receive data on behalf of other devices. It will only work with IoT Hub during the public preview though and does not solve the provisioning problem that needs to be addressed separately. We're planning to publish samples on how to use this new MQTT Broker for this scenario early next year. So look out for this update!

**Comment by Hariharnath-Paduchuru** [comment]
Thanks @ebertrams for your prompt response

1. As of now we have a custom module which uses IoT central group-level symmetric key and derives device-level symmetric keys to provision the leaf devices but it doesn't use ModuleClient class and it bypasses Edge runtime(edgeHub). Our goal is to use the Edge runtime and do the same approach that we mentioned.

2. Is there anyway right now for us to modify the existing [azure-iot-edge-identity-translation-lite](https://github.com/Azure-Samples/azure-iot-edge-identity-translation-lite) code to use it for IoT central?

3. Is there any workaround right now for provisioning leaf devices via edge runtime.

**Comment by ebertrams** [comment]
2. Not that I am aware of. Note that the azure-iot-edge-identity-translation-lite code is a sample provided by Azure Technical Sales team, it is not officially supported by the IoT Edge Product Team or the IoT Central Product Team. The official solution that we re working on is still work in progress and will leverage the new MQTT broker of version 1.2-rc1 or higher.
3. The IoT Edge runtime currently does not provide provisioning capabilities for leaf devices out of the box. The workaround is to build your own custom module that does this provisioning (and do your own security risk assessment that goes with it).

**Comment by Hariharnath-Paduchuru** [comment]
I want to clarify one thing in **azure-iot-edge-identity-translation-lite**. 
In the following sample flow **image, at step 9**, Identity translation module creates a device client to connect new leaf device to IoT hub. 
**By using the device client, does this mean that it is bypassing edgehub(Edgeruntime) to connect leaf devices to IoT Hub**

[azure-iot-edge-identity-translation-lite Image](https://raw.githubusercontent.com/Azure-Samples/azure-iot-edge-identity-translation-lite/master/docs/media/sampleflow.png)

**Comment by ebertrams** [comment]
No the device client created in a module still connects to the edgeHub as a leaf device.

Our 1.2-RC1 release is now out and you can check out our MQTT broker and its authorization policy article here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11

This bullet point is particularly interesting for the identity translation use case "Azure IoT devices or modules can access the topics, including IoT hub topics, of other devices or modules providing that appropriate explicit authorization rules are defined.". As mentioned earlier  we will work on publishing samples early next year.
