### ISSUE TITLE
Getting error when ModuleClient.OpenAsync

### ISSUE THREAD

**Issue by niksacdev** [Azure/iotedge#394]
**Getting error when ModuleClient.OpenAsync**

I am running a custom module (.net core on windows containers). When I invoke the module, the following error is logged in the module logs:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at AOT.Historian.Modules.MessageProcessor.Program.Init() in C:\app\Program.cs:line 80
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at AOT.Historian.Modules.MessageProcessor.Program.Main(String[] args) in C:\app\Program.cs:line 25

```
Upon debugging, it seems the following is causing the error:
so essentially, ModuleClient is not able to Open the connection. The Edge Agent is able to connect to internet and pull new configuration so I am assuming this is not to do with Port or Firewall configuration.

```
// Open a connection to the Edge runtime
            ModuleClient ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await ioTHubModuleClient.OpenAsync();
            Console.WriteLine("IoT Hub module client initialized.");
            
            // Register callback to be called when a message is received by the module
            await ioTHubModuleClient.SetInputMessageHandlerAsync("input1", PipeMessage, ioTHubModuleClient);
```

The Module configuration specified is as follows:
```
{

  "Env": [
    "SITE_CODE=Global",
    "DATAITEM_IDENTIFIER_PATTERN=/(\b$SITE_CODE\b.+).*"
  ],
  "HostConfig": {
    "PortBindings": {
      "8883/tcp": [
        {
          "HostPort": "8883"
        }
      ],
      "443/tcp": [
        {
          "HostPort": "443"
        }
      ],
      "5671/tcp": [
        {
          "HostPort": "5671"
        }
      ]
    }
  }
}
```

## Expected Behavior
The message should flow from custom module to IOT Hub

## Current Behavior
Module throws exception

## Context (Environment)
Windows Containers
IoTEdge 
iotedge 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)

### Device (Host) Operating System
Windows 1803

### Architecture
amd64

### Container Operating System
Windows containers 

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
 17.10.0-ee-preview-3

**Comment by varunpuranik** [comment]
Is EdgeHub able to start properly? If so, can you please provide the EdgeHub logs? 
Also, looking at your module config, looks like you are mapping ports 8883 (MQTTs), 443 (HTTPs) and 5671 (AMQPS) to host. Is this intentional? Why do you need to do this?

My guess is that because of this port mapping, and because EdgeHub also tries to map the same ports to Host, Docker is not able to start EdgeHub properly (because of port conflicts) and so your module is timing out on OpenAsync.

**Comment by niksacdev** [comment]
Closing this, a restraint of the module made things working again.
