### ISSUE TITLE
Nvidia GPU fail to run with Docker and nvidia docker with host config runtime =nvidia

### ISSUE THREAD

**Issue by initmahesh** [Azure/iotedge#3959]
with upgrade to latest edgeagent the container those were working with docker+nvidia docker and hostconfig as runtime=nvidia does not work any more, 
## Expected Behavior
Gpu is accessible in contianer

## Current Behavior
Tell us what happens instead of the expected behavior
GPU fails to mount to container
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.use the attache deployment.json and try on your GPU enable X64 cpu device on Linux 
download https://github.com/linkernetworks/azure-intelligent-edge-patterns/blob/develop-div/factory-ai-vision/debug/deployment.gpu.template.json
deploy it to a gpu vm
go to the vm, and type sudo docker logs InferenceModule , you should see the following

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS Ubuntu 18.04 x64
* Container OS Linux containers,

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: Docker version 19.03.8
* we also installed NVidia docker and can run below command to validate that on the device we can mount nvidai docker 
docker run --rm runtime=nvidia nvidia/cuda nvidia-smi

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by waitingkuo** [comment]
Here's the steps for reproducing

1. download https://github.com/linkernetworks/azure-intelligent-edge-patterns/blob/develop-div/factory-ai-vision/debug/deployment.gpu.template.json
2. deploy it to a gpu vm
3. go to the vm, and type `sudo docker logs InferenceModule` , you should see the following

```
        self._create_inference_session(providers, provider_options)
  File "/opt/miniconda/envs/python38/lib/python3.8/site-packages/onnxruntime/capi/session.py", line 205, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:123 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:117 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 35: CUDA driver version is insufficient for CUDA runtime version ; GPU=21921 ; hostname=9a917062d5f4 ; expr=cudaSetDevice(device_id_);
```

In this module, it uses onnxruntime-gpu to load a model and do predicting

**Comment by ebertrams** [comment]
On iot edge version 1.0 (e.g. 1.0.10.1) and linux x64 architectures, you should use these create options to mount NVIDIA GPUs:
"createOptions": {​​​​"HostConfig": {​​​​"DeviceRequests": [{​​​​"Capabilities": ["gpu"], "Count": -1}​​​​]}​​​

**Comment by ancaantochi** [comment]
I got an environment where it reproduced, to fix it you have to use Runtime (uppercase) instead of runtime. This only reproduces when iotedged in version 1.0.9 and edgeAgent is 1.0.10.

iotedged 1.0.9 with edgeAgent 1.0.10 fails because runtime is not set
iotedged 1.0.9 with edgeAgent 1.0.9 runtime is set correctly
iotedged 1.0.10 with edgeAgent 1.0.10 runtime is set correctly

**Comment by Y07yoyo** [comment]
Hi,

I am trying to mount Nvidia GPU into create options but I am getting the following errors:
Using the options below:
"createOptions": {​​​​"HostConfig": {​​​​"DeviceRequests": [{​​​​"Capabilities": ["gpu"], "Count": -1}​​​​]}​​​
I get the following error:
`One or more errors occurred. (Error calling Create module hydrogen_counting: Could not create module hydrogen_counting
	caused by: Could not create module hydrogen_counting
	caused by: json: cannot unmarshal string into Go struct field DeviceRequest.HostConfig.DeviceRequests.Capabilities of type []string)
 ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module hydrogen_counting: Could not create module hydrogen_counting
	caused by: Could not create module hydrogen_counting
	caused by: json: cannot unmarshal string into Go struct field DeviceRequest.HostConfig.DeviceRequests.Capabilities of type []string, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 235
`

I have also followed instructions from this page: https://github.com/Azure/iotedge/issues/3183
and implemented this code:
`"createOptions": {
                "HostConfig": {
                  "DeviceRequests": [
                    {
                        "Driver": "",
                        "Count": -1,
                        "DeviceIDs": null,
                        "Capabilities": [
                            [
                                "gpu"
                            ]
                        ],
                        "Options": {}
                    }
                  ]
                }
              }`
But I get the following error:
`One or more errors occurred. (Error calling start module hydrogen_counting: Could not start module hydrogen_counting
	caused by: Could not start module hydrogen_counting
	caused by: could not select device driver "" with capabilities: [[gpu]])
 ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling start module hydrogen_counting: Could not start module hydrogen_counting
	caused by: Could not start module hydrogen_counting
	caused by: could not select device driver "" with capabilities: [[gpu]], StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 235
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 144`

I am running IoTEdge Version: iotedge 1.0.10.2. I am trying to build on AMD64 machine. I have installed the Moby-Engine

Kind Regards,

Yusuf

**Comment by ebertrams** [comment]
Sorry for the late reply @Y07yoyo , I had a typo in my previous comment, the correct formatting to mount the GPU is actually:
"createOptions": {​​​​"HostConfig": {​​​​"DeviceRequests": [{​​​​"Capabilities": [["gpu"]], "Count": -1}​​​​]}​​​
