### ISSUE TITLE
systemctl does not stop all of the dependent units

### ISSUE THREAD

**Issue by dcasati** [Azure/iotedge#398]
Hi -

There seems to be an issue when you stop iotedge on Linux but the socket endpoints are not shutoff. This can lead to the service to come back online by issuing `iotedge list`.
## Expected Behavior
systemd should stop all of the depend units 

## Current Behavior
systemd does not stop all of the units associated to `iotedge.service`. This causes two units: iotedge.socket and iotedge.mgmt.socket to be left running. This behavior, in turn, will bring back `iotedged` even though the unit is stopped by systemd.

## Steps to Reproduce
1. Stop the service 
```
systemctl stop iotedge
Warning: Stopping iotedge.service, but it can still be activated by:
  iotedge.socket
  iotedge.mgmt.socket
```
2. Check for the service 
```bash
systemctl is-active iotedge
inactive
```
3. Service get's reactivated if any of the sockets above gets hit. For example through `iotedge list`
```bash
iotedge list
NAME             STATUS           DESCRIPTION                  CONFIG
edgeHub          stopped          Stopped 23 seconds ago       mcr.microsoft.com/azureiotedge-hub:1.0
tempSensor       stopped          Stopped 24 seconds ago       mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent        running          Up 0 seconds                 mcr.microsoft.com/azureiotedge-agent:1.0
```
4. Service is now active once again
```bash
systemctl is-active iotedge
inactive
```
### Device (Host) Operating System
Ubuntu 18.04 and Raspbian 9.4

### Architecture
(amd64)
Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:    18.04
Codename:    bionic

(ARM32)
Distributor ID:    Raspbian
Description:    Raspbian GNU/Linux 9.4 (stretch)
Release:    9.4
Codename:    stretch

### Container Operating System
Linux Containers

#### iotedged
Docker version 18.06.0-dev, build daf021fe

#### Edge Agent
azureiotedge-agent:1.0

#### Edge Hub
azureiotedge-hub:1.0

#### Docker
Docker version 18.06.0-dev, build daf021fe

## Additional Information
Adding PartOf to both socket files seem to solve the issue.
```bash
root@edge-dev:/lib/systemd/system# diff -uNp iotedge.mgmt.socket.orig iotedge.mgmt.socket
--- iotedge.mgmt.socket.orig    2018-09-21 20:37:23.570646019 +0000
+++ iotedge.mgmt.socket    2018-09-21 20:22:52.066739486 +0000
@@ -1,6 +1,7 @@
 [Unit]
 Description=Azure IoT Edge daemon management socket
 Documentation=man:iotedged(8)
+PartOf=iotedge.service
 
 [Socket]
 ListenStream=/var/run/iotedge/mgmt.sock


-----------------------------------------------------------------------------------------------------------------------------------------------------------

root@edge-dev:/lib/systemd/system# diff -uNp iotedge.socket.orig iotedge.socket
--- iotedge.socket.orig    2018-09-21 20:36:06.170654322 +0000
+++ iotedge.socket    2018-09-21 20:33:38.782670129 +0000
@@ -1,6 +1,7 @@
 [Unit]
 Description=Azure IoT Edge daemon workload socket
 Documentation=man:iotedged(8)
+PartOf=iotedge.service
 
 [Socket]
 ListenStream=/var/run/iotedge/workload.sock
```
Run systemctl daemon-reload for the changes to take effect.

**Comment by myagley** [comment]
Good find! Thanks for pointing us to the fix. I'll get a PR out for it.

**Comment by dcasati** [comment]
Glad to help! :)
