### ISSUE TITLE
IoTEdge Deployment template returns a bad request when deploying with Azure CLI (azure-cli-iot-ext)

### ISSUE THREAD

**Issue by diirib** [Azure/iotedge#4]
az : ERROR: ErrorCode:GenericBadRequest;BadRequest 

I'm getting a BadRequest error when trying to run 'az iot edge deployment create'. The error is the same for templates that were valid with the preview version, and for templates valid for the new version (I'm copying the templates from a deployment created in the portal).
The code is part of deployment scripts that haven't changed and were working perfectly until today.

Templates attached for validation with sample data.

AzureCLI version: 2.0.39
azure-cli-iot-ext version: 0.4.3

UPDATE: deployment works correctly when using azure-cli-iot-ext version: 0.5.0

cc: @ralarcon

[DeploymentTemplates.zip](https://github.com/Azure/iotedge/files/2156040/DeploymentTemplates.zip)

**Comment by aribeironovaes** [comment]
@diirib , 
Can you open an issue here? https://github.com/Azure/azure-iot-cli-extension

Thanks, 

Angelo Ribeiro.

**Comment by diirib** [comment]
Done, link to the issue: https://github.com/Azure/azure-iot-cli-extension/issues/35

**Comment by aribeironovaes** [comment]
Thanks @diirib , 

Closing this issue here, since it is on cli extension. Let us know once they fix it if you still face problem on the edge part of it. 

Meanwhile I suggest you to use the portal for deployment if this is an option for you.

**Comment by aribeironovaes** [comment]
Some more comments on this issue from Paymaun: “Been on vacation. Just saw the issue including the copy in the extension repo https://github.com/Azure/azure-iot-cli-extension/issues/35. Its now resolved. The resolution is to upgrade to the latest extension version 0.5.0. This is the one sim shipped for the GA release. ”
