### ISSUE TITLE
Include check-config.sh of moby in "iotedge check" or at least a notification

### ISSUE THREAD

**Issue by SimonSimCity** [Azure/iotedge#4000]
After having used quite some time on it I finally came to the conclusion that my custom Linux kernel, built using Yocto, is not configured correctly to run container in general.

To avoid this stress on others, I want the the file to check an environment for docker compatibility, mentioned in the docs (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06&tabs=linux#install-a-container-engine) but not at all other places, to be included in the "iotedge check" command - or at least mentioned somewhere there.

**Comment by damonbarry** [comment]
@SimonSimCity I like this idea, but one problem I can see is that it would be difficult for `iotedge check` to interpret the results of `check-config.sh`. At best, it would have to interpret anything other than total success as a warning. Also, `check-config.sh` is in the contrib section of the moby repo, so there's no guarantee it will be up-to-date.

**Comment by SimonSimCity** [comment]
Since most of the tests you have there are specific to the module you built, I would see it as enough to refer to the other check. Neither is an ideal case, I think, but the tests might also be specific to the moby version, which you don't know or want to care about, right? On the other side, it's one of the non-official scripts and might be added as cases get known.

**Comment by damonbarry** [comment]
When I install a generic Ubuntu VM in Azure and install moby-engine there, I get a few warnings in the script, and it returns exit code==1. Looking inside the script, it sets the exit code to 1 for pretty much any problem it finds, regardless of whether it classifies the recommendation as necessary or optional.

I think it's a really useful script, but probably not something we can automate in `iotedged check`. We could perhaps mention it in the output of `iotedge check`, or just do a better job highlighting it in the existing install docs.
