### ISSUE TITLE
Will edgeAgent send reported property with custom module status to IoT Hub when edgeAgent is in unhealthy status

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#4005]
HI Team,

Will edgeAgent send reported property with custom module status to IoT Hub when edgeAgent is in unhealthy status... The usecase is that we want to capture the custom module and edgeHub status from edgeAgent reported property for monitoring.. So will edgeAgent still send the status to IoT Hub when it is in unhealthy status ???

**Comment by darobs** [comment]
Hello @sachidanand, 

Usually not.  It depends a bit on why the EdgeAgent module is unhealthy, but if it is not running. the reported status will not get updated.

As of release 1.0.10, we do have [more metrics offerings](https://docs.microsoft.com/azure/iot-edge/how-to-access-built-in-metrics?view=iotedge-2018-06), which may provide additional insight into the status of the Edge device.

**Comment by darobs** [comment]
Closing this issue, @sachidanand, please reopen if this didn't answer your question.
