### ISSUE TITLE
Not all SDK Languages (leaf devices) need to include `x509=true` on it's connection string

### ISSUE THREAD

**Issue by asergaz** [Azure/iotedge#4012]
This issue originates from here: https://github.com/MicrosoftDocs/azure-docs/issues/64993

I noticed that IoT Edge Repo provides a sample to connect a downstream device using DotNet Core SDK using X509 Authentication: https://github.com/Azure/iotedge/tree/master/samples/dotnet/EdgeX509AuthDownstreamDevice

In that sample we do not need to set the connection string with the flag `x509=true` .We would rather provide the X509 certificates in PEM format and leave the function `DeviceClient.Create` take care of the creation of our deviceClient and it's authentication.

I believe not all languages work the same. For example in node-sdk you will need to use the flag `x509=true` indeed: https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device_x509.js .

Please investigate this so we can create parity in functionality across SDK languages and docs reflect the same.

**Comment by asergaz** [comment]
fyi @kgremban @eustacea

**Comment by eustacea** [comment]
FYI @PProvost on need for uniform experience across SDK languages

**Comment by darobs** [comment]
Hello @asergaz,

I am working with the above people to assure this request is assigned to the correct team and person.

**Comment by darobs** [comment]
The SDK team has responded here: https://github.com/MicrosoftDocs/azure-docs/issues/64993#issuecomment-744654976

I hope this brings some clarity. Closing this issue here, but if there are more questions, you can open it on [the csharp SDK repo](https://github.com/Azure/azure-iot-sdk-csharp) and tag @sharmasejal, who is aware of this thread.
