### ISSUE TITLE
Connection refused /var/run/iotedge/mgmt.sock

### ISSUE THREAD

**Issue by Exxou** [Azure/iotedge#4025]
Hello,

I want to run IotEdge on an Ubuntu 18.04 Server.

After installing everything like described here https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06&tabs=linux. I get an error when trying to start the IotEdge Service.

`iotedge check --verbose` 

Shows me following:

> √ config.yaml is well-formed - OK
> 
> √ config.yaml has well-formed connection string - OK
> √ container engine is installed and functional - OK
> √ config.yaml has correct hostname - OK
> × config.yaml has correct URIs for daemon mgmt endpoint - Error
>     One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)
>         caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)
> 

Already tried changing the path from mgmt.sock like described in #256 but didn't help.

Is there a different workaround?

**Comment by darobs** [comment]
Assigning this to myself because it's very similar to #4011

**Comment by darobs** [comment]
I am operating under the assumption this is related to the issue I referenced above.  Please see [my comment from yesterday](https://github.com/Azure/iotedge/issues/4011#issuecomment-742722756) on the subject, if that helps.

**Comment by darobs** [comment]
Closing this issue, still tracking #4011 - please follow up in that thread or reopen this issue if you think it's a distinct problem.
