### ISSUE TITLE
unable to override DNS server in docker container

### ISSUE THREAD

**Issue by fnbk** [Azure/iotedge#4034]
Error: **curl: (60) SSL certificate problem: unable to get local issuer certificate**

By changing the hostname in /etc/iotedge/config.yaml to the real DNS name of the virtual machine results in wrong DNS resolution inside docker containers spawned by iotedge.

```
@@ -170,11 +170,11 @@
 # It is important to note that when connecting downstream devices to the
 # Edge Hub that the lower case value of this hostname be used in the
 # 'GatewayHostName' field of the device's connection string URI.
 ###############################################################################

-hostname: "demo-edge-dev-westeurope"
+hostname: "cq.demo-edge.example.com"

 ###############################################################################
 # Watchdog settings
 ###############################################################################
```

**before:** (okay)
```
$ sudo docker exec -it 775f48b041d0 bash
root@775f48b041d0:/app# openssl s_client -connect cq.demo-edge.example.com:443
...
---
Certificate chain
 0 s:CN = cq.demo-edge.example.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
...
```

**after:** (not okay)
```
$ sudo docker exec -it e216acd86681 bash
root@e216acd86681:/app# openssl s_client -connect cq.demo-edge.example.com:443
...
---
Certificate chain
 0 s:CN = cq.demo-edge.example.com
   i:CN = iotedged workload ca
 1 s:CN = iotedged workload ca
   i:CN = Test Edge Device CA
 2 s:CN = Test Edge Device CA
   i:CN = Test Edge Owner CA
---
...
```

```
$ curl https://cq.demo-edge.example.com/auth/realms/default/.well-known/openid-configuration

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

## Expected Behavior
By applying one of these two option we expect to be able to override the nameserver in /etc/resolv.conf inside the container. 

**Option 1**: Set DNS server in container engine settings
```
$ sudo vim /etc/docker/daemon.json
{
    "dns": ["8.8.8.8"]
}

$ sudo systemctl restart docker
```

**Option 2**: Set DNS server in IoT Edge deployment per module
```
"createOptions": {
  "HostConfig": {
    "Dns": [
      "8.8.8.8"
    ]
  }
}
```
[source: troubleshoot common errors](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors)

## Current Behavior
None of these two options work. The nameserver stays the same at 127.0.0.11
```
$ sudo docker exec e1b169b5863e cat /etc/resolv.conf
search y2z0k3tt1ieuxbwr4rgdckzmxf.ax.internal.cloudapp.net
nameserver 127.0.0.11
options ndots:0
```

## Steps to Reproduce
* change the  hostname in `/etc/iotedge/config.yaml` to the DNS name of the VM
* check certificate chain inside the container using `openssl s_client -connect cq.demo-edge.example.com:443`

### Output of `iotedge check`

```
$ sudo iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname cq.demo-edge.example.com but device reports hostname demo-edge-dev-westeurope.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-03-01 15:03:22 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

18 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
```

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: ubuntu 18.0
* Architecture [e.g. amd64, arm32, arm64]: x86_64
* Container OS [e.g. Linux containers, Windows containers]: Linux Containers

### Runtime Versions

* iotedged [run `iotedge version`]: iotedge 1.0.10.2
* Edge Agent [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-agent:1.0
* Edge Hub [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-hub:1.0
* Docker/Moby [run `docker version`]: 
```
sudo docker version
Client:
 Version:           19.03.12+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        0ed913b885c8919944a2e4c8d0b80a318a8dd48b
 Built:             Wed Jun 17 17:27:03 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       9dc6525e6118a25fab2be322d1914740ea842495
  Built:            Mon Mar 12 00:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.6+azure
  GitCommit:        be75852b8d7849474a20192f9ed1bf34fdd454f1
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:
```

**Comment by dmolokanov** [comment]
Hello @fnbk ! Could you help me to understand what are you trying to achive with the setup? From `iotedge check` command response I assume you have an EdgeDevice which is using self-signed certificate. 
```
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-03-01 15:03:22 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
```

then you changed config.yaml hostname settings to `cq.demo-edge.connected-quality.com` which is different from the system settings on the machine `demo-edge-dev-westeurope`. They are should be identical.
```
× config.yaml has correct hostname - Error
    config.yaml has hostname cq.demo-edge.connected-quality.com but device reports hostname demo-edge-dev-westeurope.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
```

You are trying to resolve a hostname from custom docker container using device hostname and port 443 and see EdgeHub server certificate chain. Which seems like correct behavior.
```
$ sudo docker exec -it e216acd86681 bash
root@e216acd86681:/app# openssl s_client -connect example.com:443
...
---
Certificate chain
 0 s:CN = example.com
   i:CN = iotedged workload ca
 1 s:CN = iotedged workload ca
   i:CN = Test Edge Device CA
 2 s:CN = Test Edge Device CA
   i:CN = Test Edge Owner CA
---
...
```

If your intention was to reach HTTPS endpoint from the custom module you need to change port binding in your module. If that was not the intention please give us more information.

**Comment by fnbk** [comment]
Hi @dmolokanov  Thanks for your response and your interest.

**important:**
Could you please rename `cq.demo-edge.connected-quality.com` into `cq.demo-edge.example.com` in your **previous** post? (that would be awesome, because it is a privacy issue - I will delete this line after you change it).

## Lets elaborate a little bit more about our setup

**ssl termination:**
* We use Traefik as a reverse proxy to expose multiple backend services using different url paths. (e.g https://cq.demo-edge.example.com/serviceA/ or https://cq.demo-edge.example.com/serviceB/).
* For any iotEdge communication we expose SSL secured ports 5671 and 8883 in the iotHub module.

**certificate generation:**
* The traefik module uses LetsEncrypt to generate its certificate.
* The iotHub module generates its own certificates using an intermediate certificate from microsoft.

**Why did we change the hostname in /etc/iotedge/config.yaml?**

By changing the hostname we make sure that the iotHub generated certificate is valid for clients that establish connections on ports 5671 and 8885 (e.g https://cq.demo-edge.example.com:8883).
Specifically: In our case we consume data from a different iotEdge Device. 



But the actual problem should have nothing to do with this setup. 

## Here is our problem:

**How can we change the hard coded value `nameserver 127.0.0.11` in /etc/resolv.conf inside containers?**

The documentation gives us at least two options:

**Option 1**: Set DNS server in container engine settings
```
$ sudo vim /etc/docker/daemon.json
{
    "dns": ["8.8.8.8"]
}

$ sudo systemctl restart docker
```

**Option 2**: Set DNS server in IoT Edge deployment per module
```
"createOptions": {
  "HostConfig": {
    "Dns": [
      "8.8.8.8"
    ]
  }
}
```
[source: troubleshoot common errors](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors)


**If we could apply any of these options we are good to go. Can you help find out why these changes do not apply?**

**Comment by dmolokanov** [comment]
I deleted private information from all messages in the thread. Initially I thought this was a miconfiguration. I'll try to repro the issue on my side and get back to you.

**Comment by dmolokanov** [comment]
I did some investigation and what you see seems like expected behavior. All iotedge modules run inside the custom docker network "azure-iot-edge". In this case there is docker embedded dns comes into play (you see its ip address 127.0.0.11). "Dns" section in the "HostConfig" or in the daemon.json used by the embedded dns server when it fails to resolve an ip address for the given hostname as per documentation http://docs.docker.oeynet.com/engine/userguide/networking/configure-dns/ . I assume you should solve your issue with different approach and not setting dns address.

Could you elaborate more on your setup?
So you have and edge installed on one device. edge runs multiple modules: edgeAgent, edgeHub(443, 5671, 8883), traefik, serviceA(XXX1), serviceB(XXX2).
Expectation is that when someone **outside** of edge device calls https://cq.demo-edge.example.com/serviceA/ or https://cq.demo-edge.example.com/serviceA/ request is forwarded to corresponding module (serviceA or serviceB).
When someone inside the edge device (serviceX) wants to call edgehub https://cq.demo-edge.example.com it will still use FQDN on the device.

**Comment by fnbk** [comment]
@dmolokanov Thank you for pointing to the docker dns configuration.

We solved this issue by creating a second DNS record for the edge device.

The first one covers all external requests on port 443 (cq.demo-edge.example.com) and resolves to the LetsEncrypt generated certificate. 

And the second one on port 8883 (iot.demo-edge.example.com) provides an endpoint to external edge devices that use this machine as a GatewayHost (resolves to edge generated certificates).
