### ISSUE TITLE
Configuration of a HTTP(s) proxy is impractical for deployment at customer sites

### ISSUE THREAD

**Issue by randomstring384540** [Azure/iotedge#4053]
Hello,

we are having a bit of trouble with the way iotedge handles HTTP(s)-Proxy configuration.
Maybe we missed a way to configure the HTTP(s)-Proxy, but our Microsoft contact suggested we raise a ticket here.

## Current State
Right now a HTTP(s) proxy for an iotedge needs to be configured
- locally in /etc/iotedge/config.yml (and required linux daemons)
- and in IoT Edge deployment (IoT Hub) via
  - edgeAgent environment variable https_proxy
  - edgeHub environment variable https_proxy

Therefore each edge deployed at a customer site with a proxy needs a custom deployment in IoT Hub.

## Problem(s)
This poses several problems
- customer passwords need to be stored in IoT hub
  - which then need to be kept in sync with local proxy configuration
  - which we'd prefer not to do security-wise
  - customer IT departements prefer not to do
- a seperate deploymend needs to be defined / managed for each IoT edge
- it is not possible to offer the customer a Web-GUI to configure and check connection to IoT hub

## Possible Solutions / Workarounds
This problem could be solved
- if iotedge was able to import proxy settings from etc/iotedge/config.yml
- or if iotedge allowed importing enviroment variables for docker containers like docker does (using --env <VarName> without a value)
- or if iotedge supported the use of --env-file

**Comment by vipeller** [comment]
@randomstring384540 thank you for your feedback, it is a very good summary of valid concerns. May I ask you to copy this post to:

https://feedback.azure.com/forums/907045-azure-iot-edge

This is the site project managers use to weight and prioritize developments.
Thank you!

**Comment by randomstring384540** [comment]
Hello @vipeller , 
thanks for the heads up. I've added the suggestion at: https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/42149611-improve-configuration-of-http-s-proxy-for-deploym
