### ISSUE TITLE
X.509 does not restore provisioning result after reboot in offline state

### ISSUE THREAD

**Issue by emilm** [Azure/iotedge#4062]
## Expected Behavior
Agent + modules etc should run offline after a reboot

## Current Behavior
iotedge fails to even start

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. provision with X.509
2. let everything pull and load and run
3. rip out ethernet cable so it's offline
4. reboot

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [yocto linux]: 
* Architecture [arm32: 
* Container OS [linux]: 

### Runtime Versions
* iotedged [iotedge 1.0.9 (9161dc8eb743c1e839cc7fec07ad3e7df085a42f)]: 
* Edge Agent [1.0.9.1-linux-arm32v7]: 
* Edge Hub [1.0.9.1-linux-arm32v7]: 
* Docker/Moby [19.03.2]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

iotedge.service: Main process exited, code=exited, status=1/FAILURE
iotedge.service: Failed with result 'exit-code'.
iotedge.service: Service RestartSec=10s expired, scheduling restart.
iotedge.service: Scheduled restart job, restart counter is at 23.
Stopped Azure IoT Edge daemon.
Started Azure IoT Edge daemon.
[INFO] - Starting Azure IoT Edge Security Daemon
[INFO] - Version - 1.0.9 (f1554690f539dc53fac0cacb4fc226a159baa45d)
[INFO] - Using config file: /data/iotedge/config.yaml
[INFO] - Configuring /data/iotedge/home as the home directory.
[INFO] - Configuring certificates...
[INFO] - Configuring the Device CA certificate using "/etc/iotedge/certs/iot-edge-device-iot-device-full-chain.cert.pem".
[INFO] - Configuring the Device private key using "/etc/iotedge/certs/iot-edge-device-iot-device.key.pem".
[INFO] - Configuring the trusted CA certificates using "/etc/iotedge/certs/azure-iot.root.ca.cert.pem".
[INFO] - Finished configuring provisioning environment variables and certificates.
[INFO] - Initializing hsm...
[INFO] - Finished initializing hsm.
[INFO] - Initializing hsm X509 interface...
[INFO] - Finished initializing hsm X509 interface...
[INFO] - Provisioning edge device...
[INFO] - Starting provisioning edge device via X509 provisioning...
[INFO] - Starting DPS registration with scope_id "<redacted>", registration_id "<redacted>"
[WARN] - Could not provision device
[WARN] -         caused by: X509 certificate based registration failed
[WARN] -         caused by: Could not perform HTTP request
[WARN] -         caused by: an error occurred trying to connect: failed to lookup address information: Temporary failure in name resolution
[ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
[ERR!] -         caused by: Could not restore previous provisioning result
[ERR!] -         caused by: No such file or directory (os error 2)
iotedge.service: Main process exited, code=exited, status=1/FAILURE
iotedge.service: Failed with result 'exit-code'.


```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
This works fine with TPM auth. Where is the "previous provisioning result" stored?
Note: This does really work when the device is online, so there's nothing wrong with the certificates themselves.
I need to know if it's to be expected to fail like this in 1.0.9.x or if it's fixed in newer versions so I have to plan to upgrade.

Thanks!

**Comment by vipeller** [comment]
@emilm version 1.0.10 creates a backup provisioning file, so edge can keep working offline when DPS is configured. Unfortunately, you need to update to use DPS in offline scenario.

**Comment by emilm** [comment]
Thanks @vipeller ! It seems to work with 1.2-rc2. I assume the backup path is in the specified IoT edge "home" dir?
The reason I am not using a stable version, is that I have to match it with a specific version of Rust.
The previous versions of iot edge source had "#![deny(rust_2018_idioms, warnings)]" in them which made the linter in Rust 1.46 stop the compilation. I am no Rust expert though.

Is there a pairing / matching with a specific Rust version each release has? Or could 1.2-rc2 be stable enough for production use?

Thanks!

**Comment by vipeller** [comment]
@emilm can I ask why the rust version matters? We usually use the latest stable version, and before release, we pin that version - then it can take several weeks or 1-2-3 months for the final release, so the rust version will not keep up with the latest stable anymore.
I would not recommend 1.2 for production yet, it has massive changes in its internal structure compared to the previous versions - especially if you plan to use MQTT protocol between the devices and EdgeHub. 1.2 is intended to demonstrate some big new features (e.g. built in generic mqtt broker, nested scenario)

**Comment by emilm** [comment]
@vipeller in a yocto environment I use meta-rust which is the source code for entire Rust.
1.0.10.3 did not compile with 1.39 (too old?) or 1.46 (because of some language / linting features like #![deny(rust_2018_idioms, warnings)]. ) of rust . So it's relevant for me to see which version of Rust you compile against.

**Comment by vipeller** [comment]
@emilm how things has been going, do you need any more assistance?

**Comment by emilm** [comment]
@vipeller I ran into another problem with certificates. A device might not have RTC and thus the date is back to 1970 without internet. 
Then I get "edge_pki_openssl.c:check_certificates:1775) Verification status: 0, Error: 9, Msg: 'certificate is not yet valid'"
Is there some way to mitigate this except having the correct date?

This causes the message " Obtaining workload CA failed. Triggering reconfiguration"
"Removing all modules..."

Then since modules are gone, then it fails as in the main issue "caused by: error trying to connect: failed to lookup address information: Temporary failure in name resolution"

**Comment by vadim-kovalyov** [comment]
@emilm, I believe you must have correct datetime set in the system. Cert has 'not before" and "not after" validity properties, so it fails the validation. Please let us know if you have any other issues. I'm closing this one for now.
