### ISSUE TITLE
X509 certificate with a TPM private key

### ISSUE THREAD

**Issue by motto-phytec** [Azure/iotedge#4074]
In an project we must use x509 certificate authentication with access to a private key, which is stored in a TPM.
There is a configuration example with x509 and private key, which is stored as file. 
provisioning:
  source: "manual"
  authentication:
    method: "x509"
    iothub_hostname: "xxx.azure-devices.net"
    device_id: "board01"
    identity_cert: "file:///home/cert.pem"
    **identity_pk: "file:///home/key.pem"**
  dynamic_reprovisioning: false

Which URI's are supported for identity_pk? pkcs11 or ... ?
Which encryptions are supported for the certificates? RSA-xyz, ECC-xyz?!

**Comment by vipeller** [comment]
@motto-phytec Hello,

Sorry for the late answer. 
For identity_cert/pk, currently files paths are supported.
The certificate must be in DER format or PEM format (which is a base64 encoded DER format with a header/footer)
The private key can be in PEM format of PKCS12 format
Both RSA and ECC based certificates (and keys) are supported

Let me know if you have problems generating the necessary keys/certificates

**Comment by varunpuranik** [comment]
@motto-phytec - were you able to solve the issue with @vipeller's suggestions?
