### ISSUE TITLE
Is there a way to create a container in local blob storage module (IoT Edge)?

### ISSUE THREAD

**Issue by JoshuaRoi** [Azure/iotedge#4089]
Good Day,

You need to create a container in local blob storage in IoT Edge with the help of Azure Storage Explorer but is there another way to add a container w/o using the explorer?
Cause I'm having trouble accessing the deployed blob storage in the Storage Explorer, I followed every steps in this source:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob?view=iotedge-2018-06#connect-to-your-local-storage-with-azure-storage-explorer

I tried using Windows VM and Linux VM and I can ping both VMs but still I received the same errors. 
The Azure Storage Explorers I used is v1.5, v1.14, v1.16.
Any tips?

**Comment by vadim-kovalyov** [comment]
Hi @JoshuaRoi, it looks like you were able to resolve the issue with Azure Storage Explorer - https://github.com/microsoft/AzureStorageExplorer/issues/3887. I'm closing this one.
