### ISSUE TITLE
EdgeAgent fails to create device-to-cloud connection

### ISSUE THREAD

**Issue by alkreddy** [Azure/iotedge#409]
## Expected Behavior
Properly configured edge runtime should be able to connect and start edgeHub and other configured modules

## Current Behavior
EdgeAgent fails with the following message...
2018-10-10 10:46:22.338 +05:30 [WRN] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Operation timeout expired.) (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.

## Steps to Reproduce

1. On a new Windows 10 (Oct 2018 update) environment, Install an configure EdgeRuntime
2. Configure the device in cloud to set one test module
3. Notice only edgeAgent module running and no other modules are running
4. EdgeAgent container logs reveal the error related to failed device to Cloud connection (timeout)

### Device (Host) Operating System

Windows 10 Pro 1809 - Build 17763.1

### Architecture

amd64
### Container Operating System

Windows containers
#### iotedged

iotedge 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent   1.0                 b25d59087659        2 weeks ago         474MB
#### Docker

Docker version 18.06.1-ce, build e68fc7a

## Logs

[logs.txt](https://github.com/Azure/iotedge/files/2462852/logs.txt)

**Comment by myagley** [comment]
Thanks for the issue report. This is most likely a network issue, preventing the Edge Agent from getting internet connectivity. Do you have any firewalls in place that could be preventing a connection?

What is the output of `docker network inspect nat`?

**Comment by alkreddy** [comment]
Thanks @myagley . I too suspect it to be NW related. However, I could not address it on my own. Here's the output from `docker network inspect nat`

[
    {
        "Name": "nat",
        "Id": "67ae88e440c76810932337030c2e88d0456505bad83d3aa319f7e9f719266970",
        "Created": "2018-10-10T17:50:43.0140406+05:30",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "192.168.16.0/20",
                    "Gateway": "192.168.16.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.windowsshim.hnsid": "2ED9F926-2BE8-4733-8977-BAFEC5FDC955",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }
]

**Comment by alkreddy** [comment]
@myagley , if you haven't noticed, I have Oct 2018 update (release 1809) on my computer; if that has any influence

**Comment by myagley** [comment]
I ran through the setup on a machine with 1809 and the Edge Agent can connect to the internet. It's interesting that the subnet for the nat network above is a `192.168.16.0/20`. This is usually something like a  `172.23.48.0/20`.

For instance, this is the output from this machine:

```json
[
    {
        "Name": "nat",
        "Id": "8c895f6eff68e60eb9b2e13fb52c7d97a1bed66611f3df43146928784146db79",
        "Created": "2018-10-10T09:23:36.4123155-07:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.23.48.0/20",
                    "Gateway": "172.23.48.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "83c0b303a0996e4c9c2c6c0da4407615c783f7d2ab271bf79b3ff49c6423f615": {
                "Name": "edgeHub",
                "EndpointID": "d5c5441904f51f04d2f71a481ba9a305a8a52e1bfac27605f26d6faf2c684d06",
                "MacAddress": "00:15:5d:2c:c8:75",
                "IPv4Address": "172.23.48.77/16",
                "IPv6Address": ""
            },
            "c59a4e8590e295ae0d6f41a9f598ba6b0d365f7f6840abd508eb189265c7b315": {
                "Name": "tempSensor",
                "EndpointID": "d10ed2c18a9346ad5dce6cca417a744bb03048ffe3372b015e4996d338004e11",
                "MacAddress": "00:15:5d:2c:c2:78",
                "IPv4Address": "172.23.51.106/16",
                "IPv6Address": ""
            },
            "e504cdb0793f273323176e3afaf6b86f685f4b0b27f304fc0299ba0b1dd30551": {
                "Name": "edgeAgent",
                "EndpointID": "0bf64d942b480b5231036f90e0bd28be4fd9a00b83a9fa4334617d1335e1b896",
                "MacAddress": "00:15:5d:2c:c9:84",
                "IPv4Address": "172.23.53.6/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "562682EA-9136-48E8-9E35-5EC2E0338058",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }
]
```

**Comment by myagley** [comment]
The default network configuration on windows is `nat`. Is it possible that the addresses chosen are conflicting with other addresses on the network?

Is the device that this is running on behind a firewall or on some type of more sophisticated network (corporate intranet for instance)?

**Comment by alkreddy** [comment]
@myagley Appreciate you help and apologies for delayed response.
I do understand that Windows Containers use `nat' network. I doubt on the conflict. This environment is from my home network while not on VPN.  My understanding with networking is limited and I don't have a way to analyze this further. 
For the time being, I have switched to Linux Containers

**Comment by myagley** [comment]
Is this still an issue?

**Comment by myagley** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen.
