### ISSUE TITLE
Iotedge behind a proxy 

### ISSUE THREAD

**Issue by omarine** [Azure/iotedge#4092]
## Expected Behavior
iotedge behind a proxy should work

## Current Behavior
the edgeAgent coudn't start 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.Install IotEdge via proxy (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2018-06)
2.Get-Service iotedge
3.iotedge list

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    docker: Error response from daemon: container 93eaebe6cbfa2e193d6822bc7aa51b31efc6ef89c035213b406430076635621a encountered an error during hcsshim::System::Start: context deadline exceeded.
    time="2020-12-14T14:12:43+01:00" level=error msg="Error waiting for container: container 93eaebe6cbfa2e193d6822bc7aa51b31efc6ef89c035213b406430076635621a: driver \"windowsfilter\" failed to remove root filesystem: failed to detach VHD: Le périphérique n’est pas prêt.: rename C:\\ProgramData\\iotedge-moby\\windowsfilter\\93eaebe6cbfa2e193d6822bc7aa51b31efc6ef89c035213b406430076635621a C:\\ProgramData\\iotedge-moby\\windowsfilter\\93eaebe6cbfa2e193d6822bc7aa51b31efc6ef89c035213b406430076635621a-removing: Accès refusé."
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
× container time is close to host time - Error
    Could not query local time inside container
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-03-14 10:29:52 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the nat network could not connect to darwin-prd-iot-ingress-ne-iothub03.azure-devices.net:5671
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the nat network could not connect to darwin-prd-iot-ingress-ne-iothub03.azure-devices.net:443
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the nat network could not connect to darwin-prd-iot-ingress-ne-iothub03.azure-devices.net:8883

10 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
6 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [Windows 10 (1809)]: 
* Architecture [amd64,]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* iotedged [1.0.10.2]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

14/12/2020 18:38:45 debug: hyper::proto::h1::io -- parsed 7 headers
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 warn: edgelet_utils::logging -- Could not start module edgeAgent
14/12/2020 18:38:45 warn: edgelet_utils::logging --     caused by: hcsshim::System::Properties 851e0bd460c1f1165cf803ff18e2d67b8027bac5e17a977121a996db2836d49d: L'opération demandée pour l'ordinateur virtuel ou le conteneur n'est        
                    actuellement pas valide.
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: hyper::client::pool -- pooling idle connection for "npipe://5c5c2e5c706970655c696f74656467655f6d6f62795f656e67696e65"
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 2 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 info: edgelet_core::watchdog -- Checking edge runtime status
14/12/2020 18:38:45 warn: edgelet_utils::logging --     caused by: hcsshim::System::Properties 851e0bd460c1f1165cf803ff18e2d67b8027bac5e17a977121a996db2836d49d: L'opération demandée pour l'ordinateur virtuel ou le conteneur n'est        
                    actuellement pas valide.
14/12/2020 18:38:45 debug: hyper::client::pool -- reuse idle connection for "npipe://5c5c2e5c706970655c696f74656467655f6d6f62795f656e67696e65"
14/12/2020 18:38:45 debug: edgelet_docker::runtime -- Listing modules...
14/12/2020 18:38:45 warn: edgelet_utils::logging --     caused by: Could not start module edgeAgent                                                                                                                                          
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 warn: edgelet_utils::logging -- A module runtime error occurred.
14/12/2020 18:38:45 warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::io -- flushed 258 bytes
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::io -- parsed 7 headers
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::conn -- incoming body completed
14/12/2020 18:38:45 debug: hyper::proto::h1::conn -- incoming body is content-length (1289 bytes)
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::io -- read 1504 bytes
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: hyper::client::pool -- pooling idle connection for "npipe://5c5c2e5c706970655c696f74656467655f6d6f62795f656e67696e65"
14/12/2020 18:38:45 debug: edgelet_docker::runtime -- Successfully listed modules
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::io -- flushed 145 bytes
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: hyper::client::pool -- reuse idle connection for "npipe://5c5c2e5c706970655c696f74656467655f6d6f62795f656e67696e65"
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::io -- read 4096 bytes
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 2 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::conn -- incoming body is chunked encoding
14/12/2020 18:38:45 debug: hyper::proto::h1::decode -- incoming chunked header: 0x12D5 (4821 bytes)
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 2 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::io -- parsed 7 headers
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::conn -- incoming body completed
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::proto::h1::io -- read 959 bytes
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::client::pool -- pooling idle connection for "npipe://5c5c2e5c706970655c696f74656467655f6d6f62795f656e67696e65"
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 info: edgelet_docker::runtime -- Starting module edgeAgent...
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 0 events, 0.000s
14/12/2020 18:38:45 debug: tokio_reactor -- loop process - 1 events, 0.000s
14/12/2020 18:38:45 debug: hyper::client::pool -- reuse idle connection for "npipe://5c5c2e5c706970655c696f74656467655f6d6f62795f656e67696e65"

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

N/A 



<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

N/A

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

docker -H npipe:////./pipe/iotedge_moby_engine run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
21be49aa856f: Pull complete
8d3bdee7e2fc: Pull complete
0a3419bde20a: Pull complete
Digest: sha256:1a523af650137b8accdaed439c17d684df61ee4d74feac151b5b337bd29e7eec
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: container 9b79d1d6c02fd1c64c90bffb5cf96b14adce0016c3cdca21174a6a93f5a1d6ca encountered an error during hcsshim::System::Start: context deadline exceeded.

**Comment by dylanbronson** [comment]
Hi, did you follow the steps to configure the Moby Daemon? I ask because it looks like there are some issues with docker commands.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#proxy-configuration

This article is linked in the proxy article, but can be easy to miss. You must also configure the IoT Edge daemon with the https_proxy variable (also linked in the original link you attached).

**Comment by omarine** [comment]
Hello,

I think i did everything mentioned in the documentation ,I have  HTTPS_PROXY configured as a machine variable environment but still the containers seem not to be able to connect to Iothub,still i was able to install the edge runtime via the proxy.

does anyone encountered the same issue ?

**Comment by omarine** [comment]
here is the configuration of the proxy 

![image](https://user-images.githubusercontent.com/13197345/102232180-17a92900-3eef-11eb-9e2b-d41b383d350e.png)

I put the dns in the daemon.json but is there a way to tell the iotedge-mody to bypass the proxy ?

thanks

**Comment by omarine** [comment]
Actually,this dns is only useful to resolve name for  resources on the vpn ,while containers on nat network try to resolve  iothub hostname,is it possible  to use (iothub) ips instead of hostname  so no name resolution is needed ?

**Comment by dylanbronson** [comment]
It is weird that your docker hello world is not working. If that is not working, then your edge containers also probably won't work. Can you try reinstalling docker? It seems like a docker/moby problem you are running into, though

For your other question: I don't think you can use the IoTHub IP instead of the hostname because it will have cert issues (the cert uses the hostname, not the IP). I just tried this and it didn't work as expected.

**Comment by Prov-Matthias** [comment]
Hi, I have a similar Issue but this has nothing to do with the Proxy Server.

My Solution was descripted here: https://github.com/Azure/iotedge/issues/3680#issuecomment-706059515

Maybe it is working for you too ;)

**Comment by omarine** [comment]
Well i am trying to resolve and be able to run a hello-work container on this machine,once it's resolvec i am thinking of launching the iotedge modules on the host network

so do you think  these steps are enough for the module to be able to access the iothub since the host has no connectivity issues with the iothub ?


- docker -H network create --driver transparent trans

- change the network setting in the config.yaml file from "nat" to "trans". 

Thanks in advance

**Comment by omarine** [comment]
Connection fixed when in used docker destop but edgeAgent failed to start  

2020-12-18 17:41:12.947 +00:00 Edge Agent Main()
<6> 2020-12-18 18:41:13.312 +01:00 [INF] - Initializing Edge Agent.
<6> 2020-12-18 18:41:13.581 +01:00 [INF] - Version - 1.0.10.3.36904102 (95aa3cb67f16386be6c76e83feeb6538f6e040b9)
<6> 2020-12-18 18:41:13.582 +01:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-12-18 18:41:13.605 +01:00 [INF] - Detected proxy http://10.65.32.4:3128/
<6> 2020-12-18 18:41:13.640 +01:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<3> 2020-12-18 18:41:13.793 +01:00 [ERR] - Shutting down because no response from unix:///C:/ProgramData/iotedge/workload/sock for TrustBundleAsync
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): No connection could be made because the target machine actively refused it. C:\ProgramData\iotedge\workload\sock
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
   at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.GetConnectedSocketAsync() in C:\agent\_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 47
   at Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\agent\_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\uds\HttpUdsMessageHandler.cs:line 23
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in C:\agent\_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\version_2019_01_30\generatedCode\HttpWorkloadClient.cs:line 700
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in C:\agent\_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 126
   at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\edged\WorkloadClientVersioned.cs:line 59

**Comment by dylanbronson** [comment]
Thanks for your patience, and I'm sorry you are still having issues. 

It looks like edgeAgent isn't starting because iotedged isn't running. Are you trying to run edgeAgent with a docker start command or something similar? 

EdgeAgent should be started by the iotedge daemon (iotedged) and not by docker.

Additionally, I don't think you need to create a new network. I believe that could work (I've never done it though), but I'm not sure how it would help your situation. It is also not recommended for security reasons to have the modules running on the host network. 

If the docker HTTPS_PROXY variable is configured correctly, you shouldn't need to go to the host network. Did you end up reinstalling the Moby engine? (then resetting HTTPS_PROXY, then restarting docker). And are you able to see that hello-world is running correctly?

**Comment by omarine** [comment]
Hi,

sorry for not answering back ,

I may give it another shot,but rather try to launch my module as a standalone and have it a child of a  an edgedevice (transparent gateway ) 

i just need to figure out now how  my connection string should  look like considering the proxy we use to connect to the outside world .

**Comment by micahl** [comment]
Closing this issue as it has gone stale.
