### ISSUE TITLE
iotedge configures listening sockets incorrectly and exchanges wrong messages

### ISSUE THREAD

**Issue by roicostas** [Azure/iotedge#41]
This issue may be related to #14 

Iotedge listens randomly in work and management sockets. It seems that the configuration is correct but messages between agent and iotedge daemon are exchanged in the wrong sockets. Example, /systeminfo?api-version=2018-06-28 should go to management socket and not to work socket.

I solved this using unix sockets configuration (it sets wrong permissions) and running edgeHub and all container modules as root. 

The following configuration worked every time we have configured a new device and some others but failed eventually.

--systemd and os version --
systemd 219
rhel7.5

-- iotedge configuration --
connect:
  management_uri: "unix:///var/run/iotedge/mgmt.sock"
  workload_uri: "unix:///var/run/iotedge/workload.sock"
listen:
  management_uri: "fd://mgmt.socket"
  workload_uri: "fd://workload.socket"

-- iotedge.service --
[Service]
Environment="LISTEN_FDNAMES=workload.socket:mgmt.socket"
ExecStart=/usr/bin/iotedged -c /etc/iotedge/config.yaml
-- iotedge.socket --
[Socket]
ListenStream=/var/run/iotedge/mgmt.sock
-- iotedge.mgmt.socket --
[Socket]
ListenStream=/var/run/iotedge/workload.sock

-- Iotedge logs --
jul 19 06:48:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:27Z [INFO] - Starting management API...
jul 19 06:48:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:27Z [INFO] - Listening on **fd://mgmt.socket/** with 1 thread for management API.
jul 19 06:48:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:27Z [INFO] - Starting workload API...
jul 19 06:48:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:27Z [INFO] - Listening on **fd://workload.socket/** with 1 thread for workload API.
jul 19 06:48:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:27Z [INFO] - Starting watchdog with 60 second frequency...
jul 19 06:48:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:27Z [INFO] - Checking edge runtime status
jul 19 06:48:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:27Z [INFO] - Edge runtime status is failed, starting module now...
jul 19 06:48:32 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:48:32Z [INFO] - [**work**] - - - [2018-07-19 06:48:32.149104654 UTC] "GET **/systeminfo?api-version=2018-06-28 HTTP/1.1" 404 Not Found** - "-" "-" pid(2
jul 19 06:49:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:49:27Z [INFO] - Checking edge runtime status
jul 19 06:49:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:49:27Z [INFO] - Edge runtime status is failed, starting module now...
jul 19 06:49:29 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:49:29Z [INFO] - [work] - - - [2018-07-19 06:49:29.516516891 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 404 Not Found - "-" "-" pid(2
jul 19 06:50:27 dev-logs-fg-01 iotedged[2300]: 2018-07-19T06:50:27Z [INFO] - Checking edge runtime status

-- agent docker configuration --
            "Env": [
                ...
                "Mode=iotedged",
                "IOTEDGE_WORKLOADURI=**unix:///var/run/iotedge/workload.sock**",
                "IOTEDGE_APIVERSION=2018-06-28",
                "IOTEDGE_MODULEID=$edgeAgent",
                "IOTEDGE_AUTHSCHEME=sasToken",
                "IOTEDGE_MANAGEMENTURI=**unix:///var/run/iotedge/mgmt.sock**",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true",
                "DOTNET_VERSION=2.1.0"
            ]
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/run/iotedge/workload.sock",
                "Destination": "/var/run/iotedge/workload.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/run/iotedge/mgmt.sock",
                "Destination": "/var/run/iotedge/mgmt.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }

-- agent logs --
I dont have them anymore but they show the "404" error when getting system info.

**Comment by darobs** [comment]
Thank you, @roicostas 

You are correct. We have the same problem with Debian 8 - the named socket support doesn't work like we want on the installed version of systemd on RHEL 7.5.

Your workaround: 

> I solved this using unix sockets configuration (it sets wrong permissions) and running edgeHub and all container modules as root.

is one way to handle it, in issue #14, we also suggested:

> As a workaround, you can skip using the systemd socket activation altogether, and specify connect  and listen addresses in the config file to a different directory (using the unix scheme). This directory needs to be writable by the iotedge user, as we need to unlink when binding.

I'm going to add this to our task list for supporting Red Hat.

**Comment by myagley** [comment]
This has been addressed with #113 and will make it into the next release. You should be able to use the `unix` scheme in the `listen` now, and properly inherit the uds permissions.

**Comment by myagley** [comment]
This has been fixed in version 1.0.1 of the `iotedged`. Closing this issue.
