### ISSUE TITLE
EdgeAgent: Failed to update reported properties

### ISSUE THREAD

**Issue by szymonprokopiuk** [Azure/iotedge#411]
## Expected Behavior
Properly configured edge runtime should be able to connect and start edgeHub and other configured modules

## Current Behavior
EdgeAgent fails with the message:
` Processing subscription Methods for client rpi/$edgeHub.
2018-10-11 06:11:48.820 +00:00 [WRN] - Failed to update reported  properties for rpi/$edgeHub with error Object reference not set to an instance of an object.`

## Steps to Reproduce
1. https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module on raspberryPi 2b
2. Deploy modules
3. Notice that edgeAgent is failing

### Device (Host) Operating System
RaspberryPI 2B with Raspbian GNU/Linux 9 (stretch)

### Architecture
arm32v7

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)

#### Edge Agent
Image tag 1.0

#### Edge Hub
Version - 1.0.2.16940264 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)

#### Docker
18.06.0-dev

## Logs
[logs](https://gist.github.com/szymonprokopiuk/196b604e63ef038edef983e21bacf70a)

**Comment by avranju** [comment]
Thanks for reporting this issue. Let me investigate and get back to you.

**Comment by szymonprokopiuk** [comment]
Have same problem on RaspberryPi 3

**Comment by myagley** [comment]
This was fixed in https://github.com/Azure/iotedge/pull/494 but hasn't been released yet. We are targeting a release in the next week or two.

**Comment by myagley** [comment]
This has been fixed in the 1.0.5 release. More information on upgrading is here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge
