### ISSUE TITLE
Linux "networking.md" / "images/iotedge-network.png" wrong Edge Agent network description/visualization

### ISSUE THREAD

**Issue by sulaga** [Azure/iotedge#4124]
## Expected Behavior
The documentation of the file "networking.md" under "iotedge\doc" is not correct for linux at the point, where the Edge Agent docker network is described. The Edge Agent is not placed on the `azure-iot-edge` network, but on the docker `bridge` network.

Also the image under "images/iotedge-network.png" needs to be corrected.

## Current Behavior
On Linux, iotedged creates a user-defined network named azure-iot-edge when it boots for the first time. It also starts the Edge Agent and places it on the azure-iot-edge network.

**Comment by sulaga** [comment]
Meanwhile I recognized, that in the newer version (tested with version 1.0.10 of iotedged, edgeAgent, edgeHub) the behavior changed and the documentation is then correct. Therefore, this was not the case for previous versions.

Did you change this consciously in the meantime (edgeAgent not anymore in `bridge` network, but also in `azure-iot-edge` network)?

Many thanks

**Comment by dylanbronson** [comment]
Hello! This was a deliberate change we made. You can read more on it here: https://github.com/Azure/iotedge/pull/2318
The documentation reflects what is on the current branch. So in the current branch it is up to date, but 1.0.9 and earlier had the older documentation.

Here's a link to the **old** documentation: https://github.com/Azure/iotedge/blob/release/1.0.9/doc/networking.md

**Comment by dylanbronson** [comment]
If this did not answer your question, feel free to reopen!

**Comment by sulaga** [comment]
Hi @dylanbronson! Many thanks for the explanatory notes. Then also for me the issue is closed.
