### ISSUE TITLE
mcr.microsoft.com/azureiotedge-hub:1.2.0-rc3 not found

### ISSUE THREAD

**Issue by gimmi** [Azure/iotedge#4148]
Hi,

following the announcement [HERE](https://github.com/Azure/iotedge/releases/tag/1.2.0-rc3), I'm trying to update my installation, but:

```
> docker pull mcr.microsoft.com/azureiotedge-hub:1.2.0-rc3
Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-hub:1.2.0-rc3 not found: manifest unknown: manifest tagged by "1.2.0-rc3" is not found
```

**Comment by vadim-kovalyov** [comment]
Hi @gimmi, thanks for being interested in `rc3` release. I know it might be confusing, but our official release page is this one - https://github.com/Azure/azure-iotedge/releases. We did cut the bits but it'll take some time till the images are ready and published. Follow the announcements on the page mentioned above.
