### ISSUE TITLE
E:Error while installing IoTEdge on Debian 10 with ARM64

### ISSUE THREAD

**Issue by kjayantmenon** [Azure/iotedge#4157]
To install IoTEdge on our device, powered by ARM 64 running Debian 10, I've been try to follow the [documentation]( https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06&tabs=linux.), while making the necessary changes for Debian 10. 
After multiple failure, I took cue from this [issue](https://github.com/MicrosoftDocs/azure-docs/issues/33881), and directly edited the **sources.list** and added the entry:

deb [arch=arm64] https://packages.microsoft.com/debian/10/prod buster main
 
After this the issue of "moby-engine not found" and the installation seemed to go off without any hitch. 
But, the container engine does not start. Post this tried using to **systemctl** to start like this: 
``` 
systemctl start iotedge
```
The failure reported was :

● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-12-24 05:37:50 UTC; 24s ago
     Docs: https://docs.docker.com
  Process: 9867 ExecStart=/usr/bin/dockerd -H fd:// --containerd /var/run/containerd/containerd.sock (code=exite
d, status=1/FAILURE)
 Main PID: 9867 (code=exited, status=1/FAILURE)

Dec 24 05:37:48 rockchip-evb systemd[1]: docker.service: Main process exited, code=exited, statu
s=1/FAILURE
Dec 24 05:37:48 rockchip-evb systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 24 05:37:48 rockchip-evb systemd[1]: Failed to start Docker Application Container Engine.
Dec 24 05:37:50 rockchip-evb systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
Dec 24 05:37:50 rockchip-evb systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Dec 24 05:37:50 rockchip-evb systemd[1]: Stopped Docker Application Container Engine.
Dec 24 05:37:50 rockchip-evb systemd[1]: docker.service: Start request repeated too quickly.
Dec 24 05:37:50 rockchip-evb systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 24 05:37:50 rockchip-evb systemd[1]: Failed to start Docker Application Container Engine.

The IoTEdge runtime also  installed without any issues, but reported this error:
× container engine is installed and functional - Error
    Could not communicate with container engine at unix:///var/run/docker.sock.
    Please check your moby-engine installation and ensure the service is running.
        caused by: docker returned exit code: 1, stderr = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

What can I do get additional information on what is causing the Moby runtime startup failure?

**Comment by ggjjj** [comment]
Hello @kjayantmenon, 

Can you check if the .sock file exists under the location `/var/run/` ? If it doesn't exist then its not installed properly. Please follow the instructions to uninstall the moby runtime by 

`sudo apt-get remove --purge moby-cli`
`sudo apt-get remove --purge moby-engine`

Also re-install it and try again to see of the `.sock` is created.

**Comment by AshokPeddakotla-MSFT** [comment]
Issue raised in docs as well: https://github.com/MicrosoftDocs/azure-docs/issues/68079 linking here for reference.

**Comment by veyalla** [comment]
Debian 10 a Tier 2 platform for IoT Edge, so we don't have packages to install this in Microsoft's Debian repos.

The manual steps to follow to install would be:
* Install container engine by following the general [install instructions](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06&tabs=linux#install-a-container-engine). *Use [prerequisites](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06&tabs=linux#prerequisites) for Ubuntu Server 18.04*
* Manually download and install the Debian 9 packages from the [releases](https://github.com/azure/azure-iotedge) repo.
  * For example, for 1.0.10.4:
    * https://github.com/Azure/azure-iotedge/releases/download/1.0.10.4/libiothsm-std_1.0.10.4-1-1_debian9_arm64.deb
    * https://github.com/Azure/azure-iotedge/releases/download/1.0.10.4/iotedge_1.0.10.4-1_debian9_arm64.deb

**Comment by ribeach** [comment]
We were facing the same problem.

You need to switch iptables to legacy mode, after that moby-engine runs fine:
https://wiki.debian.org/iptables

**Comment by amit12cool** [comment]
@veyalla Please guide me where can I find the `deb` for 1.2.6. I could not locate the download link in releases page
