### ISSUE TITLE
IoTEdge Configuration and Deployments

### ISSUE THREAD

**Issue by rodrigour** [Azure/iotedge#417]
## Expected Behavior
Being Able to see IoTEdge Configuration and Deployments 

## Current Behavior
I am receiving these errors within Azure IoT Edge console for no reason, and can't see either configuration nor deployments.: 

Failed to Get Configuration(s)
RequestEntityTooLarge:{
 "Message": "ErrorCode:ConfigurationCountLimitExceeded;RequestEntityTooLarge",
 "ExceptionMessage": "Tracking ID:8ebceb44d31e44839854b33a557b1f6b-G:10-TimeStamp:10/12/2018 04:00:42"
 }
by me
a few seconds ago

Failure
Deployment information could not be retrieved.
by me
a few seconds ago

## Steps to Reproduce

1. Enter into Azure Portal, IoThub, IoTEdge
2. Click IoT Edge configuration and Click IoT Edge deployments

### Device (Host) Operating System
Ubuntu 16.04. 

### Architecture
amd64

### Container Operating System
 Linux containers,

#### iotedged
Run `iotedge version` --> 
iotedge 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)

#### Docker
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:30:52 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:26:37 2018
  OS/Arch:          linux/arm

## Logs
No logs as this is within Azure Portal

**Comment by jackt-moran** [comment]
Perhaps your deployment template has a field that is over the 8Kb limit: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-twin-size

iotedge 1.0.3 has been released so you may want to try upgrading to that as well and see if that helps.

**Comment by myagley** [comment]
Just for clarity, you are seeing this error message in the Azure portal?

**Comment by myagley** [comment]
I talked to the IoT Hub service team. They were having a service issue but this is now mitigated. This issue should be resolved now. Is it possible to try to repro?

**Comment by myagley** [comment]
Closing this issue as it was related to a service side issue in IoT Hub.

**Comment by KosukeTsumura** [comment]
It seems that I'm facing same issue as follows,
<img width="1440" alt="Screen Shot 2020-07-01 at 22 32 30" src="https://user-images.githubusercontent.com/19725264/86249949-e95aba00-bbea-11ea-91bb-b9701c653f0f.png">

Is it possible to reopen this issue again?

If here is not approptiate to ask it, please let me know.
