### ISSUE TITLE
All modules restart after updating only edgeAgent version in deployment manifest

### ISSUE THREAD

**Issue by Lexmark-chad** [Azure/iotedge#4176]
We are observing that all the modules restart after deploying a new manifest that only changes the version of edgeAgent.  Is that necessary?  It would be nice if other modules didn't have to restart to prevent an interruption in service.

iotedge version 1.0.10
edgeAgent version 1.0.9.4

I am looking for the best way to orchestrate updates to newer versions of edgeAgent.

**Comment by richma-ms** [comment]
The underlying container management logic housed in EdgeAgent can differ drastically between versions, such that a module deployed previously by a different version of EdgeAgent can potentially cause inconsistencies in the Edge runtime.  So to be on the safe side we need to redeploy the custom modules as well.

Note that when updating Edge, the only officially supported scenario is to update all 3 components (iotedge daemon, EdgeAgent, EdgeHub) at once so the whole runtime remains on the same version.
