### ISSUE TITLE
Azure IoT Edge Module not sending messages to IoTHub

### ISSUE THREAD

**Issue by payalgaikwad42** [Azure/iotedge#4194]
Hi, I have one custom module written in Java springboot with MQTT protocol. The module is supposed to send messages to iothub. But it is not doing so. 

I have IoTEdge runtime 1.10.0 installed on my Windows machine with Linux container. 
I am receiving following logs in my custom module:

> 2021-01-07 13:06:36.944 INFO 1 --- [ Thread-21] c.g.h.c.c.InTestSchedulerCallback : Message json entered in to sendDataToModule method()...
2021-01-07 13:06:36.944 INFO 1 --- [ Thread-21] c.m.a.s.i.d.transport.IotHubTransport : Message was queued to be sent later ( Message details: Correlation Id [de116cd4-274a-4b5d-b166-ce1eec04011c] Message Id [3af50239-1e2b-4e1c-baa7-d241ee04d720] )
2021

The routes are defined as follows:
` "routes": {
          "DataProcessorModuleToIoTHub": "FROM /messages/modules/dataprocessormodule/outputs/* INTO $upstream",
          "DAQNotificationToIoTHub": "FROM /messages/modules/dataacquisitionmodule/outputs/* INTO $upstream",
          "DAQModuleToDataProcessorModule": "FROM /messages/modules/dataaquisitionmodule/outputs/outDataAcquisition INTO BrokeredEndpoint(\"/modules/dataprocessormodule/inputs/input1\")"
        },`
        
    The java springboot code whereI am sending message to IoTHub is as follows:
    
    `try {
                    jsonString = mapper.writeValueAsString(deviceNotificationMessage);
                    log.info("Notification json value" + jsonString);
                    Message jsonMsg = new Message(jsonString);
                   
                    //write logic for memory of jsonMsg object.
                          SBXServerContext.client.sendEventAsync(jsonMsg, eventCallback, jsonMsg);
                } catch (JsonProcessingException e) {
                    e.printStackTrace();
                }`

Azure device client version I am using is 1.28.0 and springboot version is 2.3.1

Please help me to figure out why messages are getting stuck at module level

**Comment by richma-ms** [comment]
@payalgaikwad42 a cursory look at the SDK implementation seems to indicate that the "message was queued..." message is expected, as messages are always pushed into an in-memory queue to be processed by a worker thread later to do the actual sending.
https://github.com/Azure/azure-iot-sdk-java/blob/9b07099e18f8aa0ab81a564023537c4f645ffe42/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java

how are you verifying that the message isn't leaving the module?  Are there no corresponding events in EdgeHub module indicating that the message was received/forwarded?

**Comment by payalgaikwad42** [comment]
@richma-ms , Yes there are no corresponding events in EdgeHub module indicating that the message was received/forwarded. Also no acknowledgement was received by module itself. 
Also I am monitoring built-in-endpoints for the IoT Edge device from VS code and there are no messages.

**Comment by payalgaikwad42** [comment]
@richma-ms are there any updates ?

**Comment by payalgaikwad42** [comment]
The issue is resolved now. I don't know the specific reason but it is resolve now. i am still getting " Message was queued to be sent later" message in my logs but when I Monitor built-in-endpoints using VS code I can see the messages are reaching to the IoTHub

**Comment by payalgaikwad42** [comment]
c

**Comment by sarthakvijayvergiya** [comment]
@richma-ms  I am also facing same issue. Any resolution ?

**Comment by sarthakvijayvergiya** [comment]
@richma-ms Could you please reopen this issue again ?
