### ISSUE TITLE
edgeHub doesn't expose metrics

### ISSUE THREAD

**Issue by karakal** [Azure/iotedge#4210]
## Expected Behavior
edgeHub module should expose metrics on Port

## Current Behavior
No connection on Port possible

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Add Exposed Port and PortMapping in deployment-File
2. Deploy File
3.
4.

## Context (Environment)

Ubuntu 18.04

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 12 days (at 2021-01-25 09:00:25 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

22 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10.4
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.10.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.10.4
* Docker/Moby [run `docker version`]: 19.03.14+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by lfitchett** [comment]
EdgeHub and edgeAgent bult in metrics are documented here. Make sure you are querying port 9600. A useful command to test if the metrics are working is below.

```sudo docker exec edgeAgent wget http://edgeAgent:9600/metrics -qO-```
```sudo docker exec edgeAgent wget http://edgeHub:9600/metrics -qO-```

**Comment by karakal** [comment]
> 
> 
> EdgeHub and edgeAgent bult in metrics are documented here. Make sure you are querying port 9600. A useful command to test if the metrics are working is below.
> 
> `sudo docker exec edgeAgent wget http://edgeAgent:9600/metrics -qO-`
> `sudo docker exec edgeAgent wget http://edgeHub:9600/metrics -qO-`

Yeah, I know that two commands, and I did try them.

Here the output for the edgeAgent, which is working fine:
`sudo docker exec edgeAgent wget http://edgeAgent:9600/metrics -qO-
# HELP edgeAgent_total_network_in_bytes The amount of bytes recieved from the network
# TYPE edgeAgent_total_network_in_bytes gauge
edgeAgent_total_network_in_bytes{iothub=".....`

Here the output for the edgeHub, which isn't working at all:
`sudo docker exec edgeAgent wget http://edgeHub:9600/metrics -qO-
wget: can't connect to remote host (172.18.0.8): Connection refused
`

I am out of ideas what to try next... and as I have a big problem with edgeHub performance it is absolutely critical that I gain some insight into edgeHub metrics...

**Comment by veyalla** [comment]
Please share logs from edgeHub module.

**Comment by ReneHezser** [comment]
My IoT Edge installation was also not working on the edgeHub. I could fix it by removing **httpSettings__enabled=false** on the edgeHub and by setting **MetricsEndpointsCSV=http://edgeHub:9600/metrics,http://edgeAgent:9600** on my monitoring module.
Maybe you have a similar misconfiguration?

**Comment by karakal** [comment]
> 
> 
> My IoT Edge installation was also not working on the edgeHub. I could fix it by removing **httpSettings__enabled=false** on the edgeHub and by setting **MetricsEndpointsCSV=http://edgeHub:9600/metrics,http://edgeAgent:9600** on my monitoring module.
> Maybe you have a similar misconfiguration?

Thank you very much! it was the http_Settings__enabled=false that caused the problem. I would request an addition to the documentation for that!
