### ISSUE TITLE
EdgeHub Is not Authenticating When IoT Hub got deleted and recovered from Old Backup

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#4241]
## Expected Behavior
EdgeHub should communicate to IoT Hub when IoT Hub is recovered from backup with all the keys and connection strings..

## Current Behavior
EdgeHub and EdgeAgent don't connect to IoT Hub when IoT Hub is being recovered from backup..

## Steps to Reproduce
Repro Steps
1. Create IoT Hub
2. Deploy some modules
3. Configure connection string on Gateway
4. Take backup of IoT Hub along with keys and connection string
5. Delete IoT Hub 
6. Re-Create again IoT Hub with the same name which was earlier
7. Recover IoT Hub backup along with keys and connection string 
8. Check the module logs on Gateway 
9. Logs says unauthorize error with invalid SAS token 
10. After restarting Edge Runtime also it is not working 
10. After re-creating all modules container then it work 

## Context (Environment)
Windows  10
Edge Runtime version 1.0.10.1

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS: Windows 10
* Architecture [e.g. amd64, arm32, arm64]: 
* Container: Windows

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
 

 

<6> 2021-01-13 09:36:41.211 +01:00 [INF] - Registering request handler UploadModuleLogs <6> 2021-01-13 09:36:41.212 +01:00 [INF] - Registering request handler GetModuleLogs <6> 2021-01-13 09:36:41.212 +01:00 [INF] - Registering request handler UploadSupportBundle <6> 2021-01-13 09:36:41.213 +01:00 [INF] - Registering request handler RestartModule <3> 2021-01-13 09:36:42.228 +01:00 [ERR] - Device client threw non-transient exception during setup Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: error(condition:amqp:unauthorized-access,description:Put token failed. status-code: 401, status-description: The specified SAS token has an invalid signature. It does not match either the primary or secondary key..)  ---> Microsoft.Azure.Amqp.AmqpException: Put token failed. status-code: 401, status-description: The specified SAS token has an invalid signature. It does not match either the primary or secondary key..    at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)    at Microsoft.Azure.Amqp.AsyncResult`1.End(IAsyncResult asyncResult)    at Microsoft.Azure.Amqp.AmqpCbsLink.EndSendToken(IAsyncResult result)    at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown ---    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsLink.SendTokenAsync(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout)    --- End of inner exception stack trace ---    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTCbsLink.SendTokenAsync(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout)    at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpAuthenticationRefresher.InitLoopAsync(TimeSpan timeout)    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTConnection.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)    at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpConnectionHolder.CreateRefresherAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)    at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)    at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(CancellationToken cancellationToken)    at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass23_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass33_0.<<OpenInternalAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)    at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()    at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateAndOpenSdkModuleClient(UpstreamProtocol upstreamProtocol, ConnectionStatusChangesHandler statusChangedHandler) in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 218    at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.<>c__DisplayClass19_0.<<CreateSdkModuleClient>b__0>d.MoveNext() in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 169 --- End of stack trace from previous location where exception was thrown ---    at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider.CreateSdkModuleClientWithRetry(ConnectionStatusChangesHandler statusChangedHandler) in C:\agent\_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.IoTHub\ModuleClientProvider.cs:line 151

 
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by lfitchett** [comment]
If I understand this issue correctly, after deleting and restoring an IoTHub, the edge devices are unable to connect to the restored hub. However, deleting the containers and forcing a re-creation makes it work again? 

Are you using manual provisioning?

If this is the case, you can try setting dynamic_reprovisioning to true in the config.yaml: https://github.com/Azure/iotedge/blob/8e8f68ab1bd1cb66c4b5822b16adbed66a972397/edgelet/contrib/config/windows/config.yaml#L100

**Comment by sachidanand** [comment]
OK Sure .. We will try it and then will come back to you if it works for us

**Comment by sachidanand** [comment]
> If I understand this issue correctly, after deleting and restoring an IoTHub, the edge devices are unable to connect to the restored hub. However, deleting the containers and forcing a re-creation makes it work again?
> 
> Are you using manual provisioning?
> 
> If this is the case, you can try setting dynamic_reprovisioning to true in the config.yaml:
> 
> https://github.com/Azure/iotedge/blob/8e8f68ab1bd1cb66c4b5822b16adbed66a972397/edgelet/contrib/config/windows/config.yaml#L100

Hi Team,
We have tested with this fix and It works for us .. Thanks for this ....

**Comment by alaendle** [comment]
@veyalla - since we encountered the same problem today; what is the reasoning that the default value for dynamic_reprovisioning is set to false? I was searching for more documentation about the implications of this setting, but unfortunately the only available documentation seems to be the few comment lines in the config.yaml. Have I missed something?
