### ISSUE TITLE
Communication between IoT edge modules and IoT hub via express route.

### ISSUE THREAD

**Issue by SandeepThombare** [Azure/iotedge#4255]
Need help to understand and configure the IoT edge and docker to establish the communication between IoT edge modules and IoT hub having private IP via express route.

We can communicate if IoT Hub have access to public network, but when we disabled the public network access of IoT hub, IoT edge modules are not communicating with IoT Hub.

Getting below error,
**“Empty edge agent config was received, attempting to read config from backup”.**

As per IoT edge documentation, 
https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2018-06#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device

We have installed a DNS server (bind9) in the same VM and configured the daemon.json (IP of the host VM as DNS server), but still we were not able to connect.

Please let me know if we are missing anything and how can I check that modules are using the DNS server configuration from /etc/docker/daemon.json file. Which logs should we look into.
 
Note:- Using IoT edge version 1.0.10.4

**Comment by davilu** [comment]
@SandeepThombare Thanks for reporting the issue. Let's start with [check edge hub status ](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2018-06).

**Comment by SandeepThombare** [comment]
Hi @davilu ,

Please see attached logs of edgeAgent and iotedge status.
[Status iotedge.zip](https://github.com/Azure/iotedge/files/5856284/Status.iotedge.zip)

Can you also let me know how can I get the more detail logs related to DNS server configuration.

**Comment by davilu** [comment]
Hi @SandeepThombare  thanks for the info. Please help to get more details from edge status check:
1. sudo iotedge check: check connectivity, CA cert and configuration
2. sudo iotedge support-bundle --since 6h: create support bundle with all related logs
3. sudo nano /etc/iotedge/config.yaml: check configuration of edge, including proxy settings

**Comment by SandeepThombare** [comment]
Hi  @davilu ,
Please see attached files for your reference. In config.yaml, I have added Device provisioning- DPS information only. 
[support_bundle.zip](https://github.com/Azure/iotedge/files/5861583/support_bundle.zip)

**Comment by davilu** [comment]
Hi @SandeepThombare 
In the `check.json` file, it indicates MQTT port `8883` was blocked. But it shouldn't matter since edge agent is going with AMQP and it works fine.
```
"Could not connect to xxxx.azure-devices.net:8883", "connection timed out" 
```
From the log filr `edgeAgent_log.txt`, edge agent was trying to open a cloud connection but failed with 
```
<4> 2021-01-22 17:35:11.838 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Amqp resource is disconnected.) (Amqp resource is disconnected.)
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Amqp resource is disconnected.
```

It means TCP connection is somehow reset before it could establish the session/link. Could you please double check if you have another deployment using the same device identity?

**Comment by SandeepThombare** [comment]
Hi @davilu ,

Thank you for your response.

I am using same device identity certificate to create IoT edge device using DPS. so I have two edge devices in different IoT hub in different network. No connection in this two network, they are separate from each other. 

few points related to setup and observations,
1. IoT edge device VM can reach to IoT hub using Azure Private Link. I have checked the connectivity.

2. When I tried to deploy edge modules on IoT edge VM/device , edgeAgent module(container) is having trouble with DNS name resolution and it is not able connect with IoT hub.

3. To resolve above issue(mentioned in point 2), I have configured the DNS server(using bind9) in Edge VM and provided the DNS server details in /etc/docker/daemon.json as per IoT edge common error documentation.

4. After step 3, I was expecting IoT edge device will connect with IoT hub but it is not connecting and I am not able to see any log related to it.

5. When I enabled public network access to IoT hub, my edge device is connecting with IoT hub and I can deploy all modules and it is working fine.

Please advise if I am missing any configuration.

**Comment by davilu** [comment]
Hi @SandeepThombare,  are you using CA cert with proxy? If so, please refer to #2973.

**Comment by SandeepThombare** [comment]
@davilu , No I am not using proxy. 
I am using devic identity certificate for edge device provisioning using DPS.

**Comment by davilu** [comment]
Hi @SandeepThombare in this case the only way to figure out what's going on is get TCP dump from edge agent VM.

**Comment by SandeepThombare** [comment]
Hi @davilu ,

I will take the TCP dump but I need to check with network team that if I can share that here.

Can you share any documentation related to configuration required to configure containers(edge modules) to use DNS server so that containers can resolve the IoT hub IP address and connect with it.

**Comment by davilu** [comment]
Hi @SandeepThombare, from the log, seems DNS did found some IP address and was able to establish TCP connect to it, but it was reset after. Not sure what IP was resolved to. For your question, there is a [document](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2018-06#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device) for common errors.

**Comment by davilu** [comment]
Hi @SandeepThombare any luck to get the TCP dump? Do you still have issue to connect to IoTHub?

**Comment by micahl** [comment]
@SandeepThombare I'm closing this issue for now.  If its problematic to share the TCP dump here then consider opening a support ticket ([instructions](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request)) with Issue Type = "Technical" and the Service = "IoT Edge".  It should present you with an opportunity to share a file privately.  And be sure to link back to this issue to give the support engineer existing context.
