### ISSUE TITLE
Edge Runtime 1.0.10.4 is not working with Proxy And SSL Interception

### ISSUE THREAD

**Issue by rahulsehgal** [Azure/iotedge#4260]
Hi Team,

We are using Azure IoT Edge with windows containers and we have proxy based environment for edge gateway. Our proxy has SSL interception which is certificate-based.

To test this scenario with Azure IoT Edge, I have setup the proxy using ssl interception in Fiddler in Windows and setup the same proxy in config.yaml. Also the certificate is added to the trust bundle in the host OS as well as trust bundle certificate for IoT Edge.

## Current Behavior
Now the issue is that edgeAgent is not able to download the twin from IoTHub.

### Output of `iotedge check`

PS C:\windows\system32> iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.

###  Proxy in Config.yaml
agent:
  name: "edgeAgent"
  type: "docker"
  env:
    https_proxy: 'http://20.71.49.244:8866'
    UpstreamProtocol: 'AmqpWs'
    RuntimeLogLevel: Debug
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}

### iotedge list
PS C:\windows\system32> iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeAgent        running          Up 9 minutes     mcr.microsoft.com/azureiotedge-agent:1.0

### Edge Agent Logs:

<7> 2021-01-21 07:20:37.933 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Finished reconcile operation
<7> 2021-01-21 07:20:42.935 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Starting reconcile operation
<7> 2021-01-21 07:20:42.936 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient] - Making a Http call to unix:///C:/ProgramData/iotedge/mgmt/sock to List modules
<7> 2021-01-21 07:20:42.936 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket C:\ProgramData\iotedge\mgmt\sock
<7> 2021-01-21 07:20:42.936 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket C:\ProgramData\iotedge\mgmt\sock
<7> 2021-01-21 07:20:42.937 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://sock/modules?api-version=2020-07-07
<7> 2021-01-21 07:20:42.937 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
<7> 2021-01-21 07:20:42.944 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Response received OK
<7> 2021-01-21 07:20:42.945 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient] - Received a valid Http response from unix:///C:/ProgramData/iotedge/mgmt/sock for List modules
<4> 2021-01-21 07:20:47.951 +01:00 [WRN] [Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.BackupConfigSource] - Empty edge agent config was received. Attempting to read config from backup (C:\Windows\TEMP\edgeAgent\backup.json) instead
<7> 2021-01-21 07:20:47.951 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Finished reconcile operation
<7> 2021-01-21 07:20:52.966 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Starting reconcile operation
<7> 2021-01-21 07:20:52.967 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient] - Making a Http call to unix:///C:/ProgramData/iotedge/mgmt/sock to List modules
<7> 2021-01-21 07:20:52.967 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connecting socket C:\ProgramData\iotedge\mgmt\sock
<7> 2021-01-21 07:20:52.968 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Connected socket C:\ProgramData\iotedge\mgmt\sock
<7> 2021-01-21 07:20:52.968 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Sending request http://sock/modules?api-version=2020-07-07
<7> 2021-01-21 07:20:52.968 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Core.Agent] - Getting edge agent config...
<7> 2021-01-21 07:20:52.972 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Uds.HttpUdsMessageHandler] - Response received OK
<7> 2021-01-21 07:20:52.973 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient] - Received a valid Http response from unix:///C:/ProgramData/iotedge/mgmt/sock for List modules
<6> 2021-01-21 07:20:55.823 +01:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<7> 2021-01-21 07:20:55.850 +01:00 [DBG] [Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider] - Retrying connection to IoT Hub. Current retry count 14.

### Analysis
On analyzing the network traffic in Wireshark I see Alert 21, for the Encrypted Alert, which means the decryption failed.
![image](https://user-images.githubusercontent.com/18692450/105295087-8872ed80-5bdf-11eb-90a5-2838a7b4d006.png)

As per iot check, Edge Runtime is able to connect to IoT Hub but somehow the SSL Tunnel is not established. Could you please confirm how we can set the client certificate in Edge Runtime so that it can work with proxy with ssl interception?

A similar issue to this was already closed.
https://github.com/Azure/iotedge/issues/2973

**Comment by davilu** [comment]
@rahulsehgal  The problem is not on edge but C# SDK couldn't connect to IoT Hub through proxy with SSL Interception. The Wireshark analyzing doesn't mean decryption failed but this is an alert message, alert type code is 21 and alert message is encrypted so Wireshark  couldn't show it. Please refer to [SSL alert](https://community.cisco.com/t5/network-security/ssl-content-type-alert-21/td-p/1218378). The article also provided a way to decrypt the alert content. You could change agent `UpstreamProtocol` to `Amqp` or `MQTT` to see if you could get any luck. But as mentioned in #2973, it's an unsupported feature.

**Comment by davilu** [comment]
BTW, you can upvote the feature suggestion for cert-based proxy auth [here](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/36740230-certificate-based-proxy-authentication).
