### ISSUE TITLE
Nested Edge setup on Ubuntu

### ISSUE THREAD

**Issue by ramakrpr** [Azure/iotedge#4282]
Hi,
I am setting up a nested edge scenario using the current preview version on Ubuntu 16.04
I am following the link below to setup the Parent and i get the issues as highlighted below. I see some of them have reported the same issue, but couldnt find a solution as such

https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11&tabs=azure-portal

Post i deploy the modules using the template and run the iotedge check, i see the below error
Note that the IOT Hub as well is in preview mode

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    **One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)**
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.2.0~rc1 but 1.0.10.4 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to reference time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
**× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error**
    Could not check current state of edgeHub container
√ EdgeAgent module can be pulled from upstream - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with upstream AMQP port - OK
√ host can connect to and perform TLS handshake with upstream HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with upstream MQTT port - OK
√ container on the default network can connect to upstream  AMQP port - OK
**× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to <<iothub>>.azure-devices.net:443**
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
**× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to <<iothub>>.azure-devices.net:443**
√ container on the IoT Edge module network can connect to upstream MQTT port - OK

16 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
5 check(s) raised errors. Re-run with --verbose for more details.

iot edge status
===========

● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Mon 2021-01-25 12:15:50 UTC; 20h ago
     Docs: man:iotedged(8)
  Process: 6498 ExecStart=/usr/bin/iotedged -c /etc/iotedge/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 6498 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

any pointers on what might be going wrong?

**Comment by massand** [comment]
@ramakrpr Have you tried running the iotedge service yet, using the `sudo systemctl restart iotedge` command? Your iotedge status output indicates you haven't started the service yet, after configuring the configu.yaml of your Edge deployment. Could you provide `journalctl -u iotedge` logs after you start/restart iotedge please? 

AFAICT, your connectivity and essential configuration tests are passing. Our E2E tests run the preview bits on Ubuntu 16.04. So, you should have no issues.

**Comment by ramakrpr** [comment]
@massand 

indeed i ran restart iotedge, but dint make any difference
the output of journalctl -u is as below

-- Logs begin at Tue 2021-01-26 15:07:10 UTC, end at Tue 2021-01-26 17:12:35 UTC. --
Jan 26 17:11:55 azazdev01dvm07 systemd[1]: Stopped Azure IoT Edge daemon.
Jan 26 17:11:55 azazdev01dvm07 systemd[1]: Started Azure IoT Edge daemon.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Starting Azure IoT Edge Security Daemon
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Version - 1.2.0~rc1
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Configuring certificates...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Configuring the Device CA certificate using "/etc/iotedge/azazdev01dvm07.crt".
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Configuring the Device private key using "/etc/iotedge/azazdev01dvm07.pem".
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Configuring the trusted CA certificates using "/etc/iotedge/TSEEnterpriseCA.crt".
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Finished configuring provisioning environment variables and certificates.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Initializing hsm...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Finished initializing hsm.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Provisioning edge device...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Starting provisioning edge device via manual mode using a device connection string...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Manually provisioning device "Azazdev01dvm07" in hub "ijmedg01-tse-d1-iothub.azure-devices.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Finished provisioning edge device.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Initializing the module runtime...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Initializing module runtime...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Notary Content Trust is disabled
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Using runtime network id azure-iot-edge
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Successfully initialized module runtime
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Finished initializing the module runtime.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Stopping all modules...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Finished stopping modules.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Detecting if configuration file has changed...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Change to configuration file detected.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Removing all modules...
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Finished removing modules.
Jan 26 17:11:55 azazdev01dvm07 iotedged[8365]: 2021-01-26T17:11:55Z [INFO] - Edge issuer CA expiration date: 2023-01-25T11:28:35Z
Jan 26 17:11:55 azazdev01dvm07 systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 17:11:55 azazdev01dvm07 systemd[1]: iotedge.service: Unit entered failed state.
Jan 26 17:11:55 azazdev01dvm07 systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jan 26 17:11:56 azazdev01dvm07 systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Jan 26 17:11:56 azazdev01dvm07 systemd[1]: Stopped Azure IoT Edge daemon.
Jan 26 17:11:56 azazdev01dvm07 systemd[1]: Started Azure IoT Edge daemon.
Jan 26 17:11:56 azazdev01dvm07 iotedged[8412]: 2021-01-26T17:11:56Z [INFO] - Starting Azure IoT Edge Security Daemon
Jan 26 17:11:56 azazdev01dvm07 iotedged[8412]: 2021-01-26T17:11:56Z [INFO] - Version - 1.2.0~rc1
Jan 26 17:11:56 azazdev01dvm07 iotedged[8412]: 2021-01-26T17:11:56Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jan 26 17:11:56 azazdev01dvm07 iotedged[8412]: 2021-01-26T17:11:56Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Jan 26 17:11:56 azazdev01dvm07 iotedged[8412]: 2021-01-26T17:11:56Z [INFO] - Configuring certificates...
Jan 26 17:11:56 azazdev01dvm07 iotedged[8412]: 2021-01-26T17:11:56Z [INFO] - Configuring the Device CA certificate using "/etc/iotedge/azazdev01dvm07.crt".



One more observation is, as below the response is different for a preview version of iot hub when compared to the one now in GA. I tried with multiple GA hubs we have and all respond the same for the curl, where as the preview one shows an api version issue - in my case ijmedg01-tse-d1-iothub is preview version of hub

ramakrpr@azazdev01dvm07:~$ curl https://ijmedg01-tse-d-iothub.azure-devices.net
{"Message":"ErrorCode:InvalidProtocolVersion;BadRequest","ExceptionMessage":"Tracking ID:143e624ae84d41f2a1d6a63b05b08665-G:5-TimeStamp:01/26/2021 17:18:29"}

ramakrpr@azazdev01dvm07:~$ curl https://ijmedg01-tse-d1-iothub.azure-devices.net
{"message":"ErrorCode:ArgumentInvalid;Unknown api version","exceptionMessage":"Tracking ID:94A2AA1C2C4E4F22A7276C7E5BA10F1E-G2:0-TimeStamp:2021-01-26T17:18:35.182293496

I know that there was an issue with the preview version of hub which was fixed last week, related to template deployment which i had reported and fixed. Not sure if something still remains open?

**Comment by massand** [comment]
I cannot find any errors in the iotedged logs and this seems specific to your environment. You will need to provide the same logs after enabling debug logs. Please refer to the subsection on [security manager logging](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2018-06#check-the-status-of-the-iot-edge-security-manager-and-its-logs) in the troubleshoot docs. 
**Caution**: Your VM and hub name have not been redacted in this Github issue. You should remove this VM and rotate your Hub keys to stay secure. If you would like to provide logs in the future, please redact PII information OR share logs by filing an Azure Support ticket.

**Comment by ramakrpr** [comment]
@massand  thanks for that removed the stuff from text
Attached the log after enabling debug. I see an issue with workload CA certificate (i am using enterprise CA certificates in the certificate settings). Something wrong with the certificate itself?

certificates:
  device_ca_cert: "file:///etc/iotedge/dvm07.crt"
  device_ca_pk: "file:///etc/iotedge/dvm07.pem"
  trusted_ca_certs: "file:///etc/iotedge/IntermediateCA.crt"


[journalctl.txt](https://github.com/Azure/iotedge/files/5875461/journalctl.txt)

**Comment by massand** [comment]
@ramakrpr Please ensure the ACLs on your `device_ca_pk` file have read permissions given to the `iotedge` user
As per your latest logs, it appears the workload ca cert generation process is failing because the issuing CA cert's keys are not accessible by the `iotedge` user - 
```
Jan 26 18:47:15 dvm07 iotedged[29118]: 2021-01-26T18:47:15Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:load_private_key_file:662) Failure PEM_read_bio_PrivateKey for /etc/iotedge/dvm07.pem
Jan 26 18:47:15 dvm07 iotedged[29118]: 2021-01-26T18:47:15Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_pki_cert_and_key_helper:1496) Could not load issuer private key file
Jan 26 18:47:15 dvm07 iotedged[29118]: 2021-01-26T18:47:15Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert_internal:2633) Could not create PKI certificate and key for iotedged-workload-ca
Jan 26 18:47:15 dvm07 iotedged[29118]: 2021-01-26T18:47:15Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert:2709) Could not create certificate and key for alias iotedged-workload-ca
Jan 26 18:47:15 dvm07 iotedged[29118]: 2021-01-26T18:47:15Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:edge_hsm_client_create_certificate:288) Could not create certificate in the store
```

**Comment by ramakrpr** [comment]
Hi @massand thanks for your inputs
What i did is that i created the device certificates and key again from scratch and with that the issue what was being experienced above is gone - attached logs 
[journalctl2701.txt](https://github.com/Azure/iotedge/files/5879541/journalctl2701.txt)

I now see that edge agent is running but then i see a connecitvity issue as below

[iotedgecheck2701.txt](https://github.com/Azure/iotedge/files/5879563/iotedgecheck2701.txt)

**Comment by massand** [comment]
Does your device in IoT Hub have the Edge capability? Or is it a standalone device?

**Comment by ramakrpr** [comment]
@massand this is an ubuntu VM with edge runtimes deployed. basically i am following the nested edge setup as documented here - https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11&tabs=azure-portal
this one is the parent where i am stuck

**Comment by ramakrpr** [comment]
@massand maybe its also an idea that i can create a support incident with Microsoft directly, i have that option too

**Comment by massand** [comment]
I am closing this issue since the original device CA issue has been resolved.

Before you open a support ticket, please perform one of the following checks to ensure your device-id is edge-enabled:

**Azure CLI**: Check if the device-id is listed in the output of this command - `az iot hub device-identity list --ee -n <<PUT_IOT_HUB_NAME_HERE>>`

**Azure Portal**: IoT Hub resources > Your IoT Hub > Automatic Device Management > IoT Edge > check device list

If you cannot find the device listed, you will need to create an edge-enabled device (as per the nested edge setup link) instead of using a standalone non-edge-enabled IoT device. Otherwise, please open a new Github issue (or Azure Support ticket) with the contents from the following command: `az iot hub module-twin show -d <<PUT_DEVICE_ID_HERE>>-m '$edgeAgent' -n <<PUT_IOT_HUB_NAME_HERE>>`

**Comment by massand** [comment]
Also found this article that can help you self-resolve: 
https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot-common-errors?view=iotedge-2018-06#edge-agent-module-reports-empty-config-file-and-no-modules-start-on-the-device
