### ISSUE TITLE
IOT Edge ACR - Image pull security concerns

### ISSUE THREAD

**Issue by ramakrpr** [Azure/iotedge#4283]
Hi,

We intent to use our private ACR to pull images for module deployments
However, we have an issue that for security reasons ACR is not enabled with "Admin User". I am following the schema reference for template for IOT Edge as below and looks like it requires the User Name and Password of the ACR which is only available if Admin User is enabled.

https://docs.microsoft.com/en-us/azure/iot-edge/module-edgeagent-edgehub?view=iotedge-2018-06

Are there any other options to use ACR without enabling this? Couldnt find though

**Comment by darobs** [comment]
Hello @ramakpr, 

You do not need the admin user for ACR to pull images.  We recommend that you set up a pull-only service principle:

To set up a read-only ACR with service principal: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal
How to create a service principal via portal: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal
To manage access in production: https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist#manage-access-to-your-container-registry

**Comment by ramakrpr** [comment]
Hi @darobs ,

great i was thinking that i wouldnt be able to give the client id and secret in the manifest, but looks that is feasible. Thanks for your reponse.
