### ISSUE TITLE
Guidance on how to manage secrets in IoT Edge

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#4297]
I've been searching on how we can best store and manage secrets that are used in IoT Edge modules.

My first thought was to use the Module Twin and store the secrets there as desired properties.  That gives me the advantage to easily act in my iotedge module when secrets are being rolled.   However, it feels a bit wrong to store secrets as properties in the module twin:  anyone that has access to IoT Hub, can easily read the secrets.

So I came up with a solution where the Edge module sends a message to IoT Hub which is picked up by an Azure Function.  The Azure Function processes the message, retrieves the required secrets from a KeyVault and sends them through a Direct Method to the IoT Edge Module.

I'm wondering if there is some guidance from the IoT Edge team on how to manage secrets that are used in edge modules in a secure way.    Is storing those secrets in the Module Twin secure and is my solution overkill, or are there other options to achieve this ?

**Comment by massand** [comment]
@fgheysels In some cases, symmetric encryption of desired property value might help with confidentiality, however (as you said) it is prone to easy duplication by any IoTHub iothubowner users. Few points that might help your scenario (without any knowledge about your scenario): 

- Are there secrets that are created and used by the IoT Edge modules themselves, and never have to leave the device? The edgelet workload API may be useful. However, there is no SDK API to achieve this easily and you will need to write/generate code using the [provided swagger](https://github.com/Azure/iotedge/blob/master/edgelet/api/workloadVersion_2019_01_30.yaml#L71) and invoke edgelet's REST APIs over Unix Domain Sockets (like [EdgeHub already does](https://github.com/Azure/iotedge/blob/master/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs#L54)). 
- Are the secrets generated by the cloud and need to be transmitted to the modules? Your Azure Key Vault does employ TLS when calling direct methods and should work fine. But, you will need to manage and fine-grain your access to Key Vault secrets from your Azure Function using AAD auth tokens (that will presumably require AAD credentials in your module, which need to be secured).

**Comment by fgheysels** [comment]
Thanks for the reply :)

In my scenario, we've deployed IoT Edge on vessels.  Naturally, those vessels are not always connected to the internet, given the fact that coverage (even with sattelites) is not always possible on the ocean.
That means that the vessel has no direct connection with the internet; the only connection that we have (when internet connection is available), is through IoT Hub.
The secrets are not generated on the device/vessel, but are managed via the cloud.  We've saved those secrets now in a KeyVault in Azure and the IoT Edge modules send a message to IoTHub.   Those specific messages are processed by an Azure Function that retrieves the specific secrets for that requesting module and sends them via a Direct Method back to the device.

**Comment by massand** [comment]
It sounds like you could do with a combination of the two then. The secrets can be made accessible via the Direct Method approach you mentioned (keeping in mind that you need to generate the auth token to call the Azure Function within your module - so you need another secret credential on device). Once the secret is provided to the module. in order to encrypt the secret at rest on device, you can leverage the encrypt workload API that I pointed out in point 1 in my response above.

**Comment by fgheysels** [comment]
I was actually more looking on guidance on what the best practices are for configuring secrets in iotedge modules that are managed in the cloud.
Is it a good idea to simply use the Module Twin desired properties for this ?  Are there other possiblities, is the solution I've implemented overkill, etc...

**Comment by piisku78** [comment]
So what was your final solution? Was it a good idea to use Key Vault?

I have the same problem. My idea was to use symmetric encryption + direct Method or Module Twin. I will encrypt the credentials. Put them in in docker images environment variables during the docker build. Then the encryption key is delivered on runtime via Direct Method or Module Twin to the running module. The encryption key is only available in memory variable during runtime, never saved to a file. Module Twin would be easier than direct method while it will be delivered automatically asap the device is online.
