### ISSUE TITLE
Get device connectionState on IoT edge / IoT device

### ISSUE THREAD

**Issue by KairaMiu** [Azure/iotedge#4307]
I would like to know how it is intended to find out the connection state of the device (connectionState of device twin / module twin) on the device itself.

Reading the twin with iot.device SDK in Python (using class IoTHubModuleClient or IoTHubDeviceClient) I do not get the Device identity properties.

IoT edge hub prints the state change in the log file but it is not a good solution to parse the log file.

Build-in metrics also do not contain that information, which is kind of logical. 

Is there a way to read out connectionState of the IoT edge or IoT device?

**Comment by yophilav** [comment]
We don't expose a way to do it from the device. However, you can observe them from IoTHub: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-monitor-module-twins?view=iotedge-2018-06

**Comment by KairaMiu** [comment]
Thank you for your answer, unfortunately this does not solve our use case.

But I now know that this is not intended. Many Thanks.

**Comment by yophilav** [comment]
That's unfortunate that we currently don't have a solution you are looking for. 
If you would be so kindly or would like to suggest a new feature please feel free to add your request here; 
https://feedback.azure.com/forums/907045-azure-iot-edge

Thank you so much!
