### ISSUE TITLE
Guidance on how to resolve running IOT edge agent

### ISSUE THREAD

**Issue by raghu04012012** [Azure/iotedge#4311]
IOT Agent container throws malformed token exception with version 1.0 and others as well.

Command Executed
docker run -it -d --privileged -e connectionString='xxy' mcr.microsoft.com/azureiotedge-agent:1.0 

ConnectionString used from Azure portal.

Any help appreciated

Environment : Ubuntu 18.04, X86_64 platform

**Comment by yophilav** [comment]
Thank you for the question!
I'm not sure what steps you're taking to deploy the module. 
Did you have a chance to take a look at our user manual here?
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06

The basic idea is that you want to create a deployment then push it onto the IoTHub which will deploy the modules for you (given you have install iotedge & libiothsm on the VM).
