### ISSUE TITLE
Error building Simulated Temperature Sensor Solution in VS Code

### ISSUE THREAD

**Issue by saimachi** [Azure/iotedge#4313]
## Expected Behavior
Upon building the Simulated Temperature Sensor module, I expected to be able to package my model as a Docker container, so I could push the container to Azure Container Registry.

## Current Behavior
When I build the solution, I encounter the following error:

`error CS0234: The type or namespace name 'Edge' does not exist in the namespace 'Microsoft.Azure.Devices' (are you missing an assembly reference?)`

## Steps to Reproduce

1. Clone the repository
2. Navigate to the _SimulatedTemperatureSensor_ project, and copy the _MessageBody.cs_ and _Program.cs_ files.
3. Create an IoT Edge project in Visual Studio Code, providing the required information, including Azure Container Registry path.
4. Replace the _Program.cs_ file in the new project with the _MessageBody.cs_ and _Program.cs_ files from this repository.
5. Execute the _dotnet restore_ and _dotnet build_ commands.

### Output of `iotedge check`

The IoT Edge runtime is functioning correctly on my Ubuntu Azure VM. This issue is about building the Edge module on my Windows workstation. I know that this module exists in Azure Marketplace; however, it doesn't allow me to change the  _MessageCount_ environment variable, which is necessary for my project.

### Device Information

* amd64
* Ubuntu 18.04 LTS

### Runtime Versions
* iotedge version `1.0.10.4`
* Edge Agent (image tag `1.0`)
* Edge Hub (image tag `1.0`)
* `docker version`: `20.10.2+azure` (server)

## Additional Information
My ultimate goal with re-building the _SimulatedTemperatureSensor_ marketplace module is for me to access the _MessageCount_ environment variable so I can set it to _-1_ (no message limit). I tried editing the Module Twin once I deployed the Marketplace module to my Ubuntu 18.04 Edge device, but I had no success changing the message limit for the module. I can send you my proposed code modification to enable this value to be edited.

**Comment by yophilav** [comment]
Hello!
Thank you for the question! It looks like you're running into a dependency issue here. 
Could you please verify and install BOTH `ASP.NET Core runtime 3.1` and `SDK 3.1` please? 
https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by saimachi** [comment]
Hi @yophilav,

I have both of these installed, but I'm still facing trouble:


```
C:\Users\saima>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by yophilav** [comment]
Hmm... 
Did you try re-launching the VS Code after the SDK installation? 
What happen if you run `dotnet restore` under `iotedge\edge-modules\SimulatedTemperatureSensor` directory?

**Comment by saimachi** [comment]
Hi @yophilav,

I tried re-launching VS Code. I also tried restarting my system, but I still have no success.

I also navigated to the directory where the module `.csproj` file is located to run `dotnet restore`. The restore command executes successfully, but building the solution still fails with the same error.

As for the link you sent me, I tried modifying the module twin in Azure portal. However, there is no code in the module to handle a change to the MessageCount value in the module twin configuration. There is code already in place to handle changes to the SendData and SendInterval environment variables, however.

**Comment by yophilav** [comment]
There are 2 questions going on here: 

1. How to change the environment variable of a deployed module? 
If you want to change the environment variable `MessageCount` on the deployed module (the module can be obtained from the marketplace), you can do as follow: 
Go to azure portal -> IoT Hub -> IoT edge -> edge device -> Set modules on device -> Click on the name of the module --> click on environment variables and put MessageCount and -1

2. How to build `SimulatedTemperatureSensor` image from C# code (in case you want to change the module code, not only the runtime env variable). 
2.1 Clone the repository (which you did)
2.2 Navigate to `iotedge\edge-modules\SimulatedTemperatureSensor `
2.3 Run : `dotnet build -c release` 
2.4 Build docker image (module): `docker build --no-cache -t <DockerContainerRegistry>/<ImageName> --file iotedge\edge-modules\SimulatedTemperatureSensor\docker\linux\amd64\amd64\Dockerfile iotedge\edge-modules\SimulatedTemperatureSensor\bin\Release\netcoreapp2.1\publish\`
2.5 `docker push`

**Comment by saimachi** [comment]
@yophilav,

Thanks for your help. I still wasn't able to build the application, but I was able to set the environment variable for the module.
