### ISSUE TITLE
Blank/null Reported properties are coming for edgeHub and edgeAgent status

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#4322]
## Expected Behavior
The reported property of edgeHub and edgeAgent should not come null. 

## Current Behavior
Null values are coming in the edgeAgent and edgeHub reported properties.  This issue started coming since yesterday, as earlier it was working properly and the reported properties were not having null in the status .. 
 
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Check the reported properties on EdgeAgent
2. Reported properties payload is coming like the below 
 

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]:  Windows 10
* Architecture [e.g. amd64, arm32, arm64]:   amd64
* Container OS [e.g. Linux containers, Windows containers]:  Windows

### Runtime Versions
* aziot-edged [run `iotedge version`]:  1.0.8.0
* Edge Agent [image tag (e.g. 1.0.0)]:  1.0.8.0
* Edge Hub [image tag (e.g. 1.0.0)]:  1.0.8.0
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
 

<details>
<summary>aziot-edged logs</summary>

```

 Recieved Twin:
{
"version": 322,
"properties": {
"reported": {
"lastDesiredStatus":

{ "code": 500, "description": "Operation timed out" }
,
"systemModules": {
"edgeHub": {
"restartPolicy": "never",
"exitCode": null,
"statusDescription": null,
"lastStartTimeUtc": null,
"lastExitTimeUtc": null,
"restartCount": null,
"lastRestartTimeUtc": null,
"runtimeStatus": null,
"status": "unknown",
"type": "Unknown",
"settings": null,
"env":

{ "storageFolder": null, "UpstreamProtocol": null }
},
"edgeAgent": {
"exitCode": null,
"statusDescription": null,
"lastStartTimeUtc": null,
"lastExitTimeUtc": null,
"runtimeStatus": null,
"type": "Unknown",
"settings": null,
"env":

{ "storageFolder": null, "UpstreamProtocol": null }
}
},
"modules":

{ "iot-edge-module-upstream": null, "iot-edge-module-mqtt": null }
,
"$metadata": {
"$lastUpdated": "2021-02-02T00:29:26.0173216Z",
"lastDesiredStatus": {
"$lastUpdated": "2021-02-02T00:29:26.0173216Z",
"code":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z" }
,
"description":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z" }
},
"systemModules": {
"$lastUpdated": "2021-02-02T00:29:26.0173216Z",
"edgeHub": {
"$lastUpdated": "2021-02-02T00:29:26.0173216Z",
"restartPolicy":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z" }
,
"exitCode": null,
"statusDescription": null,
"lastStartTimeUtc": null,
"lastExitTimeUtc": null,
"restartCount": null,
"lastRestartTimeUtc": null,
"runtimeStatus": null,
"status":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z" }
,
"type":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z" }
,
"settings": null,
"env":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z", "storageFolder": null, "UpstreamProtocol": null }
},
"edgeAgent": {
"$lastUpdated": "2021-02-02T00:29:26.0173216Z",
"exitCode": null,
"statusDescription": null,
"lastStartTimeUtc": null,
"lastExitTimeUtc": null,
"runtimeStatus": null,
"type":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z" }
,
"settings": null,
"env":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z", "storageFolder": null, "UpstreamProtocol": null }
}
},
"modules":

{ "$lastUpdated": "2021-02-02T00:29:26.0173216Z", "iot-edge-module-upstream": null, "iot-edge-module-mqtt": null }
},
"$version": 306
}
}
}

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by yophilav** [comment]
Thank you for the bug report!
I noticed that you are using release 1.0.8.0 which has been long depreciated. 
At your earliest convenient, could you update the software to be using release 1.0.10.4 please? 
The release 1.0.10.4 includes a lot of important reliability bug fixes along with various security patch updates.

**Comment by varunpuranik** [comment]
@sachidanand - Can you also provide us some more information on what you mean by null values in EdgeHub/EdgeAgent reported properties? Are some fields null, or are the twin reported properties being removed?

And as @yophilav suggests, it will be good for you to move to the latest IoT Edge version - 1.0.10, as we have a number of fixes in it.
