### ISSUE TITLE
Using Azure Blob Storage as filesink for LVA

### ISSUE THREAD

**Issue by sanjaybhagia** [Azure/iotedge#4332]
Hi, 

Is it possible to use Azure Blob Storage as file sink (Microsoft.Media.MediaGraphFileSink) in media graph for Live video analytics? 
Currently, we can use Microsoft.Media.MediaGraphFileSink for local filesystem in the graph but I'm keen to understand if Blob storage is an option is this scenario. 

This will allow me to use the blob storage to store files locally which I can synchronize to the storage account in the cloud. As of now, I'm using assetSink (Microsoft.Media.MediaGraphAssetSink) for this purpose to push assets (videos primarily coming from RTSP source) to Azure Media Services account. 

Any guidance would be appreciated. 

Thanks
Sanjay

**Comment by yophilav** [comment]
Hello @sanjaybhagia,
Did you have a chance to look into `Azure Blob Storage on IoT Edge` found here?
https://azuremarketplace.microsoft.com/en-in/marketplace/apps/azure-blob-storage.edge-azure-blob-storage?tab=PlansAndPrice
If you need further assistant please feel free to open a support ticket from Portal against Azure Storage Team (not IoT Edge).

Thank you!

**Comment by sanjaybhagia** [comment]
Hey @yophilav,

Thanks for your reply. Yes I have checked that and that's what I'm using. 
in my media graph, I'm tyring to use the File sink: 

{
		"@type": "#Microsoft.Media.MediaGraphFileSink",
		"name": "fileSink",
		"inputs": [
			{
				"nodeName": "signalGateProcessor"
			}
		],				
		**"filePathPattern": "/srv/containerdata:/blobroot/tagged/filesink-${System.DateTime}"**
			}
			
the filePath I've tried to use are:
- /srv/containerdata/BlockedBlob/tagged/filesink-${System.DateTime} (this is the path that AzureStorage Module create when we bind the volume (I use this in HostConfig section of the topology:   "Binds": [
                                        "/srv/containerdata:/blobroot"
                                    ],
- /srv/containerdata:/blobroot/tagged/filesink-${System.DateTime}


both of these didn't work for me. If i specify any other path on my host, the fileSink generates the files just fine. 

I will check with the Storage team as well. 

Thanks
Sanjay

**Comment by fvneerden** [comment]
Hi Sanjay,

Currently we do not support to write to a blob endpoint directly. This is on our roadmap and we expect to have a feature that will allow to write to a blob endpoint using a SAS locator soon.
For now, you could write the files to local storage (File Sink) and create your own micro service wrapper that read the files from disk/mount and push to blob by using the Azure Blob SDK/CLI? https://docs.microsoft.com/azure/storage/blobs/storage-quickstart-blobs-cli

**Comment by sanjaybhagia** [comment]
Thanks for your reply @fvneerden. This sounds interesting approach worth trying. Do you have any rough timeline when this feature would be coming out?

**Comment by micahl** [comment]
@sanjaybhagia thanks for filling this issue.  I'm closing this issue here, but please consider opening a feature request for Live Video Analytics under the [Azure Media Services ](https://feedback.azure.com/forums/169396-azure-media-services) feedback forum.
