### ISSUE TITLE
Invoke method from one module to other module.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/iotedge#4352]
Hi,

We have a requirement where we need to invoke method from one module to another module.

Let say ,following are my 2 modules.
1. leafDevice.  
2.  iot-module

Functionality of communication to cloud  will be part of iot-module and leaf device will send command to iot-module and iot module will communicate with cloud on behalf of leafDevice.
For eg.  sendD2CMessage.
So in this example leafDevice will send command to iot-module and iot-module will send Device to cloud message of leafDevice.

I am using azure c-sdk and i can see this can be done using module-client in 2 ways.

1. messages :  If leafDevice sends message to iot-module but iot-module cannot send any response to leafDevice instead of success/Fail, means iot-module cannot return messageId to leafDevice module in response.

2. Direct method:  There is a way to send direct method from one module to another module and direct method can send response to caller module, **but direct method can be receive from cloud as well. So we cannot distinguish the direct method on iot-module whether it was invoked from leafDevice Module OR invoked from cloud.** . Is there a way to to identify whether direct method on module(iot-module) received from another module or received from cloud ?

Please let me know what is the best way to do this.

**Comment by yophilav** [comment]
Hi @rajaggrawal 
Thank you for question. I'm assuming `iot-module` mention here is your custom module that somewhat behaves like EdgeHub, so I'm not going to mention anything EdgeHub specific here. 

I believe there are 2 major questions here that need to be answered. 
1. What method should I use Messaging vs Direct Method? 

Please refer to our documentation here 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling
for the trade-off and limitation of the communication methods.

2. How can I capture/distinguish a response from the cloud (IotHub) vs my custom module (iot-module)?
2.1 Direct Method path: you could break the communication route into 2 portion: leafDevice --A--> iot-module --B--> IoTHub. This should allow you to receive the response from (A) which indicate that the message get to your module. and (B) which ack if the message gets to the cloud. 
2.2 Message path: you can have create a reply message if the module ever receive a the message: leafDevice <===> iot-module --> IoTHub. In which this message, reply to the sender if a message is received from the module?

**Comment by rajaggrawal** [comment]
Thanks @yophilav .

Let me more specific.

let say i have 2 custom module(A and B)
A ---> B
Module A wants to invoke direct method of module B and direct method of module B can be invoke from cloud as well.
So how will i know the direct method received at module B is initiated from cloud or from module A ?

**Comment by veyalla** [comment]
You can use a different direct method payload when calling from IoT Hub vs local module.

**Comment by rajaggrawal** [comment]
@veyalla 
Thanks, but different payload will not solve the purpose as somebody can accidently send same payload from cloud as well :)

Let me explain the problem scenario.
Let say my directMethod name is updateDeviceReportedProperties.

Once module B receive updateDeviceReportedProperties direct method then it will update the reported properties of a device.

But the problem is  updateDeviceReportedProperties direct method can be also triggered from cloud as well  and module B will update reported properties of a device. As per IoT Architecture, reported properties should be updated from device but in this case reported property can be updated from cloud hence we are looking a way to restrict direct method from cloud.

**Comment by yophilav** [comment]
Hi @rajaggrawal 

I think what veyalla was referring to the `payload` content which you can put a deviceId or moduleId. 
As shown here:  https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods#method-invocation
