### ISSUE TITLE
Edge hub module does not strictly check route schema

### ISSUE THREAD

**Issue by florianbader** [Azure/iotedge#4353]
## Expected Behavior
The edge hub module should warn or even throw an error if a route is not strictly based on the route schema.

## Current Behavior
The edge hub module is ignoring if a route is not completely conform to the route schema. This will ignore conditions that are not in the correct place in the route.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a route with a condition at the end:  
`FROM /messages/modules/module1/outputs/telemetry INTO $upstream WHERE some-property == 'true'`
2. Edge hub will start successfully but ignores the condition

### Output of `iotedge check`

not needed

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Debian 9, Windows 10
* Architecture [e.g. amd64, arm32, arm64]:  amd64, arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux containers 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.0.10
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.0
* Docker/Moby [run `docker version`]: doesn't matter

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>edge-hub logs</summary>

```

<6> 2021-02-05 07:51:08.179 +00:00 [INF] - Set the following 1 route(s) in edge hub
<6> 2021-02-05 07:51:08.180 +00:00 [INF] - TestRoute: FROM /messages/modules/module1/outputs/telemetry INTO $upstream WHERE some-property == 'true'
<6> 2021-02-05 07:51:08.188 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2021-02-05 07:51:08.190 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2021-02-05 07:51:08.343 +00:00 [INF] - Started operation Get EdgeHub config

```

</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by yophilav** [comment]
This appears to be expected from the current design. 
We rely on the entry points to do full on validation i.e. Az portal, VsCode, etc...
With that said, It seems like the entry points aren't checking for this either.

**Comment by yophilav** [comment]
If you would like to suggest an enchanted feature please feel free to add your suggestion here: 
https://feedback.azure.com/forums/907045-azure-iot-edge

Thank you!
