### ISSUE TITLE
IoT Edge Messages Sending

### ISSUE THREAD

**Issue by qiufan** [Azure/iotedge#44]
## Current Behavior
Is there any speed limitation of sending messages to the IoT Hub in the IoT Edge? I built a customer module in the IoT Edge which would send 10 messages per second to the IoT Hub. Meanwhile, I could only retrieve 3 or 4 messages per second from the IoT Hub. The latency between the transmitting and receiving of the message increases with the time goes by.

I do two tests. First, I test a normal IoT Device without IoT Edge and adjust the price of IoT Hub. It seems that the IoT Hub can handle more than 10 messages per second. Second, I kill the customer module and shutdown the IoT Edge service(“systemctl stop iotedge”) immediately. The message receiver for the IoT Hub will stop immediately. Then I restart the IoT Edge service, the blocked messages of the “old” customer module will show from the IoT Hub. Although currently the customer module has sent new messages to the IoT Hub. By the way, the device is a PC with Linux OS.

## Steps to Reproduce

1.built a customer module in the IoT Edge which would send 10 messages per second to the IoT Hub. 

### Device (Host) Operating System
Ubuntu 16.04 and Windows IoT Core

### Architecture
amd64

### Container Operating System
Linux containers

### Runtime Versions
iotedged

#### Docker
18.03.1

## Logs

![screenshot from 2018-07-20 13-19-17](https://user-images.githubusercontent.com/15119627/42991621-b4a457dc-8c38-11e8-833b-634c343aefae.png)

**Comment by darobs** [comment]
Hello @qiufan 

We are currently working on stress and performance tests to help evaluate and predict performance, but we don't yet have data to share. You should see some PRs related to stress testing coming soon.

Seeing a 60-70% drop in performance isn't what I would have expected to see, especially if it is a simple route to upstream.  I'll make sure we add a task to evaluate this during stress testing.

>  Then I restart the IoT Edge service, the blocked messages of the “old” customer module will show from the IoT Hub. Although currently the customer module has sent new messages to the IoT Hub.

This is expected behavior - the edgeHub will store incoming message and process them in the order which they were received.  If there was a backlog of messages when the edgeHub was stopped, we would continue to process them when it is restarted.

**Comment by qiufan** [comment]
Good morning~ @darobs Is there any progress about the stress testing results? I'm not familiar with the protocol of the stress testing. If you need any help or detailed data about this issue, please tell me. 😄

**Comment by qiufan** [comment]
Hello @darobs 

It's glad to see the new version 1.0.1 of the EdgeHub module. I did some tests based on the python sdk and c# sdk just now. It seems that there is still an upper limit for the message frequency from a custom module to the IoT Hub.

Is there any result of the stress and performance tests or plan about this issue now?

thanks.

**Comment by myagley** [comment]
@qiufan there are no throttling limits in the Edge Hub itself. With a moderate sized VM, and a multi-module deployment, you can expect somewhere in the neighborhood of ~1000 msg/sec. You should be able to easily achieve 10 msg/sec.

However, there is throttling in place for IoT Hub, which will limit the rate at which messages can be sent upstream. More info here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling

Do you have any more information about the size of the device that IoT Edge is running on?

**Comment by qiufan** [comment]
Hello @myagley 

Thanks for the reply. For this issue, I did the following tests for now~
1. The throttling speed between modules can be easily higher than 10 msg/sec(I did the test under 100msg/sec).
2. I tried several IoT Hubs with different size(S1, S2, S1 with 3 unit). In my understanding, the S2 can easily meet my needs.
![image](https://user-images.githubusercontent.com/15119627/44500841-297eb680-a6bd-11e8-95c4-0904d469f6e7.png)
![image](https://user-images.githubusercontent.com/15119627/44500806-018f5300-a6bd-11e8-95e5-14ecb9f3fc7d.png)
3. An important test is that I built a normal device in the IoT Hub instead of an IoT Edge Device. Then, in the customer module, I sent the messages(10 msg/sec) through the normal device(using its connection string to build a new connection) to the IoT Hub directly. I could fetch the messages from the IoT Hub with a stable latency.
4. I tried the both python and c# sdk in the customer module.

Besides, what do you mean the size of the device that IoT Edge is running on? I use a PC(E5-1620, 16GB) as the Edge device now. I checked the Azure Portal again and I didn't find the setting for the size of IoT Edge. Please let me know if I ignore some important settings.

According to the tests I have done, I opened this issue. However, this issue is quite weird. I cannot confirm the root cause for this phenomenon. If you cannot reproduce this issue, please share the details of your settings with me. Thank you very very much!

**Comment by qiufan** [comment]
Hi~ @myagley 
I create a totally new IoT Hub with S2 and a set of new devices.  Besides, I  also install the Edge Runtime on another PC(windows, i7, 8GB) and try it. The phenomenon still exists in both situations.
Any suggestion or test result about this issue?
Thanks~

**Comment by saikovvuri** [comment]
@qiufan  do you mind sharing your custom module and receiver side code. 
thanks

**Comment by azthec** [comment]
Hi, I seem to be encountering the same issue.

I have been trying to determine some performance metrics, one of which is measuring RTT.

Scenario one, where the simulated device directly connects to the IoT Hub, the Hub is able to handle 160 Messages per second with very little throttling.
Scenario two, a downstream device connects to a IoT Edge device which has a simple upstream route, the device begins throttling heavily at just 10 Messages per second.

I have attempted to mess about with the OptimizeForPerformance variable, manually setting it to True, deleting it, etc. Are there any other configurations I am missing that may be causing this?

**Comment by lt72** [comment]
@vipeller: can you please take a look at last question above?

**Comment by vipeller** [comment]
@lt72 @azthec I suppose the test used AQMP. Try MQTT which works faster. We found some room to improve AQMP performance on edge hub, but it is not coded yet.

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
