### ISSUE TITLE
Support for Azure IoT Edge on Suse SLES 12.3 or 15

### ISSUE THREAD

**Issue by Rumpkie** [Azure/iotedge#4405]
Looking to peace together an approach for getting the azure IoT Edge to run on Suse Enterprise 12.3 or 15.1 due to organizational constraints we are not able to run one of the tier one or tier two suggested Linuxes. I would love to work with someone on resolving this issue. 

So far I have tried the snap approach from the Ubuntu snaps, but project is very old and has not been updated in a few years.

I have tried installing using the Redhat/centos approach since the Suse installer supports RPMs but quickly run into major breaking package conflicts.

Any ideas are welcome.

**Comment by arsing** [comment]
You can't reuse the CentOS RPMs due to different package names, as you found, but you can build from source. I myself use openSUSE Tumbleweed to work on it as a developer so I know it works. We also had [this issue](https://github.com/Azure/iotedge/issues/938) where the OP was able to build it on SLES 12.

**Comment by Rumpkie** [comment]
Ok, I will give this a shot and see what comes of it, ill reply back with my results, and instructions if it works.

**Comment by shoop** [comment]
@arsing we are interested in SLES support as well. What does it take for SLES to be listed in the Tier 2 table list of supported operating systems?

**Comment by arsing** [comment]
That's a question for @veyalla , I think.

**Comment by micahl** [comment]
@shoop please open a feature request at https://aka.ms/iotedge-suggestion with some context on the request.  We do look at upvotes to help gauge general interest.

@Rumpkie were you able to get it working?  If so please do share your instructions in case others are looking to do the same and let's close this issue.

**Comment by Rumpkie** [comment]
> @shoop please open a feature request at https://aka.ms/iotedge-suggestion with some context on the request. We do look at upvotes to help gauge general interest.
> 
> @Rumpkie were you able to get it working? If so please do share your instructions in case others are looking to do the same and let's close this issue.

I was not able to get this either through munging library names nor through trying to build sles rpms. There were just too many errors.  I did get it running but It wasn't able to send telemetry to the IoT hub.

**Comment by shoop** [comment]
@micahl Thank you, [I opened a suggestion](https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/42829248-add-suse-enterprise-linux-sles-to-at-least-tier).

**Comment by micahl** [comment]
Thanks, @shoop!  @Rumpkie sorry to hear it didn't work out.

**Comment by Rumpkie** [comment]
I think we will come up with a solution, @micahl, and @shoop, I really appreciate your help.

**Comment by micahl** [comment]
@shoop, I'm closing this issue in lieu of the feature request you opened. Thank you for providing extra context on the ask.
