### ISSUE TITLE
Storing runtime containers in private registry - still accessing *.blob.core.windows.net

### ISSUE THREAD

**Issue by haverboecker** [Azure/iotedge#4438]
Hello!

Maybe someone can help me with this or point me in the right direction. I didn't find anything about this by searching, but maybe someone of you already got this covered.

We have deployed an iot edge device at a customers site. There, we have to define the traffic that should be allowed by the device, per IP.
I was following this guideline: https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-2018-06 
There it states to remove the need for *.mcr.microsoft.com, we could put the runtime images into our own repository. I did that by pulling the image and pushing it into the private repository.
It turns out that the *.blob.core.windows.net is still needed, and we cannot put placeholders in the firewall rules. See attached screenshot.
By the manifest and the URL, it seems the top part of the manifest is being requested from *.blob.core.windows.net. See URL and config.digest from here:
```

{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 7732,
		"digest": "sha256:0c50536b67179407e7f57c6e71f76ce959910c2e46be523d00a4b0d91d0d0317"
	},
	"layers": [
		{
			"mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
			"size": 22290808,
			"digest": "sha256:74cafcd4ef026d0cf9395503338bf02bc26e4f71aea4689608583ce51623688c"
		},
	...
	]
}

```

So, my questions is:
How can I prepare a device so that solely the access to our own repository is needed, and no placeholder registry?

Thanks for any hints!

Best regards,

Peer
![image003](https://user-images.githubusercontent.com/61307912/108335111-88f4a900-71ca-11eb-90a3-6a38c146d0c0.png)

**Comment by veyalla** [comment]
@SteveLasker any guidance there?

**Comment by SteveLasker** [comment]
Looks like this isn't using the [ACR Dedicated Data Endpoint ](http://aka.ms/acr/dedicated-data-endpoints )feature.
If enable Private Link, you get dedicated data endpoints by default. For public data exfiltration concerns, you need to opt-into dedicated data endpoints as changing them for customers would be a breaking change. 

The ideas around not depending on any public registries, including mcr, is covered in this co-authored article: [Consuming Public Content](https://opencontainers.org/posts/blog/2020-10-30-consuming-public-content/)

**Comment by haverboecker** [comment]
Hello @SteveLasker and @veyalla !

Thanks for the input, it seems like that's the problem. I was unaware of the additional data endpoints.
Unfortunately, I will only be able to test this next week. If I get this working, I will close the topic.

Thanks again and best regards,

Peer

**Comment by haverboecker** [comment]
I just tried it, it seems to work now. Thanks for your  help!
