### ISSUE TITLE
Hardware requirements Azure IoT Edge

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#45]
Hi there,

What are the minimal hardware requirements to run Azure IoT edge?
I'm not only interested in the numbers, but also in supported chipset architectures (such as ARM).

Kind regards, Norbert Huurnink

**Comment by darobs** [comment]
Hello @nhuurnink,

We haven't defined minimum specs on the IoT Edge runtime, but our objective was to perform well on a Raspberry Pi 3 or similar device.  The actual performance is determined by the number of modules, what these modules are doing, and how they interact.

We are currently working on stress and performance tests to help evaluate and predict performance, but we don't yet have data to share.

Please see [Azure IoT Edge Support](https://docs.microsoft.com/en-us/azure/iot-edge/support)  for officially supported platforms.  

We are interested in supporting platforms our customers use, and if you have a specific interest please [provide us with feedback.](https://feedback.azure.com/forums/907045-azure-iot-edge)

**Comment by nhuurnink** [comment]
Is there any chance there will be support for non-arm processor architectures in the short-middle term? Or is this completely out of scope?

We want to combine IoT Edge software with cost-efficient supporting hardware, therefore I'm very interested in IoT Edge's strategy in regard to this matter.

**Comment by darobs** [comment]
We have three primary programming language dependencies: C, Rust and DotNet Core.  Rust is fairly well represented across all platforms that LLVM will support.  DotNet Core platform support is determined by the DotNet Core team - so user feedback is especially important for questions like this. 

Thanks,

**Comment by gauravagarwal28** [comment]
> We are currently working on stress and performance tests to help evaluate and predict performance, but we don't yet have data to share.

@darobs Has there been any update regarding this?

It would be nice if we could have some minimum hardware requirements IoT Edge - for both AMD64 as well as ARM32 (I see ARM64 is not yet listed as a supported platform even though you have mentioned that you are aiming for raspberry pi 3 which has **64-bit** quad-core ARMv8 CPU).

**Comment by arsing** [comment]
>(I see ARM64 is not yet listed as a supported platform even though you have mentioned that you are aiming for raspberry pi 3 which has 64-bit quad-core ARMv8 CPU).

The RPi3's arm64v8 CPU can run arm32v7 binaries, which is why it was always supported.

Regardless, 1.0.8-rc1 onwards have native arm64v8 packages.

**Comment by jaredhagel** [comment]
Just to clarify, there is no support for 32 bit non-ARM Linux systems, is there? Thanks!

**Comment by arsing** [comment]
That's correct. See the link darobs posted above.

**Comment by jaredhagel** [comment]
Thank you for the prompt reply. So the biggest problem is lack of x86 Linux Support for DotNet Core? How can we provide user feedback to encourage Microsoft to add support for this? This is also very important for our organization. We have many devices that would really benefit with DotNet Core installed.

**Comment by arsing** [comment]
>So the biggest problem is lack of x86 Linux Support for DotNet Core?

That is one problem. If your hardware is not i686, it will also not be supported by [Rust](https://forge.rust-lang.org/release/platform-support.html) (only i686 is tier 1, i586 is tier 2, i486 and lower are completely unsupported).

Depending on what specific processor you have, there may be other reasons that prevent us from supporting it.


>How can we provide user feedback to encourage Microsoft to add support for this?

https://feedback.azure.com/forums/907045-azure-iot-edge

**Comment by chli** [comment]
Hi, what is the minimal amount of storage necessary ? I'm interested in the whole stack running on ARM7. There is of course the iotedge daemon and it's dependencies but then you must pull the edgeAgent and edgeHub and those are quite big it seems.
