### ISSUE TITLE
X.509 documentantion

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#4514]
There seems to be some inconsistency between documentation and code.
The scripts to create certificates for the Azure IoT Edge are mentioned in https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs?view=iotedge-2018-06, are referencing https://github.com/Azure/azure-iot-sdk-c/tree/master/tools/CACertificates. However if you follow the link and take a look at the [README](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) you'll notice that its content differ from https://github.com/Azure/iotedge/blob/master/tools/CACertificates/README.md. While the content seems to be similar for leaf devices, it differs for edge devices (only the one in `iotedge` distinguishes CA and identity certificates for the edge. I believe at least the documentation should point to the `iotedge` repository, but to have multiple varying documentation parts is itself an additional problem.

**Comment by veyalla** [comment]
Thanks for the report @alaendle. Tagging @kgremban for docs update.

**Comment by kgremban** [comment]
@veyalla I believe this issue was addressed when @massand updated the links to the scripts.
