### ISSUE TITLE
Documenation of implications of the dynamic_reprovisioning flag

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#4515]
I really miss information regarding the implications of the dynamic_reprovisioning flag; it is mentioned in a few issues (e.g. https://github.com/Azure/iotedge/issues/4241) and is briefly described in a few lines in the config.yaml. But why is it set to default `false`? What are the implications of setting it to `true`? Under which circumstances is the reprovisioning triggered? Does this have impacts on offline scenarios? Hopefully I haven't missed the answers somewhere in the already available documentation.

**Comment by and-rewsmith** [comment]
This link explains the high level of dynamic reprovisioning:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs?view=iotedge-2018-06

There is more information here which I believe answers your question:
https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device-reprovision?view=iotedge-2018-06#reprovisioning-policies

It seems that the dps enrollment group has policies which determine how reprovisioning is triggered.

**Comment by alaendle** [comment]
Thanks @and-rewsmith for the quick response. However the mentioned documentation doesn't answer all the questions. I also should have mentioned that we aren't using DPS. So we have a simple IoTEdge instance (with an dynamic_reprovisioning flag in it's config.yaml) directly connected to a Azure IoTHub. What is the essence of the flag? Under which scenarios does it's value influence the behaviour? What requirements should determine the flags value? 

To even add some more context; we spotted the flag, while searching for a solution to reconnect our edge devices after a redeployment of the IoTHub - it doesn't work with `false` and it should work in the future with `true` (https://github.com/Azure/iotedge/issues/4458). Therefore, I am looking for documentation in order to be able to assess which side effects we may encounter.

**Comment by and-rewsmith** [comment]
@alaendle  My understanding is that dynamic_reprovisioning is a dps (device reprovisioning service) specific setting.  Tagging @kgremban as we might need to update the docs here to give more context to the dynamic_reprovisioning flag.

**Comment by veyalla** [comment]
@arsing has an PR that improves config.yaml docs around this: https://github.com/Azure/iotedge/blob/e25cff135cde6fac2887fa33268b2e786a1fcbdf/edgelet/contrib/config/linux/config.yaml#L74

@alaendle - Does this help? We plan to mirror this information in our main docs. Let us know if any further clarification is required.

**Comment by alaendle** [comment]
@veyalla @arsing Many thanks; that's indeed enough information for now. I will let you know if more specific questions occur during the usage of this feature 😄 . So from my side this is issue is resolved. Once again, thanks!

**Comment by alaendle** [comment]
@veyalla @arsing @F-Joachim Sorry, but I have one more question regarding the dynamic device reprovisioning feature. Is it possible or even expected that in-flight messages on the local edge hub are lost during the reprovisioning?
