### ISSUE TITLE
Failed to install Moby Runtime on Raspberry Pi4 due to stretch packaged not matched 

### ISSUE THREAD

**Issue by timzhan** [Azure/iotedge#4563]
I am trying to install Azure IoT Edge on my new Raspberry Pi4 and failed.

After running below script, I got error while trying to update the package list on the device.

### Raspberry Pi OS Stretch:
`curl https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list > ./microsoft-prod.list`
### Copy the generated list to the sources.list.d directory.
`sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/`
### Install the Microsoft GPG public key.
`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`
`sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/`
### Update package list
`sudo apt-get update`

The error I got is as below:

![2021-03-08_165008](https://user-images.githubusercontent.com/66768111/110298700-d88efd80-802f-11eb-8d33-94f390d72c19.png)

I verified the package on the Github. The expected file size is 10080 as below screenshot.

![image](https://user-images.githubusercontent.com/66768111/110299292-75ea3180-8030-11eb-9b30-4cdea7b202a6.png)

As a result, I cannot install the Moby Runtime.
![2021-03-08_170812](https://user-images.githubusercontent.com/66768111/110299751-06c10d00-8031-11eb-814a-853aaa10e04f.png)

Could you help fix this issue?

Appreciated!

**Comment by nanowireUK** [comment]
Can replicate this issue on two separate installations I have as well

**Comment by veyalla** [comment]
Following up internally with the Linux repos team.

**Comment by micahl** [comment]
This should now been fixed.  Thanks for reporting it, @nanowireUK!
