### ISSUE TITLE
Installing IoT edge on Debian cause an error in package search

### ISSUE THREAD

**Issue by Sdelausnay** [Azure/iotedge#4564]
## Expected Behavior
Install IoT Edge on Linux Debian (RPI) requires a ```sudo apt-get update``` which will go over all the packages directories, including the added once from Microsoft. 

## Current Behavior
When calling  ```sudo apt-get update```, on the package directory of Microsoft, we get following error:
```
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Get:4 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main armhf Packages [9,633 B]
Err:4 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main armhf Packages
  Writing more data than expected (10080 > 9633)
  Hashes of expected file:
   - Filesize:9633 [weak]
   - SHA512:9647f5abb5207ba12d5b3451617e8fb8edf15b4d153ac36dc556d6efa0fd55130a2b95544cb0749d1f2ea937b9b6ba105ac66444d87f6ff49b165d38fc8ae7cf
   - SHA256:eafce3a374dbe39c74a32999a738d759a0d4a17927d99f9799f5b12de1cb2af2
   - SHA1:5b84c2de72e9fcda7e2d94139826fcb9e6cc0fae [weak]
   - MD5Sum:998af8cdb0f6c97fc4f39215528f8cf4 [weak]
  Release file created at: Sat, 06 Mar 2021 02:24:12 +0000
Fetched 25.3 kB in 6s (3,695 B/s)
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/debian/stretch/multiarch/prod/dists/stretch/main/binary-armhf/Packages.bz2  Writing more data than expected (10080 > 9633)
   Hashes of expected file:
    - Filesize:9633 [weak]
    - SHA512:9647f5abb5207ba12d5b3451617e8fb8edf15b4d153ac36dc556d6efa0fd55130a2b95544cb0749d1f2ea937b9b6ba105ac66444d87f6ff49b165d38fc8ae7cf
    - SHA256:eafce3a374dbe39c74a32999a738d759a0d4a17927d99f9799f5b12de1cb2af2
    - SHA1:5b84c2de72e9fcda7e2d94139826fcb9e6cc0fae [weak]
    - MD5Sum:998af8cdb0f6c97fc4f39215528f8cf4 [weak]
   Release file created at: Sat, 06 Mar 2021 02:24:12 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Fresh install of Debian on a RPI
2. Add the [Microsoft installation packages](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06)
4. Execute  ```sudo apt-get update```

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Debian 9 stretch 
* Architecture [e.g. amd64, arm32, arm64]: ARM64

**Comment by edgarbenet** [comment]
we have experienced exactly the same problem!
Probably is due to the change made on 6 of March in the directory /strech
[https://packages.microsoft.com/debian/stretch/multiarch/prod/dists/](https://packages.microsoft.com/debian/stretch/multiarch/prod/dists/
)

**Comment by micahl** [comment]
@edgarbenet and @sdelausnay, this appears to be the same issue as #4563 which should be fixed now.  Closing this issue.  If it still repros then please re-activate.
