### ISSUE TITLE
A custom module is 'Disconnected' in "IoT Edge hub connections"

### ISSUE THREAD

**Issue by bjbang** [Azure/iotedge#4567]
Hi,

When a customer checked the status of a custom module(‘BLTOperatingService’) in “IoT Edge hub connections” section of Edge device, it is displayed as “Disconnected” like the following screenshot and doesn't return back to 'Connected'. 
It looks that there are no specific operation errors even though it is in “Disconnected” status. (The module has a role to provide REST API. If it is called, the output is written to Kepserver.)
![IoTEdgeHubconnections](https://user-images.githubusercontent.com/69458812/110423994-68db4a00-80e5-11eb-9aeb-2781b7dd3080.jpg)

But, the module is “running” status in “Modules” section as follows.
![Modules](https://user-images.githubusercontent.com/69458812/110424027-755fa280-80e5-11eb-8093-94395b0613cc.jpg)

The modules use azure-iot-sdk-java.
The module initializes using createFromEnvironment. The below is the main function of the module.
![mainfunction](https://user-images.githubusercontent.com/69458812/110424250-d5eedf80-80e5-11eb-8998-0df93cff03e8.jpg)

 
**Questions:**
1. Why is the module displayed as "Disconnected"? Is it the module's problem?
2. When it is disconnected, can it be changed to "Connected" again? If so, how to?
3. The customer would like to know if “Disconnected” can cause any side effects.

**Comment by darobs** [comment]
Hi @bjbang 

As far as I can tell, this information is coming from $edgeHub's reported properties, and this should indicate that the module has an open connection to EdgeHub.  I think the problem with it reporting "Disconnected" is that the customer is probably not subscribing to any connectivity events in their code.  Just opening the client is not sufficient to establish and maintain the edgeHub connection.

In general, setting a handler for methods, twin or messages will maintain the connection, as will sending events.

**Comment by darobs** [comment]
One risk: Once a ModuleClient is created and becomes disconnected, we have found it to be more reliable to open a new ModuleClient and close the old.  You can see this in our code [here](https://github.com/Azure/iotedge/blob/c0bad527da979fc0d8d1c810474e5078dfee83ca/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ClientTokenCloudConnection.cs#L116) for example.

**Comment by bjbang** [comment]
Thanks for your comments.
I received the below reply from the customer.

'BLTOperatingService' module registers the connection status callback like the below screenshot. 
And so, when the module receives disconnected event, it will be ended and then will be restarted by the agent. So the customer believes that it was implemented according to your guide. Any comments for the customer's opinion?
**Note**: Other modules are also implemented as 'BLTOperatingService' module is implemented for disconnected event. But this symptom only occurs in 'BLTOperatingService' module.

![connectionsStatusCallback](https://user-images.githubusercontent.com/69458812/110792996-7811f180-82b7-11eb-9dcd-8be61b11d131.jpg)

**Comment by darobs** [comment]
I think the pattern is correct, but there's something missing.  Do you have logs for this BLTOperatingService module that shows the connection state logged in the `execute` function?

**Comment by bjbang** [comment]
The attachment is the log for edgeHub and 'BLTOperatingService' module that the problem seems to be happened.
Note: There is no further log after the last log in 'BLTOperatingService.log'.

[BLT_0312.zip](https://github.com/Azure/iotedge/files/6129148/BLT_0312.zip)

**Comment by darobs** [comment]
Taking a look, thank you for the logs.

**Comment by darobs** [comment]
The edge module was reported as disconnected because it was not able to connect to the edgeHub module.
 Is the user able to run `iotedge check`?  I think that's the next, best step, because the the common errors that cause the kind of errors I'm seeing are check with that tool.

**Comment by bjbang** [comment]
The below is the result of "iotedge check".
======
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9 but 1.1.0 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect to hhi-shipbuilding.azure-devices.net:5671
        caused by: connection timed out
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
× container on the default network can connect to IoT Hub AMQP port - Error
    Container on the default network could not connect to hhi-shipbuilding.azure-devices.net:5671
        caused by: docker returned exit code: 1, stderr = Error: could not connect to IoT Hub: connection timed out
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the azure-iot-edge network could not connect to hhi-shipbuilding.azure-devices.net:5671
        caused by: docker returned exit code: 1, stderr = Error: could not connect to IoT Hub: connection timed out
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
4 check(s) raised warnings.
3 check(s) raised errors.

**Comment by darobs** [comment]
Hi @bjbang,
From that `iotedge check` output, the things I would check first:

Is EdgeHub set with "UpstreamProtocol: AmqpWs" (Please see [this information](https://docs.microsoft.com/azure/iot-edge/production-checklist?view=iotedge-2018-06#choose-upstream-protocol))

and the DNS warning here:
> Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
> Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.

Hope that helps!

**Comment by bjbang** [comment]
Hi @darobs 

The below is the response from the customer.
====
We use MQTT as UpstreamProtocol. Is it okay?

From the "DNS warning", should we have to configure DNS server setting? Is it mean that our module could be disconnected because of the lack of DNS setting? We have two questions.
1. If the lack of DNS setting can affect the connection between IoT Hub and edge modules, can it also affect the connection between edgeHub and edge modules?  
2. If so, should configure the DNS server setting in Production?

Currently, it doesn't care although 'BLTOperatingService' module is disconnected because there is no operation error in the flow of data.
We worry that other major modules could be disconnected. It is because other modules can cause operation errors. Any comments on this?

**Comment by bjbang** [comment]
Hi @darobs,
Any comments or insights for some questions?

**Comment by bjbang** [comment]
Hi @darobs, any comments?

**Comment by bjbang** [comment]
Can you please add comments for some questions?

**Comment by veyalla** [comment]
Closing this as I see you've open a support ticket for this.
