### ISSUE TITLE
Not able to route reported property of leaf-device to iotedge custom module .

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/iotedge#4581]
I am using iot-edge as a transparent gateway and trying to access reported property of leaf-device inside custom module.
I have added following route to access leaf-device reported property inside my custom module (management-suite).

**FROM /twinChangeNotifications INTO BrokeredEndpoint("/modules/management-suite/inputs/input1")**

I have set a callback to receive message at input1 but not receiving any messages when leaf-device update reported property.
Could you please help me to receive reported property of leaf device to custom module ?
Please let me know if any additional change is needed.

**Comment by darobs** [comment]
Hi @rajaggrawal,

That route looks correct.  I tried the route out on a running system, and it parsed correctly, but I have not yet had the opportunity to test if it receives messages from leaf devices.  I will try this with a leaf device and let you know.

**Comment by darobs** [comment]
Hi @rajaggrawal,

Here's what I did:
1. create an edge device with a module named "management-suite" (I just used the SimulatedTempSensor module) in IoT Hub
2. created a leaf device in IoT Hub and made it a child device or my edge.
3. added a route named "twin": `FROM /twinChangeNotifications INTO BrokeredEndpoint("/modules/management-suite/inputs/control")`  - "control" is a input SimulatedTempSensor listens to.
4. Ran the [csharp Twin sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/device/TwinSample) with the connection string set with "GatewayHostname=<edge device>" so it connected through edgeHub.
5. I did see a message received by my "management-suite" module:
```
Received message Body: [{"DateTimeLastAppLaunch":"2021-03-11T18:15:10.0001615-08:00"}]
```

Some things to check:

- Make sure the route is reported correctly in the edgeHub logs.  You should see a message like this:
```
<6> 2021-03-12 02:07:11.993 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Config.ConfigUpdater] - twin: FROM /twinChangeNotifications INTO BrokeredEndpoint("/modules/management-suite management-suite/inputs/control")
```

- Make sure your device is connected through the edgeHub. The "/twinChangeNotifications" only records changes made through edgeHub. If the leaf device is connected through the edgeHub, then it will show up in the portal as a connected device ("dwr-leafdev" is my device here):

![image](https://user-images.githubusercontent.com/15346492/110884256-b1d3ff80-8299-11eb-892e-6b668fe9ec02.png)

**Comment by rajaggrawal** [comment]
Just wanted to cross check whether i am using correct method  to receive twinChangeNotifications. 

I am using c sdk and invoked following method to receive twinChangeNotifications.
IoTHubModuleClient_SetInputMessageCallback(iotHubModuleClientHandle,"input1",messageConfirmationCallback,nullptr);

Will management-suite module  receive twinChangeNotifications as message  or some other way?

**Comment by darobs** [comment]
> Just wanted to cross check whether i am using correct method to receive twinChangeNotifications.
> 
> I am using c sdk and invoked following method to receive twinChangeNotifications.
> IoTHubModuleClient_SetInputMessageCallback(iotHubModuleClientHandle,"input1",messageConfirmationCallback,nullptr);
> 
> Will management-suite module receive twinChangeNotifications as message or some other way?

Yes, you will receive twin update notifications as a message, and yes, that `IoTHubModuleClient_SetInputMessageCallback` call is correct, based on the route you defined above.

**Comment by rajaggrawal** [comment]
Hi @darobs ,
Thanks.

I have restarted my edge-device and started receiving twinChangeNotifications to custom module.

**I can receive reported property of a leaf device at custom module but is there a way to set desired property of a leaf device from custom module (management-suite)?**

**Comment by rajaggrawal** [comment]
I can see leaf device connection status in reported properties of edgeHub. 

           "clients": {
                "raj-test-edge/management-suite": {
                    "status": "Connected",
                    "lastConnectedTimeUtc": "2021-03-16T13:06:13.5529146Z",
                    "lastDisconnectedTimeUtc": "2021-03-16T13:06:13.4727461Z"
                },
                "**test-edge-leaf-device**": {
                    "status": "Connected",
                    "lastConnectedTimeUtc": "2021-03-16T13:36:13.5270586Z"
                }
            }


**Is there a way to get this in my custom module ?
OR please me the best way to get connection status of each leaf device which are connected through iotedge.**

**Comment by darobs** [comment]
> 
> 1. Is there a way to set desired property of a leaf device from custom module (management-suite)?

Typically a module does not have permission to modify a leaf-device's desired properties. You may be able to give a module credential to do this, but this seems a better fit for something like an Azure Function in the cloud (IMO).

> 2. How custom module will know that how many leaf device are connected with iotedge ?.
>  Is there a way to get/route this reported property to my custom module ?
> OR please let me know the best way to get connection status of each leaf device which are connected through iotedge.

EdgeHub reported properties are not sent through edgeHub's routing, so you will not see its reported properties in the /twinChangeNotifications source.

Edge Hub's scope information isn't open to other modules. Hypothetically, if Edge Hub exposed this information, it would be a privileged operation to show count, since it is device level information.  

There is some information in [edgeHub metrics](https://docs.microsoft.com/azure/iot-edge/how-to-access-built-in-metrics?view=iotedge-2018-06), but not specifically the information you are looking for,,

Other than that, the only other way to know would be to route messages from your leaf device to your management-suite module.

**Comment by rajaggrawal** [comment]
Other than that, the only other way to know would be to route messages from your leaf device to your management-suite module.

**Yes we also thought of this, we can send telemetry messages from leafDevice about connection status and these messages can be captured at custom module using iotedge routing. But this wont work when leaf Device disconnect with iotedge due to any kind of failure .**

**Comment by darobs** [comment]
After I consulted with other team members, this doesn't look like we have an in-runtime solution for this, and this is intentional. 

If there is a good use-case for this, please suggest this at our[ User Voice page](https://aka.ms/iotedge-suggestion).  Closing now, as your initial issue seems resolved.
