### ISSUE TITLE
Flaky test blocking checkin

### ISSUE THREAD

**Issue by dsajanice** [Azure/iotedge#46]
## Expected Behavior

AsyncEndpointExecutorTest.TestBatchTimeout Test should pass

## Current Behavior

AsyncEndpointExecutorTest.TestBatchTimeout is failing intermittently on Windows

## Steps to Reproduce

1. Kickoff a build against a PR
2.
3.
4.

**Comment by myagley** [comment]
Thanks Janice. I think @varunpuranik should have a fix shortly.

**Comment by varunpuranik** [comment]
This has been fixed - https://github.com/Azure/iotedge/pull/49
