### ISSUE TITLE
This is related to nested edge. Issue #1. Even after setting up a new registry and IoTEdgeAPIProxy module in parent device the custom developed modules in the private container registries are not getting pulled into child. Issue#2. The environment variable in registry module REGISTRY_PROXY_REMOTEURL is always referred by system modules even after setting up the Image-pull-policy to never.

### ISSUE THREAD

**Issue by manupradeep2000** [Azure/iotedge#4644]
## Expected Behavior
Tell us what should happen

## Current Behavior
Tell us what happens instead of the expected behavior

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.
2.
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vipeller** [comment]
@manupradeep2000 Hello, can you run the following command:

sudo iotedge support-bundle

it creates a file containing logs that would be useful for us to get closer to the problem

**Comment by vipeller** [comment]
@manupradeep2000 Hi, I am not sure if you still need assistance, if you do, please create the support bundle. To send us the bundle, please create a support ticket, so you can upload the bundle without showing its data on this public website. To create a ticket, please follow this screen:

![image](https://user-images.githubusercontent.com/51135538/112879721-633aa980-907e-11eb-9ae2-dab8657081c4.png)
