### ISSUE TITLE
Change in container ENV variable via manifest doesn't reliably get applied

### ISSUE THREAD

**Issue by nanowireUK** [Azure/iotedge#4645]
## Expected Behavior
If I change environment variables for a module in the manifest, then these get reliably applied to the container on the Edge. This often does not happen, particularly if there is no change to the image.

## Current Behavior
The container is not recreated which keeps the old environment variables. This can be confirmed with `docker inspect`. This is definitely happening with the edgeHub but also likely other modules.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a manifest where the edgeHub has `experimentalFeatures__nestedEdgeEnabled` set to true
2. Deploy the manifest and let the container get created on the edge device
3. Deploy a modified manifest where `experimentalFeatures__nestedEdgeEnabled` is set to false
4. What for this to be applied to the edge
5. Do a `docker inspect` of the edgeHub container to list the applied environment variables. This will still have `experimentalFeatures__nestedEdgeEnabled` set to true.

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Debian 9
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux, moby
Behaviour has been confirmed on other environments as well

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2rc3
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.0-rc3
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.0-rc3
* Docker/Moby [run `docker version`]: 3.0.13+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Additional Information
The fix is to simply remove the container and let it be recreated.
* `systemctl stop iotedge`
* `docker ps -a` to get container id for affected container
* `docker rm <container id>`
* systemctl start iotedge

**Comment by vipeller** [comment]
@nanowireUK which way do you deploy the manifest? (e.g. from command line with an 'az' command, or visual studio code, etc?

**Comment by ebertrams** [comment]
@nanowireUK, any update on this issue?

**Comment by nanowireUK** [comment]
Apologies - I didn't get a notification. I'm applying manifests with layered automatic deployments but I'm pretty certain I've seen this with single deployments as well.

**Comment by veyalla** [comment]
Please try this with 1.2 which now GA. If you're trying layered deployments the topmost layer should be highest priority deployment that is targeting the device.
