### ISSUE TITLE
edgeAgent: logLevel property in durect method UploadModuleLogs does not filter logs accordingly

### ISSUE THREAD

**Issue by marvin-garcia** [Azure/iotedge#4648]
## Expected Behavior
Invoking UploadModuleLogs Direct method on edgeAgent specifying a log level in the request payload should return log lines less than or equal to specified log level.

## Current Behavior
Invoking UploadModuleLogs Direct method on edgeAgent specifying a log level in the request payload only returns logs with that specific log level. If I don't provide a log level in the payload, the method uploads all logs.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Deploy Linux Azure IoT edge device to IoT hub
2. Invoke method UploadModuleLogs on module edgeAgent. Request payload:
```
{
    "deviceId": "", 
    "moduleId": "$edgeAgent", 
    "methodName": "UploadModuleLogs", 
    "methodPayload": {
       "schemaVersion": "1.0",
       "sasUrl": "sasUrl",
       "items": [
          {
             "id": "edgeHub",
             "filter": {
                "since": "30m",
                "logLevel": 7
             }
          }
       ],
       "encoding": "none",
       "contentType": "json" 
    }
}
```
4. Download blob from storage account related to the SAS token provided 
5. See only DBG (level 7) logs in file

## Context (Environment)
Azure IoT edge runtime for Linux

### Output of `iotedge check`
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.10 but 1.1.1 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 62 days (at 2021-05-24 14:48:20 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

### Device Information
* Host OS: Ubuntu 16.04.5 LTS
* Architecture:amd64
* Container OS: Linux

### Runtime Versions
* aziot-edged: 1.0.10
* Edge Agent: 1.0
* Edge Hub: 1.0
* Docker: 19.03.13+azure

**Comment by veyalla** [comment]
Thanks for the issue @marvin-garcia. This is working as designed, a workaround to achieve the behavior you're seeking would be to filter for 'Error' + 'Warning' + 'Info' etc using the regex filter.

If you'd like to see this functionality added, please put in a [feature request](https://aka.ms/iotedge-suggestion) or upvote on existing one.

**Comment by marvin-garcia** [comment]
Ah! That makes sense. Then I suggest you update the documentation to match the intended behavior, https://docs.microsoft.com/en-us/azure/iot-edge/how-to-retrieve-iot-edge-logs?view=iotedge-2018-06#upload-module-logs.

Thanks.
