### ISSUE TITLE
Edge Agent is not able to list out the modules and sending 500 error in reported property back to IoT Hub

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#4658]
## Expected Behavior
edgeAgent Module should not throw 500 error and should not reported it everytime when it is listing out the modules 

## Current Behavior
edgeAgent is trying to list out the modules and then throwing 500 error and reporting it back to IoT Hub 

## Steps to Reproduce
1.Deploy more than 15 modules
2. and then check the logs of edgeAgent logs and the status on IoT Hub
3. On IoT Hub it is showing 500 failure message in the reported property

## Context (Environment)
1. Windows 10
### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Windows 10
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]:  Windows

### Runtime Versions
* aziot-edged [run `iotedge version`]:  1.0.10.1
* Edge Agent [image tag (e.g. 1.0.0)]:  1.0.10.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.10.1
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

Exception in edgeAgent:

System.TimeoutException: Operation timed out
at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in C:\agent_work\9\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 128
at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\versioning\ModuleManagementHttpClientVersioned.cs:line 146
at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\versioning\ModuleManagementHttpClientVersioned.cs:line 146
at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.GetModules[T](CancellationToken cancellationToken) in C:\agent_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\version_2020_07_07\ModuleManagementHttpClient.cs:line 171
at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironment.GetModulesAsync(CancellationToken token) in C:\agent_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Docker\DockerEnvironment.cs:line 51
at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.GetCurrentModuleSetAsync(CancellationToken token) in C:\agent_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 251
at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in C:\agent_work\9\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 203



```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vipeller** [comment]
@sachidanand Hello, sorry for the late reply. I am trying to repro this. A quick questions:
- if you have happen to tried with fewer modules, did it work? (does it consistently breaks at 15?)
- are the module names normal names (e.g. "security" or "message_processing"), or do they have any special chars in it? are they long? (I am trying to gather info what is the best way to repro)

the system is supposed to support more that 15 modules

**Comment by sachidanand** [comment]
> @sachidanand Hello, sorry for the late reply. I am trying to repro this. A quick questions:
> 
> * if you have happen to tried with fewer modules, did it work? (does it consistently breaks at 15?)
> * are the module names normal names (e.g. "security" or "message_processing"), or do they have any special chars in it? are they long? (I am trying to gather info what is the best way to repro)
> 
> the system is supposed to support more that 15 modules
Hi @vipeller ,
It is working with less number of modules .. And usually we have seen this issue where we have more modules .. Modules name are as simple string and these are around 20-30 characters without any specially characters.

**Comment by sachidanand** [comment]
Hi Team is there any update ...

**Comment by vipeller** [comment]
@sachidanand I am sorry, but I have not gotten there yet, will be working on this issue soon

**Comment by vipeller** [comment]
@sachidanand I tested it with 20 modules (+ the 2 system modules) but I could not repro the error (it deploys the modules and starts them up)

Few things I would need:
- if you run 'sudo iotedge list', do you see some error or some list of modules (I suppose you would not see the full expected list)
- there is a command like 'sudo iotedge support-bundle --since 1h'. This creates a zip file woth a logs folder, and this will have a docker_err.txt and an iotedged.txt. Can you copy the content of those files to me?

And a question: what way did you deploy the modules (added through portal.azure.com, used a deployment file with an az command or visual studio code, etc?)

**Comment by sachidanand** [comment]
We are using windows 10 on the gateway
1. I run the iotedge list command and I am able to list out the modules 
2. We deploy the modules using REST APIs
3. Support Bundle logs are below 

**docker.txt**
Index              : 13344918
EntryType          : Error
InstanceId         : 1
Message            : The description for Event ID '1' in Source 'docker' cannot be found.  The local computer may not have the necessary 
                     registry information or message DLL files to display the message, or you may not have permission to access them.  The 
                     following information is part of the event:'Failed to log msg "" for logger json-file: rename C:\ProgramData\iotedge-moby
                     \containers\2f90d1e2b52b9d3725e8913aefc6f6e9777ef7fe33c57c8c933eb1fe7a0a9756\2f90d1e2b52b9d3725e8913aefc6f6e9777ef7fe33c5
                     7c8c933eb1fe7a0a9756-json.log C:\ProgramData\iotedge-moby\containers\2f90d1e2b52b9d3725e8913aefc6f6e9777ef7fe33c57c8c933e
                     b1fe7a0a9756\2f90d1e2b52b9d3725e8913aefc6f6e9777ef7fe33c57c8c933eb1fe7a0a9756-json.log.1: The process cannot access the 
                     file because it is being used by another process.'
Category           : (0)
CategoryNumber     : 0
ReplacementStrings : {Failed to log msg "" for logger json-file: rename C:\ProgramData\iotedge-moby\containers\2f90d1e2b52b9d3725e8913aefc6f6e
                     9777ef7fe33c57c8c933eb1fe7a0a9756\2f90d1e2b52b9d3725e8913aefc6f6e9777ef7fe33c57c8c933eb1fe7a0a9756-json.log C:\ProgramDat
                     a\iotedge-moby\containers\2f90d1e2b52b9d3725e8913aefc6f6e9777ef7fe33c57c8c933eb1fe7a0a9756\2f90d1e2b52b9d3725e8913aefc6f6
                     e9777ef7fe33c57c8c933eb1fe7a0a9756-json.log.1: The process cannot access the file because it is being used by another 
                     process.}

**iotedged.txt**
TimeCreated : 09.03.2021 11:21:39
Message     : info: edgelet_http::logging -- [mgmt] - - - [2021-03-09 10:21:39.076100400 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 
              200 OK 343290 "-" "-" auth_id(-)

TimeCreated : 09.03.2021 11:21:39
Message     : info: edgelet_core::watchdog -- Checking edge runtime status

TimeCreated : 09.03.2021 11:21:39
Message     : info: edgelet_core::watchdog -- Edge runtime is running.

TimeCreated : 09.03.2021 11:21:44
Message     : info: edgelet_http::logging -- [mgmt] - - - [2021-03-09 10:21:44.308528500 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 
              200 OK 343290 "-" "-" auth_id(-)

TimeCreated : 09.03.2021 11:21:49
Message     : info: edgelet_http::logging -- [mgmt] - - - [2021-03-09 10:21:49.548193300 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 
              200 OK 343290 "-" "-" auth_id(-)

TimeCreated : 09.03.2021 11:21:54
Message     : info: edgelet_http::logging -- [mgmt] - - - [2021-03-09 10:21:54.791419 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 200 
              OK 343290 "-" "-" auth_id(-)

TimeCreated : 09.03.2021 11:22:00
Message     : info: edgelet_http::logging -- [mgmt] - - - [2021-03-09 10:22:00.008306900 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 
              200 OK 343290 "-" "-" auth_id(-)

TimeCreated : 09.03.2021 11:22:05
Message     : info: edgelet_http::logging -- [mgmt] - - - [2021-03-09 10:22:05.239641100 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 
              200 OK 343290 "-" "-" auth_id(-)

TimeCreated : 09.03.2021 11:22:10
Message     : info: edgelet_http::logging -- [mgmt] - - - [2021-03-09 10:22:10.458314900 UTC] "GET /modules?api-version=2020-07-07 HTTP/1.1" 
              200 OK 343290 "-" "-" auth_id(-)

**Comment by sachidanand** [comment]
Hi did you check these logs ???

**Comment by vipeller** [comment]
Hi @sachidanand 

Sorry for the late answer. Unfortunately, those logs don't say much - we will need the entire support bundle and also figure out why the docker logs are not available.

You cannot put the support bundle here, so I would ask you to open a support ticket, also give the github issue number (or link) in the ticket (4658). You can create a ticket through the portal:

![image](https://user-images.githubusercontent.com/51135538/113335936-819ce100-92da-11eb-8c33-039ca74862da.png)

**Comment by veyalla** [comment]
Closing, as this is being tracked by Azure support ticket.
