### ISSUE TITLE
Help require- Code Coverage Testing and Unit Testing of custom module

### ISSUE THREAD

**Issue by SandeepThombare** [Azure/iotedge#4701]
We have developed custom IoT edge module using python. 

1. We want to do code coverage and unit testing in the DevOps pipeline for our custom modules. Could you please let me know how I can do that.
2. How are the IoT edge modules can be tested in the DevOps pipeline. Wanted to understand if there are any predefined process in place for testing of custom modules in CI/CD pipeline.
3. Since the custom modules uses IoT Edge SDK API's, how the modules can be tested end to end.

Any documentation or process flow is available please share

**Comment by marianan** [comment]
@SandeepThombare thank you for your questions. Here are a couple of pointers to get you started, please let us know if you run into issues or have any questions.
1. CICD to Azure IoT Edge devices - https://docs.microsoft.com/en-us/azure/iot-edge/how-to-continuous-integration-continuous-deployment-classic?view=iotedge-2018-06
2. IoTEdgeDev is a CLI tool that supports executing any testing from within a DevOps environment - https://github.com/Azure/iotedgedev
