### ISSUE TITLE
Using Azure IoT for device management while running edge run time

### ISSUE THREAD

**Issue by clustor** [Azure/iotedge#4753]
We currently have a (i) cloud based interface for managing various aspects of the edge device built on top of open source technologies and (ii) edge run time for integrating with customer's Azure IoT Hub.  We are considering moving the device management to Azure IoT as well. 

One of the thoughts we have is to bootstrap our edge device with our DPS instance and our IoT Hub for device management presenting ourselves as a leaf device and then have Azure IoT Edge runtime use customer's DPS instance for installing edge modules and building IoT applications. 

Are there any other patterns for accomplishing this?

**Comment by veyalla** [comment]
Hi @clustor, I don't think I'm following your question. A high level architecture diagram of your proposal would help...
