### ISSUE TITLE
Edge 1.2 RC4:  SAN does not contain the Subject name common name thus client SSL validation fails

### ISSUE THREAD

**Issue by spatdsg** [Azure/iotedge#4757]
## Expected Behavior
The client SSL stack should receive the Server Hello certificate and validate the chain as well as the destination and subject names in the SSL cert.  If the SSL cert contain a SAN (subject alternative name) with DNS name it should be the same as the common name in the subject.

In previous versions of IoT Edge (v1.1) the SSL cert was issued from the workload CA and has the following in the SAN:

•	DNS Name=ubuntu.edgeserver.spat.com ----- this is correct, it matches the subject name of the cert
•	DNS Name=edgehub

## Current Behavior
Currently the SSL cert has the incorrect DNS name in the subject alternative name

•	DNS Name=edgehub  --> module name instead of subject common name of cert
•	IP Address=192.168.12.235   

comment here seems to indicate this is understood but not implemented?
https://github.com/Azure/iotedge/blob/a526d630636b787427e4ab38aa12ce827e10d1d/edgelet/edgelet-http-workload/src/server/cert/server.rs

                // add a DNS SAN entry in the server cert that uses the module identifier as
                // an alternative DNS name; we also need to add the common_name that we are using
                // as a DNS name since the presence of a DNS name SAN will take precedence over
                // the common name

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install edge 1.2 RC4
2. Create cert chain and device CA via scripts here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2018-06
•   ./certGen.sh create_root_and_intermediate
•   ./certGen.sh create_edge_device_ca_certificate "SpatDeviceCA"

3.  Configure config.toml 
hostname
trust_bundle_cert 
provisioning =  manual and connection string
[agent.config] 
image = "mcr.microsoft.com/azureiotedge-agent:1.2.0-rc4"
[edge_ca]
cert = chain to device CA
pk = private key to device CA

 
 
## Context (Environment)
Linux client and server 

Client - tried openSSL and wolfSSL
wolfSSL output below

```

 
 wolfSSL Entering GetObjectId()
DecodeExtKeyUsage
wolfSSL Entering GetObjectId()
wolfSSL Entering GetObjectId()
wolfSSL Entering DecodeAltNames
        Unsupported name type, skipping
wolfSSL Entering GetAlgoId
wolfSSL Entering GetObjectId()
CA found
wolfSSL Entering ConfirmSignature
wolfSSL Leaving ConfirmSignature, return 0
Verified Peer's cert
**Checking AltNames
        individual AltName check
DomainName match on alt names failed**
wolfSSL Entering SendAlert
growing output buffer



```

### Output of `iotedge check`

<details>
<summary>Click here</summary>

</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by vadim-kovalyov** [comment]
Hey @spatdsg, it seems like you have 192.168.12.235 as a hostname in config.toml. Can you change that to actual hostname? If you have a hostname there, edgelet should put that in CN and SAN.

**Comment by vadim-kovalyov** [comment]
Closing this for now. Please reopen if you have further questions.
