### ISSUE TITLE
dynamic_reprovisioning and reprovisioning events for IoT Edge X509 attestation

### ISSUE THREAD

**Issue by jakereifer** [Azure/iotedge#4777]
The [edge documentation for provisioning](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs?view=iotedge-2018-06#linux-device) discusses "If a device is set to dynamically reprovision itself, IoT Edge will restart and reprovision if a reprovisioning event is detected". What are these reprovisioning events? How does one trigger one? I was unable to find any explanation even in the linked documentation "for more information"

Also created [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/73205).

**Comment by davilu** [comment]
Assigned to @veyalla to gather the requirement.

**Comment by veyalla** [comment]
There is a bit more detail in the inline comments in [config.yaml](https://github.com/Azure/iotedge/blob/a46838f7004680f283b6f41831d47560aa937d5d/edgelet/contrib/config/linux/config.yaml#L103). We'll update the main docs with a bit more detail around this. 

There is currently no API to trigger this independently. Though, you can disable the device in the hub to create conditions which will trigger it.
