### ISSUE TITLE
How to connect Android app as IoT Edge device in IoT Hub? 

### ISSUE THREAD

**Issue by sankarmca77** [Azure/iotedge#479]

**Comment by myagley** [comment]
Hello. IoT Edge on Android isn't currently a supported platform. However, we are looking at adding it in the future. The main gap here is IoT Edge's use of Docker containers, which aren't supported on Android. 

You can learn more about the supported platforms here: https://docs.microsoft.com/en-us/azure/iot-edge/support

**Comment by sankarmca77** [comment]
Okay. 👍 

I have designed my Android app as a **data transmitter hub** and it receives data from multiple sensors through Zigbee wireless. I have to pass these sensors telemetry data to my Azure IoT Hub .

Should i use only Azure IoT SDK for Android ? 

Please suggest ,

**Comment by myagley** [comment]
Yes, we have just recently announced support for Android in the IoT Hub Java SDK: https://github.com/Azure/azure-iot-sdk-java

This will be a better fit until we add Android support in IoT Edge directly.

@timtay-microsoft may be help with the details on using the Java SDK on Android. Thanks!

**Comment by timtay-microsoft** [comment]
@jasmineymlo for Android related questions on the Java SDK

**Comment by tanieee28** [comment]
Hi @jasmineymlo 
i am running iot edge v1 java binding and i have also written some iotedge modules to work around.
Now, as we know gateway starts with taking gw-config.json and starts modules and manages communication between modules. This whole process is being done in windows.


Now, What i am trying to achieve is the similar arch that i explained above in android. So the question arises is **can i run iotedge as gateway in android and write modules and manages modules in android.**
Plz Help

Thanks in Advance.

**Comment by myagley** [comment]
Unfortunately, IoT Edge is not officially supported on Android. It requires Docker container support on the platform, which Android does not support out of the box. You can learn more about the supported platforms here: https://docs.microsoft.com/en-us/azure/iot-edge/support

We have heard some interest in getting IoT Edge supported on Android, but we don't currently have a timeline for this.

**Comment by tanieee28** [comment]
Thanks for the Update @myagley 
But, i haven't used the containerization technology as i am using the first version of iotedge, where  i have built iotedge-v1 opensource code and executed it to build my custom gateway in which the whole runtime is under a single process called gw.exe and all modules are running as thread and are part of the main process(gw.exe).  

I want to have a kind of similar approach or can i run the same runtime in android ?

My Aim is to run the opensource iotedge-v1 on android as gateway and create modules and execute them under the same process. I might repeating the same thing but just to clarify.

Plz Help

Thanks in Advance

**Comment by lt72** [comment]
@tanieee28 Hello, sorry for the very late answer. Do you still need help with this?

**Comment by tanieee28** [comment]
@lt72 thanks but I think now I am on some other side of iot edge now. No help for now.
Will put it here if something comes up in future.

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.

**Comment by connectganeshs** [comment]
Hi, Is there any development going on for edge support in Android ?
Please Help if any other options for same.

Thanks

**Comment by Hobb** [comment]
Hi, I hace a scenario in which it is required to have a transparent gateway on an android device (a mobile phone) or even on an Apple device.
Have you made any progress into this matter?

**Comment by connectganeshs** [comment]
Hello!! No not yet, I haven't found any breakthrough in this yet.

**Comment by sourabhkrishna** [comment]
Hi, Is there any development going on for edge support in Android and iOS ?
