### ISSUE TITLE
Azure portal cannot display modules information if iotHub module uses schema v1.2

### ISSUE THREAD

**Issue by kvasdopil** [Azure/iotedge#4792]
Testing MQTT broker feature, available in the latest preview version. The feature requires iotHub module to use desired properties schema version 1.2, as described here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11

However, when this version is specified, the azure portal displays an error message instead of module status when device page is opened:

<img width="767" alt="Screenshot 2021-04-06 at 09 39 48" src="https://user-images.githubusercontent.com/807629/113675842-0eb9ae80-96bc-11eb-8ee2-a26de25ec6e3.png">

## Expected Behavior
List of modules is displayed

## Current Behavior
Error message is displayed

## Steps to Reproduce
1. Change schema version for edgeHub module in device twin:
```
{
   "$edgeHub":{
      "properties.desired":{
         "schemaVersion":"1.2"
      }
   }
}
```
2. Open device page in azure portal

**Comment by vadim-kovalyov** [comment]
Hey @kvasdopil, thanks for trying MQTT Broker. This is still an experimental feature, and what you see is a known limitation, and our portal team is working on it as we speak. Please follow our release updates for the latest news.

**Comment by TheRealSvc** [comment]
Hello @vadim-kovalyov , so do i get it right that in order to follow the docu  (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11#pre-requisites) it would be necessary to build your docker images for the edgeHub? If yes, what would be the proper branch ? /releases/1.2 ?  Thanks !

**Comment by vadim-kovalyov** [comment]
@TheRealSvc, to be precise, the edgehub settings schema version and edgehub container image version are independent. It is just happened that they are the same for 1.2 :) but we may update any of the version numbers independently.

For example, edge agent is still using 1.0 schema version, b/c there were no major changes in the 1.2 release related to edge agent settings.

**Comment by vadim-kovalyov** [comment]
@TheRealSvc, I believe you don't have to look up `schemaVersion` specifically, unless you want to use some new features that require specific `schemaVersion` and container image version. As I mentioned above, schemaVersion and container image versions are independent, and all schema versions are back-compatible by minor version, so any new version of the container will support all previous `schemaVersions`s. (e.g. edgehub 1.2 does support schema versions 1.0, 1.1, 1.2). 

You can update container images without worrying about schema version. But if you're looking for a specific feature (like MQTT Broker), then you would find the required minimum container image and schema version in the docs.

//cc @ebertrams if he has anything to add to this.

**Comment by vadim-kovalyov** [comment]
> Another confusion comes from the version of the iotedge runtime, which is also 1.2.0. Are there any compatibility considerations between iotedge runtime and edgeHub/edgeAgent images ?

We try our best to specify backward compatibility requirements in the release notes of every release. As far as I know, edgeHub/edgeAgent images 1.1+ are back-compatible with 1.2 runtime version. 
https://github.com/Azure/azure-iotedge/releases/tag/1.2.0

**Comment by ianchanning** [comment]
The original article can't be seen any more so here's an archived link: https://web.archive.org/web/20201113010638/https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11

**Comment by ianchanning** [comment]
Also note this Microsoft Q&A question is relevant: https://learn.microsoft.com/en-us/answers/questions/753353/publish-and-subscribe-with-azure-iot-edge-schema-v
