### ISSUE TITLE
Troubleshooting steps should document use of IOTEDGE_LOG=debug (or expand on edgelet=debug) (ported from MicrosoftDocs/azure-docs#71563)

### ISSUE THREAD

**Issue by stewartadam** [Azure/iotedge#4796]
Continuing discussion from [here](https://github.com/MicrosoftDocs/azure-docs/issues/71563):

Trying to provision a device with DPS was returning this cryptic error message, which none of the troubleshooting instructions helped with:

```
<4>2021-03-03T19:48:53Z [WARN] - Could not provision device
<4>2021-03-03T19:48:53Z [WARN] - 	caused by: DPS registration failed because the DPS operation is not assigned
<3>2021-03-03T19:48:53Z [ERR!] - The daemon could not start up successfully: Could not initialize DPS provisioning client
<3>2021-03-03T19:48:53Z [ERR!] - 	caused by: Could not restore previous provisioning result
<3>2021-03-03T19:48:53Z [ERR!] - 	caused by: No such file or directory (os error 2)
```

Only after searching the Rust source code and finding a reference to `IOTEDGE_LOG` and setting it to `debug` (instead of `edgelet=debug`) did it finally reveal the true error:

```
<7>2021-03-03T19:46:24Z [DBUG] - [dps::registration] Device Registration Result: device None, hub None, status Some("failed")
<7>2021-03-03T19:46:24Z [DBUG] - [dps::registration] <...> error_message: Some("Custom allocation failed with status code: 404") <...>
```

These log messages are **not** produced when configured as `edgelet=debug`, so this setting as recommended in the docs is not sufficient to troubleshoot edge security daemon issues.

## Expected Behavior
edgelet=debug should produce sufficient debugging information to troubleshoot DPS provisioning failures (or, that setting should be updated to include in its scope all debug services that *do* produce info relevant to troubleshooting DPS provisioning failures)

## Current Behavior
No helpful logs were output

## Steps to Reproduce
1. Setup DPS with an allocation function that returns 404 or 500
2. Try to provision
3. Set IOTEDGE_LOG='edgelet=debug'
4. Try to provision again

### Device Information
* Host OS: Ubuntu 20.04 
* Architecture: amd64
* Container OS: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.1.1
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1 (ee84873b2bc4)
* Edge Hub [image tag (e.g. 1.0.0)]: no 'azureiotedge-hub' image present in `docker image ls`
* Docker/Moby [run `docker version`]: 20.10.5+azure

**Comment by vadim-kovalyov** [comment]
Hey @stewartadam, thanks for reporting this! Indeed, it looks like documentation issue. We don't have `edgelet` crate, but have bunch of other crates like `edgelet_core`, etc... So in your case `IOTEDGE_LOG=debug` or `IOTEDGE_LOG=dps=debug` should help. We'll update the documentation, I believe it should say ``IOTEDGE_LOG=debug` for most common case. https://github.com/MicrosoftDocs/azure-docs/pull/73338

**Comment by stewartadam** [comment]
@vadim-kovalyov thx! fwiw a plain `debug` value produces *a lot* of output from tokio::reactor that would be nice to keep disabled, if that's possible.
