### ISSUE TITLE
iotedge 1.2 complains about missing registration_id when using DPS

### ISSUE THREAD

**Issue by randomstring384540** [Azure/iotedge#4829]
## Expected Behavior
Configuration provisioning via DPS does not require rgistration_id

```
## DPS provisioning with X.509 certificate
[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "0ne001D45B4"

[provisioning.attestation]
method = "x509"
identity_cert = "file:///var/aziot-id/edge-01.cert.pem"
identity_pk = "file:///var/aziot-id/edge-01.key.pem"
registration_id = "edge-01" 
```
## Current Behavior
Not providing registration_id leads to error
```
dev@ubuntu:/var/aziot-id$ sudo iotedge config apply
Command failed: could not parse config file: missing field `registration_id` at line 258 column 1
```

## Steps to Reproduce
Follow DPS setup guide at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs?view=iotedge-2020-11
```
# registration_id = "<OPTIONAL REGISTRATION ID. LEAVE COMMENTED OUT TO REGISTER WITH CN OF identity_cert>"
```

## Context (Environment)
dev@ubuntu:/var/aziot-id$ iotedge --version
iotedge 1.2.0

### Output of `iotedge check`
does not apply

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
```
dev@ubuntu:/var/aziot-id$ uname -a
Linux ubuntu 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

dev@ubuntu:/var/aziot-id$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
* Architecture [e.g. amd64, arm32, arm64]: VMWare/amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]:  1.2.0
* Edge Hub [image tag (e.g. 1.0.0)]: n.a.
* Docker/Moby [run `docker version`]: 19.03.6

## Logs
n.a.

## Additional Information
n.a.

**Comment by arsing** [comment]
>Follow DPS setup guide at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-x509-certs?view=iotedge-2020-11

>```
># registration_id = "<OPTIONAL REGISTRATION ID. LEAVE COMMENTED OUT TO REGISTER WITH CN OF identity_cert>"
>```

The error is correct and the doc is wrong. Registration ID is required for DPS X-509 starting from 1.2.

**Comment by veyalla** [comment]
FYI @kgremban

**Comment by kgremban** [comment]
Thanks @arsing, @veyalla. Does the registration ID have to match the subject name on the certificate, or can it be another value?

**Comment by arsing** [comment]
@daprilik @massand Currently the CN must still match the registration ID, right?

**Comment by massand** [comment]
Yes, for the API version IoT Edge is using. @nberdy please confirm the match is still a requirement in the latest DPS API version since [the docs still suggest it is true for all API versions](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-csharp#create-an-individual-enrollment-entry-for-the-device)?

**Comment by veyalla** [comment]
@kgremban do you need any more info here for docs change?

**Comment by kgremban** [comment]
@veyalla No, I just forgot to complete the pull request. Doing that now, and changes will go live at 3pm today.

**Comment by veyalla** [comment]
Thanks @kgremban! Closing this issue.

**Comment by kpm-at-hfi** [comment]
Hey all... just a heads up that this isn't (wasn't) really just a documentation error. This change to now require `registration_id` makes upgrading early fielded devices quite a bit trickier.
