### ISSUE TITLE
Building iotedge v1.1.2 for Ubuntu 18.04 results in DEBs with 1.1.1 version

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#4865]
I am following the instructions from https://github.com/Azure/iotedge/blob/master/edgelet/doc/devguide.md

When I run

```bash
git clone --recurse-submodules --depth 1 --branch 1.1.2 https://github.com/Azure/iotedge /tmp/iotedge
cd /tmp/iotedge
PACKAGE_OS=ubuntu18.04 PACKAGE_ARCH=amd64 ./edgelet/build/linux/package.sh
```

The last two lines of the output are 
```
/tmp/iotedge/edgelet/target/hsm/libiothsm-std_1.1.1-1_amd64.deb
/tmp/iotedge/edgelet/target/release/iotedge_1.1.1-1_amd64.deb
```

As you can see, the DEBs have version **1.1.1** but the checkout was for **1.1.2**. This is confirmed by running `git log` in the directory which shows
```
commit 5419edd44f82c229e3bb083cb52b76ce76b383b6 (grafted, HEAD, tag: 1.1.2)
Author: yophilav <54859653+yophilav@users.noreply.github.com>
Date:   Mon Apr 12 15:00:53 2021 -0700

    Prepare for Release 1.1.2
    
    Prepare for Release 1.1.2
```

This is further confirmed by installing the so-called 1.1.2 DEB and looking at journalctl log for iotedge which says `Version - 1.1.1`

**Comment by lfitchett** [comment]
@yophilav Hey bear, mind taking a look?

**Comment by yophilav** [comment]
Hi @gri6507, 

Thank you for the question! 
Per [release page](https://github.com/Azure/azure-iotedge/releases/tag/1.1.2), the release 1.1.2 does NOT impact the iotedge security daemon. The release solely updates the docker system modules to fix security vulnerability in the .Net Core. You should be able to use the `1.1.1` iotedge & libiothsm with docker images for release 1.1.2. 

You can check the latest status of each component here: 
https://github.com/Azure/azure-iotedge/blob/master/latest-iotedge-lts.json

Cheers,
Bear

**Comment by gri6507** [comment]
Thank you @yophilav. I did not realize that a single release version was used for different components within the Git repo. Since this results in confusion, does the single version make sense moving forward?

**Comment by yophilav** [comment]
That's a great question! We have asked ourselves that very question not too long ago as well. 
As a result from the discussion, we are actually separating our versioning into 2 components for release 1.2 onwards (edgelet vs IdentityService components). The release 1.1 was a LTS inherited from release 1.0.10. We cannot simply change the versioning scheme. To facilitate that, we decided to make it clear in the release process to not upload a particular edgelet artifacts without a change along with `awareness` section that artifacts are intentionally left out.

**Comment by gri6507** [comment]
thank you for the clarification.
