### ISSUE TITLE
Add ability to call direct methods without the payload limit of 128 KB

### ISSUE THREAD

**Issue by luiscantero** [Azure/iotedge#4878]
Currently, direct methods [limit the payload size](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits) of requests and responses to 128 KB. For many applications, this is not enough.

The data that is typically passed is in JSON format. Using GZIP compression, more than 128 KB can be effectively passed back and forth. For even larger requests and responses, there are workarounds such as chunking the request/response and then concatenating it back.

It would be great to have the ability to send large requests and responses directly in the iotedge platform. The API could internally use chunking and compression (with options for string and binary data).

**Comment by richma-ms** [comment]
@luiscantero both cloud-2-device request and the protocol is dictated by IoT Hub service, and Edge has no control over it.  We're just a middle layer that's passes through the payload, the same limitation exists if you tried to sent a DirectMethod to device that's directly connected to its IoT Hub endpoint.

That said, I believe IoT Hub is able to lift certain operational limits on a case-by-case basis.  Please open a support ticket and explain your case, and see if they will allow you to send payloads over the 128KB limit.
