### ISSUE TITLE
Receiving messages from IoT hub to Edge module

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#488]
I am working on Two way communication Edge Module --> IoT Hub and IoT hub --> Edge Module.  I am able to do so using Azure IoT Java SDK.  Below is the code snippet-
	private static class EventCallback implements IotHubEventCallback {
		public void execute(IotHubStatusCode status, Object context) {
			System.out.println("IoT Hub responded to message with status: " + status.name());

			if (context != null) {
				synchronized (context) {
					context.notify();
				}
			}
		}
	}

Is there any way to do so in Azure IoT Edge Module to receive data from IoT Hub to Edge Module?

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
Run `iotedge version` -1.0.3

Thanks

**Comment by myagley** [comment]
Hi Prateek. We unfortunately do not support cloud to device messages for modules on IoT Edge (IoT Hub -> Edge).

However, we do support direct methods for modules. These are similar to cloud to device messages but they are synchronous (request/response pattern). You can learn more about them here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods

Do you think direct methods will work for your scenario?

**Comment by pratson20** [comment]
@myagley Can we send 100 kb json packet from cloud to edge device using direct method? What is the best way to implement on azure edge modules?

**Comment by manueljesusrd** [comment]
Hi @myagley 
You said that direct method for modules is possible. I've checked out the link you provided but there's only a reference to the C# SDK. Since @pratson20 was using Java SDK (and so am I), is there any possibility to call a method of any Java module from IoT Hub?
