### ISSUE TITLE
1.2.0 - TLS Certificate Authentication Error

### ISSUE THREAD

**Issue by jaypaddy** [Azure/iotedge#4895]
## Current Behavior
I have updated IoTEdge from 1.1  to IoTedge 1.2.0 roughly about 30-40 days (can't remember specifically). I started using the Edge and everything was fine I have had no issues.

This morning i did a deployment of the modules (the same modules that worked until yesterday) , i started getting thee following errors...

```
IoT Hub Client for Python
Unexpected error ClientError('Error in the IoTHub client due to TLS exchanges.') caused by TlsExchangeAuthError(None) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 395, in connect
    host=self._hostname, port=8883, keepalive=self._keep_alive
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 33, in handle_result
    return await callback.completion()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/async_adapter.py", line 94, in completion
    return await self.future
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 193, in _run_op
    self.transport.connect(password=password)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 407, in connect
    raise exceptions.TlsExchangeAuthError(cause=e)
azure.iot.device.common.transport_exceptions.TlsExchangeAuthError: TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)')
```

I use CONNECTION_STRING to connect Edge to IoTHub and do not use X.509. All modules are failing to run including "SimulatedTemperatureSensor"

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
Not really sure how to reproduce..... I will keep my edge in this state for sometime to help investigate the problem

## Context (Environment)
Ubuntu 18.04
IoTEdge 1.2.0
mcr.microsoft.com/azureiotedge-agent:1.2.0
mcr.microsoft.com/azureiotedge-hub:1.2.0-rc4

### Output of `iotedge check`

```

Configuration checks (aziot)
----------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ identityd config toml file specifies a valid hostname - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK

Connectivity checks (aziot)
---------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ EdgeAgent module can be pulled from upstream - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
26 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.

```

### Device Information
* Host OS : Ubuntu 18.04
* Architecture: amd64
* Container OS :  Linux containers,

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.0~rc4
* Edge Agent [image tag (e.g. 1.0.0)]: azureiotedge-agent:1.2.0
* Edge Hub [image tag (e.g. 1.0.0)]:  azureiotedge-hub:1.2.0-rc4
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

**Comment by richma-ms** [comment]
Based on the fact that all your modules are failing, I suspect it's the EdgeHub server cert expired, not the client cert.  The server cert is signed by the workload CA, which is in turn signed by the device CA.
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs?view=iotedge-2020-11#:~:text=Example%20of%20IoT%20Edge%20certificate%20hierarchy%20%20,%20iotedgegw.local%20%28matches%20the%20%27hostname%27%20%20...%20

if you supplied your own device CA during setup, can you verify that the CA is still valid?  Otherwise if you're letting Edge runtime generate dev certs, restarting the runtime should trigger the creation of a new self-signed CA.

**Comment by jaypaddy** [comment]
@richma-ms - I did not supply any CA. I always used Device Connection String. 

Here is my config.toml

`hostname = "mythicalnuc"

[provisioning]
always_reprovision_on_startup = true
source = "manual"
iothub_hostname = "xxxxxxxxxx.azure-devices.net"
device_id = "NUC"
connection_string = "HostName=xxxxxxxxxxx.azure-devices.net;DeviceId=NUC;SharedAccessKey=tttttttttysdmsssksk="

[provisioning.authentication]
method = "sas"

#[provisioning.authentication.device_id_pk]
#value = "tttttttttysdmsssksk="

[aziot_keys]

[preloaded_keys]

[cert_issuance]

[preloaded_certs]

[agent]
name = "edgeAgent"
type = "docker"
imagePullPolicy = "on-create"

[agent.config]
image = "mcr.microsoft.com/azureiotedge-agent:1.0"

[agent.config.createOptions]

[agent.config.auth]

[agent.env]

[connect]
workload_uri = "unix:///var/run/iotedge/workload.sock"
management_uri = "unix:///var/run/iotedge/mgmt.sock"

[listen]
workload_uri = "fd://aziot-edged.workload.socket"
management_uri = "fd://aziot-edged.mgmt.socket"
min_tls_version = "tls1.0"

[watchdog]
max_retries = "infinite"

[moby_runtime]
uri = "unix:///var/run/docker.sock"
network = "azure-iot-edge"`


`aypaddy@mythicalnuc:~$ sudo cat /etc/aziot/certd/config.d/00-super.toml
# This file is auto-generated by `iotedge config apply`
# Do not edit it manually; any edits will be lost when the command is run again.

homedir_path = "/var/lib/aziot/certd"
[cert_issuance.aziot-edged-ca]
method = "self_signed"
common_name = "iotedged workload ca"
expiry_days = 30

[preloaded_certs]
aziot-edged-trust-bundle = ["aziot-edged-ca"]

[[principal]]
uid = 111
certs = ["aziot-edged-ca", "aziot-edged/module/*"]`


How do i get iotedge to reissue this cert? It was my understanding is that it reissues the cert every 30 days.

**Comment by richma-ms** [comment]
Since you didn't specify an Edge device CA, the runtime generated a dev CA for you on startup.  Restarting the runtime will create a new dev CA.  Please try that and see if the modules can connect afterwards.

**Comment by jaypaddy** [comment]
I rebooted by ubuntu box and as well restarted iotedge
sudo systemctl restart iotedge

The modules continue to be in "Failed State"

**Comment by jaypaddy** [comment]
I reinstalled iotedge and will keep an eye if this comes back up.
