### ISSUE TITLE
"Validation failed. Required information is missing or not valid." error on the portal

### ISSUE THREAD

**Issue by acharaj** [Azure/iotedge#4897]
## Expected Behavior
We should be able to see the deployments in the "Review + Create" tab on the portal, and then, we should be able to deploy it.

## Current Behavior
We see an error "Validation failed. Required information is missing or not valid." when we click on the "Review + Create" tab on the portal.

## Steps to Reproduce
1. Apply a or several layered deployments to a device
2. Go to the "Set Modules" -->  "Review + Create" tab 
3. You will see the error "Validation failed. Required information is missing or not valid."

## Context (Environment)
IoT Edge layered deployments to a device

### Output of `iotedge check`
<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.1.0 but 1.1.1 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 50 days (at 2021-06-16 12:06:42 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Debian
* Architecture [e.g. amd64, arm32, arm64]: arm64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.0
* Edge Agent [image tag (e.g. 1.0.0)]:  1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* Docker/Moby [run `docker version`]: 20.10.1

**Comment by richma-ms** [comment]
@acharaj can you provide more information on this?  The error is shown if the portal couldn't generate a valid deployment manifest based on the information provided.  It should also have red dots next to the tabs that have invalid fields, and red text for those specific params.

Is the UX not showing these indicators for you?

**Comment by acharaj** [comment]
The issue happens when we deploy a layered deployment from Azure DevOps release pipelines. Once a layered deployment is deployed using the release pipelines, we see this error when we click on the "Review + Create" tab. There are no red dots next to the tabs that have invalid fields. UX is not showing those indicators. I attach the screenshot here.
<img width="1914" alt="portal_review_create_tab_validation_failed" src="https://user-images.githubusercontent.com/18576030/116220380-ebc76b00-a74c-11eb-80d5-7d41e2dc0edb.PNG">

**Comment by ebertrams** [comment]
@acharaj, can you please share your repro steps with your deployment json stripped out from confidential information?

**Comment by itsMeDacarvalho** [comment]
Hi everyone, I will let here the module deployment manifest template (`.json` file at the end ) that is part of the process that @acharaj is using to deploy the modules on the devices. 

In fact to check it in early stages and also to understand the fields available, I created a layered deployment from the portal and at the end I copied the manifest that is displayed as confirmation. From there I started to use it as template for every other module, but maybe we are missing something here 😃 

Thanks in advance!

<details>
<summary>Module deployment manifest template</summary>

```json
{
    "id": "${IMAGE_NAME}-deploy-${ENV}",
    "priority": "${DEPLOYMENT_PRIORITY}",
    "targetCondition": "${DEPLOYMENT_TARGETCONDITION}",
    "content": {
        "modulesContent": {
            "$edgeAgent": {
                "properties.desired.runtime.settings.registryCredentials.etib-acr": {
                    "address": "${ACR_ADDRESS}",
                    "password": "${ACR_PASSWORD}",
                    "username": "${ACR_USERNAME}"
                },
                "properties.desired.modules.${MODULE_NAME}": {
                    "settings": {
                        "image": "etibacr.azurecr.io/${IMAGE_NAME}:${IMAGE_TAG}",
                        "createOptions": {
                            "HostConfig": {
                                "Privileged": true
                            }
                        }
                    },
                    "type": "docker",
                    "status": "running",
                    "restartPolicy": "always",
                    "version": "${IMAGE_VERSION}",
                    "startupOrder": "${MODULE_STARTUP_ORDER}"
                }
            }
        }
    },
    "labels": {},
    "metrics": {
        "queries": {},
        "results": {}
    },
    "etag": "*"
}
 ```

</details>

**Comment by richma-ms** [comment]
@itsMeDacarvalho @acharaj looks like the createOptions section is incorrect.  It must be a string, instead of a JSON object.  Try converting it to a stringified JSON and see if the error goes away.

The fact that the UX is not telling you exactly what failed the validation is a bug, and I believe the UX team has a fix pending for it.

**Comment by itsMeDacarvalho** [comment]
Hi @richma-ms! 😃  
Thank you for taking the time to reply... The explanation makes perfect sense, I'll try it out and as soon as I get it I'll leave feedback here.
