### ISSUE TITLE
Can I install Linux Azure IoT Edge on Dibean buster OS ?

### ISSUE THREAD

**Issue by t2865k5** [Azure/iotedge#4911]
**Question Summary**
I want to install moby-engine and aziot-edge package on Debian Burst OS. Result: Installation failed.
I want to know if Linux Azure IoT Edge supports Debian Burst OS version.

**Detailed background**
curl -k https://packages.microsoft.com/config/debian/10/prod.list > ./microsoft-prod.list
sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
sudo curl -k https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
sudo apt-get update

 sudo apt-get install moby-engine
 Unable to locate package moby-engine

 sudo apt-get install aziot-edge
 Unable to locate package aziot-edge

**Comment by and-rewsmith** [comment]
@t2865k5 What architecture are you attempting to install on? For buster we only ship packages for arm32. From this link, you can find all the OS we support and what Tier 1 means for us. 

https://docs.microsoft.com/en-us/azure/iot-edge/support#operating-systems

**Comment by t2865k5** [comment]
Hi Andrew,
I want to install Azure IoT Edge in Dibean buster OS in AM3352 (ARM32 V7) platform .  When I run "sudo apt-get install moby-engine". It appeared this message: "Unable to locate package moby-engine". I can't install moby-engine package.

**Comment by and-rewsmith** [comment]
Have you done the prerequisite setup steps to configure the microsoft package registry?
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11#prerequisites

**Comment by t2865k5** [comment]
Hi ,
I run these command and they are OK . Pelease refer as follows:
//==================================
curl -k https://packages.microsoft.com/config/debian/10/prod.list > ./microsoft-prod.list
sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
sudo curl -k https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
sudo apt-get update
//====================================
But I run "sudo apt-get install moby-engine" command , result :  Unable to locate package moby-engine

I cat /etc/apt/sources.list.d/microsoft-prod.list , 
deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main

I modify /etc/apt/sources.list.d/microsoft-prod.list as follows:
deb [arch=armhf] https://packages.microsoft.com/debian/10/prod buster main

Run  "sudo apt-get install moby-engine" command again .It can be installed successfully.

But I run sudo apt-get update and sudo apt-get install aziot-edge command .

result: Unable to locate package aziot-edge

**Comment by t2865k5** [comment]
Hi ,
About aziot-edge support on ARM 32 platform , it only supports Debian Stretch. Does it not support Debian buster?


https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2020-11#operating-systems

![image](https://user-images.githubusercontent.com/79963188/116509652-43eda100-a8f6-11eb-9587-4a49b91a948c.png)

**Comment by and-rewsmith** [comment]
> I cat /etc/apt/sources.list.d/microsoft-prod.list ,
deb [arch=amd64] https://packages.microsoft.com/debian/10/prod buster main

I know you are running buster, but if you follow the prerequisite steps for stretch it will work. So you can put this in your `/etc/apt/sources.list.d/microsoft-prod.list`:

```
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/stretch/multiarch/prod stretch main
```

> About aziot-edge support on ARM 32 platform , it only supports Debian Stretch. Does it not support Debian buster?

I know that it works on buster, but I am not sure why we don't specify that. I will ask around today.

**Comment by and-rewsmith** [comment]
@t2865k5 We have work on the backlog currently for moving Buster to tier 1. We were waiting for the 1.1 and 1.2 releases to get out the door. Now that they are done we can schedule this work.

**Comment by and-rewsmith** [comment]
@t2865k5 Did this work for you?

**Comment by t2865k5** [comment]
Hi ,
Thank you very much for the information.
I will go to work on May 3rd. I will try .

**Comment by t2865k5** [comment]
Hi Smith,
Thank you ! I can install moby-engine and aziot-edge .

**Comment by t2865k5** [comment]
Thank you very much for your support.

**Comment by amit12cool** [comment]
@and-rewsmith  I followed above solution but I get `E: unable to locate package azureiot-edge`

**Comment by and-rewsmith** [comment]
@amit12cool The package name should be aziot-edge

**Comment by amit12cool** [comment]
@and-rewsmith On a fresh virtual machine with Buster Debian 10 OS Im still facing the issue. Below is error:-
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package aziot-edge:amd64 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'aziot-edge:amd64' has no installation candidate


```

**Comment by and-rewsmith** [comment]
@amit12cool We only maintain buster packages for Raspberry Pi OS Buster. 

For more information on supported platforms:
https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2020-11

**Comment by amit12cool** [comment]
Ok..so does that mean it will not be installed using the `install` command?
