### ISSUE TITLE
C# Direct Method call from Backend app to IoT Edge module gives "DeviceNotFoundException"

### ISSUE THREAD

**Issue by marcelosilvaidp** [Azure/iotedge#4912]
I've setup a code to simulate a Direct Method call from a backend application  (e.g. Blazor Web App) to an **IoT Edge Module**, but I receive a `Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException` after call InvokeDeviceMethodAsync.

Here's the code used:

```
using System;
using System.Threading.Tasks;
using Microsoft.Azure.Devices;

namespace EdgeDirectMethodCall
{
    class Program
    {
        private static string _hubConnString = "HostName=xxxxx.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxxxxx";
        private static string _method = "ReceiveDirectMethod";
        private static string _deviceId = "MyIoTEdgeDeviceId";
        private static string _moduleId = "MyIoTEdgeDeviceModule";


        static void Main(string[] args)
        {
            var _servClient = ServiceClient.CreateFromConnectionString(_hubConnString);

            Task.Run(async () => await InvokeMethod(_servClient));

            Console.ReadKey();
        }

        static async Task<CloudToDeviceMethodResult> InvokeMethod(ServiceClient serviceClient)
        {
            
            await serviceClient.OpenAsync();


            // Create the request
            var methodInvokation = new CloudToDeviceMethod(_method);

            // Sets the JSON payload
            methodInvokation.SetPayloadJson("{ \"Message\": \"Test\" }");

            // Execute request
            CloudToDeviceMethodResult resp = await serviceClient.InvokeDeviceMethodAsync(_deviceId, _moduleId, methodInvokation);

            // Write response to log for debugging
            Console.WriteLine($"Got result {resp.GetPayloadAsJson()} with status code {resp.Status}");

            return resp;
            
        }
    }
}
```

When the code runs, I receive `Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException` .

**Comment by and-rewsmith** [comment]
@marcelosilvaidp Does it always give DeviceNotFound or just sometimes? The first thing to check is that the device id and module id are correct. Next, that EdgeHub is currently in a running state. If it is stopped that would explain this exception. 

If it is running, this exception will happen by design if EdgeHub is restarting. Do any of these explanations sound likely?

**Comment by marcelosilvaidp** [comment]
> @marcelosilvaidp Does it always give DeviceNotFound or just sometimes? The first thing to check is that the device id and module id are correct. Next, that EdgeHub is currently in a running state. If it is stopped that would explain this exception.
> 
> If it is running, this exception will happen by design if EdgeHub is restarting. Do any of these explanations sound likely?

Hi @and-rewsmith, it happens all the time. Even if I include timeout parameters like below, the same exception occurs:
```
            TimeSpan connectionTimeout = new TimeSpan(0, 1, 30);
            TimeSpan responseTimeout = new TimeSpan(0, 1, 30);

            // Create the request
            var methodInvokation = new CloudToDeviceMethod(_method, responseTimeout, connectionTimeout);
```

The edgeHub module is always UP while I'm trying to run the code (screenshot below):
<img width="725" alt="Captura de Tela 2021-04-28 às 16 09 33" src="https://user-images.githubusercontent.com/64384870/116459875-b9953680-a83c-11eb-995f-b6427f27c81d.png">

**Comment by and-rewsmith** [comment]
@marcelosilvaidp Can you confirm that the `deviceid` and `moduleid` params are set correctly? 

If they are I would like to know:
1. What C# Devices SDK version you are using so I can try to reproduce myself?
2. If there are any errors or warnings in the EdgeHub logs. You can check this with ```iotedge logs edgeHub | grep ERR``` and ```iotedge logs edgeHub | grep WRN```
3. What is the output of ```iotedge check```

We have tests for this scenario which pass, so I am trying to rule out a setup issue.

**Comment by and-rewsmith** [comment]
Also. can you confirm that the module has registered a direct method handler? If it hasn't, that is another cause of this DeviceNotFound exception.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient.setmethodhandlerasync?view=azure-dotnet#Microsoft_Azure_Devices_Client_ModuleClient_SetMethodHandlerAsync_System_String_Microsoft_Azure_Devices_Client_MethodCallback_System_Object_
