### ISSUE TITLE
Inconsistent grammar on DevGuide.md

### ISSUE THREAD

**Issue by isa3bel** [Azure/iotedge#4917]
## Expected Behavior
There should be periods after every note section of each dependency. There's only a period for the last one, causing inconsistencies. 

![image](https://user-images.githubusercontent.com/18249360/116590373-856c5500-a8d2-11eb-88b7-bb60c0039810.jpeg)

## Current Behavior
The first three notes section of the dependencies don't have periods. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Go to devguide.md
2. Scroll to Run Integration tests
3. Notice grammar inconsistency

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by isa3bel** [comment]
I'll assign to myself

**Comment by and-rewsmith** [comment]
@isa3bel Are you going to fix it yourself? If so, thanks for contributing!

**Comment by isa3bel** [comment]
@and-rewsmith yes
