### ISSUE TITLE
EFLOW YAML.config CERTIFICATIONS area issue (permissions, etc)

### ISSUE THREAD

**Issue by shyonb** [Azure/iotedge#4933]
## Expected Behavior
Tell us what should happen

EFLOW example: https://github.com/Azure/iotedge-eflow/tree/main/samples/interop-textmsg-consoleapp

Step 7.  says to move certificates to iotedge device and to update iotedge config.yaml file with the certificates

After restarting iotedge the system should pass all sudo iotedge check steps and load the containers. 

## Current Behavior
Tell us what happens instead of the expected behavior

after restaring iotedge and doing a "sudo iotedge check --verbose" the following error occurred: 

iotedge-user@TABLET-RFPU9EBP-EFLOW-5b3c5bea [ ~ ]$ sudo iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Connection refused /var/lib/iotedge/mgmt.sock)
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Connection refused /var/lib/iotedge/mgmt.sock)
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
 
Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
 
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. in the following github:  https://github.com/Azure/iotedge-eflow/tree/main/samples/interop-textmsg-consoleapp
2. in step 7, when passing the certs into the iotedge device and onto the config yaml, the yaml file had issues.

Tried using test certifacte files from EFLOW Project Manager as well and still no luck.

When commenting out the certificates section of the config.yaml file, the iot edge containers would load successfully, but need certs path to work. 

## Context (Environment)

https://github.com/Azure/iotedge-eflow/tree/main/samples/interop-textmsg-consoleapp

### Output of `iotedge check`

iotedge-user@TABLET-RFPU9EBP-EFLOW-5b3c5bea [ ~ ]$ sudo iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Connection refused /var/lib/iotedge/mgmt.sock)
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Connection refused /var/lib/iotedge/mgmt.sock)
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
√ production readiness: certificates - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
 
Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
 

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by ancaantochi** [comment]
Hi!

- Which version of aziot-edged are you using (run iotedge version)
- Please provide aziot-edged logs, details how to get the logs: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#check-the-status-of-the-iot-edge-security-manager-and-its-logs

**Comment by shyonb** [comment]
Here is my info:

Which version of aziot-edged are you using (run iotedge version)

Answer: iotedge 1.1.1

Please provide aziot-edged logs, details how to get the logs: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#check-the-status-of-the-iot-edge-security-manager-and-its-logs

Answer: currently no logs are running.  When I do "sudo iotedge list" no containers appear

when I do "sudo iotedge system status" nothing outputs

Thanks

**Comment by ancaantochi** [comment]
Please try to get the logs by running:

`journalctl -u iotedge`

details here: [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=windowsadmincenter#verify-successful-configuration](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-on-windows?view=iotedge-2018-06&tabs=windowsadmincenter#verify-successful-configuration)

**Comment by ebertrams** [comment]
@Shyonb The commands that you list above are 1.2 commands. Please use this documentation: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2018-06#check-the-status-of-the-iot-edge-security-manager-and-its-logs for the 1.1 troubleshooting commands. Please let us know if you can get the logs using @ancaantochi 's recommendation. Thanks!

**Comment by ancaantochi** [comment]
Closing the issue because no answer, please reopen if needed
