### ISSUE TITLE
Unable to Assign a Static MAC Address to the custom Module using Deployment Manifest

### ISSUE THREAD

**Issue by patibandla123861** [Azure/iotedge#4944]
I am installing a custom module on Azure iotedge using a deployment manifest, the requirement is to have a static MAC Address for this module as the app's license is tied to its MAC Address

## Expected Behavior
Static MAC Address required for the custom IoT Edge Module - as the app license is tied to the MAC Address

## Current Behavior
Static MAC Address is not getting assigned to the module and auto-generated MAC address is getting assigned even though the correct configurations are done in the deployment manifest.

## Steps that I followed
Currently I followed the link - https://docs.docker.com/engine/api/v1.32/#operation/ContainerList for options to assign a static MAC Address as mentioned in the Microsoft documentation. But it doesn't seem to work. Here is a snippet of the deployment manifest, refer to the "NetworkingConfig" section below:

 ```
 "Telit": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "env": {
              "storageFolder": {
                "value": "/dw/db"
              }
            },
            "settings": {
              "image": "ugregistryy.azurecr.io/telit/dwgateway:1.0",
              "createOptions": {
                "NetworkingConfig":{
                  "EndpointsConfig":{
                    "azure-iot-edge":{
                      "MacAddress": "12:42:bc:12:00:90",
                      "IPAddress" : "172.18.0.25"
                    }
                  }
                },
                "HostConfig": {
                  "Binds": [
                    "TelitVolume:/dw/db"
                  ],
                  "PortBindings": {
                    "4012/tcp": [
                      {
                        "HostPort": "4012"
                      }
                    ],
                    "4009/udp": [
                      {
                        "HostPort": "4009"
                      }
                    ]
                  }
                }
              }
            }
          }
```

The above deployment manifest seems to get deployed successfully on the Azure IoT Edge. But when I do `docker inspect <containerID>` the MAC Address is still auto-generated for this module and not the one I assigned here in the manifest.

Please let me know if this is the correct way to assign a static MAC Address.

### Device Information
* Host OS : CBL Mariner OS (Linux) 
* Architecture : amd64
* Container OS : Linux Containers

### Runtime Versions
* aziot-edged : 1.0.10
* Edge Agent : 1.1
* Edge Hub : 1.1
* Docker/Moby : 19.03.11+ Azure

**Comment by ancaantochi** [comment]
Hi!

To be able to set the mac address please add below config to createOptions:

```
{
  "HostConfig": {
     "NetworkMode": "azure-iot-edge"
  },
  "MacAddress": "12:42:bc:12:00:90"
}
```

**Comment by patibandla123861** [comment]
> Hi!
> 
> To be able to set the mac address please add below config to createOptions:
> 
> ```
> {
>   "HostConfig": {
>      "NetworkMode": "azure-iot-edge"
>   },
>   "MacAddress": "12:42:bc:12:00:90"
> }
> ```

**Comment by patibandla123861** [comment]
Hello

**Comment by patibandla123861** [comment]
Hi,

Thanks you, now it is working as expected.

**Comment by asergaz** [comment]
Fyi same question in StackOverflow: https://stackoverflow.com/questions/67400889/how-to-assign-the-static-mac-address-to-iot-edge-module-using-deployment-manifes
