### ISSUE TITLE
[API Proxy] The customized nginx config was not applied when create the api proxy module

### ISSUE THREAD

**Issue by huanwu** [Azure/iotedge#4946]
Repro Step:
1. Add api proxy module from the portal 
2. Open the module and add the base64 string of the customized config in Module Twin Settings. Click Update.
3. Click "Review + create"

Expected:
The api proxy module installed on the device will use the customized config

Actual:
Still use the default config.

The workaround is to open the 'Module Identity Twin' on the portal, add a space, delete and save, which will manually trigger an update.

**Comment by huguesBouvier** [comment]
This issue was fixed
