### ISSUE TITLE
The container host is on unsupported build version 16299

### ISSUE THREAD

**Issue by VikasJaiswal** [Azure/iotedge#496]
Hi,
I am getting the error while installing IOT Edge Runtime using below Powershell command: 
PowerShell Command:-
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -Manual -ContainerOs Windows

Error:-

The container host is on unsupported build version 16299.

Please use a container host running build 14393 newer when using Linux containers or with one of the following supported build versions when using Windows containers:
17134
17763

The prerequisites for installation of the IoT Edge Security daemon are not met. Please fix all known issues before rerunning this script.

Note:- I am using windows 10, 64 bit, build version 16299 and can't upgrade to that as per my company policy.

Anyone please let me know how to resolve this issue. Thanks in advance.
@iotedge-ci

**Comment by darobs** [comment]
Hello @VikasJaiswal, 

Azure IoT Edge on Windows running Windows containers is dependent on changes in versions 1803 and later to run correctly. 

You can run with Linux containers with the Fall Creators Update, but if you need Windows containers, then I don't have any good options for you.

Thanks,
Dave Robson

**Comment by veyalla** [comment]
@VikasJaiswal Would not recommend that since we've a ton of changes since the runtime the supported 16299 and it most likely will not work. 

Using a RS4 17134 VM on 16299 would work though, if that is possible on your side...

**Comment by VikasJaiswal** [comment]
Thanks @veyalla, I will try with the VM.

**Comment by darobs** [comment]
Thank you @veyalla!  @VikasJaiswal - I am going to close this issue. If you have any other questions or problems, please reopen the issue or create a new one.

Thank you.

**Comment by sergeimay** [comment]
Hello, I have almost same problem with windows 1903/18362: 
"The container host is on unsupported build version 18362.
Please use a container host running one of the following build versions for running Windows containers:
17763 " 
What I have to do ?

**Comment by arsing** [comment]
@sergeimay Use 17763, either Windows 10 or Windows Server 2019. If you don't want to modify your host, then do it in a VM.

Or use Linux containers, but as the docs say that is not supported for production.

@veyalla I think you said we had some docs that told people how to set up a VM, but I can't find them. (It's not mentioned in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows ) Can you give the link?

**Comment by veyalla** [comment]
It is listed in the [prerequisites for the Windows Quickstart](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#prerequisites):

`az vm create --resource-group IoTEdgeResources --name EdgeVM --image MicrosoftWindowsDesktop:Windows-10:rs5-pro:latest --admin-username azureuser --admin-password {password} --size Standard_DS1_v2`

Supported OS list is here:
https://docs.microsoft.com/en-us/azure/iot-edge/support#operating-systems

**Comment by kgremban** [comment]
There's also documentation specifically about installing IoT Edge on Windows Server VMs in Azure: https://docs.microsoft.com/azure/iot-edge/how-to-install-iot-edge-windows-server-vm
