### ISSUE TITLE
Message format for signal gate node

### ISSUE THREAD

**Issue by GauravChoube** [Azure/iotedge#4960]
Hi everyone,
I have scenario where i need to store the video based particular event. So i planned to used signal gate node.
from example, its start storing the video when motion detect , but did not give  more detail about what message send to signal gate nodes.
As per theory need to send some event message to gate node in order activate and i want to send the that event message from my inference AI module which is implemented as http extension.
I have two question as
1. I am planning to add this event message in inference message and send to signal gate node as well as iot hub sink, signal gate node get trigger and start storing video, what is format of event message for signal gate node.
2.  i have different situation for start recording and stop recording, but with gate node , i can start video recording and but dont have control over stop recording, so how do I achieve it ?

Please anyone know answer ,let me know

Thanks in advance

**Comment by veyalla** [comment]
Hi @GauravChoube  - this repo is geared towards technical issues around IoT Edge runtime. We don't have the expertise here to provide general architecture guidance. You can try posting in [IoT Edge Q&A site](https://docs.microsoft.com/en-us/answers/topics/azure-iot-edge.html).
