### ISSUE TITLE
iotedge check connectivity fails wrongly due to error

### ISSUE THREAD

**Issue by chull434** [Azure/iotedge#4972]
## Expected Behavior
When running iotedge check command behind a firewall set correctly connectivity check shouldn't give a false negative

## Current Behavior
When running iotedge check command behind a firewall and connectivity check fails but appears to be a false flag as connection to iothub is grand everything else works. Error from running verbose doesn't give much idea as to what the actual root cause is.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. run iotedge check behind firewall, see connection fails
2. 
3. 
4. 

## Context (Environment)
behind firewall which allows connection ok out to iothub and private acr for custom images etc as per [documentation](https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-2020-11#allow-connections-from-iot-edge-devices) 

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Connectivity checks
-------------------
× container on the default network can connect to upstream  AMQP port - Error
    Container on the default network could not connect to ***-IoTHub.azure-devices.net:5671
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Resource temporarily unavailable)
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to ***-IoTHub.azure-devices.net:443
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Resource temporarily unavailable)
× container on the default network can connect to upstream MQTT port - Error
    Container on the default network could not connect to ***-IoTHub.azure-devices.net:8883
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Resource temporarily unavailable)
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
26 check(s) succeeded.
6 check(s) raised warnings.
4 check(s) raised errors.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04]: 
* Architecture [e.g. arm64]: 
* Container OS [e.g. Linux containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.0
* Docker/Moby [run `docker version`]: 20.10.2

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Connection is fine to iothub but connection check fails as a false negative, sent us trouble shooting when none was needed.

**Comment by dylanbronson** [comment]
Hello,
While it is weird that these checks are failing, it is not weird that your edge is working correctly. 

IoT Edge doesn't have any system modules (edgeHub and edgeAgent) on the default network. So as long as the other network connectivity checks are working correctly, it makes sense that everything is working as expected.

With that being said, it's still odd that these checks are failing. Can you check to make sure your default docker network is a "bridge" network, which means it has connectivity to the internet (bridge is the default)? You can do a "docker network ls" for that.

If it is and you are still curious, on the default network, you could try running a simple docker container on the that sends a ping to see if it has connectivity.

I am looking into if we can remove this check, since it seems unnecessary (for historical context, edgeAgent used to deploy on the default network, which is probably why this check exists, but now it's on the azure-iot-edge network)

**Comment by chull434** [comment]
yeah all other docker containers on normal docker network and the iotedge modules on there iot edge network can connect out to the internet ok and the rest of the deployment is working as expected. 

the main issue we had was not being able to trouble shoot the issue as the only error you get is:
` caused by: docker returned exit code: 1, stderr = One or more errors occurred. (Resource temporarily unavailable)`
 which is only saying there was an issue but not what the issue was

**Comment by dylanbronson** [comment]
Can you try something like this
```
docker run -it --privileged ubuntu bash  # run mini ubuntu container on default network
apt-get update                                                   
apt-get install iputils-ping  # install ping
ping google.com  # ping 
```
That will test your connectivity on your default network
