### ISSUE TITLE
Impossible to use GatewayHostName with slashes in the path

### ISSUE THREAD

**Issue by jakubstochl** [Azure/iotedge#4976]
Hi,
I'm trying to connect to IoT Hub over Gateway using GatewayHostName parameter. It works without problems when GatewayHostName contains only FQDN without other path (e.g. my-gateway.server.com) but in case the gateway contains more complex path (e.g. my-gateway.server.com/gateway/iot) the setting is accepted and validated but everything after slash is ignored and only core address is used.

# Context

- **OS, version, SKU and CPU architecture used:** Tested on MacOS and Windows 10
- **Application's .NET Target Framework :** netcoreapp3.1
- **Device:** Laptop
- **SDK version used:** Microsoft.Azure.Devices.Client, 1.33.1-NestedEdge

## Description of the issue
Problem is happening when using following configuration:

`DeviceClient deviceClient = DeviceClient.CreateFromConnectionString("HostName=someiot.azuredevices.net;GatewayHostName=gw.examplegw.com/gateway/iot;DeviceId=test;SharedAccessKey=xxx", TransportType.Http1)`

What happens is that called url is 
`gw.examplegw.com/devices/test/messages/events `
instead of expected 
`gw.examplegw.com/gateway/iot/devices/test/messages/events`

This is happening because of the code in SDK class Microsoft.Azure.Devices.Client.Transport.HttpClientHelper where method PostAsync uses following code:

`new Uri(_baseAddress, requestUri)`

where _baseAddress is GatewayHostName from configuration and requestUri is set to relative part of URI based on CommonConstants (e.g. `/devices/{0}/messages/events`)

as described e.g. on [https://stackoverflow.com/questions/372865/path-combine-for-urls](url) in case that relative part of URI starts with slash, relative paths are not combined but only base address part from first uri is used.

Can you please let me know if this is intention or it is expected that uri with relative path can be used in GatewayHostName parameter?

**Comment by ebertrams** [comment]
Closing this issue since we need to transfer it to the IoT Hub team.
