### ISSUE TITLE
iotedged : Invalid URL "fd://iotedge.mgmt.socket/": URL could not be parsed as fd number nor fd name

### ISSUE THREAD

**Issue by rohitmshetty** [Azure/iotedge#5010]
**Trying to install iotedge 1.1.1 in ubuntu 18.04 azure vm. On checking _iotedged_ command, getting _"Invalid URL "fd://iotedge.mgmt.socket/": URL could not be parsed as fd number nor fd name"_error** 

**[Thu May 20 10:33:41 root@CSIDEVIOTUS0101:/home/cloud.ds.gehc.net/212773247 #] iotedged**
<6>2021-05-20T10:33:49Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2021-05-20T10:33:49Z [INFO] - Version - 1.1.1
<6>2021-05-20T10:33:49Z [INFO] - Using config file: /etc/iotedge/config.yaml
<6>2021-05-20T10:33:49Z [INFO] - Configuring /var/lib/iotedge as the home directory.
<6>2021-05-20T10:33:49Z [INFO] - Configuring certificates...
<6>2021-05-20T10:33:49Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
<6>2021-05-20T10:33:49Z [INFO] - Finished configuring provisioning environment variables and certificates.
<6>2021-05-20T10:33:49Z [INFO] - Initializing hsm...
<6>2021-05-20T10:33:49Z [INFO] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_log.c:log_init:41) Initialized logging
<6>2021-05-20T10:33:49Z [INFO] - Finished initializing hsm.
<6>2021-05-20T10:33:49Z [INFO] - Provisioning edge device...
<6>2021-05-20T10:33:49Z [INFO] - Starting provisioning edge device via manual mode using a device connection string...
<6>2021-05-20T10:33:49Z [INFO] - Manually provisioning device "device08" in hub "gehclcscsidevusea06-iot-hub.azure-devices.net"
<6>2021-05-20T10:33:49Z [INFO] - Finished provisioning edge device.
<6>2021-05-20T10:33:49Z [INFO] - Initializing the module runtime...
<6>2021-05-20T10:33:49Z [INFO] - Initializing module runtime...
<6>2021-05-20T10:33:49Z [INFO] - Using runtime network id azure-iot-edge
<6>2021-05-20T10:33:50Z [INFO] - Successfully initialized module runtime
<6>2021-05-20T10:33:50Z [INFO] - Finished initializing the module runtime.
<6>2021-05-20T10:33:50Z [INFO] - Stopping all modules...
<6>2021-05-20T10:33:50Z [INFO] - Finished stopping modules.
<6>2021-05-20T10:33:50Z [INFO] - Detecting if configuration file has changed...
<6>2021-05-20T10:33:50Z [INFO] - No change to configuration file detected.
<6>2021-05-20T10:33:50Z [INFO] - Edge issuer CA expiration date: 2021-08-17T11:37:48Z
<6>2021-05-20T10:33:50Z [INFO] - Obtaining workload CA succeeded.
<6>2021-05-20T10:33:50Z [INFO] - Starting management API...
<6>2021-05-20T10:33:50Z [INFO] - Starting workload API...
<6>2021-05-20T10:33:50Z [INFO] - Starting watchdog with 60 second frequency...
<3>2021-05-20T10:33:50Z [ERR!] - The daemon could not start up successfully: Could not start management service
<3>2021-05-20T10:33:50Z [ERR!] -        caused by: Invalid URL "fd://iotedge.mgmt.socket/": URL could not be parsed as fd number nor fd name
<3>2021-05-20T10:33:50Z [ERR!] -        caused by: Environment variable LISTEN_FDNAMES is set to an invalid value.
<3>2021-05-20T10:33:50Z [ERR!] -        caused by: environment variable not found

**[Thu May 20 10:34:05 root@CSIDEVIOTUS0101:/home/cloud.ds.gehc.net/212773247 #] iotedge check**
Configuration checks
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-08-17 11:37:48 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
× host can connect to and perform TLS handshake with IoT Hub AMQP port - Error
    Could not connect to gehclcscsidevusea06-iot-hub.azure-devices.net:5671 : could not resolve hostname
× host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - Error
    Could not connect to gehclcscsidevusea06-iot-hub.azure-devices.net:443 : could not resolve hostname
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect to gehclcscsidevusea06-iot-hub.azure-devices.net:8883 : could not resolve hostname
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

15 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.
6 check(s) raised errors. Re-run with --verbose for more details.

**Device Information**
Azure VM[e.g. Ubuntu 18.04]:

**Runtime Versions**
iot-edged [run iotedge version]: iotedge 1.1.1

**Comment by darobs** [comment]
Hi @rohitmshetty

Based on our out-of-band conversation, we discovered that the management socket unit in systemd had duplicate entries - one in `/lib/systemd/system/iotedge.mgmt.socket` and an `override.conf` in  `/etc/systemd/system/iotedge.mgmt.socket.d`.  This put 2 `iotedge.mgmt.socket` entries into "LISTEN_FDNAMES".

Removing the override.conf file got past that problem.

**Comment by darobs** [comment]
Hi @rohitmshetty,

We have high confidence the problem described in the original post has been resolved.  I am closing this issue.
