### ISSUE TITLE
Error installing moby-engine on Ubuntu 18.04 64 bit on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by ce314** [Azure/iotedge#5011]
I am following the directions from here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11

When I execute the command : sudo apt-get install moby-engine

I get the following output: Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 moby-engine : Depends: moby-containerd (>= 1.4.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I follow the trouble shooting commands however everything is enabled under Generally NEccessary and Network Drivers. So I am unsure how to fix this error.
If someone could help that has experience with iotedge devices that would be great.

**Comment by darobs** [comment]
Hi @ce314,

Very frustrating, I'm sorry this is happening. If you did the `apt update`, can you try to `sudo apt-get install  moby-containerd` and see what it says?

**Comment by ce314** [comment]
This is what I get:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 moby-containerd : Depends: moby-runc (>= 1.0.0~rc10) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by darobs** [comment]
Hi @ce314,

Any luck?

**Comment by ce314** [comment]
Sorry, forgot to respond but it did not work however I decided to go a different direction that did not need the Moby engine. Thanks for your help!

**Comment by varunpuranik** [comment]
Thanks @ce314 for the update. I will close this issue. 
Curious to know what direction you decided to go in... would you mind sharing?

**Comment by Amethyst6000** [comment]
I met exactly the same issue on Nvidia Jetson Nano on Ubuntu 18.04
following the steps in 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal
after 
~~~
sudo apt-get install moby-engine
~~~
got message:
~~~
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 moby-engine : Depends: moby-containerd (>= 1.4.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
~~~

Check Generally Necessary and Network Drivers items were all enable.

I also tried @darobs's suggestion,
but unfortunately it still doesn't work because it's different on Jetson.

**Comment by pgrudzien12** [comment]
I just conducted the installation on jetson nano:

```
jetbot@jetbot-desktop:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
At the beginning, I got similar errors but slightly different yours, @Amethyst6000. Try this and look closely at the issues you got, it should tell you what deps are wrong. For me, it was docker-ce which I didn't care about at this point.

```
jetbot@jetbot-desktop:~$ sudo apt-get install moby-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 moby-engine : Depends: moby-containerd (>= 1.4.3) but it is not going to be installed
               Depends: moby-runc (>= 1.0.0~rc93) but it is not going to be installed
               Conflicts: docker.io but 20.10.7-0ubuntu5~18.04.3 is to be installed
               Recommends: moby-cli but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The solution for me was to install everything from down to top. Started with:
`sudo apt-get install moby-runc` 
then 
`sudo apt-get install moby-containerd`
and finally:
`sudo apt-get install moby-engine`

**Comment by Amethyst6000** [comment]
> 

Those steps are very helpful!
before those steps, I met conflict: runc, so I remove older package
`
sudo apt-get remove runc
`
then use @pgrudzien12 provided steps
`
sudo apt-get install moby-runc
`
`
sudo apt-get install moby-containerd
`
`
sudo apt-get install moby-engine
`
Finally completed the installation of moby-engine.

**Comment by rahulkhairnarr** [comment]
> I just conducted the installation on jetson nano:
> 
> ```
> jetbot@jetbot-desktop:~$ cat /etc/os-release
> NAME="Ubuntu"
> VERSION="18.04.5 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.5 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic
> ```
> 
> At the beginning, I got similar errors but slightly different yours, @Amethyst6000. Try this and look closely at the issues you got, it should tell you what deps are wrong. For me, it was docker-ce which I didn't care about at this point.
> 
> ```
> jetbot@jetbot-desktop:~$ sudo apt-get install moby-engine
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  moby-engine : Depends: moby-containerd (>= 1.4.3) but it is not going to be installed
>                Depends: moby-runc (>= 1.0.0~rc93) but it is not going to be installed
>                Conflicts: docker.io but 20.10.7-0ubuntu5~18.04.3 is to be installed
>                Recommends: moby-cli but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```
> 
> The solution for me was to install everything from down to top. Started with: `sudo apt-get install moby-runc` then `sudo apt-get install moby-containerd` and finally: `sudo apt-get install moby-engine`

This works, thanks

**Comment by Kralg** [comment]
Hello, 

I am having a similar issue.
The goal is to install Device Update agent on Raspbian bullseye (11).

I was following for debian: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.5&viewFallbackFrom=iotedge-2020-11&preserve-view=true&tabs=azure-portal%2Cdebian

And at sudo systemctl restart docker I am getting:
Dependency failed for Docker Application Container Engine.
 docker.service: Job docker.service/start failed with result 'dependency'.
 
 I also tried to uninstall 
 these packages and install one by one:
 sudo apt-get install moby-runc
sudo apt-get install moby-containerd
sudo apt-get install moby-engine

Can you please write what could be the reason for this error ?
