### ISSUE TITLE
IOT DPS Set Child/Parent Relationship

### ISSUE THREAD

**Issue by zachcdr** [Azure/iotedge#5021]
To begin, there are a few other _closed_ issues circulating this topic. I have not seen any new posts, however, since August of 2020.

The use case here is to be able to provision a leaf device(s) via the Device Provisioning Service (DPS) and associate a parent device at registration. This will enable the freshly registered device to instantiate a device client and set a method handler. 

Leveraging the C# SDK I am able to do this:

```
private async void ProvisionDevice()
{
    var security = new SecurityProviderSymmetricKey(_deviceId, Utils.ComputeDerivedSymmetricKey(Convert.FromBase64String(ConfigurationManager.AppSettings["DPS_Devices_ManagementKey"]), _deviceId), null);

    ProvisioningDeviceClient provClient = ProvisioningDeviceClient.Create(ConfigurationManager.AppSettings["DPS_GlobalDeviceEndpoint"], ConfigurationManager.AppSettings["DPS_ScopeId"], security, new ProvisioningTransportHandlerMqtt(TransportFallbackType.WebSocketOnly));

    DeviceRegistrationResult result = await provClient.RegisterAsync();

    IAuthenticationMethod auth = new DeviceAuthenticationWithRegistrySymmetricKey(
        result.DeviceId,
        security.GetPrimaryKey());

    _deviceClient = DeviceClient.Create(result.AssignedHub, ConfigurationManager.AppSettings["EdgeGatewayHostName"], auth, s_transportSettings);

    await _deviceClient.SetMethodHandlerAsync("ReceivingDirectMethod", ReceivingDirectMethod, _deviceClient);
}
```

The last line here will fail due to not having an IOT Edge Device assigned as the parent of this leaf device. 

Any help or news on development would be greatly appreciated.

Cheers.

EDIT:
I should note that I have tried using the `ProvisioningRegistrationAdditionalData` JsonData property in this way also:
```
DeviceRegistrationResult result = await provClient.RegisterAsync(new ProvisioningRegistrationAdditionalData()
{
     JsonData = $"{{\"deviceScope\": \"ms-azure-iot-edge://<myEdgeDevice>\",\"parentScopes\": [\"ms-azure-iot-edge://<myEdgeDevice>\"]}}"
});
```

**Comment by arsing** [comment]
>The last line here will fail due to not having an IOT Edge Device assigned as the parent of this leaf device.

So the `SetMethodHandlerAsync` line fails and not the `provClient.RegisterAsync` line? ie provisioning with DPS succeeds, it's just the connection to Edge Hub that fails?

**Comment by zachcdr** [comment]
@arsing that is correct. The device is provisioned and viewable in azure portal after running ` DeviceRegistrationResult result = await provClient.RegisterAsync();`. The device just does not have a "parent' edge device. I believe the `SetMethodHandlerAsync` fails due to that reason.

Here are the logs:
<6> 2021-05-27 22:33:54.047 +00:00 [INF] - Unable to authenticate client 9605thechap with cached service identity 9605thechap. Resyncing service identity...
<6> 2021-05-27 22:33:54.047 +00:00 [INF] - Unable to authenticate client <myDeviceId> with cached service identity <myDeviceId>. Resyncing service identity...
<6> 2021-05-27 22:33:54.235 +00:00 [INF] - Client <myDeviceId> in device scope not authenticated locally.
<3> 2021-05-27 22:33:54.235 +00:00 [ERR] - Unable to generate identity for clientId <myDeviceId> and username ceiotedgeserver.westus2.cloudapp.azure.com/<myDeviceId>/?api-version=2020-09-30&DeviceClientType=.NET%2F1.37.2%20%28.NET%20Framework%204.8.4300.0%3B%20Microsoft%20Windows%2010.0.19042%20WindowsProduct%3A0x00000004%3B%20X86%29
<6> 2021-05-27 22:33:54.235 +00:00 [INF] - ClientNotAuthenticated, Client ID: <myDeviceId>; Username: ceiotedgeserver.westus2.cloudapp.azure.com/<myDeviceId>/?api-version=2020-09-30&DeviceClientType=.NET%2F1.37.2%20%28.NET%20Framework%204.8.4300.0%3B%20Microsoft%20Windows%2010.0.19042%20WindowsProduct%3A0x00000004%3B%20X86%29, 5fd9d4c5
<6> 2021-05-27 22:33:58.692 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub
<6> 2021-05-27 22:33:58.692 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.

**Comment by arsing** [comment]
Right, so if the portal isn't showing a parent device either, then the initial provisioning didn't set it and EH is correct to reject it.

I suggest asking at https://github.com/Azure/azure-iot-sdk-csharp/issues how you're supposed to set a parent device with the provisioning client's `RegisterAsync`. (I can only find references to the Service SDK's registry manager.)

I'll check if anyone in the Edge team happens to know.

**Comment by zachcdr** [comment]
@arsing thanks - I’ll post over there as well. I appreciate you asking around.

**Comment by varunpuranik** [comment]
DPS does not yet support creating a parent-child relationship between a leaf device and an IoT Edge device at provisioning time. It is in the backlog for the DPS team, and currently in the design/investigation phase. 
@nberdy can provide you more information.

**Comment by zachcdr** [comment]
@varunpuranik - I appreciate the response. Is there a way to do this post provisioning time via the sdk or is the only way via the azure portal?

**Comment by arsing** [comment]
You can do it through the service SDK because you'll need service-level access. So you can't do it from the device itself.
