### ISSUE TITLE
Update-IoTEdge on Windows fails with "Invalid URI"

### ISSUE THREAD

**Issue by noquarter12** [Azure/iotedge#5026]
## Expected Behavior
I would like to update my IoT Edge daemon on a windows IoT OS. As per the [instructions](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-on-windows?view=iotedge-2018-06&viewFallbackFrom=iotedge-2020-11#update-iot-edge) on the website I am running:

```
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Update-IoTEdge
```

## Current Behavior
When I run the update command I get the following output:

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IoTEdge                             {Deploy-IoTEdge, Get-IoTEdgeLog, Import-IntermediateCertCh...
The container host is on supported build version 17763.
Skipping VC Runtime installation because it is already installed.
Downloading IoT Edge...
Invoke-WebRequest : Invalid URI: The hostname could not be parsed.
At line:2209 char:13
+             Invoke-WebRequest `
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], UriFormatException
    + FullyQualifiedErrorId : System.UriFormatException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Have IoT Edge running on a windows host.
2. Have IoT Edge daemon Version 1.1.1
3. Run the following command . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Update-IoTEdge

## Context (Environment)

- Note this edge device has not had a configuration pushed to it yet, not sure if that matters.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.1.1 but 1.1.3 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 4946 days (at 2034-12-09 20:27:51 UTC) causing module-to-module and downstream device communicat
ion to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best prac
tices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Windows Server IoT 2019
* Architecture: amd64
* Container OS: Windows containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.1.1 (27369573a0c04f9c2deeaf1ba4198a7efb8e4604) 
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: N/A
* Docker/Moby [run `docker version`]: 19.03.12+azure

**Comment by arsing** [comment]
What's the value of `$env:PROCESSOR_ARCHITECTURE` in the same PS shell that you ran `Update-IoTEdge` ? I suspect it's not `AMD64` and that you're running it in a 32-bit PS window.

**Comment by noquarter12** [comment]
Yes it does return x86, its a x64 processor but a x86 PS window. Can you help me understand how that would cause an issue with the URI in the script?

**Comment by arsing** [comment]
>Can you help me understand how that would cause an issue with the URI in the script?

You can see it right there in the output you posted.

The IWR invocation is [line 2209](https://github.com/Azure/iotedge/blob/release/1.1/scripts/windows/setup/IotEdgeSecurityDaemon.ps1#L2209) -> the preceding "Downloading IoT Edge" output is from [line 2203](https://github.com/Azure/iotedge/blob/release/1.1/scripts/windows/setup/IotEdgeSecurityDaemon.ps1#L2203) -> the caller of `Download-File` with `-Description 'IoT Edge'` is [line 1347](https://github.com/Azure/iotedge/blob/release/1.1/scripts/windows/setup/IotEdgeSecurityDaemon.ps1#L1347) -> the URL in that invocation is looked up based on `$env:PROCESSOR_ARCHITECTURE`

Also, the document does mention that you need to be sure to use x64 PS in [step 1 of the installation steps.](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-on-windows?view=iotedge-2018-06#install-the-iot-edge-security-daemon)

**Comment by noquarter12** [comment]
I am sorry for bothering you.
