### ISSUE TITLE
x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by beckerben** [Azure/iotedge#5028]
Following the directions to setup a [transparent gateway](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-iot-edge-device?view=iotedge-2020-11&tabs=azure-portal) and running into issues when using the self signed demo scripts.  The directions clearly state that for the hostname on the gateway device in the config.toml, an IP can be used.  This appears to be false. 

I have to do this because my leaf device will not have internet connectivity and also can't access the DNS server.  I have setup the hostname in the config.toml on the gateway to be the IP and on the leaf device config.toml I set the parent hostname equal to the same IP.   The downstream device reports the error:

`x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs`

On the gateway host, I tried the curl command and it reports this error:

`SSL: no alternative certificate subject name matches target host name '10.10.56.25' `

Furthermore, I have tried using the actual hostname which appears in the certificate and updating the /etc/hosts file on both the gateway and leaf device, but on the leaf device I get a docker error that it can't resolve the hostname. 

```× parent hostname is resolvable from inside container - Error
    Failed to resolve parent hostname fieldgateway01
```

I also this message during iotedge check even though I have properly registered the root CA:

```Connectivity checks (aziot-identity-service)
--------------------------------------------
× host can connect to and perform TLS handshake with iothub AMQP port - Error
    Make sure the parent device is reachable using 'curl https://parenthostname'. Make sure the the trust bundle has been added to the trusted store: sudo cp <path>/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
                sudo update-ca-certificates
```

The curl command from the leaf device runs just fine:

```
advantech@edgenode02:~/proj$ curl https://fieldgateway01
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.19.9</center>
</body>
</html>
advantech@edgenode02:~/proj$
```

Seems I'm stuck, any help here?

**Comment by arsing** [comment]
>The downstream device reports the error:
>
>`x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs`

Please paste the output of running this on the leaf device:

```sh
</dev/null openssl s_client -connect x.x.x.x:443 -noout -text | openssl x509 -in - -noout -text | egrep 'DNS:|IP Address:'
```

(That's the list of all SANs in x.x.x.x's server cert.)

---

>Furthermore, I have tried using the actual hostname which appears in the certificate

If the hostname appears in the certificate (the output of the above command will confirm), that indicates the config.toml of the gateway has the hostname and not the IP. Did you perhaps start edged before you'd set the hostname to an IP?

---

>[...] and updating the /etc/hosts file on both the gateway and leaf device, but on the leaf device I get a docker error that it can't resolve the hostname.

What does "a docker error" mean. An error from running `docker` the CLI? An error logged by the `dockerd` daemon? Something else?

Apart from that, does `nslookup fieldgateway01` work?

---

>I also this message during iotedge check even though I have properly registered the root CA:

Re-running with `--verbose` may print a more enlightening error.

**Comment by beckerben** [comment]
I gave up on trying to make it work with IP and started from scratch using FQDN, all good on getting past these certificate issues. I am now stuck on what looks to be DNS issues on the leaf.  Will have to log another issue.
