### ISSUE TITLE
Does IoTEdge with kubernetes supports for multiple replicas?

### ISSUE THREAD

**Issue by archanabwk** [Azure/iotedge#5030]
Hi,
I'm working with IoTEdge on Kubernetes for a product and before using it for production deployment, we want to make sure about multiple replica support. 
I found a document where it says, IoTEdge doesn't support multiple replicas for now. https://microsoft.github.io/iotedge-k8s-doc/scaling.html#what-is-not-supported
It would be helpful, if anyone can confirm the same. 

Thanks,
Archana Borawake

**Comment by veyalla** [comment]
It does not, as the documentation says.
