### ISSUE TITLE
Iot Edge, VisualStudioCode, building new container, wrong platform

### ISSUE THREAD

**Issue by arnierambo** [Azure/iotedge#5041]
Hello
Host cpu: x86
host os: ubuntu 20.04.1 LTS 64-bit
ide: Visual studio code 1.56.2
docker: 20.10.2
on bottom menu"Default Platform of IoT Edge Solution" was chosen arm32v7

target cpu: arm32v7
targer os: debian

first line of dockerfile.arm32v7 is:
`FROM arm32v7/python:3.7-slim-buster`

but it cause error:
```
Step 1/17 : FROM arm32v7/python:3.7-slim-buster
3.7-slim-buster: Pulling from arm32v7/python
3035777cd90a: Pulling fs layer
acc9ed8dbabd: Pulling fs layer
dc831c3594fe: Pulling fs layer
5d422b8722ee: Pulling fs layer
28bc1ff4dced: Pulling fs layer
5d422b8722ee: Waiting
28bc1ff4dced: Waiting
acc9ed8dbabd: Verifying Checksum
acc9ed8dbabd: Download complete
dc831c3594fe: Verifying Checksum
dc831c3594fe: Download complete
3035777cd90a: Verifying Checksum
3035777cd90a: Download complete
5d422b8722ee: Verifying Checksum
5d422b8722ee: Download complete
28bc1ff4dced: Verifying Checksum
28bc1ff4dced: Download complete
3035777cd90a: Pull complete
acc9ed8dbabd: Pull complete
dc831c3594fe: Pull complete
5d422b8722ee: Pull complete
28bc1ff4dced: Pull complete
Digest: sha256:ae56b562bf6fd5568945e4d6852c410fe43cce8edfdc79f04611da8f26c6a642
Status: Downloaded newer image for arm32v7/python:3.7-slim-buster

WARNING: Pulled image with specified platform (linux/amd64), but the resulting image's configured platform (linux/arm) does not match.
This is most likely caused by a bug in the build system that created the fetched image (arm32v7/python:3.7-slim-buster).
Please notify the image author to correct the configuration.
```

Why pulled image has wrong platform, other than defined step 1?

**Comment by varunpuranik** [comment]
@tameraw / @konichi3 - can you please comment on this?

**Comment by veyalla** [comment]
Adding @marianan as well.

**Comment by marianan** [comment]
Tagging this week's DRI - @mhshami01 could you please take a look?

**Comment by mhshami01** [comment]
Hello @arnierambo,

Thank you for your submittal. Unfortunately, we are going to need additional information to help reproduce and triage the issue. Please provide detailed step by step instructions on what you did to observe this behavior. For example:

- select file xyz
- click menu item 123
- etc...

Also, please attach any files or screen shots if you think they would add any clarification.

Thank you, we look forward to your input.

**Comment by mhshami01** [comment]
@arnierambo, @veyalla - We should close this issue since it has been inactive for almost a month.
