### ISSUE TITLE
edgeAgent GetModuleLogs direct method returns "500 - Stream finished but there was a truncated final frame in the buffer" when using 'since' filter

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#5051]
I'm using the GetModuleLogs and UploadModuleLogs  direct methods to fetch the logs from my IoT edge modules.
I'm using IoT Edge on Windows, and using edgeAgent 1.1.0 and edgeHub 1.1.0.

## Expected Behavior
The GetModuleLogs and UploadModuleLogs should return a 200 when using the 'since' filter, and the logs should be retrieved or uploaded.

## Current Behavior
The response of the direct method indicates a failure when using the `since` filter:

```json
{"schemaVersion":"1.0", "items":[{"id":".*","filter":{"since":"5m"}}],"encoding":"none","contentType":"json"}
```

and

```json
{"schemaVersion":"1.0", "items":[{"id":".*","filter":{"since":"2021-05-27 22:08:25Z"}}],"encoding":"none","contentType":"json"}
```

return

```json
{"status":500,"payload":{"message":"Stream finished but there was a truncated final frame in the buffer"}}
```

When using the tail filter on  the other hand, the GetModuleLogs works as expected.

(When using UploadModuleLogs with the since filter, no blobs are being uploaded/added in my storage account).

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.  Execute the GetModuleLogs Direct Method with the json payload specified above, which has a 'since' parameter via the Azure portal

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Windows server 2019
* Architecture [e.g. amd64, arm32, arm64]: amd64 
* Container OS:   Windows containers 

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.0.9.5 (c602ee699e3004dc50fe4c2a4ae30765079b4855)
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1.0
* Docker/Moby [run `docker version`]: 3.0.5

**Comment by fgheysels** [comment]
I've tried this on another edge device that is running v1.3.0 of the iotedge service, and there the issue seems to be resolved.

**Comment by arsing** [comment]
>aziot-edged [run iotedge version]: iotedge 1.0.9.5 (c602ee6)

This version is unsupported. Please update to the latest 1.1 or the latest 1.2

>I've tried this on another edge device that is running v1.3.0 of the iotedge service, and there the issue seems to be resolved.

v1.3.0 ? The latest we've released is 1.2.0

**Comment by fgheysels** [comment]
Sorry, I made a mistake.  That's meant to be 1.1.3

**Comment by yophilav** [comment]
@fgheysels 
I noticed the `since":"2021-05-27 22:08:25Z"` is an incorrect format. 
Do you meant it to be `since":"2021-05-27T22:08:25Z"` -- Note the "T"
We use the same standard as docker CLI. ( https://docs.docker.com/engine/reference/commandline/logs/#examples ) 

On the other hand, we can possible make the error message more accurate than just 500 error.

**Comment by fgheysels** [comment]
The date-format was indeed the culprit.  It's fixed with using the correct format.
