### ISSUE TITLE
$edgehub module Restart  from Azure IoT Hub throwing error

### ISSUE THREAD

**Issue by mjamshad** [Azure/iotedge#5068]
## Expected Behavior
$edgehub module should restart wihtout an error

## Current Behavior
Sometimes $edgehub module goes to offline and showing error status after restart.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a nested edge hierarchy
2. Restart Parent $edge module
3.After some time, it will show error and the $edgehub will be in offline.

## Context (Environment)
dev
### Output of `iotedge check`
Getting connection error in all the ports
<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS - Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by huguesBouvier** [comment]
I am looking into the issue. While trying to reproduce, I have some additional questions:
“After some time, it will show error and the $edgehub will be in offline.”
1.	What is the order of time? about a few hours/days or weeks?
2.	Could you give details about the error?
3.	What do you mean “offline? Do you get connection refused with upstream? Or connection denied? What is the error message? 

Toubleshooting steps:
- Could you please run "sudo iotedge check" on both parent and child and give us the result?
- Could create a support bundle on parent and child: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11 and give it to us?

Thank you!



Note: There is a simple reason why iotedge could keep restarting and I have seen it many times. Check that the device ID in the parent and child are different. If device ID is the same, parent and child will keep restarting.
Check /etc/aziot/config.toml
This should be different: connection_string = "HostName=huguestest.azure-devices.net;DeviceId=huguesParent;SharedAccessKey=….
Or this device_id = “…” depending on your config.

**Comment by huguesBouvier** [comment]
Closing, will re-open with the logs.
