### ISSUE TITLE
Simulator device in the child device got crashed while restarting parent device

### ISSUE THREAD

**Issue by mjamshad** [Azure/iotedge#5069]
## Expected Behavior
Tell us what should happen
Simulator device in the child device shoild continue sending messages even after restarting parent device
## Current Behavior
Some times the simulator device installed in the child device is crashing and starting from the begining while restarting the parent device
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Setup two level nested edge scenario from the Azure Documentaion
2. Install Simulator device in the child device
3.Restart Parent device
4. See the logs and message number in the simulator device

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]:  Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

05/17/2021 05:40:50> Sending message: 109, Body:
[{"machine":{"temperature":71.12895409570962,"pressure":6.710893504574513},"ambient":{"
temperature":21.33275947898289,"humidity":25},"timeCreated":"2021-05-
17T05:40:50.0525603Z"}]
05/17/2021 05:41:15> Sending message: 110, Body:
[{"machine":{"temperature":71.5521641855837,"pressure":6.759107312281688},"ambient":{"t
emperature":20.674326223868096,"humidity":26},"timeCreated":"2021-05-
17T05:41:15.0554012Z"}]
05/17/2021 05:41:40> Sending message: 111, Body:
[{"machine":{"temperature":72.2373349256755,"pressure":6.837164738368094},"ambient":{"t
emperature":20.81842949721889,"humidity":25},"timeCreated":"2021-05-
17T05:41:40.0598377Z"}]
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was
canceled.)
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
 --- End of inner exception stack trace ---
 at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at System.Threading.Tasks.Task`1.get_Result()
 at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edgemodules/SimulatedTemperatureSensor/src/Program.cs:line 48
[2021-05-17 05:41:53 : Starting Module
SimulatedTemperatureSensor Main() started.
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that
should be sent (set it to -1 to send unlimited messages).
[Information]: Trying to initialize module client using transport type [Amqp_Tcp_Only].
[Information]: Successfully initialized module client of transport type [Amqp_Tcp_Only].
05/17/2021 05:41:54> Sending message: 1, Body:
[{"machine":{"temperature":20.78604795110228,"pressure":0.975625715948361},"ambient":{"
temperature":20.942596210372912,"humidity":24},"timeCreated":"2021-05-
17T05:41:54.6580991Z"}]
05/17/2021 05:42:19> Sending message: 2, Body:
[{"machine":{"temperature":20.99240564135481,"pressure":0.999134819901181},"ambient":{"
temperature":21.02704226389855,"humidity":24},"timeCreated":"2021-05-
17T05:42:19.712835Z"}]
<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by huguesBouvier** [comment]
Bundling with #5068 https://github.com/Azure/iotedge/issues/5068

**Comment by huguesBouvier** [comment]
Closing, will re-open with the logs.
