### ISSUE TITLE
Child is not updating the status when it is in offline

### ISSUE THREAD

**Issue by mjamshad** [Azure/iotedge#5070]
## Expected Behavior
In nested edge scenario, the child edge device is not updating the status when parent go offline

## Current Behavior
In the nested edge scenario, if we restart the parent edge device, the child will show as 'running' but if we click the status it will show as offline. The status of child edge device is not changing to 'error' or offline. The device status also showing as 200OK instead of 406
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Implement two level nested edge from azure documentation
2. Stop parent edge device(switch off the VM associated with the parent device)
3. Check the child edge device and child modules status 

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]:  1.2
* Edge Agent [image tag (e.g. 1.0.0)]:  1.2
* Edge Hub [image tag (e.g. 1.0.0)]:  1.2
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by huguesBouvier** [comment]
This behavior is expected. The runtime response shows the last known status:
![image](https://user-images.githubusercontent.com/33438817/121602427-22ef9400-c9fc-11eb-8a6e-1c00f74aecbd.png)

When the parent goes offline, the child is unable to communicate with IoTHub, hence its last status is "Ok".
That would also happen for the parent, depending how you stop it. But if you just pull the ethernet cord of the Raspberry PI, the status would similarly be "200 -Ok".
