### ISSUE TITLE
$edgehub module is showing status as 'NA" after some days

### ISSUE THREAD

**Issue by mjamshad** [Azure/iotedge#5071]
## Expected Behavior
Tell us what should happen
$edgehub module status should not change to NA aftersome time
## Current Behavior
Tell us what happens instead of the expected behavior
Created nested edge setup from the azure documentation, after a month, the $edgehub module in the parent module is showing the status as 'NA' 
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create Nested edge setup from the documentation
2. Check the status of the modules after a month

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by huguesBouvier** [comment]
Closing, will re-open with the logs.
