### ISSUE TITLE
Not able to remove modules from the IoT edge device

### ISSUE THREAD

**Issue by mjamshad** [Azure/iotedge#5072]
## Expected Behavior
Tell us what should happen
Created Two layer Nested edge setup from azure Documentation. After installing a module, the same can be removable from the device
## Current Behavior
Tell us what happens instead of the expected behavior
Created Two layer Nested edge setup from azure Documentation. After installing a module, the same is not able to remove from the edge device. The status of the module is not changing to ‘NA’ even after deleting the module. Due to this, module is not able to remove from the page and status is shown as Error.
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Setup Two layer Nested edge
2.Install a module
3.Delete the module
4.Check the status of the module

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by huguesBouvier** [comment]
This could also be linked to: https://github.com/Azure/iotedge/issues/5068.
If the connectivity is lost, because of crash or anything then iotedge may fail to get a new deployment file from IoTHub
Let's fix https://github.com/Azure/iotedge/issues/5068 first.

**Comment by huguesBouvier** [comment]
Closing, will re-open with the logs.
