### ISSUE TITLE
[ERROR]: Push docker image failed: unauthorized: authentication required

### ISSUE THREAD

**Issue by ytzh101** [Azure/iotedge#5078]
Hi there,
I am facing a clue-less error when "Build and Push IoT Edge Modules" in Visual Studio 2019. 
The local build is successful. 
When "Build and Push", the IoT Hub output shows:
 `DOCKER_HOST: `
`DOCKER_TLS_VERIFY: `
`DOCKER_CERT_PATH: `
`Additional Env Variables: `
`------ Build and Push IoT Edge Modules started: Platform: Linux Amd64, Configuration: Debug ------`
`The deployment manifest is generated at C:\Users\*\IotEdge\config\deployment.amd64.debug.json`
`........`
`docker push d1mdegencr521.azurecr.io/scmmodule:0.0.1-connectivity-amd64.debug`
`The push refers to repository [*.azurecr.io/s*module]`
`609e1722a2f4: Preparing
c0316d7cc878: Preparing
22b72e69e96c: Preparing
6c66f786940d: Preparing
b6bb9772d628: Preparing
f5b36704f50e: Preparing
82d662984338: Preparing
4e0c8e5862b8: Preparing
02c055ef67f5: Preparing`
`f5b36704f50e: Waiting
02c055ef67f5: Waiting
82d662984338: Waiting
4e0c8e5862b8: Waiting`
`unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
[ERROR]: Push docker image failed: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.`

I also tried to "Set Modules" on my IoT Edge devices in the Azure portal, since the repository is in the Container registry.
The error message is "**This device is offline.**"

When I run $iotedge list in Eflow-VM, I only have 
`$ iotedge list     `                                                                                                    
                     `NAME             STATUS           DESCRIPTION      CONFIG         `                     
                                                                                                    ` edgeAgent        running          Up 24 minutes    mcr.microsoft.com/azureiotedge-agent:1.1         `                                                                       
                 `edgeHub          running          Up 24 minutes    mcr.microsoft.com/azureiotedge-hub:1.1  `

**Comment by pmzara** [comment]
@ytzh101 Did you follow the step - Build and push images - on this link https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module?view=iotedge-2020-11?
