### ISSUE TITLE
aziot-edged not working after restart

### ISSUE THREAD

**Issue by karakal** [Azure/iotedge#5083]
## Expected Behavior
After the restart of the device iotedge should work.

## Current Behavior
After restart of device I have the following error message in my log:
`[WARN] - The daemon could not start up successfully: Could not retrieve device information
[WARN] -         caused by: HTTP response error: [400 Bad Request] {"message":"device ide>
[WARN] - Retrying getting edge device provisioning information.
[INFO] - Obtaining edge device provisioning data...
[WARN] - The daemon could not start up successfully: Could not retrieve device information
[WARN] -         caused by: HTTP response error: [400 Bad Request] {"message":"device ide>
[WARN] - Retrying getting edge device provisioning information.
[INFO] - Obtaining edge device provisioning data...
[WARN] - The daemon could not start up successfully: Could not retrieve device information
[WARN] -         caused by: HTTP response error: [400 Bad Request] {"message":"device ide>`

Check shows everything correct:
`Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Permission denied /var/run/iotedge/mgmt.sock)
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
34 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
`

I always need to issue
`iotedge config apply`

Then the problem disappears magically
`systemd[1]: Started Azure IoT Edge daemon.
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Starting Azure IoT Edge Module Runtime
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Version - 1.2.1
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Initializing the module runtime...
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Initializing module runtime...
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Using runtime network id azure-iot-edge
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Successfully initialized module runtime
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Finished initializing the module runtime.
aziot-edged[4355]: 2021-06-04T08:29:43Z [INFO] - Obtaining edge device provisioning data...
`

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install Ubuntu 20.04 on a Raspberry Pi4
2. Install aziot-edge according to documentation
3. copy config.toml.template, configure accordingly (DPS/Symetric Keys)
4. iotedge config apply
5. restart device

## Context (Environment)
OS: Ubuntu 20.04 64Bit
Hardware: Raspberry Pi4 8GB

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Permission denied /var/run/iotedge/mgmt.sock)
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
34 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubtunu 20.04
* Architecture [e.g. amd64, arm32, arm64]: arm64v8
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.1
* Edge Agent [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-agent:1.1.1
* Edge Hub [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-hub:1.1.1
* Docker/Moby [run `docker version`]: 20.10.6+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by pmzara** [comment]
@karakal Could you please provide the upload support bundle?

**Comment by karakal** [comment]
> 
> 
> @karakal Could you please provide the upload support bundle?

The comand support-bundle stalls at writing the logs:
Writing all logs since 2021-06-21 10:11:14 UTC (local time 2021-06-21 10:11:14 +00:00)

What should I too?

**Comment by thecyrusdh** [comment]
Is there a solution to this issue?

**Comment by thecyrusdh** [comment]
@pmzara , I have the same issue with iotedge 1.2.1, is it found a solution?
Thanks

**Comment by kpm-at-hfi** [comment]
@pmzara Was this closed because there is a solution? If yes, can you share the solution here?

**Comment by emibcn** [comment]
@pmzara Any news on this?
