### ISSUE TITLE
The device reprovisioning operation failed (TPM) after upgrading to Iotedge 1.2

### ISSUE THREAD

**Issue by mksp2016** [Azure/iotedge#5088]
We are trying to upgrade IotEdge device to IoT Edge 1.2. 
This device is already running with IoT Edge 1.1 + TPM. 

We are getting below errors while trying to upgrade, 
 
Here is what we have performed on the device:
•	Installed IoT Edge 1.2
•	Imported existing configuration and applied successfully. 
•	Now running iotedge system status giving error. 
 
**root@user:~# sudo iotedge system status**
System services:
    aziot-edged             Down - activating 
    aziot-identityd         Running
    aziot-keyd              Ready
    aziot-certd             Ready
    aziot-tpmd              Running

aziot-edged is in a bad state because:
aziot-edged.service: Down - activating : Printing the last 10 log lines.
-- Logs begin at Fri 2021-02-19 13:31:40 PST, end at Mon 2021-05-24 13:26:58 PDT. --
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [INFO] - Initializing the module runtime...
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [INFO] - Initializing module runtime...
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [INFO] - Using runtime network id azure-iot-edge
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [INFO] - Successfully initialized module runtime
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [INFO] - Finished initializing the module runtime.
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [INFO] - Obtaining edge device provisioning data...
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [ERR!] - The reprovisioning operation failed
May 24 13:26:56 user aziot-edged[6128]: 2021-05-24T20:26:56Z [ERR!] -         caused by: HTTP response error: [404 Not Found] {"message":"DPS client error\ncaused by: internal error"}
May 24 13:26:56 user systemd[1]: aziot-edged.service: Main process exited, code=exited, status=1/FAILURE
May 24 13:26:56 user systemd[1]: aziot-edged.service: Failed with result 'exit-code'.

## Expected Behavior
Device should auto re-provision using TPM

## Current Behavior
Tell us what happens instead of the expected behavior

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Device which is running with IoT Edge 1.1 + TPM 
2. Installed IoT Edge 1.2
3. Imported existing configuration and applied successfully. 
4.Now running iotedge system status giving error. (mentioned above) 

## Context (Environment)
 Industrial PC running Ubuntu 18.04.
### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS - Ubuntu 18.04
* Architecture - amd64
* Container OS - Linux containers

### Runtime Versions
* aziot-edged [runtime 1.2]: 

## Logs

**root@user:~# iotedge system logs**
-- Logs begin at Mon 2021-02-22 14:58:47 PST, end at Mon 2021-05-24 13:39:45 PDT. --
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [aziot_dps_client_async] DPS response status 401
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [aziot_dps_client_async] DPS response headers{"date": "Mon, 24 May 2021 20:38:27 GMT", "content-type": "application/json; charset=utf-8", "transfer-encoding": "chunked", "x-ms-request-id": "44f8cf87-cfc3-4127-b6d1-edc1742df298", "strict-transport-security": "max-age=31536000; includeSubDomains"}
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::client::pool] pooling idle connection for ("https", global.azure-devices-provisioning.net)
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::client::pool] reuse idle connection for ("http", tpmd.sock)
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::io] flushed 1402 bytes
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (1274 bytes)
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [INFO] - <-- POST /import_auth_key?api-version=2020-09-01 {"content-type": "application/json", "host": "tpmd.sock", "content-length": "1274"}
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [ERR!] - !!! internal error
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [ERR!] - !!! caused by: could not import auth key
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [ERR!] - !!! caused by: TPM API failure occurred: 341
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [INFO] - --> 500 {"content-type": "application/json"}
May 24 13:38:27 user aziot-tpmd[22737]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::io] flushed 155 bytes
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (28 bytes)
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::client::pool] pooling idle connection for ("http", tpmd.sock)
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [INFO] - !!! DPS client error
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [INFO] - !!! caused by: internal error
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [INFO] - --> 404 {"content-type": "application/json"}
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::io] flushed 172 bytes
May 24 13:38:27 user aziot-identityd[22720]: 2021-05-24T20:38:27Z [DBUG] - [hyper::proto::h1::conn] read eof
May 24 13:38:27 user aziot-edged[16017]: 2021-05-24T20:38:27Z [ERR!] - The reprovisioning operation failed
May 24 13:38:27 user aziot-edged[16017]: 2021-05-24T20:38:27Z [ERR!] -         caused by: HTTP response error: [404 Not Found] {"message":"DPS client error\ncaused by: internal error"}
May 24 13:38:27 user systemd[1]: aziot-edged.service: Main process exited, code=exited, status=1/FAILURE
May 24 13:38:27 user systemd[1]: aziot-edged.service: Failed with result 'exit-code'.
May 24 13:38:32 user systemd[1]: aziot-edged.service: Service hold-off time over, scheduling restart.
May 24 13:38:32 user systemd[1]: aziot-edged.service: Scheduled restart job, restart counter is at 543.
May 24 13:38:32 user systemd[1]: Stopped Azure IoT Edge daemon.
May 24 13:38:32 user systemd[1]: Started Azure IoT Edge daemon.
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Starting Azure IoT Edge Module Runtime
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Version - 1.2.0
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Initializing the module runtime...
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Initializing module runtime...
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Using runtime network id azure-iot-edge
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Successfully initialized module runtime
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Finished initializing the module runtime.
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [INFO] - Obtaining edge device provisioning data...
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (16 bytes)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [INFO] - <-- POST /identities/device/reprovision?api-version=2020-09-01 {"content-type": "application/json", "host": "2f72756e2f617a696f742f*REMOVED*79642e736f636b:0", "content-length": "16"}
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [INFO] - Provisioning starting. Reason: Api
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::pool] reuse idle connection for ("http", tpmd.sock)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] flushed 123 bytes
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (848 bytes)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::pool] pooling idle connection for ("http", tpmd.sock)
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (2 bytes)
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [INFO] - <-- GET /get_tpm_keys?api-version=2020-09-01 {"content-type": "application/json", "host": "tpmd.sock", "content-length": "2"}
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [INFO] - --> 200 {"content-type": "application/json"}
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] flushed 957 bytes
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [aziot_dps_client_async] DPS request Request { method: PUT, uri: https://global.azure-devices-provisioning.net/0ne0****3D4/registrations/doepqkyodd45zxigsnpadnitsq27oyhvvvzps7ih37thvwl3gkga/register?api-version=2018-11-01, version: HTTP/1.1, headers: {"content-type": "application/json"}, body: Body(Full(b"{\"registrationId\":\"doep*REMOVED*snpadnitsq27oyhvvvzps7ih37thvwl3gkga\",\"tpm\":{\"endorsementKey\":\"AToAAQALAAM*REMOVED*eGt0OsHctr5HEWQxQlU/Gaq/0PfSPKKTgVIAKSAjIB7*REMOVED*npQ8GE5W/22ASOFr/gfVlBh+/lzOExTaZZcrjzH+VUHGvTNSSarL4o*REMOVED*elRGtKnFkIR+kfBw==\",\"storageRootKey\":\"ARoAAQAL*REMOVED*i7NvJf7VaJ6tycoTnubgTF77rELAJ7GW8OcCRfsbdU=\"}}")) }
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::connect::dns] resolving host="global.azure-devices-provisioning.net"
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::connect::http] connecting to 52.151.6.77:443
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::connect::http] connected to 52.151.6.77:443
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] flushed 1151 bytes
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] parsed 5 headers
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body is chunked encoding
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::decode] incoming chunked header: 0x567 (1383 bytes)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [aziot_dps_client_async] DPS response status 401
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [aziot_dps_client_async] DPS response headers{"date": "Mon, 24 May 2021 20:38:32 GMT", "content-type": "application/json; charset=utf-8", "transfer-encoding": "chunked", "x-ms-request-id": "8b517947-b5ca-4b02-8ca3-3a0ce600e0b5", "strict-transport-security": "max-age=31536000; includeSubDomains"}
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::pool] pooling idle connection for ("https", global.azure-devices-provisioning.net)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::pool] reuse idle connection for ("http", tpmd.sock)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] flushed 1402 bytes
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (1274 bytes)
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [INFO] - <-- POST /import_auth_key?api-version=2020-09-01 {"content-type": "application/json", "host": "tpmd.sock", "content-length": "1274"}
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [ERR!] - !!! internal error
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [ERR!] - !!! caused by: could not import auth key
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [ERR!] - !!! caused by: TPM API failure occurred: 341
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [INFO] - --> 500 {"content-type": "application/json"}
May 24 13:38:32 user aziot-tpmd[22737]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] flushed 155 bytes
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (28 bytes)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::client::pool] pooling idle connection for ("http", tpmd.sock)
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [INFO] - !!! DPS client error
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [INFO] - !!! caused by: internal error
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [INFO] - --> 404 {"content-type": "application/json"}
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::io] flushed 172 bytes
May 24 13:38:32 user aziot-identityd[22720]: 2021-05-24T20:38:32Z [DBUG] - [hyper::proto::h1::conn] read eof
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [ERR!] - The reprovisioning operation failed
May 24 13:38:32 user aziot-edged[16096]: 2021-05-24T20:38:32Z [ERR!] -         caused by: HTTP response error: [404 Not Found] {"message":"DPS client error\ncaused by: internal error"}
May 24 13:38:32 user systemd[1]: aziot-edged.service: Main process exited, code=exited, status=1/FAILURE
May 24 13:38:32 user systemd[1]: aziot-edged.service: Failed with result 'exit-code'.
May 24 13:38:38 user systemd[1]: aziot-edged.service: Service hold-off time over, scheduling restart.

**journalctl -u aziot-tpmd**
 
-- Logs begin at Fri 2021-02-26 13:30:01 PST, end at Thu 2021-06-03 14:33:20 PDT. --
May 07 13:14:30 user systemd[1]: Started Azure IoT TPM Service.
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [INFO] - Starting service...
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [INFO] - Version - 1.2.0
**May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [ERR!] - service encountered an error
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [ERR!] - caused by: internal error
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [ERR!] - caused by: could not initialize TPM
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [ERR!] - caused by: TPM API returned an invalid null response
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [ERR!] -    0: <unknown>
May 07 13:14:30 user aziot-tpmd[26234]:    1: <unknown>**
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [INFO] (/tmp/aziot-identity-service-1.2.0/tpm/aziot-tpm-sys/azure-iot-hsm-c/src/hsm_log.c:log_init:22) Initialized logging
May 07 13:14:30 user aziot-tpmd[26234]: Error: Time:Fri May  7 13:14:30 2021 File:/tmp/aziot-identity-service-1.2.0/tpm/aziot-tpm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_usermode_resmg
May 07 13:14:30 user aziot-tpmd[26234]: Error: Time:Fri May  7 13:14:30 2021 File:/tmp/aziot-identity-service-1.2.0/tpm/aziot-tpm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_comm_linux.c Func:tpm_comm_create Li
May 07 13:14:30 user aziot-tpmd[26234]: Error: Time:Fri May  7 13:14:30 2021 File:/tmp/aziot-identity-service-1.2.0/tpm/aziot-tpm-sys/azure-iot-hsm-c/deps/utpm/src/tpm_codec.c Func:Initialize_TPM_Codec Li
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [ERR!] (/tmp/aziot-identity-service-1.2.0/tpm/aziot-tpm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:initialize_tpm_device:271) Failure init
May 07 13:14:30 user aziot-tpmd[26234]: 2021-05-07T20:14:30Z [ERR!] (/tmp/aziot-identity-service-1.2.0/tpm/aziot-tpm-sys/azure-iot-hsm-c/src/hsm_client_tpm_device.c:hsm_client_tpm_create:304) Failure init
May 07 13:14:30 user systemd[1]: aziot-tpmd.service: Main process exited, code=exited, status=1/FAILURE
May 07 13:14:30 user systemd[1]: aziot-tpmd.service: Failed with result 'exit-code'.
May 07 13:14:35 user systemd[1]: aziot-tpmd.service: Service hold-off time over, scheduling restart.
May 07 13:14:35 user systemd[1]: aziot-tpmd.service: Scheduled restart job, restart counter is at 1.
May 07 13:14:35 user systemd[1]: Stopped Azure IoT TPM Service.
May 07 13:14:35 user systemd[1]: Started Azure IoT TPM Service.

**Comment by micahl** [comment]
@mksp2016 this should be fixed as of release [1.2.3](https://github.com/Azure/azure-iotedge/releases/tag/1.2.3).  Please verify and reopen if it's still not working.
