### ISSUE TITLE
IotEdge on CentOS 7: works but fail after reboot

### ISSUE THREAD

**Issue by gimmi** [Azure/iotedge#5093]
I have installed IotEdge 1.2 on a CentOS 7 machine as described [HERE](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11), diverging as needed to accomodate differences between Ubuntu and CentOS. The device is configured to be used as "Nested Edge" device. The last step of the installation is this command:

```
iotedge config apply
```

After which the installation went smooth and everything seems to be working fine. The trouble start when i do a reboot of the machine...

## Expected Behavior

Iotedge should start working normal after reboot

## Current Behavior

IotEdge is not working, the following command fail:

```
iotedge list
A module runtime error occurred
    caused by: Could not list modules
    caused by: error trying to connect: Connection refused (os error 111)
```

To make thing work again after the reboot, I have to manually issue this command:

```
iotedge system restart
```

The workaround for this issue seems to be to manually enable all `aziot-*` daemons. This is certainly feasible, but it is not clear to me if this operation is appropriate, or if the command `iotedge config apply` is suppose to do that, and is not working for some reason. 

## Steps to Reproduce

1. Install IotEdge 1.2 on a CentOS 7 box, configuring it as nested edge
2. Finalize configuration with `iotedge config apply`
3. Verify that iotedge is working properly with `iotedge list`
4. Rebbot the OS
3. Verify that iotedge is not working anymore with `iotedge list`

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ host time is close to reference time - Warning
    Could not query NTP server
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
^C
```

</details>

### Device Information
* Host OS: CentOS 7
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged: iotedge 1.2.0
* Edge Agent: 1.2.0
* Edge Hub: 1.2.0
* Moby: 20.10.6+azure

**Comment by arsing** [comment]
As being discussed in the mail thread, the socket units for the services are not being enabled when installing the package because we aren't packaging a vendor preset file. This has always been a bug but is only being noticed now because there is more than one systemd unit that needs to be enabled.

**Comment by gimmi** [comment]
Good to know, so am I expected to enable those services manually?

```
systemctl enable aziot-edged
systemctl enable aziot-identityd
systemctl enable aziot-keyd
systemctl enable aziot-certd
```

**Comment by arsing** [comment]
No. The socket units need to be enabled, not the service units.

```sh
systemctl enable aziot-edged aziot-{key,cert,identity,tpm}d.socket
```

As I said in the mail thread, we're not doing anything different for the socket units vs the iotedge service in 1.1 and the aziot-edged service in 1.2. All this time we've been assuming the iotedge service was being automatically enabled by the package postinstall, but presumably you and other CentOS users have been manually enabling it assuming that's how it's supposed to be. So this disconnect has only come to light in 1.2 since we now have multiple units that ought to have been enabled by the package postinstall.

**Comment by arsing** [comment]
>I also have to execute those commands:

You can do it in one line like I wrote, but yes.

>Then a future release will fix that and make the mentioned command redundant, right?

Yes.

**Comment by gimmi** [comment]
Confirm workaround working on 3 installations

**Comment by gordonwang0** [comment]
#5099 is the fix for this. It's been merged.
