### ISSUE TITLE
No matching MQTT topic edgeHub

### ISSUE THREAD

**Issue by jackt-moran** [Azure/iotedge#5095]
I've been troubleshooting a stability issue, which is possibly not related to this repository, and turned the debug logs on for edgeHub. In the edgeHub logs I see many of the following messages, which are referring to a leaf device I have connected to the gateway:

```
<7> 2021-06-09 22:22:05.902 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Routing.RoutingEdgeHub] - Received message from MTC01_DATAREADER
<7> 2021-06-09 22:22:05.902 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessageAddressConverter] - Message address devices/MTC01_DATAREADER/messages/events/ matches more than one topic. Picking first matching topic.
<7> 2021-06-09 22:22:05.902 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Processing message for device Id MTC01_DATAREADER
```

Additionally, I have multiple routes (3 at this time) defined to route leaf device messages to different IoT Edge modules.

Do these logs mean the leaf device messages are only getting sent to 1 of the 3 routes, as they suggest?

## Expected Behavior
If the answer to the above question is yes, then I would expect outputs (from both modules and leaf devices) reused in different routes to properly "duplicate"  the data stream to each corresponding input.

## Current Behavior
It depends on the answer to my question above.

## Steps to Reproduce
(if it's a bug)
1. Define a deployment template with multiple routes from leaf devices to two different inputs, e.g.:
```
"LeafToA": {
"route": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint(\"/modules/A/inputs/test\")",
"priority": 0,
"timeToLiveSecs": 60
 },
"LeafToB": {
"route": "FROM /messages/* WHERE NOT IS_DEFINED($connectionModuleId) INTO BrokeredEndpoint(\"/modules/B/inputs/test\")",
"priority": 1,
"timeToLiveSecs": 60
},
```
2. Setup environment to correspond to the above routing and ensure leaf device is uploading data periodically.
3. Turn on debug edgeHub logs and observe for long enough to see the logs such as those pasted above.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: certificates - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

23 check(s) succeeded.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.3
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1.3
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1.3
* Docker/Moby [run `docker version`]: 20.10.6+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

If more than the above logs are required to answer my question I would be happy to provide, please let me know.

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information

Because it seems possibly relevant, I am also seeing these edgeHub logs on edgeHub startup:
```
<6> 2021-06-09 22:44:30.556 +00:00 [INF] [EdgeHub] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<3> 2021-06-09 22:44:30.822 +00:00 [ERR] [Microsoft.Azure.Devices.Edge.Hub.Service.Modules.RoutingModule] - Error creating RocksDB store. Falling back to in-memory store.
RocksDbSharp.RocksDbException: Invalid argument: You have to open all column families. Column families not opened: MTC01/RowCounter/telemetry_Pri1
   at RocksDbSharp.Native.rocksdb_open_column_families(IntPtr options, String name, Int32 num_column_families, String[] column_family_names, IntPtr[] column_family_options, IntPtr[] column_family_handles)
   at RocksDbSharp.RocksDb.Open(DbOptions options, String path, ColumnFamilies columnFamilies)
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.RocksDbWrapper.Create(IRocksDbOptionsProvider optionsProvider, String path, IEnumerable`1 partitionsList) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbWrapper.cs:line 42
   at Microsoft.Azure.Devices.Edge.Storage.RocksDb.DbStoreProvider.Create(IRocksDbOptionsProvider optionsProvider, String path, IEnumerable`1 partitionsList) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/DbStoreProvider.cs:line 33
   at Microsoft.Azure.Devices.Edge.Hub.Service.Modules.CommonModule.<Load>b__24_7(IComponentContext c) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs:line 187
```

FYI, I have previously had multiple leaf device routes defined without any issues.

Thanks!

**Comment by jackt-moran** [comment]
It appears the issue I was seeing was due to the RocksDB issue.

The issue was essentially that edgeHub appeared unable to keep up with my data volume. Does that make sense given edgeHub reverted to the in-memory store?

I rectified the issue by deleting /etc/iotedge/storage/edgeHub, which is obviously not ideal if there is a backlog of valuable data (in my case, this is a staging device, so that wasn't the case). Is there a way to "gracefully" rectify the above RocksDB issue without significant data loss?

**Comment by pmzara** [comment]
@jackt-mora
Thanks for the report. We are investigating.

**Comment by varunpuranik** [comment]
@jackt-moran - From the error message above, it seems like the DB had additional column families that are not used by EdgeHub. Can you confirm if the RocksDB store was on a volume mount, and if it was used by some other application? 
If so, then something like that is not currently supported.
