### ISSUE TITLE
[monitor-workbook] IoT Edge device details - Messaging - Displayed metrics are wrong if multiple routes between the same two modules exist

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#5102]
The KQL query

```
let minPeriod = 5m;
let startTime = {timeRange:start};
let endTime = {timeRange:end};
let endp = iff('{pid}' != \"\", '{pid}', '{id}');
let x = trim_end(@\"[^+]+\", '{id}');
let moduleid = substring(x,0, strlen(x)-1);
//let moduleid = \"Sender2\";\nInsightsMetrics
| where Name == \"edgehub_messages_sent_total\"
| where Tags contains endp
| extend dimensions=parse_json(Tags)
| extend device = tostring(dimensions.edge_device)
| where device  == '{SelectedDevice}'
| extend target = trim_start(@\"[^/]+/\", extractjson(\"$.to\", tostring(dimensions), typeof(string)))
//| extend source = trim_start(@\"[^/]+/\", tostring(dimensions.from))
| extend source = iff(tostring(dimensions.from) contains '{SelectedDevice}', trim_start(@\"[^/]+/\", tostring(dimensions.from)), tostring(dimensions.from))
| where source == moduleid
| extend messages = toint(Val)
| order by TimeGenerated
| serialize | extend nextCount = next(messages, 1) 
| extend diff = iff((messages - nextCount) >= 0, messages - nextCount, iff(TimeGenerated - startTime > 2*minPeriod, messages, 0))
| project TimeGenerated, diff;
```

and similar queries in the workbook just don't take into account that multiple routes between two modules might exists. This gets obvious if you remove the last project statement and take a look at the dimensions column - here you would multiple buckets with different routes for one timestamp.

As I think the problem is understandable and reproducible I kept short, but please don't hesitate to contact me if I was unclear or could provide further information. Thanks for your support.

**Comment by veyalla** [comment]
Thanks for the report. Will take a look.

**Comment by veyalla** [comment]
@alaendle - can you give [this](https://gist.githubusercontent.com/veyalla/a76cd11719a594e00dab37a87ff0167b/raw/aff730d59a837b896aea844c56a811f6ecfbf26a/routetest.workbook) workbook "code" a try and let me know if it works for you?

You can create an empty workbook in the IoT Hub where edge devices are sending metrics data, and paste code in the gallery template:

![CleanShot 2021-07-21 at 20 49 04@2x](https://user-images.githubusercontent.com/22105760/126587752-fea8e213-b6bb-4b87-afb6-158703a0032c.png)

**Comment by veyalla** [comment]
This has been merged in to the public templates!

<img width="649" alt="CleanShot 2021-08-03 at 19 34 24@2x" src="https://user-images.githubusercontent.com/22105760/128112716-0cb5778d-4836-4570-9431-b2b31ed6139b.png">

**Comment by alaendle** [comment]
@veyalla Please excuse my late response - I was travelling - but I want to let you know that the new version shows valid metrics for my use-case. So many thanks, the problem seems to be solved.
