### ISSUE TITLE
UploadSupportBundle gets cancelled after non configurable amount of time

### ISSUE THREAD

**Issue by florianbader** [Azure/iotedge#5103]
When creating a support bundle by calling the direct method UploadSupportBundle it creates a background task which calls the management API in order to create a support bundle and upload to a blob storage. If the creation of the support bundle takes a longer time (because e.g. the device load is higher, the network connection is slow, iot edge check takes longer because the edge device is behind a firewall) the background task is cancelled and there is no support bundle uploaded even though it would be created after a while.
As a user I don't mind if the creation of the support bundle takes longer. The important part is that I get the support bundle in order to see what's wrong with my device.

This is based on #4488, see that issue for logs and context.

## Expected Behavior
The background task cancel timeout is configurable preferably for each background task or at least for all background tasks.

## Current Behavior
The background task is cancelled after a fixed time without being able to configure it.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Put some load on the device (e.g. use the stress tool)
2. Create a minimal setup (temperature sensor module)
3. Invoke the UploadSupportBundle direct method
4. Invoke GetTaskStatus with the correlation id from before until status is cancelled

### Output of `iotedge check`
See #4488

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Debian 9
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.3
* Edge Agent [image tag (e.g. 1.0.0)]:  1.1.3
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1.3
* Docker/Moby [run `docker version`]: 3.0.13+azure

## Logs
See #4488

## Additional Information
I did some research on the code. The [RequestManager](https://github.com/Azure/iotedge/blob/d2c331d605a846911019364a31a7d098e1e2fc45/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/RequestManager.cs#L52) creates a `CancellationTokenSource` with the [RequestTimeoutSecs](https://github.com/Azure/iotedge/blob/5e84d37da1406bcef4143a47c79599c5e671ddeb/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs#L252) from the configuration and passes the token to the [SupportBundleRequestHandler](https://github.com/Azure/iotedge/blob/d2c331d605a846911019364a31a7d098e1e2fc45/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/SupportBundleRequestHandler.cs#L32). The SupportBundleRequestHandler uses that cancellation token to pass it to the [BackgroundTask](https://github.com/Azure/iotedge/blob/d2c331d605a846911019364a31a7d098e1e2fc45/edge-util/src/Microsoft.Azure.Devices.Edge.Util/BackgroundTask.cs#L9) and the [ModuleManagementHttpClient](https://github.com/Azure/iotedge/blob/2b8d49fe2f3fb3d620b4d6ba7535fc7657170d5f/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs#L150).
I don't see if the cancellation token is cancelled because of the `RequestTimeoutSecs` or because there might be a HTTP timeout with the management API but I guess that would be a good place to look. Changing the `RequestTimeoutSecs` to a higher value  still cancels the background task though and is by default already 600 seconds. The cancel happens after about 60 seconds.

**Comment by darobs** [comment]
Hi @florianbader 

Thanks for reporting this and looking into the details.

**Comment by florianbader** [comment]
Hey @darobs any update on this one as it is still a pretty huge problem for us?

**Comment by darobs** [comment]
@florianbader Actively working on this right now. I  haven't found where a 60 second timeout happens.  The `ModuleManagementHttpClient` for this specific request should _not_ have a timeout (the http request uses `CancellationToken.None`).

Am I correct in assuming the desired behavior in this case to to ensure the task will run for the timespan defined by `RequestTimeoutSecs`?

**Comment by florianbader** [comment]
@darobs It would be great to have a separate setting for background task in general e.g. BackgroundTaskTimeoutSecs if possible.

**Comment by darobs** [comment]
I am using 1.2 as a basis, and I put in a forced 5:01 minute wait and am not seeing it cancel after 1 minute - it's waiting the expected 5 minutes.

**Comment by florianbader** [comment]
I can try again with 1.2 later but can you reproduce it if you put load on the system instead of using a forced wait? I tried it on a different device by generating load over the `stress` command line tool on linux for the cpu, memory and disk.

**Comment by darobs** [comment]
Hi @florianbader, here's the situation on this:
- I was able to repro what you were seeing. 
- I made an attempt at fixing the problem, which got time-boxed and I was not able to get this working to my satisfaction. 
- This was added to our backlog, to track this effort.

closing because we are tracking this in our backlog
