### ISSUE TITLE
Error in watchdog when checking for edge runtime...

### ISSUE THREAD

**Issue by mekatrol** [Azure/iotedge#512]
## Reproduce
When following the instructions at: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm the install works but I get a run time error.

### Logs
Running journalctl -u iotedge --no-pager --no-full
shows error:
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Starting Azure IoT Edge Security Daemon
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Version - 1.0.3 (1ccb9b0728cd046f89a7d6eb0af000b3cbd7bb6a)
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Using config file: /etc/iotedge/config.yaml
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Using runtime network id azure-iot-edge
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Initializing the module runtime...
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Finished initializing the module runtime.
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Configuring certificates...
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Finished configuring certificates.
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Initializing hsm...
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Finished initializing hsm.
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Detecting if configuration file has changed...
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Change to configuration file detected.
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Removing all modules...
Nov 01 05:45:13 raspberrypi iotedged[1459]: 2018-11-01T05:45:13Z [INFO] - Finished removing modules.
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Provisioning edge device...
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Manually provisioning device "HomeMaster" in hub "Segmentum.azure-devices.net"
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Finished provisioning edge device.
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Starting management API...
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Listening on fd://iotedge.mgmt.socket/ with 1 thread for management API.
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Starting workload API...
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Listening on fd://iotedge.socket/ with 1 thread for workload API.
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Starting watchdog with 60 second frequency...
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Checking edge runtime status
Nov 01 05:45:18 raspberrypi iotedged[1459]: 2018-11-01T05:45:18Z [INFO] - Creating and starting edge runtime module edgeAgent
Nov 01 05:45:19 raspberrypi iotedged[1459]: 2018-11-01T05:45:19Z [WARN] - Error in watchdog when checking for edge runtime status:
Nov 01 05:45:19 raspberrypi iotedged[1459]: 2018-11-01T05:45:19Z [WARN] - Edge runtime module has not been created in IoT Hub. Please make sure this device is an IoT Edge capable device.
Nov 01 05:46:18 raspberrypi iotedged[1459]: 2018-11-01T05:46:18Z [INFO] - Checking edge runtime status
Nov 01 05:46:18 raspberrypi iotedged[1459]: 2018-11-01T05:46:18Z [INFO] - Creating and starting edge runtime module edgeAgent
Nov 01 05:46:19 raspberrypi iotedged[1459]: 2018-11-01T05:46:19Z [WARN] - Error in watchdog when checking for edge runtime status:
Nov 01 05:46:19 raspberrypi iotedged[1459]: 2018-11-01T05:46:19Z [WARN] - Edge runtime module has not been created in IoT Hub. Please make sure this device is an IoT Edge capable device.
Nov 01 05:47:18 raspberrypi iotedged[1459]: 2018-11-01T05:47:18Z [INFO] - Checking edge runtime status
Nov 01 05:47:18 raspberrypi iotedged[1459]: 2018-11-01T05:47:18Z [INFO] - Creating and starting edge runtime module edgeAgent
Nov 01 05:47:18 raspberrypi iotedged[1459]: 2018-11-01T05:47:18Z [WARN] - Error in watchdog when checking for edge runtime status:
Nov 01 05:47:18 raspberrypi iotedged[1459]: 2018-11-01T05:47:18Z [WARN] - Edge runtime module has not been created in IoT Hub. Please make sure this device is an IoT Edge capable device.
Nov 01 05:48:18 raspberrypi iotedged[1459]: 2018-11-01T05:48:18Z [INFO] - Checking edge runtime status
Nov 01 05:48:18 raspberrypi iotedged[1459]: 2018-11-01T05:48:18Z [INFO] - Creating and starting edge runtime module edgeAgent
Nov 01 05:48:18 raspberrypi iotedged[1459]: 2018-11-01T05:48:18Z [WARN] - Error in watchdog when checking for edge runtime status:

## Device Info:
Raspberry PI 3 Model B+
Raspbian Stretch Lite (have tried both 27-06-2018 and 4.14 09-10-2018 builds)
SD Cards: Verbatim Micro SDXC Class 10 64GB and Micro SDHC Class 10 16GB

## Connection String
Config provisioning details (I will delete this device so don't care that I have posted the details publicly):
provisioning:
  source: "manual"
  device_connection_string: "HostName=Segmentum.azure-devices.net;DeviceId=HomeMaster;SharedAccessKey=xxx"

## Things I have done:

- I have tried deleting and re-adding the device in the IoT hub.
- I have restarted device after configuring.
- Tried both ethernet and WIFI 
- Two different stretch lite versions.
- Two different SD cards

I have tried several times without success, the last attempt I literally flashed the SD card, and followed the instructions in the steps at the URL listed above. No other changes were made to the device other than listed in the instructions.

**Comment by veyalla** [comment]
@mekatrol Can you confirm that you are creating an “IoT Edge” device and not a vanilla IoT device in the Portal? There are different explorers for them...

**Comment by mekatrol** [comment]
Hi Veyalla,

yes, I hang my head in shame. I added the device under 'IoT devices' instead of 'IoT edge' in the IoT hub.

Thanks, for the quick response.

**Comment by lciummo** [comment]
I made the same mistake. It's container time (I mean "module" time).

**Comment by kevin-vitro** [comment]
Could anybody explain when you would use an IoT device that wouldn't be an IoT edge device? Would this be in an instance where a device on your network already was sending messages that could be read by IoT Hub so you weren't deploying any modules or controlling the machine?  Also curious if there are any examples of these types of setups in the real world. Thanks for the information here this helped me resolve my issue! One other question, is there a way to turn a device into an edge device if it was created under IoT devices to begin with?
