### ISSUE TITLE
GetModuleLogs/UploadModuleLogs returns empty payload on Azure Stack Edge device

### ISSUE THREAD

**Issue by gegeo0** [Azure/iotedge#5121]
## Expected Behavior
Tell us what should happen

## Current Behavior
GetModuleLogs and UploadModuleLogs return empty payload

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
az iot hub invoke-module-method --method-name 'GetModuleLogs' -n <name> -d <device> -m '$edgeAgent' --method-payload \
'
    {
        "schemaVersion": "1.0",
        "sasUrl": "sasurl",
        "items": [
            {
                "id": ".*"
            }
        ],
        "contentType": "json"
    }
'
returns an empty payload:

{"status":200,"payload":[{"id":"edgeAgent","payloadBytes":null,"payload":"[]"},{"id":"moduleid","payloadBytes":null,"payload":"[]"},{"id":"edgeHub","payloadBytes":null,"payload":"[]"}]}

## Context (Environment)
ASE T4 machine
Version - 1.1-k8s-beta14.40964814 (167db05eea0df2c806655a69d8e9549c3293a4ce)

### Output of `iotedge check`
iotedge check is not supported on ASE T4

**Comment by veyalla** [comment]
These direct methods are not yet supported on Kubernetes which is what ASE uses. Unfortunately, we don't have timeline for when/if they will be. 

On ASE systems, you should use Azure Monitor for logs.
