### ISSUE TITLE
Installing IoT Edge 1.2 on Ubuntu 18.04 cause an error

### ISSUE THREAD

**Issue by shaeussler** [Azure/iotedge#5124]
## Expected Behavior
The command "sudo apt-get install aziot-edge" should work.

## Current Behavior
The command fails with the following error message:
```
Err:1 https://packages.microsoft.com/ubuntu/18.04/multiarch/prod bionic/main amd64 aziot-identity-service amd64 1.2.0-1
  404  Not Found [IP: 104.214.230.139 443]
Err:2 https://packages.microsoft.com/ubuntu/18.04/multiarch/prod bionic/main amd64 aziot-edge amd64 1.2.1-1
  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/a/aziot-identity-service/aziot-identity-service_1.2.0-1_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool/main/a/aziot-edge/aziot-edge_1.2.1-1_amd64.deb  404  Not Found [IP: 104.214.230.139 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

## Steps to Reproduce
1. Fresh install of Ubuntu 18.04
2. Run the installation preparation from https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11
3. sudo apt-get install aziot-edge

### Device Information
* Host OS Ubuntu 18.04
* Architecture amd64
* Container OS Linux containers,

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Additional Information
The directory https://packages.microsoft.com/ubuntu/18.04/multiarch/prod/pool is missing.

**Comment by bartex** [comment]
Confirming. I have the same issue.

Apart from manual installation fail I also tried using the [deployment template](https://github.com/Azure/iotedge-vm-deploy/tree/1.2.0). It was all good not even a month go.

**Comment by bartex** [comment]
It started to work on my side. I'm able to successfully download the `aziot-edge` package.

**Comment by veyalla** [comment]
packages.microsoft.com was experiencing an outage. It has now been fixed.
