### ISSUE TITLE
Module desired properties updated gets reverted

### ISSUE THREAD

**Issue by xela-95** [Azure/iotedge#5139]
## Expected Behavior
I want to be able to update the values of the desired properties I have defined for my custom module in its module twin, in order to change the configuration of the module on runtime.

## Current Behavior
When I update a desired property value in the module identity twin from Azure IoTHub portal, the module (which has successfully called SetDesiredPropertyUpdateCallbackAsync, receives the new properties but, after some seconds, it receives another event containing the desired property values that I initially defined in the deployment manifest.

## Context (Environment)
I am using an automatic deployment based on tags, even if in this case it targets only one edge device.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

PS C:\Users\TenovaDigital> iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 74 days (at 2021-09-05 15:38:00 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its C:\Windows\Temp\edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its C:\Windows\Temp\edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Windows 10
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Windows

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.1.3 (68e71a5384b14956775241557877497274d0ce7e)
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]:  1.0

### Other info
Related question [here](https://github.com/Azure/azure-iot-sdk-csharp/issues/2037#issue-923988890)
Potential related SO question [here](https://stackoverflow.com/questions/61817920/iotedge-module-twin-update-gets-reverted)

**Comment by dmolokanov** [comment]
Hello! This is expected behavior for automatic deployment. SO [answer](https://stackoverflow.com/a/62041917) mentions the possible way to handle this via [Layered deployment](https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring?view=iotedge-2020-11#layered-deployment)

@veyalla Any additional suggestions?

**Comment by xela-95** [comment]
@dmolokanov ok but I might not use layered deployment... It is correct to say that the correct way to modify the desired property is through a new deployment? Or is there a clever (and faster) way to do that?

**Comment by dmolokanov** [comment]
Correct. Automatic deployment job runs periodically (~5min) and applies deployment for all devices which match tags. If there were some changes which made manually to some devices it overrides those changes making all devices having the same deployment.

**Comment by xela-95** [comment]
Ok thank you @dmolokanov 
And what would be the benefit of using a layered deployment? There the module twin can be changed without a new deployment?

**Comment by veyalla** [comment]
Checkout https://azure.microsoft.com/en-us/blog/new-enhancements-for-azure-iot-edge-automatic-deployments/

**Comment by dmolokanov** [comment]
Closing this issue. Feel free to reopen if more assistance require
