### ISSUE TITLE
Compile security daemon to arrch64 platform

### ISSUE THREAD

**Issue by v-jiq** [Azure/iotedge#516]
I want to run iot-edge to aarch64 platform, but Microsoft currently only support arm32/.armhf . whether I can compile security-daemon to aarch64 platform  by sources code?  if that is effective, whether some detail need to attention.

**Comment by darobs** [comment]
Hello, @v-jiq, 

We have recently pushed in scripts to build the security daemon in the platform in preparation for the platform support, but we have not yet released binaries.  

The setup for our build may be [seen here](https://github.com/Azure/iotedge/tree/master/edgelet/build/linux/docker/cross-compile).  This shows how we build the containers to cross-compile the packages. The scripts we run to utilize the containers are [here](https://github.com/Azure/iotedge/tree/master/edgelet/build/linux), organized by distribution.

If you don't need the specific requirements we have for producing binary packages, the [Rust Cross ](https://github.com/rust-embedded/cross) tool may also work for you.

**Comment by v-jiq** [comment]
when I according to the Dockerfile -- Dockerfile.ubuntu16.04.aarch64-unknown-linux-gnu  build a docker image will occur a error .

 the error log : 
Step 3/15 : COPY apt/cmake.sh /
COPY failed: stat /var/lib/docker/tmp/docker-builder969769958/apt/cmake.sh: no such file or directory

the build cmd:sudo docker build -t ubuntu_aarch64_iotedge:amd64 . 

prompt: no such file or directory

**Comment by myagley** [comment]
I'm going to close this issue for now, but please feel free to reopen if you run into issues with the scripts. Thanks!
