### ISSUE TITLE
IoT Edge check report to update identity services while they are already up to date. 

### ISSUE THREAD

**Issue by algorni** [Azure/iotedge#5183]
Deploying a new IoT Edge 1.2 on a fresh Ubuntu 18.04 following step by step instructions:

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11

checking if everything was ok with the command: 

`sudo iotedge check `

shows a warning asking to update to 1.2.1

![image](https://user-images.githubusercontent.com/45007019/123797728-c7237700-d8e6-11eb-966f-6e1690149fac.png)

checking with 

`sudo iotedge system logs`

it seems clear that I'm running a more updated version of the services:

![image](https://user-images.githubusercontent.com/45007019/123797501-862b6280-d8e6-11eb-8ef4-35b50f9eeb40.png)

## Expected Behavior
No warning rised.

### Device Information
* Host OS: Ubuntu 18.04
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]:  iotedge 1.2.2
* Edge Agent [image tag (e.g. 1.0.0)]:  1.2
* Edge Hub [image tag (e.g. 1.0.0)]:  1.2
* Docker/Moby [run `docker version`]:  

Client:
 Version:           20.10.6+azure
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c28948e3c12dce3d1df60b6f184990618553f
 Built:             Fri Apr  9 17:01:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.6+azure
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd246c3ab53105434eef8ffe997b6fd14dc6
  Built:            Fri Apr  9 22:06:18 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6+azure
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:

**Comment by vipeller** [comment]
@algorni thank you for reporting this, it turned out that we have not updated something. It will be fixed.

**Comment by vipeller** [comment]
The fix is merged, closing this
