### ISSUE TITLE
aziot-identityd Hub client error...unknown protocol

### ISSUE THREAD

**Issue by briand-abl** [Azure/iotedge#5186]
Good afternoon,

I'm seeing a strange error in my system logs and haven't been able to make any traction on solving it. I believe it may be keeping deployments from working on my edge gateway. The setup is a VM running Oracle Linux Server v 8.3 and the environment the VM runs in sits behind our proxy server (proxy.networkname.com) as seen below. We've added two environment variables for the proxy, one for http_proxy and one for https_proxy with the corresponding values. The IP address seen on the next two log lines is correct for the proxy. We are using x.509 certificates (CA signed certs) for authentication. Currently, I'm just using the test certificates generated by the scripts here:  https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11

Here is the snippet from my logs (this error repeats itself periodically):

> Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::proto::h1::io] parsed 3 headers
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::proto::h1::conn] incoming body is content-length (2158 bytes)
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::proto::h1::conn] incoming body completed
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::client::pool] pooling idle connection for ("http", certd.sock)
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::client::connect::dns] resolving host="proxy.networkname.com"
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::client::connect::http] connecting to 10.xxx.xxx.xx:3128
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::client::connect::http] connected to 10.xxx.xxx.xx:3128
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [INFO] - !!! Hub client error
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [INFO] - !!! caused by: error trying to connect: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [INFO] - !!! caused by: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [INFO] - --> 404 {"content-type": "application/json"}
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::proto::h1::io] flushed 555 bytes
Jun 29 17:10:26 iot-edge-dev aziot-edged[872694]: 2021-06-29T21:10:26Z [ERR!] - Internal server error: Could not list identities
Jun 29 17:10:26 iot-edge-dev aziot-edged[872694]:         caused by: HTTP response error: [404 Not Found] {"message":"Hub client error\ncaused by: error trying to connect: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:\ncaused by: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:\ncaused by: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:\ncaused by: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:"}
Jun 29 17:10:26 iot-edge-dev aziot-edged[872694]: 2021-06-29T21:10:26Z [INFO] - [mgmt] - - - [2021-06-29 21:10:26.180884203 UTC] "GET /identities/?api-version=2020-07-07 HTTP/1.1" 500 Internal Server Error 538 "-" "-" auth_id(-)
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::proto::h1::io] parsed 1 headers
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::proto::h1::conn] incoming body is empty
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [INFO] - <-- GET /identities/modules?api-version=2020-09-01&type=aziot {"host": "2f72756e2f617a696f742f6964656e74697479642e736f636b:0"}
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::client::pool] reuse idle connection for ("http", keyd.sock)
Jun 29 17:10:26 iot-edge-dev aziot-identityd[872699]: 2021-06-29T21:10:26Z [DBUG] - [hyper::proto::h1::io] flushed 75 bytes

The edgeAgent module is up and running and seems to be able to communicate with the IoT Hub. I can see it's Runtime Status as "running" on the IoT Hub page for the edge gateway in Azure. The edgeAgent module log has these messages repeating (I did try to make a deployment to that gateway when I saw the edgeAgent was running):

> <6> 2021-06-29 21:16:31.046 +00:00 [INF] - Plan execution started for deployment 2
<6> 2021-06-29 21:16:31.046 +00:00 [INF] - Executing command: "Saving edgeAgent to store"
<6> 2021-06-29 21:16:31.046 +00:00 [INF] - Plan execution ended for deployment 2
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Unable to update EdgeAgent module as the EdgeAgent module identity could not be obtained
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Unable to process module edgeAgent add or update as the module identity could not be obtained
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Unable to process module DbReaderModule add or update as the module identity could not be obtained
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Unable to process module SendModule add or update as the module identity could not be obtained
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Unable to process module CleanupModule add or update as the module identity could not be obtained
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Unable to process module sql add or update as the module identity could not be obtained
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Unable to process module edgeHub add or update as the module identity could not be obtained
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Plan execution started for deployment 2
<6> 2021-06-29 21:16:52.000 +00:00 [INF] - Executing command: "Saving edgeAgent to store"
<6> 2021-06-29 21:16:52.001 +00:00 [INF] - Plan execution ended for deployment 2

Here is the support bundle archive generated by the "iotedge support-bundle" command:
[support_bundle.zip](https://github.com/Azure/iotedge/files/6736706/support_bundle.zip)

I have worked with our network engineers to try to eliminate some possibilities, but they don't see anything that might point to issues with the proxy itself. I'm fairly certain this is an issue with my configuration of the edge gateway server and possibly the proxy.

Any insight you can provide as to why we might be seeing these communication issues would be greatly appreciated. Please let me know if you need any more information. Thank you!

**Comment by vipeller** [comment]
Hi @briand-abl

Sorry for the late answer! It definitely seems like a proxy error. When you created the support bundle, that tries to call different services, and it seems that whenever it calls an https service, then the response it gets back is something different than TLS. If you run 'iotedge check' then probably you will see some  "SSL23_GET_SERVER_HELLO:unknown protocol" or " tls: first record does not look like a TLS handshake" or just simply TLS timeouts. The daemon log also has this problem.
Maybe you can try to call from the host machine e.g. using wget the address 'https://aka.ms/latest-aziot-identity-service', probably you will see similar error.
It is like the proxy intercepts the tls communication and sends back a wrong packet. Can you try these (runnung iotedge check and see the tls related errors and calling an https server from the host machine) and confirm if it works or not?

**Comment by briand-abl** [comment]
Hi @vipeller,
Thank you for your response. We suspected that it was most likely an issue with the configuration of the proxy on the edge gateway, or TLS configuration in the proxy itself. To  that end, our next step will be to disable it and validate that traffic flows from the edge to the IoT Hub. Hopefully it's just a case we haven't had to deal with yet (we mostly have web traffic outbound from our environment). I'll update this issue once we've had a chance to test.

**Comment by briand-abl** [comment]
@viperller,
Sorry for the delay in this update: after our TechOps team removed the proxy server from the line of communications from our test edge gateway, and from the configuration on the gateway itself, the TLS errors disappeared from the system logs. It seems that using our dev environment proxy is the issue, however I'm not sure what configuration specifically was the culprit. Is there documentation for running the edge gateway using x.509 authentication and a proxy server? This is a supported configuration, correct? My apologies if I missed the setup instructions for this configuration somewhere. Thanks for your help!

**Comment by veyalla** [comment]
Glad you were able to find the issue. Adding @kgremban if we have any docs around use of x.509 and proxy.

**Comment by kgremban** [comment]
@veyalla The only information we have specific to X.509 authentication and proxies is this: 

> If the proxy you're attempting to use performs traffic inspection on TLS-secured connections, it's important to note that authentication with X.509 certificates doesn't work. IoT Edge establishes a TLS channel that's encrypted end to end with the provided certificate and key. If that channel is broken for traffic inspection, the proxy can't reestablish the channel with the proper credentials, and IoT Hub and the IoT Hub device provisioning service return an Unauthorized error.
>
>To use a proxy that performs traffic inspection, you must use either shared access signature authentication or have IoT Hub and the IoT Hub device provisioning service added to an allowlist to avoid inspection.

Source: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#working-with-traffic-inspecting-proxies

Besides that, we don't have documentation about how proxy configuration is different based on the authentication type. If there's information that should be added, let me know.

**Comment by veyalla** [comment]
Thanks Kelly, closing.
