### ISSUE TITLE
UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.4:8883 error

### ISSUE THREAD

**Issue by Rollin-stone** [Azure/iotedge#5206]
Hi,

I created an IoT Edge module to send data to IoT Central. 
At each startup, the module stops with the error UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.4:8883 error
After a few minutes, the module restarts and run well.

I don't understand why.

Any Idea ?

iotedge version is 1.1.3

**Comment by vadim-kovalyov** [comment]
@Rollin-stone, thanks for reporting this. It is hard to say without EdgeHub logs, module logs or deployment manifest. Can you provide that please?

**Comment by Rollin-stone** [comment]
Hi Vadim,

Yes of course.

please find the edgeAgent,edgeHub the module logs and the deployment manifest

The pb -  I think - is not relative to a specific module but to a new deployment (I'm using IoT Central to deploy the module with the iotc-poclain-deployement-monitoring.json file).

After systemctl restart iotedge the errors disappears (see logs  edgeAgent-after-restart-log.txt) .. until the next deployment

same pb with different devices

I also have a node js script driven by IoT Central to interact directly with the device  (reboot the device for exemple). 

the error "UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized)":  in the module file is an other pb (other issue)

tell me if you have enough data to analyse this pb

Thanks 


[edgeAgent-after-restart-log.txt](https://github.com/Azure/iotedge/files/6775766/edgeAgent-after-restart-log.txt)

[iotc-poclain-deployement-monitoring-json.txt](https://github.com/Azure/iotedge/files/6775761/iotc-poclain-deployement-monitoring-json.txt)


[edgeAgent-logs.txt](https://github.com/Azure/iotedge/files/6775668/edgeAgent-logs.txt)
[devicemonitor-logs.txt](https://github.com/Azure/iotedge/files/6775656/devicemonitor-logs.txt)
[edgeAgent-logs.txt](https://github.com/Azure/iotedge/files/6775634/edgeAgent-logs.txt)

**Comment by Rollin-stone** [comment]
sorry I I mixed up the issues. 
This one is for the UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized) not for Unable to process module devicemonitor add

**Comment by vadim-kovalyov** [comment]
@Rollin-stone, thanks for providing some logs. Unfortunately I need EdgeHub logs (not EdgeAgent) to investigate UnauthorizedError. As an alternative, you can generate the whole [support bundle](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#gather-debug-information-with-support-bundle-command). 

Also, just a side question, is "test:8883" a valid address of your edgeHub?

I also see that you use 1.0 version. Can you try using the latest released LTS version (1.1.4)?

**Comment by Rollin-stone** [comment]
Hi Vadim,

sorry I forgot to upload it. 
Please find the bundle.zip and edgeHub logs 

Same error with the version 1.1.4


I developed another module to monitor the device (cpu, ram)  and I have the same error  (both are running on the same device)
Bellow the nodesjs  code I'm using . It's the standard code provided with VSC

the Client.fromEnvironnement seems not to be ready and after a few second when iotedge restarts the modules it's ok.


I don't understand your question about test:8883. Where did you get this information ?

Thanks

Have a good day

[edgeHub-log.txt](https://github.com/Azure/iotedge/files/6782733/edgeHub-log.txt)
[support_bundle.zip](https://github.com/Azure/iotedge/files/6782734/support_bundle.zip)


var Transport = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').ModuleClient;
var Message = require('azure-iot-device').Message;

Client.fromEnvironment(Transport, function (err, client) {
  if (err) {
    throw err;
  } else {
    client.on('error', function (err) {
      throw err;
    });


    // connect to the Edge instance
    client.open(function (err) {
      if (err) {
        console.log('Error IoT Hub Module not initialized')
        throw err;
      } else {
        console.log('IoT Hub module client initialized');

**Comment by vadim-kovalyov** [comment]
@Rollin-stone, thanks for providing the edgehub logs and support bundle, that helps.

In the devicemonitor-logs.txt file in your original message I saw the following error and was confused by it. That's why I was asking about `test:8883`, because clearly it meant that the module was trying to connect to a non-existing endpoint `test:8883`.
```
UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): getaddrinfo ENOTFOUND test test:8883 error
```

From the edgehub logs and the support bundle I see the following errors, which simply mean that edgeHub is not yet ready to receive the connections.
```
UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.6:8883 error
```

The error above can happen for any reason, but I was able to reproduce that just by restarting the device, and if test module starts up before the edgeHub, I see that error in the logs.

The Node.js SDK should have handled that case with default retry policy without the need to restart the container. If it indeed does restart the container, then you can tune up the [retry policy](https://github.com/Azure/azure-iot-sdk-node/wiki/Connectivity-and-Retries), or you may want to ask the question in here https://github.com/Azure/azure-iot-sdk-node/issues 

Apart from that, I did not see any problems in the edgeHub logs.
