### ISSUE TITLE
Connection Timed Out in MQTT in Azure Percept DK

### ISSUE THREAD

**Issue by IcaAvanade** [Azure/iotedge#5208]
I have a working end-to-end solution which is currently deployed in a Linux VM which is a custom module as the publisher and web app as subscriber with the IoT edge runtime as the broker. Right now, we are using Azure Percept so I need to deploy my solution to the Azure Percept but currently encountering error: connection timed out. Do I need to have additional/changed setup when deploying in Azure Percept?

Here is the error in the logs of my custom module (publisher):
![image](https://user-images.githubusercontent.com/80704905/124497333-42a48d00-dded-11eb-961a-b058249a216c.png)

Here are the logs of edgeHub:
![image](https://user-images.githubusercontent.com/80704905/124497019-cf9b1680-ddec-11eb-94b9-ad0fbf2ae2b1.png)
![image](https://user-images.githubusercontent.com/80704905/124497032-d590f780-ddec-11eb-8554-f832b2e76f56.png)
![image](https://user-images.githubusercontent.com/80704905/124497045-daee4200-ddec-11eb-9db3-0a1e6412e21e.png)

Here is the deployment manifest:
![image](https://user-images.githubusercontent.com/80704905/124497219-1a1c9300-dded-11eb-9d0a-ea2158dd8726.png)
![image](https://user-images.githubusercontent.com/80704905/124497228-1e48b080-dded-11eb-8bcf-3db397eb8adc.png)
![image](https://user-images.githubusercontent.com/80704905/124497237-2143a100-dded-11eb-94be-c4a0e8ad7803.png)
![image](https://user-images.githubusercontent.com/80704905/124497248-24d72800-dded-11eb-9f7d-3d3148fbbcb9.png)
![image](https://user-images.githubusercontent.com/80704905/124497258-27d21880-dded-11eb-91c6-dcb075f5b08f.png)
![image](https://user-images.githubusercontent.com/80704905/124497271-2b659f80-dded-11eb-990c-6dcd3d56d995.png)
![image](https://user-images.githubusercontent.com/80704905/124497288-30c2ea00-dded-11eb-83b0-dd04c97144a9.png)

**Comment by vadim-kovalyov** [comment]
Hey @IcaAvanade, sorry to hear you having issues running your module on Azure Percept DK. I'm not aware of any special setup for CBL-Mariner (OS for Azure Percept DK). Did you try running `sudo iotedge check` and see if everything is green? I also see that you use old RC version of iotedge. I would recommend to update to the latest version. Also, make sure that you have proper "hostname" set in the config.toml.

**Comment by IcaAvanade** [comment]
May I ask what is the latest RC version of iotedge? 

Here are the logs of sudo iotedge check.
![image](https://user-images.githubusercontent.com/80704905/124712205-95875d00-df31-11eb-8ea6-28d29737d508.png)
![image](https://user-images.githubusercontent.com/80704905/124712233-a041f200-df31-11eb-9953-b8eac2994e69.png)

**Comment by vadim-kovalyov** [comment]
@IcaAvanade, thanks for providing the result of `iotedge check`. Although, the text form is preferable, if possible :) Here is our release page you can follow for latest versions - https://github.com/Azure/azure-iotedge/releases
For checking config.toml, you can try `vim`. I'm not super familiar with CBL-Mariner, so you would need to do some research.

Although it is hard for me to say from the screenshots of the EdgeHub logs, I don't see that the module even reached the EdgeHub. It means there are some connectivity problems between the module and edgehub. I would try to open a shell to the module container and run `telnet` to the edgeHub port 1883 or 8883 to see if the connection can be opened.

**Comment by vadim-kovalyov** [comment]
@IcaAvanade, do you still have this issue? It seems to me that you were able to resolve that and created a follow up issue #5215, so I'm closing this for now.
