### ISSUE TITLE
Compile Security daemon(edgelet) on aarch64 platform

### ISSUE THREAD

**Issue by v-jiq** [Azure/iotedge#521]
### I can't compile a security daemon program which supports aarch64 platform.
    

- **The compiling steps are as follow:**

1. According to script edgelet/build/linux/docker/crosscompile/armbuild/build_arm_toolchain_container.sh generate containers for compiling security daemon.
 
2.  push iotedge sources code to the container and enter edgelet/build/linux directory  to run ./build. However the building process will paused at 140/210 and no update for hours.

- **Details are as the image below:**
![image](https://user-images.githubusercontent.com/39880470/48108568-9813ef00-e27e-11e8-9934-0c40ba6a6b79.png)

**Comment by v-jiq** [comment]
After a few minutes will print below  message:
![image](https://user-images.githubusercontent.com/39880470/48113120-61e16a00-e294-11e8-8d65-f2af0a556b35.png)

**Comment by darobs** [comment]
Hello @v-jiq,

Is this a cross-compile scenario, or are you building on the target?  This looks to me like the compiler is running out of resources - which is common when building on a constrained system.  The C unit tests in the HSM (found in iotedge/edgelet/hsm-sys/azure-iot-hsm-c ) use macros heavily which can consume a large amount of memory.

You may try setting this environment variable: "FORCE_NO_UNITTEST" and running the compile again.  This will tell the build to skip the C unit tests when building the HSM library.

**Comment by v-jiq** [comment]
Thanks for your Suggest @darobs.  
I had successfully cross-compiled the security daemon on aarch64 platform according to your suggest. 

I am currently experiencing another problem. The following log appears when I run the iotedged program on the target board.
![1541748393 1](https://user-images.githubusercontent.com/39880470/48248888-0e0d8700-e434-11e8-9bc9-753a83c911d2.png)

**Why the iotedged process will not  pull the iotedge-agent docker images?**

The target board is running docker.
