### ISSUE TITLE
Azure Percept Device messaging suddenly stops.

### ISSUE THREAD

**Issue by IcaAvanade** [Azure/iotedge#5215]
## Summary
I deployed a custom Python module that sends a message to a custom IoTHub route. The module runs smoothly for one day, sending messages to the IoTHub, which I monitor in VS Code using "Start Monitoring Built-in Endpoint". However, the morning after, we find out that although the module is running smoothly, the endpoint is no longer receiving any messages

## Details
**DEVICE**
I am currently using an Azure Percept camera as an Edge Device.

**MODULE**
I have a Python module that was created using the template offered by Azure IoT Edge. After performing some analysis and checks, it is supposed to send the output as a message to IoT Hub. This analysis is continuously cycled or repeated using a `while True` loop.

The messaging client is instantiated using
`module_client = IoTHubModuleClient.create_from_edge_environment()`

And the message is sent using
`await module_client.send_message_to_output(message_content, "iothub-custom-route")`

This is sandwiched between two lines that tell me when the messaging is supposed to be sent.

```
print("Sending message...")
await module_client.send_message_to_output(message_content, "iothub-custom-route")
print("Message sent!")
```

In summary:
```
module_client = IoTHubModuleClient.create_from_edge_environment()
await module_client.connect()

while True:
    # do analysis-related tasks here
    message_content = analysis_results
    print("Sending message...")
    await module_client.send_message_to_output(message_content, "iothub-custom-route")
    print("Message sent!")
```

**IOT HUB**
The `iothub-custom-route` was created in IoT Hub > Messaging > Message Routing. It has the following settings:
> ![image](https://user-images.githubusercontent.com/80704905/124796727-1111fa00-df84-11eb-93b9-93b2610e1932.png)

This route is the route that is being sent to by the `await module_client.send_message_to_output(message_content, "iothub-custom-route")` line from the custom module.

## Expected Behavior
I watch my Module's logs by navigating to IoT Hub > IoT Edge > DeviceName > ModuleName > Troubleshooting. Upon first deployment, the module logs show that the messages are being sent without a hitch.

```
Sending message...
Message sent!
```

And when I look at my IoT Hub monitoring in VS Code, I see something like
```
[IoTHubMonitor] [10:00:59 PM] MEssage received from [azureperceptdevice/$edgeHub]:
{
    "op": "replace",
    "path": "/$metadata/version/lastUpdateTime",
    "value": "2021-06-24T22:00:59.24660295"
}
[IoTHubMonitor] [10:04:57 PM] MEssage received from [azureperceptdevice/ModuleName]:
{
    "message": "messageContent"
}

[IoTHubMonitor] [10:05:12 PM] MEssage received from [azureperceptdevice/$edgeHub]:
{
    "op": "replace",
    "path": "/$metadata/version/lastUpdateTime",
    "value": "2021-06-24T22:05:12.47444417"
}
```

This means that the message successfully reached the IoTHub and I can now listen to it with Azure Event Hub or Azure Functions.

## Actual Behavior
The next day, I logged in to check on my Azure Function. and it turns out I'm not getting any messages anymore.

When I checked IoTHubMonitor to monitor the live logs, the only logs I got where from edgeHub:
```
[IoTHubMonitor] [02:30:48 PM] MEssage received from [azureperceptdevice/$edgeHub]:
{
    "op": "replace",
    "path": "/$metadata/version/lastUpdateTime",
    "value": "2021-06-25T02:30:48.55714686"
}
```

I tried to **restart** the custom module from IoTHub, in an attempt to force it to reconnect, but the messages were still not being received by the IoT Hub.

## Attempted Fix
I read that while the edgeAgent handles the module image deployment and health monitoring, the edgeHub does everything related to messaging. As such, I restarted edgeHub, and then the custom module (the `await module_client.connect()` was at the start of the module, before a `while True`-looped task, so a hard reconnect is only achievable via restart.)

Thankfully, the messaging was back on. My Azure Function was being triggered again whenever the code passes through `Sending message...Message sent!`. I let the device run for another day.

## The Problem
Unfortunately, the problem has repeated again. The messaging seems to turn off suddenly, even though the module continues to run smoothly as usual. There doesn't seem to be any indication in the logs when the Messaging suddenly stops. I fixed it again by manually restarting the edgeHub and custom modules. However, I strongly need a long-term fix for this.

Any ideas why the messaging stops? And as to how we can fix this?
Thank you very much.

**Comment by vadim-kovalyov** [comment]
Hey @IcaAvanade, can you please repro the issue again and gather the [support bundle](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#gather-debug-information-with-support-bundle-command)? That will help us start investigating.

**Comment by veyalla** [comment]
Note, support-bundle can have personal information (device/module/iothub names etc.), please don't upload it here if you don't want to this information shared publicly.

It might be worth setting up monitoring to review built-in metrics using instructions @ https://aka.ms/edgemon-docs

If that doesn't help, recommend opening a [support ticket ](https://azure.microsoft.com/support/create-ticket/)as the issue might need deeper analysis.

**Comment by veyalla** [comment]
If you're still having this issue, please open a [technical support ticket](https://azure.microsoft.com/support/create-ticket/) and choose Azure Percept as the service.
