### ISSUE TITLE
Local build of iotedge 1.1.4

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#5265]
After the release of 1.1.4, I decided to build my own version of `iotedge` following the standard steps:
```bash
git clone --recurse-submodules --depth 1 --branch 1.1.4 https://github.com/Azure/iotedge /tmp/iotedge
cd /tmp/iotedge
PACKAGE_OS=ubuntu20.04 PACKAGE_ARCH=amd64 ./edgelet/build/linux/package.sh
```

I was surprised when the resulting DEBs were versioned 1.1.3. According to https://github.com/Azure/azure-iotedge/releases/tag/1.1.4 the artifacts should be called 1.1.4. 

This appears to be different from https://github.com/Azure/iotedge/issues/4392 because unlike that issue, 1.1.4 truly had code differences (bug fixes according to log) from 1.1.3 and should therefore have a unique version.

**Comment by ancaantochi** [comment]
@gri6507 Thanks for reporting this issue, I will investigate what happened. It looks like the version was updated to 1.1.4 after the tag for release was set.

**Comment by ancaantochi** [comment]
There was a mistake in our release process where the daemon was accidentally released to be 1.1.4 instead of just being 1.1.3
There were no changes to the daemon and the prod code of 1.1.4 and 1.1.3 are the same. The version was later bumped to 1.1.4

**Comment by gri6507** [comment]
> There was a mistake in our release process where the daemon was accidentally released to be 1.1.4 instead of just being 1.1.3
There were no changes to the daemon and the prod code of 1.1.4 and 1.1.3 are the same. The version was later bumped to 1.1.4

So does that mean that the artifacts listed on https://github.com/Azure/azure-iotedge/releases/tag/1.1.4 page should be rebuilt to have the proper version 1.1.3 in their name?

Since this is not the first time this appears to have happened (see https://github.com/Azure/iotedge/issues/4392), what safeguards will be put in place to prevent this from happening again?

**Comment by ancaantochi** [comment]
We don't plan to rebuild the artifacts, there was no change between version 1.1.3 and 1.1.4 Are there any issues that this might cause for you?

We do have a work item to add smoke test for iotedge artifacts. This test will be a post-release-built, pre-publication test to make sure the versioning & the components work properly.

**Comment by gri6507** [comment]
> We don't plan to rebuild the artifacts, there was no change between version 1.1.3 and 1.1.4 Are there any issues that this might cause for you?

No, this will not cause an issue for me. But it could be confusing to others who experience the same issue.

> We do have a work item to add smoke test for iotedge artifacts. This test will be a post-release-built, pre-publication test to make sure the versioning & the components work properly.

Thank you for adding this planned work.

**Comment by ancaantochi** [comment]
closing this issue, it should be solved with the next release.
