### ISSUE TITLE
Graceful shutdown of IoT Edge module when restarting module in IoT Edge 1.1

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#5274]
When restarting an IoT Edge module via `iotedge restart <modulename>` I'd expect that the module can be gracefully shut down.

For instance, if I have this simple module:

```csharp
 static void Main(string[] args)
{
    Init().Wait();

    // Wait until the app unloads or is cancelled
    var cts = new CancellationTokenSource();
    AssemblyLoadContext.Default.Unloading += (ctx) =>
    {
        Console.WriteLine("Assembly unloading");
        cts.Cancel();
    };
    Console.CancelKeyPress += (sender, cpe) => cts.Cancel();
    WhenCancelled(cts.Token).Wait();
    Console.WriteLine("Stopped");
}
```

When I issue a, `iotedge restart` command, the 'Assembly Unloading', and 'Stopped' messages are not written to the console, so it looks like a restart just kills the container.

Isn't there a possibility to send a SIGTERM signal when restarting, which could cause the container to gracefully shut down ?

**Comment by ancaantochi** [comment]
Is this running on linux or windows? You can take a look how edgeAgent and edgeHub implement it for linux and windows: https://github.com/Azure/iotedge/blob/master/edge-util/src/Microsoft.Azure.Devices.Edge.Util/ShutdownHandler.cs

**Comment by fgheysels** [comment]
Thanks, looks quite interesting.   Is this ShutdownHandler class available via some nuget package ?

**Comment by ancaantochi** [comment]
Hi @fgheysels 
No, Microsoft.Azure.Devices.Edge.Util it's not published as nuget package.

**Comment by fgheysels** [comment]
I have integrated a modified version of the `ShutdownHandler` in my own small library and made it available as a nuget package
https://github.com/fgheysels/Fg.IoTEdgeModule/pull/3/files
