### ISSUE TITLE
MQTT topic subscribe

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#5275]
I would like to subscribe to a topic within a module, but I don't see any examples of how to implement it. I've read all the documentation, especially the ones I show below, and here they mention it's possible, but don't show how...

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11&viewFallbackFrom=iotedge-2018-06
https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-runtime?view=iotedge-2020-11#using-the-mqtt-broker

Is there any example in nodejs? Something that can explain how to subscribe to a topic?

**Comment by ancaantochi** [comment]
We don't have a sample of nodejs module that subscribes to a topic. You should be able to use an generic mqtt client to subscribe to topic. You can follow the example for mosquitto to seethe connection details (like port, username, password): [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11#symmetric-keys-authentication-without-tls](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11#symmetric-keys-authentication-without-tls)

**Comment by Ilheu** [comment]
Thank you for the reply!

**Comment by ancaantochi** [comment]
closing the issue, please reopen if you have further questions
