### ISSUE TITLE
Mqtt data stops dispalying after 19 messages in Device Explore Twin

### ISSUE THREAD

**Issue by Gowresh-MARC** [Azure/iotedge#5288]
I am following the azure mqtt python example. When sending data from python using paho mqtt, I am monitoring the data in Azure's Device Explorer Twin. After 19 messages, the message stops printing on the box in the monitoring application. My python script however does not print any error and continues to send data, but it is not being displayed on the application. When I restart my Python script, data resumes to be printed and stops after 19 messages. How can this be solved?

**Comment by huguesBouvier** [comment]
I can have a look at iotedge logs and see if something is wrong.
Could you please provide a support bundle? 
https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#gather-debug-information-with-support-bundle-command

**Comment by Gowresh-MARC** [comment]
The issue was solved by adding `client.loop_start()`  before the call to `client.connect()` as @stevebus suggested. Thank you very much for the support. Closing this issue now.
