### ISSUE TITLE
IOT edge Module Update

### ISSUE THREAD

**Issue by anoop18pant** [Azure/iotedge#5293]
hi,

I am using a edge device and my requirement is to update the custom module from IOT hub. But the problem is that we have to perform some verification steps once the module gets downloaded from IOT hub to Edge device but as of now it seems edge runtime is doing everything automatically. But due to our custom verification process i want to write the process of download and verification of edge device.

Can anyone advice or share some code how to do it?

**Comment by huguesBouvier** [comment]
Hello,

Currently, edgeAgent gets the config then requests images to be download to edged.
Edged will directly call the docker API. So with that flow, you cannot put some additional step between.

One possibility I see is that you could write a module that pulls the images, make the verification and put them in a local registry. You would have a "curated" local repo on the same host. Then edgeAgent could pull directly from that local repo.

**Comment by anoop18pant** [comment]
> Hello,
> 
> Currently, edgeAgent gets the config then requests images to be download to edged.
> Edged will directly call the docker API. So with that flow, you cannot put some additional step between.
> 
> One possibility I see is that you could write a module that pulls the images, make the verification and put them in a local registry. You would have a "curated" local repo on the same host. Then edgeAgent could pull directly from that local repo.

Hi Hugues,
Thank you for the reply.One point on which i have. Concern is that when on IOT hub side i ll add new deployment version for existing module then edgeAgent will automatically starts updating the module how to stop edgeAgent in doing this so that my custom module can do download and verification?

**Comment by huguesBouvier** [comment]
Hi!

By the way, which type of check do you want to do? Is that similar to docker content trust?
If the check are of a different kind, could you instead have a remote "curated" repo were you can put all your images? Or the checks must be done on the host?

For what I was mentioning:
If you write that "bootstrap" module this is how the flow would be:
1. You control the bootstrap to download images. Bootstrap do the checks you want and push them in a local registry.
2. Then you do a deployment to use the new image from the local registry. edgeAgent will pick images only from the curated repo that is located on the host.

**Comment by anoop18pant** [comment]
> Hi!
> 
> By the way, which type of check do you want to do? Is that similar to docker content trust?
> If the check are of a different kind, could you instead have a remote "curated" repo were you can put all your images? Or the checks must be done on the host?
> 
> For what I was mentioning:
> If you write that "bootstrap" module this is how the flow would be:
> 
> 1. You control the bootstrap to download images. Bootstrap do the checks you want and push them in a local registry.
> 2. Then you do a deployment to use the new image from the local registry. edgeAgent will pick images only from the curated repo that is located on the host.

Hi Hugues,

Basically check needs to be done on host side only. It will be basically to verify the image signature.The signature will be added by our custom tool on cloud side.So basic idea was to use our own custom module to download and verification of signature.
BTW as you said to use bootstrap but our requirement is modules can be updated any time not only boot time.

**Comment by huguesBouvier** [comment]
Hello,

This should not be a problem:
Let's imagine you have 2 modules already running:
bootstrap:1.0, foo:1.1
You want:
bootstrap:1.0, foo:1.2

Then you trigger a download of foo:1.2 with module "bootstrap".
"bootstrap" checks foo:1.2 if it is good then it does:
docker push 127.0.0.1:5000/foo:1.2

Then you can do a new iotedge deployment with image name = 127.0.0.1:5000/foo:1.2

**Comment by anoop18pant** [comment]
> Hello,
> 
> This should not be a problem:
> Let's imagine you have 2 modules already running:
> bootstrap:1.0, foo:1.1
> You want:
> bootstrap:1.0, foo:1.2
> 
> Then you trigger a download of foo:1.2 with module "bootstrap".
> "bootstrap" checks foo:1.2 if it is good then it does:
> docker push 127.0.0.1:5000/foo:1.2
> 
> Then you can do a new iotedge deployment with image name = 127.0.0.1:5000/foo:1.2

Hi hugues,
Thank you for providing me guidance.
In this approach one point is how can we update bootstrap1.1. 
Allso anotger question is docker push 127.0.0.1:5000/foo1.1 where it will place the new image and how iotedgent will know that it has to deploy from this?

**Comment by huguesBouvier** [comment]
Hello, 

Updating bootstrap1.1 to 1.2 would happen the same way:
Bootstrap:1.1 downloads Bootstrap:1.2, verifies it and pushes it to the the local registry.
Then you can do a deployment of bootstrap:1.2.

"Allso anotger question is docker push 127.0.0.1:5000/foo1.1 where it will place the new image and how iotedgent will know that it has to deploy from this?"
You can use for that local docker registry image:
https://docs.docker.com/registry/deploying/
It works very well and it is "friendly" to use and put in place. You can have the "registry" module, open a local docker server on you host.
docker push 127.0.0.1:5000/foo1.1  will push the image to the local registry server.

For edgeAgent you can just do:
![image](https://user-images.githubusercontent.com/33438817/127762386-6601a394-b084-488e-a90d-9821afa5d798.png)

Or use your hostname IP and it will pull the image locally.

**Comment by anoop18pant** [comment]
> Hello,
> 
> Updating bootstrap1.1 to 1.2 would happen the same way:
> Bootstrap:1.1 downloads Bootstrap:1.2, verifies it and pushes it to the the local registry.
> Then you can do a deployment of bootstrap:1.2.
> 
> "Allso anotger question is docker push 127.0.0.1:5000/foo1.1 where it will place the new image and how iotedgent will know that it has to deploy from this?"
> You can use for that local docker registry image:
> https://docs.docker.com/registry/deploying/
> It works very well and it is "friendly" to use and put in place. You can have the "registry" module, open a local docker server on you host.
> docker push 127.0.0.1:5000/foo1.1 will push the image to the local registry server.
> 
> For edgeAgent you can just do:
> ![image](https://user-images.githubusercontent.com/33438817/127762386-6601a394-b084-488e-a90d-9821afa5d798.png)
> 
> Or use your hostname IP and it will pull the image locally.

Hi hugues 

Thank you very much for your support 
I will try this and will let you know.
Once again thank you very much for guidance.

**Comment by huguesBouvier** [comment]
You're welcome! I am closing the ticket for now. Please re-open if you see an issue.

**Comment by anoop18pant** [comment]
hi Hugues,

As you suggested to use docker push command but i want to do it in source code . I was not able to find the functions corresponding these commands. Can you please guide me by sharing some code example to setup a local registery server and pushing image on that in C#

**Comment by huguesBouvier** [comment]
Hey!

You can find a library here: https://github.com/dotnet/Docker.DotNet.
For setting up a local registry server you could look here: https://docs.docker.com/registry/deploying/
