### ISSUE TITLE
Layered deployment used to update edge module desired properties creates inconsistent deployment status 

### ISSUE THREAD

**Issue by MahrRah** [Azure/iotedge#5299]
When using layered deployments to change only the desired properties of a module on the edge device the deployment status of that layer deployment will end up in an inconsistent state. 

## Expected Behavior
The desired property changes are applied and visible in the reported properties of the targeted module, and the layer is marked as `Applied` in all module twins including the `edgeAgent`. 

## Current Behavior
The desired property changes are applied and visible in the reported properties of the targeted module, but the layer is **only** marked as applied in the module twin, for which the property changes are defined in the deployment layer. 
In the `edgeAgent` module twin, the layer is still marked as `Targeted`.

## Steps to Reproduce

Template setup to reproduce the bug.

### 1. Create deployments

A base layer deployment `base.json` with a custom module here called `exampleModule`. 
#### `base.json`
```json
{
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": ""
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.1",
              "createOptions": "{}"
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.1",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
            }
          }
        },
        "modules": {
          "exampleModule": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "XXXX.azurecr.io/exampleModule:0.0.1-amd64"
            }
          }
        }
      }
    }
  }
}
```
Create deployment using Azure CLI 
```bash
az iot edge deployment create -d base-01 -n <iothub-namer> --content base.json --target-condition tags.base=true --priority 10
```
#### `demo-layer.json`
Create a demo layer `demo-layer.json` that only changes the desired properties of the custom module `exampleModule`.
```json
{
  "content": {
    "modulesContent": {
      "$edgeAgent": {},
      "exampleModule": {
        "properties.desired": {
          "foo": "bar"
        }
      }
    }
  }
}
 ```
And create this as layered deployment. 
 ```bash
az iot edge deployment create layered -d demo-01 -n <iothub-namer> --content demo-layer.json --target-condition tags.demo=true --priority 20
```
### 2. Set target condition
Set the conditions for both of these deployments to `true` for your edge device by changing the device twin. 

```json
    "tags": {
        "base": true,
        "demo": true,
```

### 3. Results
This will result in the following inconsistency 

- `edgeAgent` module twin (hence also the Azure portal deployment view)
  - The demo layer is set to `Targeted`
    ```
    {
        "deviceId": "XXXXX-edge-device",
        "moduleId": "$edgeAgent",
         ...
        "configurations": {
            "base-01": {
                "status": "Applied"
            },
            "demo-01": {
                "status": "Targeted"
            }
        }
    }
    ```
- `exampleModule` module twin 
  - The demo layer is set to `Applied`
  - Changes are applied and visible in the reported properties
    `exampleModule`
    ```
    {
        "deviceId": "XXXXX-edge-device",
        "moduleId": "exampleModule",
         ...
        "properties": {
            "desired": {
                "foo": "bar",
                 ...
            "reported": {
                "foo": "bar",
                 ...
            }
        },
        "configurations": {
            "demo-01": {
                "status": "Applied"
            }
        }
    }
    ```

**Comment by huguesBouvier** [comment]
I am seeing: $edgeAgent": {},
That seems to be the problem. The update is applied to separate modules but it failed to be applied as a whole, hence the "targeted" in edgeAgent.

Looking in edgeAgent logs, maybe you can find some error that would help. Also doing it from the portal will give you a template for layered deployement.

**Comment by MahrRah** [comment]
Hi @huguesBouvier , thanks for the response. Azure CLI does not consider it a valid layered deployment unless there is the `$edgeAgent` key.  I tried doing it from the portal, however, then I would need to define the module creation as well, which I don't want for our use case.  

Could it be that using layered deployment is not designed to handle changes only to the desired properties, without creating the module itself? 
I assume this would then also indicate why an`$edgeAgent` object is always expected as part of the deployment.

**Comment by nlcamp** [comment]
@MahrRah - We think this is an IoT Hub service issue because IoT Edge does not set the "configurations" JSON section where you are seeing the inconsistency.  Can you please open an Azure support ticket against IoT Hub?
