### ISSUE TITLE
Supported OS and Platform combination

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iotedge#53]
I see [Azure IoT Edge Support](https://docs.microsoft.com/en-us/azure/iot-edge/support#operating-systems).
But I don't understand that IoT Edge supported OS and Platform(x86/x64/Arm) combination.

So, I tried IoT Core on RasPi, I had error.
```
[192.168.0.4]: PS C:\Data\Users\Administrator\Documents> Invoke-WebRequest -useb https://download.microsoft.com/download/0/6/4/064F84EA
-D1DB-4EAA-9A5C-CC2F0FF6A638/vc_redist.x64.exe -o vc_redist.exe
[192.168.0.4]: PS C:\Data\Users\Administrator\Documents> .\vc_redist.exe /quiet /norestart
Program 'vc_redist.exe' failed to run: The specified executable is not a valid applicati
on for this OS platform..
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

[192.168.0.4]: PS C:\Data\Users\Administrator\Documents>
```

Please tell me some support infomation.

**Comment by darobs** [comment]
Hello @matsujirushi, 

We are still working on GA support for Windows IoT Core.   The instructions in our quickstart are for Windows 10 or Windows Server 2016 VMs or desktops.

I can understand the confusion here. Is there a way we can improve the documentation make this more clear?

**Comment by matsujirushi** [comment]
Thanks for your reply, @darobs .
I'm glad that platform is written in support doc.

i.e.
* Generally Available
  * Ubuntu Server 18.04 - x64
  * Ubuntu Server 16.04 - x64
  * Raspbian-stretch - ARM32v7
* Public Preview
  * Windows 10 Server 1803 - x64
  * Windows 10 IoT Enterprise (with April 2018 update) - x64
  * Windows 10 IoT Core (with April 2018 update) - x64

**Comment by veyalla** [comment]
At the moment, IoT Core supports IoT Edge only on x64. Documented here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-core

**Comment by matsujirushi** [comment]
@veyalla I see.

**Comment by myagley** [comment]
Closing this issue, as the documentation has been updated to include architecture with the OS: https://docs.microsoft.com/en-us/azure/iot-edge/support
