### ISSUE TITLE
EdgeHub cannot reconnect to the IoTHub if restarted while offline

### ISSUE THREAD

**Issue by simardst** [Azure/iotedge#530]
Is the EdgeHub module is restarted while the network connectivity was down, it does not seem to succeed to recover.  In the present case, I have installed a simple module that publishes a simple message every seconds.  Then I disconnect the device from the network and restarts the EdgeHub module (`~$ iotedge restart edgeHub`).  Wait few minutes and reconnect the the device to the network.  The EdgeHub is trying to connect to the iot hub for my module (via MQTT) forever.

## Expected Behavior
When the network connectivity is restored, the EdgeHub resume the communication between the module and the IoTHub and send the buffered messages.

## Current Behavior
The EdgeHub is trying to restore the communication with the IotHub forever.

## Steps to Reproduce
1. Configure the EdgeHub to persist buffered messages on disk and use the MQTT upstream protocol (as decribed into the documentation (https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities)
2. Deploy a simple module that publish an event every seconds (ex. "Message 1", "Message 2", ...)
3. Ensure that the messages sent by the module are forwarded to the IoT Hub
4. Disconnect the network.
5. Wait few minutes.
6. Reconnect the network and verify that the Edge Hub is reconnecting to the Iot Hub
7. Verify that the message sent by the module while offline are forwarded to the IoT Hub.
8. Disconnect the network.
9. Wait few minutes.
10. Restart the EdgeHub (`~$ iotedge restart edgeHub`).
11. Wait few minutes.
12. Verify the the module is reconnecting to the EdgeHub.
13. Reconnect the network.
14. The EdgeHub is trying to reconnect to the IoTHub forever.

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.4

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
docker (client & Server) 3.0.1

## Logs
EdgeAgent
![image](https://user-images.githubusercontent.com/1949586/48267710-0aacd800-e401-11e8-87f1-33cf30bb8ea7.png)
![image](https://user-images.githubusercontent.com/1949586/48267642-dc2efd00-e400-11e8-88e5-228a6295e528.png)

EdgeHub
![image](https://user-images.githubusercontent.com/1949586/48267900-80b13f00-e401-11e8-8ffd-b8fbb7490f8b.png)
![image](https://user-images.githubusercontent.com/1949586/48267982-be15cc80-e401-11e8-98aa-91fca8c8407e.png)
![image](https://user-images.githubusercontent.com/1949586/48268031-e0a7e580-e401-11e8-8a04-d583eb1180fb.png)
![image](https://user-images.githubusercontent.com/1949586/48268067-f87f6980-e401-11e8-8647-83ad80f54d29.png)
![image](https://user-images.githubusercontent.com/1949586/48268154-39777e00-e402-11e8-9535-960895d49636.png)
... And so on forever

#### Deployment Manifest
`
{
    "content": {
        "modulesContent": {
            "$edgeAgent": {
                "properties.desired": {
                    "schemaVersion": "1.0",
                    "runtime": {
                        "type": "docker",
                        "settings": {
                            "loggingOptions": "",
                            "minDockerVersion": "v1.25",
                            "registryCredentials": {
                                "ssimard": {
                                    "address": "ssimard.azurecr.io",
                                    "password": "-----",
                                    "username": "-----"
                                }
                            }
                        }
                    },
                    "systemModules": {
                        "edgeAgent": {
                            "type": "docker",
                            "settings": {
                                "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
                                "createOptions": "{}"
                            }
                        },
                        "edgeHub": {
                            "type": "docker",
                            "settings": {
                                "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
                                "createOptions": "{\"HostConfig\":{\"Binds\":[\"/mnt/iotedge/:/home/edgehubuser/.local/cache/\"],\"PortBindings\":{\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}]}}}"
                            },
                            "env": {
                                "storageFolder": {
                                    "value": "/home/edgehubuser/"
                                },
                                "UpstreamProtocol": {
                                    "value": "MQTT"
                                }
                            },
                            "status": "running",
                            "restartPolicy": "always"
                        }
                    },
                    "modules": {
                        "filtermodule": {
                            "type": "docker",
                            "settings": {
                                "image": "ssimard.azurecr.io/filtermodule:0.0.4-amd64",
                                "createOptions": "{}"
                            },
                            "version": "1.0",
                            "status": "running",
                            "restartPolicy": "always"
                        }
                    }
                }
            },
            "$edgeHub": {
                "properties.desired": {
                    "schemaVersion": "1.0",
                    "routes": {
                        "route": "FROM /messages/* INTO $upstream"
                    },
                    "storeAndForwardConfiguration": {
                        "timeToLiveSecs": 7200
                    }
                }
            }
        }
    },
    "createdTimeUtc": "2018-11-09T13:32:46.122Z",
    "etag": "MQ==",
    "id": "test-01",
    "labels": {},
    "lastUpdatedTimeUtc": "2018-11-09T13:32:46.122Z",
    "metrics": {
        "results": {},
        "queries": {}
    },
    "systemMetrics": {
        "results": {
            "targetedCount": 1,
            "appliedCount": 1,
            "reportedSuccessfulCount": 1,
            "reportedFailedCount": 0
        },
        "queries": {
            "targetedCount": "select deviceId from devices where capabilities.iotEdge = true",
            "appliedCount": "select deviceId from devices.modules where moduleId = '$edgeAgent' and configurations.[[test-01]].status = 'Applied'",
            "reportedSuccessfulCount": "select deviceId from devices.modules where moduleId = '$edgeAgent' and configurations.[[test-01]].status = 'Applied' and properties.desired.$version = properties.reported.lastDesiredVersion and properties.reported.lastDesiredStatus.code = 200",
            "reportedFailedCount": "select deviceId from devices.modules where moduleId = '$edgeAgent' and configurations.[[test-01]].status = 'Applied' and properties.desired.$version = properties.reported.lastDesiredVersion and properties.reported.lastDesiredStatus.code != 200"
        }
    }
}
`

#### filtermodule code
`
    class Program
    {
        static void Main(string[] args)
        {
            Init().Wait();

            // Wait until the app unloads or is cancelled
            var cts = new CancellationTokenSource();
            AssemblyLoadContext.Default.Unloading += (ctx) => cts.Cancel();
            Console.CancelKeyPress += (sender, cpe) => cts.Cancel();
            WhenCancelled(cts.Token).Wait();
        }

        public static Task WhenCancelled(CancellationToken cancellationToken)
        {
            var tcs = new TaskCompletionSource<bool>();
            cancellationToken.Register(s => ((TaskCompletionSource<bool>)s).SetResult(true), tcs);
            return tcs.Task;
        }

        static async Task Init()
        {
            AmqpTransportSettings amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            ITransportSettings[] settings = { amqpSetting };

            // Open a connection to the Edge runtime
            ModuleClient moduleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await moduleClient.OpenAsync();
            Console.WriteLine("IoT Hub module client initialized.");

            int counter = 0;
            while (true)
            {
                counter++;
                Console.WriteLine($">>> Sending message: {counter}");
                
                var message = new Message(Encoding.UTF8.GetBytes($"Message #{counter}."));
                message.Properties.Add("counter", counter.ToString());

                await moduleClient.SendEventAsync(message);
                Console.WriteLine($"--- Message sent.");

                await Task.Delay(TimeSpan.FromSeconds(1));
            }
        }
    }
`

**Comment by veyalla** [comment]
Thanks for the report and details @simardst. We can repro and taking a look.

**Comment by veyalla** [comment]
@simardst Are you testing in a VM or on a physical machine?

**Comment by simardst** [comment]
I'm using a VM running in Hyper-V.

**Comment by veyalla** [comment]
How are you disconnecting the VM’s network?
Are you removing its Ethernet adapter from Hyper-V manager on the host?
________________________________

**Comment by simardst** [comment]
I am disconnecting the VM's network using the linux network manager.

**Comment by veyalla** [comment]
@simardst After restarting the hub while offline, could you share the output of:

* `sudo docker exec edgeHub cat /etc/resolv.conf`
* `sudo docker exec tempSensor cat /etc/resolv.conf`
(if you're not using tempSensor module, replace with your custom module name)

**Comment by veyalla** [comment]
Following up on this. Our investigation showed that this can happen because the module containers don't get a working DNS config when restarted while offline. The solution is to specify the DNS servers used in your environment in the container engine options. This has been documented here:

https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities#specifying-dns-servers
