### ISSUE TITLE
Edge transparent gateway - openssl verification error

### ISSUE THREAD

**Issue by davebanthorpe** [Azure/iotedge#532]
Having followed the guide to setup a Transparent Gateway (Windows edge, linux container), when I run the command:

`PS C:\users\dave\documents\certs> openssl s_client -connect el1000edge.local:8883 -CAfile azure-iot-test-only.root.ca.cer
t.pem`

I get the following error:

`Verify return code: 20 (unable to get local issuer certificate)`

Root CA cert is in trusted root (local computer). Interestingly MQTT box can connect OK with a setting of "CA signed server certificate" but I need to get openssl working correctly as I'm trying to connect a downstream client of KepServerEX and that it throwing a similar error:

`unable to find valid certification path to requested target`

**Comment by mrohera** [comment]
A few things you can check and try:

1) Is the path to the CA cert file (azure-iot-test-only.root.ca.cert.pem) accurate? Per your comment there is a typo.

2) Is ```el1000edge.local``` the hostname you configured in the config.yaml? They should be the same for a successful TLS handshake.

3) If all else fails. could you please re-run your command with -showcerts as well and send us the output. There shouldn't be anything sensitive as it only prints the public certificates.

**Comment by davebanthorpe** [comment]
in reply to your questions:

1) yes path is correct. am running the command in the certs directory. Error also occurs if I used -CApath

2) correct yes

3) here you go

[output.txt](https://github.com/Azure/iotedge/files/2573065/output.txt)

**Comment by mrohera** [comment]
Thanks for getting back to me. I have a follow up question:

* What files did you use to setup the config,yaml after you ran the scripts? You could simply copy paste the certificates section in the config.yaml.

**Comment by davebanthorpe** [comment]
I ran all the certificate processing scripts locally on the edge so did not need to move them. This is the section from the config.yaml:

`certificates:
  device_ca_cert: "c:\\users\\hpe\\documents\\certs\\new-edge-device-full-chain.cert.pem"
  device_ca_pk: "c:\\users\\hpe\\documents\\private\\new-edge-device.key.pem"
  trusted_ca_certs: "c:\\users\\hpe\\documents\\certs\\azure-iot-test-only.root.ca.cert.pem"`

**Comment by mrohera** [comment]
Thanks for getting back to me. In the ```new-edge-device-full-chain.cert.pem``` file, how many certificates do you see? There should be 3 certificate file each marked by a 

```
-----BEGIN CERTIFICATE----- 

-----END CERTIFICATE-----
```

The very top of the file should be the certificate with ```CN=el1000edge.local.ca```.
Next should be certificate with ```CN=Azure IoT Hub Intermediate Cert Test Only``` and finally,
at the very bottom should be the certificate with ```CN=Azure IoT Hub CA Cert Test Only```.

I typically use the command ```openssl x509 -in <file> -text -noout``` to view the contents of each of the certificates. If you would like, you can simply attach the ```new-edge-device-full-chain.cert.pem``` and we can examine at our end. Either way is fine.

**Comment by davebanthorpe** [comment]
Certificate attached - thanks!


[new-edge-device-full-chain.cert.zip](https://github.com/Azure/iotedge/files/2575464/new-edge-device-full-chain.cert.zip)

**Comment by mrohera** [comment]
@davebanthorpe overall the ```new-edge-device-full-chain.cert.zip``` file seems okay. 

The only thing I can think of is the file passed into the openssl command ```-CAfile azure-iot-test-only.root.ca.cert.pem``` is not the same as the last certificate (end of the file) in the file ```new-edge-device-full-chain.cert.zip.``` Can you please check this?

I went through a new setup of the transparent gateway scenario using the powershell scripts and I cannot repro this issue.

**Comment by davebanthorpe** [comment]
Just checked - they are identical

**Comment by mrohera** [comment]
Could you kindly list the version of iotedged and edgeHub that you are using?

**Comment by davebanthorpe** [comment]
mcr.microsoft.com/azureiotedge-hub:1.0

and

mcr.microsoft.com/azureiotedge-agent:1.0

**Comment by mrohera** [comment]
@davebanthorpe after adding the lines in the config.yaml did you restart the iotedge service (iotedge)?
A colleague of mine noticed that we did not have the instructions that state that we need to restart the iotedge after updating the config.yaml file. This should be fixed very shortly.

Powershell:
```
Stop-Service iotedge -NoWait
Start-Service iotedge
```

After restarting can you observe the iotedge logs and see if you can see these lines:
```
info: iotedged -- Configuring the Device CA certificate using "<your-path>".
info: iotedged -- Configuring the Device private key using "<your-path>".
info: iotedged -- Configuring the trusted CA certificates using "<your-path>"
```

Steps to view the logs: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-with-windows#verify-successful-installation
(You probably do not have go back 5 mins)

After you have determined this, can you please re-run your openssl command and let us know what you see. Thanks again for your help.

**Comment by ancaantochi** [comment]
Hi @davebanthorpe,

From iotedged logs, the path to the certs is c:\users\hpe\documents\certs, but in the openssl command (from the first message) you provide CAfile path as C:\users\dave\documents\certs. Can you please confirm that you use the same certs path?

Thanks,
Anca

**Comment by davebanthorpe** [comment]
Yep path is correct. I had originally created them under different user
account on same machine. But now they exist under c:\users\hpe

**Comment by ancaantochi** [comment]
Hi @davebanthorpe,

Can you please check in C:\ProgramData\iotedge\hsm\certs, open the file that starts with edgeHub and extension pem: 
- Does it have 4 certs? 
- Is the last cert the same cert as you provide to openssl command (azure-iot-test-only.root.ca.cert.pem)

Thanks!

**Comment by myagley** [comment]
I am going to close this issue due to inactivity. Please feel free to reopen.
