### ISSUE TITLE
Setup IotEdge with Manual provisioning configuration using an X.509 identity certificate but getting error

### ISSUE THREAD

**Issue by RohitMundhra** [Azure/iotedge#5328]
**Device Information:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Iotedge Version: iotedge 1.1.0

Config.yaml file:
<img width="1391" alt="Screenshot 2021-08-05 at 11 21 34 AM" src="https://user-images.githubusercontent.com/54216466/128298908-9693cd8a-396d-49ad-b232-39884763d9f0.png">

Error: systemctl status iotedge
<img width="1425" alt="Screenshot 2021-08-05 at 11 24 11 AM" src="https://user-images.githubusercontent.com/54216466/128298967-16d161c1-3880-43b6-ac15-92d08fb62399.png">

**Comment by nyanzebra** [comment]
Hi, would it be possible to add either the support-bundle (aka `iotedge support-bundle`) or more of the system logs (aka `iotedge system logs`)? Also if you could add the output of `iotedge check` that would be usefule :)

Did you recently create this cert? Or is this an older test cert?

**Comment by RohitMundhra** [comment]
**iotedge check output:**
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: identity certificates expiry - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 47 days (at 2021-09-22 22:29:25 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with IoT Hub MQTT port - Error
    Could not connect to WE-SB-DEV-SC-iothub02.azure-devices.net:8883
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK

**Comment by RohitMundhra** [comment]
I have recently created these certs

**Comment by nyanzebra** [comment]
Just to rule this out, have the certificate thumbprints been added on hub side? https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2018-06#option-2-authenticate-with-x509-certificates

There should be an actual error within edgeHub module as well, should be able to use `iotedge logs edgeHub` and there should be some error likely in regards to communicating upstream with cloud.

**Comment by varunpuranik** [comment]
@RohitMundhra - 
- Can you please provide debug iot edge daemon logs as described here - https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#check-the-status-of-the-iot-edge-security-manager-and-its-logs
- Can you also please re-run iotedge check with --verbose option, and share the output?

@arsing

**Comment by micahl** [comment]
Closing this issue.  @RohitMundhra please reactivate with requested logs to help us further assist.
