### ISSUE TITLE
OPC Publisher doesn't send data in order as in generated by OPC simulation server

### ISSUE THREAD

**Issue by sinfergit** [Azure/iotedge#5339]
I have been trying to retrieve sensor data generated by OPC simulation server (data listed in excel file and read by OPC simulation) in to one of the custom modules in Azure IOT Edge. When the data logged in the console it shows me that data has not been logged in order. Following is the JSON for OPC publisher hosted in iot edge as a module

![image](https://user-images.githubusercontent.com/24528193/127675761-0de83cc6-3858-426b-85f8-0bfa4639f3a8.png)

Following is the published nodes json in gateway device

![image](https://user-images.githubusercontent.com/24528193/127675942-7fe86059-1a5d-4daf-9b46-2e60a5479ac4.png)

Following is the screenshot of my excel sheet data
![image](https://user-images.githubusercontent.com/24528193/127676048-04c82ed6-2d05-412f-aedb-2b336afb82e0.png)

But the OPC publisher will not route the data in to modules in order that starting from anywhere but in order . For an example it sends starting from the row ,value 11 for Tag11 and then again sends the next row which has the value 17 for tag 11. And sometimes sends a batch of data. no proper order. This is not a issue with OPC server simulation since i have tested Simulation server with a standalone OPC client and it gets the data in order. Excel is read by simulation server. Appreciate any help on this.

Following image is a screenshot of my IoT edge module(python) where i log the data to console retrieved from OPC Publisher routing.
![image](https://i.stack.imgur.com/y1Z45.png)

I have attached the iot edge support bungle logs 
[IoTedgeLogs.zip](https://github.com/Azure/iotedge/files/6965134/IoTedgeLogs.zip)

**Comment by nyanzebra** [comment]
Hi, I am the one who asked you on stackoverflow to open a GitHub issue on us :) If you don't mind, would you update this with a support-bundle? To do this, from your device run `iotedge support-bundle`.

**Comment by nlcamp** [comment]
I'm also reaching out to our Industrial IoT Team to see if this is a known issue with the OPC Publisher module.

**Comment by nlcamp** [comment]
@sinfergit Our Industrial IoT Team suggested that you open an issue here instead: https://github.com/Azure/Industrial-IoT/issues

They maintain the OPC Publisher and are better suited to help you with the issues you're seeing.

**Comment by koepalex** [comment]
Please close this issue: all further discussion should be in Azure/Industrial-IoT#1308 only.
