### ISSUE TITLE
EFLOW VM Host Monitoring

### ISSUE THREAD

**Issue by nenright** [Azure/iotedge#5341]
We're currently using the Azure Monitor module to collect metrics for our modules. Works great!  However, we have a need to get metrics from the EFLOW VM Host itself. We can configure the metrics module to scrape the windows exporter service installed on the host (https://github.com/prometheus-community/windows_exporter) but obviously the data isn't associated with an edge module/device so querying on the backend isn't straight forward. 

I guess one solution would be to create a proxy module that added the appropriate tags to the windows_exporter output. Before I went down that road, I wanted to make sure that I wasn't missing anything or there was another out of the box solution available for EFLOW VM host monitoring.

Any ideas?

**Comment by nlcamp** [comment]
Adding @Azure/iotedge-eflow team, which may have some ideas.

**Comment by veyalla** [comment]
@nenright 

> I guess one solution would be to create a proxy module that added the appropriate tags to the windows_exporter output. 

If you want to use the metrics-collector module for transporting these metrics, this seems like the way to go about it. I'm not aware of any other out-of-box solution outside of the Kubernetes (Windows containers) ecosystem. In case you haven't already, see these [custom module metrics recommendations](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-add-custom-metrics?view=iotedge-2020-11) on the the tags the proxy module should enrich with.

**Comment by nenright** [comment]
Thanks @veyalla, ya creating a proxy was what I was thinking as well but seems like extra overhead. 

Feature request :), add tag configurability to the metrics module so that the tags can be added without the need for a proxy (I may take a stab with a fork).

**Comment by veyalla** [comment]
I've captured this feature request here: https://github.com/Azure/iotedge/projects/2#card-66526158

We'd obviously love contributions here :). If you have questions about current implementation or brainstorm design, please include @and-rewsmith and @damonbarry
