### ISSUE TITLE
Using Bluez Bluetooth stack in IOT Edge Module

### ISSUE THREAD

**Issue by anoop18pant** [Azure/iotedge#5344]
Dear All,

I want to write a IOT Edge module in C#. In this module i want to use Bluez bluetooth stack to control my BLE device.

Can someone please share some already existing source code to guide in how to implement it as a container module.

**Comment by damonbarry** [comment]
@anoop18pant A BlueZ bluetooth module is a fantastic idea, and it's possible that someone in the community has one. But this project does not provide one.

We have a generic sample module here: [edge-modules/SimulatedTemperatureSensor](https://github.com/Azure/iotedge/tree/master/edge-modules/SimulatedTemperatureSensor)
You can also find documentation about writing a module here: [Develop modules for Azure IoT Edge](https://docs.microsoft.com/en-us/azure/iot-edge/module-development?view=iotedge-2020-11)
