### ISSUE TITLE
How to cross-compile edgeagent module on aarch64 platform?

### ISSUE THREAD

**Issue by v-jiq** [Azure/iotedge#536]
I had cross-compile a aarch64 platform security_daemon program  and it can run on target board.But will occur below  error:
![image](https://user-images.githubusercontent.com/39880470/48387257-03066f80-e730-11e8-8e0c-aeb077174b67.png)

Is it also necessary to cross-compile a aarch64 version of edgeagent module？

I want to consult if need to cross-compile this module,what detail need attention?

**Comment by myagley** [comment]
Hello. Yes, Docker is attempting to pull an aarch64 image. aarch64 images don't exist yet for the Edge Agent and EdgeHub. However, you may be able to get arm32 images to work.

There's more information on how to try this here: https://blogs.msdn.microsoft.com/iotdev/2018/11/05/a-workaround-to-run-azure-iot-edge-on-arm64-devices/

Thanks!

**Comment by v-jiq** [comment]
@myagley  Thank  you very much,this way is ok. you can close this issue!!

**Comment by v-jiq** [comment]
Thank you very much, this way is ok!
