### ISSUE TITLE
Is it possible to get rid of the guaranteed message order delivery?

### ISSUE THREAD

**Issue by davidguidali** [Azure/iotedge#5364]
Hi Guys
I have the following scenario:

- There are two modules, module A and module B 
- Module A sends messages to Module B which sends them to the IoT Hub (of course always with the edge hub in between)
- If Module B fails to send a message, it returns _MessageResponse.None_. If it succeeds, it returns _MessageResponse.Completed_.
- If MessageResponse.None is send, the edgeHub waits 30 seconds until it resends the message (this is by design I guess)
- Because ordered delivery is guaranteed, all other messages incoming at this time will queue up at the edgeHub.

Question:
- Is it somehow possible to get rid of the ordered delivery, so that other messages incoming during the 30 seconds will still be send from edgeHub to module B?

Bonus Question:
- If I use a public dictionary instance in the SetInputMessageHandlerAsync callback, is it safe to use a "normal" dictionary or do I need to care about thread safety and use e.g. a ConcurrentDictionary? My goal is to store the message id with an integer on how often the message has been tried to send and if it gets higher than a certain value, abandon the message.

Thanks for your help!

**Comment by nlcamp** [comment]
@davidguidali - Have you tried `SendEventBatchAsync`? [link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient.sendeventbatchasync?view=azure-dotnet)

There are also two settings you may want to consider (however these could result in dropped messages, which may not be acceptable for your use case):

1. The[ edge hub time to live (TTL) desired property ](https://docs.microsoft.com/en-us/azure/iot-edge/module-edgeagent-edgehub?view=iotedge-2020-11#edgehub-desired-properties)-- lowering this value from the default of 7200 seconds would reduce the amount of time the messages are queued by Edge Hub during offline periods,
2. The SDK's  [retry policy](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-reliability-features-in-sdks#retry-policy-apis)

**Comment by nlcamp** [comment]
@davidguidali - It turns out `SendEvenBatchAsync()` will also always send messages in order when going module to module. The ordering in which messages are sent is baked into Edge Hub and we do not support changing the behavior.

You may still want to consider the TTL and retry policy mentioned in my previous comment.

Regarding your question about thread safety in the callback provided to `SetInputMessageHandlerAsync`, I would suggest asking your question here: https://github.com/Azure/azure-iot-sdk-csharp/issues

**Comment by davidguidali** [comment]
Thanks for your answer!
Wasn't really aware of this retry policy, I will check it out. :)
