### ISSUE TITLE
Certificate failure

### ISSUE THREAD

**Issue by sabrioezer** [Azure/iotedge#5368]
## Expected Behavior
Tell us what should happen

## Current Behavior
Cerificates are either not valid or not created ...

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Update from 1.0.9 to 1.2.3
2. import config from yaml to toml

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ tpmd is running - OK
√ identityd is running - OK
× read all preloaded certificates from the Certificates Service - Error
    could not load cert with ID "aziot-edged-trust-bundle"

    Caused by:
        parameter "id" has an invalid value
        caused by: not found
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
23 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) raised errors. Re-run with --verbose for more details.
6 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.3
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 3.0.11+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
sudo journalctl -u iotedge -f
-- Logs begin at Wed 2020-05-13 09:14:31 UTC. --
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:36Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:load_if_cert_and_key_exist_by_alias:1521) Certificate for alias is invalid iotedged-workload-ca
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:36Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert:2701) Failed certificate validation for alias iotedged-workload-ca
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:36Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:edge_hsm_client_create_certificate:285) Could not create certificate in the store
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:37Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:validate_cert_chain:1678) Did not find issuer certificate in certificate /var/lib/iotedge/hsm/certs/iotedge-tlsTLNi220opyZbShBY7-R4NIxntUhft8tKSA59Ln8BbSA_.cert.pem
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:37Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:verify_certificate_internal:1813) Certificate file does not contain issuer certificate /var/lib/iotedge/hsm/certs/iotedge-abcdasda_.cert.pem
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:37Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:load_if_cert_and_key_exist_by_alias:1521) Certificate for alias is invalid iotedge-tls
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:37Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_cert:2701) Failed certificate validation for alias iotedge-tls
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:11:37Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:edge_hsm_client_create_certificate:285) Could not create certificate in the store
Aug 13 07:52:34 svr-hymon-00002 iotedged[4829]: 2021-08-11T13:18:53Z [ERR!] (/project/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:remove_if_cert_and_key_exist_by_alias:1443) Certificate and key file for alias do not exist $edgeHub637253822613638778server
Aug 13 07:52:34 svr-hymon-00002 systemd[1]: Stopped Azure IoT Edge daemon.

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by nlcamp** [comment]
@sabrioezer - Please see the following document regarding the special case of upgrading from iotedge v1.0 to v1.2: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge?view=iotedge-2020-11&tabs=linux#special-case-update-from-10-or-11-to-12

**Comment by sabrioezer** [comment]
I have followed these steps to upgrade

**Comment by nlcamp** [comment]
@sabrioezer - the `sudo journalctl -u iotedge -f` command is for checking logs in iotedge v1.0 and v1.1.  In v1.2, the commands you should run are `sudo journalctl -u aziot-edged`,  `sudo journalctl -u aziot-identityd`,  `sudo journalctl -u aziot-certd`, and  `sudo journalctl -u aziot-keyd`. You can also run `sudo iotedge system logs` to return all the daemon logs aggregated.

As for the runtime modules, you can run `sudo iotedge logs edgeHub` and `sudo iotedge logs edgeAgent`

It's likely that either the upgrade was not completed successfully OR the logs you've pasted above are from before the upgrade. Please run the v1.2 commands to view the logs and let us know if there are any errors.

**Comment by nlcamp** [comment]
@sabrioezer Did you have a chance to run the commands from my previous comment? If so, did you see any errors? Are you still having the issues you originally reported?

**Comment by sabrioezer** [comment]
Sorry Noel for my late reply. I couldnot apply your suggestion since we had another major issue with our edge device. We formatted it because of that and after installing iotedge, there was no problem anymore.
