### ISSUE TITLE
Windows Support for 1.2

### ISSUE THREAD

**Issue by Steve0212a** [Azure/iotedge#5386]
Sorry, I know this is not a bug, but I can't find the info anywhere.  I am working with a customer and we are in the design phase.  We would definitely like to use IOT Edge, but it must support Windows as the host OS.  Version 1.1 clearly states that it does, but 1.2 does not state that it does.  Further, there is not installer for Windows for v1.2 on the releases page.

In the documentation at https://docs.microsoft.com/en-us/azure/iot-edge/?view=iotedge-2020-11, if I click on "Deploy your first IoT Edge module to a Windows device", it takes me to a 1.1 page.

I do see that v1.1 is the LTS version, but I do not want to use IOT Edge v1.1 if support for Windows as the host is going to be dropped in v1.2. 

On the platform support page (https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2020-11)
`Currently, there is no supported way to run IoT Edge version 1.2 on Windows devices. IoT Edge for Linux on Windows is the recommended way to run IoT Edge on Windows devices, but currently only runs IoT Edge 1.1. For more information, refer to the IoT Edge 1.1 version of this article.`

So, really, I am asking if there be a "supported way to run IoT Edge version 1.2 on Windows devices" in future releases?

Thanks.

**Comment by veyalla** [comment]
I believe this is on backlog of the EFLOW team. Transferring to EFLOW repo.
