### ISSUE TITLE
Certificate chain fails to validate if lifetime longer than 2038

### ISSUE THREAD

**Issue by matsjoha-MS** [Azure/iotedge#5395]
According to this https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-2018-06&preserve-view=true#install-production-certificates

“a limitation in libiothsm prevents the use of certificates that expire on or after January 1, 2038.” 

When device tries to validate the cert chain, it throws an error: TLS authentication error: The remote certificate is invalid according to the validation procedure. 

I am guessing since 1.1 is LTS and this only affects customers with certs with lifetime longer than 2038, it will not be fixed in 1.1?
What would be the best recommendation?

1. Go with IoT Edge 1.2 as this limitation has been resolved (no libiothsm)?
2. Create a new Root and intermediate certificate chain with expiration before 2038?
3. ?

**Comment by pmzara** [comment]
Hi @matsjoha-MS 

It will not be fixed in 1.1 since this is a limitation of 3rd party library. Unless they fixed it in the library.
Both options (1 and 2) are good choices. But everything depends on how is your environment. Is it possible to go with IoT Edge 1.2?

**Comment by matsjoha-MS** [comment]
@pmzara, customer does have IT support for Windows but no Linux support, so we were targeting EFLOW, for which I have no timeline for 1.2 GA. So options may be go with Linux and have OS unmanaged, or if allowed use new cert for IoT solution(s).

**Comment by veyalla** [comment]
Based on response in https://github.com/Azure/iotedge-eflow/issues/65#issuecomment-902130334, 1.2 support for EFLOW is on the future roadmap. The options you listed above are accurate for now.
