### ISSUE TITLE
Required port openings for Azure

### ISSUE THREAD

**Issue by tickledblue3** [Azure/iotedge#5397]
Modules fail to deploy on the IoT Edge device with the error messages in the edgeAgent log:
Unable to process module AzureBlobStorageonIoTEdge add or update as the module identity could not be obtained
Unable to process module edgeHub add or update as the module identity could not be obtained
Unable to process module digTwinMgr add or update as the module identity could not be obtained

In addition, the AzureBlobStorageonIoTEdge module fails to load files to blob storage.

Both of these issues occur when running on a device that is on a firewalled enterprise network.  
When the device is connected to a home network, the issues go away.

The enterprise firewall is configured with the following port openings:

Source                     /    Destination DNS name                                    /  Destination Port               /  Protocol
iotEdgeDev IP addr  /  IotHubName.azure-devices.net                 /          5671                         /       TCP
iotEdgeDev IP addr  /  IotHubName.azure-devices.net                 /          8883                         /       TCP
iotEdgeDev IP addr  /  BlobStorageName.blob.core.windows.net  /          5671                         /       TCP
iotEdgeDev IP addr  /  BlobStorageName.core.windows.net          /          8883                         /      TCP
iotEdgeDev IP addr  /  AzContainerRegName.azurecr.io               /          5671                         /       TCP
iotEdgeDev IP addr  /  AzContainerRegName.azurecr.io               /          8883                         /       TCP

Are there any ports that need to be opened that are missing above?

**Comment by pmzara** [comment]
Thanks, @tickledblue3 for your question. Could you give more details about the version that you are using? Is port 443 open in your firewall?

**Comment by tickledblue3** [comment]
This is being done with EFLOW and using Azure IOT Edge LTS (1.1.2107.0)

Versions being used:
AzureBlobStorageonIoTEdge  mcr.microsoft.com/azure-blob-storage:latest
edgeAgent    mcr.microsoft.com/azureiotedge-agent:1.1
edgeHub       mcr.microsoft.com/azureiotedge-hub:1.1

Yes, I'm pretty sure that port 443 is open.

**Comment by pmzara** [comment]
@tickledblue3 Please run 'iotedge check --verbose' and publish here, after removing any personal info.

**Comment by tickledblue3** [comment]
I guess I was wrong about port 443 for the IoT Hub (see iotedge check results below).   I'll get that opened.

I'd like to get all needed ports opened in 1 IT request.  Is port 443 (and any other ports) needed for the following?

- Azure Container Registry?  My custom module isn't successfully downloaded behind the firewall.
- AzureBlobStorageonIoTEdge?  This isn't successfully downloaded behind the firewall.  Destination port is mcr.microsoft.com?
- Blob storage?  Blobs are not successfully uploaded behind the firewall.

Thanks!

----------------
$ sudo iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
        caused by: error trying to connect: Connection timed out (os error 110)
‼ host time is close to real time - Warning
    Could not query NTP server
        caused by: could not receive NTP server response: Resource temporarily unavailable (os error 11)
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2021-11-21 20:17:13 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
× host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - Error
    Could not connect to <IoTHub>.azure-devices.net:443
        caused by: connection timed out
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
× container on the default network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the default network could not connect to <IoTHub>.azure-devices.net:443
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (A task was canceled.)
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to <IoTHub>.azure-devices.net:443
        caused by: docker returned exit code: 1, stderr = One or more errors occurred. (A task was canceled.)
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

13 check(s) succeeded.
7 check(s) raised warnings.
3 check(s) raised errors.

**Comment by pmzara** [comment]
@tickledblue3 
Could you please run again the command - sudo iotedge check --verbose? There are some connectivity errors related to port 443. Is it opened?

**Comment by tickledblue3** [comment]
Port 433 is now open.  Here is the output of iotedge check --verbose:
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
        caused by: error trying to connect: Connection timed out (os error 110)
‼ host time is close to real time - Warning
    Could not query NTP server
        caused by: could not receive NTP server response: Resource temporarily unavailable (os error 11)
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 82 days (at 2021-11-21 20:17:13 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
7 check(s) raised warnings.

**Comment by tickledblue3** [comment]
All issues are now resolved.   Port openings used were:

Source / Destination DNS name / Destination Port / Protocol
iotEdgeDev IP addr / IotHubName.azure-devices.net / 5671 / TCP
iotEdgeDev IP addr / IotHubName.azure-devices.net / 8883 / TCP
iotEdgeDev IP addr / IotHubName.azure-devices.net / 443 / TCP
iotEdgeDev IP addr / AzContainerRegName.azurecr.io / 8883 / TCP
iotEdgeDev IP addr / BlobStorageName.blob.core.windows.net / 443 / TCP  (for ACR modules and blob storage)
iotEdgeDev IP addr / mcr.microsoft.com / 443 / TCP    (for microsoft marketplace modules)
iotEdgeDev IP addr / eastus.data.mcr.microsoft.com / 443 / TCP  (for microsoft marketplace modules)

Thanks for your help.
