### ISSUE TITLE
IoTEdge commands get hangs on armv7 based artik target

### ISSUE THREAD

**Issue by raviinroorkee-7** [Azure/iotedge#54]
Hi ,
I have followed -
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm
to setup iotedge on ARM32 (armv7-l) based ARTIK board. I was able to installed moby-engine and moby-cli as mentioned.

**Content**: How to install Azure IoT Edge on Linux
**Content Source**: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm
**Service**: iotedge
**OS - Ubuntu 16.04
Architecture - arm32 (armv7-l)
Toolchain - arm-linux-gnueabihf**

[root@artik ~]# **sudo systemctl status iotedge**
● iotedge.service - Azure IoT Edge daemon
Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
**Active: active (running) since** Thu 2018-07-19 06:13:00 UTC; 209ms ago
Docs: man:iotedged(8)
Main PID: 3484 (iotedged)
Tasks: 6
Memory: 1.3M
CPU: 200ms
CGroup: /system.slice/iotedge.service
└─3484 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Using runtime network id azure-iot-edge
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Initializing the module runtime...
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Finished initializing the module runtime.
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Configuring certificates...
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Finished configuring certificates.
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Initializing hsm...

[root@artik ~]# sudo journalctl -u iotedge -f
-- Logs begin at Thu 2018-07-19 05:47:18 UTC. --
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Using runtime network id azure-iot-edge
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Initializing the module runtime...
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Finished initializing the module runtime.
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Configuring certificates...
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Finished configuring certificates.
Jul 19 06:13:00 artik iotedged[3484]: 2018-07-19T06:13:00Z [INFO] - Initializing hsm...
**Jul 19 06:13:18 artik iotedged[3484]: 2018-07-19T06:13:18Z [ERR!] - An hsm error occurred.
Jul 19 06:13:18 artik systemd[1]: iotedge.service: Failed with result 'exit-code'.**
Jul 19 06:13:18 artik iotedged[3498]: 2018-07-19T06:13:18Z [INFO] - Starting Azure IoT Edge Security Daemon
Jul 19 06:13:19 artik iotedged[3498]: 2018-07-19T06:13:18Z [INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
Jul 19 06:13:19 artik iotedged[3498]: 2018-07-19T06:13:18Z [INFO] - Using config file: /etc/iotedge/config.yaml

**[root@artik ~]# iotedge list
gets hang.**

Please suggest.

**Comment by darobs** [comment]
Hello @raviinroorkee-7,

I can't tell much from this failure as is, but this is indicating it's failing in the HSM library, which is the Hardware Security Module.  This is a separate library which contains the security implementation.

The first thing to try is running `journalctl` **without** the `-u iotedge` - as the service is ending, some logs aren't always captured as part of the "iotedge" unit.  That might give me more to go on.

I don't know much about the ARTIK board, but my first guess is that this library is having some trouble with creating the certificates needed for quickstart. This looks like a secure board, so it might not like some of the things we're doing in the reference HSM library.

Some other things to look at: 
`dpkg-query -s libssl1.0.2` 
- we currently link to libssl1.0 and link with version 1.0.2m on the ARM platform.  There might be some incompatibility issues.

`ls /var/lib/iotedge/hsm/*`
- here should be 3 directories, `cert_keys`, `certs`, and `enc_keys`.  In `cert_keys` and `certs` you should expect to see at least 3 files there, starting with "device_ca_alias", "edge_owner_ca", "iotedged-workload-ca".  In `enc_keys`, you should expect to see a file starting with "edgelet-master".  If you don't have all of these files, that will give us an idea where it's failing.
 

Turning on debug logging on the daemon might help:

`sudo systemctl edit iotedge.service`

Add the following:

[Service]
Environment="IOTEDGE_LOG=edgelet=debug"

If this doesn't give us enough information, we can rebuild the HSM library with debugging turned on, and that will give us even more information.

**Comment by raviinroorkee-7** [comment]
Hi ,
Here is the observation  -
**1)**
**[root@artik hsm]# journalctl -r**
-- Logs begin at Wed 2018-07-25 05:53:27 UTC, end at Wed 2018-07-25 06:36:15 UTC. --
Jul 25 06:36:15 artik kernel: tx_buf_size 1536
Jul 25 06:36:15 artik kernel: EVENT:  AMSDU_AGGR_CTRL 1744
Jul 25 06:36:15 artik kernel: wlan0: 1532500575.028211 : Event: 0x42
Jul 25 06:35:54 artik kernel: tx_buf_size 0
Jul 25 06:35:54 artik kernel: EVENT:  AMSDU_AGGR_CTRL 0
Jul 25 06:35:54 artik kernel: wlan0: 1532500554.218385 : Event: 0x42
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Initializing hsm...
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Finished configuring certificates.
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Configuring certificates...
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Finished initializing the module runtime.
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Initializing the module runtime...
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Using runtime network id azure-iot-edge
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Version - 1.0.0 (52ef77db24126bf473265fc09c53d35290a2dd6b)
Jul 25 06:35:45 artik iotedged[5662]: 2018-07-25T06:35:45Z [INFO] - Starting Azure IoT Edge Security Daemon
J**ul 25 06:35:45 artik systemd[1]: iotedge.service: Failed with result 'exit-code'.
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_crypto.c:hsm_client_crypto_init:43) Could
 not create store. Error code 1949
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:hsm_provision_edge_certificates:1
838) Failure generating required HSM certificates
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c:edge_hsm_client_store_create_pki_
cert_internal:2433) Could not create PKI certificate and key for edge_owner_ca
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_pki_cert_and_key_helper:1035)
 Could not generate private key for certificate create request
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:generate_cert_key:861) Error writing p
rivate key to file /var/lib/iotedge/hsm/cert_keys/edge_owner_cav0cQJsrFHjxosiOJDer2oKf-O45ZXKVJrO5WFWtFKe0_.key.pem
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] (/project/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:write_private_key_file:507) Failure op
ening key file for writing for /var/lib/iotedge/hsm/cert_keys/edge_owner_cav0cQJsrFHjxosiOJDer2oKf-O45ZXKVJrO5WFWtFKe0_.key.pem. Errno 13, Permission denied
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] -         caused by: HSM Init failure: 44
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] -         caused by: HSM failure
Jul 25 06:35:45 artik iotedged[5635]: 2018-07-25T06:35:45Z [ERR!] - An hsm error occurred.**
Jul 25 06:35:37 artik kernel: uap0: CMD_RESP (1532500537.791923): 0x80b3, result 0, len 22, seqno 0x106b
Jul 25 06:35:37 artik kernel: uap0: DNLD_CMD (1532500537.791662): 0xb3, act 0x0, len 8, seqno 0x106b
Jul 25 06:35:37 artik kernel: uap0: QUEUE_CMD: cmd=0xb3 is queued

**2)**
I do not have required files in /var/lib/iotedge/hsm -
**[root@artik hsm]# tree
.
├── cert_keys
│   └── edge_owner_cav0cQJsrFHjxosiOJDer2oKf-O45ZXKVJrO5WFWtFKe0_.key.pem
├── certs
│   └── edge_owner_cav0cQJsrFHjxosiOJDer2oKf-O45ZXKVJrO5WFWtFKe0_.cert.pem
└── enc_keys**

Please suggest.

Regards,
Ravi

**Comment by myagley** [comment]
Hi Ravi. It looks like this is a permissions issue with that directory. This is how it should look:

```
$ ls -al /var/lib/iotedge/
total 16
drwxr-xr-x  4 iotedge iotedge 4096 Jun 27 17:25 .
drwxr-xr-x 50 root    root    4096 May 24 02:35 ..
drwxr-xr-x  2 iotedge iotedge 4096 Jun 27 17:25 cache
drwxr-xr-x  5 iotedge iotedge 4096 Jun 18 18:05 hsm
```

This directory is created when the deb package is installed and chown'd as part of the `postinst`. I'm guessing that this directory may still be owned as root?

**Comment by raviinroorkee-7** [comment]
Thanks for help. That was the same issue as you mentioned. However I could not get why this happened at first place.

**Comment by myagley** [comment]
Is this still an issue? These permissions get setup as part of the `postinst` step in the debian package install. Is it possible an error was thrown during installation?

**Comment by raviinroorkee-7** [comment]
No. Its solved now. We can close the issue.
