### ISSUE TITLE
Cannot provision device - HTTP request error

### ISSUE THREAD

**Issue by ZacMelendez** [Azure/iotedge#5419]
I'm attemping to set up a new edge device behind my company proxy.

The device is running Debian 9 (stretch), and came without any traces of Moby/Docker, or any Azure IoT packages. 

I followed the Microsoft documentation for setting up [IoT Edge in Linux](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge?view=iotedge-2020-11), as well as setting up [devices behind a proxy](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2020-11#install-iot-edge-through-a-proxy).

We have other types of devices in our offices which are running an older version of Iot Edge (1.0), and are able to connect to the IoT Hub perfectly fine.

But after following every step in the two links above, these are the outputs of logs from the device:

`sudo journalctl -fu aziot-edged`
-- Logs begin at Wed 2021-08-25 15:24:23 EDT. --
Aug 25 15:56:16 Moxa aziot-edged[16355]: 2021-08-25T19:56:16Z [WARN] -         caused by: HTTP request error
Aug 25 15:56:16 Moxa aziot-edged[16355]: 2021-08-25T19:56:16Z [WARN] -         caused by: connection error: Connection reset by peer (os error 104)
Aug 25 15:56:16 Moxa aziot-edged[16355]: 2021-08-25T19:56:16Z [WARN] - Requesting device reprovision.
Aug 25 15:56:22 Moxa aziot-edged[16355]: 2021-08-25T19:56:22Z [WARN] - The reprovisioning operation failed
Aug 25 15:56:27 Moxa aziot-edged[16355]: 2021-08-25T19:56:27Z [INFO] - Obtaining edge device provisioning data...
Aug 25 15:56:27 Moxa aziot-edged[16355]: 2021-08-25T19:56:27Z [WARN] - The daemon could not start up successfully: Could not retrieve device information
Aug 25 15:56:27 Moxa aziot-edged[16355]: 2021-08-25T19:56:27Z [WARN] -         caused by: HTTP request error
Aug 25 15:56:27 Moxa aziot-edged[16355]: 2021-08-25T19:56:27Z [WARN] -         caused by: connection error: Connection reset by peer (os error 104)
Aug 25 15:56:27 Moxa aziot-edged[16355]: 2021-08-25T19:56:27Z [WARN] - Requesting device reprovision.
Aug 25 15:56:32 Moxa aziot-edged[16355]: 2021-08-25T19:56:32Z [WARN] - The reprovisioning operation failed
Aug 25 15:56:37 Moxa aziot-edged[16355]: 2021-08-25T19:56:37Z [INFO] - Obtaining edge device provisioning data...
Aug 25 15:56:37 Moxa aziot-edged[16355]: 2021-08-25T19:56:37Z [WARN] - The daemon could not start up successfully: Could not retrieve device information
Aug 25 15:56:37 Moxa aziot-edged[16355]: 2021-08-25T19:56:37Z [WARN] -         caused by: HTTP request error
Aug 25 15:56:37 Moxa aziot-edged[16355]: 2021-08-25T19:56:37Z [WARN] -         caused by: connection error: Connection reset by peer (os error 104)
Aug 25 15:56:37 Moxa aziot-edged[16355]: 2021-08-25T19:56:37Z [WARN] - Requesting device reprovision.
Aug 25 15:56:37 Moxa aziot-edged[16355]: 2021-08-25T19:56:37Z [WARN] - The reprovisioning operation failed
Aug 25 15:56:42 Moxa aziot-edged[16355]: 2021-08-25T19:56:42Z [INFO] - Obtaining edge device provisioning data...
Aug 25 15:56:43 Moxa aziot-edged[16355]: 2021-08-25T19:56:43Z [WARN] - The daemon could not start up successfully: Could not retrieve device information
Aug 25 15:56:43 Moxa aziot-edged[16355]: 2021-08-25T19:56:43Z [WARN] -         caused by: HTTP request error
Aug 25 15:56:43 Moxa aziot-edged[16355]: 2021-08-25T19:56:43Z [WARN] -         caused by: connection error: Connection reset by peer (os error 104)
Aug 25 15:56:43 Moxa aziot-edged[16355]: 2021-08-25T19:56:43Z [WARN] - Requesting device reprovision.
Aug 25 15:56:48 Moxa aziot-edged[16355]: 2021-08-25T19:56:48Z [WARN] - The reprovisioning operation failed
Aug 25 15:56:53 Moxa aziot-edged[16355]: 2021-08-25T19:56:53Z [INFO] - Obtaining edge device provisioning data...
Aug 25 15:56:53 Moxa aziot-edged[16355]: 2021-08-25T19:56:53Z [WARN] - The daemon could not start up successfully: Could not retrieve device information
Aug 25 15:56:53 Moxa aziot-edged[16355]: 2021-08-25T19:56:53Z [WARN] -         caused by: HTTP request error
Aug 25 15:56:53 Moxa aziot-edged[16355]: 2021-08-25T19:56:53Z [WARN] -         caused by: connection error: Connection reset by peer (os error 104)
Aug 25 15:56:53 Moxa aziot-edged[16355]: 2021-08-25T19:56:53Z [WARN] - Requesting device reprovision.

`sudo journalctl -fu aziot-identityd`
-- Logs begin at Wed 2021-08-25 15:24:23 EDT. --
Aug 25 15:59:10 Moxa aziot-identityd[22779]: 2021-08-25T19:59:10Z [INFO] - Provisioning starting. Reason: Startup
Aug 25 15:59:10 Moxa aziot-identityd[22779]: 2021-08-25T19:59:10Z [INFO] - Updated device info for us-rkhl-211.
Aug 25 15:59:10 Moxa aziot-identityd[22779]: 2021-08-25T19:59:10Z [INFO] - Provisioning complete.
Aug 25 15:59:10 Moxa aziot-identityd[22779]: 2021-08-25T19:59:10Z [INFO] - Identity reconciliation started. Reason: Startup
Aug 25 15:59:10 Moxa aziot-identityd[22779]: 2021-08-25T19:59:10Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: internal error
Aug 25 15:59:10 Moxa aziot-identityd[22779]: 2021-08-25T19:59:10Z [ERR!] - service encountered an error
Aug 25 15:59:10 Moxa aziot-identityd[22779]: 2021-08-25T19:59:10Z [ERR!] - caused by: internal error
Aug 25 15:59:10 Moxa systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 15:59:10 Moxa systemd[1]: aziot-identityd.service: Unit entered failed state.
Aug 25 15:59:10 Moxa systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Aug 25 15:59:15 Moxa systemd[1]: aziot-identityd.service: Service hold-off time over, scheduling restart.
Aug 25 15:59:15 Moxa systemd[1]: Stopped Azure IoT Identity Service.
Aug 25 15:59:15 Moxa systemd[1]: Started Azure IoT Identity Service.
Aug 25 15:59:15 Moxa aziot-identityd[22827]: 2021-08-25T19:59:15Z [INFO] - Starting service...
Aug 25 15:59:15 Moxa aziot-identityd[22827]: 2021-08-25T19:59:15Z [INFO] - Version - 1.2.2
Aug 25 15:59:15 Moxa aziot-identityd[22827]: 2021-08-25T19:59:15Z [INFO] - Detected HTTPS proxy server http://proxy.[company_name].net/
Aug 25 15:59:15 Moxa aziot-identityd[22827]: 2021-08-25T19:59:15Z [INFO] - Provisioning starting. Reason: Startup
Aug 25 15:59:15 Moxa aziot-identityd[22827]: 2021-08-25T19:59:15Z [INFO] - Updated device info for us-rkhl-211.
Aug 25 15:59:15 Moxa systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 15:59:15 Moxa systemd[1]: aziot-identityd.service: Unit entered failed state.
Aug 25 15:59:15 Moxa systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Aug 25 15:59:20 Moxa systemd[1]: aziot-identityd.service: Service hold-off time over, scheduling restart.
Aug 25 15:59:20 Moxa systemd[1]: Stopped Azure IoT Identity Service.
Aug 25 15:59:20 Moxa systemd[1]: Started Azure IoT Identity Service.
Aug 25 15:59:20 Moxa aziot-identityd[22834]: 2021-08-25T19:59:20Z [INFO] - Starting service...
Aug 25 15:59:20 Moxa aziot-identityd[22834]: 2021-08-25T19:59:20Z [INFO] - Version - 1.2.2
Aug 25 15:59:20 Moxa aziot-identityd[22834]: 2021-08-25T19:59:20Z [INFO] - Detected HTTPS proxy server http://proxy.[company_name].net/
Aug 25 15:59:20 Moxa aziot-identityd[22834]: 2021-08-25T19:59:20Z [INFO] - Provisioning starting. Reason: Startup
Aug 25 15:59:20 Moxa systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 15:59:20 Moxa systemd[1]: aziot-identityd.service: Unit entered failed state.
Aug 25 15:59:20 Moxa systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.

`sudo journalctl -xe`
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [INFO] - Provisioning starting. Reason: Startup
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [INFO] - Updated device info for us-rkhl-211.
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [INFO] - Provisioning complete.
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [INFO] - Identity reconciliation started. Reason: Startup
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: internal error
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] - service encountered an error
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] - caused by: internal error
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] - caused by: could not parse device information state
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] - caused by: missing field `hub_name`
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] -    0: <unknown>
Aug 25 16:04:04 Moxa systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 16:04:04 Moxa systemd[1]: aziot-identityd.service: Unit entered failed state.
Aug 25 16:04:04 Moxa systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Aug 25 16:04:09 Moxa systemd[1]: aziot-identityd.service: Service hold-off time over, scheduling restart.
Aug 25 16:04:09 Moxa systemd[1]: Stopped Azure IoT Identity Service.
Subject: Unit aziot-identityd.service has finished shutting down
Defined-By: systemd
Support: https://www.debian.org/support

Unit aziot-identityd.service has finished shutting down.
Aug 25 16:04:09 Moxa systemd[1]: Closed Azure IoT Identity Service API socket.
Subject: Unit aziot-identityd.socket has finished shutting down
Defined-By: systemd
Support: https://www.debian.org/support

Unit aziot-identityd.socket has finished shutting down.
Aug 25 16:04:09 Moxa systemd[1]: Stopping Azure IoT Identity Service API socket.
Subject: Unit aziot-identityd.socket has begun shutting down
Defined-By: systemd
Support: https://www.debian.org/support

Unit aziot-identityd.socket has begun shutting down.
Aug 25 16:04:09 Moxa systemd[1]: Starting Azure IoT Identity Service API socket.
Subject: Unit aziot-identityd.socket has begun start-up
Defined-By: systemd
Support: https://www.debian.org/support

Unit aziot-identityd.socket has begun starting up.
Aug 25 16:04:09 Moxa systemd[1]: Listening on Azure IoT Identity Service API socket.
Subject: Unit aziot-identityd.socket has finished start-up
Defined-By: systemd
Support: https://www.debian.org/support

Unit aziot-identityd.socket has finished starting up.

The start-up result is done.
Aug 25 16:04:09 Moxa aziot-edged[16355]: 2021-08-25T20:04:09Z [WARN] - The reprovisioning operation failed
Aug 25 16:04:09 Moxa systemd[1]: Started Azure IoT Identity Service.
Subject: Unit aziot-identityd.service has finished start-up
Defined-By: systemd
Support: https://www.debian.org/support

Unit aziot-identityd.service has finished starting up.

The start-up result is done.
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [INFO] - Starting service...
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [INFO] - Version - 1.2.2
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [INFO] - Detected HTTPS proxy server http://proxy.[company_name].net/
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [INFO] - Provisioning starting. Reason: Startup
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [INFO] - Updated device info for us-rkhl-211.
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [INFO] - Provisioning complete.
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [INFO] - Identity reconciliation started. Reason: Startup
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: internal error
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [ERR!] - service encountered an error
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [ERR!] - caused by: internal error
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [ERR!] - caused by: could not parse device information state
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [ERR!] - caused by: missing field `hub_name`
Aug 25 16:04:09 Moxa aziot-identityd[25931]: 2021-08-25T20:04:09Z [ERR!] -    0: <unknown>
Aug 25 16:04:09 Moxa systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 16:04:09 Moxa systemd[1]: aziot-identityd.service: Unit entered failed state.
Aug 25 16:04:09 Moxa systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Aug 25 16:04:11 Moxa sudo[25881]: pam_unix(sudo:session): session closed for user root
Aug 25 16:04:11 Moxa sudo[25937]:     moxa : TTY=pts/0 ; PWD=/home/moxa ; USER=root ; COMMAND=/bin/journalctl -xe
Aug 25 16:04:11 Moxa sudo[25937]: pam_unix(sudo:session): session opened for user root by moxa(uid=0)

I'm unsure of where the error is coming from, it seems "caused by: missing field `hub_name` is the main issue, but it also is not specified where this will need to go.

Any insights would be helpful, and if I need to include any other information, please let me know, it's my first time submitting an issue.

Thanks

**Comment by yophilav** [comment]
Hi @ZacMelendez !

Thank you for your question! Hmmm... I suspect there is a misconfiguration (mostly a typo) in the `/etc/aziot/config.toml`. 
Notably from the error:
```
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] - caused by: could not parse device information state
Aug 25 16:04:04 Moxa aziot-identityd[25885]: 2021-08-25T20:04:04Z [ERR!] - caused by: missing field hub_name
```
I'd make sure you are using the correct connection string, iothub hostname and device id. 

Once you verify that those are correct, please restart the iotedge service. 
To confirm everything will work correct, please run `iotedge check --verbose`. It should give you a more readable output on what maybe going wrong with the config.

Cheers,
Bear

**Comment by ZacMelendez** [comment]
Hey @yophilav

the config file doesn't have any fields that have those names, but either way, I removed the device in my IoT Hub, added a new one, and replaced the connection string. Here's my config.toml:

```
# ==============================================================================
# Hostname
# ==============================================================================
#
# Uncomment the next line to override the default hostname of this device.
#
# hostname = "my-device"


# ==============================================================================
# Parent hostname
# ==============================================================================
#
# If this is a Nested Edge device, uncomment the next line to set the
# parent hostname of this device.
#
# parent_hostname = "my-parent-device"


# ==============================================================================
# Trust bundle cert
# ==============================================================================
#
# If you have any trusted CA certificates required for Edge module communication,
# uncomment the next line and set the value to a file URI for
# the path of the file.
#
# trust_bundle_cert = "file:///var/secrets/trust-bundle.pem"


# ==============================================================================
# Provisioning
# ==============================================================================


# Optional auto reprovisioning mode
# ------------------------------------

# This property specifies the conditions under which the device attempts to
# automatically reprovision with the cloud. It is ignored if the device has
# been provisioned manually. One of the following values can be set:
# Dynamic:          Reprovision when the device detects that it may have
#                   been moved from one IoT Hub to another. This is the default.
# AlwaysOnStartup:  Reprovision when the device is rebooted or a crash causes
#                   the daemon(s) to restart.
# OnErrorOnly:      Never trigger device reprovisioning automatically.
#                   Device reprovisioning only occurs as fallback, if the device
#                   is unable to connect to IoT Hub during identity provisioning
#                   due to connectivity errors. This fallback behavior is implicit
#                   in Dynamic and AlwaysOnStartup modes as well.
#
# auto_reprovisioning_mode = Dynamic
#


# Provisioning configuration
# --------------------------

# Uncomment one block and replace the stub values with yours.

## Manual provisioning with connection string
#
 [provisioning]
 source = "manual"
 connection_string = "HostName=rhl-iot-dev.azure-devices.net;DeviceId=us-rkhl-211;SharedAccessKey=[access_key]="


## Manual provisioning with symmetric key
# [provisioning]
# source = "manual"
# iothub_hostname = "example.azure-devices.net"
# device_id = "my-device"
#
# [provisioning.authentication]
# method = "sas"
#
# device_id_pk = { value = "YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGU=" }     # inline key (base64), or...
# device_id_pk = { uri = "file:///var/secrets/device-id.key" }                  # file URI, or...
# device_id_pk = { uri = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" } # PKCS#11 URI


## Manual provisioning with X.509 certificate
# [provisioning]
# source = "manual"
# iothub_hostname = "example.azure-devices.net"
# device_id = "my-device"
#
# [provisioning.authentication]
# method = "x509"
#
# identity_cert = "file:///var/secrets/device-id.pem"                # file URI, or...
# identity_cert = { method = "est", common_name = "my-device" }      # dynamically issued via EST, or...
# identity_cert = { method = "local_ca", common_name = "my-device" } # dynamically issued by a local CA
#
# identity_pk = "file:///var/secrets/device-id.key.pem"              # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" # PKCS#11 URI


## DPS provisioning with symmetric key
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "symmetric_key"
# registration_id = "my-device"
#
# symmetric_key = { value = "YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGVudGl0eS1zZXJ2aWNlfGF6aW90LWlkZW50aXR5LXNlcg==" } # inline key (base64), or...
# symmetric_key = { uri = "file:///var/secrets/device-id.key" }                                                          # file URI, or...
# symmetric_key = { uri = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" }                                         # PKCS#11 URI


## DPS provisioning with X.509 certificate
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "x509"
# registration_id = "my-device"
#
# identity_cert = "file:///var/secrets/device-id.pem"                # file URI, or...
# identity_cert = { method = "est", common_name = "my-device" }      # dynamically issued via EST, or...
# identity_cert = { method = "local_ca", common_name = "my-device" } # dynamically issued by a local CA
#
# identity_pk = "file:///var/secrets/device-id.key.pem"              # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=device%20id?pin-value=1234" # PKCS#11 URI


## DPS provisioning with TPM
# [provisioning]
# source = "dps"
# global_endpoint = "https://global.azure-devices-provisioning.net"
# id_scope = "0ab1234C5D6"
#
# [provisioning.attestation]
# method = "tpm"
# registration_id = "my-device"


# ==============================================================================
# Cert issuance
# ==============================================================================
#
# If you configured any dynamically issued certs above, uncomment the block
# corresponding to the issuance method and replace the stub values with yours.


# Cert issuance via EST
# ---------------------

# [cert_issuance.est]
# trusted_certs = [
#     "file:///var/secrets/est-id-ca.pem",
# ]
#
# [cert_issuance.est.auth]
# username = "estuser"
# password = "estpwd"
#
# # EST ID cert already on device, or...
# identity_cert = "file:///var/secrets/est-id.pem"
#
# identity_pk = "file:///var/secrets/est-id.key.pem"            # file URI, or...
# identity_pk = "pkcs11:slot-id=0;object=est-id?pin-value=1234" # PKCS#11 URI
#
# # EST ID cert requested via EST bootstrap ID cert
# bootstrap_identity_cert = "file:///var/secrets/est-bootstrap-id.pem"
#
# bootstrap_identity_pk = "file:///var/secrets/est-bootstrap-id.key.pem"            # file URI, or...
# bootstrap_identity_pk = "pkcs11:slot-id=0;object=est-bootstrap-id?pin-value=1234" # PKCS#11 URI
#
# [cert_issuance.est.urls]
# default = "https://example.org/.well-known/est"


# Cert issuance via local CA
# --------------------------

# [cert_issuance.local_ca]
# cert = "file:///var/secrets/local-ca.pem"
#
# pk = "file:///var/secrets/local-ca.key.pem"            # file URI, or...
# pk = "pkcs11:slot-id=0;object=local-ca?pin-value=1234" # PKCS#11 URI


# ==============================================================================
# PKCS#11
# ==============================================================================
#
# If you used any PKCS#11 URIs above, uncomment the next block and
# replace the stub values with your PKCS#11 configuration.

# [aziot_keys]
# pkcs11_lib_path = "/usr/lib/libmypkcs11.so"
# pkcs11_base_slot = "pkcs11:slot-id=0?pin-value=1234"


# ==============================================================================
# Default Edge Agent
# ==============================================================================
#
# If you need to override the parameters of the default Edge Agent module,
# uncomment this section and replace the values in this section with your own.
#
# Note that the agent.config.createOptions field is specified as
# a TOML inline table. This format looks similar to JSON but it is not JSON.
# See https://toml.io/en/v1.0.0#inline-table for documentation.

 [agent]
 name = "edgeAgent"
 type = "docker"
# imagePullPolicy = "..."   # "on-create" or "never". Defaults to "on-create"

 [agent.config]
 image = "mcr.microsoft.com/azureiotedge-agent:1.2"
# createOptions = { HostConfig = { Binds = ["/iotedge/storage:/iotedge/storage"] } }

# [agent.config.auth]
# serveraddress = "example.azurecr.io"
# username = "username"
# password = "password"

 [agent.env]
 "RuntimeLogLevel" = "debug"
 "UpstreamProtocol" = "AmqpWs"
# "storageFolder" = "/iotedge/storage"
 "https_proxy" = "http://proxy.[company_name].net:80"

# ==============================================================================
# Daemon management and workload API endpoints
# ==============================================================================
#
# If you need to override the management and workload API endpoints,
# uncomment this section and replace the values in this section with your own.

# [connect]
# workload_uri = "unix:///var/run/iotedge/workload.sock"
# management_uri = "unix:///var/run/iotedge/mgmt.sock"
#
# [listen]
# workload_uri = "fd://aziot-edged.workload.socket"
# management_uri = "fd://aziot-edged.mgmt.socket"


# ==============================================================================
# Edge Agent watchdog
# ==============================================================================
#
# If you need to override the default Edge Agent watchdog settings,
# uncomment this section and replace the values with your own.
#
# [watchdog]
# max_retries = "infinite"   # the string "infinite" or a positive integer. Defaults to "infinite"


# ==============================================================================
# Edge CA certificate
# ==============================================================================
#
# If you have your own Edge CA certificate that you want all module certificates
# to be issued by, uncomment this section and replace the values with your own.
#
# [edge_ca]
# cert = "file:///var/secrets/edge-ca.pem"                # file URI
#
# pk = "file:///var/secrets/edge-ca.key.pem"              # file URI, or...
# pk = "pkcs11:slot-id=0;object=edge%20ca?pin-value=1234" # PKCS#11 URI


# ==============================================================================
# Edge CA certificate (Quickstart)
# ==============================================================================
#
# If you do not have your own Edge CA certificate that you want all
# module certificates to be issued by, you can uncomment this section and
# set the number of days for the lifetime of the auto-generated
# self-signed Edge CA certificate. Defaults to 90 days.
#
# SECURITY NOTE: this setting is NOT recommended for production usage. Please
# configure your own Edge CA certificate in the Edge CA certificate section
# above instead.
#
# [edge_ca]
# auto_generated_edge_ca_expiry_days = 90


# ==============================================================================
# Moby runtime
# ==============================================================================
#
# If you need to override the default Moby runtime configuration,
# uncomment this section and replace the values in this section with your own.

# [moby_runtime]
# uri = "unix:///var/run/docker.sock"
# network = "azure-iot-edge"
```

And I didn't include my `iotedge check --verbose` output as Microsoft themselves says doing that behind a proxy isn't conclusive, but here it is either way:

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
‼ host time is close to reference time - Warning
    Could not query NTP server
        caused by: could not receive NTP server response: Resource temporarily unavailable (os error 11)
        caused by: Resource temporarily unavailable (os error 11)
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
× host can connect to and perform TLS handshake with iothub AMQP port - Error
    Could not connect to rhl-iot-dev.azure-devices.net : could not complete TLS handshake
        caused by: tcp connect error: Connection timed out (os error 110)
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Could not connect to rhl-iot-dev.azure-devices.net : could not complete TLS handshake
        caused by: tcp connect error: Connection timed out (os error 110)

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
‼ configuration up-to-date with config.toml - Warning
    /etc/aziot/config.toml was modified after edged's config
    You must run 'iotedge config apply' to update edged's config with the latest config.toml
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
    docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35940->[proxy_ip_addr]:80: read: connection reset by peer.
    See 'docker run --help'.
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35940->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
‼ aziot-edge package is up-to-date - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
        caused by: error trying to connect: Connection timed out (os error 110)
× container time is close to host time - Error
    Could not query local time inside container
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35944->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
        caused by: docker returned exit code: 1, stderr = Error: No such object: edgeAgent
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub
× Agent image is valid and can be pulled from upstream - Error
    Failed to get edge Agent image
        caused by: docker returned exit code: 1, stderr = Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35946->[proxy_ip_addr]:80: read: connection reset by peer

Connectivity checks
-------------------
× container on the default network can connect to upstream  AMQP port - Error
    Container on the default network could not connect to rhl-iot-dev.azure-devices.net:5671
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35948->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to rhl-iot-dev.azure-devices.net:443
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35950->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
× container on the default network can connect to upstream MQTT port - Error
    Container on the default network could not connect to rhl-iot-dev.azure-devices.net:8883
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35952->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
× container on the IoT Edge module network can connect to upstream AMQP port - Error
    Container on the azure-iot-edge network could not connect to rhl-iot-dev.azure-devices.net:5671
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35954->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to rhl-iot-dev.azure-devices.net:443
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35956->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
× container on the IoT Edge module network can connect to upstream MQTT port - Error
    Container on the azure-iot-edge network could not connect to rhl-iot-dev.azure-devices.net:8883
        caused by: docker returned exit code: 125, stderr = Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.2.3' locally
                   docker: Error response from daemon: Get https://mcr.microsoft.com/v2/: proxyconnect tcp: read tcp [device_ip_addr]:35958->[proxy_ip_addr]:80: read: connection reset by peer.
                   See 'docker run --help'.
18 check(s) succeeded.
5 check(s) raised warnings.
13 check(s) raised errors.
```

Based off this, it seems to be a proxy error? But I double checked the proxy address and it is correct as well.

**Comment by ZacMelendez** [comment]
Unsure of why, but downgrading to IoT Edge 1.1 solved the issue. Closing for now
