### ISSUE TITLE
IoT edge does not start after reboot

### ISSUE THREAD

**Issue by thecyrusdh** [Azure/iotedge#5439]
After machine reboot IoT edge does not start containers (edgeAgent, edgeHub, custom containers)

docker ps command does not return any containers.

iotedge system logs returns the following 

`aziot-edged[1127]: 2021-08-25T05:15:01Z [WARN] - The daemon could not start up successfully: Could not retrieve device information
aziot-edged[1127]: 2021-08-25T05:15:01Z [WARN] -         caused by: HTTP response error: [400 Bad Request] {"message":"device identity not found"}
aziot-identityd[1165]: 2021-08-25T05:15:01Z [INFO] - <-- POST /identities/device?api-version=2020-09-01 {"content-type": "application/json", "host": "2f72756e2f617a696f742f6964656e74697479642e736f636b:0", "content-length": "16"}
aziot-identityd[1165]: 2021-08-25T05:15:01Z [INFO] - !!! device identity not found
aziot-identityd[1165]: 2021-08-25T05:15:01Z [INFO] - --> 400 {"content-type": "application/json"}
aziot-edged[1127]: 2021-08-25T05:15:06Z [WARN] - Retrying getting edge device provisioning information.
aziot-edged[1127]: 2021-08-25T05:15:06Z [INFO] - Obtaining edge device provisioning data...`

iotedge check returns the following warning
`‼ host time is close to reference time - Warning
    Could not query NTP server
        caused by: could not receive NTP server response: Resource temporarily unavailable (os error 11)
        caused by: Resource temporarily unavailable (os error 11)
`

The virtual machine checks and sets the NTP at the startup. 

The only way to runs the containers is to execute the command `iotedge config apply` manually.

The IoT Edge currently in use is 1.2.1.

Any suggestion to solve the issue?
Thanks

**Comment by and-rewsmith** [comment]
@ancaantochi This looks like a potential bug in 1.2. Have you seen this before on machine reboot?

**Comment by thecyrusdh** [comment]
Hi @and-rewsmith @ancaantochi  
do you think that updating the IoT Edge to last release (version 1.2.3) should avoid this problem? Can you suggest me a workaround in order to start all services/containers when the machine reboots? 
Thanks

**Comment by and-rewsmith** [comment]
@thecyrusdh I tried this scenario out myself. Started with 1.2.3 edge device with connection string (not dps). On reboot every module came back up as expected. Although I do not expect 1.2.3 to fix your particular issue as there haven't been any relevant changes from 1.2.2 -> 1.2.3.

From the logs it seems the problem is that the device identity doesn't exist.
```
aziot-edged[1127]: 2021-08-25T05:15:01Z [WARN] - The daemon could not start up successfully: Could not retrieve device information 
aziot-edged[1127]: 2021-08-25T05:15:01Z [WARN] - caused by: HTTP response error: [400 Bad Request] {"message":"device identity not found"}
aziot-identityd[1165]: 2021-08-25T05:15:01Z [INFO] - <-- POST /identities/device?api-version=2020-09-01 {"content-type": "application/json", "host": "2f72756e2f617a696f742f6964656e74697479642e736f636b:0", "content-length": "16"}
 aziot-identityd[1165]: 2021-08-25T05:15:01Z [INFO] - !!! device identity not found
```

Since it works after `iotedge config apply` there is definitely something wrong. If I can get a repro myself then I can give you a better workaround. Can you address the following please:
1. Gather `aziot-*`  service logs from around the timeframe the reboot happens
2. What is your device provisioning method? (dps or connection string)
3. Assuming this is running as a single-node device rather than a hierarchical topology?
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11
4. Does this always reproduce on every reboot, or just some? Assuming when the problem occurs it never recovers.

**Comment by thecyrusdh** [comment]
Hi @and-rewsmith,

try to report some answers :)
1) these are the logs for aziot-* services after reboot (I have changed some info with xxxxyyy)
`-- Reboot --
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Starting Azure IoT Edge daemon management socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Starting Azure IoT Certificates Service API socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Starting Azure IoT Edge daemon workload socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Starting Azure IoT Identity Service API socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Starting Azure IoT TPM Service API socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Starting Azure IoT Keys Service API socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Listening on Azure IoT Edge daemon management socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Listening on Azure IoT Certificates Service API socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Listening on Azure IoT Edge daemon workload socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Listening on Azure IoT Identity Service API socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Listening on Azure IoT Keys Service API socket.
Sep 06 06:01:27 xxxxxyyyyyy systemd[1]: Listening on Azure IoT TPM Service API socket.
Sep 06 06:01:31 xxxxxyyyyyy systemd[1]: Started Azure IoT Edge daemon.
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Starting Azure IoT Edge Module Runtime
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Version - 1.2.1
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Initializing the module runtime...
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Initializing module runtime...
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Using runtime network id azure-iot-edge
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Successfully initialized module runtime
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Finished initializing the module runtime.
Sep 06 06:01:31 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:31Z [INFO] - Obtaining edge device provisioning data...
Sep 06 06:01:31 xxxxxyyyyyy systemd[1]: Started Azure IoT Identity Service.
Sep 06 06:01:31 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:31Z [INFO] - Starting service...
Sep 06 06:01:31 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:31Z [INFO] - Version - 1.2.0
Sep 06 06:01:31 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:31Z [INFO] - Provisioning starting. Reason: Startup
Sep 06 06:01:31 xxxxxyyyyyy systemd[1]: Started Azure IoT Keys Service.
Sep 06 06:01:31 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:31Z [INFO] - Starting service...
Sep 06 06:01:31 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:31Z [INFO] - Version - 1.2.0
Sep 06 06:01:31 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:31Z [INFO] - Loaded libaziot-keys with version 0x02000000
Sep 06 06:01:31 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:31Z [INFO] - Starting server...
Sep 06 06:01:31 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:31Z [INFO] - <-- GET /key/device-id?api-version=2020-09-01 {"host": "keyd.sock"}
Sep 06 06:01:31 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:31Z [INFO] - --> 200 {"content-type": "application/json"}
Sep 06 06:01:32 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:32Z [INFO] - <-- POST /sign?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "374"}
Sep 06 06:01:32 xxxxxyyyyyy aziot-keyd[1215]: 2021-09-06T06:01:32Z [INFO] - --> 200 {"content-type": "application/json"}
Sep 06 06:01:42 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:42Z [WARN] - Failed to reprovision device. Running offline. Reprovisioning failure reason: DPS client error.
Sep 06 06:01:42 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:42Z [INFO] - Starting server...
Sep 06 06:01:42 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:42Z [INFO] - <-- POST /identities/device?api-version=2020-09-01 {"content-type": "application/json", "host": "xxxxxxxxxxxxxxxxxxx:0", "content-length": "16"}
Sep 06 06:01:42 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:42Z [INFO] - !!! device identity not found
Sep 06 06:01:42 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:42Z [INFO] - --> 400 {"content-type": "application/json"}
Sep 06 06:01:42 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:42Z [WARN] - The daemon could not start up successfully: Could not retrieve device information
Sep 06 06:01:42 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:42Z [WARN] -         caused by: HTTP response error: [400 Bad Request] {"message":"device identity not found"}
Sep 06 06:01:47 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:47Z [WARN] - Retrying getting edge device provisioning information.
Sep 06 06:01:47 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:47Z [INFO] - Obtaining edge device provisioning data...
Sep 06 06:01:47 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:47Z [WARN] - The daemon could not start up successfully: Could not retrieve device information
Sep 06 06:01:47 xxxxxyyyyyy aziot-edged[1159]: 2021-09-06T06:01:47Z [WARN] -         caused by: HTTP response error: [400 Bad Request] {"message":"device identity not found"}
Sep 06 06:01:47 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:47Z [INFO] - <-- POST /identities/device?api-version=2020-09-01 {"content-type": "application/json", "host": "xxxxxxxxxxxxxxxxxxx:0", "content-length": "16"}
Sep 06 06:01:47 xxxxxyyyyyy aziot-identityd[1195]: 2021-09-06T06:01:47Z [INFO] - !!! device identity not found`

From the logs it seems to be a problem when the device try to re-provision

2) Device provisioning method is DPS with symmetric key

3) We don't have an hierarchical structure... there is just a VM (with IoT Edge) running on a NAS.
The IoT Edge version installed is 1.2.1.
Executing the iotedge check there are these warnings 
![image](https://user-images.githubusercontent.com/9257354/132177577-6b3d7897-16cc-4b09-bc26-1805940f7b11.png)

and the command seems to be blocked to this point (no other feedback)
![image](https://user-images.githubusercontent.com/9257354/132177649-7d742771-7574-4cd5-be0b-13928b5e424f.png)

4) This issue happen after each reboot.

5) The VM time is set via NTP, there is an automatic job which runs every xx minutes in order to sync the time.
Concerning the network, the VM is not connected directly to internet but traffic is forwarded through a VPN to internet which enables all the ports and url required to IoT Edge to communicate with the IoT Hub, docker registry, etc. using ports 8883, 443, 567. Anyway, after the reboot, executing the command `iotedge config apply` manually , everything works fine (so I think that it isn't a network problem)

Thanks for your support :)

**Comment by thecyrusdh** [comment]
Hi @and-rewsmith, do you have any update?

**Comment by and-rewsmith** [comment]
@thecyrusdh This issue looks very similar to https://github.com/Azure/iotedge/issues/4964. Could you try upgrading aziot-edge, aziot-identity-service, and system module (hub and agent) to 1.2.3?

**Comment by asergaz** [comment]
Relates with: https://docs.microsoft.com/en-us/answers/questions/532856/index.html

**Comment by and-rewsmith** [comment]
@thecyrusdh Did this solve the issue?

**Comment by thecyrusdh** [comment]
Hi @and-rewsmith, on a fresh installation of IoT Edge 1.2.3. It seems that work. We are currently monitoring the status in order to check if the problem appears again.
We have another problem on another edge where we have upgraded IoT Edge from version 1.2.1 to 1.2.3.
The problem is related to the storageFolder option (this is the guide followed [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-2020-11](url) . The edgeAgent cannot start and the logs give this error:
`<0> 2021-09-16 11:19:10.068 +00:00 [FTL] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Fatal error reading the Agent's configuration.
System.UnauthorizedAccessException: Access to the path '/iotedge/storage/edgeAgent' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.GetOrCreateDirectoryPath(String baseDirectoryPath, String directoryName) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 433
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 111
`
Any advice? 
Thanks :)

**Comment by and-rewsmith** [comment]
@thecyrusdh Can you please open a new issue though? It is team policy that one problem is handled per github issue. This makes it easier for other users to troubleshoot their problems.
