### ISSUE TITLE
edgeAgent/edgeHub storage directory is persisted on the host warning but files are persisted on the host filesystem

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#5441]
We have an IoT Edge 1.1 solution running on Windows VM's.

I have configured host storage for both edgeAgent and edgeHub.  These are extracts from the deployment, as it is available in IoT Hub:

```json
"edgeAgent": {
    "type": "docker",
    "env": {
        "storageFolder": {
            "value": "c:\\iotedge\\edgeAgent\\storage"
        }
    },
    "settings": {
        "image": "mcr.microsoft.com/azureiotedge-agent:1.1.3",
        "createOptions": "{\"HostConfig\":{\"Binds\":[\"C:\\\\ProgramData\\\\VesselGateway\\\\systemmodules\\\\storage:c:\\\\iotedge\\\\edgeAgent\\\\storage\"]}}"
    }
},
"edgeHub": {
    "type": "docker",
    "status": "running",
    "restartPolicy": "always",
    "env": {
        "storageFolder": {
        "value": "c:\\iotedge\\edgeHub\\storage"
    }
},
"settings": {
    "image": "mcr.microsoft.com/azureiotedge-hub:1.1.3",
    "createOptions": "{\"HostConfig\":{\"Binds\":[\"C:\\\\ProgramData\\\\VesselGateway\\\\systemmodules\\\\storage:c:\\\\iotedge\\\\edgeHub\\\\storage\"],\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
    }
}
```

We see this warning when running `iotedge check`

![image](https://user-images.githubusercontent.com/3605786/131536055-4fb79765-51cb-45ae-91c8-abed8b5d3758.png)

However, we also do see files in the `c:\ProgramData\VesselGateway\systemmodules\storage` folder.  

Another related question: how does this (host storage) affect the buffering that is done by iot edge ?  Suppose there's no connection to the IoT Hub, edgeHub will buffer the messages and send them to IoT Hub once connection is established.  Will those buffered messages be written to the configured directory on the host' filesystem ?

-> Is there something missing to make sure that module storage is persisted on the host filesystem ?
-> Is there an issue with iotedge check, and is this warning erroneously displayed  ?

**Comment by and-rewsmith** [comment]
Thanks for the bug report! Looks like an issue if files are indeed showing up on the host. Some comments below.

> Another related question: how does this (host storage) affect the buffering that is done by iot edge ? Suppose there's no connection to the IoT Hub, edgeHub will buffer the messages and send them to IoT Hub once connection is established. Will those buffered messages be written to the configured directory on the host' filesystem ?

Your understanding is correct.

> Is there something missing to make sure that module storage is persisted on the host filesystem ?

What is the naming scheme of these files? I am assuming if files are showing up then storage should work as expected.

> Is there an issue with iotedge check, and is this warning erroneously displayed ?

Yep seems like an issue with iotedge check.

**Comment by fgheysels** [comment]
There are multiple sorts of files in that directory.
For edgeAgent, we have *.sst and *.dbtmp files
![image](https://user-images.githubusercontent.com/3605786/131969508-9673a0d1-d8bd-41ca-8033-6d000f2995f3.png)


For edgeHub, we also have *.sst, *.dbtmp and *.log files

![image](https://user-images.githubusercontent.com/3605786/131969692-f389a062-c3f4-4501-a06b-98d99b3b2b69.png)

**Comment by and-rewsmith** [comment]
@fgheysels EdgeAgent will create an `edgeAgent` directory inside the `storageFolder` you specify. So that folder (`c:\iotedge\edgeAgent\storage\edgeAgent`) is what you want to mount to remove the warning.

I think ideally iotedge check should not complain if the custom storage folder is what's mounted. I'll follow up with others to see if we can fix it.

**Comment by fgheysels** [comment]
@and-rewsmith : you mean that I should change the mounting specification to something like this:
![image](https://user-images.githubusercontent.com/3605786/135293833-c560112d-e45a-4052-a6c0-ccdb21009169.png)
As you can see, I've added the `edgeAgent` folder to the storage folder in the binding.
However, `iotedge check` still gives this error:
![image](https://user-images.githubusercontent.com/3605786/135294091-538ff934-ad9e-4f03-bb16-84616e3476ce.png)

**Comment by and-rewsmith** [comment]
Yes you are correct. Something is broken. Although I did a test on a linux machine and it worked like expected. Right now I am thinking it only affects Windows.

**Comment by and-rewsmith** [comment]
@fgheysels This issue has turned up another problem related to the storageFolder and our documentation (at least on linux where I tested). It seems that the docs give an example of setting the storage folder to "/iotedge/storage/". This won't work because EdgeHub and EdgeAgent should only be able to write to paths beginning with /tmp.
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-2020-11

I setup a windows machine to debug the behavior you are seeing. I am running into the same sort of behavior I saw on linux though. Edge Agent does not have permissions to write to this custom location. From your screenshots of your sst folder though, you got past this somehow. Is there something I am missing here? Did you alter any host folder permissions?

**Comment by fgheysels** [comment]
@and-rewsmith  I haven't done anything specific to get past the issue you're facing.   We have scripted a deployment procedure for deploying iotedge.   That script just makes sure that the storage directory on the host filesystem exists (`c:\program data\vesselgateway\systemmodules\storage`).

**Comment by and-rewsmith** [comment]
@fgheysels Sorry for the run-around. I managed to get past it by adding the right permissions to the folder (all permissions for "all authenticated users") and reproduced your issue. I also got non /tmp `StorageFolder` paths to work on both linux and windows.

So now I am looking into what exactly is going wrong with the check. This is broken on Windows but not Linux.

**Comment by fgheysels** [comment]
Any news or update on this @and-rewsmith ?
