### ISSUE TITLE
iot edge 1.2: edgeHub env variable "MessageCleanupInterval" not wired?

### ISSUE THREAD

**Issue by arlotito** [Azure/iotedge#5447]
Based on some tests we did, the message store seems to be cleaned up every 30', regardless of the value of the env variable "MessageCleanupInterval".

Looking at the code [here](https://github.com/Azure/iotedge/blob/1c9b39a4bf00d88d619164f8332df414a56ba1da/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs#L189):
![image](https://user-images.githubusercontent.com/60540284/131656550-fbfc9dc5-b0e7-4bed-a2aa-a7d5c701e9e3.png)

...the cleanup interval "CheckCleanupTaskInterval" seems to be hard-coded and equal to 30', suggesting that the env variable "MessageCleanupInterval" is not wired yet.

Am I'm missing something here?

thanks!

**Comment by arlotito** [comment]
"MessageCleanupInterval" does not work as per previous message, while "MessageCleanupInterval**Secs**" does.
Maybe just a typo in the documentation?

**Comment by varunpuranik** [comment]
@arlotito - thanks for catching this, this is indeed a typo. We will fix it.
