### ISSUE TITLE
IoT Edge not so secure

### ISSUE THREAD

**Issue by rifaterdemsahin** [Azure/iotedge#5458]
Edge modules as IoT Edge servers need to get secured, which connects to various source systems. 
Should I develop a service that uses Azure App Id/Secrets/ Azure Key Vault and grab the secrets (e.g. api user/password, sql user/password) or is there an edge solution for that ?

I need a practical way not to store the secrets in the source code. And I expect the edge key vault to sync with the cloud key vault and the edge systems to use the key vault on the edge.

What is the best approach to use Key Vault from IoT Edge module ?

What we don't want 
- When the edge machines get stolen the IP gets stolen
- Not to save secrets to the git

Thanks

**Comment by and-rewsmith** [comment]
@rifaterdemsahin Yes, you are right. Our security story around secrets in the deployment file needs improvement. One thing to consider is that a direct method can be used to inject secrets into your modules at runtime.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient.invokedevicemethodasync?view=azure-dotnet#Microsoft_Azure_Devices_ServiceClient_InvokeDeviceMethodAsync_System_String_System_String_Microsoft_Azure_Devices_CloudToDeviceMethod_System_Threading_CancellationToken_

As for further protecting the edge machines against tampering, an HSM/TPM might be able to help in this area.
