### ISSUE TITLE
manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.1.6 not found

### ISSUE THREAD

**Issue by ksh7393** [Azure/iotedge#5473]
## Expected Behavior
After iotedge runtime install to 1.1.6 on a Ubuntu 18.04 box the command **sudo iotedge check** should not display any errors.

## Current Behavior
config.yaml has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.1.6' locally
    docker: Error response from daemon: manifest for mcr.microsoft.com/azureiotedge-diagnostics:1.1.6 not found: manifest unknown: manifest tagged by "1.1.6" is not found.
    See 'docker run --help'.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.Install iotedge on linux
2.Start iotedge
3.Check the configuration status using **sudo iotedge check**

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Check Above

```
</details>

### Device Information
* Host OS : Ubuntu 18.04
* Architecture : amd64
* Container OS : Linux containers 

### Runtime Versions
* aziot-edged [run `iotedge version`]:  1.1.6
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]:  1.0
* Docker/Moby [run `docker version`]: 20.10.8+azure

**Comment by arsing** [comment]
Copying @damonbarry's comment from the other issue:

>Yes, we're aware of this. (See #5473). We're working on publishing `mcr.microsoft.com/azureiotedge-diagnostics:1.1.6`. In the meantime, you can use the `--diagnostics-image-name mcr.microsoft.com/azureiotedge-diagnostics:1.1.5` option when you call `iotedge check`.

**Comment by yophilav** [comment]
@ksh7393 
Thank you for your wait! We have published the `mcr.microsoft.com/azureiotedge-diagnostics:1.1.6`. The `iotedge check` should be working properly now with 1.1.6 Runtime. 

Cheers,
Bear

**Comment by ksh7393** [comment]
Thank you for the update. Its working now
