### ISSUE TITLE
"registration ID is currently required" error appears to make updating impossible

### ISSUE THREAD

**Issue by kpm-at-hfi** [Azure/iotedge#5488]
Based on the direction found at https://github.com/Azure/iotedge/blob/master/doc/packaging.md I'm trying to update pre-1.1 iotedge (on Raspberry OS) to the latest by doing the following:

```bash
# Preparing to update to entirely new iotedge
# Per https://github.com/Azure/iotedge/blob/master/doc/packaging.md
yes | sudo apt remove iotedge ;
yes | sudo apt remove libiothsm-std ;

# Update everything else using full-upgrade for nice dependency resolution
yess | sudo apt full-upgrade ;

# Now actually update to entirely new iotedge
# Per https://github.com/Azure/iotedge/blob/master/doc/packaging.md
yes | sudo apt install aziot-edge ;
yes | sudo iotedge config import ;
```

All seems to go well until the last command:

```
+ sudo iotedge config import
Command failed: registration ID is currently required
```

I see from [here, for example](https://github.com/Azure/iotedge/issues/4829), that this is "expected behavior", but how is someone like me with fielded remote devices supposed to accomodate this change?

Getting the __device__ identity certificate's common name in there is not trivial.

For those devices that are fielded, it's going to require some fancy footwork.

And we're going to have to change our manufacturing process for new devices.

This seems like kind of a big deal.

Am I missing something?

**Comment by ggjjj** [comment]
@arsing  can you comment on the best practice for the fielded remote devices?

**Comment by arsing** [comment]
>Getting the device identity certificate's common name in there is not trivial.

Why's that?

**Comment by kpm-at-hfi** [comment]
Because it will require me to remotely modify the config file on each fielded device. I can script my way out of this, I'm sure. But it isn't nothing.

When the devices are manufactured and their certs are installed, that will be pretty easy. But as I noted above, I have an approved manufacturing process in place, and this will mean slightly enhancing (and officially revising) that process to accomodate for this once-optional-now-required situation.

So, I guess I'm just trying to let you know that this is a cost for a user like me, and I'm asking here hoping that I really am missing something.

**Comment by arsing** [comment]
>Because it will require me to remotely modify the config file on each fielded device.

You already have to remotely run `iotedge config import` on each fielded device.

>and I'm asking here hoping that I really am missing something.

You're not missing anything. Initially in 1.2's development there was flux in whether registration ID should be required or not, because a) DPS does not / will not require the registration ID to match the CN of the device ID cert, and b) in 1.2 the device ID cert can be dynamically issued and thus identityd needs to know what to use for the CN of the CSR.

Eventually we decided to keep the fallback to the device ID cert CN if it exists (and an error if it doesn't). But [this change](https://github.com/Azure/iot-identity-service/commit/2df97b987c36a337fe143d12b3c6d38f32b3c0a5) was made after 1.2 was branched and we didn't backport it.

**Comment by kpm-at-hfi** [comment]
OK, so I have one device modified (added `registration_id` to the YAML config) and successfully ran `sudo iotedge config import`. Note that your documentation says that "command helps ease the transition from v1.1 to v1.2" but it seems to have worked for me coming from 1.0.10.

That script's output says that I need to run `sudo iotedge config apply -c '/etc/aziot/config.toml'`, so I did.

Now when running `sudo iotedge check` I'm getting:
```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ production readiness: identity certificates expiry - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (AccessDenied) : Permission denied /var/run/iotedge/mgmt.sock
    One or more errors occurred. (Got bad response: )
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
28 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
6 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.
```

So I think I have two questions, please:

### 1: Given the `Permission denied /var/run/iotedge/mgmt.sock` error, did the `[connect] block maybe not get properly migrated?

```
[connect]
workload_uri = "unix:///var/run/iotedge/workload.sock"
management_uri = "unix:///var/run/iotedge/mgmt.sock"

[listen]
workload_uri = "fd://aziot-edged.workload.socket"
management_uri = "fd://aziot-edged.mgmt.socket"
min_tls_version = "tls1.0"
```

### 2: For the `iothub_hostname` error, do I need to change something on my DPS?

Keep in mind that the DPS service is already working great for my fielded pre-1.1 devices.

**Comment by kpm-at-hfi** [comment]
```bash
$ ls -l /var/run/iotedge/mgmt.sock
srw-rw---- 1 iotedge iotedge 0 Sep 14 14:55 /var/run/iotedge/mgmt.sock
```

**Comment by kpm-at-hfi** [comment]
Running `iotedge system status` gives me:

```
System services:
    aziot-edged             Running
    aziot-identityd         Down - activating 
    aziot-keyd              Running
    aziot-certd             Running
    aziot-tpmd              Ready

aziot-identityd is in a bad state because:
aziot-identityd.service: Down - activating : Printing the last 10 log lines.
-- Logs begin at Tue 2021-09-14 15:17:05 UTC, end at Tue 2021-09-14 15:56:07 UTC. --
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [INFO] - Starting service...
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [INFO] - Version - 1.2.2
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [INFO] - Provisioning starting. Reason: Startup
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - service encountered an error
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - caused by: DPS client error
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - caused by: Unauthorized
Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] -    0: <unknown>
Sep 14 15:56:07 hfiq-alfred systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 15:56:07 hfiq-alfred systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.

Use 'iotedge system logs' to check for non-fatal errors.
Use 'iotedge check' to diagnose connectivity and configuration issues.
```

FWIW, everything in my `certs` directory is 755, and all the references to these files from the `config.toml` are correct.

**Comment by kpm-at-hfi** [comment]
Since many of the blocks in `config.conf` are for overrides, I've simplified my `config.toml` down to only this:

```
trust_bundle_cert = "---redacted---"
auto_reprovisioning_mode = "OnErrorOnly"
imported_master_encryption_key = "---redacted---"
hostname = "---redacted---"

[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net/"
id_scope = "---redacted---"

[provisioning.attestation]
method = "x509"
registration_id = "---redacted---"
identity_cert = "---redacted---"
identity_pk = "---redacted---"
```

I'm seeing exactly the same behavior noted in the prior two comments.

**Comment by kpm-at-hfi** [comment]
**Question:** The Deployment for this device is currently set up to point to`mcr.microsoft.com/azureiotedge-agent:1.0.10` and `mcr.microsoft.com/azureiotedge-hub:1.0.10`.

Let's say we get this working so that the runtime is up to 1.2. Will the current deployment run?

**Comment by arsing** [comment]
>When will that change be released?

https://github.com/Azure/iotedge/commit/f147f12881c91c029de49c1aba8f509d6c3eed47 pulls in the fix to release/1.2. Whenever the next 1.2 release is made, it'll be there.

---

>```
>Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
>Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - service encountered an error
>Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - caused by: DPS client error
>Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] - caused by: Unauthorized
>Sep 14 15:56:07 hfiq-alfred aziot-identityd[4059]: 2021-09-14T15:56:07Z [ERR!] -    0: <unknown>
>```

If DPS says Unauthorized, then your registration ID is not correct.

**Comment by kpm-at-hfi** [comment]
Yes, that was the DPS "problem"... thanks!

So in case it helps anyone prior to that 1.2 release (wherein the "rergistration_id" becomes optional again), here's what I'm doing and it seems to be working well:

```bash
# Preparing to update to entirely new iotedge
# Per https://github.com/Azure/iotedge/blob/master/doc/packaging.md
yes | sudo apt remove iotedge ;
yes | sudo apt remove libiothsm-std ;

# overcome the new requirement for "registration_id" per https://github.com/Azure/iotedge/issues/5488
  # get the id
THE_DEVICE_CERT_CN=$(___get-the-device-cert-cn____)

 # install needed python library
pip install pyyaml

 # modify the config.yaml
$(python <<EOF
import yaml
with open("/etc/iotedge/config.yaml", "r+") as f:
    y=yaml.safe_load(f)
    y['provisioning']['attestation']['registration_id'] = '$THE_DEVICE_CERT_CN'
    f.seek(0)
    f.write(yaml.dump(y, default_flow_style=False, sort_keys=False))
    f.truncate()
    f.close()
EOF
)

# Now actually update to entirely new iotedge
# Per https://github.com/Azure/iotedge/blob/master/doc/packaging.md
yes | sudo apt install aziot-edge ;
sudo iotedge config import ;
sudo iotedge config apply -c '/etc/aziot/config.toml' ;
```

**Comment by kpm-at-hfi** [comment]
> **Question:** The Deployment for this device is currently set up to point to`mcr.microsoft.com/azureiotedge-agent:1.0.10` and `mcr.microsoft.com/azureiotedge-hub:1.0.10`.
> 
> Let's say we get this working so that the runtime is up to 1.2. Will the current deployment run?

The answer is yes. I am up and running and the deploy is pointing at 1.0.10 images and it's all working so far. :)
