### ISSUE TITLE
IoT Edge configuration uses an unsupported schema and cannot be displayed

### ISSUE THREAD

**Issue by yahanda** [Azure/iotedge#5491]
My customer encountered the same issue as below:
https://docs.microsoft.com/en-us/answers/questions/367245/mqtt-connectivity-setup-iot-edge.html

The error `"IoT Edge configuration uses an unsupported schema and cannot be displayed."` occurred when `$edgeHub.properties.desired.schemaVersion` was set to 1.2, and resolved when it was set to 1.1.

Is this the expected behavior of the product? Even in the case of the error, it doesn't seem to affect the behavior, just not being able to see the IoT Edge configuration from Azure portal.

Thanks,

**Comment by ggjjj** [comment]
@vadim-kovalyov can you comment on this expected behavior?

**Comment by vadim-kovalyov** [comment]
@yahanda, as of right now, the Portal does not support 1.2 schema version. MQTT Broker is in preview, and this is a known limitation that we are working to resolve sometime soon. Thank you for your patience!

Dup of #4792.
