### ISSUE TITLE
IoT Edge connection  - openssl verification 

### ISSUE THREAD

**Issue by anfelbeghoura** [Azure/iotedge#554]
## Expected Behavior
The Downstream Leaf device is using the C SDK to connect then send Messages to the IoT Edge Transparent gateway. 

## Current Behavior
The Downstream device can't connect and send messages to the IoT Edge Transparent Gateway. If I Remove the GatewayHostName from the connection string, the messages show up directly in IoT Hub.

## Steps to Reproduce
1. I have followed the instruction for setting up a Downstream Device to send messages through IoT Edge running in Transparent Gateway. 
https://docs.microsoft.com/fr-fr/azure/iot-edge/how-to-create-transparent-gateway

2.1. The Downstream Device is a Raspberry pi 3 with OS Raspbian Jessie is using  azure-iot-sdk-c
https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples
connection string : 
HostName=<myIothubName>.azure-devices.net;DeviceId=<myDeviceID>;SharedAccessKey=<MYSharedAccessKey>;X509Cert=False;GatewayHostName=<my-gateway-name>.contoso.com
       
2.2. The Transparent Gateway a Raspberry pi 3 as well with OS Raspbian Jessie.  I used iotedge 1.0.4 Version ; To install tools and runtime I have followed:
https://docs.microsoft.com/fr-fr/azure/iot-edge/how-to-install-iot-edge-linux-arm

3. IoT Edge Transparent Gateway is configured with all the certs properly setup, configured and verified by using the openssl tool as follows:
a.  I get a successful verification of the SSL cert using :
openssl s_client -connect <my-gateway-hostname>.local:8883 -CAfile <CertsPATH>/azure-iot-test-only.root.ca.cert.pem -showcerts
b. I get Error with:
  openssl s_client -connect <my-gateway-hostname>.contoso.com:8883 -CAfile <CertsPATH>/azure-iot-test-only.root.ca.cert.pem -showcerts
=> connect : errno=2

### Device (Host) Operating System

linux

### Architecture

arm32

### Container Operating System

Linux containers

#### iotedged

iotedge 1.0.4 

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0

## Logs

1.iotedge 

pi@mygateway:~ $ openssl s_client -connect <my-gateway-name>.local:8883 -CAfile /etc/ssl/certs/azure-iot-test-only.root.ca.cert.pem -showcerts
CONNECTED(00000003)
depth=2 CN = Test Edge Device CA
verify error:num=20:unable to get local issuer certificate
---
Certificate chain
 0 s:/CN=<my-gateway-name>
   i:/CN=iotedged workload ca
 1 s:/CN=Test Edge Device CA
   i:/CN=Test Edge Owner CA
 2 s:/CN=iotedged workload ca
   i:/CN=Test Edge Device CA
---
Server certificate
-----BEGIN CERTIFICATE-----

.......................................

pi@mygateway:~ $ openssl s_client -connect <my-gateway-name>.contoso.com:8883 -CAfile /certsPATH/azure-iot-test-only.root.ca.cert.pem -showcerts
1996412320:error:20087002:BIO routines:BIO_lookup:system lib:../crypto/bio/b_addr.c:693:Name or service not known
connect:errno=2

2.Downstream Device logs

pi@raspberrypi:~/azure-iot-sdk-c/cmake/iothub_client/samples/iotedge_downstream_device_sample $ ./iotedge_downstream_device_sample
This sample will send 20 messages and wait for any C2D messages.
Press the enter key to end the sample

Creating IoTHub handle
Error: Time:Mon Nov 19 10:05:12 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:283 Failure: getaddrinfo failure -2.
Error: Time:Mon Nov 19 10:05:12 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:766 lookup_address_and_connect_socket failed
Error: Time:Mon Nov 19 10:05:12 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Nov 19 10:05:12 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Mon Nov 19 10:05:12 2018 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Mon Nov 19 10:05:12 2018 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address mygateway.
The device client has been disconnected
Sending message 1 to Edge Hub
Sending message 2 to Edge Hub
Sending message 3 to Edge Hub
Sending message 4 to Edge Hub
Sending message 5 to Edge Hub
Sending message 6 to Edge Hub
Sending message 7 to Edge Hub
Sending message 8 to Edge Hub
Sending message 9 to Edge Hub
Sending message 10 to Edge Hub
Sending message 11 to Edge Hub
Sending message 12 to Edge Hub
Sending message 13 to Edge Hub
Sending message 14 to Edge Hub
Sending message 15 to Edge Hub
Sending message 16 to Edge Hub
Sending message 17 to Edge Hub
Sending message 18 to Edge Hub
Sending message 19 to Edge Hub
Sending message 20 to Edge Hub

Press any key to continue
Error: Time:Mon Nov 19 10:05:13 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:283 Failure: getaddrinfo failure -2.
Error: Time:Mon Nov 19 10:05:13 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:766 lookup_address_and_connect_socket failed
Error: Time:Mon Nov 19 10:05:13 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Nov 19 10:05:13 2018 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Mon Nov 19 10:05:13 2018 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Mon Nov 19 10:05:13 2018 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address mygateway.
The device client has been disconnected

Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 2 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 3 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 4 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 5 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 6 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 7 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 8 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 9 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 10 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 11 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 12 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 13 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 14 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 15 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 16 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 17 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 18 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 19 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY
Confirmation callback received for message 20 with result IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY

**Comment by ancaantochi** [comment]
Hi @anfelbeghoura,

It looks like the leaf device is not able to resolve .contoso.com, what is the result if you run this command:
host .contoso.com

Just to clarify: 
- What is the gateway hostname that you set when you generated the certificates?
- What is the hostname value in the config.yaml?

From the logs that you provided it looks like openssl s_client -connect .local:8883 -CAfile /azure-iot-test-only.root.ca.cert.pem -showcerts  it is able to connect, but the certificate validation fails, I assume because the hostname doesn't match.

**Comment by anfelbeghoura** [comment]
I'm actually confused about the hostname, the tutorial wasn't clear that much about it, so I put the hostname: "mygateway"  in the config.yaml which it is the same hostname of my raspberry pi 3 and I think I'm not really sure about the contoso.com could you give me more details?

**Comment by anfelbeghoura** [comment]
Well, when I ping mygateway.local it workes fine, But ping mygateway I got:
ping: maygateway: Name or service not known

And please, once again what is the contoso.com?

**Comment by ancaantochi** [comment]
Hi @anfelbeghoura,

You have to generate the certificates with mygateway.local and use mygateway.local in the openssl command.

In the first message you sent at step 3b you had this command (using constoso.com): openssl s_client -connect **_.contoso.com_**:8883 -CAfile /azure-iot-test-only.root.ca.cert.pem -showcerts

**Comment by myagley** [comment]
I'm going to close this issue due to inactivity. Please feel free to reopen.

**Comment by anfelbeghoura** [comment]
The .local is to ping the local network is it not the hostname!!!!
