### ISSUE TITLE
Unable to process module {...} add or update as the module identity could not be obtained

### ISSUE THREAD

**Issue by erwinkraskacancom** [Azure/iotedge#5582]
### Expected Behavior
We have a working deployment with several custom modules. Everything is working fine when the device is connected to the internet. When I cut the internet connection and reboot the device all the modules should start.

### Current Behavior
When I cut the internet connection and reboot the device. One or some custom modules are not starting up correctly.

The only message regarding this in the log is:
`Unable to process module {...} add or update as the module identity could not be obtained`

When I connect the internet connection again, everything is fine within seconds, the edgeAgent also uses the correct name of the module:

`Executing command: "Command Group: (\n [Create module {...}]\n [Start module {...}]\n)"`
`Executing command: "Create module {...}"`
`Executing command: "Start module {...}"`

### Context (Environment)
iot-edge on Ubuntu 18.04.6 LTS

### Device Information
Host OS: Ubuntu 18.04.06
Architecture: amd64
Container OS: Linux containers
### Runtime Versions
iotedged [run iotedge version]: iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)
Edge Agent: 1.1.4 (i tryed also with 1.1.5 and 1.2.3)
Edge Hub: 1.1.4 (i tryed also with 1.1.5 and 1.2.3)

**Comment by gordonwang0** [comment]
It seems like the log message you posted comes from the initial deployment (or redeployment) of a module. Internet connectivity is required for this. After the module has been deployed, you can go offline.

**Comment by erwinkraskacancom** [comment]
Thank you for your quick answere. After the EdgeDevice was one houre online, i reboot the Device without internet connection. Ich mean that in this case all moduls must start.

**Comment by gordonwang0** [comment]
Please provide the logs of edgeAgent, iotedged, and any modules failing to start.

**Comment by erwinkraskacancom** [comment]
Log from iotedged
`<6>2021-09-30T11:04:27Z [INFO] - Using default configuration
<6>2021-09-30T11:04:27Z [INFO] - Starting Azure IoT Edge Security Daemon
<6>2021-09-30T11:04:27Z [INFO] - Version - 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)
<3>2021-09-30T11:04:27Z [ERR!] - The daemon could not start up successfully: Edge device information is required.
`

**Comment by erwinkraskacancom** [comment]
[Uploading OnlineStartup_edgeAgent.log…](
[OfflineStartup_edgeAgent.log](https://github.com/Azure/iotedge/files/7259044/OfflineStartup_edgeAgent.log)
)

**Comment by erwinkraskacancom** [comment]
### Logfile Online Startup:
[OnlineStartup_edgeAgent.log](https://github.com/Azure/iotedge/files/7259064/OnlineStartup_edgeAgent.log)

### Logfile Offline Startup:
[OfflineStartup_edgeAgent.log](https://github.com/Azure/iotedge/files/7259071/OfflineStartup_edgeAgent.log)

**Comment by erwinkraskacancom** [comment]
This is a Logfile from edgeAgent when System starts offline.
[edgeAgent.log](https://github.com/Azure/iotedge/files/7482204/edgeAgent.log)

In line 42 the Modul influxdb can not start and there is no Logfile for this Modul.

**Comment by gordonwang0** [comment]
Could you provide debug logs for edgeAgent? Set the env var `RuntimeLogLevel` to `debug` in your config.yaml.

**Comment by erwinkraskacancom** [comment]
EdgeAgent.Log with LogLevel debug:
[edgeAgent.log](https://github.com/Azure/iotedge/files/7490503/edgeAgent.log)

**Comment by gordonwang0** [comment]
From the debug logs, it looks like the influxdb module has a status `unknown`. edgeAgent treats these unknown status as errors and will attempt to redeploy the module.

Could you check this module and see if any errors happen? And check docker to see what its actual status is?

**Comment by erwinkraskacancom** [comment]
Sometimes we have the same Problem with other Modules or with all modules. Should the iotedge-System store all informationen about his modules for offline-mode? When i plug in the network cable everthing wir start right.

**Comment by gordonwang0** [comment]
Please let us know if you need any more help with this. Closing stale issue.

**Comment by richterr** [comment]
I just made a minimal example reproducing the error with two modules, one being an influxdb and one being a grafana instance. Back when startup order wasn't available the legacy docker container link could be used as a workaround to achieve some kind of ordering for the modules since it forced a restart for the module linking the other one.
However, when using a docker container link from the grafana module the influxdb module becomes grafana/influxdb for the iotedge runtime. I assume it also gets a new identity. Therefore the "original" module influxdb configured in the desired properties of the edgeAgent can not be found in the current list of modules.

When removing the link the error goes away. Can you confirm this being the root cause of the problem?
