### ISSUE TITLE
Deployment succeeded, but failed

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#56]
Hi There,

I'm following https://docs.microsoft.com/ms-my/azure/iot-edge/tutorial-csharp-module to deploy a csharp module into my edge device.

Everything looks nice, including deploying the module using VSC, returning "deployment succeeded". But if I refresh (or list the iotedge modules on my device) it is failed with state Backoff and exit code 1.

How can I debug from here? I only found one error message (just now):
Exec user process caused "exec format error"

**Comment by nhuurnink** [comment]
I've found my issue, I was running my code on a raspberry Pi 3 (arm32v7), whereas the default configuration in mentioned tutorial is arm64.

After changing the image settings to use arm32v7, the code runs fine.

**Comment by darobs** [comment]
Thank you @nhuurnink, if this is resolved, I will close this issue.
