### ISSUE TITLE
aziot-edged 1.2.3 does not seem to work correct with proxy

### ISSUE THREAD

**Issue by chris-dmg** [Azure/iotedge#5603]
## Expected Behavior
All aziot services (aziot-edged as well as aziot identity services) work correct if you use them behine a proxy.

## Current Behavior
The aziot-edged log shows connection errors when it runs behind a proxy:

> aziot-edged[2245]: 2021-09-30T11:49:46Z [ERR!] - Internal server error: A request to Azure IoT Hub failed
aziot-edged[2245]:         caused by: HTTP request error
aziot-edged[2245]:         caused by: connection error: Connection reset by peer (os error 104)
aziot-edged[2245]: 2021-09-30T11:49:46Z [INFO] - [mgmt] - - - [2021-09-30 11:49:46.401935275 UTC] "PUT /identities/settings-ui?api-version=2020-07-07 HTTP/1.1" 500 Internal Server Error 152 "-" "-" auth_id(-)
aziot-edged[2245]: 2021-09-30T11:49:46Z [ERR!] - Internal server error: A request to Azure IoT Hub failed
aziot-edged[2245]:         caused by: HTTP request error
aziot-edged[2245]:         caused by: connection error: Connection reset by peer (os error 104)
aziot-edged[2245]: 2021-09-30T11:49:46Z [INFO] - [mgmt] - - - [2021-09-30 11:49:46.456864136 UTC] "PUT /identities/mpc-ui?api-version=2020-07-07 HTTP/1.1" 500 Internal Server Error 152 "-" "-" auth_id(-)
aziot-edged[2245]: 2021-09-30T11:49:46Z [ERR!] - Internal server error: A request to Azure IoT Hub failed
aziot-edged[2245]:         caused by: HTTP request error
aziot-edged[2245]:         caused by: error writing a body to connection: Broken pipe (os error 32)
aziot-edged[2245]: 2021-09-30T11:49:46Z [INFO] - [mgmt] - - - [2021-09-30 11:49:46.507734183 UTC] "PUT /identities/guacd?api-version=2020-07-07 HTTP/1.1" 500 Internal Server Error 156 "-" "-" auth_id(-)
aziot-edged[2245]: 2021-09-30T11:49:46Z [ERR!] - Internal server error: A request to Azure IoT Hub failed
aziot-edged[2245]:         caused by: HTTP request error
aziot-edged[2245]:         caused by: error writing a body to connection: Broken pipe (os error 32)
aziot-edged[2245]: 2021-09-30T11:49:46Z [INFO] - [mgmt] - - - [2021-09-30 11:49:46.511052737 UTC] "PUT /identities/nc-file-backup?api-version=2020-07-07 HTTP/1.1" 500 Internal Server Error 156 "-" "-" auth_id(-)

The basic network setup is as follows:
- the device runs a local proxy service (cntlm, listening on port 3128)
- the local proxy service is configured to use a parent proxy
- the iotedge daemon is configured to use the local proxy service (https_proxy=http://localhost:3128)
- the use of a proxy is configured in the systemd service fails as described in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2020-11
```
[aziot-edged.service.txt](https://github.com/Azure/iotedge/files/7259529/aziot-edged.service.txt)
[aziot-identityd.service.txt](https://github.com/Azure/iotedge/files/7259530/aziot-identityd.service.txt)
```

This error does not show up if you run the identical device with identical network/proxy configuration and iotedge 1.1.1. If we switch to iotedge 1.2.3 it does not work anymore.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Configure aziot edge daemon to use a proxy
2. Confgiure aziot identity service to use a proxy
3. Start aziot edge daemon, it connects to azure dps & iothub
4. aziot edge daemon is not able to retrieve deployment and modules

### aziot configuration
```
[config.toml.txt](https://github.com/Azure/iotedge/files/7259531/config.toml.txt)
```

### Output of `iotedge check`

<details>
<summary>Click here</summary>
`
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
‼ host time is close to reference time - Warning
    Could not query NTP server
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ tpmd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
‼ aziot-edge package is up-to-date - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
23 check(s) succeeded.
8 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
6 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.
`

</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Yocto OS,  Linux version 5.4.94-yocto-standard
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: linux 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.3
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0
* Docker/Moby [run `docker version`]: 19.03.15

## Logs

<details>
<summary>aziot-edged logs</summary>

```
[iotedge_logs_1.2.3.txt](https://github.com/Azure/iotedge/files/7259532/iotedge_logs_1.2.3.txt)

</details>


## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by chris-dmg** [comment]
The issue seems to be resoved with https://github.com/Azure/iot-identity-service/releases/tag/1.2.3

**Comment by scb01** [comment]
@chris-dmg Good to know. I'm going to go ahead and close this issue.
