### ISSUE TITLE
[QUESTION] how to preserve edge module device twin tags on deployment

### ISSUE THREAD

**Issue by goetae** [Azure/iotedge#5637]
Hello
we have several edge devices up and running, initially with manual module deployment and manual module twin configuration e.g. classifying the data type the module is sending e.g. 

```
    "tags": {
        "datatype": "importantdata"
        }
    }
```
We use the message enrichment feature to add properties to the events property collection, which we use for data routing e.g. `datatype=$twin.tags.datatype`

In the meantime we have setup a deployment pipeline and each time, we deploy/upgrade an existing edge module, the tags are cleared and we apply them manually again.

The [layered deployment](https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring?view=iotedge-2020-11#layered-deployment) article describes how to to extend, overwrite or delete desired properties but is not mentioning module twin tags at all. 
If it follows the same principle, the tags should not be overwritten, as we do not provide the tags json fragment in the deployment script. 

Can someone guide us to the right direction, how to setup module twin tags properly and preserve them during deployments?

**Comment by veyalla** [comment]
@goetae can you please share what the module twin looks like before and after the update? And also the layered deployment that updates it?

**Comment by jlian** [comment]
@goetae Are you deleting the deployment to create one that has a higher image build/version number? If you're deleting the deployment, it will delete the tags as well. For layered deployments, if you increase the priority, that should keep the tags while overwriting the older deployment (but I’m still not entirely certain if you're deleting the deployments).

**Comment by goetae** [comment]
hello

I'm just digging into the topic myself but I'm not creating the deployments but I have the same concerns, deleting and recreating will delete the tags.

I was told by the dev ops engineer that a deployment upgrade is not possible and therefore the existing gets deleted and a new deployment is created, see the script fragment in the previous post.

I check the CLI myself and yes, there is no upgrade command for whole deployment `az iot edge deployment` 
Based on the [modify deployment](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-cli-at-scale?view=iotedge-2020-11#modify-a-deployment) documentation, Its only possible to update
- targetCondition (for example, targetCondition=tags.location.state='Oregon')
- labels
- priority

Its not possible to upgrade the image  `"settings": { "image": "myregistry/myedgemodule:<myversion>" }` , correct?

You mentioned "priority", I reviewed the documentation and I try to give this as input to the dev ops engineer to change the script and generate / increase the "priority" of the new deployments

process should be
- get priority for existing deployment e.g. priority=1
- create new deployment with higher priority e.g. priority=2


Some assumptions/questions
- is there a max limit on deployment priorities?  (route priorities seem to be limited to "0-9")
- is there a need to cleanup deployments afterwards, e.g. updating a module 50 times, would result in 50 layered deployments with increasing priority?
- could I delete a deployment with priority 1 if a deployment with priority 2 is already deployed?

**Comment by goetae** [comment]
I just wanted to get some guideline how to properly upgrade a deployment to preserve all settings e.g. tags and properties as this does not work in our environment which is not built by myself. 
So please can someone just provide me an documentation I maybe overlooked or some simple bullet point steps how to properly setup an edge deployment?

Otherwise we can close this request as I cannot provide more information and don't know how to rephrase my question about deployments of edge modules that keep the module twin settings unchanged.

**Comment by gxyjenny** [comment]
This doc should walk through how to create deployments: [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-at-scale?view=iotedge-2020-11](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-at-scale?view=iotedge-2020-11)

**Comment by jlian** [comment]
> You mentioned "priority", I reviewed the documentation and I try to give this as input to the dev ops engineer to change the script and generate / increase the "priority" of the new deployments
> process should be
> - get priority for existing deployment e.g. priority=1
> - create new deployment with higher priority e.g. priority=2

I think yes. Looks like you already had your base deployments. Then do one layered deployment, set priority, etc. Then if you did another layered deployment and the priority is higher, then it'll overwrite the previous layered deployment.

> - is there a max limit on deployment priorities? (route priorities seem to be limited to "0-9")

I assume that to mean the highest number you can assign a priority, which I think it's much higher than 9. Let me check

> - is there a need to cleanup deployments afterwards, e.g. updating a module 50 times, would result in 50 layered deployments with increasing priority?

There technically isn't a need to clean up deployments, but it would eat into the 100 deployment limit 

> - could I delete a deployment with priority 1 if a deployment with priority 2 is already deployed?

If you updated a module and created a new deployment, we are assuming that you would delete the old deployment (with the old version of the module)

**Comment by jlian** [comment]
The limit for priority is the C# max in value, 2,147,483,647

**Comment by varunpuranik** [comment]
@goetae - 
Does the info from @jlian answer your questions? 
I will go ahead and close this issue. Please feel free to open a new one if you run into any more issues with IoT Edge.
