### ISSUE TITLE
Make installation of VC runtime optional on Windows installer

### ISSUE THREAD

**Issue by sebader** [Azure/iotedge#565]
The powershell install script for Windows supports now to supply a previously downloaded zip file ("archive") of the IoT Edge daemon. But it will still try to download and install every the VC runtime.
It should be either

- made optional to download and install VC at all
- or at least, give the user the chance to manually supply the path to the downloaded installer.exe similar to the IoT Edge daemon.

Especially when re-installing Edge, the VC is obviously already there and downloading it again just takes unnecessary time. Or - even worse - in cases where the device does not have internet connectivity, even behind a proxy, this might fail.

Still seems the case in the latest PR regarding the installer: https://github.com/Azure/iotedge/pull/550/files#diff-8ae7a24c87a2048c653a1cfb9f7e1d8bR502

**Comment by myagley** [comment]
Thanks for the feedback. We will look at getting the installation script updated.

**Comment by sebader** [comment]
This is also needed for the newly added Moby-binaries. We need to have an installer, that is fully offline-capable. In many cases the Edge device will have no general internet connectivity at all.
