### ISSUE TITLE
Metric edgeAgent_module_start_total and edgeAgent_module_stop_total report data about old module versions

### ISSUE THREAD

**Issue by MagdaPaj** [Azure/iotedge#5707]
## Expected Behavior
Metrics `edgeAgent_module_start_total` and `edgeAgent_module_stop_total` report starts or stops only from the latest module version.

## Current Behavior
`edgeAgent_module_start_total` reports starts for older module versions. This is the output for a single module named  `CustomConnector`, for which I deployed couple of versions.
```
edgeAgent_module_start_total{iothub="iot-1234.azure-devices.net",edge_device="edge-device-01",instance_number="1234cced-af32-4909-8bb2-804710e5f6ad",module_name="CustomConnector",module_version="0.0.3",ms_telemetry="True"} 5
edgeAgent_module_start_total{iothub="iot-1234.azure-devices.net",edge_device="edge-device-01",instance_number="1234cced-af32-4909-8bb2-804710e5f6ad",module_name="CustomConnector",module_version="0.0.4",ms_telemetry="True"} 1
edgeAgent_module_start_total{iothub="iot-1234.azure-devices.net",edge_device="edge-device-01",instance_number="1234cced-af32-4909-8bb2-804710e5f6ad",module_name="CustomConnector",module_version="0.0.2",ms_telemetry="True"} 7
```

`edgeAgent_module_stop_total` reports stops for older module versions.
```
edgeAgent_module_stop_total{iothub="iot-1234.azure-devices.net",edge_device="edge-device-01",instance_number="1234cced-af32-4909-8bb2-804710e5f6ad",module_name="CustomConnector",module_version="0.0.3",ms_telemetry="True"} 4
edgeAgent_module_stop_total{iothub="iot-1234.azure-devices.net",edge_device="edge-device-01",instance_number="1234cced-af32-4909-8bb2-804710e5f6ad",module_name="CustomConnector",module_version="0.0.4",ms_telemetry="True"} 3
edgeAgent_module_stop_total{iothub="iot-1234.azure-devices.net",edge_device="edge-device-01",instance_number="1234cced-af32-4909-8bb2-804710e5f6ad",module_name="CustomConnector",module_version="0.0.2",ms_telemetry="True"} 4
```

Sometimes `module_version` is reported as empty string.

This is the behavior in case there is no change of `instance_number` between multiple module version updates.

Because of this it harder to create a query that will show restarts in last 10 min (or any other time window) as I need to discard data for older versions. Another thing is that more than required is reported, old module starts/stops don't seem to be relevant, but they increase storage and overall cost.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Have at least 1 module deployed in IoT Edge
2. Update a version of the module in the deployment manifest (there is no need to update the image version, you can just update version).
3. Access built-in metrics as described [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-built-in-metrics?view=iotedge-2020-11), I used the example, so I mapped the default metrics port to port 9601 on the host
4. call metrics endpoint, search `edgeAgent_module_start_total` and check how many `module_version` is reported for a specific module, my query: `curl http://localhost:9601/metrics | grep edgeAgent_module_start_total | grep CustomConnector` 

When `instance_number` is changed (for example after restarting the edgeAgent) I only get data with latest `module_version`, which is what I would expect always. 

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux 

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.4 (I saw the same in older versions too)
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.4
* Docker/Moby [run `docker version`]: 20.10.9+azure-1

**Comment by nlcamp** [comment]
Hi @MagdaPaj. We include counts for multiple versions of a module because some customers want the extra information.  If you only want the metrics collector module to export metrics for the latest version of your module, you could use the AllowedMetrics and BlockedMetrics configuration options. I believe this would address your concern regarding increased storage and cost associated with transmitting these metrics to the cloud. Please see the following document for details on how you can incorporate labels (e.g. module_version) in these allow and disallow lists:

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-collect-and-transport-metrics?view=iotedge-2020-11&tabs=iothub#allow-and-disallow-lists 

Please let us know if this addresses your concern.

**Comment by MagdaPaj** [comment]
Hey @nlcamp. Thank you for your answer. 
I wasn't clear enough. Let me explain it better. By old version I meant the version that doesn't exist anymore. So my module `CustomConnector` doesn't run at the same time 3 different versions, only one version is deployed at any given time.

First, I deployed `CustomConnector`  with version `0.0.2`. Later, I updated that version to `0.0.3`. And the version `0.0.2` stopped running. And finally I updated the version to `0.0.4` and only `0.0.4` version was running.

So is it expected to see metrics `edgeAgent_module_start_total` or `edgeAgent_module_stop_total` for module versions that are not running anymore? (like in my case, I see metrics for version `0.0.2` and `0.0.3` where only `0.0.4` is running).

**Comment by nlcamp** [comment]
Yes, it is expected to see metrics for any modules that were started by the currently running instance of edgeAgent. If you restart edgeAgent via `sudo iotedge system restart` or `sudo ioedge restart edgeAgent` you should see those metrics cleared. You can also restart edgeAgent through the Troubleshoot page in Portal.

**Comment by nlcamp** [comment]
@MagdaPaj  - I'm closing this issue because the observed behavior is expected. Please submit a new Github issue if you run into any other problems.
