### ISSUE TITLE
IoT Edge in Raspberry pi 4 model B python module errors

### ISSUE THREAD

**Issue by balakreshnan** [Azure/iotedge#5719]
i created the python custom module based on our documentation
https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module?view=iotedge-2020-11

Here is the docker file:
FROM arm32v7/python:3.7-slim-buster

WORKDIR /app
RUN echo 'asd'

RUN apt-get update && apt-get -y install gcc
RUN apt-get update -y && apt-get install -y python3-dev build-essential

RUN apt-get update && apt-get install -y python-rpi.gpio python3-rpi.gpio

RUN pip3 install --upgrade pip

COPY requirements.txt ./
RUN apt-get install -y libgpiod2

RUN pip3 install -r requirements.txt

COPY . .

USER root:root

CMD [ "python3", "-u", "./main.py" ]

Every time i deploy i am getting this error. i have tried so many thing to install the libraries and still not working
Also provided privileaged access to the container as well. When i use part of the code without docker as iot device works fine.

Traceback (most recent call last):
  File "./main.py", line 13, in <module>
    import board
  File "/usr/local/lib/python3.7/site-packages/board.py", line 58, in <module>
    from adafruit_blinka.board.raspberrypi.raspi_40pin import *
  File "/usr/local/lib/python3.7/site-packages/adafruit_blinka/board/raspberrypi/raspi_40pin.py", line 3, in <module>
    from adafruit_blinka.microcontroller.bcm283x import pin
  File "/usr/local/lib/python3.7/site-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 2, in <module>
    import RPi.GPIO as GPIO
ModuleNotFoundError: No module named 'RPi'

**Comment by nlcamp** [comment]
@balakreshnan Thanks for reporting. I'll try to repro this once I can get ahold of a Raspberry pi.  My initial thoughts just looking at the error are that either 1) you are not installing the RPi package that has the RPi python module, or 2) the PYTHONPATH needs to be updated to include the path to the RPi module.

**Comment by nlcamp** [comment]
@balakreshnan I was able to deploy the python module from the tutorial to a Raspberry Pi 3 Model B without any errors. I'll have to get access to an RPi 4 to see if I can repro the errors you're seeing.

**Comment by balakreshnan** [comment]
Here is now i fixed - raspiot/raspdht11iotedge.md at main · balakreshnan/raspiot (github.com)<https://github.com/balakreshnan/raspiot/blob/main/raspdht11iotedge.md>
________________________________

**Comment by nlcamp** [comment]
@balakreshnan - Are you saying you've fixed the issue?

**Comment by nlcamp** [comment]
Closing as it appears you've fixed the issue you were experiencing.
