### ISSUE TITLE
Azure IoT Edge deployment targeting idles 5-6 minutes, workaround available

### ISSUE THREAD

**Issue by asinitson** [Azure/iotedge#5721]
## Expected Behavior
After deployment has reached IoT Edge, it should reach device virtually immediately.

## Current Behavior
After deployment has reached IoT Edge, it takes 5-6 minutes for deployment to target device matching the device query.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Delete existing deployment
2. Re-create new deployment
3. Open device and do `sudo watch 'iotedge list | sort'`
4. Observe that there is 5-6 minutes delay between the time deployment appears in Azure "IoT Edge Deployments" tab and container startup. It is also visible that "System Metrics" for deployment shows "0 Targeted" for those 5-6 minutes.

## Workaround
**If you insert 45 seconds delay between step 1. and 2., deployment happens virtually immediately (under a minute) after step 2.** This is how our deployment pipeline looks like right now:

![image](https://user-images.githubusercontent.com/13285303/138081923-3b92c8f9-a833-460d-a701-fe0aed021f1d.png)

If you do two builds like that for two separate deployments simultaneously (targeting different device tags), workaround does not work reliably. Let's say we have tags: _test_ and _integration_:
* One time device matching _test_ gets deployed immediately and _integration_ is delayed by 5-6 minutes
* Second time device matching _test_ gets delayed by 5-6 minutes and _integration_ happens immediately

## Context (Environment)

Note: All containers in deployment have fixed, precise version tags, so **no time** is spend on downloading container images during steps 1., 2., 3., 4. In fact we are just deleting and re-creating the same deployment. This is to make sure no time is spent on anything extra.

### Device Information
* Host OS: Ubuntu 18.04
* Architecture: amd64
* Container OS: Linux containers with Moby

## Additional Information
This problem has been observed since pretty much day 1 we started using CI/CD with both full and layered deployments. Note that there is really no other meaningful workflow right now, but deleting and re-creating deployments with the same name:
* Deployment is pretty much read-only, so we cannot updated anything but metadata (but we want to update container versions)
* Generating new deployment IDs (by using for example build number) works until you reach 100 deployments and IoT Edge refuses to take more

**Comment by nlcamp** [comment]
@asinitson - Can you provide some more context on the tools, instructions, and/or commands you're using to make these deployments? I'd like to try to repro the issue you're seeing.

**Comment by asinitson** [comment]
@nlcamp: I cannot share all the details since it is a not an open source project. Besides a lot of details (like generating deployment manifests) are not really relevant. So I tried to rip out the relevant parts. Feel free to ask for more information, if is is still not clear and of course you don't need a script and can run `az iot edge` directly. Note we have switched to layered deployments recently, so system containers (edgeAgent and edgeHub) are not restarted. **With "ordinary" deployments exactly the same behavior was observed.**

For doing steps 1. and 2. I created a wrapper script. See it in the lower past of this post verbatim (just copy-pasted it from our repository). The most interesting bits are in `create-deployment` and `delete-deployment` sections. Here is how it is being called from CI/CD (all necessary environment variable are supplied from the environment of course):

------------------------
0. Open the target machine and keep monitoring containers:
```bash
# In one console open the list of running containers
sudo watch 'iotedge list | sort'

# In 2nd console open edgeAgent logs
docker logs --follow edgeAgent

# In 3rd console open edgeHub logs
docker logs --follow edgeHub
```

1. Delete existing deployment
```bash
# TODO: uncomment lines below and fill in with your values
# export DEPLOYMENT_ID=
# export HUB_NAME=
az_iot_edge.sh delete-deployment

# In a few seconds after you will notice in a console from step 0. that deployment containers 
# have been shut down. Since we are running layered deployment edgeAgent and edgeHub
# remain running.
```

2. Re-create new deployment (**run immediately after step 1.!**)
```bash
# TODO: uncomment lines below and fill in with your values
# export HUB_NAME=
# export DEPLOYMENT_ID=
# export DEPLOYMENT_PRIORITY=
# export DEPLOYMENT=<path_to_deployment.json>
# export TARGET_CONDITION=<query_to_match_your_device_or_device_group>
# export LAYERED: 1
az_iot_edge.sh create-deployment

# Now you need to wait for 5-6 minutes until containers are brought up.
# Even if all containers versions have been pulled and everything is cached.
# edgeAgent and edgeHub containers are completely idle during those 5-6 minutes.
```
------------------------

az_iot_edge.sh:

```bash
#!/usr/bin/env bash

# Wrapper script for Azure IoT Edge CLI
#
# This script does not handle Azure subscription ID and authentication.
# It can be handled on Azure DevOps (Server) using Azure CLI build task:
# https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCLIV1/Readme.md

# Exit when a command fails
set -o errexit
# Exit on undeclared variable
set -o nounset
# Exit on the first command in pipe fail
set -o pipefail

ACTION="$@"
if [ ! ${ACTION} ]
then
    echo Nothing to do, exiting >/dev/stderr
    exit 1
fi

# For debugging issues with extension versions
print_az_versions () {
    if [ ${DEBUG-""} ]
    then
        az --version
        az version
        az extension list
    fi
}

# Add extensions for working with Azure IoT Edge
#
# When running with Azure CLI task v1 `az` is running in separate workspace
# which is clean on every build, so extensions have to be reinstalled.
print_az_versions
az extension add --name azure-iot
print_az_versions


################################

if [ ${ACTION} == "check-base-deployment" ]
then
    id=base_${BASE_DEPLOYMENT_VERSION}

    echo Checking base deployment "'"${id}"'" in "'"${HUB_NAME}"'"
    set +o errexit
    az iot edge deployment list --hub-name "${HUB_NAME}" \
        | grep " \"id\": \"${id}\""
    error_code=$?
    set -o errexit

    if [ ${error_code} == 1 ];
    then
        echo Deployment "'"${id}"'" was not found in "'"${HUB_NAME}"'" >&2
        exit ${error_code}
    fi
    echo Deployment "'"${id}"'" found in "'"${HUB_NAME}"'".
    exit
fi

################################

if [ ${ACTION} == "create-deployment" ]
then
    echo Creating base IoT Edge deployment "'"${DEPLOYMENT_ID}"'" \
        in "'"${HUB_NAME}"'" \
        for target condition "'"${TARGET_CONDITION}"'"

    az iot edge deployment create \
        --deployment-id ${DEPLOYMENT_ID} \
        --hub-name ${HUB_NAME} \
        --content ${DEPLOYMENT} \
        --target-condition "${TARGET_CONDITION}" \
        --priority ${DEPLOYMENT_PRIORITY} \
        --output none \
        ${LAYERED+--layered} \
        --verbose
    exit
fi

################################

if [ ${ACTION} == "delete-deployment" ]
then
    echo Deleting deployment "'"${DEPLOYMENT_ID}"'" from "'"${HUB_NAME}"'"
    set +o errexit
    az iot edge deployment delete \
        --hub-name ${HUB_NAME} \
        --deployment-id ${DEPLOYMENT_ID} \
        --verbose
    error_code=$?
    set -o errexit

    if [ ${error_code} == 0 ];
    then
        echo Deployment "'"${DEPLOYMENT_ID}"'" has been deleted successfully
        exit
    fi
    echo Deployment "'"${DEPLOYMENT_ID}"'" deletion failed
    exit
fi

```

**Comment by veyalla** [comment]
IoT hub service evaluates deployments every 5 min. If you change the priority of the deployment it will trigger the evaluation on the hub side immediately, otherwise what you’re observing is expected.

If not documented, we should add this to our docs. FYI @kgremban

**Comment by asinitson** [comment]
@veyalla:
> IoT hub service evaluates deployments every 5 min. If you change the priority of the deployment it will trigger the evaluation on the hub side immediately, otherwise what you’re observing is expected.

Yes, this definitely should be documented, but how do you explain this: 
* Why does waiting for 45 seconds before deploying mysteriously makes IoT hub service it not wait for 5 minutes and evaluate deployment almost immediately?
* Why is it always 5 minutes? If there is regular polling interval and I get "lucky" or "unlucky" with deployments, why it's never 1 or 2 minutes, but always more than 5 minutes?

--------------------------------------------

P.S. **Waiting 5 minutes every time for nothing is not a good developer experience.** This is currently our biggest pain point with Azure IoT Edge, since we do deployment really often and we have some staging/debug devices, where you basically sit and wait for containers to restart. Workaround which reduces 5-6 minutes to 45 seconds makes it somewhat tolerable.

**Comment by veyalla** [comment]
This is behavior from the IoT Hub service side for all configurations (edge and non-edge). The extent of my knowledge is that some operations (like deleting deployment, changing priority etc.) force an immediate e-eval on the service side; perhaps one of those conditions are being hit.

To clarify service side behavior, I suggest open a [support ticket](https://azure.microsoft.com/support/create-ticket/) against the IoT Hub service with your questions. 

Another thing is to try is deleting the old deployment as the last step when updating the deployment...

**Comment by asinitson** [comment]
@veyalla:
> Another thing is to try is deleting the old deployment as the last step when updating the deployment...
That is exactly what we are doing (as described in posts above). There is no other sane way to do deployments, since you are limited to 100 per hub. And with 45 second delay magically speed things up. Without it we bounce to 5+ minutes sitting and waiting for something on Azure side.

**Comment by nlcamp** [comment]
@asinitson I was able to repro the issue you reported. As you're seeing, a layered `az iot create` operation does not take effect for  ~5 minutes when it is attempted soon after an `az iot delete` (i.e. within ~45 seconds). 

I've investigated and unfortunately, I don't think there's anything that can be done to fix this in iotedge code because the edge agent is not receiving the deployment until after the 5 minute delay. This indicates that as @veyalla mentioned, this behavior is likely controlled by code in the IoT Hub service. Your best bet is to open a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) against IoT Hub as @veyalla suggested.

Since this seems like an IoT Hub issue, I'll close this issue but feel free to comment and/or re-open if you have any additional concerns about this that are related to the iotedge product.

**Comment by asinitson** [comment]
@nlcamp: Thank you for the confirmation that this is not a problem on our side! I think this will be useful for others when searching for the same issue.

---------------------------------

**Regarding support ticket: no, I am not going to deal with a support ticket.** I don't think I will get anything past "yeah, this is how it works" and I would rather invest the time into figuring out how to migrate from Azure IoT Edge to Kubernetes. We have had enough problems at this point and since the cloud service itself is faulty putting more time into Azure IoT Edge setup does not seem like a good time investment. That being said, if someone actually bothers with creating a ticket somewhere, I can provide additional information.

**Comment by Vic152** [comment]
> @nlcamp: Thank you for the confirmation that this is not a problem on our side! I think this will be useful for others when searching for the same issue.
> 
> **Regarding support ticket: no, I am not going to deal with a support ticket.** I don't think I will get anything past "yeah, this is how it works" and I would rather invest the time into figuring out how to migrate from Azure IoT Edge to Kubernetes. We have had enough problems at this point and since the cloud service itself is faulty putting more time into Azure IoT Edge setup does not seem like a good time investment. That being said, if someone actually bothers with creating a ticket somewhere, I can provide additional information.

Absolutely, spot on.
