### ISSUE TITLE
[monitor-workbook] IoT Edge device details - Module restart timeline - Doesn't show module restarts

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#5734]
If you take a look at the related KQL the problem gets obvious (if I interpret things correctly :innocent:) , the column `instance` is read from `edgeAgent_module_start_total` and therefore reflects the instance number of the `edgeAgent` module, which only changes if the `edgeAgent` itself restarts. It seems to be correct that this is taken into account, because I expect the reported start values are reset on agent restarts. However if only a module crashes and the edgeAgent is running continuously `instance != nextInstance ` never holds and therefore `diff` is always zero - and this leads to the fact that module restarts aren't reported in the 'Module restart timeline' graph.

Please let me know if this problem description is sufficient and if my assumptions are correct.

For easier reference I copied the problematic KQL query:
```
InsightsMetrics
| where TimeGenerated > startTime and TimeGenerated < endTime
| where Name == "edgeAgent_module_start_total"
| extend dimensions=parse_json(Tags)
| extend device = tostring(dimensions.edge_device)
| where device == deviceid
| extend module = tostring(dimensions.module_name)
| extend mversion = tostring(dimensions.module_version)
| where mversion == "1.0" or module == "edgeHub"
| extend instance = tostring(dimensions.instance_number)
| extend value = toint(Val)
| order by module, instance, TimeGenerated
| serialize
| extend nextValue = next(value, 1)
| extend nextInstance = next(instance, 1)
| extend nextmodule = next(module, 1)
| project
    TimeGenerated,
    device,
    instance,
    nextInstance,
    module,
    nextmodule,
    value,
    nextValue
| extend diff = iff((instance != nextInstance and module == nextmodule), 1, 0)
| make-series Count=sum(diff) on TimeGenerated from (startTime - 10m) to endTime step 10m by module
```

**Comment by nlcamp** [comment]
@alaendle - I believe the following diff to the KQL query you referenced will fix the issue:
```
12c12
< | order by module, instance, TimeGenerated
---
> | order by module, TimeGenerated
26c26
< | extend diff = iff((instance != nextInstance and module == nextmodule), 1, 0)
---
> | extend diff = iff((instance != nextInstance and module == nextmodule), 1, iff((instance == nextInstance and module == nextmodule), (value - nextValue), 0))

```
While investigating I noticed another related error in the Availability graph that shows up to the left of the Module Restart TImeline plot. I plan to fix this as well before merging in this fix. Please let me know if you foresee any problems with this proposed fix.

**Comment by nlcamp** [comment]
Re-opening because I made a mistake applying the change. The actual committed change did not match the diff provided above. I'll be merging a fix shortly.
