### ISSUE TITLE
Custom modules that become unhealthy on healthcheck do not restart.

### ISSUE THREAD

**Issue by MCYamamoto** [Azure/iotedge#5746]
Deploying iotedge with vocode.
In "deployment.template.json", we have the following settings.

```
          "SampleModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "on-unhealthy",
            "settings": {
              "image": "${MODULES.SampleModule}",
              "createOptions": {
                "Healthcheck": {
                  "Test": ["CMD", "redis-cli ping || exit 1"],
                  "Interval": 15000000000,
                  "Timeout": 5000000000,
                  "Retries": 1,
                  "StartPeriod": 30000000000
                }
              }
            }
          },
```

We have implemented a custom module to make sure that "redis-cli ping" will fail.
Therefore, when 30 seconds have passed since the SampleModule was started, the status will display "unhealthy" as shown below.
However, the SampleModule will not be restarted.

```
root@obsiot:~# docker ps -a
CONTAINER ID   IMAGE                                                             COMMAND                   CREATED         STATUS                      PORTS                                                                                                                         NAMES															
7a089f4535de   xxxxxx/samplemodule:0.0.2-amd64                       "docker-entrypoint.s…"    2 minutes ago   Up 31 seconds (unhealthy)                                                                                                                                 SampleModule															
```

The "restartPolicy" is set to "on-unhealthy", so it is expected to restart when the status of the custom module becomes "unhealthy".
Is my understanding wrong?
Or is there a configuration error?
A complete execution environment is attached.

[20211025_EdgeSolution.zip](https://github.com/Azure/iotedge/files/7408337/20211025_EdgeSolution.zip)

**Comment by MCYamamoto** [comment]
@lfitchett 
Thanks for the answer.

I have two additional questions.

(1)Will the "on-unhealthy" restartPolicy be supported in the future?

(2)If the answer to (1) is yes, do you know when you plan to support it?

**Comment by vadim-kovalyov** [comment]
@MCYamamoto, sorry for not replying in time to your question. The quick answer is no, we don't have that `restartPolicy` support in our roadmap. If you'd like, you can post it as a suggestion and vote - https://aka.ms/iotedge-suggestion.
