### ISSUE TITLE
SimulatedTemperatureSensor fails soon after being deployed.

### ISSUE THREAD

**Issue by rwhitney456** [Azure/iotedge#5757]
I am trying to deploy the SimulatedTemperatureSensor module to my device before deploying the custom modules I have written.  The module fails after a few minutes, even after being restarted by edgeAgent several times.  

### Device Information
```
Architecture:          armv7l
Byte Order:            Little Endian 
CPU(s):                1 
On-line CPU(s) list:   0 
Thread(s) per core:    1 
Core(s) per socket:    1 
Socket(s):             1 
Model:                 2 
Model name:            ARMv7 Processor rev 2 (v7l) 
CPU max MHz:           1000.0000 
CPU min MHz:           275.0000 
BogoMIPS:              995.32 
Flags:                 half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32 
```
```
Operating System: Debian GNU/Linux 9 (stretch) 
Kernel: Linux 4.14.71-ti-r78 
Architecture: arm 
```
### Docker Info
```
Client: 
Debug Mode: false 
Server: 
Containers: 3 
  Running: 2 
  Paused: 0 
  Stopped: 1 
Images: 4 
Server Version: 3.0.13+azure 
Storage Driver: vfs 
Logging Driver: json-file 
Cgroup Driver: cgroupfs 
Plugins: 
  Volume: local 
  Network: bridge host ipvlan macvlan null overlay 
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog 
Swarm: inactive 
Runtimes: runc 
Default Runtime: runc 
Init Binary: docker-init 
containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429 
runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd 
init version: fec3683 
Security Options: 
  seccomp 
   Profile: default 
Kernel Version: 4.14.71-ti-r78 
Operating System: Debian GNU/Linux 9 (stretch) 
OSType: linux 
Architecture: armv7l 
CPUs: 1 
Total Memory: 991.4MiB 
Name: <my_device_host_name>
ID: 2L67:YYKI:A4QB:LRCN:Y35X:NGBW:JO57:KYKR:PHXA:CSLC:JDUW:VORH 
Docker Root Dir: /var/lib/docker 
Debug Mode: false 
Registry: https://index.docker.io/v1/ 
Labels: 
Experimental: false 
Insecure Registries: 
  127.0.0.0/8 
Live Restore Enabled: false 
WARNING: No cpuset support 
```

### docker.json
`{ 
"storage-driver": "vfs", 
"dns": ["1.1.1.1"], 
"log-driver": "json-file",  
"log-opts": {  
"max-size": "10m",  
"max-file": "3"  
} 
} 
`

### Runtime Version
`iotedge version` returns 1.2.x. 
edgeAgent and edgeHub have rolling tags for 1.2.x.

I manually provisioned the device.  The ONLY lines I changed in the default config.toml were the Hostname, DeviceID and Share Access Key in the manual provisioning section.

### The Error
I'm including the support bundle, but the specific error from the module log is below.

`[Information]: Trying to initialize module client using transport type [Amqp_Tcp_Only]. 
Unhandled exception. System.AggregateException: One or more errors occurred. (Transient network error occurred, please retry.) 
---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. 
---> System.Net.Sockets.SocketException (111): Connection refused `

And here is an error from edgeHub logs.

`<4> 2021-10-26 13:06:16.560 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead. 
<6> 2021-10-26 13:06:17.217 +00:00 [INF] - Updated reported properties for NeousysDev/$edgeHub 
<6> 2021-10-26 13:06:17.436 +00:00 [INF] - Processing pending subscriptions for NeousysDev/$edgeHub 
<0> 2021-10-26 13:06:17.517 +00:00 [FTL] - Unable to start Kestrel. 
System.Net.Sockets.SocketException (13): Permission denied `

Any ideas? `SocketException` is not very descriptive.  One interesting thing about my device: the default user is root (I have never needed `sudo `).  Could this be related?

I've tried a few things...

- rebooting
- investigating `NO CPUSET SUPPORT` .  I checked the kernel with 
`curl -sSL https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh -o check-config.sh
chmod +x check-config.sh
./check-config.sh` from [the Microsoft Page.](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal)  
Then I tried re-configuring and re-building the kernel.  It kept failing but I don't think this was related anyway.  I believe cpusets support is for coordinating devices with several (hundred) cores.  Mine has only one.
- fiddling around with the Azure portal settings like changing the upstream protocol and giving both edgeAgent and edgeHub 'Privileged' host config settings.
- rebooting
- `iotedge check` runs clean,  ALTHOUGH it takes a lot longer (10-15m) than it has on my other devices (10-15s).

Any help is greatly appreciated.  Been scratching my head for a bit.

### Support Bundle Zip
[support_bundle.zip](https://github.com/Azure/iotedge/files/7419401/support_bundle.zip)

**Comment by rwhitney456** [comment]
Thanks for your suggestions.  I don't think anything else is on port 80.  `lsof -i :80` as well as ` sudo fuser 80/tcp`  return nothing.
I also tried installing everything from scratch as another user but I didn't notice anything different.  This doesn't surprise me too much since most of the processes involving iotedge need root privileges and are owned by root (I think...).
Any other ideas?

**Comment by micahl** [comment]
@rwhitney456 if you try this on another device do you see the same issue?

**Comment by varunpuranik** [comment]
@rwhitney456 - did you get a chance to try it on another device? 
Also, can you check a couple of things - 
1. Is something on your device is already bound to port 443 (not 80), as that is what EdgeHub will try to bind to?
2. If nothing there, then can you provide us your edgeHub create options?

**Comment by jlian** [comment]
@rwhitney456 if you've tried above suggestions and still encounter problems, please reopen the issue
