### ISSUE TITLE
edgeHub runs into a strange condition which stops sending message to Azure IoT hub

### ISSUE THREAD

**Issue by KevinKao809** [Azure/iotedge#5766]
## Expected Behavior
EdgeHub shall continue sending a message to Azure IoT Hub every 5 seconds when it receives a message from module.

## Current Behavior
EdgeHub runs as expected couple of hours but stops sending messages on Oct 27 16:12:44  (see edgeHub log)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.
2.
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    One or more errors occurred. (Connection refused /var/run/iotedge/mgmt.sock)
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.10.2 but 1.1.7 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
‼ host time is close to real time - Warning
    Time on the device is out of sync with the NTP server. This may cause problems connecting to IoT Hub.
    Please ensure time on device is accurate, for example by installing an NTP daemon.
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 81 days (at 2022-01-16 11:12:26 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.


```
</details>

### Device Information
* Host OS [Debian 9]: 
* Architecture [arm32]: 
* Container OS [Linux containers]: 

### Runtime Versions
* aziot-edged [1.0.10.2]: 
* Edge Agent [1.0.10.3]: 
* Edge Hub [1.0.10.3]: 
* Docker/Moby [3.0.5]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```


[edgeAgent.log](https://github.com/Azure/iotedge/files/7424881/edgeAgent.log)


```
</details>

<details>
<summary>edge-hub logs</summary>

```
[edgeHub.zip](https://github.com/Azure/iotedge/files/7424880/edgeHub.zip)


```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue
![message](https://user-images.githubusercontent.com/3096796/139039047-10cb6f08-08e3-4048-81a2-b6d5fd9eebec.jpg)
.
[agent.log](https://github.com/Azure/iotedge/files/7424920/agent.log)

![message2](https://user-images.githubusercontent.com/3096796/139039058-e4b1607a-d1a0-4a20-b4b2-7bfb9618a64e.jpg)
![edgeHub](https://user-images.githubusercontent.com/3096796/139039193-d4354970-158b-4678-ba03-e1b7af5be55f.jpg)
![agent](https://user-images.githubusercontent.com/3096796/139039205-81bad94e-adf0-4ad4-bd6f-4750d722884e.jpg)

thingspro-agent is an edge module that sends reported properties when it is connected and sends telemetry to edgeHub every 5 seconds.
On thinngspro-agent log, it didn't receive any message send fail event from edgeHub after Oct 27 16:12:44.

**Comment by lfitchett** [comment]
Hi, thanks for opening an issue. 

I took a look through the logs, but I haven't isolated the cause of the issue yet. I wanted to update you on the status and will continue looking into it.

**Comment by RobertIIoT** [comment]
@lfitchett is there anything we at Moxa can do to help you isolate this further?

**Comment by lfitchett** [comment]
@RobertIIoT sorry for the late response, are you still seeing this issue? Is it consistent? I don't see any obvious reason for the messages to have stopped.

**Comment by KevinKao809** [comment]
This case doesn't happen again. Closed.
