### ISSUE TITLE
Moby engine doesn't work with Raspberry Pi OS Buster and custom vision containers

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/iotedge#5767]
## Expected Behavior

The Moby engine that is installed with IoT Edge should support Raspberry Pi OS Buster. Currently it has issues, related to Alpine updates.

As an example:

* Set up IoT Edge on a Raspberry Pi running Buster
* Export a Raspberry Pi docker container from Custom Vision
* Build this container on a Raspberry Pi with IoT Edge installed

The expected behavior is the container should build successfully, and this was the case up until the last couple of months.

## Current Behavior

The following error occurs with the `docker build` command:

```output
pi@edge-test:~/docker $ sudo docker build .
Sending build context to Docker daemon  86.38MB
Step 1/9 : FROM python:3.7-slim
3.7-slim: Pulling from library/python
4e5300249f84: Pull complete 
fe75bff67d10: Pull complete 
6a299a3fd5d9: Pull complete 
96c18185415b: Pull complete 
a84c094467d0: Pull complete 
Digest: sha256:c2cc09c3de140f59b3065b9518fa7beb5fbedb4414762963bfe01079ce219f2e
Status: Downloaded newer image for python:3.7-slim
 ---> 68fdc5095c5d
Step 2/9 : RUN apt update && apt install -y libjpeg62-turbo libopenjp2-7 libtiff5 libatlas-base-dev libgl1-mesa-glx
 ---> Running in d995a8846ae2

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Err:2 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
The command '/bin/sh -c apt update && apt install -y libjpeg62-turbo libopenjp2-7 libtiff5 libatlas-base-dev libgl1-mesa-glx' returned a non-zero code: 100
```

Going further, with a container built using Docker on a different device instead of Moby engine, running the container under IoT Edge give the same error.

## Steps to Reproduce

* Set up a Raspberry Pi using Buster using the latest Raspberry Pi imager and update to the latest version
* Install IoT Edge bu following these instructions: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal
* Create a Custom Vision docker container and export it as ARM (Raspberry Pi 3)
* Copy the container to the Pi and build it with `sudo docker build .`

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
× keyd configuration is well-formed - Error
    Could not open file. You might need to run this command as root.

Configuration checks
--------------------
0 check(s) succeeded.
1 check(s) raised errors. Re-run with --verbose for more details.


pi@edge-test:~/docker $ sudo iotedge check

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
32 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Raspberry Pi OS 10
* Architecture [e.g. amd64, arm32, arm64]: Arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.4
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* Docker/Moby [run `docker version`]:

```
Client:
 Version:           3.0.13+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
 Built:             Thu May 28 20:41:25 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fda0c
  Built:            Mon Jun  1 20:22:16 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
``` 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Additional Information

This change is described in:
* https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/
* https://github.com/debuerreotype/docker-debian-artifacts/issues/116

The fix for the Pi is to use a different version of libseccomp2, and a version of Docker greater than 19.0.4.

One suggestion for a fix:

* Add instructions to use the back ports of libseccomp2 to the IoT edge documentation
* Update the Azure fork of Moby engine to be based on a later version

I'm aware the docs only show Stretch as supported, but Buster has been out for 2 years, and this was working until recently.

**Comment by micahl** [comment]
@jimbobbennett assuming you followed the instructions for Stretch then try changing your /etc/apt/sources.list.d/microsoft-prod.list from

> deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/stretch/multiarch/prod stretch main

to 

> deb [arch=armhf] https://packages.microsoft.com/debian/10/prod buster main

That should enable you to find the [more recent versions of moby-engine](https://packages.microsoft.com/debian/10/prod/pool/main/m/moby-engine/) that are appropriate for Buster.  

Since there aren't Buster packages for IoT Edge on packages.microsoft.com you'd need to get them from our github releases page.  E.g.

* [aziot-edge_1.2.5-1_debian10_armhf.deb](https://github.com/Azure/azure-iotedge/releases/download/1.2.5/aziot-edge_1.2.5-1_debian10_armhf.deb)
* [aziot-identity-service_1.2.4-1_debian10_armhf.deb](https://github.com/Azure/azure-iotedge/releases/download/1.2.5/aziot-identity-service_1.2.4-1_debian10_armhf.deb)

**Comment by Padu98** [comment]
@micahl Installing moby-engine now worked for me. But If I try to install on of the above listed packages from your github  release page, I get the following message: 
 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package aziot-identity-service_1.2.4-1_debian10_armhf.deb
E: Couldn't find any package by glob 'aziot-identity-service_1.2.4-1_debian10_armhf.deb'
E: Couldn't find any package by regex 'aziot-identity-service_1.2.4-1_debian10_armhf.deb'

**Comment by jimbobbennett** [comment]
Thanks @micahl, I'm just working through testing the various Raspberry Pi OS versions from Stretch onwards to see what compatibility we have so I can raise an issue against the docs. I'm hoping we fix everything and release support for Buster and Bullseye very soon as Stretch ends long term support in June next year.

So far, I can't install Moby-engine on stretch by following the instructions, as the packages list is incorrect, and is missing an arm entry:

https://github.com/Azure/iotedge/issues/5882

**Comment by jimbobbennett** [comment]
@micahl - this also occurs with Stretch

https://github.com/Azure/iotedge/issues/5883

**Comment by kottoz** [comment]
@jimbobbennett  What is the version of your Raspberry Pi? is it 4 or 3

**Comment by jimbobbennett** [comment]
@kottoz - I've tried on both - a 4 and a 3B+

**Comment by kottoz** [comment]
@jimbobbennett, i have issue may be like yours, instead i can't install iotedge 1.2 on PI-4, here is my issue #5928
