### ISSUE TITLE
Workload CA does not honor [common_name] and is hard coded to "iotedge workload ca"

### ISSUE THREAD

**Issue by ksaye** [Azure/iotedge#5782]
## Expected Behavior
When using EST certificate providers like GlobalSign or DigiCert, IoT Edge always sets the CN or the Edge CA to "iotedge workload ca", which makes it difficult, at scale, to manage and monitor specific certificates.  This happens even when we try to use the common_name setting in config.toml, as shown below:

```
[edge_ca]
method = "est"
common_name = "Gateway1234 Edge CA"
url = "https://xxxxxca.est.edge.dev.globalsign.com:443/.well-known/est/"
```

## Current Behavior
Currently, this creates all certificate with 'iotedge workload ca', as shown below:

![image](https://user-images.githubusercontent.com/15837044/139750511-b88236de-16e1-4070-b590-7e67332a2ad1.png)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Setup an EST server,
2. Configure IoT Edge using the Identity Service here: https://github.com/Azure/iot-identity-service/runs/3805391728, that supports CA Certs via EST
3. Apply a config file, similar to below:

```

[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net/"
id_scope = "0ne*********0"

[provisioning.attestation]
method = "x509"
registration_id = "*****bootstrap-globalsign-vnm2"

identity_cert = { method = "est", common_name = "*****bootstrap-globalsign-vnm2", url ="https://*****.est.edge.dev.globalsign.com:443/.well-known/est/" }


[cert_issuance.est]
trusted_certs = [
        "file:///var/secrets/globalsign_root.pem",
]

[cert_issuance.est.auth]
username = "*****"
password = "*****"

# EST ID cert requested via EST bootstrap ID cert
 bootstrap_identity_cert = "file:///var/secrets/*****_bootstrap_gs.pem"
 bootstrap_identity_pk = "pkcs11:token=IoTEdgeCert;object=bootstrap-rsa-pair?pin-value=*****" # PKCS#11 URI

[cert_issuance.est.urls]
#default = "https://*****.est.edge.dev.globalsign.com:443/.well-known/est/"

[aziot_keys]
pkcs11_lib_path = "/usr/local/lib/libtpm2_pkcs11.so"

[edge_ca]

method = "est"
common_name = "***** test Edge CA"
url = "https://*****.est.edge.dev.globalsign.com:443/.well-known/est/"
```
4. Note how the common_name is not applied

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]:  https://github.com/Azure/iot-identity-service/suites/3964124249/artifacts/99607813
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by onalante-msft** [comment]
We are aware of this limitation. Even though there is a configuration option for the common name in `[edge_ca]`, edgelet does not use it during CSR generation (*cf.* [1.2](https://github.com/Azure/iotedge/blob/release/1.2/edgelet/edgelet-http-workload/src/server/cert/mod.rs#L341-L345), [master](https://github.com/Azure/iotedge/blob/master/edgelet/edgelet-http-workload/src/module/cert/mod.rs#L266)). On the other hand, `certd` cannot override the CSR DN unless it is using a local signing method (either self-signed or local CA): with EST, it simply forwards the CSR. So, when the edge CA is issued by EST, it always has the hard-coded common name "iotedged workload ca". The situation is slightly better in master, where the string is suffixed by the device ID.

**Comment by maksokami** [comment]
it would be helpful to at least make the CN unique (even just a device ID suffix), so that customers could keep track of issued certs on the CA side.

**Comment by ksaye** [comment]
@onalante-msft, I think that the [master](https://github.com/Azure/iotedge/blob/master/edgelet/edgelet-http-workload/src/module/cert/mod.rs#L266) change you suggest will suffice.  Clearly the deviceID will be unique (per IoT Hub) so that should work.

Because I don't follow 100% the master --> release patterns, would this change be expected in the next release of 1.2.x?

**Comment by onalante-msft** [comment]
If you would like to test a build immediately, you can clone the source of #5785. Please be warned, however, that I have not tested the build.

Unfortunately, I cannot give a precise day for our next 1.2 release. However, I think this issue is significant. I will see if the aforementioned PR can be included in the next release.

**Comment by ksaye** [comment]
Thanks again.  This is significate, but it is not required this month or quarter.  Closing the issue.
