### ISSUE TITLE
Edge Hub MQTT Broker - Device messages are not published

### ISSUE THREAD

**Issue by lukasbrun** [Azure/iotedge#5789]
When setting up the edge module and connecting to the built-in MQTT broker with an MQTT Client, I did not get any notifications on device messages. Any messages on user-defined topics worked fine, however. Is this the intended behaviour? If so, is there a reason why device messages are not published to MQTT clients?

Edge Hub Module Twin:
```jsonc
{
    // Module Identity section
    "properties": {
        "desired": {
            "routes": {
                // ...
            },
            "schemaVersion": "1.2",
            "storeAndForwardConfiguration": {
                "timeToLiveSecs": 7200
            },
            "mqttbroker": {
                "authorizations": [
                    {
                        "identities": [
                            "{{iot:identity}}"
                        ],
                        "allow": [
                            {
                                "operations": [
                                    "mqtt:connect",
                                    "mqtt:subscribe",
                                    "mqtt:publish"
                                ],
                                "resources": [
                                    "#",
                                    "$SYS/#",
                                    "devices/+/messages/events/"
                                ]
                            }
                        ]
                    }
                ]
            },
            // Metadata
        },
        "reported": {
            "schemaVersion": "1.0",
            "version": {
                "version": "1.2.4",
                "build": "47309863",
                "commit": "d23e0cafc3a1e4b9741b99cba8077a6df3f015c6"
            },
            // ...
        }
    },
    "configurations": {
        // ...
    },
    "tags": {}
}
```

Subscribed MQTT topics:
* \#
* devices/+/messages/events/

**Comment by pmzara** [comment]
@lukasbrun
Could you give more details about your scenario? iotegde version, OS version, etc

**Comment by lukasbrun** [comment]
iotedge version: 1.2.3
Edge Hub version: 1.2.4.47309863
OS version: Debian Buster
MQTT Client(s) used: MQTT Explorer 0.3.5, run on a different computer from the edge device

I used two clients: One with the edge device identity, one with the identity of one of its child devices.
I tried publishing messages on one client and receiving them on the other. This works for custom topics, but not for topics of the form `devices/<device Id>/messages/events`

After publishing a message to `foo/bar`, the topic is shown in the left pane:
![grafik](https://user-images.githubusercontent.com/53816889/140274309-bd1ec7c7-908c-4bdb-9230-2a556a001792.png)

After publishing a message to `devices/child-device-1/messages/events`, this new topic is not shown:
![grafik](https://user-images.githubusercontent.com/53816889/140274945-9e4b672a-7947-4653-98df-a1e0685dea55.png)
(`child-device-1` exists, and it is a child of the edge device)

**Comment by vadim-kovalyov** [comment]
@lukasbrun, thanks for trying MQTT Broker in Edge. The scenario that you're trying to achieve is not supported. The `devices/<device Id>/messages/events` topics are special case topics (as well as other topics mentioned [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support)). They do not work in Edge as regular mqtt topics, but are treated as "IoTHub primitives". In your case this is "a device telemetry messages", so to route them, you need to setup routing in the corresponding twin section. But I'm not sure if that's what you need.

If you provide more details about what problem are you trying to solve - I can try to help.

**Comment by lukasbrun** [comment]
@vadim-kovalyov My goal is to send device telemetry messages to a 3rd party MQTT client running on some other computer on-site, as well as to the upstream IoT Hub

**Comment by vadim-kovalyov** [comment]
@lukasbrun, you can try to publish `$iothub/<device_id>/messages/events/` and subscribe `$iothub/vk_pub/messages/events/#`. Please note "/" at the end for pub, "/#" for sub, and "$iothub" prefix. But again, this is **not supported feature**, so you'll be using it **AS IS**. There is no guarantee that it will continue to work that way in the new versions of edge.

**Comment by vadim-kovalyov** [comment]
I'm closing this for now due to inactivity. Please let me know if you have any further questions.

**Comment by lukasbrun** [comment]
@vadim-kovalyov Thank you for the suggestion. Can you also subscribe to messages sent by a module client in this way?

**Comment by vadim-kovalyov** [comment]
@lukasbrun, you're welcome! 

>Can you also subscribe to messages sent by a module client in this way?

Yes, for that use `$iothub/<edge_id>/<module_id>/messages/events/#` topic.
