### ISSUE TITLE
Getting an empty list when running iotedge list

### ISSUE THREAD

**Issue by belkinirena** [Azure/iotedge#58]
I'm running on Ubuntu 16.04 machine
I followed the quick-start instructions for Linux:
https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux

When running the command:
sudo iotedge list

I'm getting an empty list:
administrator@administrator-desktop:~$ sudo iotedge list
NAME STATUS DESCRIPTION CONFIG

These are the logs:
[ERR!] - Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" })
[WARN] - Error in watchdog when checking for edge runtime status:
[WARN] - Identity error
[WARN] - caused by: IoT Hub service error
[WARN] - caused by: Core error
[WARN] - caused by: Hyper error
[WARN] - caused by: Connection timed out (os error 110)
[INFO] - Checking edge runtime status
[INFO] - Creating and starting edge runtime module edgeAgent

**Comment by darobs** [comment]
Hello @belkinirena,

Is that consistent with the list of containers? i.e. if you do a `docker ps -a` are any modules running?

**Comment by myagley** [comment]
This looks like a connectivity error with IoT Hub. The `iotedged` is failing to update the Edge Agent identity. Can you please verify that the device can reach IoT Hub?

**Comment by belkinirena** [comment]
Thanks for the quick response.
@darobs docker ps -a return an empty list also.
@myagley I believe that you are right.  
This is the output of curl -v:
![image](https://user-images.githubusercontent.com/20966642/43137538-b606c29e-8f54-11e8-83c4-c048ac6a0886.png)

Any idea what can be the cause for the failed connection?
I'm running from my cooperate machine, could it be a proxy issue? (The firewall is disabled)

**Comment by myagley** [comment]
Unfortunately, IoT Edge can't run behind a proxy yet. This is an important feature that we will be looking at soon.

From looking at the log output, it looks like the proxy is returning a 503, which could indicate it is having trouble proxying to your iot hub.
