### ISSUE TITLE
Pull Images for deployment updates before tearing down the old deployment

### ISSUE THREAD

**Issue by KamalAman** [Azure/iotedge#5803]
## Expected Behavior
When changing a modules image version through a deployment update, the IoT Edge device should pull down the new image before stopping the old image. More of a `RollingUpdate` with minimal downtime between updates.

## Current Behavior
Currently the existing deployment is torn down, then images are pulled, and then the new deployment is spin up. 

## Steps to Reproduce
Change a modules docker image version

## Context (Environment)
In slow network conditions, downloading docker images can take minutes to hours to download. Currently the update & system down time is dramatically impacted due to not having a rolling like update. The current work around is to manually access each device and have it pull down the image first before deployment and update which defeats the OTA update life cycle.

**Comment by veyalla** [comment]
What is the environment you're deploying IoT Edge in?

**Comment by KamalAman** [comment]
IoT Edge does do this. This issue was caused because the EdgeAgent and EdgeHub was also updated in the same deployment which tore everything down. Under a normal deployment without changing the edgeAgent/EdgeHub versions, a smooth rollover does happen.
