### ISSUE TITLE
#5746 Additional Questions

### ISSUE THREAD

**Issue by MCYamamoto** [Azure/iotedge#5804]
#5746 was closed and there were no answers to my questions, so I created a new issue.

I have two additional questions for #5746.

(1)Will the "on-unhealthy" restartPolicy be supported in the future?

(2)If the answer to (1) is yes, do you know when you plan to support it?

**Comment by vadim-kovalyov** [comment]
@MCYamamoto, sorry for not replying in time to your question. The quick answer is no, we don't have that `restartPolicy` support in our roadmap. If you'd like, you can post it as a suggestion and vote - https://aka.ms/iotedge-suggestion.
