### ISSUE TITLE
Error 500 IoT Edge module container Image expecting IOTEDGE_WORKLOADURI enviorment variable

### ISSUE THREAD

**Issue by prashbv** [Azure/iotedge#584]
Error 500 at IoT Edge module 

The container Image expecting IOTEDGE_WORKLOADURI enviorment variable when trying to run the application in debug mode.

[Module] Module info: {
  "moduleId": "WinUDPListener",
  "managedBy": "IotEdge",
  "deviceId": "vm-win10-edge",
  "generationId": "636790063927487363",
  "etag": "NjE0NzI1NjM2",
  "connectionState": "Disconnected",
  "connectionStateUpdatedTime": "0001-01-01T00:00:00",
  "lastActivityTime": "0001-01-01T00:00:00",
  "cloudToDeviceMessageCount": 0,

Connection State is also disconnected.  When tried running the module at the edge runtime envionment using powershell

Unhandled Exception: System.AggregateException: One or more errors occurred. (Environment variable IOTEDGE_WORKLOADURI is required.) ---> System.InvalidOperationException: Environment variable IOTEDGE_WORKLOADURI is required.
   at Microsoft.Azure.Devices.Client.Edge.EdgeModuleClientFactory.CreateInternalClientFromEnvironmentAsync()
   at UdpListenerModule.Program.Init() in C:\app\Program.cs:line 53
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at UdpListenerModule.Program.Main(String[] args) in C:\app\Program.cs:line 27

Appreciate your help as setting  IOTEDGE_WORKLOADURI  environment variable didnt make any difference.

![image](https://user-images.githubusercontent.com/26093186/49214469-bf2c8f00-f3ec-11e8-8278-8248bc716469.png)

![image](https://user-images.githubusercontent.com/26093186/49214510-d9666d00-f3ec-11e8-96a9-38361904cbc1.png)

**Comment by prashbv** [comment]
Hello Mike,

Thanks for your time in reading out this issue.   These Iot edge modules are a customer one built in C# and deployed into the edge runtime both onprem and VM hosted in cloud.

I am not getting the 500 error now and the module is also running.  But during its runtime its not able to get the environment variable IOTEDGE_WORKLOADURI although its been configured at the .env file and as well at the within module environment variables section at the azure portal.

![image](https://user-images.githubusercontent.com/26093186/49423274-f0c2a300-f7bc-11e8-9597-db659cb2ef84.png)

Appreciate if you have any advise.

**Comment by myagley** [comment]
This environment variable (`IOTEDGE_WORKLOADURI`) is set by the runtime itself. It shouldn't need to be set explicitly via the .env file or in the portal.

What version of iotedge is running? You can run `iotedge version` in the terminal to get the version number.

**Comment by prashbv** [comment]
ISSUE RESOLVED.
For a custom application like C# edge module in my case IOTEDGE_WORKLOADURI i had to configure it into the CreateOptions section which i did earlier but failed due to syntax issues. 

Upon defining Createoptions section with required environment variables into deployment template file pushed these into the edge solution config file and was able to be picked up during runtime.

Likewise the same can be configured at the ARM portal within the module when you select through Set Module option.  

However the text boxes given to input envionment variables wasnt really working well and i did stay away from that option as working through the application config file was much easier.

Thankyou for your time.  Cheers!

**Comment by RotateAt60MPH** [comment]
How about some additional detail on how you/where solved this?

**Comment by cdjc** [comment]
I solved this by adding:

```xml
<ItemGroup>
  <ProjectCapability Include="AzureIoTEdgeModule" />
</ItemGroup>
```
to the .csproj file
