### ISSUE TITLE
Module to Module communication over different Edge hubs

### ISSUE THREAD

**Issue by julianhatzky** [Azure/iotedge#585]
Hey there!

I wanted to ask if there is a way to realize module to module communication over different devices.

So basically what I mean is I have for example one edge hub with a module and another edge hub with some other module on another device.
Can those two modules communicate directly ? (e.g via their moduleID or device id string)?

Kind Regards,

Julian

**Comment by ju2ez** [comment]
The only thing I could found so far is to shift the cloud service onto one of the devices.
https://blogs.windows.com/buildingapps/2016/09/08/device-to-device-communication-with-azure-iot-hub/

Is this the only solution so far? And if so, is there a way to connect this cloud to another?
Kind Regards,
Julian

**Comment by ju2ez** [comment]
Hey thanks for your answer!
That sounds like a fair way to archive D2D connection. Is there a "best-practice" to do so? 
Can they speak over their Ip Adresses or are there virtual network adresses (next to the model id's) provided by the azure environment which they could use to communicate with each other (e.g. as well via MQTT or AMQP)

Its really nice that you at least consider to build it someday!
That shouldn't sound rude but I don't really see "edge computing" as long as you have to still use the cloud in your communication route. What is your opinion on that?

Kind regards,
Julian

**Comment by lt72** [comment]
Closing as it seems stale. Please re-open if necessary.
