### ISSUE TITLE
edge container network seems to hang after after a few hours of operation.

### ISSUE THREAD

**Issue by Rumpkie** [Azure/iotedge#5850]
## Expected Behavior
Docker azure-iot-edge network should continuously provide access to and from the external network of the the edge modules

## Current Behavior
after a few minutes sometimes hours the network seems to drop access to the world outside the host.
restarting.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Run the modules as normal, at some point within the next 24 hours the network will stop working.
2. iotedge check fails container network reaching azure but the host doesn't have an issue.

### Output of `iotedge check`
   everything is good except the container network section.

<details>
<summary>Click here</summary>

```

√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK

√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK

√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK

× container on the default network can connect to IoT Hub AMQP port - Error

    Container on the default network could not connect to qa2-f01-iothub-01.azure-devices.net:5671

× container on the default network can connect to IoT Hub HTTPS / WebSockets port - Error

    Container on the default network could not connect to qa2-f01-iothub-01.azure-devices.net:443

× container on the default network can connect to IoT Hub MQTT port - Error

    Container on the default network could not connect to qa2-f01-iothub-01.azure-devices.net:8883

× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error

    Container on the azure-iot-edge network could not connect to qa2-f01-iothub-01.azure-devices.net:5671

× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error

    Container on the azure-iot-edge network could not connect to qa2-f01-iothub-01.azure-devices.net:443

× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error

    Container on the azure-iot-edge network could not connect to qa2-f01-iothub-01.azure-devices.net:8883

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture AMD64
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent mcr.microsoft.com/azureiotedge-agent:1.1
* Edge Hub [mcr.microsoft.com/azureiotedge-hub:1.1.3
* Docker/Moby 20.10.5+azure (we updated the engine to 3.0.12 but it has had no effect)

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs 
There isn't much in the way of usefulness from the edge side it says that it cannot connect
<!--

## Additional Information
This works for a various amounts of time and then stops, the Ip tables and Ip chains and docker network inspect azure-iot-edge all are the same when both working and not. I loaded a container full of network tools and when its working I can ping the host's default gateway from inside the container when it stops working I cannot. I can always ping the external network IP of the host and the containers can talk to each other. I am at a loss. restarting the docker service seems to fix the problem briefly.

**Comment by gordonwang0** [comment]
Could look at the logs from docker to see if any errors are detected?

**Comment by nyanzebra** [comment]
@Rumpkie, are you still having issues?

**Comment by micahl** [comment]
Closing this issue until / unless additional info is available to further debug.
