### ISSUE TITLE
Unable to Authenticate downstream device with Certificates generated from script

### ISSUE THREAD

**Issue by gindarapid** [Azure/iotedge#5865]
Hi, 

I am trying to test a transparent gateway and a downstream device scenario but am facing an issue authentication the gateway.
Both devices are raspberry pi.

gateway hostname: rpigateway
downstream device hostname: rpidownstreamdev1

Here are the steps that I did.

**Step 1:** Followed this guide to generate the test certificates on the gateway device (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11). I used the **certGen.sh** script provided from the guide.
From this step I got the:

    Root CA certificate (azure-iot-test-only.root.ca.cert.pem)
    Device CA certificate (iot-edge-device-ca-rpigateway_device_ca.cert.pem)
    Device CA private key (iot-edge-device-ca-rpigateway_device_ca.key.pem)

**Step 2:** modified the gateway's config file (/etc/aziot/config.toml) and referenced the :

    trust_bundle_cert (azure-iot-test-only.root.ca.cert.pem) 
    edge_ca cert (iot-edge-device-ca-rpigateway_device_ca-full-chain.cert.pem)
    edge_ca pk (iot-edge-device-ca-rpigateway_device_ca.key.pem)

I then applied the new config file  (sudo iotedge config apply)

**Step 3:** Copied the downstream device connectionstring from the IoT Hub and set the parent device to the rpigateway. I then modified the connection string of the downstream device and added the gateway device hostname (;GatewayHostName=rpigateway) towards the end of the connection string and uncommented/modified the parent_hostname = "rpigateway".
I then applied the new config file  (sudo iotedge config apply). 

**Step 4:** Copied the rpigateway's root CA certificate from Step 1 to the downstream device. And ran the command:

    sudo cp /xxx/certs/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
    sudo update-ca-certificates

I then verified that the certificate is there on the /etc/ssl/certs and it is ok.

**Step 5:** updated the firewall rules on both the rpigateway and the downstream device to open port 8883, 5674, and 443

**Step 6:** updated the hostname file on both the rpigateway and the downstream device to have reference of their respective hostnames and IP Addresses.

**Step 7:** Followed this guide as the final step to test connection (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device?view=iotedge-2020-11) and ran the command:

    openssl s_client -connect rpigateway:8883 -CAfile /xxx/certs/azure-iot-test-only.root.ca.cert.pem -showcerts

And here are the issues that I encountered:

**Issue #1 :** on Step 3 after applying the new config file, both the edge_hub and edge_agent refuses to start. I played around the config file, and it is able to run **ONLY** if I commented back the parent_hostname = "rpigateway" section.

**Issue #2 :** on Step 4 after running the command (sudo update-ca-certificates) and checked the /etc/ssl/certs directory, I can see the certificate is there. BUT, it added an additional .pem extension on the certificate so it becomes "azure-iot-test-only.root.ca.cert.pem.pem". I tried to remove the extra .pem extension, rebooted and ran the openssl connect again, but it still fails to verify the connection.

**Issue #3 :** on Step 7 while running the openssl connect, I am not able to get the expected "Verify return code: 0" as steted on the guide, but I am getting "Verify return code: 21 (unable to verify the first certificate)".

Issue #2 confuses me as I ran the command as it asked on the guide, but why does it add an additional .pem extension on the certificate file?
As for Issue #1 and Issue #3 is there a step that I missed or incorrectly followed?

Any information or pointers is really really appreciated! Thank you

**Comment by nyanzebra** [comment]
Hi, from both the downstream device and the parent could you run `iotedge support-bundle`? If I had to guess the problem might be the FQDN for the parent not being recognized... but this is just a guess; to see if this is the case, find the actual IP and run step 7 and see if can connect and auth with the cert. If so, then swapping the hostname = "blah" section with the IP should hopefully fix the problem.

**Comment by nyanzebra** [comment]
^ actually, the support-bundle might share too much information, could you instead just share the result of `iotedge check`?

**Comment by gindarapid** [comment]
> ^ actually, the support-bundle might share too much information, could you instead just share the result of `iotedge check`?

Hi, thanks for responding!

Here is the iotedge check result, with the parent-hostname=<gateway ip address>.
The edge-hub and edge-agent refuses to start if I use the parent-hostname on the config.toml file


`Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
× host can connect to and perform TLS handshake with iothub AMQP port - Error
    Make sure the parent device is reachable using 'curl https://parenthostname'. Make sure the the trust bundle has been added to the trusted store: sudo cp <path>/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
                sudo update-ca-certificates
× host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Error
    Make sure the parent device is reachable using 'curl https://parenthostname'. Make sure the the trust bundle has been added to the trusted store: sudo cp <path>/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
                sudo update-ca-certificates
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Make sure the parent device is reachable using 'curl https://parenthostname'. Make sure the the trust bundle has been added to the trusted store: sudo cp <path>/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
                sudo update-ca-certificates

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct parent_hostname - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image '192.168.1.124/azureiotedge-diagnostics:1.2.5' locally
    docker: Error response from daemon: Get "https://192.168.1.124/v2/": x509: cannot validate certificate for 192.168.1.124 because it doesn't contain any IP SANs.
    See 'docker run --help'.
× container time is close to host time - Error
    Could not query local time inside container
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
× container on the default network can connect to upstream  AMQP port - Error
    Container on the default network could not connect to 192.168.1.124:5671
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to 192.168.1.124:443
× container on the default network can connect to upstream MQTT port - Error
    Container on the default network could not connect to 192.168.1.124:8883
× container on the IoT Edge module network can connect to upstream AMQP port - Error
    Container on the azure-iot-edge network could not connect to 192.168.1.124:5671
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to 192.168.1.124:443
× container on the IoT Edge module network can connect to upstream MQTT port - Error
    Container on the azure-iot-edge network could not connect to 192.168.1.124:8883
19 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
13 check(s) raised errors. Re-run with --verbose for more details.`

**Comment by gindarapid** [comment]
did an update with the openssl_root_ca.cnf and inserted the **subjectAltName = DNS:rpigateway** under the [ v3_ca ].

Here is the latest iotedge check:
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ host time is close to reference time - Warning
    Time on the device is out of sync with the NTP server. This may cause problems connecting to IoT Hub.
    Please ensure time on device is accurate, for example by installing an NTP daemon.
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
× host can connect to and perform TLS handshake with iothub AMQP port - Error
    Make sure the parent device is reachable using 'curl https://parenthostname'. Make sure the the trust bundle has been added to the trusted store: sudo cp <path>/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
                sudo update-ca-certificates
× host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Error
    Make sure the parent device is reachable using 'curl https://parenthostname'. Make sure the the trust bundle has been added to the trusted store: sudo cp <path>/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
                sudo update-ca-certificates
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Make sure the parent device is reachable using 'curl https://parenthostname'. Make sure the the trust bundle has been added to the trusted store: sudo cp <path>/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
                sudo update-ca-certificates

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct parent_hostname - OK
× parent hostname is resolvable from inside container - Error
    Failed to resolve parent hostname rpigateway
× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'rpigateway/azureiotedge-diagnostics:1.2.5' locally
    docker: Error response from daemon: pull access denied for rpigateway/azureiotedge-diagnostics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
    See 'docker run --help'.
× container time is close to host time - Error
    Could not query local time inside container
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ Agent image is valid and can be pulled from upstream - OK

Connectivity checks
-------------------
× container on the default network can connect to upstream  AMQP port - Error
    Container on the default network could not connect to rpigateway:5671
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to rpigateway:443
× container on the default network can connect to upstream MQTT port - Error
    Container on the default network could not connect to rpigateway:8883
× container on the IoT Edge module network can connect to upstream AMQP port - Error
    Container on the azure-iot-edge network could not connect to rpigateway:5671
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to rpigateway:443
× container on the IoT Edge module network can connect to upstream MQTT port - Error
    Container on the azure-iot-edge network could not connect to rpigateway:8883
18 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
14 check(s) raised errors. Re-run with --verbose for more details.

**Comment by nyanzebra** [comment]
I am going to check with my team and see if they have some ideas here, but could you also post the output of this:

`openssl s_client -connect <IP address goes here>:8883 -CAfile /xxx/certs/azure-iot-test-only.root.ca.cert.pem -showcerts`

Just to see if there is an issue with resolving the DNS name of your parent device.

**Comment by nyanzebra** [comment]
We do have this tutorial with a script to create everything necessary to install for each device in the hierarchy... tutorial: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-nested-iot-edge?view=iotedge-2020-11
script: https://github.com/Azure-Samples/iotedge_config_cli/tree/main/src

Since this is automated for generated everything that needs to be done for deployment (except for filling out some fields in a yaml file) this might be an easy thing to try and see if this gets you going. From above steps everything looks correct, but this script should do all the same things and might be easier to work with for you. 

I will post here if I see an obvious mistake on the steps followed that are leading you to cert problems, to make sure things are perfectly clear :)

**Comment by nyanzebra** [comment]
@gindarapid if you follow this script linked above does it unblock you?

**Comment by nyanzebra** [comment]
Closing this issue due to lack of communication, but feel free to open again if the issue persists! :)
