### ISSUE TITLE
[QUESTION] How to connect modules running on a nested edge to Azure resources?

### ISSUE THREAD

**Issue by F-Joachim** [Azure/iotedge#5870]
Specifically, I want to connect the Azure IoT Edge [MetricsCollector ](https://github.com/Azure/iotedge/tree/master/edge-modules/MetricsCollector) to Azure Log Analytics in a nested edge scenario, where the `MetricsCollector` is running on the nested edge.

How do I have to parameterize the `MetricsCollector` (or any other module) in the deployment manifest, so that the module is able to connect to Azure Log Analytics via the parent edge?

**Comment by huguesBouvier** [comment]
Usually you can setup the API proxy to reroute the message to the workspaceId

How to setup API proxy:
You have to add a rule to forward message + token. There is a doc that explains it here:
https://github.com/Azure/iotedge/tree/master/edge-modules/api-proxy-module

However, in this case I don't think that's possible. The metric collector has the url hardcoded: https://github.com/Azure/iotedge/blob/master/edge-util/src/Microsoft.Azure.Devices.Edge.Util/azureLogAnalytics/AzureLogAnalytics.cs#L52
It will work only if your nested device has internet access.

**Comment by F-Joachim** [comment]
I've tried to configure the nginx proxy, so that a module running on the nested edge is able to connect to the internet via the parent edge and our corporate proxy. The flow should be as follows:

```
----------------------               ----------------               -------------------               ---------------
|     Nested Edge    |      ==>      | Parent Edge  |      ==>      | Corporate Proxy |      ==>      | Target host |
|   (ubuntu module)  |               | (API proxy)  |               -------------------               | (internet)  |
----------------------               ----------------                                                 ---------------
```

I haven't found a solution to configure the nginx proxy so that I can curl a website from the ubuntu module. The request ends up with the http code **302 Found**.

This is the relevant part of my nginx proxy:

```conf
if ($uri ~ ^/editions*.)
{
  rewrite ^(.*)$ /editions$1 last;
}

location ~^/editions/(.*)$ {
  proxy_http_version 1.0;
  resolver 127.0.0.11;
  rewrite ^(.*)$ "https://hub.docker.com/editions/community/docker-ce-server-ubuntu" break; # hardcoded for test purposes
  proxy_pass http://<corporate proxy host>:<port>;
}
```

How must the configuration look so that I can reach the Internet via the corporate proxy?

Please let me know if you need further information. Thanks in advance.

**Comment by huguesBouvier** [comment]
proxy_pass is not a going through a proxy. 
It just mean sending the request directly to this address.
Try a simple "proxy pass" to google.com and curl your nginx, it will return a google page.

If I understand correctly, you want to route the request through a forward proxy. 
I am not sure nginx supports it: http://mailman.nginx.org/pipermail/nginx-devel/2013-March/003534.html
I tried before too and have not found a way to do it with nginx.

I have not tried it, but that  should be possible to do with an intermediate container.

**Comment by F-Joachim** [comment]
Thanks for your reply, @huguesBouvier. I will evaluate the configuration you've posted and get back to you as soon as possible.

**Comment by F-Joachim** [comment]
Hi @huguesBouvier. I followed the instructions you posted and it worked that a module running on the child edge node is able to curl an URL on hub.docker.com. But this was just the "Hello-World" example for me. The real use case I have (as I already [described](https://github.com/Azure/iotedge/issues/5870#issue-1065657854)) is to connect the MetricsCollector (running on the child edge node) via the parent edge to Log Analytics, among other modules (e.g. Azure Monitor Collector). Unfortunately this is currently not possible, because of the [hardcoded target URL](https://github.com/Azure/iotedge/blob/master/edge-util/src/Microsoft.Azure.Devices.Edge.Util/azureLogAnalytics/AzureLogAnalytics.cs#L52). I would create a separate issue for this.

In my opinion, the advantage of the nested edge feature is that security zones can be built so that requests are only routed through the edge device hierarchy and not bypassed.

Thanks again for your effort.

**Comment by huguesBouvier** [comment]
Indeed, the hardcoded url is an issue.
Nested feature was added April 2022, so modules older than that have not been designed with nested in mind.
I don't think there is a way around it, other than add route to IP tables...
Thanks for spotting the issue.
