### ISSUE TITLE
Cannot install moby-engine and aziot-edge on Raspberry Pi Stretch

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/iotedge#5882]
## Expected Behavior

When following the steps in this document:

https://docs.microsoft.com/azure/iot-edge/how-to-provision-single-device-linux-symmetric

to install on Raspberry Pi Stretch, the command:

```sh
sudo apt-get install moby-engine
```

should install Moby-engine, and:

```sh
sudo apt-get install aziot-edge
```

should install aziot-edge.

## Current Behavior

The Moby-engine package cannot be located:

```output
pi@edge-test:~ $ sudo apt install moby-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package moby-engine
```

Neither can aziot-edge:

```output
pi@edge-test:~ $ sudo apt-get install aziot-edge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package aziot-edge
```

## Steps to Reproduce

1. Set up Raspberry Pi using Stretch using the latest image from the [Raspbian downloads](https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/)
2. Work through the steps in [this how to guide](https://docs.microsoft.com/azure/iot-edge/how-to-provision-single-device-linux-symmetric) to install IoT Edge

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Raspberry Pi Stretch 2019-04-09
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: 

## Additional Information

It looks like the installed packages list is incorrect. When I cat /etc/apt/sources.list.d/microsoft-prod.list, I get this:

```output
deb [arch=amd64] https://packages.microsoft.com/debian/9/multiarch/prod stretch main
```

The `arch` field has amd64, but no arm entries. If I change this manually to `arch=amd64,armhf`, I can install moby-engine and aziot-edge.

**Comment by nyanzebra** [comment]
Hmm that is strange... you shouldn't have to manually add arm... let me try a fresh install on a pi and verify :)

**Comment by nyanzebra** [comment]
Can confirm this is a problem, just made a fresh os image of latest raspbian and went through steps in guide and see only amd64 in source list for microsoft...

**Comment by damonbarry** [comment]
@jimbobbennett For now, you can work around this problem using the olders steps that we used to have in the document you referenced:
```sh
# remove the previous repo config
sudo apt install packages-microsoft-prod
# workaround
curl https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list > ./microsoft-prod.list
sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
```

**Comment by damonbarry** [comment]
The doc page you referenced has since been reverted (see MicrosoftDocs/azure-docs#84643), so you should be able to install edge on Raspberry Pi OS by following the documented instructions.
