### ISSUE TITLE
Moby engine doesn't work with Raspberry Pi OS stretch and custom vision containers

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/iotedge#5883]
## Expected Behavior

When building a Custom Vision Docker Arm Raspberry Pi 3 container on a Raspberry Pi 3 running Stretch (a Tier 1 supported operating system for IoT Edge), the Docker build should work, and the container should be able to be run.

## Current Behavior

Run this command:

```sh
sudo docker build .
```

using a container exported from Custom Vision, and you get this output:

```output
Sending build context to Docker daemon  21.72MB
Step 1/9 : FROM python:3.7-slim
3.7-slim: Pulling from library/python
b6e5ca4da968: Pull complete 
66f8097783f7: Pull complete 
ed1b7dc0b58c: Pull complete 
de2827b1b2d4: Pull complete 
c12346225484: Pull complete 
Digest: sha256:7c669d3fc34a7b54a48028fbab955fc135fc0237b4666176709a147ab1b73ee0
Status: Downloaded newer image for python:3.7-slim
 ---> b4e1300134d3
Step 2/9 : RUN apt update && apt install -y libjpeg62-turbo libopenjp2-7 libtiff5 libatlas-base-dev libgl1-mesa-glx
 ---> Running in 1deadaa78a99

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Err:2 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Err:1 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
The command '/bin/sh -c apt update && apt install -y libjpeg62-turbo libopenjp2-7 libtiff5 libatlas-base-dev libgl1-mesa-glx' returned a non-zero code: 100
```

## Steps to Reproduce

1. Build a Custom Vision model on [customvision.ai](https://CustomVision.ai)
2. Export this model as a Docker container for ARM (Raspberry Pi 3)
3. Set up Raspberry Pi using Stretch using the latest image from the [Raspbian downloads](https://downloads.raspberrypi.org/raspbian/images/raspbian-2019-04-09/)
4. Work through the steps in [this how to guide](https://docs.microsoft.com/azure/iot-edge/how-to-provision-single-device-linux-symmetric) to install moby-engine and IoT Edge. You will also need to workaround #5882 by fixing the package list so you can install Moby-engine.
5. Download the Custom Vision model to the Pi, and build it using this following command from inside the unzipped folder with the docker image inside:

  ```sh
  sudo docker build .
  ```

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Raspberry Pi OS Stretch  2019-04-09
* Architecture [e.g. amd64, arm32, arm64]: arm32
* Container OS [e.g. Linux containers, Windows containers]: Linux

### Runtime Versions
* Docker/Moby [run `docker version`]:

```output
Client:
 Version:           3.0.13+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
 Built:             Thu May 28 20:41:25 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fda0c
  Built:            Mon Jun  1 20:22:16 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Additional Information

This change is described in:
* https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/
* https://github.com/debuerreotype/docker-debian-artifacts/issues/116

The fix for the Pi is to use a different version of libseccomp2, and a version of Docker greater than 19.0.4.

**Comment by jimbobbennett** [comment]
Note that you don't even need a custom vision container. Any container based off Python:3.7-slim gives the same error as soon as you run `apt update` inside the container. For example, you can reproduce this with the following Dockerfile:

```dockerfile
FROM python:3.7-slim

RUN apt update
```

**Comment by nyanzebra** [comment]
Can confirm this problem, I have also reached out to moby people to see if they are aware of this problem and if an update needs to happen on that side.

**Comment by nyanzebra** [comment]
It appears the stretch might be EOL for moby, I am trying to get some more info through an strace. 

From @cpuguy83 who works on Moby, "Recently newer versions of glibc have been problematic for these seccomp profiles because glibc is trying to use clone3 which is going to be denied by the profile since the profile doesn't know about clone3... since it is an outright denial (permission denied) glibc can't fallback to its old behavior and causes all kinds of issues.

It may be possible to fix the issue by adding a custom seccomp profile from the newer version (there is a flag on dockerd) or by disabling it completely."

^ if this solves the issue as a work around, then I will pin this response, but will dive deeper through an strace as mentioned to get more context.

**Comment by jimbobbennett** [comment]
If stretch is EOL for Moby, then are we going to move support to Buster/Bullseye?

Both still have the same problem though. The fix as I understand it is to use back ports of seccomp, and update the Moby-engine to a later version based off Docker 20. If we can get the updated Moby version, then maybe we just need a docs update to refer to the process to install the sec comp back ports (it should really be in docs rather than here so anyone who does the install will know the steps)

**Comment by cpuguy83** [comment]
There are up to date builds for buster and bullseye.
https://packages.microsoft.com/debian/10/prod/pool/main/m/moby-engine/

**Comment by kottoz** [comment]
I have the problem, i have downloaded the recent `bullseye debian; released 2021:10:30` Raspbian from official Raspberry Pi site,
Then i follow the following [tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal) to install IOT edge on Raspberry Pi 4.  #5928 this is my issue

**Comment by nyanzebra** [comment]
@jimbobbennett, did using bullseye or buster work for you in not encountering the seccomp issue?

**Comment by jimbobbennett** [comment]
Sorry @nyanzebra - was OOF for a long Christmas break.

When I tested them on Dec 9th they both had the same issue. If there has been a Moby release since then, I can retest.

**Comment by nyanzebra** [comment]
@jimbobbennett, from what I understand from speaking with @damonbarry those flavours (buster/bullseye) should work... Are you doing the same test (alpine docker file) as above on updated images? Just want to understand what you did to see the same issue :)

**Comment by jimbobbennett** [comment]
@nyanzebra - do you want me to test with the instructions in docs (so use the stretch version on buster/bullseye), or using the latest release @cpuguy83 mentions?

**Comment by nyanzebra** [comment]
@jimbobbennett use latest release, I think stretch on buster/bullseye might have same problem but newest release should work. Let me know if you encounter any issues :)

**Comment by jimbobbennett** [comment]
## Results part 2 - Buster ❌

* Installed buster lite (Raspberry Pi OS Lite (legacy)) from the Raspberry Pi imager.
* From the [MS prod packages](https://packages.microsoft.com/debian/10/prod/pool/main/m/), I downloaded:
  * `moby-engine_20.10.9+azure-1_armhf.deb`
  * `moby-containerd_1.5.9+azure-2_armhf.deb`
  * `moby-runc_1.0.3+azure-1_armhf.deb`
  * `moby-cli_20.10.9+azure-1_armhf.deb`

  These were based of trying to install moby-engine and getting a list of dependencies.

* Installed `apparmor` and `iptables` as these are recommended dependencies
* Installed `moby-runc_1.0.3+azure-1_armhf.deb`
* Installed `moby-containerd_1.5.9+azure-2_armhf.deb`
* Installed `moby-cli_20.10.9+azure-1_armhf.deb`
* Installed `moby-engine_20.10.9+azure-1_armhf.deb`
* Created the following dockerfile (this one fails on stretch):

  ```dockerfile
  FROM python:3.7-slim

  RUN apt update
  ```
  
  This failed:
  
  ```output
  Sending build context to Docker daemon  2.048kB
  Step 1/2 : FROM python:3.7-slim
  3.7-slim: Pulling from library/python
  d0061d6703dc: Pull complete 
  b06134f643dd: Pull complete 
  53ed2a177e6c: Pull complete 
  fef57bd1227c: Pull complete 
  aa00916dbb34: Pull complete 
  Digest: sha256:f7f072342e7c29b0fb035057368dfdce5221550c48aa5421bafed0ad1da5a435
  Status: Downloaded newer image for python:3.7-slim
   ---> 4d6dece9bedf
  Step 2/2 : RUN apt update
   ---> Running in 19364f360385

  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

  Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
  Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
  Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
  Err:1 http://security.debian.org/debian-security bullseye-security InRelease
    At least one invalid signature was encountered.
  Err:2 http://deb.debian.org/debian bullseye InRelease
    At least one invalid signature was encountered.
  Err:3 http://deb.debian.org/debian bullseye-updates InRelease
    At least one invalid signature was encountered.
  Reading package lists...
  W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
  E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
  W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
  E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
  W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
  E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
  The command '/bin/sh -c apt update' returned a non-zero code: 100
  ```
  
  I then repeated with a custom vision container, and this also fails with the same error.

**Comment by jimbobbennett** [comment]
So based off the above - using the Debian 10 packages (so Buster packages), Buster doesn't work but Bullseye does.

Should we then drop support for Stretch and Buster, and just support Bullseye, updating the docs to match?

**Comment by cpuguy83** [comment]
In order to run a bullseye container on a buster host, you'll need to use an updated libseccomp2 package, which can be installed from the backports repo.

**Comment by cpuguy83** [comment]
Actually, that may not even work. Let me try some things.

**Comment by micahl** [comment]
@jimbobbennett we are planning to move to Buster / Bullseye and our guidance will be to match the container with the host.  In your Buster example above I'd expect it to work if you the Buster image `python:3.7-slim-buster` was used instead of the one based on Bullseye `python:3.7-slim`.

**Comment by jimbobbennett** [comment]
Thanks @micahl. How long till these containers are ready?

**Comment by micahl** [comment]
@jimbobbennett Um, [not very long](https://github.com/Azure/iotedge/pull/6225)...

**Comment by jimbobbennett** [comment]
![An animated Gif of Carlton from fresh prince of bel air dancing](https://media1.giphy.com/media/kHmVOy84g8G6my09fu/giphy.gif?cid=ecf05e47zbmrrm1rdhmnmgpupacdmvkcd5n98y1vwe1306e7&rid=giphy.gif&ct=g)

**Comment by micahl** [comment]
@jimbobbennett the latest [v1.2.9 released today](https://github.com/Azure/azure-iotedge/releases/tag/1.2.9) and also brought with it installable packages for Debian 10 and 11 that we've published to packages.microsoft.com [here ](https://packages.microsoft.com/debian/10/prod/pool/main/a/aziot-edge/) and [here](https://packages.microsoft.com/debian/11/prod/pool/main/a/aziot-edge/).

**Comment by jimbobbennett** [comment]
Just tested this out with a bullseye install and using the 1.2.9 version.

If I use this to build a Dockerfile based off `python:3.7-slim`, when the build runs `apt update`, I get this error:

```sh
cgroups: cgroup mountpoint does not exist: unknown
```


Output:

```sh
pi@raspberrypi:~/container $ sudo docker build .
Sending build context to Docker daemon  9.706MB
Step 1/9 : FROM python:3.7-slim
3.7-slim: Pulling from library/python
f98812e1a494: Pull complete 
c42e1e4a0443: Pull complete 
82f3a6cad3e8: Pull complete 
6b2e429aea54: Pull complete 
8c6309713130: Pull complete 
Digest: sha256:675065b89ddf179449bfbd71fdd9c7a7ea91ec2613382f44e8d1131851931bb6
Status: Downloaded newer image for python:3.7-slim
 ---> eaeaa76778da
Step 2/9 : RUN apt update && apt install -y libjpeg62-turbo libopenjp2-7 libtiff5 libatlas-base-dev libgl1-mesa-glx
 ---> Running in 4ef184e2e1d6
cgroups: cgroup mountpoint does not exist: unknown
```

I've also tried `3.7-slim-buster`, `3.10-slim-bullseye`, all the same problem.


I also tried docker hello world, same error.

```sh
pi@raspberrypi:~/container $ sudo docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
9b157615502d: Pull complete 
Digest: sha256:bfea6278a0a267fad2634554f4f0c6f31981eea41c553fdf5a83e95a41d40c38
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
ERRO[0003] error waiting for container: context canceled 
```

**Comment by veyalla** [comment]
Can try this: https://github.com/Azure/iotedge/issues/5812#issuecomment-965573485

**Comment by jimbobbennett** [comment]
If I do that then the group error goes away - but I'm back at the original error.

```sh
pi@raspberrypi:~/container $ sudo docker build .
Sending build context to Docker daemon  9.706MB
Step 1/2 : FROM python:3.7-slim
 ---> eaeaa76778da
Step 2/2 : RUN apt update
 ---> Running in 1e7176dc6e0d

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Err:2 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
The command '/bin/sh -c apt update' returned a non-zero code: 100
```

**Comment by veyalla** [comment]
Can you share the Dockerfile you're trying to build? You can also provide the output of `uname -a` and `docker version` from your Raspberry Pi?

**Comment by jimbobbennett** [comment]
```sh
pi@raspberrypi:~/container $ cat Dockerfile 
FROM python:3.7-slim

RUN apt update
```

```sh
pi@raspberrypi:~/container $ uname -a
Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
```

```sh
pi@raspberrypi:~/container $ sudo docker version
Client:
 Version:           3.0.13+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
 Built:             Thu May 28 20:41:25 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fda0c
  Built:            Mon Jun  1 20:22:16 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by cpuguy83** [comment]
You have to upgrade to a newer version of moby for it to work.

**Comment by veyalla** [comment]
Looks like you running an older version of Moby-engine. Our docs haven't been updated yet to use the new Debian 11 packages on a Raspberry Pi.

Regardless, is there a reason to build the image on the target platform? With newer versions of Docker Desktop, you can use the `buildx` to build and push the ARM32 images on your dev box. With your `Dockerfile`  in current directory, you can run:

`docker buildx build --platform linux/arm/v7 -t testarm32 .`

More details: https://collabnix.com/building-arm-based-docker-images-on-docker-desktop-made-possible-using-buildx/

**Comment by jimbobbennett** [comment]
@veyalla - ok, let me try agin when the docs are updated. I'm trying to ensure the experience is as easy as possible for everyone as custom vision is a popular demo for IoT edge and Pi, so having it working on the Pi would be an easier step for folks than having to build on one device then deploy the built container to another.

**Comment by micahl** [comment]
@jimbobbennett we're working on doc updates.  They will say to do the following which should already work for 1.2.9.  Can you give these a try to let me know the result?

```base
curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
sudo apt install ./packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install moby-engine
sudo apt-get install aziot-edge defender-iot-micro-agent-edge
```

**Comment by jimbobbennett** [comment]
> @jimbobbennett we're working on doc updates. They will say to do the following which should already work for 1.2.9. Can you give these a try to let me know the result?

Clean install of bullseye lite, ran an `apt update` and `apt full-upgrade`.

Ran the instructions above, rebooted the Pi, and I can build the Docker container successfully! I'll try running it through IoT Edge tomorrow as it's later here now.

**Comment by jimbobbennett** [comment]
@micahl - All good! I can build the custom vision container on Bullseye, push it to an Azure Container Registry, then deploy it using IoT Edge and classify an image.

Do you want me to close this now, or wait till the docs are updated?

**Comment by micahl** [comment]
Thanks, @jimbobbennett!  Closing this one.  We'll update the docs shortly.
