### ISSUE TITLE
Return Code 32 (key usage does not include certificate signing) when testing gateway connection

### ISSUE THREAD

**Issue by scout208** [Azure/iotedge#5890]
## Expected Behavior

I setup up a gateway connection by following the [tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway?view=iotedge-2018-06) using the [self-signed demo certificates](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2018-06#prerequisites). Everything was working up until I tried [testing the connection](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device?view=iotedge-2018-06#test-the-gateway-connection) and expected it to return 0 (ok).

## Current Behavior

Instead of returning 0 (ok) it is returning 32 (key usage does not include certificate signing).

## Steps to Reproduce

1. Follow the [tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway?view=iotedge-2018-06) to setup an edge device acting as a gateway.
2. Setup a downstream device following the [tutorial](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-authenticate-downstream-device?view=iotedge-2018-06).
3. Test the gateway connection using `openssl s_client -connect mygateway.contoso.com:8883 -CAfile <CERTDIR>/certs/azure-iot-test-only.root.ca.cert.pem -showcerts`

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
‼ host time is close to real time - Warning
    Time on the device is out of sync with the NTP server. This may cause problems connecting to IoT Hub.
    Please ensure time on device is accurate, for example by installing an NTP daemon.
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: identity certificates expiry - OK
‼ production readiness: certificates - Warning
    The device CA cert will expire within the next 90 days, at 2022-01-02 15:12:39 UTC. Renew the certificate before this date to retain functionality.
    See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

20 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Windows 10 IoT Ent 2021 LTSC
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.8
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* Docker/Moby [run `docker version`]: 19.03.15+azure

## Additional Information

I'm not sure what code 32 or the message means exactly. I can't tell if I'm doing something wrong.

**Comment by huguesBouvier** [comment]
Can you give me print here the config that you have put for the certificate in the config.toml?
Chance either: You didn't use the full chain or you didn't generate the device-ca but instead the simple device.

**Comment by scout208** [comment]
Yes, here's the certificate settings.

````
certificates:
  device_ca_cert: "file:///home/iotedge-user/certs/azure-iot-edge-device-identity-mycacert-full-chain.cert.pem"
  device_ca_pk: "file:///home/iotedge-user/private/iot-edge-device-identity-mycacert.key.pem"
  trusted_ca_certs: "file:///home/iotedge-user/certs/azure-iot-test-only.root.ca.cert.pem"
  auto_generated_ca_lifetime_days: 90
````

**Comment by huguesBouvier** [comment]
Those are the wrong certificates. You have used: ./certGen.sh create_edge_device_identity_certificate "<name>"
This only generate identity certificates. Those are for clients not servers.
Instead you should use: ./certGen.sh create_edge_device_ca_certificate "<CA cert name>".

**Comment by scout208** [comment]
Thank you. I must have accidentally used the wrong command when I was creating the certificates.
