### ISSUE TITLE
Custom module causing edgeHub to leak memory

### ISSUE THREAD

**Issue by bkarrlander** [Azure/iotedge#5892]
Hi,

It seems like calls to our custom HTTP module is causing Microsoft.Azure.Devices.Edge.Hub.Service.dll to indefinitely increase its memory usage and to frenetically log the same output, about 500 lines per second (see log details below). 

We have limited the log size so that is not a problem but the memory consumption eventually renders the device unusable.

Our module seems to cause a MultipleConnectionsException but we are not sure why this is. We only have one device using the same identifier (as was not the case in this issue: https://github.com/Azure/iotedge/issues/5854)

Restarting iotedge solves the problem only temporarily.

### Detailed information

 - Windows Host: Windows 10 
 - Edition: Professional
 - Version: build 19042
 - EFLOW version: 2110.03111 (we can't use the latest LTS because it doesn't let us set static IP).
- iotedge version: 1.1.5

We have an EFLOW solution with a custom module (a dotnet webapp) that receives HTTP requests and forwards them to IoT Hub. The module receives about one HTTP request per minute.

After some investigating we found out that it was the custom module causing edgeHub to behave like this. As soon as the module starts receiving calls we can immediately see that edgeHub increases its memory usage and starts logging the output. 

The log output repeated by edgeHub looks like this:

```
<6> 2021-12-04 18:48:14.906 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-04 18:48:14.907 +00:00 [INF] - Client MST086F/CameraEventHandlerModule in device scope authenticated locally.
<6> 2021-12-04 18:48:14.908 +00:00 [INF] - New device connection for device MST086F/CameraEventHandlerModule
<6> 2021-12-04 18:48:14.908 +00:00 [INF] - Closing AMQP device proxy for MST086F/CameraEventHandlerModule because no handler was registered.
Microsoft.Azure.Devices.Edge.Hub.Core.MultipleConnectionsException: Multiple connections detected for device MST086F/CameraEventHandlerModule
<6> 2021-12-04 18:48:14.908 +00:00 [INF] - Closing link Events for MST086F/CameraEventHandlerModule
<6> 2021-12-04 18:48:14.909 +00:00 [INF] - Initialized device listener in the AMQP protocol head for MST086F/CameraEventHandlerModule
<6> 2021-12-04 18:48:14.909 +00:00 [INF] - Opened link Events for MST086F/CameraEventHandlerModule
<6> 2021-12-04 18:48:14.910 +00:00 [INF] - Client MST086F/CameraEventHandlerModule connected to edgeHub, processing existing subscriptions.
<6> 2021-12-04 18:48:14.910 +00:00 [INF] - Bind device proxy for device MST086F/CameraEventHandlerModule
```

So we have two problems, really: the memory leak and why we get that MultipleConnectionsException although we only have one device.

Please let us know what more information we can provide you with.

Best regards,
Björn

**Comment by bkarrlander** [comment]
I have just been able to reproduce the edgeHub behavior locally with IotEdge version 1.1.8.

**Comment by bkarrlander** [comment]
Interesting note: The reported behavior does **not** occur after the very first http request to our custom module. It's after the **second** request that the problems starts. That's when we get the MultipleConnectionsException and the excessive logging and memory leak. 

Here is the edgeHub log after iotedge restart, with inlined comments for when http calls were made: [edgeHub-logs-after-restart.txt](https://github.com/Azure/iotedge/files/7656991/edgeHub-logs-after-restart.txt)

Kind regards,
Björn

**Comment by nyanzebra** [comment]
This seems similar to #5854 (minus the # of devices) and does make it seem there is a memory leak issue with how connections are being handled. Let me see what I can find out from our side. Would you mind also providing an `iotedge check`?

**Comment by bkarrlander** [comment]
@nyanzebra, the problem was solved by improving the custom code. The ModuleClient was instantiated at every request and that's likely why the second request caused the MultipleConnectionsException. Now, instead the client is instantiated once at program startup and this plays much better with EdgeHub.

Probably this shouldn't cause EdgeHub to leak memory that way but at least we can code our module right! :)

Let me know if you still want more information.

Thanks for your help
Björn

**Comment by nyanzebra** [comment]
Hi, @bkarrlander, yes, if you could still provide the result of `iotedge check` that would be appreciated :) as it still sounds like we have a problem in EdgeHub that should be fixed. Or maybe two problems, in that maybe we can have better error messages to help identify this kind of issue sooner :)

**Comment by bkarrlander** [comment]
@nyanzebra, here's the output from iotedge check:

```
iotedge-user@MST086F-EFLOW [ ~ ]$ sudo iotedge check --verbose
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.1.5 but 1.1.8 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 9124 days (at 2046-11-28 13:55:07 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

19 check(s) succeeded.
5 check(s) raised warnings.
```

Regards,
Björn

**Comment by wenbya** [comment]
is there any progress ?

**Comment by nyanzebra** [comment]
Hello @wenbya and @bkarrlander; sorry for the delay, but this got put on the backburner for me... I had tried to reproduce the situation, but couldn't... If it is possible could the following be provided to help us investigate and see where the problem lies?

1. Enable Debug logs to capture everything when problem occurs
2. Enable metrics and go through the Metrics collector to get data on what the system is doing [Metrics](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-monitor-with-workbooks?view=iotedge-2020-11#:~:text=The%20IoT%20Edge%20agent%20reports%20on%20the%20state,of%20CPU%20being%20used%20on%20the%20device.%20)
3. Provide detailed instructions on what was done to see this problem
4. If possible, can a minimally viable replication be made? With just a simple client to help us see what all is sent for replication from client side.

@varunpuranik, @vipeller is there anything else we can ask or do to make sure we can adequately debug this problem?

**Comment by bkarrlander** [comment]
@nyanzebra, we are currently far from the situation we were in at the time of this issue was filed so I can't help with logs or to reproduce this any longer. But we know that the memory usage went increasingly higher when the ModuleClient connection wasn't reused. Reusing the connection solved the problem for us.

**Comment by bkarrlander** [comment]
Reusing the connection solved the problem for us, as mentioned above.

**Comment by garethpotter** [comment]
This is still a problem in 1.4 and sharing the `ModuleClient` instance between the two classes where we were using it solved the issue. If it's not going to be fixed, it should probably be made very very clear that this is not something that should be done, almost to the point of throwing an exception when a second call to, e.g. `CreateFromEnvironmentAsync` is made in same process.
