### ISSUE TITLE
UpdateReportedPropertiesAsync not updating twin in cloud after TimeoutException

### ISSUE THREAD

**Issue by AdamMachera** [Azure/iotedge#590]
Updating device twin in loop every 500 ms over gateway reaches a throttling limit and in edgeHub TimeoutException is presented. Restarting edgeHub doesn't solve issue. No exception is presented for leaf node. Nothing is logged inside edgeHub logs except the first timeoutexception.
I had to remove iotedge and install it again to make it working.

## Expected Behavior

After throttling limit is rechead gateway should inform client or aggregate changes and send them later.
## Current Behavior

Currently after this exception surface:
2018-11-30 14:14:07.972 +00:00 [INF] - Updating reported properties for minint-k9f9qt1 in cloud failed with error System.TimeoutException Operation timeout expired.
nothing is sent to cloud. Leaf node doesn't get any exception so it can think everything was successful.

## Steps to Reproduce

Run below code and in connection string use GatewayHostName to ensure that traffic goes over iotedge:

var transport = ConfigurationManager.AppSettings["TransportType"];
            var tt = (TransportType)Enum.Parse(typeof(TransportType), transport);
            ITransportSettings settings = null;
            if (tt == TransportType.Mqtt)
            {
                settings = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only)
                {
                    RemoteCertificateValidationCallback = (sender, certificate, chain, errors) => true
                };
            }
            else
            {
                settings = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only)
                {
                    RemoteCertificateValidationCallback = (sender, certificate, chain, errors) => true
                };
            }

            Console.WriteLine($"Using transport type {tt}");

            var connectionString = ConfigurationManager.AppSettings["IotHubConnectionString"];
            var client = DeviceClient.CreateFromConnectionString(connectionString, new[] { settings });

            for (int i = 0; i < 1000; i++)
            {
                var twinValue = DateTime.UtcNow.ToString("HHmmss");

                var twinCollection = new TwinCollection
                {
                    ["adam:ConfigurationVersion"] = $"1_0_0-{twinValue}-{tt}",
                    ["adam:Version"] = $"1_0_0-{twinValue}",
                    ["adam:WasRolledBack"] = $"false-{twinValue}"
                };

                try
                {
                    client.UpdateReportedPropertiesAsync(twinCollection).Wait();
                    Console.WriteLine($"Twin was updated: {twinCollection.ToJson()}");
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }

                Thread.Sleep(500);
            }

            Console.WriteLine("Press any key to exit...");
            Console.ReadLine();

### Device (Host) Operating System

Ubuntu 18.01
### Architecture

Amd64
### Container Operating System

Linux
#### iotedged

iotedge 1.0.4
#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0.4
#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0.4
#### Docker

Client:
 Version:           3.0.1
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        021bf39d
 Built:             Tue Oct 16 21:05:20 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.1
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       09f5e9d
  Built:            Tue Oct 16 20:55:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by varunpuranik** [comment]
Hi @AdamMachera - 

Thanks for the issue. I will look into the edgeHub behavior to see why the reported properties are not getting synced on subsequent attempts. 

Meanwhile, a couple of questions -
- What is your scenario that requires twin to be updated once every 500ms? That is not the expected usage pattern for twins (we expect it to happen much slower), and typically telemetry is best suited for such high volume updates. 
- Did the device have any connectivity issues? On throttling, the SDK should throw a throttled exception, not a timeout. If the device was always connected, I believe multiple calls might be overlapping each other. 
I believe you are updating reported properties at a fixed interval of 500ms, without waiting for the previous UpdateReportedProperties call to succeed/fail, right?

**Comment by AdamMachera** [comment]
We have 10 addins that can start asynchronously and we are not currently controlling when they are updating its state over reported properties. This interaction with UpdateReportedPropertiesAsync() is done only once per each addin. We are not getting on leaf node none information that it was unsuccessful. All time we are getting information that this method was invoked without none problems but device twin is not updated.
We haven't experience any connectivity issues.
The problem is that sdk is not throwing throttled exceptions.
If I run without gateway sdk by itself handles throttling issue. It just takes longer to execute UpdateReportedPropertiesAsync.

Regarding the question if in demo application I'm waiting for success/fail - we are actually waiting
client.UpdateReportedPropertiesAsync(twinCollection).Wait();
Task is being waited.

**Comment by lt72** [comment]
@AdamMachera Closing as it seems stale. We apologize for the lack of a prompt answer. Please re-open if you still need help.
