### ISSUE TITLE
Target Condition on Deployment Manifest seems to be required in IoT Edge 1.2

### ISSUE THREAD

**Issue by fgheysels** [Azure/iotedge#5903]
I have setup IoT Edge 1.2 on a Linux VM and created a device identity in IoT Hub.
Afterwards, I've created a simple deployment manifest, and uploaded that deployment manifest using Azure CLI, like this:

```
az iot edge deployment create -d device1 -n iothubname --content deployment.json
```

After a while, I've realized that the Iot Edge device was not applying the deployment manifest.   When I looked at the deployment manifests in IoT Hub, I could also see that this manifest was targetting no devices.
When I specified a Target Condition on the manifest, I could make it so that a device was targetted.   

I think this behavior is a bit strange, as it is -afaik- nowhere documented:

[Target Condition documentation](https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring?view=iotedge-2020-11#target-condition)

The `--target-condition` argument of the CLI command `az iot edge deployment create` is also optional, which would also assume that all devices can be targetted without specifiying this target condition: https://docs.microsoft.com/en-us/cli/azure/iot/edge/deployment?view=azure-cli-latest#az_iot_edge_deployment_create

## Expected Behavior
When a deployment manifest has no target condition, all devices should be targetted.

## Current Behavior
No devices are targetted when a deployment manifest has no target condition.

**Comment by fgheysels** [comment]
If the current behavior is the expected behavior, I think it would be good to mention this in the documentation.

**Comment by nyanzebra** [comment]
Trying to reach out to who knows about how the cli tool works and whether this needs to be fixed or documented better. Thank you for your patience, will update once I know

**Comment by nyanzebra** [comment]
Documentation should be getting updated, once it is, I will post a link and then we can confirm if it is clear :)

**Comment by nyanzebra** [comment]
The link here: https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring should be updated shortly and convey that target-condition absent does not apply to all devices and that is required parameter in some cases.
