### ISSUE TITLE
API proxy update via module twin not possible due to a size limitation of 4096 bytes

### ISSUE THREAD

**Issue by F-Joachim** [Azure/iotedge#5921]
I've tried to update the API proxy configuration via module twin as described [here](https://github.com/Azure/iotedge/tree/master/edge-modules/api-proxy-module#update-the-proxy-configuration-dynamically).

For test purposes I used the base64 encoded [default template ](https://github.com/Azure/iotedge/blob/023c919d49f9de0feabf539ab7326f7cdcf7ccc9/edge-modules/api-proxy-module/templates/nginx_default_config.conf)

The following error is thrown when I try to deploy via the Azure Portal or the Azure CLI.

```bash
{'Message': 'ErrorCode:ArgumentInvalid;Property or Tag value should be maximum 4096 bytes. Error in Property/Tag <base64 encoded default template>', 'ExceptionMessage': 'Tracking ID: <tracking-id>'}
```

If you need further information, don't hesitate to contact me.

**Comment by nyanzebra** [comment]
@huguesBouvier any ideas on why this might happen?

**Comment by huguesBouvier** [comment]
Yes, F-Joachim is right there is a size limitation. 
There are 3 ways around it:
- The default config is huge because it is parameterizable. A custom config _usually_ don't need so much and can be made smaller.
- The config can be on the host and mounted around it
- Rebuild API proxy with the custom config inside

**Comment by nyanzebra** [comment]
@F-Joachim did the recommendations from @huguesBouvier help?

**Comment by jlian** [comment]
@F-Joachim this is a known issue and @huguesBouvier's recommendation is all we can provide right now. If you continue to have problems, please reopen the issue. Thanks!
