### ISSUE TITLE
Does Azure IoT Edge runtime and modules support host network mode?

### ISSUE THREAD

**Issue by allenzt** [Azure/iotedge#5935]
Hello everyone! could you help to figure out whether  Azure IoT Edge runtime and modules support **host** network mode? 
I tried the following methods, but it didn't work.

https://docs.microsoft.com/en-us/answers/questions/75596/iot-edge-module-add-hostconfig-for-networkmodehost.html

**Comment by veyalla** [comment]
Try the following createOptions for each module that needs to be on the host network namespace:

```
   "createOptions": {
                "NetworkingConfig": {
                    "EndpointsConfig": {
                         "host": {}
                    }
                },
                "HostConfig": {
                    "NetworkMode": "host"
                }
            }
```

**Comment by allenzt** [comment]
@veyalla Thanks! I have tried this configuration, but it still has no effect. Is there any debugging or checking method?
My deployment configuration is as follows:
```json
{
    "modulesContent": {
        "$edgeAgent": {
            "properties.desired": {
                "modules": {
                    "temp": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.1.3-linux-arm32v7",
                            "createOptions": "{\"createOptions\":{\"NetworkingConfig\":{\"EndpointsConfig\":{\"host\":{}}},\"HostConfig\":{\"NetworkMode\":\"host\",\"Memory\":67108864,\"CpuPeriod\":50000}}}"
                        },
                        "type": "docker",
                        "version": "1.0",
                        "env": {
                            "MessageCount": {
                                "value": "-1"
                            }
                        },
                        "status": "running",
                        "restartPolicy": "always"
                    }
                },
                "runtime": {
                    "settings": {
                        "minDockerVersion": "v1.25"
                    },
                    "type": "docker"
                },
                "schemaVersion": "1.0",
                "systemModules": {
                    "edgeAgent": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-agent:1.1.3-linux-arm32v7",
                            "createOptions": "{\"createOptions\":{\"HostConfig\":{\"Memory\":67108864,\"CpuPeriod\":50000}}}"
                        },
                        "type": "docker"
                    },
                    "edgeHub": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.1.3-linux-arm32v7",
                            "createOptions": "{\"createOptions\":{\"HostConfig\":{\"Memory\":134217728,\"CpuPeriod\":50000,\"PortBindings\":{\"443/tcp\":[{\"HostPort\":\"8443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}]}}}}"
                        },
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always"
                    }
                }
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "routes": {
                    "route": "FROM /messages/* INTO $upstream"
                },
                "schemaVersion": "1.0",
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        },
        "temp": {
            "properties.desired": {}
        }
    }
}
```

**Comment by veyalla** [comment]
> I have tried this configuration, but it still has no effect.

Can you clarify what effect you're hoping to see?

Please also share the output of `docker inspect temp` and `docker inspect edgeHub`. Be sure to redact any sensitive info before sharing the output.

**Comment by allenzt** [comment]
@veyalla Sorry for my late reply! 
> Can you clarify what effect you're hoping to see?

I want to set network mode of temp module to host, so program has the ability to directly access the CAN interface in the container. After applying the configuration I said in the previous reply, network mode of temp module is still bridge.

Output of `docker inspect edgeHub`
[edgeHub_inspect.log](https://github.com/Azure/iotedge/files/7743424/edgeHub_inspect.log)

Output of `docker inspect temp`
[temp_inspect.log](https://github.com/Azure/iotedge/files/7743426/temp_inspect.log)

**Comment by allenzt** [comment]
@veyalla do you have any update or suggestion?

**Comment by veyalla** [comment]
The changes don't seem have applied on the device? I don't see the CPU or Memory limit applied either.

Can you confirm the deployment is applied to the correct device AND there is no other [at-scale deployment](https://docs.microsoft.com/azure/iot-edge/how-to-deploy-at-scale?view=iotedge-2020-11) targeting the device? 

Any other ideas, @darobs?

**Comment by allenzt** [comment]
@veyalla Could you give me some suggestion about deployment debug ? I deploy again, but it didn't take effect

**Comment by darobs** [comment]
Hi @allenzt 

Seems like you have an additional problem where the deployment isn't getting updated.

Venkat's suggestion to make sure you don't have a competing at-scale deployment is a good suggestion. If that's not the case:

First off, check in the portal to see if the edge device is reporting a status back to you. If there's an error there, that will give you a good indicator what's wrong.

 Could you run `sudo iotedege check` and show us the report?

**Comment by allenzt** [comment]
@darobs Thanks a lot ! but we don't have any deployment and runtime response is 200(ok).
![image](https://user-images.githubusercontent.com/36235312/148483483-77948c57-0fd1-4e45-bbdc-e39a48969ad8.png)



![image](https://user-images.githubusercontent.com/36235312/148483603-6d82a9b7-3780-49f4-a93e-61ad1a9c716e.png)

`iotedge check` result is as below:
![image](https://user-images.githubusercontent.com/36235312/148483742-a5f66555-9034-4819-965d-02529e432ba6.png)

**Comment by darobs** [comment]
Well, there's an interesting error in the check: the certificate verification failed.  It shouldn't - it looks like quickstart had created new certificates 2 days previous to the check, and they're good for 90 days - you can see in the warning that it had 88 days left. This is rather unusual.

Is there a reason why you're using 1.1.3?

**Comment by allenzt** [comment]
> Well, there's an interesting error in the check: the certificate verification failed. It shouldn't - it looks like quickstart had created new certificates 2 days previous to the check, and they're good for 90 days - you can see in the warning that it had 88 days left. This is rather unusual.

We use Connection String to connect IoT hub. Is there anything wrong with this? Or do we have to use a certificate to connect IoT hub.

> Is there a reason why you're using 1.1.3?

Since we deployed the Azure IoT Edge runtime on the device a long time ago, we have been using the 1.1 branch architecture. In June 2021, we updated to the latest version that supports the 1.1 branch architecture, the latest version at that time was 1.1.3

Is there any way to check whether `deployment.json` has been successfully applied on Azure portal or IoT edge device?
![image](https://user-images.githubusercontent.com/36235312/150739689-39bd44e1-fe7c-4e80-ba7a-bb350dca0099.png)

**Comment by allenzt** [comment]
@darobs Hi darobs, I use the following cli commands, port mapping, cpu and memory limits are all in effect.
```sh
docker run -it -p 8443:443 -p 5671:5671 -p 8883:8883 --restart=always --cpu-period 50000 --m 67108864 --name edgeHub mcr.microsoft.com/azureiotedge-agent:1.1
```

**Comment by allenzt** [comment]
@darobs @jlian @pmzara Do you have any update? This issue is very common to anyone who wants to access CAN or Bluetooth in an Azure IoT edge environment

**Comment by allenzt** [comment]
![image](https://user-images.githubusercontent.com/36235312/152954056-dbd46e8f-e242-4490-88d6-9b6bfc93ad2d.png)
Using wrong settings as above described, close it. Many thanks for your support!
