### ISSUE TITLE
Misleading naming used in documentation and code about certain certificates

### ISSUE THREAD

**Issue by vjrantal** [Azure/iotedge#5937]
## Expected Behavior

It would be good if documentation and code is aligned on the terminology used to describe various types of certificates.

## Current Behavior

In [here](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs?view=iotedge-2020-11#changes-in-version-12), it is said that `workload CA certificate was deprecated`.

When using IoT Edge with default settings, the common name of the certificate that the Edge Hub use is `iotedged workload ca` (coming from [this line]( https://github.com/Azure/iotedge/blob/070610dbc54ec9078e149dcd8457e4c5a54b2280/edgelet/edgelet-http-workload/src/module/cert/mod.rs#L250)). The naming sounds misaligned with the deprecation note in the documentation.

**Comment by arsing** [comment]
Yeah, I'd noticed that when the code had originally been merged but we kept putting off fixing it.
