### ISSUE TITLE
SQL Edge on IoT Edge - Reinstallation Issues

### ISSUE THREAD

**Issue by andresu13** [Azure/iotedge#5938]
## Expected Behavior
If I reinstall SQL Edge module on IoT Edge with a new password, it should be able to take that new password for that new installation.

## Current Behavior
Not sure if this was done by design or not, but if SQL Edge module is deployed to an Azure IoT Edge and then re-installed (with a new password), the new password to connect to SQL inside the container does not work - you still have to use the old password (from the previous installation).

I found out that the reason why this happens is because when the SQLEdge module gets removed, it does not delete the Docker volume "sqlvolume" located in the following host path:

/var/lib/docker/volumes/sqlvolume

The password information seem to be stored somewhere inside that volume and, therefore, when SQLEdge gets re-installed, it re-uses that volume and therefore the previously stored password instead of the new password passed through an environment variable.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install SQLEdge Module in IoT Edge specifying a password using an environment variable
2. Connect to the SQLEdge container and authenticate to SQL using the password you configured - this should work!
2. Remove the SQLEdge Module
3. Re-Install the SQLEdge Module again with a different password in the environment variable
4.  Connect to SQLEdge container and authenticate to SQL using the new password - this will fail!
5.  Try to authenticate to SQL using the old password - this should work!

### Device Information
* Host OS: Ubuntu 18.04
* Architecture: AMD64
* Container OS: Linux Containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* Docker/Moby [run `docker version`]: Docker 20.10.11

**Comment by veyalla** [comment]
This repository does not track SQL Edge module issues. Please open an [Azure support ticket ](https://azure.microsoft.com/en-us/support/create-ticket/)and choose SQL service from the support topic tree.
