### ISSUE TITLE
IoT Edge - Status: stopped

### ISSUE THREAD

**Issue by Eriq9** [Azure/iotedge#5942]
Hello, 

I want to run IoTEdge on Raspberry Pi 4. After installing everything I've got the following results:

1. sudo iotedge check --verbose

> √ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
√ latest security daemon - OK
√ host time is close to real time - OK
× container time is close to host time - Error
    Could not query local time inside container
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2022-03-18 18:40:29 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file /etc/docker/daemon.json
        caused by: No such file or directory (os error 2)
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
× container on the default network can connect to IoT Hub AMQP port - Error
    Container on the default network could not connect to ioticonics.azure-devices.net:5671
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
× container on the default network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the default network could not connect to ioticonics.azure-devices.net:443
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
× container on the default network can connect to IoT Hub MQTT port - Error
    Container on the default network could not connect to ioticonics.azure-devices.net:8883
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
× container on the IoT Edge module network can connect to IoT Hub AMQP port - Error
    Container on the azure-iot-edge network could not connect to ioticonics.azure-devices.net:5671
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
× container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to ioticonics.azure-devices.net:443
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
× container on the IoT Edge module network can connect to IoT Hub MQTT port - Error
    Container on the azure-iot-edge network could not connect to ioticonics.azure-devices.net:8883
        caused by: docker returned exit code: 125, stderr = docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.

10 check(s) succeeded.
4 check(s) raised warnings.
9 check(s) raised errors.

2. sudo iotedge list 

NAME             STATUS           DESCRIPTION      CONFIG
edgeAgent        stopped          Stopped          mcr.microsoft.com/azureiotedge-agent:1.1

3. sudo journalctl -u iotedge

Dec 18 19:40:42 raspberrypi iotedged[2964]: 2021-12-18T18:40:42Z [ERR!] - The daemon could not start up successfully: Could not load setti>
Dec 18 19:40:42 raspberrypi iotedged[2964]: 2021-12-18T18:40:42Z [ERR!] -         caused by: Edge device information is required.

4. sudo systemctl status iotedge  

> iotedge.service - Azure IoT Edge daemon

     Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-12-19 14:24:27 CET; 1h 44min ago
TriggeredBy: ● iotedge.mgmt.socket
             ● iotedge.socket
       Docs: man:iotedged(8)
   Main PID: 876 (iotedged)
      Tasks: 14 (limit: 4915)
        CPU: 1.124s
     CGroup: /system.slice/iotedge.service
             └─876 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Dec 19 16:07:46 raspberrypi iotedged[876]: 2021-12-19T15:07:46Z [WARN] -         caused by: OCI runtime create failed: container with id exists: 516d6b151d2b10930cc4e67dbe04769fb1ad741a1ca2c6dfa1b1ed87886d51b3: unknown

Dec 19 16:08:45 raspberrypi iotedged[876]: 2021-12-19T15:08:45Z [INFO] - Checking edge runtime status
Dec 19 16:08:45 raspberrypi iotedged[876]: 2021-12-19T15:08:45Z [INFO] - Edge runtime status is stopped, starting module now...
Dec 19 16:08:45 raspberrypi iotedged[876]: 2021-12-19T15:08:45Z [INFO] - Starting module edgeAgent...
Dec 19 16:08:46 raspberrypi iotedged[876]: 2021-12-19T15:08:46Z [WARN] - Could not start module edgeAgent
Dec 19 16:08:46 raspberrypi iotedged[876]: 2021-12-19T15:08:46Z [WARN] -         caused by: OCI runtime create failed: container with id exists: 516d6b151d2b10930cc4e67dbe04769fb1ad741a1ca2c6dfa1b1ed87886d51b3: unknown
Dec 19 16:08:46 raspberrypi iotedged[876]: 2021-12-19T15:08:46Z [WARN] - Error in watchdog when checking for edge runtime status:
Dec 19 16:08:46 raspberrypi iotedged[876]: 2021-12-19T15:08:46Z [WARN] - A module runtime error occurred.
Dec 19 16:08:46 raspberrypi iotedged[876]: 2021-12-19T15:08:46Z [WARN] -         caused by: Could not start module edgeAgent
Dec 19 16:08:46 raspberrypi iotedged[876]: 2021-12-19T15:08:46Z [WARN] -         caused by: OCI runtime create failed: container with id exists: 516d6b151d2b10930cc4e67dbe04769fb1ad741a1ca2c6dfa1b1ed87886d51b3: unknown

Of course I updated the file config.yaml with connection string. Can somebody help me with that problem?

**Comment by arsing** [comment]
>docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.

https://github.com/Azure/iotedge/issues/5812
