### ISSUE TITLE
dufell: error during compile iotedge-daemon

### ISSUE THREAD

**Issue by nandra** [Azure/iotedge#5943]
Trying to build iotedge-dameon on dunfell branch and hitting this:
```
| error: attributes are not yet allowed on `if` expressions
|   --> /usr/src/debug/iotedge-daemon/1.1.8-r0/iotedge-1.1.8/vendor/sysinfo/src/utils.rs:27:5
|    |
| 27 |     #[allow(clippy::identity_conversion)]
|    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| 
| error: aborting due to previous error
| 
| error: could not compile `sysinfo`.
| 
```
Any ideas? Thanks.

**Comment by darobs** [comment]
Hi @nandra,

Please see [my comment on the meta-iotedge repo issue here](https://github.com/Azure/meta-iotedge/issues/72)

> Azure IoT Edge 1.1 is tied to Rust 1.47.0 - right now that means we pin the meta-rust repo at this commit:

>METARUST_REV: '7ff669d8cedd83a2d3efb73073a63b0a7efffddc'

My pre-holiday attempts at improving this experience didn't improve the experience, so fixing this is still in the backlog.  I am closing this here to continue to track the issue on the Azure/meta-iotedge.
