### ISSUE TITLE
Timestamp of log entries in module logs is 13.5 hrs ahead of local time

### ISSUE THREAD

**Issue by alkreddy** [Azure/iotedge#595]
## Expected Behavior
Timestamp is local or in GMT

## Current Behavior
Timestamp is 13.5 hrs ahead of local time 

## Steps to Reproduce

1. Install iotedge 1.0.4
2. Start iotedge
3. Notice log entries for edgeAgent module
4.

### Device (Host) Operating System
Windows 10 -1809

### Architecture
amd64

### Container Operating System
Linux Containers

#### iotedged
iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Docker
Docker version 18.09.0, build 4d60db4

## Logs
**2018-12-02 06:35:47.757 +05:30** [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-12-02 06:35:47.759 +05:30 [INF] - Edge agent config backup file does not exist - backup.json
2018-12-02 06:35:57.772 +05:30 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
2018-12-02 06:35:57.772 +05:30 [INF] - Edge agent config backup file does not exist - backup.json

### Local Time at the time of reporting this issue
**Saturday, December 1, 2018 5:05:45 PM**
User in India Time Zone

**Comment by myagley** [comment]
Hello. In this setup you are running Linux containers on a Windows host? The linux containers are run in a Hyper-V VM. Is it possible there is time skew between this VM and the host?

What's interesting is that the log time stamp indicates a timezone offset of `+05:30` (which is for India Standard Time). However, the Edge Agent should be logging timestamps in UTC. (`+00:00`) I believe this is explicitly set.

**Comment by alkreddy** [comment]
Hi @myagley . That's corrrect, I am running LInux Containers on a Windows Host. I do understand that the linux containers are run in a Hyper-V VM. I don't know how to check if there is time skew. Will investigate.

Is there a setting that I should look for w.r.t edgeAgent timezone offset? I haven't explicitly set anything

**Comment by arsing** [comment]
If this is still an issue, please confirm that the Docker Linux VM does have the correct time (`docker-machine ssh docker date`). If it is, we can reopen the issue then.
