### ISSUE TITLE
iotedge service fails to start (1.0.4)

### ISSUE THREAD

**Issue by alkreddy** [Azure/iotedge#596]
## Expected Behavior
IotEdge Service should start without errors

## Current Behavior
Start-Service : Failed to start service 'iotedge (iotedge)'.
At line:1 char:1
+ Start-Service iotedge
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand

## Steps to Reproduce

1. In powershell run **Start-Service iotedge**

### Device (Host) Operating System
Win10 Pro Build 1809

### Architecture
amd64

### Container Operating System
Linux

#### iotedged
iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0.4

#### Docker
Docker version 18.09.0, build 4d60db4

## Logs
attached
[iotedgedlogs.txt](https://github.com/Azure/iotedge/files/2635947/iotedgedlogs.txt)

**Comment by myagley** [comment]
Thanks for the issue.

Is it possible to see more of iotedged.exe logs? Initially it looks like the `config.yaml` is invalid and can't parse correctly.

**Comment by alkreddy** [comment]
@myagley Sure. Can you help point me to the location of iotedged.exe logs?

**Comment by alkreddy** [comment]
@myagley I just used www.yamllint.com to validate the content of config.yaml and it reported no issues.

**Comment by alkreddy** [comment]
@myagley Looking for advice on resolving this issue

**Comment by myagley** [comment]
The following page explains how to retrieve logs for `iotedged`: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#standard-diagnostic-steps

More logs will help provide more context for what is happening.

**Comment by myagley** [comment]
It looks like the daemon is failing to connect to the docker engine.

What is the value of the `moby_runtime.uri` setting in the `config.yaml`? This should be `npipe://./pipe/docker_engine` on Windows.

**Comment by alkreddy** [comment]
@myagley  The setting appears to have the correct value
moby_runtime:
  uri: "npipe://./pipe/docker_engine"
  network: "azure-iot-edge"

**Comment by alkreddy** [comment]
I moved ahead with newer version and a new environment. This issue is not relevant anymore
