### ISSUE TITLE
[QUESTION] How dev Azure Iot Edge?

### ISSUE THREAD

**Issue by mdevgum** [Azure/iotedge#5970]
After reading the Dev Guide I still don't understand how to start developing in this project.

My steps I have followed are:

[1] Clone the repo.
[2]  Run the script scripts/linux/buildBranch.sh
[3] Try to build the IotEdge Hub
-     scripts/linux/cross-platform-rust-build.sh --os alpine --arch amd64 --build-path mqtt/mqttd
-       scripts/linux/cross-platform-rust-build.sh --os alpine --arch amd64 --build-path edge-hub/watchdog
-       scripts/linux/consolidate-build-artifacts.sh --artifact-name "edge-hub"
With the last command I get errors like:

- cp: /Users/Desktop/iotEdge/iotedge/target/publish/Microsoft.Azure.Devices.Edge.Hub.Service: No such file or directory
- cp: /Users/Desktop/iotEdge/iotedge/mqtt/target/armv7-unknown-linux-gnueabihf/release/mqttd: No such file or directory
- cp: /Users/Desktop/iotEdge/iotedge/mqtt/target/aarch64-unknown-linux-gnu/release/mqttd: No such file or directory
- cp: /Users/Desktop/iotEdge/iotedge/edge-hub/watchdog/target/armv7-unknown-linux-gnueabihf/release/watchdog: No such file or directory
- cp: /Users/Desktop/iotEdge/iotedge/edge-hub/watchdog/target/aarch64-unknown-linux-gnu/release/watchdog: No such file or directory

[4] Try to complie EdgeAgent

After getting some errors with  librocksdb installation I changed this line in Dockerfile  and executed this command and seems to work.

Install RocksDB
- COPY $EXE_DIR/librocksdb/librocksdb.so.amd64 /usr/local/lib/librocksdb.so
+ COPY native/amd64/librocksdb.so /usr/local/lib/librocksdb.so

docker build --no-cache -t localhost:5000/microsoft/edge-agent:1.0.0-linux-amd64 --file target/publish/Microsoft.Azure.Devices.Edge.Agent.Service/docker/linux/amd64/Dockerfile  target/publish/Microsoft.Azure.Devices.Edge.Agent.Service

But when I run the container I get:

2022-01-10 08:09:04.486 +00:00 [FTL] - Fatal error building application.

System.FormatException: Malformed Token

   _at Microsoft.Azure.Devices.Common.CommonExtensionMethods.ToDictionary(String valuePairString, Char kvpDelimiter, Char kvpSeparator)
   at Microsoft.Azure.Devices.IotHubConnectionStringBuilder.Parse(String iotHubConnectionString)
   at Microsoft.Azure.Devices.IotHubConnectionStringBuilder.Create(String iotHubConnectionString)
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /Users/Desktop/iotEdge/iotedge/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 169_

So In this points I have 2 questions.
How do I compile the Iot Hub Edge project?
and more important.
After I get booth containers (Agent and Hub), how I deploy these containers in a VM to try my custom feature ?

This is the first project of this type that I am trying to develop and I am having a lot of problems getting started. I have a strong background in web development, so it is possible that I am asking something basic. Any help or guidance you can give me would be appreciated. 
Best regards

**Comment by micahl** [comment]
Hi @mdevgum, is your goal to modify IoT Edge or is it to create your own containerized module of functionality that leverages the features of IoT Edge?  I'm assuming the latter in which case I'd suggest starting with our docs on [Develop your own IoT Edge modules](https://docs.microsoft.com/en-us/azure/iot-edge/module-development?view=iotedge-2020-11).

**Comment by mdevgum** [comment]
Hi @micahl. Thanks for your time.

Im focus in modify IoT Edge to give the project some new functionalities. My first goal, is manage modules with an API but without use Azure IoT Hub. 

For achieve this, my first approach, has been compile the hub and agent modules, and try to use them inside a  normal installation, but I have problems following this documentation. 
https://github.com/Azure/iotedge/blob/master/doc/devguide.md

My second attempt, and I think this is the important to get the functionality, has been try to compile the runtime module following this instructions: https://github.com/Azure/iotedge/blob/master/edgelet/doc/devguide.md
but when I run the command:

`cargo run -p aziot-edged -- -c /my/path/to/config.yaml or cargo run -p aziot-edged -- -c /my/path/to/config.toml`

I get  Found argument '-c' which wasn't expected, or isn't valid in this context

So I have tried to use only: cargo run -p aziot-edged, and create the a config.toml in /etc/aziot folder,  but I get 
_The daemon could not start up successfully: Could not load settings_

I don't know if I am using the command incorrectly, or the documentation is not updated to version 1.2 .

Any advice or comments would be very helpful
Thanks for your time.

**Comment by micahl** [comment]
Ah, thanks for clarifying @mdevgum!  I'll defer to @and-rewsmith and others on ensuring the docs to build the project are correct.  

I'll focus more on the new functionality you're interested in.  Can you talk more about what kind of module management you'd like to do without IoT Hub?  There may already be something that provides what you need.  Or it could be a good starting place to look.  

The other aspect to consider is that the current design and implementation of IoT Edge depends on a number of things from IoT Hub that are non-trivial to change without significant effort (i.e. multiple dev team members working for an extended period of time).  If what you want to accomplish falls into that bucket then minimally I'd like to make sure you're aware before embarking on that kind of journey.  :)

**Comment by mdevgum** [comment]
Hi @micahl 
First of all, thanks again for your time. 

I'm going to try to explain the functionality I'm working on and why. The first functionalities will be:
- Provision a new device and generate a connection string with symmetric key.
- Monitor the status of devices and modules.
- Deploy modules to devices

And why am I trying to do this without azure hub. Basically because all the devices are going to be deployed in the same area with no possibility of internet access, and they need to be monitored in real time.

These are the steps I am following to achieve this:
- Run edgelet (Iot Edge security deamon) and try to find how it connects to iot hub, and how iot hub connect to it. 
I found the files: "device_actions_api", "identity_api", "module_api"... and this guide "https://github.com/Azure/iotedge/blob/release/1.1/edgelet/doc/testiotedgedapi.md". I'm not sure if this allows the connection directly to the client, but I'm working from here.

- The second part would be to perform the same analysis with the iot agent to see how it gets the manifest to deploy the modules.

As you say it is a very large project and therefore it is possible that I am not understanding well the scope of what I want to do. There are other solutions that may suit the offline environment that I want to do, but the advantage of being able to deploy in the future in Azure Hub is one thing I do not want to lose.

By the way, running version 1.1 of the project I have no problems, neither compilation nor execution, so for now, it's enough for my research.

Again, thanks, and any comments or advice will be very helpful.

**Comment by micahl** [comment]
Thank you for elaborating on your scenario, @mdevgum.  [IoT Edge does support an extended offline mode ](https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities?view=iotedge-2020-11) that may be sufficient for your needs.  The big question is whether its OK to have at least one initial connection to IoT Hub to establish a cloud identity for the various modules you want to deploy.  If so then the doc I referenced should help.  You may also find the [doc page on our built-in metrics for EdgeAgent / EdgeHub](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-built-in-metrics?view=iotedge-2020-11) to be relevant if you want to set up something locally on the box to scrape the metrics and expose it in a dashboard.

If that's not OK and the requirement is to do all the above without ever connecting to IoT Hub then that will be in the "prepare for a long journey" kind of exercise.

**Comment by and-rewsmith** [comment]
@mdevgum 

We can work on getting this devguide build process cleaned up for our 1.2 bits.

> With the last command I get errors like:
cp: /Users/Desktop/iotEdge/iotedge/target/publish/Microsoft.Azure.Devices.Edge.Hub.Service: No such file or directory

This error is valid, and I think it is because the dotnet source code hasn't been built:
`scripts/linux/buildBranch.sh`

The other errors are actually warnings about artifacts for other platforms, and we can help to clear that up. The script is being reused here from something in our build pipelines which is used in a slightly different way. But with the below warnings I believe it will still work.
```
cp: /Users/Desktop/iotEdge/iotedge/mqtt/target/armv7-unknown-linux-gnueabihf/release/mqttd: No such file or directory
cp: /Users/Desktop/iotEdge/iotedge/mqtt/target/aarch64-unknown-linux-gnu/release/mqttd: No such file or directory
cp: /Users/Desktop/iotEdge/iotedge/edge-hub/watchdog/target/armv7-unknown-linux-gnueabihf/release/watchdog: No such file or directory
cp: /Users/Desktop/iotEdge/iotedge/edge-hub/watchdog/target/aarch64-unknown-linux-gnu/release/watchdog: No such file or directory

```

**Comment by and-rewsmith** [comment]
I fixed up the local EdgeHub build script which broke due to a recent change to our build process.  Should be all good now.
https://github.com/and-rewsmith/iotedge/blob/877351cbe525032735c900825288beccbef323c6/doc/devguide.md#build-edge-hub-container-locally
