### ISSUE TITLE
Metrics for IoT devices running behind an IoT edge device in transparent mode

### ISSUE THREAD

**Issue by krokoko** [Azure/iotedge#5989]
Hi team,

  Could you please provide some information related to metrics available for downstream IoT devices child (running the IoT C SDK) to an IoT edge device running in transparent mode ? I see [this page](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-monitor-with-workbooks?view=iotedge-2020-11) about metrics available for an IoT edge device through Azure workbooks. 
Is there anything supported out of the box for this use case ? If not, is there anything planned ?

Thank you !

**Comment by and-rewsmith** [comment]
@krokoko If these downstream devices are connected to EdgeHub, EdgeHub will emit these prometheus metrics for connected clients:
https://github.com/Azure/iotedge/blob/master/doc/BuiltInMetrics.md

As the link you found described, you can setup the metrics collector module to collect these prometheus metrics from EdgeHub (and EdgeAgent too if needed). The metrics collector module will then send these metrics either to iothub or directly to Log Analytics for consumption.

If you need metrics which aren't specified in the `BuiltInMetrics.md` documentation, you have the option to setup a prometheus metrics server and emit whatever metrics you want for downstream clients. The metrics collector module can then be used to collect these custom metrics and route them to the desired location.

**Comment by jlian** [comment]
Hey @krokoko I'm closing this issue since @and-rewsmith has provided an answer. I assume your question is answered since we haven't heard back for about a week. If not, please reopen the issue.

Also tagging @micahl for visibility on workbook improvements
