### ISSUE TITLE
MetricsCollector does not support changing the request URI

### ISSUE THREAD

**Issue by F-Joachim** [Azure/iotedge#5992]
In a nested edge scenario, I want to connect the [MetricsCollector](https://github.com/Azure/iotedge/tree/master/edge-modules/MetricsCollector) running on a child edge node to the Log Analytics workspace via the parent edge node (and thus the API proxy). For this I would have to adjust the request URI so that it points to the parent edge node first. Unfortunately this is not possible because the URI is [hardcoded](https://github.com/Azure/iotedge/blob/master/edge-util/src/Microsoft.Azure.Devices.Edge.Util/azureLogAnalytics/AzureLogAnalytics.cs#L52) and thus the MetricsCollector cannot be used in a nested edge setup.

Are there already any efforts to support this case or is there any other way?

Please let me know if you need more information. Thanks in advance.

**Comment by veyalla** [comment]
Thank you for your question. In a nested scenario, the recommended pattern for transporting metrics is via D2C messages. You'd need to [set](https://aka.ms/edgemon-config) `UploadTarget` to `IoTMessage`. Please see the[ Route metrics](https://docs.microsoft.com/azure/iot-edge/how-to-collect-and-transport-metrics?view=iotedge-2020-11&tabs=iothub#route-metrics) doc section for more details.

Note: the latest code for metrics collector module lives here: https://github.com/Azure/iotedge/tree/release/1.1/edge-modules/azure-monitor
