### ISSUE TITLE
edgeHub Memory Usage with Persistent Storage Enabled

### ISSUE THREAD

**Issue by sely-growlink** [Azure/iotedge#5999]
I have a customer device whose edgeHub module consumes a large amount of RAM relative to our device (Raspberry Pi CM3). This customer's setup is processing about 4-5 UDP messages off the network per second and forwarding them to another module via routing. Most customers don't seem to have an issue, but this one may have a higher volume of messages than most.

As a test, we changed TTL from 30 seconds to 15 seconds, and saw a significant reduction in memory usage. My questions are:

1. If we're using the default where `UsePersistentStorage` is `false`, why would we see a change here? I understand the message queue is not being stored in RAM in this case, so I wouldn't expected the TTL change to impact RAM usage.
2. How can I determine why TTL would even be a factor in this setup? I have a bit more digging to do, but given the TTL change, the queue seems to not be processed very quickly and would indicate high latency. Any suggestions on optimizing this?

Let me know what additional information I can pull to make it easier to troubleshoot as well. Thanks!

**Comment by and-rewsmith** [comment]
@sely-growlink Assume you mean `UsePersistentStorage` is `true`.

I agree a change in TTL shouldn't cause this behavior. However EdgeHub is a dotnet component, which uses garbage collection. Garbage collection isn't guaranteed to run periodically, which means EdgeHub may be "using" a lot of memory, but a lot of this is no longer needed and can be freed when needed. This behavior around when garbage collection occurs is probably adding some noise to your investigation.

Assuming this isn't causing any functional issues for you?

**Comment by sely-growlink** [comment]
@and-rewsmith Sorry, you're right. It's set to the default of `true`. What's odd here is I can restart edgeHub, all the memory is freed, but then within 10 minutes or so it's re-used a lot of it, and then it continues to grow at a slower rate. There are no cycles or anything that I've observed.

**Comment by and-rewsmith** [comment]
@sely-growlink I've ran some tests myself on this when someone else encountered this behavior. For all the tests I have done, EdgeHub memory will be freed at some point.

If you are interested in capping EdgeHub memory usage, I would recommend using docker create options in the EdgeHub portion of your deployment file:
https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-2020-11#limit-container-access-to-host-resources

**Comment by sely-growlink** [comment]
@and-rewsmith Does setting the cap just cause an OOM to be thrown and then the module is restarted?

Are there tools I can use to get information on queue sizes that are occurring? I still feel like there's a throughput issue to address, and I don't understand why persistent storage queues would be impacted in this case.

Tangentially, would disabling persistent storage increase performance by not using the disk for every operation?

**Comment by and-rewsmith** [comment]
> Does setting the cap just cause an OOM to be thrown and then the module is restarted?

Setting the cap disallows EdgeHub memory from ever growing past some arbitrary threshold. If it does pass this threshold the module will be restarted, but at least it won't impact your whole device (and importantly, ssh access).

> I have a bit more digging to do, but given the TTL change, the queue seems to not be processed very quickly and would indicate high latency.

Can you elaborate on this? What leads you to believe the queue is not being processed very quickly?

> Are there tools I can use to get information on queue sizes that are occurring? I still feel like there's a throughput issue to address, and I don't understand why persistent storage queues would be impacted in this case.

I think EdgeHub logs would give a good indication. You will probably need debug level logs.

> Tangentially, would disabling persistent storage increase performance by not using the disk for every operation?

It would, but then the data in flight becomes less resilient in the case of crashes or high memory usage across the system.

**Comment by sely-growlink** [comment]
> > I have a bit more digging to do, but given the TTL change, the queue seems to not be processed very quickly and would indicate high latency.
> 
> Can you elaborate on this? What leads you to believe the queue is not being processed very quickly?

Well, if we cut TTL in half, and the memory issue is largely mitigated, it would indicate messages are being left in the queue for some time. In this case, we're looking to route multiple messages per second, so if going from 30 seconds TTL to 15 shrinks memory usage, it would indicate the queue is not being kept relatively clear, and if memory usage is growing over time, it would seem like the queue is getting longer as well, but like you said, I probably need to turn on debug logs for edgeHub.

**Comment by and-rewsmith** [comment]
> Are there tools I can use to get information on queue sizes that are occurring? I still feel like there's a throughput issue to address, and I don't understand why persistent storage queues would be impacted in this case.

Forgot about the fact our built in metrics expose insight into EdgeHub queue length. If you want to leverage these built in metrics, I would follow this documentation:
https://aka.ms/edgemon-docs

Please let me know if you have any questions, happy to help!

**Comment by sely-growlink** [comment]
@and-rewsmith Thanks. That module is definitely on my to do list to check out. Maybe this is a good case for trying it out.

**Comment by and-rewsmith** [comment]
@sely-growlink Did you get a chance to try out the built in metrics?

**Comment by sely-growlink** [comment]
@and-rewsmith Not yet, unfortunately. I'm on vacation this week and the TTL change has mitigated this device's issue until we have time to deploy the monitoring module. Definitely plan to get to it as soon as I can though. Thanks for checking in. If you'd prefer to close the issue for now, I can open a new one if I discover something later. I'm still at a loss for why the TTL change would free up so much RAM while using persistent storage.
