### ISSUE TITLE
IOTEDGE Module metrics Collector Certificate Clarification

### ISSUE THREAD

**Issue by anoop18pant** [Azure/iotedge#6014]
hi,
IOT egde module metrics collector creates one certificate when it starts but we can not find any documentation regarding the expiration policy of that certificate.

Can you please help us to understand the lifecycle for that certificate which mertrics collector creates when it starts.

Basically the question is if this certificate gets expire does metrcis collector will renew it itself without ?

**Comment by ancaantochi** [comment]
Metrics collector doesn't generate a certificate. Can you please let me know where did you see a certificate for metrics collector?

**Comment by anoop18pant** [comment]
Thank you for your reply!!!!

We are using azureiotedge-metrics-collector.

we are using this link https://docs.microsoft.com/en-us/azure/iot-edge/how-to-collect-and-transport-metrics?view=iotedge-2020-11&tabs=iothub
and this section :
"Metrics collector module"
"A Microsoft-supplied metrics-collector module can be added to an IoT Edge deployment to collect module metrics and send them to Azure Monitor. The module code is open-source and available in the IoT Edge GitHub repo.

The metrics-collector module is provided as a multi-arch Docker container image that supports Linux X64, ARM32, ARM64, and Windows X64 (version 1809). It's publicly available at mcr.microsoft.com/azureiotedge-metrics-collector.

It also available in the IoT Edge Module Marketplace."

The module is at "https://hub.docker.com/_/microsoft-azureiotedge-metrics-collector" and the source code is at 
https://github.com/Azure/iotedge/tree/release/1.1/edge-modules/azure-monitor

We are using this module. Should we worry about the certificate renewal/expiration ?

Thanks

**Comment by ancaantochi** [comment]
If there is when error when metrics are published the cert is regenerated automatically: https://github.com/Azure/iotedge/blob/7b689b3d58f2b732f7ff5138ba36c9c331449322/edge-modules/azure-monitor/src/FixedSetTableUpload/AzureFixedSetTable.cs#L138

**Comment by anoop18pant** [comment]
Thanks for your reply. 
I am asking for https://github.com/Azure/iotedge/blob/7b689b3d58f2b732f7ff5138ba36c9c331449322/edge-modules/azure-monitor/src/CertificateGenerator/CertGenerator.cs

        private static (X509Certificate2, (string, byte[]), string) CreateSelfSignedCertificate(string agentGuid, string logAnalyticsWorkspaceId)
        {
            var random = new SecureRandom();

            var certificateGenerator = new X509V3CertificateGenerator();

            var serialNumber = BigIntegers.CreateRandomInRange(BigInteger.One, BigInteger.ValueOf(Int64.MaxValue), random);

            certificateGenerator.SetSerialNumber(serialNumber);

            var dirName = string.Format("CN={0}, CN={1}, OU=Microsoft Monitoring Agent, O=Microsoft", logAnalyticsWorkspaceId, agentGuid);

            X509Name certName = new X509Name(dirName);

            certificateGenerator.SetIssuerDN(certName);

            certificateGenerator.SetSubjectDN(certName);

            certificateGenerator.SetNotBefore(DateTime.UtcNow.Date);

            certificateGenerator.SetNotAfter(DateTime.UtcNow.Date.AddYears(1));

Is this certificate will also be generated automatically? If yes then why 1 year is passed as hardcoded value.

Can you please let me know if this certificate will also generated automatically whenever needed?

**Comment by ancaantochi** [comment]
yes, that certificate from CertGenerator is going to be automatically renewed. The 1 year lifetime is the default that Log Analytics uses.

**Comment by anoop18pant** [comment]
Hi, I have one more query if i am behind proxy  and i have configured the proxy environment for aziot-edged and aziot-identity using sudo systemctl edit aziot-edged and sudo systemctl edit aziot-identityd and specified our proxy URL. Followed the link (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2020-11)

Will my metrcis collector will work correctly if i followed above steps or do i need to make some changes for metrcs collector saparately to work behind proxy.

**Comment by ancaantochi** [comment]
@anoop18pant I am sorry for the delayed reply. 
Yes, the metrics collector should work behind a proxy, you need to configure https_proxy env variable in deployment, similar as for edgeHub: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support?view=iotedge-2020-11#azure-portal

**Comment by micahl** [comment]
Closing this issue as the question(s) appear to have been answered.
