### ISSUE TITLE
[Request] Make it easier to have edgeHub / edgeAgent data persisted in a volume instead on the host

### ISSUE THREAD

**Issue by derSchtefan** [Azure/iotedge#6035]
Using edgeAgent/edgeHub 1.1.8. 

We are migrating existing IoT solutions to a common solution on Azure IoT edge. Because we do not know or have full control over the host's file system, and for reasons of a "clean" and contained architecture and deployment, we prefer not to have the edgeAgent and edgeHub data persisted on the host storage system.

We do have to persist that data otherwise the issues in #5849 start to occur when the edgeAgent gets recreated during a deployment.

We worked around this limitation by mounting two volumes into the /tmp folder of the edgeAgent / edgeHub. We cannot use any other folder like [described in this document](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-2018-06), because only /tmp has 777 permission inside the images, and the container is running as uid 1000 and not root. With docker, when you mount a new volume, the mount is inheriting the existing mountpoint's permission.

Right now, the default for `storageFolder` is an empty string, which seems to default to /tmp by an unspecified mechanism. And only /tmp has 777 permission. What we would like to see is that a clear default is established either by declaring and documenting that the /tmp directory will stay the default mount point for the whole 1.1 LTS series, or a clear sensible default like /data is declared and documented as the default. (Although it looks ugly, having /tmp stay the default directory that is 777 is probably the best). In either case `storageFolder` in the correspoinding appconfig.json files should be pre-filled to make the default less obscure.

This would make using a volume as permanent storage much more safe, without having to create a custom Dockerfile.
Our fear is that otherwise (even though it is a 1.1 LTS), somebody might change something in the Dockerfile, and (for example)  version 1.1.9 won't suddenly have a /tmp directory with 777 permission created, causing the startup to fail.

**Comment by scb01** [comment]
Hello @derSchtefan 
I am checking with the team on this request and will let you know once I have an update.

**Comment by micahl** [comment]
Hi @derSchtefan, thank you for sharing this suggestion.  It certainly has merit.  We're using [https://aka.ms/iotedge-suggestion](https://aka.ms/iotedge-suggestion) to track feature requests.  Please add your suggestion (and feel free to link back to this github issue).
