### ISSUE TITLE
LISTEN_FDNAMES is set to an invalid value

### ISSUE THREAD

**Issue by Takahiro-Tsuji** [Azure/iotedge#6043]
I have set up my raspberry pi 3B(raspbian stretch) with IOT Edge according to the instruction [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11](url) .
the authentication type of the device is symmetric.

1. Provision the device with its cloud identity section
iotedge version is 1.2.7  
So, skipped editing /etc/iotedge/config.yaml and quickly configured with my primary connection string.
When issued "sudo iotedge config apply' command, the following message appeared:

Note: Symmetric key will be written to /var/secrets/aziot/keyd/device-id
Azure IoT Edge has been configured successfully!

Restarting service for configuration to take effect...
Stopping aziot-edged.service...Stopped!
Stopping aziot-identityd.service...Stopped!
Stopping aziot-keyd.service...Stopped!
Stopping aziot-certd.service...Stopped!
Stopping aziot-tpmd.service...Stopped!
Starting aziot-edged.mgmt.socket...Started!
Starting aziot-edged.workload.socket...Started!
Starting aziot-identityd.socket...Started!
Starting aziot-keyd.socket...Started!
Starting aziot-certd.socket...Started!
Starting aziot-tpmd.socket...Started!
Starting aziot-edged.service...Started!
Done.
I think it is ok.

2. Verify successful configuration" section
"sudo systemctl status iotedge" command message:
iotedge service
  Loaded: not found (Reason: No such file or directory)
  Active:  inactive ( dead)
.
"sudo iotedge system status" command message:
System services:
    aziot-edged             Down - activating
    aziot-identityd         Running
    aziot-keyd              Running
    aziot-certd             Running
    aziot-tpmd              Ready

aziot-edged is in a bad state because:
aziot-edged.service: Down - activating : Printing the last 10 log lines.
-- Logs begin at 火 2022-01-25 19:35:26 JST, end at 火 2022-01-25 19:56:56 JST. --
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [INFO] - Finished provisioning edge device.
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [INFO] - Stopping all modules...
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [INFO] - Finished stopping modules.
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [INFO] - Detecting if device information has changed...
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [INFO] - Starting management API...
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [INFO] - Starting watchdog with 60 second frequency...
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [ERR!] - The daemon could not start up successfully: Could not start management service
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [ERR!] -         caused by: Invalid URL "fd://aziot-edged.mgmt.socket": URL could not be parsed as fd number nor fd name
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [ERR!] -         caused by: Environment variable LISTEN_FDNAMES is set to an invalid value.
 1月 25 19:56:52 cloverfieldrasp aziot-edged[2234]: 2022-01-25T10:56:52Z [ERR!] -         caused by: environment variable not found

Use 'iotedge system logs' to check for non-fatal errors.
Use 'iotedge check' to diagnose connectivity and configuration issues.

3. config.toml
auto_reprovisioning_mode = "OnErrorOnly"

[provisioning]
source = "manual"
connection_string = "HostName=....;DeviceId=....;SharedAccessKey=....="

[aziot_keys]

[preloaded_keys]

[cert_issuance]

[preloaded_certs]

[agent]
name = "edgeAgent"
type = "docker"
imagePullPolicy = "on-create"

[agent.config]
image = "mcr.microsoft.com/azureiotedge-agent:1.2"
[agent.config.createOptions]

[agent.env]

[connect]
workload_uri = "unix:///var/run/iotedge/workload.sock"
management_uri = "unix:///var/run/iotedge/mgmt.sock"

[listen]
workload_uri = "fd://aziot-edged.workload.socket"
management_uri = "fd://aziot-edged.mgmt.socket"
min_tls_version = "tls1.0"

[watchdog]
max_retries = "infinite"

[moby_runtime]
uri = "unix:///var/run/docker.sock"
network = "azure-iot-edge"
<end of config.toml>

4. system version
:~ $ systemctl --version
systemd 215
+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR
tsuji@cloverfieldrasp:~ $ dpkg -l systemd
要望=(U)不明/(I)インストール/(R)削除/(P)完全削除/(H)保持
| 状態=(N)無/(I)インストール済/(C)設定/(U)展開/(F)設定失敗/(H)半インストール/(W)トリガ待ち/(T)トリガ保留
|/ エラー?=(空欄)無/(R)要再インストール (状態,エラーの大文字=異常)
||/ 名前           バージョン   アーキテクチ 説明
+++-==============-============-============-=================================
ii  systemd        215-17+deb8u armhf        system and service manager
:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.13 (n/a)
Release:        9.13
Codename:       n/a
tsuji@cloverfieldrasp:~ $ iotedge --version
iotedge 1.2.7

I don't know LISTEN_FDNAMES variable.
systemd version is old even if os version is 9.
Let me know how to correct this issue, please.

**Comment by Takahiro-Tsuji** [comment]
Today issued the following command and now daemon is running.
sudo apt-get upgrade systemd

Now I run sudo iotege check command and I need help for the following error:
Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

**Comment by scb01** [comment]
@Takahiro-Tsuji 
Good to know that you are now past the LISTEN_FDNAMES issue.

To address the other issues, have you tried the steps in the links mentioned by the check tool?

**Comment by Takahiro-Tsuji** [comment]
@scb01 
The above error is gone and now 3 warning still remains.
On my iot edge page $edgeAgent and $edgeHub and SimulatedTemperatureSensor are all running.
I checked the check tools from the links but it is not easy to understand.
I just want to make steps to test with Pi 3 and my USB camera according to Code Sample "Custom Vision + Azure IoT Edge on a Raspberry Pi 3". But now at "Get started section" of the github page it says "Update the .env file with the values for your container registry and make sure that your docker engine has access to it".
Where is the container registry? and How to make docker access to it?

**Comment by Takahiro-Tsuji** [comment]
@scb01 
Happy with your answer. I posted an issue there.

**Comment by scb01** [comment]
@Takahiro-Tsuji 
Thank you. I'll go ahead and close this issue. Please feel free to reach back if you run into further issues.
