### ISSUE TITLE
Changing path of config files folder

### ISSUE THREAD

**Issue by SebsSa** [Azure/iotedge#6045]
## Expected Behavior
There should be documentation on how to change the path of the config files folder.

## Current Behavior
Missing possibility to change the path of the config folder. At the moment they are under /etc/aziot
But I would like to put them in a another location.

### Device Information
* Host OS : linux
* Architecture : arm32
* Container OS:  linux congtainer

### Runtime Versions
* aziot-edged: iotedge 1.2.6 
* Docker: Docker version 19.03.8-ce

**Comment by scb01** [comment]
Hello @SebsSa 

Currently there isn't a fully supported way of changing the path of the config files folders. 
Curious - what is the scenario or reason why you want these located elsewhere?

**Comment by SebsSa** [comment]
Hey @scb01 

In my/our setup we use an over-the-air update manager and the device will be "split" into A/B partition.
There is in this case only one folder that remains constant (called data folder).
In special cases the whole system could be overwritten except this special folder. 

Thanks - Counter question: So there is a "not" supporten way ? Is there any documentation on this?

**Comment by scb01** [comment]
@Sebsa Unfortunately there isn't any documentation that I know of that describes setting up alternate locations for the config files. Have you explored options such as symlinks, mounting a disk at /etc/aziot etc?

**Comment by SebSa** [comment]
@scb01 You've ping the wrong user fyi

**Comment by scb01** [comment]
@SebSa my bad. 

@SebsSa Please review my response and let me know if there are further questions.

**Comment by SebsSa** [comment]
Thank you very much yes with syslinks it works!

**Comment by emilm** [comment]
I created a symlink /etc/aziot/identityd/config.d/00-super.toml -> /mydata/identity/00-super.toml with ln -s and it does no work. 
` aziot-identityd[13651]: 2023-03-10T14:47:08Z [ERR!] - could not read config
2023-03-10T14:47:08Z [ERR!] - caused by: could not read config `
