### ISSUE TITLE
Mismatch iotedged and edgeHub versions

### ISSUE THREAD

**Issue by dehoward** [Azure/iotedge#6046]
Hi team,
We have a customer who would like to take advantage of the `$.sub` component name mapping [introduced in v1.2.4](https://github.com/Azure/azure-iotedge/releases/tag/1.2.4) of the `azureiotedge-hub`, but is currently running [LTS v.1.1.8](https://raw.githubusercontent.com/Azure/azure-iotedge/master/latest-iotedge-lts.json) of `iotedged`. 

Is the version mismatch here ok? Or, is it necessary to update the `iotedged` to 1.2 as well to avoid conflicts?

I've seen mention in older issues that the changes made in any subsequent versions are meant to be backwards compatible ([#3986](https://github.com/Azure/iotedge/issues/3986#issuecomment-730065915) & [#2809](https://github.com/Azure/iotedge/issues/2809#issuecomment-610602490)), but wanted to confirm this specific scenario.

**Comment by micahl** [comment]
Our guidance for production usage is to match the release of the runtime with the system modules (e.g. only use 1.1.x or only use 1.2.x).  While our APIs between versions are developed to be backward compatible, we don’t do general testing on mixing / matching of the runtime and system modules.  

If the customer has devices in production already and want to minimize churn then using 1.2.4 EdgeHub with 1.1.* iotedged should work.  But again, its not a combination we’re actively testing.  A customer would need to be willing to test their scenarios thoroughly before going down that route.

**Comment by dehoward** [comment]
Thanks for the quick response, closing.
