### ISSUE TITLE
Remote restart of the Azure IoT Edge runtime

### ISSUE THREAD

**Issue by iconics-pavels** [Azure/iotedge#608]
Hi,

I would like to ask you whether there is a way e.g. from the Azure portal to restart remotely the Azure IoT Edge runtime running on the gateway? If not, is there a plan to support it?

I am asking because we are seeing a situation when our custom Edge module doesn't start properly when we remove it and add it again. I know this will be fixed and I got some other recommendations how to resolve or workaround the issue.

In this case the solution was to restart the IoT Edge runtime and then our module started too. Maybe there will be some other issue in the future and the restart of the runtime will be needed. So I would like to know whether there is a plan to have this feature.

Thank you.

**Comment by myagley** [comment]
This isn't directly supported but is something that we are looking to add in the next couple of months. 

You can simulate a restart for your module by setting the status to "stopped", deploying, and then setting to "running" and redeploying. This will cause the Edge Agent to stop the module and then subsequently start it. However, this will not work for the Edge Agent itself or the daemon (`iotedged`).

Can I ask why you are removing modules and adding them back? I'm just trying to understand the scenario. Perhaps we can improve the underlying issue.

**Comment by icebat83** [comment]
Well, at this moment we are doing it during the development. But I can imagine that in the future our customers will install some custom module. They can then decide to remove it and maybe add later because they will need it again.

But as I wrote, it may happen that there will be another issue that will require restart of the Azure IoT Edge runtime. And if the gateway will not be accessible via SSH e.g. then it will be a big problem.

**Comment by myagley** [comment]
We fully understand the concern and will have a solution in the near term. I unfortunately can't provide more details at this moment.

**Comment by khilscher** [comment]
> +1
> Edge devices in my use cases are turn-key arms-length affairs locked away on a customer premises. Remote restart (or killing of the container so docker will restart it) of IOT Edge Agent would be good so we wouldn't have to ask a customer to press the reboot button on the Edge hardware.

Likewise, I foresee the need to restart the operating system on an Edge device via a direct module method call. I don't believe you can restart an operating system from the within the container due to the security.

**Comment by pazniak** [comment]
+1
This is an issue for me as well. I workaround it with an `ssh systemctl restart iotedge.service` , but it'd be more reliable to have an `az iot edge` command to do that.

**Comment by petermillsacumentive** [comment]
We are facing a similar problem, we don't really want to run one of our containers with elevated permissions. It would be excellent if this sort of functionality was built-in.

**Comment by mparkitny** [comment]
> 
> This isn't directly supported but is something that we are looking to add in the next couple of months.
> 

Any chances that this feature will be added?

**Comment by veyalla** [comment]
@mparkitny - can you please clarify which components on the edge device you'd like to restart remotely?

**Comment by mparkitny** [comment]
@veyalla 
prefferably entire device, but restarting runtime would also be useful

**Comment by petermillsacumentive** [comment]
@veyalla – if we were able to restart any module that would be useful too. Many thanks.

**Comment by kpm-at-hfi** [comment]
Any status on this? @myagley mentioned that a solution might be in the works.

FWIW, I'd like to see the ability to invoke a Direct Method on $edgeAgent that could...

* Reboot the device
* Stop|start|restart one or more modules

**Comment by A605052** [comment]
@myagley @veyalla 

Any updates ?

**Comment by veyalla** [comment]
We've added support to restart modules via an edge agent direct method in the [1.0.9 release](https://techcommunity.microsoft.com/t5/internet-of-things/iot-edge-1-0-9/ba-p/1237100), see: https://docs.microsoft.com/azure/iot-edge/how-to-edgeagent-direct-method#restart-module

At this time, there are no plans to implement rebooting the device or other host components via the application framework.

Thanks for your patience, closing this issue!
