### ISSUE TITLE
Return code of the direct method

### ISSUE THREAD

**Issue by icebat83** [Azure/iotedge#609]
Hi,

I would like to ask you about the return code of the direct methods. In your samples you are using System.Net.HttpStatusCode. Is it possible to define and use own status codes or is it required to use HttpStatusCode because it's maybe also processed somehow on the way?

Thank you.

**Comment by myagley** [comment]
The HTTP status code is used by IoT Hub to convey error information. The `status` component of the body of the response is meant to be customized for your specific situation. There is more information here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods#response
