### ISSUE TITLE
docker run --net=host works but not in azure iot edge deployment.template.json

### ISSUE THREAD

**Issue by wiltonkkw** [Azure/iotedge#6128]
## Expected Behavior
I'm using Ubuntu 20.04 as host and deploy an edge module using Azure IoT Edge. The module uses SocketCAN to read/write data via CAN. So the edge module should show the **can0** interface.

## Current Behavior
In the edge module using bash command like: `ip link ls` and `ifconfig`. These commands do not return **can0** or similar device. 

The result of `ip link ls` in edge module
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
71: eth0@if72: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0`

The result of `ifconfig` in edge module
`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
71: eth0@if72: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0`

**In Host**
The partial result of `ip link ls` in host:
`4: can0: <NOARP,UP,LOWER_UP,ECHO> mtu 16 qdisc pfifo_fast state UP mode DEFAULT group default qlen 10
link/can `

The partial result of `ifconfig` in host:
`can0: flags=193<UP,RUNNING,NOARP>  mtu 16
    unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
    RX packets 1244494  bytes 9396052 (9.3 MB)
    RX errors 2  dropped 0  overruns 0  frame 2
    TX packets 0  bytes 0 (0.0 B)
    TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

In edge module, the command `ip link set up can0` returns `Cannot find device "can0"`

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install proper SocketCAN driver in host
2. In the `deployment.template.json`, `modules` section add the following:
`              "createOptions": {
                "NetworkingConfig": { "EndpointsConfig": { "host": {} } },
                "HostConfig": {
                  "NetworkMode": "host",
                  "CapAdd": [ "NET_ADMIN" ],
                  "CapDrop": [ "CHOWN", "SETUID" ]
                }
              }`
3. Add the follow command in `Dockerfile.amd64`
`RUN apt-get install -y net-tools iproute2 can-utils`
4. In edge module, execute bash command `ip link set can0 type can bitrate 500000` and returns `Cannot find device "can0"`

On the other side, if I use docker command with --net=host, it works
## Steps to Reproduce (2)
1. Install proper SocketCAN driver in host
2. In host, execute bash command `docker run --rm -it --name test --net=host ubuntu:20.04
3. `apt-get update && apt-get install -y can-utils iproute2 net-tools`
4. `ip link ls` returns the same list of host
5. `ifconfig` returns the same list of host

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 20.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux container

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.7
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1.10
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1.10
* Docker/Moby [run `docker version`]: 20.10.11.+azure-3

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by nlcamp** [comment]
@wiltonkkw - I'd expect the following createOptions to work:

```
   "createOptions": {
                "NetworkingConfig": {
                    "EndpointsConfig": {
                         "host": {}
                    }
                },
                "HostConfig": {
                    "NetworkMode": "host"
                }
            }
```

Can you share the output of `docker inspect <module-name>` with any sensitive information redacted?

**Comment by wiltonkkw** [comment]
@nlcamp Here is the result of `docker inspect <module-name>`

`[
    {
        "Id": "f8f2cedbf76443bd14a8f50ae72f1a0ab9a7901627eabc04589882375e05f8b9",
        "Created": "2022-02-19T03:06:02.826831267Z",
        "Path": "dotnet",
        "Args": [
            "InzightEdge.dll"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2192984,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2022-02-19T03:06:03.25270328Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:a2b4dfc5514f1fe9da5bd4bc4edf61091bbbe516f4eede11a0a9e50c83af8fa1",
        "ResolvConfPath": "/var/lib/docker/containers/f8f2cedbf76443bd14a8f50ae72f1a0ab9a7901627eabc04589882375e05f8b9/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/f8f2cedbf76443bd14a8f50ae72f1a0ab9a7901627eabc04589882375e05f8b9/hostname",
        "HostsPath": "/var/lib/docker/containers/f8f2cedbf76443bd14a8f50ae72f1a0ab9a7901627eabc04589882375e05f8b9/hosts",
        "LogPath": "/var/lib/docker/containers/f8f2cedbf76443bd14a8f50ae72f1a0ab9a7901627eabc04589882375e05f8b9/f8f2cedbf76443bd14a8f50ae72f1a0ab9a7901627eabc04589882375e05f8b9-json.log",
        "Name": "/inzightedge",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "unconfined",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/home/ubuntu/Videos:/app/dms",
                "/home/ubuntu/Pictures:/app/adas",
                "/home/ubuntu/Documents:/app/db",
                "/dev/v4l:/dev/v4l",
                "/usr/lib/libsdc.so.1:/usr/lib/libsdc.so.1",
                "/usr/lib/x86_64-linux-gnu/libc.so:/usr/lib/x86_64-linux-gnu/libc.so",
                "/lib/modules/5.4.0-96-generic:/lib/modules/5.4.0-96-generic",
                "/var/lib/aziot/edged/mnt/inzightedge.sock:/var/run/iotedge/workload.sock"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "host",
            "Dns": [
                "8.8.8.8",
                "192.168.1.1"
            ],
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "label=disable"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [
                {
                    "PathOnHost": "/dev/ttyUSB0",
                    "PathInContainer": "/dev/ttyUSB0",
                    "CgroupPermissions": "666"
                },
                {
                    "PathOnHost": "/dev/ttyACM0",
                    "PathInContainer": "/dev/ttyACM0",
                    "CgroupPermissions": "666"
                },
                {
                    "PathOnHost": "/dev/video0",
                    "PathInContainer": "/dev/video0",
                    "CgroupPermissions": "666"
                }
            ],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/cc58e19f335a326bc7c1ac986c587fab579657f3a7d1274dabcaf5b33f5c5732-init/diff:/var/lib/docker/overlay2/40402e4d39ea76d5298c8c6b50278ae4f4d112e5c8894a688e070ecd6d40a9c2/diff:/var/lib/docker/overlay2/83521dc108768e44386c79ea3a0cda4b2248bfb722573e7b26ca425bdf2af1d2/diff:/var/lib/docker/overlay2/acdfc1f730e4b463d29d5e85772902d12e4c03a34036f08f4cfb2113e2e2e384/diff:/var/lib/docker/overlay2/3f4cef791f5a63f800547826509cbc5d4a2f96a2f9e76005b56f7bf8c53a2388/diff:/var/lib/docker/overlay2/2d46cd6c630f9e03ef05a60b4ae8bb21c3e3c0b8b2a6d9f976f9b30cd6aeb9b0/diff:/var/lib/docker/overlay2/49c30c44d11caf860ac6c6d3822a7794f1d41e8a4eda235e5d286c1d84e80aca/diff:/var/lib/docker/overlay2/949a410d8904116c0659968c18d9569d589e427a50468819886c99f7eacdea9a/diff:/var/lib/docker/overlay2/86a0483f5c630278b49eea15cdbedae7cf786e960ffe703ef833898aa516bfbd/diff:/var/lib/docker/overlay2/aaa03ce19631f6876cc798a951f600bc1fd09adf7a1bbbeb178895efb4b05e09/diff:/var/lib/docker/overlay2/71982949adbe5c0334003b9f3b29437c8048c1696a317ee6d9a5bc061f952fdf/diff:/var/lib/docker/overlay2/909ca071c1d49cd35f15cb7ea791910bc0ebbb03c80f5277995b4017b57b81c4/diff:/var/lib/docker/overlay2/813eac903a92abbb3a69aca55a0e97565e4044397add7594099c3c91545a278b/diff:/var/lib/docker/overlay2/2ad068708c7d6a3233100a8a7a888aecd58efe52e8284662a6f610c9460b23be/diff:/var/lib/docker/overlay2/100ec5fa6f18fd1d07e6fd161b57fda9217c956faee8af284b72b4006d43a815/diff:/var/lib/docker/overlay2/b2f0690b4ee9783253ee62dcb93866e6b84e23694e6e1bd115561cbb81fe4d02/diff:/var/lib/docker/overlay2/dc0fb3bbb2e40ba10c6077821ae7fe25d46b20e2b92fbcc77f10a0a91a08eded/diff",
                "MergedDir": "/var/lib/docker/overlay2/cc58e19f335a326bc7c1ac986c587fab579657f3a7d1274dabcaf5b33f5c5732/merged",
                "UpperDir": "/var/lib/docker/overlay2/cc58e19f335a326bc7c1ac986c587fab579657f3a7d1274dabcaf5b33f5c5732/diff",
                "WorkDir": "/var/lib/docker/overlay2/cc58e19f335a326bc7c1ac986c587fab579657f3a7d1274dabcaf5b33f5c5732/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/usr/lib/x86_64-linux-gnu/libc.so",
                "Destination": "/usr/lib/x86_64-linux-gnu/libc.so",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/lib/modules/5.4.0-96-generic",
                "Destination": "/lib/modules/5.4.0-96-generic",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/aziot/edged/mnt/inzightedge.sock",
                "Destination": "/var/run/iotedge/workload.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/Videos",
                "Destination": "/app/dms",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/Pictures",
                "Destination": "/app/adas",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/ubuntu/Documents",
                "Destination": "/app/db",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/dev/v4l",
                "Destination": "/dev/v4l",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/usr/lib/libsdc.so.1",
                "Destination": "/usr/lib/libsdc.so.1",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "f8f2cedbf764",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "IOTEDGE_APIVERSION=2019-01-30",
                "IOTEDGE_AUTHSCHEME=sasToken",
                "IOTEDGE_DEVICEID=se50-01",
                "IOTEDGE_GATEWAYHOSTNAME=ubuntu",
                "IOTEDGE_IOTHUBHOSTNAME=inzight-dev.azure-devices.net",
                "IOTEDGE_MODULEGENERATIONID=637804538422742624",
                "IOTEDGE_MODULEID=inzightedge",
                "IOTEDGE_WORKLOADURI=unix:///var/run/iotedge/workload.sock",
                "RuntimeLogLevel=Information",
                "storageContainername=files",
                "storageconnectionstring=DefaultEndpointsProtocol=https;AccountName=XXXX;AccountKey=XXXXXXXXXXX;EndpointSuffix=core.windows.net",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true"
            ],
            "Cmd": null,
            "Image": "inzightdev.azurecr.io/inzightedge:0.0.37-amd64.debug",
            "Volumes": null,
            "WorkingDir": "/app",
            "Entrypoint": [
                "dotnet",
                "InzightEdge.dll"
            ],
            "OnBuild": null,
            "Labels": {
                "net.azure-devices.edge.original-image": "XXXXXXXX",
                "net.azure-devices.edge.owner": "Microsoft.Azure.Devices.Edge.Agent"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "XXXXXXXX",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/6185deb93811",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "azure-iot-edge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "f8f2cedbf764"
                    ],
                    "NetworkID": "XXXXXXX",
                    "EndpointID": "XXXXX",
                    "Gateway": "XXXXXXX",
                    "IPAddress": "XXXXX",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:03",
                    "DriverOpts": null
                }
            }
        }
    }
]`


This is the portion of the module section of **deployment.template.json**
`        "modules": {
          "InzightEdge": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULEDIR<../InzightEdge>.debug}",
              "createOptions": {
                "NetworkingConfig": {
                  "EndpointsConfig": {
                    "host": {}
                  }
                },
                "HostConfig": {
                  "NetworkMode": "host"
                }
              }
            }
          },`

**Comment by nlcamp** [comment]
@wiltonkkw - Sorry for the delay in responding. Are you sure that `docker inspect` output came from the module you deployed using the deployment manifest you pasted above? The reason I ask is because it says `"NetworkMode": "default"` instead of `"NetworkMode": "host"`.

As a sanity check I made a deployment to an ubuntu20.04 Azure VM with iotedge v1.2.7 installed. I configured the SimulatedTemperatureSensor with the following create options:

```
{
    "NetworkingConfig": {
        "EndpointsConfig": {
            "host": {}
        }
    },
    "HostConfig": {
        "NetworkMode": "host"
    }
} 
```

I then confirmed that `sudo docker inspect SimulatedTemperatureSensor` showed `"NetworkMode": "host"`.  I also confirmed that `sudo docker exec SimulatedTemperatureSensor ifconfig` showed that the container reported all the network interfaces from the host. Without the createOptions from above, only the `eth0` and `lo`  network interfaces were returned. Can you please give this a try and let us know what you see?

**Comment by wiltonkkw** [comment]
@nlcamp This is the content of **deployment.template.json**

```
{
  "$schema-template": "2.0.0",
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.1",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {}
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:DEFAULT_RT_IMAGE",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:DEFAULT_RT_IMAGE",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "modules": {
          "InzightEdge": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULEDIR<../InzightEdge>.debug}",
              "createOptions": {
                "NetworkingConfig": {
                  "EndpointsConfig": {
                    "host": {}
                  }
                },
                "HostConfig": {
                  "NetworkMode": "host"
                }
              }
            }
          },
          "SimulatedTemperatureSensor": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
              "createOptions": {}
            }
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.2",
        "routes": {
          "InzightEdgeToIoTHub": "FROM /messages/modules/InzightEdge/outputs/* INTO $upstream",
          "sensorToInzightEdge": "FROM /messages/modules/SimulatedTemperatureSensor/outputs/temperatureOutput INTO BrokeredEndpoint(\"/modules/InzightEdge/inputs/input1\")"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}
```

I am using vs2022 to **Build and Push IoT Edge Modules**, then manual update the azure container to IoT Hub. Is there any place that should put the `"NetworkMode": "host"`?

**Comment by nlcamp** [comment]
@wiltonkkw - Is it possible you are forgetting to create the deployment using the deployment file that gets generated from the template? After selecting **Build and Push IoT Edge Modules** you'll need to follow the steps in the **Deploy modules to device** section of the following doc:

https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module?view=iotedge-2018-06#deploy-modules-to-device

Once you complete the deployment using the steps on the above page, you should see the NetworkMode set to "host" when you run `docker inspect [module-name]`

**Comment by nlcamp** [comment]
Great! Glad that worked.
