### ISSUE TITLE
Could not pull image mcr.microsoft.com/azureiotedge-agent:1.1

### ISSUE THREAD

**Issue by shijiong** [Azure/iotedge#6138]
## Expected Behavior
Pull image from mcr.microsoft.com

## Current Behavior
Can not pull image from mcr.microsoft.com/azureiotedge-agent:1.1

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install IoTEdge successfully on RaspberryPi 4 
2. Create IoTEdge device successfully on Azure Portal
3. Modify device connect string for config.yaml
4. Run "sudo systemctl restart iotedge" on Raspberry Pi terminal

### Output of `iotedge check`

<details>
<summary>Z [INFO] - Checking edge runtime status  
Z [INFO] - Creating and starting edge runtime module edgeAgent  
Z [INFO] - Updating identity for module $edgeAgent  
Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.1...  
Z [WARN] - Could not pull image mcr.microsoft.com/azureiotedge-agent:1.1  
Z [WARN] -         caused by: Get https://mcr.microsoft.com/v2/: net/http: request canceled while waiting for connection  
Z [WARN] - Error in watchdog when checking for edge runtime status:  
Z [WARN] - A module runtime error occurred.  
Z [WARN] -         caused by: Could not pull image mcr.microsoft.com/azureiotedge-agent:1.1  
Z [WARN] -         caused by: Get https://mcr.microsoft.com/v2/: net/http: request canceled while waiting for connection  
~</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS: Raspberry pi 4, Raspbian  
* Architecture: arm64  
* Container OS: Linux containers  

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.9
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 3.0.13+azure

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Additional Information
I think the "https://mcr.microsoft.com/v2/_catalog" is blocked here, since I can not access this on my Microsoft Edge. So, is it possible to pull the azureiotedge-agent manually to the Raspberry Pi?  
Thanks!

**Comment by micahl** [comment]
Hi @shijiong, if `docker pull mcr.microsoft.com/azureiotedge-agent:1.1` fails from the CLI then verify if there are proxy / firewall rules on the device that need to be configured to allow access.  If that is not applicable, then per the [Support documentation](https://github.com/microsoft/containerregistry/blob/main/docs/mcr-endpoints-guidance.md#support) for the Microsoft Container Registry, please contact Microsoft support via https://azure.microsoft.com/support/create-ticket/.
