### ISSUE TITLE
Metrics Collector should not be limited to size of edgeHub packet

### ISSUE THREAD

**Issue by ghormann** [Azure/iotedge#6139]
## Expected Behavior
One should be able to capture  more than 256kb of metrics from  IoT Edge using azureiotedge-metrics-collector,   The metrics collector should be splitting the captured data into multiple packets that fit on edge hub.

## Current Behavior
An error is thrown.
![image](https://user-images.githubusercontent.com/24968726/154692687-2d496edd-c4ad-422d-8bb5-597a978d2961.png)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Deploy a scraping configuration that contains more than 300 metrics to scrape across all the running containers. 
2. Monitor the logs of zureiotedge-metrics-collector and see error thrown.

## Context (Environment)
* Ubuntu 18.04
* Iot Edge 1.2.7
* azureiotedge-metrics-collector 1.0.2
* Using tested edge, but technically doesn't matter

### Output of `iotedge check`

<details>
<summary>Click here</summary>

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
‼ host time is close to reference time - Warning
    Could not query NTP server
√ production readiness: identity certificates expiry - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
33 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.

</details>

### Device Information
* Ubuntu 18.04
* amd64
* IoT Edge 1.2.7

### Runtime Versions
* aziot-edged 1.2.7
* Edge Agent 1.2
* Edge Hub1.2

**Comment by damonbarry** [comment]
In the metrics collector code, I can see that we aren't doing any splitting before we upload to IoT Hub:
https://github.com/Azure/iotedge/blob/2a76f57cb60922a99472b42fe7b4d8659baf114e/edge-modules/azure-monitor/src/IotHubUpload/IotHubUpload.cs#L27-L60

There's also a TODO in the Log Analytics uploader suggesting we need to do something similar there:
https://github.com/Azure/iotedge/blob/2a76f57cb60922a99472b42fe7b4d8659baf114e/edge-modules/azure-monitor/src/FixedSetTableUpload/FixedSetTableUpload.cs#L47

We already have the splitting code in Edge Agent for uploading RQT as IoT Hub messages; we could do the same thing in the metrics collector:
https://github.com/Azure/iotedge/blob/2a76f57cb60922a99472b42fe7b4d8659baf114e/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/publisher/EdgeRuntimeDiagnosticsUpload.cs#L35

**Comment by damonbarry** [comment]
@ghormann Are you using the default settings in the Metrics Collector? If so, metrics are only being sent to IoT Hub once per _day_. What you're reporting sounds like something we need to fix, but as a temporary workaround you could reduce the time between sends by adding the "IotHubConnectFrequency" environment variable to the metrics collector in your deployment.
https://github.com/Azure/iotedge/blob/2a76f57cb60922a99472b42fe7b4d8659baf114e/edge-modules/azure-monitor/src/README.md?plain=1#L63-L67

**Comment by damonbarry** [comment]
@ghormann Scratch what I said about "IotHubConnectFrequency". I didn't read carefully enough...that variable controls something else.

**Comment by ghormann** [comment]
@damonbarry  We don't do anything "as default".  :-)   We send metrics from edge every 60 seconds.   We have a custom function listening to eventhub on IoTEdge processing the messages so that variable doesn't apply.   We don't compress the metrics and I'm not 100% sure why not. This is something I need to look into as an option our end. 

                            "ScrapeFrequencyInSecs": {
                                "value": "60"
                            },
                            "CompressForUpload": {
                                "value": "false"
                            }
                        },

**Comment by damonbarry** [comment]
Thinking out loud...in order to chunk metrics, I suspect we'd have to
1. Serialize the full metrics payload to JSON (we're already doing this)
2. Compress the JSON payload if compression is enabled (we're already doing this)
3. If the resulting payload is too large
  a. Discard the payload
  b. Split the original payload
  c. Sent smaller payloads back to step 1
4. Send the payload(s)

This means you would pay a performance penalty for gathering lots of metrics and/or send metrics less frequently--more so if you have compression enabled.

@ghormann What do you think about the tradeoffs here?

**Comment by nlcamp** [comment]
@ghormann  - While we work out the longer-term, more robust solution on our end, can you enable the `CompressForUpload` option as a workaround and let us know if that unblocks you for now?

**Comment by ghormann** [comment]
> @ghormann - While we work out the longer-term, more robust solution on our end, can you enable the `CompressForUpload` option as a workaround and let us know if that unblocks you for now?

@nlcamp  Yes.   This change has already been deployed to our development environment.  Initial test are positive.

**Comment by nlcamp** [comment]
Ok, good to hear. I'll close this issue.

We plan to provide a more robust solution in a future release. However, feel free to submit this feature request at https://aka.ms/iotedge-suggestion
