### ISSUE TITLE
Could not start module edgeAgent after reboot on Bullseye OS (OCI runtime create failed)

### ISSUE THREAD

**Issue by AlanTuring1988** [Azure/iotedge#6153]
Hi all,

I installed iotedge version 1.2.7 on my Raspberry Pi4. 

I installed as OS the bullseyes for arm32. My deployment manifest contains only the containers edgeHub and edgeAgent. First installation is ok and these containers are up&running.

When I reboot the board, these containers are in failed status. From the iotedge system logs the edgeAgent module does not start because there is an error related to the creation of the **OCI runtime**.

![image](https://user-images.githubusercontent.com/37872833/155301493-1a98705d-cacb-4576-bf20-e671d49d547a.png)

What can it depend on? What could i do to fix it?
To fix the problem temporarily I had to remove the containers and restart the iotedge system every reboot.

The _iotedge check_ not identified any issue
![image](https://user-images.githubusercontent.com/37872833/155301940-d2bc4ce9-79a9-4ffe-9be0-07ef2b2bd0d6.png)

Below is the installed _Deployment Manifest_ and details about docker and _Operating System_.

**Device Information**
Raspberry Pi 4
Operation System:
- Static hostname: raspberrypi
- Icon name: computer
- Machine ID: ce513f1a44ff4c9dbd382eb66e08c51e
- Boot ID: 0498012d1f6e43a9b6d4c1fc159f3d72
- Operating System: Raspbian GNU/Linux 11 (bullseye)
- Kernel: Linux 5.10.92-v7l+
- Architecture: arm

**Runtime Versions**
 **Docker Version**
> Client:

- Version:           	3.0.13+azure
- API version:       1.40
- Go version:	go1.13.11
- Git commit:       dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
- Built:             	Thu May 28 20:41:25 2020
- OS/Arch:           	linux/arm
- Experimental:   false

> Server-Engine:

- Version:          3.0.13+azure
- API version:      1.40 (minimum version 1.12)
- Go version:       go1.13.11
- Git commit:       77e06fda0c
- Built:            	Mon Jun  1 20:22:16 2020
- OS/Arch:        	linux/arm
- Experimental:   false

> Server-Containerd:

- Version:	v1.2.13
- GitCommit:	7ad184331fa3e55e52b890ea95e65ba581ae3429

> Server-Runc:

- Version:          	1.0.0-rc10
- GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd

> Server-docker-init:

- Version:	0.18.0
- GitCommit	fec3683

**Deployment Manifest**
`{
    "modulesContent": {
        "$edgeAgent": {
            "properties.desired": {
                "modules": {},
                "runtime": {
                    "settings": {
                        "minDockerVersion": "v1.25"
                    },
                    "type": "docker"
                },
                "schemaVersion": "1.1",
                "systemModules": {
                    "edgeAgent": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-agent:1.1",
                            "createOptions": ""
                        },
                        "type": "docker"
                    },
                    "edgeHub": {
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.1",
                            "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"443/tcp\":[{\"HostPort\":\"443\"}],\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}]}}}"
                        },
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always"
                    }
                }
            }
        },
        "$edgeHub": {
            "properties.desired": {
                "routes": {},
                "schemaVersion": "1.1",
                "storeAndForwardConfiguration": {
                    "timeToLiveSecs": 7200
                }
            }
        }
    }
}`

The following the iotedge system logs:

_Feb 23 10:04:14 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:14Z [INFO] - Checking edge runtime status
Feb 23 10:04:14 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:14Z [INFO] - Edge runtime status is failed, starting module now...
Feb 23 10:04:14 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:14Z [INFO] - Starting module edgeAgent...
Feb 23 10:04:14 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:14Z [INFO] - Starting new listener for module edgeAgent
Feb 23 10:04:14 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:14Z [INFO] - Listener  edgeAgent already started, removing old listener
Feb 23 10:04:14 raspberrypi aziot-certd[1864]: 2022-02-23T10:04:14Z [INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "2f72756e2f617a696f742f63657274642e736f636b:0"}
Feb 23 10:04:14 raspberrypi aziot-certd[1864]: 2022-02-23T10:04:14Z [INFO] - --> 200 {"content-type": "application/json"}
Feb 23 10:04:14 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:14Z [INFO] - Listening on unix:///var/lib/aziot/edged/mnt/edgeAgent.sock with 1 thread for workload API.
**Feb 23 10:04:15 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:15Z [WARN] - Could not start module edgeAgent
Feb 23 10:04:15 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:15Z [WARN] -         caused by: OCI runtime create failed: container with id exists: b7b9f5cd6b1ea4341668b867a75d6784df8d0d01314cf33394d087241e3f5831: unknown
Feb 23 10:04:15 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:15Z [WARN] - Error in watchdog when checking for edge runtime status:**
Feb 23 10:04:15 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:15Z [WARN] - A module runtime error occurred.
Feb 23 10:04:15 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:15Z [WARN] -         caused by: Could not start module edgeAgent
Feb 23 10:04:15 raspberrypi aziot-edged[1829]: 2022-02-23T10:04:15Z [WARN] -         caused by: OCI runtime create failed: container with id exists: b7b9f5cd6b1ea4341668b867a75d6784df8d0d01314cf33394d087241e3f5831: unknown_

I wait for your feedback.
Thanks and Br

**Comment by lfitchett** [comment]
HI @AlanTuring1988,

It looks like the edgeAgent container isn't being properly recognized after a hard reboot. I'm not sure how to fix this problem. Unfortunately, Bullseye isn;t one of our [supported operating systems](https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2020-11), so I won't be able to provide debugging assistance. Can you please try on Stretch for arm32 or ubuntu for arm64? 

If the problem is replicable on a tier 1 OS I will be happy to help out.

**Comment by AlanTuring1988** [comment]
Hi @lfitchett ,

I will try with Stretch or Buster for arm32.

Thanks for your time.

Br.

**Comment by AlanTuring1988** [comment]
Hi @lfitchett ,
I conferm that this issue is not present with the OS Buster

**Comment by AlanTuring1988** [comment]
Bullseye isn't one of our [supported operating systems](https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2020-11),
