### ISSUE TITLE
Cannot get logs from any container using normal methods

### ISSUE THREAD

**Issue by ZachM05** [Azure/iotedge#6157]
## Expected Behavior
Tell us what should happen
Entering `iotedge logs [MODULE]` should provide some output from the running container
## Current Behavior
Tell us what happens instead of the expected behavior
```
moxa@Moxa:~$ docker logs edgeHub
Error response from daemon: configured logging driver does not support reading
```
## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Running Debian 9 Stretch, install moby-engine and iotedge 1.1
2. Configure connection string
3. Add `{"log-driver": "journald"}` to `/etc/docker/daemon.json`
4. Try and retrieve logs from any edge container

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
‼ host time is close to real time - Warning
    Could not query NTP server
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2022-05-25 14:53:30 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Debian GNU/Linux 9 (stretch)
* Architecture [e.g. amd64, arm32, arm64]: arm32v7
* Container OS [e.g. Linux containers, Windows containers]: linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.9
* Edge Agent [image tag (e.g. 1.0.0)]: 1.1
* Edge Hub [image tag (e.g. 1.0.0)]: 1.1
* Docker/Moby [run `docker version`]: 3.0.13+azure, build dd360c7c0de8d9132a3965db6a59d3ae74f43ba7

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.
I cannot attach logs as I can not get logs from edgeHub or edgeAgent. I am using company proxy, which affects my setup steps but shouldnt impact log drivers.

**Comment by lfitchett** [comment]
Hi @ZachM05,

At first glance, this doesn't seem like an edge specific issue. You are using `docker logs`, which isn't edge specific. Do both `docker logs` and `iotedge logs` fail? Have you tried running docker logs as sudo? 

Unfortunately, I might not be able to provide much more support, since Debian 9 Stretch isn't one of our [tier 1 os's](https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2020-11), and this seems like an operating system specific issue.

**Comment by ZachM05** [comment]
Hey @lfitchett!

Great questions, here's the output: 

```
moxa@Moxa:~$ docker ps
CONTAINER ID        IMAGE                                      COMMAND                   CREATED             STATUS              PORTS                                                                  NAMES
4aff06381b09        mcr.microsoft.com/azureiotedge-hub:1.1     "/bin/sh -c 'echo \"$…"   40 hours ago        Up 18 hours         0.0.0.0:443->443/tcp, 0.0.0.0:5671->5671/tcp, 0.0.0.0:8883->8883/tcp   edgeHub
33aea63d960a        mcr.microsoft.com/azureiotedge-agent:1.1   "/bin/sh -c 'exec /a…"    40 hours ago        Up 18 hours                                                                                edgeAgent
moxa@Moxa:~$ docker logs edgeHub
Error response from daemon: configured logging driver does not support reading
moxa@Moxa:~$ iotedge logs edgeHub
A module runtime error occurred

moxa@Moxa:~$ iotedge list
NAME             STATUS           DESCRIPTION           CONFIG
edgeAgent        running          Up 17 hours           mcr.microsoft.com/azureiotedge-agent:1.1
edgeHub          running          Up 17 hours           mcr.microsoft.com/azureiotedge-hub:1.1
moxa@Moxa:~$ sudo docker logs edgeHub
Error response from daemon: configured logging driver does not support reading
moxa@Moxa:~$ sudo iotedge logs edgeHub
A module runtime error occurred
```

The containers are running, but both iotedge and docker logs receive no value. I am able to get logs using this: 
```
moxa@Moxa:~$ sudo journalctl CONTAINER_NAME=edgeHub
-- Logs begin at Fri 2022-02-25 05:59:03 UTC, end at Fri 2022-02-25 23:36:26 UTC. --
Feb 25 05:59:47 Moxa 4aff06381b09[608]: 2022-02-25 05:59:47 +00:00 Starting Edge Hub
Feb 25 05:59:48 Moxa 4aff06381b09[608]: 2022-02-25 05:59:48.610 +00:00 Edge Hub Main()
...
```

Which is a good workaround, just not how it works for me on some other device types, so I wasn't sure whether or not I could get some help with it.

I understand if you can't do much cause of the OS, but any help would be appreciated!

**Comment by cpuguy83** [comment]
For the version of moby you have installed (3.0.x), this is a static build.
Static builds of moby do not support reading from systemd.

ref: moby journald logger build tags: https://github.com/moby/moby/blob/c78f6963a1c0234cdfb296f479c9bf98adffe31e/daemon/logger/journald/read.go#L1-L2

**Comment by cpuguy83** [comment]
As a note, these `3.0.x` builds are just a totally custom versioning scheme.
All of those 3.0.x builds are statically linked but otherwise are within the docker 19.03 release branch.
We also have versions of moby that follow the 19.03.x (and 20.10.x) version scheme, those are dynamically linked and _should_ work here (I haven't explicitly tested arm builds with journald like this, but it should work).
