### ISSUE TITLE
Inter-module direct method payload size is limited to 8KiB instead of 128KiB

### ISSUE THREAD

**Issue by yfakariya** [Azure/iotedge#616]
According to [the document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods#method-lifecycle), max payload size of all direct methods are 128KiB. In fact, module method invocation from IoT Hub accepts about 100KiB payload. However, if the method invoked from IoT Edge modules, its max limit is set to 8KB. 

I think it should be 128KiB max as IoT Hub initiated direct method. 

## Expected Behavior

* Inter module method invocation accepts max 128KiB payload as document says.

## Current Behavior

* Inter module method invocation limits its payload size up to 8KiB.

## Steps to Reproduce

1. Create 2 modules as you like.
2. From one module, invoke module method to another module with a over 8KiB but under 128KiB payload.
3. `ArgumentException` is thrown.

### Device (Host) Operating System

Ubuntsu Server 18.04, but it should not be related to OS.

### Architecture

x64, but it should be happen in arm32.

### Container Operating System

Linux, but is should be occured in Windows.

#### iotedged

1.0.4

#### Edge Agent

1.0.4

#### Edge Hub

1.0.4

## Logs

This is a log in C# module which invoked direct method to another module:

```
System.ArgumentException: "Payload should not be greater than 8192 bytes."
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isSuccessful, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.HttpClientHelper.PostAsync[T1,T2](Uri requestUri, T1 entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.ModuleClient.InvokeMethodAsync(Uri uri, MethodRequest methodRequest, CancellationToken cancellationToken)
```
   
## Additional Information

I found that inter module method invocation limit in [EdgeHub code](https://github.com/Azure/iotedge/blob/52ef77db24126bf473265fc09c53d35290a2dd6b/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/MethodRequestValidator.cs#L14), it validates the palyload size with 8KiB.

**Comment by varunpuranik** [comment]
@yfakariya - Thanks for the issue. You are right, this needs to be updated. We will fix it and it will be available in the next release.
