### ISSUE TITLE
azure-iot-edge.setupIotedgehubdev Error: getaddrinfo ENOTFOUND XXXXXX.azure-devices.net

### ISSUE THREAD

**Issue by CarlosGomesMarel** [Azure/iotedge#6174]
## Expected Behavior
Setup Iot Edge Simulator is failing from Visual Studio Code.  The previous IOT Edge is no longer available.  Now I cannot replace it.

**How do I setup a new IOT Edge device if the previously IOT Edge device no longer exists?**

`Error: getaddrinfo ENOTFOUND xxxxxx.azure-devices.net`

![image](https://user-images.githubusercontent.com/58279569/156656675-1b2745af-f525-4082-9e43-366437d1722a.png)

## Current Behavior
`Error: getaddrinfo ENOTFOUND xxxxxx.azure-devices.net`

## Steps to Reproduce
Run the Azure Iot Edge: Setup Iot Edge Simulator step.

## Context (Environment)

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by marianan** [comment]
@CarlosGomesMarel thank you for reporting this issue. To get a baseline whether the issue is related to environment setup or a specific tool, could you follow the steps in this tutorial below and let us know if you still experience the same failures? If yes, please share which step and the exact versions of your host OS, VSCode Azure IoT Edge extension and iotedgehubdev tool. https://docs.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-2020-11

**Comment by marianan** [comment]
It appears that the IoT Hub that was initially associated is no longer accessible. You should be able to see the IoT Hub in the Azure IoT Hub Explorer window (bottom left in VSCode), then setup the simulator with any of the devices that are available under the specific IoT Hub. See screenshot below. Please feel free to log a new issue if you have questions or run into issues.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/10135329/158645766-380df97d-4bb7-4951-940c-50a5e56eaaef.png">
