### ISSUE TITLE
[Could not start module edgeAgent]network azure-iot-edge not found

### ISSUE THREAD

**Issue by amit12cool** [Azure/iotedge#6178]
## Expected Behavior
EdgeAgent should be installed 

## Current Behavior
EdgeAgent is throwing errors

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Follow steps in docs for installing Azure IoT Edge as transparent gateway on Ubuntu 18.04 amd64

### Output of `iotedge check`
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ production readiness: identity certificates expiry - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
24 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
7 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: 
* amd64
* Container OS [e.g. Linux containers, Windows containers]: 
Ubuntu Virtual machine

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.8
* Edge Agent [image tag (e.g. 1.0.0)]: NA
* Edge Hub [image tag (e.g. 1.0.0)]: NA
* Docker/Moby [run `docker version`]: 
Version:           20.10.11+azure-3
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        dea9396e184290f638ea873c76db7c80efd5a1d2
 Built:             Wed Nov 17 23:49:46 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [INFO] - Checking edge runtime status
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [INFO] - Edge runtime status is stopped, starting module now...
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [INFO] - Starting module edgeAgent...
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [INFO] - Starting new listener for module edgeAgent
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [INFO] - Listener  edgeAgent already started, removing old listener
Mar 07 20:25:19 amit-VirtualBox aziot-certd[27253]: 2022-03-07T14:55:19Z [INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "2f72756e2f617a696f742f63657274642e736f636b:0"}
Mar 07 20:25:19 amit-VirtualBox aziot-certd[27253]: 2022-03-07T14:55:19Z [INFO] - --> 200 {"content-type": "application/json"}
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [INFO] - Listening on unix:///var/lib/aziot/edged/mnt/edgeAgent.sock with 1 thread for workload API.
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [WARN] - Could not start module edgeAgent
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [WARN] -         caused by: network azure-iot-edge not found
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [WARN] - Error in watchdog when checking for edge runtime status:
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [WARN] - A module runtime error occurred.
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [WARN] -         caused by: Could not start module edgeAgent
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [WARN] -         caused by: network azure-iot-edge not found
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [INFO] - Checking edge runtime status
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [INFO] - Edge runtime status is stopped, starting module now...
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [INFO] - Starting module edgeAgent...
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [INFO] - Starting new listener for module edgeAgent
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [INFO] - Listener  edgeAgent already started, removing old listener
Mar 07 20:26:19 amit-VirtualBox aziot-certd[27253]: 2022-03-07T14:56:19Z [INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "2f72756e2f617a696f742f63657274642e736f636b:0"}
Mar 07 20:26:19 amit-VirtualBox aziot-certd[27253]: 2022-03-07T14:56:19Z [INFO] - --> 200 {"content-type": "application/json"}
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [INFO] - Listening on unix:///var/lib/aziot/edged/mnt/edgeAgent.sock with 1 thread for workload API.
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [WARN] - Could not start module edgeAgent
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [WARN] -         caused by: network azure-iot-edge not found
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [WARN] - Error in watchdog when checking for edge runtime status:
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [WARN] - A module runtime error occurred.
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [WARN] -         caused by: Could not start module edgeAgent
Mar 07 20:26:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:56:19Z [WARN] -         caused by: network azure-iot-edge not found

**Comment by ancaantochi** [comment]
@amit12cool , is this a clean install on the device or was there a previous install? from the logs it seems that edgeAgent container was already there, do you have any logs from when daemon started? 
Mar 07 20:25:19 amit-VirtualBox aziot-edged[27226]: 2022-03-07T14:55:19Z [INFO] - Edge runtime status is stopped, starting module now...

**Comment by amit12cool** [comment]
@ancaantochi Indeed. I did a fresh install of my certs and the error was gone. Thanks
