### ISSUE TITLE
[metricsCollector] No change in docker image code regardless of tag

### ISSUE THREAD

**Issue by beandrad** [Azure/iotedge#6179]
## Expected Behavior
The code in the docker image mcr.microsoft.com/azureiotedge-metrics-collector with tag 1.0.4 should be the code in  [edge-modules/MetricsCollector](https://github.com/Azure/iotedge/tree/metrics-collector-1.0.4/edge-modules/MetricsCollector); same goes for version 1.0.3.

## Current Behavior
It seems the image has a code different from the one in [edge-modules/MetricsCollector](https://github.com/Azure/iotedge/tree/main/edge-modules/MetricsCollector); see images below. I couldn't find in the code in the repo where "Version - 1.0.2" is printed; in fact, when I run it in local that doesn't get printed for any git repo tags (I tried with metrics-collector-1.0.4 and metrics-collector-1.0.3).

![Screenshot 2022-03-07 at 14 59 05](https://user-images.githubusercontent.com/67916678/157059717-4a7c9614-9bc0-4af6-91df-900ee87e1511.png)

![Screenshot 2022-03-07 at 14 57 27](https://user-images.githubusercontent.com/67916678/157059724-757e82b2-07be-4051-ac4b-36a89bbb62ab.png)

## Steps to Reproduce
docker run mcr.microsoft.com/azureiotedge-metrics-collector:1.0.4

**Comment by brotherneeru** [comment]
Thank you for calling this out. There's a version info file that should be updated, but unfortunately we haven't recently because of  slight oversight. This probably wont be fixed in 1.04, but we will be fixing this in later versions.
