### ISSUE TITLE
.Net SDK support for Edge Device Creation

### ISSUE THREAD

**Issue by codesmon** [Azure/iotedge#62]
I don’t seem to be able to find support in the latest .Net SDK for creating an Edge device programmatically, only via the portal, CLI or VS Code. 

Is this going to be a supported use case at some point?

**Comment by dsajanice** [comment]
Hi @codesmon the .Net SDK has support for creating a device with Edge capability. The Device class (https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/service/src/Device.cs) contains a Capabilities property that in turn contains a flag to set Edge capability. When creating a device in the service, please set the IotEdge flag (https://github.com/Azure/azure-iot-sdk-csharp/blob/master/shared/src/DeviceCapabilities.cs) to true to create an Edge device.

**Comment by myagley** [comment]
I am closing this as @dsajanice pointed out how to achieve this with service SDK. Please feel free to reopen if you have any more questions.
