### ISSUE TITLE
Custom Resource Definition that supports new Kubernetes API apiextensions.k8s.io/v1 

### ISSUE THREAD

**Issue by angudadevops** [Azure/iotedge#6212]
## Expected Behavior
edge-kubernetes CRD should support new Kubernetes API apiextensions.k8s.io/v1 

## Current Behavior
Whenever tried to deploy on cluster that is more kubernetes 1.22, failed to install as Kubernetes apiextensions.k8s.io/v1beta1 API is deprecated 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. create a Kubernetes cluster with 1.22.5 
2. install edge-kubernetes helm chart from here (https://github.com/Azure/iotedge/tree/release/1.1-k8s-preview/kubernetes)
3. it will failed to install as no supported CRD
4.

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Ubuntu 20.04
* Architecture [e.g. amd64, arm32, arm64]:  amd64
* Container OS [e.g. Linux containers, Windows containers]:  Linux Contianers 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 0.1.0-beta15
* Edge Agent [image tag (e.g. 1.0.0)]:  0.1.0-beta15
* Edge Hub [image tag (e.g. 1.0.0)]: 0.1.0-beta15
* Docker/Moby [run `docker version`]:  contaainerd 1.4.9

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
The CustomResourceDefinition "edgedeployments.microsoft.azure.devices.edge" is invalid: 
* spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
* spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by yophilav** [comment]
Hello @angudadevops, 

Thank you for the report. We have assessed the effort for this, but customer demand hasn't made this a high priority fix. Please feel free to make a comment heard at "User Voice" (https://aka.ms/iotedge-suggestion). 

Have a wonderful day,
Bear

**Comment by angudadevops** [comment]
@yophilav I don't see that effort on suggestions, please share the right topic. and what is the best way to resolve this ?

**Comment by angudadevops** [comment]
@ancaantochi can you help me with above query ?
