### ISSUE TITLE
Timeout exception while initializing module client

### ISSUE THREAD

**Issue by niravjprabtani** [Azure/iotedge#6229]
## Expected Behavior
Module client should get initialized without any exception after reboot

## Current Behavior
We are getting a timeout exception while initializing module client after a reboot of a gateway.

## Steps to Reproduce
This is very rare but we have seen it in a production environment where we have rebooted one of the devices and modules stopped working. We are raising this bug as a preventive measure so we don't face the same error for any other sites.

### Device Information
Host OS [Windows 10 version 1809]:
Container OS [Windows containers]:

### Runtime Versions
* aziot-edged [edgeRuntime `1.0.10.4`]: 
* Edge Agent [image tag (e.g. 1.1.10)]: 
* Edge Hub [image tag (e.g.  1.1.10)]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Additional Information
```
The operation did not complete within the allocated time 00:01:00 for object sender27.\r\n ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object sender27.\r\n   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception excep
tion)\r\n   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)\r\n   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)\r\n   at System.Threading.Tasks.
TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Azure.Devices.Client.Transport.A
mqpIoT.AmqpIoTSession.OpenSendingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String CorrelationId, TimeSpan timeout)\r\n
   --- End of inner exception stack trace ---\r\n   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenSendingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String devi
ceTemplate, String moduleTemplate, String linkSuffix, String CorrelationId, TimeSpan timeout)\r\n   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenTelemetrySenderLinkAsync(DeviceIdentity deviceIdentity, TimeSpan timeout)\r\n   at Microsoft.Azure.D
evices.Client.Transport.AmqpIoT.AmqpUnit.EnsureSessionAsync(TimeSpan timeout)\r\n   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpUnit.OpenAsync(TimeSpan timeout)\r\n   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.OpenAsync(Cancellation
Token cancellationToken)\r\n   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass28_0.<<ExecuteWithErrorHan
dlingAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)\r\n   at Microsoft.Azure.Devices.
Client.Transport.RetryDelegatingHandler.<>c__DisplayClass39_0.<<OpenInternalAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(
CancellationToken cancellationToken)\r\n   at Microsoft.Azure.Devices.Client.InternalClient.OpenAsync()\r\n   --- End of inner exception stack trace
```
We are going to implement the retry mechanism from our end but we just wanted to know the probable root causes for the same to understand all possible scenarios where it can be failed

**Comment by niravjprabtani** [comment]
> @niravjprabtani Thank you for the report! Is upgrading your devices to the latest IoTEdge version (1.1.11) a viable option here? I see that you're currently using the version 1.0.10.4 which is quite old. We have done multiple bug fixes related to module connectivity since the release.

Thanks for the reply,

We are using edgeAgent version 1.1.10 but iotedge is running on an older version, We have started using the latest only for new gateways. We will upgrade the existing older version of IoT edge as well.

**Comment by yophilav** [comment]
@niravjprabtani 
Thank you for the response! 
Let's keep monitoring the behavior for a few days. Please let us know if the problem still persists with the latest bits.

**Comment by yophilav** [comment]
Hello @niravjprabtani ,
Just checking in if the issue has been resolved. 
If so, is it alright for me to close the issue? 
Thank you!
