### ISSUE TITLE
production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error

### ISSUE THREAD

**Issue by murali513** [Azure/iotedge#6235]
Facing this issue on RSB 3720, please let me know what will be the reason for this.
deployed Azure IoT Edge 1.2 version on Device
Trying to deployed modules (edgeAgent & edgeHub) version 1.1 from cloud IoT Hub

### production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
× container on the default network can connect to upstream  AMQP port - Error
    Container on the default network could not connect to iothubmp.azure-devices.net:5671

**Environment:**
![image](https://user-images.githubusercontent.com/24382172/160073551-acd1bc75-c7b1-4fc9-bc4d-a9acd67f976c.png)
[errorondeployingiotedge.txt](https://github.com/Azure/iotedge/files/8348310/errorondeployingiotedge.txt)

**Comment by yophilav** [comment]
@murali513 
Without much log, I can't really investigate on the issue. 
The log 
```
Could not check current state of edgeHub container
    caused by: docker returned exit code: 1, stderr = Error: No such object: edgeHub
```
is telling me that edgeHub is not up and running. However, I can't investigate on why edgeHub is not running. 

Could you please get logs from EdgeAgent and EdgeHub and upload it please?

Note: These logs will contain (secrets) identification, so you may want to redact those out first before uploading them here.  If you don't feel comfortable uploading them here, please feel free to open a support ticket so we can logs exchange.

**Comment by murali513** [comment]
I am sharing here IoT Edge System Logs
[systemlog.txt](https://github.com/Azure/iotedge/files/8368635/systemlog.txt)
:

**Comment by yophilav** [comment]
@murali513 
Thank you for the logs!  The behavior I'm seeing from the logs looks very strange. 
Please correct me if I'm wrong, currently you're doing: 
1. Running iotedge 1.2 
2. Deploy edgeHub 1.1 & edgeAgent 1.1
on the device, correct? 

This is not exactly our recommended configuration. We recommend the customer using the same iotedge (edge runtime) to have the same major version as image modules (edgeAgent & edgeHub).
I'd suggest you try either 
A. Reinstall iotedge to have the same version 1.1 (LTS) as the images
OR
B. Upgrade the images to be version 1.2

**Comment by yophilav** [comment]
Close the issue due to inactivity

**Comment by swamil30** [comment]
Facing the same issue discussed above in Windows System, edgeHub is failing to run again and again. Please suggest some solution.
