### ISSUE TITLE
[Question] how to setup IoT Edge to use TrustZone

### ISSUE THREAD

**Issue by manszigher** [Azure/iotedge#6244]
Hi,

We have an arm system with Trustzone where we have a closed source system from QualComm called QSEE running. We are unsure on how IoT Edge would interface with our secure world in the TrustZone. I have found some indication about #PKCS11 here https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-security-manager?view=iotedge-2020-11#hardware-security-module. But it is not clear to me how to configure the IoT Edge to use a #PKCS11. Is IoT Edge making use of openssl and we should setup openssl to use the #PKCS11 interface to communicate with the TrustZone or do we need to configure IoT Edge to load the #PKCS11 engine? Any pointers on this topic would be really appreciated. Or maybe this is the wrong forum for this question then please point me to right direction.

Thanks

**Comment by manszigher** [comment]
I found this which seems to be what we are looking for https://github.com/Azure/iotedge/tree/1.0.10/edgelet/hsm-sys/azure-iot-hsm-c but this is for an older version. But would like to find something like this covering how to get the security module to interact with our TrustZone Application.

**Comment by manszigher** [comment]
I also found this https://github.com/Azure/iotedge/blob/main/edgelet/contrib/README.md#libiothsm-std but the link which is referring to libiothsm-std is broken.

**Comment by manszigher** [comment]
I found some references to pkcs11 that points to https://azure.github.io/iot-identity-service/ which the Iot Edge seems to depend on.

**Comment by huguesBouvier** [comment]
Which version of edge runtime are you using?
IS is present starting version 1.2 
 if trustzone is using pcks11 you should be able to configure IS to use it.

**Comment by manszigher** [comment]
Thanks for your reply we are currently using 1.0.10 but only for testing things out on our device and that was the fastest thing to get up and running. But I think we want to use 1.1 since that is LTS. I have found some more information but I am still missing some kind of explanation on how to actually configure IoT Edge to use TPM or some other HSM solution. Do you know where I can maybe find some documentation covering how to do that?

**Comment by manszigher** [comment]
For anyone else looking into this here are some links that I have found about the subject

https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-security-manager?view=iotedge-2018-06&preserve-view=true
https://github.com/Azure/iot-identity-service/blob/main/docs-dev/openssl-engine-internals.md
https://azure.github.io/iot-identity-service/pkcs11/
https://azure.github.io/iot-identity-service/

**Comment by huguesBouvier** [comment]
"I have found some more information but I am still missing some kind of explanation on how to actually configure IoT Edge to use TPM or some other HSM solution"=>You found it:https://azure.github.io/iot-identity-service/pkcs11/ "Protecting keys via an HSM or TPM"
But you will have to use 1.2 not 1.1.

**Comment by jlian** [comment]
We should port the document over to docs.microsoft.com. In the meantime @manszigher if you have other questions, please reopen the issue
