### ISSUE TITLE
Custom topic structure

### ISSUE THREAD

**Issue by madstt** [Azure/iotedge#6245]
Is it possible to somehow create a custom MQTT topic structure like `<tenant>/<dataType>`? This means no prefixed '/' nor any mention of `messages`, `devices` etc, just a custom topic structure.

**Comment by huguesBouvier** [comment]
Yes you should be able to.
Please refer to this:
There is this doc: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11#publish-and-subscribe-on-user-defined-topics
Hope this help.

**Comment by jlian** [comment]
@madstt hopefully that answers your question. If you need additional help, please reopen the issue

**Comment by madstt** [comment]
One quick question. I've tried using the `mqttBroker` preview feature and this [sample](https://github.com/Azure-Samples/iot-hub-mqtt-5-preview-samples-csharp/blob/main/src/Program.cs) without luck. If I do not use the `mqttBroker` preview feature and this [sample](https://github.com/Azure/iotedge/blob/main/samples/dotnet/EdgeDownstreamDevice/Program.cs) it works fine. 

So my question is, can I use the `DeviceClient` with the preview feature or am I forced to use the `MQTTClient` from the `MQTTnet` library?

**Comment by huguesBouvier** [comment]
I am sorry I don't understand the question can you specify:
which:  DeviceClient and MQTTClient you are refering too?

But preview MQTT works with version 1.2. Check that you have the latest version, it could be the issue.

**Comment by madstt** [comment]
I am running version 1.2 of the IoT Edge. 

So I have a client using the `DeviceClient` which I can use to connect to the IoT Edge version 1.2, but with this client, I can't send to a custom topic, the topic has to have the `/messages/`-format. Therefore, I added

`      "mqttBroker": {
        "authorizations": [
          {
            "identities": [
              "{{iot:identity}}"
            ],
            "allow": [
              {
                "operations": [
                  "mqtt:connect"
                ]
              }
            ]
          },
          {
            "identities": [
              "{{iot:identity}}"
            ],
            "allow": [
              {
                "operations": [
                  "mqtt:publish",
                  "mqtt:subscribe"
                ],
                "resources": [
                  "test_topic"
                ]
              }
            ]
          }
        ]
      }
`
Then I can't connect, I get a `CONNECT failed: RefusedNotAuthorized` error. Is this due to the client not being authorized? 

Therefore, I'm trying a different sample that uses the `MQTTnet` client, but does it matter whether I'm using the `MqttClient` or the `DeviceClient`?

**Comment by huguesBouvier** [comment]
Yes, it doesn't matter. Any MQTT client will do. I personally used Paho/Mosquito.

**Comment by madstt** [comment]
Ok, I'll look check that out.

But is it correct that adding the `mqttBroker` part would require different authorization of the devices? I mean the `"identities": [ "{{iot:identity}}" ]` looks like some authorization piece.

**Comment by madstt** [comment]
Ok, I tried the Paho/mosquito client. I'm using x509 certs, so I provided them in the command line, but I get the following error in the `edgeHub` log:

`<7> 2022-04-08 18:35:15.031 +00:00 [DBG] [server{{listener}}: mqtt_broker::transport] - accepted connection from client
<4> 2022-04-08 18:35:15.047 +00:00 [WRN] [mqtt_broker::server] - failed to process connection error=An error occurred decoding a packet. could not identify packet with type 0x10, flags 0x6 and remaining length 3 Caused by: could not identify packet with type 0x10, flags 0x6 and remaining length 3`

What am I missing here?

**Comment by huguesBouvier** [comment]
From this, it looks more like an issue in setting up paho. 
I was using the snipper here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#tlsssl-configuration

**Comment by madstt** [comment]
Ok, one step further, now I'm getting this error in the log:

`<7> 2022-04-08 19:42:56.083 +00:00 [DBG] [server{{listener}}: mqtt_broker::transport] - accepted connection from client
<4> 2022-04-08 19:42:56.086 +00:00 [WRN] [mqtt_broker::server] - failed to process connection error=An error occurred decoding a packet. packet is truncated Caused by: packet is truncated`

How and why is the packet truncated?
