### ISSUE TITLE
IoT Edge downstream device discover gateway device

### ISSUE THREAD

**Issue by amit12cool** [Azure/iotedge#6249]
I need a way by which the downstream device can discover and connect to the Gateway device i.e. the IP address of gateway device can change and is not static. the downstream device should be able to capture the IP address changes and connect to the new IP address of the gateway.

Is above possible? If yes, please suggest ways to do it. Also I don't want to do a entry in /etc/hosts file.

**Comment by jlian** [comment]
We should document this

**Comment by darobs** [comment]
@amit12cool - are there any follow-up questions?

**Comment by amit12cool** [comment]
No.Thanks.
