### ISSUE TITLE
Module in IotEdge gets its connection removed after day or two

### ISSUE THREAD

**Issue by mortslhawmit** [Azure/iotedge#625]
## Module in IotEdge gets its connection removed after day or two
Hi,
I've run in to an issue with my IoTEdge solution. I got IotEdge up and running on a rpi3 with two of my own modules and everything works fine for about one to two days but then then the "azureiotedge-hub" removes the connection to one of my modules

> {"log":"2018-12-08 21:47:42.002 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse\n","stream":"stdout","time":"2018-12-08T21:47:42.003145911Z"}
{"log":"2018-12-08 21:47:42.131 +00:00 [INF] - Cleaned up 10 messages from queue for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse and 10 messages from message store.\n","stream":"stdout","time":"2018-12-08T21:47:42.131
718586Z"}
{"log":"2018-12-08 21:51:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:51:03.641007915Z"}
{"log":"2018-12-08 21:56:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:56:03.641869859Z"}
{"log":"2018-12-08 22:01:03.645 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:01:03.645890177Z"}
{"log":"2018-12-08 22:02:47.318 +00:00 [INF] - Closing link Events for RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.319196253Z"}
{"log":"2018-12-08 22:02:47.348 +00:00 [INF] - Closing link ModuleMessages for RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.349335165Z"}
{"log":"2018-12-08 22:02:47.379 +00:00 [INF] - Setting proxy inactive for RPI_Gateway_One/ModuleB.\n","stream":"stdout","time":"2018-12-08T22:02:47.379598451Z"}
{"log":"2018-12-08 22:02:47.399 +00:00 [INF] - Device connection removed for device RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.400352498Z"}
{"log":"2018-12-08 22:02:47.420 +00:00 [INF] - Remove device connection for device RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.420992118Z"}
{"log":"2018-12-08 22:06:03.648 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:06:03.64972239Z"}
{"log":"2018-12-08 22:07:39.081 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:39.081704387Z"}
{"log":"2018-12-08 22:07:40.187 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:40.1880762Z"}
{"log":"2018-12-08 22:07:42.002 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:42.003503903Z"}

I am not sure if my case is similar to #356 but I am running version 1.18.1 of the Microsoft.Azure.Devices.Client nuget.

When i get this message the "ModuleB " stops responding and nothing works anymore, i dont get any errors of weird behavior from the "ModuleB " image before this happen, but as soon as it happens the module "freezes" (Still is running in docker, but according to docker logs of image nothing has happen since the removal of the connection).

I'm sorry if I've missed something obvious but I cant seems to get passed this issue.

## Expected Behavior
The modules should continue to run as they do for the first day

## Current Behavior
Solutions stops working after 1-2 days

### Device (Host) Operating System
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

### Architecture
arm32

### Container Operating System
Linux

#### iotedged
iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)

#### Edge Agent
azureiotedge-agent:1.0 

#### Edge Hub
azureiotedge-hub:1.0

#### Docker
 18.06.0-dev

## Logs

> {"log":"2018-12-08 20:41:03.642 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T20:41:03.643124173Z"}
{"log":"2018-12-08 20:41:03.871 +00:00 [INF] - Starting refresh of device scope identities cache\n","stream":"stdout","time":"2018-12-08T20:41:03.87183775Z"}
{"log":"2018-12-08 20:43:41.427 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub\n","stream":"stdout","time":"2018-12-08T20:43:41.427897176Z"}
{"log":"2018-12-08 20:43:41.428 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.\n","stream":"stdout","time":"2018-12-08T20:43:41.428566288Z"}
{"log":"2018-12-08 20:44:11.422 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest\n","stream":"stdout","time":"2018-12-08T20:44:11.42350538Z"}
{"log":"2018-12-08 20:44:11.536 +00:00 [INF] - Cleaned up 9 messages from queue for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest and 9 messages from message store.\n","stream":"stdout","time":"2018-12-08T20:44:11.53
7195401Z"}
{"log":"2018-12-08 20:44:41.532 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse\n","stream":"stdout","time":"2018-12-08T20:44:41.560080101Z"}
{"log":"2018-12-08 20:44:41.653 +00:00 [INF] - Cleaned up 9 messages from queue for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse and 9 messages from message store.\n","stream":"stdout","time":"2018-12-08T20:44:41.65376
2484Z"}
{"log":"2018-12-08 20:46:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T20:46:03.641661289Z"}
{"log":"2018-12-08 20:51:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T20:51:03.641019083Z"}
{"log":"2018-12-08 20:56:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T20:56:03.641071991Z"}
{"log":"2018-12-08 21:01:03.642 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:01:03.643480596Z"}
{"log":"2018-12-08 21:06:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:06:03.642825162Z"}
{"log":"2018-12-08 21:11:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:11:03.641140024Z"}
{"log":"2018-12-08 21:15:11.661 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub\n","stream":"stdout","time":"2018-12-08T21:15:11.662350039Z"}
{"log":"2018-12-08 21:15:11.662 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.\n","stream":"stdout","time":"2018-12-08T21:15:11.66327488Z"}
{"log":"2018-12-08 21:15:41.666 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest\n","stream":"stdout","time":"2018-12-08T21:15:41.680075519Z"}
{"log":"2018-12-08 21:15:41.783 +00:00 [INF] - Cleaned up 9 messages from queue for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest and 9 messages from message store.\n","stream":"stdout","time":"2018-12-08T21:15:41.78
4221194Z"}
{"log":"2018-12-08 21:16:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:16:03.641474867Z"}
{"log":"2018-12-08 21:16:11.785 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse\n","stream":"stdout","time":"2018-12-08T21:16:11.786427477Z"}
{"log":"2018-12-08 21:16:11.887 +00:00 [INF] - Cleaned up 9 messages from queue for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse and 9 messages from message store.\n","stream":"stdout","time":"2018-12-08T21:16:11.88860
7794Z"}
{"log":"2018-12-08 21:21:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:21:03.641317721Z"}
{"log":"2018-12-08 21:26:03.641 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:26:03.642694674Z"}
{"log":"2018-12-08 21:31:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:31:03.640930926Z"}
{"log":"2018-12-08 21:36:03.641 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:36:03.643848451Z"}
{"log":"2018-12-08 21:37:27.995 +00:00 [INF] - Existing token not found for RPI_Gateway_One/ModuleB. Getting new token from the client...\n","stream":"stdout","time":"2018-12-08T21:37:27.99809775Z"}
{"log":"2018-12-08 21:37:27.995 +00:00 [INF] - Connection status for RPI_Gateway_One/ModuleB changed to TokenNearExpiry\n","stream":"stdout","time":"2018-12-08T21:37:27.998316031Z"}
{"log":"2018-12-08 21:37:27.996 +00:00 [INF] - Existing token not found for RPI_Gateway_One/ModuleB. Getting new token from the client...\n","stream":"stdout","time":"2018-12-08T21:37:27.998384728Z"}
{"log":"2018-12-08 21:37:28.145 +00:00 [INF] - New token received on the Cbs link\n","stream":"stdout","time":"2018-12-08T21:37:28.147565572Z"}
{"log":"2018-12-08 21:37:28.146 +00:00 [INF] - Token updated for RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T21:37:28.147680884Z"}
{"log":"2018-12-08 21:37:33.993 +00:00 [INF] - Existing token not found for RPI_Gateway_One/ModuleA. Getting new token from the client...\n","stream":"stdout","time":"2018-12-08T21:37:33.99727204Z"}
{"log":"2018-12-08 21:37:33.994 +00:00 [INF] - Connection status for RPI_Gateway_One/ModuleA changed to TokenNearExpiry\n","stream":"stdout","time":"2018-12-08T21:37:33.997482872Z"}
{"log":"2018-12-08 21:37:33.994 +00:00 [INF] - Existing token not found for RPI_Gateway_One/ModuleA. Getting new token from the client...\n","stream":"stdout","time":"2018-12-08T21:37:33.997550216Z"}
{"log":"2018-12-08 21:37:34.044 +00:00 [INF] - New token received on the Cbs link\n","stream":"stdout","time":"2018-12-08T21:37:34.045462831Z"}
{"log":"2018-12-08 21:37:34.128 +00:00 [INF] - Token updated for RPI_Gateway_One/ModuleA\n","stream":"stdout","time":"2018-12-08T21:37:34.129038841Z"}
{"log":"2018-12-08 21:37:47.993 +00:00 [INF] - Connection status for RPI_Gateway_One/ModuleB changed to TokenNearExpiry\n","stream":"stdout","time":"2018-12-08T21:37:47.995060483Z"}
{"log":"2018-12-08 21:37:47.995 +00:00 [INF] - Obtained new token for client RPI_Gateway_One/ModuleB that expires in 00:59:40.0048028\n","stream":"stdout","time":"2018-12-08T21:37:47.995934073Z"}
{"log":"2018-12-08 21:37:53.990 +00:00 [INF] - Connection status for RPI_Gateway_One/ModuleA changed to TokenNearExpiry\n","stream":"stdout","time":"2018-12-08T21:37:53.991640321Z"}
{"log":"2018-12-08 21:37:53.992 +00:00 [INF] - Obtained new token for client RPI_Gateway_One/ModuleA that expires in 00:59:40.0078792\n","stream":"stdout","time":"2018-12-08T21:37:53.99271839Z"}
{"log":"2018-12-08 21:40:25.332 +00:00 [INF] - Starting compaction of stores\n","stream":"stdout","time":"2018-12-08T21:40:25.333175951Z"}
{"log":"2018-12-08 21:40:25.332 +00:00 [INF] - Starting compaction of store messages\n","stream":"stdout","time":"2018-12-08T21:40:25.333438762Z"}
{"log":"2018-12-08 21:40:25.359 +00:00 [INF] - Starting compaction of store DeviceScopeCache\n","stream":"stdout","time":"2018-12-08T21:40:25.360748287Z"}
{"log":"2018-12-08 21:40:25.360 +00:00 [INF] - Starting compaction of store checkpoints\n","stream":"stdout","time":"2018-12-08T21:40:25.371379911Z"}
{"log":"2018-12-08 21:40:25.388 +00:00 [INF] - Starting compaction of store iothub\n","stream":"stdout","time":"2018-12-08T21:40:25.389103746Z"}
{"log":"2018-12-08 21:40:25.388 +00:00 [INF] - Starting compaction of store default\n","stream":"stdout","time":"2018-12-08T21:40:25.389625254Z"}
{"log":"2018-12-08 21:40:25.389 +00:00 [INF] - Starting compaction of store sessions\n","stream":"stdout","time":"2018-12-08T21:40:25.39018671Z"}
{"log":"2018-12-08 21:40:25.390 +00:00 [INF] - Starting compaction of store RPI_Gateway_One/ModuleB/inputcommandrequest\n","stream":"stdout","time":"2018-12-08T21:40:25.390714365Z"}
{"log":"2018-12-08 21:40:25.437 +00:00 [INF] - Starting compaction of store RPI_Gateway_One/ModuleA/inputcommandresponse\n","stream":"stdout","time":"2018-12-08T21:40:25.438565578Z"}
{"log":"2018-12-08 21:40:25.454 +00:00 [INF] - Starting compaction of store twins\n","stream":"stdout","time":"2018-12-08T21:40:25.455415822Z"}
{"log":"2018-12-08 21:41:03.641 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:41:03.64217094Z"}
{"log":"2018-12-08 21:41:04.531 +00:00 [INF] - Starting refresh of device scope identities cache\n","stream":"stdout","time":"2018-12-08T21:41:04.532382519Z"}
{"log":"2018-12-08 21:46:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:46:03.64158297Z"}
{"log":"2018-12-08 21:46:41.886 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub\n","stream":"stdout","time":"2018-12-08T21:46:41.887743486Z"}
{"log":"2018-12-08 21:46:41.888 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.\n","stream":"stdout","time":"2018-12-08T21:46:41.889405354Z"}
{"log":"2018-12-08 21:47:11.890 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest\n","stream":"stdout","time":"2018-12-08T21:47:11.891898703Z"}
{"log":"2018-12-08 21:47:12.006 +00:00 [INF] - Cleaned up 9 messages from queue for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest and 9 messages from message store.\n","stream":"stdout","time":"2018-12-08T21:47:12.00
7164814Z"}
{"log":"2018-12-08 21:47:42.002 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse\n","stream":"stdout","time":"2018-12-08T21:47:42.003145911Z"}
{"log":"2018-12-08 21:47:42.131 +00:00 [INF] - Cleaned up 10 messages from queue for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse and 10 messages from message store.\n","stream":"stdout","time":"2018-12-08T21:47:42.131
718586Z"}
{"log":"2018-12-08 21:51:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:51:03.641007915Z"}
{"log":"2018-12-08 21:56:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T21:56:03.641869859Z"}
{"log":"2018-12-08 22:01:03.645 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:01:03.645890177Z"}
{"log":"2018-12-08 22:02:47.318 +00:00 [INF] - Closing link Events for RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.319196253Z"}
{"log":"2018-12-08 22:02:47.348 +00:00 [INF] - Closing link ModuleMessages for RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.349335165Z"}
{"log":"2018-12-08 22:02:47.379 +00:00 [INF] - Setting proxy inactive for RPI_Gateway_One/ModuleB.\n","stream":"stdout","time":"2018-12-08T22:02:47.379598451Z"}
{"log":"2018-12-08 22:02:47.399 +00:00 [INF] - Device connection removed for device RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.400352498Z"}
{"log":"2018-12-08 22:02:47.420 +00:00 [INF] - Remove device connection for device RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:02:47.420992118Z"}
{"log":"2018-12-08 22:06:03.648 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:06:03.64972239Z"}
{"log":"2018-12-08 22:07:39.081 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:39.081704387Z"}
{"log":"2018-12-08 22:07:40.187 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:40.1880762Z"}
{"log":"2018-12-08 22:07:42.002 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:42.003503903Z"}
{"log":"2018-12-08 22:07:45.610 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:45.610928134Z"}
{"log":"2018-12-08 22:07:52.303 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:07:52.303744267Z"}
{"log":"2018-12-08 22:08:07.101 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:08:07.10181956Z"}
{"log":"2018-12-08 22:08:39.341 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:08:39.341495334Z"}
{"log":"2018-12-08 22:09:39.342 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:09:39.343253084Z"}
{"log":"2018-12-08 22:10:39.341 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:10:39.341780405Z"}
{"log":"2018-12-08 22:11:03.641 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:11:03.642174742Z"}
{"log":"2018-12-08 22:11:39.340 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:11:39.340703677Z"}
{"log":"2018-12-08 22:12:39.341 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:12:39.342290308Z"}
{"log":"2018-12-08 22:13:39.340 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:13:39.34147673Z"}
{"log":"2018-12-08 22:14:39.340 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:14:39.341745112Z"}
{"log":"2018-12-08 22:15:39.341 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:15:39.341631485Z"}
{"log":"2018-12-08 22:16:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:16:03.640534657Z"}
{"log":"2018-12-08 22:16:39.350 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:16:39.351343392Z"}
{"log":"2018-12-08 22:17:39.408 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:17:39.409181232Z"}
{"log":"2018-12-08 22:18:12.133 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint iothub\n","stream":"stdout","time":"2018-12-08T22:18:12.134412579Z"}
{"log":"2018-12-08 22:18:12.134 +00:00 [INF] - Cleaned up 0 messages from queue for endpoint iothub and 0 messages from message store.\n","stream":"stdout","time":"2018-12-08T22:18:12.135309503Z"}
{"log":"2018-12-08 22:18:39.411 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:18:39.412300802Z"}
{"log":"2018-12-08 22:18:42.133 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest\n","stream":"stdout","time":"2018-12-08T22:18:42.138540958Z"}
{"log":"2018-12-08 22:18:42.137 +00:00 [INF] - Cleaned up 6 messages from queue for endpoint RPI_Gateway_One/ModuleB/inputcommandrequest and 6 messages from message store.\n","stream":"stdout","time":"2018-12-08T22:18:42.138661322Z"}
{"log":"2018-12-08 22:19:12.133 +00:00 [INF] - Started task to cleanup processed and stale messages for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse\n","stream":"stdout","time":"2018-12-08T22:19:12.133880039Z"}
{"log":"2018-12-08 22:19:12.200 +00:00 [INF] - Cleaned up 5 messages from queue for endpoint RPI_Gateway_One/ModuleA/inputcommandresponse and 5 messages from message store.\n","stream":"stdout","time":"2018-12-08T22:19:12.200720527Z"}
{"log":"2018-12-08 22:19:39.411 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:19:39.412863219Z"}
{"log":"2018-12-08 22:20:39.411 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:20:39.412621184Z"}
{"log":"2018-12-08 22:21:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:21:03.640610755Z"}
{"log":"2018-12-08 22:21:39.420 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:21:39.421375536Z"}
{"log":"2018-12-08 22:22:39.422 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:22:39.422451793Z"}
{"log":"2018-12-08 22:23:39.421 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:23:39.422365745Z"}
{"log":"2018-12-08 22:24:39.421 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:24:39.422748043Z"}
{"log":"2018-12-08 22:25:39.430 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:25:39.4316878Z"}
{"log":"2018-12-08 22:26:03.643 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:26:03.644124666Z"}
{"log":"2018-12-08 22:26:39.433 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:26:39.433616449Z"}
{"log":"2018-12-08 22:27:39.434 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:27:39.43469946Z"}
{"log":"2018-12-08 22:28:39.434 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:28:39.434793268Z"}
{"log":"2018-12-08 22:29:39.433 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:29:39.434833185Z"}
{"log":"2018-12-08 22:30:39.434 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:30:39.435312606Z"}
{"log":"2018-12-08 22:31:03.643 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:31:03.644939535Z"}
{"log":"2018-12-08 22:31:39.433 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:31:39.434292619Z"}
{"log":"2018-12-08 22:32:39.430 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:32:39.432050762Z"}
{"log":"2018-12-08 22:33:39.433 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:33:39.433824261Z"}
{"log":"2018-12-08 22:34:39.433 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:34:39.434227209Z"}
{"log":"2018-12-08 22:35:28.004 +00:00 [INF] - Existing token not found for RPI_Gateway_One/ModuleB. Getting new token from the client...\n","stream":"stdout","time":"2018-12-08T22:35:28.009872313Z"}
{"log":"2018-12-08 22:35:28.005 +00:00 [INF] - Connection status for RPI_Gateway_One/ModuleB changed to TokenNearExpiry\n","stream":"stdout","time":"2018-12-08T22:35:28.010006271Z"}
{"log":"2018-12-08 22:35:28.006 +00:00 [INF] - Device connection removed for device RPI_Gateway_One/ModuleB\n","stream":"stdout","time":"2018-12-08T22:35:28.010042313Z"}
{"log":"2018-12-08 22:35:34.001 +00:00 [INF] - Existing token not found for RPI_Gateway_One/ModuleA. Getting new token from the client...\n","stream":"stdout","time":"2018-12-08T22:35:34.002187756Z"}
{"log":"2018-12-08 22:35:34.002 +00:00 [INF] - Connection status for RPI_Gateway_One/ModuleA changed to TokenNearExpiry\n","stream":"stdout","time":"2018-12-08T22:35:34.002440204Z"}
{"log":"2018-12-08 22:35:34.002 +00:00 [INF] - Existing token not found for RPI_Gateway_One/ModuleA. Getting new token from the client...\n","stream":"stdout","time":"2018-12-08T22:35:34.003166244Z"}
{"log":"2018-12-08 22:35:34.036 +00:00 [INF] - New token received on the Cbs link\n","stream":"stdout","time":"2018-12-08T22:35:34.03700957Z"}
{"log":"2018-12-08 22:35:34.037 +00:00 [INF] - Token updated for RPI_Gateway_One/ModuleA\n","stream":"stdout","time":"2018-12-08T22:35:34.037968631Z"}
{"log":"2018-12-08 22:35:39.491 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:35:39.492452284Z"}
{"log":"2018-12-08 22:35:54.002 +00:00 [INF] - Connection status for RPI_Gateway_One/ModuleA changed to TokenNearExpiry\n","stream":"stdout","time":"2018-12-08T22:35:54.003470543Z"}
{"log":"2018-12-08 22:35:54.003 +00:00 [INF] - Obtained new token for client RPI_Gateway_One/ModuleA that expires in 00:59:39.9961883\n","stream":"stdout","time":"2018-12-08T22:35:54.004189188Z"}
{"log":"2018-12-08 22:36:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:36:03.640946246Z"}
{"log":"2018-12-08 22:36:39.501 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:36:39.50164012Z"}
{"log":"2018-12-08 22:37:39.502 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:37:39.503295565Z"}
{"log":"2018-12-08 22:38:39.502 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:38:39.503570546Z"}
{"log":"2018-12-08 22:39:39.503 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:39:39.503510179Z"}
{"log":"2018-12-08 22:40:39.502 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:40:39.503592201Z"}
{"log":"2018-12-08 22:41:03.640 +00:00 [INF] - Reauthenticating connected clients\n","stream":"stdout","time":"2018-12-08T22:41:03.640656287Z"}
{"log":"2018-12-08 22:41:05.209 +00:00 [INF] - Starting refresh of device scope identities cache\n","stream":"stdout","time":"2018-12-08T22:41:05.210375611Z"}
{"log":"2018-12-08 22:41:39.502 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:41:39.502737504Z"}
{"log":"2018-12-08 22:42:39.501 +00:00 [WRN] - Module RPI_Gateway_One/ModuleB is not connected\n","stream":"stdout","time":"2018-12-08T22:42:39.501767428Z"}

Cheers!
Tim

**Comment by varunpuranik** [comment]
Hi @mortslhawmit,

Thanks for the issue. I believe the issue you are seeing is because of an issue in the underlying library that the Edge runtime uses - https://github.com/Azure/azure-amqp/issues/131
That issue has been fixed recently, but the version of the library hasn't been updated in our images yet. We will do that in one of our upcoming releases and then the issue should go away. I will keep you posted when that happens.

**Comment by myagley** [comment]
The version of the AMQP library was updated in #632. It will be available in the next release.

**Comment by myagley** [comment]
This has been fixed in the 1.0.5 release. More information on upgrading is here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge

**Comment by mortslhawmit** [comment]
I´ve upgraded it now so i will try it out thanks for the help!

Cheers
Tim
