### ISSUE TITLE
ARM32 Build

### ISSUE THREAD

**Issue by WalkenOnWasser** [Azure/iotedge#6257]
What is the process for building the Agent for ARM32 devices? I have some devices that are ARM32 and would like to be able to use these devices.
- Thanks

**Comment by darobs** [comment]
Hi @WalkenOnWasser,

All the container images this team provides have an ARM32 compatible tag, which is manifested with the floating tag, so these should work for most ARM32 systems. 

For the host services - aziot-edged and IIS, we do provide arm32 packages for some OSs, please check out the latest releases [here](https://github.com/Azure/azure-iotedge/releases), _but_ presuming we don't have a package that works for you, it depends on the OS and how you build for it.

- If you have a build environment on your target platform, following the [devguide](https://github.com/Azure/iotedge/blob/release/1.2/edgelet/doc/devguide.md) may work for you - Rust can be installed on a lot of platforms.
- If you have a Yocto build, you may want to try the [meta-iotedge project](https://github.com/Azure/meta-iotedge).
- If you are cross-compiling to build applications for the system, we typically install the cross-compile toolchain into a container and run the container to do the build...  Our setup is annoyingly complicated, but you can find everything we do to build the packages in the [packages.sh script](https://github.com/Azure/iotedge/blob/main/edgelet/build/linux/package.sh). 
- If you have a development system with the toolchain installed, the above packages.sh script is still the best reference for how we build the aziot-edged packages.

Note for 1.2, there are two projects to build, this project and the [IoT Identity Service](https://github.com/Azure/iot-identity-service/blob/main/docs-dev/README.md).

**Comment by darobs** [comment]
Any follow up questions?
