### ISSUE TITLE
SimulatedTemperatureSensor not using desired SentInterval

### ISSUE THREAD

**Issue by sebader** [Azure/iotedge#626]
I just deployed the latest version of the SimulatedTemperatureSensor by following the tutorial (https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux). When I change the SendInterval during module creation or also later in the module twin, from 5 to 1, this is nerver taken into account. The module keeps sending with 5 second interval. Also after module restart etc. this never goes into effect.

Also SendData property seems to have no effect. So maybe none of the desired properties are being watched?!

Version: 
mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0       
EdgeAgent and EdgeHub: 1.0.4
on Ubuntu 18.04

**Comment by myagley** [comment]
Hi Sebastian. The code for the simulated temperature sensor is here: https://github.com/Azure/iotedge/blob/master/edge-modules/SimulatedTemperatureSensor/src/Program.cs

I don't believe it does anything with configuring through the twin. All configuration is done via environment variables. (I don't see SendInterval or SendData referenced in the code)

**Comment by sebader** [comment]
Yeah that's what I realized as well by looking into the code :) So I guess the tutorial should be updated there.

**Comment by varunpuranik** [comment]
@sebader - Yes, we should do that. But I couldn't find the place in the tutorial where it talks about setting the SendInterval in the Twin desired properties. Can you please point me to it, so that I can log an issue to get it fixed?
Thanks.

**Comment by sebader** [comment]
Ah sorry, my bad. It is actually in the deployment, when you follow the tutorial and deploy from Azure Marketplace
![image](https://user-images.githubusercontent.com/11445087/49748740-d306a980-fca6-11e8-9beb-71d86b87ad80.png)

**Comment by varunpuranik** [comment]
I see, got it, thanks. I will log an issue to get it fixed.

**Comment by aribeironovaes** [comment]
Hi Sebastian and Call. This change is checked in and should be available on the next release. 

Code commit is here: https://github.com/Azure/iotedge/commit/7dc7041f790ebe323d720913782e8085f1f65c21

Thanks! 

Angelo Ribeiro.

**Comment by myagley** [comment]
This has been released as part of the 1.0.7 release candidate. You can get the fix by using the following tag for the temp sensor: `mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0.7-rc2`
