### ISSUE TITLE
IoT Edge Runtime shall be prevented to scan /home

### ISSUE THREAD

**Issue by fvsecunet** [Azure/iotedge#6267]
We have previously recognized, Azure runtime 1.2.3 scanning the /home folder, a new behavior compared to 1.1.7. It was causing 20 minutes delay for initial configuration, as it was scanning /home folder simultaneously with another scan. Now with 1.2.5 we experience a real issue, as this simultaneous prevents modules to start.
Question 1: why does Azure runtime make such a scan on host device?
Question 2: Is it possible to disable the /home folder scan totally, or is it possible to close some subfolders to scan?
Request: This was not the behavior with Azure Runtime 1.1.x. Will it be fixed / changed for 1.2.x in the near future?

### Device Information
* Host OS: customized Debian10
* Architecture amd64  
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.6
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.0
* Docker/Moby [run `docker version`]: 20.10.11+azure-3

## Logs
No logs possible as the logs do not give any hint.

**Comment by gordonwang0** [comment]
Could you clarify what you mean by 'scan'? Edge 1.2 only checks its configuration directories on startup (which are not in /home).

**Comment by darobs** [comment]
Hi @fvsecunet, 

Do you have any clarifications to @gordonwang0's questions?

**Comment by fvsecunet** [comment]
We determined that the container modules need approximately 20 minutes to start if a subdirectory in /home is blocked by an unsuccessful network mount command. That’s why we suppose that the runtime looks into the /home directory.

**Comment by gordonwang0** [comment]
Edge runtime only looks at its config, home, and socket directories, which are /etc/aziot, /var/lib/aziot, and /run/aziot, respectively. It does not look in /home unless you have configured it. Have you done something to configure Edge runtime or modules to use /home?

**Comment by fvsecunet** [comment]
Hi Gordon, we do not see any /home entry within the .toml. Also our external partner did not do anything (intentionally). How could we check this? Where could we do the change? Would it help sharing the .toml file here (excluding the connection string)?

**Comment by gordonwang0** [comment]
If you haven't configured Edge to look in /home, then I don't know what would cause it to do so on your system. You can try using strace to monitor which module or application is attempting to access /home, but otherwise there isn't much else I can help with.
