### ISSUE TITLE
Question: Declaring custom routes

### ISSUE THREAD

**Issue by madstt** [Azure/iotedge#6295]
Is it possible to declare custom routes, where the source is without the prefixed `/`, such as 

`
        "routes": {
          "Telemetry": "FROM Telemetry/* INTO $upstream"
        },
`

**Comment by and-rewsmith** [comment]
@madstt What is stopping you from doing what you want with the current syntax?
https://docs.microsoft.com/en-us/azure/iot-edge/module-composition?view=iotedge-2020-11#source

**Comment by and-rewsmith** [comment]
@madstt The way the syntax works is that leading `/` is supposed to capture absolutely everything. 

> All device-to-cloud messages or twin change notifications from any module or leaf device

When you are sending a message from a device on example topic `input1`, it goes to `/messages/modules/<moduleId>/input1`. So I think the current syntax should work for you and something else is going wrong. Does that make sense?

**Comment by madstt** [comment]
@and-rewsmith that is a new insight for me, thank you.

You might also be able to answer another question. What is the difference between configuring the `mqttBroker` directly on the `$edgeHub` like this:

`"$edgeHub":{
      "properties.desired":{
         "schemaVersion":"1.2",
         "mqttBroker":{
...
`
And just using the default configuration?

**Comment by and-rewsmith** [comment]
That configuration is applied only to our preview broker. I recommend sticking with the non-preview broker for now (i.e. default) as the future of the preview broker is unclear.

**Comment by madstt** [comment]
@and-rewsmith thanks, I appreciate that info. I might have further questions, should I just create a new issue or do you prefer other communication methods?

**Comment by madstt** [comment]
> @madstt The way the syntax works is that leading `/` is supposed to capture absolutely everything. The docs say for `/`:
> 
> > All device-to-cloud messages or twin change notifications from any module or leaf device
> 
> When you are sending a message from a device on example topic `input1`, it goes to `/messages/modules/<moduleId>/input1`. So I think the current syntax should work for you and something else is going wrong. Does that make sense?

@and-rewsmith I'm not sure. If I have the `/*` route configured and I send a message to this topic: `devices/<deviceId>/messages/events`, then everything works fine and the message is forwarded to the IoT Hub. But if I send the message to this topic `devices/<deviceId>/<companyName>/telemetry` then I get this exception in the `$edgeHub` log: `Message was not sent for device Id <deviceId> exception System.InvalidOperationException: Topic name could not be matched against any of the configured routes.`

**Comment by madstt** [comment]
@and-rewsmith can I get this issue re-opened?

Digging into the source code, I think the issue is related to the `InboundTemplates` in [`appsettings_hub.json`](https://github.com/Azure/iotedge/blob/main/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json#L43). These does not allow you to send to other topics than the ones listed.

Is it possible to manipulate this list somehow?

**Comment by madstt** [comment]
@and-rewsmith no. The routes configured in the deployment look like this:

`        "routes": {
          "Upstream": "FROM /messages/* INTO $upstream",
          "Telemetry": "FROM /* INTO $upstream"
        },
`
Which, according to the documentation, should be able to handle `All device-to-cloud messages or twin change notifications from any module or leaf device`, but this is obviously not the case.

I get these entries in the `edgeHub` log:

`<4> 2022-04-27 12:24:01.168 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessageAddressConverter] - Message address <companyId>/telemetry does not match any topic.`

and

`<4> 2022-04-27 12:24:01.169 +00:00 [WRN] [Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient] - Message was not sent for device <deviceId> exception System.InvalidOperationException: Topic name could not be matched against any of the configured routes.
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.ProtocolGatewayMessageConverter.ToMessage(IMessage sourceMessage) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs:line 28
   at Microsoft.Azure.Devices.Edge.Hub.Mqtt.MessagingServiceClient.ProcessMessageAsync(IMessage message) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MessagingServiceClient.cs:line 209`
