### ISSUE TITLE
Get device twin in IoT Edge module

### ISSUE THREAD

**Issue by AndyLiTaiwan** [Azure/iotedge#631]
Hi all,

Currently, I would like to monitor the event about updating **device's** desired property(not module twin).
It seems doable, but how can I get device connection string in IoT Edge module? or is there any better way?

Below is my code in edge module

```
static string _deviceConnectionString = "***";
static DeviceClient _deviceClient = null;

//Monitor Device Twin
_deviceClient = DeviceClient.CreateFromConnectionString(_deviceConnectionString, TransportType.Mqtt);
Twin twin = await _deviceClient.GetTwinAsync();

private static async Task OnDeviceTwinDesiredPropertyChanged(TwinCollection desiredProperties, object userContext)
        {
            Console.WriteLine("\tDesired property changed:");
            Console.WriteLine($"\t{desiredProperties.ToJson()}");

            Console.WriteLine("\tSending current time as reported property");
            TwinCollection reportedProperties = new TwinCollection();
            reportedProperties["DateTimeLastDesiredPropertyChangeReceived"] = DateTime.Now;

            await _deviceClient.UpdateReportedPropertiesAsync(reportedProperties).ConfigureAwait(false);
        }
```

**Comment by varunpuranik** [comment]
@AndyLiTaiwan, thanks for the issue. 

The Edge runtime does not provide a way for a module to connect as the edge device using the edge device connection string. This is by design for security reasons.

Can you provide some more details on what is your scenario that requires this? And why are you not able to use the Module twin for the same purpose?

**Comment by AndyLiTaiwan** [comment]
Does anyone have an idea?

**Comment by varunpuranik** [comment]
@AndyLiTaiwan - Thanks for the details on your scenario. As I mentioned previously, accessing device twin from a module is currently not supported by the Edge runtime.
We do understand your scenario, and we will work to make enhancements that enable it. However, at the moment, sending messages (or invoking methods), is your best option to communicate information from one module to another.
If you do want to use the device twin from the module, then you would have to hard code the device connection string in the module. But this approach is not recommended for security and maintenance purposes.

**Comment by AndyLiTaiwan** [comment]
Got it, thanks!

**Comment by danigian** [comment]
Same issue here.
What if an edge device has metadata in its device twin, that a customer wants to use in device registry queries, that any given module wants to access? @varunpuranik what's the suggested pattern here?
Connection string in module twin is definitely not a way for production scenarios where a TPM is involved, neither it is the duplication of these metadata in every module twin.

**Comment by danigian** [comment]
@AndyLiTaiwan @varunpuranik this is a workaround I found to achieve our goal with "TPM-provisioned" devices: https://www.danielemaggio.eu/iot/devicetwin-tpm-csharp-edge-module/

**Comment by Jazmine7** [comment]
I could not find a way to access device twin from within the module without specifying connection string. I was using the Python SDK on Linux.  Take a look at this for [further](https://github.com/MicrosoftDocs/azure-docs/issues/18767#issuecomment-485997487) details.

**Comment by torangel** [comment]
@varunpuranik 
I also would like to read relevant device-twin information from modules running on the device. Any updates on if this will be/is possible?

**Comment by varunpuranik** [comment]
@torangel - No, there is no way to access the device twin from the modules. This is because the device is a separate parent identity for all the modules on the device. 

The only way to do this would be to pass in the device connection string to the module, but it is not recommended for security reasons.

**Comment by danigian** [comment]
@torangel if you are using TPM you can try this https://www.danielemaggio.eu/iot/devicetwin-tpm-csharp-edge-module/ (more secure than passing the connection string to the module)

**Comment by FabGre** [comment]
Hi there, we also have scenarios where some device models, running modes(, ...), should be shared between modules and it's not really convenient to duplicate in each module twin...
We have different edge device projects and we have always met this need.
Thanks,

**Comment by henrik2424** [comment]
Hello, i would also like to fetch meta data on a device level instead of on the specific module for a device.
Is it still not possible to do?

**Comment by TheZeion** [comment]
any update? We have the same needs here

**Comment by amitkmcs** [comment]
Any update on the query how to get [device twin] not [module identity twin ] with using connection string?
