### ISSUE TITLE
Mounting remote Windows folders from module

### ISSUE THREAD

**Issue by bkarrlander** [Azure/iotedge#6319]
Hi,

Is there a way to mount a __remote Windows folder__ from a module container? We currently do this by mounting from **the host** but we are trying to make our modules more self-contained.

We have tried to do this from a **non-iotedge** container and it works fine when running the container with `--privileged` flag. 

We use IoT Edge 1.2. Hosts are Raspbian and Ubuntu Server.

Best regards,
Björn

**Comment by gordonwang0** [comment]
There is no way to natively remote mount a folder from a container. As you mentioned, mounting to the host first is the only way to do so.

**Comment by bkarrlander** [comment]
Ok. Thank you, @gordonwang0.

Björn
