### ISSUE TITLE
deviceId is not set in the module twin

### ISSUE THREAD

**Issue by icebat83** [Azure/iotedge#633]
Hi,

I created own Edge module. I can connect via module client and set different callbacks and handlers. It works fine. But when I read the module twin using GetTwinAsync() method on the instance of the Microsoft.Azure.Devices.Client.ModuleClient class then I get some content but the deviceId is set to null. When I check it on the Azure portal I can see the deviceId there.

## Expected Behavior
I would expect that I will see proper deviceId as on the Azure portal when I open module twin there.

## Current Behavior
Currently deviceId is set to null.

## Steps to Reproduce
1. Create own Edge module.
2. Create an instance of the module client and get the module twin using GetTwinAsync() method.
3. Check content and the deviceId is null.

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
1.0.4

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
3.0.1

## Logs
{"deviceId":null,"etag":null,"version":null,"properties":{"desired":{"$version":1},"reported":{"moduleVersion":"10.96.220.00","cpuArchitecture":"X64","osArchitecture":"X64","osDescription":"Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018","frameworkDescription":".NET Core 4.6.26919.02","$version":3}}}

**Comment by icebat83** [comment]
Thank you for the response.

Since I am working with the module twin I wanted to use it also in this case. But if it's possible to get the information from the environment variable then I have no problem with it.

**Comment by ancaantochi** [comment]
Closing since using the Environment variable solves it.
