### ISSUE TITLE
azureblobstorageoniotedge module queuing up corrupted blobs

### ISSUE THREAD

**Issue by abhishekcodework** [Azure/iotedge#6333]
I'm currently facing an issue with the azureblobstorageoniotedge module. There were some blobs that failed to be uploaded to the Azure Cloud Storage Container. The module keeps retrying to upload these corrupted blobs. Due to this the uncorrupted blobs upload slows down drastically. I've also referred to the link below:

https://docs.microsoft.com/en-us/answers/questions/183321/azure-blob-storage-on-iot-edge-module-stops-upload.html

One of the suggestions in the above link- is to set the module property to 'NewestFirst' however, I would need to keep the property of the module to 'OldestFirst' for the entire solution to work smoothly.

Possible solution- Is there a way to limit the number of retries made by the module due to which it will stop retrying to upload corrupted blobs after a certain amount of retries- unable to find any documentation related to this. 

Also, I wasn't able to locate deviceToCloudUploadProperties:retryIntervalSeconds and deviceToCloudUploadProperties:consecutiveErrorsLimit module twin properties in the azureblobstorageoniotedge documentation.

**Comment by gordonwang0** [comment]
This seems like a problem with the Blob Storage module, not IoT Edge. @veyalla

**Comment by veyalla** [comment]
This Github repo is for the core IoT Edge runtime. For Blob storage issues, please open an Azure Technical Support ticket: https://azure.microsoft.com/support/create-ticket/
