### ISSUE TITLE
Can't find the marketplace image for azureiotedge-metrics-collector

### ISSUE THREAD

**Issue by absolutebandit** [Azure/iotedge#6341]
We've been informed that the latest version of the metrics collector is in the release 1.1 branch of this repo (it was recently moved to the "test" area) but I can't find the corresponding image anywhere.  On the market place only version 1.0 is available which is an old version.  I've found there is a tag 1.0.7 on Docker Hub but this also doesn't work with the ENV settings I'm using that were specified in the readme of the release 1.1 branch.  Is there an image for this somewhere?  Shouldn't it be updated on the marketplace?

**Comment by micahl** [comment]
@absolutebandit The metrics collector follows the [same pattern as IoT Edge when tagging images](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge#understand-iot-edge-tags).  The 1.0 from the marketplace is a rolling tag and will result in pulling whatever the latest is (current 1.0.7).  For example, when I pull the 1.0 and 1.0.7 the Digest is the same (see below).  

What are the ENV settings you're using that no longer work?

> ~$ docker pull mcr.microsoft.com/azureiotedge-metrics-collector:_1.0_
> 1.0: Pulling from azureiotedge-metrics-collector
> **Digest: sha256:afd3fa4107126781507076f7ca10c4548e8cebb5ba77a0f277898e75f0b9d4e0**
> Status: Downloaded newer image for mcr.microsoft.com/azureiotedge-metrics-collector:1.0
> mcr.microsoft.com/azureiotedge-metrics-collector:1.0
> 
> ~$ docker pull mcr.microsoft.com/azureiotedge-metrics-collector:_1.0.7_
> 1.0.7: Pulling from azureiotedge-metrics-collector
> **Digest: sha256:afd3fa4107126781507076f7ca10c4548e8cebb5ba77a0f277898e75f0b9d4e0**
> Status: Downloaded newer image for mcr.microsoft.com/azureiotedge-metrics-collector:1.0.7
> mcr.microsoft.com/azureiotedge-metrics-collector:1.0.7

**Comment by absolutebandit** [comment]
Hi Micah,

Thanks for the fast response, that's very helpful.  I have now located the correct version and figured out where I was going wrong on the ENV settings.  I was confused because I was looking at the source code for the wrong metric collector.  I was looking in the iotedge solution in the modules/TestMetricsCollector.csproj where the ENV setting are different (upload target is IoTHub instead of IotMessage).  Also I missed that ResourceId is a required field.  I found the proper source code which is now not part of the iotedge solution but has it's own solution Microsoft.Azure.Devices.Edge.Azure.Monitor.

Thanks for your support!

**Comment by micahl** [comment]
@absolutebandit glad to hear its working now.  I'm going to close this issue, but do let us know if there's anything in our docs that if we modified might have helped you sooner.

As for the feature request I don't think it's currently on our radar.  We use https://aka.ms/iotedge-suggestion to capture asks.  Please create an entry there with as much detail to describe the ask as necessary and tag it to be in the "Monitoring" category.
