### ISSUE TITLE
On raspberry pi Linux device edgeAgent status is always stopped, edgeHub doesn't appear when provisioning new IoT Edge device 

### ISSUE THREAD

**Issue by arseny-sandaar** [Azure/iotedge#6347]
Hello,

I am new to these technologies, so my explanation may be weak.
Why edgeAgent is always stopped?

The following steps I do:

1. On Microsoft Azure portal I created an IoT hub and then added an IoT Edge device.
2. From the details of a created device I save a primary connection string to insert it in config.toml file located in /etc/aziot for manual provisioning

3. On Linux device (raspberry pi) I installed Microsoft installation packages: https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list
4. Installed Microsoft GPG: https://packages.microsoft.com/keys/microsoft.asc
5. Installed moby-engine, aziot-edge, docker
6. entered in the configuration file the connection string of my device from azure portal
7. applied the changes in the config file
8. created daemon.json file in the docker folder which has several lines for dns, log-driver, and log-opts
9. restarted the docker service

To my understanding the edgeAgent and edgeHub already need to be running after these steps: I did it before

I am using Raspbian GNU/Linux 11 (bullseye)

as I see the iotedge agen image is mcr.microsoft.com/azureiotedge-agent:1.2

iotedge system log:
```
May 11 16:31:13 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:13Z [INFO] - Checking edge runtime status
May 11 16:31:13 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:13Z [INFO] - Edge runtime status is stopped, starting module now...
May 11 16:31:13 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:13Z [INFO] - Starting module edgeAgent...
May 11 16:31:13 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:13Z [INFO] - Starting new listener for module edgeAgent
May 11 16:31:13 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:13Z [INFO] - Listener  edgeAgent already started, removing old listener
May 11 16:31:13 raspberrypi aziot-certd[11430]: 2022-05-11T14:31:13Z [INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "2f72756e2f617a696f742f63657274642e736f636b:0"}
May 11 16:31:13 raspberrypi aziot-certd[11430]: 2022-05-11T14:31:13Z [INFO] - --> 200 {"content-type": "application/json"}
May 11 16:31:13 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:13Z [INFO] - Listening on unix:///var/lib/aziot/edged/mnt/edgeAgent.sock with 1 thread for workload API.
May 11 16:31:14 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:14Z [WARN] - Could not start module edgeAgent
May 11 16:31:14 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:14Z [WARN] -         caused by: OCI runtime create failed: container with id exists: 6bd1a88b77cf6349f3cdab6f81958e97b89e4f275c610d7d01810b817423562e: unknown
May 11 16:31:14 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:14Z [WARN] - Error in watchdog when checking for edge runtime status:
May 11 16:31:14 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:14Z [WARN] - A module runtime error occurred.
May 11 16:31:14 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:14Z [WARN] -         caused by: Could not start module edgeAgent
May 11 16:31:14 raspberrypi aziot-edged[11404]: 2022-05-11T14:31:14Z [WARN] -         caused by: OCI runtime create failed: container with id exists: 6bd1a88b77cf6349f3cdab6f81958e97b89e4f275c610d7d01810b817423562e: unknown
```

**Comment by onalante-msft** [comment]
Could you provide the device information, runtime versions, and similar data requested in the "Context" heading of the issue template? That would help with debugging.

Restarting `docker` could have corrupted one of the containers' states. I would try starting from a clean slate with the following:
```
# iotedge system stop
# docker system prune
# docker image rm $(docker image ls -q)
# iotedge system restart
```
It also looks like we have a number of prior issues with edge on 64-bit Raspberry Pis running Debian Bullseye:
- #5812 
  Workaround here: https://github.com/Azure/iotedge/issues/5812#issuecomment-965573485 (typo: `cgroup-fsmount` should be `cgroupfs-mount`).
- #6153

**Comment by micahl** [comment]
@arseny-sandaar since your on Bullseye you need to set up your device to use the packages built for Bullseye (instead of Stretch).  Please revert what you've done in steps #3-5 (remove the prod.list for Stretch, uninstall moby, aziot-edge, aziot-identity-service) and then do the following:
```bash
curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
sudo apt install ./packages-microsoft-prod.deb
sudo apt update
sudo apt install moby-engine
sudo apt install aziot-edge
```

Then, let's see what issues remain.

**Comment by bishal41** [comment]
@arseny-sandaar were you able to follow Micah's suggestion above? Do you have any further questions?

**Comment by bishal41** [comment]
@arseny-sandaar please let us know if you have any further questions. If I don't hear from you by Tuesday, I will proceed and close this issue and you may open it anytime.

**Comment by bishal41** [comment]
Hi @arseny-sandaar, I will proceed and close this issue, but please do re-open as needed. Thankyou!
