### ISSUE TITLE
Healthcheck not restarting unhealthy module

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#6358]
## Expected Behavior
When a custom module's healthcheck fails, thus putting the module into "unhealthy" status, edgeAgent should restart the module

## Current Behavior
edgeAgent does not restart the module

## Steps to Reproduce
1. Create a custom module with the following at the end of it's Dockerfile
    ```dockerfile
    HEALTHCHECK --interval=15s --timeout=3s --retries=2 \
      CMD exit 1
    ```
1. Deploy this module with a deployment.json which has `modulesContent.$edgeAgent.properties.desired`
    ```json
    "modules": {
      "MyModule": {
        "version": "34136",
        "type": "docker",
        "status": "running",
        "restartPolicy": "on-failure",
        "settings": {
          "image": "...",
          "createOptions": "{\"Healthcheck\":{\"Test\":[],\"Interval\":0,\"Timeout\":0,\"Retries\":0,\"StartPeriod\":0}, \"HostConfig\":{\"CapAdd\":[\"SYS_PTRACE\"], \"ExtraHosts\":[\"dockerhost:172.16.99.99\"], \"Binds\":[\"/etc/daikin-software-gateway/:/etc/storage/\"]}}"
        },
        "env": {
          "storageFolder": {
            "value": "/etc/storage/"
          }
        }
      }
    }
    ```
    According to [documentation](https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate), those Test settings should just inherit the healthcheck definition from the container. 
1. Let the deployment happen. Then run `sudo iotedge list && sudo docker container ls` and observe that `iotedge` lists the module as `running` and `docker` shows the state of the container as `Up 10 seconds (starting)`
1. Wait until the container has run for at least 30 seconds, which comes from the Dockerfile ` --interval=15s --retries=2` settings. Observe that `iotedge` lists the module as `running` and `docker` shows the state of the container as `Up 1 minute (unhealthy)`
1. Observe that regardless of how long you let `edgeAgent` run, it does not restart the custom module. Furthermore, `sudo docker logs -f edgeAgent | grep "scheduled to restart after"` does not show any attempts to restart the custom module.

### Output of `iotedge check`

<details>
<summary>Click to show</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: identity certificates expiry - OK
√ production readiness: certificates - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

22 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.
```

</details>

### Device Information
* Host OS  Ubuntu 18.04]: 
* Architecture [amd64,]: 
* Container OS Linux containers]: 

### Runtime Versions
* iotedge 1.1.13
* mcr.microsoft.com/azureiotedge-agent                                        1.1            d1bbbd315877
* mcr.microsoft.com/azureiotedge-hub                                          1.1            c25873c1704a
* Docker/Moby [run `docker version`]: 20.10.8+azure

## Additional Information
I have also tried a deployment with an explicit Healthcheck specification, but that also did not work
```json
    "modules": {
      "MyModule": {
        "version": "34136",
        "type": "docker",
        "status": "running",
        "restartPolicy": "on-failure",
        "settings": {
          "image": "...",
          "createOptions": "{\"Healthcheck\":{\"Test\",[\"CMD\":\"exit 1\"],\"Interval\":15000000000,\"Timeout\":3000000000,\"Retries\":2,\"StartPeriod\":1000000000}, \"HostConfig\":{\"CapAdd\":[\"SYS_PTRACE\"], \"ExtraHosts\":[\"dockerhost:172.16.99.99\"], \"Binds\":[\"/etc/daikin-software-gateway/:/etc/storage/\"]}}"
        },  
        "env": {
          "storageFolder": {
            "value": "/etc/storage/"
          }   
        }   
      }   
    }  
```

**Comment by gauravIoTEdge** [comment]
@gri6507 - Yes, I'm afraid that policy is also not supported.

Currently, our recommendation is that you use the docker health checks. Like the issue you linked suggested,  you can post it as a suggestion and vote - https://aka.ms/iotedge-suggestion.

I'll work with someone to make sure the documentation reflects this too. Sorry about that.

**Comment by veyalla** [comment]
As workaround, you can achieve the desired result without relying on IoT Edge runtime. For example for the health check below:

```
HEALTHCHECK \
 --interval=30s \
 --timeout=30s \
 --start-period=60s \
 --retries=3 \
 CMD curl -f http://localhost:9070/health || exit 1
```

...use these createOptions:

```
"createOptions": "{\"Healthcheck\":{\"Test\":[\"CMD-SHELL\",\"curl -f http://localhost:9070/health || exit 1\"],\"Interval\":30000000000,\"Timeout\":30000000000,\"Retries\":1,\"StartPeriod\":60000000000},\"HostConfig\":{\"PortBindings\":{\"9070/tcp\":[{\"HostPort\":\"9070\"}]},\"Binds\":[\"/data/misc:/data/misc\"]}}"
```

If you use this approach, ensure `curl` is available in your container image.

**Comment by veyalla** [comment]
9070 is just an example. `/data/misc` is also just a copy/paste artifact and not needed.

The uber point is that only the module knows whether it is healthy or not. So it exposes a binary health signal on a local endpoint of its choosing (9070 in this example). 

Docker engine is configured to periodically call the health endpoint (per the Healthcheck parameters) and crashes the module if unhealthy status is returned. EdgeAgent will subsequently restart the module, and that hopefully *unstucks* the module from a "running but not working" state.

**Comment by veyalla** [comment]
My expectation is that the module exits if the health endpoint indicates unhealthy, which is equivalent to crashing itself. 

Example from heath check above:

```
CMD curl -f http://localhost:9070/health || exit 1
```

**Comment by bqstony** [comment]
Hi @veyalla 

I am digging arount in the issues to find the right way for a working health check in iotedge v1.2.

When i set the the restart policy, in the Manifest, like: modules.{moduleId}.restartPolicy = always, i get always the following result on the edgeHost, no matter what value i use:

```bash
# docker inspect --format '{{json .HostConfig.RestartPolicy}}' mycustommodule| jq
{
  "Name": "",
  "MaximumRetryCount": 0
}

# docker inspect --format '{{json .Config.Healthcheck}}' mycustommodule | jq
{
  "Test": [
    "CMD-SHELL",
    "curl --fail http://localhost:80/health || exit 1"
  ],
  "Interval": 30000000000,
  "Timeout": 10000000000,
  "Retries": 3
}
``` 

I have configured the health in the dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim AS base
WORKDIR /app
EXPOSE 80

HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl --fail http://localhost:80/health || exit 1

# Install prerequisites for healthcheck
RUN apt-get update && apt-get install -y \
    curl && \
    rm -rf /var/lib/apt/lists/*

...
```

what else i have to do for a working restart after my container goes to unhealthy state?

**Comment by veyalla** [comment]
I'm not sure the what the expectation here is. 

The health-check mechanism is transparent to IoT Edge and controlled exclusively by the Docker engine. There will be nothing reflected in Edge Agent's twin. You should just confirm the container is indeed restarted by Docker when health endpoint reports unhealthy.

**Comment by bqstony** [comment]
that is also what i am expecting

**Comment by bqstony** [comment]
After found a few things, i think your solution doesn't work out of the box. Because moby-engine does not support the restart behavior on health probe, see https://github.com/moby/moby/pull/22719 . The restart is triggered by orchestrators like docker swarm (docker-compose) or other tools. 

I Think it should be the job of the edgeAgent. Actually the RestartPolicyManager does only look at the state of the Container and not the Healt. See the remark in the code: https://github.com/Azure/iotedge/blob/719bffd58b353dc0156010ad76ede96c611fb4ef/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/RestartPolicyManager.cs#L24

**Comment by rafaelschlatter** [comment]
I created an issue to ask for the implementation of restart "on-unhealthy" here: https://feedback.azure.com/d365community/idea/32f1a962-70a0-ed11-a81b-6045bd79fc6e 

Please upvote this if you think it is useful.
