### ISSUE TITLE
Multiple deployment instances running after system restart

### ISSUE THREAD

**Issue by jackt-moran** [Azure/iotedge#636]
## Expected Behavior

When the host system is rebooted iotedge should gracefully shutdown and restart and afterward there should only be 1 instance of the deployment running. For example, if the deployment has no custom modules there should only be 1 instance of edgeHub and edgeAgent running.

## Current Behavior

After rebooting the host system there is a duplicate instance of every module specified in the deployment. To isolate the problem I removed all custom modules so there is a duplicate of edgeAgent and edgeHub running. The duplicate edgeHub instance causes the expected edgeHub instance to fail regularly because the duplicate is using all the ports the expected instance expects to use. The duplicate edgeAgent instance runs silently and does not effect the expected edgeAgent instance as far as I can tell.

## Steps to Reproduce

1. Deploy edgeHub and edgeAgent (no custom modules) to an Ubuntu Server 18.04 edge device (give edgeHub the following createOptions: "{\"NetworkingConfig\": {\"EndpointsConfig\": {\"host\":{}} }, \"HostConfig\":{\"NetworkMode\": \"host\", \"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}], \"443/tcp\":[{\"HostPort\":\"443\"}]}}}" ).
2. Perform a system restart on the edge device.
3. After restart completes go to terminal and enter `ps aux | grep /usr/bin/dotnet`.
4. On successful reproduction observe 2 processes running `/usr/bin/dotnet Microsoft.Azure.Devices.Edge.Agent.Service.dll` and 1-2 processes running `/usr/bin/dotnet Microsoft.Azure.Devices.Edge.Hub.Service.dll`

### Device (Host) Operating System

Ubuntu Server 18.04

### Architecture

amd64

### Container Operating System

Linux containers

#### iotedged

iotedge 1.0.4 (2835ac47fbb944ba628a5cfe812ff394768842e0)

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker

Client:
 Version:           3.0.2
 API version:       1.38 (downgraded from 1.40)
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Mon Oct  1 14:25:33 2018
  OS/Arch:          linux/amd64
  Experimental:     false

## Logs

System restart occurred at 20:01:23 UTC/15:01:23 EST

edgeAgent logs: https://gist.github.com/jackt-moran/c826472a20cfd71c4f3e15a31e33e29f

edgeHub logs: https://gist.github.com/jackt-moran/aa0f5721256d6ec6edf3478432efb86a

iotedge logs: https://gist.github.com/jackt-moran/2ad063ec8c783bb6a9ac2db615b2ce15

Output from `ps aux | grep /usr/bin/dotnet`:
```
test-user  1262 52.6  1.2 2740708 104080 ?      SLsl 15:37   0:05 /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Hub.Service.dll
test-user  1830  0.0  0.0  13136  1088 pts/0    S+   15:37   0:00 grep --color=auto /usr/bin/dotnet
root      2955  0.3  0.9 2353336 79460 ?       SLsl 15:04   0:07 /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Agent.Service.dll
test-user  3589  0.6  1.9 2713784 159404 ?      SLsl 15:04   0:13 /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Hub.Service.dll
root      9173  0.4  0.9 2363948 77308 ?       SLsl 15:09   0:07 /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Agent.Service.dll
```
## Additional Information

This problem is occurring on a physical machine. I tried reproducing the issue on a test VM I have, which also runs Ubuntu Server 18.04, and I could not reproduce.

**Comment by myagley** [comment]
This is very strange. If you `docker ps -a` are both instances present, or is it just the `dotnet` processes still running?

**Comment by jackt-moran** [comment]
`docker ps -a` only shows one instance of each container, it is only that there are duplicate `dotnet` processes.

**Comment by myagley** [comment]
Is this behavior reproducible?

**Comment by jackt-moran** [comment]
Hi @darobs thanks for getting back to me and sorry about the delay. We have been able to reproduce this. Here are the outputs to the commands you listed:

```
<omitted>:~$ ps aux | grep /usr/bin/dotnet
root      2802  2.2  0.9 2352840 76808 ?       SLsl 19:10   0:03 /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Agent.Service.dll
test-ip+  3556  7.1  2.1 2744616 170344 ?      SLsl 19:10   0:11 /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Hub.Service.dll
root      4510  3.2  0.9 2355444 74984 ?       SLsl 19:11   0:03 /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Agent.Service.dll
test-ip+  6052  0.0  0.0  13136  1052 pts/0    S+   19:13   0:00 grep --color=auto /usr/bin/dotnet

<omitted>:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                               COMMAND                   CREATED             STATUS              PORTS               NAMES
b93151f960db        mcr.microsoft.com/azureiotedge-hub:1.0              "/bin/sh -c 'echo \"$…"   3 weeks ago         Up 3 minutes                            edgeHub
dcd3e22383a0        <omitted>/datareader:0.0.1-amd64                    "python ./main.py"        3 weeks ago         Up 3 minutes                            dataReader
2381f0daf29f        mcr.microsoft.com/azureiotedge-agent:1.0            "/bin/sh -c 'echo \"$…"   3 weeks ago         Up 2 minutes                            edgeAgent

<omitted>:~$ sudo docker inspect edgeAgent | grep -A 3 Labels
          "Labels": {
              "net.azure-devices.edge.owner": "Microsoft.Azure.Devices.Edge.Agent"
            }
        },

<omitted>:~$ sudo docker inspect edgeAgent --format '{{.State.Pid}}'
4510

<omitted>:~$ sudo docker inspect edgeHub | grep -A 3 Labels
            "Labels": {
                "net.azure-devices.edge.owner": "Microsoft.Azure.Devices.Edge.Agent"
            }
        },

<omitted>:~$ sudo docker inspect edgeHub --format '{{.State.Pid}}'
3556

<omitted>:~$ for c in $(sudo docker ps -aq); do echo -n "$c : "; sudo docker inspect $c --format '{{.Name}} : {{.State.Pid}}'; done
b93151f960db : /edgeHub : 3556
dcd3e22383a0 : /dataReader : 3462
2381f0daf29f : /edgeAgent : 4510
```

If I correctly understand what you mean by "repeat the commands for the containers matching the other process ids", I unfortunately I wasn't able to find the container id of the extra edgeAgent process (the process with PID == 2802).

Interestingly, in our deployment.template.json file the restartPolicy is not specified for edgeAgent. It is specified for edgeHub, but it is specified at the root level of the edgeHub json element, rather than in CreateOptions.HostConfig.RestartPolicy like you suggest. I will experiment with changing these values and update you with the results.

**Comment by myagley** [comment]
This was reproducible on a separate device? Is there any special configuration of docker, changes to the `/etc/docker/daemon.json`, etc that we should be aware of? How are Docker and IoT Edge being installed? Are you using Docker CE, or the Microsoft distribution of Moby for the container runtime?

Is it possible to see the full output of `docker inspect edgeHub`?

Is it possible to find out what the parent process for each of the Edge Agent processes? You can see this with `ps -ef`. They should be parented to a `docker-containerd-shim` process. It seems like at least some of these processes are running outside of the context of docker, which is very strange.

We restart devices all of the time and have never seen this behavior. Any help or information you can provide to help us get a repro is greatly appreciated.

**Comment by jackt-moran** [comment]
Also, here is the output of `docker inspect edgeHub`:

https://gist.github.com/jackt-moran/9c4ab78c8b8c90e1445b61501290ed45

Additionally, in case you need it, here is the output of `docker inspect edgeAgent`:

https://gist.github.com/jackt-moran/cc00667b2d104166f4a1bb38f8f2323b

**Comment by myagley** [comment]
If I'm reading this correctly, it looks like you may have two `dockerd`s running. One via the Moby deb package and one from an Ubuntu Snap. You can verify that docker is installed via snap by running `snap list`.

I could see this behavior occurring if two versions of docker are running with different data directories but using the same socket.

If there is a snap version of docker installed, is it possible to uninstall it and see if this still repros?

**Comment by jackt-moran** [comment]
That sounds possible. My colleague who set the machine up thinks they may have installed it with Ubuntu Snap at the device's provision time.

Unfortunately the device crashed due to a likely unrelated issue and it is in a remote location, so I won't be able to verify this until we get it back up and running.

**Comment by jackt-moran** [comment]
We've recovered the device and have been able to test uninstalling the `snap` version of `docker` - issue resolved!

An interesting (and annoying) side effect of this extra instance of Docker running on our device was that the hard drive got filled to the brim.

Thanks for your help!
