### ISSUE TITLE
metrics-collector changed name and moved

### ISSUE THREAD

**Issue by svenna** [Azure/iotedge#6371]
Hi,

is there a reason why the metrics-collector is renamed to TestMetricsCollector and moved to under test?
We are using the metrics-collector and as far as i understand the module has nothing to do with tests.
it is a module that can send diagnostics regarding a running system?

Has the scope of the metrics-collector changed?

**Comment by gauravIoTEdge** [comment]
Hi @svenna - Not at all. 

We were just reorganizing the code base.  If you get your Metrics Collector from the Azure Marketplace, this should have no impact on you at all.

In case you're using the code, these two PRs will clarify the change: https://github.com/Azure/iotedge/pull/6187 and https://github.com/Azure/iotedge/pull/6233 .

The Metrics Collector we ship to the Azure Marketplace was actually under edge-modules/azure-monitor and the one that was previously under edge-modules/MetricsCollector was largely the same product, but and older version of what was previously under edge-modules/azure-monitor .

It's probably slightly disconcerting, but we simply renamed this in an effort to bring clarity. The scope of the Metrics Collector has not changed.

**Comment by gauravIoTEdge** [comment]
Presumably, the enquiry has been addressed. @svenna , please reopen if you have further questions.
