### ISSUE TITLE
Add support for OpenSSL 3 in version 1.

### ISSUE THREAD

**Issue by Dvergatal** [Azure/iotedge#6388]
Currently iotedge and iotedged does not compile on yocto kirkstone, due to the switch to new OpenSSL 3 release. Are you willing to add support for it?

**Comment by ggjjj** [comment]
Adding this issue for reference. https://github.com/Azure/iot-identity-service/issues/413

**Comment by micahl** [comment]
> Are you willing to add support for it?

Yes, but it won't happen in the near term.  We know we'll have to address it at some point since it is required outside of the changes in yocto kirkstone (i.e. we've seen that Ubuntu 22.04 has also switched to openssl 3.0).

**Comment by micahl** [comment]
@arsing I assume that any future changes to support openssl3 would largely be isolated to the keys service and engine, correct?  If so, I'd propose closing this issue and keeping https://github.com/Azure/iot-identity-service/issues/413.

**Comment by arsing** [comment]
Yes, I can't think of anything that would affect this repo specifically.

**Comment by micahl** [comment]
Thanks for confirming.  Closing this issue in favor of the other.
