### ISSUE TITLE
Behavior when multiple items.id match same module is not clearly documented

### ISSUE THREAD

**Issue by nachoalonsoportillo** [Azure/iotedge#6408]
Documentation doesn't mention that if you specify the same id for different elements in the items array of the payload passed as input to the GetModuleLogs and UploadModuleLogs direct methods, the logOptions used for each module are only those declared in the first appearance of that id in the payload value is honored.

Permalink pointing to the relevant code in [here](https://github.com/Azure/iotedge/blob/01bc4dc5d2a061615773531880e72d104a3998c8/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsRequestToOptionsMapper.cs#L66)

<details>
<summary>Lack of documentation rather than a code defect</summary>
I don't consider this a code defect. It is clearly seen in the code that this behavior is intentional. So, I have created this [PR](https://github.com/MicrosoftDocs/azure-docs/pull/93888) in the documentation to clarify that this is the expected behavior.
</details>

**Comment by ggjjj** [comment]
@micahl Can you comment if we need to make any changes to our documentation in this case?

**Comment by micahl** [comment]
@ggjjj yes, looks like a doc update is warranted.  And it look like @nachoalonsoportillo has submitted a PR with a proposed change already (thanks!).

**Comment by ggjjj** [comment]
Since the documentation is merged. We can close this issue @micahl @nachoalonsoportillo
