### ISSUE TITLE
IoT Edge Container Pull Workflow

### ISSUE THREAD

**Issue by richardleeaus** [Azure/iotedge#641]
Hi

What we've experienced is when we want to update a container to a new tag number, IoT Edge's workflow is to stop the original container, and then it will attempt to pull down the new container, lastly it will then start running the new one.

The issue here is if there are issues with pulling down the new container (which we are getting alot of the time due to transport errors on larger containers), the particular module could be down for sometime. We are starting to use modules in critical situations and we can't have this happen.

Is there any recommendation regarding the above? Is there an ability to pull the container before stopping the original?

Cheers

**Comment by myagley** [comment]
Yes, we are aware of this and are updating the order to pull first. This work won't be complete until January.

There is a workaround to solve the downtime issue in the meantime. You can deploy a module with a different name, with the new image, and set the Desired Status to stopped. This will pull the new image to the device but won't start it. After this is complete, submit a new deployment that removes this module and updates the image tag of the original module.

This workaround is effectively forcing a pull of the module by deploying a stopped module with the new image.

**Comment by myagley** [comment]
This is being fixed by #702 and #656

**Comment by myagley** [comment]
This will land in the `1.0.7` release.

**Comment by myagley** [comment]
This has been released as part of the 1.0.7 release candidate. You can get packages here: https://github.com/Azure/azure-iotedge/releases/tag/1.0.7-rc2
