### ISSUE TITLE
Configure twin while offline

### ISSUE THREAD

**Issue by nesherhh** [Azure/iotedge#645]
We have one IoT Edge device in LAN with many child IoT devices. We need to reconfigure the IoT devices even if the Internet is offline and Azure Cloud is not available.
Is it possible to make twin configuration directly on edge device while it is offline?

**Comment by myagley** [comment]
Thanks for the suggestion. We have an item on the roadmap to allow modifying the desired properties of a twin on the edge. However, this hasn't been implemented or scheduled yet.

**Comment by gabrielpereirapinheiro** [comment]
Hello ! I would like to configure local desired properties in case of the azure stays offline . Until now i'm trying to do in that way :


            if (desiredProperties.Contains(SnmpSlaves))
            {
                 get config from Twin
               jsonStr = serializedStr;
            }
            else
            {

    
                Console.WriteLine("No configuration found in desired properties, look in local...");
                if (File.Exists(@"iot-edge-snmp.json"))
                {
                    ....
                }
            }

But i don't know where I have to put my json file with my configures .

**Comment by nonoxp** [comment]
Hi,
Any updates on this item? We have more and more customers asking for the same capability.

**Comment by mma-mm** [comment]
That would also be helpful for us.

**Comment by wesselkranenborg** [comment]
It would also be helpful for us.

**Comment by simardst** [comment]
This features would be awesome.  We also need to find a way to change configuration while offline, and be able to use the device twin to do this (as we do it when online) would greatly simplified the whole thing. The only issue remaining would be: How to we synchronize the device twin desired properties when the device goes back online.

**Comment by corollaries** [comment]
Would be incredibly helpful if this could be implemented. We're relying heavily on twins for our IoT Edge modules. Not having access to this while the device is offline would make the offline scenario's very difficult. We could mitigate this issue by using other communication channels, but using the twin would be preferable. Is there any update on this?

**Comment by veyalla** [comment]
This is on the longer term roadmap but not prioritized. Please file or vote for a suggestion on the feedback portal: https://feedback.azure.com/forums/907045-azure-iot-edge

**Comment by corollaries** [comment]
I filed a suggestion on the feedback portal that can be found here:
https://feedback.azure.com/forums/907045-azure-iot-edge/suggestions/40748023-support-configuring-twin-in-offline-scenarios.
