### ISSUE TITLE
How can build edgeHub module according to DockerFile

### ISSUE THREAD

**Issue by v-jiq** [Azure/iotedge#647]
I want to build a  arm32v7 edgeHub module according to this DockerFile ....../edge-hub/docker/linux/arm32v7/Dockerfile. but when I use command "docker run -it docker_images_name  /bin/bash" join in the edgehub module that I build then run command  "exec /usr/bin/dotnet Microsoft.Azure.Devices.Edge.Hub.Service.dll" will not successful and prompt below log:
![1544709952 1](https://user-images.githubusercontent.com/39880470/49943694-8aa7ef80-ff23-11e8-9b4e-3d1b59fb8fad.png)

the /app list:
![1544709940 1](https://user-images.githubusercontent.com/39880470/49943630-60eec880-ff23-11e8-8cb8-3b159f7c143b.png)

Backgroup：
I want to add some feature on edgehub module. So, need to rebuild it . 

what I need to notice in during build edgehub module?

Thanks .

**Comment by myagley** [comment]
You can see how these images are built by looking at the build scripts:

Linux: https://github.com/Azure/iotedge/blob/master/scripts/linux/buildImage.sh
Windows: https://github.com/Azure/iotedge/blob/master/scripts/windows/build/Publish-DockerImage.ps1

We typically build the dlls and then copy them into the docker image. The base images don't contain the dotnet sdk. They only contain the dotnet runtime.

**Comment by v-jiq** [comment]
Got it ,Thanks !!
