### ISSUE TITLE
Incorrect binary for IoT Edge 1.1.15-1 on Debian 11

### ISSUE THREAD

**Issue by ksaye** [Azure/iotedge#6504]
## Expected Behavior
Per the documentation here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal%2Cdebian#install-iot-edge the instructions to install Edge 1.2 on Debian 11 is:
```
curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
sudo apt install ./packages-microsoft-prod.deb

sudo apt-get update
sudo apt-get install iotedge
``` 
Which I would expect to work on an amd64 device.

## Current Behavior
Following the instructions above, the package https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb is only valid for armhf as shown below:

```
upgrade3@upgrade3:~$ uname -a
Linux upgrade3 5.10.0-16-cloud-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

upgrade3@upgrade3:~$ cat /etc/issue
Debian GNU/Linux 11 \n \l

upgrade3@upgrade3:~$ sudo apt search iotedge
Sorting... Done
Full Text Search... Done

upgrade3@upgrade3:~$ curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb

upgrade3@upgrade3:~$ sudo apt install ./packages-microsoft-prod.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'packages-microsoft-prod' instead of './packages-microsoft-prod.deb'
The following NEW packages will be installed:
  packages-microsoft-prod
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3134 B of archives.
After this operation, 43.0 kB of additional disk space will be used.
Get:1 /home/upgrade3/packages-microsoft-prod.deb packages-microsoft-prod all 1.0-debian11.1 [3134 B]
Selecting previously unselected package packages-microsoft-prod.
(Reading database ... 21359 files and directories currently installed.)
Preparing to unpack .../packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-debian11.1) ...
Setting up packages-microsoft-prod (1.0-debian11.1) ...

upgrade3@upgrade3:~$ sudo apt update
Hit:1 http://debian-archive.trafficmanager.net/debian bullseye InRelease
Hit:2 http://debian-archive.trafficmanager.net/debian-security bullseye-security InRelease
Hit:3 http://debian-archive.trafficmanager.net/debian bullseye-updates InRelease
Hit:4 http://debian-archive.trafficmanager.net/debian bullseye-backports InRelease
Get:5 https://packages.microsoft.com/debian/11/prod bullseye InRelease [10.5 kB]
Get:6 https://packages.microsoft.com/debian/11/prod bullseye/main arm64 Packages [13.2 kB]
Get:7 https://packages.microsoft.com/debian/11/prod bullseye/main amd64 Packages [68.1 kB]
Get:8 https://packages.microsoft.com/debian/11/prod bullseye/main armhf Packages [15.8 kB]
Fetched 108 kB in 1s (184 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

upgrade3@upgrade3:~$ sudo apt search iotedge
Sorting... Done
Full Text Search... Done
iotedge/bullseye 1.1.15-1 armhf
  Azure IoT Edge Security Daemon
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. create a Debian 11 on amd64 VM in Azure and log in
2. run curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
3. run sudo apt install ./packages-microsoft-prod.deb
4. run sudo apt update
5. run sudo apt search iotedge

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by micahl** [comment]
@PatAltimore we should add a qualifier to the Debian 11 install instructions that its only for arm32v7 devices similar to how [on RHEL8](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal%2Crhel#install-iot-edge) we note its only for amd64.

**Comment by PatAltimore** [comment]
@micahl and @ksaye, 

Added qualifier **11 - Bullseye (arm32v7)**.  Change has been merged and will be published tomorrow morning.

**Comment by micahl** [comment]
Thanks @PatAltimore for adding the qualifier in docs.  @ksaye we've only published to packages.microsoft.com for the OS + platforms that are in the [Tier 1 list](https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2018-06#linux-containers).
