### ISSUE TITLE
edgeAgent Doesn't Start on Downstream Device 

### ISSUE THREAD

**Issue by savastosic** [Azure/iotedge#6532]
## Current Behavior
Tell us what happens instead of the expected behavior

IoT Edge starts perfectly fine before connecting in an nested edge configuration, but when I try to configure the Parent_Hostname on the child device, the edgeAgent no longer starts. The parent device is running fine. 

**Using the following config file (Note that parent_hostname is commented out):** 
#parent_hostname = "ParentIP"
trust_bundle_cert = "file:///var/secrets/azure-iot-test-only.root.ca.cert.pem"
[provisioning]
source = "manual"
connection_string = ""
[edge_ca]
cert = "file:///var/secrets/iot-edge-device-ca-Child-full-chain.cert.pem"
pk = "file:///var/secrets/iot-edge-device-ca-Child.key.pem"

[agent]
name = "edgeAgent"
type = "docker"

[agent.config]
image = "ParentIP:443/azureiotedge-agent:1.3"

edgeAgent starts up using Parent image: 
![image](https://user-images.githubusercontent.com/90868835/180504986-096803f1-3b10-4e16-a4f2-ac39afe9cdab.png)

System status is good:
![image](https://user-images.githubusercontent.com/90868835/180505124-5afe960c-70f2-40b2-a97c-612a55b0e731.png)

Docker image for the agent is running fine: 
![image](https://user-images.githubusercontent.com/90868835/180505232-9971b858-36af-4977-9061-9c5cc89e0e60.png)

The modules are configured according to the documentation, and the child device is set to pull from $upstream, instead of mcr.microsoft.com. But they do not. Here is the sudo iotedge check results:
![image](https://user-images.githubusercontent.com/90868835/180505965-7d8b2669-cafe-4a61-b5f0-234271915e1a.png)

**When I Uncomment the Parent_Hostname in the Config File**
edgeAgent can no longer start: 
![image](https://user-images.githubusercontent.com/90868835/180506372-2c885874-5301-42e9-ace5-9ce9f63ac911.png)

Docker image seems to exit: 
![image](https://user-images.githubusercontent.com/90868835/180506455-73304d4f-058e-4663-b1d6-3a1eab3c037a.png)

Errors in system logs: 
![image](https://user-images.githubusercontent.com/90868835/180506509-74b6de5b-feb4-4869-9d9b-a90a9922ea6c.png)

Results of iotedge check
![image](https://user-images.githubusercontent.com/90868835/180506639-41145e19-a95a-4ce7-96fa-9f14d475eb0b.png)

**Things I Have Checked**

- Set Module configurations have been checked, and match documentation. 
- VMs have inbound and outbound ports open to 443, 5671, 8883
- The following command has been run and looks good (azureUser@child-vm:~$ echo | openssl s_client -connect 10.0.0.4:8883 2>/dev/null | openssl x509 -text) 
- Everything on the parent VM is looking great: 
![image](https://user-images.githubusercontent.com/90868835/180508435-92ba78e3-556e-45d1-9fc8-3ed8afb5786f.png)

I have also tried to remove the docker image as suggested between changing the hostname, and it seems the image will not restart in that case.
![image](https://user-images.githubusercontent.com/90868835/180507818-0e8b3023-0112-4416-b214-0702d162bebc.png)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
I am following the nested edge documentation exactly as written, using two Ubuntu 20.04 VMs. 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-iot-edge-device?view=iotedge-2020-11&tabs=azure-portal

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 20.04
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.3
* Edge Agent [image tag (e.g. 1.0.0)]: 1.3
* Edge Hub [image tag (e.g. 1.0.0)]: 1.3
* Docker/Moby [run `docker version`]:  20.10.17+azure-1

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

Jul 22 19:17:39 ChildDevice systemd[1]: aziot-edged.service: Succeeded.
Jul 22 19:17:39 ChildDevice systemd[1]: Stopped Azure IoT Edge daemon.
Jul 22 19:17:39 ChildDevice systemd[1]: Stopping Azure IoT Identity Service...
Jul 22 19:17:39 ChildDevice systemd[1]: aziot-identityd.service: Succeeded.
Jul 22 19:17:39 ChildDevice systemd[1]: Stopped Azure IoT Identity Service.
Jul 22 19:17:39 ChildDevice systemd[1]: Stopping Azure IoT Keys Service...
Jul 22 19:17:39 ChildDevice systemd[1]: aziot-keyd.service: Succeeded.
Jul 22 19:17:39 ChildDevice systemd[1]: Stopped Azure IoT Keys Service.
Jul 22 19:17:39 ChildDevice systemd[1]: Stopping Azure IoT Certificates Service...
Jul 22 19:17:39 ChildDevice systemd[1]: aziot-certd.service: Succeeded.
Jul 22 19:17:39 ChildDevice systemd[1]: Stopped Azure IoT Certificates Service.
Jul 22 19:17:39 ChildDevice systemd[1]: Started Azure IoT Edge daemon.
Jul 22 19:17:39 ChildDevice aziot-edged[7882]: 2022-07-22T19:17:39Z [INFO] - Starting Azure IoT Edge Daemon
Jul 22 19:17:39 ChildDevice aziot-edged[7882]: 2022-07-22T19:17:39Z [INFO] - Version - 1.3.0
Jul 22 19:17:39 ChildDevice aziot-edged[7882]: 2022-07-22T19:17:39Z [INFO] - Obtaining Edge device provisioning data...
Jul 22 19:17:39 ChildDevice systemd[1]: Started Azure IoT Identity Service.
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Starting service...
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Version - 1.3.0
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Provisioning starting. Reason: Startup
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Updated device info for ChildDevice.
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Provisioning complete.
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Identity reconciliation started. Reason: Startup
Jul 22 19:17:39 ChildDevice systemd[1]: Started Azure IoT Keys Service.
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - Starting service...
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - Version - 1.3.0
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - Loaded libaziot-keys with version 0x02010000
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - Starting server...
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "382"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "382"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Could not reconcile Identities with current device data. Reprovisioning.
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [INFO] - Updated device info for ChildDevice.
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "382"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "382"}
Jul 22 19:17:39 ChildDevice aziot-keyd[7888]: 2022-07-22T19:17:39Z [INFO] - --> 200 {"content-type": "application/json"}
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: Hub client error
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [ERR!] - service encountered an error
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [ERR!] - caused by: Hub client error
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [ERR!] - caused by: invalid HTTP status code
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]: 2022-07-22T19:17:39Z [ERR!] -    0: <unknown>
Jul 22 19:17:39 ChildDevice aziot-identityd[7885]:    1: <unknown>
Jul 22 19:17:39 ChildDevice systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Jul 22 19:17:39 ChildDevice systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Jul 22 19:17:44 ChildDevice systemd[1]: aziot-identityd.service: Scheduled restart job, restart counter is at 1.
Jul 22 19:17:44 ChildDevice systemd[1]: Stopped Azure IoT Identity Service.
Jul 22 19:17:44 ChildDevice aziot-edged[7882]: 2022-07-22T19:17:44Z [WARN] - Failed to send HTTP request (attempt 1 of 2): connection error: Connection reset by peer (os error 104)
```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by savastosic** [comment]
Hey Hugues, 

Yes I just avoided putting the connection string in the post. 

Iotedge check verbose: 
![image](https://user-images.githubusercontent.com/90868835/180842737-2a45c41d-b1d9-480e-a4d1-70f0e56a8023.png)

APIproxy gives the following message on repeat: 
![image](https://user-images.githubusercontent.com/90868835/180842859-c338adad-5374-4b1e-9b8e-a48cab37a5f7.png)

Not sure what you mean by logs for the IoT Hub?

**Comment by savastosic** [comment]
Update: I was able to resolve this issue.

The documentation notes that you should replace the runtime settings with "$upstream" in the image URI.
![image](https://user-images.githubusercontent.com/90868835/180848462-62c8f340-4968-4f2f-beaf-d1430b921f01.png)

However, it seems this doesn't work. Instead of using the "$upstream" shortcut, I explicitly defined the parent IP address and everything seems to be running fine now. 
![image](https://user-images.githubusercontent.com/90868835/180848992-4b416157-6ca0-4ce1-8832-6c484042ae32.png)

Documentation link: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-iot-edge-device?view=iotedge-2020-11&tabs=azure-portal

**Comment by huguesBouvier** [comment]
Thanks for reporting the issue! 

**Note: that $upstream can also be used in the config.yaml file instead of parentIP.**

I checked our pipeline and we are running the tests using $upstream with a problem: https://github.com/Azure/iotedge/blob/release/1.3/e2e_deployment_files/nestededge_middleLayer_e2e_amqp.json.

There might be something else: 
If you still want to troubleshoot it, looking at the logs, can you see what address was $upstream replaced with (otherwise it will be in docker logs)?
Did it the children manage to download at least one container (edgeAgent?).

One thing that could potentially have happened: $upstream is replaced by "parent hostname" from the config. If you changed the config, make sure to clean the containers because they are persistent! Killing the containers ensure they are reloaded with the right config.

**Comment by savastosic** [comment]
The reason I was hesitant to use "$upstream" in the config was due to a line in the documentation! The example here sounds like it warns against it.  
![image](https://user-images.githubusercontent.com/90868835/180874492-db5369df-9b26-47da-b255-e1129377156c.png)

I will dive deeper into this a bit later as I am curious myself, but it looks like edgeAgent fails to start when that parent_hostname is not commented out. You'll see from my original post that after I kill the containers, they don't start up again. 

For now I will stick to the manually defined hostnames, and revisit this with $upstream later. I'll open up a new issue if I still have a problem then. 

Appreciate the help!

**Comment by 2635891552** [comment]
Hello, I have encountered the same problem as you, have you solved it?
