### ISSUE TITLE
createOptions HostConfig configuration doesn't work on k3s deployments

### ISSUE THREAD

**Issue by cjaca** [Azure/iotedge#6533]
## Expected Behavior

After configuring the following memory limits in the createOptions docker module running on k3s:

```json
"createOptions": {
  "HostConfig": {
    "Memory": 268435456
  }
}
```

I don't see these limits being set on the new deployment of the module using the command:
```bash
kubectl get deployment <module_name>
```
Under *.resources.requests.*

I can see **only** the default requests for a proxy container in this pod.

Is there any chance to get those memory requests in the deployment configuration?

**Comment by huguesBouvier** [comment]
Can you please add some details like the version you are using? k3s is not supported in 1.2 and 1.3

**Comment by cjaca** [comment]
Hi @huguesBouvier, the version of edgeAgent and edgeHub that I'm using is 1.1:

- ` mcr.microsoft.com/azureiotedge-agent:1.1 ` 
- ` mcr.microsoft.com/azureiotedge-hub:1.1 `

**Comment by huguesBouvier** [comment]
Thanks! You are correct, looking at the code it seems that it is not supported for k3s.
I can't commit to us adding this feature in current 1.1, it is possible it will be supported in later version.

**Comment by micahl** [comment]
From [our docs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-kubernetes#sample):

> A functional sample for running IoT Edge on Azure Kubernetes Service (AKS) using KubeVirt is available at https://aka.ms/iotedge-kubevirt.
> ![image](https://user-images.githubusercontent.com/1009123/182740558-eee0b94a-546a-41da-b63d-9c41e41ad55f.png)
