### ISSUE TITLE
[Question] - How to workaround of the environment variable limitation of 4096 bytes?

### ISSUE THREAD

**Issue by F-Joachim** [Azure/iotedge#6547]
I'm trying to pass the module configuration via environment variable. But the Azure CLI throws an error, that there is a limitation of 4096 bytes:

```
ERROR: {'Message': 'ErrorCode:ArgumentInvalid;Property or Tag value should be maximum 4096 bytes. Error in Property/Tag...
```

What are the suggested way to pass static configuration to a module?

**Comment by micahl** [comment]
@F-Joachim, the deployment manifest is provided to IoT Edge via a twin and IoT Hub limits the maximum size of each individual property in every section to 4KB (see [IoT Hub limits](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling?view=iotedge-2020-11#other-limits)).  That seems to be the issue you're hitting here similar to #5921.  The suggestions given in that issue seem like they'd still be relevant here.

**Comment by F-Joachim** [comment]
@micahl. Sorry for the duplication of the issue. I have not remembered this issue :-O
