### ISSUE TITLE
Typo in RPM command used for querying RPM version

### ISSUE THREAD

**Issue by contre** [Azure/iotedge#6548]
The line referenced below uses the flag --querryformat when it should instead be --queryformat

https://github.com/Azure/iotedge/blob/38f06e42fd910e9d1e6dabbc1daf2d1f79c6a58a/edgelet/build/linux/package-mariner.sh#L76

**Comment by micahl** [comment]
@josephknierman?

**Comment by josephknierman** [comment]
Have multiple fixes including the one mentioned here in the PR https://github.com/Azure/iotedge/pull/6526

**Comment by contre** [comment]
We can close out the issue and the PR I raised then if you wish

**Comment by micahl** [comment]
I'm closing this issue and leave it up to you guys to bring one of the PRs to closure.
