### ISSUE TITLE
IdentityNotMappedException

### ISSUE THREAD

**Issue by shaeussler** [Azure/iotedge#655]
## Expected Behavior
SecurityDaemon installation runs without error.

## Current Behavior
SecurityDaemon installation stops with IdentityNotMappedException error. 

## Steps to Reproduce

1. . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -Manual -DeviceConnectionString $deviceConnectionString -ContainerOs Linux

### Device (Host) Operating System
Windows 10 1809

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
1.0.5

#### Docker
Docker version 18.09.0, build 4d60db4

## Logs
Docker is running.
The container host is on supported build version 17763.
Downloading IoT Edge security daemon...
Using IoT Edge security daemon from C:\xxxxx\AppData\Local\Temp\iotedged-windows.zip
Install-SecurityDaemon : Ausnahme beim Aufrufen von "AddAccessRule" mit 1 Argument(en):  "Manche oder alle Identitätsverweise konnten nicht übersetzt werden."
In Zeile:2 Zeichen:1
+ Install-SecurityDaemon -Manual -ContainerOs Linux
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-SecurityDaemon], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException,Install-SecurityDaemon

## Additional Information
The call to AddAccessRule generates the IdentityNotMappedException.
If I change the value from  'NT AUTHORITY\Authenticated Users' to 'mydomainname\myusername', the installation works.

**Comment by sebader** [comment]
Sounds like you are using a German-localized system?! Maybe the built-in group name is localized as well and that might be causing the issue.

Btw, why are you using Linux containers if your are running Windows 1809?

**Comment by shaeussler** [comment]
I'm using Windows 10 Professional, version 1809(Build 17763.194), runing docker CE and using linux containers.

**Comment by shaeussler** [comment]
Yes, I'm using a German-localized system.

**Comment by sebader** [comment]
Can you change that line in the script
`$rule = New-Object -TypeName System.Security.AccessControl.FileSystemAccessRule(
'NT AUTHORITY\Authenticated Users', 'Modify', 'ObjectInherit', 'InheritOnly', 'Allow')`

to

`$rule = New-Object -TypeName System.Security.AccessControl.FileSystemAccessRule('NT-Autorität\Authentifizierte Benutzer', 'Modify', 'ObjectInherit', 'InheritOnly', 'Allow')`

and test if it works then?

**Comment by shaeussler** [comment]
The script works with 'NT-Autorität\Authentifizierte Benutzer'.

**Comment by sebader** [comment]
@damonbarry @veyalla Looks like the installer script has issues with non-English systems

**Comment by myagley** [comment]
We should be using the security id `S-1-5-11` instead of the username `NT AUTHORITY\Authenticated Users`. We will get this updated.

**Comment by EnNico** [comment]
I have the same problem as described by @shaeussler. In order to apply the solution to edit the script, but which script, i cant find it.

**Comment by sebader** [comment]
From here: https://github.com/MicrosoftDocs/azure-docs/issues/21559#issuecomment-451419310

> 
> You can download the script from here: **aka.ms/iotedge-win** and save it locally as "IotEdgeSecurityDaemon.ps1".
> 
> After, you should edit the script as suggested here and then run the following command:
> 
> "C:\locationofthescript\IotEdgeSecurityDaemon.ps1" | Invoke-Expression; ` 
> Install-SecurityDaemon -Manual -ContainerOs Windows

**Comment by EnNico** [comment]
Hm i have downloaded the script and applied the edit for the given line, but the same error still occurs.
Is there some other way of workaround for this problem, or how can i make sure that the "username" is the right one for the rule?
Thanks in advance.

**Comment by EnNico** [comment]
I am also running on German, but German (Austria)

**Comment by EnNico** [comment]
@sebader thanks for your help, the issue was due to blank spaces in the script line for the rule... saw it in the debugger, now it works for me!

**Comment by Futtrup87** [comment]
> @sebader thanks for your help, the issue was due to blank spaces in the script line for the rule... saw it in the debugger, now it works for me!

Are you using Windows or Linux containers?
Can you tell me a little about how you debug the solution (The IoTEdge)?

**Comment by EnNico** [comment]
@Futtrup87 I am using Windows containers. 
I debugged the Powershell script in the Windows Powershell ISE Editor and inspected the values for the rule.
