### ISSUE TITLE
Support for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by codeminic** [Azure/iotedge#6555]
Hi!

We would like to use Ubuntu 22.04 on our edge devices, because the ethernet interface in the devices is not supported in the kernel shipped with Ubuntu 20.04. Looking at the [list of supported OS](https://docs.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2020-11&preserve-view=true#linux-containers), it is not mentioned. Do you plan to support Ubuntu 22.04 LTS in the future or is there a reason why it can't be supported?

Thanks in advance for your feedback!

**Comment by codeminic** [comment]
FYI @JoshouaDPE

**Comment by and-rewsmith** [comment]
@micahl Are we planning to support this in the foreseeable future?

**Comment by micahl** [comment]
Yes, but no definite ETA to share yet.  To support 22.04 requires that we first move from openssl 1.1 -> 3.0 (see https://github.com/Azure/iot-identity-service/issues/413).

Fwiw, installing an earlier version of openssl on 22.04 may unblock installing latest versions of IoT Edge on 22.04, but note that is not an officially supported scenario.

**Comment by codeminic** [comment]
@micahl thx for the feedback 👍

**Comment by jerfcero** [comment]
With the release of ubuntu 22.04 LTS and IotEdge 1.4 LTS. It would be good to have a solution pair of operating system and long-term support agent.

**Comment by DamianSuess** [comment]
Any word on where this issue stands on the backlog?

**Comment by micahl** [comment]
Short answer: Under development. 

Long answer: The identity service needs to add support before iot edge.  The work so far enables it in the main branch for the identity service (see https://github.com/Azure/iot-identity-service/commit/f66c155113cce5089d398376d16b206f7973d6f6).  That change will need to be taken to the release/1.4 branch.  And then adding support in the iotedge repo along with updating test pipelines, automated publishing, etc.

**Comment by DamianSuess** [comment]
Thank you @micahl, I really appreciate the quick feedback.  We just upgraded our hardware specs to use v22.04 and .NET 6 and unfortunately had to roll back after it hosed the `dotnet` installation. Rather than doing ad-hoc workarounds, we'd prefer to wait for the official solution - _as this is going into production. Thank you again, sir

**Comment by klaas-thoelen** [comment]
Is there an ETA for the Ubuntu22.04 support? Would help a lot in planning our upcoming maintenance/upgrade round.
Thanks for the efforts!

**Comment by micahl** [comment]
@klaas-thoelen best case scenario is by end of this year.  Sometimes unknowns appear when adding a platform that make including it less linear.

Cc @damonbarry

**Comment by DamianSuess** [comment]
That would be a wonderful (post) Christmas gift. Thank you, @micahl

**Comment by klaas-thoelen** [comment]
That is very helpful, thanks @micahl

**Comment by kedrzu91** [comment]
Are there any news regarding this issue?

**Comment by micahl** [comment]
We need to chase down an issue we saw in our end-to-end tests right before the holiday break.  It's related to our use of openssl 3.  We have a lot of the infrastructure in place otherwise (https://github.com/Azure/iotedge/pull/6801).

**Comment by micahl** [comment]
Just an update for anyone watching this issue... we suspect that the test failure we've been seeing is related to the machine setup used up by the test accidentally had both openssl 1.1 and openssl 3.0 installed.  Investigating...

**Comment by micahl** [comment]
Closing this issue.  Asks / feature improvement ideas (such as this one) technically should be logged at https://aka.ms/iotedge-suggestion.

But fwiw, we did just merge work in the iotedge repo to add 22.04 to our build/test pipeline (https://github.com/Azure/iotedge/pull/6801).  Taking that to our release/1.4 branch and officially publishing the bits to packages.microsoft.com will be pending internal sign-off and then the next available release opportunity.

**Comment by DamianSuess** [comment]
Thank you @micahl you're the best!

**Comment by jelalanne** [comment]
Hello @micahl , will it be mentionned here when that build is available?

**Comment by micahl** [comment]
@jelalanne we would plan to put an announcement in the [Azure Updates feed tagged with the Internet of Things category](https://azure.microsoft.com/en-us/updates/?category=iot) similar to in the past when we've expanded (or reduced) OS targets.

**Comment by micahl** [comment]
Jfya, the official announcement should appear next week, but we've already published the packages for 22.04 (amd64 + arm64) and updated our docs ([for example](https://learn.microsoft.com/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.4&tabs=azure-portal%2Cubuntu#install-iot-edge)).
