### ISSUE TITLE
After 3 months without any errors events could not be sent from the custom module to the IoT Hub because of TLS authentication error  

### ISSUE THREAD

**Issue by draganrmijailovic** [Azure/iotedge#6562]
## Expected Behavior
Events could be sent from the custom module to the IoT Hub without any errors.

## Current Behavior
Events were sent from the custom module to the IoT Hub for almost 3 months without any errors. The IoT Edge device uses a default temporary certificate - we didn't install our certificate. But, suddenly, we got TLS authentication errors and the events could not be sent to the IoT Hub (the screenshot of the source code and the error have been attached).

**We had to restart the IoT Edge device since it is our Production's IoT Edge device. There are any errors after restarting but probably the error will happen again.** 

Before we updated the IoT Edge to version 1.2.8 because of the following issue https://github.com/Azure/iotedge/issues/6008

Please, ignore the **metricsCollector** custom module since it is in an invalid state for a long time.
 
## Steps to Reproduce
We can't reproduce the bug.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.2.6 but 1.3.0 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
‼ aziot-edge package is up-to-date - Warning
    Installed IoT Edge daemon has version 1.2.8 but 1.3.0 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
30 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
</details>

### Device Information
* Host OS: Ubuntu 18.04 
* Architecture: amd64 
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]:  1.2.8
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]:  1.2
* Docker/Moby [run `docker version`]: 20.10.14+azure-1

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.
![Custom module - IoT Edge Logs - TLS Authentication error](https://user-images.githubusercontent.com/28098446/182689588-03bdb1d0-ad5d-43ef-bf53-458e607e9494.jpg)
![Custom module - source code](https://user-images.githubusercontent.com/28098446/182689635-504466b0-af4f-442d-aa73-c7c2361d9d2a.jpg)
![Custom modules - IoT Edge Hub connections](https://user-images.githubusercontent.com/28098446/182689669-3773c7ab-53fa-4ff1-87ec-5d7ba0797c9c.jpg)
![IoT Edge Device - Overview](https://user-images.githubusercontent.com/28098446/182689691-9bf81669-c86a-49b7-a85a-8cbacdf16840.jpg)
[support_bundle.zip](https://github.com/Azure/iotedge/files/9254322/support_bundle.zip)

**Comment by and-rewsmith** [comment]
This is by design. These temporary certs aren't meant for production. You will need production certificates to avoid this.

More information:
https://docs.microsoft.com/en-us/azure/iot-edge/production-checklist?view=iotedge-2020-11#install-production-certificates

**Comment by draganrmijailovic** [comment]
Thanks, @and-rewsmith for your answer. We are working on the installation of production certificates. The issue can be closed.
