### ISSUE TITLE
Enhancement: When specifying proxy during installation, also set proxy for Edge runtime

### ISSUE THREAD

**Issue by sebader** [Azure/iotedge#657]
## Expected Behavior

The Windows installer does support proxy now to download all the required components. Great! But in most setups where you would use that, your Edge runtime (daemon, agent and hub) would also need to use (the same) proxy to reach IoT Hub. 
So it would be a great enhancement to take the supplied proxy information and put it in the required places as well (config.yaml for the agent and registry key for the daemon).
## Current Behavior

After the installation, Edge automatically starts up. But of course fails to connect to IoT Hub because the daemon doesn't know about the proxy. So the user needs to do all the steps manually and then restart the service.

**Comment by veyalla** [comment]
Please file or vote for a feature enhancement at https://feedback.azure.com/forums/907045-azure-iot-edge
