### ISSUE TITLE
edgeHub failing due to 'sdk hanging'

### ISSUE THREAD

**Issue by DarthLowen** [Azure/iotedge#6578]
## Expected Behavior
Our setup is the following: industrial equipment sends out 2 UDP packets every second, an IoT edge server is the gateway for these machines towards the cloud. In larger networks with (for example) 200 machines, edgeHub uses a large amount of processing power and fails after some time with an error, explaining the SDK is hanging. (see logs below). We have several containers running, 1 container receives the UDP packets (400/sec, through logging detected that we do in fact receive and parse all these UDP packets) and forwards them to edgeHub (using ModuleClient.SendEventAsync), routes are in place to forward these packets to 2 other containers, generating in total probably 1200 messages/sec. This runs on an industrial PC with ubuntu 18.04, quad-core intel celeron processor and 4GB RAM. I would expect this to be sufficient for 1200 messages/second. All code in our modules is written in .net core 3.1

## Current Behavior
The container that sends the messages takes up all memory after some time (after a few hours), edgeHub container uses 200% CPU (according to ```top```) and after a while, the edgeHub module fails with mention of 'ProtocolGatewayException', 'Error due to sdk hanging and upstream call timed out', 'EdgeHubCloudSDKException', ... and Mayhem ensues... Also, the container that sends the messages happily keeps on sending data (and taking up all the memory), it does not seem to detect the ModuleClient connection is down.

## Steps to Reproduce
~~Right now, this occurs at our customers and in testing environments, there is no easy way to reproduce~~
Run the test solution as provided below in comment

### Output of `iotedge check`

```iotedge check``` does not yield any warnings nor errors

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.3.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.3.0
* Edge Hub [image tag (e.g. 1.0.0)]: 1.3.0
* Docker/Moby [run `docker version`]: 20.10.11+azure-3

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>

[iotedged-log.txt](https://github.com/Azure/iotedge/files/9287539/iotedged-log.txt)

<summary>aziot-edged logs</summary>

</details>

<details>
<summary>edge-agent logs</summary>

[edgeAgent-log.txt](https://github.com/Azure/iotedge/files/9287550/edgeAgent-log.txt)

</details>

<details>
<summary>edge-hub logs</summary>

[edgeHub-log.txt](https://github.com/Azure/iotedge/files/9287547/edgeHub-log.txt)

</details>

## Additional Information
I removed most of the irrelevant logs in the edgeHub, The interesting messages start at 11:44:26 when the edgehub starts reauthenticating. It doesn't seem to recover from that.

**Comment by DarthLowen** [comment]
PS: limiting the memory of the container that sends the messages, doe not cause garbage collection to occur sooner, it just kills the process because it is out of memory. This is a nice fail-safe, but not intended behaviour

**Comment by DarthLowen** [comment]
I have created a test solution with 2 modules, 1 sender module that sends 400 messages per second (256 bytes) and 2 receiver modules (2 containers based on same image) that receive them. I added some Console.WriteLines showing that the system is not capable of sending/receiving this amount of messages. This was tested in a simulator (Ubuntu 20.04 vmware image)
[MessageFloodSim.tgz](https://www.dropbox.com/s/8zbbw26pydr4lse/MessageFloodSim.tgz?dl=0)

Can you confirm that I'm reaching the limit of this setup? 400 messages/sec is too much?

**Comment by nyanzebra** [comment]
Hello @DarthLowen

The 'sdk hanging' error message is due to a workaround of an SDK error (edge uses the same C# SDK to communicate to IoTHub as you use from your modules). As you can see from the logs, you use mqtt to talk to edge hub, however you use amqp to communicate upstream (between edge and iot hub) - that is usually ok, but the 'sdk hanging' appears with higher odds using amqp.

Is it possible to switch to mqtt upstream and see how it works, that way maybe you can avoid running into the sdk problem.

Regarding the 400msg/sec, it is higher than what people usually try with edge. Edge's main purpose wasn't performance when it was designed (but to mirror IoTHub for offline scenarios and to do message preprocessing with modules). Yet, it should be ok with 400msg/sec on a normal pl. Let us take a look at your test.

**Comment by nyanzebra** [comment]
So, I tried to replicate and things seem to be working. Let me know if I have something different, below is my info from testing:

Version:
iotedge 1.3.0

Status:
![image](https://user-images.githubusercontent.com/6096983/184030120-be562a7e-a184-455b-b808-85ccd9640efa.png)

Specs:
![image](https://user-images.githubusercontent.com/6096983/184030045-8edf6ac1-3633-4636-8a38-afc968eec03a.png)

Top:
![image](https://user-images.githubusercontent.com/6096983/184029934-d4ae22be-ec30-46f7-88c1-e5aa1a97872e.png)

**Comment by DarthLowen** [comment]
Hi @nyanzebra,

Thanks for testing, however the SDK issue I think is indeed not present in this demo. The modules I created were more for the missing packets/performance issue. I agree it's confusing, I'm starting off with an SDK exception and I'm supplying modules to test something else. To me these items have always been linked (which I understood they're not because it would be an AMQP related-thing?). I'll see if I can add a route to $upstream and send some packets to the iothub (we have 1 packet every 3s going upstream), according to your theory that should trigger the SDK exception then? Perhaps you would like me to open a separate issue for the missing packets/performance? Let me know.

What these modules do is:
* Sender just sends 400 packets per second, no fancy payload, just 256 bytes of 0's. Each of the 400 packets does have a packet ID, from 0 to 399
* Receiver1 and Receiver2 receive these packets and add them to a dictionary with the key being the packet ID. 2 statistics are kept for the received packets:
    * Are packets received with all packet ID's (e.g. received 400 packets: all packet IDs have been received)
    * Of all packets received, are there any packets that are older than 1,1s (e.g. nr of items more than 1s old: 178)

This leads me to believe the edgeHub can't handle this message load (which I then thought was the cause of the SDK hang issue)

Could you perhaps share the logs of the Receiver modules? Here are mine:
![image](https://user-images.githubusercontent.com/731510/184076285-6a08574b-736f-485a-8852-70faf3a9b622.png)

For reference, my lscpu and top output:
![image](https://user-images.githubusercontent.com/731510/184076154-66699a5b-1ddb-437b-8bc7-3909cb5ad580.png)

![image](https://user-images.githubusercontent.com/731510/184076188-338fa0e7-86e3-4ea4-9151-06ac08a06712.png)

**Comment by nyanzebra** [comment]
@DarthLowen,

Yes, the exceptions you see are likely related to AMQP. Would you also mind testing module to module message rate with MQTT instead of AMQP if not already? This might yield faster message transfer.

In the meantime, I will test out your new example.

**Comment by DarthLowen** [comment]
@nyanzebra, the modules already use MQTT, see the init code below. Only the upstream is AMQP. This small test project actually failed in the meantime btw, just came back from holiday and had 22 mentions of the error in the edgeHub log.

This is the init code:
```
MqttTransportSettings mqttSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only);
ITransportSettings[] settings = { mqttSetting };
// Open a connection to the Edge runtime
ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
```

I am planning to completely refactor our code and either send messages in bulk instead of one per one OR have a completely separate communication path between our custom modules, bypassing edgeHub. We're actually loading up the edgeHub with messages that it doesn't have anything to do with.

**Comment by nyanzebra** [comment]
@DarthLowen, yes batching messages might help with rate of message transfer. The maximum is 256MiB for payload of publish in MQTT (if I recall correctly).

**Comment by nyanzebra** [comment]
@DarthLowen, did batching and using MQTT for upstream resolve your problems?

**Comment by DarthLowen** [comment]
@nyanzebra, I'm confident it will, we haven't had the time yet to experiment with that though, we're really short on staff right now. The plan is to move away our inter-module communication from edgeHub but keep the 'real-time' behaviour of the packets (so no batching) since we do rely on it for some very limited functionalities. I'll keep MQTT in the back of my mind if we should encounter the hang issue again when the refactor is complete. The small project I made can trigger the sdk hang, so maybe you can use that to find & fix the problem, but for now this is not a pressing issue for us anymore. Do you propose we close this ticket?

**Comment by nyanzebra** [comment]
@DarthLowen, yes if batching and using mqtt solved your problem we can close ticket. Please reopen ticket if problem persists :)

**Comment by DarthLowen** [comment]
Just an fyi, I implemented RabbitMQ as a message broker between our own modules, resulting in 80% less CPU usage, 50% less memory and no dropped packets. Bottom-line: don't use edgeHub as a message-broker for messages that have nothing to do with iot hub or leaf devices...
