### ISSUE TITLE
Daemon fails to start "Could not load settings"

### ISSUE THREAD

**Issue by ondrejspilka** [Azure/iotedge#658]
Fresh install of 1.0.5 with HTTPS proxy on RHEL 7.5 Enterprise
Please can you help me to identify why settings couldn't be loaded?
It says "Permission denied", but /etc/iotedge/config.yaml is owned by iotedge user.
Many thanks...

## Expected Behavior
Agent should start

## Current Behavior
Agent fails with "[edgelet_utils::logging] The daemon could not start up successfully: Could not load settings". See logs

## Steps to Reproduce
- Fresh install 1.0.5 from RPMs using yum
- configured etc/iotedge/config.yaml
-  configured iotedge.service for proxy

### Device (Host) Operating System
RHEL 7.5 Ent.

### Architecture
amd64

### Container Operating System
 Docker CE

#### iotedged
1.0.5

#### Docker
17.03.2-ce 

## Logs

Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Starting Azure IoT Edge Security Daemon
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Version - 1.0.5
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Using runtime network id azure-iot-edge
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Initializing the module runtime...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Initializing module runtime...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Successfully initialized module runtime
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Finished initializing the module runtime.
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Configuring certificates...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Finished configuring certificates.
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Initializing hsm...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Finished initializing hsm.
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Detecting if configuration file has changed...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [DBUG] - [edgelet_utils::logging] The daemon could not start up successfully: Could not load settings
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [DBUG] - [edgelet_utils::logging]         caused by: Permission denied (os error 13)
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Change to configuration file detected.
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Removing all modules...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [DBUG] - [edgelet_docker::runtime] Listing modules...
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [DBUG] - [edgelet_docker::runtime] Successfully listed modules
Dec 20 13:20:11 torsr701.od.cssdom.com iotedged[2022]: 2018-12-20T11:20:11Z [INFO] - Finished removing modules.
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: Unit iotedge.service entered failed state.
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: iotedge.service failed.
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: iotedge.service holdoff time over, scheduling restart.
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: start request repeated too quickly for iotedge.service
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: Failed to start Azure IoT Edge daemon.
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: Unit iotedge.service entered failed state.
Dec 20 13:20:11 torsr701.od.cssdom.com systemd[1]: iotedge.service failed.

**Comment by myagley** [comment]
Can you run `ls -al` in the `/etc/iotedge` directory to see the mode/owner of the config file?

**Comment by ondrejspilka** [comment]
Was iotedge, -r------ ...
Changed temporarily chown/chgrp to root, no chenge
Changed temporarily to 777 iotedge, no change...

**Comment by myagley** [comment]
Hmm. What are the permissions on `/var/lib/iotedge`? I think it's actually failing to read some data out of the `cache` directory in `/var/lib/iotedge`.

Also, since this is RHEL, is it possible that SELinux is causing the permission denied?

**Comment by ondrejspilka** [comment]
I have changed /var/lib/cache owner from root to iotedge, error disappears.
There are some other issues with pulling agent image down to the device, but this will have something to do with proxy setup most probably.

**Comment by HenrikBach1** [comment]
In my case, it seemed that there were a permission problem:
```
$ ls -al /var/lib/iotedge/
total 4
drwxr-xr-x.  3 iotedge iotedge   55 Dec 22 20:53 .
drwxr-xr-x. 68 root    root    4096 Dec 19 09:56 ..
drwxr-xr-x.  3 root    root      19 Dec 21 15:49 hsm
-rw-rw----.  1 iotedge iotedge    0 Dec 17 20:36 mgmt.sock
-rw-rw-rw-.  1 iotedge iotedge    0 Dec 17 20:36 workload.sock
```

Changed user and group from `root` to `iotedge` for `hsm` left the service in running state.

**Comment by ondrejspilka** [comment]
Yes, it is a permission problem. All subfolders related to iotedge have to be iotedge owned.
On RHEL solution is:
` sudo chown iotedge /var/lib/iotedge/cache/`

`ls /var/lib/iotedge/  -la`
`total 16`
`drwxr-xr-x.  2 iotedge iotedge 4096 Dec 22 09:01 cache`
`drwxr-xr-x.  5 iotedge iotedge 4096 Dec  5 11:45 hsm`
`srw-rw----.  1 iotedge iotedge    0 Jan  2 14:31 mgmt.sock`
`srw-rw-rw-.  1 iotedge iotedge    0 Jan  2 14:31 workload.sock`
