### ISSUE TITLE
Is there any standard modules available for file upload from iot edge device to hub

### ISSUE THREAD

**Issue by Elsaligi** [Azure/iotedge#6580]
Hi,

1) Is there any standard marketplace modules available for a iot edge device to  push data file from edge device to iot hub.(GW consist of ftp client which fetch few data from ftp file on node end and that data file to be pushed to iot hub/blob storage)
2) Will standard file upload option work for iot edge device? will somebody provide few links for the same. I know it will work for normal devices, not sure about edge devices.

Thanks in advance..

**Comment by nyanzebra** [comment]
Hello @Elsaligi, please check out this link: https://docs.microsoft.com/en-us/answers/topics/azure-iot-edge.html

If there are additional questions please feel free to reopen this issue :)

**Comment by suneetnangia** [comment]
You could potentially host a device virtually inside of edge module and upload files via IoT Hub's File Upload feature.
