### ISSUE TITLE
Edge modules 'failed' after reboot

### ISSUE THREAD

**Issue by dcrupel** [Azure/iotedge#659]
Hi,

I install the new Edge version (windows host - windows containers) using the quickstart tutorial:
https://docs.microsoft.com/en-us/azure/iot-edge/quickstart

After the installation is finished everything is working fine and the messages are coming in the IoTHub.
But when I restart my windows device (VM) the containers (modules) are in the 'failed' status.
The service is running, restarting the service has no effect, the containers remain 'failed'.

Regards

## Expected Behavior
iotedge containers start again after restarten windows device.

## Current Behavior
When I restart my windows device (VM) the containers (modules) are in the 'failed' status.
The service is running, restarting the service has no effect, the containers remain 'failed'.

## Steps to Reproduce
1. Install windows 10 Enterprise LTSC - Version 1809 (OS Build 17763.194) trial version in Hyper-V VM
2. Create Edge in cloud
3. Install Edge using quickstart guide + check if it's running --> RUNNING
4. Restart VM (restart windows) --> service is still running but containers FAILED

### Device (Host) Operating System
WIndows 10 Enterprise LTSC - Version 1809 (OS Build 17763.194)

### Architecture
windows/amd64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.5

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0.5

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0.5

#### Docker
3.0.2

## Logs
![image](https://user-images.githubusercontent.com/35105327/50303230-baf40e80-048c-11e9-987f-15dd9b3d7267.png)
![image](https://user-images.githubusercontent.com/35105327/50303321-0a3a3f00-048d-11e9-8602-659d0918c164.png)
![image](https://user-images.githubusercontent.com/35105327/50303187-94ce6e80-048c-11e9-9ae6-a39584ecf633.png)
![image](https://user-images.githubusercontent.com/35105327/50303119-6cdf0b00-048c-11e9-991e-ca331bf5fb37.png)
![image](https://user-images.githubusercontent.com/35105327/50303128-71a3bf00-048c-11e9-905b-c7fc20df5d05.png)

## Additional Information
Already did:
- Set DCOM settings
- Enabled containers features + Hyper-V
- Used different network adapters
- ...

**Comment by myagley** [comment]
Thanks for the issue report. The underlying issue is that custom user defined networks are not persisted across reboots on Windows.

In 1.0.5, we updated the default network to a user defined network to solve an issue related to port binding. This change unfortunately introduced this regression.

The workaround is to set the `moby_runtime.network` to `nat` instead of `azure-iot-edge` in `C:\ProgramData\iotedge\config.yaml` and restart the service. This places all of the containers on the `nat` network, which is persisted across reboots, and reverts to the previous behavior.

We are working with the windows container team to see if we can get networks to persist across reboots.

**Comment by dcrupel** [comment]
> Thanks for the issue report. The underlying issue is that custom user defined networks are not persisted across reboots on Windows.
> 
> In 1.0.5, we updated the default network to a user defined network to solve an issue related to port binding. This change unfortunately introduced this regression.
> 
> The workaround is to set the `moby_runtime.network` to `nat` instead of `azure-iot-edge` in `C:\ProgramData\iotedge\config.yaml` and restart the service. This places all of the containers on the `nat` network, which is persisted across reboots, and reverts to the previous behavior.
> 
> We are working with the windows container team to see if we can get networks to persist across reboots.

Changing the moby_runtime.network did the trick for now. Thanks!

**Comment by myagley** [comment]
This is fixed in #709

**Comment by myagley** [comment]
This has now been released in version 1.0.6 of the install scripts for Windows.
