### ISSUE TITLE
Runtime Version

### ISSUE THREAD

**Issue by PedroBuhigas** [Azure/iotedge#6629]
Is there a way to get the device iotedge runtime version in reported properties or some other iot hub metric? Not the version of the hub or edge module, but the version of aziot installed on the device.

**Comment by veyalla** [comment]
This information is available in the `runtime` version of the `edgeAgent` reported properties:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/22105760/187044009-4ef4ea1d-5735-41a3-9876-84dea24e69b3.png">
