### ISSUE TITLE
Edge 1.4: Modules files permissions on Binds

### ISSUE THREAD

**Issue by jelalanne** [Azure/iotedge#6634]
Hi,
I have upgraded to 1.4 this morning after discussing permission issues over edgeHub and Agent user creations on one of the issues reported here. The very thing we were discussing was resolved, as edgeHub and Agent correctly accessed their folders, but something weird happened aside.
I have a Python module and a C# module, both need storage access, but only the python module is able to read/write in his folder.
They both have the same Binds settings createOptions in the deployment manifest. It appears they also have the same permissions.

From inside the containers:
![image](https://user-images.githubusercontent.com/32770824/187451010-2877176e-bc58-4b25-90d5-43066d8b2952.png)

From host:
![image](https://user-images.githubusercontent.com/32770824/187451264-57f9c2be-fd46-4b3b-a3a7-4576ebad123c.png)

Deployment manifest:
![image](https://user-images.githubusercontent.com/32770824/187452426-7baee193-307e-4413-8982-d7f4f6a228b6.png)

## Expected Behavior
Both Python and C# modules should be able to read/write in their folders with their Binds option.

## Current Behavior
Only the Python module can access his storage folder. The C# module raises an I/OException:
System.UnauthorizedAccessException: Access to the path '/aziot/storage/lifecycle/******.json' is denied

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a simple python module that uses using file.open("/aziot/storage/<modulename>/***.json", "w") command
2. Create a simple C# module that uses File.WriteAllText("/aziot/storage/<modulename>/***.json", "****") 
3. Deploy them with the binds on /etc/aziot/storage/<modulename>:/aziot/storage/<modulename>
4. Check logs

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
35 check(s) succeeded.
1 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]:  Ubuntu 20.04
* Architecture [e.g. amd64, arm32, arm64]: arm64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.4.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4
* Docker/Moby [run `docker version`]: 20.10.17+azure-1

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

No error/warning

```
</details>

<details>
<summary>edge-agent logs</summary>

```

No error/warning

```
</details>

<details>
<summary>edge-hub logs</summary>

```

No error/warning


```
</details>

<details>
<summary> C# module logs</summary>

```

Writing new state to file.
Unexpected exception happened while trying to write to file: System.UnauthorizedAccessException: Access to the path '/aziot/storage/<modulename>/<file>.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at lifecycle.Program.saveNewCurrentState(StateModel model) in /app/Program.cs:line 290
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/aziot/storage/<modulename>/<file>.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at lifecycle.Program.saveNewCurrentState(StateModel model) in /app/Program.cs:line 293
   at lifecycle.Program.Main(String[] args) in /app/Program.cs:line 83


```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by veyalla** [comment]
This depends on the user context under which the module (container) is running. I'd wager the one that is working is running as `root` which is the default.

**Comment by jelalanne** [comment]
As it appears on the screenshots, they both have the same permissions, and the same createOptions. Why would the C# module act different than the Python one?


Cordialement,

LALANNE Jérémie
________________________________

**Comment by jelalanne** [comment]
**UPDATE**

The Python module seems to be executed as root user, but C# is moduleuser.
Somebody know why this difference? If i configured something wrong?

**Comment by jelalanne** [comment]
**Workaround**

For the moment I simply deleted the moduleuser creation in C# Dockerfiles, which worked as C# now started using root, by the time we find a better option.

**Comment by orjanto** [comment]
I have a similar issues with the edgeHub with following deployment config: 
```
  "edgeHub": {
                        "type": "docker",
                        "status": "running",
                        "restartPolicy": "always",
                        "settings": {
                            "image": "mcr.microsoft.com/azureiotedge-hub:1.4.0",
                            "createOptions": "{\"HostConfig\":{\"Binds\":[\"/etc/iotedge/storage/:/iotedge/storage/\"],\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
                        },
                        "env": {
                            "StorageFolder": {
                                "value": "/iotedge/storage/"
                            }
                        }
                    }
```

which results in 

```
2022-09-01 13:16:20  Starting Edge Hub
2022-09-01 13:16:20  Starting Edge Hub
2022-09-01 13:16:20  Changing ownership of storage folder: /iotedge/storage/edgeHub to 13623
2022-09-01 13:16:20  Changing ownership of backup folder: /tmp/edgeHub_backup to 13623
2022-09-01 13:16:20.558 +00:00 Edge Hub Main()
<6> 2022-09-01 13:16:28.740 +00:00 [INF] - Installing certificates ...
<6> 2022-09-01 13:16:29.198 +00:00 [INF] - Enabling SSL protocols: Tls12
<3> 2022-09-01 13:16:29.696 +00:00 [ERR] - Stopping with exception
System.UnauthorizedAccessException: Access to the path '/iotedge/storage/edgeHub' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
```

I assume this is the same issue since the edgeHub-module is written in c# and the user in the Dockerfile was changed to **edgeagentuser** in 1.4.0. [Github diff - edgeHub docker file ](https://github.com/Azure/iotedge/commit/388ec1a341cf18fce3379c6750e62591963c8624)

My only option for now is to keep using 1.3.0.

**Comment by jelalanne** [comment]
From what I understood you do not need to do the chown and chmod command written in the documentation, maybe you did them and it changed the permissions. No? I removed them and it works now. They are not the same issue, I had the edgeHub permission issues many times before 1.4.0 came out.

> I have a similar issues with the edgeHub with following deployment config:
> 
> ```
>   "edgeHub": {
>                         "type": "docker",
>                         "status": "running",
>                         "restartPolicy": "always",
>                         "settings": {
>                             "image": "mcr.microsoft.com/azureiotedge-hub:1.4.0",
>                             "createOptions": "{\"HostConfig\":{\"Binds\":[\"/etc/iotedge/storage/:/iotedge/storage/\"],\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
>                         },
>                         "env": {
>                             "StorageFolder": {
>                                 "value": "/iotedge/storage/"
>                             }
>                         }
>                     }
> ```
> 
> which results in
> 
> ```
> 2022-09-01 13:16:20  Starting Edge Hub
> 2022-09-01 13:16:20  Starting Edge Hub
> 2022-09-01 13:16:20  Changing ownership of storage folder: /iotedge/storage/edgeHub to 13623
> 2022-09-01 13:16:20  Changing ownership of backup folder: /tmp/edgeHub_backup to 13623
> 2022-09-01 13:16:20.558 +00:00 Edge Hub Main()
> <6> 2022-09-01 13:16:28.740 +00:00 [INF] - Installing certificates ...
> <6> 2022-09-01 13:16:29.198 +00:00 [INF] - Enabling SSL protocols: Tls12
> <3> 2022-09-01 13:16:29.696 +00:00 [ERR] - Stopping with exception
> System.UnauthorizedAccessException: Access to the path '/iotedge/storage/edgeHub' is denied.
>  ---> System.IO.IOException: Permission denied
>    --- End of inner exception stack trace ---
>    at System.IO.FileSystem.CreateDirectory(String fullPath)
>    at System.IO.Directory.CreateDirectory(String path)
> ```
> 
> I assume this is the same issue since the edgeHub-module is written in c# and the user in the Dockerfile was changed to **edgeagentuser** in 1.4.0. [Github diff - edgeHub docker file ](https://github.com/Azure/iotedge/commit/388ec1a341cf18fce3379c6750e62591963c8624)
> 
> My only option for now is to keep using 1.3.0.

**Comment by orjanto** [comment]
Did you change it back to what the documentation says? [Give modules access to a device's local storage - host-system-permissions](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4#host-system-permissions)

> From what I understood you do not need to do the chown and chmod command written in the documentation, maybe you did them and it changed the permissions. No? I removed them and it works now. They are not the same issue, I had the edgeHub permission issues many times before 1.4.0 came out.
> 
> > I have a similar issues with the edgeHub with following deployment config:
> > ```
> >   "edgeHub": {
> >                         "type": "docker",
> >                         "status": "running",
> >                         "restartPolicy": "always",
> >                         "settings": {
> >                             "image": "mcr.microsoft.com/azureiotedge-hub:1.4.0",
> >                             "createOptions": "{\"HostConfig\":{\"Binds\":[\"/etc/iotedge/storage/:/iotedge/storage/\"],\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
> >                         },
> >                         "env": {
> >                             "StorageFolder": {
> >                                 "value": "/iotedge/storage/"
> >                             }
> >                         }
> >                     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which results in
> > ```
> > 2022-09-01 13:16:20  Starting Edge Hub
> > 2022-09-01 13:16:20  Starting Edge Hub
> > 2022-09-01 13:16:20  Changing ownership of storage folder: /iotedge/storage/edgeHub to 13623
> > 2022-09-01 13:16:20  Changing ownership of backup folder: /tmp/edgeHub_backup to 13623
> > 2022-09-01 13:16:20.558 +00:00 Edge Hub Main()
> > <6> 2022-09-01 13:16:28.740 +00:00 [INF] - Installing certificates ...
> > <6> 2022-09-01 13:16:29.198 +00:00 [INF] - Enabling SSL protocols: Tls12
> > <3> 2022-09-01 13:16:29.696 +00:00 [ERR] - Stopping with exception
> > System.UnauthorizedAccessException: Access to the path '/iotedge/storage/edgeHub' is denied.
> >  ---> System.IO.IOException: Permission denied
> >    --- End of inner exception stack trace ---
> >    at System.IO.FileSystem.CreateDirectory(String fullPath)
> >    at System.IO.Directory.CreateDirectory(String path)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I assume this is the same issue since the edgeHub-module is written in c# and the user in the Dockerfile was changed to **edgeagentuser** in 1.4.0. [Github diff - edgeHub docker file ](https://github.com/Azure/iotedge/commit/388ec1a341cf18fce3379c6750e62591963c8624)
> > My only option for now is to keep using 1.3.0.

**Comment by jelalanne** [comment]
I simply deleted those two commands

**Comment by jlian** [comment]
@ggjjj or @gordonwang0 any ideas about this permissions issue?

**Comment by veyalla** [comment]
FYI. We just published some updated docs around usage and expected behavior in v1.4 around this: https://docs.microsoft.com/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4#configure-system-modules-to-use-persistent-storage

**Comment by jelalanne** [comment]
Perfect! Thanks! That is exactly all the information I needed! 
(BTW, i'm french, the updates have only been applied to the english page, i assume the other languages will come soon)

**Comment by jelalanne** [comment]
Lets say I was a bit... quick, closing this issue. Documentation is great, but it does not work properly for me. 

This is the host config from deployment manifest for one of my custom modules. Tried with two different modules, doesn't work either. I am willing to create a volume and not a bind, as volumes are persistent went removing a container.

```
"createOptions": {
    "HostConfig": {
      "Mounts": [
        {
          "Source": "/etc/aziot/storage/<modulename>",
          "Target": "/aziot/storage/<modulename>",
          "Type": "volume",
          "ReadOnly": false
        }
      ]
    }
  }
```

This is why I am trying to deploy, but it wouldn't work.
Log message from aziot-edge:

``` 
2022-09-02T08:52:38Z [WARN] - container runtime error
Sep 02 10:52:38 iotedgesystem aziot-edged[1335]: Caused by:
Sep 02 10:52:38 iotedgesystem aziot-edged[1335]:     HTTP 400 Bad Request: create /etc/aziot/storage/<modulename>: "/etc/aziot/storage/<modulename>" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
``` 

It is an absolute path, I don't understand.

Any idea?

**Comment by veyalla** [comment]
As noted docs in the page linked for Mount options details, if type `volume` is used, one needs to provide a name not a path for the source:
![CleanShot 2022-09-02 at 09 49 37@2x](https://user-images.githubusercontent.com/22105760/188201607-a3864c3c-cde1-4e0e-a882-b9447e64f665.png)

So your createOption would look like something like:
```
"createOptions": {
    "HostConfig": {
      "Mounts": [
        {
          "Source": "<modulename>-volume",
          "Target": "/aziot/storage/<modulename>",
          "Type": "volume",
          "ReadOnly": false
        }
      ]
    }
  }
```

If not present, the Docker engine will create the volume. Do note that the module will need to run as `root` to access the volume as Docker engine creates volumes as `root`

**Comment by jelalanne** [comment]
Thanks for your answer! In an Iot Edge context, what would be the pros/cons between volumes and binds? (if there is any difference with Docker's docs)

**Comment by ggjjj** [comment]
https://docs.docker.com/storage/bind-mounts/ 
https://docs.docker.com/storage/volumes/ for an explanation on the limitations of binds over volumes

**Comment by ggjjj** [comment]
Please re-open if any more clarification is needed. Thank you!
