### ISSUE TITLE
Iot Edge 1.4 Failed to provision with IoT Hub, and no valid device backup was found: DPS client error

### ISSUE THREAD

**Issue by raza707mirza** [Azure/iotedge#6638]
Hi,
I upgraded iot edge to 1.4 and I am unable to run it with DPS individual enrollment.

Below are the logs:

Aug 31 09:52:56 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:56Z [INFO] - Starting service...
Aug 31 09:52:56 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:56Z [INFO] - Version - 1.4.0
Aug 31 09:52:56 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:56Z [INFO] - Provisioning starting. Reason: Startup
Aug 31 09:52:56 F0AC0168857 aziot-tpmd[1337]: 2022-08-31T09:52:56Z [INFO] - <-- GET /get_tpm_keys?api-version=2020-09-01 {"host": "tpmd.sock"}
Aug 31 09:52:56 F0AC0168857 aziot-tpmd[1337]: 2022-08-31T09:52:56Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 31 09:52:56 F0AC0168857 aziot-tpmd[1337]: 2022-08-31T09:52:56Z [INFO] - <-- POST /import_auth_key?api-version=2020-09-01 {"content-type": "application/json", "host": "tpmd.sock", "content-length": "1206"}
Aug 31 09:52:57 F0AC0168857 aziot-tpmd[1337]: WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:326:Esys_EvictControl_Finish() Received TPM Error
Aug 31 09:52:57 F0AC0168857 aziot-tpmd[1337]: ERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x0000014c)
Aug 31 09:52:57 F0AC0168857 aziot-tpmd[1337]: 2022-08-31T09:52:57Z [ERR!] - !!! internal error
Aug 31 09:52:57 F0AC0168857 aziot-tpmd[1337]: 2022-08-31T09:52:57Z [ERR!] - !!! caused by: could not import auth key
Aug 31 09:52:57 F0AC0168857 aziot-tpmd[1337]: 2022-08-31T09:52:57Z [ERR!] - !!! caused by: tpm:error(2.0): NV Index or persistent object already defined
Aug 31 09:52:57 F0AC0168857 aziot-tpmd[1337]: 2022-08-31T09:52:57Z [INFO] - --> 500 {"content-type": "application/json"}
Aug 31 09:52:57 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:57Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Aug 31 09:52:57 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:57Z [ERR!] - service encountered an error
Aug 31 09:52:57 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:57Z [ERR!] - caused by: DPS client error
Aug 31 09:52:57 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:57Z [ERR!] - caused by: internal error
Aug 31 09:52:57 F0AC0168857 aziot-identityd[2258]: 2022-08-31T09:52:57Z [ERR!] -    0: <unknown>
Aug 31 09:52:57 F0AC0168857 aziot-identityd[2258]:    1: <unknown>
Aug 31 09:52:57 F0AC0168857 systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 09:52:57 F0AC0168857 systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.

Following is my config.toml

[provisioning]
source = "dps"
global_endpoint = "https://<>.azure-devices-provisioning.net"
id_scope = "<>"

[provisioning.attestation]
method = "tpm"
registration_id = "F0AC0168857"

With this configuration, it works fine with previous versions

**Comment by ggjjj** [comment]
Can you please follow the format of the github Issue in IoT edge? would have a better understanding of the system in place?

https://github.com/Azure/iotedge/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by ggjjj** [comment]
The new fix should resolve the issue. closing it for now. Please open if the issue persists.

**Comment by jlian** [comment]
@ggjjj I imagine customer would have to update to a newer version of IoT Edge to get the fix? Or I guess they'd have to build the identity service from source and replace package?

@raza707mirza what is your timeline/urgency on this fix?

**Comment by ggjjj** [comment]
Yes that right. It will come in the next release. In the meantime, have to build from source

**Comment by raza707mirza** [comment]
Its not very urgent, But as this is a basic functionality, it should be released asap. But yes, I can wait for month.

**Comment by MattCosturos** [comment]
We use TPM attestation for enrolling our devices.
This blocks us upgrading to 1.4.0

**Comment by jlian** [comment]
Got it. Let me get back to everyone here tomorrow re: patch to 1.4

**Comment by jlian** [comment]
We're taking this fix for 1.4.1 as soon as possible. ETA is hopefully next week around 9/14. We need to take a .NET security patch as well. 

In the meantime, if you need an urgent fix, you can download the binary from https://github.com/Azure/iot-identity-service/actions/workflows/packages.yaml which builds off of `main`

Tag https://github.com/Azure/iot-identity-service/issues/450 as the fix will also address that issue.

**Comment by jlian** [comment]
1.4.1 is out https://github.com/Azure/azure-iotedge/releases/tag/1.4.1

**Comment by micahl** [comment]
@raza707mizra can you confirm the 1.4.1 works for you?

**Comment by micahl** [comment]
Closing

**Comment by raza707mirza** [comment]
@micahl Its working for me.Thank you
