### ISSUE TITLE
Failure to Restart iotedge - apparently after upgrade to 1.0.5

### ISSUE THREAD

**Issue by MarkSlosberg** [Azure/iotedge#664]
Referencing the following issue reported earlier in 

https://social.msdn.microsoft.com/Forums/en-US/e42e0eb1-e6e2-4957-8a7c-11b32d03835e/iot-edge-for-raspberry-pi?forum=azureiothub

Just did a complete reinstall following this blog article (https://thenewstack.io/tutorial-connect-and-configure-raspberry-pi-as-an-azure-iot-edge-device/) on a fresh Pi and fresh version Raspian "stretch" and reproduced the error exactly.  Included deleting the original IoTEdge device in the Azure Portal and adding a new one.  Here are the results of the latest _**systemctl status iotedge**_ command.

```
_● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sat 2018-12-22 14:06:42 PST; 1min 33s ago
     Docs: man:iotedged(8)
  Process: 6204 ExecStart=/usr/bin/iotedged -c /etc/iotedge/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 6204 (code=exited, status=1/FAILURE)
      CPU: 16ms

Dec 22 14:06:41 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
Dec 22 14:06:41 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Dec 22 14:06:42 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Dec 22 14:06:42 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
Dec 22 14:06:42 raspberrypi systemd[1]: Dependency failed for Azure IoT Edge daemon.
Dec 22 14:06:42 raspberrypi systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'._
```

I had this working originally nicely on Monday the 12/27 and it stopped working on the afternoon of 12/28 and I haven't been able to get it working since.  Now on a 2nd Pi.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by myagley** [comment]
Is it possible to get more of the logs from the `iotedged`? This will help provide more context for the error.

`journalctl --no-pager -u iotedge`

**Comment by MarkSlosberg** [comment]
Here you go:

pi@raspberrypi:~/iot-hub-node-raspberrypi-client-app $ journalctl --no-pager -u iotedge
-- Logs begin at Thu 2016-11-03 10:16:42 PDT, end at Wed 2019-01-02 20:15:50 PST. --
Dec 26 12:32:42 raspberrypi systemd[1]: Started Azure IoT Edge daemon.
Dec 26 12:32:43 raspberrypi iotedged[957]: 2018-12-26T20:32:43Z [INFO] - Starting Azure IoT Edge Security Daemon
Dec 26 12:32:43 raspberrypi iotedged[957]: 2018-12-26T20:32:43Z [INFO] - Version - 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)
Dec 26 12:32:43 raspberrypi iotedged[957]: 2018-12-26T20:32:43Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Dec 26 12:32:43 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
Dec 26 12:32:43 raspberrypi systemd[1]: Started Azure IoT Edge daemon.
Dec 26 12:32:43 raspberrypi iotedged[986]: 2018-12-26T20:32:43Z [INFO] - Starting Azure IoT Edge Security Daemon
Dec 26 12:32:43 raspberrypi iotedged[986]: 2018-12-26T20:32:43Z [INFO] - Version - 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)
Dec 26 12:32:43 raspberrypi iotedged[986]: 2018-12-26T20:32:43Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Dec 26 12:32:43 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Dec 26 12:32:43 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi systemd[1]: Started Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi iotedged[998]: 2018-12-26T20:32:44Z [INFO] - Starting Azure IoT Edge Security Daemon
Dec 26 12:32:44 raspberrypi iotedged[998]: 2018-12-26T20:32:44Z [INFO] - Version - 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)
Dec 26 12:32:44 raspberrypi iotedged[998]: 2018-12-26T20:32:44Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Dec 26 12:32:44 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi systemd[1]: Started Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi iotedged[1009]: 2018-12-26T20:32:44Z [INFO] - Starting Azure IoT Edge Security Daemon
Dec 26 12:32:44 raspberrypi iotedged[1009]: 2018-12-26T20:32:44Z [INFO] - Version - 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)
Dec 26 12:32:44 raspberrypi iotedged[1009]: 2018-12-26T20:32:44Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Dec 26 12:32:44 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi systemd[1]: Started Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi iotedged[1025]: 2018-12-26T20:32:44Z [INFO] - Starting Azure IoT Edge Security Daemon
Dec 26 12:32:44 raspberrypi iotedged[1025]: 2018-12-26T20:32:44Z [INFO] - Version - 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)
Dec 26 12:32:44 raspberrypi iotedged[1025]: 2018-12-26T20:32:44Z [INFO] - Using config file: /etc/iotedge/config.yaml
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Dec 26 12:32:44 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Start request repeated too quickly.
Dec 26 12:32:44 raspberrypi systemd[1]: Failed to start Azure IoT Edge daemon.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
Dec 26 12:32:44 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.

**Comment by ancaantochi** [comment]
Hi @MarkSlosberg,

The logs don't have not enough details to identity the issue, can you please provide the logs without  -u iotedge:

`journalctl --no-pager`

or add --since to get only the significant logs:

`journalctl --no-pager --since '2019-01-07 19:40:26'  `

Please also enable debug logs for iotedge: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#standard-diagnostic-steps

Thanks!

**Comment by MarkSlosberg** [comment]
Here are two files:


  1.  The Journal file you requested.  I reran the sequence found here https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm including reinstalling the IoTEdge device in my Azure Portal and putting the connection string into the config.yaml file as instructed.  Then I reran the journalctl command.
  2.  The config.yaml file – you will find my connect string in it. As I was rereading the logs it certainly looks like the diagnostics are telling me that this is where the problem is but everything looks right to me but I am clearly missing something.

     *   (provisioning:
     *     source: "manual"
     *   # device_connection_string: "<ADD DEVICE CONNECTION STRING HERE>"
     *                   device_connection_string: "HostName=Demonstration-Training.azure-devices.net;DeviceId=GreenhousePi;SharedAccessKey=rRsqj/DHteuNS+cOx3KDlsvuNXKZSe07lZ6GcBmHeEg="

One other note.  As I was reading through the journalctl log file, once I removed the -u iotedge parameter, it looked like someone was trying to “break into my Pi” through the DMZ.  I have subsequently disabled the DMZ address but if it might help you to see my configuration directly, I am happy to re-enable it and give you access to the unit directly.  It is strictly an “experimental machine” at this point with nothing of any value on it other than this iotedge lab.  It is amazing though that some hacker found it and decided he wanted to attack it.

I have also enabled the debug logs as instructed so that info will be available within this sequence and from now on.

Also to restate things, with regards to the log notes that say the following, I definitely had this working before the IoTEdge update to 1.0.5.

Jan 07 14:41:17 greenhousepi iotedged[29091]: 2019-01-07T22:41:17Z [INFO] - Starting Azure IoT Edge Security Daemon
Jan 07 14:41:17 greenhousepi iotedged[29091]: 2019-01-07T22:41:17Z [INFO] - Version - 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)
Jan 07 14:41:17 greenhousepi iotedged[29091]: 2019-01-07T22:41:17Z [INFO] - Using config file: /etc/iotedge/config.yaml
Jan 07 14:41:17 greenhousepi iotedged[29091]: 2019-01-07T22:41:17Z [ERR!] - The daemon could not start up successfully: Edge device information is required.
Jan 07 14:41:17 greenhousepi iotedged[29091]: Please update the config.yaml and provide the IoTHub connection information.
Jan 07 14:41:17 greenhousepi iotedged[29091]: See https://aka.ms/iot-edge-configure-linux for more details.

**Comment by MarkSlosberg** [comment]
Here are the files from my email attachments.

[iotedge-log.txt](https://github.com/Azure/iotedge/files/2734618/iotedge-log.txt)
[config.yaml.txt](https://github.com/Azure/iotedge/files/2734619/config.yaml.txt)

**Comment by ancaantochi** [comment]
It looks like the indentation for the device_connection_string is not correct: YAML files cannot contain tabs as identation. Use 2 spaces instead.

**Comment by MarkSlosberg** [comment]
That appears to have been the ticket.  Very picky.

Thanks

**Comment by MarkSlosberg** [comment]
This might be worth noting in the different blogs that reference editing the YAML file this formatting constraint exists and to always check through a YAML file format validator (who knew those existed;-).

Also, is it possible that IoTEdge version 1.0.4 was more lenient on this than the current version 1.0.5?  I definitely had it working on v 1.0.4 and don't think I made any changes to the config.yaml file when I upgraded initially.  I may have inadvertently introduced the Tab trying to "fix it" though later.

**Comment by MarkSlosberg** [comment]
And one other question.  Are the two spaces required or optional?

**Comment by myagley** [comment]
Hi Mark. Yes, yaml is pretty opinionated about whitespace. The two spaces are required because that field is a sub-field of the `manual` field.

We are working on a diagnostics tool that will include verifying that the yaml is correctly formatted. The error reporting in this area should get significantly better.

**Comment by MarkSlosberg** [comment]
Excellent. After your email, I saw some references to YAML validation tools out there but I haven’t tried them yet.

Now that I am functioning again, I will pick up where I left off. This was migrating a host of direct sensor reading code (air and soil temp, humidity, soil moisture for greenhouse and agricultural apps) that I had in production that was transmitting directly back to the IoTHub from the Pi, into an “Edge” implementation that would allow offline or disconnected operations which I was finding a challenge in my alpha implementation.

If you don’t mind, I might connect with you as I drive forward with this effort.

I really appreciate your help on this.

Thanks
Mark

Mark D. Slosberg
Mobile: +1 206-679-3277

On Jan 8, 2019, at 8:10 AM, Mike Yagley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mark. Yes, yaml is pretty opinionated about whitespace. The two spaces are required because that field is a sub-field of the manual field.

We are working on a diagnostics tool that will include verifying that the yaml is correctly formatted. The error reporting in this area should get significantly better.

**Comment by ancaantochi** [comment]
Closing this issue, please reopen if the problem was not solved.
