### ISSUE TITLE
edgeHub fails and up repeatedly

### ISSUE THREAD

**Issue by xiaocongfu** [Azure/iotedge#665]
## Current Behavior
I followed the steps in https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm
After configuration, I checked the status of iotedge:

`root@linaro-alip:~# systemctl status iotedge
● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-12-24 14:24:07 UTC; 7min ago
     Docs: man:iotedged(8)
 Main PID: 22223 (iotedged)
    Tasks: 11 (limit: 4915)
   Memory: 47.0M
      CPU: 14.638s
   CGroup: /system.slice/iotedge.service
           └─22223 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Dec 24 14:30:28 linaro-alip iotedged[22223]: 2018-12-24T14:30:28Z [INFO] - [mgmt] - - - [2018-12-24 14:30:28.690536043 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:30:33 linaro-alip iotedged[22223]: 2018-12-24T14:30:33Z [INFO] - [mgmt] - - - [2018-12-24 14:30:33.711721685 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:30:38 linaro-alip iotedged[22223]: 2018-12-24T14:30:38Z [INFO] - [mgmt] - - - [2018-12-24 14:30:38.726271567 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:30:43 linaro-alip iotedged[22223]: 2018-12-24T14:30:43Z [INFO] - [mgmt] - - - [2018-12-24 14:30:43.751744689 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:30:48 linaro-alip iotedged[22223]: 2018-12-24T14:30:48Z [INFO] - [mgmt] - - - [2018-12-24 14:30:48.764959931 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:30:53 linaro-alip iotedged[22223]: 2018-12-24T14:30:53Z [INFO] - [mgmt] - - - [2018-12-24 14:30:53.782133132 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:30:58 linaro-alip iotedged[22223]: 2018-12-24T14:30:58Z [INFO] - [mgmt] - - - [2018-12-24 14:30:58.799717694 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:31:03 linaro-alip iotedged[22223]: 2018-12-24T14:31:03Z [INFO] - [mgmt] - - - [2018-12-24 14:31:03.818800336 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:31:08 linaro-alip iotedged[22223]: 2018-12-24T14:31:08Z [INFO] - [mgmt] - - - [2018-12-24 14:31:08.836520978 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
Dec 24 14:31:13 linaro-alip iotedged[22223]: 2018-12-24T14:31:13Z [INFO] - [mgmt] - - - [2018-12-24 14:31:13.850669580 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(22346)
`
Then run iotedge list:
root@linaro-alip:~# iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
edgeAgent        running          Up 7 minutes     mcr.microsoft.com/azureiotedge-agent:1.0
root@linaro-alip:~# iotedge list
NAME                        STATUS           DESCRIPTION      CONFIG
SimulatedTemperatureSensor  running          Up 2 seconds     mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent                   running          Up 12 minutes    mcr.microsoft.com/azureiotedge-agent:1.0
edgeHub                     running          Up 3 seconds     mcr.microsoft.com/azureiotedge-hub:1.0
root@linaro-alip:~# iotedge list
NAME                        STATUS           DESCRIPTION      CONFIG
SimulatedTemperatureSensor  running          Up 20 seconds    mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeHub                     running          Up 21 seconds    mcr.microsoft.com/azureiotedge-hub:1.0
edgeAgent                   running          Up 12 minutes    mcr.microsoft.com/azureiotedge-agent:1.0
root@linaro-alip:~# iotedge list
NAME                        STATUS           DESCRIPTION      CONFIG
SimulatedTemperatureSensor  running          Up a minute      mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent                   running          Up 14 minutes    mcr.microsoft.com/azureiotedge-agent:1.0
edgeHub                     running          Up a minute      mcr.microsoft.com/azureiotedge-hub:1.0
root@linaro-alip:~# iotedge list
NAME                        STATUS           DESCRIPTION                 CONFIG
edgeAgent                   running          Up 14 minutes               mcr.microsoft.com/azureiotedge-agent:1.0
SimulatedTemperatureSensor  failed           Failed (132) 2 seconds ago  mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeHub                     failed           Failed (132) 2 seconds ago  mcr.microsoft.com/azureiotedge-hub:1.0
root@linaro-alip:~# iotedge list
NAME                        STATUS           DESCRIPTION      CONFIG
SimulatedTemperatureSensor  running          Up 13 seconds    mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0
edgeAgent                   running          Up 18 minutes    mcr.microsoft.com/azureiotedge-agent:1.0
edgeHub                     running          Up 14 seconds    mcr.microsoft.com/azureiotedge-hub:1.0

I checked the list repeatedly, edgeHub and SimulatedTemperatureSensor would fail and up again and again. I don't if it was normal to happen like this.

## Steps to Reproduce

1.
2.
3.
4.

### Device (Host) Operating System
debian 9.6

### Architecture
arm32

### Container Operating System
Linux containers

**Comment by varunpuranik** [comment]
@xiaocongfu - Can you please get the edgeHub/edgeAgent/simulated temp sensor logs ($>sudo iotedge logs edgeHub) and provide them to us. That will tell us what exactly is going on.

**Comment by ancaantochi** [comment]
Closing because no response with logs, please reopen if you still have this issue.
