### ISSUE TITLE
Where are the Container registry credentials stored when a new deployment manifest file is deployed in the Azure iot edge

### ISSUE THREAD

**Issue by vikasreddy-bh** [Azure/iotedge#6650]
Is it stored on the device side ?(if yes where exactly is it stored)

Is it only present on the portal in the IotHub?

Is it secure to have the credentials on the IotHub or on the devices?

Can you please give the answer for the above questions.

**Comment by ggjjj** [comment]
Container registry credentials once entered in the IoT hub portal - it is part of the twin desired properties which gets sent to the device. So yes, it is stored in the device. It is used by the moby/docker engine eventually and would be in its config file. @veyalla Can you comment on the security question?

**Comment by ggjjj** [comment]
For answering questions on security,

Access to Azure Portal is secured by AAD credentials  and RBAC (az login)

Device connection to IoT Hub is secured by IoT Hub device authentication (certs or sas key.

**Comment by ggjjj** [comment]
Let us know if you have more questions/clarifications and we will get back to you.

**Comment by ggjjj** [comment]
Closing the issue as the clarification has been provided to the questions. Please re-open if needed.

**Comment by vikasreddy-bh** [comment]
@ggjjj Can you please let us know in which location the deployment.json file is stored on the edge device?
Just want to make sure that it is secured properly on the device.

**Comment by amit12cool** [comment]
@ggjjj You said registry credentials are stored on config file of mobi engine installed on device, is that secure? Can I not easily access that file on device?

**Comment by ggjjj** [comment]
It is not secure. You can check config.toml file under /etc/aziot
