### ISSUE TITLE
Is there a way for a module to wait for another module to finish first? 

### ISSUE THREAD

**Issue by Punnpd** [Azure/iotedge#6651]
## Expected Behavior
- I deployed 2 IoT Edge modules on Jetson Nano. 
- Module No.1 will generate an artifact that will be used by the Module No.2
- Thus, Module No.1 done --> Module No.2 start running

## Current Behavior
Module No.2 doesn't wait for Module No.1 to finish first.
Note: I know that StartupOrder wouldn't help in this situation. it just initiates the module in order.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Build 2 custom modules
2. Deploy
3.
4.

### Device Information
- Container OS: Linux container

### Runtime Versions
- aziot-edged [run iotedge version]: 1.1.11
- Edge Agent [image tag (e.g. 1.0.0)]: 1.1
- Edge Hub [image tag (e.g. 1.0.0)]: 1.1
- azure metrics collector: 1.0.9
- Docker/Moby [run docker version]: 19.03.15

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by ggjjj** [comment]
@micahl can you comment on this? I am not sure if we have a feature like that

**Comment by micahl** [comment]
The runtime doesn't have insight into when a given module is "ready" for another module to consume.  General guidance is to design modules to be resilient to failures with appropriate retry logic, but if that isn't feasible then crafting scripts for the entrypoint that facilitate some level of coordinated startup sequence between modules is your best option (e.g. for example, see the [Control startup and shutdown order in Compose](https://docs.docker.com/compose/startup-order/))
