### ISSUE TITLE
Delete module or container once it's done

### ISSUE THREAD

**Issue by Punnpd** [Azure/iotedge#6657]
Expected behavior:
- The module or container gets deleted after it finishes executing a script.

Note:
I try to build a solution with 2 modules. The first module converts the model.onnx to model.trt, and this conversion process **has to** be executed in the container running in the edge device. The second module would use the model.trt to run a pipeline and do some predictions. The problem here is that the first module still runs even though the script is done executing. 

- I wonder if is there a way to set the config file which tells the module or container to delete itself.
- Or Is there an alternative approach that would work best in this scenario?

**Comment by Punnpd** [comment]
Is the issue that the first container gets restarted even if you make it exit?
- Yes. I just want it to get deleted after the conversion

Could you make that conversion a bash script in module 1 Dockerfile?
- I already tried the approach you mentioned, but the problem is that if I want to restart the module, the conversion process will be executed again which is not preferable in this case. Only the running pipeline should get restarted.

Do you need the conversion to happen at build time or run time?
- Run time.

**Comment by AltoTechGithub** [comment]
Any update on this feature?

**Comment by Punnpd** [comment]
Any update on this feature?

**Comment by jlian** [comment]
> I already tried the approach you mentioned, but the problem is that if I want to restart the module, the conversion process will be executed again which is not preferable in this case. Only the running pipeline should get restarted.

Where would the file `model.trt` stored, in the second container's own file system or a mount? Could you make the script such that it checks for the existence of the file and run based on the decision?

**Comment by jlian** [comment]
Either way, IoT Edge is not designed to do what you asked (do a docker run exactly once and delete after). I think there are ways to achieve the result you want without doing the delete though.

**Comment by jlian** [comment]
@Punnpd any thoughts on my questions?
