### ISSUE TITLE
Support for nested edge provisioning using DPS.

### ISSUE THREAD

**Issue by pavel-orlov** [Azure/iotedge#6667]
Hi!

We would like to use nested edge in IoT Central but it seems not supported now. Do you plan to support DPS for nested edge?
Is there a way to provision a nested edge to IoT Central app?

Thank you.

**Comment by veyalla** [comment]
Hi @pavel-orlov - it is currently not possible to do this and there are no near-term plans for add support. 

If you'd like to see this capability in the product, I'd encourage you to create/upvote a feature request at https://aka.ms/iotedge-suggestion.
