### ISSUE TITLE
Managing Downstream Devices in Disconnected Mode

### ISSUE THREAD

**Issue by hkashif** [Azure/iotedge#6679]
We have the following 'typical' setup. An Edge device connected to the IoT Hub. Downstream IoT devices are connected through this Edge device. We use the following functions for device managing downstream devices:
- Direct methods
- D2C messages
- Device Twins

Now, in a disconnected scenario where the IoT Hub is no longer connected to the Edge device. How can we still manage downstream devices? I am assuming everything going upstream can still be retrieved through the Edge device (since it goes through it anyway). So more concretely:
- How can I retrieve twins of downstream devices through the Edge Hub?
- How can I set desired properties for downstream devices (or even Edge modules) through the Edge Hub?
- For D2C messages, do I handle this through message routing? Or is there an alternative way to get it to work similarly in offline/online mode?
- How can I trigger direct methods on downstream devices (or even the Edge device) in this setup?

**Comment by jlian** [comment]
> * How can I retrieve twins of downstream devices through the Edge Hub?

I'll need to get back to you on this. Wasn't able to find a non-hacky method to do this offline yet. 

> * How can I set desired properties for downstream devices (or even Edge modules) through the Edge Hub?

Unfortunately, this cannot be done since desired properties are owned completely by the cloud. See https://github.com/Azure/iotedge/issues/1147

> * For D2C messages, do I handle this through message routing? Or is there an alternative way to get it to work similarly in offline/online mode?

Not sure what you mean here. You shouldn't have to do anything special from a client perspective for messages. But I don't think I understand your question.

> * How can I trigger direct methods on downstream devices (or even the Edge device) in this setup?

Here might be a good place to start https://stackoverflow.com/questions/56910425/direct-method-invocation-from-azure-iot-edge-device-to-a-child-device-without-in****

**Comment by hkashif** [comment]
### Read downstream twin in disconnected mode
Waiting for your reply.
### Write downstream twin in disconnected mode
If I understand this correctly, I cannot (and should not) use desired properties to modify downstream device configuration in disconnected modes. What do you recommend in this case instead? (bearing in mind that I also want to support modifying configuration in online modes)
### D2C messages in disconnected mode
In an online mode, D2C messages are sent to the cloud and routed through the hub's built-in endpoints. Now, in a disconnected mode, is there a way to listen to those messages and act upon them at (or from) the Edge instead? Or do I have to modify the Edge's message routing in a disconnected mode to handle the messages differently (basically send them somewhere other than upstream to the hub)?
### Direct methods in disconnected mode
I have a .Net setup. I will give this a try.

**Comment by jlian** [comment]
Here's some documentation we have about EdgeHub API and get twin https://github.com/Azure/iotedge/blob/main/doc/edgehub-api.md which says

> The offline features include...[providing] the latest known twin for devices/modules when they become online, but there is no connection to IoT Hub.

So you should be able to call the get twin API from a module client, and edgeHub would return the desired + reported properties if the queried device twin is within the IoT Edge device's scope (parented correctly).

Otherwise 

> If I understand this correctly, I cannot (and should not) use desired properties to modify downstream device configuration in disconnected modes. What do you recommend in this case instead? (bearing in mind that I also want to support modifying configuration in online modes)

Hmm, maybe direct methods? What do you need to modify?

> In an online mode, D2C messages are sent to the cloud and routed through the hub's built-in endpoints. Now, in a disconnected mode, is there a way to listen to those messages and act upon them at (or from) the Edge instead? Or do I have to modify the Edge's message routing in a disconnected mode to handle the messages differently (basically send them somewhere other than upstream to the hub)?

Yeah, upstream for edgeHub is just IoT Hub and I don't think there's a way to listen to it without additional routing rules like you said.

**Comment by hkashif** [comment]
So in summary, to manage disconnected devices:

- Direct methods: Invokable through module client
- Get Twin: GetTwin API from a module client
- Set Twin (desired properties): Cannot be done. Desired properties are owned by the cloud.
- D2C and C2D messages: Additionally routing rules to route it somewhere other than the cloud.

> Hmm, maybe direct methods? What do you need to modify?

I need to modify device configuration. It makes sense to use the twin in an online mode. Direct methods would also work.

Now from an architectural perspective. Consider this setup:
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/8807101/194935246-c834f23f-39b6-42f4-9da6-192b33b02e57.png">

For the online setup, the on-premises Edges are connected to the IoT Hub. Backend services interact with devices Edge/IoT through the IoT Hub through all of the aforementioned means of communication: Direct Methods/Set Twin/Read Twin/C2D Messages/D2C Messages.

Now for the disconnected setup, based on our discussion so far, there is no easy way to deploy the same Backend services on-premises (let's say in a k8s cluster). So if I want to run the Backend services, in a disconnected mode, with minimal changes, what is the recommendation here?
- Do I run an additional parent Edge (maybe in a VM) to all existing Edge devices and have the Backend Services interact with this new Edge instead of the IoT Hub? or do I just add an additional controller module on the existing Edge devices and interact with them directly through the BE services?
- Do I ditch setting anything through desired properties and use direct methods instead to have the same interfaces for both online and disconnected deployments?
- Any other thoughts/ideas/recommendations on having something that works with minimal changes between both deployments?
-

**Comment by jlian** [comment]
> Do I run an additional parent Edge (maybe in a VM) to all existing Edge devices and have the Backend Services interact with this new Edge instead of the IoT Hub? or do I just add an additional controller module on the existing Edge devices and interact with them directly through the BE services?

I think to minimize the changes between the two deployments, the additional parent Edge option makes the most sense here. However it's hard to tell exactly since I don't know what your offline pattern is like and what are the most important things.

> Do I ditch setting anything through desired properties and use direct methods instead to have the same interfaces for both online and disconnected deployments?

That's what I would do

> Any other thoughts/ideas/recommendations on having something that works with minimal changes between both deployments?

Maybe you could describe your system needs (from user perspective maybe) and we could see. CC @veyalla

**Comment by veyalla** [comment]
Please post discussion style questions to [Microsoft Q&A ](https://learn.microsoft.com/en-us/answers/topics/25493/azure-iot-edge.html)where the larger community including IoT MVP can weigh in.
