### ISSUE TITLE
How to get aarch64 moby-engine & moby-cli?

### ISSUE THREAD

**Issue by v-jiq** [Azure/iotedge#668]
I have a confuse about moby-engine, beacuse the iotedge document only introduce amd64 and armhf moby-engine. Now I want to run iot-edge on aarch64 platform, So , I try build aarch64 platform moby-engine by moby source code -- https://github.com/moby/moby.

 but the binary file after build is not moby-engine . I consult that whether the  moby-engine source code is in this link --  https://github.com/moby .  if not, whether can provide a link moby-engine source code.

the moby build way:
1. clone the Moby/moby repository on an ARM64 device `git clone https://github.com/moby/moby.git`
2. cd moby
3. execute `make binary` 

below is output binary file(not have moby-engine):
![image](https://user-images.githubusercontent.com/39880470/50436281-09d3f500-0920-11e9-8fd0-1e8125ab0f84.png)

And I know can use  aarch64 docker-ce to instead moby-engine ,but the iotedge document highly recommended moby-engine, So We also want to use moby-engine on aarch64 platform.

Thanks !!

**Comment by mrohera** [comment]
Hello @v-jiq, I have not built this myself to comment, will try and dig up more information and/or add experts who know about the details. Perhaps asking this on the Moby project makes more sense.

Also we do not support ARM64 officially yet but this is something we are looking at adding for the future. The currently released ARM32 images for Edge Hub and Edge Agent "should work" though. You would have to explicitly list the following image tags in your deployment:

mcr.microsoft.com/azureiotedge-hub:1.0.5-linux-arm32v7
mcr.microsoft.com/azureiotedge-agent:1.0.5-linux-arm32v7
Optional:
mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0.5-linux-arm32v7

**Comment by mrohera** [comment]
Thanks @olljanat for the information makes sense.

@v-jiq I am marking this as an enhancement for now since we don't have official support for ARM 64 just yet but please stay tuned. When this support is enabled, we will provide instructions on how to obtain Moby based binaries for the engine and cli. For now we hope with Docker CE and the images listed above you are unblocked.

**Comment by v-jiq** [comment]
Thanks @mrohera

**Comment by xiaofengren** [comment]
Iotedge document mentioned that it need moby-engine & moby-cli, may I know whether we can use docker-ce?

**Comment by mrohera** [comment]
I think it should be fine to use Docker CE for your development and prototyping. To address production needs, until the Edge officially supports ARM64 I'm afraid the moby-engine and moby-cli will not be formally released. Also just so you know we and other teams are actively working on it.
