### ISSUE TITLE
edgeHub restarting multiple times per day

### ISSUE THREAD

**Issue by perttvil** [Azure/iotedge#6682]
I have a problem that edgeHub keeps restarting multiple times per day.
I think it started after I updated from Iot edge 1.2 to 1.3. Currently running Azure Iot edge 1.4.1.

Running it in Azure VM (ubuntu 20.04.1), Standard D2s v3, 2vCPUs, 8Gb memory, with constant internet connectivity.
Load seems to be very low and plenty of memory left.

Log before edgeHub restart:

```
<6> 2022-09-20 05:08:14.249 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<4> 2022-09-20 05:08:32.507 +00:00 [WRN] - As of ""2022-09-20T05:08:30.3629169+00:00"", the heartbeat has been running for ""00:00:02.1133785"" which is longer than ""00:00:01"". This could be caused by thread pool starvation.
<4> 2022-09-20 05:08:36.715 +00:00 [WRN] - As of ""2022-09-20T05:08:34.5076644+00:00"", the heartbeat has been running for ""00:00:02.2073606"" which is longer than ""00:00:01"". This could be caused by thread pool starvation.
2022-09-20 05:08:53  Starting Edge Hub
2022-09-20 05:08:53  Starting Edge Hub
2022-09-20 05:08:53  Changing ownership of storage folder: /tmp/edgeHub/edgeHub to 13623
2022-09-20 05:08:53  Changing ownership of backup folder: /tmp/edgeHub_backup to 13623
2022-09-20 05:08:53.575 +00:00 Edge Hub Main()
```

`iotedge check` reports that everything is ok.

Otherwise everything works ok, just the edgeHub keeps restarting which causes pauses in the data processing.

Any idea which causes this? Has there been some threading change in edgeHub which really causes thread pool starvation? There seems to be plenty of CPU resources free on the VM and load is low.

**Comment by m-drozd** [comment]
Do you have any traces of OOM killer in your kernel logs (check with dmesg)? Maybe you are hitting the same issue as in #6630

**Comment by perttvil** [comment]
It seems so: 
[dmesg.log](https://github.com/Azure/iotedge/files/9605265/dmesg.log)

```
[1222685.231424] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/8bf249edcae93e24eee44e4eb728459e4ec209ccfad517128f11d1267b2371df,task=dotnet,pid=1329396,uid=13623
[1222685.231492] Out of memory: Killed process 1329396 (dotnet) total-vm:9898864kB, anon-rss:6938724kB, file-rss:0kB, shmem-rss:0kB, UID:13623 pgtables:14252kB oom_score_adj:0
```

**Comment by m-drozd** [comment]
The name of my issue is a little bit misleading for now, cause from what I understand the trigger is closing the connection to edgeHub at wrong time and hitting that issue in DotNetty. Maybe one of you modules is reconnecting periodically or something like that. Either way I believe that the solution for both of our issues is the same.

**Comment by jlian** [comment]
We're working on the DotNetty fix and are starting to do long-haul testing. Looks like it will probably take until first week of Oct.

**Comment by jlian** [comment]
[1.4.2 is out](https://github.com/Azure/azure-iotedge/releases/tag/1.4.2), should fix your problem 🤞

**Comment by perttvil** [comment]
Been testing a few days now, without any problems, so it seems like fixed 👍
