### ISSUE TITLE
Restart or Reinitialize the Edge Hub module using a custom Iotedge Module

### ISSUE THREAD

**Issue by vaishnavils97** [Azure/iotedge#6683]
How to restart or reinitialize  Edge Hub default module using a custom Iotedge module ?

**Comment by veyalla** [comment]
Please post discussion-type questions on [Microsoft Q&A site](https://learn.microsoft.com/answers/topics/25493/azure-iot-edge.html), so the larger community can help. GitHub issues are mainly for reporting product bugs.
