### ISSUE TITLE
IoT Edge 1.4 blocks and reports errors to Azure Portal UI during module updates

### ISSUE THREAD

**Issue by thetanz-geoff** [Azure/iotedge#6684]
## Expected Behavior
When an IoT Edge instance responds to a new targeted layered deployment and begins updating modules, the status of all modules should continue to be displayed via the Azure Portal and logs should be accessible via the Troubleshooting tab.

## Current Behavior
After updating to IoT Edge 1.4:

- When the acquisition of new modules starts, any attempt to get logs via the Troubleshooting tab times out, including for the system modules (edgeAgent and edgeHub). The output of the existing modules and the status of acquisition of new modules is impossible to see.
![image](https://user-images.githubusercontent.com/2903322/191825767-f0f1376b-a64d-4a15-8134-ed91ed1a3079.png)
- After a time, the **Runtime Status** column on the device's **Modules** tab shows as all **Error**s.
![image](https://user-images.githubusercontent.com/2903322/191825542-f5bd7366-9563-4580-b1b8-cf1705e3f09c.png)
- Some time later, after the modules have been updated, these experiences become operable again.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Update to IoT Edge 1.4 (previously 1.1).
2. Target a new layered deployment for the Edge device.
3. Visit the device in the Azure Portal and attempt to view the status of its modules.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
× aziot-identity-service package is up-to-date - Error
    could not query https://raw.githubusercontent.com/Azure/azure-iotedge/main/latest-aziot-identity-service.json for latest available version
‼ host time is close to reference time - Warning
    Could not query NTP server
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK



Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Failed to do TLS Handshake, Connection Attempt Timed out in 10 Seconds



Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
× aziot-edge package is up-to-date - Error
    Error while fetching latest versions of edge components: could not send HTTP request
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK



Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
26 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
3 check(s) raised errors. Re-run with --verbose for more details.
4 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details

```
</details>

### Device Information
* Host OS: Linux xxx.prod01.inroot.net 3.10.0-1160.53.1.el7.x86_64 #1 SMP Thu Dec 16 10:19:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Architecture: Red Hat Enterprise Linux Server release 7.9 (Maipo)
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4
* Docker/Moby [run `docker version`]: 20.10.17+azure-1

## Logs
Looking back through the `edgeAgent` logs to the impacted period we see the `OperationCanceledException` which has been described previously [here](https://github.com/Azure/iotedge/issues/6220) and determined by MS to be benign.
![image](https://user-images.githubusercontent.com/2903322/191829498-e5dca3a2-a932-4bce-9e17-9514ad1d33fd.png)

## Additional Information
This was initially encountered while testing the `ModuleUpdateMode`: `WaitForAllPulls` setting. However, even after reverting that setting to its default, this behaviour still occurred.

**Comment by veyalla** [comment]
This is expected behavior. edgeAgent is the component that is responsible for handling the logs related direct methods and pulling logs from the Moby/Docker engine in response. If it is busy starting modules, the log retrieval task can get starved and time/error out. 

We'll document this in our [limits and restrictions](https://learn.microsoft.com/azure/iot-edge/iot-edge-limits-and-restrictions?view=iotedge-1.4 ) page. Thanks for reporting. FYI @PatAltimore

**Comment by micahl** [comment]
Closing now that the Limits and Restrictions page has been updated to include a [Troubleshooting logs](https://learn.microsoft.com/azure/iot-edge/iot-edge-limits-and-restrictions?view=iotedge-1.4#troubleshooting-logs) section.
