### ISSUE TITLE
Modules out-of-sync after new layered deployment

### ISSUE THREAD

**Issue by thetanz-geoff** [Azure/iotedge#6685]
## Expected Behavior
When a layered deployment is created, module versions present on the edge device should eventually conform to the image version tags described in the deployment.

## Current Behavior
Sometimes, some modules update but others don't, and remain permanently stuck in this invalid configuration.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.

Background: _We have two modules. Module `b` depends on module `p`. When a layered deployment is published, `b` and `p` are both updated to a new version. `b` will try to communicate with `p`, and if `p` does not report the version that `b` is expecting, `b` will wait and retry until `p` does._

1. Current module images are `b:53609` and `p:53609`.
2. New layered deployment created, with images `b:53757` and `p:53757`. Incidentally, this layered deployment is newer but has the same priority as the previous layered deployment containing these images (may or may not be a contributing factor).
3. Some time later, we check the device's modules via the Azure Portal.

In this particular case, we can see that `b` has updated correctly:
![image](https://user-images.githubusercontent.com/2903322/191832635-f5474a80-36cb-4d69-bf3b-66232b8eba36.png)
but `p` has not:
![image](https://user-images.githubusercontent.com/2903322/191832750-e73aa502-3591-4bb1-85c8-6e2231607d96.png)
and our layered deployments report that 53757 believes it has been Applied correctly:
![image](https://user-images.githubusercontent.com/2903322/191832864-b550a0c6-8c33-4498-a653-514c601ef20a.png)
and `edgeAgent` is making a lot of noise about `p` but not saying very much:
![image](https://user-images.githubusercontent.com/2903322/191832987-e1603cfd-5e34-41c3-ad5e-d10c3d80cafe.png)

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
× aziot-identity-service package is up-to-date - Error
    could not query https://raw.githubusercontent.com/Azure/azure-iotedge/main/latest-aziot-identity-service.json for latest available version
‼ host time is close to reference time - Warning
    Could not query NTP server
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK



Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Failed to do TLS Handshake, Connection Attempt Timed out in 10 Seconds



Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
× aziot-edge package is up-to-date - Error
    Error while fetching latest versions of edge components: could not send HTTP request
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK



Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
26 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
3 check(s) raised errors. Re-run with --verbose for more details.
4 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details


```
</details>

### Device Information
Host OS: Linux xxx.prod01.inroot.net 3.10.0-1160.53.1.el7.x86_64 SMP Thu Dec 16 10:19:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Architecture: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.0
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4
* Docker/Moby [run `docker version`]: 20.10.17+azure-1

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
As detailed above.

## Additional Information
This specific instance was encountered after changing the `ModuleUpdateMode`: `WaitForAllPulls` setting back to its default, `NonBlocking`. However, we have seen this behaviour on occasion previously with IoT Edge 1.1.

**Comment by jlian** [comment]
@thetanz-geoff any updates?

**Comment by raisalitch** [comment]
@thetanz-geoff any updates on this? If not, we will go ahead and close this.

**Comment by thetanz-geoff** [comment]
Hi @and-rewsmith, sorry for the wait. In response to your questions:

1. We have gone straight to `1.4` from `1.1`, so can't speak as to `1.2` or `1.3`. If this issue has occurred under `1.1`, we have not observed it.
2. Unfortunately we have `RuntimeLogLevel` set to `Debug` for `edgeAgent` on another site, not the one which was affected.
3. After a series of attempts to reproduce, we can confirm that this behaviour only occurs if two layered deployments with matching priority are released. Ideally, the more recent should still supersede the older deployment, but I can appreciate that priorities should be increased as a matter of course. Can you please confirm the expected behaviour?
4. Will hold fire on the logs unless we see this issue again across deployments with differing priorities, or if you think they're of use for investigating #3.
5. We have `WaitForAllPulls` turned off (set to its default of `NonBlocking`), certainly.
6. Output of `iotedge list`:
![image](https://user-images.githubusercontent.com/2903322/193728712-5a221816-5893-40bf-83ef-4463f39b2153.png)

**Comment by and-rewsmith** [comment]
It is weird that layered deployment status effects this issue. The expected behavior should be that the most recently created deployment applies with priority. 

I see that in your screenshot, the desired module seems to be deployed though. Is this the same device you were seeing an issue with?

**Comment by raisalitch** [comment]
Hey @thetanz-geoff any updates? Is this the same device?

**Comment by raisalitch** [comment]
@thetanz-geoff We're going to close this for now. Please reopen if you need further help.

**Comment by veyalla** [comment]
Adding @nyanzebra who is looking into the area of layered deployments.

**Comment by nyanzebra** [comment]
@thetanz-geoff I have been trying to replicate something like this all day to no avail, so want to go through the exact steps for repro :)

1. Create a device in Hub
2. Create 1 deployment (layered) with say priority 100
3. Make sure edgeAgent has default value of NonBlocking for ModuleUpdateMode
4. verify both deployments were successful
5. Create another deployment (layered) with same priority (100)
6. See one module report correctly and the other not?

Have you always seen this with only your `b` and `p` modules or does this apply to any module? For example, is it always `p` that doesn't update? Or does this happen with say BlobStorage module too if layered deployment occurs?

If above steps are wrong or not quite correct, would you mind elaborating minimal viable reproduction?

**Comment by thetanz-geoff** [comment]
Discussion progressed with @nyanzebra via MS support channels. Edge device at issue was demonstrated. Edge Agent restart performed but since it came back up, the same issue persists.

In a couple of days the iot edge service on the device will be restarted, and if that doesn't help, we'll restart the device itself.

Looking forward to Robert's further investigation.

**Comment by nyanzebra** [comment]
@thetanz-geoff one quick update is I have tried to see if I have any issues with large images as I understand `b` and `p` to be ~1-2GiB. I tried with a 3GiB image and it worked fine, just to see if there were any timeout issues. I am now trying a layered deployment with updated version and will see if that works. Will also chat internally with team to see if there are any other ideas.

**Comment by nyanzebra** [comment]
@thetanz-geoff As spoken offline, things seem to be working with the only action item being a feature request for seeing if need to clear space for new images on device (@bishal41 tag for feature request). If this is all correct, should we close this issue or are there additional asks/issues?

**Comment by bishal41** [comment]
Hi @thetanz-geoff could you please open up a feature request using the below link and provide your use case and impact? https://feedback.azure.com/d365community/forum/0e2fff5d-f524-ec11-b6e6-000d3a4f0da0#

**Comment by micahl** [comment]
@thetanz-geoff please confirm there is no remaining action item.  I plan to close this issue in the next 2 days unless I hear otherwise.  If there is a feature request please open it at https://aka.ms/iotedge-suggestion.

**Comment by thetanz-geoff** [comment]
Sumptuous new feature request raised here: https://feedback.azure.com/d365community/idea/8b58939a-7c79-ed11-a81b-000d3ae5ae95

Closing this issue. The root cause was insufficient space on the device. In such cases, the layered deployment may show as "Applied" but the module versions have not been updated.

Thanks for the support.
