### ISSUE TITLE
Azure / azure-iotedge releases are broken again

### ISSUE THREAD

**Issue by sindelar-fr** [Azure/iotedge#6706]
Releases 1.1.16 LTS and 1.1.17 LTS are missing most of the artifacts which prevents meta-iotedge/dunfell-1.1 to be updated to the latest 1.1 LTS releases.

**Comment by varunpuranik** [comment]
@sindelar-fr - 
For both the releases in question - [1.1.16](https://github.com/Azure/azure-iotedge/releases/tag/1.1.16) and [1.1.17](https://github.com/Azure/azure-iotedge/releases/tag/1.1.17) - only the Docker images for EdgeHub and EdgeAgent were updated. The daemon (iotedged) was not updated and remains at version [1.1.15](https://github.com/Azure/azure-iotedge/releases/tag/1.1.15). 
So to upgrade to one of those versions, you don't need the artifacts as you don't need to update the iotedged. You can just update the Docker images via the deployment. Those images have been uploaded to mcr.microsoft.com registry. 
I will close this issue as addressed. Please feel free to open a new one, if you have any other issues.
