### ISSUE TITLE
Access to path is denied - Azure Iot Edge 1.4 version

### ISSUE THREAD

**Issue by amit12cool** [Azure/iotedge#6731]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6692132/196438863-8c336905-15fc-442b-bb64-81aa7a118f26.png)

I have mounted the host storage to `edgeAgent` module storage but I see that edgeAgent doesn't have access rights on the host storage. 
As per the docs of MS, ```https://learn.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4#automatic-host-system-permissions-management``` permission management is done automatically by the edge runtime. Am I missing something?

**Comment by vadim-kovalyov** [comment]
@amit12cool thanks for reporting this, and sorry to see you having this issue. Yes, from the docs it seems like it should work... can you, just in case, give me the output of `ls -l` on the host storage folder?

**Comment by amit12cool** [comment]
@vadim-kovalyov here are the output of 2 commands. Apologies for being late it was festival time here in India :-)

![tmp_233ba608-0103-4f8b-b1fe-88d0a0b7b84a.png](https://user-images.githubusercontent.com/6692132/198064328-fe92b906-73c5-4fd1-b3fa-dbf549c0495f.png)

```
 $ ls -l /etc/iotedge/storage/
total 4
drwx------ 2 edgeagentuser root 4096 Oct 18 09:18 edgeAgent
```

**Comment by vadim-kovalyov** [comment]
Hm... everything seems fine. Can you please try to stop the service, delete the `/etc/iotedge/storage/` folder, update the edge package to the latest one (1.4.2) and try again?

**Comment by amit12cool** [comment]
Hey @vadim-kovalyov It did resolve the issue. Thanks.

Is it the patch version of the sdk had the fix of the issue or deleting the ```/etc/iotedge/storage/``` did the trick?

**Comment by vadim-kovalyov** [comment]
The only reason I can think of if you have upgraded from previous version (<1.4). In this case the storage folder would have remain owned by a outdated user id, preventing the new functionality in 1.4 to work and set the proper permissions. So, answering your question - I think removing the folder did the trick.
