### ISSUE TITLE
IoTEdge Device is not communicating with IoT Hub and edgeHub not running

### ISSUE THREAD

**Issue by jcbendernh** [Azure/iotedge#6735]
I ran the default eFlow configuration and when I run a sudo iotedge list command, I only see the EdgeAgent running and not the EdgeHub.  I do not see any connection of the Edge device on the IoT Hub.

![Screenshot_20221020_065031](https://user-images.githubusercontent.com/16260984/196929401-73e8c627-ee98-4888-a7a2-5e218b9cb3f9.png)

Below are the verbose logs.  What is the best way to resolve this error?

iotedge-user@iotedge-vm [ ~ ]$ sudo iotedge check --verbose

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
× identityd config toml file specifies a valid hostname - Error
    identityd config has hostname iotedgesandbox-eflow but device reports hostname iotedge-vm.
    Hostname in identityd config must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
        caused by: identityd config has hostname iotedgesandbox-eflow but device reports hostname iotedge-vm.
                   Hostname in identityd config must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
‼ aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.3.0 but 1.4.1 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
        caused by: Installed aziot-identity-service package has version 1.3.0 but 1.4.1 is the latest stable version available.
                   Please see https://aka.ms/aziot-update-runtime for update instructions.
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
‼ aziot-edge package is up-to-date - Warning
    Installed IoT Edge daemon has version 1.3.0 but 1.4.2 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
        caused by: Installed IoT Edge daemon has version 1.3.0 but 1.4.2 is the latest stable version available.
                   Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
                   Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
                   You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Container engine is not configured to rotate module logs which may cause it run out of disk space.
                   Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
                   You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
        caused by: The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
                   Data might be lost if the module is deleted or updated.
                   Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: Could not check current state of edgeHub container
        caused by: docker returned exit status: 1, stderr = Error: No such object: edgeHub
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
27 check(s) succeeded.
5 check(s) raised warnings.
2 check(s) raised errors.
2 check(s) were skipped due to errors from other checks.

iotedge-user@iotedge-vm [ ~ ]$

**Comment by vadim-kovalyov** [comment]
Hey @jcbendernh, Vadim is here from Edge team. I'm not super familiar with how EFLOW packages and delivers our Edge installation, but to correct the error that you see, you need to update `hostname` property in `/etc/aziot/config.toml` and run `sudo iotedge config apply`.

> × identityd config toml file specifies a valid hostname - Error

It is still a good question for @fcabrera23 why the hostname was set to something other than the host machine name.

**Comment by jcbendernh** [comment]
I figured it out…  the behavior I saw was “normal”.  You only see the edgeAgent until you deploy a module to the device…

Note
On a newly provisioned device, you may see an error related to IoT Edge Hub:
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
Could not check current state of edgeHub container
This error is expected on a newly provisioned device because the IoT Edge Hub module isn't running. To resolve the error, in IoT Hub, set the modules for the device and create a deployment. Creating a deployment for the device starts the modules on the device including the IoT Edge Hub module.
From https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-on-windows-symmetric?view=iotedge-1.4&tabs=azure-portal%2Cpowershell#verify-successful-configuration

Once I added the Simulated Temperature sensor to the Edge Device and deployed it, everything is working as expected.

 
![Screenshot_20221020_013016](https://user-images.githubusercontent.com/16260984/197018164-22d4cbe2-7cb4-41b5-97a3-b06a3e2b856a.png)
![Screenshot_20221020_012951](https://user-images.githubusercontent.com/16260984/197018166-291013d0-8303-45d2-9991-48e1e27f330c.png)


I guess it was a case of RTFM on my part.  

I did delete the Azure VM and redo the instructions and the hostname error did not appear this time so that could have affected it to.

**Comment by fcabrera23** [comment]
Hi @vadim-kovalyov,

Thanks for your help. The change of hostname was CBL-Mariner issue that is already fixed with [1.1.2207.13102](https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2207.13102) and will be part of the next EFLOW 1.4LTS release.

If everything else is fixed, i think we can close this issue.

Thanks,
Francisco
