### ISSUE TITLE
Events from iotedge-moby event source on Windows cannot be properly queried due to missing EventMessageFile

### ISSUE THREAD

**Issue by DaveEM** [Azure/iotedge#674]
## Expected Behavior
The following command should return any relevant events logged by the iotedge-moby service instance of dockerd.exe:

Get-WinEvent -ea SilentlyContinue -FilterHashtable @{ProviderName='iotedge-moby';LogName='application';StartTime=[datetime]::Now.AddMinutes(-5)}

## Current Behavior
The Get-WinEvent command above returns the following error:

> Get-WinEvent : The parameter is incorrect
> At line:1 char:5
> \+     Get-WinEvent -ea SilentlyContinue -FilterHashtable @{ProviderName ...
> \+     \~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     \+ CategoryInfo          : NotSpecified: (:) [Get-WinEvent], EventLogException
>     \+ FullyQualifiedErrorId : System.Diagnostics.Eventing.Reader.EventLogException,Microsoft.PowerShell.Commands.GetWinEventCommand

In addition, looking in the Application event log with event viewer shows something like this:

> The description for Event ID 1 from source iotedge-moby cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> 824569b760f7f05239a531bc9a98212447feefac4a68a0ee501cdb6828e69950 cleanup: failed to delete container from containerd: no such container

## Steps to Reproduce
1. Install the Azure IoT Edge runtime in a VM running Server 2019 (17763.195) Datacenter Edition according to the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows.
2. Once everything is up and running, restart the iotedge-moby service.  At this point, due to another issue, warning and error logs will start being logged by iotedge-moby and will not be queryable via Get-WinEvent.

### Device (Host) Operating System
Windows Server 2019

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.5 (d76e0316c6f324345d77c48a83ce836d09392699)

#### Edge Agent
1.0 (logs say it's 1.0.5)

#### Edge Hub
1.0 (logs say it's 1.0.5)

#### Docker
Client:
 Version:           3.0.2
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by myagley** [comment]
Thanks for the issue report. It looks we need to add this step to the install script.

**Comment by myagley** [comment]
I hadn't realized that you also submitted a PR with a fix. Thank you so much!
