### ISSUE TITLE
iotedge check should perform connectivity check with DPS when it can

### ISSUE THREAD

**Issue by chriswue** [Azure/iotedge#6740]
As detailed in #1232, #2033, and #2313 the `iotedge check` command fails (now with warnings instead of an error) that it cannot perform the connectivity checks.

The rational given is that iotedge has no way to determine the target hub when DPS is involved. This seems factually wrong (at least in the absolute sense of "no way") since  the information can be found in `/var/lib/aziot/identityd/device_info` .
Granted the info may not always be present - depending on where in the state of the provisioning process via DPS the device is currently in but I'd argues it's there often enough.

`iotedge check` should at least do a best effort in trying to determine the hub rather than refusing outright.

For us it's important since the connectivity check covers 99% of all problems encountered at customer sites during install and commissioning phase by field service techs.

**Comment by bishal41** [comment]
@chriswue sorry for the delayed response here. I personally think this is a valid ask, but I am also afraid that we don't any near-term plan to integrate this feature. Dev team have acknowledged this issue. In the meantime, may I ask you create a feature ask or share this idea broadly in the community using this link https://feedback.azure.com/d365community/forum/0e2fff5d-f524-ec11-b6e6-000d3a4f0da0#? 

Please let me know once you are done sharing your ideas in the link that I provided. Thanks

**Comment by chriswue** [comment]
@bishal41 Done - https://feedback.azure.com/d365community/idea/a293d385-a566-ed11-a81b-000d3ae5ae95

**Comment by bishal41** [comment]
thanks @chriswue. We will review your ask and prioritize accordingly. It may take a while to get to this feature though, I just want to set up the right expectations Additionally, if other folks in the community are running into the same issue and they vote on your feedback, it will help us prioritize. I will now close this issue unless you have any additional questions. Thank you!
