### ISSUE TITLE
edgeAgent 1.4.2 bad permissions on persistent storage

### ISSUE THREAD

**Issue by emibcn** [Azure/iotedge#6741]
## Expected Behavior
The new version of edgeAgent allows setting a custom UID to use when creating the container running user, by setting the container env var `EDGEAGENTUSER_ID` (for edheHub it's `EDGEHUBUSER_ID`). Before starting the service, the entrypoint creates the user with the desired UID (using `13622` as default when not set). Then, sets the owner and permissions to files and directories needed by the service.

The expected behaviour is that, even without setting the `EDGEAGENTUSER_ID` env var, it would work as before.

## Current Behavior
A `permission denied` error arises and the container stops. Even more, if we fix the base deployment, it will not receive the update, as the edgeAgent is already unable to start.

### Workaround
In the base deployment, set the variables `EDGEAGENTUSER_ID` and `EDGEHUBUSER_ID` to the edgeAgent and edgeHub, respectively, to the value of `1000`. Then, recreate the persisted storage of both and restart the edgeAgent.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. In the base deployment, update to edgeAgent/edgeHub 1.4.2, without setting the env vars `EDGEAGENTUSER_ID` and `EDGEHUBUSER_ID`
2. When the edgeAgent receives the update and restarts itself, it will get to the error and permanently stop

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.10
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4.2
* Docker/Moby [run `docker version`]: 
  ```
  Client:
   Version:           20.10.17+azure-1
   API version:       1.41
   Go version:        go1.17.11
   Git commit:        100c70180fde3601def79a59cc3e996aa553c9b9
   Built:             Mon Jun  6 21:36:39 UTC 2022
   OS/Arch:           linux/amd64
   Context:           default
   Experimental:      true

  Server:
   Engine:
    Version:          20.10.17+azure-1
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.17.11
    Git commit:       a89b84221c8560e7a3dee2a653353429e7628424
    Built:            Mon Jun  6 22:32:38 2022
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.5.13+azure-1
    GitCommit:        a17ec496a95e55601607ca50828147e8ccaeebf1
   runc:
    Version:          1.0.3
    GitCommit:        f46b6ba2c9314cfc8caae24a32ec5fe9ef1059fe
   docker-init:
    Version:          0.19.0
    GitCommit:      
  ```

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

![image](https://user-images.githubusercontent.com/693791/197991793-11270043-ae9b-4be9-a8cb-51fb6492f557.png)

</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by ancaantochi** [comment]
The default UID change from 1000 was as part of security fix. I see that documentation is still describes how to set permissions using UID 1000 and that should be updated.

**Comment by emibcn** [comment]
Hmmm, but if the container uses the default UID 13622 and its entrypoint does a `chown` before calling the service, ¿shouldn't it just work? I still see a bug in there, unless the installation process changes significantly.

**Comment by gordonwang0** [comment]
The automatic fixing of permissions only works if the edgeagentuser and edgehubuser (uid 13622 and 13623, respectively) already exist on your system. Could you check that they exist?

**Comment by emibcn** [comment]
@gordonwang0 Could you please link the documentation where this is stated?

**Comment by ancaantochi** [comment]
@emibcn 
I am sorry for the delayed reply. I was not able to reproduce the issue, I tried to upgrade edgeAgent from 1.2.10 to 1.4.2 or 1.4.3 
The user 13622 should be created when edgeAgent starts, unless it already exists in which case the ownership change should work. From your logs it looks like the user already exists because it doesn't have log line "Creating UID 13622 as edgeagentuser" before the " Changing ownership of storage folder ...". 
If you upgraded from 1.2.10 the user should not exists already on the system, can you please provide the exact steps that you took to upgrade?
please also check what is the ownership of the edgeAgent folder: 
`ls -l /iotedge/storage`

**Comment by micahl** [comment]
@emibcn we're unable to reproduce this issue.  Can you provide the repro steps you took to upgrade that we should try?  We'll plan to close this issue by end of week if there's no response.
