### ISSUE TITLE
Exceptions thrown on module reauthentication

### ISSUE THREAD

**Issue by sebader** [Azure/iotedge#676]
## Expected Behavior

Edge Hub should run stable and without throwing random error messages.

## Current Behavior

Sometimes - apparently every 70 minutes - when the Edge Hub starts "Reauthenticating connected clients", it throws a exceptions due to expired SAS token and removes the module connections. Just after that, it will re-authenticate the module after all, and connect it again.
This a) throws unnecessary errors and b) seems like module connections are being dropped every once in a while which might lead to unstable behavior.

## Steps to Reproduce

1. Have a couple of modules running normally.
2. Wait ... in my logs over night, this actually seems to happen more or less **every 70 minutes**

### Device (Host) Operating System

Ubuntu 16.04

### Architecture

amd64

### Container Operating System

Linux
#### iotedged

1.0.5
#### Edge Agent

1.0.5
#### Edge Hub

1.0.5
## Logs

I cleaned the log so that only messages from one module are in there. But I have several modules running and all throw the same error.

> 2019-01-03 06:28:20.833 +00:00 [INF] - Reauthenticating connected clients
> 2019-01-03 06:28:20.834 +00:00 [WRN] - Error authenticating token for minimalUbuntu/tempgenerator because the token could not be parsed
> System.UnauthorizedAccessException: The specified SAS token is expired
>    at Microsoft.Azure.Devices.Common.Security.SharedAccessSignature..ctor(String iotHubName, DateTime expiresOn, String expiry, String keyName, String signature, String encodedAudience)
>    at Microsoft.Azure.Devices.Common.Security.SharedAccessSignature.Parse(String iotHubName, String rawToken)
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Authenticators.DeviceScopeTokenAuthenticator.TryGetSharedAccessSignature(String token, IIdentity identity, SharedAccessSignature& sharedAccessSignature) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs:line 46
> 2019-01-03 06:28:20.835 +00:00 [INF] - Credentials for client minimalUbuntu/tempgenerator are not valid.
> 2019-01-03 06:28:20.835 +00:00 [WRN] - Reauthenticating client minimalUbuntu/tempgenerator failed, removing client connection
> 2019-01-03 06:28:20.836 +00:00 [INF] - Unable to re-authenticate minimalUbuntu/tempgenerator, dropping client connection.
> 2019-01-03 06:28:20.836 +00:00 [WRN] - Closing connection for device: minimalUbuntu/tempgenerator, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device minimalUbuntu/tempgenerator.,
> 2019-01-03 06:28:20.836 +00:00 [INF] - Disposing MessagingServiceClient for device Id minimalUbuntu/tempgenerator because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device minimalUbuntu/tempgenerator.
> 2019-01-03 06:28:20.838 +00:00 [INF] - Closing device proxy for device Id minimalUbuntu/tempgenerator
> 2019-01-03 06:28:20.838 +00:00 [INF] - Device connection removed for device minimalUbuntu/tempgenerator
> 2019-01-03 06:28:21.379 +00:00 [INF] - Client minimalUbuntu/tempgenerator in device scope authenticated locally.
> 2019-01-03 06:28:21.379 +00:00 [INF] - Successfully generated identity for clientId minimalUbuntu/tempgenerator and username minimal-iotedge-vm/minimalUbuntu/tempgenerator/?api-version=2018-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.18.1%20%28.NET%20Core%204.6.27019.06%3B%20Linux%204.15.0-1035-azure%20%2336-Ubuntu%20SMP%20Fri%20Nov%2030%2012%3A47%3A16%20UTC%202018%3B%20X64%29
> 2019-01-03 06:28:21.379 +00:00 [INF] - ClientAuthenticated, minimalUbuntu/tempgenerator, 67d9b543
> 2019-01-03 06:28:21.380 +00:00 [INF] - New device connection for device minimalUbuntu/tempgenerator
> 2019-01-03 06:28:21.381 +00:00 [INF] - Bind device proxy for device minimalUbuntu/tempgenerator
> 2019-01-03 06:28:21.387 +00:00 [INF] - Binding message channel for device Id minimalUbuntu/tempgenerator
> 2019-01-03 06:28:21.388 +00:00 [INF] - Processing subscription TwinResponse for client minimalUbuntu/tempgenerator.
> 2019-01-03 06:28:21.388 +00:00 [INF] - Set subscriptions from session state for minimalUbuntu/tempgenerator

> 2019-01-03 07:33:20.831 +00:00 [INF] - Reauthenticating connected clients
> 2019-01-03 07:38:20.829 +00:00 [INF] - Reauthenticating connected clients
> 2019-01-03 07:38:20.830 +00:00 [WRN] - Error authenticating token for minimalUbuntu/tempgenerator because the token could not be parsed
> System.UnauthorizedAccessException: The specified SAS token is expired
>    at Microsoft.Azure.Devices.Common.Security.SharedAccessSignature..ctor(String iotHubName, DateTime expiresOn, String expiry, String keyName, String signature, String encodedAudience)
>    at Microsoft.Azure.Devices.Common.Security.SharedAccessSignature.Parse(String iotHubName, String rawToken)
>    at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Authenticators.DeviceScopeTokenAuthenticator.TryGetSharedAccessSignature(String token, IIdentity identity, SharedAccessSignature& sharedAccessSignature) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs:line 46
> 2019-01-03 07:38:20.830 +00:00 [INF] - Credentials for client minimalUbuntu/tempgenerator are not valid.
> 2019-01-03 07:38:20.831 +00:00 [WRN] - Reauthenticating client minimalUbuntu/tempgenerator failed, removing client connection
> 2019-01-03 07:38:20.831 +00:00 [INF] - Unable to re-authenticate minimalUbuntu/tempgenerator, dropping client connection.
> 2019-01-03 07:38:20.831 +00:00 [WRN] - Closing connection for device: minimalUbuntu/tempgenerator, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device minimalUbuntu/tempgenerator.,
> 2019-01-03 07:38:20.831 +00:00 [INF] - Disposing MessagingServiceClient for device Id minimalUbuntu/tempgenerator because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device minimalUbuntu/tempgenerator.
> 2019-01-03 07:38:20.833 +00:00 [INF] - Closing device proxy for device Id minimalUbuntu/tempgenerator
> 2019-01-03 07:38:20.833 +00:00 [INF] - Device connection removed for device minimalUbuntu/tempgenerator
> 2019-01-03 07:38:21.340 +00:00 [INF] - Client minimalUbuntu/tempgenerator in device scope authenticated locally.
> 2019-01-03 07:38:21.340 +00:00 [INF] - Successfully generated identity for clientId minimalUbuntu/tempgenerator and username minimal-iotedge-vm/minimalUbuntu/tempgenerator/?api-version=2018-06-30&DeviceClientType=Microsoft.Azure.Devices.Client%2F1.18.1%20%28.NET%20Core%204.6.27019.06%3B%20Linux%204.15.0-1035-azure%20%2336-Ubuntu%20SMP%20Fri%20Nov%2030%2012%3A47%3A16%20UTC%202018%3B%20X64%29
> 2019-01-03 07:38:21.342 +00:00 [INF] - ClientAuthenticated, minimalUbuntu/tempgenerator, 33196e6f
> 2019-01-03 07:38:21.343 +00:00 [INF] - New device connection for device minimalUbuntu/tempgenerator
> 2019-01-03 07:38:21.343 +00:00 [INF] - Bind device proxy for device minimalUbuntu/tempgenerator
> 2019-01-03 07:38:21.343 +00:00 [INF] - Binding message channel for device Id minimalUbuntu/tempgenerator
> 2019-01-03 07:38:21.345 +00:00 [INF] - Processing subscription TwinResponse for client minimalUbuntu/tempgenerator.
> 2019-01-03 07:38:21.345 +00:00 [INF] - Set subscriptions from session state for minimalUbuntu/tempgenerator

**Comment by varunpuranik** [comment]
Hi @sebader - Thanks for the issue.
This behavior is by design. EdgeHub checks the tokens for all connected clients periodically, and will drop the connection if a client token is expired. On MQTT there is no token refresh mechanism, and by default the token expiry period is 60 mins. So after about 65~70 mins, EdgeHub token validation will fail and EdgeHub will bounce the connection, with the expectation that the client will reopen the connection. 
We can maybe update EdgeHub to log the exception only in debug mode, so that the logs stay clean..

**Comment by sebader** [comment]
Thanks for the quick response!
Just to double check: So when using AMQP to connect modules to the Edge Hub, the connection should stay stable and not getting reconnected?!

**Comment by varunpuranik** [comment]
Yes, that is correct - for AMQP, we should not see this.
