### ISSUE TITLE
Connect container to azure-iot-edge and local docker network.

### ISSUE THREAD

**Issue by satfl** [Azure/iotedge#6760]
Hello. We are trying to deploy a docker image to an Azure IoTEdge device. 
If we do not specify any networking in Container Create options in Deployment, it automatically connects to the `azure-iot-edge` network. However, we need our container to also be connected to another network `local_network_name` in addition to `azure-iot-edge` network. 
If we try to specify both networks in Container Create options our container fails to start because `azure-iot-edge` network is non Attachable. We have been able to get it running in the lab by manually connecting our container to the `azure-iot-edge` network after it has been created. 

Our container has to be able to communicate to both EdgeHub and local containers in order to function. 
Is there a way we can resolve this issue?

**Comment by huguesBouvier** [comment]
Could you describe in detail what commands and how you could manually connect your container to iotedge network?
I am not sure what can be done yet, I just want to understand the problem better.

**Comment by mortenn** [comment]
The manual connection was just done in the portainer gui of the device.
I am not entirely sure what commands you refer to, we only configured it using json in the azure portal

**Comment by satfl** [comment]
> Could you describe in detail what commands and how you could manually connect your container to iotedge network? I am not sure what can be done yet, I just want to understand the problem better.

So, if we use the following Container Create Options  while configuring the Deployment in Azure Portal:

```
{
    "NetworkingConfig": {
        "EndpointsConfig": {
            "local_network_name": {}
        }
    }
}
```
Our container connects to the `local_network_name` automatically. When our container is on this network, we somehow see logs on the Azure Portal. However, when we need to register Method Handlers - it doesn't work. If we go to the Portainer and connect our container to the `azure-iot-edge` network - then it is possible to register Method Handlers. So we trying the following Container Create Options:
```
{
    "NetworkingConfig": {
        "EndpointsConfig": {
            "local_network_name": {},
             "azure-iot-edge":{}
        }
    }
}
```
In this case our container fails to start because the `azure-iot-edge` is non Attachable ("Attachable": false from docker network inspect). However, if we leave Container Create Options empty - our container connects to `azure-iot-edge` on arrival.

Just to clarify what we want to do: we want our container to connect to both networks on arrival.

**Comment by huguesBouvier** [comment]
I checked the code, I currently don't see a way to set it as attachable. It looks like it hardcoded as false.
https://github.com/Azure/iotedge/blob/54163699b0db1b1c8eb3ff5b7ab15fd5f6137857/edgelet/docker-rs/src/models/network.rs#L55

I'll check internally if there is a reason why but for now manually seem to be the only way to go.

**Comment by mortenn** [comment]
It won't neccessarily have to be attachable, as long as we can attach the container to other networks without the default behaviour of being attached to it is not overridden. I can guess there are some valid security arguments for keeping it unattachable.
Seeing as how we can attach the image to either network manually after it has been created, would it be possible for the agent to do the same?

**Comment by mortenn** [comment]
alternatively, if there is some other way we can get our image to be able to open the connection it uses to register direct method handlers without being on the azure-iot-edge network, that would also be acceptable

**Comment by satfl** [comment]
> I checked the code, I currently don't see a way to set it as attachable. It looks like it hardcoded as false.
> 

What is not clear as to why if edgeAgent, edgeHub and our container reside tgether in `local_network_name` our container still unable to register method handlers.
It is also somewhat confusing that it is possible to use `docker network connect` from console to connect container to the network which has `attachable` option set to `false`.

**Comment by huguesBouvier** [comment]
If you do the opposite it should work:
>{
>    "NetworkingConfig": {
>        "EndpointsConfig": {
>             "azure-iot-edge":{}
>        }
>    }
>}

Then 
> docker network connect local_network_name <container-name>

**Comment by huguesBouvier** [comment]
I am going to log it as a feature request. Currently, ASAIK, there is not way to do it automatically.

**Comment by mortenn** [comment]
roger that, I am considering changing the architecture so we don't need to add the private local network - it contains an instance of postgresql and the hope was to avoid running two separate RDBMs on single raspberry

**Comment by huguesBouvier** [comment]
I'll close the issue, let us know if you need anything else!

**Comment by skyrimax** [comment]
I didn't find the feature request metioned above, so I opened one, here is the link if other people stumbling upon this issue want to upvote it

https://feedback.azure.com/d365community/idea/530cbbff-881e-ef11-989a-000d3ae2b698
