### ISSUE TITLE
Can't set the restart policy to be "unless-stopped"

### ISSUE THREAD

**Issue by Punnpd** [Azure/iotedge#6768]
## Expected Behavior
Be able to set the restart policy of the module
## Current Behavior
The manifest is as follows
<img width="557" alt="image" src="https://user-images.githubusercontent.com/79767186/200739456-6249928b-331d-4904-a564-79db93d8a941.png">
When deploying the module, 
<img width="535" alt="image" src="https://user-images.githubusercontent.com/79767186/200739115-658b91eb-193d-4eb8-85cf-749828ce781f.png">

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.
2.
3.
4.

**Comment by huguesBouvier** [comment]
We don't currentlu support "unless-stopped",  I will add this as a feature request.

**Comment by Punnpd** [comment]
Oh, ok I got it. Do you have any suggestions or workaround solutions if we need this? @huguesBouvier

**Comment by huguesBouvier** [comment]
The only way I see is creating a "special" module that will watch for stopped containers and restart them.

**Comment by Punnpd** [comment]
Do you mean the separated module outside of my main module? 
or I can do it within 1 module?

**Comment by huguesBouvier** [comment]
You can do it withing one module, but if that module is stopped the monitoring will stop too! It doesn't need to be in one module, it can also be a watch on the host.

**Comment by bishal41** [comment]
@Punnpd could you also please share your feedback or feature request in this below forum? This was other folks can vote and we can prioritize accordingly. Thanks.
https://feedback.azure.com/d365community/forum/0e2fff5d-f524-ec11-b6e6-000d3a4f0da0# ?

**Comment by bishal41** [comment]
@Punnpd please let me know if you were able to share your feedback in the link I provided. We will periodically go over the feedback that we have received and prioritize them as needed. If you don't have any other questions, I will proceed and close this issue. thanks

**Comment by bishal41** [comment]
Closing this issue. @Punnpd please do submit a feedback request using the link I provided if you haven't already done so and feel free to open this issue if needed. Thank you!
