### ISSUE TITLE
Error grabbing logs: log message is too large (2349467251 > 1000000)

### ISSUE THREAD

**Issue by andregodin** [Azure/iotedge#6777]
I'm trying to use Troubleshoot from the Azure Portal for a custom module deployed on an IoT Edge Device.

When I click of the Time range criteria and I check the "Enter time instead" to retrieve log of a specific period It gives me the error

**Error grabbing logs: log message is too large (2349467251 > 1000000)**

## Expected Behavior
I should be able to consult the Troubleshoot Logs 

## Current Behavior
the text "Error grabbing logs: log message is too large (2349467251 > 1000000)" is displayed instead of the logs entries

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Goto an Azure Portal IotEdge
3. Open a Device
4. click to open the detail of a module
5. open the "Troubleshoot" 
6. click the "Time range" criteria and check the "Enter time instead" to retrieve log of a specific period 
7. click "Apply"

You can see in the image below that the only logs I have (behind the Time range box) are not so large
![image](https://user-images.githubusercontent.com/43258445/201440047-c9b5eadd-36c4-473c-bf92-8ded93e1f22d.png)

In the following image is the result I have after I click the Apply button
![image](https://user-images.githubusercontent.com/43258445/201440204-d205c0e0-237a-4576-9259-4c69d2ca6512.png)

I also reproduced the issue with a time range of 1 second 
![image](https://user-images.githubusercontent.com/43258445/201440290-1c0599ee-ba60-446b-9213-8a413d3e66d2.png)

### Device Information
* Host OS : Ubuntu 20.04.5 LTS
* Architecture : amd64
* Container OS:  Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.4.1
* Edge Agent [image tag (e.g. 1.0.0)]:  1.4.0.59620487 (157650c3b1c5fb58b17f5975e6f1417a5a5f4f89)
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4.0.59620487 (157650c3b1c5fb58b17f5975e6f1417a5a5f4f89)
* Docker/Moby [run `docker version`]: 
![image](https://user-images.githubusercontent.com/43258445/201440667-10c9a113-e201-4620-ae9f-54e82fbc3844.png)

## Additional Information
I first detected the new behaviour since yesterday (or maybe this morning) by using DirectMethod GetModuleLogs with the since parameter : 

![image](https://user-images.githubusercontent.com/43258445/201441182-6841890c-e58b-41cd-a055-d675104fb4a1.png)

**Comment by huguesBouvier** [comment]
Thanks! 

Note for later tracking: I noticed that same issue in a customer provided support bundled.
I tried to repro the issue with a big log but didn't encounter the problem. It seems to repro inconsistently.
