### ISSUE TITLE
Visual Studio Code extension unaware of 1.3, 1.4

### ISSUE THREAD

**Issue by TAMHAN** [Azure/iotedge#6778]
## Expected Behavior
In Visual Studio Code, running " Azure IoT Edge: Set default IoT Edge runtime version."  SHOULD IMHO list 1.3 and 1.4.

## Current Behavior
Only 1.0, 1.1 and 1.2 are offered as shown in the screenshot.

![Screenshot from 2022-11-14 07-28-09](https://user-images.githubusercontent.com/15024709/201590383-aa23209b-f6a2-43c4-9c27-b55ac8057e0c.png)

## Steps to Reproduce

Provide a detailed set of steps to reproduce the bug.
1. Open Command Palette
2. Run Azure IoT Edge: Set default IoT Edge runtime version.
3. Check content of list

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Ubuntu 20.04
* Architecture [e.g. amd64, arm32, arm64]: 
* amd64
* Container OS [e.g. Linux containers, Windows containers]: 
* Not relevant, dev tool issue

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by konichi3** [comment]
Thank you for reporting the issue. Including @PatAltimore for awareness.

This is [known issue](https://github.com/microsoft/vs-azure-iot-edge-docs/issues/43) and you can manually modify the deployment manifest to the target IoT Edge runtime.

We are currently working on the documentation across multiple articles to clarify.

**Comment by PatAltimore** [comment]
Thanks @TAMHAN ,

Until we release the documentation update, you can follow the steps to set the runtime version outlined in the CLI version of the article. https://learn.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-1.4&tabs=c&pivots=iotedge-dev-cli#set-iot-edge-runtime-version 

Thanks,
Pat

**Comment by TAMHAN** [comment]
Hello Pat,
sorry for being slow in responding here. I was traveling to West Germany...

So, if I understand this correctly, I edit the deployment file like so:
...
"systemModules": {
    "edgeAgent": {
    ...
        "image": "mcr.microsoft.com/azureiotedge-agent:1.4",
    ...
    "edgeHub": {
    ...
        "image": "mcr.microsoft.com/azureiotedge-hub:1.4",
    ...

**Comment by PatAltimore** [comment]
Hi @TAMHAN ,

I hope you had a great trip. Yes, that's right. You need to update your deployment manifest and change the image version to 1.4. The ellipsis ... is intended to remove irrelevant sections of the manifest file. You just need to change the two "image" lines in the manifest.

The documentation update has been published. You should see a similar explanation in the article now.

Thanks,
Pat

**Comment by konichi3** [comment]
Given we have published a documentation describing how to modify deployment manifest to change Edge version, we are closing the item
