### ISSUE TITLE
Request to re-open #6685

### ISSUE THREAD

**Issue by thetanz-geoff** [Azure/iotedge#6786]
I am unable to fulfill @raisalitch's request that I re-open #6685 due to outstanding concerns. Please refer to details on that issue.

**Comment by thetanz-geoff** [comment]
Now re-opened by @veyalla. Thanks!

**Comment by nyanzebra** [comment]
Can this be closed @thetanz-geoff now that 6685 is reopened?

**Comment by thetanz-geoff** [comment]
Yes, my previous comment should have closed it. Odd behaviour.
