### ISSUE TITLE
IoT edge runtime 1.4.2 custom modules are "Module Identity"s for a really long time in the iot hub

### ISSUE THREAD

**Issue by FinitelyFailed** [Azure/iotedge#6788]
Hi,

There seems to be a difference between how IoT Edge runtime 1.2 and 1.4 works when it comes to reporting custom modules to the IoT hub.

When a device running 1.2 gets custom modules via a layer deployment they quickly becomes "IoT Edge Custom Module".
However when a device running 1.4 (1.4.2) gets custom modules via a layer deployment they stay "Module Identity"s for a long time, 10+ mins. Until they turn into "IoT Edge Custom Module"s.

This is quite an issue for us as we listen for when a new modules is created, via life cycle events. To be able to add some properties on the module twin. Our query is base on device.modules, where we know the deviceId. When using 1.2 this works, but when using 1.4 we get no hits. And therefore the module twins stay unmodified.

Is there some kind of configuration that can be done on the device (config.toml) or via a deployment?

Soon after the modules are added via the layer deployment:
![Screenshot 2022-11-18 at 11-31-37 Microsoft Azure](https://user-images.githubusercontent.com/26271794/202686594-4a841360-3e47-4f96-9029-292835118331.png)

After about 10-15 min:
![Screenshot 2022-11-18 at 11-32-14 Microsoft Azure](https://user-images.githubusercontent.com/26271794/202686379-8c3c4d3a-f5d5-4c21-a044-e161a36a5171.png)

**Comment by nyanzebra** [comment]
@FinitelyFailed just to make sure I understand the probelm correctly

You have recently done a 1.2 deployment and see the custom modules get reported quickly in hub. However when using 1.4 it takes ~15 to show up?

Would you mind also explaining a bit about your setup? OS, nested/single device, proxy, etc?

Would also be great if this is reproducible to share edgeAgent logs, edgeHub logs and the results of `iotedge check`. 

I will create a local copy and see if can replicate behaviour observed.

@varunpuranik & @micahl do we have any known changes to twin report time or hub changes for display?

**Comment by micahl** [comment]
@nyanzebra we have https://github.com/Azure/iotedge/commit/e43cdc91a7969d8029c679d2b169f0682bf65e18 to fix an issue where the initial update to reported properties was delayed.  The fix is pending the next 1.4.x patch release which is in testing right now.  Not sure if it's the same issue here.

**Comment by FinitelyFailed** [comment]
@nyanzebra in the iot hub we have:

- A deployment with edgeAgent and edgeHub 1.2.8, which targets devices with some specific tags on the twin. So that a device running runtime 1.2.6 will get targeted.
- A deployment with edgeAgent and edgeHub 1.4.2, which targets devices with some other specific tags on the twin. So that a device running runtime 1.4.2 will get targeted.
- A layer deployment contain our 3 custom modules, which will target both kinds of devices, no matter which runtime the device runs.

When we run `iotedge config mp --connection-string "<connection-string>"` and `iotedge config apply` on a  device with:
- IoT edge runtime 1.2.6: It takes maybe 3-5 mins before it gets all the modules. And most importantly the modules gets reported in the iot hub as "IoT Edge Custom Module" as soon as the layer deployment is handled by the edgeAgent.
- IoT edge runtime 1.4.2: The custom modules are reported as "Module Identity"s for a really long time before they are reported as "IoT Edge Custom Module". Which breaks our jobs which handles the device and module twins in the cloud.

The only difference between the two setups are the versions of the runtime and the system modules.

Our devices run a custom RaspberryPi OS buster, armv7 (no we can't upgrade to bullseye). We have applied the [workaround for iot edge runtime 1.3+](https://github.com/Azure/azure-iotedge/releases/tag/1.3.0) on the device. I really hope that this issue isn't connected to the workaround. 

The setup is single device.

I do not have access to the devices until Monday, so I can't supply you with any logs until then.

**Comment by nyanzebra** [comment]
@FinitelyFailed seems we might have a new release soon 1.4.3. Would you mind upgrading and seeing if that resolves your problem?

**Comment by FinitelyFailed** [comment]
@nyanzebra with 1.4.3 this issue seems to be resolved. Thanks. :)
