### ISSUE TITLE
Updating modules

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#68]
Hi there,

When I'm trying to update a module by using "Create deployment to single device" in VSC, it states Deployment succeeded. However on my device the module seems to keep running, and I don't see any changes in behavior until I completely reset IoT Edge.

What is required to force the module to re-run with the new deployed code? Or am I thinking about this whole process the wrong way?

**Comment by dsajanice** [comment]
Can you please provide some more information on the full container image names (including tags) you created before and after the deployment. The Edge Agent will only detect a change in image if the new image tag differs from the previous one. If both images are pushed with tag 'latest', the Edge Agent will not detect the change in deployment and will only pull the new image the next time IoT Edge is reset.

**Comment by nhuurnink** [comment]
Oh that is based on meta info and not on changes in code itself? That would explain my case.
What is the recommended approach to do this via visual studio code? Up the version? Cause this feels like overkill during development.

**Comment by dsajanice** [comment]
Yes, please up the version. If you are using the VS Code extension, it can be changed in module.json. The Edge Agent cannot detect changes in code because the code is packaged inside a container. It detects a change in container based on the properties of the image.

**Comment by nhuurnink** [comment]
Ok clear, thanks!

**Comment by nkolchakov** [comment]
If I have the image can I update the module manually though Portal or something w/o using Visual Studio Code functionality ?

**Comment by elliotchaim** [comment]
@dsajanice I am updating the version in the module.json file, yet still experiencing the issue which @nhuurnink described. Any advice?
