### ISSUE TITLE
Unable to locate package aziot-edge

### ISSUE THREAD

**Issue by iliam** [Azure/iotedge#6811]
I'm trying to install aziot-edge on Debian 11, but I face an error that unable to locate the package. Any suggestion? 
![azure error](https://user-images.githubusercontent.com/13187974/206231270-9c5679f3-da30-4363-af53-25e5648aafa3.png)

**Comment by brotherneeru** [comment]
Please confirm you are using an ARM32-based device, as Debian 11 is only supported for that architecture: https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-2018-06#linux-containers. If you are, please reopen this issue following our template found here: https://github.com/Azure/iotedge/issues/new/choose

**Comment by ziutoslav** [comment]
Hi, I've got the same problem.
I use Raspberry Pi 4
Debian was downloaded from here https://raspi.debian.net/

`lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
pi@rpi4-20220121:~$ sudo apt-get install aziot-edge
sudo: unable to resolve host rpi4-20220121: Name or service not known
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package aziot-edge
pi@rpi4-20220121:~$ ^C
pi@rpi4-20220121:~$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
`

`cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

Will be really gratefull for any help
Best Regards

**Comment by iliam** [comment]
RaspberryPi has ARM64 as CPU, there is no Tire 1 device instruction. (https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.4).
I moved forward with Ubunto 20 instruction for ARM64 with some modifications. I tested it, and it worked for my application. While I do not take responsibility for the results (due to lack of enough tests and so on), here is how you can do it:

1) wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

1*) you may need to install iptables:
     apt-get install iptables

2)sudo apt-get update; \
   sudo apt-get install moby-engine

3) Create the Docker daemon's config file at /etc/docker/daemon.json.

Insert the below text in json file:

   {
      "log-driver": "local"
   }

4) sudo systemctl restart docker

Now you need to test it. But you need to have the kernal config, unzipped in /proc
So do this:

-   sudo modprobe configs
-   zcat /proc/config.gz > .config

Now you can test by:

5) curl -ssl https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh -o check-config.sh
chmod +x check-config.sh
./check-config.sh

Now install MS defender:

6) sudo apt-get update; \
  sudo apt-get install aziot-edge defender-iot-micro-agent-edge

Let me know if you face issues. There are other ways to install which you need to take more step by install package by package.
