### ISSUE TITLE
Question: How can an IoT module get notified when the module twin connection state changes?

### ISSUE THREAD

**Issue by dominique-ruest** [Azure/iotedge#6815]
I have created a C# edge module for a raspberry pi that controls a module through GPIO using twin configuration. I need to change the GPIO state when the edge device loses connection to the iot hub. How can this be achieved using the sdk? The module client and twin object do not appear to expose that functionality.

**Comment by ggjjj** [comment]
To find if the device connection status you can use the device client SDK API. sample [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/main/iothub/device/samples/how%20to%20guides/DeviceReconnectionSample)

**Comment by dominique-ruest** [comment]
Those samples apply to DeviceClient. The code I have runs inside an iotedge module using the ModuleClient. My understanding is that the DeviceClient cannot/should not (?) be created inside a module. Is this correct? If so, my issues lies with the fact that the ModuleClient does not expose the connection state of the edgeHub with the iothub. The moduleclient appears to expose only the state of its connection with the edgeHub.

**Comment by ggjjj** [comment]
Correct
_If so, my issues lies with the fact that the ModuleClient does not expose the connection state of the edgeHub with the iothub._
> Currently there is no mechanism to find this via SDK module client

**Comment by micahl** [comment]
@dominique-ruest Does that custom module depend on IoT Edge capabilities (e.g. store and forward of edgeHub, being deployed as part of a deployment manifest, etc.)?  It may be feasible to create a non-containerized process that uses the SDK and establishes its own connection to IoT Hub as the IoT Edge device in which case you could do what the sample shows.  The trade-off, of course, is that other than using the device's identity, that process couldn't leverage IoT Edge's runtime capabilities.

**Comment by dominique-ruest** [comment]
Yes the module is deployed alongside other modules on a raspberry pi leveraging the edgeHub functionalities.

**Comment by micahl** [comment]
> Yes the module is deployed alongside other modules on a raspberry pi leveraging the edgeHub functionalities.

And that one module also requires edgeHub functionality?  It's OK if there are edge modules.  The idea here would be to create [a device agent](https://azure.github.io/iot-identity-service/develop-an-agent.html) that runs SxS with IoT Edge.  Here's an [example in C#](https://github.com/vslepakov/iot-identity-service-agent).  It could use the device identity (or a module identity) and would be establishing its own direct connection to IoT Hub to observe the status.

**Comment by dominique-ruest** [comment]
That one module indeed does not need the edgeHub. It is deployed as a module at the moment for the convenience of deploying updates using a single deployment manifest. I will try out the approach you suggested which seems reasonable for my use case.

Thank you!

**Comment by micahl** [comment]
> That one module indeed does not need the edgeHub. It is deployed as a module at the moment for the convenience of deploying updates using a single deployment manifest. I will try out the approach you suggested which seems reasonable for my use case.

Yes, using this approach you'd need some other mechanism to deploy / update that module.  E.g. if you packaged it as a .deb then there are things like [Device Update for IoT Hub](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-ubuntu-agent) that could be used.  Just note that the deployment process for it would be distinct from your IoT Edge modules.

> (please consider making the twin connection state available to modules as it would simplify implementing some interesting use cases)
Great suggestion!  Please consider adding it to https://aka.ms/iotedge-suggestion (or upvoting an existing idea if you feel it matches yours).

OK to close this issue?

**Comment by dominique-ruest** [comment]
Yes, I will add it to suggestion, thanks!

**Comment by micahl** [comment]
> Yes, I will add it to suggestion, thanks!

OK, if you post the link to your suggestion here then anyone else who runs across this github issue can follow your link to upvote your suggest.  ;)  Since I don't recall if you can add comments after the issue is closed I'll hold off till tomorrow on marking it closed.  Feel free to close it early.

**Comment by dominique-ruest** [comment]
Upvote link: https://feedback.azure.com/d365community/idea/ff6fef09-7f7a-ed11-a81b-000d3adb7ffd
