### ISSUE TITLE
Potential mismatch between Ubuntu package and module runtimes

### ISSUE THREAD

**Issue by arminghasemazar** [Azure/iotedge#6822]
Hi.

We would like to keep our production devices updated and at the same time version-consistent. So the question is should IoT Edge agent modules version be equivalent to aziot-edge package version?

Right now, in [azureiotedge-agent tags list](https://mcr.microsoft.com/v2/azureiotedge-agent/tags/list), the latest version is "1.4.5" while the latest version of aziot-edge ubuntu package in [microsoft-prod-amd64 repository](https://ubuntu.pkgs.org/20.04/microsoft-prod-amd64/) is ["1.4.3"](https://ubuntu.pkgs.org/20.04/microsoft-prod-amd64/aziot-edge_1.4.3-1_amd64.deb.html). Should we also pull version "1.4.3" of the modules to align with this package version? or instead can we use version "1.4.5" version of edgeAgent and edgeHub modules while we have version "1.4.3" of aziot-edge installed on our device?

Would appreciate to shed some lights on this matter. It's quite important for us to keep our production edge devices updated but at the same time prevent any version mismatch.

**Comment by ggjjj** [comment]
There is no need to align the version numbers. Just use the latest version available whenever possible. aziot-edged is still in 1.4.3 and aziot-identity-service is in 1.4.1 and it will not be possible to match the upated module runtime images i,e 1.4.5.

**Comment by micahl** [comment]
The packages and modules should have  the same major + minor product version (i.e., 1.4).  And as @ggjjj says, the individual components might be on different patch versions (e.g, 1.4.1 vs 1.4.3).  We recommend using the latest patch version of each component as it will have the latest security and bug fixes.

**Comment by micahl** [comment]
@arminghasemazar let us know if we've fully answered your question(s).

**Comment by arminghasemazar** [comment]
@ggjjj @micahl Thank you so much for your information. Now it is clear. Will close the issue.
