### ISSUE TITLE
Build IoT Nested Edge and report an error

### ISSUE THREAD

**Issue by 2635891552** [Azure/iotedge#6829]
According to the document: [https://learn.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-iot-edge-device?view=iotedge-1.4&tabs=azure-portal](url)

I execute sudo iotedege check -- verbose error on my child device

`root@childdevice:/etc/aziot# sudo iotedge check --verbose

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct parent_hostname - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image '159.27.188.144/azureiotedge-diagnostics:1.4.3' locally
    docker: Error response from daemon: Get "https://159.27.188.144/v2/": x509: certificate signed by unknown authority.
    See 'docker run --help'.
× container time is close to host time - Error
    Could not query local time inside container
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
× Agent image is valid and can be pulled from upstream - Error
    Failed to get edge Agent image
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
× container on the default network can connect to upstream AMQP port - Error
    Container on the default network could not connect to 159.27.188.144:5671
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to 159.27.188.144:443
× container on the IoT Edge module network can connect to upstream AMQP port - Error
    Container on the azure-iot-edge network could not connect to 159.27.188.144:5671
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to 159.27.188.144:443
23 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.
9 check(s) raised errors. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

`

I am sure that I have executed on my parent device and child device:
sudo cp /var/aziot/certs/azure-iot-test-only.root.ca.cert.pem /usr/local/share/ca-certificates/azure-iot-test-only.root.ca.cert.pem.crt
sudo update-ca-certificates

[child-config.toml.txt](https://github.com/Azure/iotedge/files/10317376/child-config.toml.txt)
[parent-config.toml.txt](https://github.com/Azure/iotedge/files/10317377/parent-config.toml.txt)

**Comment by gordonwang0** [comment]
From your parent config, you are using `/var/aziot/certs/iot-edge-device-ca-gateway-full-chain.cert.pem` as the CA. Have you added the certs in this file to the child's trust bundle and `/usr/local/share/ca-certificates/`?

**Comment by 2635891552** [comment]
> 
Thank you for your reply
Yes, I've already done that

**Comment by gordonwang0** [comment]
On the child device, can you run:

`openssl s_client -connect 159.27.188.144:443 -showcerts`

and post the output of that? Thanks.

**Comment by 2635891552** [comment]
> 在子设备上，您可以运行：
> 
> `openssl s_client -connect 159.27.188.144:443 -showcerts`
> 
> 并发布它的输出？谢谢。

Okay, no problem. Here's my output

`root@childdevice:~# openssl s_client -connect 159.27.188.144:443 -showcerts
CONNECTED(00000005)
depth=3 CN = Azure_IoT_Hub_CA_Cert_Test_Only
verify return:1
depth=2 CN = Azure_IoT_Hub_Intermediate_Cert_Test_Only
verify return:1
depth=1 CN = gateway.ca
verify return:1
depth=0 CN = 159.27.188.144
verify return:1
---
Certificate chain
 0 s:CN = 159.27.188.144
   i:CN = gateway.ca
-----BEGIN CERTIFICATE-----
MIIEGjCCAgKgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDDApnYXRl
d2F5LmNhMB4XDTIyMTIyOTA2NDI0M1oXDTIzMDEyODAwNTk1MFowGTEXMBUGA1UE
AwwOMTU5LjI3LjE4OC4xNDQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
AQDxNngGp8OJZDyQoMYWBpO2QXBFlNTvxRPpOglcgTIGa51XCXCH1jCwGcVeLwbH
lnAJySVgwTKkYMl1t2VjHdjvDhKqCLEa6P75n63rSGDqmS+/1uP1KApYAIEXL7DL
yI9KUUFS0iWHzQrHCOuaf9HORkG8qC5ht5wEHI78y5bMTQh/gHshSYYezqU5Nlsf
19vIRuPNCDcBiGGeKnULwDzF8cbth6u66f3BZQHzui8uUwzrMgNGwNM7eoARmDCU
jm/5SCFgwanORhTPxJvfiq96UXjViQkBk0CeL+WKlLGhrjHAPJbCPGutILAuoh27
ea8AXZ6978AE29hqFsmwibS9AgMBAAGjcTBvMBMGA1UdJQQMMAoGCCsGAQUFBwMB
MBgGA1UdEQQRMA+HBJ8bvJCCB2VkZ2VIdWIwHQYDVR0OBBYEFBIyPorCZCOOwByB
GZESreANJWrcMB8GA1UdIwQYMBaAFCmCP1g8cwnJ5mSBiaZ8qAFz+LjFMA0GCSqG
SIb3DQEBCwUAA4ICAQCOl6VhKmnVRPDxwYIgae5zj7bBFi5S/40h81ApmMXck5YX
UbDQ3BqL+zFVgh6rasBI0D0zsCca4/AosYwD5vKnimrvKVDAGaujjvceyywctMQm
59s7E2mOTFZz7cMZOV6tBvcFfMkmBuT4ezkJx+QHQ0bmOapuYHbOCLKS4bl+1Cqm
jsR/CzTayaS4iuhY7K/msZK6R9rQMsVhxD8R4ticFkITb/O2yVWxvmh5nreQovDn
kFjNdLxX8RRwUNLitIHDzrARXTAgeuMFga5XroRqlyb9M721thVlL1hgjkqXalBP
z7fc3nHTaJzbn9Wg7gWMGi78hKSzRELLse4nluVd0Lr9RxASP4aUjDupy/X+rVbo
Fnn8KOD4NGlxJPylk5zWIK8bVyEyMnD9agv0pneXCHAi3X/9SoMxox1+6Vevu+Hr
8TEkqpQQ7cmjuuG9SeY3b/iHWh/CXjeEbGUhK88QB+zmK1KNMRBqK3MEQmtsW5Z8
WqzSp6VHE6t5aDIvLRU/hcWKYHlpHq/FsMmbEDhFM1FSm8C45FSjFyFUHlofkDWR
qUGwDfJrH020921KsrgD+r33NQ1r/iJxj2pw+W7q3/aRCTEn0NITfRK1AhhilbHp
uyE78s0ppFAMRqE+rxc/tHeGAaxmybw8iy4iGwhVUfEq9CWqxSF7QTR9ixLKXg==
-----END CERTIFICATE-----
 1 s:CN = gateway.ca
   i:CN = Azure_IoT_Hub_Intermediate_Cert_Test_Only
-----BEGIN CERTIFICATE-----
MIIFXjCCA0agAwIBAgICEAEwDQYJKoZIhvcNAQELBQAwNDEyMDAGA1UEAwwpQXp1
cmVfSW9UX0h1Yl9JbnRlcm1lZGlhdGVfQ2VydF9UZXN0X09ubHkwHhcNMjIxMjI5
MDA1OTUwWhcNMjMwMTI4MDA1OTUwWjAVMRMwEQYDVQQDDApnYXRld2F5LmNhMIIC
IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEApEhq7GLlywoVnqlnseVPoLwq
hQh7iBr8GxVJ+Oocx+TawRQO+0zoHCa6pfT6hInTva9BpRj84WIiD5+8d2r73JRG
FoOiW7gdmjcb6G0SRyZy9Vmu4SebtNa0ah60gJpwnz6VpI7znM4qosg9S4+3vxZF
v1iPISCMDHlgaHLIuZ9RHtC1DjXZm3LEPzWL+jp0mzRnxv4u0BGOaqzadBZbAbLa
zI0+WsA/S4hEYIkFOdPmmsmJL+CtWAgS0qUTjwrDVSsfzDKYHLKSxUUzciULfuCQ
a8cslaFk0ulE0r6gdzRlz/JTPULxCq+e14GFJspvpqWj5iF9BmNxX30Cbj+xdaW4
JNyxARkbMx+yMsh7E7TEoN4G2PTj/Q+NKBBl4vEkpTehD44NmpWOEBMPZ2RNtCDv
yAF+sDXFLdSpwS2Kaj8OzyDoo9XrYhiDlfeGkkGRJjtcU0s8elNf+/hVWW5OuXZs
226131eNRFuGooB0uaeMugfRyqmqkgjc3ep2wwF82lcdjDRErKgDerhDN/CLMYTP
TqhI2xbgmVUNdo/P2TihIb0lnmYQX4uBtsK99+XtjYM/3QGKPcT1ilC7RWlCXQOS
jzDfjCX2fwshtpGkkFiLZDDu+E03cJRt3WX/gnvjlac4xuOiJ5aAJ/Kr7sLZw5sT
AFLtCbnSHAkN4hmuvxkCAwEAAaOBmDCBlTAdBgNVHQ4EFgQUKYI/WDxzCcnmZIGJ
pnyoAXP4uMUwUwYDVR0jBEwwSoAU2DQXYZ/IKBQuOsRVbq+dkYHrdXChLqQsMCox
KDAmBgNVBAMMH0F6dXJlX0lvVF9IdWJfQ0FfQ2VydF9UZXN0X09ubHmCAhAAMA8G
A1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4IC
AQAZRDFAYgAvYPTGqpH3VTXqSqN+GP07T/goh7UVZgjyWmwFCzGgb6bDZAusnTVt
27L/DWWHmlbBOxhQF2kNOGG2R9eVOv2h0Z2Dahf6vcz597ekQ0cZQBDR4r3mpo9k
t5I5JEp8zB/aeKbVRkCFqbxmXgJ0+4ksu0GNpkSsVSx/8EorITJnV0ENzUxsa1gR
wx0eMuANGnKg/9khU/ADurUGmQDp+ZmDs+G5yn1Nngs3EFGvFOk8d+t8KVx77Ijl
TAsh0SboSCoxnCIEE7W90Y2F9LXwq07CNc6KLpxdx6p+Z2te+ovSV+X1TgC2C/Fz
YiStxqwse3TuNvTxYLThgtjD2e56ypDil5SQyLurbMvpkQ3U5xuk0ylKabeOz/3o
70Lu99R/HSBMTH5au6H+9a8C5EGa42i/djQPw2aU1p7FZueNr5DosYc+MgsfYUpt
E1sqBfQ8J/f/g5+21gw0lHSdT5uNgEXE08laijk0rsbF/Iv1YGhLsP0P9Kv9KuFF
H9tULqg+P6xRczWyfo1U3/p12VT5TENPK8n1kKMlTnPhCjU3il+8DSsrvjBqs+qE
Nl8B7akHyKKVZ0tNy/r2ObCJQ3AwFJ0mA1x1lAXo0unPRlZVpDE8UtCOzG03w139
pImDckW57Kn66risSDg8yGBBVhRvn9q9qo++vp8HPlcxpw==
-----END CERTIFICATE-----
 2 s:CN = Azure_IoT_Hub_Intermediate_Cert_Test_Only
   i:CN = Azure_IoT_Hub_CA_Cert_Test_Only
-----BEGIN CERTIFICATE-----
MIIFejCCA2KgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwKjEoMCYGA1UEAwwfQXp1
cmVfSW9UX0h1Yl9DQV9DZXJ0X1Rlc3RfT25seTAeFw0yMjEyMjkwMDU5NDlaFw0y
MzAxMjgwMDU5NDlaMDQxMjAwBgNVBAMMKUF6dXJlX0lvVF9IdWJfSW50ZXJtZWRp
YXRlX0NlcnRfVGVzdF9Pbmx5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
AgEAxKiRORnyDBDlIUJ3vWZUqVE2PnHCUlVf0fKLkWSCYzM3OOWMxEM1vewaSPpL
tZN13zf41fEW1cInsklIkk4vp/dMgcAh6YnC8EH95yjoMPvnQKX47+Bzf4lpoIHn
0Yt1vTvf60STd4zcX1BJGfFlKmS6xlVTkE/Se3j9TmnxgxXiFmYEV8Zv85rf8bPe
ChKxUNwdylbjcMPvNFqBgLHZC4+cQyiUtvSbuHp/9FgrWNEujL1lJfV5XDcZPtPp
Lykq09Slf0Z3PtfodHhRW6yQusd/cvyOMGsniozmfoH6w2avBDQ9zQ2dI/wx8roq
R9AGoQ+wNtJdoYFfxt25FLoOzr6UtRp1oNxGZBG5W2Ahn+W+xFk4jTmknuyyDNEH
7PiNm1+aoZzmJcwvm085U3ZN01heFKhCnBwrnfv/NZPK0Kh7A+xenOacQk4f+D3/
9OUvqfFmWRGB0VuJT+Z2hU6yAOJQ1hWUdNwJrKC3OOj4EDjjr6zvg+Q/M15ME0x2
UZz9fxpDhf2w7Ez0AedQN2wfvzXk4Cp9IVvyEF/yfZuRXqQ0EZdYmRt87eAyRr+N
XA3kqF2QMAGySraz3E+F2oTkireja3mwIDm2d+iptEyYFjYDXfy1GZ/6m2TFttzp
6yPAvogDI8JtC3lQR+PHBp2FWMSEt7QJ+DrFQCrtfltSr38CAwEAAaOBnzCBnDAd
BgNVHQ4EFgQU2DQXYZ/IKBQuOsRVbq+dkYHrdXAwWgYDVR0jBFMwUYAU6gGJrW4n
cEnL5How4qcyaMdvscehLqQsMCoxKDAmBgNVBAMMH0F6dXJlX0lvVF9IdWJfQ0Ff
Q2VydF9UZXN0X09ubHmCCQC5I1B7Ld2I+DAPBgNVHRMBAf8EBTADAQH/MA4GA1Ud
DwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAgEAMO0WTKXxgtTJT9yZ77z4LgYP
G1D9giLPN+uOEKhzKDJD/hwcYVb85BAzWB3vkd67NMsTLmOIOBaefL4ugvvFMGQ2
mOtXHHLpPLPRwjjmAX0n1hQd4pisrUIEcE82bWJEUHA1PImmTs80QS/ZUjjuVhF3
UO6e+ymE6vkRIR8mDUIQLE1o7eoov58FSsgqvUwXniMyFZe6n0GPcyrnngI4x/IW
1UpY6U1pJleVYSBuG0YLl4kSeMCdmaG88L7S8ozcZzYoAZwye+yfuy7CfLUYf0+1
iG/cxasRWETycF6ZdKaq3kV/HDB1FJ0qXFxTrkSdfbODuIgXpB/fqS07/NGlDNXb
bRitSbima1uCW3bSS5zfl5qH6M+y7yvkHbaKDU05CEoZQonL6xzvufhJIoaLHeao
PldO2PSe+Jcf9v8ZQ90ZuVosS4zgBw5ZFf0s7X8EpNsdebymwtv1SMsCsqKjQBxb
fKHnekHzgO4mv7MpkhRndx1hMDie1LGelGCIvgbAFvLg6LhjuOcjCg+D47zEAEiR
d2U/6ZVAjSxG7Ga0jXrtrZuOJUNeWzSMqm8pc6j8oRgtEzVYNp6OmvfBrJHpr0Sk
ELuPXY2T5HmpjaeILsopnL92N+g5Iol89/3EYpqwQTnZlznb7GeAlyeBqYB+idrl
PQTPAj3RQmTyCj/HlN0=
-----END CERTIFICATE-----
---
Server certificate
subject=CN = 159.27.188.144

issuer=CN = gateway.ca

---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:E                                                                                                                              d448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:                                                                                                                              RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA2                                                                                                                              24:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed                                                                                                                              25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+                                                                                                                              SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:R                                                                                                                              SA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4532 bytes and written 421 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 0088C8F21A2D6833DC70FB89C9767AB12C132DACF08941DD767D0971D5080DD5
    Session-ID-ctx:
    Master-Key: C75FB9BAD168ED6642459D3E91D6564FDFB9C4ACED9C6BF5B1AEF1C3D19B36E5                                                                                                                              BC783D95BF40CCCEBE5B3576D16E9D7A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - f1 30 50 f9 79 c5 52 1a-71 32 7d 7d ca 9f 8a a0   .0P.y.R.q2}}....
    0010 - 2c 5b a7 a3 34 ab 01 88-18 a5 52 9c 20 16 fe ec   ,[..4.....R. ...
    0020 - e9 ae e8 1a 23 cd 13 56-85 e7 ac 62 26 0a cd 38   ....#..V...b&..8
    0030 - c3 64 6d bc af 55 92 7a-4c 26 7c 37 37 ce 43 22   .dm..U.zL&|77.C"
    0040 - 7f 85 48 06 c8 6e b1 51-86 4e 90 cd 8a 85 7a 8f   ..H..n.Q.N....z.
    0050 - b0 b1 1e f7 e5 91 91 16-14 98 6d 43 12 48 5a 33   ..........mC.HZ3
    0060 - 4a 35 0a ee 22 ba 8f f2-02 ef a9 68 3e 86 83 78   J5.."......h>..x
    0070 - e5 a2 04 b5 56 46 9c df-30 6b 8a 94 3d 78 93 f5   ....VF..0k..=x..
    0080 - a9 b7 52 1a ba 22 64 86-94 6d 5f 1c e4 86 70 73   ..R.."d..m_...ps
    0090 - cd 3d b0 10 fd 2c fe db-91 a6 03 c9 61 20 3d 3a   .=...,......a =:

    Start Time: 1672409366
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
`

**Comment by gordonwang0** [comment]
Those certificates look fine. Could you also try restarting docker and running iotedge check again?

**Comment by 2635891552** [comment]
Yes, I tried. But it hasn't been solved

**Comment by gordonwang0** [comment]
Please attach support bundles from both the child and parent devices.

**Comment by 2635891552** [comment]
I have tried to solve it myself
