### ISSUE TITLE
IoTEdge 1.4.3 LTS support for - Ubuntu 22.04 LTS Operating System.

### ISSUE THREAD

**Issue by post2vishwa** [Azure/iotedge#6867]
Hi Team / @fcabrera23 

One of our customers is looking for support for IoTEdge 1.4.3. LTS support (not eflow runtime) for Ubuntu 22.04 LTS (AMD 64 and ARM64)

Could you throw some light on when this support will be available?

Also i am observing below:

Prepared a Ubuntu 22.04 LTS machine and installed

Below are versions of packages in that order.

1. moby-cli_20.10.22+azure-ubuntu22.04u1_amd64.deb
2. moby-runc_1.1.4+azure-ubuntu22.04u3_amd64.deb
3. moby-containerd_1.6.9+azure-ubuntu22.04u1_amd64.deb
4. moby-engine_20.10.22+azure-ubuntu22.04u1_amd64.deb

with above docker installed successfully. Then

5. libssl1.1_1.1.1-1ubuntu2.1_18.04.20_amd64.deb  => dependency package for "aziot-identity"
6. libtss2-esys0_2.3.2-1_amd64.deb                         => dependecy package for "aziot-identity"
7. aziot-identity-service_1.4.1-1_ubuntu20.04_amd64.deb
8. aziot-edge_1.4.3-1_ubuntu20.04_amd64.deb

After this with Ubuntu 20.04 aziot packages i am able to successfully install iotedge 1.4.3 On Ubuntu 22.04 LTS as well.

**Could you confirm can we go ahead with above packages ?** 

![image](https://user-images.githubusercontent.com/50254283/214363627-23c7a62a-505a-4077-a8b4-1cde5d840830.png)

Thanks.
Vishwa

**Comment by nlcamp** [comment]
@micahl or @konichi3 - Are there any insights that you can share on this user's questions? 
1. Do we have an expected release date for Ubuntu 22.04 packages?
2. What's the support stance on using 20.04 packages on a 22.04 system?

**Comment by post2vishwa** [comment]
Hi @micahl   @konichi3

Could you provide any insight on the above?

Thanks,
vishwa

**Comment by micahl** [comment]
@post2vishwa we had hoped to have it by now but have been delayed while we investigate a failure we were seeing in our E2E tests.  Our latest findings suggest that the error is a result of the test machine accidentally having both openssl 1.1 and openssl 3.0 installed (which is not a scenario we target or support).  So... if you proceeded with the approach you've outlined and then ever wanted to switch to the package we explicitly build for 22.04 then it's possible you may need to also remove the openssl 1.1 package.

**Comment by post2vishwa** [comment]
Hi @micahl ,

Thanks much for clarifying.

Regards,
Vishwa

**Comment by micahl** [comment]
Jfya, an official announcement should appear next week on the Azure updates feed, but we have already published the packages for 22.04 and updated our docs ([for example](https://learn.microsoft.com/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.4&tabs=azure-portal%2Cubuntu#install-iot-edge)).
