### ISSUE TITLE
Events sent using ModuleClient.SendEventAsync do not match any routes

### ISSUE THREAD

**Issue by chatnoir1982** [Azure/iotedge#6872]
Hi,

I am using ModuleClient.SendEventAsync to send a utf-8 encoded message to IotHub. The ModuleClient is instantiated using **_moduleClient = ModuleClient.CreateFromEnvironmentAsync()**, and used as a singleton throughout execution.

I have set up a route to a custom EventHub endpoint, which looks for a BODY reference (e.g. $body.SomeProperty=5).
The route has been tested against a sample body JSON and matches correctly.

The problem is that the route does not seem to work. I am expecting to see messages arriving at my custom Eventhub endpoint.

              try
               { 
                var options = new JsonSerializerOptions()
                {
                    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
                    PropertyNameCaseInsensitive = true
                };

                foreach (var cc in customConverters)
                {
                    options.Converters.Add(cc);
                }

                string msg = JsonSerializer.Serialize(message, options);

                var telemetryMessage = new Message(Encoding.UTF8.GetBytes(msg))
                {
                    CorrelationId = correlationId,
                    ContentType = "application/json",
                    ContentEncoding = "utf-8"
                };

                await _moduleClient.SendEventAsync(telemetryMessage, cancellationToken);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }

Replacing the ModuleClient with a DeviceClient instance solves the problem, and I can see events reaching the Eventhub defined in my custom endpoint.

My question is whether IotHub message routing work with messages sent using the **ModuleClient**, or if it's _mandatory_ to use **DeviceClient**.

Thanks.

**Comment by nlcamp** [comment]
@chatnoir1982 - It's possible that your deployment is missing a route that tells EdgeHub to forward messages from your custom module to IoT Hub. Please look at the following document which explains EdgeHub routes and confirm that you have a valid route specified in your deployment: https://learn.microsoft.com/en-us/azure/iot-edge/module-composition?view=iotedge-1.4#declare-routes

If you're still experiencing the same issue after checking your routes, please share your custom module logs, EdgeHub logs (w/ debug enabled), and the `routes` section of your deployment. 

Also, please share what version of IoT Edge you're using, the output of `sudo iotedge check` and the other information listed in the [iotedge bug report template](https://github.com/Azure/iotedge/issues/new?assignees=&labels=&template=bug_report.md&title=).

**Comment by chatnoir1982** [comment]
Hi @nlcamp ,

It seems that the issue was being caused by an outdated package reference of our ModuleClient wrapper, after updating it the routes started working.
Closing the ticket, thanks for the help.
