### ISSUE TITLE
TLS certificat validation error on Windows 2019 server with external switch

### ISSUE THREAD

**Issue by Priyanka-L-Dalawai** [Azure/iotedge#6877]
**Question Summary**
After provisioning edge device on Windows 2019 server with external switch ssl certificate errors are coming how to resolve it

**Detailed background**
After provisioning edge device on Windows 2019 server with external switch 
if we run sudo iotedge check getting below errors

× aziot-identity-service package is up-to-date - Error
    could not query https://aka.ms/latest-aziot-identity-service for latest available version
        caused by: could not query https://aka.ms/latest-aziot-identity-service for latest available version
        caused by: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:: self signed certificate in certificate chain
        caused by: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:: self signed certificate in certificate chain
        caused by: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
        caused by: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:

Connectivity checks (aziot-identity-service)
--------------------------------------------
× host can connect to and perform TLS handshake with iothub AMQP port - Error
    Could not connect to iot-dev-001.azure-devices.net : could not complete TLS handshake
        caused by: Could not connect to iot-dev-001.azure-devices.net : could not complete TLS handshake
        caused by: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:: self signed certificate in certificate chain
× host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Error
    Could not connect to iot-dev-001.azure-devices.net : could not complete TLS handshake
        caused by: Could not connect to iot-dev-001.azure-devices.net : could not complete TLS handshake
        caused by: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:: self signed certificate in certificate chain
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Could not connect to iot-dev-001.azure-devices.net : could not complete TLS handshake
        caused by: Could not connect to iot-dev-001.azure-devices.net : could not complete TLS handshake
        caused by: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:: self signed certificate in certificate chain

**Comment by vadim-kovalyov** [comment]
@Priyanka-L-Dalawai can you please clarify what steps have you done (or what documentation have you followed) to setup Windows 2019 with external switch? The error indicates that there is a TLS proxy that presents self-signed certificate instead of real Azure/Github certificate. 

If you just navigate to https://aka.ms/latest-aziot-identity-service (or run `openssl s_client -x509_strict -connect <your-hub-name>.azure-devices.net:443
`) you can see that the certs are fine, belongs to `*.github.com`/`*.azure-devices.com`. So it must be something in between that terminates TLS and presents self signed cert.

@fcabrera23 I might still need your help, b/c this seems to be related to the connectivity setup on Windows, not the Edge provisioning.

**Comment by Priyanka-L-Dalawai** [comment]
after running  above command this is output

iotedge-user@ABCD-EFLOW [ ~ ]$ sudo openssl s_client -x509_strict -connect iot-dev-001.azure-devices.net:443
CONNECTED(00000003)
depth=1 CN = XYZ_Access_SSLInspect
verify error:num=19:self signed certificate in certificate chain
verify return:1
depth=1 CN = XYZ_Access_SSLInspect
verify return:1
depth=0 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net
verify return:1
---
Certificate chain
0 s:C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net
   i:CN = XYZ_Access_SSLInspect
1 s:CN = XYZ_Access_SSLInspect
   i:CN = XYZ_Access_SSLInspect
---
Server certificate
-----BEGIN CERTIFICATE-----
Base64-Encoded
-----END CERTIFICATE-----
subject=C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net issuer=CN = XYZ_Access_SSLInspect ---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2385 bytes and written 476 bytes
Verification error: self signed certificate in certificate chain
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-SHA256
    Session-ID: <Session-ID>
    Session-ID-ctx:
    Master-Key: <Master-Key>
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1675227692
    Timeout   : 7200 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
    Extended master secret: yes
---
read:errno=0

What can be done to solve it?

**Comment by Priyanka-L-Dalawai** [comment]
Even after adding XYZ_Access_SSLInspect root certificate to trusted root of EFLOW, we are getting the error at edgeAgent logs as below:-


<6> 2023-02-03 10:21:48.932 +00:00 [INF] - ModuleUpdateMode: NonBlocking
<6> 2023-02-03 10:21:49.016 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2023-02-03 10:21:49.252 +00:00 [INF] - Installing certificates [CN=aziot-edge CA iot-dev-001:04/24/2023 14:45:48] to Root
<6> 2023-02-03 10:21:49.426 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: metrics
<6> 2023-02-03 10:21:49.447 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2023-02-03 10:21:49.453 +00:00 [INF] - Started operation Get system resources
<6> 2023-02-03 10:21:49.455 +00:00 [INF] - Collecting metadata metrics
<6> 2023-02-03 10:21:49.536 +00:00 [INF] - Set metadata metrics: 1.4.8.67766159 (5b27647895ba476c3a6ba69a8fbb42f436667475), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"Linux","Architecture":"x86_64","Version":"1.4.2","Provisioning":{"Type":"ProvisioningType","DynamicReprovisioning":false,"AlwaysReprovisionOnStartup":false},"ServerVersion":"20.10.14","KernelVersion":"#1 SMP Sat Dec 3 02:47:09 UTC 2022","OperatingSystem":"mariner","NumCpus":1,"TotalMemory":907814912,"Virtualized":"yes"}, True
<6> 2023-02-03 10:21:49.562 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2023-02-03 10:21:49.572 +00:00 [INF] - Started operation refresh twin config
<6> 2023-02-03 10:21:49.600 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2023-02-03 10:21:50.295 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2023-02-03 10:21:50.370 +00:00 [INF] - Started operation Metrics Scrape
<6> 2023-02-03 10:21:50.370 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2023-02-03 10:21:51.218 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2023-02-03 10:21:51.219 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2023-02-03 10:21:51.219 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2023-02-03 10:21:51.219 +00:00 [INF] - Registering request handler RestartModule
<6> 2023-02-03 10:21:54.162 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2023-02-03 10:21:56.356 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<6> 2023-02-03 10:21:56.359 +00:00 [INF] - Edge agent config backup file does not exist - /tmp/edgeAgent/backup.json
<4> 2023-02-03 10:21:58.481 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (TLS authentication error.) (TLS authentication error.)
---> System.Security.Authentication.AuthenticationException: TLS authentication error.
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
---> Interop+Crypto+OpenSslCryptographicException: error:0A000152:SSL routines::unsafe legacy renegotiation disabled


The result of "sudo iotedge check --verbose" as below:-


iotedge-user@ABCD-EFLOW [ ~ ]$ sudo iotedge check --verbose Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
× aziot-identity-service package is up-to-date - Error
    received unexpected response 503 Service Unavailable
        caused by: received unexpected response 503 Service Unavailable
‼ host time is close to reference time - Warning
    Could not query NTP server
        caused by: Could not query NTP server
        caused by: could not receive NTP server response: Resource temporarily unavailable (os error 11)
        caused by: Resource temporarily unavailable (os error 11)
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
× aziot-edge package is up-to-date - Error
    Error while fetching latest versions of edge components: response failed with status code 503 Service Unavailable
        caused by: Error while fetching latest versions of edge components: response failed with status code 503 Service Unavailable
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Container engine is not configured to rotate module logs which may cause it run out of disk space.
                   Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
                   You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
        caused by: The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
                   Data might be lost if the module is deleted or updated.
                   Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: Could not check current state of edgeHub container
        caused by: docker returned exit status: 1, stderr = Error: No such object: edgeHub
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to iot-dev-001.azure-devices.net:443
        caused by: Container on the default network could not connect to iot-dev-001.azure-devices.net:443
        caused by: docker returned exit status: 1, stderr = One or more errors occurred. (The SSL connection could not be established, see inner exception.)
√ container on the default network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to iot-dev-001.azure-devices.net:443
        caused by: Container on the azure-iot-edge network could not connect to iot-dev-001.azure-devices.net:443
        caused by: docker returned exit status: 1, stderr = One or more errors occurred. (The SSL connection could not be established, see inner exception.)
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
27 check(s) succeeded.
3 check(s) raised warnings.
5 check(s) raised errors.
2 check(s) were skipped due to errors from other checks.
Prepare to deploy your solution in production - Azure IoT Edge
Learn how to take your Azure IoT Edge solution from development to production, including setting up your devices with the appropriate certificates and making a deployment plan for future code updates.

**Comment by Tarak-Chandra-Sarkar** [comment]
> You need to find out with your network administrator what is `XYZ_Access_SSLInspect` and, if needed, add its certificate into the trusted root.
> 
> ```
> Certificate chain
> 0 s:C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net
>    i:CN = XYZ_Access_SSLInspect
> 1 s:CN = XYZ_Access_SSLInspect
>    i:CN = XYZ_Access_SSLInspect
> ```
> 
> This is the certificate chain that is expected for a direct connection to an iot hub.
> 
> ```
> Certificate chain
>  0 s:C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net
>    i:C = US, O = Microsoft Corporation, CN = MSFT BALT RS256 CA
>  1 s:C = US, O = Microsoft Corporation, CN = MSFT BALT RS256 CA
>    i:C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
> ```

After adding XYZ_Access_SSLInspect to trusted root CA certificate (in '/etc/pki/ca-trust/source/anchors/' & 'file:///var/aziot/certs/XYZ_Access_SSLInspect.pem') and trust_bundle_cert = "file:///var/aziot/certs/XYZ_Access_SSLInspect.pem" to config.toml  and running command 'sudo update-ca-trust'
 & 'sudo iotedge config apply' still getting below error:-

iotedge-user@ABCD-EFLOW [ ~ ]$ sudo openssl s_client -x509_strict -connect iot-dev-001.azure-devices.net:443
CONNECTED(00000003)
depth=1 CN = XYZ_Access_SSLInspect
verify return:1
depth=0 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net
verify return:1
---
Certificate chain
 0 s:C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net
   i:CN = XYZ_Access_SSLInspect
 1 s:CN = XYZ_Access_SSLInspect
   i:CN = XYZ_Access_SSLInspect
---
Server certificate
-----BEGIN CERTIFICATE-----
Base64-Encoded
-----END CERTIFICATE-----
subject=C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = *.azure-devices.net

issuer=CN = XYZ_Access_SSLInspect

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2400 bytes and written 509 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-SHA256
    Session-ID: 123ABCDEFGH456
    Session-ID-ctx:
    Master-Key: 123ABCDEFGH4567890
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1675606253
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---

Can you please help us to passthrough communication in this TLS Inspector proxy in restricted network.?
Thanks in advance.

**Comment by vadim-kovalyov** [comment]
For the Zscaler users, I'll put the resolution here for the posterity:

Zscaler forces TLS1.2, where our system modules are based on Alpine 3.17 (and as a result OpenSSL 3). OpenSSL 3 does not work well with ZScaler - https://github.com/dotnet/runtime/issues/80641. To work around that Zscaler users can follow resolution on this issue - https://github.com/Azure/iotedge/issues/6291
