### ISSUE TITLE
Proxy not working in Agent and Hub on Windows containers

### ISSUE THREAD

**Issue by sebader** [Azure/iotedge#688]
I'm just opening this issue for this - already known - issue of missing proxy support in Windows containers so (external) folks are aware of it and we have a common place to track it.
Already in the process of being fixed. See https://github.com/Azure/iotedge/pull/687

## Expected Behavior

Proxy support working on all plattforms.

## Current Behavior

Proxy settings in not observed in Agent and Hub on Windows containers.
Proxy does work for the Daemon (Edgelet) on Windows.

### Device (Host) Operating System

Windows

### Architecture

amd64
### Container Operating System

Windows
### Runtime Versions
1.0.5

**Comment by sebader** [comment]
Underlying issue is basically this: https://github.com/Azure/azure-iot-sdk-csharp/issues/477#issuecomment-404983104
IoT SDK for C# does not take into account the https_env in Windows - it does so on Linux.

**Comment by myagley** [comment]
This should now be resolved with #697

**Comment by sebader** [comment]
thanks, looks good! Do you usually close the ticket after the PR is merged or should we leave it open until the fix makes it into the next release?

**Comment by myagley** [comment]
We've typically left it open until the release. I'll add a `checkedin` label.

**Comment by sebader** [comment]
Yep this works now with 1.0.6 :)
One minor thing (unrelated to Windows): In the agent and hub log, you sanatize the proxy password (if there is one). In the daemon log, the password is printed in clear text. Should be changed at some point.

**Comment by myagley** [comment]
Ah thanks for the feedback. We'll get this fixed. cc/ @arsing 

I'm going to close this issue since 1.0.6 is public now.
