### ISSUE TITLE
Broken package for azure iotedge while installing version 1.4.2-1 on ubuntu server

### ISSUE THREAD

**Issue by UPPY** [Azure/iotedge#6889]
## Expected Behavior
Installation of azure iotedge package on ubuntu should succeed for version 1.4.2-1.

## Current Behavior
Installation of azure iotedge package on ubuntu fails for version 1.4.2-1. The error is shown below :-
![image](https://user-images.githubusercontent.com/1179787/216884560-25f39105-2d33-4605-84b4-3df0ec635353.png)

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Use any running ubuntu server 20.04.5 and launch a ssh session.
3.  Run wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
4.  Run sudo dpkg -i packages-microsoft-prod.deb
5.  Run  rm packages-microsoft-prod.deb
6.  Run sudo apt-get update. 
7. sudo apt-get install aziot-edge=1.4.2-1

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [Ubuntu server 20.04.5]: 
* Architecture [e.g. amd64]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by micahl** [comment]
@UPPY the patch version of the aziot-edge and aziot-identity-service packages may differ and apt's default behavior is to always grab the latest version of a package if not explicitly given.  If you're looking to install a specific patch version of aziot-edge then you'll also need to install the required version of aziot-identity-service which in this case is 1.4.1-1.  This should work:
`sudo apt-get install aziot-edge=1.4.2-1 aziot-identity-service=1.4.1-1`

Alternatively, if you want to get the latest patch of each component for the 1.4 LTS release then just `sudo apt-get install aziot-edge` would be sufficient.

**Comment by sandipanaich** [comment]
@micahl We have to fix the version of aziot-edge at the time of installing it on a gateway. We cannot automatically upgrade to the latest version of aziot-edge on Production, without testing it for Functionality and Security.

**Comment by techipank** [comment]
@micahl i understand each version of `aziot-edge `is depending upon specific version of `aziot-identity-service`, but if i mention specific version of `aziot-edge`  then it should resolve dependency.
For example `curl `is depending upon many packages

But as a end-user we never install specific version of child package, what we do as a end-user 
`sudo apt-get install curl=7.68.0`
and child packages gets pulled by itself.

**Comment by micahl** [comment]
@sandipanaich I agree that for production you should test a specific version.

@techipank the issue is not with the package which correctly embeds its dependency(ies) in its metadata.  What you're seeing instead is related to [the default behavior for apt-get](https://unix.stackexchange.com/questions/350192/apt-get-not-properly-resolving-a-dependency-on-a-fixed-version-in-a-debian-ubunt).
