### ISSUE TITLE
mgmt/sock and workload/sock in Manual x.509 (No connection could be made because the target machine actively refused it. C:\ProgramData\iotedge\mgmt\sock)

### ISSUE THREAD

**Issue by YoushaKhan** [Azure/iotedge#6905]
**In config.yaml file**
listen and connect are both set to 
management_uri: 'unix:///C:/Data/ProgramData/iotedge/mgmt/sock'
workload_uri: 'unix:///C:/Data/ProgramData/iotedge/workload/sock'

**iotedge list is showing result**
A module runtime error occurred
        caused by: Could not initialize module client
        caused by: Invalid URL "unix:///C:/ProgramData/iotedge/mgmt/sock": Socket file could not be found

**iotedge check logs:**
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ Windows host version is supported - OK
√ config.yaml has correct hostname - OK
× config.yaml has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (ConnectionRefused) : No connection could be made because the target machine actively refused it. C:\ProgramData\iotedge\mgmt\sock
    One or more errors occurred. (Got bad response: )
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: identity certificates expiry - OK
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 89 days (at 2023-05-14 10:33:03 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

16 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
3 check(s) raised errors. Re-run with --verbose for more details.

Hyper-v is enabled ,what steps can i take to resolve this socket error?

**Comment by micahl** [comment]
@YoushaKhan it looks like you're using the v1.1 of IoT Edge for Windows with support for Windows containers that reached its end-of-life in mid-December of last year.  Refer to this blog post on [IoT Edge v1.1 EoL: What does that mean for me?](https://techcommunity.microsoft.com/t5/internet-of-things-blog/iot-edge-v1-1-eol-what-does-that-mean-for-me/ba-p/3662137) for guidance / recommendations on what to use instead.

**Comment by YoushaKhan** [comment]
> @YoushaKhan it looks like you're using the v1.1 of IoT Edge for Windows with support for Windows containers that reached its end-of-life in mid-December of last year. Refer to this blog post on [IoT Edge v1.1 EoL: What does that mean for me?](https://techcommunity.microsoft.com/t5/internet-of-things-blog/iot-edge-v1-1-eol-what-does-that-mean-for-me/ba-p/3662137) for guidance / recommendations on what to use instead.

Hi i am using IoT Edge version 1.1.15 and  OS is windows, Build version 17763
