### ISSUE TITLE
Azure IoT module twin update gets reverted back

### ISSUE THREAD

**Issue by nlv-hack** [Azure/iotedge#6913]
My layered deployment (single module) properties read as follows:
```
"properties": {
        "desired": {
            "PublishInterval": 2000,
            "OtherProperty": 1
            "layeredProperties": {}
        }
},
...
```
After the deployment is applied I would like to add a custom property on some of the devices using the Azure portal, so the result might look like so:
```
"properties": {
            "desired": {
                "PublishInterval": 2000,
                "OtherProperty": 1
                "layeredProperties": {
                    "instance-specific-property": 4000
                }
            }
    },
    ...
```

### Current Behaviour

A few minutes later this property gets reverted back and we end up with an empty `layeredProperties `collection.

### Expected behaviour

Additional or custom settings added through Azure Porta aren't reverted/removed back.

Following up on similar questions asked [here](https://stackoverflow.com/questions/61817920/iotedge-module-twin-update-gets-reverted) and [here](https://github.com/Azure/iotedge/issues/2914) Im starting to think that it is not possible to do this at all and if one needs some specific properties on devices there should be a layered deployment created for that.

Is there really no way of updating a module's twin desired properties but using a specific deployment? Seems like an overkill.

**Comment by huguesBouvier** [comment]
Some fields in the TWIN cannot be edited.

If you want to pass parameters, I suggest that you use the module TWIN settings for that:
For example: https://learn.microsoft.com/en-us/azure/iot-edge/how-to-configure-api-proxy-module?view=iotedge-1.4#edit-the-proxy-configuration

**Comment by vasdee** [comment]
my experience with this is that you need to not target the top level, `properties.desired` if you don't want portal changes to be reverted. For example, 

```
"properties": {
        "desired": {
            "PublishInterval": 2000,
            "OtherProperty": 1
            "layeredProperties": {}
        }
},
```
This is essentially declaring that you _always_ want your desired properties to be in this state, as it targets the top level of the properties objects. If you want to allow manual changes via the portal, something like the following tends to work, where the layered twin values target a specific part of the twin. 

 ```
"properties.desired.layeredProperties": {
            "PublishInterval": 2000,
            "OtherProperty": 1
}
```

This _should_ allow you to place other variables within the top level of the twin, without the layer reverting them back - as the layer is only concerned with the `layeredProperties` state

The end result of the properties would then look like this 

```
properties.desired: {
   "instance-specific-property": 4000,
   "layeredProperties": {
            "PublishInterval": 2000,
            "OtherProperty": 1
    }
}
```

**Comment by veyalla** [comment]
@vasdee is correct. See here for a similar example: https://stackoverflow.com/a/62661466/10033433

**Comment by nlv-hack** [comment]
Understood, so the trick is to specify the desired properties in a layered deployment that target specific property object e.g.
```
"properties.desired.powerSettings": {
    "MaxChargePower": 5000,
    "MaxDischargePower": 10000
}
```
This is the "unchangeable" object and will get reverted back by the layered deployment. But this now allows adding additional settings to the root object (`properties.desired`) through e.g. Azure portal, and it would look something like this

```
"properties": {
        "desired": {
            "powerSettings": {
                "MaxChargePower": 5000,
                "MaxDischargePower": 10000
            },
            "instance-specific-property": 4000, // new property that won't get reverted/removed by the layered deployment
....
}
```

Tested and verified -works as expected, thanks for your help @vasdee and  @veyalla

**Comment by huguesBouvier** [comment]
I am closing the issue, let us know if there is anything else.
