### ISSUE TITLE
Layered Configuration to only change edgeAgent / edgeHub UpstreamProtocol setting

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#6940]
My deployment contains a typical edgeAgent + edgeHub + myCustomModule. The deployment does not specify the `UpstreamProtocol` setting for edgeAgent / edgeHub. I would like to create a layered deployment which only changed the `UpstreamProtocol` setting for edgeAgent / edgeHub without having to re-specify myCustomModule. 

Is this possible?

**Comment by veyalla** [comment]
Hello @gri6507! Please use IoT Edge Q&A site (https://aka.ms/azure-iotedge-qa)  for "how-to" style questions, thanks!
