### ISSUE TITLE
Configuring module desired status in french and italian Azure IoT Hub interfaces crashes edgeAgent

### ISSUE THREAD

**Issue by EtienneV** [Azure/iotedge#6947]
## Expected Behavior
When using Azure interface in a language other than english (french or italian for example), the configuration parameters sent to the devices should not be translated. They should stay in english so the device can parse them.

## Current Behavior
When setting "Desired Status" of an IoT Edge module to "running" or "stopped" from a translated interface of Azure IoT Hub, the parameter is translated in the configuration JSON sent to the device. The edgeAgent can't understand the parameter, it crashes and the modules don't starts.
This has been seen with the french and the italian Azure Portal interfaces

After defining "stopped" in the italian interface, this log has been seen in the edgeAgent logs : 
---> System.ArgumentException: Requested value 'arrestato' was not found

**Comment by and-rewsmith** [comment]
@EtienneV Thanks for the bug report! 

I am not familiar with Azure interfaces of different languages. I assume you mean that you change the language to Italian somewhere in Azure Portal? Following this, you put "stopped" for runtime status of a module, and it gets sent to device translated.

Am I understanding this correctly? If so, it looks like an Azure Portal bug and we can loop in the necessary contacts.

**Comment by jlian** [comment]
Tagging @iluican to for potential portal bug

**Comment by EtienneV** [comment]
@and-rewsmith Yes, exactly !

I will make an example in french (because I am french, but my italian colleague had the same issue ^^)

1 - Change the language of the interface
![image](https://user-images.githubusercontent.com/8397260/224350716-2ff8a647-8f42-4d6e-b82e-f15b21a14bcd.png)

2 - Go to IoT Hub, select a device, go to "Set Modules", select a module and set it as "stopped" ("arrêté" in french)
![image](https://user-images.githubusercontent.com/8397260/224351689-8030683b-bfb0-483e-a4c3-f305559ed51b.png)

--> We can see that the name of the selected parameter is not shown
![image](https://user-images.githubusercontent.com/8397260/224351865-5b366482-45f8-4391-bcac-d1011b8bcbd7.png)

3 - Validate. We see that the deployment descriptor contains the parameter in french : 
![image](https://user-images.githubusercontent.com/8397260/224352290-33e8ae56-667c-4d45-94ae-439cd8c7afa3.png)

**Comment by iluican** [comment]
Thanks a lot for bringing this to our attention. We will issue a fix ASAP and update the thread once it is deployed. Apologies for the inconvenience.

**Comment by jlian** [comment]
According @iluican, the fix is merged, and I'm checking if it's been deployed

**Comment by EtienneV** [comment]
Hello,
I have tested with the french interface, it is working now !
Thank you and have a nice day

**Comment by jlian** [comment]
Thanks!
