### ISSUE TITLE
Blob Storage module gets amqp:unauthorized-access

### ISSUE THREAD

**Issue by tickledblue3** [Azure/iotedge#6958]
# Background
Having very similar issue as [https://github.com/Azure/iotedge/issues/6828](https://github.com/Azure/iotedge/issues/6828) observed within an EFLOW environment.

Root cause wasn't determined but the workaround was to create/use another IoT Hub and then the thread died.  While I could have another IoT Hub created, it involves quite a bit of coordination with the corporate IT department to create it and open ports within IPS/firewall.   Thus, this workaround is undesirable but I'll go that route if root cause cannot be found.

It has been verified that all of the correct IPS/firewall ports were opened (including the secure amqp port, 5671) from the device to the existing IoT Hub.  IoT Edge was working with these ports previously (months ago).

I followed all the troubleshooting suggestions in the above thread except for the last one because I don't have IoT Hub creation permissions in our Azure cloud and it's difficult getting a lot of IT support's time.
> Also, could you try connecting to the old hub using [this tutorial](https://learn.microsoft.com/en-us/azure/iot-edge/quickstart-linux?view=iotedge-1.4)? That sets up iotedge without the VSCode extension, which will help narrow down whether the issue is with iotedge or the VSCode extension.

# Expected Behavior
Modules on IoT Edge should connect to Cloud and should be able to send Device to Cloud Messages.

# Current Behavior
iotEdge log indicates a unauthorized-access error

Connection is failing with this error:

```
<4> 2023-03-14 20:01:39.583 +00:00 [WRN] - Error creating cloud connection for client VTCKSA4524295/AzureBlobStorageonIoTEdge
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: error(condition:amqp:unauthorized-access,description:Unauthorized access)
 ---> Microsoft.Azure.Amqp.AmqpException: Unauthorized access
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.AmqpIoT.AmqpIoTSession.OpenSendingAmqpLinkAsync(DeviceIdentity deviceIdentity, AmqpSession amqpSession, Nullable`1 senderSettleMode, Nullable`1 receiverSettleMode, String deviceTemplate, String moduleTemplate, String linkSuffix, String correlationId, TimeSpan timeout)
``` 

# Steps to Reproduce

### Context (Environment)
<details><summary>Output of iotedge check</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
31 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Windows 10 Enterprise LTSC
Architecture [e.g. amd64, arm32, arm64]: amd64
Container OS [e.g. Linux containers, Windows containers]: Linux containers
### Runtime Versions
aziot-edged [run iotedge version]: iotedge 1.4.9
Edge Agent [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-agent 1.4.9
Edge Hub [image tag (e.g. 1.0.0)]: mcr.microsoft.com/azureiotedge-hub 1.4.9
<details><summary>Docker/Moby [run docker version]:</summary>

```
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.19.5
 Git commit:        e91ed5707e038b02af3b5120fa0835c5bedfd42e
 Built:             Wed Feb  8 10:10:18 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       87a90dc
  Built:            Wed Feb  8 10:14:15 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        a916309fff0f838eb94e928713dbc3c0d0ac7aa4
 docker-init:
  Version:          0.19.0
  GitCommit:

```
</details>

Attached is the support bundle
[support_bundle_2023_03_14_20_07_48_UTC.zip](https://github.com/Azure/iotedge/files/10973517/support_bundle_2023_03_14_20_07_48_UTC.zip)

**Comment by jlian** [comment]
@arsing would you be able to take a look? Bunch of errors in both edgeAgent and edgeHub logs

**Comment by arsing** [comment]
Based on the logs, identityd does have functional access to the IoT Hub since it was able to query the existing module identities. So your device credentials are correct.

Edge Agent is able to pull its twin from IoT Hub, so its module credentials are being derived correctly. That would mean the master identity key in identityd used to generate module identity keys is also correct.

So for some reason IoT Hub doesn't like the module identity key for the AzureBlobStorageonIoTEdge module, that is being derived from the same master identity key.

1. Did anything change with the IoT Hub or the device at the time it stopped working? For example, did you create / delete identities in the IoT Hub for one or more modules? Did you reinstall IoT Edge on the device or reprovision the device? Anything else?

2. Can you try deleting the AzureBlobStorageonIoTEdge module's identity from IoT Hub and let it be recreated by identityd?

**Comment by arsing** [comment]
Based on internal discussion, your issue might actually be because of an IoT Hub change. We're investigating it internally.

**Comment by arsing** [comment]
IoT Hub made a fix on their end. Do you still see the `amqp:unauthorized-access` error?

**Comment by tickledblue3** [comment]
`amqp:unauthorized-access` error is now gone.   All is working with no errors.  Thanks!
