### ISSUE TITLE
%pre script causes the agent not to install on rpm-ostree versions of RHEL

### ISSUE THREAD

**Issue by mrguitar** [Azure/iotedge#6964]
I'm testing the install of aziot-edge-1.4.9-1.el8.x86_64.rpm on a RHEL 8 edge image. It's basically a RHEL 8 system, w/ the same rpms but put together with rpm-ostree to make it more resilient in edge environments. 

rpm-ostree executes the package install inside a bubblewrap container before it's layered on the underlying host OS. 
The %pre script queries for the docker group on the host to serve as a check to ensure a container engine is installed. Unfortunately this causes the install to fail as we cannot view this group from inside the bwrap container. 

https://github.com/Azure/iotedge/blob/dc5c99ed0c74467776e9b7a5dd4cacccf2c9feab/edgelet/contrib/centos/aziot-edge.spec#L66

Is it possible to drop this check and use a regular rpm dependency instead?

**Comment by jlian** [comment]
@brotherneeru please help investigate feasibility

**Comment by brotherneeru** [comment]
Had to do some asking around, but looks like we intentionally don't use an RPM dependency because we want to allow people to use docker for non-production scenarios. 

The current situation is that we require the user to install moby-engine first and aziot-edge second. Looks like that should work for rpm-ostree too.

**Comment by Gunni** [comment]
Would it not be possible to put a pre-dependency on `containerd` instead? That way anything that satisfies `Provides: containerd` would satisfy it, and allow us to install `aziot-edge` in one transaction.

We are bootstrapping our system via `debootstrap` where every single package to be installed is done withing a single Apt transaction. We don't have a way to tell Apt ourselves the order of package installation.

**Comment by Gunni** [comment]
> The problem there isn't such a thing

Then it might be time to make a feature request for all parties for such a feature, and then modify the `moby-containerd` to have it and then start depending on it.

> we require the group to exist in aziot-edge's preinst script

That's what `Pre-Depends` is meant to solve. And also why I said `pre-dependency` in my comment earlier.

**Comment by arsing** [comment]
>then modify the `moby-containerd` to have it and then start depending on it.

The group is created by `docker-ce` / `moby-engine`, not `moby-containerd`.

**Comment by veyalla** [comment]
Adding @cpuguy83 for his thoughts..

**Comment by cpuguy83** [comment]
Depending on a common "Provides" keyword would be ideal however neither the docker-ce packaging nor our packaging have anything here.

You should be able to do something like `Requires: (moby-engine or docker-ce)`.
This _may_ not work on rhel7... the feature was added to rpm 4.13... but you can handle this in the rpm spec with a macro (and rhel7 will just behave like it does today).

**Comment by cpuguy83** [comment]
For reference: https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html

**Comment by arsing** [comment]
Thanks, good to know.

We have separate specs for 7 vs 8 anyway, so we can just not change the 7 spec if it doesn't work there.

**Comment by bishal41** [comment]
@mrguitar the fix for this issue is already merged and will be included in the next release.

**Comment by Gunni** [comment]
This is fixed for RHEL, which this bug was for, but this issue also exists on Debian based systems, such as Ubuntu as well.
