### ISSUE TITLE
How to run Time Triggered Azure Function on IoTEdge

### ISSUE THREAD

**Issue by raghavrawat98** [Azure/iotedge#6970]
Hello. I have a requirement in which I have to schedule a job to check for updates. I have to run a C# TimeTriggered function and deploy it as a module so that it can detect the change and pass the message to other modules via routing. I was unable to find any documentation. I tried: [Deploy AzFunction on IoTEdge](https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function?view=iotedge-1.4)
But I wasn't able to change the trigger to timer trigger

**Comment by ggjjj** [comment]
Have you looked into this https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=in-process&pivots=programming-language-csharp ? You can implement this in IoT edge module?

what do you mean by "not able to change the trigger to timer trigger"?

**Comment by jlian** [comment]
> schedule a job to check for updates

Can you elaborate? Updates for what?

**Comment by raghavrawat98** [comment]
> Does the link from @ggjjj help?

No. I have added the screenshot for reference
![Screenshot from 2023-03-29 00-27-34](https://user-images.githubusercontent.com/49871652/228342174-95488d69-82ac-4384-9ee3-522a4d6d1f68.png)

**Comment by ggjjj** [comment]
Try `using Microsoft.Azure.WebJobs.Extensions.Timer`

**Comment by ggjjj** [comment]
Did that work?

**Comment by raghavrawat98** [comment]
> using Microsoft.Azure.WebJobs.Extensions.Timer

Apologies for the delay. I tried just now, but am getting this error
![Screenshot from 2023-03-30 22-15-24](https://user-images.githubusercontent.com/49871652/228908016-64b6bb69-7013-4cb8-8842-8b772aacb162.png)

**Comment by ggjjj** [comment]
Looks the the nuget packages need to be updated in your project. 

Open the console by going to Tools > NuGet Package Manager > Package Manager Console in Visual Studio. Then, run the following command:


`Install-Package Microsoft.Azure.WebJobs.Extensions.Timer`

**Comment by raghavrawat98** [comment]
> Looks the the nuget packages need to be updated in your project.
> 
> Open the console by going to Tools > NuGet Package Manager > Package Manager Console in Visual Studio. Then, run the following command:
> 
> `Install-Package Microsoft.Azure.WebJobs.Extensions.Timer`

error: There are no versions available for the package 'Microsoft.Azure.WebJobs.Extensions.Timer'.
I am getting this error for the mentioned command.

**Comment by ggjjj** [comment]
To add a Nuget Package in Visual Studio Code, first make sure NuGet Package manager is added. We can do this by `Ctrl + Shift + X` in windows and select "NuGet Package Manager"

To add the specific NuGet Package, use `Ctrl + Shift + P` in windows and type "NuGet Package Manager: Add Package" and type `Microsoft.Azure.WebJobs.Extensions.Timers.Storage` and choose a version

Now it should work and make sure the nuget package is restored in the output terminal

**Comment by raghavrawat98** [comment]
Apologies for the late reply. Yes @bishal41 the solution provided by @ggjjj is correct and has fixed my issue.
I added the NuGet Package and now my solution is compiling.
Although I noticed I had to remove the namespace
using Microsoft.Azure.WebJobs.Extensions.Timer;
![image](https://user-images.githubusercontent.com/49871652/232868964-287d5acf-b4f1-4907-bb4f-a41b32b0b9e2.png)

**Comment by bishal41** [comment]
@raghavrawat98 thanks for the prompt response and great to hear that the issue is now resolved.
