### ISSUE TITLE
Unable to recover from `Previously failed in deployment xx in prior attempt. Not running command`

### ISSUE THREAD

**Issue by mathiash98** [Azure/iotedge#6971]
## Expected Behavior
EdgeAgent should recover and apply new deployment _regardless_ of how many failed attempts

## Current Behavior
EdgeAgent fails x times, then refuse to reattempt. See logs from EdgeAgent:

```
<6> 2023-03-27 07:26:37.583 +00:00 [INF] - Plan execution ended for deployment 18
<6> 2023-03-27 07:26:45.493 +00:00 [INF] - Plan execution started for deployment 18
<6> 2023-03-27 07:26:45.493 +00:00 [INF] - Executing command: "Prepare module proxy"
<6> 2023-03-27 07:26:57.150 +00:00 [INF] - Executing command: "Prepare module status-dashboard"
<3> 2023-03-27 07:27:06.344 +00:00 [ERR] - Step previously failed in deployment 18 on prior attempt. Not running command Prepare module api. Skipping remaining commands in deployment.
<6> 2023-03-27 07:27:06.344 +00:00 [INF] - Plan execution ended for deployment 18
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Slow internet, some of the new modules in new deployment fail to download, probably due to timeouts
2. EdgeAgent will then refuse to reattempt download of this container after unknown amount of failed attempts
3. Need to restart EdgeAgent in order to reattempt download of new deployment

## Context (Environment)
- Low bandwidth, high ping environment using satellite internet

- `ModuleUpdateMode = WaitForAllPulls`

### Device Information
* Host OS: Ubuntu 20.04
* Architecture: amd64 
* Container OS: Linux 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.1.15
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4.6
* Edge Hub [image tag (e.g. 1.0.0)]:  1.4.6
* Docker/Moby [run `docker version`]: 20.10.17+azure-1

**Comment by ggjjj** [comment]
Edge agent version is `1.4.6` which will not be supported by `1.1.15 aziot-edged`

**Comment by ggjjj** [comment]
Can you get edge agent version to match the 1.1.x version? Has it failed recently or always been this way?

**Comment by jlian** [comment]
We should advise to update IoT Edge runtime to 1.4 to match the containers, right?

**Comment by ggjjj** [comment]
> We should advise to update IoT Edge runtime to 1.4 to match the containers, right?

yes or if they cannot get the runtime to update they can still change edge agent images right?

**Comment by mathiash98** [comment]
> Edge agent version is `1.4.6` which will not be supported by `1.1.15 aziot-edged`

According to the release of 1.4.0: https://github.com/Azure/azure-iotedge/releases/tag/1.4.0

`1.4 LTS is backward compatible with 1.1+`

**Comment by ggjjj** [comment]
@mathiash98 Yes 1.4 LTS is backward compatible with 1.1+ but it is tested extensively. I have another recommendation to try to see if it fixes the retry of the module. 
The environment variable `MaxRestartCount` can be set to a desired value and see if EdgeAgent try to deploy it. 
https://github.com/Azure/iotedge/blob/main/doc/EnvironmentVariables.md?plain=1#L17 

Actually it is the expected behaviour that if something fails enough, then we don't retry. so you can config it using the env variable mentioned above.

**Comment by mathiash98** [comment]
> @mathiash98 Yes 1.4 LTS is backward compatible with 1.1+ but it is tested extensively. I have another recommendation to try to see if it fixes the retry of the module. The environment variable `MaxRestartCount` can be set to a desired value and see if EdgeAgent try to deploy it. https://github.com/Azure/iotedge/blob/main/doc/EnvironmentVariables.md?plain=1#L17
> 
> Actually it is the expected behaviour that if something fails enough, then we don't retry. so you can config it using the env variable mentioned above.

Thanks for the `MaxRestartCount` env variable, will test it.
- Is it possible to set it to 0 to retry forever?

I would argue that "Network failures" are _not_ the same as normal deployment failures. An IoT framework MUST retry until network finally works fine. We _can not_ have lots of installations refusing to update because they have slow or no internet for a couple of days. Our fleet of devices consists of lots of vessels depending on Satellite or LTE connection where they might be without signal for 2 days before they finally come back to shore and have quite good internet speed.
- Current implementation makes IotEdge quite unusable for our business usecase.

**Comment by ggjjj** [comment]
I don't think it is possible to retry forever as per design. I understand your concern. We are backward compatible with 1.1+ but full support is limited. So I would recommend moving to 1.4 LTS

**Comment by mathiash98** [comment]
> I don't think it is possible to retry forever as per design. I understand your concern. We are backward compatible with 1.1+ but full support is limited. So I would recommend moving to 1.4 LTS

Thank you, I trust that you bring this bug to whoever need to consider and implement a better solution for it 👍🏼

**Comment by ggjjj** [comment]
We have created action items to be reviewed based on our priorities for this issue. So closing this issue now.

**Comment by mathiash98** [comment]
I would like to emphasise the severity if this issue again:
1. We inform customer about newly released software
2. The customer calls us and says they have not received it yet, even though it's been 2 days
3. We check EdgeAgent logs and see:

10 attempts per minute to apply latest deployment, but refuses to do so because of this "bug".
```
<6> 2023-05-26 08:16:04.411 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:04.411 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:04.411 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:10.117 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:10.117 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:10.118 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:15.856 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:15.856 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:15.856 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:21.704 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:21.704 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:21.704 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:27.431 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:27.431 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:27.431 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:33.160 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:33.160 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:33.160 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:38.846 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:38.847 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:38.847 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:44.558 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:44.558 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:44.558 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:50.458 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:50.458 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:50.458 +00:00 [INF] - Plan execution ended for deployment 22
<6> 2023-05-26 08:16:56.291 +00:00 [INF] - Plan execution started for deployment 22
<3> 2023-05-26 08:16:56.291 +00:00 [ERR] - Step previously failed in deployment 22 on prior attempt. Not running command Prepare module connect-frontend. Skipping remaining commands in deployment.
<6> 2023-05-26 08:16:56.291 +00:00 [INF] - Plan execution ended for deployment 22
```

**Comment by damonbarry** [comment]
@mathiash98 In the logs you provided, I think Edge agent is still retrying. It's just that the exponential backoff strategy in the Edge agent code is pretty basic and aggressive:
```csharp
coolOff * (2 ^ runCount)
```

The default cool off is 10 seconds, so two days is only about 13 retries.

If you set the environment variable `CoolOffTimeUnitInSeconds` to 0 and increase the `MaxRestartCount` environment variable to some large number (max is 2147483647), that will effectively disable exponential backoff. You could also set `CoolOffTimeUnitInSeconds` to 1 to keep the exponential backoff, but give yourself a few more retries before the numbers get big.

**Comment by mathiash98** [comment]
> @mathiash98 In the logs you provided, I think Edge agent is still retrying. It's just that the exponential backoff strategy in the Edge agent code is pretty basic and aggressive:
> 
> ```cs
> coolOff * (2 ^ runCount)
> ```
> 
> The default cool off is 10 seconds, so two days is only about 13 retries.
> 
> If you set the environment variable `CoolOffTimeUnitInSeconds` to 0 and increase the `MaxRestartCount` environment variable to some large number (max is 2147483647), that will effectively disable exponential backoff. You could also set `CoolOffTimeUnitInSeconds` to 1 to keep the exponential backoff, but give yourself a few more retries before the numbers get big.

Thank you! I will try this. Seems like the log messages are a bit misleading though. And the numbers should definately be reduced
