### ISSUE TITLE
Memory Leak in an embedded Linux environment. IoTEdge 1.4

### ISSUE THREAD

**Issue by MCYamamoto** [Azure/iotedge#6983]
## Expected Behavior
The memory used does not continue to increase even if telemetry is continuously sent.

## Current Behavior
Each time telemetry is sent from the custom module, the memory used by the edgeHub module continues to increase.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Install IoT Edge on an embedded Linux device (OpenBlocks IoT VX2 in our case)
2. Add the `edgeHub` and `edgeAgent` modules to its deployment
3. Add the `sampleModule` custom modules to its deployment
4. Start IoT Edge
5. Continuously transmit telemetry from the custom module.
   The telemetry transmission volume is 20 characters in 250 ms cycles.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
? aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.4.1 but 1.4.3 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
? aziot-edge package is up-to-date - Warning
    Installed IoT Edge daemon has version 1.4.2 but 1.4.9 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ container time is close to host time - OK
? DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
? production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
? production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
? production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
27 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
4 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Custom Debian 10 (buster), on a OpenBlocks IoT VX2
* Architecture: Intel
* Container OS:Linux containers

### Runtime Versions
* aziot-edged: `iotedge 1.4.2`
* Edge Agent: `1.4`
* Edge Hub: `1.4`
* Docker/Moby: `20.10.21+azure-1`

## Logs

More detailed or specific logs can be provided if needed.

The graph below shows the amount of memory measured after running the system for 24 hours.

**Blue line：Graph of used(MB) obtained by "free" command**

**Orange line：Graph of edgeHub's memory volume obtained with the "docker stats" command**
![image-20230405160216068](https://user-images.githubusercontent.com/49817876/230008543-1ab40f59-7280-4999-bc71-42ad8e03e762.png)

## Additional Information
A complete set of execution environment is attached.
[MemLeak_EdgeSolution.zip](https://github.com/Azure/iotedge/files/11156146/MemLeak_EdgeSolution.zip)

**Comment by gordonwang0** [comment]
An increase in memory usage is expected as edgeHub runs. When you run it for longer (after 1 week or so), does the memory usage level off or keep increasing?

Note that we cannot help debug custom modules.

**Comment by MCYamamoto** [comment]
@gordonwang0 
The edgeHub's memory usage kept increasing even after running it for 6 days.
Therefore, I created an Issue with a sample program to attach.
Will the memory usage stop increasing in 7 days?

Debugging custom modules is not required.
Please use the attached file as a reproduction environment.

**Comment by MCYamamoto** [comment]
I would like to limit the memory usage of edgeHub because it is using a lot of memory.
It is recognized that the following options can limit edgeHub's memory usage.
``` 
"createOptions": {
  "HostConfig": {
    "Memory": 268435456
  }
}
``` 
What is the minimum memory requirement for edgeHub?

**Comment by gordonwang0** [comment]
We recommend between 300MB to 500MB as a minimum, depending on your use case. Note that edgeHub will restart if it reached the memory limit you set.

**Comment by MCYamamoto** [comment]
@gordonwang0 
Thank you very much.
I just checked the progress for 7 days,
The memory used has not increased since 550MB.

> We recommend between 300MB to 500MB as a minimum, depending on your use case. Note that edgeHub will restart if it reaches the memory limit you set.

So, I guess that means that edgeHub may restart when I set the memory limit.
If so, I will not set the upper limit of memory usage.

**Comment by bishal41** [comment]
@MCYamamoto is setting the memory limit helping with your issue? Let us know whether this issue can be closed? thanks!

**Comment by MCYamamoto** [comment]
@bishal41 
> is setting the memory limit helping with your issue? Let us know whether this issue can be closed? 

No.
We believe that it is not possible to set a memory limit because the answer is that edgeHub will restart if a memory limit is set.

However, we have confirmed that memory usage does not continue to rise without setting a memory limit, so the problem has been resolved.

**Comment by bishal41** [comment]
@MCYamamoto - thanks for sharing the update and glad the issue is resolved now.
