### ISSUE TITLE
`iotedge check` should not warn about DNS not being configured in docker config

### ISSUE THREAD

**Issue by Gunni** [Azure/iotedge#6984]
## Expected Behavior
When no DNS is specified in Docker daemon.json it uses the system configured dns, this warning is unhelpful.

Check should only warn if communication with DNS servers from within containers does not work.

```
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
```

## Current Behavior
Containers use the system configured DNS servers, the warning serves no purpose.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Remove DNS configuration from docker daemon.json
2. Restart docker and iot runtime
3. Run `iotedge check`
4. Observe warning
5. Observe that despite the warning, DNS within containers still works

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ tpmd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
38 check(s) succeeded.
1 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS: Ubuntu 20.04
* Architecture: amd64
* Container OS: Docker?

### Runtime Versions
* aziot-edged: 1.4.9
* Edge Agent: 1.2.8
* Edge Hub: 1.2.8
* Docker/Moby: 20.10.23+azure-2

**Comment by gordonwang0** [comment]
I checked with the team; it is expected that DNS is set in docker's daemon.json. While it's true that this warning isn't helpful in cases like you mentioned, you can ignore it. For now, there are no plans to change this warning.

**Comment by Gunni** [comment]
`iotedge` is designed for IoT devices that are intended for deployment in various environments, many of which rely on DHCP for network configuration.

In cases where DHCP is not used, we still need to configure a static IP and DNS on the host. It would be more efficient to configure only the host, rather than both the host and the Docker daemon.json file.

The current warning only indicates that the DNS configuration is missing from the daemon.json file. It does not mention that the DNS server defaults to the host's DNS settings, or that it is safe to ignore the warning in certain cases. This can lead to unnecessary troubleshooting and configuration changes when there is no actual issue with the setup.

As a first step, I suggest updating the warning message to include information about the default behavior of using the host's DNS settings and when it is appropriate to ignore the warning. In the future, a more robust improvement could involve testing the actual networking functionality from within a test container to ensure proper DNS connectivity.

This approach would provide a clearer and more informative warning system that is better suited to the diverse environments in which `iotedge` nodes are deployed.

**Comment by polarina** [comment]
I concur with @Gunni.

I would like to request clarification from the team as to why it is expected one configures static DNS addresses in `docker.json`.

It feels counterintuitive for IoT devices to have static DNS. We deploy IoT devices on customers' premises where they provide and are responsible for network access. I would've though that to be by-far the most common use-case for IoT, where static DNS is simply impractical.
