### ISSUE TITLE
Unable to run a customEdgeModule and receiving back-off status with exit code 145

### ISSUE THREAD

**Issue by ilyas-it83** [Azure/iotedge#70]
I'm trying to run a custom Edge Module by following https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module, when deployed on edge i get "backoff" status with 145 error code

I suspect the issue could be because of the connection attempt at INIT, the OpenAsync() method gets timedout.

ModuleClient ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
await ioTHubModuleClient.OpenAsync();  

## Expected Behavior
Able to filter telemetry message that comes from TempSimulator as shown in https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux#deploy-a-module, the simulation model works as per the article. 

## Current Behavior
Able to develop and deploy Filter Module as described here https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module, however i get module status as "backoff" with an error code 145

## Steps to Reproduce
1.  Setup Edge as described here https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux
2.  Simulate data as described here https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux#deploy-a-module

3. Build and deploy custom module as described here https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module

## Context (Environment)
IoTEdge Simulation on DSVM (Ubuntu)
### Device (Host) Operating System
Linux version 4.15.0-1018-azure (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu116.04.10)) #1816.04.1-Ubuntu SMP Thu Jul 19 13:13:57 UTC 2018

### Architecture
amd64

### Container Operating System
Linux containers 

### Runtime Versions
iotedge 1.0.0
#### iotedged
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Agent
mcr.microsoft.com/azureiotedge-hub:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
Docker version 18.06.0-dev, build daf021fe

## Logs
refer the logs attached here https://github.com/Azure/iotedge/issues/69

**Comment by dsajanice** [comment]
Hi @ilyas-it83 if switching to amqp fixed the problem, I would like to close this issue.

**Comment by WilliamBerryiii** [comment]
@dsajanice - shouldn't the modules support both MQTT and AMQP protocols ... does this mean that MQTT is broken? Is that documented somewhere?

**Comment by varunpuranik** [comment]
@WilliamBerryiii MQTT and AMQP are both connected, but right now we have an issue (that we are investigating), that causes MQTT connection requests to timeout during the TLS handshake. If the module retries on the timeout exception, it should succeed.

**Comment by WilliamBerryiii** [comment]
@varunpuranik sweet thanks!  Do we have a reference implementation for the best retry approach? Using, say, something like [Polly](https://github.com/App-vNext/Polly)? Is it just as simple as waiting for the timeout exception and attempting to reconnect?

**Comment by varunpuranik** [comment]
You can look at the SimulatedTemperatureSensor for the retry policy (it uses AMQP, but the retry policy can remain the same). 
https://github.com/Azure/iotedge/blob/master/edge-modules/SimulatedTemperatureSensor/src/Program.cs

Essentially, you just need to catch the Timeout exception and retry... any mechanism you use is fine.

**Comment by ilyas-it83** [comment]
Not exactly the same issue, but weirdly another issue popped up today from nowhere.  There is one closed thread which captures this problem here https://github.com/Azure/azure-iot-sdk-c/issues/214

However, filter module using AMQP works fine, but intermittently this module also has opening connections with the local broker.

Error Logs
---------------------------------------
IoT Hub Client for Python
Starting the IoT Hub Python sample using protocol MQTT...
The sample is now waiting for messages and will indefinitely.  Press Ctrl-C to exit.
Error: Time:Wed Aug  1 13:02:56 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Wed Aug  1 13:02:56 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Wed Aug  1 13:02:56 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Wed Aug  1 13:02:56 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Wed Aug  1 13:02:56 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Wed Aug  1 13:02:56 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2036 failure connecting to address ilyasvm.
Error: Time:Wed Aug  1 13:02:57 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Wed Aug  1 13:02:57 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Wed Aug  1 13:02:57 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Wed Aug  1 13:02:57 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Wed Aug  1 13:02:57 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Wed Aug  1 13:02:57 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2036 failure connecting to address ilyasvm.
Error: Time:Wed Aug  1 13:02:59 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Wed Aug  1 13:02:59 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Wed Aug  1 13:02:59 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Wed Aug  1 13:02:59 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Wed Aug  1 13:02:59 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Wed Aug  1 13:02:59 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2036 failure connecting to address ilyasvm.
Error: Time:Wed Aug  1 13:03:03 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Wed Aug  1 13:03:03 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Wed Aug  1 13:03:03 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Wed Aug  1 13:03:03 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Wed Aug  1 13:03:03 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Wed Aug  1 13:03:03 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2036 failure connecting to address ilyasvm.

Twin callback called with:
updateStatus = COMPLETE
payload = {"desired":{"$version":1},"reported":{"$version":1}}
context = <__main__.HubManager object at 0x7f07de6522d0>
Total calls confirmed: 1

**Comment by SachaLhopital** [comment]
Hi, 
I am facing the same issue as you @ilyas-it83 : 

```shell
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609]

IoT Hub Client for Python
MESSAGE_TIMEOUT: 10000
Error: Time:Tue Sep  4 12:42:35 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep  4 12:42:35 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep  4 12:42:35 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep  4 12:42:35 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep  4 12:42:35 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep  4 12:42:35 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address advantech-desktop.
Starting the IoT Hub Python sample using protocol MQTT...
The sample is now waiting for messages and will indefinitely.  Press Ctrl-C to exit.
Error: Time:Tue Sep  4 12:42:36 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep  4 12:42:36 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep  4 12:42:36 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep  4 12:42:36 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep  4 12:42:36 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep  4 12:42:36 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address advantech-desktop.
Error: Time:Tue Sep  4 12:42:39 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep  4 12:42:39 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep  4 12:42:39 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep  4 12:42:39 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep  4 12:42:39 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep  4 12:42:39 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address advantech-desktop.
Error: Time:Tue Sep  4 12:42:42 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep  4 12:42:42 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep  4 12:42:42 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep  4 12:42:42 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep  4 12:42:42 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep  4 12:42:42 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address advantech-desktop.
Error: Time:Tue Sep  4 12:42:50 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:383 Failure: connect failure 111.
Error: Time:Tue Sep  4 12:42:50 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:767 wait_for_connection failed
Error: Time:Tue Sep  4 12:42:50 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:748 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Sep  4 12:42:50 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1246 Failed opening the underlying I/O.
Error: Time:Tue Sep  4 12:42:50 2018 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:989 Error: io_open failed
Error: Time:Tue Sep  4 12:42:50 2018 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2037 failure connecting to address advantech-desktop.

Twin callback called with:
updateStatus = COMPLETE
payload = {"desired":{"$version":1},"reported":{"$version":1}}
context = <__main__.HubManager object at 0x7f6db56ab450>
Total calls confirmed: 1
```
I also have that feeling that this issue popped up from nowhere. This issue appears on a Python module using MQTT and an Ethernet connection. But this error appears right after starting. 

Is anyone has a guess on how to solve it ?
Many thanks,
Sacha
