### ISSUE TITLE
Iotedge Module OpcPublisher is not running

### ISSUE THREAD

**Issue by vaishnavils97** [Azure/iotedge#7015]
Hi Team,
I am using multiple opcpublisher module with different runtime settings. But only one module is running as if now. The other opcpublisher module is getting failed . This is a marketplace Module from Microsoft. I have configured 2 different opc server to communicate to this 2 different modules.

Please give inputs on how to run multiple opcpublisher Modules with multiple OPC servers or is it possible in a way that we can configure 2 different OPC server end points on same opcpublisher module.

**Comment by veyalla** [comment]
Please use https://github.com/Azure/Industrial-IoT for help around OPC Publisher module.

**Comment by vaishnavils97** [comment]
Hi @veyalla 

In the above mentioned repo, i have noticed that it is possible to add multiple OPC server to one OPC publisher module.The only change  is with the json file of OPC publisher Module with tag details. Is there any way to add 2 OPC Publisher Module at Edge to connect to 2 OPC server ? 

This point is missing in the above document
