### ISSUE TITLE
IoT Edge Runtime takes a long time to cycle through signing mechanisms before giving up and moving on

### ISSUE THREAD

**Issue by maskimthedog** [Azure/iotedge#7016]
## Expected Behavior
Iotedge system reprovision should execute without error.

## Current Behavior
Previously we have been able to provision iotedge runtime devices with a cert/key stored in an optee keystore and accessed via PKCS#11.

Iotedge config apply
Iotedge system reprovision

At some point in time in the past few weeks, this has stopped working. The version of iotedge has remained the same (1.4.9 also tested 1.4.10), as has the optee implementation.

See iotedge-reprovision-error.md for logs

When the key is stored on the filesystem, and accessed as a file in the config.toml, we can provision the device.

We have been drilling down into keyd and optee client, comment from Jerry:

“I got the debug output and aziot-keyd passed the mechanism 0x251 CKM_SHA256_HMAC and 0x3 CKM_RSA_X_509 to the function serialize_ck_mecha_params in serialize_ck.c 
the first 0x251 should be supported in code except the variable ulParameter not empty. 0x3 was not supported in optee”

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
Observed on iotedge 1.4.9 and 1.4.10

Clear overlayfs
Reinstall certs/key to optee key storage
Reboot
"run iotedge config apply"
root@imx8mmevk:~# iotedge system status System services: aziot-edged Running aziot-identityd Down - activating aziot-keyd Running aziot-certd Running aziot-tpmd Ready

aziot-identityd is in a bad state because: aziot-identityd.service: Down - activating : Printing the last 10 log lines. -- Journal begins at Thu 1970-01-01 00:00:03 UTC, ends at Thu 2023-05-04 21:02:16 UTC. -- May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 4: May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 5: May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 6: May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 7: May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 8: May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 9: May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 10: __libc_start_main May 04 21:02:15 imx8mmevk aziot-identityd[3182]: 11: May 04 21:02:15 imx8mmevk systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE May 04 21:02:15 imx8mmevk systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.

Use 'iotedge system logs' to check for non-fatal errors. Use 'iotedge check' to diagnose connectivity and configuration issues.

iotedge system reprovision Failed to reprovision: connection error: Connection reset by peer (os error 104) Error running system command
May 04 21:05:19 imx8mmevk systemd[1]: Stopped Azure IoT Identity Service. May 04 21:05:19 imx8mmevk aziot-edged[2884]: 2023-05-04T21:05:19Z [WARN] - Failed to send HTTP request (attempt 2 of 2): connection error: Connection reset by peer (os error 104) May 04 21:05:19 imx8mmevk aziot-edged[2884]: 2023-05-04T21:05:19Z [ERR!] - Failed to obtain device identity: connection error: Connection reset by peer (os error 104) May 04 21:05:19 imx8mmevk aziot-edged[2884]: 2023-05-04T21:05:19Z [INFO] - Requesting device reprovision May 04 21:05:19 imx8mmevk aziot-edged[2884]: 2023-05-04T21:05:19Z [WARN] - Failed to clear provisioning cache before reprovision: No such file or directory (os error 2) May 04 21:05:19 imx8mmevk aziot-edged[2884]: 2023-05-04T21:05:19Z [WARN] - Failed to send HTTP request (attempt 1 of 2): error trying to connect: Connection refused (os error 111) May 04 21:05:19 imx8mmevk systemd[1]: Started Azure IoT Identity Service. May 04 21:05:19 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:19Z [ERR!] - could not encrypt: C_SignInit failed with CKR_MECHANISM_INVALID May 04 21:05:19 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:19Z [ERR!] - !!! internal error May 04 21:05:19 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:19Z [ERR!] - !!! caused by: could not encrypt May 04 21:05:19 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:19Z [ERR!] - !!! caused by: could not encrypt: AZIOT_KEYS_RC_ERR_EXTERNAL May 04 21:05:22 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:22Z [ERR!] - could not encrypt: C_SignInit failed with CKR_MECHANISM_INVALID May 04 21:05:22 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:22Z [ERR!] - !!! internal error May 04 21:05:22 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:22Z [ERR!] - !!! caused by: could not encrypt May 04 21:05:22 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:22Z [ERR!] - !!! caused by: could not encrypt: AZIOT_KEYS_RC_ERR_EXTERNAL May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - service encountered an error May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - caused by: DPS client error May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - caused by: error trying to connect: error:81005001:aziot_key_openssl_engine:aziot_key_rsa_priv_enc::key/aziot-key-openssl-engine/src/lib.rs:112:internal error, error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib:../openssl-1.1.1n/ssl/statem/statem_lib.c:308: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - caused by: error:81005001:aziot_key_openssl_engine:aziot_key_rsa_priv_enc::key/aziot-key-openssl-engine/src/lib.rs:112:internal error, error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib:../openssl-1.1.1n/ssl/statem/statem_lib.c:308: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - caused by: error:81005001:aziot_key_openssl_engine:aziot_key_rsa_priv_enc::key/aziot-key-openssl-engine/src/lib.rs:112:internal error, error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib:../openssl-1.1.1n/ssl/statem/statem_lib.c:308: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - caused by: error:81005001:aziot_key_openssl_engine:aziot_key_rsa_priv_enc::key/aziot-key-openssl-engine/src/lib.rs:112:internal error, error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib:../openssl-1.1.1n/ssl/statem/statem_lib.c:308: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2023-05-04T21:05:22Z [ERR!] - 0: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 1: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 2: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 3: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 4: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 5: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 6: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 7: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 8: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 9: May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 10: __libc_start_main May 04 21:05:22 imx8mmevk aziot-identityd[8503]: 11: May 04 21:05:22 imx8mmevk systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE May 04 21:05:22 imx8mmevk systemd[1]: aziot-identityd.service: Failed with result 'exit-code'. May 04 21:05:27 imx8mmevk systemd[1]: aziot-identityd.service: Scheduled restart job, restart counter is at 41. May 04 21:05:27 imx8mmevk systemd[1]: Stopped Azure IoT Identity Service. May 04 21:05:27 imx8mmevk aziot-edged[2884]: 2023-05-04T21:05:27Z [WARN] - Failed to send HTTP request (attempt 2 of 2): connection error: Connection reset by peer (os error 104) May 04 21:05:27 imx8mmevk aziot-edged[2884]: 2023-05-04T21:05:27Z [WARN] - Failed to reprovision: connection error: Connection reset by peer (os error 104) May 04 21:05:27 imx8mmevk systemd[1]: Started Azure IoT Identity Service. May 04 21:05:27 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:27Z [ERR!] - could not encrypt: C_SignInit failed with CKR_MECHANISM_INVALID May 04 21:05:27 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:27Z [ERR!] - !!! internal error May 04 21:05:27 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:27Z [ERR!] - !!! caused by: could not encrypt May 04 21:05:27 imx8mmevk aziot-keyd[2895]: 2023-05-04T21:05:27Z [ERR!] - !!! caused by: could not encrypt: AZIOT_KEYS_RC_ERR_EXTERNAL

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
Yocto Hardknott

### Runtime Versions
meta-iotedge 1.4.9
meta-iotedge 1.4.10

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
At the beginning, aziot-keyd selected x251 CKM_SHA256_HMAC and 0x3 CKM_RSA_X509 as signing mechanism but optee didn't support CKM_RSA_X509, which cause the following errors and device provision always stuck on the loop of producing this error (image below). I cannot capture the earlier log because it was overwritten.
![IoT_Edge_Error_1](https://user-images.githubusercontent.com/41034265/236525844-9a220460-773e-4ad8-a337-f8b47b0a1a2c.png)
 
 However, waiting for long time, I saw azure discarded the mechanism 0x3 CKM_RSA_X509 and switched to 0x251 CKM_SHA256_HMAC and 0x1 CKM_RSA_PKCS.
![IoT_Edge_Error_2](https://user-images.githubusercontent.com/41034265/236525909-d63c05c1-6e13-47c0-a8cd-1d23925b3a6e.png)

Because CKM_RSA_PKCS is supported by optee, the device then can work normally. 
![IoT_Edge_Error_3](https://user-images.githubusercontent.com/41034265/236525956-c0ffbe6f-a772-4165-9094-2ae814376b86.png)

**Comment by nyanzebra** [comment]
Hi @maskimthedog, just to be clear, you have been using 1.4.9/10 for a while, where provisioning was working? Then at somepoint provisioning stopped working?

In regards to secrets, could you provide what openssl version you are using?

Also, do you know when this roughly started happening?

**Comment by maskimthedog** [comment]
From my colleagues:

"when we changed over from iotc to iothub (roughly a month or so ago), Matt and I did a whole lot of reprovisioning of devices and we didn't have any issues other than the osconfig config running interference. And we've been running 1.4.9 over that same period as well

OpenSSL 1.1.1n  15 Mar 2022

I was having issues provision my device maybe a couple of weeks ago, but I didn't follow up on it as I had other things I was working on"

**Comment by nyanzebra** [comment]
@maskimthedog just to eliminate this possibility, are you able to verify the key using openssl? Just want to eliminate the simplest possibility first if I can :)

**Comment by maskimthedog** [comment]
> @maskimthedog just to eliminate this possibility, are you able to verify the key using openssl? Just want to eliminate the simplest possibility first if I can :)

yes, using a key on the filesystem works

**Comment by nyanzebra** [comment]
@maskimthedog so after looking into this, 

IoT Edge runtime does not make any decision to "cycle through" RSA mechanisms, nor is there "a long time" between them. When IoT Edge tells openssl to do TLS, openssl internally tells the openssl engine to do an RSA private encrypt operation with the mechanism specified by openssl. If openssl told it to use RSA_PKCS1_PADDING then that manifests as keyd telling the PKCS#11 library to do C_Sign(CKM_RSA_PKCS). If openssl told it to use RSA_NO_PADDING then that manifests as keyd telling the PKCS#11 library to do C_Sign(CKM_RSA_X509). The mechanism is chosen by openssl internally (you can trace through your distro's openssl if you want), and one would expect that openssl tries one mechanism and then immediately tries the next if the first one fails.

**Comment by maskimthedog** [comment]
> @maskimthedog so after looking into this,
> 
> IoT Edge runtime does not make any decision to "cycle through" RSA mechanisms, nor is there "a long time" between them. When IoT Edge tells openssl to do TLS, openssl internally tells the openssl engine to do an RSA private encrypt operation with the mechanism specified by openssl. If openssl told it to use RSA_PKCS1_PADDING then that manifests as keyd telling the PKCS#11 library to do C_Sign(CKM_RSA_PKCS). If openssl told it to use RSA_NO_PADDING then that manifests as keyd telling the PKCS#11 library to do C_Sign(CKM_RSA_X509). The mechanism is chosen by openssl internally (you can trace through your distro's openssl if you want), and one would expect that openssl tries one mechanism and then immediately tries the next if the first one fails.
> 
> Also, does your PKCS#11 library supports EC keys?

Thanks for your thorough analysis.  We will look into our distros (Yocto) OpenSSL.

**Comment by nyanzebra** [comment]
@maskimthedog, are you okay with closing this issue? Feel free to re-open at any time :)

**Comment by maskimthedog** [comment]
> @maskimthedog, are you okay with closing this issue? Feel free to re-open at any time :)

Yes, I feel comfortable with the provided analysis and will re-open if needed.  :)
