### ISSUE TITLE
Give container access to USB devices via the createOptions

### ISSUE THREAD

**Issue by tcochunk** [Azure/iotedge#7024]
I am new to IOT development so please forgive my ignorance.  I am trying to create a container and deploy it to raspberry pi thru Azure.  I want the container to have access to a certain usb device (access to all usb devices would be acceptable at this point as well).  I have updated the createOptions to be the following:

{
    "HostConfig": {
        "Privileged": true,
        "Devices": [
            {
                "PathOnHost": "/dev/serial/by-id/usb-MicroPython_Board_in_FS_mode_e66118604b659326-if00",
                "PathInContainer": "/dev/serial/by-id/usb-MicroPython_Board_in_FS_mode_e66118604b659326-if00",
                "CgroupPermissions": "rwm"
            }
        ]
    }
}

the Privileged was trying to brute force all devices.  I am trying to connect a Pico board via usb cable to the Pi.

However, when the module starts up i get the following error:

Unhandled exception. System.AggregateException: One or more errors occurred. (Access to the port '/dev/ttyACM0' is denied.)
 ---> System.UnauthorizedAccessException: Access to the port '/dev/ttyACM0' is denied.
 ---> System.IO.IOException: Permission denied

When i run the same code on the Pi directly (not in a container) it works as expected.

Any help would be much appreciated

**Comment by yophilav** [comment]
Hi there! 
@tcochunk, the USB device that you're trying to access is some sort of the storage memory? 
If so, you will want to mount the device with the following configuration: 
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4

**Comment by tcochunk** [comment]
@yophilav it is NOT a storage device but rather a micro controller board

[https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html](url)

connected to the raspberry pi via USB cable

**Comment by yophilav** [comment]
@tcochunk , 
I see. May we close this github issue and post the question to https://aka.ms/iotedge-qna for guidance please?
