### ISSUE TITLE
Debian postrm script fails to execute purge command when run inside systemd-nspawn container

### ISSUE THREAD

**Issue by msqr** [Azure/iotedge#7027]
I use `systemd-nspawn` to automate the management of packages in OS image files, and I have one image that comes with the Debian `aziot-edge` package pre-installed and I want to remove it. Unfortunately the `postrm` script if failing at this line:

https://github.com/Azure/iotedge/blob/cfbdbf61c23744b279d7d47a87b2039b3f89f124/edgelet/contrib/debian/postrm#L6

because `systemctl daemon-reload` returns an error when run within a container:

```
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package aziot-edge (--purge):
 installed aziot-edge package post-removal script subprocess returned error exit status 1
```

I have encountered this issue myself in Debian package scripts, and the solution I've used was to simply ignore errors for the command, like

```
systemctl daemon-reload 2>/dev/null || true
```

**Comment by yophilav** [comment]
@arsing I think that should be fine. Any thoughts on this?

**Comment by arsing** [comment]
Just what I said in https://github.com/Azure/iot-identity-service/issues/531#issuecomment-1553919251 , ie it's fine to ignore the exit code but I wonder if we need it at all.
