### ISSUE TITLE
Users can create devices with a name using special MQTT characters (#...) leading to impossibility to connect to the EdgeHub

### ISSUE THREAD

**Issue by chefmtt** [Azure/iotedge#7029]
## Expected Behavior

User should be denied the right to create a device containing invalid characters and be warned about it

## Current Behavior

Device creation works fine, but that leads to issues when trying to use the device connection string

## Steps to Reproduce

1. Through either the Azure Portal or CLI, create a device containing an invalid character (I stumbled upon this with "#", but I guess "+" should produce the same result ?
2. Initiate a connection from a module on the device you created, using the erroneous DEVICE_CONNECTION_STRING

### Output of `iotedge check`

Everything is fine, except for a few production readiness warning, on both devices on which I tested the issue

### Device Information

Tested it on both an amd64 Ubuntu install and an arm64 Debian install

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent: 1.4
* Edge Hub: 1.4
* Docker/Moby [run `docker version`]: 
(I am not on my work machine right now, but I installed both moby and the runtime through the Microsoft APT repo)

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

Starting the Python IoT Hub C2D Messaging device sample...
Waiting for C2D messages, press Ctrl-C to exit
Subscribe for c2d failed.  Not enabling feature
Shutting down IoT Hub Client
Traceback (most recent call last):
  File "/home/{user}/projects/{project}/IoT-playground/template_solution/modules/message_monitoring/main.py", line 97, in <module>
    main()
  File "/home/{user}/projects/{project}/IoT-playground/template_solution/modules/message_monitoring/main.py", line 83, in main
    client.on_message_received = message_handler
  File "/home/{user}/miniconda3/envs/edge-device/lib/python3.9/site-packages/azure/iot/device/iothub/abstract_clients.py", line 683, in on_message_received
    self._generic_receive_handler_setter(
  File "/home/{user}/miniconda3/envs/edge-device/lib/python3.9/site-packages/azure/iot/device/iothub/sync_clients.py", line 151, in _generic_receive_handler_setter
    self._enable_feature(feature_name)
  File "/home/{user}/miniconda3/envs/edge-device/lib/python3.9/site-packages/azure/iot/device/iothub/sync_clients.py", line 107, in _enable_feature
    callback.wait_for_completion()

**Comment by yophilav** [comment]
@chefmtt 
Thank you for the feedback! It indeed looks like there was no check for these [special characters](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#device-identity-properties).
We have communicated to Azure CLI and Azure Portal teams regarding the issue. We will let you know when the next fix is available.

**Comment by yophilav** [comment]
@chefmtt
After some further internal discussion, we decided it will be best for IoTHub service team to handle the issue. The service team is aware of the problem. If you would like to have a tracking issue, please feel free to contact Microsoft Support to file a support ticket with IoT Hub.  Again, Thank you for your feedback.

**Comment by chefmtt** [comment]
@yophilav Thank you very much for your quick handling of the issue and keeping me in the loop!
