### ISSUE TITLE
Bring back the IOT Edge VS Code extension

### ISSUE THREAD

**Issue by mwilcox12014** [Azure/iotedge#7039]
I believe we have moved backwards in the effort to make it easy to create an IOT Edge Module.  
The Azure IOT extension in VS code worked seamlessly and efficiently.   

Not so much with the Python Code (https://github.com/Azure/iotedgedev/blob/main/docs/environment-setup/manual-dev-machine-setup.md)  suggested here:  Tutorial: Develop IoT Edge modules using Visual Studio Code https://learn.microsoft.com/en-us/azure/iot-edge/tutorial-develop-for-linux?view=iotedge-1.4&tabs=python&pivots=iotedge-dev-cli 
The installation of the C++ code is time consuming and 'bloats' the dev box.  The pip install of the python is full of time consuming errors to resolve.  Here is an example: 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.41 requires requests_mock, which is not installed.
pytoolconfig 1.2.5 requires packaging>=22.0, but you have packaging 21.3 which is incompatible.
jupyter-core 5.3.0 requires pywin32>=300; sys_platform == "win32" and platform_python_implementation != "PyPy", but you have pywin32 227 which is incompatible.
conda-repo-cli 1.0.41 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.41 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
conda-repo-cli 1.0.41 requires PyYAML==6.0, but you have pyyaml 5.4.1 which is incompatible.
conda-repo-cli 1.0.41 requires requests==2.28.1, but you have requests 2.25.1 which is incompatible.
black 0.0 requires packaging>=22.0, but you have packaging 21.3 which is incompatible.

**Comment by arsing** [comment]
I see you already filed https://github.com/Azure/iotedgedev/issues/608

As for the extension, you should file an issue in https://github.com/microsoft/vscode-azure-iot-edge . (I'd transfer it but I seem to be unable to.)
