### ISSUE TITLE
Connect to Azure sql Server from Custom Edge Module .

### ISSUE THREAD

**Issue by vaishnavils97** [Azure/iotedge#7042]
Hi Team, 

We are facing issue while trying to connect to an Azure SQL server from custom module which is running at iotedge. The same have tested outside the edge and that was working fine. The custom  module is giving error while opening a connection towards server using the function <conn.Open();>

Please find the below error. Kindly help to resolve this issue with container based application

BackgroundService failed System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'username'.    at System.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)    at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)    at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)    at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)    at System.Data.SqlClient.SqlConnection.Open()    at sqlfunction.ModuleBackgroundService.ExecuteAsync(CancellationToken cancellationToken) in /app/ModuleBackgroundService.cs:line 46    at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService) C5",

**Comment by david-emakenemi** [comment]
@arunguru-msft please can you have someone from the Azure SQL Server team look into this, as we don't own the SQL Server module.

**Comment by david-emakenemi** [comment]
Hey @vaishnavils97, we don't debug custom modules running on IoT Edge. Also, since we don't own the SQL Server module, I suggest you open an issue with the Azure SQL Server team. They are better equipped to resolve the issue you're facing.

**Comment by david-emakenemi** [comment]
@vaishnavils97 any updates on this? Also, I created a GitHub issue regarding this on the SQL server GitHub page, which you can track here: https://github.com/MicrosoftDocs/sql-docs/issues/9103. Let us know if you have any concerns or questions

**Comment by david-emakenemi** [comment]
@vaishnavils97 any update on this? Also, created a GitHub issue for you on the Azure SQL server GitHub repo, which you can track here: https://github.com/microsoft/sql-server-samples/issues/1174. They should be able to debug your custom module and resolve your issue.

**Comment by varunpuranik** [comment]
Closing this issue, as it is being tracked in the other repo.
