### ISSUE TITLE
Child Device is Not able to Connect with Parent Device.

### ISSUE THREAD

**Issue by NebulaQuasar** [Azure/iotedge#7044]
Hi,
I am trying to setup a Nested-Edge scenario where only the Parent Device will be connected to the IoT-Hub and the Child Device will get the Modules through Parent Device.

But I am getting this error:
----------------------------------
**× parent hostname is resolvable from inside container - Error
    Failed to resolve parent hostname parent
        caused by: Failed to resolve parent hostname parent
        caused by: docker returned exit status: 125, stderr = Unable to find image 'parent/azureiotedge-diagnostics:1.4.10' locally
                   docker: Error response from daemon: pull access denied for parent/azureiotedge-diagnostics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
                   See 'docker run --help'.**
**× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'parent/azureiotedge-diagnostics:1.4.10' locally
    docker: Error response from daemon: pull access denied for parent/azureiotedge-diagnostics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
    See 'docker run --help'.
        caused by: Unable to find image 'parent/azureiotedge-diagnostics:1.4.10' locally
                   docker: Error response from daemon: pull access denied for parent/azureiotedge-diagnostics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
                   See 'docker run --help'.
        caused by: docker returned exit status: 125, stderr = Unable to find image 'parent/azureiotedge-diagnostics:1.4.10' locally
                   docker: Error response from daemon: pull access denied for parent/azureiotedge-diagnostics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
                   See 'docker run --help'.
× container time is close to host time - Error
    Could not query local time inside container
        caused by: Could not query local time inside container
        caused by: docker returned exit status: 125, stderr = Unable to find image 'parent/azureiotedge-diagnostics:1.4.10' locally
                   docker: Error response from daemon: pull access denied for parent/azureiotedge-diagnostics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
                   See 'docker run --help'.**
----------------------------------------------------------------------------------------------------------------------------------------------------------------
I have followed the steps as mentioned in the below link:
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-iot-edge-device?view=iotedge-1.4

I am able to ping one device from another using the Hostname.

Using the command "openssl s_client -connect <parent hostname>:8883 </dev/null 2>&1 >/dev/null"
on the Child Device I am getting the result as expected:
**Can't use SSL_get_servername
depth=3 CN = Azure_IoT_Hub_CA_Cert_Test_Only
verify return:1
depth=2 CN = Azure_IoT_Hub_Intermediate_Cert_Test_Only
verify return:1
depth=1 CN = gateway.ca
verify return:1
depth=0 CN = parent
verify return:1
DONE**

I am using the Raspberrypi Devices with Raspbian OS.

Can anyone suggest the solution to this please.

**Comment by david-emakenemi** [comment]
Hey @NebulaQuasar any updates on this?

**Comment by ryanwinter** [comment]
Hi @NebulaQuasar, we will close this issue for now. If you are still having a problem here, feel free to reopen the item.
