### ISSUE TITLE
edgeHub module failing to start within VM

### ISSUE THREAD

**Issue by dominicloria** [Azure/iotedge#705]
## Steps to Reproduce
1. Within Device VM - Install-SecurityDaemon -Manual -ContainerOs Windows .... 
2. Configure SimulatedTemperatureSensor for deployment in azure
3. edgeHub fails to start with - caused by: failed to create endpoint edgeHub on network azure-iot-edge: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. 

### Device (Host) Operating System
Windows IOT Enterprise 2019

### Architecture
64

### Container Operating System
Windows containers

#### iotedged
1.0.5

#### Edge Agent
1.0.0

#### Edge Hub
1.0.0

#### Docker
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.2
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.11.2
  Git commit:       74baf62
  Built:            Tue Dec  4 20:29:24 2018
  OS/Arch:          windows/amd64
  Experimental:     false

## Logs
10/01/2019 2:04:18 PM info: edgelet_docker::runtime -- Starting module edgeHub...
10/01/2019 2:04:18 PM warn: edgelet_utils::logging -- Could not start module edgeHub
10/01/2019 2:04:18 PM info: edgelet_http::logging -- [mgmt] - - - [2019-01-10 03:04:18.490047200 UTC] "POST /modules/edgeHub/start?api-version=2018-06-28
                      HTTP/1.1" 500 Internal Server Error 276 "-" "-" pid(2416)
10/01/2019 2:04:18 PM warn: edgelet_utils::logging --   caused by: failed to create endpoint edgeHub on network azure-iot-edge: hnsCall failed in Win32: The
                      process cannot access the file because it is being used by another process. (0x20)

**Comment by ancaantochi** [comment]
Please update config.yaml file and set network to 'nat' instead of 'azure-iot-edge'. We will fix in the next release to have by default network to nat on windows.

Thanks!

**Comment by myagley** [comment]
This is fixed in #709

**Comment by myagley** [comment]
Version `1.0.6` was just released yesterday. The install script now defaults the `network` to `nat` in the `config.yaml`.
