### ISSUE TITLE
Microsoft documentation vs Github mismatch 

### ISSUE THREAD

**Issue by fadwalakhal** [Azure/iotedge#7053]
Hello 

I want to report that the letter case of an eflow's environment variable name in microsoft documentation is mismatching the case of the environment variable name here in github.

env name in MS documentation is 'storageFolder'  :
https://learn.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4

but env name in github is 'StorageFolder' :
https://github.com/Azure/iotedge/blob/main/doc/EnvironmentVariables.md

Please can you check and confirm which environment variable is correct  'storageFolder' or 'StorageFolder'.

Thank you 
<img width="889" alt="Screenshot 2023-06-22 at 12 20 30" src="https://github.com/Azure/iotedge/assets/52038416/a25d6f4f-ebce-4f08-a8ce-eaa735110958">
<img width="1226" alt="Screenshot 2023-06-22 at 12 20 57" src="https://github.com/Azure/iotedge/assets/52038416/d79284fb-aed7-48f5-8364-8ac906227a42">

**Comment by ancaantochi** [comment]
Thanks for reporting the issue, they are both working because the configuration provider in C# are case insensitive. I will make a request to update the doc to use StorageFolder so they are consistent.

**Comment by ancaantochi** [comment]
Fixed by https://github.com/MicrosoftDocs/azure-docs-pr/pull/243023
