### ISSUE TITLE
Obtain host's environment variable value during IoT Hub layered deployment

### ISSUE THREAD

**Issue by chatnoir1982** [Azure/iotedge#7056]
We have build a layered deployment for our custom module in IoT Hub through the Azure Portal, that targets a set of Edge devices.

The IoT Edge module we are deploying on those devices requires unique, device-specific values to operate; the values are already set on the target edge device as environment variables.
My understanding is that evaluation of the host's environment variables is not possible at container startup, and was considering using the "**Cmd**"  section under Container Options, however I am not sure how this would work.

**So the question is:** which is the best practice when it comes to dynamically injecting values taken from the edge device's environment variables into the container's respective env vars, at the time IoTHub's deployment touches the edge device/container start-up? 

Thanks.

**Comment by veyalla** [comment]
Please direct Q&A style questions to https://aka.ms/iotedge-qna
