### ISSUE TITLE
Edge Hub is unable to update child device identities on edge devices with a large number of immediate child edge devices.

### ISSUE THREAD

**Issue by Evan-Walden-ATS** [Azure/iotedge#7058]
## Expected Behavior

When a edge device with a large number of children first starts up, it should read and register all of their identities so that they can later connect to the gateway.

## Current Behavior

The device identities are rejected and the error "`No valid authentication chain for <device-id>`" is logged.

```
<7> 2023-06-30 17:36:47.618 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.CloudProxy.NestedDeviceScopeApiClient] - Error getting device scope result from the cloud
System.InvalidOperationException: No valid authentication chain for child5
   at Microsoft.Azure.Devices.Edge.Util.Option`1.Expect[TException](Func`1 exception) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/Option.cs:line 117
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.NestedDeviceScopeApiClient.GetIdentitiesInTargetScopeInternalAsync(Uri uri, Option`1 continuationToken) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/NestedDeviceScopeApiClient.cs:line 203
   at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout, Action action) in /mnt/vss/_work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/TaskEx.cs:line 135
   at Microsoft.Azure.Devices.Edge.Hub.CloudProxy.NestedDeviceScopeApiClient.GetIdentitiesInTargetScopeWithRetry(Uri uri, Option`1 continuationToken) in /mnt/vss/_work/1/s/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/NestedDeviceScopeApiClient.cs:line 149
```

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Create a new IoT Hub in Azure
2. Create a device identity for a transparent gateway edge device. 
3. Create a large number of edge device identities to the IoT Hub with their parent set to the gateway. The exact number required is random, continue at least until the gateway is no longer in the first 10 devices listed in the hub.
4. Attach an actual edge device to the hub using the gateway identity and deploy EdgeHub to that device.
5. Wait for EdgeHub to attempt to update it's identity cache, then examine the logs to see that this has failed.

<img width="1280" alt="2023-06-30 12_38_14-" src="https://github.com/Azure/iotedge/assets/93946708/595cf05b-0bc0-44af-9fdb-b60fe6b2bf45">

### Output of `iotedge check`

<details>
<summary>Click Here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
31 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Ubuntu 20.04
* Architecture: amd64
* Container OS:Linux containers

### Runtime Versions
* aziot-edged: 1.4.10
* Edge Agent: 1.4.14.75317783 
* Edge Hub: 1.4.14.75317783
* Docker/Moby: 20.10.25+azure-2 

## Logs

Edge Hub Logs: [hub_logs.txt](https://github.com/Azure/iotedge/files/11923155/hub_logs.txt)

## Additional Information

I believe that the underlying issue is that [NestedServiceIdentitiesIterator](https://github.com/Azure/iotedge/blob/main/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs#L247) does not guarantee that the identity of the device on which EdgeHub itself is running is in the first batch of identities returned.

I have been able to work around this issue by increasing the batch size specified here: https://github.com/Azure/iotedge/blob/main/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs#L333 to a value larger than the number of child devices.

**Comment by vadim-kovalyov** [comment]
@Evan-Walden-ATS thanks for the detailed explanation and trying to narrow down the issue. We are looking into it and will try to fix it in the future releases.

**Comment by jlian** [comment]
After checking with the team, seems like the size of the fix is quite large. Unfortunately we won't be able to fix this in the near future. If this is impacting you in a business critical matter please let us know and we can reopen. 

Alternatively, @Evan-Walden-ATS would you want to propose a fix on [NestedServiceIdentitiesIterator](https://github.com/Azure/iotedge/blob/main/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs#L247) via a PR?
