### ISSUE TITLE
Missing messages with Offline functionality

### ISSUE THREAD

**Issue by enicky** [Azure/iotedge#706]
Hi,

We're experiencing some issues with the offline capabilities of the IoTEdge. We know that it still is in public preview, but the behavior is kind of strange and the result is that we completely lose messages that should have been sent to the IoTHub

We tried this functionality on several platforms and we seem to get the same behavior every time over and over again. 

## Expected Behavior

When a device is online, it sends the messages from a module towards the IoTHub. When suddenly, due to bad network, the device becomes offline. The IoTEdge runtime stores, and backups those messages in a local storage. When the network connectivity restores, it's able to send messages over to the IoTHub.

When a device is offline, and buffers some messages from the modules, for the IoTHub and that device gets rebooted (or restarts the edgeAgent for some reason), it should be able to resend all buffered messages.
## Current Behavior

At the moment, we lose the messages, that are being buffered when the device is offline, when the device is being rebooted. 
We tried this on a local installation, but also on an Azure VM. 

## Steps to Reproduce

1 .Create Azure Ubuntu VM
2. Install Iot edge 1.0.5 following the by Microsoft provided linux installation steps
3. Connect to iot hub and install sample temp sensor
4. Create Route in iot hub to route messages to a servicebus instance
5. Create a NSG to block all outgoing traffic
6. Restart iot edge hub to disconnect all connections “iotedge restart edgeHub”
7. Clear servicebus queue
8. Wait 5 minutes
9. Restart iot edge agent by execution “sudo docker restart edgeAgent”
10. Wait 5 minutes
11. Enable NSG to allow outgoing traffic
=>> All Messages should appear in servicebus
XX All messages while offline are missing

### Device (Host) Operating System

Ubuntu 18.04.1 LTS
### Architecture

amd64

### Container Operating System

Linux Containers

#### iotedged

1.0.5
#### Edge Agent

1.0
#### Edge Hub

1.0

**Comment by ancaantochi** [comment]
Hi,

Can you please turn on debug logging and provide logs for edgeHub and edgeAgent? Here is the documentation about getting the logs: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#check-container-logs-for-issues

I can reproduce the issue with some messages missing, but not all. Do you add a sequence number or how do you determine which messages are missing?

Thanks,
Anca

**Comment by myagley** [comment]
This was fixed with version `1.0.6` of the Edge Hub, and released yesterday. You can upgrade by setting the image for the Edge Hub to `mcr.microsoft.com/azureiotedge-hub:1.0.6`
