### ISSUE TITLE
Support for Debian 12(bookworm)

### ISSUE THREAD

**Issue by habehabe** [Azure/iotedge#7077]
Hi!

I want to use Debian12(bookworm) on edge device.
Debian 12 is not on the supported OS list, do you have any plans to add it?
Also, when will it be added?

**Comment by jlian** [comment]
We support bullseye whose LTS end date is in 2026. Currently it doesn't look like Debian 12 has a defined LTS support date yet, but presumably it would be after 2026. 

We will support the LTS Debian OS in accordance and overlapping with the overall IoT Edge support lifecycle https://learn.microsoft.com/en-us/lifecycle/products/azure-iot-edge

So, we will probably be able to be more specific about the dates around mid-2024 when there's more info about the upcoming IoT Edge LTS as well as Debian 12. Let me know if you have more questions.

**Comment by Clockwork-Muse** [comment]
@jlian - Part of the problem is that there are some devices which don't have (official) support for an earlier OS.  I have a Raspberry Pi 5, which (officially) supports Debian 12/Bookworm (or the RPi version) and Ubuntu 23.10 .

**Comment by amolinamartinez** [comment]
@jlian , @Clockwork-Muse - Indeed, as of now, Azure IoT Edge is not compatible in any way with the Raspberry Pi 5. It's a great pity, and I'm confident that Microsoft is working on a solution. In the meantime, I plan to use Docker with some additional development as a substitute for Azure IoT Edge on several Raspberry Pi 5 units.
