### ISSUE TITLE
Bad warning message from iotedge config apply

### ISSUE THREAD

**Issue by markrad** [Azure/iotedge#7079]
## Expected Behavior
Warning message is accurate.

## Current Behavior
Message is currently misleading and contains a syntax error in the suggested bash command sequence.

## Steps to Reproduce

1. Bring up an IoT Edge instance with the host name in the config.toml set to host1 (or whatever, the value is not important).
2. Edit the config.toml and change the host name to something else such as host2 (anything as long as it's different).
3. Run the command sudo iotedge config apply. The following message is generated:
```
Command failed: Cannot apply config because the hostname in the config host1 is different from the previous hostname host2. To update the hostname, run the following command which deletes all IoT Edge modules and reapplies the configuration. Or, revert the hostname change in the config.toml file.
                    sudo iotedge system stop && sudo docker rm -f $(sudo docker ps -aq -f "label=net.azure-devices.edge.owner=Microsoft.Azure.Devices.Edge.Agent")) && sudo iotedge config apply.
                Warning: Data stored in the modules is lost when above command is executed.
```
There are two problems with this message. First the host names are transposed. The message implies that one changed the host name from host2 to host1, but the opposite is true. Secondly, in the sample command, there should only be one right parenthesis after the string Microsoft.Azure.Devices.Edge.Agent". If you paste the command into your command prompt, you will see:
```
-bash: syntax error near unexpected token `)'
```
### Output of `iotedge check`
iotedge check is not relevant.
<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS: Ubuntu 22.04
* Architecture: amd64 
* Container OS: Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.16
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4
* Docker/Moby [run `docker version`]: 23.0.6+azure-2

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by nlcamp** [comment]
@markrad Thanks for reporting this. I'll work on a fix.
