### ISSUE TITLE
Edge modules fail to connect to EdgeHub when device is offline

### ISSUE THREAD

**Issue by jakhog** [Azure/iotedge#7084]
## Expected Behavior
ModuleClients should be able to connect and send messages to EdgeHub even though the device is offline.

## Current Behavior
When a ModuleClient attempts to connect to the EdgeHub while the device is offline, it times out because of hardcoded timeouts while it is waiting for __identityd__ to revert to backup identities.

With default settings, we first observe a timeout in EdgeHub caused by the MQTT Connect packet arrival timeout:
https://github.com/Azure/iotedge/blob/87075622955eb7f52818c99cce1c04d84b7a69ed/edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json#L7
If we increase this, we get another timeout caused by the default `HttpClient` timeout (100s) from this client created here
https://github.com/Azure/iotedge/blob/87075622955eb7f52818c99cce1c04d84b7a69ed/edge-util/src/Microsoft.Azure.Devices.Edge.Util/HttpClientHelper.cs#L35
https://github.com/Azure/iotedge/blob/87075622955eb7f52818c99cce1c04d84b7a69ed/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2020_07_07/WorkloadClient.cs#L103

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Have a working IoT Edge device with one module container (connecting to EdgeHub) running.
    * Configure `ConnectArrivalTimeout` to a high value (e.g. 5min)
3. Introduce bad cloud connectivity (100% packet loss). It is important that it still has a route to the internet, otherwise it fails before timing out.
4. Restart the module connecting to EdgeHub.
5. Observe it timing out while attempting to connect.

### Device Information
* Host OS: Clear Linux
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged: 1.4.9
* Edge Agent: 1.4.18
* Edge Hub: 1.4.18
* Docker: 20.10.17

## Logs
I have lost the logs (they have been rotated) but if we have to - we can reproduce them.

## Additional Information
This is technically not a IoT Edge only problem, it is really caused by the combination of timeouts here and in the identity service (see related issue https://github.com/Azure/iot-identity-service/issues/542). But being able to configure the `HttpClient` timeout would help us get around the issue for now - and help us tune the offline behaviour of our setup going forward.

**Comment by ancaantochi** [comment]
Does it reproduce only if you restart multiple modules in the same time? I am trying to understand why it reaches HttpClient timeout since the identityd should timeout at 70secs. 
If you have multiple modules restarting in the same time, aren't they able to connect after a few retries?

**Comment by jakhog** [comment]
The default configuration for identityd is actually 70s x 2 attempts, so 140s in total:
https://github.com/Azure/iot-identity-service/blob/61f903baa4083921d7cee63671829c58b97464f9/aziotctl/config/unix/template.toml#L38-39

But yes, after changing the identityd config to 0 retries, one module would be able to connect. The problem mostly arises when there are multiple modules trying to start up at the same time.

We have some things we need to change in our code to handle retries better - but IMO being able to configure the HttpClient timeout would be nice, and maybe changing the default timeouts so they align with identityd defaults 🙂

**Comment by gordonwang0** [comment]
As discussed in https://github.com/Azure/iot-identity-service/issues/542, we have added the `prefer_module_identity_cache` to use bypass cloud connections for module identity calls. That should help in your case. Please reopen if you have any further questions.
