### ISSUE TITLE
Read serialport on Linux

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#71]
Hi there,

I'm trying to read a serialport from a c# module within IoT Edge. Since Linux doesn't support System.IO.Ports yet, I tried using SerialPortStream.

When I try to list the portnames that are available with `System.IO.Directory.GetFiles("/dev/");`
I only get a bunch of filenames, and not ttyUSB0 (that I need), while if I just list the files in linux from command line, I do see all those files. As if I don't have access to all files from the IoT Edge module.

I also cannot open the '/dev/ttyUSB0' port within a module, but I am able to do this using the command line in linux.

Any ideas?

**Comment by jason-e-gross** [comment]
Is your module dockerfile including the moduleuser creation?  If so, try commenting that part out so your module has root.

I think you might need to set privilege to true on create settings also.

________________________________

**Comment by nhuurnink** [comment]
I removed the moduleuser creation part, but no luck there.

How can I set privilegde on 'create settings'? Not sure what you mean by that.

**Comment by jason-e-gross** [comment]
When you Set Modules in the IOT Hub portal, there's a place where you can add settings - *Container Create Options* 

{
  "HostConfig": {
    "Privileged": true
  }
}



![](https://i.imgur.com/lYMKOIz.png)

**Comment by nhuurnink** [comment]
Well, it works. So that really is great!

I've tried to a moduleUser to 'dialout' group on the device, but the device doesn't recognize that user.
I'm new to Linux, could you point me in the right direction how to do this in the most secure way?

We want to scale this solution to many users, so I need to figure this out for sure.

**Comment by jason-e-gross** [comment]
The moduleuser created in the dockerfile is just set up to have that container run as that user.    It's a relatively new addition to the IOT Edge solution toolkit -- showing up just a bit before GA.    It runs with less permissions than root, obviously -- and to give it the appropriate permissions in the container, you'd have to add those to the dockerfile for setting them.

For now, though - I'd suggest just commenting out moduleuser in the dockerfile, having your host privileges set to true -- and when you get more comfortable with dockerfile commands and options - and linux - you can work on restricting it down.     Start with googling about "dockerfile useradd".

That link regarding the Create Config options -- dive into reading about how to map in devices as part of the HostConfig - if your serial ports will remain the same.

https://docs.docker.com/engine/api/v1.30/#operation/ContainerCreate
https://docker-py.readthedocs.io/en/1.4.0/host-devices/

As well as boning up on ADDUSER, and setting their groups/UIDs and stuff in dockerfile.   You can give the moduleuser the permissions it needs, just need to learn up on how to do it.  There's lots of links out there related to docker, adding users in the dockerfile and assigning them the right groups/perms.  

As you have it now, per my instructions - it's running as a root user, and with privileged=true, it has access to the host -- so it's not a very secure option.     

Glad it worked, good luck with IOT Edge. =)
