### ISSUE TITLE
Fail to unistall iotedge security deamon on Windows after unsuccessful install

### ISSUE THREAD

**Issue by Chubacca73** [Azure/iotedge#710]
## Expected Behavior
iotEdge Security deamon can be installed on Windows 10 for development

## Current Behavior
IoTedgeSecurityDeamon faild to installation due to following error

```
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
 Install-SecurityDaemon -Manual -DeviceConnectionString '<MY_CONN_STRING>'

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IotEdgeSecurityDaemon               {Install-SecurityDaemon, Uninstall-SecurityDaemon}
Docker is running.
The container host is on supported build version 16299.
Downloading IoT Edge security daemon...
Using IoT Edge security daemon from C:\Users\<MY USER>\AppData\Local\Temp\iotedged-windows.zip
Install-SecurityDaemon : Ausnahme beim Aufrufen von "AddAccessRule" mit 1 Argument(en):  "Manche oder alle
Identitätsverweise konnten nicht übersetzt werden."
In Zeile:2 Zeichen:1
+ Install-SecurityDaemon -Manual -DeviceConnectionString 'HostName=oss- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-SecurityDaemon], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException,Install-SecurityDaemon
```

Tried to uninstall the deamon after wards but failing leaving machine in a partially installed state

```
Uninstall-SecurityDaemon
Uninstalling...
Uninstall-SecurityDaemon : Die Eigenschaft "net.azure-devices.edge.owner" wurde für dieses Objekt nicht gefunden.
Vergewissern Sie sich, dass die Eigenschaft vorhanden ist.
In Zeile:1 Zeichen:1
+ Uninstall-SecurityDaemon
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Uninstall-SecurityDaemon], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Uninstall-SecurityDaemon
```

Already looked at work around like removing all running containers but did not improve the situation

## Steps to Reproduce

1. Install IoTEdgeServiceDeamon
2. Hope that it fails the same way as it did on my machine 
3. Try to unistall it

### Device (Host) Operating System
Windows 10 Enterprise V1709 Build 16299.846

### Architecture
x64

### Container Operating System
Linux

#### Docker
18.09.0

**Comment by myagley** [comment]
Hello. This looks like a duplicate of #655 and was fixed in #695. This fix hasn't been released yet but we are planning on a release at the end of this month.

**Comment by ancaantochi** [comment]
Hi, The workaround for uninstall is to remove all containers, including not running containers. That's also going to be fixed in the next release.

**Comment by Chubacca73** [comment]
Thank you for the update. Will follow up once the new release is available.

**Comment by myagley** [comment]
Version `1.0.6` was released yesterday. The new install/uninstall script contains this fix. You can try it out with:

Uninstall IoT Edge:
```powershell
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Uninstall-SecurityDaemon -DeleteConfig -DeleteMobyDataRoot
```
