### ISSUE TITLE
Help: Failed to call systemctl stop

### ISSUE THREAD

**Issue by Ming-Y-ANG** [Azure/iotedge#7109]
I want to run IoTedge on my embedded system, but the system does not support systemd. When running ./iotedge config apply, the following error occurs? Is there any solution(eg. iotedge system sub-commands?)
![image](https://github.com/Azure/iotedge/assets/48575506/b3d03026-4d51-46ba-aac2-c85551b0e55d)

**Comment by brotherneeru** [comment]
Please fill out the issue template found here: https://github.com/Azure/iotedge/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Supported OSes are found here:
https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.4

**Comment by bishal41** [comment]
@Ming-Y-ANG closing this issue, please follow the steps above suggested by @brotherneeru. thanks!
