### ISSUE TITLE
Incorrect edgeAgent_total_time_running_correctly_seconds metric

### ISSUE THREAD

**Issue by tds-captic** [Azure/iotedge#7115]
## Expected Behavior

Following [this guide](https://aka.ms/edgemon-docs) led me to notice a potential bug while developing.
I still had a few modules that were failing:
![Screenshot 2023-09-23 at 23 14 22](https://github.com/Azure/iotedge/assets/118256626/1cd25b00-8ccd-478e-8ea0-a400b7d1b006)

But strangely enough, when looking at the Workbook I saw inconsistent results related to the uptime of these modules:
![Screenshot 2023-09-23 at 23 17 49](https://github.com/Azure/iotedge/assets/118256626/f1889358-7b30-42e0-9a7c-ee23102210d8)

At least a few of these should be close to 0.

This is the output of the `iotedge list` command on the IoT device itself:
![Screenshot 2023-09-23 at 23 22 52](https://github.com/Azure/iotedge/assets/118256626/276c5e2d-3057-4f4d-8d0b-d57b12abfeab)

The logs confirm the fact that 

## Current Behavior

The `edgeAgent_total_time_running_correctly_seconds` is not correct.
It does not reflect the amount of time the module was specified in the deployment and was in the running state.

### Device Information
* Host OS: Ubuntu 18.04
* Architecture: arm64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged: 1.4.10
* Edge Agent: 1.4
* Edge Hub: 1.4 
* Docker/Moby: 20.10.25+azure-2

**Comment by simondegheselle** [comment]
I am facing the same issue 😔

**Comment by yophilav** [comment]
Could you try expose the port 9600 and scrape the metrics per step 1 & 2 from the comment above?  How do those metrics looking?

**Comment by yophilav** [comment]
@tds-captic Did you get a chance to try scrap and look at the edgeAgent metrics ?

**Comment by yophilav** [comment]
Close the issue due to inactivity.
