### ISSUE TITLE
Debian 11/arm64 packages missing from packages.microsoft.com

### ISSUE THREAD

**Issue by stefanb2** [Azure/iotedge#7117]
## Expected Behavior

On a Debian 11/arm64 installation, e.g. Raspi OS Lite 64, after enabling the [production package repository](https://packages.microsoft.com), I should be able to simply execute

~~~sh
# apt-get install aziot-edge
~~~

to install the package during the OS build, just like it works for e.g. `moby-engine`.

The packages for Debian 11/arm64 are built and available in the `azure-iotedge` release download directory (though hidden), f.ex. for [1.4.20](https://github.com/Azure/azure-iotedge/releases/download/1.4.20/aziot-edge_1.4.20-1_debian11_arm64.deb), so I don't quite understand why they aren't automatically pushed to the official package directory like the `armhf` packages.

## Current Behavior
It tries to install `armhf` packages, which drags in a whole plethora of multiarch packages.

Currently I have to add shell code to manually download & install the `.deb` packages from `azure-iotedge` release download directory during the OS build for Debian 11/arm64 platform.

**Comment by vipeller** [comment]
Hi @stefanb2, sorry for the late answer: we upload only Tier 1 images to the repo.

**Comment by david-emakenemi** [comment]
Hi @stefanb2 here's a list of what we support: https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.4#tier-1 & https://github.com/Azure/azure-iotedge/releases
