### ISSUE TITLE
Please provide builds for Debian 12 armhf & arm64

### ISSUE THREAD

**Issue by stefanb2** [Azure/iotedge#7118]
[Raspberry Pi 5](https://www.raspberrypi.com/products/raspberry-pi-5/) is coming soon. Along with its release [Raspi OS](https://github.com/RPi-Distro/pi-gen) will be rebased to Debian 12.

F.ex. [moby-engine](https://packages.microsoft.com/debian/12/prod/pool/main/m/moby-engine/) already supports this platform.

Please provide builds for Debian 12 armhf & arm64 and also push them to the [production package repository](https://packages.microsoft.com).

**Comment by stefanb2** [comment]
To whom it may concern: initial testing shows that Debian 11/arm64 packages install & work fine on Debian 12/arm64.

**Comment by gimmi** [comment]
Please also add support for `arm64` that as of 03-2024 is still missing

**Comment by bishal41** [comment]
@stefanb2 apologies for the late response. We triaged this few months ago and have an item in our backlog for Debian 12 support. We will keep you posted on the progress. 

@gimmi your ask is also for Debian12 amd64 support correct?

**Comment by gimmi** [comment]
Yes, we need `amd64` support.

So far I've managed to have a Debian12 + iotedge working by "backporting" some Debian11 packages and use the IotEdge Debian 11 build as follows:

```sh
wget http://ftp.it.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb -O /tmp/libssl1.1.deb
chmod 777 /tmp/libssl1.1.deb
apt install /tmp/libssl1.1.deb

wget https://github.com/Azure/azure-iotedge/releases/download/1.4.33/aziot-identity-service_1.4.8-1_debian11_amd64.deb -O /tmp/aziot-identity-service.deb
chmod 777 /tmp/aziot-identity-service.deb
apt install /tmp/aziot-identity-service.deb

wget https://github.com/Azure/azure-iotedge/releases/download/1.4.33/aziot-edge_1.4.33-1_debian11_amd64.deb -O /tmp/aziot-edge.deb
chmod 777 /tmp/aziot-edge.deb
apt install /tmp/aziot-edge.deb
```

That works, but is not optimal.

**Comment by gimmi** [comment]
Hello,

iotedge 1.5 LTS has just been released, which dropped support for Debian 10.

Do we have some update on Debian 12 support?

**Comment by ljubisa-dobric** [comment]
Hello all,
I am also interested in Debian 12 or Ubuntu 24.04 support? Is there any plan when this will be released?

**Comment by bishal41** [comment]
Hi, we are targeting end of August 2024 to include Debian 12 support.

**Comment by engineirik** [comment]
> Hi, we are targeting end of August 2024 to include Debian 12 support.

Hi, this is good news. Is the plan still on track? Can we expect it to be available at the end of August 2024?

**Comment by bishal41** [comment]
Barring we don't run into any technical hurdles; we are still targeting to add Debian 12 support by end of August 2024.

**Comment by Muximize** [comment]
Will Ubuntu 24.04 LTS be supported too?

**Comment by zaphod-pab** [comment]
thank you folks for working on this. eagerly awaiting aziot-edge support for ubuntu noble.

**Comment by egil** [comment]
@bishal41 are the end of August 2024 still looking good?

We have a few PI 5 devices that do not play nice with Ubuntu 22.04 so it would be extremely helpful to us :)

**Comment by wbunthof** [comment]
Another up for Debian 12 AMD64.
Want to use it in WSL, and all our edge devices are going to be migrated to Debian 12.

**Comment by zaphod-pab** [comment]
> @bishal41 are the end of August 2024 still looking good?
> 
> We have a few PI 5 devices that do not play nice with Ubuntu 22.04 so it would be extremely helpful to us :)

I am in the exact same situation. Our RPi5 devices are running on 23.10 (using the 22.04 iotedge packages) and we'd love to get to a clean setup with LTS

**Comment by egil** [comment]
@zaphod-pab are you able to share a guide on getting 23.10 (or 24.04) running on a RPi5? We are fighting with it and not winning right now :)

**Comment by zaphod-pab** [comment]
> @zaphod-pab are you able to share a guide on getting 23.10 (or 24.04) running on a RPi5? We are fighting with it and not winning right now :)

nothing really fancy, I'm afraid. we're using
- 23.10 server image
- docker engine provided by "moby-engine" package
- aziot-edge package from this deb repository: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb

not sure if any of this helps ... I'm afraid I can't share much more detail as I am no expert in how to set up the azure side of things

**Comment by bishal41** [comment]
Hi, both Debian 12 and Ubuntu 24.04 release are in progress, it's week to week at this point. Below are the PRs where you can monitor the progress.

- https://github.com/Azure/iotedge/pull/7276
- https://github.com/Azure/iot-identity-service/pull/625

**Comment by gimmi** [comment]
Nice! will test in the newxt few days.

**Comment by zaphod-pab** [comment]
Thank you for the great work!

**Comment by engineirik** [comment]
Awesome! Thanks!

**Comment by richardNieuwlandAlten** [comment]
@bishal41 , tnx a lot. But i'm not sure how to install this version, when i follow the 'normal edge install'  i get an E: unable to locate package aziot-edge.  In the documentation for installing specific version (https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.5&tabs=azure-portal%2Cubuntu#offline-or-specific-version-installation-optional) it's stating: Find the aziot-identity-service file that matches your IoT Edge device's architecture. Right-click on the file link and copy the link address. But where an i find this ?

**Comment by martin-stangel** [comment]
Unfortunatelly, it seems that currently only armhf architecture is supported for Debian 12. arm64 is not yet and Raspberry needs arm64. You can check:

- https://packages.microsoft.com/debian/12/prod/dists/bookworm/main/binary-armhf/Packages
- https://packages.microsoft.com/debian/12/prod/dists/bookworm/main/binary-arm64/Packages

The 1st one contains aziot-edge, the 2nd one does not. 

@bishal41 Could you please comment on availability of debian package for arm64 architecture? Thanks a lot!

**Comment by bishal41** [comment]
@martin-stangel all supported platforms, and the architecture support are listed here --> https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.5

Anything beyond what is not listed in the link above is not in the scope.

**Comment by gimmi** [comment]
`amd64` build are not available in the Microsoft package repository for Debian 12, however you can download it from [release page](https://github.com/Azure/azure-iotedge/releases) and install like in the following example:

```sh
wget https://github.com/Azure/azure-iotedge/releases/download/1.5.10/aziot-identity-service_1.5.3-1_debian12_amd64.deb -O /tmp/aziot-identity-service.deb
chmod 777 /tmp/aziot-identity-service.deb
sudo apt install /tmp/aziot-identity-service.deb

wget https://github.com/Azure/azure-iotedge/releases/download/1.5.10/aziot-edge_1.5.10-1_debian12_amd64.deb -O /tmp/aziot-edge.deb
chmod 777 /tmp/aziot-edge.deb
sudo apt install /tmp/aziot-edge.deb
```

**Comment by Clockwork-Muse** [comment]
.... Raspberry Pi4 and later only come in Armv8/Arm64 and the default distro is Debian-based, so essentially the Tier 1 support is only for Pi3 and before.  Presumably many other devices are also going to be migrating to Arm64 as well (and/or RISC V, but that's a bit future).

**Comment by martin-stangel** [comment]
@gimmi Thanks a lot! This will work for me. 

Unfortunately, [the official tutorial from Microsoft](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-x509?view=iotedge-1.5&tabs=azure-portal%2Cdebian#install-iot-edge) mentions only installation via apt-get install from packages-microsoft-prod.deb, so I didn't know I am supposed to download the deb files manually. 

Perhaps, the tutorial could be updated by Microsoft.

**Comment by stefanb2** [comment]
> @martin-stangel all supported platforms, and the architecture support are listed here --> https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.5
> 
> Anything beyond what is not listed in the link above is not in the scope.

To quote from this page:

> **Tier 2**
>
> The systems listed in the following table are considered compatible with Azure IoT Edge, but aren't actively tested or maintained by Microsoft.
>
> _Important_
>
> Support for these systems is best effort and may require you reproduce the issue on a tier 1 supported system.

What I **DO NOT** see in that policy:

* we do not generate and release artifacts on GitHub for Tier 2 platforms.
* we do not push release artifacts from GitHub to the package repository for Tier 2 platforms.

Why is then that the only packages missing for an Azure IoT Edge installation on a Tier 2 platform from the package repository, are `azure-edge` & `azure-identity-service`?


Instead of repeating the same Tier 2 nonsense every time this topic is raised, the Azure IoT Edge project should choose between

* remove all Tier 2 platform packages from the package repository, f.ex. `moby-egnine`, or
* remove the manual filter for Tier 2 platforms from the release script for  `azure-edge` & `azure-identity-service`

Do **one**, but not both, and stop confusing people.

**Comment by patheikkinen** [comment]
> Instead of repeating the same Tier 2 nonsense every time this topic is raised, the Azure IoT Edge project should choose between
> 
>     * remove all Tier 2 platform packages from the package repository, f.ex. `moby-egnine`, or
> 
>     * remove the manual filter for Tier 2 platforms from the release script for  `azure-edge` & `azure-identity-service`
> 
> 
> Do **one**, but not both, and stop confusing people.

My vote would go for the second option (in the hypothetical case that anyone asked :) ).

**Comment by damonbarry** [comment]
@martin-stangel We can look into promoting Debian 12 amd64 and aarch64 to Tier 1 and publishing the deb files to packages.microsoft.com. We already have most of what we need to do that.

@stefanb2 I think part of the confusion here is that `moby-engine` is not part of the IoT Edge product. We take a dependency on it, but it's published and serviced by an entirely different team on its own schedule and with its own support policies.

You said:
> Why is then that the only packages missing for an Azure IoT Edge installation on a Tier 2 platform from the package repository, are `aziot-edge` & `aziot-identity-service`?

...but the thing is, `aziot-edge` and `aziot-identity-service` are the _only_ two packages that comprise IoT Edge.

**Comment by stefanb2** [comment]
@damonbarry 

> @martin-stangel We can look into promoting Debian 12 amd64 and aarch64 to Tier 1 and publishing the deb files to packages.microsoft.com. We already have most of what we need to do that.

Nobody has requested that. This view is only supported when interpreting something into the policy ("we do not push to package repository for Tier 2") what the documented Azure IoT Edge policy doesn't say.

> @stefanb2 I think part of the confusion here is that `moby-engine` is not part of the IoT Edge product. We take a dependency on it, but it's published and serviced by an entirely different team on its own schedule and with its own support policies.

This argument is based on company internals, not something that is written in the Azure IoT Edge documentation.

> ...but the thing is, `aziot-edge` and `aziot-identity-service` are the _only_ two packages that comprise IoT Edge.

A distinction that a customer doesn't get when reading the official Azure IoT Edge documentation. Without Azure IoT Edge a customer wouldn't consider to install Moby artifacts from the Microsoft package repository.

**Comment by martin-stangel** [comment]
> @martin-stangel We can look into promoting Debian 12 amd64 and aarch64 to Tier 1 and publishing the deb files to packages.microsoft.com. We already have most of what we need to do that.

@damonbarry That would make life for me easier. Thank you. 

However, I would still suggest to update also documentation.
[This block of documentation](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-1.5&tabs=azure-portal%2Cdebian#install-iot-edge) doesn't mention downloading deb files manually from release page at all. 

On top of that, the topmost release at [release page](https://github.com/azure/azure-iotedge/releases) currently contains only source code. So every time I looked there I didn't see deb files there (which are only stored for the penultimate release)

**Comment by damonbarry** [comment]
@martin-stangel @stefanb2 I agree that the documentation can be clarified, both in terms of policy and implementation; we'll work on that. We can also update the language on the release pages in GitHub to be more precise about the _component_ versions that map to a given _product_ version, and where you can find the corresponding bits.

**Comment by bishal41** [comment]
Hey folks - we took the feedback and updated the docs. Debian 12 is also now listed as Tier 1 supported OS platform for all architectures. Thanks!

**Comment by stefanb2** [comment]
It seems that a certain place has frozen over.

> Hey folks - we took the feedback and updated the docs. Debian 12 is also now listed as Tier 1 supported OS platform for all architectures. Thanks!

@bishal41 Thanks. Finally I can remove all special installation code from the pi-gen scripts...
