### ISSUE TITLE
Behavior of iotedge when there is no Internet connection

### ISSUE THREAD

**Issue by kinugasa-k** [Azure/iotedge#7122]
Hi, Please let me know if the following is possible.

The server is deployed with edgeAgent, edgeHub and several custom modules.
Internet connection is normal.
In this state, the server can be restarted (power off/on) and it will still operate normally.

In this state, even if the Internet is disabled.
server will operate normally.

Above condition,
(Internet is not available, but the server is working properly)
Here, if the server is rebooted (powered off/on), should iotedge work correctly?
*If iotedge is restarted with no internet, will it work correctly?

**Comment by gordonwang0** [comment]
iotedge does have an offline mode. See the documentation here:

https://learn.microsoft.com/en-us/azure/iot-edge/offline-capabilities?view=iotedge-1.4

**Comment by kinugasa-k** [comment]
Thank you!
