### ISSUE TITLE
Iot Edge error configuration has correct URIs for daemon mgmt endpoint - Error     SocketError - SocketErrorCode (TimedOut) : Operation timed out

### ISSUE THREAD

**Issue by danudeep90** [Azure/iotedge#7128]
I am trying to deploy custom docker images via Azure Portal. I provided all the registry details and docker image information, but i see that there is some issue with EdgeAgent downloading docker images. On inspecting the logs i can see the message below

![image](https://github.com/Azure/iotedge/assets/10043245/2fb29f54-32c2-4117-944b-65351ffa9ec9)

Also, on running the command `sudo iotedge check --verbose` i see an error as shown below
![image](https://github.com/Azure/iotedge/assets/10043245/6aa84939-473f-4360-83c7-26759191c899)

The error message is 
configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out

**Comment by gauravIoTEdge** [comment]
@danudeep90 -  The key is invalid. Deleting it and trying again would be a simple way to proceed. Could you give that a shot please?

**Comment by danudeep90** [comment]
@gauravIoTEdge : I am using symmetric key for authentication. Tried with a new key as well it doesnt work

**Comment by gauravIoTEdge** [comment]
Please provide detailed repro steps. We need to know exactly what you did to be able to help you and to point out if something may have been missed or done differently.

**Comment by gauravIoTEdge** [comment]
@danudeep90 - We typically see this error when the hostname has been changed, but that may not be the only reason.

But we can't help you without repro steps. I understand it's not working for you. That's different from it not working at all.

**Comment by gauravIoTEdge** [comment]
@scout208 - Please file a new issue with logs and repro steps (or at least an indication of what changed). Help us help you.
