### ISSUE TITLE
Access to iothub connection string dynamically from custom iot edge module.

### ISSUE THREAD

**Issue by malavvakharia** [Azure/iotedge#7137]
## Expected Behavior
Tell us what should happen

## Current Behavior
Tell us what happens instead of the expected behavior

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.
2.
3.
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by malavvakharia** [comment]
Just like we can get the deviceId and moduleId dynamically can we get the device connection string?

https://github.com/Azure/iotedge/issues/986

IOTEDGE_DEVICEID
IOTEDGE_MODULEID

**Comment by ggjjj** [comment]
do you want to get the connection string in the module?

**Comment by malavvakharia** [comment]
> do you want to get the connection string in the module?

Hello @ggjjj ,

I want the IOT hub connection string in custom azure module. Not the module connection string.

**Comment by ggjjj** [comment]
You can build it yourself by quering the values of `IOTEDGE_IOTHUBHOST` and `IOTEDGE_DEVICEID` from the env var. 

**connection_string = f"HostName={iot_hub_hostname};DeviceId={device_id};SharedAccessKey=<Your Shared Access Key>"**

**Comment by malavvakharia** [comment]
Hello @ggjjj ,

So, what is the best practice of defining the SharedAccessKey in code?

And I want **iot hub connection string** not the device connection string.

Format looks like below:
connection_string = f"HostName={iot_hub_hostname};SharedAccessKeyName=;SharedAccessKey="

**Comment by ggjjj** [comment]
You can set an env variable by setting the output of `az iot hub connection-string show` and use that in your module to read from

Command Link source - https://learn.microsoft.com/en-us/cli/azure/iot/hub/connection-string?view=azure-cli-latest

**Comment by david-emakenemi** [comment]
Hey @malavvakharia did you try @ggjjj suggestion above?
