### ISSUE TITLE
IoT Edge Local Routing Fails to Resume Post-Network Reconnection

### ISSUE THREAD

**Issue by rabergerik** [Azure/iotedge#7140]
## Expected Behavior
In the event of network disruptions, all data flows within the IoT Edge system should automatically resume upon reconnection, without requiring a system restart. Specifically, for our current setup with four custom modules:
1. Two modules collect data via TCP connections.
2. The collected data is sent to a third module for processing.
3. The processed data is then routed (from different outputs) both to the cloud (IoT Hub) and to a fourth module, which is responsible for pushing data via a HTTP connection (in the local network).

The system should ensure that both the cloud uplink and the local HTTP data push are consistently maintained post any network reconnection.

## Current Behavior
When the IoT Edge device experiences a loss and subsequent restoration of network connectivity, the cloud uplink communication with the IoT Hub is restored automatically. However, the local route for pushing processed data to the fourth module (local display) fails to re-establish. Logging in that module suggests that no data is received / routed to this module. The failure is not in the http requests, and the state of the module is "running". This failure results in the customers local displays are not updating with the latest data, which is critical for on-site monitoring and operations. Attempts to manually restart the edgeHub and the HTTP data push module do not resolve the issue, indicating a potential problem with the routing mechanism's state or configuration that persists beyond module restarts. The only successful workaround so far is a complete restart of the IoT Edge runtime (sudo iotedge system restart), which is not a sustainable solution for production environments due to the downtime and manual intervention required.

This setup relies on the assumption that all routes are robust against transient network issues, and the observed behavior deviates from this expectation, leading to operational challenges.

## Steps to Reproduce
1. Setup IoT Edge with 4 custom modules as described.
2. Disconnect network connectivity to simulate an outage.
3. Restore network connectivity.
4. Observe that the cloud data push resumes, but the local HTTP data push does not.

## Context (Environment)
The EdgeHub and EdgeAgent included in the EFLOW installation bundle (AzureIoTEdge_LTS_1.4.9.10083_X64). 

## Additional Information
The failure of local routes to re-establish post-network reconnection is not consistent, making the issue difficult to predict and diagnose. It is currently hard to determine the frequency or conditions under which the problem occurs.

**Comment by david-emakenemi** [comment]
@lfitchett any ideas?

**Comment by jlian** [comment]
@rabergerik can you elaborate a bit on the local HTTP push aspect? Any logs you can share?

**Comment by jlian** [comment]
@rabergerik checking in one more time

**Comment by jlian** [comment]
Closing this for now, we can reopen if we get more detail
