### ISSUE TITLE
IoT Edge not connecting to Hub and giving container name name does not resolve error

### ISSUE THREAD

**Issue by IoTEdgeUser** [Azure/iotedge#7149]
We have deployed IOT Edge on an on-premise system and are connecting to Azure IoT Hub from it via Site to Site VPN. Outbound ports 443 and 5671 are enabled via site to site vpn for IoT Hub and 443 is enable for container registry. As the system does not have internet we have installed iotedge via packages and copied tar files of Edge Agent, Edge Hub from Microsoft container registry. On executing docker load command for these tar files, all the docker images are getting created for these modules. However no containers for them are created in docker ps -a. Only Edge Agent is up but with error Name does not resolve. . On running IoTEdge check we get error that the containers cannot resolve to the host name. However host connectivity works fine. We have added host entry in etc/hosts for the FQDN and IP and also tried adding extra hosts in the IoT Edge deployment template json to deploy to device.  We tried to add hostname explicitly to the docker by using docker run add host for the Edge Agent and Hub but they are giving null exceptions. Kindly suggest how to resolve this issue so that container issue gets resolved

**Comment by vadim-kovalyov** [comment]
It seems like there is an internal support case for that. We will use that support channel for communication and I will post the findings back here if they would be found useful for the public.

**Comment by jlian** [comment]
After correlating with internal support ticket looks like the issue was with the on-prem DNS server resolving IoT Hub FQDN, so this I'm closing the issue.
