### ISSUE TITLE
Azure IOT hub edge agent metrics not sending metrics related to memory usage by the module when using raspberry Pi.

### ISSUE THREAD

**Issue by thechromosomes** [Azure/iotedge#7159]
## Expected Behavior
Azure IOT hub edge agent metrics should send metrics related to memory usage by the module

## Current Behavior
Azure IOT hub edge agent metrics not sending metrics related to memory usage by the module

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. deploy edge runtime on **_Raspberry Pi Bullseye_** 
2. expose the edge agent metrics
3. check **_edgeAgent_used_memory_bytes_** 

<details>
<summary>Click here</summary>

```

![image](https://github.com/Azure/iotedge/assets/48309910/23661341-3bcf-470a-8bc2-c31d90ff1ccc)


```
</details>

### Device Information
* Host OS Raspberry Pi Bullseye  : 
* Architecture linux/arm: 
* Container OS Raspberry PI Bullseye: 

### Runtime Versions
* aziot-edged 1.4.10: 
* Edge Agent 1.1: 
* Edge Hub 1.1: 
* Docker/Moby 20.10.25+azure-1: 

## Additional Information
REF: https://learn.microsoft.com/en-us/answers/questions/1424158/azure-iot-hub-edge-agent-metrics-not-sending-metri

**Comment by nyanzebra** [comment]
@thechromosomes, so just to understand fully, if you run `iotedge list` from both devices you have same modules running and from grafana you are using `edgeAgent_used_memory_bytes` for the metric? If so, would you mind providing debug logs for edgeAgent on the pi device?

**Comment by jlian** [comment]
@thechromosomes any updates

**Comment by jlian** [comment]
Closing for now. We can reopen when we get the logs
