### ISSUE TITLE
Azure IoT Edge 1.4 fails to start on boot - mgmt.sock is created as a directory

### ISSUE THREAD

**Issue by dme-development** [Azure/iotedge#7172]
We are trying to install Azure IoT edge 1.4 on our IoT devices which run Ubuntu 18.04. The installation went fine, following the official documentation. EdgeAgent was running and we could deploy our custom modules.

However, after every reboot, Azure IoT isn't starting up. We see that the /var/run/iotedge folder gets removed and the mgmt.sock inside is created again as a directory.
![image](https://github.com/Azure/iotedge/assets/38321985/f1ae82e1-d2d1-47f3-a0d0-9e5ca1a05a40)

When we manually remove the directory and restart iotedge, everything seems to be running normal again.

Can you think of any reason why the mgmt.sock gets created as a directory?

## Context (Environment)
Ubuntu 18.04
Jetson Nano
IoT Edge 1.4

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

iotedge check

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ aziot-identity-service package is up-to-date - Warning
    Installed aziot-identity-service package has version 1.4.5 but 1.4.6 is the latest stable version available.
    Please see https://aka.ms/aziot-update-runtime for update instructions.
√ host time is close to reference time - OK
√ production readiness: identity certificates expiry - OK
√ preloaded certificates are valid - OK
× keyd is running - Error
    Could not connect to keyd on unix:///run/aziot/keyd.sock
× certd is running - Error
    Could not connect to certd on unix:///run/aziot/certd.sock
× identityd is running - Error
    Could not connect to identityd on unix:///run/aziot/identityd.sock

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (ConnectionRefused) : Connection refused /var/run/iotedge/mgmt.sock
    One or more errors occurred. (Got bad response: )
‼ aziot-edge package is up-to-date - Warning
    Installed IoT Edge daemon has version 1.4.16 but 1.4.20 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
18 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
4 check(s) raised errors. Re-run with --verbose for more details.
11 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
Jetson Nano
* Host OS: Ubuntu 18.04 
* Architecture: arm64 
* Container OS: Linux containers 

### Runtime Versions
* aziot-edged: iotedge 1.4.16
* Edge Agent: not running
* Edge Hub: not running
* Docker/Moby:  23.0.7+azure-1
 

## Logs

<details>
<summary>aziot-edged status</summary>

```

iotedge system status
System services:
    aziot-edged             Ready
    aziot-identityd         Ready
    aziot-keyd              Ready
    aziot-certd             Ready
    aziot-tpmd              Ready

```
</details>

iotedge system logs are empty...

**Comment by arsing** [comment]
Any time a Docker container is started with a volume mount and the mounted path doesn't already exist, dockerd creates it as a directory.

The management socket file gets created by systemd when the `aziot-edge.mgmt.socket` unit is started. On package install, the unit is `enable`d but not `start`ed, since it doesn't make sense to start it until the user has configured IoT Edge first using `iotedge config apply`.

Two containers start with a volume mount of the management socket - Edge Agent and the test container used by `iotedge check`.

So putting it all together, if you just installed the package and immediately run `iotedge check`, the management socket path will get created as a directory.

**Comment by arsing** [comment]
(Sent too soon.)

... Alternatively, if you do something to start the Edge Agent container automatically instead of letting edged do it, then the container might start before the socket unit is started, so again the socket path will get created as a directory.

**Comment by arsing** [comment]
`aziot-mgmt.socket` is `PartOf=aziot-edged.service`, so it'll be started when `aziot-edged.service` is started.

**Comment by dme-development** [comment]
As soon as I run "iotedge check", the mgmt.sock gets re-created as a directory.

**Comment by jlian** [comment]
@arsing is this a bug on our side? Is there a workaround?

**Comment by arsing** [comment]
>As soon as I run "iotedge check", the mgmt.sock gets re-created as a directory.

Yes, as I already explained in https://github.com/Azure/iotedge/issues/7172#issuecomment-1846611655

---

>is this a bug on our side?

We could make `iotedge check` pre-emptively fail the `mgmt.sock` test if the socket doesn't already exist, instead of deploying the test container which would cause it to be created as a directory.

>Is there a workaround?

The workaround is to not do any of the things that cause it to be created as a directory, as I mentioned in my first two comments. That is, don't run `iotedge check` before starting `edged`, and don't start any containers that bind `mgmt.sock` (like Edge Agent) until `edged` starts them.

**Comment by dme-development** [comment]
After doing some more investigation, the root cause is we are using overlay mounts on /lib directory. The edged service is started before the mounts are in place and cannot start properly. 

This explains the behavior and why it works with some manual interference. After removing the overlay mount on /lib everything worked as expected.
