### ISSUE TITLE
Cloud to device connection string in IoT Edge device

### ISSUE THREAD

**Issue by ralarcon** [Azure/iotedge#719]
Hi,

Related to #205, I'm looking for guidance opening a device client connection from an IoT Edge Device. I would like to take use C2D communication with my iot edge modules but taking adavantage of the IoT Hub Jobs to be able to create a job targeting multiple IoT Edge devices. 

Since Jobs can only be created by using a DeviceClient connection and only targets Device direct methods, I will require the IoT Hub Device Connection String.

By the way, it would be great if the DeviceClient would create a connection to IoT Hub device in the same way the ModuleClient do it: ModuleClient.CreateFromEnvironmentAsync(settings).

Thanks in advance.

**Comment by avranju** [comment]
The device connection string will be basically the same as the device connection string that you get from the Azure portal except that we add an additional parameter called `GatewayHostName` to the connection string. This is documented here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device.

As for having an API like `ModuleClient.CreateFromEnvironmentAsync` for device connection strings, that may not be possible since, in case of modules, the edge runtime sets up the environment properly in order for this API to work. In case of leaf devices, the edge runtime doesn't really have any way of influencing its environment.

**Comment by ralarcon** [comment]
As per the issue #205, it is not a good practice to store the device connection string. I'm looking for guidance and recommendations to avoid to store the secret at the module level. I need to setup a device direct method in the edge device.

In other words, what is the proper way to create a DevceClient connection from an azure iot edge device

**Comment by ralarcon** [comment]
I'm currently retrieving the device connection string directly from the IoT Edge runtime configuration (config.yaml) as workaround mentioned in #205 and it looks it works fine. Wonder to know how to deal with this when using certificates & DPS... 

I miss some guidance on security best practices.

**Comment by myagley** [comment]
You should be able to target modules running on an IoT Edge device using a direct method job. The job would be configured like normal and the "query condition" would look something like the following:

`FROM devices.modules WHERE ModuleId = 'custom-module'`

A more complete example of the HTTP request:

```http
PUT /jobs/v2/<jobId>?api-version=2018-06-30

Authorization: <config.sharedAccessSignature>
Content-Type: application/json; charset=utf-8
Request-Id: <guid>
User-Agent: <sdk-name>/<sdk-version>

{
    "jobId": "<jobId>",
    "type": "scheduleDirectMethod",
    "cloudToDeviceMethod": {
        "methodName": "methodName",
        "payload": "payload",
        "responseTimeoutInSeconds": "methodTimeoutInSeconds"
    },
    "queryCondition": "FROM devices.modules WHERE ModuleId = 'moduleid'",
    "startTime": "jobStartTime",
    "maxExecutionTimeInSeconds": "maxExecutionTimeInSeconds"
}
```

You will need to fill in the appropriate info for the method, following the docs here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-jobs#jobs-to-execute-direct-methods

**Comment by ralarcon** [comment]
Yes that World properly, but in the device side, to register the direct method, where I can find the connection staging?


Un saludo,
Raul.

________________________________

**Comment by varunpuranik** [comment]
You can register a callback for direct methods from your module in the same way that you would for a device. So you can have code like this in your module, to register for the callback ReceiveMethodCallback on some method -

```
ModuleClient moduleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
await moduleClient.SetMethodHandlerAsync(methodName, ReceiveMethodCallback, context);
```

**Comment by ralarcon** [comment]
Bit this methods cannot be invoked thru a Job, at least, I didn't succeded trying to.


Un saludo,
Raul.

________________________________

**Comment by avranju** [comment]
Turns out, the query condition that @myagley gave above does work. Here's some sample C# service code that does this:
```csharp
var client = JobClient.CreateFromConnectionString(CONNECTION_STRING);
var method = new CloudToDeviceMethod(METHOD_NAME);
method.SetPayloadJson(PAYLOAD_JSON);
var result = await client.ScheduleDeviceMethodAsync(
    Guid.NewGuid().ToString(),
    $"FROM devices.modules WHERE ModuleId = '{MODULE_ID}'", method, DateTime.Now, 10);
```

**Comment by ralarcon** [comment]
Thanks @avranju, probably I missing something but, if not wrong, you are requesting a **device** method, then for the Edge Device to register a device method I need a device connection, created using a DeviceClient object, so I need the device connection string accesible in the device side. The code you are sending is to request the method execution. I need the edge device side.

**Comment by myagley** [comment]
@varunpuranik showed the device side code above. You can use that code on the device to set up the direct method receiver:

> You can register a callback for direct methods from your module in the same way that you would for a device. So you can have code like this in your module, to register for the callback ReceiveMethodCallback on some method -
>```csharp
> ModuleClient moduleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
> await moduleClient.SetMethodHandlerAsync(methodName, ReceiveMethodCallback, context);
> ```

The code that @avranju listed is called on the service side to set up the job. The names in the service side code are unfortunately a little misleading. They are in fact targeting a direct method call on a module even though the word `Device` is in the name.

**Comment by ralarcon** [comment]
Thanks @myagley, I will try this and see if using the query FROM devices.modules WHERE ModuleId = '{MODULE_ID}'" will allow the modules to receive the method invocations. I'll let you know the result.

**Comment by myagley** [comment]
Is there any update here?

**Comment by ralarcon** [comment]
Sorry, we have been focused in other priorities. I hope to be able to test it out by the end of the week.

**Comment by ralarcon** [comment]
Hi all, 

It worked fine, the "FROM devices.modules" did the trick. 

Thanks.

**Comment by myagley** [comment]
Closing this as it looks like it has been resolved.
