### ISSUE TITLE
Layered deployment returns only layered desired properties. Not idempotent?

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/iotedge#7199]
## Expected Behavior
When a layered deployment including module desired properties is cloned and deployed, for a device that has custom desired properties for that same module, a merge of both desired properties should be sent to the device.

Note: custom desired properties and layered desired properties are sitting next to each other, no overwrite situation due to reused properties (as seen [here](https://learn.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring?view=iotedge-1.4#module-twin-configuration)).

## Current Behavior
When a layered deployment including module desired properties is cloned and deployed, for a device that has custom desired properties for that same module, ONLY THE LAYERED desired properties are sent to the device.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Start a new IoT Hub, create a new 1.4 runtime edge device, and register the device
2. Add a custom module that listens to desired properties
3. See that the module is deployed and running on the edge
4. Create a layered deployment for that module. Include a layered desired property like "properties.desired.deployment: {"value": 42}"
5. Deploy the layered deployment
6. See the layered desired property is arriving -> OK
7. Create a desired property for that module like  "properties.desired.extra: {"value": 43}"
8. See both the 'extra' and the 'deployment' desired properties arrive in one go at the edge -> OK
9. make a clone of the layer with a higher version and priority. Change the deployment property. Deploy the cloned layer
10. See that only the 'deployment' desired properties arrive at the edge -> NON EXPECTED

## Context (Environment)

Both seen on Azure VM and at customer production (VM).

### Output of `iotedge check`

not available

### Device Information
* Host OS: Ubuntu 20.04LTS 
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]:  1.4.29
* Edge Agent [image tag (e.g. 1.0.0)]:  1.4.29
* Edge Hub [image tag (e.g. 1.0.0)]:  1.4.29
* Docker/Moby [run `docker version`]: ??

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

--

## Additional Information

--

**Comment by jlian** [comment]
@vipeller (on-call) would you mind checking on this? I think we might have docs and/or related issue on this. Would be IoT Hub side behavior I think.

**Comment by vipeller** [comment]
@sandervandevelde @jlian The merging of the layers is done by IoT Hub, let me locate a person who can take care of this in that team

**Comment by jlian** [comment]
@vipeller any progress?

**Comment by jlian** [comment]
@vipeller any updates?

**Comment by vipeller** [comment]
@jlian @sandervandevelde I've pinged IoT Hub Gateway team and posted on their channel, but they did not pick it up. I suggest to file a ticket at their team, that will be at higher priority, and they cannot ignore.

@jlian maybe you can pint to the site where to file the ticket.

**Comment by bishal41** [comment]
@sandervandevelde closing this GH issue, feel free to re-open if you have any further questions. Thanks!
