### ISSUE TITLE
Desired property updates not seen by device app

### ISSUE THREAD

**Issue by vbadri** [Azure/iotedge#72]
I deployed .NET and python modules on two edge hub devices. At first, the modules worked as expected -- when I made updates to desired properties on the azure portal, they would be seen by the edge apps. 

However, as I was developing and debugging some functionality, this stopped working. The device apps always "see" an older version of the module twin. 

When I created new versions of these modules (by simply copying the code over), I get normal functionality again. This was observed for both .NET and python modules. 

Details:
Ubuntu 16.04
amd64
Linux containers

Example:
See an example below. The desired TemperatureThreshold was set to 28 at  15:23 GMT. However, even at 15:42 GMT, the device still reads the older value of 29 (I have verified that this is not just due to erroneous updates of reported properties. The edge app is in fact reading an older version of the module twin).

"properties": { 
"desired": { 
"TemperatureThreshold": 28, 
"$metadata": { 
"$lastUpdated": "2018-07-24T15:23:23.7053839Z", 
"$lastUpdatedVersion": 4, 
"TemperatureThreshold": { 
"$lastUpdated": "2018-07-24T15:23:23.7053839Z", 
"$lastUpdatedVersion": 4 
}, 
}, 
"$version": 4 
}, 
"reported": { 
"TemperatureThreshold": 29, 
"DateTimeLastAppLaunch": "2018-07-24T15:42:08.9362554Z", 
"$metadata": { 
"$lastUpdated": "2018-07-24T15:42:08.9873934Z", 
"TemperatureThreshold": { 
"$lastUpdated": "2018-07-24T15:42:08.9873934Z" 
}, 
}, 
"$version": 7 
}

**Comment by varunpuranik** [comment]
Thanks for reporting the issue @vbadri 
We have not seen this issue before.. but we will investigate what might be going on.
A few questions -
- Was your device connected the whole time? Or did you have intermittent connectivity?
- Can you share the EdgeHub logs for this period (that might tell us what might be going on).
- Just to confirm - the reported properties echo what the device read in desired properties, right?

**Comment by vbadri** [comment]
@varunpuranik, thanks for the follow-up. 

1. Far as I know, the device was connected throughout.  Also, to be clear, I saw the same problem from another hub device as well, so it looks like the problem is in the backend.  Happy to share details of the container and the modules if you tell me what's needed. 

2. Edgehub logs are below..
[edgeHubLogs.txt](https://github.com/Azure/iotedge/files/2229082/edgeHubLogs.txt)

3. Yes. Confirmed. The device does read outdated values of desired properties

**Comment by varunpuranik** [comment]
Thanks for the logs. I can't see any errors there, so doesn't look like something is going wrong. Also, in the logs there seem to be several modules... which one had this issue?

Have you tested your module logic with IoTHub? Does that work?
Will you be willing to share the code containing the logic in your module that deals with the Twin updates? 

You mention that "at first it was working" and then it stopped working after some debugging/development. Was the module connected properly to EdgeHub and able to perform various operations successfully (including GetTwin?), when the GetTwin stopped working? Did you see any errors in the module logs? 

If you are seeing this consistently, then can you enable debug logs for the EdgeHub? That will give us more insights. Set the RuntimeLogLevel environment variable to "debug" for the EdgeHub module (or the EdgeAgent module) to enable debug logs.

**Comment by dsajanice** [comment]
@vbadri Another data point that would help is printing the twin's desired properties in your module's desired property update callback. Each time you update the properties from the portal, the callback should be called within a few seconds and should print the updated twin information.

**Comment by dsajanice** [comment]
Might be orthogonal to this issue, but are you using MQTT or AMQP to connect the module to EdgeHub?

**Comment by vbadri** [comment]
@dsajanice : For the modules with the problem, the callback is not invoked when I change desired properties. as I mentioned, for the new (code-identical) modules, it works just fine. 

@varunpuranik: Please find attached the source code of the module. Throughout my development, the module was invoked on a regular Ubuntu machine running the edge hub sdk. I'll try enabling the debug and send you logs.

[moduleCode.tar.gz](https://github.com/Azure/iotedge/files/2230098/moduleCode.tar.gz)

**Comment by varunpuranik** [comment]
In the code I see one issue - you are not awaiting the ioTHubModuleClient.UpdateReportedPropertiesAsync either in Init or in OnDesiredPropertiesUpdate. So if something fails during the update, we may not know. 

My primary suspicion is that the module hasn't connected properly to EdgeHub, which is why it is not seeing any desired property updates. So with the new modules, since they connect to EdgeHub successfully, they are able to get the twin desired property updates and everything works as expected. The debug logs should tell us more.

**Comment by vbadri** [comment]
Hmm, I cannot recreate the problem today. I do see updates show up immediately on both my python and C# modules. I have turned on debug logs. 

I recommend I close this for now.  If it comes up again, I can reopen the issue.

**Comment by varunpuranik** [comment]
Thanks for the update. Alright, sounds good. I will go ahead and close the issue.
