### ISSUE TITLE
EOL update

### ISSUE THREAD

**Issue by vasdee** [Azure/iotedge#7207]
Wondering what the plan is for the next release? v1.4 is EOL in November 2024, and not seeing any further updates for a new release? Can someone please enlighten the community?

https://learn.microsoft.com/en-us/lifecycle/products/azure-iot-edge

**Comment by vasdee** [comment]
Can you give any indication of how drastic the upgrade path from v1.4 will be? We currently manage around 100 iotedge devices and the process of upgrading is already time consuming. Having to incorporate big changes to the install is way more involved, eg the 1.2/1.3 -> 1.4 upgrade was an example of this

**Comment by bishal41** [comment]
@vasdee the upgrade will process will be similar to this--> https://learn.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge?view=iotedge-1.4&tabs=windows

We are primarily upgrading the .NET 6 which will be EOL Nov 2024. The new LTS release will use .NET 8 and will be sometime in Q1- early Q2 of this year.

**Comment by bishal41** [comment]
@vasdee closing this issue, let me know if you have any additional questions.
