### ISSUE TITLE
Protecting  Edge (Docker) Module Images at rest with the IoT-Edge?

### ISSUE THREAD

**Issue by PtwHub** [Azure/iotedge#7218]
We are users of IoT-Hub and IoT-Edge in the MedTec space. Our current threat analyses opened up a question that maybe you can help with? The IoT-Edge (Docker) module images and containers are stored on the host OS file system. What is to prevent them from being compromised between IoT-Edge restarts? 

Is there a feature, such as signing, provided by the iot-edge that could reduce the risk? 
If not, are there any non iot-edge-specific features that you recommend to reduce the residual risk?
Or am I over paranoid? If so, how much over :-) ? 

This is above and beyond the standard "organizational security" argument argument, of course. We isolate the images in directories with iot-edge group access, but if a malicious user has root privileges, then we would not know if the docker images had been modified. Or how would/could the IoT-Edge notice?

Thanks for your help.

**Comment by nyanzebra** [comment]
@PtwHub There is currently nothing that iotedge does to verify the integrity of images. If a maligned entity had root access and changed the images, then iotedge would still use those images.

**Comment by PtwHub** [comment]
Sincere thanks Robert. That gives us clarity, so we can assess/discuss whether we need to add this above and beyond the standard organizational security of protecting the root user. And thanks for a great IoT product set...

**Comment by PtwHub** [comment]
Closing...
