### ISSUE TITLE
Offline detection status / event

### ISSUE THREAD

**Issue by emilm** [Azure/iotedge#7221]
Is there a way to detect if a module lost connection to the Internet (remote hub) yet? iot edge does know itself, but I think it should expose that information so I can act on it.

**Comment by nyanzebra** [comment]
@emilm The goal of edgehub is to hide the connectivity issues/status from the modules/devices so by purpose, a module cannot know that the upstream connection is lost. What is your use case?

**Comment by nyanzebra** [comment]
@emilm sorry, but unfortunately, there is way to query the services like that at this time. I can bring this up internally as a formal ask though it might take time even if it is decided to implement such a feature.

**Comment by nyanzebra** [comment]
Closing issue due to staleness, please reopen if further action is needed.
