### ISSUE TITLE
Create a reusable Volume in Azure IOT Edge Module via Container Create Options

### ISSUE THREAD

**Issue by tcochunk** [Azure/iotedge#7265]
This is not so much a bug but more of a question.  I have been searching for days but cant find anything.

The larger question is where can i find **good** documentation for the Container Create Options for an IOT Edge Module?

My very specific scenario is:

I have a module i created based on a third party database provider with the intent of pushing this database to my edge devices.
Because its a database, I want the data to survive updates and my research says Volumes are the mechanism for doing that.

My current Container Create Options looks like this:

`{
    "Volumes": {
        "/data": {}
    }
}`

When I deploy the module, a volume is created with a generated name.  If I modify the database the changes will persist across container restarts but if I deploy again, the changes are lost.  

What options are available in the {}?
What does "/data" mean?
Where does this map to on the host? (the docker folder?)
Can I specify the location on the host?
Can I give this volume a name?
How do I create a volume that can be reused by different versions of a module?

**Comment by david-emakenemi** [comment]
Hey @tchochunk,  here are some good documentations that we have that covers [how to configure container create options for IoT Edge modules](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-use-create-options?view=iotedge-1.4) and [modules access to a device's local storage](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4). Let us know if this helps.

**Comment by tcochunk** [comment]
@david-emakenemi thank you for the response.  I read both those articles and if I copy the HostConfig section from [modules access to a device's local storage](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module?view=iotedge-1.4) and use that with my information, **it does work.**  But I dont know what it does.  The following link is provided on the azure web site under Container Create Option - [https://docs.docker.com/engine/api/v1.30/#tag/Container/operation/ContainerCreate](url) I could not find a Mount option under Host Config so how do i know it is a valid option, as the example shows?  After reading several sites, it seems that Volumes are better than binds but i cant find any documentation on implementing Volumes.  While I have a working example, I dont have an understanding of what is happening and the 2 articles are focused on a very small subset of the options available.

I guess I am looking for additional documentation so I will keep searching.
Sincerely, Thank You.
