### ISSUE TITLE
Can not ssh into a (running) VM with Ubuntu Core 20 on my k3s cluster

### ISSUE THREAD

**Issue by bilbobegg** [Azure/iotedge#7266]
## Expected Behavior
k3s environment with Kubevirt and CDI.
Perfectly works with Ubuntu 20.04 as OS for the VM. Kubevirt VM boots and I can ssh into it.
I expect it to work with Ubuntu Core as OS for the VM too.

## Current Behavior
Testing it with Ubuntu Core 20 as OS, Kubevirt VM boots (running status) BUT I can NOT ssh into it (connection refused).
Maybe because Ubuntu Core devices need manual configuration (networking and ubuntu one account) at first boot (?).

I see that "Tier 1 supported operating systems for Azure IoT Edge has been expanded to include Ubuntu Core Snaps on AMD 64".
But also that when you boot an Ubuntu Core device for the first time you need a screen and a keyboard (for the network configuration and ubuntu one account I guess).

## Context (Environment)
kairos-ubuntu20.04 host OS. k3s single node cluster with kubevirt and CDI. Azure Iotedge lives on the (kubevirt) vm on the cluster.

### Device Information
* Host OS [kairos-ubuntu20.04 host OS]: 
* Architecture [amd64]:

**Comment by veyalla** [comment]
Sorry but the team here can't help with Kubevirt and Ubuntu Core issues.
