### ISSUE TITLE
[Documentation] [Low priority] Add to the config.toml template and documentation a section for logging

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/iotedge#7284]
After running `iotedge check` I get the following warning

```text
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
```

The link points to the `config.toml` documentation, but the section for log-policy doesn't exist.

Suggestion: add the log-policy description to the best practices document.

**Comment by yophilav** [comment]
@uriel-kluk 
Thank you for reporting the issue. 😄 The document https://aka.ms/iotedge-prod-checklist-logs suggested that we updated the log policy in `daemon.json` which configured the underlying docker log service. On the other hand, the `config.toml` is a configuration that we used to configure the iotedged. I believe the document is accurate. Please let me know if I'm missing something. Thanks!
