### ISSUE TITLE
Iot edge not starting on debian bullseye

### ISSUE THREAD

**Issue by Kralg** [Azure/iotedge#7287]
## Expected Behavior
I would like to run iot edge with some modules on Raspbian bullseye (11) armv6l Raspberry pi zero. I managed to install docker and test it with a test image Hello world so far, but iot edge does not work. 

## Current Behavior
I try to check if iot edge is working with sudo systemctl status aziot-edge.
And getting report: 
sudo iotedge config mp --connection-string 'my primary connection string for iot edge'
I get: Illegal instruction
sudo iotedge logs edgeAgent
I get: Illegal instruction

With:  sudo systemctl status aziot-edged
I get:
 Loaded: loaded (/lib/systemd/system/aziot-edged.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Thu 2024-05-09 16:29:04 BST; 4s ago
TriggeredBy: ● aziot-edged.workload.socket
             ● aziot-edged.mgmt.socket
       Docs: man:aziot-edged(8)
    Process: 3042 ExecStart=/usr/libexec/aziot/aziot-edged (code=killed, signal=ILL)
   Main PID: 3042 (code=killed, signal=ILL)
        CPU: 44ms

## Context (Environment)

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

### Output of `iotedge check`
Illegal instruction
<details>
<summary>Any help would be very appreciated</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 22.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

 aziot-edged.workload.socket - Azure IoT Edge daemon workload socket
     Loaded: loaded (/lib/systemd/system/aziot-edged.workload.socket; enabled; vendor preset: enabled)
     Active: active (listening) since Thu 2024-05-09 16:36:55 BST; 3s ago
   Triggers: ● aziot-edged.service
       Docs: man:aziot-edged(8)
     Listen: /run/iotedge/workload.sock (Stream)
      Tasks: 0 (limit: 414)
        CPU: 12ms
     CGroup: /system.slice/aziot-edged.workload.socke

```
</details>

<details>
<summary>edge-agent logs</summary>

```

This service is not found.

```
</details>

<details>
<summary>edge-hub logs</summary>

```

This service is not found.

```
</details>

<details>
<summary>aziot-edged.mgmt.socket </summary>

```
● aziot-edged.mgmt.socket - Azure IoT Edge daemon management socket
     Loaded: loaded (/lib/systemd/system/aziot-edged.mgmt.socket; enabled; vendor preset: enabled)
     Active: active (listening) since Thu 2024-05-09 16:37:28 BST; 3s ago
   Triggers: ● aziot-edged.service
       Docs: man:aziot-edged(8)
     Listen: /run/iotedge/mgmt.sock (Stream)
      Tasks: 0 (limit: 414)
        CPU: 13ms
     CGroup: /system.slice/aziot-edged.mgmt.socket

May 09 16:37:28 tvsiot-1-1-41 systemd[1]: Starting Azure IoT Edge daemon management socket.
May 09 16:37:28 tvsiot-1-1-41 systemd[1]: Listening on Azure IoT Edge daemon management socket.

```
</details>

**Comment by mamonetti** [comment]
I'd say armv6 is not supported, that's why you get the Illegal instruction errors. See [here](https://github.com/MicrosoftDocs/azure-docs/issues/24443)

**Comment by ryanwinter** [comment]
Armv6 is not support. Please see our OS support list [here](https://learn.microsoft.com/en-us/azure/iot-edge/support?view=iotedge-1.4#tier-2).
