### ISSUE TITLE
Is it possible to manually renew the Edge CA certificates?

### ISSUE THREAD

**Issue by shaeussler** [Azure/iotedge#7303]
Is it possible to ssh into a Azure IoT Edge and then manually trigger the renewal of the Edge CA certificates?
I found this post for the manually renewal of the device identity certificate: https://github.com/Azure/iotedge/issues/5787#issuecomment-958020511

**Comment by bilalsellak** [comment]
Please fill out the issue template found here: https://github.com/Azure/iotedge/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by shaeussler** [comment]
Hi [bilalsellak](https://github.com/bilalsellak),
I have no issue, it's only a question. 
Do you have a better place to put this question?

**Comment by veyalla** [comment]
Please post on https://aka.ms/iotedge-qna. Thanks!
