### ISSUE TITLE
EFLOW 1.5 Release?

### ISSUE THREAD

**Issue by maggiojoe2** [Azure/iotedge#7377]
I asked in the eflow repo, but no one has responded. When will the 1.5 version be released for EFLOW?

https://github.com/Azure/iotedge-eflow/issues/290

**Comment by ryanwinter** [comment]
Closing, following up with EFLow to answer on the eflow github.

**Comment by maggiojoe2** [comment]
It has been months since anyone from that team posted on the EFLOW repo. Is there any way to get this more visibility instead of closing it and moving on? End of life for 1.4 is in a month and we haven't had any updates since 1.5 was released and we were given a Q3 estimate in the announcement.

**Comment by SummerSmith** [comment]
The EFLOW team is currently working on the EFLOW release with IoT Edge 1.5. This will be released before the 1.4 EOL date, but we do not have a specific date to share at this time.
