### ISSUE TITLE
Edge modules 'failed' after restart-service

### ISSUE THREAD

**Issue by linda6234** [Azure/iotedge#739]
Hi,
I install the new Edge version (windows host - windows containers) and occur the problem as https://github.com/Azure/iotedge/issues/659 .
It works first time, after I using restart-service iotedge, same problem occurs.

## Expected Behavior

iotedge containers start again after restart-service iotedge.

## Current Behavior

When I using restart-service iotedge the containers (modules) are in the 'failed' status.
The service is running, restarting the service has no effect, the containers remain 'failed'.

## Steps to Reproduce

1. Install windows 10 Enterprise LTSC - Version 1809 (OS Build 17763.rs5_release.1809144-1434) trial version in VMplayer
2. Create Edge in cloud
3. Install Edge using quickstart guide + check if it's running --> RUNNING
4. Restart VM (restart windows) --> service is still running but containers FAILED
5. Fixed step 4 by https://github.com/Azure/iotedge/issues/659
6. restart-service iotedge.

### Device (Host) Operating System

WIndows 10 Enterprise LTSC - Version 1809 (OS Build 17763.rs5_release.1809144-1434)
### Architecture

windows/amd64
### Container Operating System

windows containers
#### iotedged

iotedge 1.0.5.19141174
#### Edge Agent

mcr.microsoft.com/azureiotedge-hub:1.0
#### Edge Hub

mcr.microsoft.com/azureiotedge-agent:1.0
#### Docker

![image](https://user-images.githubusercontent.com/12811372/51647065-485bde80-1fb6-11e9-9963-53507e109b75.png)

## Logs

![image](https://user-images.githubusercontent.com/12811372/51647205-cc15cb00-1fb6-11e9-98fc-b198c198f50c.png)

**Comment by myagley** [comment]
Is it possible to get logs for one of the Edge Hub or one of the failed containers? `iotedge logs edgeHub`

The other thing you should try is updating the config.yaml's `moby_runtime.network` to `nat`. The block near the end of the config file should look like:

```yaml
moby_runtime:
  uri: 'npipe://./pipe/iotedge_moby_engine'
  network: nat
```

**Comment by linda6234** [comment]
Hi myagley,
It wasn't possible to get log of edgeHub. And I modify config.yaml

> moby_runtime:
>   uri: 'npipe://./pipe/iotedge_moby_engine'
>   network: nat

It's works first time after restart-service same problem occurs.
Thanks!
