### ISSUE TITLE
Edge Agent can not connect to IoT Hub (IoT Edge 1.0.5)

### ISSUE THREAD

**Issue by bvuden** [Azure/iotedge#740]
## Expected Behavior

Installing IoT Edge Runtime on Windows 10 with Linux as Container OS based on the command provided in the docs should install and run the runtime without errors.

## Current Behavior
IoT Edge installs without problems. The edgeAgent module starts, but throws a timeout exception:

2019-01-24 12:32:35.374 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
2019-01-24 12:32:36.075 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
2019-01-24 12:33:05.507 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
2019-01-24 12:33:35.533 +00:00 [WRN] - Error creating a device-to-cloud connection
System.AggregateException: One or more errors occurred. (Operation timeout expired.) (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

## Steps to Reproduce

1. Register a new Edge Device in Azure IoT Hub
2. Install the runtime with the command as mentioned in the docs:
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -Manual -ContainerOs Windows -DeviceConnectionString '<connection-string>'
3. Make a deployment to the edge Device
4. Verify that the edgeAgent is running:
`iotedge list`
5. Check the logs to see the exception:
`iotedge logs edgeAgent`

### Device (Host) Operating System

Windows 10 Pro

### Architecture

amd64

### Container Operating System

Linux containers

#### iotedged

1.0.5
#### Edge Agent

1.0
#### Edge Hub

1.0
#### Docker

18.09.1
## Logs

[Logs](https://gist.github.com/bvuden/44a35617766c1be0fbe42a30a71df68b)

## Additional Information

After uninstalling and installing the runtime with version 1.0.4 of the IotEdgeSecurityDaemon powershell script everything works as expected:
. {Invoke-WebRequest -useb https://raw.githubusercontent.com/Azure/iotedge/1.0.4/scripts/windows/setup/IotEdgeSecurityDaemon.ps1} | Invoke-Expression; `
Install-SecurityDaemon -Manual -ContainerOs Linux -DeviceConnectionString '<connection-string>'

It seems the problem is related to the 1.0.5 version of the IotEdgeSecurityDaemon powershell script.

**Comment by myagley** [comment]
This may have been fixed in the 1.0.6-rc1 version of the script. We did some work to get Linux containers on Windows working. You can try the script here: https://github.com/Azure/iotedge/blob/1.0.6-rc1/scripts/windows/setup/IotEdgeSecurityDaemon.ps1

Please note that Linux containers on Windows is **not** a supported scenario.

**Comment by bvuden** [comment]
Using the 1.0.6-rc1 version of the IoTEdgeSecurityDaemon script results in the same timeout exception.

**Comment by myagley** [comment]
Is it possible to upgrade to `1.0.7` and run `iotedge check` on the device?

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
