### ISSUE TITLE
InvokeMethodAsync results in Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException

### ISSUE THREAD

**Issue by dieterdp** [Azure/iotedge#756]
Hello

I am trying to activate a direct methode inside a IoT edge module.
I have the following code:

string connectionString = "HostName=frigro.azure-devices.net;DeviceId=raspi-samuel;ModuleId=ReceiveCommands;SharedAccessKey=my key";
 
                ModuleClient module = ModuleClient.CreateFromConnectionString(connectionString);

                MethodRequest method = new MethodRequest("reboot", Encoding.UTF8.GetBytes("{   }"));
          
                var result = module.InvokeMethodAsync("raspi-samuel", "ReceiveCommands", method).GetAwaiter().GetResult();

The method InvokeMethodAsync results in a Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException: {"Message":"{\"errorCode\":401002

I am using the module connectionstring with deviceid and moduleid in the connectionstring.
Where can i change the permissions in the portal  or is there a other reason ?

It works from Visual Code when i invoke the same method and it also works when i choose the module abd then "Direct Method" invoke methode from the portal.

regards
Dieter

**Comment by myagley** [comment]
Can you try instantiating your client from the environment?

```csharp
ModuleClient module = ModuleClient.CreateFromEnvironment();

MethodRequest method = new MethodRequest("reboot", Encoding.UTF8.GetBytes("{   }"));      
var result = await module.InvokeMethodAsync("raspi-samuel", "ReceiveCommands", method);
```

The IoT Edge runtime manages module identities and provides access to a module's credentials via the daemon. This is all handled transparently by the SDK, but requires that the client is created from the environment.

**Comment by dieterdp** [comment]
Hello

I want to call this from a ASP.NET Core Web Application not from a other module.
I am testing now from a .NET Core Console app.

regards
Dieter

**Comment by dieterhowest** [comment]
this is fixed, i was using the devices SDK ,  i had to use services SDK

**Comment by myagley** [comment]
Glad to hear it is fixed. I am going to close the issue but please feel free to reopen if you still have issues.
