### ISSUE TITLE
Issue when uninstalling iotedge runtime: "The property 'net.azure-devices.edge.owner' cannot be found on this object"

### ISSUE THREAD

**Issue by ddobric** [Azure/iotedge#764]
Trying to remove iotedge runtime fails. I have copied following statement from [this ](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#clean-up-resources) documentation page.

` . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Uninstall-SecurityDaemon -DeleteConfig  -DeleteMobyDataRoot`

Command fails with following error:

```
Uninstall-SecurityDaemon : The property 'net.azure-devices.edge.owner' cannot be found on this object. Verify that the
property exists.
At line:1 char:2
+  Uninstall-SecurityDaemon
+  ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Uninstall-SecurityDaemon], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Uninstall-SecurityDaemon
```

### Architecture
 Windows x64 - 10.0.17134 N/A Build 17134

### Container Operating System
Windows

#### iotedged
iotedge 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)

#### agent/hub
Cannot enlist agent and hub, because daemon service does not exist on the box. Runtime was installed long time ago. Now it has to be reinstalled.

#### Docker
Docker version 18.09.1, build 4c52b90

**Comment by myagley** [comment]
This was fixed in the uninstall script here: https://github.com/Azure/iotedge/commit/10042ee53eba659e2f019b1e3a502f24efa76525

You can try this command to use the new script:

```powershell
. {Invoke-WebRequest -useb aka.ms/iotedge-win-install-rc} | Invoke-Expression; Uninstall-SecurityDaemon -DeleteConfig -DeleteMobyDataRoot
```

Note that this will download and use the install script for the 1.0.6 release candidate `1.0.6-rc1`.

**Comment by myagley** [comment]
Version `1.0.6` was released with a fix for this issue. You should be able to install `1.0.6` by running the following powershell commands:

Uninstall:
```powershell
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Uninstall-SecurityDaemon -DeleteConfig -DeleteMobyDataRoot
```

Install 1.0.6:
```powershell
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -Manual -ContainerOs Windows -DeviceConnectionString '<connection-string>'
```
