### ISSUE TITLE
Modules are not getting started after restarting iotedge device in offline mode

### ISSUE THREAD

**Issue by piyushka17** [Azure/iotedge#771]
## Expected Behavior

After restarting iotedge device while the network is disconnected the modules should come up again.

## Current Behavior

Modules aren't coming up after restarting iotedge device till the network is disconnected.

## Steps to Reproduce

1. Configure iotedge device.
2. Provision a test module on the device.
3. Disable network connection of the device.
4. Reboot iotedge device.
5. Start iotedge daemon.

### Device (Host) Operating System

Ubuntu 16.04
### Container Operating System

Linux
#### iotedged

1.0.4
#### Edge Agent

1.0
#### Edge Hub

1.0
#### Docker

moby-engine_1.0.0-1
## Logs

hcsuser@ubuntu-vm:~$ sudo docker ps
CONTAINER ID        IMAGE                                               COMMAND                   CREATED              STATUS              PORTS                                                                  NAMES
fb8f264f2c64        edgecompute.azurecr.io/filemovemodule:0.0.1-amd64   "dotnet FileMoveModu…"    3 seconds ago        Up 2 seconds                                                                               filemovemodule
701e5a0c95d9        mcr.microsoft.com/azureiotedge-hub:1.0              "/bin/sh -c 'echo \"$…"   34 seconds ago       Up 33 seconds       0.0.0.0:443->443/tcp, 0.0.0.0:5671->5671/tcp, 0.0.0.0:8883->8883/tcp   edgeHub
d77fd77a10d0        mcr.microsoft.com/azureiotedge-agent:1.0            "/bin/sh -c 'echo \"$…"   About a minute ago   Up About a minute                                                                          edgeAgent

[[ Turn off network connection ]]

[[ Restart machine ]]

hcsuser@ubuntu-vm:~$ sudo systemctl start iotedge

hcsuser@ubuntu-vm:~$ sudo journalctl -u iotedge -f
-- Logs begin at Tue 2019-01-29 14:36:32 PST. --
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Manually provisioning device "piyushroleofflinetest2-edge" in hub "piyushiothub0128.azure-devices.net"
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Finished provisioning edge device.
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Starting management API...
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Starting workload API...
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Starting watchdog with 60 second frequency...
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Listening on fd://iotedge.mgmt.socket/ with 1 thread for management API.
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Listening on fd://iotedge.socket/ with 1 thread for workload API.
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Checking edge runtime status
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [INFO] - Creating and starting edge runtime module edgeAgent
Jan 29 14:37:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:37:27Z [DBUG] - [edgelet_http::client] Success generating token for request GET /devices/piyushroleofflinetest2-edge/modules/$edgeAgent
Jan 29 14:38:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:15Z [ERR!] - Error { kind: Connect, cause: Some(Custom { kind: Other, error: StringError("failed to lookup address information: Temporary failure in name resolution") }) }
Jan 29 14:38:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:15Z [WARN] - Error in watchdog when checking for edge runtime status:
Jan 29 14:38:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:15Z [WARN] - Identity error
Jan 29 14:38:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:15Z [WARN] -         caused by: IoT Hub service error
Jan 29 14:38:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:15Z [WARN] -         caused by: Core error
Jan 29 14:38:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:15Z [WARN] -         caused by: Hyper error
Jan 29 14:38:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:15Z [WARN] -         caused by: an error occurred trying to connect: failed to lookup address information: Temporary failure in name resolution
Jan 29 14:38:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:27Z [INFO] - Checking edge runtime status
Jan 29 14:38:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:27Z [INFO] - Creating and starting edge runtime module edgeAgent
Jan 29 14:38:27 ubuntu-vm iotedged[2582]: 2019-01-29T22:38:27Z [DBUG] - [edgelet_http::client] Success generating token for request GET /devices/piyushroleofflinetest2-edge/modules/$edgeAgent
Jan 29 14:39:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:39:15Z [ERR!] - Error { kind: Connect, cause: Some(Custom { kind: Other, error: StringError("failed to lookup address information: Temporary failure in name resolution") }) }
Jan 29 14:39:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:39:15Z [WARN] - Error in watchdog when checking for edge runtime status:
Jan 29 14:39:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:39:15Z [WARN] - Identity error
Jan 29 14:39:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:39:15Z [WARN] -         caused by: IoT Hub service error
Jan 29 14:39:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:39:15Z [WARN] -         caused by: Core error
Jan 29 14:39:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:39:15Z [WARN] -         caused by: Hyper error
Jan 29 14:39:15 ubuntu-vm iotedged[2582]: 2019-01-29T22:39:15Z [WARN] -         caused by: an error occurred trying to connect: failed to lookup address information: Temporary failure in name resolution

hcsuser@ubuntu-vm:~$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

hcsuser@ubuntu-vm:~$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

## Additional Information

Auto start of iotedge daemon is disabled on the setup.

**Comment by myagley** [comment]
There is a bug in the iotedge daemon that can cause spurious reprovisioning. This causes the daemon to reach out to IoT Hub to check the Edge Agent identity. This was fixed in #689 and will be in the `1.0.6` release. This will come out in the next few days.

Can I ask are you specifying environment variables for the Edge Agent module in the `config.yaml`?

**Comment by piyushka17** [comment]
Yes, we are setting these variables:
    RuntimeLogLevel: "debug"
    http_proxy: "http://10.128.44.142:8080"
    https_proxy: "http://10.128.44.142:8080"
    UpstreamProtocol: "AmqpWs"

Sure, I will wait for 1.0.6

**Comment by myagley** [comment]
Version `1.0.6` was released yesterday which contains a fix for this issue. You can upgrade with:

```bash
sudo apt-get update
sudo apt-get install iotedge libiothsm-std
```
