### ISSUE TITLE
SimulatedTemperatureSensor throwing AuthenticationException on latest IoTEdge runtime

### ISSUE THREAD

**Issue by darenm** [Azure/iotedge#781]
## Expected Behavior
Deploying latest version of the IoT Edge runtime onto an Azure VM running Win Server 2019 + virtualization + hyper-v + Docker

Unable to deploy the SimulatedTemperatureSensor from the Azure MarketPlace

## Current Behavior
`SimulatedTemperatureSensor  failed           Failed (139) 2 minutes ago  mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0`

## Steps to Reproduce

Following steps here to [Deploy a module](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux#deploy-a-module)

## Context (Environment)
Azure VM running Windows Server 2019 Data Center

### Device (Host) Operating System
WIndows Server 2019 Data Center VM with Virtualization Enabled

### Architecture
x64

### Container Operating System
Linux Containers

#### iotedged
`iotedge 1.0.6 (8288bc9bd6f6e15295fea506cd3f99d7f6347a6a)`

#### Edge Agent
`edgeAgent                   running          Up 37 minutes               mcr.microsoft.com/azureiotedge-agent:1.0`

#### Edge Hub
`edgeHub                     running          Up 28 minutes               mcr.microsoft.com/azureiotedge-hub:1.0`

#### Docker

```console
PS C:\Users\iotadmin> docker version
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Logs

```log
PS C:\Users\iotadmin> iotedge logs SimulatedTemperatureSensor -f
[2019-02-01 02:57:28 : Starting Module
[02/01/2019 02:57:28.623 AM] Main()
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Using transport Amqp_Tcp_Only

Unhandled Exception: System.AggregateException: One or more errors occurred. (The remote certificate is invalid according to the validation procedure.) ---> System.Security.Authentication.AuthenticationException: The remote certif
icate is invalid according to the validation procedure.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 114
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 81
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 39
[2019-02-01 02:57:46 : Starting Module
[02/01/2019 02:57:46.222 AM] Main()
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Using transport Amqp_Tcp_Only
```

**Comment by veyalla** [comment]
I cannot repro this. 

If an [uninstall](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#remove-the-iot-edge-runtime) and reinstall doesn't fix it, can you share the config.yaml and log from edgeHub and temp sensor please?

**Comment by darenm** [comment]
After uninstall and reinstall it still fails.

[edgeHub.log](https://github.com/Azure/iotedge/files/2822021/edgeHub.log)
[sensor.log](https://github.com/Azure/iotedge/files/2822023/sensor.log)
[config.yaml.txt](https://github.com/Azure/iotedge/files/2822024/config.yaml.txt)

**Comment by myagley** [comment]
Can you set the `network` to `nat` in the bottom section (`moby_runtime`) of your `config.yaml`, like so:

```yaml
moby_runtime:
  uri: 'npipe://./pipe/docker_engine'
  network: 'nat'
```

There is a bug in how user defined networks work on Windows that prevents them from surviving a reboot. This is now the default on 1.0.6.

**Comment by darenm** [comment]
OK - I made that change and restarted the `iotedge` windows service- do I need to do more than that?

The SimulatedTemperatureSensor is still failing with this error in it's log:

```log
Unhandled Exception: System.AggregateException: One or more errors occurred. (The remote certificate is invalid according to the validation procedure.) ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeout>b__62_2(Task t)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at SimulatedTemperatureSensor.Program.InitModuleClient(TransportType transportType) in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 114
   at SimulatedTemperatureSensor.Program.MainAsync() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 81
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at SimulatedTemperatureSensor.Program.Main() in /home/vsts/work/1/s/edge-modules/SimulatedTemperatureSensor/src/Program.cs:line 39
[2019-02-01 16:37:18 : Starting Module
[02/01/2019 04:37:18.481 PM] Main()
Initializing simulated temperature sensor to send 500 messages, at an interval of 5 seconds.
To change this, set the environment variable MessageCount to the number of messages that should be sent (set it to -1 to send unlimited messages).
Using transport Amqp_Tcp_Only
```

**Comment by veyalla** [comment]
Actually since you are running Linux containers, the "azure-iot-edge" the right value to have in your config yaml for the network. 

I am suspecting this maybe due to time drift in the VM since multiple layers of virtualization are at play. Any chance you can get test this on a non-VM?

**Comment by darenm** [comment]
So I switched Docker to use Windows containers, uninstalled and reinstalled iotedge and the SimulatedTemperatureSensor is now running.... I am going to cycle back to Linux containers in a moment to see if there was some "random glitch" in the Docker setup or whether then may be an issue with the Windows image.

**Comment by darenm** [comment]
@veyalla Runs fine on my laptop... Hmm.

**Comment by veyalla** [comment]
I've tried the same with DsV3 Server 2019 Azure VM and Docker Desktop as well, and cannot repro.

**Comment by darenm** [comment]
@veyalla Well, shoot - seems like it is non-deterministic then... The reason I am looking into this is a few students ran into the same issue and it happened to recur for me. I can get you access to my VM if you think there is anything you could see...

**Comment by veyalla** [comment]
Sure, I can try to take a look. You can reach me at veyalla at microsoft dot com

**Comment by darenm** [comment]
With thanks to @veyalla and team we tracked down the issue - TLS doesn't like it if your machine name starts with a numeric - as I named my VM - "2019Edge", that was a problem and resulted in an invalid cert being generated for the telemetry data being sent to the IoT Hub. Creating a new VM with an appropriate name addressed the issue.

**Comment by ddimitrov90** [comment]
the validation of the certificate also fails if the hostname contains dots (most probably will fail with other symbols like - _ etc..)
you have to edit the `/etc/iotedge/config.yaml` and remove those characters from the `hostname` property
