### ISSUE TITLE
Id returned 1 exit status

### ISSUE THREAD

**Issue by Imacutekayx** [Azure/iotedge#782]
Hello there,

I have a problem when I try to send informations from my development board (collected by sensors) to my hub.
I started by creating an IoTHub sample in VS2017 and it worked perfectly.
I created a module which analyse the information of my sensors which worked as well but when I try to merge the two of the (by adding methods, includes needed and calls in the main) it always return me this error: "Id returned 1 exit status".

Does anyone have an idea?
Thanks

**Comment by Imacutekayx** [comment]
Nevermind it was a problem with the Grove_Shield_Library project which didn't open correctly and so couldn't be found in the references...

**Comment by myagley** [comment]
It sounds like you have the issue fixed. I'm going to close the issue, but feel free to reopen if you have other questions.
