### ISSUE TITLE
'Folder already exists' error when installing on Windows with -ExistingConfig

### ISSUE THREAD

**Issue by kgremban** [Azure/iotedge#789]
## Expected Behavior
The IoT Edge installation script for Windows comes with an option to preserve the config file when you uninstall, and then use that config file when you install the runtime instead of having to provision your device again. 

## Current Behavior
When I try to install the IoT Edge runtime with my existing config file, I get an error that install failed because the iotedge folder already exists. That folder should exist; it's where my saved config file is. 

![image](https://user-images.githubusercontent.com/13578436/52156157-6b803100-263b-11e9-918a-cff0d7697400.png)

## Steps to Reproduce

1. 
```
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -Manual -ContainerOs Windows -DeviceConnectionString '<connection-string>'
```

2. 
```. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Uninstall-SecurityDaemon```

3. 
```. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -ExistingConfig -ContainerOs Windows```

### Device (Host) Operating System
Windows 10 Enterprise

### Architecture
amd64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.6

#### Edge Agent
1.0
(installed on 2/1, so should be 1.0.6)

#### Edge Hub
1.0
(installed on 2/1, so should be 1.0.6)

#### Docker
![image](https://user-images.githubusercontent.com/13578436/52156305-53f57800-263c-11e9-9237-f3205739c8d6.png)

**Comment by arsing** [comment]
https://github.com/Azure/iotedge/commit/82b82ccffdaeed408b04803ea2679e9b626d15c9 added `-Force` to [the branch for the expanded `iotedged-windows` directory](https://github.com/Azure/iotedge/commit/82b82ccffdaeed408b04803ea2679e9b626d15c9#diff-8ae7a24c87a2048c653a1cfb9f7e1d8bR515) but not to [the branch for the `iotedged-windows.zip` file.](https://github.com/Azure/iotedge/commit/82b82ccffdaeed408b04803ea2679e9b626d15c9#diff-8ae7a24c87a2048c653a1cfb9f7e1d8bR524)

You can work around it by changing the line in the error to `New-Item -Type Directory $EdgeInstallDirectory -Force | Out-Null`

**Comment by arsing** [comment]
aka.ms link has been updated to point to the fixed script.
