### ISSUE TITLE
Custom module is failing on Edge Version 1.0.6

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#797]
I have upgraded Azure edge version from 1.0.5 to 1.0.6,  Everything was working fine on older edge version, but module started failing with latest update with 1.0.6

Is there any way to move back to edge Version 1.0.5 on Ubuntu 16.0.4?

### Device (Host) Operating System
<Ubuntu 16.04>

### Architecture
< amd64 >

### Container Operating System
<Linux containers>

#### iotedged
< Run `iotedge version` 1.0.6 >

#### Edge Agent
< Image tag (i.e. 1.0.6) >

#### Edge Hub
< Image tag (i.e. 1.0.6) >

#### Docker
< Run `docker version` 3.0.2 >

**Please find attached logs of edgeHub, edgeAgent, edgeModule**

[edgeAgent_log_Edge_1.0.6.txt](https://github.com/Azure/iotedge/files/2827850/edgeAgent_log_Edge_1.0.6.txt)
[edgeHub_Log_Edge_1.0.6.txt](https://github.com/Azure/iotedge/files/2827851/edgeHub_Log_Edge_1.0.6.txt)
[Module_Failure_on_Version Edge_1.0.6.txt](https://github.com/Azure/iotedge/files/2827852/Module_Failure_on_Version.Edge_1.0.6.txt)

**Comment by myagley** [comment]
What is the `hostname` for this device? We unfortunately may have a regression in certificate generation when the hostname starts with a number.

**Comment by myagley** [comment]
I believe the spec for domain names is `[A-Za-z0-9\.-]+`, with the additional restriction that it cannot start or end with a hyphen. The code that does this verification is here: https://github.com/Azure/iotedge/blob/master/edgelet/edgelet-utils/src/lib.rs#L80

This code currently strips out leading numbers, and doesn't allow dot.

Are there others characters that need to be accepted?

**Comment by pratson20** [comment]
I have used mygateway.local as hostname in config.yaml file

**Comment by myagley** [comment]
The dot in the hostname is causing this issue.

To move back to `1.0.5` you can run `sudo apt-get install iotedge=1.0.5-1`. There is also a fix for this in #795

**Comment by pratson20** [comment]
@myagley 

Thanks @myagley . I have removed the dot and issue is resolved.

I am following below link to connect downstream device to edge runtime and as per document. This document need to be updated if that is the issue. 

Connection string mentioned there-

HostName=yourHub.azure-devices.net;DeviceId=yourDevice;SharedAccessKey=XXXYYYZZZ=;GatewayHostName=mygateway.contoso.com

https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device

https://github.com/AzureIoTGBB/azure-iot-edge-hol-linux/tree/master/module1

**Comment by myagley** [comment]
We have rolled out a hotfix for this issue. There is a new version of the daemon (`1.0.6.1`) in all of the package repos and a new release page here: https://github.com/Azure/azure-iotedge/releases/tag/1.0.6.1

To upgrade on ubuntu, you can run:
```
sudo apt-get update
sudo apt-get install iotedge libiothsm-std
```

**Comment by pratson20** [comment]
Thanks @myagley

**Comment by myagley** [comment]
I am going to close the issue as a fix has been released.
