### ISSUE TITLE
How to read data from device over RS485 in azure edge as module in Linux/Windows

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#801]
Hi,
I have to read data over UART protocol as custom module. Is there any support is available on azure edge in linux or Windows IoT Core?

There is a requirement to implement UART communication as custom module.

**Comment by darobs** [comment]
Hello @pratson20,

Not sure about which kind of device you need to access, but the Modbus Module project might be a source of useful information:
https://github.com/Azure/iot-edge-modbus

In general, if you have a library which can communicate to the device, getting it to run in a container mostly involves mounting the correct devices visible to the container. In the Edge deployment, this is usually achieved by setting [createOptions.HostConfig](https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate) options (either setting Devices, or bind mounting the device).

**Comment by pratson20** [comment]
HI @darobs,

I have requirement to connect device similar to  Arduino Uno with Edge gateway. Device connectivity is over USB.
Is there any solution available on Linux as well as on Windows IoT Core

**Comment by darobs** [comment]
Hello @pratson20, 

There may be a possible module on the Azure Marketplace, from Alleantia, but I don't have any other projects I'm aware of - I'm asking around if there are any other projects which might fit the bill.

**Comment by pratson20** [comment]
Hi @darobs , We have some client requirement for  data transfer over USB communication in Azure Edge implementation. As per my knowledge, This support is release on RS5 build. Any tutorial on this will be really helpful for us.

**Comment by pratson20** [comment]
@myagley Will it be applicable for this issue-

https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Samples/EdgeModules/SerialWin32/CS/README.md

**Comment by myagley** [comment]
Closing this issue as a valid sample has been posted.
