### ISSUE TITLE
IoT edge daemon fails to start when certificates for transparent proxy are used

### ISSUE THREAD

**Issue by ondrejspilka** [Azure/iotedge#808]
## Expected Behavior
Normal start

## Current Behavior
Daemon fails to start

## Steps to Reproduce
Install IoT, deploy basic modules
Create certificates according to https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway
Configure certificates for gateway, restart

### Device (Host) Operating System
RHEL 7.5

### Architecture
x64

### Container Operating System
Linux containers

#### iotedged
1.0.6

#### Docker
17.03.2-ce

## Logs
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Starting Azure IoT Edge Security Daemon
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Version - 1.0.6
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Using config file: /etc/iotedge/config.yaml
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Detected HTTPS proxy server http://xxxxx:8080/
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Using runtime network id azure-iot-edge
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Initializing the module runtime...
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Initializing module runtime...
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Successfully initialized module runtime
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Finished initializing the module runtime.
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Configuring /var/lib/iotedge as the home directory.
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Configuring certificates...
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Configuring the Device CA certificate using "/var/lib/iotedge/certs/new-edge-device-full-chain.cert.pem".
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Configuring the Device private key using "/var/lib/iotedge/private/new-edge-device.key.pem".
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Configuring the trusted CA certificates using "/var/lib/iotedge/certs/azure-iot-test-only.root.ca.cert.pem".
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Finished configuring certificates.
Feb 05 19:46:09 XXXHOST iotedged[24124]: 2019-02-05T17:46:09Z [INFO] - Initializing hsm...
Feb 05 19:46:09 XXXHOST systemd[1]: iotedge.service: main process exited, code=exited, status=1/FAILURE
Feb 05 19:46:09 XXXHOST systemd[1]: Unit iotedge.service entered failed state.
Feb 05 19:46:09 XXXHOST systemd[1]: iotedge.service failed.
Feb 05 19:46:09 XXXHOST systemd[1]: iotedge.service holdoff time over, scheduling restart.
Feb 05 19:46:09 XXXHOST systemd[1]: start request repeated too quickly for iotedge.service
Feb 05 19:46:09 XXXHOST systemd[1]: Failed to start Azure IoT Edge daemon.
Feb 05 19:46:09 XXXHOST systemd[1]: Unit iotedge.service entered failed state.
Feb 05 19:46:09 XXXHOST systemd[1]: iotedge.service failed.

## Additional Information
All certificate files created by guide https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway
All folders and certificate files changed to owner/group iotedge

When certificates section is commented out, daemon starts normally.
Thanks...

**Comment by ondrejspilka** [comment]
Ah, I see, that's why I haven't been able to find any error log.
Once used `journatctl `without `-u iotedge` I was able to identify the issue.
My certs `private` folder was still under root as well as private keys.
When I issued
`chown iotedge /var/lib/iotedge/private`
`chgrp iotedge /var/lib/iotedge/private`
it runs smoothly.
Thanks for pointing me to the right direction.

Any chance to have all `iotedge` logs integrated in one tool so future diagnostics will be easier?

Thanks anyway, Ondřej

**Comment by myagley** [comment]
Yes, we are looking at getting the daemon's logs into the `iotedge` tool, so that you can get all of the logs in one place. This will happen in the next couple of months.

I'm going to close this issue for now, but please feel free to reopen it if you run into any more issues.
