### ISSUE TITLE
connectionState in Custom Module device twin is always showing as disconnected

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#809]
Hi,

I am looking to implement connection state of Edge gateway in device twin to check whether gateway is connected to IotHub or not.

## Expected Behavior
 connectionState should be updated as _Connected_ in Azure Edge device twin

## Current Behavior
 connectionState always showing as _Disconnected_ in Azure Edge device twin but it is working for IoT device in transparent gateway solution

### Device (Host) Operating System
 Ubuntu 16.04 

### Architecture
 amd64 

### Container Operating System
 Linux containers 

#### iotedged
 Run `iotedge version` 1.0.5

#### Edge Agent
 Image tag (i.e. 1.0.5) 

#### Edge Hub
 Image tag (i.e. 1.0.5) 

#### Docker
 Run `docker version` 3.0.2

## Logs
**Edge Device**  _Parent Device_

{
  "deviceId": "EdgeSimulator1",
  "etag": "AAAAAAAAAAE=",
  "deviceEtag": "MTAzNTA4Nzc1Ng==",
  "status": "enabled",
  "statusUpdateTime": "0001-01-01T00:00:00",
  **"connectionState": "Disconnected",**
  "lastActivityTime": "0001-01-01T00:00:00",
  "cloudToDeviceMessageCount": 0,
  "authenticationType": "sas",
  "x509Thumbprint": {
    "primaryThumbprint": null,
    "secondaryThumbprint": null
  }

**IoT Device**  _Leaf Device_

{
  "deviceId": "IoTSimulator1",
  "etag": "AAAAAAAAAAE=",
  "deviceEtag": "MjYwNjIzNDM0",
  "status": "enabled",
  "statusUpdateTime": "0001-01-01T00:00:00",
  **"connectionState": "Connected",**
  "lastActivityTime": "0001-01-01T00:00:00",
  "cloudToDeviceMessageCount": 0,
  "authenticationType": "sas",
  "x509Thumbprint": {
    "primaryThumbprint": null,
    "secondaryThumbprint": null
  }

<img width="1189" alt="screen shot 2019-02-06 at 17 53 23" src="https://user-images.githubusercontent.com/7486266/52341737-6a834100-2a39-11e9-80cb-e06966642872.png">

**Comment by myagley** [comment]
Nothing on IoT Edge connects with the device's identity, which means that this field will always show as disconnected.

A better proxy to use for connection status is to look at the Edge Agent's twin and its connection status. The Edge Agent keeps a persistent connection open listening for deployments.

One thing to keep in mind is that the connection status can be quirky. There are edge cases where it may not be 100% accurate. If you want to track connection status changes cloud-side, you may want to look at using IoT Hub's Event Grid integration: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-event-grid IoT Hub will publish events when devices connect and disconnect.

**Comment by pratson20** [comment]
@myagley I have implemented heartbeat packet for device state. I though to use connectionState in device twin. Is there any support is coming to identify the connectionState for GW in device twin for custom module?

You mean to say i can check device connectionState in edgeAgent module identity.

<img width="752" alt="screen shot 2019-02-07 at 00 19 10" src="https://user-images.githubusercontent.com/7486266/52365849-658cb480-2a6e-11e9-8c6b-3348660960c6.png">
