### ISSUE TITLE
Edge Hub Storage Capacity 

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#817]
Hi Team,
   We have created an Edge Module which is running in the Plant on PLC. And there is issue with connectivity and some time PLC is disconnected from IoT Hub for 10 days and during that time period the data is being stored on the Edge Hub. So could you please suggest the best way to us to store these data on Edge Gateway??

**Comment by veyalla** [comment]
@sachidanand Please see our docs around this: https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities#additional-offline-storage

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
