### ISSUE TITLE
Cannot start edge daemon

### ISSUE THREAD

**Issue by mlidia** [Azure/iotedge#818]
## Expected Behavior
Iotedge service running and connecting to iot hub.

## Current Behavior

404 not found error in the log of iotedge service
## Steps to Reproduce

1. I followed this guide https://gist.github.com/marktayl1/108bdb8a5a0cee8dc354a7b88d831043
2.
3.
4.

### Device (Host) Operating System

 Ubuntu 16.04,
### Architecture

arm64
#### iotedged

iotedge 1.0.6.1
#### Edge Agent

1.0.0
#### Docker

18.06.1-ce
## Logs

```
Feb 07 08:50:59 artik iotedged[3006]: 2019-02-07T08:50:59Z [INFO] - Checking edge runtime status
Feb 07 08:50:59 artik iotedged[3006]: 2019-02-07T08:50:59Z [INFO] - Edge runtime status is failed, starting module now...
Feb 07 08:50:59 artik iotedged[3006]: 2019-02-07T08:50:59Z [INFO] - Starting module edgeAgent...
Feb 07 08:51:00 artik iotedged[3006]: 2019-02-07T08:51:00Z [INFO] - Successfully started module edgeAgent
Feb 07 08:51:07 artik iotedged[3006]: 2019-02-07T08:51:07Z [INFO] - [work] - - -[2019-02-07 08:51:07.011402510 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 404 Not Found - "-" "-" pid(9824)
```

**Comment by myagley** [comment]
How are the `listen` and `connect` sections of your `config.yaml` configured? From the logs it looks like the Edge Agent is making this request on the workload socket instead of the management socket. This is most likely being caused by a mismatch in the `connect`/`listen` section for the management and workload uris.

**Comment by mlidia** [comment]
I didn't modify those parts of the config.yaml file.

Connect section is:
`connect:
 management_uri: "unix:///var/run/iotedge/mgmt.sock"
workload_uri: "unix:///var/run/iotedge/workload.sock"`

Listen section is:
`listen:
management_uri: "fd://iotedge.mgmt.socket"
workload_uri: "fd://iotedge.socket"`

**Comment by myagley** [comment]
How was IoT Edge installed? We don't have public packages for ARM64. In this setup it is important that systemd manages the domain sockets.

What version of systemd is on the system? Can you run `systemctl --version`?

**Comment by mlidia** [comment]
I followed this [link](https://gist.github.com/marktayl1/108bdb8a5a0cee8dc354a7b88d831043).

`[root@artik ~]# systemctl --version

systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN`

**Comment by myagley** [comment]
I just saw in the link provided that step 17 mentions setting the `LISTEN_FDNAMES` environment variable. This shouldn't be necessary and is likely causing this issue. Is it possible to remove this step? Your version of systemd should be compatible with these packages without setting this environment variable.

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
