### ISSUE TITLE
connection between iot edge gateway and iothub device 

### ISSUE THREAD

**Issue by chirazment** [Azure/iotedge#819]
hi,
i installed the certificate in my iotedge gateway , and when i type qn OpenSSl co;;and i got this .

```
pi@iotedgegateway:~ $ openssl s_client -connect port:8883 -CAfile /home/pi/WRKDIR/certs/azure-iot-test-only.root.ca.cert.pem -showcerts
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1549532660
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```
what is the difference between the gateway"s IPadress and the hosname cuz in the connection string when i use the ip adress of my gateway the client has been connected but when i use the hostname i get this ;

```
Creating IoTHub handle
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -3.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway.
The device client has been disconnected
Sending message 1 to Edge Hub
Sending message 2 to Edge Hub
Sending message 3 to Edge Hub
Sending message 4 to Edge Hub
Sending message 5 to Edge Hub
Sending message 6 to Edge Hub
Sending message 7 to Edge Hub
Sending message 8 to Edge Hub
Sending message 9 to Edge Hub
Sending message 10 to Edge Hub
Sending message 11 to Edge Hub
Sending message 12 to Edge Hub
Sending message 13 to Edge Hub
Sending message 14 to Edge Hub
Sending message 15 to Edge Hub
Sending message 16 to Edge Hub
Sending message 17 to Edge Hub
Sending message 18 to Edge Hub
Sending message 19 to Edge Hub
Sending message 20 to Edge Hub

Press any key to continue
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -3.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway.
The device client has been disconnected
```
i m using the latest version of iotedge 1.0.6-1and the sa;e for SDK 1.2.13

**Comment by myagley** [comment]
What is the value of the `hostname` field in the `/etc/iotedge/config.yaml`? Can you try running the following, replacing the `<hostname>` with the value from the `config.yaml`:

`openssl s_client -connect <hostname>:8883 -CAfile /home/pi/WRKDIR/certs/azure-iot-test-only.root.ca.cert.pem -showcerts`

**Comment by chirazment** [comment]
same result , even with hostname's value in config.yaml ,t got the same result .
What about the second problem : 
Creating IoTHub handle
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -3.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:29:34 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway.
The device client has been disconnected
Sending message 1 to Edge Hub
Sending message 2 to Edge Hub
Sending message 3 to Edge Hub
Sending message 4 to Edge Hub
Sending message 5 to Edge Hub
Sending message 6 to Edge Hub
Sending message 7 to Edge Hub
Sending message 8 to Edge Hub
Sending message 9 to Edge Hub
Sending message 10 to Edge Hub
Sending message 11 to Edge Hub
Sending message 12 to Edge Hub
Sending message 13 to Edge Hub
Sending message 14 to Edge Hub
Sending message 15 to Edge Hub
Sending message 16 to Edge Hub
Sending message 17 to Edge Hub
Sending message 18 to Edge Hub
Sending message 19 to Edge Hub
Sending message 20 to Edge Hub

Press any key to continue
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:277 Failure: getaddrinfo failure -3.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:760 lookup_address_and_connect_socket failed
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Thu Feb  7 09:29:35 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2261 failure connecting to address iotedgegateway.
The device client has been disconnected

this is happened why i try to connect my downstream device with the iotedge gateway using the hostname's value in config.yml in my connection string

**Comment by myagley** [comment]
This looks like it is failing to resolve the hostname to an ip address. Is your downstream device a physically separate device? You may need to add the gateway's hostname to the downstream device's `/etc/hosts` file to get the downstream device to connect.

**Comment by chirazment** [comment]
yup the downstream device was installed seperaly on  a rasspberry pi 3 and the gateway on another rasspberry ,so as i understand from your answer i shoud to add the hosname's gateway to /etc/hosts but this field where will i  find it? in myedge device or in the other rassberry ?

**Comment by chirazment** [comment]
hii @myagley : 
thank you , now it is working but i have another problem.
when i connect the device hub to the gateway it works in the first time but when i try it for another time t got this : 

This sample will send 20 messages and wait for any C2D messages.
Press the enter key to end the sample

Creating IoTHub handle
Sending message 1 to Edge Hub
Sending message 2 to Edge Hub
Sending message 3 to Edge Hub
Sending message 4 to Edge Hub
Sending message 5 to Edge Hub
Sending message 6 to Edge Hub
Sending message 7 to Edge Hub
Sending message 8 to Edge Hub
Sending message 9 to Edge Hub
Sending message 10 to Edge Hub
Sending message 11 to Edge Hub
Sending message 12 to Edge Hub
Sending message 13 to Edge Hub
Sending message 14 to Edge Hub
Sending message 15 to Edge Hub
Sending message 16 to Edge Hub
Sending message 17 to Edge Hub
Sending message 18 to Edge Hub
Sending message 19 to Edge Hub
Sending message 20 to Edge Hub

Press any key to continue
The device client has been disconnected
The device client has been disconnected
Error: Time:Sun Feb 10 16:40:08 2019 File:/home/pi/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2341 mqtt_client timed out waiting for CONNACK
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR




the second probleme that i still have it it's about the certificate i still have : 

pi@iotedgegateway:~ $ openssl s_client -connect port:8883 -CAfile /home/pi/WRKDIR/certs/azure-iot-test-only.root.ca.cert.pem -showcerts
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1549532660
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

even if i use <hostname'sgateway>:8883

thank you

**Comment by mrohera** [comment]
* The sample you have referenced above is suitable for connecting to the IoT Hub and must be tailored to work for connecting to the Edge. 

* Here is another sample that is well suited for connecting a device directly to the Edge gateway. https://github.com/Azure/iotedge/tree/master/samples/dotnet. 

* This sample is effectively the same sample as you have used above but it handles certificate installation and also deals with handling of the connection string with the Edge gateway hostname.

* I would suggest you try this and report any issues and we would be glad to help.  For you reference, here is the documentation that talks about connecting a downstream device to the Edge https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device

**Comment by chirazment** [comment]
thank you , i will try to do it and report you what i will have

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
