### ISSUE TITLE
Could not create module edgeAgent

### ISSUE THREAD

**Issue by royzangnxp** [Azure/iotedge#826]
## Expected Behavior

After iotedge installation, there should be edgeAgent and edgeHub as default module.

## Current Behavior

No any module inside.
## Steps to Reproduce

1.  follow the steps:
  https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm
2. sudo systemctl restart iotedge

### Device (Host) Operating System

Ubuntu 16.04
### Architecture

arm32
### Container Operating System

Linux containers

#### iotedged

root@nxp-iot-imx8mm:~# iotedge --version
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Docker

root@nxp-iot-imx8mm:~# docker version
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 17:16:17 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       74baf62
  Built:            Tue Dec  4 23:30:17 2018
  OS/Arch:          linux/arm
  Experimental:     false

## Logs

root@nxp-iot-imx8mm:~# sudo systemctl status iotedge
��● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: 
   Active: active (running) since Thu 2019-02-07 21:55:54 UTC; 4min 49s ago
     Docs: man:iotedged(8)
 Main PID: 4268 (iotedged)
    Tasks: 11
   Memory: 10.4M
      CPU: 156ms
   CGroup: /system.slice/iotedge.service
           ��└��─4268 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Feb 07 21:59:54 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:54Z [INFO] - Upd
Feb 07 21:59:54 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:54Z [INFO] - Pul
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [INFO] - Suc
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [INFO] - Cre
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [WARN] - Cou
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [WARN] -    
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [WARN] - Err
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [WARN] - A m
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [WARN] -    
Feb 07 21:59:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T21:59:55Z [WARN] - 

root@nxp-iot-imx8mm:~# cat /var/log/syslog |tail
Feb  7 22:01:54 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:54Z [INFO] - Updating identity for module $edgeAgent
Feb  7 22:01:54 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:54Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0...
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.0
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [INFO] - Creating module edgeAgent...
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [WARN] - Could not create module edgeAgent
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [WARN] - #011caused by: Conflict with current operation
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [WARN] - Error in watchdog when checking for edge runtime status:
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [WARN] - A module runtime error occurred.
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [WARN] - #011caused by: Could not create module edgeAgent
Feb  7 22:01:55 nxp-iot-imx8mm iotedged[4268]: 2019-02-07T22:01:55Z [WARN] - #011caused by: Conflict with current operation

**Comment by darobs** [comment]
Hello @royzangnxp,
 
It looks like we're not reporting the message associated with the CONFLICT response.

Would you please get the docker logs (typically `sudo journalctl -r -u docker` or see [here](https://docs.docker.com/config/daemon/#read-the-logs) for other places) to see what the error from docker create is reporting?

**Comment by royzangnxp** [comment]
I remove my previous iotedgectl and it works.
