### ISSUE TITLE
"Module not found" When running arm32v7 image

### ISSUE THREAD

**Issue by mortslhawmit** [Azure/iotedge#83]
I've upgraded from preview to GA and have run in to an issue with running iotedge images on my RPI3, the solution works fine if I run on a local repo with the amd64.debug images on my windows machine but when I try to run my arm32v7 images on my RPI I get an error as soon as one of my custom modules run OpenAsync on the ModuleClient.

## Steps to Reproduce
1. I build the solution with arm32v7 images in the deployment template, with azure container registry credentials.
2. I deploy to IoTEdge device (RPI3).
3. Wait for IoTEdge device to get images.
4. Getting the error when the image starts and tries to OpenAsync.

### Device (Host) Operating System
RPI3 rasbian

### Architecture
arm32

### Container Operating System
linux containers

#### iotedged
1.0.0

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
Docker version 18.02.0-ce, build fc4de44

## Logs
Error recevied when image starts, this is revieved as soon as "OpenAsync" is called on my ModuleClient.
> Unhandled Exception: System.AggregateException: One or more errors occurred. (Error calling SignAsync: Module not found, StatusCode: 404) ---> Microsoft.Azure.Devices.Client.HsmAuthentication.HttpHsmComunicationException: Error calling SignAsync: Module not found, StatusCode: 404

## Additional Information
I'm using AMQP as mentioned [here](https://github.com/Azure/iotedge/issues/70)
```
var amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
ITransportSettings[] settings = { amqpSetting };

var moduleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
await moduleClient.OpenAsync();

```

**Comment by varunpuranik** [comment]
This typically indicates that the Iotedged was not able to identify your custom module. Can you copy the iotedged logs here? That should tell us more. You can get them using $>journalctl -u iotedge -f
My guess is your module might have multiple processes in it. The iotedged requires the first process in the container to communicate with it (as a security feature).

**Comment by mortslhawmit** [comment]
I spoke to soon, i forgot that i ran a bashscript to start my .dll file because i want to start some services before i run the module, so I just added "exec" before my "dotnet mycostommodule.dll" and now it all works fine. 
Thanks for your time!

**Comment by prashbv** [comment]
Is this issue resolved ?  I am looking for solution on the same issue.

Thanks

**Comment by mortslhawmit** [comment]
@prashbv It is solved for me lite i said i had a script that i ran before starting the module that led having multiple processes, so i changed my script and got it to work.
