### ISSUE TITLE
AmqpWs proxy authentication - log file reports credential usage; nonetheless tcpdump shows that authentication isn't working

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#852]
I'm behind a corporate proxy so I configured the edge node as suggested (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support). However I doubt that the the proxy_host in format user:password@proxy_host is used correctly everywhere - still it should work as https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support documents.

/etc/iotedge/config.yaml:

> https_proxy: "http://user:password@proxy-server:8080/"                                                                                     
> UpstreamProtocol: "AmqpWs"

Logging of the azure IOT Edge container:

```2020-07-08 08:02:55  Starting Edge Agent
2020-07-08 08:02:55.712 +00:00 Edge Agent Main()
<6> 2020-07-08 08:02:55.924 +00:00 [INF] - Initializing Edge Agent.
<6> 2020-07-08 08:02:56.111 +00:00 [INF] - Version - 1.0.9.3.32101608 (ad04e23b1865211913282b918263700deafdccfa)
<6> 2020-07-08 08:02:56.112 +00:00 [INF] -
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2020-07-08 08:02:56.136 +00:00 [INF] - Detected proxy http://[user]:****@[proxy]:8080/
<6> 2020-07-08 08:02:56.183 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false,"EnableGetLogs":false,"EnableMetrics":false}
<6> 2020-07-08 08:02:56.353 +00:00 [INF] - Installing certificates [CN=Test Edge Owner CA:09/21/2020 08:44:29] to Root
<6> 2020-07-08 08:02:56.838 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2020-07-08 08:02:56.913 +00:00 [INF] - Started operation refresh twin config
<6> 2020-07-08 08:02:56.936 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<6> 2020-07-08 08:02:57.003 +00:00 [INF] - Registering request handler RestartModule
<4> 2020-07-08 08:03:02.160 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:03:02.167 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-08 08:03:12.187 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:03:12.187 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-08 08:03:22.189 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:03:22.189 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-08 08:03:32.190 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:03:32.190 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<6> 2020-07-08 08:03:33.233 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<4> 2020-07-08 08:03:42.191 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:03:42.191 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-08 08:03:52.192 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:03:52.192 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-08 08:04:02.194 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:04:02.194 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
<4> 2020-07-08 08:04:12.196 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup file (backup.json) instead
<6> 2020-07-08 08:04:12.196 +00:00 [INF] - Edge agent config backup file does not exist - backup.json
```

If I take a look at the tcpdump I see that the proxy is answering with a "HTTP/1.1 407 Proxy Authentication Required" to the connect request of the edgeAgent container - but the connect from the edgeAgent doesn't provide an authentication header (also it should).

My guess is that the edge correctly detects the proxy credentials (proofed by the logging line _"Detected proxy http://[user]:****@[proxy]:8080/"_) but for whatever reason doesn't use the provided credentials to connect via AmqpWs to the IotHub.

## Expected Behavior
EdgeAgent should be able to connect to the cloud via amqp-ws trough the proxy.

## Current Behavior
Credentials didn't seem to make it to the connect telegram to the proxy.

## Steps to Reproduce
Setup a proxy that enforces basic authentication; or just configure username/password and dump the CONNECT telegram of the AmqpWs connection.

### Device Information
* Host OS:  RHEL7
* Architecture: x86_64
* Container OS: Linux containers

### Runtime Versions
* iotedged: iotedge 1.0.9.3
* Edge Agent: mcr.microsoft.com/azureiotedge-agent:1.0.9.3
* Docker/Moby: 
```Client:
 Version:           3.0.13+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
 Built:             Thu May 28 20:41:25 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fda0c
  Built:            Mon Jun  1 20:22:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Logs
See information above.

**Comment by alaendle** [comment]
Forgot to configure the proxy in the deployment manifests - sorry.

**Comment by veyalla** [comment]
@alaendle were you able to resolve this or is it still an issue?

**Comment by alaendle** [comment]
@veyalla Thanks for asking; I encountered this problem first in February 2019, but then we used a proxy without authentication and everything works fine - so I was no longer sure what exactly the problem was and closed this issue (to save you effort). Since I'm now encouraged to use a proxy with authentication I remembered this issue, and was able to reproduce it as the updated logs and version numbers in the issue description reflects. Sorry if this proceeding lead to confusion. And as always, please don't hesitate to contact me if you encounter questions or is I could contribute anything to further track down the issue.

**Comment by R25l84IHeXjIxy6HO1QXn0y0Dq9mt8EN** [comment]
It seems that whatever proxy settings are specified are passed through to a `Microsoft.Azure.Devices.Client.ModuleClient` in the form of an `ITransportSettings[]`. The flow that I can see is as follows:

1. `Microsoft.Edge.Devices.Edge.Agent.Service.Program` parses the configuration and extracts `https_proxy`, `UpstreamProtocol`: [source](https://github.com/Azure/iotedge/blob/10cf7779f6999da5a466e6f87bc1736ed9ad19ed/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs#L135-L136)
2. (Assuming `iotedged` mode) These are passed into a `Microsoft.Azure.Devices.Edge.Agent.Service.EdgeletModule`: [source](https://github.com/Azure/iotedge/blob/10cf7779f6999da5a466e6f87bc1736ed9ad19ed/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs#L169)
3. `EdgeletModule` creates a `Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClientProvider` using the proxy and protocol information: [source](https://github.com/Azure/iotedge/blob/10cf7779f6999da5a466e6f87bc1736ed9ad19ed/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs#L89-L90)
4. `ModuleClientProvider` uses these to [initialize a connection configuration](https://github.com/Azure/iotedge/blob/8a7c3972498a43d410bd79fa1b078f09f797eede/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs#L107-L117)
5. All relevant code paths in `ModuleClientProvider` converge to [`CreateAndOpenSdkModuleClient`](https://github.com/Azure/iotedge/blob/8a7c3972498a43d410bd79fa1b078f09f797eede/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs#L201) which invokes `Microsoft.Azure.Devices.Edge.Agent.IoTHub.SdkClient.SdkModuleClientProvider.GetSdkModuleClient` with the [transport settings](https://github.com/Azure/iotedge/blob/8a7c3972498a43d410bd79fa1b078f09f797eede/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs#L203): [source](https://github.com/Azure/iotedge/blob/8a7c3972498a43d410bd79fa1b078f09f797eede/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs#L206-L208)
6. `SdkModuleClientProvider.GetSdkModuleClient` calls into `Microsoft.Azure.Devices.Client.ModuleClient`, which is an external SDK

This suggests that this is an issue for the IoT Hub SDK developers, unfortunately.

**Comment by alaendle** [comment]
Thanks @R25l84IHeXjIxy6HO1QXn0y0Dq9mt8EN for your profound investigation. I'm not 100% sure if comment is addressed to me (or just a piece of writing to document your results); since basically my experience is that the image mcr.microsoft.com/azureiotedge-agent doesn't work as expected. So I think it is asking too much to be able (as an end-user) to place the issue at the repo that owns the code that may be the root of the problem. If you need an upstream fix it would be very helpful if you could create an issue on the upstream project yourself - not to save me work, but because I think that might have more weight, may be more accurate (because of your deep-dive) and also gives you notifications about fixes that should be included in your project. I'm more than willing to contribute and support you to solve the problem, so please just tell me if I could do anything. I really believe our interests match here.

**Comment by R25l84IHeXjIxy6HO1QXn0y0Dq9mt8EN** [comment]
My apologies, I should have added some front-matter explaining my comment. I agree wholeheartedly that this is a problem; my intention was to provide some additional background for other developers on the project.

I will open an issue in the SDK repository and link it here for tracking.
