### ISSUE TITLE
Installing Edge runtime on Windows breaks power management

### ISSUE THREAD

**Issue by wickste** [Azure/iotedge#854]
Once I install the Edge runtime on Windows (set to use Windows containers) on my dev machine (laptop in my case), the machine no longer goes to sleep. Even when I close the lid, the machine keeps running which is a battery life, data loss as well as a security concern (as it won't automatically go to the lockscreen anymore). After uninstalling the Edge runtime the behavior is back to normal.

## Expected Behavior

Edge runtime should not interfere with how/when the OS goes to low power states / sleep.

## Current Behavior

Windows OS no longer goes to sleep once the Edge runtime is installed.

## Steps to Reproduce

1. Install Edge runtime on Windows (set to use Windows containers)
2. Attempt to put system to sleep (either by closing the laptop lid, or by Start->Shutdown->Sleep
3. Result: system does not go to sleep

## Context (Environment)
Windows 10 dev machine

### Device (Host) Operating System

Windows 10 Enterprise Update 1809 (build 17763.316

### Architecture
AMD64

### Container Operating System
Windows

### Runtime Versions
???

#### iotedged
1.0.6.1

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
3.0.2

**Comment by myagley** [comment]
Thanks for the issue. We are investigating.

**Comment by arsing** [comment]
1. Please post event logs of the iotedge service +/- 5 minutes around the time you closed your laptop's lid. (You can get these in a script with `Get-WinEvent`.) If the service received a `SERVICE_CONTROL_SHUTDOWN`, then it would log that and we can see why it didn't finish stopping.

1. Please post the result of the following command:

    ```powershell
    (Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control').'WaitToKillServiceTimeout'
    ```

    On my machine this is 5000 = 5 seconds, so if the service did receive a SHUTDOWN control but remained in `STOP_PENDING` state, MSDN implies Windows would wait this long before forcing shutdown. (However MSDN says this applies in the context of rebooting the machine, so I'm not sure it would also apply for going to sleep.)

**Comment by arsing** [comment]
As discussed offline, currently Windows machines running nanoserver-based containers (which edge agent and edge hub are) cannot go to sleep. So this behavior is currently expected.

Stopping the service (`Stop-Service iotedge`) before sending the machine to sleep should work, since stopping the service stops those two containers (and any other nanoserver-based module containers).

**Comment by myagley** [comment]
This has been addressed for the time being with a warning message in the 1.0.7 installer.
