### ISSUE TITLE
How to use serial port and usb  with  Nano server container on iotedge?

### ISSUE THREAD

**Issue by LiangJy123** [Azure/iotedge#859]
Hi, 
     I have a question that my program is running in nano server container and I need to access the hardware by using serial port and USB.
     Does iotedge support this?
     if it supports, how can i config my iotedge ( dockerfile,deployment.json...etc )?
Thanks.

### Device (Host) Operating System
win10 1809

### Architecture
windows-amd64

### Container Operating System

Windows containers ,nano server 1809 

#### iotedged
iotedge 1.0.6.1

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker

moby engine 

## Additional Information

it's a virtual serial port  and the hareware is using USB.

**Comment by jackt-moran** [comment]
I've been doing this using Docker bind-mounts (https://docs.docker.com/storage/bind-mounts/)

The following is how I do it within deployment.template.json (warning: it may not be valid json). This will make the entire `/host_directory` directory in the host available in your sampleModule container's `/container_directory` directory. If you need a different directory just change the names. You may also need to add your container user to a group to have proper permissions for the serial ports.

```
"modules": {
          "sampleModule": {
            "version": <>,
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": <>,
                  "createOptions": {
                        "HostConfig": {
                             "Binds": [
                                 "/host_directory:/container_directory"
                             ],
                             "Privileged": true
                       }
                 }
             }
         }
}      
```

Has anyone been able to do this without setting the `Priveleged` attribute to `true`? Or does anyone have a better recommendation on how to do this in general?

**Comment by myagley** [comment]
@LiangJy123 I'll follow up with the nano server team to see how to provide serial port access on windows.

@jackt-moran the issue you are most likely running into with needing Privileged true is a permissions issue on the host directory. The host directory needs to have the proper permissions for the user running inside the container. A quick test is to `chmod 777 /host_directory` and see if you can remove the privileged flag, then tighten up the permissions for your user later. Are you trying to access files on the filesystem or actually access to a device (in /dev)?

**Comment by myagley** [comment]
@LiangJy123 there is an example module in this repo that uses a serial port on a nano server container: https://github.com/Microsoft/Windows-iotcore-samples/blob/develop/Samples/EdgeModules/SerialWin32/CS/README.md

This gives an example for the createOptions required to gain access to the serial port.

**Comment by LiangJy123** [comment]
Thank you for providing useful documentation!  I can list my device in the container now.
I will try to communicate with my device later.
