### ISSUE TITLE
Install issue on iot-core RPi3 (supported)

### ISSUE THREAD

**Issue by PtwHub** [Azure/iotedge#876]
Hi, ran into the following error installing on supported iot-core and RPi3. See the precise screen flow and the log below. Thanks for any tips.

https://docs.microsoft.com/en-us/azure/iot-edge/support "Azure IoT Edge runs great on devices as small as a Raspberry Pi3 to server grade hardware"

![image](https://user-images.githubusercontent.com/26715077/53243809-541bed00-36a9-11e9-8987-69118613c619.png)

[172.16.10.195]: PS C:\Data\Users\Administrator\Documents>
[172.16.10.195]: PS C:\Data\Users\Administrator\Documents>
[172.16.10.195]: PS C:\Data\Users\Administrator\Documents>
[172.16.10.195]: PS C:\Data\Users\Administrator\Documents> . {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expre
ssion; `
>> Install-SecurityDaemon -Dps -ContainerOs Windows -ScopeId 0ne00048CA8 -RegistrationId ggiotcore3-registration-id

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        IotEdgeSecurityDaemon               {Install-SecurityDaemon, Uninstall-SecurityDaemon}
The container host is on supported build version 17763.
Downloading Moby Engine...
Using Moby Engine from C:\Data\Users\Administrator\AppData\Local\Temp\iotedge-moby-engine.zip
Downloading Moby CLI...
Using Moby CLI from C:\Data\Users\Administrator\AppData\Local\Temp\iotedge-moby-cli.zip
Downloading IoT Edge security daemon...
Using IoT Edge security daemon from C:\Data\Users\Administrator\AppData\Local\Temp\iotedged-windows.zip
Skipping VC Runtime installation on IoT Core.
Generating config.yaml...
Configured device for DPS provisioning.
Configured device with hostname 'ggiotcore3'.
Configured device with Moby Engine URL 'npipe://./pipe/iotedge_moby_engine' and network 'nat'.
Updated system PATH.
Added IoT Edge registry values.
Service 'iotedge (iotedge)' cannot be started due to the following error: Cannot start service iotedge on computer '.'.
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

[172.16.10.195]: PS C:\Data\Users\Administrator\Documents>

**Comment by veyalla** [comment]
Windows ARM32 (e.g. Windows IoT Core on RPi) is not yet supported with IoT Edge. 

IoT Core X64 is supported, currently in Preview.

**Comment by PtwHub** [comment]
Thanks, my oversight on the X64.
