### ISSUE TITLE
IoT edge (offline storage) Edgehub cannot connect to storageFolder 

### ISSUE THREAD

**Issue by saikovvuri** [Azure/iotedge#882]
## Expected Behavior
Edge Hub should be able to connect to the custom storage folder specified in the config.

## Current Behavior
Looking at the edgehub dockerfile - https://github.com/Azure/iotedge/blob/master/edge-hub/docker/linux/amd64/Dockerfile

it appears that edge hub service runs under the account edgehubuser which at boot is not configured to have write access to the custom storage location.

## Steps to Reproduce
1. Configure IoT edge with offline storage 

![image](https://user-images.githubusercontent.com/7659507/53289378-1081bb80-375b-11e9-8edf-edec18bfe8b8.png)

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
1.0.6

#### Edge Agent
1.0.6

#### Edge Hub
1.0.6

#### Docker
Docker version 3.0.3, build 48bd4c6d

## Logs
Unhandled Exception: System.AggregateException: One or more errors occurred. (Ac                                                                                                                                                             cess to the path '/iotedge/storage/edgeHub' is denied.) ---> System.Unauthorized                                                                                                                                                             AccessException: Access to the path '/iotedge/storage/edgeHub' is denied. ---> S                                                                                                                                                             ystem.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Azure.Devices.Edge.Hub.Service.DependencyManager.GetStoragePath(                                                                                                                                                             ) in /home/vsts/work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/D                                                                                                                                                             ependencyManager.cs:line 217

## Additional Information
temporary fix : sudo chmod o+w /etc/iotedge/storage/

**Comment by veyalla** [comment]
Hi @saikovvuri - this is expected behavior. I'll augment our docs to mention that user in the edgeHub container should have write access to the storage folder.

**Comment by saikovvuri** [comment]
Hey Venkat, thanks for the prompt response.  
so just a correction,  i had to assign group level access to the folder,   chmod g+w /etc/iotedge/storage. 

so 2 follow up questions:
- is the edgehubuser is added to the "root" group and that is why after assigning the current group which is "root" write access, it started working
- secondly any reason why this step cannot be added when the container is being created and initialized. 

Thanks

**Comment by myagley** [comment]
We can look at how we can set the permissions on the host. However, none of the components run as root (by design) so this may not be feasible, and I think we would be a little hesitant to start changing directory permissions on the host. We will have to investigate.

In the meantime, the intention is that this storage location on the host should be provisioned with the proper permissions so that it is writable by the user in the container. This is entirely in your control. The default location works out of the box, but any changes to the default need to ensure the permissions are set properly. The requirement is that `edgehubuser (uid=1000)` needs `rw` on the storage directory on the host.
