### ISSUE TITLE
How to reject a message in custom c# module 

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iotedge#884]
In my understanding with AMQP a client should be able to either **ACCEPT**, **REJECT** or **ABANDON** a message.
An **accepted** messages should be removed from the message queue because it has been handled successfully. A **rejected** message could not be handled successfully but should not be readded to the message queue because it cannot be handled no matter how often it is received. An **abandoned** message could not be handled successfully at the moment but should be readded to the queue to retry again later.
Is this understanding correct?

I'm implementing custom iotedge modules in C#.  The MessageResponse class only lets me choose one of the following:
- **None**
- **Completed** 
- **Abandoned**

I cannot find a way to REJECT a message.  I would think that both None and Abandoned would re-add the message to the queue again.  Is this the case?

Is there a way to reject a message or do I have to choose Completed to get it out of the message queue even though it could not be handled successfully?

**Comment by myagley** [comment]
`None` doesn't send any response at all. This is intended to be used when you would like to send a response from outside of the callback function (for whatever reason).

In this case, you will need to call `Completed` to remove it from the queue.
