### ISSUE TITLE
The different between docker-ce and microsoft-moby

### ISSUE THREAD

**Issue by v-jiq** [Azure/iotedge#887]
Background:
I want to run iotedge on a device with arm64 platform and it is completed. but the container engine  is docker-ce(arm64) beacuse microsoft not provide arm64 moby. So ,Microsoft doesn't acknowledge the action.

I Want know the differ between microsoft-moby and docker-ce, but i can't find the the source code of  microsoft-moby , or who can tell me the different of them.

I can find the docker-ce source code：https://github.com/moby/moby. but can't find micosoft moby source code.

Thanks!

**Comment by veyalla** [comment]
@v-jiq The moby-engine supplied with IoT Edge is Microsoft built and supported container engine. As the license for it states, it is licensed to be only used in conjunction with other MS services. The repo is not public, but It is currently built from the same code base as upstream moby/moby.

Any production deployment of IoT Edge must use MS moby-engine to be considered a supported configuration.

**Comment by v-jiq** [comment]
Thanks your feedback！！@veyalla

**Comment by LaurentLesle** [comment]
@veyalla I understand the moby-engine is a fork of the upstream moby/moby version. Where can I track the mapping of the moby-engine tags like 3.0.4, 3.0.6 and so on with the upstream moby version?
