### ISSUE TITLE
Slow performance of IoTEdge on running modules in Raspberry Pi 3+

### ISSUE THREAD

**Issue by gadgetman4u** [Azure/iotedge#891]
## Expected Behavior
IoTEdge modules in Python deployed through Docker should run at least in couple of minutes after deployed.

## Current Behavior
IoTEdge modules in Python after deployment using Microsoft Code to IoTHub, takes up to 30 minutes before the IoTEdge modules run. 

## Steps to Reproduce
1.  Delete all the IoTEdge modules from the IoTHub in Azure portal
2. Clean the docker system by using "sudo docker system prune -a"
3. Reboot the Raspberry Pi.
4. Go to Microsoft Code, build and push IoTEdge solution from deployment.config.json
5. Go to Azure IoTHub devices, select the Raspberry Pi device in Microsoft Code and right click to "Create Single Deployment on Device".  
6. Connect to Raspberry Pi and type "sudo iotedge list".  It shows the edgeHub and edgeAgent are running.
7. Repeatedly type "sudo iotedge list" to see if the other IoTEdge modules show up.  They won't but sometimes I do see that edgeHub failed so I restart edgeHub.
8. I even sometimes decide to restart IoTEdge by typing:

sudo systemctl daemon-reload
sudo systemctl restart iotedge

9. After maybe 5 minutes or so (I've seen up to 20 minutes), then I will see my IoTEdge modules show up, but some of them will say "stopped" or "failed" as status.  So I restart those modules.

10. If the IoTEdge modules don't say "running" as status, then I either restart those modules or even restart IoTEdge.  

11. Then usually after about 30 minutes, I finally see that the IoTEdge modules are running, but sometimes it takes couple of minutes before I see data being output from the module.

### Device (Host) Operating System
Raspbian GNU/Linux 9 (stretch)

### Architecture
arm32v7

### Container Operating System
Docker containers, Docker version 3.0.2 build e042b58f

#### iotedged
iotedge 1.0.4

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
3.0.2 build e042b58f

## Logs
I can share logs if needed.

## Additional Information

**Comment by ancaantochi** [comment]
Hi @gadgetman4u,

The modules images have to be pulled when there is a new deployment and this might take a while depending on the network speed. 
In the deployment you can set status of the module as stopped so those modules won't be started by the deployment, can you please check that all modules are set as running in the deployment?

Please share logs so I can investigate why some of the modules fail after they are started (edgeAgent, edgeHub and failed module logs).

Thanks

**Comment by lt72** [comment]
Closing this issue as it seems stale. Please re-open as needed.
