### ISSUE TITLE
ENOENT when accessing WORKLOADURI with Node.js module on Windows containers

### ISSUE THREAD

**Issue by Griffrez** [Azure/iotedge#894]
I'm attempting to use Node.js modules using Windows as the underlying host operating system.

I've successfully booted the module under the IoT Edge environment, but now I have an issue where I get the following error when running Client.fromEnvironment:
```
Error: connect ENOENT /C:/ProgramData/iotedge/workload/sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

I noticed that there's a forward slash at the beginning of the path and that is probably part of the problem.

## Expected Behavior
Client.fromEnvironment should work without any issues.

## Current Behavior
Client.fromEnvironment throws an exception:
```
Error: connect ENOENT /C:/ProgramData/iotedge/workload/sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

## Steps to Reproduce
1. Run the example Node.js module solution create by the Azure IoT Edge Visual Studio Code extension under a Windows machine.
2. Get the error showing up under "iotedge logs \<module\>".

### Device (Host) Operating System
Windows 10 Enterprise 1809

### Architecture
windows-amd64

### Container Operating System
Windows containers

#### iotedged
1.0.6.1

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by myagley** [comment]
Hello. Thank you for the issue. This seems like an issue in the node SDK. Is it possible to repost this issue over at https://github.com/Azure/azure-iot-sdk-node/issues?

**Comment by Griffrez** [comment]
Thank you for your response and sorry for the misunderstanding. 

I've added an issue on that repository talking about the problem: Azure/azure-iot-sdk-node#500.

I don't know if the issue is just Node.js SDK's fault. Might also have to do with the IOTEDGE_WORKLOADURI environment variable passed over by the IoT Edge runtime.

**Comment by myagley** [comment]
The `IOTEDGE_WORKLOADURI` is set directly from the `connect.workload_uri` setting in the `config.yaml`. I'm guessing this contains the extra `/`. Is it possible to see this setting in your config.yaml?

**Comment by Griffrez** [comment]
I don't have the project on me right now, so I can only share that with you on Monday.

Either way, while doing my investigation, I removed the `/` from the pathname the URL parser retrieved but it generated some other error, so maybe even if the slash problem is fixed, there's another layer to it.

**Comment by Griffrez** [comment]
The workload uri matches the uri in the `config.yaml` file in the repository. [config.yaml](https://github.com/Azure/iotedge/blob/master/edgelet/contrib/config/windows/config.yaml)

Therefore, I suppose it really has something to do with the Node.js SDK. But it's difficult to be sure.

**Comment by avranju** [comment]
This should work once support for Unix Domain Sockets lands in the Node.js SDK on Windows. Do you think its OK to close this issue here and continue tracking this on the Node SDK repo?

**Comment by Griffrez** [comment]
Sounds good to me.
