### ISSUE TITLE
can't pull edgebuilds.azurecr.io/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu:ubuntu16.04-1

### ISSUE THREAD

**Issue by xiaofengren** [Azure/iotedge#899]
I'm trying to build libiothsm for arm64 platform, it will report following error:

Error: image gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu:ubuntu16.04-1 not found
Looks like the docker images can't be pulled, do I need login to "edgebuilds.azurecr.io" container registry?

## Steps to Reproduce

1. Clone source code of iotege to my arm64 platform
2. follow devguide to build edgelet on my arm64 platform
3. run "cargo build --all", it show build pass
4. try to run "build/linux/ubuntu16.04/aarch64/package-libiothsm.sh"

## Context (Environment)
my arm64 platform and boot system with ubuntu 16.04 rootfs

### Device (Host) Operating System

Ubuntu 16.04
### Architecture

arm64 

### Container Operating System

Ubuntu 16.04

**Comment by myagley** [comment]
Yes, this image is currently in a private container registry. In the meantime, you can build this image locally: https://github.com/Azure/iotedge/tree/master/edgelet/build/linux/docker/cross-compile

You can call the build script like so:

```
./containers.sh Dockerfile.ubuntu16.04.aarch64-unknown-linux-gnu ubuntu16.04-1
```

**Comment by xiaofengren** [comment]
Thank you so much for your quick response. I'm able to build docker image.
