### ISSUE TITLE
docker pull mcr.microsoft.com/azureiotedge-agent:1.0 failed due to x509 certificate issue

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#906]
Hi, 

I am installing IoT Edge on RHEL using https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux.

I installed Moby from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-engine-3.0.2-centos.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-cli-3.0.2-centos.x86_64.rpm

I installed IoT Edge runtime from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/libiothsm-std-1.0.6.1-1.el7.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/iotedge-1.0.6.1-1.el7.x86_64.rpm

Output of the status of IoT Edge (systemctl status iotedge): 
● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/usr/lib/systemd/system/iotedge.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/iotedge.service.d
           └─override.conf
   Active: active (running) since Mon 2019-03-04 00:00:53 UTC; 13s ago
     Docs: man:iotedged(8)
 Main PID: 19886 (iotedged)
    Tasks: 9
   Memory: 5.0M
   CGroup: /system.slice/iotedge.service
           └─19886 /usr/bin/iotedged -c /etc/iotedge/config.yaml

Mar 04 00:00:55 devbox iotedged[19886]: 2019-03-04T00:00:55Z [INFO] - Pulling image mcr.microsoft.com/azureiotedge-agent:1.0...
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [INFO] - Successfully pulled image mcr.microsoft.com/azureioted...ent:1.0
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [INFO] - Creating module edgeAgent...
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [DBUG] - [edgelet_docker::runtime] Creating container edgeAgent...ent:1.0
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [WARN] - Could not create module edgeAgent
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [WARN] -         caused by: No such image: mcr.microsoft.com/az...ent:1.0
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [WARN] - Error in watchdog when checking for edge runtime status:
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [WARN] - A module runtime error occurred.
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [WARN] -         caused by: Could not create module edgeAgent
Mar 04 00:00:57 devbox iotedged[19886]: 2019-03-04T00:00:57Z [WARN] -         caused by: No such image: mcr.microsoft.com/az...ent:1.0
Hint: Some lines were ellipsized, use -l to show in full.

It says Successfully pulled the image but when I checked using docker images it does not list that image.

I tried to pull image myself as shown below:
[root@devbox mmasood2]# docker pull mcr.microsoft.com/azureiotedge-agent:1.0
1.0: Pulling from azureiotedge-agent
407ea412d82c: Pulling fs layer
e88ff66da18c: Pulling fs layer
0013a852b911: Pulling fs layer
85fc25fb7f8b: Waiting
57541c8ad217: Waiting
47b7811d667e: Waiting
a2e631cf7279: Waiting
error pulling image configuration: Get https://mcrea0.cdn.mscr.io/b29889755b1f4e46b6b44eb3182530c5-0joxcrfl25//docker/registry/v2/blobs/sha256/e4/e4917eb97425815862809020fd5968c67dea666df19150b9ad989924ed7f7561/data?P1=1551658996&P2=1&P3=1&P4=MMqzDJnv%2FCoigmHzGrTkeuQYGRdpIEvpFSaVr7NnmHY%3D&se=2019-03-04T00%3A23%3A16Z&sig=sSL2aW9VKtbzeetuXH30TKDX5V67Frd3eG2GBJd%2BQOk%3D&sp=r&sr=b&sv=2016-05-31&regid=b29889755b1f4e46b6b44eb3182530c5: x509: certificate signed by unknown authority

Can you please assist on this?

Thanks,
Muhammad Masood

**Comment by myagley** [comment]
One potential reason for this failing is that the common root CA certificates are not installed on this system. I'm not super familiar with Redhat based systems, but Debian systems allow the CA certificates to be installed via the package manager: `apt-get install ca-certificates`

Do you know if there is a way to do this for RHEL? Perhaps `yum install ca-certificates`?

**Comment by ancaantochi** [comment]
There is a known bug in the runtime that it reports the image was successfully pulled when it actually failed and then it fails to create the container. So pulling the image manually shows the actual failure. 
Please try myagley suggestion to install the common root CA certs.

**Comment by myagley** [comment]
@ancaantochi this is fixed here: https://github.com/Azure/iotedge/commit/020ddbc7e73650956cb85dfa0dea152a89c44e60?

**Comment by mmasooddatascience** [comment]
We had to install to intermediate certificate, on the edge device, signed by company's CA and it started working. Thanks for your help.
