### ISSUE TITLE
Can we use Edge Module with Proxy

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#907]
Hi,
  Our clients are having proxy settings for accessing Internet. So can we use Edge Module under the proxy or not?? please could you send me some details that how to test it with proxy ??

**Comment by sebader** [comment]
The modules communicate to the Edge Hub directly over a private network. And only the Edge (Daemon, Agent and Hub) communicate to the IoT Hub. Those can use proxies.
If you module needs to make internet-outbound calls as well for some reason, you need to implement this inside your code - but it is possible.

**Comment by sachidanand** [comment]
Could you send some Reference URLs

**Comment by sebader** [comment]
[Configure Edge with Proxy](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support)

**Comment by myagley** [comment]
I'm going to close this issue for now. The linked documentation should guide you through setting this up. If you have issues setting this up, then feel free to reopen.
