### ISSUE TITLE
Upload Images

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#909]
Hi, 
I'm trying without sucess, upload from a local folder a jpeg image to Iot Hub using an iot edge module.
I only found an example where the module uploads the file from the module's folder in container, this example (https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-custom-vision).
Can you explain me if this feature is possible and some alternatives ?? 
I would really love to integrate Azure Iot Edge in my solution ...

**Comment by sebader** [comment]
The module you reference also does not do a a file upload.
File upload, as it is available in the IoT Device SDK, is not yet available in the ModuleClient.
So I see to alternatives:
a) Use the Azure Blob Storage SDK yourself and make a direct connection to the blob storage. This requires that a module can connect via HTTP to Azure. (the File Upload feature for devices is not much different under the hood)
b) Chuck your file into smaller parts (if nessecary) and send it as telemetry messages. In the IoT Hub in Azure, set up a route for those messages (e.g. identify them by some custom property), read those messages by something like an Azure Function and reconstruct the file. Not beautiful but would work - as long as you don't need to send too much file data as you would burn through your message quota quite fast.

**Comment by Ilheu** [comment]
Thank you for your answer !!

> a) Use the Azure Blob Storage SDK yourself and make a direct connection to the blob storage. This requires that a module can connect via HTTP to Azure. (the File Upload feature for devices is not much different under the hood)

So, in this case I don't connect with Iot Hub ? Is there any example of this ?

**Comment by sebader** [comment]
> So, in this case I don't connect with Iot Hub ? Is there any example of this ?
Your module still connects to Edge Hub (and consequently to IoT Hub through it). But as the file upload feature for devices is not yet available for modules, the path to the blob storage is completely separate from that. 
That also means that the pricing you mention does not apply here.

So your module will have its persistent connection to Edge Hub via AMQP/MQTT. Additionally you open a HTTP connection to your blob storage when you need to upload files.

**Comment by Ilheu** [comment]
I still have a doubt, 
While Edge hub is not available for modules, I think uploading files through IoT Device SDK will be a better option, the price will be what I mentioned above ?

**Comment by sebader** [comment]
Oh, now I understand what you mean. Well, you you could also connect your module to IoT Hub. But the storage transfer will nevertheless go directly to the blob storage - outside of the communication with IoT Hub.  So yes, the IoT Hub metering would only be 2 messages.
What you get from using the IoT File Upload SDK is that the IoT Hub will generate the SAS token for the blob access and will also send file upload notifications.

**Comment by lt72** [comment]
Closing as stale.
