### ISSUE TITLE
Unable to locate package moby-engine

### ISSUE THREAD

**Issue by sympthom** [Azure/iotedge#91]
I'm trying to install Azure IoT using the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux but keep getting an error in a fresh installed distribution.

## Expected Behavior
The installation should find the package.

## Current Behavior
The instructions in not complete for finding the package.

## Steps to Reproduce
https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
arm32

### Container Operating System
Linux containers

## Logs
ubuntu@ubuntu:~$ sudo apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
Reading package lists... Done
ubuntu@ubuntu:~$ sudo apt-get install moby-engine
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package moby-engine

**Comment by veyalla** [comment]
@sympthom The Linux quickstart is for amd64 devices. Please use the [linux arm install instructions](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm). Note, at this time, Raspbian-stretch is the only supported ARM distro as mentioned in the [platform support doc](https://docs.microsoft.com/en-us/azure/iot-edge/support#operating-systems).

**Comment by myagley** [comment]
I'm closing this as arm32 packages are not supported on packages.microsoft.com at the moment. We will update the documentation when this becomes possible. Thanks!

**Comment by kottoz** [comment]
@myagley  i have the same problem but when i'm trying to install aziot -edge. i see that bullseye [packages ](https://packages.microsoft.com/debian/11/prod/)are available right now!
