### ISSUE TITLE
Can we Send Telemetry messages to Another IoT Hub From Edge Module

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#916]
HI Team,
    We need to send Telemetry messages to another IoT Hub from Edge Module. So is there any way to achieve it. So the messages would be sending two IoT Hubs one is the base where Module is connected and one is out side IoT Hub. So please suggest the best way for this.

**Comment by myagley** [comment]
This will work provided that you can get a connection string for the second IoT Hub down to the device. Unfortunately, the IoT Edge runtime doesn't provide much help in this area yet. You can potentially transmit the connection string in the module's twin.

**Comment by sachidanand** [comment]
This approach is not secure if we are sending connection string using Module Twin. Can we use KeyVault in Edge Module???

**Comment by myagley** [comment]
Yes, I understand that it is not secure. Like I mentioned, we don't have good support for this scenario yet, but it is on our backlog to support.
