### ISSUE TITLE
Debugging Windows Container Modules

### ISSUE THREAD

**Issue by rahulsehgal** [Azure/iotedge#917]
Hi Team,

I am not able to debug the Windows Container Module.
There is no Dockerfile.windows-amd64.debug file. How should I set the debugger in VS Code.
Note: I have image name in pipeArgs in launch.json and other required details but when I launch debgger it give me error See remote-attach output and ask to Open launch.json to add details.

**Comment by myagley** [comment]
@shizn is it possible to debug on windows containers?

**Comment by shizn** [comment]
@rahulsehgal are you running C# module? If yes, VS Code cannot debug C# Windows containers at this moment. Please check this issue for details and updates - https://github.com/OmniSharp/omnisharp-vscode/issues/2195.

**Comment by rahulsehgal** [comment]
Yes I am running C# module. So if we want to develop and debug modules we should use Linux containers. 
As this is strange because for production MS supports Windows Host and Windows Containers.
https://docs.microsoft.com/en-us/azure/iot-edge/support
As we cannot move our Host to Linux what is the best possible configuration here?

**Comment by shizn** [comment]
In VS Code, you can still debug the C# module locally without running in Container. If you want to do remote debug (moduleClient running in Win container), VS 2017 will support this soon (early next week). Note the overall Windows support is in public preview, so the debug experience is still working in progress.

**Comment by rahulsehgal** [comment]
You can still debug the C# module locally without running in Container. 
How this can be achieved? Shall I use edgeHubDev. How I can launch debbuger with edgeHubDev and using local container registry. Could you please help me with some sample code.

**Comment by shizn** [comment]
Check this link and let me know if it's not working for you - https://docs.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module#debug-a-module-without-a-container-c-nodejs-java

**Comment by RollsChris** [comment]
I am having the same issue trying to debug my module inside the simulator.

The filtermodule doesn't have the Dockerfile.windows-amd64.debug file when created with the **iotedgedev solution init** 
and running **dotnet publish --os linux --arch x64 /t:PublishContainer** seems to create a production ready container without **vsdbg** installed


im on a windows machine with linux containers, im actually developing inside the iotedgedev container with the simulator running with the image genearated with **dotnet publish --os linux --arch x64 /t:PublishContainer** ...

when i f5 i get: 

Starting: "docker" exec -i filtermodule sh -c "~/vsdbg/vsdbg --interpreter=vscode"
Error from pipe program 'docker': sh: 1: /home/app/vsdbg/vsdbg: not found
The pipe program 'docker' exited unexpectedly with code 127.

Any ideas?

thank you
