### ISSUE TITLE
Registry credentials with "https://registry_address" address doesn’t work

### ISSUE THREAD

**Issue by blackchoey** [Azure/iotedge#924]
## Expected Behavior
When using "https://***.azurecr.io" as registry address, edgeagent should be able to authenticate and pull image successfully as docker login accepts such kind of address. Here's a sample config snippet in deployment.json (removed password):
```
"registryCredentials": {
              "chaoyitest": {
                "username": "chaoyitest",
                "password": "…",
                "address": "https://chaoyitest.azurecr.io"
              }
            }
```

## Current Behavior
Edgeagent cannot pull image from private registry with unauthorized error.
![image](https://user-images.githubusercontent.com/16605901/53849490-04b3b600-3ff3-11e9-8980-dd3104d32909.png)

## Steps to Reproduce

1. Create a new Edge device
2. Make sure the address in registryCredentials has "https://" header and there're modules from the private registry
3. Deploy the deployment.json to the new Edge device
4. Check iotedge logs

### Device (Host) Operating System

I created a VM using `Ubuntu Server 16.04 LTS + Azure IoT Edge runtime` VM image from Azure marketplace as Edge device.

**Comment by sebader** [comment]
why do you want to include `https://` in the address? If you only put `chaoyitest.azurecr.io` it there it should work fine. Won't access to the registry be over https in any case?!

**Comment by blackchoey** [comment]
We received customer feedback that their registry address has `https://` and it doesn't work. It's confusing since `docker login` accepts addresses with `https://`. Is there any reasons that we could not have `https://` in the address?

**Comment by sebader** [comment]
again, the connection to the registry should use https anyway. But to specify the credentials, you only need the address (aka DNS name) of the registry.

**Comment by myagley** [comment]
Having the address begin with `https://` is not supported. The intention is that you would use the value in the `Login server` box from azure container registry:
![image](https://user-images.githubusercontent.com/833747/53896440-e21c9f80-3fe8-11e9-9685-8bf6dbd2e902.png)

This assumes no scheme on the address. We can improve the validation here, but it would reject addresses with schemes.

**Comment by shizn** [comment]
The reason that customer wants to begin with `https://` is that they have their on-prem private registry (definitely not ACR, ACR is good in this case). When they run `docker login` in shell, they always begin with `https://`. They naturally put this in the IoT Edge deployment manifest and it doesn't work.
I think the key point here is - should we align with the behavior with docker cli or the [Credential Store](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) (there is an example begin with `http://`) when pulling images with authentication in EdgeAgent?

**Comment by arsing** [comment]
(For reference, the docker CLI does [this.](https://github.com/moby/moby/blob/5635c248cd3bead105b4b6d336a8502b1d25a6ee/registry/auth.go#L202-L215) Not only does it allow the user to give a leading `http://` or `https://`, it also allows the user to give a path component after the hostname and strips that too.)
