### ISSUE TITLE
How to Test Edge Module in CI-CD

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#925]
Hi Team,
    How to test the Edge Module in CI-CD pipeline. We need to finalize the approach for this so please help us on this...

**Comment by myagley** [comment]
@shizn what's the latest on CI-CD support?

**Comment by shizn** [comment]
@sachidanand any specific tests you want to run in your CI/CD?

**Comment by sachidanand** [comment]
I want to run integration tests so that I can test the edge module before
deployment on the device

**Comment by toolboc** [comment]
@sachidanand , take a look at https://github.com/toolboc/IoTEdge-DevOps.  There are a few different techniques demonstrated for smoke and integration testing of IoT Edge modules.

**Comment by myagley** [comment]
I'm going to close this issue for now. The repo from @toolboc looks like a great resource for CI/CD and IoT Edge!
