### ISSUE TITLE
ModuleClient.GetTwinAsync() throwing timing out exception

### ISSUE THREAD

**Issue by m4masood** [Azure/iotedge#929]
Hi,

I have created a simple module in C# that just get the data from some api and send back to IoT Hub. I have setup desired property so that I can pass values from Azure portal when configuring/deploying module to device/iotedge.

Below is code snippet:

        static async Task Init()
        {
            AmqpTransportSettings amqpSetting = new AmqpTransportSettings(TransportType.Amqp_Tcp_Only);
            ITransportSettings[] settings = { amqpSetting };

            // Open a connection to the Edge runtime
            ModuleClient ioTHubModuleClient = await ModuleClient.CreateFromEnvironmentAsync(settings);
            await ioTHubModuleClient.OpenAsync();
            Console.WriteLine("IoT Hub module client initialized.");

            // Read the TemperatureThreshold value from the module twin's desired properties
            var moduleTwin = await ioTHubModuleClient.GetTwinAsync();
            await OnDesiredPropertiesUpdate(moduleTwin.Properties.Desired, ioTHubModuleClient);

            // Attach a callback for updates to the module twin's desired properties.
            await ioTHubModuleClient.SetDesiredPropertyUpdateCallbackAsync(OnDesiredPropertiesUpdate, null);

            await ExecuteCustomCodes();
        }

When I commented/disabled desired property it works fine but as soon as it executes await ioTHubModuleClient.GetTwinAsync() it throws (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired

Here is the docker container logs:
[root@devbox ~]# sudo docker logs -f temperatureModule
IoT Hub module client initialized.

Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation timeout expired.) ---> System.TimeoutException: Operation timeout expired.
   at Microsoft.Azure.Devices.Client.InternalClient.<>c.<ApplyTimeoutTwin>b__64_2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at MMasood.TemperatureModule.Program.Init() in D:\a\1\s\MMasood\MMasood.TemperatureModule\Program.cs:line 63
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MMasood.TemperatureModule.Program.Main(String[] args) in D:\a\1\s\MMasood\MMasood.TemperatureModule\Program.cs:line 29

My IoT Edge device is RHEL 7 with following Moby and Edge runtime:

Moby from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-engine-3.0.2-centos.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.5/moby-cli-3.0.2-centos.x86_64.rpm

IoT Edge runtime from:
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/libiothsm-std-1.0.6.1-1.el7.x86_64.rpm
https://github.com/Azure/azure-iotedge/releases/download/1.0.6.1/iotedge-1.0.6.1-1.el7.x86_64.rpm

Please assist on this.

Thanks,
Muhammad Masood

**Comment by varunpuranik** [comment]
Hi @mmasooddatascience,

Couple of questions - 
- How can you tell that the timeout is coming from GetTwinAsync. I don't see anything in the call stack that suggests it would be the GetTwinAsync call.
- What does OnDesiredPropertiesUpdate do? I am curious because you are passing in the ModuleClient as context to it. 
- You said "What I commented/disabled desired property it works fine". Can you elaborate on what that means?

**Comment by mmasooddatascience** [comment]
Hi @varunpuranik, Thanks for your reply. The line number indicates that.  When I simply initialize the module without using below code:

// Read the TemperatureThreshold value from the module twin's desired properties
        var moduleTwin = await ioTHubModuleClient.GetTwinAsync();
        await OnDesiredPropertiesUpdate(moduleTwin.Properties.Desired, ioTHubModuleClient);

        // Attach a callback for updates to the module twin's desired properties.
        await ioTHubModuleClient.SetDesiredPropertyUpdateCallbackAsync(OnDesiredPropertiesUpdate, null);

it works. 
Please check https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module it has got that method.

There could be a possibility of the port is blocked I am checking with our network guys. But the thing is that Azure portal can send command to pull image etc so I believe there is a connectivity between device and IoT Hub.

Thanks

**Comment by mmasooddatascience** [comment]
Hi, 

I have used Amqp_WebSocket_Only as transport setting and still I am not able to get desired properties collection.

Here is the logs:
[root@devbox ~]# sudo docker logs -f piHistorian2SqlModule
amqpSetting.GetTransportType: Amqp_WebSocket_Only
IoT Hub module client initialized.
Calling await ioTHubModuleClient.GetTwinAsync() to get twin
Got moduleTwin. It's not null
Calling await OnDesiredPropertiesUpdate(moduleTwin.Properties.Desired, ioTHubModuleClient)

Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OT.IDP.IoTEdge.Modules.PiHistorian2Sql.Program.Init() in D:\a\1\s\MMasood\Edge\TestModule\Program.cs:line 73
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TestModule.Program.Main(String[] args) in D:\a\1\s\MMasood\Edge\TestModule\Program.cs:line 31
[root@devbox ~]#

I have updated the Microsoft.Azure.Devices.Client package to version 1.19 (latest version) but still having issue to get desired properties.

Either moduleTwin.Properties  or moduleTwin.Properties.Desired returns null.

Can you please assist on this?

Thanks,
Muhammad Masood.

**Comment by varunpuranik** [comment]
Hi @mmasooddatascience  - Neither the moduleTwin.Properties or moduleTwin.Properties.Desires should be null. One easy way to test this is to print the moduleTwin as soon as you get it. 
You can do it using the ToJson method on the Twin object, like so - 
Console.WriteLine($"ModuleTwin = {moduleTwin.ToJson()}");
That will give us insight on what the Twin object includes.

**Comment by m4masood** [comment]
Hi,
Sorry I missed to tell you the my device was behind proxy and it got fixed by following https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support

But in my other device (which is also behind proxy) I am getting different error. I will create another issue.

Thanks,
Muhammad Masood

**Comment by varunpuranik** [comment]
That is good to know - thanks for the update! I will close this issue. Please re-open it if you run into this issue again.
