### ISSUE TITLE
Connect a downstream device to an Azure IoT Edge gateway

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#933]
Hi,
I like to know if there is any example or tutorial with the connection of a a downstream device to an Azure IoT Edge transparent gateway without SDK. I can't find any help out there ...

**Comment by mrohera** [comment]
You can start here: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway
This should walk you through setting up your Edge device and click through for samples on connecting downstream devices.

Hope this helps, let us know if you have follow up questions.

**Comment by lt72** [comment]
Closing issues as it seems stale. please feel free to re-open as needed.
We recommend upgrading to 1.0.8.4 (released today) where we implemented lots of reliability improvements.
