### ISSUE TITLE
Iot Edge transparent gateway + downstream device:  Connection error to Iot Hub:TLS authentication error

### ISSUE THREAD

**Issue by conekeo** [Azure/iotedge#937]
## Expected Behavior
Connect downstream devices to Iot Edge transparent gateway.

##Current Behavior
After appending "GatewayHostName=ADNM-CONEKEO" to the connection string, the datas didn't send to Iot Hub and I got this error:
`Connection error to Iot Hub:TLS authentication error`

## Steps to Reproduce
I follow this tutorial: https://docs.microsoft.com/en-ca/azure/iot-edge/how-to-create-transparent-gateway and https://docs.microsoft.com/en-ca/azure/iot-edge/how-to-connect-downstream-device

My edge and downstream devices are on the same computer, following this scenario:

I deployed a monitoring module that loop through downstream devices to save their sensors in IoT Hub is working (Connection string without GatewayHostName).

But my problem, after appending "GatewayHostName=ADNM-CONEKEO" to the connection string, the datas didn't send to Iot Hub and I got this error:
`Connection error to Iot Hub:TLS authentication error`

Here what I did:
1) I added the devices in Manage child devices of the Edge device.
2) I generated the certificates and edit my config.yaml

```
certificates:
  device_ca_cert: "C:\\ADNM\\IoTEdge\\ssl\\certs\\new-edge-device-full-chain.cert.pem"
  device_ca_pk: "C:\\ADNM\\IoTEdge\\ssl\\private\\new-edge-device.key.pem"
  trusted_ca_certs: "C:\\ADNM\\IoTEdge\\ssl\\certs\\azure-iot-test-only.root.ca.cert.pem"
```
  
3) I added in Manage computer certificates/Trusted Root Certification Authorities the azure-iot-test-only.root.ca.cert.pem.

Route in my edge device:
`"route": "FROM /* INTO $upstream"`

Monitoring Module installed in Edge device looping through one downstream device code sample ( I got 10 devices to monitor):

 ```

string connectionString = "HostName=myhub-devices.net;DeviceId=mydevicetest;SharedAccessKey=xxxx;GatewayHostName=ADNM-CONEKEO"

 _DeviceClient = DeviceClient.CreateFromConnectionString(connectionString);
 _DeviceClient.OperationTimeoutInMilliseconds = 5000;
                        
var retryPolicy = new ExponentialBackoff(
                5,
                TimeSpan.FromSeconds(2),
                TimeSpan.FromSeconds(60),
                TimeSpan.FromSeconds(4));

 _DeviceClient.SetRetryPolicy(retryPolicy);

  try
   {           
    string messageString = null;
    Microsoft.Azure.Devices.Client.Message message = null;

     messageString = JsonConvert.SerializeObject(telemetryDataPoint);
     message = new Microsoft.Azure.Devices.Client.Message(Encoding.ASCII.GetBytes(messageString));

     // Send the telemetry message                                 
    Console.WriteLine("\n*[{0}]{1} > Sending message: {2}", equipment.DeviceId, DateTime.Now, messageString);
    await _DeviceClient.SendEventAsync(message).ConfigureAwait(false);
    Console.WriteLine("Message sent!");

    }
   catch (Exception e)
    {
     Console.WriteLine("Message not sent. Connection error to Iot Hub:" + e.Message);
    }

```
In my logs:

```
3/12/2019 8:53:11 AM info: iotedged -- Finished configuring certificates.
3/12/2019 8:53:11 AM info: iotedged -- Initializing hsm...
3/12/2019 8:53:11 AM info: iotedged -- Configuring the trusted CA certificates using
                     "C:\\ADNM\\IoTEdge\\ssl\\certs\\azure-iot-test-only.root.ca.cert.pem".
3/12/2019 8:53:11 AM info: iotedged -- Configuring the Device CA certificate using
                     "C:\\ADNM\\IoTEdge\\ssl\\certs\\new-edge-device-full-chain.cert.pem".
3/12/2019 8:53:11 AM info: iotedged -- Configuring the Device private key using
                     "C:\\ADNM\\IoTEdge\\ssl\\private\\new-edge-device.key.pem".
3/12/2019 8:53:11 AM info: iotedged -- Detecting if configuration file has changed...

```

when I'm running this script
` openssl s_client -connect ADNM-CONEKEO:8883 -CAfile C:/ADNM/IoTEdge/ssl/certs/azure-iot-test-only.root.ca.cert.pem -showcerts`

Here the result of my test certificate:

```
CONNECTED(00000204)
depth=4 CN = Azure IoT CA TestOnly Root CA
verify return:1
depth=3 CN = Azure IoT CA TestOnly Intermediate 1 CA
verify return:1
depth=2 CN = ADNM-CONEKEO.ca
verify return:1
depth=1 CN = iotedged workload ca
verify return:1
depth=0 CN = adnm-conekeo
verify return:1
7896:error:89070063:lib(137):CAPI_RSA_SIGN:cant create hash object:e_capi.c:858:Error code= 0x80090008
7896:error:14099006:SSL routines:ssl3_send_client_verify:EVP lib:s3_clnt.c:3271:
---
Certificate chain
 0 s:/CN=adnm-conekeo
   i:/CN=iotedged workload ca
-----BEGIN CERTIFICATE-----
MIIEazCCAlOgAwIBAgIBKTANBgkqhkiG9w0BAQsFADAfMR0wGwYDVQQDDBRpb3Rl
ZGdlZCB3b3JrbG9hZCBjYTAeFw0xOTAzMTIxNzI2MzNaFw0xOTA0MTExNzI1MDha
MBcxFTATBgNVBAMMDGFkbm0tY29uZWtlbzCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAMVNUShoFw0yq7ru7/OXx5udcilvZlrM7vTXBiMgfsTGV7ao0BNX
Vv5eAD6S/UsBFhSPdjOOIisFLP0QtqikGk4w2+8LGobcwERIJ+W5e2GlWyH8JYpD
nBR3jeuTmlrhXKLXlvbWudlMWc1c7ZiQluop0P+jimuM/a2CqVapJ9Z1uuWZqfzb
KTCoUAAYFPCSVH6ktYOjo/9v8S1R/9N+9WHdks0uq85wy48vtOgZDsWn37OSMDvo
yFaGT9eN5E2b/UdfjtsW8CH98IJgmKfJu/qnlzZWMNtKBx9Sd/2CyfSxZCNKajSG
pjOgA2OR2wPf3bfaEhF8d50/bjDagna/SL8CAwEAAaOBuTCBtjAJBgNVHRMEAjAA
MA4GA1UdDwEB/wQEAwID+DATBgNVHSUEDDAKBggrBgEFBQcDATAgBgNVHREEGTAX
ggxhZG5tLWNvbmVrZW+CB2VkZ2VodWIwHQYDVR0OBBYEFK9OdC1xMOUGETHb8jYb
WNPELLUeMEMGA1UdIwQ8MDqAFLNUYeThSiBkMfkGPgTDC6gSM4oFoR6kHDAaMRgw
FgYDVQQDDA9BRE5NLUNPTkVLRU8uY2GCAkhnMA0GCSqGSIb3DQEBCwUAA4ICAQAv
QnwO9ou+y43P0k4ogaCssldTphHYbnsj5T7TEqxbN+KqGmSSwJ/Pd8VcFn/V5cKB
Ii56jxI6edi6PZPnOatuGw5G2g4ar3bGtud9+SHji8DKGEptp+DNxUq4bqLy3WMT
XMP4SZpJApZwpLxQDi/w4YQysLF7QLngKUeTo72muPlyAKg/W51JPh/3mrxH0Yu9
ZLlyItXCWp/mT6YXSic003XuhiIWo7A0fJ49hX7iQI0jEi2p7wXLIm/vvjLFxWv+
AJ7VUuUIXbUc8MgK6+BN3RtWEtOCSQUN9nF9TLxPMIuI67iGcHNu7sNWyMqvAr53
EqSkGCZCTPBGbRdPilTWoeqymxgqpfNdBRSSN8ln/Bm+jp09LUNrg6QI33WcSy9u
n+F7HrR7o8gsehTXv8rzPDv4fUO0wE78R5owzsQO6jGewT6TzzuXOmt18QV6DP5B
Kp69ioJFm5poeUAXkakMu4W5s058z1O/ZjQrupjqgjFj8TYsc9Mpg06NROWIycS4
Pn6mKm1H5gE6dwQzC2L8pv1tCzkCmfGDZ/2/QIMkPsjKMbbCZ6eElaIQTnH5Ljoe
kqti/Od894jPPWeIB3pGVoHcIwYRKYxn+nVxrxYgrheosh8fVda4mcIW1Icg4DiV
RMNugwhx8/ZZP1zYsnqwVYmwhn5FjeCsfnb+KpKF8A==
-----END CERTIFICATE-----
 1 s:/CN=iotedged workload ca
   i:/CN=ADNM-CONEKEO.ca
-----BEGIN CERTIFICATE-----
MIIEZzCCA0+gAwIBAgICSGcwDQYJKoZIhvcNAQELBQAwGjEYMBYGA1UEAwwPQURO
TS1DT05FS0VPLmNhMB4XDTE5MDMxMjE3MjYyMloXDTE5MDQxMTE3MjUwOFowHzEd
MBsGA1UEAwwUaW90ZWRnZWQgd29ya2xvYWQgY2EwggIiMA0GCSqGSIb3DQEBAQUA
A4ICDwAwggIKAoICAQDI/wS1QaWkg5b5rfTuEAlzFhIB6AP094JwV7aMmEEEabhq
KlDNeKg+R6Gp2ecqJaV+9BJFbcpMHgEHYrQ5GDstEHc13nucF6HujOKU2W/bUCrA
lIc0w6F31lfiy5MVkFCZy1rxwilpxZAjS0QcjnU4poUN5C4u9qTqYdi9f+/ycft7
Io6zvADM2jQHMPwBb8JhIimxq1qcIAAUGrjh1VLMd65pMdxr7+vvKchW2u8gUrQs
p2MV7SExWW2+fDyFslvSO58MotffkREDeR5ArWJgavSqfxJDz+/5REVjR4YKfhE2
hEKg0Y1b2R9Vg+I8MA+ihJg2IS+dC3r4PtjWt7b9lSI74xF94CltgbFm2ADXVS/R
7pHx7qHgLhil6JEhRX/DBNdKCj4a67NcCI5c1kIZAjBx8a3gqx1rssfq6APQuOYr
UL6rVG7A4M/Jz/Dlaulv24zQW/zKWlhO76O0oBGIb0wo2YrwcXrv18JJD11x/USk
Xe39TqWruUvwYN25UKs9bLue185aHT37f5GxgOVz1DnDE0MDiuuEZwASb7PpgxY4
d5cSEII/4a31CZ7mZ891HE0pjDyNYTbtwvol30O1uhO1mFLsvl2eXEAZGqELdrv7
EHLpd6kywaMUhI82DU0PC+PUfSWGkM6T21lzbFXQ8KrY1vONMtphVvMMuMevfQID
AQABo4GxMIGuMBIGA1UdEwEB/wQIMAYBAQECAQAwDgYDVR0PAQH/BAQDAgKEMB0G
A1UdDgQWBBSzVGHk4UogZDH5Bj4EwwuoEjOKBTBpBgNVHSMEYjBggBSFY5nxgwR8
9bG0+8AsiPbtgtmWWKE2pDQwMjEwMC4GA1UEAwwnQXp1cmUgSW9UIENBIFRlc3RP
bmx5IEludGVybWVkaWF0ZSAxIENBghB9qlx8VfmCt0wozjxjY+jVMA0GCSqGSIb3
DQEBCwUAA4IBAQBx44kJMmulk3SK5jkBy+7lj6OGI8TeKp3HuHuxVcI2KX+BcK9O
fJA/IYMGLIEOHEW6YjfRmcmbJGMEgBvl27dvbeF26a6lWVoqe+AF7Zz6uewYiLaj
WXgfzErdkp48LW7h3yFr4bbARrKIOCmspAlUVAb7py3veKAeURR2Ox1PVioiHuC7
kY7PzWcFl/fD8m6o53X4UH+eWtUQ4YMdGUvPkh5JD1v/qqYvuQzQ+r+wsDrL9vEI
sPPHEOycUNcoljC9LHQLz35qXpMHcpJIzqbDlQFe6Kb4oLo6mZLsRy/wbmCD1QL8
2cHVSnGqR3WaFWMzqejMgSir2+3pVCSBCDlN
-----END CERTIFICATE-----
 2 s:/CN=ADNM-CONEKEO.ca
   i:/CN=Azure IoT CA TestOnly Intermediate 1 CA
-----BEGIN CERTIFICATE-----
MIIDeTCCAmGgAwIBAgIQfapcfFX5grdMKM48Y2Po1TANBgkqhkiG9w0BAQsFADAy
MTAwLgYDVQQDDCdBenVyZSBJb1QgQ0EgVGVzdE9ubHkgSW50ZXJtZWRpYXRlIDEg
Q0EwHhcNMTkwMzEyMTcxNTA3WhcNMTkwNDExMTcyNTA4WjAaMRgwFgYDVQQDDA9B
RE5NLUNPTkVLRU8uY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCs
O6HQN07f5k7hKxgHGD66243bbwxUJrD83lF3PcPlOqUqma3t0kVKkAfPkZzwsUiz
ZElb6BsDi4OE7x9s8H1/MT4uxwoQ4bVJmWFvKr2j0kdnIp7Bbidcp5v/RzAv/vIW
+n/cqfA3ZsiA32FJzFV7KvPE6s5IefPMyBu5z3tzUIwEzSpcfBXoluSn6U0wKIb1
KOcKfRYFc3Pj73ph7jeFMrTbxvK722V+ZSfr3rdSX1Xq6JGt3vMPAHrT6o6agEMp
7ekGUTvhkZ9yE9gNnesJYMoT8hIvImz4D87oZgu6yIlOlJnHwD1wIpaGdddh92dN
krNc7XEGXSNOJhjQFy3RAgMBAAGjgaIwgZ8wDgYDVR0PAQH/BAQDAgIEMB0GA1Ud
JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAaBgNVHREEEzARgg9BRE5NLUNPTkVL
RU8uY2EwEgYDVR0TAQH/BAgwBgEB/wIBDDAfBgNVHSMEGDAWgBTQeQR+bUF4bmue
RctvCiyXbOt8zjAdBgNVHQ4EFgQUhWOZ8YMEfPWxtPvALIj27YLZllgwDQYJKoZI
hvcNAQELBQADggEBAG6iRGQmHpRSWR85M2wW9lM7pU2lsPh0Szg2xu1Rmg9LMyib
SLeIRj1TGJjxM4AZmKtQ4jMWcJ+0YktvrINpW/2+Qeu0aDtVrFU1dGcOdotC69J4
uK48j1IVeonem+NeAOEUP2IANWauVliEJX7yYbzGfwYdULhTHnfO8lp+k2QFt+I9
0XNzmtWJ7qfQJSlf4l80fpQ2uEgyqrw45fQM5p4MbxrtFsZoafvvY71SIKykOtp9
YIFS2UbvMYhx17oD2qnHyAhmI1G8MTQACM/Tf61abHSV8ZVk8wo+MZkSYV6j+u2U
SCxQkGDCuYzT0WNPbRZvNkDEdHRo0RUZibTLlbE=
-----END CERTIFICATE-----
 3 s:/CN=Azure IoT CA TestOnly Intermediate 1 CA
   i:/CN=Azure IoT CA TestOnly Root CA
-----BEGIN CERTIFICATE-----
MIIDnzCCAoegAwIBAgIQKBjebqqzxrlI9n025gOdEDANBgkqhkiG9w0BAQsFADAo
MSYwJAYDVQQDDB1BenVyZSBJb1QgQ0EgVGVzdE9ubHkgUm9vdCBDQTAeFw0xOTAz
MTIxNzE0NDNaFw0xOTA0MTExNzI0NDNaMDIxMDAuBgNVBAMMJ0F6dXJlIElvVCBD
QSBUZXN0T25seSBJbnRlcm1lZGlhdGUgMSBDQTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAJqeWhhoDSyYs/2/bCXBZjwEssTrpcYoLWB+ELiU848uPTwz
G5xeIhPJksAPrPMijvDbuHKyW7DwG6pyY0PG9gnmZrDa+0J8IK7OUT9P/A7ujATC
HtUa8wr92kLbw2Id/AECb8YDSpdVe3+n1xjyufoX+KDnvEoVhhKep0zHsOPGtdtf
FjRajJFAOa2T3BqUYv7e3kUi3+yfHQ76nR/lKfcCdBw26NubNWHBD1LD2cCT1bcH
TAyLEi2c0KbpUzcvGF5yCIZgAet23Ac+V7EHUCQLBpwCy3e4KUJXUhFvBjyU2p/u
1IT2CA9107yHhPG5EprDpspSp2UaFFqbEfWaQlkCAwEAAaOBujCBtzAOBgNVHQ8B
Af8EBAMCAgQwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMDIGA1UdEQQr
MCmCJ0F6dXJlIElvVCBDQSBUZXN0T25seSBJbnRlcm1lZGlhdGUgMSBDQTASBgNV
HRMBAf8ECDAGAQH/AgEMMB8GA1UdIwQYMBaAFNV3J4J5a+GdPahphBGnyXe7LBJE
MB0GA1UdDgQWBBTQeQR+bUF4bmueRctvCiyXbOt8zjANBgkqhkiG9w0BAQsFAAOC
AQEAMIQU3Mmw+dKpTO60+5O1goUI2B5mzIainT6hFv1eBxkPphcsByRZCiQg1SKk
S2wIJNYOjHNsK7DSUWBU7C9Co/ERuE7KoHvbHKjU6zwO1x9+A4v7DnW14NIiOlUf
WlczoQePOiNheDqoT5dNGSx5yPQir0k4MbXaoXQNcb1QDRIfYa/Zf5d0+6/DO/ww
lOxm36J86/KlK1a9HE3H8LVOZKBGdzKLiIa8Op6b3LxAOAzQNTWx2hhFOhbgX2Bx
H5578oEvS7Yoqf2ImtaG5zBy9cCrRrK0M+TWomEQo566yRf6eWUZuFPo12s99I+z
ruw4Uce8sphkbFrbTMMjcBEvYw==
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=adnm-conekeo
issuer=/CN=iotedged workload ca
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1:RSA+SHA512:ECDSA+SHA512
Shared Requested Signature Algorithms: RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1:RSA+SHA512:ECDSA+SHA512
Peer signing digest: SHA256
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 4594 bytes and written 1051 bytes
---
New, (NONE), Cipher is (NONE)
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 1D3C00006DB53473DBB91BB835B5E018C16ED9FFC982D679C30C9B35508BA673
    Session-ID-ctx:
    Master-Key: 9E9CBC2D885C7DB1409485657DFE7044F22A4E70CDE42BE72B09EA149214C41B2255B5F42375CBC41E29380B4130C526
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1552413280
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

```

Any idea? Is it the right way to implement the offline mode for my use case?

### Iot Hub Location

West US

### Device (Host) Operating System
Windows 10

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Edge Agent
1.0.6.19913336

#### Edge Hub
1.0.6.19913336

#### Docker
Community 18.09.2

**Comment by conekeo** [comment]
I'm still trying to figuring my Iot Edge gateway problem. When running this sample https://github.com/Azure/iotedge/tree/master/samples/dotnet/EdgeDownstreamDevice

I got these errors:

```
Inner Exception 1:
AuthenticationException: TLS authentication error.

Inner Exception 2:
AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

**Comment by conekeo** [comment]
I'm redid the certification creation process several time now:

Test-CACertsPrerequisites:
```
Testing if any test certificates have already been installed...
  Ok.
Testing if openssl.exe is set in PATH...
  Ok.
Testing if environment variable OPENSSL_CONF is set...
  Ok.
Success

```

New-CACertsCertChain rsa:
`Success`

New-CACertsEdgeDevice "ADNM-CONEKEO":
```
MAC verified OK
writing RSA key
Certificate with subject CN=ADNM-CONEKEO.ca has been output to C:\ADNM\IoTEdge\ssl\.\ADNM-CONEKEO.ca-public.pem
```
Write-CACertsCertificatesForEdgeDevice "ADNM-CONEKEO"
`Success`

**Comment by conekeo** [comment]
Any idea someone what I'm missing?

**Comment by varunpuranik** [comment]
Hi @conekeo - 

Looking at all the information you have provided, one thing that jumps out is this - 
"System.InvalidOperationException: Cbs message missing audience property"

Which version of the C# SDK are you using in your device/module? And which protocol are you using to connect to EdgeHub?
If you are using MQTT, can you try using the version 1.18.1 - https://www.nuget.org/packages/Microsoft.Azure.Devices.Client/1.18.1 
That should get you past this error. Then we can investigate if there are any other errors coming from the Transparent gateway scenario.

**Comment by conekeo** [comment]
I'm using the sample provided https://github.com/Azure/iotedge/tree/master/samples/dotnet/EdgeDownstreamDevice

I tested it with Microsoft.Azure.Devices.Client/1.18.1 and Microsoft.Azure.Devices.Client/1.19.0 and got the same error: 

`Unhandled Exception: System.AggregateException: One or more errors occurred. (Put token failed. status-code: 400, status-description: Cbs message missing audience property.) ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubException: Put token failed. status-code: 400, status-description: Cbs message missing audience property.`

**Comment by conekeo** [comment]
Hi @varunpuranik 

Good news!  So the downtream sample(application) to my IoTEdge transparent gateway is working!
I was able to run the downstream sample code, I see the datas in my database now (I restart streaming analytics jobs). I try the offline mode and it working also!

But for my use case:  I deployed a monitoring module that loop through downstream devices to save their sensors in IoT Hub. I still got an error: 
`Connection error to Iot Hub:TLS authentication error.`

Probably because it didn't find the certificates (OS level) in the docker.

My question is, can I do it this way? What is the best practice? Should I create an application that loop through downstream devices instead of putting in a module?

**Comment by varunpuranik** [comment]
Hi @conekeo -

Can you please describe your scenario a bit more? 
- What is the topology? What modules are deployed? What downstream devices are connecting to EdgeHub?
- Which modules/devices are able to connect successfully and and send telemetry successfully?
- For your failing monitoring module - 
       - is it really a module deployed on the Edge Device via a deployment? Or a downstream device?
       - Which version of the C# SDK is it using? The error you mention has been introduced in the very recent SDKs - "Cbs message missing audience property"). Is it possible it is still using the new SDK?

Thanks,
Varun

**Comment by conekeo** [comment]
@varunpuranik 
My Module is using Microsoft.Azure.Devices.Client/1.19

To sum up, I want to put downtream devices in module deployed on the Edge Device via a deployment.
But the module failed probably because it didn't find the certificate on OS level:
`Connection error to Iot Hub:TLS authentication error.`

So I need to change it to certificate on application level? Or it's not recommanded this scenario? 
If yes, any idea how?

**Comment by myagley** [comment]
The root cause is that the Edge Hub's TLS server certificate is generally not chained to a known trusted root CA. The runtime provides an API to get the CA certificate that was used to sign the Edge Hub's server certificate and this CA cert needs to be added to the local trust store.

The C# SDK does all of this for you when calling `ModuleClient.CreateFromEnvironment`. You can see exactly what it is doing here: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/device/src/Edge/EdgeModuleClientFactory.cs#L101

We don't really have support for using a Device Client inside of a module. The main reason being is that there is no way to get access to the device credentials like is possible for modules. If you need to use the device client you will need to do something similar to what is being done in the `ModuleClient.CreateFromEnvironment` to enable the TLS connection to be validated.

**Comment by conekeo** [comment]
Ok understood! Thank you guys! You helped me a lot! I will close this ticket!

**Comment by GGleGrand** [comment]
Great answer, since we are indeed using the Device Client inside a module. For clarity, you explain:

> no way to get access to the device credentials like is possible for modules

Do you mean that the API is just not directly provided? ... so we need to write ourselves similar to ModuleClient.CreateFromEnvironment? Or is there another reason why it is not possible?

We are still wondering why, after installing the proper root cert/chain in the Windows certificate store, it is still not found. Is this probably because docker cannot access the Windows certificate store by default?

Thanks again?
