### ISSUE TITLE
Some IoT Hub features are disabled or contain limited functionality due to the location of your resource. The following are the impacted features: Manual failover (preview)

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#948]
Hi, 
I'm trying to "Start Monitoring D2C Message" in Visual Studio Code, but I don't receive nothing of what I'm sending ... yesterday morning was everything ok.

I noticed the following warning in my Azure Iot Hub's "Overview" : 
![image](https://user-images.githubusercontent.com/8053606/54227757-84acb500-44f8-11e9-8e16-a8e9e78b978a.png)

Do you know what this is about?

**Comment by myagley** [comment]
Yes, we are making a bunch of improvements to IoT Edge's logging story, but currently you must have access to the device to get the logs. (We will be enabling remote log access shortly)

The runtime ships with a CLI tool called `iotedge` on the device. You can run `iotedge -h` to see everything it can do. To get logs run `iotedge logs edgeHub`. To save these logs to a file you can pipe the output to a file: `iotedge logs edgeHub > edgehub.log`

There's more information on how to debug issues in the documentation here: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot

**Comment by Ilheu** [comment]
Let me see if I understood ... I ONLY can read the logs in the device ?, it is not possible to read logs in Hub ???

**Comment by myagley** [comment]
Today you must have access to the device to get the device logs. However, this is being actively worked on and addressed. We will have remote log access in the next couple of months.

**Comment by Ilheu** [comment]
You are talking about downstream devices too or just edge devices ??

**Comment by myagley** [comment]
Just edge devices. There is currently no standard for how a downstream device writes log lines so there is no way to ship a downstream device's log lines to the cloud.

There is a standard on edge (write to `stdout`/`stderr`) so those log lines can be shipped.

**Comment by lt72** [comment]
Closing issues as it seems resolved. please feel free to re-open as needed.
We recommend upgrading to 1.0.8.4 (released today) where we implemented lots of reliability improvements.
