### ISSUE TITLE
Direct methods not working anymore after update of module.

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iotedge#950]
## Expected Behavior
Direct Methods should still be able to be invoked after a module has been updated.

## Current Behavior
After updating a module, the direct methods cannot be invoked anymore using ServiceClient.
(Invoking direct methods by ModuleClient on same device still works.)

## Steps to Reproduce
1. Create Module with Direct Method
2. Invoke direct method using ServiceClient --> works
3. Update Module
4. Invoke direct method using ServiceClient --> Does not work anymore (timeout)

## Additional Information
After restarting the edgeHub module  with "sudo iotedge restart edgeHub" the direct methods can be invoked again.

Issue probably related to [https://github.com/Azure/iotedge/issues/646](https://github.com/Azure/iotedge/issues/646)

**Comment by varunpuranik** [comment]
Hi @BewaControl-ReneDivossen -
Can you please provide complete EdgeHub logs for the scenario? Debug logs would be better. That will tell us why the invoke method call is timing out.
Does your edge device have network connectivity throughout?

**Comment by BewaControl-ReneDivossen** [comment]
@varunpuranik Following your advice I turned on debug logs for edgeHub.  Since we are sending a lot of messages the log was very cluttered so I turned off some modules and some message sending to have a readable log.  With this done, updating a module did not break DirectMethods anymore.  They were unavailable for about a minute but then could be triggered again. At some point DirectMethods stopped working again but this did not seem to be connected to updating the module.  Problem:  When calling the direct method resulted in a timeout, the edgeHub log (even in debug) did not display anything! 

Since updating the module seems not to be the sole reason for disabling the direct methods, I'll get back to you if I find a way to consistently reproduce the problem.

**Comment by varunpuranik** [comment]
Alright, sounds good. From what you describe, it sounds like EdgeHub is losing the direct method link to IoThub for that client. This might be related to a C# SDK issue. 
If you get a repro, please provide us the EdgeHub logs for further investigation.

**Comment by lt72** [comment]
Closing issues as it seems stale. please feel free to re-open as needed.
We recommend upgrading to 1.0.8.4 (released today) where we implemented lots of reliability improvements.
