### ISSUE TITLE
Working IoTEdge v1.0.6.1 install on Ubuntu 16.04 VM broke

### ISSUE THREAD

**Issue by azthec** [Azure/iotedge#952]
I had a fully functional transparent gateway up and running, configured [as exemplified](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway) two weeks ago. In order to make sure the install is reproducible it's running on a provisioned Vagrant Virtual Machine, the configurations of which can be found [here](https://github.com/azthec/iot-edge-vagrant-box) (The _device_connection_string_ is missing on that repository, but is configured on my local clone).

In case something had changed on the runtime installation guide for Linux x64 I have performed the [manual install](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux) again and also have also created a Virtual Machine (also Ubuntu 16.04 x64) on the Azure Cloud and the same error occurs.

## Expected Behavior
The iotedge service should start and run.

## Current Behavior
The iotedge service fails to start.

## Steps to Reproduce
1. Use the Vagrant provisioning on [this](https://github.com/azthec/iot-edge-vagrant-box) repository for the installation or manually follow the guide official guide [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux).
2. Update the connection string.

### Device (Host) Operating System
**Physical host:**  ```Linux r12830192-pc 4.19.0-1-amd64 #1 SMP Debian 4.19.5-2~mx17+1 (2018-12-12) x86_64 GNU/Linux```
**Vagrant VM:** ```Linux edgeDevice1 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```
**Cloud VM:** ```Linux edgeDevice1 4.15.0-1037-azure #39~16.04.1-Ubuntu SMP Tue Jan 15 17:20:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)

#### Docker

<details><summary>CLICK ME</summary>
<p>

```
Client:
 Version:           3.0.3
 API version:       1.40
 Go version:        go1.11.4
 Git commit:        48bd4c6d
 Built:             Wed Jan 23 16:17:56 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.4
  Git commit:       8ecd530
  Built:            Fri Jan 25 01:45:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.2
  GitCommit:        9754871865f7fe2f4e74d43e2fc7ccd237edcbce
 runc:
  Version:          1.0.0-rc6+dev
  GitCommit:        96ec2177ae841256168fcf76954f7177af9446eb
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
</p>
</details>

### sudo systemctl status iotedge
<details><summary>CLICK ME</summary>
<p>

```
● iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Wed 2019-03-13 15:36:56 UTC; 1min 53s ago
     Docs: man:iotedged(8)
  Process: 3659 ExecStart=/usr/bin/iotedged -c /etc/iotedge/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 3659 (code=exited, status=1/FAILURE)
```
</p>
</details>

### sudo journalctl -u iotedge -f
<details><summary>CLICK ME</summary>
<p>

```
-- Logs begin at Wed 2019-03-13 15:35:46 UTC. --
Mar 13 15:36:56 edgeDevice1 systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Mar 13 15:36:56 edgeDevice1 systemd[1]: iotedge.service: Unit entered failed state.
Mar 13 15:36:56 edgeDevice1 systemd[1]: iotedge.service: Failed with result 'exit-code'.
Mar 13 15:36:56 edgeDevice1 systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Mar 13 15:36:56 edgeDevice1 systemd[1]: Stopped Azure IoT Edge daemon.
Mar 13 15:36:56 edgeDevice1 systemd[1]: Dependency failed for Azure IoT Edge daemon.
Mar 13 15:36:56 edgeDevice1 systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.
Mar 13 15:36:58 edgeDevice1 systemd[1]: Stopped Azure IoT Edge daemon.
Mar 13 15:36:58 edgeDevice1 systemd[1]: Dependency failed for Azure IoT Edge daemon.
Mar 13 15:36:58 edgeDevice1 systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.
```
</p>
</details>

### sudo iotedge list
<details><summary>CLICK ME</summary>
<p>

```
A module runtime error occurred
        caused by: Could not list modules
        caused by: an error occurred trying to connect: Connection refused (os error 111)
```
</p>
</details>

### sudo iotedge list
<details><summary>CLICK ME</summary>
<p>

```
A module runtime error occurred
        caused by: Could not list modules
        caused by: an error occurred trying to connect: Connection refused (os error 111)
```
</p>
</details>

### sudo iotedge list --host unix:///var/lib/iotedge/mgmt.sock
<details><summary>CLICK ME</summary>
<p>

```
A module runtime error occurred
        caused by: Could not list modules
        caused by: an error occurred trying to connect: Connection refused (os error 111)
```
</p>
</details>

**Comment by myagley** [comment]
The daemon is exiting with an error. The most likely cause for this issue with your config file `/etc/iotedge/config.yaml`.

Due to a quirk in how `journald` on linux collects logs from processes the last couple of lines of the daemon are being truncated. Is it possible to run `journalctl` without the `-u iotedge` to see if there is more information about what is failing?

**Comment by azthec** [comment]
This issue is not due to the ```config.yaml```, as I explained its the exact same as the version that was running before, this issue was instead caused by expired certificates. To double check I did as you asked and running grep on the unfiltered ```journalctl``` does provide an indication of that .

<details><summary>CLICK ME</summary>
<p>

```
Mar 14 10:48:54 edgeDevice1 iotedged[5014]: 2019-03-14T10:48:54Z [INFO] - Configuring /var/lib/iotedge as the home dir
Mar 14 10:48:54 edgeDevice1 iotedged[5014]: 2019-03-14T10:48:54Z [INFO] - Configuring certificates...                 
Mar 14 10:48:51 edgeDevice1 iotedged[4982]: 2019-03-14T10:48:51Z [INFO] - Removing module edgeAgent...                
Mar 14 10:48:53 edgeDevice1 iotedged[4982]: 2019-03-14T10:48:53Z [ERR!] - The daemon could not start up successfully:
Could not prepare workload CA certificate
Mar 14 10:48:53 edgeDevice1 iotedged[4982]: 2019-03-14T10:48:53Z [ERR!] -         caused by: A error occurred in the key store.
Mar 14 10:48:53 edgeDevice1 iotedged[4982]: 2019-03-14T10:48:53Z [ERR!] -         caused by: HSM failure
Mar 14 10:48:53 edgeDevice1 iotedged[4982]: 2019-03-14T10:48:53Z [ERR!] -         caused by: HSM API returned an invalid null response
Mar 14 10:48:53 edgeDevice1 iotedged[4982]: 2019-03-14T10:48:53Z [ERR!] (/home/vsts/work/1/s/edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c:validate_certificate_expiration:687) Certificate has expired
```
</p>
</details>

Although this issue is fixed, I would recommend that the iotedge daemon should at least echo the hardware security module failure report for easier debugging of similar issues in the future.

**Comment by myagley** [comment]
Yes, I agree that it would be nice for the logs to be written when exiting. The daemon actually does write these logs but like I mentioned above, due to a quirk in `journald` (which is part of linux, not IoT Edge) the last couple of logs aren't attached to the service name. We would be eager to fix this but we don't know how. We are open to any ideas.

**Comment by lt72** [comment]
Closing issues as it seems stale. please feel free to re-open as needed.
We recommend upgrading to 1.0.8.4 (released today) where we implemented lots of reliability improvements.
