### ISSUE TITLE
Need clarification with platform support for raspberry pi

### ISSUE THREAD

**Issue by gauravagarwal28** [Azure/iotedge#955]
As per this issue https://github.com/Azure/iotedge/issues/40
IoT Edge is not readily/easily supported on ARM64 devices.

As per the docs on this link https://docs.microsoft.com/en-us/azure/iot-edge/support:
IoT Edge is given Tier 1 support for ARM32v7 with Raspbian Stretch and Tier 2 support for some other Operating Systems. Correct me if I am wrong but Raspberry pi 2 with raspbian stretch qualifies as a Tier 1 supported platform right?

The link here suggests that IoT Edge is supported for Raspberry pi 3 as well:
https://azure.microsoft.com/en-in/resources/samples/custom-vision-service-iot-edge-raspberry-pi/

However,  Raspberry pi 3 has a 64-bit quad-core ARMv8 CPU which is ARM64.
Although I have successfully installed IoT Edge on it, I am unclear about 2 things:

1. Is it a supported platform or not? Should I stick with the Raspberry Pi 2?
2. If raspberry pi 3 is supported, then am I supposed to deploy docker images of arm32v7 or arm64 via IoT Edge on the Raspberry Pi 3?

**Comment by FluxReality** [comment]
Raspberry PI 3 ARM CPU is 64 bits, but Raspbian Stretch (the operatingsystem) is 32 bits.

Which means u can still run a 32bits program on a 64bits OS, just not the opposite.

**Comment by gauravagarwal28** [comment]
@FluxReality Thank you. 

Just to be clear, if I install Raspbian Stretch on any ARM64 device, then I should be able to run IoT Edge on it. Correct? And I will be deploying ARM32v7 docker images.

**Comment by FluxReality** [comment]
I cannot say "any ARM64 device" but certainly on Raspberry PI (at least it did for me).

**Comment by myagley** [comment]
Yes, we have a raspberry pi 3 with Raspbian Stretch as part of our automated test matrix. Like @FluxReality mentioned Raspbian is a 32-bit operating system so even though the hardware is 64-bit it looks like an arm32v7 device.

We are working on arm64 support. In fact there are scripts in this repo that will produce arm64 packages for the `iotedged`. The main blocker is getting arm64 support in dotnet core (which is used by the Edge Agent and Edge Hub). This is coming in dotnet core 3.0 and we have done some initial testing on it with the preview releases. We are hoping to get a public preview of arm64 support in the next few months.

**Comment by gauravagarwal28** [comment]
@FluxReality @myagley Thank you for your help and clearing my doubts.

**Comment by StefanSchoof** [comment]
There is a related issue in the azure-docs https://github.com/MicrosoftDocs/azure-docs/issues/24443

**Comment by myagley** [comment]
Closing this issue as arm64 isn't directly supported at this time.
