### ISSUE TITLE
How to separate credentials at deployment manifest

### ISSUE THREAD

**Issue by matsujirushi** [Azure/iotedge#96]
I see below at [this](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-csharp-module#build-your-iot-edge-solution):

`In the deployment.template.json file, the registryCredentials section stores your Docker registry credentials. The actual username and password pairs are stored in the .env file`

But I can't find how to.

**Comment by dsajanice** [comment]
@kgremban could you please clarify what this means.

**Comment by kgremban** [comment]
@matsujirushi Can you add more details of what you tried to do? I agree that the documentation should be clarified, and I'm working on rolling those changes out across the tutorials but I can't address your specific question without knowing more information.. 

When you create a solution that has a container registry specified (not localhost), a .env file is created automatically. You should populate that file with your container registry credentials, and then it will be reference by the deployment.template.json file.

**Comment by matsujirushi** [comment]
I tried and success. Thanks.

![image](https://user-images.githubusercontent.com/8079404/44265221-a5fa3b00-a260-11e8-9fe4-ce79f103b84a.png)

![image](https://user-images.githubusercontent.com/8079404/44265238-b7dbde00-a260-11e8-9159-d86ccc5239d5.png)
