### ISSUE TITLE
timeToLiveSecs for edgeHub is not reflected

### ISSUE THREAD

**Issue by levi106** [Azure/iotedge#966]
Even if setting the value of timeToLiveSecs in the deployment.template.json file, CleanupProcessor.CleanupMessage is always processed once in 30 minutes.

## Expected Behavior

The cleanup process is performed according to the value of timeToLiveSecs.

## Current Behavior

CleanupMessage method is called from the CleanupProcessor constructor, and the cleanupTaskSleepTime variable is initialized only once at the beginning of this method.

Therefore, even if setting the value of timeToLiveSecs, the value passed to the Task.Delay will be always 30 minutes (the value of CleanupTaskFrequency).

## Steps to Reproduce

1. Deploy with the following deployment.template.json

```json
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "CSharpModuleToClient1": "FROM /messages/modules/CSharpModule/outputs/output INTO $upstream"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 300
        }
      }
    },
```

2. `sudo systemctl iotedge restart`
3. `iotedge logs edgeHub|grep -e TTL -e Cleaned`

### Device (Host) Operating System

Raspbian Stretch Lite

### Architecture

arm32v7

### Container Operating System

Linux containers

#### iotedged

```sh
$ iotedge version
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
```

#### Edge Agent

mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub

mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker

```sh
$ docker -v
Docker version 3.0.2, build e042b58f
```

## Logs

```
$ iotedge logs edgeHub|grep -e TTL -e Cleaned
2019-03-15 07:53:17.517 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Updated message stor
e TTL to 300 seconds
2019-03-15 08:23:09.740 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Cleaned up 178 messa
ges from queue for endpoint iothub and 178 messages from message store.
2019-03-15 08:32:45.914 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Updated message stor
e TTL to 300 seconds
2019-03-15 09:02:38.919 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Cleaned up 229 messa
ges from queue for endpoint iothub and 229 messages from message store.
2019-03-15 09:33:10.420 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Cleaned up 183 messa
ges from queue for endpoint iothub and 183 messages from message store.
2019-03-15 10:03:42.179 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Core.Storage.MessageStore] - Cleaned up 183 messa
ges from queue for endpoint iothub and 183 messages from message store.
```

**Comment by varunpuranik** [comment]
Hi @levi106 - This behavior is currently by design. The TTL setting doesn't affect when the cleanup loop runs, as you correctly said, but it does affect when the messages get deleted. In each loop, it goes through the messages and cleans up only whose which have not been processed and have exceeded the set TTL value.
It is not really possible to run the loop as per the TTL setting - since messages come in at any time, the loop duration decides the maximum time the messages can exceed their TTL setting. So currently this is 30 mins. If the TTL is, say 2 days, and the loop is run 2 days, messages could stay in the queue for up to 2 days post their expiry, which would be undesirable.

**Comment by levi106** [comment]
I agree with you about a large TTL value. However, if the TTL setting is smaller than 30 mins, it may take 30 minutes for the messages to be deleted.

I hope the following calculation should work correctly.

https://github.com/Azure/iotedge/blob/027a509549a248647ed41ca7fe1dc508771c8123/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs#L237

**Comment by varunpuranik** [comment]
Yes, you are right. We don't currently update the cleanupTaskSleepTime when the TTL is updated. I will mark it as a bug and fix it in the code. Thanks.

I am curious to know if this was affecting any of your scenarios, or was it just a bug that you noticed?

**Comment by levi106** [comment]
I have not yet hit any problem. However, because resources of our environment is not enough, if lots of messages are queued, we may encounter out of memory. So, I would like to set small TTL value.

**Comment by lt72** [comment]
Closing issues as it seems stale. please feel free to re-open as needed.
We recommend upgrading to 1.0.8.4 (released today) where we implemented lots of reliability improvements.
