### ISSUE TITLE
IoT Edge service unable to start when using DPS provisioning

### ISSUE THREAD

**Issue by gauravagarwal28** [Azure/iotedge#97]
I was previously unable to start IOT Edge service on windows. I was successful in doing so for manual provisioning thanks to the steps provided by @veyalla in #78 

However, the service refuses to start when I configure it for dps provisioning. it shows the message:

>PS C:\WINDOWS\system32> Start-Service iotedge
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...
WARNING: Waiting for service 'iotedge (iotedge)' to start...

This is my config.yaml file:
[config.txt](https://github.com/Azure/iotedge/files/2240284/config.txt)

(I copied it to desktop and renamed it to config.txt so that it could be uploaded here)

My Terminal:
![capture](https://user-images.githubusercontent.com/41729265/43386698-1e0fed8c-9402-11e8-991a-59093c9b0c6f.PNG)

I don't see any output from the logs (as was the case previously in #78 )
![capture2](https://user-images.githubusercontent.com/41729265/43386777-51a18912-9402-11e8-939c-f435363e87e9.PNG)

My registry:
![capture3](https://user-images.githubusercontent.com/41729265/43387500-392b2fda-9404-11e8-98f9-da7a0c7d6d4d.PNG)

 I was following the instructions provided here:
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-auto-provision-simulated-device-windows

**Comment by darobs** [comment]
Hello @gauravagarwal28 

It might be nothing, but the first thing I see is that the "provisioning" section is indented by 1 space.  YAML is very sensitive to whitespace, and that would be the first thing I would fix. The word "provisioning" should not have any white space in front of it.  

If that's not the problem, we'll have to dig deeper.

Thank you,

**Comment by veyalla** [comment]
Hi @gauravagarwal28 - you can use the install script that worked for in https://github.com/Azure/iotedge/issues/78 for Dps as well.

1. Cleanup the current installation like before:
```
. { Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
UnInstall-SecurityDaemon -v -Force
```

2. Use Dps mode with Linux containers (cmdlet will prompt for scope and registration id):
```
. { Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Install-SecurityDaemon -Dps
```

**Comment by gauravagarwal28** [comment]
@darobs You were right. It was the spaces in the YAML file that was causing the problem on my machine.

@veyalla I tried the steps provided by you and they worked seamlessly.

Thank you for the support (y)
