### ISSUE TITLE
IoT Egde hub monitoring and statistics

### ISSUE THREAD

**Issue by ondrejspilka** [Azure/iotedge#971]
Hi,

for production purposes when we use IoT edge as a transparent gateway, it is necessary to have the ability to monitor basic health and status measures, like:
- disk space used
- messages processed
- messaged queued
- time spent in processing
- data volumes etc...

Monitoring via IoT hub is indirect and we would like to have real numbers propagated from IoT hub agent via IoT hub so we can monitor live statistics from IoT Edge.

Any suggestion how to achieve this in IoT Edge 1.0.6+?

Thanks
Ondřej

**Comment by myagley** [comment]
Yes, this is something we are actively working on. Do you have any opinions/ideas on how you think this should work? I want to make sure we capture your feedback when designing/implementing the feature.

cc @veyalla

**Comment by veyalla** [comment]
Yes!
 
@ondrejspilka - could you please reach out to me at veyalla@microsoft.com?

**Comment by ondrejspilka** [comment]
Hi,

first let me describe use cases we are after:
- central monitoring and maintenance
- fleet diagnostics

I believe technically you already have the mechanisms in place, as indicated [in this article](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-runtime).
What we would like to have the very first moment is int this picture:

![IoThub](https://user-images.githubusercontent.com/3624673/54596115-47827e80-4a34-11e9-9222-0a79bae4639b.png)

Hope this a bit clarifies?
Regards
Ondřej

**Comment by veyalla** [comment]
We’re now exposing some metrics from IoT Edge system modules, see: https://aka.ms/iotedgemetrics
