### ISSUE TITLE
Calling DirectMethods from ModuleClient causes increase in memory consumption.

### ISSUE THREAD

**Issue by BewaControl-ReneDivossen** [Azure/iotedge#978]
Within an iotedge module I'm calling a direct method of another module on the same device like this:

```
MethodRequest request = new MethodRequest("MyDirectMethod", Encoding.UTF8.GetBytes(payload), TimeSpan.FromSeconds(30), TimeSpan.FromSeconds(30));
var response = await _ioTHubModuleClient.InvokeMethodAsync(_deviceId, "MyModule", request).ConfigureAwait(false);
```

This is called about every two seconds and it makes memory consumption of the calling module grow rapidly.  Memory consumption on the module containing the direct method does not increase.

The increase in memory consumption is caused by **InvokeMethodAsync...**  If I comment out that line, memory consumption does not increase anymore.

If I let the module run a couple of days, memory consumption rises from an initial 13.5 MB to over 130 MB.  In addition CPU usage also increases. After  a couple of days I had CPU usage of up to 180% (initially it is around 10 %) on the raspberry pi. 

Note: The moduleClient is a static member and created and opened in the Init method of the module.

Why is the memory consumption increasing like this?

**Comment by varunpuranik** [comment]
@BewaControl-ReneDivossen - Thanks for the issue. We will investigate what is going on and get back to you.
InvokeMethodAsync is the only call that is invoked over Http (as opposed to Mqtt or Amqp). Maybe that has something to do with the behavior you see. 
Also, it seems likely that this is an issue in the C# SDK, as opposed to the Edge runtime. If that is so, then we might have to move this issue to the C# SDK repo.

**Comment by BewaControl-ReneDivossen** [comment]
@varunpuranik  Thanks for the feedback.  In case you are moving the issue to the C# SDK repo, please post a link to the corresponding issue here.
By the way:  As you can see in [https://github.com/Azure/iotedge/issues/893](https://github.com/Azure/iotedge/issues/893) I would love to be able to use AMQP as the only protocol.
