### ISSUE TITLE
Access to twin device in iot edge Stream Analytics module 

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#979]
Is it possible to access device twin data in stream jobs ? 

Is there a way I can access device (tags, desired properties, reported properties) in stream job so I can make calculations and make decision accordingly ?

**Comment by varunpuranik** [comment]
@xitia can help with this.

**Comment by xitia** [comment]
You could try your device twin logic from udf, however, since udf function is stateless, it will re initialize client each time you call the function, which might cause huge latency in stream jobs. Do you mind sharing more details about your case? We will support Set/Get Metadata shortly, where you could store module/device info in edgehub message metadata and having logic based on it.

**Comment by Ilheu** [comment]
Hi, 
I have a lot of devices which send different format messages with their ports and their values to an Iot Edge Transparent Gateway, I want to define their ports in each device twin device, and use it to make some filter and extra calculations in Stream analytics to send to the Iot Hub.

I'm actually trying to make a module to get all twin devices which belongs to that iot edge device, and merge with the device message its twin device tags properties, and send it to Azure Stream Analytics job module. 

What you think ?

**Comment by xitia** [comment]
Thanks for providing your scenario, in this case, you might want to take snap shot of the device ids / ports, and use it as reference data. We currently support local file reference data and blob reference data will be coming lately. The other option is to add ports to events metadata on leaf device, and having logic based on metadata in ASA running on gateway. Let me know if either of the solution fits your case.

**Comment by Ilheu** [comment]
It is a bit hardcoded solution, but in last resource it could fit, thank you. I'm finishing my module to get all twin devices which belong to that edge device, and merging their tags in the message, so I can use them in ASA. 
By the way, can you explain me, where can I see the deviceId in the message sended ?

**Comment by myagley** [comment]
I'm going to close this issue for now, as a workaround has been provided.
